### ISSUE TITLE
Caught TemplateDoesNotExist while rendering: facebook/fbconnect.html

### ISSUE THREAD

**Issue by benjamindell** [pennersr/django-allauth#10]
Looking at some of your project forks it seems that others have fixed this issue by creating this required template. Are you planning on integrating their work? Or is there a reason why i am getting the above error?

Thanks in advance - really loving the concept of this app, just desperately trying to get it to work :)

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/10
