### ISSUE TITLE
How to bypass verification step conditionally on runtime?

### ISSUE THREAD

**Issue by san89kalp** [pennersr/django-allauth#1004]
Ideally the user has to click on the verification link in his email to be able to activate his profile.
I do want to keep this feature.

However, my application also has the feature wherein the admin sends the invitation link to someone. In this case I do not want the user to receive an email and click on the link to be able to verify himself in the application. (Basically, I want to bypass the email verification step just for this case). I will manually activate the user in the database from code. I just need to suppress emailing to him from the code.

Could you please tell me which methods I need to override or how can I achieve this?

Any help is greatly appreciated.
Thanks.

**Comment by pennersr** [comment]
See the "Advanced" section of the documentation. You can accomplish this by invoking `stash_verified_email`...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1004
