### ISSUE TITLE
custom registration form in django 1.8 user is None

### ISSUE THREAD

**Issue by deecodameeko** [pennersr/django-allauth#1005]
I am using django 1.8 for the first time and things are a little different than in the past.

Here's my model:

    from django.db import models
    from django.contrib.auth.models import User

    class FDUserProfile(models.Model):
        user = models.OneToOneField(User)
        organization = models.CharField(max_length=100)
Here's my form:

    from django import forms
    from django.contrib.auth.models import User
    from .models import FDUserProfile

    class FDSignupForm(forms.ModelForm):
        class Meta:
            model = FDUserProfile
            fields = ['organization']

        first_name = forms.CharField(max_length=30, label='Voornaam')
        last_name = forms.CharField(max_length=30, label='Achternaam')
        organization = forms.CharField(max_length=100, label='Company')

        def signup(self, request, user):
            user.first_name = self.cleaned_data['first_name']
            user.last_name = self.cleaned_data['last_name']
            profile = FDUserProfile(user=user, organization=self.cleaned_data['organization'])
            profile.save()
The error I get is the following:

    NOT NULL constraint failed: fdauth_fduserprofile.user_id

Looking at the logs, user is None:

    params [None, 'organization name']
    sql ('INSERT INTO "fdauth_fduserprofile" ("user_id", "organization") VALUES (%s, '
 '%s)')

I'm not sure why user is None as it's passed to the signup method. Any help would be greatly appreicated!

**Comment by deecodameeko** [comment]
Also related to how rest auth interacts with allauth

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1005
