### ISSUE TITLE
Email confirmation deletion notice renders incorrectly in admin panel

### ISSUE THREAD

**Issue by HEdingfield** [pennersr/django-allauth#1006]
A minor cosmetic bug: when deleting a user account via the admin panel in Django 1.8.2, the email confirmation deletion notice seems to render incorrectly (i.e. differently from the other fields):

    User-group relationship: User_groups object
    Email address: test@test.com (test@test.com)
    ['Email confirmation: <a href="/admin/account/emailconfirmation/24/">confirmation for test@test.com (test@test.com)</a>']

Also, if a user has multiple confirmations assigned to their account, it renders as a list:

    ['Email confirmation: <a href="/admin/account/emailconfirmation/25/">confirmation for test@test.com (test@test.com)</a>', 'Email confirmation: <a href="/admin/account/emailconfirmation/26/">confirmation for test@test.com (test@test.com)</a>']

**Comment by pennersr** [comment]
This appears to be a Django issue, I can confirm this in 1.8.2.. but it is gone in 1.8.11.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1006
