### ISSUE TITLE
Limit number of failed login attempts

### ISSUE THREAD

**Issue by HEdingfield** [pennersr/django-allauth#1007]
Not sure if it's in the scope of the project, but I'd love to see something that allows you to limit the number of failed login attempts (and, say, locks an account for x minutes, hours, etc. once this limit is reached). This would prevent someone / some script from just spamming a bunch of attempts at guessing a user's password.

**Comment by bitcity** [comment]
:+1:

**Comment by pennersr** [comment]
What would be minimally in scope is making minimal changes to allow you to plug this in yourself by exposing a few adapter methods. 

One step further, I would be willing to provide a truly minimal implementation. While this can be regarded as feature creep, being out-of-the-box secure is more important here.  What I mean by "minimal implementation"  is:

- allauth won't be extending existing models or introducing new models
- add a `pre_login(request, **credentials)` adapter method, and an `login_failed(request, **credentials)` signal/adater method, 
- The default implementation of these methods can use the regular `django.core.cache.get_cache` to do some administration and raise `ImmediateHttpResponse` / `ValidationError` if needed.

I wouldn't want to go further than that, that would open a real can of worms. See:
https://www.djangopackages.com/grids/g/antiflood/

**Comment by HEdingfield** [comment]
Cool, I like this idea, but unfortunately think it's over my head to do a PR. It'd be nice to get allauth to a point where it's really easy to integrate with [django-axes](https://github.com/django-pci/django-axes) or [django-defender](https://github.com/kencochrane/django-defender), including a little documentation section on how to get them to play nicely together.

**Comment by pennersr** [comment]
I am not familiar with those packages. I quickly glanced at the documentation of axes, it seems as if you can use that one without any changes to allauth by just using the `watch_login` construct...?

https://github.com/django-pci/django-axes#not-being-locked-out-after-failed-attempts

**Comment by HEdingfield** [comment]
I haven't used them either, I just found them in your antiflood link. It'd be great if it was as simple as just using that construct. I'll try to test it out on my app when I get a chance.

**Comment by bitcity** [comment]
@pennersr `pre_login` & `login_failed` signals should be useful, thanks for taking this up.

**Comment by pennersr** [comment]
Fixed in ae472772c8f93bcb972205c9d7159051cf6f413a

**Comment by AnkitMItraOfficial** [comment]
Can anyone kindly say how to show the message when using custom forms??It would be really helpful

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1007
