### ISSUE TITLE
Limit number of email verifications sent

### ISSUE THREAD

**Issue by HEdingfield** [pennersr/django-allauth#1008]
A user can potentially sign up for an account at a site that uses allauth with someone else's e-mail address, and then attempt to login repeatedly, spamming that address with verification requests. Is it possible to build in an option that lets you limit the number of email verifications sent (e.g. 1 / hour. after the 2nd one)?

**Comment by pennersr** [comment]
For email verification there is already an internal configuration (`COOLDOWN_PERIOD = timedelta(minutes=3)`) that limits the # of emails sent. I would be okay with making this a public setting in the form of `ACCOUNT_EMAIL_COOLDOWN_PERIOD`).

However, a similar situation holds for the password forgotten scenario as well. And in this case, allauth simply does not have the required state to determine if the user requested a password reset before.

You could keep track of this via the adapter method `send_mail`. E.g. keep track of what type of mail per user was sent last, e.g. using a cache backend. I do feel that this goes a bit beyond allauth scope, throttling requests et al should be handled at a level higher than allauth.

So I am closing this, feel free to open a PR to move the `COOLDOWN_PERIOD` public and add a note in the docs...

**Comment by 9mido** [comment]
PR #2631 should hopefully solve this if merged.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1008
