### ISSUE TITLE
Broken 0002 migration in account app with ACCOUNT_UNIQUE_EMAIL = False

### ISSUE THREAD

**Issue by jezdez** [pennersr/django-allauth#1011]
It sees as if the newly added migration to extend the email field overwrites the uniqueness when having the setting `ACCOUNT_UNIQUE_EMAIL = False`. That leads to traceback during migrating like:

```
[localhost] err: django.db.utils.IntegrityError: (1062, "Duplicate entry '<user@email.tld>' for key 'account_emailaddress_email_206527469d8e1918_uniq'")
```

This is the culprit:

https://github.com/pennersr/django-allauth/blob/13db1ff13eff3758743f24274d16996445a55309/allauth/account/migrations/0002_email_max_length.py#L17

**Comment by jezdez** [comment]
Oh, I see, seems like #970 would fix that

**Comment by pennersr** [comment]
Merged #970, 0.21.0 coming up soon...

**Comment by jezdez** [comment]
@pennersr woot!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1011
