### ISSUE TITLE
email_changed signal processing can interrupt actual email change

### ISSUE THREAD

**Issue by HEdingfield** [pennersr/django-allauth#1015]
I'm not sure if this is intended for some reason, but I noticed that when I set up the following signal processor (to automatically set the username to the email address), the username would end up changing, but the email address would remain the same.

    from allauth.account.utils import user_email, user_username
    from allauth.account.signals import email_changed
    from django.dispatch import receiver

    @receiver(email_changed, dispatch_uid="allauth_email_changed")
    def email_changed(request, user, from_email_address, to_email_address, **kwargs):
        # Make sure username is updated in addition to email address
        user_username(user, to_email_address.email)
        user.save()

I'm not sure why this happens; it seems like this signal should trigger after the user's new email address is saved since it runs once the EmailAddress model finishes executing set_as_primary, which clearly has the line self.user.save(). I had to add the following line before user.save() in my signal processor in order to ensure the email address changed as well:
    
    user_email(user, to_email_address.email)

**Comment by pennersr** [comment]
This is due to the fact that `set_as_primary` is referring to `self.user`, which is a different copy of the same user as `request.user`.  Probably the best solution is to add (`email_address.user = request.user`) -- that solves your problem, and also saves on a DB lookup.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1015
