### ISSUE TITLE
newly registered user password is empty

### ISSUE THREAD

**Issue by deecodameeko** [pennersr/django-allauth#1016]
I've noticed that a new user's password is empty. Django 1.8, python 3.4. I'm using the following custom form:

    from django import forms
    from django.contrib.auth.models import User

    class SignupForm(forms.ModelForm):
        class Meta:
            model = User
            fields = ['username', 'email', 'first_name', 'last_name']

        first_name = forms.CharField(max_length=30, label='First Name')
        last_name = forms.CharField(max_length=30, label='Last Name')

        def signup(self, request, user):
            user.first_name = self.cleaned_data['first_name']
            user.last_name = self.cleaned_data['last_name']

This was working and since I've started playing with adding first_name, last_name it doesn't seem to be saving anymore. I have seen your post on stackoverflow and although this is a ModelForm instead of a Form from your example it does save the first and last name but now the password is empty?

**Comment by pennersr** [comment]
Don't use a model form listing the username and email fields, as allauth already takes care of that. Only put up a form containing the additional fields you require. So, if it's just first and last name you are after, only add those fields to your form. Furthermore, allauth already handles creation and storage of the newly created `User` instance for you. So, a model form is not really needed...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1016
