### ISSUE TITLE
UNIQUE constraint failed: account_emailaddress.email

### ISSUE THREAD

**Issue by deecodameeko** [pennersr/django-allauth#1017]
Hi, 

This is odd, I'm getting a http 500 error when attempting to signup a new user with an existing users' email address. I'd expect a nice form error rather than this. I'm using django-rest-auth with allauth(0.21). 

I seem to be running into many issues like this and am wondering what could be wrong with my setup.

**Comment by pennersr** [comment]
I am sorry, but I have not looked into django-rest-auth myself. Closing, as this is not an allauth specific issue.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1017
