### ISSUE TITLE
'SignupForm' object has no attribute 'save'

### ISSUE THREAD

**Issue by deecodameeko** [pennersr/django-allauth#1018]
Using the stackoverflow post, I copied the following:

    class SignupForm(forms.Form):
        first_name = forms.CharField(max_length=30, label='Voornaam')
        last_name = forms.CharField(max_length=30, label='Achternaam')

        def signup(self, request, user):
            user.first_name = self.cleaned_data['first_name']
            user.last_name = self.cleaned_data['last_name']
            user.save()

I get the error 'SignupForm' object has no attribute 'save' using django 1.8.

**Comment by pennersr** [comment]
What version of allauth are you using? Version 0.15.0 and below indeed required a `save` to be defined, but that is no longer the case. The above looks just fine.

**Comment by deecodameeko** [comment]
Using 0.21

**Comment by deecodameeko** [comment]
It turns out this is a result of how django rest with works.

**Comment by fproldan** [comment]
@deecodameeko how you solve this?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1018
