### ISSUE TITLE
"IntegrityError: Duplicate username" with Facebook login and username disabled

### ISSUE THREAD

**Issue by tezro** [pennersr/django-allauth#1022]
Hey guys. I'm trying to use django-allauth along with django-rest-auth having users signing up using their **email**, **first** and **last name** only. Apart from that I am trying to use Facebook auth too. In both cases, when a user is registering/signing-up, he user is created without a username, which results in *IntegrityError: (1062, "Duplicate entry '' for key 'username'")* which is obviously empty for the first created user.

Here are my settings.

```
INSTALLED_APPS = (
    ...
    'rest_framework',
    'rest_framework.authtoken',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.facebook',
    'rest_auth',
    'rest_auth.registration',
)

# Context processors.
TEMPLATE_CONTEXT_PROCESSORS += (
    'django.core.context_processors.request',
    'allauth.account.context_processors.account',
    'allauth.socialaccount.context_processors.socialaccount',
)

# Django All auth.
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_EMAIL_VERIFICATION = 'optional'
ACCOUNT_USER_MODEL_USERNAME_FIELD = None

SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_REQUIRED = True
SOCIALACCOUNT_EMAIL_VERIFICATION = False
```

Also the url that handles Facebook auth is handled by this view.

```
# urls.py
    url(r'^rest-auth/facebook/$', views.FacebookLogin.as_view(), name='fb_login'),

# views.py
from allauth.socialaccount.providers.facebook.views import FacebookOAuth2Adapter

class FacebookLogin(SocialLogin):
    adapter_class = FacebookOAuth2Adapter
```

That's about it. I am doing everything by the docs, but it doesn't seem to work :(

Thanks ahead.

**Comment by pennersr** [comment]
I do not think this is an issue in allauth, as under normal circumstances it properly fills in a unique username. Your configuration states that there is no username field (`ACCOUNT_USER_MODEL_USERNAME_FIELD = None`) which is why allauth is not touching that field at all, which is probably why you are running into trouble because you apparently do have a `username` field.

**Comment by tezro** [comment]
Ok, cool. So if I'm not using a custom user model, I should just leave this field empty? Right? As in not set it to anything.

**Comment by pennersr** [comment]
Yes, the default value is `"username"` which matches standard Django models

**Comment by tezro** [comment]
Yep, looks like that was the problem. Thank you.

**Comment by fmalina** [comment]
I am having similar problem on MySQL:

IntegrityError at /facebook/login/callback/
(1062, "Duplicate entry 'allison' for key 'username'")

I am using a custom user model and my username field is called "username" and has unique=True off course.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1022
