### ISSUE TITLE
Facebook login not working neither with oauth2 or js_sdk

### ISSUE THREAD

**Issue by stefanilie** [pennersr/django-allauth#1023]
I'm trying a Facebook Login using django-allauth and guided by this tutorial: http://www.sarahhagstrom.com/2013/09/the-missing-django-allauth-tutorial/

After I enter my password, I get this error

`[11/Jul/2015 22:51:32] "GET /static/js/main.js HTTP/1.1" 404 1631
No handlers could be found for logger "allauth.socialaccount.providers.facebook.views"
[11/Jul/2015 22:51:39] "POST /accounts/facebook/login/token/ HTTP/1.1" 200 1231`

This happens when I use the js_sdk login for facebook. If I the same but with oauth2, it crashes with an HTTPError at /accounts/facebook/login/callback/ and with this log:

`[11/Jul/2015 23:03:34] "GET /accounts/facebook/login/callback/?code=AQDx4EG7nLSCTvihlPGIubZYzVDXXZ3CYgOF4mClLmPwVENhcFSrq6674_ltwD0ev1hXJwRg5wTWHzVbBjRKgOoabyGn1THhfZFfGvAU0pPLBpYIhAlyHwl30pJz0g-ms40dcNF3hSmTWD5sno4YTBSG0Oy7G1lysPQAUKnfK7pwNyX9lLCbxQEsU_orEkHFdvS_MhoIdsE5WTgxpmKOe2olR1x2mIG_swpUSz5ZTiMVD3vbp_ezq4ewTRblzp7ymLcmxn0suX8UHYozqQzVn_DoS26J83EvBlFCYtWKb_UCSxKaBSRPU7DYtfQx1Ho6J63_eYs4yIv--aTatJrZIH_XhqBZfPa2uN0PzfLmnxA0AvzA59vYTgyeNdIR4kmFS3KRGCkiumiIYxz_aC7Z4Ik13wede3bzC1YICqmQNjMhofVDwgstj3WkQGAZRwXvGvI&state=JGzKNQjlSgqr HTTP/1.1" 500 129058`

I can't seem to find anywhere how to fix this. I just need the access_token in order to make graph_api calls.

**Comment by HEdingfield** [comment]
That tutorial is *extremely* out of date, from what I can tell. You're much better off using the official docs (though these also need to be updated, they should still get your basic functionality working):
http://django-allauth.readthedocs.org/en/latest/providers.html#facebook

**Comment by pennersr** [comment]
The " No handlers could..." is not an error, simply a logging configuration related notice. I am closing this as this is not related to an issue in allauth.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1023
