### ISSUE TITLE
Name gathered from Facebook login not populating user.first_name and user.last_name

### ISSUE THREAD

**Issue by HEdingfield** [pennersr/django-allauth#1024]
I had to introduce this code to the user_signed_up signal in order to make sure it actually occurs:

    # If using Facebook to login, make sure it properly populates the name if it hasn't already
    if 'sociallogin' in kwargs:
        if user.first_name == '':
            if kwargs['sociallogin'].account.provider == 'facebook':
                name = kwargs['sociallogin'].account.extra_data['name']
                user.first_name = name.split()[0]
                user.last_name = name.split()[1]
                user.save()

**Comment by pennersr** [comment]
This is due to #1030 -- if no fields were passed, FB only returns `id` and `name`... which is why this split() workaround could work.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1024
