### ISSUE TITLE
How can i create conditional redirection ?

### ISSUE THREAD

**Issue by mbambafd** [pennersr/django-allauth#1025]
Hello,
I am faced with a problem that would deserve some help ,
here I used me django- allauth ( latest version ) and everything works perfectly except for comfort needs I wish overriding three views views.account_confirm
views.password_reset_done
views.password_reset_key_done
why: because I want these pages to be called only once ( when a new account is created currently create for example) .
How can I Celaá please ?

**Comment by pennersr** [comment]
I am not sure what the issue is. If you need to override one or more views completely, simply put up your own urls.py and override as needed.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1025
