### ISSUE TITLE
Migration issue on Django 1.8 - relation "django_site" does not exist

### ISSUE THREAD

**Issue by andradei** [pennersr/django-allauth#1027]
With a newly created database, running `manage.py migrate` throws the following:

```
System check identified some issues:

WARNINGS:
companies.CompanyInvitation.created: (fields.W161) Fixed default value provided.
        HINT: It seems you set a fixed date / time / datetime value as default for this field. This may not be what you want. If you want to have the current date as default, use `django.utils.timezone.now`
Operations to perform:
  Synchronize unmigrated apps: registration, localflavor, filebrowser, django_extensions, rest_framework, grappelli.dashboard, floppyforms, debug_toolbar, grappelli, rest_auth, contact_us, staticfiles, messages, allauth, django_markdown
  Apply all migrations: auth, authtoken, sites, guardian, about, account, users, faq, sessions, admin, contenttypes, reversion, news, companies
Synchronizing apps without migrations:
  Creating tables...
    Creating table allauth_socialapp
    Creating table allauth_socialaccount
    Creating table allauth_socialtoken
    Running deferred SQL...
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/zfx/lib/python3.4/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
psycopg2.ProgrammingError: relation "django_site" does not exist

(Tracesbacks ...)
```

`allauth` is listed in `INSTALLED_APPS` _after_ `django.contrib.sites`:

```
DJANGO_APPS = (
    'django.contrib.sites',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles'
    'django.contrib.admin',
)

THIRD_PARTY_APPS = (
    'allauth',
    'allauth.account',
    'rest_auth.registration',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_auth',
    'guardian',
)

LOCAL_APPS = (
    'mylocal.apps',
)

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS
```

Migrations will work if I do it this way:

1. Comment out `allauth` and `allauth.accout`
2. Run `manage.py migrate`
3. Uncomment `allauth` and `allauth.accout`
4. Run `manage.py migrate`

**Comment by bspotted** [comment]
In your settings.py you have to add SITE_ID = 1 or it won't work

**Comment by wldcordeiro** [comment]
@bspotted I've run into the same issue even with the SITE_ID set to 1.

**Comment by pennersr** [comment]
Something is wrong in the way you set things up. For example:

    Creating table allauth_socialapp
    Creating table allauth_socialaccount
    Creating table allauth_socialtoken

Allauth does not feature these tables. If you install things correctly, the `allauth.socialaccount` app creates `socialaccount_social*` tables. How did you add the `socialaccount` app?

**Comment by agconti** [comment]
@bspotted @wldcordeiro, running into the same issue. `SITE_ID = 1` in my settings.

**Comment by raratiru** [comment]
@agconti 
I overcame this issue with the following order in `INSTALLED_APPS`:

    INSTALLED_APPS = (
        'django.contrib.sites',
        'allauth',                                                                 
        'allauth.account',                                                         
        # my other apps,
    )

**Comment by mgpepe** [comment]
@rartiru
My apps are already in that order and it still gives the error

**Comment by raratiru** [comment]
@mgpepe 
I am not currently using this app. 

If [SO](https://stackoverflow.com/questions/tagged/django-allauth) cannot help,try opening a new issue. However, make sure you use a Django > 2.1 [release](https://www.djangoproject.com/download/)!

**Comment by fzchriha** [comment]
I am facing the same issue

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1027
