### ISSUE TITLE
ACCOUNT_EMAIL_VERIFICATION parameter setting not work !

### ISSUE THREAD

**Issue by mbambafd** [pennersr/django-allauth#1029]
I have python v3.4 and django 1.8.3
that's my setting:
<code>

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

gettext = lambda x: x

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '````````'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = (
    'django.contrib.sites',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'swampdragon',
    'cities',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.twitter',
    'test',
    'debug_toolbar',
    'nocaptcha_recaptcha',
)
# ALLAUTH management
AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
)

ACCOUNT_AUTHENTICATION_METHOD = "username_email"
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 2
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
# Add default http protocol
ACCOUNT_LOGOUT_ON_PASSWORD_CHANGE = True
ACCOUNT_USERNAME_MIN_LENGTH = 3

ACCOUNT_PASSWORD_MIN_LENGTH = 8
ACCOUNT_SESSION_COOKIE_AGE = 84600

SOCIALACCOUNT_PROVIDERS =\
    {'facebook':
        {'SCOPE': ['email', 'public_profile', 'user_friends'],
            'AUTH_PARAMS': {'auth_type': 'reauthenticate'},
            'METHOD': 'oauth2',
            'VERIFIED_EMAIL': False,
            'VERSION': 'v2.3'},
     'google':
        {'SCOPE': ['profile', 'email'],
         'AUTH_PARAMS': {'access_type': 'online'}}}

ACCOUNT_SIGNUP_FORM_CLASS = "test.forms.SignForm"
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Debug-toolbar management
DEBUG_TOOLBAR_PATCH_SETTINGS = False
INTERNAL_IPS = '127.0.0.1'
DEBUG_TOOLBAR_PANELS = [
    'debug_toolbar.panels.versions.VersionsPanel',
    'debug_toolbar.panels.timer.TimerPanel',
    'debug_toolbar.panels.settings.SettingsPanel',
    'debug_toolbar.panels.headers.HeadersPanel',
    'debug_toolbar.panels.request.RequestPanel',
    'debug_toolbar.panels.sql.SQLPanel',
    'debug_toolbar.panels.staticfiles.StaticFilesPanel',
    'debug_toolbar.panels.templates.TemplatesPanel',
    'debug_toolbar.panels.cache.CachePanel',
    'debug_toolbar.panels.signals.SignalsPanel',
    'debug_toolbar.panels.logging.LoggingPanel',
    'debug_toolbar.panels.redirects.RedirectsPanel',
]

CONFIG_DEFAULTS = {
    # Toolbar options
    'RESULTS_CACHE_SIZE': 3,
    'SHOW_COLLAPSED': True,
    # Panel options
    'SQL_WARNING_THRESHOLD': 100,   # milliseconds
}

# We add this to maching query
SITE_ID = 1

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
)

ROOT_URLCONF = 'test.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.core.context_processors.i18n',
                'django.core.context_processors.media',
                'django.core.context_processors.static',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'allauth.account.context_processors.account',
                'allauth.socialaccount.context_processors.socialaccount',
            ],
        },
    },
]

WSGI_APPLICATION = 'test.wsgi.application'

# Database

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'test',
        'USER': 'test',
        'PASSWORD': 'test',
        'HOST': 'localhost',
        'PORT': '5432',
        'ATOMIC_REQUESTS': True,

    }
}

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGES = (
    ('fr', gettext('French')),
    ('en', gettext('English')),
)
LANGUAGE_CODE = 'fr-FR'

USE_I18N = True

USE_L10N = True

USE_TZ = True

APPEND_SLASH = True

# Static files (CSS, JavaScript, Images) management
STATIC_ROOT = str(os.path.join(BASE_DIR, "assets"))
STATIC_URL = '/assets/'

# SwampDragon settings (for realtime management )
SWAMP_DRAGON_CONNECTION = (
    'swampdragon.connections.sockjs_connection.DjangoSubscriberConnection',
    '/data')

# CITIES management

CITIES_FILES = {
    'city': {
        'filename': '////////',
        'urls': ['something}']
    },
}
CITIES_LOCALES = ['ALL']
CITIES_PLUGINS = [
    'cities.plugin.postal_code_ca.Plugin',
]

# CACHE management
CACHE = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.PyLibMCCache',
        'LOCATION': '127.0.0.1:11211',
        'TIMEOUT': 60,
        'OPTIONS': {
            'MAX_ENTRIES': 1000
        }
    }
}

# CSRF AND SECURITY management
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True

# SESSION management
SESSION_ENGINE = "django.contrib.sessions.backends.cached_db"

# RECAPTCHA management
NORECAPTCHA_SITE_KEY = ""
NORECAPTCHA_SECRET_KEY = ""
NORECAPTCHA_AJAX = True

</code>

When i created new account it pass well and i receive a link in my console but i can login it before confirmed with a link!
i have put mandatory option !
That's normal ?

**Comment by pennersr** [comment]
There is a fairly elaborate test case that tests the mandatory email confirmation scenario. See `test_email_verification_mandatory` in the `accounts` app. All in all, I do not expect an issue in allauth at this point, but feel free to reopen if you have something more concrete to go on. It is simply not feasible for me to start debugging your project / settings.py ...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1029
