### ISSUE TITLE
Make the example use localhost:8000 in email verifications

### ISSUE THREAD

**Issue by terrycojones** [pennersr/django-allauth#103]
The example uses example.com in the email verification link. This makes it impossible to simply click on a verification link to confirm an account email (you need to copy the link, edit it, then click).  Change this so the link is to localhost:8000.

I'd prefer to pull the port number out of the settings, but I don't know how. According to stack exchange you can get it from `request.META`, but you need a request to do that so I'm going to do the simplest thing possible.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/103
