### ISSUE TITLE
Facebook signup to retrieving user profile

### ISSUE THREAD

**Issue by smilledge** [pennersr/django-allauth#1030]
When signing up using Facebook users accounts are being created with an empty email address and the username set to "user".

This request is only returning the following data in the JSON response;

https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/providers/facebook/views.py#L22

Request:
```
def fb_complete_login(request, app, token):
    resp = requests.get(GRAPH_API_URL + '/me',
                        params={'access_token': token.token})
    resp.raise_for_status()
    extra_data = resp.json()
    login = providers.registry \
        .by_id(FacebookProvider.id) \
        .sociallogin_from_response(request, extra_data)
    return login
```

Response:
```
{
    "name": "Walter White",
    "id": "12345678912345"
}
```

Does the Facebook API `/me` endpoint require the fields to be provided?For example, the following request would return the correct data;

```
https://graph.facebook.com/me?fields=id,email,name,first_name,last_name&access_token=...
```

Also, here's my config from `settings.py`;

```
SOCIALACCOUNT_PROVIDERS = {
    'facebook': {
        'SCOPE': ['public_profile', 'email'],
        'AUTH_PARAMS': {
            'auth_type': 'reauthenticate'
        },
        'METHOD': 'oauth2',
        'VERIFIED_EMAIL': False,
        'VERSION': 'v2.4'
    }
}
```

Not sure if this is not configured correctly or a bug?

**Comment by ervell** [comment]
I met the same problem and here is the reason - https://developers.facebook.com/blog/post/2015/07/08/graph-api-v2.4/  ('Fewer default fields for faster performance'). Currently django allauth doesn't support v2.4 , maybe I'll find some time to create a pull-request.

**Comment by MichalPodeszwa** [comment]
+1 I've got the same issue

**Comment by Codeidea** [comment]
+1

**Comment by HEdingfield** [comment]
This is likely related to #1024, which I posted the other day.

**Comment by philippeluickx** [comment]
+1

**Comment by HEdingfield** [comment]
Another thing that might be worth looking into when resolving this issue: I tried setting VERSION to 2.3 (which theoretically should have reverted things back to 2.3 when django-allauth pulled the params correctly):

	SOCIALACCOUNT_PROVIDERS = {
		'facebook':
		   {'SCOPE': ['email', 'public_profile'],
			'AUTH_PARAMS': {'auth_type': 'https'},
			'METHOD': 'oauth2',
			'LOCALE_FUNC': lambda request: 'en_US',
			'VERIFIED_EMAIL': False,
			'VERSION': 'v2.3'},
    ...

However, the link that was generated still contained v2.4 in it:
...&next=https%3A%2F%2Fwww.facebook.com%2F**v2.4**%2Fdialog%2Foauth%3Fredirect_uri...

I checked `resp` in providers/facebook/views.py `fb_complete_login()`, and it seemed to contain the 2.3 in `GRAPH_API_URL`, but I guess it's getting overridden at some point?

**Comment by ervell** [comment]
@HEdingfield https://developers.facebook.com/docs/apps/versions
"An app can make calls to the version of the API that was the latest available when the app was created, as well as any newer, un-deprecated versions launched after the app is created.

As an example, if your app was created after v2.0 was released, it will be able to make calls to v2.0 until the expiration date of that version, and any subsequent versions (v2.1 etc) until their expiration dates."

So if you are calling the older version your request is automatically redirected to v2.4 and it has nothing to do with django_allauth.

**Comment by HEdingfield** [comment]
@pennersr my hero! any ETA on when we can see this pushed to PyPI?

Worth verifying, but I think this will close #1024 as well.

**Comment by pennersr** [comment]
@HEdingfield  :-) This issue is important enough to get a release out soon(ish)... stay tuned.

**Comment by pennersr** [comment]
In order to be compatible to the previous behavior, these fields are needed as well:

verified, locale, timezone, link, gender, updated_time

**Comment by HEdingfield** [comment]
I believe 'friends' should be included in the fields as well, to capture the 'user_friends' scope.

**Comment by pennersr** [comment]
@HEdingfield I've added a note in the documentation, allauth should not be doing that by default. Note that fetching the friends requires more work than just adding `friends`, as you would need to work your way through the paginated list of friends.

**Comment by variable** [comment]
Hi just curious when this will be released? It's currently a blocker for us.

**Comment by pennersr** [comment]
Now.

**Comment by HEdingfield** [comment]
:muscle: :clap:

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1030
