### ISSUE TITLE
Reverse URL generation failing for namespaced API

### ISSUE THREAD

**Issue by nathanmyles** [pennersr/django-allauth#1033]
I am trying to integrate facebook authentication into a namespaced API. We are using namespaces to version our API.

I am getting the following error:
```
NoReverseMatch: Reverse for 'socialaccount_signup' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
```

I found this existing issue that was closed because there was no valid use case for at the time https://github.com/pennersr/django-allauth/issues/362. I think that having a namespace to version an API is a valid use case. Thoughts?

**Comment by pennersr** [comment]
How does versioning your API relate to the URLs routing provided by allauth? You should be able to namespace your own urls without being hindered by whatever mechanism allauth uses.

**Comment by nathanmyles** [comment]
We are using the ```namespace``` parameter when including our urls (which includes the allauth social authentication URLs). This seems to break the Reverse URL generation for the allauth URLs. We can definitely namespace our URLs without touching the allauth URLs but we'd like to be able to version the social authentication endpoints along with the rest of our URL in case we need to change them in the future.

**Comment by pennersr** [comment]
URLs are being reversed in various places. Some cases of URL reversal can even occur outside of the request context (e.g. see #933). So I am still pondering on how URL reversal would work in case multiple allauth instances were running. 

On top of that, multiple allauth instances really does not make any sense, as for example for OAuth you need to set up a callback URL. For most providers this must be exactly one URL. So, that is not something you can namespace and instantiate multiple times.

All in all, it may be very easy to wrap the allauth URLs using an include with a namespace, but actually putting the namespaces to use is complicated and perhaps not even possible.

**Comment by pennersr** [comment]
Closing, if there is a complete picture for adding namespaces including reversal and multiple instances, feel free to reopen.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1033
