### ISSUE TITLE
Foursquare Callback uri is not valid for this consumer

### ISSUE THREAD

**Issue by bspotted** [pennersr/django-allauth#1036]
Did you drop the support for foursquare ? 
Because if i try to connect i get Connection Failed uri is not valid for this consumer.

cheers Daniel

**Comment by pennersr** [comment]
Must admit, I never had Foursquare up and running myself, it was contributed by somebody. I did a quick scan over at https://developer.foursquare.com/overview/auth.html and found nothing indicating that current allauth code should no longer work. What is the URI being fetched?

**Comment by bspotted** [comment]
Ahhh thanks i had connections as callback but needed the login URI. That's why i got the error. Now it's working.

**Comment by pennersr** [comment]
Ok, glad it works, thanks for reporting back...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1036
