### ISSUE TITLE
Limit Allowed OpenID servers

### ISSUE THREAD

**Issue by spirit2343** [pennersr/django-allauth#1042]
in my django settings file in define one SOCIALACCOUNT_PROVIDERS which is to one openid server. Howeve, if a hacker tries to put a different openid server in the login url: /accounts/opneid/login?process=login&openid=<somethingelse> then the application can be used as an attack proxy.

Is there a simple way to address this?

**Comment by pennersr** [comment]
Duplicate of #656

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1042
