### ISSUE TITLE
Visible request in adapter

### ISSUE THREAD

**Issue by nikolaz111** [pennersr/django-allauth#1049]
The `request` object should be visible to the `send_mail` function in the adapter. Why this would be useful? I use mandrill in all my projects to handle email sending. Request objects are the only objects that can provide access to HTTP headers. I need headers in the adapter in order to provide an organized and easy way to send i18n emails. This is because its much easier to edit mandrill templates rather than editing Django templates, plus madrill provides useful analytics.

I think this would provide greater flexibility and it is a very easy to do improvement.

The function definition would be:

```
def send_mail(self, template_prefix, email, context, request):
```

Any comments appreciated.

**Comment by pennersr** [comment]
Whether or not exposing `request` is a good thing is debatable, as there are many projects out there that are sending mails not in the context of a request, but for example from within a celery worker.

In your case, if it is the language you need, can't you use `django.utils.translation.get_language()`, and derive the params from that?

**Comment by HEdingfield** [comment]
Something like this might be useful in my case because I send out emails that have links to my site in them. I'm currently having to do something like this to create these links:

    'https://www.%s%s' % (Site.objects.get_current().domain, reverse('my_rad_page', args=(foo)))

...but it might be nicer to grab the actual domain by using `build_absolute_uri`. Maybe request could be provided as a `kwarg` so it still runs fine without requiring a request?

**Comment by pennersr** [comment]
You can use `allauth.utils.build_absolute_uri(request=None, location='/foo')` to clean up that code.

But, given that this is debatable and I do not want to be too opinionated I am ok with adding a `request=None` parameter.

**Comment by HEdingfield** [comment]
I saw you expanded that helper function today, nice work! However, in this case it still means I need to manually add the "www" in, which isn't great. I think this is just an annoying limitation with the way the Django sites framework operates (e.g. I can't make my site www.example.com, or else it'll screw up the email addresses I use to send things out).

**Comment by pennersr** [comment]
I don't fully understand what issue you are running into with the `www` prefix. You should be able to make your site www.example.com without any impact on your email...

Feel free to submit a PR that adds a `request=None` to the send_mail ...

**Comment by HEdingfield** [comment]
My mistake, the problem I had with the sites domain is actually a result of using subdomains and dev servers, not with email addresses. E.g. sometimes I use www.example.com and other times I use dev.example.com or 127.0.0.1:8000.

In any case, I'll put it on my list to do a PR for this, unless someone (@nikolaz111?) else beats me to it.

**Comment by nikolaz111** [comment]
I could use `django.utils.translation.get_language()` but in the case that any additional headers were needed, this wouldn't be enough. Thank you

**Comment by pennersr** [comment]
Closing, as there is no point in keeping this issue afloat while there currently is no real demand. Feel free to issue a pull request for https://github.com/pennersr/django-allauth/issues/1049#issuecomment-124236910 if the need arises...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1049
