### ISSUE TITLE
[Facebook] appsecret_proof parameter missing to finalize oauth2 login  

### ISSUE THREAD

**Issue by gargame** [pennersr/django-allauth#1050]
Hello pennersr, 

thank you for you great project django-allauth !

allauth.socialaccount.providers.facebook.views.fb_complete_login raises a 400 Bad Request Error because appsecret_proof parameter is missing in case of "Require App Secret" is enabled in Facebook app.

FB App Settings 
![fb_app_advanced_config_appsecret_proof](https://cloud.githubusercontent.com/assets/864245/8866119/ed8862ec-31b8-11e5-9105-87ecfd6f479c.png)

Django1.8 settings.py
```python
SOCIALACCOUNT_PROVIDERS = {
    'facebook': {
        'SCOPE': ['public_profile', 'email'],
        'AUTH_PARAMS' : { 'auth_type' : 'reauthenticate' },
        'METHOD': 'oauth2'  # instead of 'oauth2'
    }
}
```

These few lines solved the problems ; fb_complete_login still ok if you pass the parameter without this option checked.

```python

def fb_complete_login(request, app, token):
    provider = providers.registry.by_id(FacebookProvider.id)

    # Generate an appsecret_proof parameter to secure the Graph API call
    # see https://developers.facebook.com/docs/graph-api/securing-requests
    import hashlib, hmac
    _msg = bytes(token.token).encode('utf-8')
    _key = bytes(app.secret).encode('utf-8')
    appsecret_proof = hmac.new(_key, _msg, digestmod=hashlib.sha256).hexdigest()    

    resp = requests.get(
        GRAPH_API_URL + '/me',
        params={
            'fields': ','.join(provider.get_fields()),
            'access_token': token.token,
            'appsecret_proof' : appsecret_proof
        })


    resp.raise_for_status()
    extra_data = resp.json()
    login = provider.sociallogin_from_response(request, extra_data)
    return login


```

Also, in your great documentation http://django-allauth.readthedocs.org/en/latest/installation.html the lines about template context_processors make my django bug; i commented them, and for the moment (simple login/registration steps), it works without them as these modules do not exist.

```python
                # `allauth` specific context processors
                'allauth.account.context_processors.account',
                'allauth.socialaccount.context_processors.socialaccount',

```

Regards,

gargame

**Comment by pennersr** [comment]
Thanks for your contribution, I'll integrate this later on (or if you have something to pull, that would be great too).

The docs over at readthedocs.org were not updated yet...

Btw, what do you mean by "instead of" over here:

        'METHOD': 'oauth2'  # instead of 'oauth2'

**Comment by gargame** [comment]
hello,

ok, i take a look at making you a pull request; perhaps there is a better
place to put the code that generates this hash. I have to take a look a bit
more to the code and make you a proposition as soon as i can.

   'METHOD': 'oauth2'  # instead of 'oauth2'

it's just a dummy remaining comment.


Regards,



2015-07-24 8:19 GMT+02:00 Raymond Penners <notifications@github.com>:

> Thanks for your contribution, I'll integrate this later on (or if you have
> something to pull, that would be great too).
>
> The docs over at readthedocs.org were not updated yet...
>
> Btw, what do you mean by "instead of" over here:
>
>     'METHOD': 'oauth2'  # instead of 'oauth2'
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pennersr/django-allauth/issues/1050#issuecomment-124343375>
> .
>



-- 
Estelle Eulriet
(+33) 6 81 51 26 79

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1050
