### ISSUE TITLE
ImportError: No module named context_processors

### ISSUE THREAD

**Issue by variable** [pennersr/django-allauth#1051]
After upgrading to 0.22.0, I started to get this error: ImportError: No module named context_processors

It's coming from the context processors defined in the settings

    'allauth.account.context_processors.account',
    'allauth.socialaccount.context_processors.socialaccount',

If I comment them out, then I don't get the error.

**Comment by pennersr** [comment]
This is mentioned in the documentation notes on upgrading...

**Comment by ryfloyd** [comment]
I had the same issue. I know this package is still in Beta. but typically breaking changes are revisioned by a whole step. Not just from 0.21.0 to 0.22.0. Something like 0.30.0 would be a nice gesture for those of us with requirement files which allow for minor updates. This broke my production site.

**Comment by bittner** [comment]
For future reference, the information on upgrading can be found in the [change log](http://django-allauth.readthedocs.org/en/latest/changelog.html#from-0-21-0).

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1051
