### ISSUE TITLE
Care about Twitch's request rate limit

### ISSUE THREAD

**Issue by mxscho** [pennersr/django-allauth#1052]
Hi,

The Twitch API documentation suggests sending the client ID in each request to avoid getting request-limited too early, which is not implemented currently (see https://github.com/justintv/Twitch-API#rate-limits).
I'm not quite sure how this quota/whatever system works, here is some more (maybe outdated) information concerning the limits:
https://github.com/justintv/Twitch-API/issues/50

Nevertheless I think this should be implemented.
The first authorization request to https://api.twitch.tv/kraken/oauth2/authorize obviously already contains the client ID as a query parameter.
[Here](https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/providers/twitch/views.py#L17)'s an example where it is missing. Are there any more or would it just be this small fix?

**Comment by pennersr** [comment]
Indeed, only that.. as the client ID is already passed to https://api.twitch.tv/kraken/oauth2/token as well.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1052
