### ISSUE TITLE
Check for potential issues with new version of oauthlib

### ISSUE THREAD

**Issue by HEdingfield** [pennersr/django-allauth#1053]
v1.0.0 was released the other day (and v1.0.1 just came out today). It looks like there are a few "breaking changes"; probably a good idea to check over all this to make sure allauth is fully compatible with the new version: https://github.com/idan/oauthlib/releases

**Edit:** or maybe this is better reported over at [requests-oauthlib](https://github.com/requests/requests-oauthlib/)? Sorry, I'm not sure what the best practice is in this case.

**Comment by pennersr** [comment]
That is indeed a dependency of requests-oauthlib ...

**Comment by HEdingfield** [comment]
Thanks, posted here: requests/requests-oauthlib/issues/186.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1053
