### ISSUE TITLE
form opens login url inside of logging in 

### ISSUE THREAD

**Issue by amitbend** [pennersr/django-allauth#1055]
Hi,
I'm quite new to Jango & Allauth.

I'm did few changes in the login form,
now when i'm trying to login (clicking the button)
i'm being redirected to the same page without being logged in.

any ideas?

"""
<form class="form-signin" method="POST" action="{% url 'account_login' %}"> {% csrf_token %}
    {{ form.non_field_errors  }}
        <label for="userName" class="sr-only">Email address</label>
        <input type="text" id="userName" class="form-control" placeholder="Username" required autofocus>
        <label for="inputPassword" class="sr-only">Password!</label>
        <input type="password" id="inputPassword" class="form-control" placeholder="Password" required> {{ form.password.errors }}<br>
    {% if redirect_field_value %}
    <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
    {% endif %}
    <a class="button secondaryAction" href="{% url 'account_reset_password' %}">{% trans "Forgot Password?" %}</a>
    <button class="btn btn-lg btn-primary btn-block" type="submit">{% trans "Sign In" %}</button>
  </form>
"""

**Comment by pennersr** [comment]
I am sorry, that would require some debugging... closing this, as this is not an issue in allauth but rather a support ticket ...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1055
