### ISSUE TITLE
LoginForm fields order with 0.22.0

### ISSUE THREAD

**Issue by spout** [pennersr/django-allauth#1056]
Password field is displayed before email.

Django==1.8.3
django-allauth==0.22.0

```{{ form.fields|pprint }}```
```
OrderedDict([('password', <allauth.account.forms.PasswordField object at 0x3b54b10>), ('remember', <django.forms.fields.BooleanField object at 0x3b54b90>), ('login', <django.forms.fields.EmailField object at 0x3b54c10>)])
```

I have another project with django-allauth==0.21.0 and fields order was fine, then I updated to 0.22.0 same problem appeared.

Any idea ?

**Comment by spout** [comment]
Thank you !

**Comment by joshowen** [comment]
@pennersr any chance there is a release coming soon with this included?

**Comment by richardcornish** [comment]
:+1: Also bit by this.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1056
