### ISSUE TITLE
Exception silently ignored when templates are overridden

### ISSUE THREAD

**Issue by bitcity** [pennersr/django-allauth#1057]
I'm following this method to override allauth templates : http://stackoverflow.com/a/9571112/

    TEMPLATE_DIRS = (os.path.join(PROJECT_DIR, 'templates'),)

I have a custom signup form: 

    class SignupForm(forms.Form):
        city = forms.CharField(max_length=30, label='City')

        def signup(self, request, user):
            user.city = city  # <-- ERROR, it should be self.cleaned_data['city']
            user.save()

The form has an obvious error but it does not throw an exception (silently ignored). However when I comment the above `TEMPLATE_DIRS` line in settings.py, the default templates show the error. How can I catch exceptions in allauth and log them ?

**Comment by pennersr** [comment]
I don't get it. If the error above is silently ignored, what happens then? Is your user saved as is, and what is the value of city then? If it is not saved, what do you see on screen?

**Comment by bitcity** [comment]
If I use my custom templates, the user is not saved and the form is sign-up form is re-displayed with previous values filled in. 

If I use the default templates (i.e. comment out `TEMPLATE_DIRS`), the user is saved (city is blank) but the sign-up form displays an error also 

    global name 'city' is not defined

**Comment by bitcity** [comment]
@pennersr  Can you help a bit with this. Still bugged by the same issue.

**Comment by bitcity** [comment]
Reason for silent error was that the field was missing from the custom template. As a result, the field specific error message was not printed out.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1057
