### ISSUE TITLE
E-mail unique constraint fail

### ISSUE THREAD

**Issue by ervell** [pennersr/django-allauth#1058]
I wanted to test case when user with already created account is trying to connect via different provider with the same e-mail. It seems like allauth properly detects e-mail duplication because user is redirected to the form presented below:

![image](https://cloud.githubusercontent.com/assets/932227/8900890/5413c65e-3444-11e5-8515-5aae7bb5e8e1.png)

When I'm entering duplicated email form displays errors and everything is OK. However in case of entering different email IntegrityError occurs.

![image](https://cloud.githubusercontent.com/assets/932227/8901157/d11843d0-3446-11e5-8d4f-b4d167361250.png)
![image](https://cloud.githubusercontent.com/assets/932227/8901168/e63b6e9a-3446-11e5-914d-e6cfb8bea5e6.png)

In django admin I can clearly see that user has been created correctly, so going to the main page and signing in the second time works.

I believe that problem is in DefaultSocialAccountAdapter in this code:
``` python
    def save_user(self, request, sociallogin, form=None):
        """
        Saves a newly signed up social login. In case of auto-signup,
        the signup form is not available.
        """
        u = sociallogin.user
        u.set_unusable_password()
        if form:
            get_account_adapter().save_user(request, u, form)
        else:
            get_account_adapter().populate_username(request, u)
        sociallogin.save(request)
        return u
```
User is being saved two times in here - the code breaks because sociallogin.save() method doesn't take email entered in form but uses duplicated one - I think it's a bug.

**Comment by pennersr** [comment]
I cannot confirm this. The `sociallogin.save` deals with the same `self.user` instance as the once `.save_user(request, u, form)` is using. The latter properly sets `user.email`, so it is not clear to me why this conflict occurs.

**Comment by pennersr** [comment]
See d56c00ef406b1c76537e21db9270c0c383cd9f19 for a test case that covers this.

**Comment by pennersr** [comment]
Do you have a reproducible scenario for this?

**Comment by mxscho** [comment]
I'm not quite sure if this does help at all but I still want to share it.
I remember that I saw the same error page a few days ago. I believe it had something to do with me playing around with the settings - must have been ACCOUNT_UNIQUE_EMAIL (default = True).
If I remember correctly I did change this to False (and ran the migrations) while having ACCOUNT_EMAIL_REQUIRED = True. Then this error occured while playing with duplicate user insertions.
Thought I was doing something wrong (which might actually have been the case).
Finally after dumping the whole database/done migrations and rerunning all migrations from the beginning it worked.

As said ... just some random thoughts. You're obviously not trying to achieve the same thing than I was (= having non-unique emails). If I missed it completely just ignore it.

**Comment by pennersr** [comment]
You cannot toggle `ACCOUNT_EMAIL_REQUIRED` on the fly without consequences, as this setting has impact on your data model definition (uniqueness). I am closing this until we've got a clear identifiable issue in allauth, as the problem you are describing, and the source code you are referenced are covered by the test case I mentioned earlier.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1058
