### ISSUE TITLE
Can't gather data from Facebook when signing up new account

### ISSUE THREAD

**Issue by tiagofmc** [pennersr/django-allauth#1059]
Hi.

I was using django-allauth 0.20.0 and everything was working fine, but last week I couldn't login (create a new user) with Facebook. 
I saw that Facebook updated the login to version 2.4 and I decided to update django-allauth to 0.22.0 too, to see if it works, but it doesn't. 

The code in my settings.py is equal to the updated version on the documentation: 
{'facebook':
       {'METHOD': 'oauth2',
        'SCOPE': ['email', 'public_profile', 'user_friends'],
        'AUTH_PARAMS': {'auth_type': 'reauthenticate'},
        'FIELDS': [
            'id',
            'email',
            'name',
            'first_name',
            'last_name',
            'verified',
            'locale',
            'timezone',
            'link',
            'gender',
            'updated_time'],
        'EXCHANGE_TOKEN': True,
        'LOCALE_FUNC': 'path.to.callable',
        'VERIFIED_EMAIL': False,
        'VERSION': 'v2.4'}}

When I click in the Facebook link, it redirects me to the normal user sign up to fill the fields that Facebook is missing, but all the fields (first_name, last_name, email) are blank. 
Thanks in advance.

**Comment by MaxFriedrichInitPy** [comment]
I' ve got the same problem. Does anyone got some solution?

**Comment by richardcornish** [comment]
Is this happening when `SOCIALACCOUNT_AUTO_SIGNUP = False`? That's when `SignupForm` on template `socialaccount/signup.html` with username/email shows up.

**Comment by MaxFriedrichInitPy** [comment]
Thanks for quick response. Somehow pip didn't install the newest version of allauth. Works now.

**Comment by pennersr** [comment]
So this can be safely closed?

**Comment by MaxFriedrichInitPy** [comment]
Yes, problem solved. Thank you.

**Comment by tiagofmc** [comment]
I still have the problem. I updated with pip last week to version 0.22.0 of django-allauth and it didn't work. 
Did django-allauth got updated after that? 

And to answer richardcornish, no. The only thing I have on my settings is the providers info. But django all-auth should gather the info from Facebook anyway. 
For example, I can't get the email from Twitter, so the normal sign up form shows up, but it has the first name filled in with the Twitter name.

**Comment by tiagofmc** [comment]
Is Django 1.8 required for the Facebook (or the django-allauth) login to work? 
When I updated django-allauth to 0.22.0 all sort of errors appeared because I'm using Django 1.7.3.

**Comment by richardcornish** [comment]
Version 0.22.0 [dropped support](https://github.com/pennersr/django-allauth/blob/master/ChangeLog#L12) for Django 1.6, and the [Travis file](https://github.com/pennersr/django-allauth/blob/master/.travis.yml) covers versions 1.7, 1.8, and 1.9. Can you share the errors? You might need to [drop the context processors](https://github.com/pennersr/django-allauth/blob/master/ChangeLog#L16).

It's worth saying that [setup.py](https://github.com/pennersr/django-allauth/blob/master/setup.py#L127) (erroneously?) says allauth can work with Django 1.6 or higher.

**Comment by pennersr** [comment]
@richardcornish 1.6 is supported, Travis states "< 1.7"

**Comment by tiagofmc** [comment]
I got my problem solved by doing this on my project #1043

Also I had to comment the context processors as richardcornish said and update django-allauth to version 0.22.0. 

Thank you guys for the replies!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1059
