### ISSUE TITLE
Handling security breaches

### ISSUE THREAD

**Issue by bitcity** [pennersr/django-allauth#1060]
When a site's security is breached or logins are compromised, it is often required to reset passwords in bulk. More importantly, one should be able to keep track of which users were affected. 

Would it make sense to add a table to keep track of recent password resets (with a manage.py command to periodically flush it out) ?

**Comment by pennersr** [comment]
That may make sense, but not within the scope of allauth... this is best handled in a separate package.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1060
