### ISSUE TITLE
Wrong order in logn form

### ISSUE THREAD

**Issue by andreage** [pennersr/django-allauth#1062]
I've just upgraded to allauth 0.22 with Django 1.8.3 and the order of the form fields in the `LoginForm` is wrong: it is password-remember-login.

The problem as I see it is in the function `set_form_field_order`.

If I put the following code at the beginning of the function

    print type(form.fields)
    print isinstance(form.fields, SortedDict)

I get

    <class 'collections.OrderedDict'>
    True

If I force the function to go to the second part of the `if/else` instead, i.e. replacing the `if` code with

    if isinstance(form.fields, SortedDict) and False:

the problem disappears.
My limited knowledge of the subject prevents me to understand what is happening.

**Comment by andreage** [comment]
I guess the problem is here:

    if django.VERSION > (1, 8,):
        from collections import OrderedDict as SortedDict

**Comment by andreage** [comment]
Sorry, already solved.

**Comment by TobitRE** [comment]
He guys,

sorry for asking, but this would be fixed in the next version?
or is there a work around?

**Comment by aellerton** [comment]
See #1056 and
https://github.com/pennersr/django-allauth/commit/a378583c1352eb2a9e926a5e0c2cedc285bae65d

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1062
