### ISSUE TITLE
Error when opening confirmation link

### ISSUE THREAD

**Issue by arnaudlimbourg** [pennersr/django-allauth#1069]
Hello,

I have an error that comes up regularly when users click on the confirmation link.

This is the error I get
```
allauth.account.utils.url_str_to_user_pk
object of type 'int' has no len()
```

which makes sense because
```
the code is pk = base36_to_int(s)
but s has value '6336' which is the user id
```

I don't quite understand what is going on and when I use the link (with an admin account) it works properly.

I have not found anything related to that but I may have missed it.

Has anybody seen that behaviour?

**Comment by pennersr** [comment]
The PK to URL code has had quite some updates since then, so I am assuming this is fixed by now. If not, please reopen...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1069
