### ISSUE TITLE
example.db does not contain tables for email addresses

### ISSUE THREAD

**Issue by terrycojones** [pennersr/django-allauth#107]
When you run the example with the provided `example.db` file and you have email address verification turned on (or something like that), an exception is thrown when you click the signup button after entering your details at `http://localhost:8000/accounts/signup/`:

```
DatabaseError at /accounts/signup/
no such table: account_emailaddress
Request Method: POST
Request URL:    http://localhost:8000/accounts/signup/
Django Version: 1.4.1
Exception Type: DatabaseError
Exception Value:    
no such table: account_emailaddress
Exception Location: /home/terry/.virtualenvs/allauth-test/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py in execute, line 337
```

I don't think it makes that much sense to distribute `example.db` (what does it have in it anyway?). Would it be better to change the README in the examples dir to tell the user to run `python manage.py syncdb --noinput`?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/107
