### ISSUE TITLE
Use `allauth` templates folder

### ISSUE THREAD

**Issue by dyve** [pennersr/django-allauth#1070]
This may be a personal frustration of mine, but I'd like to bring this up.

Each time I use `django-allauth`, I have to make multiple template directories that seemingly have no association with allauth. Templates are in `account`, `socialaccount` and `openid` folders.

Why not consolidate all templates in an `allauth` directory? This would cause less conflicts with other applications, and provide a much more streamlined developer experience.

**Comment by pennersr** [comment]
allauth is following django convention: templates of an app `acme.foo.bar` are placed below the `bar` directory. `allauth` is the `acme` here, it is not the app name, `account` and the likes are...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1070
