### ISSUE TITLE
Problem with POST action to "." not working

### ISSUE THREAD

**Issue by gabn88** [pennersr/django-allauth#1071]
The POST action (".") as in some of the templates does not work and goes into the root of the page.

It seems to be caused by the < base href="/" > I have set for my angular application.

Anyway, I think this path should explicitly by set, for example by {{request.path}} (UGLY!) or {% url ... %} on all the templates. The latter needs some work, because for example with change password the uid32 is not known to the view...

**Comment by spout** [comment]
POST action to "." is fine most of the time. Some forms POST to unknown/multiple URLs.
You should adapt your template or not use relative path ?

**Comment by gabn88** [comment]
Fine most of the time is not enough for something as important as login/registration, etc.

A form can only post once, to one url.

But based on the comments I do not expect much help, sadly. I think I fixed it in my installation, but just wanted to mention it here as well. In case somebody has the same issue.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1071
