### ISSUE TITLE
Customizing login view to add dectorators

### ISSUE THREAD

**Issue by jlgne** [pennersr/django-allauth#1072]
I couldn't find a suitable example for customizing LoginView, so I'm verifying my approach here. I would like to add decorators (with arguments) to `LoginView` to check for certain hosts & geographical locations before proceeding with authentication & login. 

Should I inherit from `LoginView` and add `method decorators` to its `dispatch` method ? The default LoginView uses a decorator on its dispatch : `sensitive_post_parameters_m`. Do I need to specify that too here with my custom decorators or will it be called automatically when I inherit ? 

    verify_host = method_decorator(verify_header(header='host'))
    verify_city  = method_decorator(verify_geo(key='city'))

    class NewLoginView(LoginView):

        @verify_host
        @verify_city
        def dispatch(self, request, *args, **kwargs):
            return super(NewLoginView, self).dispatch(request, *args, **kwargs)

**Comment by pennersr** [comment]
Yes, you're on the right track...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1072
