### ISSUE TITLE
Facebook app

### ISSUE THREAD

**Issue by takethegum** [pennersr/django-allauth#1074]
Hi,
Is it possible to link a user with a second Facebook app with asking for the creation of a new user account ?

Thanx

**Comment by pennersr** [comment]
Users can connect multiple social accounts, even multiple of the same provider, if that is what you mean.

**Comment by takethegum** [comment]
I have one django app and two sites a.com and b.com. Each one has a Facebook app.
The user account was created with Facebook on site a.com. When i try to connect using Facebook on site b.com, django allauth ask me to create a new account.

**Comment by pennersr** [comment]
If you are using two different FB apps, the same FB user will have a different FB user ID. This complicates authentication. The FB business mapping API (https://developers.facebook.com/docs/apps/for-business) could be used to sort that out, but allauth has no support for that. You can still build this on top of allauth though ...

**Comment by jibaku** [comment]
Is creating a pull request interesting for the project ? I was thinking of adding a config var to allow the use for "for-business" apps.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1074
