### ISSUE TITLE
Adding provider meetup

### ISSUE THREAD

**Issue by cdvv7788** [pennersr/django-allauth#1079]
I created a new provider to connect with meetup. It was pretty easy using the base you provide.
Are you accepting pull requests for new providers?

**Comment by takotuesday** [comment]
:+1:

**Comment by pennersr** [comment]
Ofcourse, any provider is welcome. Please take care to include a unit test though...

**Comment by pennersr** [comment]
Closing for now -- feel free to issue a pull request ...

**Comment by abhishek-jaiswal** [comment]
is meetup supported ?
any links to docs how to add custom authentication ?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1079
