### ISSUE TITLE
ORCID provider: choose between endpoints

### ISSUE THREAD

**Issue by wetneb** [pennersr/django-allauth#1083]
The ORCID platform provides three distinct OAuth2 endpoints and it would be useful to be able to choose between them without changing the code of django-allauth. (For now the URLs are hardcoded in allauth/socialaccount/providers/orcid/views.py).

The endpoints are:
http://pub.orcid.org/
http://api.orcid.org/
http://api.sandbox.orcid.org/

What is the right way to do this? Duplicate the provider for the three different endpoints? Add a dropdown menu in the admin interface to choose between the endpoints? (How?) With sufficient pointers, I can provide a pull request.

Note: the first API endpoint require a small change in the code, as explained in the documentation:
http://django-allauth.readthedocs.org/en/latest/providers.html#orcid

**Comment by wetneb** [comment]
I went for the duplication, the code is here http://github.com/wetneb/django-allauth.

**Comment by pennersr** [comment]
There will only be one endpoint in use right? If so, then how about simply adding support for picking up the endpoint from the existing setting:

    SOCIALACCOUNT_PROVIDERS = { 'orcid': { 'ENDPOINT': 'http://api.sandbox.orcid.org' } }

**Comment by wetneb** [comment]
Ideally I'd like to be able to use both in the same app, but that's already interesting, I'll try to do that and send a PR soon.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1083
