### ISSUE TITLE
Default implementation of `allauth.utils.generate_unique_username` raises MultipleObjectsReturned in some cases

### ISSUE THREAD

**Issue by gbozee** [pennersr/django-allauth#1085]
I noticed that the default implementation in generating usernames throws/raises a MultipleObjectReturned on some occasion. I traced this to this line of code in allauth/utils.py

    def generate_unique_username(txts, regex=None):
        from .account.app_settings import USER_MODEL_USERNAME_FIELD
        username = _generate_unique_username_base(txts, regex)
        User = get_user_model()
        max_length = get_username_max_length()
        i = 0
        while True:
            try:
                if i:
                    pfx = str(i + 1)
                else:
                    pfx = ''
                ret = username[0:max_length - len(pfx)] + pfx
                query = {USER_MODEL_USERNAME_FIELD + '__iexact': ret}
                User.objects.get(**query)
                i += 1
            except User.DoesNotExist:
                return ret

The use of `User.objects.get` is what raises this exception. A solution that works is replacing `User.objects.get(**query)` with `User.objects.filter(**query)[0]` and then catching the `IndexError` Exception

**Comment by pennersr** [comment]
If you are running into MultipleObjectsReturned then something is wrong. We should not hide this, as your database needs fixing. Probably there is some collation issue, for example two users with identical usernames with different caps.

**Comment by gbozee** [comment]
But if the usernames are supposed to be autogenerated by allauth, then this problem shouldn't occur but it does. I do not collect username field in my signup form.

**Comment by gonzalodelgado** [comment]
I believe the problem here is using a `__iexact` query.
For example, we're having this exact issue with two different users: 'Deb' and 'deb'.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1085
