### ISSUE TITLE
Bug in PasswordResetFromKeyView view

### ISSUE THREAD

**Issue by mmapping** [pennersr/django-allauth#1088]
The form_valid() method within the PasswordResetFromKeyView view attempts to login the user (post LOGIN_ON_PASSWORD_RESET check).

The first parameter passed to perform_login() is request - looks like this should be self.request

**Comment by julen** [comment]
This was fixed in #1090. Mind closing the issue please?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1088
