### ISSUE TITLE
`select_related` doesn't working with 'sociallaccount_set'

### ISSUE THREAD

**Issue by luanfonceca** [pennersr/django-allauth#1089]
I am reducing the amount of queries that a page does in my Django application, but i am having problem with a specific part of it: The Django still hits the DB to create the `socialaccount` instance, event when i use `.select_related('author', 'author__socialaccount_set')` on my query.

I have the following scenario.
`Activity` has an `Author (auth.User)`, and when i iterate over the `Activity`items i am getting the gravatar photo of the `activity.author`, so i put an `select_related('author')` on the `Activity` query and its works fine for user instances, but when i go get the Gravatar photo, the Django creates a instance for the `socialaccount` and go again on the db, there are any way of use the `select_related` for the django not hit the database for each user?

If you guys want to see the code: 
My manager: https://github.com/luanfonceca/speakerfight/blob/feature/create-grade/deck/models.py#L24
My `Activity` Model: https://github.com/luanfonceca/speakerfight/blob/feature/create-grade/deck/models.py#L123
My template filter for get the Gravatar photo: https://github.com/luanfonceca/speakerfight/blob/feature/create-grade/deck/templatetags/deck_tags.py#L31

**Comment by pennersr** [comment]
I am sorry, but this is not really an issue in allauth. There might be an issue in your code or the Django ORM, but I am time-wise unable to dive into that...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1089
