### ISSUE TITLE
Email confirmation can be verified by an unauthenticated user.

### ISSUE THREAD

**Issue by kjin-** [pennersr/django-allauth#109]
I'm not sure if this is how the actual implementation should work but I still dont find it quite right that that an unauthenticated user can verify an email address from his email

http://localhost:8000/confirm_email/82fe174096e0bc6b97dd58930eb4e1d7024a584bddaf31f670961a5ed68552bf/

Anyone that receives this email with this link can actually view the content and click on the confirm button and the successful flash message appears and redirects accordingly to app_settings.EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL

If i can remember correctly, prior to the upgrade, I didnt bump into any issue like this.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/109
