### ISSUE TITLE
Determining how user authenticated

### ISSUE THREAD

**Issue by amadornimbis** [pennersr/django-allauth#1091]
I tried searching the documentation for this, but I can't seem to find what the best way is to determine how a user authenticated given a view request. There will be small differences in my site depending on if a user authenticated via a specific SocialAccount provider or via the default django.contrib.auth, and I'm not sure if this functionality is built into allauth.

**Comment by pennersr** [comment]
You can hookup some signals, and then mark some flags in the session, set a cookie, or perhaps create some database records. It depends on your project.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1091
