### ISSUE TITLE
Cannot use my own SocialaccountAdapter

### ISSUE THREAD

**Issue by ncp1113** [pennersr/django-allauth#1092]
These are my settings:
ADAPTER = "startup.views.MyAccountAdapter"
ACCOUNT_ADAPTER = "startup.views.MyAccountAdapter"
SOCIALACCOUNT_ADAPTER = 'startup.views.MySocialAccountAdapter'

Allauth would not call MySocialAccountAdapter.  I was able to fix this locally by changing  socialaccount/app_settings.py

    #@property
    #def ADAPTER(self):
        #return self._setting('ADAPTER',
                             #'allauth.socialaccount.adapter'
                             #'.DefaultSocialAccountAdapter')

 
    @property
    def SOCIALACCOUNT_ADAPTER(self):
        return self._setting('SOCIALACCOUNT_ADAPTER',
                             'allauth.socialaccount.adapter'
                             '.DefaultSocialAccountAdapter')

and

    #app_settings = AppSettings('SOCIALACCOUNT_')
    app_settings = AppSettings('')

I have put in a pull request with the changes.

**Comment by pennersr** [comment]
I am not sure what problem you are running into, but removing the AppSettings prefix is not the solution.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1092
