### ISSUE TITLE
Default base template "accounts/base.html" should show required blocks

### ISSUE THREAD

**Issue by thenewguy** [pennersr/django-allauth#110]
Minor issue... the base template should be updated to show required blocks.  Just extending a "base.html" template from "accounts/base.html" is not very helpful and then one needs to dig into other templates and find the expected block names.  This would make it faster/easier to override the base template when adding allauth to a project.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/110
