### ISSUE TITLE
Make using django.contrib.sites optional

### ISSUE THREAD

**Issue by pydolan** [pennersr/django-allauth#1101]
There should be an optional way to avoid using django.contrib.sites, where in areas of the code that read site name this model, instead it reads some configurable settings variable (e.g. SITE_NAME).

**Comment by pennersr** [comment]
See #57 for motivation on why `sites` is required. This is not something I plan on changing in the near future...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1101
