### ISSUE TITLE
Allow optional storing of provider secret/keys in settings.py instead of Social App models

### ISSUE THREAD

**Issue by pydolan** [pennersr/django-allauth#1102]
It would be nice to have the option of storing the provider secret and keys in a settings file instead of in the database.  Has there been any past discussion on the pros and cons of using one versus the other?  I suppose a database versus a file system can each be compromised as easily as the other -- with similar severity -- so maybe there is generally no advantage to storing these out of the database, but I'm guessing some users will prefer one over the other, so having an extra option would be good.

**Comment by pennersr** [comment]
For now, this is just the way it is. It is somewhat related to the use of the sites framework (see #57). Debatable, yes, but unlikely to be changed any time soon ...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1102
