### ISSUE TITLE
Revert signup and display error when signup can't send activation email

### ISSUE THREAD

**Issue by unho** [pennersr/django-allauth#1110]
If the configured email server is unavailable when a new account is being registered the action email can't be sent but no error message is displayed.

**Comment by unho** [comment]
Actually the right behavior would be to either:

- Create the registration and send the email
- Do not record the registration and report the error in the UI

**Comment by pennersr** [comment]
This is a bit of a corner case, and how you solve this is rather project specific. Why bother the user with an error message about internal server issues if you could solve this automatically in the background, e.g. by queuing up mail (celery, local smtp server, etc.). allauth provides a way for you to alter the way in which emails are sent. IMHO that should be sufficient ...

**Comment by unho** [comment]
> allauth provides a way for you to alter the way in which emails are sent.

Can you please point me to this? Thanks in advance.

**Comment by pennersr** [comment]
See the `send_mail` / `render_mail` methods of the accounts adapter.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1110
