### ISSUE TITLE
get_language() can return None in Django 1.8 by sites that refuse django internationalization

### ISSUE THREAD

**Issue by AndrewBC** [pennersr/django-allauth#1112]
This has lead to a crash in /allauth/socialaccount/providers/facebook/locale.py -- on line 56

**Comment by pennersr** [comment]
Could you elaborate? get_language seems to fallback to settings.LANGUAGE_CODE .... under what circumstances can None arise?

**Comment by AndrewBC** [comment]
Sure, I'm not sure why I didn't link this the first time. :-) https://docs.djangoproject.com/en/1.8/ref/utils/#django.utils.translation.get_language

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1112
