### ISSUE TITLE
Translations not updated

### ISSUE THREAD

**Issue by andreage** [pennersr/django-allauth#1113]
After this commit for example:
https://github.com/pennersr/django-allauth/commit/58f22fd6801a17177cb45f5de75b76c32ff231b2
some translations were left behind.
How can I help updating the missing translations?

**Comment by pennersr** [comment]
The allauth templates are merely meant as a starting point, something to get you going quickly. Hence, I do not treat issues in the translations as blocking for release, which can result in translations getting left behind.  Feel free to submit pull requests to fill in the gaps.

**Comment by andreage** [comment]
I'm happy to help, I found the link with the translations here:
http://www.transifex.com/projects/p/django-allauth/
But how can I contribute if the .po files are not up to date?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1113
