### ISSUE TITLE
Confirmation Email still sends in English when language is set to zh-CN

### ISSUE THREAD

**Issue by benwu7** [pennersr/django-allauth#1114]
Anyone has the same experience? here is my setting.py

    LANGUAGE_CODE = 'zh-CN'
    TIME_ZONE = 'America/Los_Angeles'
    USE_I18N = True
    USE_L10N = True
    USE_TZ = True

**Comment by andreage** [comment]
Is it related to https://github.com/pennersr/django-allauth/issues/1113 ?

**Comment by benwu7** [comment]
Hmm, not sure. How would I know?

**Comment by andreage** [comment]
That's how I did it. Check if part of the to be translated string is present in the .po file.
https://github.com/pennersr/django-allauth/blob/master/allauth/locale/zh_CN/LC_MESSAGES/django.po
If it's not, it means that the .po translation files are not aligned with the current version of allauth. If that's the case, it's issue https://github.com/pennersr/django-allauth/issues/1113

**Comment by benwu7** [comment]
It is in the .po file.

**Comment by pennersr** [comment]
See discussion in #1113

**Comment by iloveyo123u1** [comment]
大哥，我和你一样的问题， 发送的邮件内容是英文的，请问你最后怎么解决的

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1114
