### ISSUE TITLE
AssertionError at /accounts/social/connections/ (No exception message supplied)

### ISSUE THREAD

**Issue by flexpeace** [pennersr/django-allauth#1119]
I am getting the error at this line in the package 

Exception Location:	/mnt/data/.local/lib/python2.7/site-packages/allauth/socialaccount/providers/facebook/provider.py in get_login_url, line 71

<b>Error during template rendering</b>
In template /mnt/project/project_name/templates/socialaccount/snippets/provider_list.html, error at line 18

<b>The error is happening here in templates/socialaccount/snippets/provider_list.html: </b>
<li> <a title="{{provider.name}}" class="socialaccount_provider {{provider.id}}"
 href="{% provider_login_url provider.id process=process scope=scope auth_params=auth_params %}">{{provider.name}}</a></li>

I have set email required to true and also authentication method to email, am using js_sdk

Thanks

**Comment by pennersr** [comment]
Have a look at the line 71 -- as you can see method is expected to be either oauth2 or js_sdk.  Given that it asserts it is not one of those two, so please check your settings.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1119
