### ISSUE TITLE
South migrations fail if twitter/openid/facebook plugins are not in settings.py

### ISSUE THREAD

**Issue by powellc** [pennersr/django-allauth#112]
If you only intend to use one or two services, the application's migrations fail hard telling you that < app_name > does not exist, whether that be twitter, openid or facebook.

I'll post a proper error message the next time I migrate my app. But it should be pretty clear what's going on: the migrations don't consider what plugins are enabled. The workaround is to add the kitchen sink to the project for the first migration and then pull things out, but this doesn't work well in an automated deployment setting.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/112
