### ISSUE TITLE
Please log OAuth2 authentication failures

### ISSUE THREAD

**Issue by Almad** [pennersr/django-allauth#1120]
[OAuth2 view here](https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/providers/oauth2/views.py#L126) doesn't log failures, making them very tricky to debug.

**Comment by manlycode** [comment]
This would be helpful as I'm currently having trouble w/ Instagram logins (https://github.com/pennersr/django-allauth/issues/1220)

**Comment by zags** [comment]
Any update on this?  Debugging OAuth login failures is currently a pain.  "Social Network Login Failure" is not very informative on its own.

**Comment by zags** [comment]
I have a temporary workaround posted here: http://stackoverflow.com/a/36728888/2800876

**Comment by rorito** [comment]
This bit us really badly today. The workaround described by @zags only got us this output:
Code: unknown, Error: None

I think we really need some better logging here asap

**Comment by jleclanche** [comment]
For those wondering, it's pretty easy to add explicit logging (eg. to an instrumentation server) by overriding the `authentication_error` method on an adapter.

Example: https://github.com/HearthSim/HSReplay.net/blob/0c20282dfa75f639bd12a0ca689d4ffa7bdee80d/hsreplaynet/accounts/providers.py#L14

**Comment by benjaoming** [comment]
> This bit us really badly today. The workaround described by @zags only got us this output:
> Code: unknown, Error: None

I agree, and I apologize in advance that my case is a bit non-common.. but I was trying to make a Read the Docs' development settings work in a UWSGI deployment, which can seem a bit silly and probably is. But while doing this, I really missed better debugging info.

Injecting logging statements directly in to allauth's codebase helped me identify the issues.

If you are faced with similar issues, check that...

1. ...the cache backend `settings.CACHE_BACKEND` is shared (e.g. memory-based caching isn't shared across UWSGI workers)
1. ...same goes for the session engine, use the default database backed and ensure that your database is writable
1. ...session cookie configuration works and is readable from your instances, I found an empty `request.session` dict during debugging
1. Try setting `SOCIALACCOUNT_STORE_TOKENS=True`
1. I had django-debug-toolbar's middleware inserted before the session middleware, and that broke stuff, too

**Comment by derek-adair** [comment]
**aside -- wooo! we are up to 3 year old issues here @pennersr

------------------------

This is probably worth bumping up a bit in priority.  Certainly valid, if anyone in this issue is interested in helping contribute and give back to allauth, this would be a good quality of life fix.

**Comment by pennersr** [comment]
Moved to https://codeberg.org/allauth/django-allauth/issues/1120
