### ISSUE TITLE
Get list of Facebook friends using the same site

### ISSUE THREAD

**Issue by jaineshp** [pennersr/django-allauth#1123]
How to get the list of facebook friends using the same site if an user links his account with Facebook, and also how to import Google Contacts if he links the account with google? @pennersr 
Thank you!

**Comment by pennersr** [comment]
I am sorry, but this goes beyond the scope of allauth. The access tokens are stored (see `SocialToken`), so you can DIY based on that ...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1123
