### ISSUE TITLE
How to make google use username instead of first name

### ISSUE THREAD

**Issue by davegri** [pennersr/django-allauth#1124]
I'm using auto signup and was wondering if there is some way to change it so that auto signing up from google uses whatever is before the @ sign as the username instead of the first name (current behavior)

**Comment by pennersr** [comment]
Have a look at the account adapter populate_username() method. Here, you'll see first_name listed first as being passed to the unique username generation method. You can override this method to put in your own logic...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1124
