### ISSUE TITLE
Angellist doesn't send social_account_added signal

### ISSUE THREAD

**Issue by codygman** [pennersr/django-allauth#1130]
It sends pre_social_login. It seems that either allauth.socialaccount.providers.base.Provider.sociallogin_from_response or more likely it's caller should be sending a signal to social_account_added.

It seems that allauth.socialaccount.helpers._add_social_account is the older way of doing things? I'm guessing maybe the social_account_added Signal got overlooked in migration to the newer architecture?

**Comment by pennersr** [comment]
Sending these signals is centrally handled, and not the responsibility of the individual providers.
Note that that signal only fires when you connect (add) and additional social account, not when you signup.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1130
