### ISSUE TITLE
Add support for BitBucket Oauth 2

### ISSUE THREAD

**Issue by ericholscher** [pennersr/django-allauth#1131]
It seems Bitbucket has added support for OAuth2:

* https://blog.bitbucket.org/2015/07/30/bitbucket-now-supports-oauth2-and-fine-grained-scopes-for-resources/
* https://developer.atlassian.com/static/bitbucket/concepts/oauth2.html

I'm happy to work on adding this support if there is a good model to base it off. Should I just implement it as a named OAuth2 provider, copying one like GitHub?

**Comment by pennersr** [comment]
Indeed, I suggest you to have a look at one of the existing OAuth2 providers as a skeleton/starting point. Don't forget to provide a unit test as well (which is relatively trivial, as you only need to provide a response -- again see one of the existing providers).

I am closing this for now, feel free to submit a pull request when you are done.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1131
