### ISSUE TITLE
Can't use Django 1.8's Jinja2 template backend

### ISSUE THREAD

**Issue by jwhitlock** [pennersr/django-allauth#1133]
In Django 1.7, I was able to substitute Jinja2 templates for almost all django-allauth pages, so that authentication pages could be styled the same way as the rest of my content.  In Django 1.8, almost all can be substituted except for ``socialaccount/authentication_error.html``, and ``openid/login.html``, because of how the views render the templates.

In the case of ``socialaccount/authentication_error.html``, the call is in the file``allauth/socialaccount/helpers.py``, in ``render_authentication_error()``:

```python
        return render_to_response(
            "socialaccount/authentication_error.html",
            context, context_instance=RequestContext(request))
```

Using ``context_instance`` triggers the deprecated code path in Django's [template/loader.py](https://github.com/django/django/blob/master/django/template/loader.py#L84-L86), which includes removing template backends (like Jinja2) that don't support the legacy parameters.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1133
