### ISSUE TITLE
global name 'request' is not defined; different source code in repo vs pypi

### ISSUE THREAD

**Issue by illagrenan** [pennersr/django-allauth#1139]
When I try to reset my password I get `NameError global name 'request' is not defined`:

```
Stacktrace (most recent call last):

  File "django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "allauth/account/views.py", line 601, in dispatch
    **kwargs)
  File "django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "allauth/account/views.py", line 84, in post
    response = self.form_valid(form)
  File "allauth/account/views.py", line 619, in form_valid
    return perform_login(request, self.reset_user,
```
Line `619` in `allauth/account/views.py` is strange. In source code here on Github is this: https://github.com/pennersr/django-allauth/blob/master/allauth/account/views.py#L619 (it was fixed in this commit https://github.com/pennersr/django-allauth/commit/9c6fd09993ee86fbffe83eeef6f25cc4c91b827f).

But I just downloaded `tar` file directly from pypi and I can see different source code:

![image 1](https://cloud.githubusercontent.com/assets/320373/10179027/accf122a-6703-11e5-8b4d-4de3d05f4461.png)

![image 3](https://cloud.githubusercontent.com/assets/320373/10179120/3bc0c668-6704-11e5-91ab-c761380226e8.png)

Same wrong source code is in Github releases. I „fixed“ this temporarily by setting:
```python
ACCOUNT_LOGIN_ON_PASSWORD_RESET = False
```

**Comment by julen** [comment]
What you see is completely normal: the fix is in the master branch, however it hasn't been released to PyPI yet.

**Comment by illagrenan** [comment]
Thanks for the clarification, I'm closing this issue.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1139
