### ISSUE TITLE
Gathering emails from different social accounts

### ISSUE THREAD

**Issue by twitwi** [pennersr/django-allauth#114]
Hi again,
I used the following setup:

```
ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_EMAIL_REQUIRED = True
SOCIALACCOUNT_QUERY_EMAIL = True
```

When the user first logs in with a social account, the authorization to read his email is asked and this email is used for the User. That's perfect.

If the user tries to associate another social account to the same User, the authorization to read the email is still asked but the email is not added to the User. Here, I was expected either that the authorization would not be asked or that the email would be added to the User.

Do you think it is meaningful to implement a option for these two possible behaviors or am I missing something?
Any recommendations if I want to try and implement it? (I'm not very used to python and django yet)

Rémi

**Comment by derek-adair** [comment]
@pennersr Definitely close this as dated.  This is such a minor thing for a teeeeeny tiny amount of users.  I have NEVER... EVERRRR associated my account with more than one social network.  Why would you?

The ONLY use case I can see for this would be linking accounts to integrate with the service in some way.  However, that seems to be outside of the scope of this project.  As a power user on the internet for over a decade I social log in with google, and if they dont do google, twitter, and if they dont do twitter facebook.

The very clear solution, if you feel like addressing this, is to NOT modify/add email address.  It would avoid over complicating things and as a user this would be unexpected for you to do this.  I will add my email addresses I want associated with my account

**Comment by pennersr** [comment]
@derek-adair Valid point -- bullet nr 2 from https://github.com/pennersr/django-allauth/issues/114#issuecomment-8576150 it is then. Closing.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/114
