### ISSUE TITLE
django 1.9a KeyError at /accounts/signup

### ISSUE THREAD

**Issue by pusateri** [pennersr/django-allauth#1142]
Upgraded to django 1.9a with the cookie cutter template and got this:

KeyError at /accounts/signup/

'form'

Request Method: 	GET
Request URL: 	http://127.0.0.1:8000/accounts/signup/
Django Version: 	1.9a1
Exception Type: 	KeyError
Exception Value: 	

'form'

Exception Location: 	/usr/home/foo/src/django-allauth/allauth/account/views.py in get_context_data, line 192
Python Executable: 	/usr/home/foo/.virtualenvs/bar/bin/python
Python Version: 	2.7.10
Python Path: 	

['/usr/home/foo/Projects/bar',
 '/usr/home/foo/src/django-allauth',

The Django 1.9a release notes (https://docs.djangoproject.com/en/dev/releases/1.9/) say this which seems related. I tried moving the call to super() above the kwargs lookup but it didn't help the kwargs dict is still empty:

Form initialization was moved from the ProcessFormView.get() method to the new FormMixin.get_context_data() method. This may be backwards incompatible if you have overridden the get_context_data() method without calling super().

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1142
