### ISSUE TITLE
Populating with initial data on signup form

### ISSUE THREAD

**Issue by azolson** [pennersr/django-allauth#1146]
Hi,
thanks for making this package :)
I'm trying to populate initial data off the back of a invitation email.
Whilst I can populate the email quite easily by setting the right session attribute, I have other that I would like to populate in initial form data - first name, last name

I'm running a custom form via ACCOUNT_SIGNUP_FORM_CLASS

What's the best way of getting a request object in to read in other session attributes into initial form data?

**Comment by pennersr** [comment]
Currently, you'll have to create your own view deriving from `allauth.account.views.SignupView`, and implement a `get_form_kwargs` (see Django `FormView`).

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1146
