### ISSUE TITLE
Lazy object returned unexpected type. error  while authentication to admin page

### ISSUE THREAD

**Issue by ibrahimyilmaz** [pennersr/django-allauth#115]
Hi 
I think to use  your social authentication system in my fancy application. I tried to use  you app in my windows it works but when i try to run it on my  MAC. It gives me this tedious error.

To solve this issue, I have created at least 20 test  project which are  just copy of your test app. It doesnt run on my MAC.

What can cause me to get this error? and how can I solve this problem?

Any help will be appreciated.
Error: 
Error :

Environment:

Request Method: GET
Request URL: http://127.0.0.1:8000/admin/

Django Version: 1.5
Python Version: 2.7.1
Installed Applications:
('django.contrib.auth',
'django.contrib.contenttypes',
'django.contrib.sessions',
'django.contrib.sites',
'django.contrib.messages',
'django.contrib.staticfiles',
'django.contrib.admin',
'main',
'allauth',
'allauth.account',
'allauth.socialaccount')
Installed Middleware:
('django.middleware.common.CommonMiddleware',
'django.contrib.sessions.middleware.SessionMiddleware',
'django.middleware.csrf.CsrfViewMiddleware',
'django.contrib.auth.middleware.AuthenticationMiddleware',
'django.contrib.messages.middleware.MessageMiddleware')

Traceback:
File "/Library/Python/2.7/site-packages/django/core/handlers/base.py" in get_response

response = callback(request, _callback_args, *_callback_kwargs) File "/Library/Python/2.7/site-packages/django/contrib/admin/sites.py" in wrapper
return self.admin_view(view, cacheable)(_args, *_kwargs) File "/Library/Python/2.7/site-packages/django/utils/decorators.py" in _wrapped_view
response = view_func(request, _args, *_kwargs) File "/Library/Python/2.7/site-packages/django/views/decorators/cache.py" in _wrapped_view_func
response = view_func(request, _args, *_kwargs) File "/Library/Python/2.7/site-packages/django/contrib/admin/sites.py" in inner
return view(request, _args, *_kwargs) File "/Library/Python/2.7/site-packages/django/views/decorators/cache.py" in _wrapped_view_func
response = view_func(request, _args, *_kwargs) File "/Library/Python/2.7/site-packages/django/contrib/admin/sites.py" in index
app['models'].sort(key=lambda x: x['name']) File "/Library/Python/2.7/site-packages/django/utils/functional.py" in lt
other = other.__cast() File "/Library/Python/2.7/site-packages/django/utils/functional.py" in __cast
return self.__text_cast() File "/Library/Python/2.7/site-packages/django/utils/functional.py" in __text_cast
return func(_self.args, *_self.kw) File "/Library/Python/2.7/site-packages/django/utils/text.py" in
capfirst = lambda x: x and forcetext(x)[0].upper() + force_text(x)[1:] File "/Library/Python/2.7/site-packages/django/utils/functional.py" in __wrapper_
raise TypeError("Lazy object returned unexpected type.")
Exception Type: TypeError at /admin/
Exception Value: Lazy object returned unexpected type.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/115
