### ISSUE TITLE
ACCOUNT_USERNAME_BLACKLIST and populate_username

### ISSUE THREAD

**Issue by dogukantufekci** [pennersr/django-allauth#1150]
I've noticed that populate_username function is not working as desired.

It doesn't check ACCOUNT_USERNAME_BLACKLIST while populating account username.

https://github.com/pennersr/django-allauth/blob/1b59ba0f622bc7fc151509cd9cef8f76d28d8f83/allauth/account/adapter.py#L158

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1150
