### ISSUE TITLE
ACCOUNT_SIGNUP_REDIRECT_URL

### ISSUE THREAD

**Issue by dogukantufekci** [pennersr/django-allauth#1151]
It is very surprising to see that we are missing ACCOUNT_SIGNUP_REDIRECT_URL.

I would like to break down my signup process to at least two steps. On the first step I will create a user, then on the following steps I will ask for further input information.

Currently solving this problem by placing next parameter; however, it would be nice to have signup redirect functionality.

**Comment by sasha0** [comment]
@pennersr what do you think?

**Comment by pennersr** [comment]
If you already create the user in the first step, and start asking for additional information, you run the risk of having users in your system that signed up but did not complete the additional information. So, you'll have to take care that when such user logs in at a later time that you will continue with completing his profile (or whatever). All of this goes beyond the registration & signup phase at which allauth is focused, so this is not something I consider to be in scope. 

After signing up and logging in the normal redirect URL is used. Use this to determine the state your user is in, and redirect accordingly.

**Comment by jonashaag** [comment]
I'd love to see this too. Maybe I'd like to redirect new signups to a welcome page. I could determine this from an additional boolean flag in the database, but it feels much simpler to simply change the behaviour of the `SignupView.get_success_url` method to work as follows:

- Use `?next` param if available
- Use `ACCOUNT_SIGNUP_REDIRECT_URL` is available
- Fall back to `LOGIN_REDIRECT_URL`.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1151
