### ISSUE TITLE
SSO with SAML

### ISSUE THREAD

**Issue by radeksvarz** [pennersr/django-allauth#1153]
Hi, 

we would like to implement SSO using SAML. 

SAML Identity Provider does not seam to be listed in Providers. Are there any plans to add it?

Or is there any plan to use it together with https://bitbucket.org/lgs/djangosaml2/overview

or https://github.com/rohe/pysaml2 ?

Thanks, Radek

**Comment by pennersr** [comment]
I myself have no plans for this but am normally open to pull requests with new providers. In this case, given the additional dependencies that would be introduced, it's probably best to offer this provider in a separate package on its own...

**Comment by radeksvarz** [comment]
Hi, I propose, can you add this statement to the documentation?

**Comment by thenewguy** [comment]
@radeksvarz Did you ever get a saml provider working with allauth?

**Comment by radeksvarz** [comment]
Not tried yet.

**Comment by epicserve** [comment]
I just started researching for solutions for Shibboleth/SAML and would love to know if anyone has found a simple solution that works with django-allauth. Universities are requesting that our web app works with their Shibboleth/SAML SSO.

cc: @radeksvarz, @thenewguy, @pennersr

**Comment by ckcollab** [comment]
@epicserve sorry to bother, just checking if you ever resolved this/came up with some kind of solution?

**Comment by epicserve** [comment]
@ckcollab,

I haven't ... I've sorta had to move on to other things. I've been told though that the CAS protocol works with Shibboleth/SAML, so you might look into using [django-cas-client](https://pypi.org/project/django-cas-client/), which is what we're using for one university.

**Comment by heliodor** [comment]
Along similar lines, I've created an add-on for django-allauth to implement SSO using OAuth2. Link:
[https://github.com/HostedMetrics/django-allauth-sso](https://github.com/HostedMetrics/django-allauth-sso)

This github issue comes up when I search for SSO, so I thought I'd add a note here for anyone looking. Hope people find it useful!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1153
