### ISSUE TITLE
No module named 'account'

### ISSUE THREAD

**Issue by and-nothing-else** [pennersr/django-allauth#1154]
Django 1.9a1

Error: Invalid template library specified. ImportError raised when trying to load 'allauth.account.templatetags.account_tags': No module named 'account'

in allauth/account/templatetags/account_tags.py: `from account import *`
but all works great if: `from allauth.account import *`

**Comment by pennersr** [comment]
This was fixed in 647a1970e9e1b37ade9edc1e7430048ea25abec8

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1154
