### ISSUE TITLE
User account is getting created with empty username and email in facebook login

### ISSUE THREAD

**Issue by sarvesh-dwivedi** [pennersr/django-allauth#1155]
Hi,

I am using django-allauth (0.19.1) for facebook login. User is getting created successfully however username and email is empty. Following is the config
###############################################################
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_AUTHENTICATION_METHOD = "username_email"
ACCOUNT_SIGNUP_PASSWORD_VERIFICATION = False
ACCOUNT_EMAIL_VERIFICATION = 'optional'
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 30
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = False
ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = None
SOCIALACCOUNT_PROVIDERS = \
            {   'facebook':
                    {   'SCOPE': ['email', 'public_profile'],
                        'AUTH_PARAMS': {'auth_type': 'reauthenticate'},
                        'METHOD': 'oauth2',
                        'LOCALE_FUNC': 'path.to.callable',
                        'VERIFIED_EMAIL': False,
                        'VERSION': 'v2.3'
                    }
            }
####################################################################
Regards,
Sarvesh

**Comment by pennersr** [comment]
Closing, 0.19 is rather dated.. see https://github.com/pennersr/django-allauth/issues/1061 for possibly related info

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1155
