### ISSUE TITLE
Add a command about adding social applications

### ISSUE THREAD

**Issue by sih4sing5hong5** [pennersr/django-allauth#1156]
with this, we can add applications by command line.

It is convenient for deployment.

I think the format may be `python manage.py account_addsocialapplication NAME ID SECRET domain [domain ...]`

For security, the SECRET may be entered like password in `python manage.py createsuperuser`.

**Comment by pennersr** [comment]
I am not sure that using such a command matches the best practices for deplyoment, I think I'll pass this one. If you want to prepopulate the values automatically, you might want to look into creating a migration for this (secrets themselves could be derived from os.environ)

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1156
