### ISSUE TITLE
AssertionError when trying to syncdb

### ISSUE THREAD

**Issue by dekoza** [pennersr/django-allauth#116]
I stumbled upon a strange problem which I can't debug.
I used documentation to install allauth. I can't spot anything I may have ommited but I get AsserionError when I try to run ./manage.py syncdb

The last part of the tracebak looks like this:

```
  File "/projects/myproject/venv/lib/python2.7/site-packages/allauth/utils.py", line 9, in <module>
    import app_settings
  File "/projects/myproject/venv/lib/python2.7/site-packages/allauth/app_settings.py", line 7, in <module>
    in settings.TEMPLATE_CONTEXT_PROCESSORS
AssertionError
```

I don't know what's going on. Why does it throw AsserionError complaining about TEMPLATE_CONTEXT_PROCESSORS?

My settings look like this: https://gist.github.com/3743107

What am I missing?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/116
