### ISSUE TITLE
email_confirmation_message.html not overwriting default .txt file of the same name

### ISSUE THREAD

**Issue by audioburn** [pennersr/django-allauth#1160]
I have email_confirmation_message.html in my templates/account/email folder, where I also stored email_confirmation.message.txt which successful overwrote the default .txt file.

**Comment by audioburn** [comment]
Just upgraded. Checking to see if I still have the issue.

**Comment by audioburn** [comment]
still does not work

**Comment by pennersr** [comment]
See `allauth.account.adapter.DefaultAccountAdapter.render_mail` -- I suggest you set a breakpoint there and do some debugging why it does not work for your project configuration. Feel free to reopen if you really do find a concrete issue in allauth itself ... for now I assume this is project specific.

**Comment by jacebrowning** [comment]
I am experiencing this issue as well. 

Apparently even if the template is HTML, the file must have a `.txt` extension:

https://github.com/pennersr/django-allauth/blob/c4864dc217ef4a106e58d5ddabe88fba1dae1a4c/allauth/account/adapter.py#L102-L103

**Comment by jacebrowning** [comment]
I am also experiencing this.

**Comment by rasulkireev** [comment]
Try overwriting `email_confirmation_signup_message.html` instead of just message.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1160
