### ISSUE TITLE
How to make not unique email and unique username with good working confirmation and others functions.

### ISSUE THREAD

**Issue by aiksu** [pennersr/django-allauth#1162]
Trying to make not unique email and unique username to make registration work separate to each department. 
Like for it department all users will have 1 email address, but they will login and have their own permissions to access.
All of staff in business department will have like b2b@company.com email address. 

Made some changes in app_settings, just to avoid errors that happens, when trying to set in settings

#allauth
ACCOUNT_AUTHENTICATION_METHOD = 'username'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = False
ACCOUNT_UNIQUE_USERNAME = True
ACCOUNT_USERNAME_REQUIRED = True

in app_settings.py changed:
line 24:
        assert (self.AUTHENTICATION_METHOD
                == self.AuthenticationMethod.USERNAME) or self.UNIQUE_USERNAME

and added:
    @property
    def UNIQUE_USERNAME(self):
        """
        Enforce uniqueness of e-mail addresses
        """
        return self._setting("UNIQUE_USERNAME", True)

Thats it.
After signing up new user is created, but error happens:

Found wrong number (0) of constraints for account email address(user id, email) 

Seems, that it's is about email confirmation, but i don't know what to do.

Maybe someone can help me and show the best way how to do this hack.

**Comment by pennersr** [comment]
I am not sure what you are attempting to do here. `allauth` has no `UNIQUE_USERNAME` -- username are always required to be unique (standard Django behavior). So you only need to set `ACCOUNT_UNIQUE_EMAIL` to `False`. Also do note that if you alter settings like these for a running project, you'll need to add migrations to remove the database contraints ...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1162
