### ISSUE TITLE
Continuous alter of the provider field migration

### ISSUE THREAD

**Issue by micko75** [pennersr/django-allauth#1163]
Good evening,

The application keeps generating migration files, without any changes in the application.
For info i have configured two providers : Facebook and twitter. 
The only difference I noticed is the position of the max_length=30.

The migrations files are generated continuously.

The full files are given below :

------------------------------------
file 0002_auto_20151026_2317.py
------------------------------------
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='provider',
            field=models.CharField(verbose_name='provider', choices=[('facebook', 'Facebook'), ('twitter', 'Twitter')], max_length=30),
        ),
        migrations.AlterField(
            model_name='socialapp',
            name='provider',
            field=models.CharField(verbose_name='provider', choices=[('facebook', 'Facebook'), ('twitter', 'Twitter')], max_length=30),
        ),
    ]
--------------------------------------------------

File 0003_auto_20151026_2321.py

--------------------------------------------------
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0002_auto_20151026_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='provider',
            field=models.CharField(verbose_name='provider', max_length=30, choices=[('twitter', 'Twitter'), ('facebook', 'Facebook')]),
        ),
        migrations.AlterField(
            model_name='socialapp',
            name='provider',
            field=models.CharField(verbose_name='provider', max_length=30, choices=[('twitter', 'Twitter'), ('facebook', 'Facebook')]),
        ),
    ]
--------------------------------------------------

File 0004_auto_20151026_2336.py

--------------------------------------------------
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_auto_20151026_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='provider',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter')], max_length=30, verbose_name='provider'),
        ),
        migrations.AlterField(
            model_name='socialapp',
            name='provider',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter')], max_length=30, verbose_name='provider'),
        ),
    ]
----------------------------------

**Comment by pennersr** [comment]
What Django version are you using?

**Comment by pennersr** [comment]
I could not reproduce this myself, but I think this is fixed as part of 5b1cbf4. If not, please reopen.

**Comment by kishan3** [comment]
I am having the same error. Any idea why?
I am overriding views, serializers, for facebook login.

repetead migration files :+1: 
 -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0007_auto_20160513_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='provider',
            field=models.CharField(choices=[('google', 'Google'), ('twitter', 'Twitter'), ('facebook', 'Facebook')], max_length=30, verbose_name='provider'),
        ),
        migrations.AlterField(
            model_name='socialapp',
            name='provider',
            field=models.CharField(choices=[('google', 'Google'), ('twitter', 'Twitter'), ('facebook', 'Facebook')], max_length=30, verbose_name='provider'),
        ),
    ]

**Comment by johanneswilm** [comment]
I am seeing the same with Django 3.1. It wants to create a migration with socialapp every time the setting for which social accounts are enabled is changed. It seems to be the same as this issue: https://github.com/pennersr/django-allauth/issues/749 .

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1163
