### ISSUE TITLE
Fail to connect to github/facebook for access token--'Connection aborted.'

### ISSUE THREAD

**Issue by microelec** [pennersr/django-allauth#1164]
ConnectionError at /accounts/github/login/callback/
('Connection aborted.', error(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
Request Method:	GET
Request URL:	http://127.0.0.1:8000/accounts/github/login/callback/?code=xxxxxxxxxxxxxxxxxxxxx
Django Version:	1.7.7
Exception Type:	ConnectionError
Exception Value:	
('Connection aborted.', error(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
Exception Location:	C:\xxx\AppData\Local\Continuum\Anaconda\lib\site-packages\requests\adapters.py in send, line 407
=====================================================
And this is the run time context when send the POST request carrying 'Authorization Code' to get access token. I checked the client_id/secret and they are match with the values in github app.
What will make git hub authorization server no response?

settings	
{'cert': None, 'proxies': {}, 'stream': False, 'verify': True}
url	'https://github.com/login/oauth/access_token'

send_kwargs	
{'allow_redirects': True,
 'cert': None,
 'proxies': {},
 'stream': False,
 'timeout': None,
 'verify': True}
allow_redirects True
proxies	{}
data	
{'client_id': u'xxxxxxxxxxxxxx',
 'client_secret': u'xxxxxxxxxxx',
 'code': u'xxxxxxxxxxxxxxx',
 'grant_type': 'authorization_code',
 'redirect_uri': 'http://127.0.0.1:8000/accounts/github/login/callback/'}
method	'POST'

**Comment by pennersr** [comment]
I am not sure, but not being able to connect to upstream services is more of a server/deployment related issue and not something caused by allauth

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1164
