### ISSUE TITLE
Login error, doesn't populate django messages

### ISSUE THREAD

**Issue by fellipeh** [pennersr/django-allauth#1165]
Hello,

In my project, when a user try to make a login using username and password, if they are wrong, allauth doesn't show any message..

But when all info is correct, and it's make a login, allauth show the correct message, show login success and etc..

According to the docs, allauth, for default use django message, but.. why in wrong login isn't using message?

Regards

**Comment by pennersr** [comment]
I am sorry, but it is not feasible for me to debug specific project configurations... feel free to reopen if you truly find that there is an issue in allauth.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1165
