### ISSUE TITLE
key_expired(): unsupported operand type(s) for +: 'NoneType' and 'datetime.timedelta' 

### ISSUE THREAD

**Issue by gitdeepak** [pennersr/django-allauth#117]
in accounts.models 
    def key_expired(self):
        expiration_date = self.sent + datetime.timedelta(days=app_settings.EMAIL_CONFIRMATION_EXPIRE_DAYS)
        return expiration_date <= timezone.now()

It complains about the + operand.. 
The error is as follows :  How can i fix this ? 

TypeError at /accounts/confirm_email/7b67f20d7b3ec758f8d5ce9ea768e8b51531c4e4cf5a6de2385950ca8977bde3/
unsupported operand type(s) for +: 'NoneType' and 'datetime.timedelta'
Request Method: POST
Request URL:    http://localhost:8000/accounts/confirm_email/7b67f20d7b3ec758f8d5ce9ea768e8b51531c4e4cf5a6de2385950ca8977bde3/
Django Version: 1.4.1
Exception Type: TypeError
Exception Value:  
unsupported operand type(s) for +: 'NoneType' and 'datetime.timedelta'
Exception Location: /Users/deepakvokaliga/workspace/wazo/allauth/account/models.py in key_expired, line 92
Python Executable:  /usr/bin/python
Python Version: 2.7.2

**Comment by iraycd** [comment]
Same issue which occurred when I was testing. 
The email is not has been sent still I was checking to verify. 
Simple hack would be make the data in the `Email Confimation` to Present DateTime.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/117
