### ISSUE TITLE
Inconsistency: self vs get_adapter()

### ISSUE THREAD

**Issue by davidfischer-ch** [pennersr/django-allauth#1179]
https://github.com/pennersr/django-allauth/blob/master/allauth/account/adapter.py#L363

Why are you using get_adapter() and not self inside the adapter class?
If you have a valid reason, then why its not the case everywhere?

**Comment by pennersr** [comment]
There is no valid reason... it's simply code that once lived outside of the adapter that is now moved in there without altering to `self`...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1179
