### ISSUE TITLE
Django 1.8.5 Custom Model with only social Auth

### ISSUE THREAD

**Issue by ponty96** [pennersr/django-allauth#1181]
Please i want to use my custom model with only social auth like facebook and google. 
After successful login, if the user token doesn't exist in the DB, i redirect to a form where the user fills some details else i redirect back to the user dashboard page

**Comment by pennersr** [comment]
You can already do this with allauth, closing, not an issue.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1181
