### ISSUE TITLE
No providers in admin

### ISSUE THREAD

**Issue by daniel1943** [pennersr/django-allauth#1182]
I am using latest django beta (1.9x)

I followed guide and posted apps to settings but they don't show on admin page when creating new "social applications". Here are entire settings:

http://stackoverflow.com/questions/33516638/django-allauth-keyerror-ufacebook

Any ideas?

**Comment by pennersr** [comment]
This should be fixed as part of  5b1cbf4

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1182
