### ISSUE TITLE
Facebook Auth not working

### ISSUE THREAD

**Issue by ponty96** [pennersr/django-allauth#1183]
I clicked onhttp://127.0.0.1:5000/accounts/facebook/login/ and this was what i saw

    DoesNotExist at /accounts/facebook/login/
    SocialApp matching query does not exist.
    Request Method:	GET
    Request URL:	http://127.0.0.1:5000/accounts/facebook/login/?process=login
    Django Version:	1.8.5
    Exception Type:	DoesNotExist
    Exception Value:	
    SocialApp matching query does not exist.
    Exception Location:	/home/ponty/Documents/Projects/Pitchaman/venv/lib/python3.4/site-   packages/django/db/models/query.py in get, line 334
    Python Executable:	/home/ponty/Documents/Projects/Pitchaman/venv/bin/python3.4
    Python Version:	3.4.3

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1183
