### ISSUE TITLE
Context processors no longer needed

### ISSUE THREAD

**Issue by adrian2020my** [pennersr/django-allauth#1184]
Hi there, 

Please kindly update your installation document here:http://django-rest-auth.readthedocs.org/en/v0.5.0/installation.html#social-authentication-optional and remove point number 3 as django all-auth no longer needs context processor.Please refer: http://django-allauth.readthedocs.org/en/latest/changelog.html#from-0-21-0

Thank you, 
Kai

**Comment by pennersr** [comment]
This is not an allauth issue ...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1184
