### ISSUE TITLE
Get Twitter favourites if user has connected with their Twitter account

### ISSUE THREAD

**Issue by jackappleby** [pennersr/django-allauth#1188]
Hello, just a question. I'd like to pull my users Twitter favourites into my application. I have the option to authenticate via Twitter already. So for users that have Twitter as a connected account, I'm trying to work out how to extend this to also pull in their tweets. 

Does allauth assign the correct permissions for this to be allowed, and if so can someone enlighten me in how I would go about pulling in their tweets?

Or is it advisable that I create a completely separate app to do what I want to do? The problem with that is that it seems a shame not to use the already working and implemented Twitter auth that allauth provides.

**Comment by jackappleby** [comment]
Though about this more and realised I probably don't need users to authenticate to do what I want to do. I can use my applications Twitter credentials to get the data. Closing.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1188
