### ISSUE TITLE
Signup through admin interface with email confirmation

### ISSUE THREAD

**Issue by rivf** [pennersr/django-allauth#1191]
I want to pre-register multiple users (due to core idea of the product) through admin interface. And I want the behavior of this admin user creation to be the same as when I fill SignupForm. Particularly I want the email confirmation to be send.
What is the least painless way to do this in allauth? Don't you think admin forms for this (and similar) case should be added to django-allauth?

**Comment by sssbox** [comment]
Seems like that'd be outside of the scope of allauth, however it should be relatively easy to send email confirmations on save by overriding the `save_model` method of a custom UserAdmin class.

Some links to get you pointed in the right direction:

https://docs.djangoproject.com/en/1.8/ref/contrib/admin/#django.contrib.admin.ModelAdmin.save_model (save_model on ModelAdmin (save the object (probably by using `super()`) then check for `change == False`  and send the confirmation if the user is being created.

https://docs.djangoproject.com/en/1.8/topics/auth/customizing/#extending-the-existing-user-model (admin.site.unregister)

https://github.com/pennersr/django-allauth/blob/master/allauth/account/utils.py#L271 (send_email_confirmation)

**Comment by pennersr** [comment]
Thanks for the explanation @sssbox ... closing, this is not something in scope for allauth

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1191
