### ISSUE TITLE
Custom email backend?

### ISSUE THREAD

**Issue by jplehmann** [pennersr/django-allauth#1200]
I utilize two email backends, one for administrative tasks such as error emails and one for user-facing emails, using my domain for maximum reputation.  I want to make allauth use my custom backend. Normally this is done by providing a connection in instantiating or sending the email.  Does allauth provide a way to do this?

If not, it seems like this might be easy to add: a new setting that provided a factor method for getting the connection. If set it would use this instead of default.  I would be willing to add this myself. Am I right?

**Comment by pennersr** [comment]
All mail sent by allauth passes through https://github.com/pennersr/django-allauth/blob/master/allauth/account/adapter.py#L108 -- so simply override that adapter method.

**Comment by jplehmann** [comment]
Thank you @pennersr.

I did this, but now I'm having another strange problem -- possibly not allauth related":

```
class CustomEmailAccountAdapter(DefaultAccountAdapter):
    def render_mail(self, template_prefix, email, context):
        from project.common import get_mandrill_connection
        msg = super(CustomEmailAccountAdapter, self).render_mail(template_prefix, email, context)
        msg.connection = get_mandrill_connection()
        return msg
```

If `get_mandrill_connection` returns the default `get_connection`, this works fine. But if I actually return the mandrill connection, the email seems to never get sent, but no errors.  Of course mandrill would be the suspect here, except I use this `get_mandrill_connection` several other places in the same way, without issue.

I looked at `EmailMessage` and it looks like setting `msg.connection` should do what I want.  Do you see any problems here?

Thanks!

**Comment by mecampbellsoup** [comment]
> All mail sent by allauth passes through [https://github.com/pennersr/django-allauth/blob/master/allauth/account/adapter.py#L108](https://github.com/pennersr/django-allauth/blob/master/allauth/account/adapter.py?rgh-link-date=2015-11-20T18%3A21%3A59Z#L108) -- so simply override that adapter method.

@pennersr could you provide a link that isn't tied to `master`? Looks like the file contents have changed to the link is no longer accurate...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1200
