### ISSUE TITLE
Show exception in authentication_error.html

### ISSUE THREAD

**Issue by groovecoder** [pennersr/django-allauth#1201]
The `render_authentication_error` helper includes an `exception` context variable, but the `authentication_error.html` template does not show it, even with `DEBUG=True`

It makes it more difficult to debug socialaccount auth errors.

**Comment by pennersr** [comment]
Logging/error reporting is definitely an improvement point. I am keeping #1120 open for this.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1201
