### ISSUE TITLE
Schema.org markup for email validation

### ISSUE THREAD

**Issue by teolemon** [pennersr/django-allauth#1203]
Probably to leave behind a flag, but it would enable users to validate their account without even having to open the email. See: https://developers.google.com/gmail/markup/reference/one-click-action
```
<div itemscope itemtype="http://schema.org/EmailMessage">
<div itemprop="potentialAction" itemscope itemtype="http://schema.org/ConfirmAction">
<meta itemprop="name" content="Activate account"/>
<div itemprop="handler" itemscope itemtype="http://schema.org/HttpActionHandler">
 <link itemprop="url" href="{{ activate_url }}"/>
</div>
</div>
<meta itemprop="description" content="{% trans "You've signed up properly. To confirm your email address, click on the following link" %}"/>
</div>
```

**Comment by pennersr** [comment]
allauth currently does not contain built-in HTML templates for emails that are being sent.  It does support sending out HTML mails, just drop in an `account/email_confirmation_signup_message.html` template. In this template, you can put the HTML listed above. So all in all, there is not much for allauth to do here. It's really up to your project to come up with good looking HTML templates...

If somebody is willing to provide good looking, neutral, default HTML email templates, containing best practices as above, feel free to submit a patch. Until then, I am closing this issue.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1203
