### ISSUE TITLE
'Error retrieving access token'

### ISSUE THREAD

**Issue by rashbhat** [pennersr/django-allauth#1205]
I have followed all the steps  mentioned in the tutorial to integrate allAuth with my django project. Whenever i try to login via Google it displays
 "Social Network Login Failure

An error occurred while attempting to login via your social network account."

When i tried to debug in the AllAuth code i discovered that it is not able to retrieve the access token. It is failing at line 68 in allauth/socialaccount/providers/oauth2/client.py.

def get_access_token(self, code):
        data = {'client_id': self.consumer_key,
                'redirect_uri': self.callback_url,
                'grant_type': 'authorization_code',
                'client_secret': self.consumer_secret,
                'code': code}
        params = None
        self._strip_empty_keys(data)
        url = self.access_token_url
        if self.access_token_method == 'GET':
            params = data
            data = None
        # TODO: Proper exception handling
        resp = requests.request(self.access_token_method,
                                url,
                                params=params,
                                data=data)
        access_token = None
        print(resp.status_code)
        if resp.status_code == 200:
            # Weibo sends json via 'text/plain;charset=UTF-8'
            if (resp.headers['content-type'].split(';')[0] == 'application/json'
                or resp.text[:2] == '{"'):
                access_token = resp.json()
            else:
                access_token = dict(parse_qsl(resp.text))
            print (access_token)
       **if not access_token or 'access_token' not in access_token:**
            print('Error retrieving acess token')
            raise OAuth2Error('Error retrieving access token: %s'
                              % resp.content)
        return access_token

resp.status_code returns 401 instead of 200. Since the access_token is empty it is not able to login using google account.

**Comment by sssbox** [comment]
Please check that the you have configured callback urls on google's side properly (see the note at the top of http://django-allauth.readthedocs.org/en/latest/providers.html and also http://django-allauth.readthedocs.org/en/latest/providers.html#google)

**Comment by rashbhat** [comment]
@sssbox I have followed those steps to the 's'. It is going to the redirect_uri, once it is redirected it is not able to access the access_token.

**Comment by rashbhat** [comment]
finally resolved it.. looks like there was a trailing space in the client secret which i had entered in google developers console while registering my app.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1205
