### ISSUE TITLE
application error - Connection aborted.', gaierror(-2, 'Name or service not known')

### ISSUE THREAD

**Issue by vinodpandey** [pennersr/django-allauth#1206]
Environment:
Django==1.8.4
django-allauth==0.23.0
gunicorn==18.0

apache in front of gunicorn.

Configuration:
################### django allauth #####################################

INSTALLED_APPS.append('allauth')
INSTALLED_APPS.append('allauth.account')
INSTALLED_APPS.append('allauth.socialaccount')
INSTALLED_APPS.append('allauth.socialaccount.providers.facebook')
INSTALLED_APPS.append('allauth.socialaccount.providers.google')

AUTHENTICATION_BACKENDS.append("allauth.account.auth_backends.AuthenticationBackend")

LOGIN_REDIRECT_URL = '/'

ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 7
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_UNIQUE_EMAIL = True
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_VERIFICATION = "none"
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_SIGNUP_FORM_CLASS = 'custom_auth.forms.SignupForm'
ACCOUNT_SIGNUP_PASSWORD_VERIFICATION = True

SOCIALACCOUNT_QUERY_EMAIL = True

SOCIALACCOUNT_ADAPTER = 'custom_auth.adapter.LoginConnectAdapter'

SOCIALACCOUNT_PROVIDERS = {

     'facebook':
       {
        'SCOPE': ['email', 'public_profile', 'user_friends'],
        'AUTH_PARAMS': {'auth_type': 'https'},
        'METHOD': 'oauth2',
        'LOCALE_FUNC': lambda request: 'en_US',
        'VERIFIED_EMAIL': True,
        'VERSION': 'v2.3'
       },

      'google':
        { 'SCOPE': ['profile', 'email'],
          'AUTH_PARAMS': { 'access_type': 'online' }
        }

}

AUTH_USER_MODEL = "custom_auth.User"
################### django allauth #####################################

Issue:
Facebook and Google login works fine. But, when server is under high traffic, both google and facebook login throw application error. Normal login and registration works fine.

Below is the log file entry:

[u"ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))", u'  File "django/core/handlers/base.py", line 132, in get_response', u'  File "allauth/socialaccount/providers/oauth2/views.py", line 55, in view', u'  File "allauth/socialaccount/providers/oauth2/views.py", line 110, in dispatch', u'  File "allauth/socialaccount/providers/oauth2/client.py", line 58, in get_access_token', u'  File "requests/api.py", line 50, in request', u'  File "requests/sessions.py", line 465, in request', u'  File "requests/sessions.py", line 573, in send', u'  File "requests/adapters.py", line 415, in send']

**Comment by pennersr** [comment]
I'm sorry, but it is not feasible for me to debug project specific setups... closing, this is unlikely to be an issue in allauth.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1206
