### ISSUE TITLE
create user as user@none  not the correct user

### ISSUE THREAD

**Issue by fellipeh** [pennersr/django-allauth#1207]
Hi,

I have my custom user model, and try to make a signup using django-allauth, and they create one user as user@none  not using info passed via form...

Any ideas for these problem?

**Comment by pennersr** [comment]
I am sorry, but this is too little info to go on.. if you suspect there is a problem in allauth, please reopen and provide more elaborate info on what went wrong under what circumstances using what inputs.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1207
