### ISSUE TITLE
uniqueness of principal email

### ISSUE THREAD

**Issue by ppp0h** [pennersr/django-allauth#1211]
in django administration you can define more than 1 principal email for one user.

**Comment by saifrahmed** [comment]
Thanks for logging this.  It is indeed strange that Django allows two "Primary" email addresses.  This state appears to break Django Allauth when a user tries to log in via Social media and the social media primary email .  However, it seems more an idiosyncrasy of Django than Allauth.  How does everyone else handle this?

**Comment by aaugustin** [comment]
Django's solution for this is to define a custom user model and mark its email field as `unique=True`.

I don't think django-allauth has any role to play here. I believe this ticket can be closed.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1211
