### ISSUE TITLE
How get the access token?

### ISSUE THREAD

**Issue by Asinox** [pennersr/django-allauth#122]
Im playing with Allauth, i can say, thanks, its amazing, easy to use, but i cant see how get the access token to pass to facepy and send some post to facebook user account.

Allauth dont have any function to get this?

Thank you guys

**Comment by stefanilie** [comment]
Hi, I am trying the same thing. Where do I get the user variable? Is it in a class or somethig?

**Comment by simkimsia** [comment]
For those who were googling and landed here, this is an actual example for my use case.

My use case was to attempt to get the servers that the logged in user (and already connected with digitalocean) has on DO.

```python
from allauth.socialaccount.models import SocialToken
from django.shortcuts import render

from django.views.generic import ListView # only because i use CBV 

from core.models import Server # whatever your custom model is you need to change accordingly

# I am using a class based view. if you use DRF, or something else, you need to adapt accordingly
class ServerList(ListView):
    model = Server

    def get_queryset(self):
        user = self.request.user
        result = SocialToken.objects.filter(account__user=user, account__provider="digitalocean")
        # you can put debug points using ipdb here to check
        return super().get_queryset()
        
 ```

**Comment by krrish-sehgal** [comment]
Anyone who's wondering why the allauth token is not getting stored , use this in the settings.py SOCIALACCOUNT_STORE_TOKENS = True

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/122
