### ISSUE TITLE
Instagram error:  Social Network Login Failure

### ISSUE THREAD

**Issue by qasimalbaqali** [pennersr/django-allauth#1220]
Have instagram updated their API so that I get this error? I googled around and a lot of issues that have been opened usually got fixed by updating django-allauth. If I update django-allauth I get way more errors that I can't even open the homepage or any other page of the app, until I fix the problems (which I didn't), so I stayed on version 0.20.0 which was working great until today when I tried to try logging in with an already registered instagram account in my app. 

The error is on this link: 
http://127.0.0.1:8000/accounts/instagram/login/callback/?code=ad0282cbd2bf4eb49f489d30f08d2861&state=CyZOdFAXHR2S
```
Social Network Login Failure

An error occurred while attempting to login via your social network account.
```

**Comment by erinc** [comment]
Having the same issue.

**Comment by manlycode** [comment]
Also having this issue. I'm using:
* Django 1.6.5
* django-allauth 0.18.0

**Comment by agharabwi** [comment]
I'm facing the same issue only with Instagram. Facebook worked right away.

I tried using Django 1.5, 1.6 and 1.9 --> same issue

Can anyone help please

**Comment by manlycode** [comment]
The version I was using had the following urls for the InstagramOAuth2Adapter (allauth/socialaccount/providers/instagram/views.py):

```python
class InstagramOAuth2Adapter(OAuth2Adapter):
    provider_id = InstagramProvider.id
    access_token_url = 'https://instagram.com/oauth/access_token'
    authorize_url = 'https://instagram.com/oauth/authorize'
    profile_url = 'https://api.instagram.com/v1/users/self'
```

Those should be `https://api.instagram.com...` which was fixed in 804cb4bd6ebeca3370d6a5e5c445dbfb33fbc0b1

**Comment by pennersr** [comment]
This issue is fixed in master..

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1220
