### ISSUE TITLE
what dependencies I should install if I use source code directly

### ISSUE THREAD

**Issue by gavinxyang** [pennersr/django-allauth#1224]
HI, 
I am wondering if it is possible to just copy allauth code as a sub app in my django project. Because I may change the code in the future. But I run into some exceptions, 

looks like only copy code does not work. Any idea or instructions?

Exception Type: ImportError at /accounts/logout/
Exception Value: No module named context_processors

**Comment by bspotted** [comment]
Check for the context processors in your settings file. It appears they are missing

**Comment by pennersr** [comment]
I would recommend you to fork the repo, and pip install directly from your forked repo instead of trying to copy things yourself. All in all, it should be possible... though you are a bit on your own here. Not an issue in allauth, closing ...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1224
