### ISSUE TITLE
HTTP and HTTPS error Foursquare

### ISSUE THREAD

**Issue by bspotted** [pennersr/django-allauth#1225]
Foursquare Provider seems to have a URI Callback issue. The Callback URI is working fine on HTTP but is unable to connect to HTTPS on foursquare. It appears the https redirect is not working correctly.

It sends to http instead of https.
cheers Daniel

https://de.foursquare.com/oauth2/authenticate?redirect_uri=http%3A%2F%2Fwww.bspotted.net%2Faccounts%2Ffoursquare%2Flogin%2Fcallback%2F

**Comment by pennersr** [comment]
Did you set ACCOUNT_DEFAULT_HTTP_PROTOCOL to https? If not, then http urls can pop up due to #1258

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1225
