### ISSUE TITLE
Social only: disable all local account handling by means of a simple setting

### ISSUE THREAD

**Issue by hellvix** [pennersr/django-allauth#1227]
I wanted to use only the social media login, since I find unnecessary the auth part for unlinking accounts, e-mail validation, etc. I already use built-in Django's auth and having to deal with another one is just some work I was not expecting.

The integration is great but all these new URLs and templates that does not match mine are a down side.

**Comment by aaugustin** [comment]
You could copy the URLconf and keep only the routes you need. (Of course you'd have to be careful when upgrading, in case some routes you depend on change.)

**Comment by pennersr** [comment]
To answer the question, yes, it's possible, but currently it's not just a matter of flipping a switch. It may be worthwhile to accomodate for this use case in the future ...

**Comment by vatsalparekh** [comment]
Any update on this? Is it possible now to make only social login?

**Comment by bittner** [comment]
I too think we should make this easily configurable, as in "flipping a switch". Issue #345 is a similar discussion. Can we define what would be needed to do to make this "social login-only" (or `DISABLE_EMAIL_AUTH`) switch become reality?

**Comment by bittner** [comment]
I've added a sample solution for the current state [on StackOverflow](http://stackoverflow.com/questions/27157396/django-allauth-how-can-i-only-allow-signup-login-through-social/41454423#41454423).

**Comment by wgordon17** [comment]
@pennersr Have there been any attempts, or any open PRs for this? I wouldn't want to duplicate any efforts ;)

**Comment by kasbohm** [comment]
Hi, @wgordon17, any news on this issue?

**Comment by wadefletch** [comment]
Could I take this on?

**Comment by pennersr** [comment]
AFAIK, no work has been done in this area. Feel free to submit a PR.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1227
