### ISSUE TITLE
Twitter login problem

### ISSUE THREAD

**Issue by hellvix** [pennersr/django-allauth#1228]
After the app authorization in Twitter page, it goes back unauthenticated to the Django webiste. It is a constant loop if you try to authenticate again. No error message is presented.

**Comment by pennersr** [comment]
There is likely a configuration issue here, check callback URLs and/or app secrets. Until you have more concrete info pointing to an issue in allauth, I am closing this issue...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1228
