### ISSUE TITLE
Django 1.9 password validation

### ISSUE THREAD

**Issue by ron8mcr** [pennersr/django-allauth#1233]
Need to update `.clean_password()` method of `DefaultAccountAdapter` in order to use new Django 1.9 feature [password validation](https://docs.djangoproject.com/en/1.9/topics/auth/passwords/#password-validation)

**Comment by pennersr** [comment]
Done -- 599dfa6

**Comment by peterlauri** [comment]
When is the next planned release? We would like to use this...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1233
