### ISSUE TITLE
Github social signup throws KeyError exception

### ISSUE THREAD

**Issue by wktang** [pennersr/django-allauth#1234]
Hit a KeyError when attempting to sign up using Github social login at this following line:

https://github.com/pennersr/django-allauth/blob/6723cd03643ad24b98a8897b9bee4909c873c49e/allauth/socialaccount/providers/github/views.py#L32

Printing the value of `emails` give:

    {u'documentation_url': u'https://developer.github.com/v3', u'message': u'Not Found'}

**Comment by wktang** [comment]
@fabiocerqueira I saw this issue is still open: https://github.com/pennersr/django-allauth/issues/369

Is this expected due to the above issue still open? Any ideas?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1234
