### ISSUE TITLE
Ajax validation creates a user account

### ISSUE THREAD

**Issue by bitcity** [pennersr/django-allauth#1235]
I'm using AJAX to validate existence of a username, as the user types it in the form. When the validation is successful & the form is complete with all the details, the user is created with the Ajax request. This is undesirable in my case. I want to create the user only when a regular (non-ajax) request is submitted. 

For signup with e-mail flow, I can prevent this by submitting partial form for Ajax validation. However for social login (with username only needed at signup, no email), how can I avoid creating a user when Ajax request validates the username ? 

Should there be a flag `create_account`, which when set to False, would prevent user creation ? Or is there some way to override the custom user form & prevent this ?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1235
