### ISSUE TITLE
Security risk in linking to profile pictures hosted in Facebook

### ISSUE THREAD

**Issue by diegomatar** [pennersr/django-allauth#1237]
One of the users raised that linking to profile pictures hosted in Facebook can be a serious security issue. Right now, I am using Django Allauth for logins and social accounts.

And I use links for the user image (hosted in facebook) and user profile page on Facebook, as you can see in my own profile: http://qanda.com.br/perfil/diego-wawrzeniak/

Thanks for your time and help.

**Comment by sssbox** [comment]
This discussion isn't really in the scope of the django-allauth project.

See:

> Built-in support for django-avatar has been removed. Offering such functionality means making choices which may not be valid for everyone. For example, allauth was downloading the image (which can take some time, or even block) in the context of the login, whereas a better place might be some celery background job. Additionally, in case of an error it simply ignored this. How about retries et al? Also, do you want to copy the avatar once at sign up, or do you want to update on each login? All in all, this functionality goes way beyond authentication and should be addressed elsewhere, beyond allauth scope. The original code has been preserved here so that you can easily reinstate it in your own project: https://gist.github.com/pennersr/7571752

source: http://django-allauth.readthedocs.org/en/latest/changelog.html?highlight=avatar#from-0-14-2

**Comment by diegomatar** [comment]
Ok, thanks a lot.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1237
