### ISSUE TITLE
Username validation bug

### ISSUE THREAD

**Issue by eevilgeniuss** [pennersr/django-allauth#124]
Username validation will eventually going to fail if chosen ACCOUNT_USERNAME_REQUIRED = False in settings.

Scenario:
lets assume my email is eye-see-you@live.com

function "generate_unique_username" (in allauth.utils) will going to return "eye-see-you" without validating it with "alnum_re = re.compile(r"^[0-9a-zA-Z ]+$")" regix (in allauth.account.forms) and it is directly set as a username which is causing trouble later on in URL mappings.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/124
