### ISSUE TITLE
How to avoid social login while keeping account connect

### ISSUE THREAD

**Issue by caruccio** [pennersr/django-allauth#1240]
Hi.

Is there any way to connect an existing (regular) account with social login disabled?

What I need is to have my users to signup as usual, and later connect one or more social accounts, but they must be unable to signin/signup using any social account.

Thanks.

**Comment by pennersr** [comment]
You can use the `is_open_for_signup` adapter method and the `/accounts/social/connections/` view.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1240
