### ISSUE TITLE
how to login using token to django allauth LinkedIn

### ISSUE THREAD

**Issue by myeureka** [pennersr/django-allauth#1241]
I'm using django allauth and I have configured to LinkedIn, Its socialapp and site too. I can login using accounts/LinkedIn/login using browser.

Now I have to login to Linkedin using token in post method like accounts/Facebook/login/token but don't know how. Its desired use is to login through mobile but I want my users to register on my server using django allauth. this will be easy for to integerate android linkedin-sdk with django server

Any help is appreciated

**Comment by pennersr** [comment]
I am sorry, but I am unable to offer support on this issue. Closing, as this is not an issue in allauth itself...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1241
