### ISSUE TITLE
Django-allauth instagram issue - Social Network Login Failure

### ISSUE THREAD

**Issue by agharabwi** [pennersr/django-allauth#1243]
I'm trying to use django-allauth==0.24.1 with Django==1.9 and python-instagram==1.3.2 to login in using Instagram API.

I have created an client in Instagram.com with redirect_url
http://127.0.0.1:8000/accounts/instagram/login/callback/

I can connect to facebook correctly and after the login it redirects to correct location. However, when I try to login with Instagram, I get

    Social Network Login Failure

    An error occurred while attempting to login via your social network account.

    and the URL: http://127.0.0.1:8000/accounts/instagram/login/callback/?code=12d4ec2ac8e2XXX

my settings.py:

    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    
    AUTHENTICATION_BACKENDS = (
    # Needed to login by username in Django admin, regardless of `allauth`
    "django.contrib.auth.backends.ModelBackend",
    # `allauth` specific authentication methods, such as login by e-mail
    "allauth.account.auth_backends.AuthenticationBackend"
    )
 
    TEMPLATE_CONTEXT_PROCESSORS = (
        "django.core.context_processors.request",
        "django.contrib.auth.context_processors.auth",
        "allauth.account.context_processors.account",
        "allauth.socialaccount.context_processors.socialaccount",
    )
 
    SITE_ID = 1
    # auth and allauth settings
    LOGIN_REDIRECT_URL = '/'
    ACCOUNT_LOGOUT_REDIRECT_URL = '/'
    SOCIALACCOUNT_QUERY_EMAIL = True
    SOCIALACCOUNT_PROVIDERS = {
     'facebook': {
        'SCOPE': ['email',],
        'METHOD': 'oauth2', #'js_sdk'  # instead of
        'VERIFIED_EMAIL': False,
    },
    'instagram': {
        'SCOPE':['public_content'],
        'METHOD': 'oauth2', #'js_sdk'  # instead of
        'VERIFIED_EMAIL': False,  
    },
    }

     ACCOUNT_SIGNUP_FORM_CLASS = 'webPortal.forms.CustomSignupForm'

     #ACCOUNT_USER_MODEL_USERNAME_FIELD = None
     ACCOUNT_EMAIL_REQUIRED = True
     ACCOUNT_USERNAME_REQUIRED = True
     ACCOUNT_FIRSTNAME_REQUIRED = True
     ACCOUNT_LASTNAME_REQUIRED = True
     ACCOUNT_AUTHENTICATION_METHOD = 'email'

     INSTALLED_APPS = [
        'django.contrib.sites',
        'django.contrib.admin',
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.staticfiles',
        'allauth',
        'allauth.account',
        'allauth.socialaccount',
        'allauth.socialaccount.providers.facebook',
        'allauth.socialaccount.providers.instagram',
        'webPortal',
        ]
my url.py:

    urlpatterns = [
        url(r'^$', 'webPortal.views.home', name='home'),
        url(r'^admin/', admin.site.urls),
        url(r'^accounts/', include('allauth.urls')),
    ]

I tried many different version of Django and allauth with the same error for Instagram.

What am I doing wrong? please help

**Comment by igor-shevchenko** [comment]
Instagram recently changed their oauth URLs. The old ones return 405 error now. This was fixed in #1218, but the change is not released on PyPI yet. You can update to current master version to receive that fix:

    pip install https://github.com/pennersr/django-allauth/zipball/master

**Comment by olivercera** [comment]
I was facing this problem as well, master version did the trick

how can I know whene this is released on PyPI? thanks

**Comment by pennersr** [comment]
Closing... hope to get a release out soonish

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1243
