### ISSUE TITLE
Facebook js_sdk popup blocked

### ISSUE THREAD

**Issue by genxstylez** [pennersr/django-allauth#1245]
as titled.

searched on the net, couldn't find the answer, any help is appreciated!

Thanks!

Code I am using
```
{% load socialaccount %}
{% providers_media_js %}
<a href="{% provider_login_url "facebook" method="js_sdk" %}">Facebook Connect</a>
```

**Comment by pennersr** [comment]
Is there any other JS on the page that might be interfering with things?

**Comment by pennersr** [comment]
Is your site viewable somewhere?

**Comment by pennersr** [comment]
Closing for now, works as far as I can tell.. reopen if you really do come to the conclusion there is an issue in allauth

**Comment by leonardtkt** [comment]
Hi, I'm having the same issue here. Any solution found since ?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1245
