### ISSUE TITLE
how to override ResetPasswordKeyForm

### ISSUE THREAD

**Issue by damianpv** [pennersr/django-allauth#1246]
I'm having trouble with a custom ResetPasswordKeyForm is not working in the template

ACCOUNT_FORMS = {
    ....
    'reset_password_key': 'profile.forms.CustomResetPasswordKeyForm',
}
Regards,

**Comment by v1k45** [comment]
Hi @damianpv 
Use `reset_password_from_key` instead of `reset_password_key`.

**Comment by damianpv** [comment]
Thanks @v1k45

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1246
