### ISSUE TITLE
Missing migration for Django 1.9

### ISSUE THREAD

**Issue by ivanvenosdel** [pennersr/django-allauth#1247]
### To reproduce with Django 1.9:

```
python manage.py makemigrations --dry-run

Migrations for 'authtools':
  0003_auto_20160108_1548.py:
    - Alter field groups on user
```

### Suggestion for automatically detecting this in the future
I was able to setup automated testing for this in my own project by adding a manage command to my demo app and invoking it from tox.

https://github.com/WimpyAnalytics/django-andablog/commit/45501a2e0015712ec539f198e6dbe065925c1b6e

Edit: If your demo app uses other 3rd party apps will want an ignore list. Like in [this version](https://github.com/WimpyAnalytics/django-andablog/blob/72d0f318388482750e0b69e86efa3ff182e3b597/demo/common/management/commands/check_missing_migrations.py).

### Want a PR?
I would be happy to create a PR for the missing migration or the code to check for it in the future or both. Just let me know what is of interest.

**Comment by pennersr** [comment]
I am not sure I fully understand the issue. Your makemigrations output shows a migration being created for `authtools`, which is not something offered by `allauth`. Is there an issue in `allauth` that you are referring to here?

**Comment by ivanvenosdel** [comment]
@pennersr Dangit, yes, this is isn't the first time I mixed these project names up in my project. Sorry about the distraction.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1247
