### ISSUE TITLE
Reformat changelog according to best practices

### ISSUE THREAD

**Issue by svetlyak40wt** [pennersr/django-allauth#1250]
Is it possible to make the changelog more version oriented. I belive, format suggested by http://keepachangelog.com is a good candidate.

If you wish, I could send your a pull request with reformatted changelog.

This will help humans and [robots](https://allmychanges.com) to understand what happened in which version.

**Comment by pennersr** [comment]
For now I have been keeping track of noteworthy changes in a GNU ChangeLog formatted file, which, according to your linked article, is a rather naive format. It does not do much explaining on this point though.

I am open to alternatives, provided they have sufficient traction in the community. I have not done any research on this matter, do you have any pointers to well known projects using this approach?

**Comment by svetlyak40wt** [comment]
I have many examples. Working on my [petproject](https://allmychanges.com) (it is a release notes tracker which transforms them to RSS like feeds), I encountered only few projects with strange changelog formats.

Many famous software projects keep their changelog in a way which abovermentioned article suggests:

- [nose](https://raw.githubusercontent.com/nose-devs/nose/master/CHANGELOG)
- [requests](https://github.com/kennethreitz/requests/blob/master/HISTORY.rst)
- Django keeps release notes in [separate files](https://github.com/django/django/tree/master/docs/releases), because their are huge, but AllMyChanges's parser is able [to eat them too](https://allmychanges.com/p/python/django/).
- and there are many of others.

Pretend, you are a django-allauth's user who have pinned version `0.15.0` in his `requirements.txt`. And your friend said look basecamp support was introduced in `0.24.0` version. You are eager to know what else was added/fixed/broken in this `0.24.0` version, but have to scan changelog and picking pieces of text delimited with dates and emails if changelog is in the GNU ChangeLog format.

Most people upgrade to the version not to the date. That is why it is important to describe what changed in each version.

**Comment by svetlyak40wt** [comment]
Created a pull

**Comment by pennersr** [comment]
Thanks for going to the trouble of doing this. I picked up your pull, but changed from md to rst so that the content can be easily included in the existing documentation. Also separated backwards incompatible changes from note worthy features.

**Comment by svetlyak40wt** [comment]
Great! Thank you for accepting my changes!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1250
