### ISSUE TITLE
Provide plain Python equivalents of socialaccount templatetags

### ISSUE THREAD

**Issue by aaugustin** [pennersr/django-allauth#1252]
First, thanks for a great library! django-allauth gets lots of things right :-)

I noticed that overriding `account/login.html` with a Jinja2 template is more difficult than it should be, because that template relies very heavily on Django template tags which cannot be used in any other context than rendering a Django template.

Specifically, `ProviderLoginURLNode.render` contains a significant amount of logic. It would be nice to push that logic into the provider base class or in a standalone function.

Furthermore, templatetags look up providers in the global registry. I recommend that any data the template needs be passed explicitly in the template context. It's a good practice to make explicit which data is used in the template.

I could write a patch for this, but as a first step, I wanted to check if you had an opinion on this issues. Let me know how we could move forwards.

**Comment by pennersr** [comment]
I think it is a good idea to decouple things here, though I am not sure how you envision to handle the global registry here, and whether or not that is really essential. Feel free to come up with a proposal...

**Comment by derek-adair** [comment]
I dont use jinja2 but this seems to be a valid point and potentially another reason to refactor `account/login.html` as I outlined in option (a) of #459

**Comment by pennersr** [comment]
See: https://github.com/pennersr/django-allauth/issues/3408#issuecomment-1703759227

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1252
