### ISSUE TITLE
`account/email_confirmed.html` template appears to be unused

### ISSUE THREAD

**Issue by aaugustin** [pennersr/django-allauth#1254]
`ConfirmEmailView` returns this email from `get_template_names()` on POST requests, but such requests (rightfully) never render a template; instead they set a message and redirect.

I believe the template can be removed and `get_template_names()` can be replaced by simply declaring:

    template_name = "account/email_confirm.html"

**Comment by pennersr** [comment]
You're right -- this is apparently some dead code from the times the confirm email was rendering a template instead of redirecting. To be removed...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1254
