### ISSUE TITLE
Built-in SESSION_COOKIE_AGE Django setting is duplicated and overridden

### ISSUE THREAD

**Issue by aaugustin** [pennersr/django-allauth#1257]
Unless I missed something, `ACCOUNT_SESSION_COOKIE_AGE` has exactly the same semantics as Django's built-in `SESSION_COOKIE_AGE` and overrides it. I discovered that after spending some time scratching my head about why Django ignored `SESSION_COOKIE_AGE`...

I would suggest to document its usefulness, if there is one, and remove it in favor of `settings.SESSION_COOKIE_AGE` otherwise.

**Comment by aaugustin** [comment]
For now the workaround is just:

    ACCOUNT_SESSION_COOKIE_AGE = SESSION_COOKIE_AGE

**Comment by pennersr** [comment]
I had to do some digging to see why this got introduced, here it is: 81c8210e0012cdf785a728d704cc23807219ade7

Though, I must admit, looking back introducing a new setting only because the default value is different does not make much sense. So we need to phase this out ...

**Comment by pennersr** [comment]
Phased it out in e3b09f3 (its value now defaults to Django's value, and its existence has been removed from the documentation)

**Comment by bitcity** [comment]
This was missed from CHANGELOG :)

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1257
