### ISSUE TITLE
build_absolute_uri enforces http even when Django correctly uses https

### ISSUE THREAD

**Issue by aaugustin** [pennersr/django-allauth#1258]
The docstring of `allauth.utils.build_absolute_uri` says:

> Like request.build_absolute_uri, but gracefully handling the case where request is None.

This is misleading because `build_absolute_uri`:

1. always gets a `request` parameter
2. overrides the scheme even when request is not None — that is, always

The latter is especially annoying because it can destroy information correctly gathered by Django. Also, by default, it weakens security.

Indeed, most sites that use django-allauth will run on HTTP in development and HTTPS in production. Assuming a site is properly configured for Django to [detect HTTPS](https://docs.djangoproject.com/en/1.9/ref/request-response/#django.http.HttpRequest.is_secure), by default, in production, django-allauth's version of `build_absolute_uri` will change the scheme to `http`, while Django had automatically and correctly set it to `https`. If the site isn't deployed with HSTS, this might allow an attacker to intercept a password reset link.

This behavior makes django-allauth less secure by default for users who don't peruse the documentation and provide a different value of `ACCOUNT_DEFAULT_HTTP_PROTOCOL` in development and production. That's one more thing to configure and it's redundant with built-in Django settings.

By the way, three years after Firesheep, it doesn't seem reasonable to even consider running a website with authenticated users over HTTP ;-)

For reference, here are the three uses of this function in the django-allauth code base (see below), I believe:

- the first two should just use `request.build_absolute_uri`
- the third one still needs a way to enforce https for providers that require it, which could be as simple as:

```python
uri = request.build_absolute_uri(...)
if protocol == 'protocol':
    uri = uri.replace('http://', 'https://')
```
----

`allauth.account.adapter`

```python
class DefaultAccountAdapter(object):
    # ...
    def get_email_confirmation_url(self, request, emailconfirmation):
        # ...
        ret = build_absolute_uri(
            request,
            url,
            protocol=app_settings.DEFAULT_HTTP_PROTOCOL)
```

`allauth.accounts.forms`

```python
class ResetPasswordForm(forms.Form):
    # ...
    def save(self, request, **kwargs):
        # ...
            url = build_absolute_uri(
                request, path,
                protocol=app_settings.DEFAULT_HTTP_PROTOCOL)
```

`allauth.socialaccount.providers.oauth2.views`

```python
class OAuth2View(object):
    # ...
    def get_client(self, request, app):
        # ...
        callback_url = build_absolute_uri(
            request, callback_url,
            protocol=protocol)
```

**Comment by pennersr** [comment]
This method stems from the (debable) use case where a site is running both HTTP and HTTPS. For example, HTTP for the public parts, and HTTPS for all private views. In this case, allauth should switch from HTTP to HTTPS when constructing e.g. password reset URLs.

Still pondering on how to proceed. Drop all of this and possibly break things, or without breaking backwards compatibility:  change `build_absolute_uri` so that the protocol is only changed in case we're upgrading HTTP to HTTPS, and prevent downgrading the protocol at any time.

**Comment by pennersr** [comment]
See 4032ad8 -- this keeps backwards compatibility, while respecting request.build_absolute_uri ...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1258
