### ISSUE TITLE
Setting a user's password always logs them out

### ISSUE THREAD

**Issue by aaugustin** [pennersr/django-allauth#1262]
I believe "set password" should honor `ACCOUNT_LOGOUT_ON_PASSWORD_CHANGE`, that is:

```diff
diff --git a/allauth/account/views.py b/allauth/account/views.py
index f4cc684..f06b8a4 100644
--- a/allauth/account/views.py
+++ b/allauth/account/views.py
@@ -525,6 +525,9 @@ class PasswordSetView(AjaxCapableProcessFormViewMixin, FormView):
 
     def form_valid(self, form):
         form.save()
+        if (update_session_auth_hash is not None and
+                not app_settings.LOGOUT_ON_PASSWORD_CHANGE):
+            update_session_auth_hash(self.request, form.user)
         get_adapter().add_message(self.request,
                                   messages.SUCCESS,
                                   'account/messages/password_set.txt')
```

Alternatively you could provide a `ACCOUNT_LOGOUT_ON_PASSWORD_SET` setting that would default to the value of `ACCOUNT_LOGOUT_ON_PASSWORD_CHANGE`. But I fail to imagine a reason why one would want them to have different values.

**Comment by darklow** [comment]
+1
`ACCOUNT_LOGOUT_ON_PASSWORD_CHANGE = False` not respected.
Really unexpected behaviour for a user to be logged out when changing its password.
@aaugustin if your fixes bug, could you make PR?
Thanks.

**Comment by darklow** [comment]
Just realised, user is loggout out only when setting password for first time, for example if only social account is present.

**Comment by aaugustin** [comment]
I could, but I'd like to hear back from a maintainer about their preferred approach first.

(It isn't hard to copy-paste the diff above either.)

**Comment by darklow** [comment]
@aaugustin Same code is applied to `PasswordChangeView` i can't see any reason why it shouldn't be applied to `PasswordSetView` as well.

**Comment by pennersr** [comment]
@aaugustin Agreed -- this should be rectified. It is really not worthwhile introducing a setting for this. It does deserve a note in the `changelog.rst` so that people become aware this behavior was changed.
Minor nitpick about the proposed code change -- I would prefer to move this logic in one shared method to keep things DRY...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1262
