### ISSUE TITLE
Custom response in registration

### ISSUE THREAD

**Issue by mhipo1364** [pennersr/django-allauth#1263]
Hi guys 

I want to login after signup, and return `jwt` token in registration response, I've already override `SignupForm` to get custom data from user, how can I add token in response ?

**Comment by pennersr** [comment]
Please only file an issue when there is an issue in allauth, not for support related questions like this. 

Having said that, it appears you want to return custom JSON from the login view, perhaps the best way forward then is to override the adapter `login` method and raise an `ImmediateHttpResponse` there containing your JSON response.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1263
