### ISSUE TITLE
Get E-Mail address from LinkedIn Profile

### ISSUE THREAD

**Issue by frbry** [pennersr/django-allauth#127]
Hello,

My e-mail address is not saved when I try to login with LinkedIn. My providers setting's as below. Am I missing something?

SOCIALACCOUNT_PROVIDERS = {
    'facebook': {
        'SCOPE': ['email', 'user_about_me'],
        'METHOD': 'js_sdk',
    },
    'linkedin': {
        'SCOPE': ['r_basicprofile', 'r_emailaddress', ]
    }
}

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/127
