### ISSUE TITLE
Automatically generate new password and email it on password reset

### ISSUE THREAD

**Issue by jordanjambazov** [pennersr/django-allauth#1270]
In some cases it might be useful to automatically generate the new password on reset, and email it.
It seems to me that django-allauth currently does not support such workflow.
Do you think that would be a nice feature for the project to have? What is the correct way to implement such workflow?

**Comment by pennersr** [comment]
Sending passwords by mail is not secure, I wouldn't want to introduce complexity in allauth to support that scenario. Having said that, I do think you can easily create this yourself by overriding some views.. 

http://security.stackexchange.com/questions/17979/is-sending-password-to-user-email-secure

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1270
