### ISSUE TITLE
Variable login_url in PasswordResetFromKeyDoneView()

### ISSUE THREAD

**Issue by avorio** [pennersr/django-allauth#1271]
Could we add a context variable `login_url` to `PasswordResetFromKeyDoneView()`, the same way it is available in `SignupView()`? I'd like to display the login link after successfully changing a password. Otherwise the user is left in a dead end.

**Comment by pennersr** [comment]
Given that there is typically no ?next= construct for the password reset, the login_url is actually nothing special. Just `<a href="{% url 'account_login' %}">` would do.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1271
