### ISSUE TITLE
extra_data defaults to a string

### ISSUE THREAD

**Issue by agriffis** [pennersr/django-allauth#1272]
If I don't intentionally overwrite `account.extra_data` then it ends up being a string:
```
>>> account = SocialAccount(user=User.objects.first())
>>> account.extra_data
'{}'
>>> type(account.extra_data)
<type 'str'>
```

This appears to be a result of the default value setting:
```
@python_2_unicode_compatible
class SocialAccount(models.Model):
    # ...snip...
    extra_data = JSONField(verbose_name=_('extra data'), default='{}')
```

It seems like I get the desired behavior like this:
```
@python_2_unicode_compatible
class SocialAccount(models.Model):
    # ...snip...
    extra_data = JSONField(verbose_name=_('extra data'), default=dict)
```

I think using a string as default used to work properly, but it probably broke with some of the more recent (within the past year) changes to `JSONField`.  Any reason not to update the default now?

I'm using Python 2.7.6 with Django 1.8.8 and django-allauth ~0.23

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1272
