### ISSUE TITLE
OpenID Connect?

### ISSUE THREAD

**Issue by protoforge** [pennersr/django-allauth#1278]
While I realize OAuth2 can be used with a OIDC provider, are there any plans for native support of the specification?

**Comment by jfkw** [comment]
Related to #676

**Comment by pennersr** [comment]
I realize I am really lagging behind on this, but my remark over at the referenced issue still stands... yes, there are plans, but I need to find time and scramble myself to dig into the matter.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1278
