### ISSUE TITLE
Facebook js_sdk fail with apostrophe in URL

### ISSUE THREAD

**Issue by agriffis** [pennersr/django-allauth#1279]
This causes a JS syntax error:

```django
{% provider_login_url "facebook" method="js_sdk" next="/foo?msg=I%27m+broken" %}
```

The problem is that the output lands in an HTML attribute, and the browser decodes it before passing it to JavaScript. The `%27` becomes a single quote which breaks the JS. The existing code calls `encodejs` but additionally needs to call `urlquote`.

I have a working fix, will submit a PR in a minute.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1279
