### ISSUE TITLE
My settings are not read by django-allauth

### ISSUE THREAD

**Issue by frbry** [pennersr/django-allauth#128]
I realize that this may be not directly related with django-allauth but I wanted to ask anyway.

I put the below line in my_project/settings.py, but it seems they don't affect anything. I have django-allauth as a directory in my project, so it's not installed via pip or easy_install. I tried some debug printings confirmed that the settings doesn't override the app defaults.

ACCOUNT_UNIQUE_EMAIL = False

I run my code with runserver command. Do you have any ideas?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/128
