### ISSUE TITLE
Queries made by allauth

### ISSUE THREAD

**Issue by wasabigeek** [pennersr/django-allauth#1282]
Hi,

When checking the SQL queries made in Django Debug Toolbar, I see two duplicate queries from allauth. Is this expected?

Details in attached image:
![capture](https://cloud.githubusercontent.com/assets/4256705/12896440/fd599bfc-cedc-11e5-8acc-1f987d46c4d5.PNG)

**Comment by wasabigeek** [comment]
Awesome! Is this already packaged? I couldn't find it with pip.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1282
