### ISSUE TITLE
Social-based logins don't expire

### ISSUE THREAD

**Issue by aptwebapps** [pennersr/django-allauth#1283]
As noted [here](https://github.com/pennersr/django-allauth/issues/420#issuecomment-179311365), SocialToken.expires_at never seems to be read or used. They also don't get their session expiry set like regular logins so no matter what the provider's token says or the Allauth-specific settings say, they never expire.

**Comment by aptwebapps** [comment]
I'm now monkey patching base.Provider.sociallogin_from_response to honor the ACCOUNT_SESSION_COOKIE_AGE setting, but it could just as easily check the token's expires_at as well. I chose that point because it was not overridden by any of the subclasses. I monkey patched it instead of forking because I don't want to maintain a fork but would you be interested in a pull request?

**Comment by pennersr** [comment]
The `SocialToken.expires_at` is not related to the Django session. When you log in using a social provider you establish a Django session, that adheres to the regular Django session lifetime rules. The token is independent of that. The `expires_at` is optionally used for some providers that indicate when the token is no longer valid and needs to be refreshed.

**Comment by aptwebapps** [comment]
I was _sure_ my social auth was not expiring, but you're right of course. ;) While the expires_at thing was a red herring, it really does not appear to be read anywhere so I don't think it's being honored.

**Comment by pennersr** [comment]
True, allauth does not need the token for any other purpose than logging in. In case your own application would need to do anything with the token afterwards, such as posting status updates or whatever, then details like `expires_at` come into play. So you won't find allauth using that field...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1283
