### ISSUE TITLE
Feature request - adding USERNAME_REGEX to the configuration

### ISSUE THREAD

**Issue by erez-o** [pennersr/django-allauth#1284]
Changing the username allowed characters is pretty standard in Django. 
As far as I know, the current way to change the allowed characters, is to create a CustomAccountAdapter, and override the clean_username method.

Since the [clean_username](https://github.com/pennersr/django-allauth/blob/master/allauth/account/adapter.py#L220-L248) method is pretty thorough and uses other settings as well, you'd have to copy-paste all of it, and just change the USERNAME_REGEX, and the validation error message.

Copy-paste makes it difficult to track changes you might do in the future in clean_username. 

I think that adding USERNAME_REGEX, and USERNAME_VALIDATION_ERROR_MESSAGE to the configuration, will make the task of changing allowed characters easier.

**Comment by pennersr** [comment]
Hmm, I don't like to move validation errors into the settings. I would rather opt for something like this:

- give the adapter an `error_messages` property. Move the current message in there (`"invalid_username"`).

- move the USERNAME_REGEX into a property of the adapter as well.

**Comment by pennersr** [comment]
See 1e106b9

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1284
