### ISSUE TITLE
Confirmation email not sent when upgrading email_confirmation_subject.txt

### ISSUE THREAD

**Issue by ainslied** [pennersr/django-allauth#1285]
Hi,
I can t figure out why this doesn't work, we have a very strange behaviour here :

Running last version of django & allauth in debug mode (in windows 7, python 3.5)

Copy email_confirmation_subject.txt from site-packages\allauth\templates\account\email to your_app\blog\templates\account\email

If one replace "Please Confirm Your E-mail Address"
by "Veuillez valider votre adresse E-Mail"
-> no email is sent

But if one replace "Please Confirm Your E-mail Address"
by "Veuillez confirmer votre adresse E-Mail"
-> the email is sent

I can't believe it, and can't understand why the behaviour is different changing just one word...
Can you understand why?

**Comment by ainslied** [comment]
Ok, I have tested the sending with the console EmailBackend and it works..
It works as well with gmail (smtp.gmail.com) so it looks like it is linked to my smtp provider : SSL0.OVH.NET, which block for an unknown reason the message (very strange right?).

I have met a sending issue in the past with this provider related to malformed SMTP packet blocked, but in that case, we concluded that it was a bug in the django mail library ( ticket here : https://code.djangoproject.com/ticket/23063?cversion=1&cnum_hist=41 )

Thinking seriously to switch to another provider...

**Comment by ainslied** [comment]
You can close the issue I guess..

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1285
