### ISSUE TITLE
Enable request.is_secure() for ACCOUNT_DEFAULT_HTTP_PROTOCOL

### ISSUE THREAD

**Issue by danni** [pennersr/django-allauth#1288]
It would be good to have an option for ACCOUNT_DEFAULT_HTTP_PROTOCOL which used request.is_secure() to decide on a protocol. Propose making this the default, so if you have SSL redirection happening on your site, you don't make a http request, but that it still can produce http urls in dev.

**Comment by pennersr** [comment]
I am not sure I understand what you are actually proposing. Perhaps this is related to #1258

**Comment by danni** [comment]
Yes, that would also be fine.

**Comment by pennersr** [comment]
OK, then this is taken care of

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1288
