### ISSUE TITLE
Cant run example application: No module named reddit

### ISSUE THREAD

**Issue by overnine** [pennersr/django-allauth#1289]
Please view the error output when attempting to run the example: https://gist.github.com/overnine/bcc76cc7726c353a40b5

**Comment by patvdleer** [comment]
Reddit seems to be missing from the providers

**Comment by pennersr** [comment]
You are probably running 0.24.1.. reddit is in master only...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1289
