### ISSUE TITLE
ACCOUNT_ADAPTER import exception information

### ISSUE THREAD

**Issue by ubertrader** [pennersr/django-allauth#1290]
Hello, I've found a lack of debug information when trying to use custom AccountAdapter with typos or wrong paths in settings.py.

I've just copy-pasted wrong settings for ACCOUNT_ADAPTER = 'project.adapter.CustomAccountAdapter' and forgot it. And when I tried to access /accounts/login/, I've got weird "ImportError: No module named 'project'" (there is not 'import from project' in entire PYTHON_PATH :) ). It costs me about 2-3 hours to figure out this problem. This is my fault, but it would be nice for provide more informative error handling in cases like that.

Thanks.

**Comment by patvdleer** [comment]
If I'm not mistaken, this isn't AllAuth behavior but Django behavior.

**Comment by pennersr** [comment]
I am not sure what improvement you expect here... IMHO an import error is the proper hint in this case.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1290
