### ISSUE TITLE
404 after signing up

### ISSUE THREAD

**Issue by pythdasch** [pennersr/django-allauth#1291]
Hey everyone ! 

since 2 days on production I've a 404 when trying to signup with allauth.

I just upgraded of version to be compatible for django 1.9.2 and my production is in https.
before there was no problem, but now when I'm signing up => 404.

I've a basic configuration in production : 

`ACCOUNT_DEFAULT_HTTP_PROTOCOL = "https"

and in common settings : 
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

INSTALLED_APPS += (
'allauth',
'allauth.account',
'allauth.socialaccount',
'allauth.socialaccount.providers.facebook',
'allauth.socialaccount.providers.twitter',
)
SOCIALACCOUNT_PROVIDERS = \
{'facebook':
   {'SCOPE': ['email', 'public_profile', 'user_friends'],
    'AUTH_PARAMS': {'auth_type': 'reauthenticate'},
    'METHOD': 'oauth2',
    'VERIFIED_EMAIL': False,
    'VERSION': 'v2.3'}
}

ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_USERNAME_BLACKLIST = ['asshole']
ACCOUNT_USERNAME_MIN_LENGTH = 4

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 5,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'users.User'
LOGIN_REDIRECT_URL = '/citizen/~redirect/'
LOGIN_URL = 'account_login'`

Very basic. does someone had this issue before ?
It appears that the problem is when sending emails. But my setup for email is working well and I can't reproduce it in local.
Thanks in advance

**Comment by pythdasch** [comment]
ok so sorry for this issue, it was a misconfiguration in the email. It's still strange, that it raises an 404 error and not a 500 error.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1291
