### ISSUE TITLE
AnonymousUser after login with twitter

### ISSUE THREAD

**Issue by HosniD** [pennersr/django-allauth#1292]
django: 1.9/ python 3.4  and latest version of django-allauth

After Loging with twitter and redirection to /accounts/profile/ : the user stays unauthenticated and is considered as AnonymousUser, hence no access neither to the socialaccount_set attribute nor to the django-allauth "account" template tags.
i checked if the log in happens with the @receiver(user_logged_in), and it seems to happen and the user is set properly. Any insights on this problem?  a similar question on [stackoverflow](http://stackoverflow.com/questions/35108746/request-user-is-authenticated-stays-false-after-django-allauth-social-login)

**P.S. Twitter is the only authentication solution i will be providing**

in the settings.py 
i declared SITE_ID to 1, changed the SITE_ID to 127.0.0.1:8000
my INSTALLED_APPS are the following
```

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.twitter',
    'django.contrib.admindocs',
    'main'
]
```

and my context processors look like so: 
```

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
            ],
        },
    },
]
```
and here are my middleware classes: 

```

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
```

the routing in project/urls.py:
```
from django.views.generic.base import TemplateView
...
	url(r'^accounts/profile/', TemplateView.as_view(template_name="profile.html")),
...
```
A duplicate of this issue will be posted on SO, will edit with the link.

**Comment by pennersr** [comment]
I am sorry, I am not sure what the problem is but it is most like project specific. I am closing the issue... if you learn more, or find a concrete issue in allauth, feel free to provide feedback and/or reopen.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1292
