### ISSUE TITLE
Link to revoke social accounts

### ISSUE THREAD

**Issue by tanzaho** [pennersr/django-allauth#1293]
I did not get, from the documentation, whether it is possible to revoke social tokens/accounts or not. If it's possible, what is the template tag/url that should be used ?

For the connection I am using '/accounts/twitter/login/?process=connect'

**Comment by tanzaho** [comment]
So, I've found the page [rootUrl]/accounts/social/connections/ and see the current working connections.
It's a form and not a url as I expected. When I click on remove, the page just get refreshed, but the connection is not removed.

**Comment by pennersr** [comment]
It's indeed a form. Just like a list of email addresses that control access to the account, there is a list of social accouts that do the same, albeit not by email but by an external provider. In that sense, having a list of email addresses and a list of social accounts to manage via a form/view is consistent.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1293
