### ISSUE TITLE
TemplateSyntaxError when not using 'allauth.socialaccount'

### ISSUE THREAD

**Issue by rapilabs** [pennersr/django-allauth#1294]
Using allauth 0.24.1 with Django 1.9.2, if I only want to use `allauth.account` and not `allauth.socialaccount`, then I receive a `TemplateSyntaxError` when viewing `/accounts/login`:

```
TemplateSyntaxError at /accounts/login/
'socialaccount' is not a registered tag library. Must be one of:
account
account_tags
admin_list
admin_modify
admin_static
admin_urls
cache
future
i18n
l10n
log
rest_framework
static
staticfiles
tz
```

**Comment by fproldan** [comment]
+1

**Comment by aaugustin** [comment]
This could be related to #459.

**Comment by pennersr** [comment]
Dupe of #459 indeed ..

**Comment by akhiewu** [comment]
raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'socialaccount' is not a registered tag library. Must be one of:
account
admin_list
admin_modify
admin_urls
cache
custom_tags
debugger_tags
highlighting
i18n
indent_text
l10n
log
rest_framework
static
syntax_color
tz
widget_tweaks
widont

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1294
