### ISSUE TITLE
Pass request (and/or SocialApp instance) to extract methods (Different user instances per social app with same provider)

### ISSUE THREAD

**Issue by thenewguy** [pennersr/django-allauth#1297]
I am working on a project that needs to use a single provider that returns different user instances based on the SocialApp for permissions handling.

I've been working through the code and it looks like the simplest way to make this happen is for the `Provider.extract_uid` method to return a combination of the SocialApp id and the uid from the provider.  Something like `"{};{}".format(app.id, uid)`

I narrowed in on `Provider.extract_uid()` because `Provider.sociallogin_from_response()` appears to be the only [method that calls it and it has access to the request](https://github.com/pennersr/django-allauth/blob/5b1cbf485fa363ccb87513545e3b98f3c3bd81fa/allauth/socialaccount/providers/base.py#L72).

Is there any reason that the extract methods cannot be passed the request object (and/or SocialApp instance) in addition to the response data?  It seems like this would be a common benefit for multi-tenant sites.

It can be added in a backwards compatible way along with a depreciation warning if wanted.

**Comment by pennersr** [comment]
I would rather opt for providing the request to the constructor of the `Provider class, e.g.:

```
class Provider(object):
    def __init__(self, request=None):
        self.request = request
```

**Comment by thenewguy** [comment]
@pennersr It has been a long time since I've looked at this but that would work just as well and generally be more useful

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1297
