### ISSUE TITLE
fb_login is not defined

### ISSUE THREAD

**Issue by philippeluickx** [pennersr/django-allauth#130]
First of all, thanks for a great package!
I started the implementation to my app, but get one error when using the FB js_sdk option (when selection the link, with firebug):

```
ReferenceError: FB_login is not defined
```

Seems like this is a known issue and solutions exist:
http://stackoverflow.com/questions/5331165/fb-is-not-defined-problem
http://stackoverflow.com/questions/9092801/fb-is-not-defined-in-facebook-login

Or I am doing something horribly wrong and all help is appreciated!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/130
