### ISSUE TITLE
Question: ACCOUNT_USER_DISPLAY

### ISSUE THREAD

**Issue by philippeluickx** [pennersr/django-allauth#131]
Could you please ellaborate on the ACCOUNT_USER_DISPLAY setting?

I would like to have it return the full name of a user (get_full_name), but first_name would be as good.  I'm having troubles in defining the setting: what should I put there?

Thanks!

**Comment by oguzhancelikarslan** [comment]
ACCOUNT_USER_DISPLAY = 'public_api.utility.user_display'
`
def user_display(user):
    return user.first_name `

I tried that but it doesn't work. 
Also i tried  adding ACCOUNT_USER_DISPLAY = lambda user: user.get_full_name().

Again the same problem when it creates a mail confirmation template. It automatically makes it a username.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/131
