### ISSUE TITLE
facebook provider.py assumes "username" field is present

### ISSUE THREAD

**Issue by chriscdn** [pennersr/django-allauth#1311]
I'm new to all of this, so apologies if I'm missing something.  The [provider.py](https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/providers/facebook/provider.py) for facebook has the following for `extract_common_fields()`:

    def extract_common_fields(self, data):
        return dict(email=data.get('email'),
                    username=data.get('username'),
                    first_name=data.get('first_name'),
                    last_name=data.get('last_name'),
                    name=data.get('name'))
                    
As far as I can tell `username` is [not listed as valid return value from facebook](https://developers.facebook.com/docs/graph-api/reference/user).  The side-effect of this is blank usernames when automatically creating an account on login.

**Comment by pennersr** [comment]
User names won't be blank. The fields extracted here are used as a hint, and allauth will always generate its own unique username, derived from this username, if available.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1311
