### ISSUE TITLE
Auto-login after registration does not work with a custom Authentication backend

### ISSUE THREAD

**Issue by skrivanos** [pennersr/django-allauth#1315]
If for any reason you need to override the default Authentication Backend, this will stop working. This is due to the backend path being hard coded in the default adapter:

https://github.com/pennersr/django-allauth/blob/master/allauth/account/adapter.py#L310

I'm not sure if this is documented behaviour or not (haven't found anything about it at least), but it causes quite a headache. Not sure how to solve it either, but figured I should post an issue in case more people run into this.

A workaround is to create your own authentication adapter and override the login method.

**Comment by pennersr** [comment]
See 0da4ebf -- this removes the hardcodedness, though it is all still a bit hacky. Hopefully that solves your issue.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1315
