### ISSUE TITLE
Reset password allowed for inactive users

### ISSUE THREAD

**Issue by JulieGoldberg** [pennersr/django-allauth#1317]
A user whose account has been deactivated can use the reset password form to log in.  They have to update their password every time, but they can get in that way.

Presumably filter_users_by_email() should exclude inactive users.  Or it might need to be an additional filter in ResetPasswordForm.clean_email() depending on how widespread filter_users_by_email() is used.  I'm on an older version, but the current version doesn't fix it.

**Comment by akarambir** [comment]
+1 on issue. We had to patch an api where we were using all-auth.

**Comment by peckjon** [comment]
+1 as well... this is a not-uncommon bug in auth systems, and one that definitely needs fixing!

**Comment by JulieGoldberg** [comment]
I don't think the perform login always checks if the user is active.  Maybe
it depends on the django version?  I can and do impersonate inactive users.

However that works, the check comes too late.

I don't believe that an inactive user should be able to request the
password reset link in the first place.

Sent from my iPhone

On Mar 10, 2016, at 1:50 PM, Raymond Penners <notifications@github.com>
wrote:

Could you elaborate a bit. If I am not mistaken, the password reset comes
in 2 flavors. One, where after completing the password reset the user has
to follow the regular login procedure. In that case, the perform_login
method will check user.is_active and not allow the user to log in. The
other case is where login-on-password-reset is turned on, but even in that
case the code path follows perform_login which checks user.is_active. Could
you let me know what scenario you are following to reproduce the issue?

—
Reply to this email directly or view it on GitHub
<https://github.com/pennersr/django-allauth/issues/1317#issuecomment-195066189>
.

**Comment by pennersr** [comment]
allauth always routes through its own `perform_login`:

https://github.com/pennersr/django-allauth/blob/master/allauth/account/utils.py#L130

If you are impersonating users.. you are probably doing some other user session magic beyond allauth scope?

**Comment by JulieGoldberg** [comment]
We use django-impersonate package for impersonating users.  It was just an example.

My point still stands that inactive users shouldn't even be able to get a lost password link in the first place.

**Comment by pennersr** [comment]
That is just polish, and even debatable as it leaks even more information about a user (see #1307) ...  but I was a bit surprised to see the +1s when there is no issue in allauth:

- "...can use the reset password form to log in. They have to update their password every time, but they can get in that way." -- not true, at least, not true as long as allauth is in control. From a django-impersonate point of view, you can even argue that it is a feature to be able to impersonate inactive users.

- @akarambir "We had to patch an api where we were using all-auth" --  I don't think allauth was the cause here, care to elaborate?

- @peckjon "... needs fixing!" -- please point me to an issue in allauth

**Comment by pennersr** [comment]
(feel free to reopen if you do find an issue)

**Comment by peckjon** [comment]
The generally accepted pattern for this problem, in order to avoid data leakage, is to allow the reset form to be submitted, but then to email the user a message with no link, stating that their account is inactive.

**Comment by akarambir** [comment]
@pennersr We were using all-auth's forms in our drf serializers. So we had to add a check so that inactive users do not receive email for password reset.

I agree with @peckjon here. We should accept the form, but not send the email.

**Comment by pennersr** [comment]
@akarambir -- But, @peckjon is suggesting that a mail is sent...

Whichever way it is, can we all at least agree that there is no security leak nor a grave bug in allauth that needs to be fixed? The way I see it we can choose between:

1) Do nothing, keep things as is. We send out a mail, so what?

2) Report back that the account is inactive. Downside is that this leaks information, namely that the user a) has an account and b) it is inactive. I don't like leaking more unless there is a good reason.

3) Do send a mail, but change the content of that mail: "Your account is inactive, you either spammed or did not pay your invoice ... and so on". This is is something you can do today.. simply `{% if user.is_active %}` in the password reset mail template.

**Comment by JulieGoldberg** [comment]
It's conceivable that we we have some configuration flag set wrong in
allauth, but I discovered this bug, because an inactive user used this path
to login.  We are on an old version, but I tried upgrading and it didn't
solve the bug immediately, so I didn't pursue that path further.  If this
is truly fixed, we will upgrade to a version with the fix.

As a quick patch, I inherited from the form that receives the email request
and overridden clean_email to add an additional is_active validation check
to the user.  I don't plan to keep my patch in my codebase once you fix it.
It won't work the same in the latest version.

I tend to think an inactive user should be unable to get the email.  If
they can, a switch as you suggest should definitely be in the default
template.  I may actually change our approach to that.

That said, if their account was inactivated after requesting the link but
before using it, they should be unable to use the link.

Sent from my iPhone

On Mar 10, 2016, at 11:18 PM, Raymond Penners <notifications@github.com>
wrote:

@akarambir <https://github.com/akarambir> -- But, @peckjon
<https://github.com/peckjon> is suggesting that a mail is sent...

Whichever way it is, can we all at least agree that there is no security
leak nor a grave bug in allauth that needs to be fixed? The way I see it we
can choose between:

1) Do nothing, keep things as is. We send out a mail, so what?

2) Report back that the account is inactive. Downside is that this leaks
information, namely that the user a) has an account and b) it is inactive.
I don't like leaking more unless there is a good reason.

3) Do send a mail, but change the content of that mail: "Your account is
inactive, you either spammed or did not pay your invoice ... and so on".
This is is something you can do today.. simply {% if user.is_active %} in
the password reset mail template.

—
Reply to this email directly or view it on GitHub
<https://github.com/pennersr/django-allauth/issues/1317#issuecomment-195229815>
.

**Comment by pennersr** [comment]
As stated, all allauth logins are channeled through `perform_login`, which checks `is_active`. So there is nothing to fix here.

As for sending the mail, see https://github.com/pennersr/django-allauth/issues/1317#issuecomment-195229815 -- I don't like 2), and 1) and 3) are already available.

**Comment by JulieGoldberg** [comment]
Have you actually tested the codebase?  Because that check didn’t stop my user from logging in.

**Comment by pennersr** [comment]
If you have a reproducible scenario, that would be of great help.

**Comment by JulieGoldberg** [comment]
Unfortunately, I'm about to leave on a two week vacation, so I can't spend much time on this right now.  I've attached our requirements.txt file, so you can see all the modules we're using.  I know we need to upgrade our django version (working on it), and we're way behind on allauth.  But when I tried simply upgrading allauth to the latest version, it did not fix the problem.  It just made the bug more difficult to patch.  
[requirements.txt](https://github.com/pennersr/django-allauth/files/170080/requirements.txt)

**Comment by pennersr** [comment]
Ouch, 0.12.0 ... I just did a quick checkout of that version to see how things looked back then, and I can indeed confirm that is_active was handled differently back then.  Starting from fb497499cc238dd6cb08e323833e121541439b23 the is_active checking has been centralized in one place. From that moment onwards, things should be safe... except for perhaps things other apps (e.g. django-impersonate) are doing...

**Comment by JulieGoldberg** [comment]
I definitely did try upgrading and didn’t see the problem fixed.  I will need to upgrade allauth as part of my upgrade to django 1.7, so I’ll try again.  Maybe I didn’t do it quite right originally.

**Comment by JulieGoldberg** [comment]
I did just upgrade allauth, and the problem remains, at least with django-impersonate 0.9 installed as well.  I've solved it with your suggested change -- adding a check for user.is_active in my password_reset_key_message template.  If the user is not active, I tell them to contact their site admin.  I suggest you put a generic version of such a message in the default password_reset_key_message template.

**Comment by pennersr** [comment]
@JulieGoldberg I really do not think the problem is with allauth, but don't let that stop you from trying to come up with a reproducible scenario using just allauth (no impersonate/whatever). Please let me know if anything comes up...

**Comment by JulieGoldberg** [comment]
If I have a deactivated account, I shouldn't be able to get a reset password link.  That's entirely in allauth and solely in allauth.  It's possible that without impersonation and/or on later versions of django (we're still on 1.6) that lost password may not work for logging in.  Unfortunately, I don't have the time to test that.  But the ability to get the reset password link for a deactivated user is inherently problematic.

**Comment by pennersr** [comment]
I outlined the "issue" with the password reset link here: https://github.com/pennersr/django-allauth/issues/1317#issuecomment-195229815

With "I really do not think the problem is with allauth" above I was referring to an actual security issue, where inactive accounts are able to login. If that comes up using a standard allauth installation, something is definitely wrong...

**Comment by pennersr** [comment]
"But the ability to get the reset password link for a deactivated user is inherently problematic."

I am still wondering why you put it like this. As far as allauth is concerned, there is really no problem here...

**Comment by JulieGoldberg** [comment]
It's problematic if it allows folks with an unexpected setup to log in
after they've been deactivated

Sent from my iPhone

On Apr 20, 2016, at 2:40 PM, Raymond Penners <notifications@github.com>
wrote:

"But the ability to get the reset password link for a deactivated user is
inherently problematic."

I am still wondering why you put it like this. As far as allauth is
concerned, there is really no problem here...

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/pennersr/django-allauth/issues/1317#issuecomment-212618270>

**Comment by peckjon** [comment]
@pennersr are you implying that a deactivated account *should* be able to get a "reset password" link?  Because that's definitely nonstandard behaviour.

**Comment by pennersr** [comment]
I am implying that getting a reset password link is rather a non issue, it is definitely not problematic in allauth, it does not cause a security issue. In order to address this issue, one of 1)-3) would need to be chosen (see https://github.com/pennersr/django-allauth/issues/1317#issuecomment-195229815). Currently it is 1), 2) is a no-go, and 3) is rather project specific wording wise. 

The actual issue you are bumping into arises from allauth being used in a broader scope with other apps joining the party. That security issue, if any, should be filed against the other app(s).

**Comment by pennersr** [comment]
One more thing: if you do decide to patch allauth to stop sending out the password reset mail, do note that this does not fully protect you against the security issue when following this scenario:

1. User requests password reset, keeps link around
2. User start misbehaving and gets deactivated
3. User clicks password reset link he received before the incident

**Comment by peckjon** [comment]
@pennersr don't get me started on the insecurity of reusable password-reset links...

**Comment by peckjon** [comment]
http://stackoverflow.com/a/16018373

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1317
