### ISSUE TITLE
Google login email not obtaining while using django allauth.All other datas even profile picture is getting

### ISSUE THREAD

**Issue by anoopms1988** [pennersr/django-allauth#1320]

**Comment by harshilpatel** [comment]
Did you add options for SOCIALACCOUNT_PROVIDERS in settings.py ?

**Comment by jfmatth** [comment]
I am having the same issue, and YES did add settings for Google to the SOCIALACCOUNT_PROVIDERS dict.

```
# Dictionary containing provider specific settings.
SOCIALACCOUNT_PROVIDERS = { 'google':
        { 'SCOPE': ['profile', 'email'],
          'AUTH_PARAMS': { 'access_type': 'online' } }
}
```

unfortunately, i'm still not getting my email address back from Google :(

**Comment by jfmatth** [comment]
Maybe i need to remove my app as a connected one, but can't seem to find that :)

**Comment by pennersr** [comment]
Works in production on quite a few other sites. As far as I can tell there is no issue in allauth that can be fixed here, I'll have to close this.

**Comment by jfmatth** [comment]
Can you post some more examples on using Google specifically?  In reading through other provider libraries not just yours, google seems to require more parameters.

thanks,

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1320
