### ISSUE TITLE
Social Network Login Failure after starting to use SSL

### ISSUE THREAD

**Issue by bkoatz** [pennersr/django-allauth#1323]
Hi all

My login process was working until we started using SSL. In the [providers](http://django-allauth.readthedocs.org/en/latest/providers.html) section of your docs, y'all say that urls of the type 'http://example.com/accounts/twitter/login/callback/' work, but would something break once we start using https?

I change the Site object in my DB (connected to my Soundcloud SocialApp) to use https, and my redirect uris, is there anything else i need to do?

Thanks

Ben

**Comment by pennersr** [comment]
Over at Tw/FB/G where you are configuring the callback URLs you will have to set up things accordingly, so if you switch to https, edit the configuration there as well...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1323
