### ISSUE TITLE
context_instance argument of render_to_string  warning

### ISSUE THREAD

**Issue by b3h3rkz** [pennersr/django-allauth#1324]
` RemovedInDjango110Warning: The context_instance argument of render_to_string is deprecated.
  RequestContext(request))
`

should I be worried about this for now? Using on Django1.9

**Comment by pennersr** [comment]
Are you still seeing this in current master?

**Comment by pennersr** [comment]
Should be fixed.. see allauth.compat

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1324
