### ISSUE TITLE
Keeping custom signup form class and importing allauth built in forms in same apps/forms.py causing import errors.

### ISSUE THREAD

**Issue by contactr2m** [pennersr/django-allauth#1325]
http://stackoverflow.com/questions/35945784/keeping-custom-sign-up-class-and-importing-allauth-forms-in-same-forms-py-file-c

Is there any dependency on how to keep your allauth custom forms/classes ??

**Comment by pennersr** [comment]
Closing, this has been answered on SO...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1325
