### ISSUE TITLE
Logout status & CSRF error after signup action

### ISSUE THREAD

**Issue by fonar** [pennersr/django-allauth#1329]
Steps:

1. goto http://site/accounts/signup/
2. fill with existent email, submit and get validation error
3. fill with new email and get successful signup and logged in
4. press 'Back' button in browser

You will see unlogged in page for signup and if you press F5 you will get CSRF error

This is not happening if we omit point 2.

UPDATE: The same is with login!

**Comment by pennersr** [comment]
This is not an allauth issue, see:

https://docs.djangoproject.com/en/1.10/ref/csrf/#why-might-a-user-encounter-a-csrf-validation-failure-after-logging-in

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1329
