### ISSUE TITLE
Expensive iexact clause on username lookups

### ISSUE THREAD

**Issue by megatron-me-uk** [pennersr/django-allauth#1331]
Here, it is stated that usernames are case insensitive: https://github.com/pennersr/django-allauth/blob/7b00fdc596e6f48409114262e236b98db0464cf4/allauth/account/auth_backends.py#L36
However usernames are always created as lowercase: https://github.com/pennersr/django-allauth/blob/599dfa69b8095c6c8d5e5cc630d4bb4e58454c36/allauth/utils.py#L35
Also see this issue raised on django where it is stated that usernames should be considered case-sensitive: https://code.djangoproject.com/ticket/25399
This issue leads to many queries on our database server that look like: `select * from auth_user where UPPER(username)=UPPER('user1234');`. django creates a unique index on `username` but this is not used for a query that uses the `UPPER` function. This leads to many expensive full table scans on the auth_user table.
As a temporary work-around I have added an index as: `create index my_hacky_index on auth_user (UPPER(username));` however this is not ideal. Presumably this could be improved by calling `username.lower()` at: https://github.com/pennersr/django-allauth/blob/599dfa69b8095c6c8d5e5cc630d4bb4e58454c36/allauth/account/adapter.py#L258 else allowing usernames to be case-insensitive in line with other uses of the django auth_user framework.

**Comment by ducheneaut** [comment]
+1 on this. My app is hosted at Heroku and my user base is now large enough that the full table scans can cause the OAUth2 callback request to time out (Heroku's router will terminate a request if it takes longer than 30 seconds to complete - see https://devcenter.heroku.com/articles/request-timeout , there is unfortunately nothing I can configure server-side to extend it).

**Comment by yguarata** [comment]
+1 on this.

as our users database increased so much, allauth was consuming most of the time of our CPUs trying to populate unique usernames. 

**Workaround:** As username is not required at all in our application, we simply provided an adapter which extends from **DefaultAccountAdapter** and override the method **populate_username**, populating the username with the user email.

maybe allauth could provide some setting to change the populate_username behavior.

thanks for the great django app.

**Comment by pennersr** [comment]
I am still pondering on how to approach this. If we automatically lowercase the username before storing it, we lose information. For  example, on Twitter, user names are case insensitive, but it preserves the original casing for display purposes (@TheOriginalName). Tackling that would require us to store both the lower cased and the original user name, but that is quite hacky... making the manually added index as quite a clean solution.  So I am afraid auto lower casing of the username should have to be an option enabled via the settings. Thoughts?

**Comment by MikiSoft** [comment]
> So I am afraid auto lower casing of the username should have to be an option enabled via the settings. Thoughts?
Agree @pennersr, there should be an option for lowercase username. Or anything which would solve this issue.

**Comment by pennersr** [comment]
See: 7538d907aad3eabb749ed3cd74dd8fea6e46a473

**Comment by pennersr** [comment]
Note: I've switched off case preserving by default, intentionally breaking backwards compatibiity...

**Comment by pennersr** [comment]
Strike the above... I am reconsidering this. There are a lot of MySQL deployments that are mostly not affected by this issue at all, because of case insensitive matching by default. Reverting back to case preserving by default ...

**Comment by MikiSoft** [comment]
Maybe you should include that option which defaults to `True` instead of `False`?

**Comment by pennersr** [comment]
It does default to True now...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1331
