### ISSUE TITLE
Limiting number of additional email addresses tied to a user

### ISSUE THREAD

**Issue by zkwp** [pennersr/django-allauth#1335]
Should there be a configuration setting to limit the amount of email addresses a user can add in /accounts/email/? Something like **ACCOUNT_EMAIL_ADDRESSES_LIMIT(=10)**?

The reason I ask is mainly because of bots, I also think it'd be very rare for a project where users would need or want more than 10 email addresses. 

Or is this kinda edge-case and something we should implement individually on our own projects?

**Comment by zkwp** [comment]
On second thought this alone wouldn't do much since email addresses can be removed > readded.

I'll just do something custom for my project. Closing.

**Comment by pennersr** [comment]
I don't see how adding limits on allauth are going to get you anywhere. Typically, there are all sorts of endpoints in your site that need to be protected as well. I think you are better off configuring some per IP  HTTP POST rate limitting configuration in your web server.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1335
