### ISSUE TITLE
Django110 Deprecation Warning for SubfieldBase

### ISSUE THREAD

**Issue by drernie** [pennersr/django-allauth#1338]
The social account module creates a deprecation warning for six due to use of models.SubfieldBase:
```
RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead

../lib/python2.7/site-packages/allauth/socialaccount/fields.py:    JSONFieldBase = six.with_metaclass(models.SubfieldBase, models.TextField)
```
cf. https://github.com/django-extensions/django-extensions/pull/783

**Comment by kjg531** [comment]
Please fix this!

**Comment by pennersr** [comment]
When are you seeing this warning? That particular line of code should not trigger with recent Django versions:

```
if django.VERSION < (1, 8):
    JSONFieldBase = six.with_metaclass(models.SubfieldBase, models.TextField)
else:
    JSONFieldBase = models.TextField
```

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1338
