### ISSUE TITLE
SocialAccount custom signupform not running signup method

### ISSUE THREAD

**Issue by dwasyl** [pennersr/django-allauth#1344]
This seems to be a bit of a processing/flow bug that I can't track down. Or maybe there's a good reason for the behaviour. The only thing I can track down is that there might be some sort of circular logic with inheriting from Allauth's forms to make the custom form (which is then inherited by custom form code again).

I have a new social account sign up form defined that inherits from allauth.socialaccount.forms.SignupForm which works great. The additional fields appear, the user's information (username/password) from the sign up form are saved. The intent being that all of the extra fields are to be saved in a UserProfile instance. However, it seems that when saving the form the new signup form's signup() method is never called so the extra information is never saved.

**Comment by MikiSoft** [comment]
I can confirm that it happens to the (default) account signup form too. I've set `ACCOUNT_SIGNUP_FORM_CLASS` in settings.py to point to my form and it really does by displaying all the fields in there, but the problem is when I try to submit it due to my custom extra fields - it always raises an error that first of them is blank.

**Comment by dwasyl** [comment]
Yes, I noticed the same thing when I extended the ModelForm class and specified my UserProfile as the base model. Whenever I'd try to save the new form, it would fail with the error that the user_id wasn't there for saving. It seemed like when Save saved the user account and called custom signup for some reason the user object didn't have an id.                                                                                                                                                                                                                                                                                                                                                                                                                   From: MikiSoftSent: Thursday, April 7, 2016 5:48 PMTo: pennersr/django-allauthReply To: pennersr/django-allauthCc: dwasylSubject: Re: [pennersr/django-allauth] SocialAccount custom signupform not running signup method (#1344)I can confirm that it happens to the (default) account signup form too. I've set ACCOUNT_SIGNUP_FORM_CLASS in settings.py to point to my form and it really does by displaying all the fields in there, but the problem is when I try to submit it due to my custom extra fields - it always raises an error that first of them is blank.

—You are receiving this because you authored the thread.Reply to this email directly or view it on GitHub

**Comment by MikiSoft** [comment]
Well, it appears that `DefaultAdapter` has to be sub-classed, like someone explained here: stackoverflow.com/questions/24536774/django-allauth-custom-user-generates-integrityerror-at-accounts-signup-custo#answer-24622274
But I still can't get it to work...

**Comment by pennersr** [comment]
See my answer to a similar issue over here: http://stackoverflow.com/questions/36015534/how-django-allauth-signal-adapter-flow-works/36021818#36021818

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1344
