### ISSUE TITLE
ACCOUNT_DEFAULT_HTTP_PROTOCOL needed

### ISSUE THREAD

**Issue by guettli** [pennersr/django-allauth#1350]
Why is the ACCOUNT_DEFAULT_HTTP_PROTOCOL setting needed?

Is there no default way in django to create mails in cron-jobs which contains links to the web application?

**Comment by pennersr** [comment]
Somewhere a choice needs to be made whether or not to use HTTPS for constructing links. When you have a `request` instance handy, you can derive the protocol from it... but what about when running outside a `request` context?

**Comment by guettli** [comment]
I get tears in my eyes if I see that the same things get implemented over and over again.

Why is this part left to programmers of reusable apps?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1350
