### ISSUE TITLE
django.core.context_processors is deprecated in favor of django.template.context_processors.   __import__(name)

### ISSUE THREAD

**Issue by eve1234** [pennersr/django-allauth#1351]
Hello,

I have the flooding error and my app would not work. Its a warning plus i have a feeling my static files ain't loading. Do I need to worry about this what is it about.

> TEMPLATES = [
>     {
>         "BACKEND": "django.template.backends.django.DjangoTemplates",
>         "DIRS": [
>             os.path.join(PROJECT_ROOT, "templates")
>         ],
>         "APP_DIRS": True,
>         "OPTIONS": {
>             "context_processors": [
> 
>                 "django.contrib.auth.context_processors.auth",
>                 "django.contrib.messages.context_processors.messages",
>                 "django.core.context_processors.debug",
>                 "django.core.context_processors.i18n",
>                 "django.core.context_processors.static",
>                 "django.core.context_processors.media",
>                 "django.core.context_processors.request",
>                 "django.core.context_processors.tz",
>                 "mezzanine.conf.context_processors.settings",
>                 "mezzanine.pages.context_processors.page",
>             ],
>             "builtins": [
>                 "mezzanine.template.loader_tags",
>             ],
>         },
>     },
> ]
> 
> 
> 
> if DJANGO_VERSION < (1, 9):
>     del TEMPLATES[0]["OPTIONS"]["builtins"]
> 
> TEMPLATE_DEBUG = DEBUG

I am going around google and trying to understand what the error is.

Is it the reason why my statics files of css and js not working?

Regards

**Comment by eve1234** [comment]
Please, help.  Thanks.

**Comment by emilioramirez** [comment]
I had the same problem, I'm using 0.22.5 (django 1.7) and reading the doc[1] I figure out that I need to remove `allauth.account.context_processors.account` and `allauth.socialaccount.context_processors.socialaccount` from `TEMPLATE_CONTEXT_PROCESSORS`, so the conf must be as follow:

    TEMPLATE_CONTEXT_PROCESSORS = (
        "django.core.context_processors.request",
        ...
      )

[1] http://django-allauth.readthedocs.io/en/latest/installation.html#django

**Comment by pennersr** [comment]
See above..

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1351
