### ISSUE TITLE
error message from socialaccount.providers.openid.tests?

### ISSUE THREAD

**Issue by birophilo** [pennersr/django-allauth#1353]
Hi, fairly new to this so apologies if this is a stupid point or already asked elsewhere etc., but when I install allauth and run 'manage.py test', it raises an error message. It originates in socialaccount.providers.openid.tests.py, and returns the error message "django.db.utils.OperationalError: no such table: socialaccount_openidstore" as if it's referring to a model that doesn't exist. Removing this test file removes the error. Does something need updating in this tests file?

I also asked the question on Stackoverflow: 
http://stackoverflow.com/questions/36633190/django-all-auth-testing-error-django-db-utils-operationalerror-no-such-table

PS. Thanks for maintaining this fantastic app!

**Comment by pennersr** [comment]
I suggest you run `test yourproject` -- there is little point in testing the whole of allauth or django while you are working on your own project. The reason this happens is that you did not add the openid provider to your INSTALLED_APPS, yet, you are running its tests.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1353
