### ISSUE TITLE
Feature request: DELETE instead of GET /logout/

### ISSUE THREAD

**Issue by MikiSoft** [pennersr/django-allauth#1356]
Explanation here: https://code.djangoproject.com/ticket/15619#comment:2

**Comment by kxxoling** [comment]
+1 We also use DELETE /user/session/ in Python China.

**Comment by pennersr** [comment]
The referenced ticket actually indicates DELETE is not an option, POST is. And, allauth already uses POST. See `ACCOUNT_LOGOUT_ON_GET`

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1356
