### ISSUE TITLE
Problem with password_reset_key_message.txt

### ISSUE THREAD

**Issue by jlariza** [pennersr/django-allauth#1359]
Hello,

I modified the template password_reset_key_message.txt to add custom message to my users. The problem is that the context variables "current_site" and "username" are not being returned by the view that it is in charge of sending the message so I can not shown in a proper way the site name and site domain. I hard coded this information, but it should not be working this way.

Thank you,

**Comment by pennersr** [comment]
Have a look at `ResetPasswordForm.save`. Here you'll

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1359
