### ISSUE TITLE
ImportError: No module named weixin when weixin provider is enabled

### ISSUE THREAD

**Issue by kxxoling** [pennersr/django-allauth#1364]
I looked up my installation directory, and found there's no weixin folder in providers folder, as well as tar.gz setup package downloaded from pypi.

Neither work when I tried to install it directly from github: ``pip install git+https://github.com/pennersr/django-allauth@master``.

But fixed when I download the repo and install it locally.

**Comment by Mindey** [comment]
+

**Comment by pennersr** [comment]
Weixin was merged on master, but there is no pypi release yet containing weixin.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1364
