### ISSUE TITLE
I want to use mobile number on login and forgot password

### ISSUE THREAD

**Issue by sanchig** [pennersr/django-allauth#1365]
I want to use Mobile Number instead of Username or Email. Now a days user want to use mobile number for login and forgot password (we are using SMS api so we are sending otp and then user can register and login. ex. paytm.com login. we need to set sms api settings in setting.py file). I have done this in my frontend but it is not at best. I am doing get Username using mobile number in backend and then pass it to login url. whatever it is not best practice. Can you please add this functionality to this django-allauth package. so other developer can use this too. Please give me suggestion if already implemented.

**Comment by pennersr** [comment]
For now, I won't be supporting this out of the box. Such a feature can easily grow out of hand, ideally you would want to store phone numbers, but also device IDs of users and such. You should be able to build this on top of allauth though.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1365
