### ISSUE TITLE
Misleading error message if using AUTH_PASSWORD_VALIDATORS

### ISSUE THREAD

**Issue by delgiudices** [pennersr/django-allauth#1366]
`django-allauth`'s password length checker is checking the length of the password by default 6  but i set my django length validator to 8. So if the password is less than 6 characters the form error message will be min length is 6 but if i put 7 characters form error message will be 8

**Comment by pennersr** [comment]
`ACCOUNT_PASSWORD_MIN_LENGTH` is deprecated, either it needs to be removed completely, or, we need to keep in order not to break backwards compatibility, but only use it when `AUTH_PASSWORD_VALIDATORS` is empty...

**Comment by pennersr** [comment]
Done (3558cf1a0a7bc62cfacdd499deb6f5b8b2ab1398)

**Comment by bitcity** [comment]
Django 1.8 does not support `AUTH_PASSWORD_VALIDATORS` and it's a long term release. Please don't completely remove `ACCOUNT_PASSWORD_MIN_LENGTH` so that it keeps on working as long as `AUTH_PASSWORD_VALIDATORS` is not being used.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1366
