### ISSUE TITLE
SocialApp matching query does not exist (vk, odnoklassniki)

### ISSUE THREAD

**Issue by kaldown** [pennersr/django-allauth#1369]
Once I configured `django-allauth` everything works well, so I move forward.
Recently found that I have an issue.
Checkout back again, and even fully drop-restore-migrate whole db won't take effect =(
running django on `127.0.0.1:8000`
in sites added `127.0.0.1:8000`
added socialapp- with right `client ID` and `secret key`, added site from `sites`
still doesn't works.
`SITE_ID = 2`
Just curious, it works before.
And what exactly `SITE_ID` is? Is it a URL of site from where I start authentication ?
I can't really understand what this mean `Add a Site for your domain, matching settings.SITE_ID (django.contrib.sites app).` What exact does it mean to add site to domain?

I have no idea, what happened, but now it works =\

**Comment by shanegibney** [comment]
This really helped me with issues you are having, 
https://youtu.be/1yqKNQ3ogKQ
Best of luck

**Comment by kaldown** [comment]
Thanks. I already `SELECT * FROM django_sites;` to understand what `SITE_ID`is :)

**Comment by JahanzebNawaz** [comment]
The reason we get this error SITE_ID = 1
# When "SocialApp matching query does not exist" occurs, this ID needs to be replaced.
SITE_ID = 1

**Comment by PainKKKiller** [comment]
> The reason we get this error SITE_ID = 1
> When "SocialApp matching query does not exist" occurs, this ID needs to be replaced.
> SITE_ID = 1

Replace for what? I have SITE_ID = 1, and I have this error too.

**Comment by doomedraven** [comment]
@PainKKKiller ensure that site_ID = 1 is correct in django admin sites as probably 1 is example.com, jsut saw video posted by  @shanegibney and that was my issue

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1369
