### ISSUE TITLE
Login/Sign up with FB. An error occured while attempting to login via your social network account.

### ISSUE THREAD

**Issue by Asinox** [pennersr/django-allauth#137]
I need some help with this, after move my website im getting this error:
An error occured while attempting to login via your social network account. 
trying to make sign up /login with FB
I must to say, im using the 0.8.2 version

The user creations is working and everything else (sending email, etc)

Any idea?

Thanks

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/137
