### ISSUE TITLE
Customize login.html template

### ISSUE THREAD

**Issue by shanegibney** [pennersr/django-allauth#1370]
Running Django (1.9.6) and django-allauth (0.25.2)
I cloned the django-allauth repo to ~/allauthDjango. Then I copied the example directory to a new directory 'example' in my home directory. 
cp -r example ~/
Created a virtualenv in ~/example
$ virtualenv .
$ source bin/activate
$ pip install -r requirements.txt
$ python manage.py migrate
$ python manage.py runserver
This gives a warning,

/home/pi/example/lib/python2.7/site-packages/django/template/utils.py:37: RemovedInDjango110Warning: You haven't defined a TEMPLATES setting. You must do so before upgrading to Django 1.10. Otherwise Django will be unable to load templates.
  "unable to load templates.", RemovedInDjango110Warning)

Otherwise this runs fine. Next I want to customize the login/logout/signup etc html files.But django is reading ~/example/lib/python2.7/site-packages/allauth/templates/account/login.html
and not  example/templates/bootstrap/allauth/account/login.html
Why is it reading the login.html file from the site-packages template and not from the above? How can I change it? I presume in settings.py, but don't know how to do this.

Many tutorials say to copy the files from site-packages to your project, but why when there is already a login.html file there? 

This does seem to be a problem many people are frustrated with, with this package. Are there any examples of how to do it?

Any help would be greatly appreciated.

Thanks

**Comment by pennersr** [comment]
Put this in your settings:

```
TEMPLATE_LOADERS = (
    'django.template.loaders.filesystem.Loader',
    'django.template.loaders.app_directories.Loader',
)

TEMPLATE_DIRS = (
    os.path.join(PROJECT_ROOT, 'some', 'where', 'templates'),
```

Then, copy the `account/login.html` to `some/where/templates/account/login.html`.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1370
