### ISSUE TITLE
Multiple migration files generated for social account

### ISSUE THREAD

**Issue by kishan3** [pennersr/django-allauth#1372]
Everytime I do python manage.py makemigrations 
A new migration is generated.

Migrations for 'socialaccount':
  0013_auto_20160513_1224.py:
    - Alter field provider on socialaccount
    - Alter field provider on socialapp

I am overriding view and serializers for my custom facebook social login.
I am using django 1.9

**Comment by getup8** [comment]
This was happening to me for awhile as well but has seemingly stopped.  If you're able, maybe try installing from scratch w/ a new DB and see if it happens.  I'd also upgrade to Django 1.9.7 if you haven't already, I remember reading there was a bug potentially related to this.

**Comment by kishan3** [comment]
Ok i uninstalled django-allauth and reinstalled and it has stopped seemingly.Thanks for the help man @getup8

**Comment by Akay7** [comment]
@kishan3 If everything okay you can close that issue

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1372
