### ISSUE TITLE
Recommendation - Add "site" field to SocialAccount model

### ISSUE THREAD

**Issue by apiljic** [pennersr/django-allauth#1374]
When using django-allauth for many sites, then once the user signs in and socialaccount instance is created, the information is not preserved at which site this took place.

My recommendation is to add a "site" field to SocialAccount model, where information is saved at which site the sign up occured.

**Comment by pennersr** [comment]
This is rather project specific. You might just as well use a many to many, to record at what sites (multiple) the account was used. You can easily create your own models for these things and hook into the allauth signals to record them.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1374
