### ISSUE TITLE
Nedd to add form error when usernam or password is wrong in login

### ISSUE THREAD

**Issue by kartikdanidhariya** [pennersr/django-allauth#1378]
hi,
i am using allauth in my django-cms
now i want to add error msg in login page when username or password is wrong .
how can i get that in alltuth

also not return any error when both password are different in registration screen
plz suggest me!!

**Comment by pennersr** [comment]
I am sorry, but this is an issue in your specific setup. allauth handles form errors properly, if they do not show up check your templates.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1378
