### ISSUE TITLE
KeyError: 'access_token' for Facebook login

### ISSUE THREAD

**Issue by ipalka** [pennersr/django-allauth#1382]
Started getting these intermittently on my site as of few days ago:
Using Django 1.6.

----------

File "/home/admin/django/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/home/admin/django/local/lib/python2.7/site-packages/allauth/socialaccount/providers/facebook/views.py", line 93, in login_by_token
access_token = resp['access_token']

KeyError: 'access_token'

**Comment by yarbelk** [comment]
@ipalka django 1.6 support was dropped; you should probably update to a newer django.

**Comment by ipalka** [comment]
Sure @yarbelk  that's true, but let's be certain that this is a bug specific to Django 1.6 before dismissing, because I've seen similar bugs reported for authentication via other social media channels.

**Comment by pennersr** [comment]
It's probably unrelated to Django 1.6.... but I have no clue why this is happening to you. I have not seen this issue in other projects, so I am going to have to close this. If you do find out more, feel free to report back and reopen...

**Comment by ipalka** [comment]
Thanks. I've seen similar bugs reported for other platforms supported by
django-allauth (i.e. Google), so I know it's not just me. If I get any more
insight into the issue I'll reopen.

**Comment by iMerica** [comment]
I'm seeing this in Django 1.9.7

```
Internal Server Error: /facebook/login/token/

KeyError at /facebook/login/token/
'access_token'
```

```
POST:
expires_in = '6796'
csrfmiddlewaretoken = '*********************************'
next = ''
access_token = '******************************'
process = 'login'
```

**Comment by enriquesoto** [comment]
Hi, same here 

![selection_839](https://user-images.githubusercontent.com/5711590/31312519-3927aaa2-ab8b-11e7-9633-3f4d9b1e0738.png)

![selection_840](https://user-images.githubusercontent.com/5711590/31312523-55834de6-ab8b-11e7-8698-da7e2b2b7484.png)

**Comment by benmurden** [comment]
I see this intermittently, too. The offending line appears to be here.

allauth/socialaccount/providers/facebook/views.py in login_by_token at line 104
```python
                       GRAPH_API_URL + '/oauth/access_token',
                        params={'grant_type': 'fb_exchange_token',
                                'client_id': app.client_id,
                                'client_secret': app.secret,
                                'fb_exchange_token': access_token}).json()
                    access_token = resp['access_token'] # Here's the problem
                    expires_in = resp.get('expires_in')
                    if expires_in:
                        expires_at = timezone.now() + timedelta(
                            seconds=int(expires_in))
                if ok:
```

From Sentry.io, I gathered that sometimes Facebook returns an error object instead of the expected `access_token`. In this case Sentry recorded the following for `resp`.

```python
{
  'error': {
    'code': 1, 
    'fbtrace_id': 'BdOUaHu3KoO', 
    'message': [Filtered], 
    'type': [Filtered]
  }
}
```
Sadly, it clobbered the actual message, but it's clear we need to handle this error scenario in the token view.

**Comment by kwhandy** [comment]
Did you make some restriction to some countries? Please be aware about your restricted list

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1382
