### ISSUE TITLE
Facebook login with js_sdk “Unsupported” in Chrome on iOS

### ISSUE THREAD

**Issue by Bartvds** [pennersr/django-allauth#1383]
After we click the Facebook button on signup form we get a Facebook page that says iOS Chrome is unsupported.

Apparently this is a long standing issue with iOS Chrome and the Facebook JS SDK; we find a ton of issues about it on Google/Stackoverflow etc. For example: http://stackoverflow.com/questions/16843116/facebook-oauth-unsupported-in-chrome-on-ios

We could switch to the alternate FB auth method but it seems wrong to degrade all users experience for a single browser issue. 

This issue has been around for a while (approaching 3 years :disappointed:). There seem to be some hacky workarounds floating around but I wonder if anyone using django-allauth encountered this before? Is there a known workaround to apply in django-allauth?

**Comment by harshilpatel** [comment]
Came across this as a default issue on all devices with latest version.
never faced with issue before on v0.23.0. was able to signup on all devices

**Comment by pennersr** [comment]
Not sure if this is to be solved within allauth...

**Comment by derek-adair** [comment]
Close as wont fix.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1383
