### ISSUE TITLE
Facebook Login fails in v0.25

### ISSUE THREAD

**Issue by harshilpatel** [pennersr/django-allauth#1384]
facebook login with js_sdk doesn't work in latest version. I had to fall back to v0.23.0

**Comment by getup8** [comment]
Works fine for me

**Comment by j0hn** [comment]
It's failing to me to using the `login_by_token` method.
I'm getting a facebook `access token` using javascript and calling a view that all it does is this:

```python
from allauth.socialaccount.providers.facebook.views import login_by_token
@csrf_exempt
def facebook_access_token_login(request):
    return login_by_token(request)
```

with v0.25 version is failing at the point of calling `fb_complete_login` and do the request to `/me/` endpoint.

```python
resp = requests.get(
    GRAPH_API_URL + '/me',
    params={
        'fields': ','.join(provider.get_fields()),
        'access_token': token.token,
        'appsecret_proof': compute_appsecret_proof(app, token)
    })
```
The response to that request is this:

```json
{
	"error": {
		"message": "Invalid appsecret_proof provided in the API argument",
		"type": "GraphMethodException",
		"code": 100,
		"fbtrace_id": "C7VRqEtcn9c"
	}
}
```

Removing the param `appsecret_proof` seams to do the trick but i moved back to `0.23.0` so i don't have to fork this version and make the change myself.

**Comment by pennersr** [comment]
See #1050 -- does flipping this switch help?

**Comment by j0hn** [comment]
Nope, same json response

**Comment by pennersr** [comment]
I am going to close this until there is something more conclusive to work on. As far as I can tell and a few others can tell, things work properly out of the box...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1384
