### ISSUE TITLE
Multiple SignupForm Classes for Same User Type

### ISSUE THREAD

**Issue by mjsisley** [pennersr/django-allauth#1385]
I am looking to have two custom SignupForm classes. The two signup forms are for the same type of users, but have the user submit a different amount of information. 

- User just makes an account (default signup).
- User makes an account and submits additional information at the same time.

What is the recommended way of accomplishing this?

Would it be desirable and feasible to have django-allauth's ACCOUNT_SIGNUP_FORM_CLASS take a list of classes instead of a single class, that allow for multiple views and forms that trigger account creation?

**Comment by mjsisley** [comment]
I ended up doing this by using one SignupForm class and then including the additional information in a second form class within a second View Class that inherits from SignupView. 
 
To get the two forms to work, I needed to overwrite:

- get_context_data()
- post()
- form_invalid()
- form_valid()

I also wanted a different redirect for the second form, so I needed to overwrite:

- get_authenticated_redirect_url()
- dispatch()

I imported the following in views.py:

```python
from allauth.account.views import SignupView, _ajax_response
from allauth.account.utils import complete_signup
from allauth.account import app_settings
```

While this worked, it certainly isn't elegant. If there is a more recommended solution or it is of interest for the package to support having multiple signup form classes, that would be great. If not, this issue should probably be closed.

**Comment by pennersr** [comment]
It's a matter of how you look at things. If you can sign up, either with or without providing additional information, then apparently that information is optional. So I would put it in one signup form and not make those fields required.

**Comment by EdCampion** [comment]
Apologies for bringing this back from the dead, but have spent today stuck on following scenario.

A company_user can sign up to my service, providing it's auth info and data for the company table.
A developer user simply gives his auth info and a company name.

How with one signup form can both these users signup?

**Comment by pennersr** [comment]
You apparently have 3 models: company, developer and account. The latter is the one taken care of by allauth (`User`). The company and developer model can have an foreign key to the account. Another way of modelling things is to simply have one typed account, so one `User` model with a type indicating if it is a developer or company.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1385
