### ISSUE TITLE
Signup Page Logs in User if User Already Exists

### ISSUE THREAD

**Issue by mjsisley** [pennersr/django-allauth#1386]
If a user has an existing account, would it be possible to have a setting that logs in a user instead of giving the "user already exists" error?

If a setting isn't possible, what is your recommended way of accomplishing this?

Thanks for the time you have put into this project and if you have a chance to answer this question!

**Comment by pennersr** [comment]
I assume you are referring to social accounts? Have a look at issue #215 for a discussion on this.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1386
