### ISSUE TITLE
account email unique in utf8mb4

### ISSUE THREAD

**Issue by Alchemist85K** [pennersr/django-allauth#1388]
I'm using django-allauth 0.24.1 and django 1.7.0.
Lately I changed my database to utf8mb4 and migration was failed because of the unique property in email inside accout model. 
I needed some options whose default value is 191 to set accout email. 
I have to use unique option of utf8mb4 and accout email. 
Please apply this soon. 
Since 0.25.0 version is not compatible with 0.24.1 version. please apply this patch as 0.24.2 version.
Thanks.

https://github.com/pennersr/django-allauth/pull/1387

**Comment by pennersr** [comment]
Sorry, but I am not maintaining/patching past releases...

**Comment by pennersr** [comment]
EMAIL_MAX_LENGTH setting was merged...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1388
