### ISSUE TITLE
Incorrect password causing 200 Ok response, but no error in the form

### ISSUE THREAD

**Issue by davemerwin** [pennersr/django-allauth#1393]
I have a  test user with a username that exists. When I submit the incorrect password, the response is 200 Ok. But that doesn't make any sense. Should the response be something like 403 Forbidden? Also, shouldn't the form return an error?

**Comment by dicato** [comment]
Django returns a 200 upon failed authentication; you can see the code here:

https://github.com/django/django/blob/92107522ed3568740ec7c3597db50b5c3a6e84d3/django/contrib/auth/views.py#L98

...coincidentally someone asked me about this on a different project. It appears there has been quite a bit of debate about this topic in the past.

**Comment by davemerwin** [comment]
I wonder if there would be a way to capture the redirect from the above reference and then in Allauth, give the option to find the next var and then send an error message in the templates. Thoughts?

**Comment by pennersr** [comment]
This is common for regular forms. If you submit invalid data to a form you won't bump into a 400 BAD REQUEST either. As for the AJAX responses in allauth, you have full control over them by hooking into `ajax_response`.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1393
