### ISSUE TITLE
Users with duplicate names show up with unclear usernames in Admin

### ISSUE THREAD

**Issue by FunkyLoveCow** [pennersr/django-allauth#1394]
I am using the Stack Exchange provider currently. I have two users that have the same name - `Stephen`. The first user to authenticate receives a user entry in both the Social Users and Users sections of the Django admin.

The second user is created correctly in the Social users, but in Users has a user name of `user`. 

With only two users, it's easy to figure out which is which. With many users, it's difficult to determine which duplicate name is which user. Since I need to assign additional permissions to these users, I need to be able to determine *who* I'm applying them to quickly.

Is there a way to allow duplicate names in the Users section OR a way to assign Django based permissions (not scope permissions) from the Social Users section?

**Comment by pennersr** [comment]
Have a look here:

https://github.com/pennersr/django-allauth/blob/master/allauth/account/adapter.py#L211

There, you'll find that the unique username that is being automatically generated is based off one of first name, last name, email... and if all these are empty, then plain `"user"`. Given that the Stack Exchange provider only passes along the `username` and nothing else, `"user"` is being chosen. So, probably your issue can be addressed by adding username to the list. Could you give that a try?

**Comment by pennersr** [comment]
See 136d6bf
