### ISSUE TITLE
Username field in signup form lost maxlength in 0.25.0

### ISSUE THREAD

**Issue by jwhitlock** [pennersr/django-allauth#1395]
Commit ce7ea1b3952f8ed211c25e03a5a1ccede2c077e9 moved ``max_length`` from the ``username`` field initialization to the form initialization, to fix bug #1319.  The widget is initialized during field initialization, so the ``max_length`` parameter doesn't get initialized in the widget, and the ``maxlength`` attribute is no longer present in the username ``<input>`` element.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1395
