### ISSUE TITLE
weixin: 'WeixinProvider' object has no attribute 'package'

### ISSUE THREAD

**Issue by Milor8** [pennersr/django-allauth#1397]
I just drop **winxin**  folder into **providers** folder, then add `allauth.socialaccount.providers.weixin` in settings' INSTALLED_APPS, now give me the error when reload the project: `AttributeError: 'WeixinProvider' object has no attribute 'package'`

**Comment by pennersr** [comment]
See 51e4aac -- the package property was required to be present in if I recall correctly 0.25.1 and below. So copying over new providers into old code won't work without adding the property.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1397
