### ISSUE TITLE
Prevent from saving using ACCOUNT_SIGNUP_FORM_CLASS

### ISSUE THREAD

**Issue by kaldown** [pennersr/django-allauth#1400]
How to create custom fields for signup, with additional logic, for example:
test input value of custom field and then decide, what to do?
I tried kinda this:
````
class MySignupForm(forms.Form):
    DOC = 'doc'
    PAT = 'pat'
    CHOICES = (
        (DOC, 'Doctor'),
        (PAT, 'Patient')
    )
    first_name = forms.CharField()
    last_name = forms.CharField()
    phone = forms.CharField(required=False)
    profile = forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect())
    secret = forms.CharField(required=False)
    def signup(self, request, user):
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        if self.cleaned_data['profile'] == self.DOC:
            if secret_verify(self.cleaned_data['secret']):
                user.groups.add(Group.objects.get(name='Doctors'))
                send_sms(self.cleaned_data['phone'])
            else:
                messages.add_message(request, messages.ERROR, 
                    'Secret code is wrong')
                print 'SHOULD END'
                return HttpResponseRedirect(reverse('/'))
        
    def save(self):
        import pdb; pdb.set_trace()
        if self.cleaned_data['profile'] == self.DOC:
            print 'in save'

````
But user creates anyway.
Or parralel question:
how nearly better to solve a problem of registering one type of `profile` only after putting some `secret`, and the other type of profile remain same. And if first type of profile want to sugnup - do some addition, like adding a `group` or even send_sms.

Spend too much time, I think I'm so close, but missing something.

Thanks.

**Comment by pennersr** [comment]
If you need to do additional tests and show errors in case of failure, you should implement this using regular Django form validation. So simply add a ‘def clean(...)‘ to your form...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1400
