### ISSUE TITLE
security: user email addresses are leaked via reset password form

### ISSUE THREAD

**Issue by wtfrank** [pennersr/django-allauth#1401]
When resetting your password, you are asked for an email address. If you enter an unknown email address then you receive an error from allauth. This opens allauth up to a bruteforce email discovery attack, where you scan common email addresses to find out if an account exists on the site.

Best practice is probably to return the same response, regardless of whether a valid email address is entered: "If this email address is associated with an account, then an email with instructions on how to reset your password will be sent out shortly."

**Comment by pennersr** [comment]
Duplicate, see #1307

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1401
