### ISSUE TITLE
feature request: ability to force email validation when an email address is provided

### ISSUE THREAD

**Issue by wtfrank** [pennersr/django-allauth#1402]
If ACCOUNT_EMAIL_REQUIRED is set to True, then you can set ACCOUNT_EMAIL_VERIFICATION to True and it works as expected.

However if ACCOUNT_EMAIL_REQUIRED is set to False, then you cannot set ACCOUNT_EMAIL_VERIFICATION to True.

It would be useful to force validation for any email address that is provided, without forcing an email address to be provided at all.

**Comment by pennersr** [comment]
From a UX point of view this is kind of weird. Users not providing an email address can immediately start to use your site, whereas users that are kind enough to provide an email are "punished" by the fact that they have to jump through hoops, open their mailbox and verify the mail before being able to use the site.

It would also cause weird flows. What about this one: a user signs up without providing an email address and is happily using your site. Then, he visits the email management screen and adds an email address. What should happen now next time he logs in? The newly added email address was not validated yet, so should he be stopped from being able to log in with an unverified email address?

All in all, I am not interested in pursuing this flow ...

**Comment by wtfrank** [comment]
The problem I ran into is that an email address that is not verified might be incorrect and could be used to spam people by triggering actions on the site. So I either want no email address to be provided whatsoever, or a confirmed valid email to be provided. An email that has been provided but not validated is of no use for communication or account reset, and could be used to annoy 3rd parties via my site which I definitely don't want!

**Comment by pennersr** [comment]
Why don't you just filter on those email addresses that are verified when communicating with your users?

**Comment by wtfrank** [comment]
I think you can use the password reset form to send emails that come from my site to victim 3rd party email addresses as a method of annoyance/harassment.

**Comment by pennersr** [comment]
Consider this scenario: a user signs up, but does not actually proceed in using the site. He basically forgets all about it, and does not verify his email address as well. Later on he returns to the site, but he forgot his password. Now what?

You can always harass people as you indicate above. A simple signup will trigger your system to also send an email to an unverified address.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1402
