### ISSUE TITLE
Send email confirmation with ACCOUNT_SIGNUP_FORM_CLASS

### ISSUE THREAD

**Issue by kaldown** [pennersr/django-allauth#1403]
Good evening.
First of all, I want to thank for previous advice. Was very helpful. 
But now I realized that I don't understand how to handle sending email confirmation with custom `def signup()` using `ACCOUNT_SIGNUP_FORM_CLASS`. Without `ACCOUNT_SIGNUP_FORM_CLASS` all just works.

Thanks!

Ok, It was just in case `is_active = False`.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1403
