### ISSUE TITLE
HTML5 required attribute

### ISSUE THREAD

**Issue by kevinmickey** [pennersr/django-allauth#1405]
Shouldn't the widgets for required inputs have an HTML5 required attribute?  I don't see them on my signup form, but the server does recognize the field as required after submission.

**Comment by kevinmickey** [comment]
You could also set the HTML5 minlength attribute for the password.

**Comment by kevinmickey** [comment]
> server side validation always more preferred for important data

Yes, I am suggesting client side validation in addition to server side validation.

I don't know much about django's password validators.  I saw the ACCOUNT_USERNAME_MIN_LENGTH and ACCOUNT_PASSWORD_MIN_LENGTH settings.  I see that the username one is listed as deprecated.  If the password one is as well, it should be documented.

I am talking about any field that is required -- username if ACCOUNT_USERNAME_REQUIRED, email if ACCOUNT_EMAIL_REQUIRED, password.  The widgets for each required field should include 'required': True, so that in HTML there is a 'required' attribute.

**Comment by pennersr** [comment]
Closing -- this is dated.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1405
