### ISSUE TITLE
Can not migrate

### ISSUE THREAD

**Issue by kaldown** [pennersr/django-allauth#1406]
````
python manage.py migrate
django.db.utils.ProgrammingError: relation "auth_group" does not exist
LINE 1: SELECT (1) AS "a" FROM "auth_group" WHERE "auth_group"."name...
````
And can not disable `django-allauth` always returns me something 
`RuntimeError: Model class allauth.account.models.EmailAddress doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.`

**Comment by Akay7** [comment]
@kaldown what inside your installed apps?

**Comment by kaldown** [comment]
@Akay7 
[
   'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
]

**Comment by Akay7** [comment]
@kaldown 
You forget [install allauth](https://django-allauth.readthedocs.io/en/latest/installation.html)

**Comment by kaldown** [comment]
@Akay7 No, I'm not, Want to disable it for a while. Actually I've reached this, following through every error occuurence and deactivete allauth. Now I steped back to `django.db.utils.ProgrammingError: relation "auth_group" does not exist
LINE 1: SELECT (1) AS "a" FROM "auth_group" WHERE "auth_group"."name...` But I've no custom user model, maybe it was in migrations, but not in streaming comimnts (forgot to remove).
Is there any not such painful method to remove all occurences of AbstractBaseUser in migration, in case it's 100% not used?

**Comment by kaldown** [comment]
Done, by removing all occurencies of allaith, then migrate, then migrate with allauth.

**Comment by yjoonjang** [comment]
Hello, I'm having the same issue and cannot resolve it. how can I resolve this?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1406
