### ISSUE TITLE
redirect_uri - paypal

### ISSUE THREAD

**Issue by gurjmatharu** [pennersr/django-allauth#1411]
I am unable to successfully connect to Paypal as I am getting the following error:

> Relying Party Validation error: redirect_uri provided in the request does not match with the registered redirect_uri. Please check the request.

I am able to successfully connect and login through javascript using the following:
https://developer.paypal.com/docs/integration/direct/identity/button-js-builder/

It seems that django allauth is not passing the correct return_uri to paypal.
`"returnurl":"http://my.domain.here/return.php"`

In my template I am triggering the connect to paypal like so:
`<a href="{% provider_login_url "paypal" process="connect"%}">Paypal</a>`

My apologies if I'm overlooking anything, as I've read the docs, ensured the setting file is correct: scope and test mode.

**Comment by pennersr** [comment]
Closing -- seems dated.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1411
