### ISSUE TITLE
Requiring First and Last Name

### ISSUE THREAD

**Issue by stringsonfire** [pennersr/django-allauth#1412]
`First Name` and `Last Name` are default fields in the Django `User` model, so don't require a custom User model to use.

That being the case, does it make sense to add functionality to require these out of the box, in a similar fashion to the following:

- `ACCOUNT_EMAIL_REQUIRED`
- `SOCIALACCOUNT_QUERY_EMAIL`
- `SOCIALACCOUNT_EMAIL_REQUIRED`

I'd assume that these two fields are fairly common among `django-allauth` users, so having them pulled from Social where available could be helpful here.

**Comment by pennersr** [comment]
First/last name are already pulled from the social provider. Not sure what you are proposing here, adding input fields to the regular non-social account signup?

**Comment by stringsonfire** [comment]
Making First and Last names required for standard sign up with a setting similar to `ACCOUNT_EMAIL_REQUIRED`, as you say. 

I'm a little new here. What happens if Social doesn't return an email address, and `SOCIAL_ACCOUNT_EMAIL_REQUIRED = True`? Is the user required to enter the email manually?

**Comment by pennersr** [comment]
Yes, though it is questionable if you would want to stop a social auto signup just because one of first/last name is missing. So, adding such a feature would either force us to make opinionated choices (what to do with auto signup), or, we would need an additional setting on how to handle auto signup.  Hmm....

**Comment by pennersr** [comment]
For now I prefer not to pick this up given the above. You can easily add a custom form like this, and turn off auto signup if you like:

```
class CustomSignupForm(forms.Form):
    first_name = forms.CharField(max_length=30, label='First name')
    last_name = forms.CharField(max_length=30, label='Last name')

    def signup(self, request, user):
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.save()
```

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1412
