### ISSUE TITLE
Clarifying ACCOUNT_UNIQUE_EMAIL - How is email uniqueness checked and enforced?

### ISSUE THREAD

**Issue by stantond** [pennersr/django-allauth#1413]
How does `django-allauth` ensure that emails are unique when `ACCOUNT_UNIQUE_EMAIL = True`?

Would be great to have a brief description of how this is done in the [Configuration documentation](https://django-allauth.readthedocs.io/en/latest/configuration.html) to help a developer quickly decide if they're happy with it or want to implement anything in addition.

I've seen multiple ways of doing this so far, and still see no sign that Django itself will directly support email uniqueness any time soon.

**Comment by pennersr** [comment]
For now, you'll have to take a peek at the source to see how this is done. If anybody wants to add a section to the documentation on this, feel free to submit a pull request.

**Comment by stringsonfire** [comment]
@pennersr Please re-open. I'll close with a docs update.

From what I can see, `django-allauth` stores all emails in the `emailaddress` model, and is `ACCOUNT_UNIQUE_EMAIL = True`, the `emailaddress.email` field is changed to `UNIQUE`, so it's enforced at the db level. 

Unique emails are also enforced in forms. When True, a user cannot register with an existing email, nor can a user add an additional email that is already attached to a different user's account.

Is that everything?

**Comment by pennersr** [comment]
That's a nice summary...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1413
