### ISSUE TITLE
Clarifying ACCOUNT_CONFIRM_EMAIL_ON_GET - Why not use this?

### ISSUE THREAD

**Issue by stringsonfire** [pennersr/django-allauth#1414]
The following is in the [Configuration documentation](http://django-allauth.readthedocs.io/en/latest/configuration.html):

> ACCOUNT_CONFIRM_EMAIL_ON_GET (=False)
Determines whether or not an e-mail address is automatically confirmed by a mere GET request.

I can't remember following an email confirmation link to then have to confirm this again on the website. My expectation would be to land on a page telling me that my email has been confirmed. However, the word _mere_ in the quote above makes it sound like enabling this behaviour is a bad idea. Is that intentional? If so, why is it a bad idea to set this to `True`?

**Comment by pennersr** [comment]
Verifying your email address modifies the state of the server. Semantically, GET requests should not be modifying server state. Having said that, doing so is actually common practice and will not do much harm. `ACCOUNT_LOGOUT_ON_GET` is in a similar situation, but there things can be worse. See the `LogoutView` documentation for notes on why. 

Btw, if you like to have it set to POST without forcing interaction from the user, you could put some auto-posting Javascript in your email confirmation template...

**Comment by stringsonfire** [comment]
Thanks, I've added that to the docs for the next person with the same question in #1417.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1414
