### ISSUE TITLE
What should be done to be identified by facebook mobile & fixed

### ISSUE THREAD

**Issue by alvaro562003** [pennersr/django-allauth#1419]
Hello,
I installed allauth for the facebook identification on my web server. It works very well.
Now i want to extend the same function to moibile user. What do you recommend to do ?

Apparently,  i should create another app on facebook (android and ios menu).

**Comment by pennersr** [comment]
I am not sure what you would like to know. On mobile, you can simply point your browser to the web server and things will work as well, without additional apps. If you are talking about mobile apps, perhaps this helps: http://stackoverflow.com/questions/16834514/connect-facebook-phonegap-login-with-django-allauth/16845596#16845596

**Comment by alvaro562003** [comment]
Hi raymond,I solved my problem. Thank you for the advice.


      De : Raymond Penners <notifications@github.com>
 À : pennersr/django-allauth <django-allauth@noreply.github.com> 
Cc : alvaro562003 <alvaro562003@yahoo.fr>; Author <author@noreply.github.com>
 Envoyé le : Lundi 27 juin 2016 23h36
 Objet : Re: [pennersr/django-allauth] What should be done to be identified by facebook mobile & fixed (#1419)
   
I am not sure what you would like to know. On mobile, you can simply point your browser to the web server and things will work as well, without additional apps. If you are talking about mobile apps, perhaps this helps: http://stackoverflow.com/questions/16834514/connect-facebook-phonegap-login-with-django-allauth/16845596#16845596—

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1419
