### ISSUE TITLE
ACCOUNT_LOGOUT_ON_GET=True not working if user tick remember on login

### ISSUE THREAD

**Issue by sowinski** [pennersr/django-allauth#1421]
Hi,

I am using django-allauth==0.24.1 with ACCOUNT_LOGOUT_ON_GET=True. Everything works fine except one thing.
If I login and then click on logout, everything is fine. I am logged out!
But if I login and tick remember me, then I'm not able to logout. Any Idea what is wrong?
Can anyone confirm that?

**Comment by pennersr** [comment]
No, I am pretty sure this is a local issue, but if you do find evidence of an issue in allauth, feel free to reopen.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1421
