### ISSUE TITLE
adding @verified_email_required returns error

### ISSUE THREAD

**Issue by kaldown** [pennersr/django-allauth#1423]
Just new project, did all from _installation_ and right after adding `@verified_email_required` got this:
`Reverse for 'account_email' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []`

No addition settings were applied.

Forgot to add it in `urls`

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1423
