### ISSUE TITLE
Synching django default auth user pk & user profile pk, anybody has the solution?

### ISSUE THREAD

**Issue by sunjoomoon** [pennersr/django-allauth#1424]
I have challenging time trying to sync user pk (django default auth) and user profile pk, but django default auth user pk is always +1 than user profile pk. That is because I created superuser upon first database migration. How can I do the sync? Hope is whatever it is, the pk from django auth is used in user profile as well.

**Comment by pennersr** [comment]
Why should user.pk be identical to profile.pk? You shouldn't worry about that...

**Comment by sunjoomoon** [comment]
Thanks for the comment. It is because of user profile edit purpose. I want users to edit their profiles - his or her own only and instead of username pk is used. Seems there is a better way of letting users edit profile? Any clue or related doc would be appreciated

**Comment by sunjoomoon** [comment]
trying things out now.. thank for the tip. All were fine (following the doc) but at the stage where allowing user actual edits his/her own profile (preferrably using username) got me lost out of nowhere.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1424
