### ISSUE TITLE
Authenticate with phone number

### ISSUE THREAD

**Issue by mhipo1364** [pennersr/django-allauth#1426]
Hi guys, I need too authenticate my users via theirs `cellphone` numbers, how can I do this?

**Comment by MUDASSARHASHMI** [comment]
Its out of scope of allauth . Use twilio.com instead and you can integrate it with django-all auth. You can learn more at https://django-twilio.readthedocs.io/en/latest/.

**Comment by mhipo1364** [comment]
Thanks @MUDASSARHASHMI

**Comment by itmard** [comment]
@mhipo1364 I changed allauth default login backends to support phone number ( everything else ) based login. I can share it here as pull request.

**Comment by pennersr** [comment]
You should be able to build this on top of allauth, but if there is anything in allauth that makes life difficult for you, please let me know.

**Comment by magic-overflow** [comment]
I want to authenticate with email or phone number. Can anyone guide me where to change in allauth?

**Comment by bhuthesh** [comment]
@itmard Is your code that supports mobile number as one of the backends available publicly? It'll be useful for me if it is available. Thank you.

**Comment by enchance** [comment]
Has anyone found a way to register via mobile? I'm new to Django.

**Comment by divick** [comment]
@pennersr From what I can understand, modifying allauth to support phone based authentication requires significant work. It would required modifying the allauth code too. One can always extend allauth but the effort would be much more and would require overriding almost all forms for signup, login etc. If someone is ready to modify allauth to support phone number based authentication and signup, would be you open to integrate the pull request?

**Comment by pennersr** [comment]
@divick I think this is more suited to be built on top of allauth instead of within. The requirements are too diverse. Also, you'll likely need to support multiple backends, like Twilio and so on.  

I don't think there is anything in the way that makes life difficult in trying to build this on top of allauth. If there is, I would be happy to discuss and accept a pull request to streamline things.

**Comment by ajinkya-bhosale** [comment]
@itmard cna you share your code ?

**Comment by lggwettmann** [comment]
Wouldn't it be possible to build a twilio-sms backend for django-allauth?

**Comment by mmmcorpsvit** [comment]
are any progress to include mobile phone SMS auth ?

**Comment by ashwinkjoseph** [comment]
@pennersr I see that this is requested quite a few times. I came to this page hoping to find a solution too. Apart from this, another useful login provider could be something like a Magic Link or a Password-less Email login.
I would love to help you with the password-less email login, it wouldn't have the problem of multiple backends you mentioned here
> @divick I think this is more suited to be built on top of allauth instead of within. The requirements are too diverse. Also, you'll likely need to support multiple backends, like Twilio and so on.

As for mobile login, would you consider the idea of providing an abstract class that would define the expected behaviours for an SMS service backend and then asking the user to implement the class however they want and using settings variable to access the concrete class that the user implemented?  (let me know if this is a bad suggestion, just looking for ways to contribute).

If you are okay with this idea, I would love to help you in this process.

**Comment by hemarastylepeke** [comment]
Has a solution on extending allauth default signup and login to support SMS otp verification found? I developed my entire authentication backend using allauth. Really I didn't want to add any other package on top of my stack. Most of the information I find on the internet and the packages they recommend doesn't intergrate well with allauth.

**Comment by pennersr** [comment]
I understand -- this and MFA in general is a feature that is not very well suited to be bolted on using external packages. Would love to see some increased sponsorship to make this happen...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1426
