### ISSUE TITLE
provider_login_url not working for google

### ISSUE THREAD

**Issue by rajexp** [pennersr/django-allauth#1430]
The provider_login_url "google" is not redirected to google while facebook is working fine.
` 
{% load socialaccount %}
<a id="google_login" class="circle google" href="{% provider_login_url "google" method="oauth2">
                                        <i class="fa fa-google-plus fa-fw"></i>
                                    </a>
                                    <a id="facebook_login" class="circle facebook" href="{% provider_login_url "facebook" method="oauth2" %}">
                                        <i class="fa fa-facebook fa-fw"></i>
                                    </a>`

**Comment by pennersr** [comment]
This seems to be working just fine... closing for now, if you do think there is an issue in allauth please file a more specific bug report. What URL is it redirecting to in your case, and how does that differ from what you expected?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1430
