### ISSUE TITLE
Facebook authentication error won't go away

### ISSUE THREAD

**Issue by MUDASSARHASHMI** [pennersr/django-allauth#1431]
settings.py:
```
INSTALLED_APPS = [
    '.......', 
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.facebook',
]
SITE_ID = 1
LOGIN_REDIRECT_URL = '/'
SOCIALACCOUNT_PROVIDERS = \
    {'facebook':
       {'METHOD': 'oauth2',
        'SCOPE': ['email', 'public_profile', 'user_friends'],
        'AUTH_PARAMS': {'auth_type': 'reauthenticate'},
        'FIELDS': [

            'email',
           ],
        'EXCHANGE_TOKEN': True,
        'LOCALE_FUNC': 'path.to.callable',
        'VERIFIED_EMAIL': False,
        'VERSION': 'v2.4'}}
AUTHENTICATION_BACKENDS = (
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',
    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
)

```
In my Django admin in "Sites" I added in Domain name: localhost:8000 and Display Name: Mydomain.com. After that in my Django admin under "Social Accounts/Social Application:

```
Provider: Facebook
Name: Mydomain.com #same as in sites
Client ID: xxxxxxxxxxx #same as Facebook client ID
Secret Key: xxxxxxxxxxxxxxx # same as Facebook secret key. 
Key: # I left empty
Sites: I chose localhost in available sites and added to chosen sites.
```

Facebook Developer tools:
```
App Id: xxxxxxxxx
App Secret: xxxxxxxxxxxxxx
Display Name: mydomain.com
App Domain: localhost
Site URL: http://localhost:8000/
```

In my template:

```
{% load socialaccount %}
<a class="btn btn-block btn-social btn-facebook btn-lg" href="{% provider_login_url 'facebook' method='oauth2' %}"> <i class="fa fa-facebook"></i> Login using Facebook </a>
```

I also selected Add Product and then "Facebook Login" app at left panel. Client OAuth settings in my "Facebook Login" are:

```
Client OAuth Login = Yes
Web OAuth Login = Yes
Force Web OAuth Reauthentication = Yes
Embedded Browser OAuth Login = No
Valid OAuth Redirects URIs = http:localhost:8000/
Login from devices = Yes
Deauthorize = "I added one my site I built with ssl, it said so that it has to be a domain with https://something.com"
```

The error message I get after getting to FB page is:

`URL Blocked: This redirect failed because the redirect URI is not whitelisted in the app’s Client OAuth Settings. Make sure Client and Web OAuth Login are on and add all your app domains as Valid OAuth Redirect URIs.
`
This error comes with a pop-up message with an "Ok" button on facebook page loaded behind. When I click ok it redirects me to django page with another error:

`An error occurred while attempting to login via your social network account.
`
Any thing I am doing wrong or any fix?

Thanks.

**Comment by pennersr** [comment]
Visit the /accounts/facebook/login/ of your site. It will redirect you to FB, looking like this:

`https://www.facebook.com/login.php?....%3Fredirect_uri%3Dhttps%253A%252F%252Fwww.yoursite.com%252Faccounts%252Ffacebook%252Flogin%252Fcallback%252F%26....`

Make sure that the `redirect_uri` listed here matches the one you configured over at FB.

**Comment by sachitad** [comment]
Anyone having trouble, I have created a detailed tutorial for facebook login using django all auth.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1431
