### ISSUE TITLE
ACCOUNT_USERNAME_MIN_LENGTH should be enforced during username generation

### ISSUE THREAD

**Issue by djw27** [pennersr/django-allauth#1432]
The ACCOUNT_USERNAME_MIN_LENGTH is currently only used in the signup form to check the min_length of the input.

If the form isn't used (e.g. if allauth is purely being used as a backend over an api) then this setting never has an effect. My recommendation would be to enforce this setting in generate_unique_username() or _generate_unique_username_base() so that the generated username always meets the minimum length requirements

**Comment by pennersr** [comment]
It is used in `generate_username_candidates`:

```
    min_suffix_length = max(1, USERNAME_MIN_LENGTH - len(basename))
```

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1432
