### ISSUE TITLE
Number of password fields is not consistent

### ISSUE THREAD

**Issue by marfire** [pennersr/django-allauth#1434]
Allauth has a configuration setting `ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE` to control whether or not the user has to enter their password twice on the signup form.

When it comes to the password change form, password set form, and password reset form, however, that setting is ignored and the user is always required to enter their password twice.

It seems to me that it makes more sense to consistently respect that setting everywhere that the user sets their password.

**Comment by pennersr** [comment]
Naming wise, things are consistent as the name clearly indicates that it is related to signup. The rationale for not requiring the user to enter the password twice is to lower the barrier of signup. For the regular password change form, you are already dealing with onboarded users, so there is no barrier to lower. Here, safety is more important, which explains the way things work now. Not sure it is worth changing this..  any examples of big sites which do this differently?

**Comment by marfire** [comment]
Hmm, I don't see it as a "safety" issue. Is a mis-typed password less safe? I see it as user experience tradeoff, between the relative cost and frequency of re-typing a password versus resetting a mis-typed password. The *reason* that it lowers the barrier to signup is that it makes for a better user experience, something that is just as true for all the other forms.

That said, I see your perspective and it may well be the case that most people only care about the setting for the signup form.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1434
