### ISSUE TITLE
Trying to change a user's password is resulting in a 405 error

### ISSUE THREAD

**Issue by davemerwin** [pennersr/django-allauth#1437]
I'm not really sure why, but when a user tries to reset a password the form sends it to root and I get a POST 405 error. 

Any ideas on why that is happening? It seems to be going to the wrong url, but I can't see where it is being redirected to root.

Relevant settings:

LOGIN_REDIRECT_URL = 'start'
ACCOUNT_LOGIN_ON_PASSWORD_RESET = True

I've tried turning both settings on and off to no avail.

**Comment by davemerwin** [comment]
It looks like the issue is the "." for the action. When the URL is changed to the request.path it works fine.

**Comment by davemerwin** [comment]
Yep, just used {{ request.path }} for the action and it worked great.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1437
