### ISSUE TITLE
(German) language file is broken

### ISSUE THREAD

**Issue by raphaa** [pennersr/django-allauth#1440]
Tried to fix the german i18n on [Transifex](https://www.transifex.com/django-allauth/django-allauth/) but it says there are 0 strings to translate. Maybe it could be that there are fuzzy tags and translations are filled with wrong suggestions?

If so, I'd do a pull request with removed fuzzy tags and update the language on Transifex.

**Comment by pennersr** [comment]
See: fd1961dccbe2bc253c273972b862304e047ea604

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1440
