### ISSUE TITLE
Discord social authentication backend

### ISSUE THREAD

**Issue by jleclanche** [pennersr/django-allauth#1443]
I'm filing this issue so that the discussion with @pennersr in #1420 isn't forgotten about.

Discord, like Battle.net, has "battletag" formatted usernames with a `#` in the middle of them. This means that in order for a discord provider to land, we need to figure out the issues highlighted in [this comment](https://github.com/pennersr/django-allauth/pull/1420#issuecomment-231529054).

**Comment by AileenLumina** [comment]
Discord has IDs, too. :) @jleclanche

**Comment by jleclanche** [comment]
@AileenLumina Unless you use those IDs to build the username, I don't think it really helps though.

**Comment by Braintelligence** [comment]
If this issue is anything about including Discord in the list of supported providers, then please do take my 👍

**Comment by pennersr** [comment]
Closing this issue, as it is currently about a non-existing provider. FWIW, make sure your user model has a username validator that allows for '#' being present in the name. That is required anyway for this to work, e.g. if you need to save the user in the Django admin.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1443
