### ISSUE TITLE
Different behavior of double checked password and email

### ISSUE THREAD

**Issue by raphaa** [pennersr/django-allauth#1446]
If a double checked email doesn't match, the error will be displayed directly at field email2 and if the double checked password doesn't match, it raises a ValidationError and will be displayed as a global error.

Maybe it would make sense to adjust the behavior. I prefer the error message directly at the field but that could be a breaking change other peoples projects.

**Comment by pennersr** [comment]
Agreed....

**Comment by pennersr** [comment]
b88885c6c617eb35f8b8de80db229600ca02953d

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1446
