### ISSUE TITLE
in varification mail set sender mail id

### ISSUE THREAD

**Issue by kartikdanidhariya** [pennersr/django-allauth#1448]
hi,
i used django allauth after registration allauth send mail to the user in that mail sender mail id is "webmaster@localhost" i want to change this from our mail id so how can i do that

**Comment by pennersr** [comment]
See `settings.DEFAULT_FROM_EMAIL` or `DefaultAccountAdapter.get_from_email`

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1448
