### ISSUE TITLE
Unique Email: Error Message Issue 

### ISSUE THREAD

**Issue by FSE-DEV** [pennersr/django-allauth#1449]
Attempt to create another account with the same email while ACCOUNT_UNIQUE_EMAIL = True renders an error message - as it should. The message however reads like "%(model_name)s mit diesem %(field_label)s existiert bereits." instead of something humanly readable.

**Comment by bnisevic** [comment]
I have the same. And I figured out that you removed this check from clean_email method in forms.py. Any good reason for removing raise_duplicate_email_error()? Any advice to overcome this problem?

You should be careful with this kind of changes because it breaks backwards compatibility. At least you should document it.

**Comment by bnisevic** [comment]
For others who have the same issue. I fixed it like this:

I've created custom adapter like this:
```
from django.utils.translation import ugettext_lazy as _
from allauth.account.adapter import DefaultAccountAdapter

class GiivxAccountAdapter(DefaultAccountAdapter):
    def __init__(self, request=None):
        super(GiivxAccountAdapter, self).__init__(request)
        self.error_messages['email_taken'] = _('A user is already registered with this e-mail address.')
```


Then you put this config into your setting:
`ACCOUNT_ADAPTER = 'apps.your_app.pathtothe.adapter.CustomAccountAdapter'`

The thing is that DefaultAdapter checks email field uniqueness against EmailAddresses model (not against your custom user model). And if you want to customize message there then you will need to override EmailAddresses which is not convenient.

Having documentation after this kind of change would be much helpful.

**Comment by j0hn** [comment]
Happened to me too, thanks for the workaround @bnisevic

**Comment by bnisevic** [comment]
@j0hn you're welcome. Yes, sorry, I had problem with github code markup while I was writing the comment. Giivx name was leftover from my own project. I've updated the comment with CustomAccountAdapter name. Thanks for noticing!

**Comment by pennersr** [comment]
Done (0e62e7be524168b19dd18bb617e661a61f5a63e0)

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1449
