### ISSUE TITLE
MySQL UTF8MB4 and migrations

### ISSUE THREAD

**Issue by pmuilu** [pennersr/django-allauth#1450]
It seems that the allauth schema is not compatible with utf8mb4. When running initial migrations I get:

Applying account.0002_email_max_length...Traceback (most recent call last):
django.db.utils.OperationalError: (1071, 'Specified key was too long; max key length is 767 bytes')

"Fixed" that with

ACCOUNT_EMAIL_MAX_LENGTH = 190 in settings.py

However this is not configurable anymore:

Applying socialaccount.0001_initial...Traceback (most recent call last):
django.db.utils.OperationalError: (1071, 'Specified key was too long; max key length is 767 bytes')

About utf8mb4 http://dev.mysql.com/doc/refman/5.7/en/charset-unicode-conversion.html

Is there already an off-the-shelf solution for this?

**Comment by pennersr** [comment]
Are you also seeing this when migration clean from scratch instead of half way changing the value?

**Comment by pmuilu** [comment]
Initial migration from scratch. I guess this is mainly a Django issue, there's discussion about it here: https://code.djangoproject.com/ticket/18392

I see most apps just workaround this problem by limiting the length of char fields to 191.

**Comment by pennersr** [comment]
Closing, this issue has been addressed in allauth as far as possible...

**Comment by kelly-ry4n** [comment]
For anyone else who finds this issue and needs a quick fix, you can set the mysql variables 

innodb_file_format=barracuda
innodb_file_per_table=true
innodb_large_prefix=1

and then for each table in question set the row format to dynamic

ALTER TABLE", $table_name, "ROW_FORMAT=DYNAMIC; (or during the CREATE TABLE).

With innodb_large_prefix and DYNAMIC row format (or maybe COMPRESSED, but I haven't tried this yet), the key length error will go away.

I imagine you could set something similar in the actual migration to add compatibility.

**Comment by grote** [comment]
So is the conclusion of this ticket that django-allauth does not work with `utf8mb4` which is the default on Debian now?

**Comment by pennersr** [comment]
@grote If you set `ACCOUNT_EMAIL_MAX_LENGTH = 190` then things should work just fine

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1450
