### ISSUE TITLE
Send email in background thread to prevent slow page load

### ISSUE THREAD

**Issue by rfj001** [pennersr/django-allauth#1451]
Whenever an email is sent, there is a noticeable delay in loading the next page. Since the email itself does not need to be shown to the user in the browser, it can be rendered and sent on a background thread, preventing the visible slowdown.

I did this by implementing a custom adapter, but I would expect a lot of users wanting this performance optimization without having to manually subclass the default adapter. Perhaps consider sending mail in the background by default? Or create a setting like `SEND_EMAIL_BACKGROUND` or something that a user can simply set to True to have all emails sent on a background thread.

Below is the code I used for my custom adapter.

```
from allauth.account.adapter import DefaultAccountAdapter
import threading

class BackgroundEmailSendingAccountAdapter(DefaultAccountAdapter):

    def send_mail(self, template_prefix, email, context):
        mailing_thread = threading.Thread(
            target=super(BackgroundEmailSendingAccountAdapter, self).send_mail,
            args=(template_prefix, email, context)
        )
        mailing_thread.start()
```

**Comment by pennersr** [comment]
Thanks, you may want to put this up in a gist or something. I prefer not to include this kind of stuff in allauth, as it is rather opinionated... e.g. others may prefer to use celery.

**Comment by SiyuanQi** [comment]
Thanks for sharing! I also noticed the obvious delay when signing up. This is a clean way to solve it.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1451
