### ISSUE TITLE
Warning in running example

### ISSUE THREAD

**Issue by sbagri** [pennersr/django-allauth#1456]
I tried running the example app in the project and on running 'python manage.py runserver' got this warning

WARNINGS:
?: (1_8.W001) The standalone TEMPLATE_* settings were deprecated in Django 1.8 and the TEMPLATES dictionary takes precedence. You must put the values of the following settings into your default TEMPLATES dict: TEMPLATE_CONTEXT_PROCESSORS, TEMPLATE_DEBUG.

I am using django 1.8.14 with python 3.5.1

I am new to django so don't know how to resolve the issue properly. I would be happy to provide a patch if someone can guide what exactly is to be done

**Comment by pennersr** [comment]
Unfortunately, the example app is rather outdated... to be fixed.

**Comment by pennersr** [comment]
Done (c62a64815f48a18981ff14d81a532a74d17c93d9)

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1456
