### ISSUE TITLE
Show user email in the EmailVerificationSentView

### ISSUE THREAD

**Issue by juliomrqz** [pennersr/django-allauth#1457]
Are you planning to show the user email in the **EmailVerificationSentView**? Maybe It's useful for users to see if they set a wrong email.

Thanks.

**Comment by pennersr** [comment]
No plans here, the email to which the verification was sent is already available via the messages:

            get_adapter(request).add_message(
                request,
                messages.INFO,
                'account/messages/'
                'email_confirmation_sent.txt',
                {'email': email})

The EmailVerificationSentView itself is completely stateless, it has no clue about the email. Adding that would be messy...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1457
