### ISSUE TITLE
How to save case-insensitive username?

### ISSUE THREAD

**Issue by myvirtualarena** [pennersr/django-allauth#1459]
Being trying around with no avail. How do i save users who register on my site to have case-insensitive username? I.e. They can have usernames of multiple casing but e.g. John and john refers to the same username in login.

**Comment by pennersr** [comment]
allauth already considers usernames to be case insensitive, you do not need to worry about that.

**Comment by myvirtualarena** [comment]
Thats not true? I just tested on my website over and over again. E.g. I got a username that i registered as victorchris, I was able to log in but when I tried VictorChris, it doesnt work?

**Comment by pennersr** [comment]
Did you enable the authentication backends? See `iexact` over at: https://github.com/pennersr/django-allauth/blob/master/allauth/account/auth_backends.py#L36

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1459
