### ISSUE TITLE
key error 'request'

### ISSUE THREAD

**Issue by jlariza** [pennersr/django-allauth#1462]
I am using django allauth in one of my projects. Locally, it is working fine but in the production server I am getting this error.

`  File "/home/ubuntu/.envs/appname/local/lib/python2.7/site-packages/allauth/socialaccount/templatetags/socialaccount.py", line 20, in render
    request = context['request']
  File "/home/ubuntu/.envs/appname/local/lib/python2.7/site-packages/django/template/context.py", line 77, in __getitem__
    raise KeyError(key)
KeyError: 'request'`

I read about this problem and apparently it was caused if 'django.template.context_processors.request' is missing but I do have it inside my templates configuration.

I am using django-allauth==0.25.2 and django==1.9.8

do you know what I may be missing? thank you

**Comment by pennersr** [comment]
Upgrade to 0.27.0...  there were some changes along the way on this area: https://github.com/pennersr/django-allauth/commit/765d0693891d7d0e58492d3c2ab4e1ddb8582195#diff-129f947e9ab5377d6f003c60ae465194R39

**Comment by jlariza** [comment]
With 0.27.0, I am getting this error. 

File "/home/ubuntu/.envs/508q/local/lib/python2.7/site-packages/allauth/socialaccount/templatetags/socialaccount.py", line 19, in render
    request = template_context_value(context, 'request')
  File "/home/ubuntu/.envs/508q/local/lib/python2.7/site-packages/allauth/compat.py", line 43, in template_context_value
    value = getattr(context, key)
AttributeError: 'Context' object has no attribute 'request'

It is a very similar error. am I missing something?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1462
