### ISSUE TITLE
Unique username: Error message issue

### ISSUE THREAD

**Issue by yourcelf** [pennersr/django-allauth#1469]
The same problem in  #1449 exists for usernames as well as emails.  The error message displayed is literally `%(model_name)s with this %(field_label)s already exists.`, without replacing the template holders.

![screenshot from 2016-08-24 14 49 40](https://cloud.githubusercontent.com/assets/21318/17947528/4b488a1c-6a0a-11e6-8671-02344fed9fd1.png)

This was fixed for emails in https://github.com/pennersr/django-allauth/commit/0e62e7be524168b19dd18bb617e661a61f5a63e0 by hard-coding an error message rather than looking up the value on `AbstractUser`.  Some similar fix is needed for `username`.

**Comment by pennersr** [comment]
The difference is that for `username` there is actually a proper error message we can pick up:

https://github.com/django/django/blob/master/django/contrib/auth/models.py#L313

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1469
