### ISSUE TITLE
Why is there no `commit=` argument in DefaultSocialAccountAdapter.save_user?

### ISSUE THREAD

**Issue by bittner** [pennersr/django-allauth#1474]
In [DefaultAccountAdapter](https://github.com/pennersr/django-allauth/blob/master/allauth/account/adapter.py#L221-L244) there is a `commit=` argument to prohibit saving the model. From the comment in the method I understand this is to make it easier to inherit from the Adapter. With `commit=False` I would get the user created, do whatever I do with it, and then `user.save()` it myself. - This makes sense.

So, why is there no such argument in [DefaultSocialAccountAdapter](https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/adapter.py#L67-L77)? Is that a design decision? Or was this just forgotten, and we should add a `commit=True` argument the same way as above? - PR?

**Comment by pennersr** [comment]
The social `save_user()` saves both user and it's social m2ms (token, account). You cannot do the latter without committing.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1474
