### ISSUE TITLE
Context variable as next parameter on provider_login_url

### ISSUE THREAD

**Issue by invertium** [pennersr/django-allauth#1475]
The ProviderLoginURLNode.render function should check if a the next parameter is a context variable using resolve like suggested in this [stackoverflow post](http://stackoverflow.com/questions/6037789/django-custom-template-tag-with-context-variable-argument).

If the resolve returns none it should fall back to string.

**Comment by derek-adair** [comment]
Oh boy we're in 2016! awesome @pennersr.

I think this is is maybe related to #513.  There are [quite a few](https://github.com/pennersr/django-allauth/issues?q=is%3Aissue+is%3Aopen+next) related to this that are open.

**Comment by pennersr** [comment]
Currently, the tag sources `next` from:

- The `next` parameter passed to the tag: `{% provider_login_url "google" next="/path" %}`
- The `?next=/path` parameter of the current page/request.

I think what is asked for here is to add a 3rd source:

- Use the `next` template variable, if it is available in the context.

Though, that can be done like so:

`{% provider_login_url "google" next=next %}`

Don't think that is related to #513.

**Comment by derek-adair** [comment]
yes, i understand now. not related.

Probably a close - welcome PR?  Would be a minor QoL but not something really worth your time as the lead here...

Maybe even creating a tag to signify that anyone who would want this can write it and submit it for stuff like this?  I feel like its really easy to get inundated with valid-but-minor feature requests like this.

**Comment by pennersr** [comment]
Closing -- I don't like the idea of implicitly picking up `next`.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1475
