### ISSUE TITLE
Question: Login Redirect URL to user's username?

### ISSUE THREAD

**Issue by alzearafat** [pennersr/django-allauth#1476]
Hi there!

Great plugin!
But I'm having difficulty implement login redirect to user's username.
I want to make something like this : 

```
#settings.py
LOGIN_REDIRECT_URL = '/account/{{ user.username }}'
```

How I can make this possible?
Thank you in advance for any help you can provide :)

**Comment by g33klord** [comment]
IMHO keep it simple: 
let it be a static url, say `/accounts/redirect` and redirect to /account/{{ user.username }} from that view

```
def user_home_redirect(request):
    return redirect('/accounts/' + request.user.username + '/')  # user url namespace
```

or 


```
class UserHomeRedirectView(RedirectView):

    permanent = True

    def get_redirect_url(self, *args, **kwargs):
        return '/accounts/' + self.request.user.username + '/'  # user url namespace
```

**Comment by pennersr** [comment]
Closing, this is a support question, not an issue in allauth

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1476
