### ISSUE TITLE
IntegrityError thrown if logging in with username of user with non-unique email

### ISSUE THREAD

**Issue by gitsimon** [pennersr/django-allauth#1477]
When having set ACCOUNT_UNIQUE_EMAIL=True, ACCOUNT_EMAIL_VERIFICATION ='mandatory', the following can happen:
- Some stupid third-party-app/human admin adds two users U and U' in the Django User model with the same email address (uniqueness is not enforced for email by Django).
- When I attempt to login with the username of U' for the first time, allauth tries to add the duplicate email to the allauth EmailAddress model, which fails with an IntegrityError.

Proposal: It should either show some warning to U' that logging in is not possible, or delete the duplicate email from user U', letting him to login with his username only and add some new email later (which is then checked to be unique by allauth). This should be allowed even when ACCOUNT_EMAIL_REQUIRED=True

**Comment by renatobellotti** [comment]
Any progress on this?

**Comment by derek-adair** [comment]
aren't emails enforced to be unique now? Is this still an issue it's not clear what the problem is to me.

It *looks* like a corner case of admins making a mistake???  Seems like this is not worth.

**Comment by pennersr** [comment]
The issue being described is somehow trying to prevent other apps / Django admin to put users in an invalid state. If somebody has proposals in this direction, feel free to submit a PR, but it is not something considered to be worth pursuing from this end.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1477
