### ISSUE TITLE
Does not support Django (1.4.3+)

### ISSUE THREAD

**Issue by dan-klasson** [pennersr/django-allauth#1481]
In [your docs](http://django-allauth.readthedocs.io/en/latest/overview.html) you state you support `1.4.3+`. But on line 13 in `allauth/utils.py` you import `BinaryField`, which according to the [release notes](https://docs.djangoproject.com/es/1.10/releases/1.6/#binaryfield-model-field) was added in `1.6`.

Is there any list of releases that supports which Django versions?

**Comment by pennersr** [comment]
Django 1.7+ (see https://github.com/pennersr/django-allauth/blob/master/.travis.yml)

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1481
