### ISSUE TITLE
GitHub error "The redirect_uri MUST match the registered callback URL for this application" (Authorization callback URL)

### ISSUE THREAD

**Issue by bittner** [pennersr/django-allauth#1483]
The GitHub auth provider is special in a way that you can **only specify a single** "Authorization callback URL" for an app in your [developer applications](https://github.com/settings/developers). This is problematic when your website is using

1. several domains, subdomains, etc., or
1. http and https interchangeably (i.e. both can be used).

Then the callback URL allauth passes on to GitHub to redirect to will not match in many cases, and you will face:

> Social Network Login Failure
> An error occurred while attempting to login via your social network account.

Other auth providers solve this by **allowing several callback URLs**, GitHub doesn't. [Their suggested solution](https://developer.github.com/v3/oauth/#redirect-uri-mismatch) to the problem is:

> To correct this error, either provide a redirect_uri that matches what you registered
> or leave out this parameter to use the default one registered with your application.

In allauth, however, it looks like there is no setting to make the GitHub auth provider not send a callback URL to GitHub, correct? Is this problem known?

**Comment by pennersr** [comment]
I do not see how adding a setting to not send the callback URL would fix the situation. If you bump into the URL mismatch error, it means that the URL configured over at github does not match the one allauth is communicating. So, github will complain. But, if no callback URL is communicated github would indeed not complain immediately, but you are still bound to bump into wrong URLs later on.

**Comment by bittner** [comment]
The point is what the [GitHub documentation](https://developer.github.com/v3/oauth/#redirect-uri-mismatch) says:

> To correct this error, either provide a redirect_uri that matches what you registered
> or leave out this parameter to use the default one registered with your application.

Leave out the `redirect_uri` parameter in your [OAuth request](https://developer.github.com/v3/oauth/#web-application-flow), and the GitHub application will use the  callback URL specified in its "Authorization callback URL" field.

**In other words:** If your application supplies a dynamic value for the `redirect_uri` (this is the case with multiple domains and protocols) then always redirect back to the URL [configured on GitHub](https://github.com/settings/developers). No need to supply the return path as a query parameter.

**Comment by pennersr** [comment]
I still fail to see how this solves a problem. As it currently stands, allauth passes along /foo whereas /bar is configured over at github, causing a mismatch failure. Now, if we don't send the callback url there will still be a mismatch, as github will redirect to /bar (as that was configured over at github), whereas allauth is expecting /foo. So what did we gain?

**Comment by bittner** [comment]
I agree that if developers are idiots we should help them not to hurt themselves too badly. (:bulb:You design the `redirect_uri` to be a double-check on a correct implementation: _"Do allauth and the GitHub app want the same thing - are they made for each other?"_)

Now, with GitHub we have a situation where we have to ask idiots to stay away from the GitHub application configuration. And we need to trust non-idiot programmers that they configure exactly the URL value in their GitHub application that will work with `allauth`. (:bulb:GitHub designs the `redirect_uri` to be a security feature: _"We won't send you out to a malicious site - even if you tell us!"_)

That's why it actually makes sense to make this feature optional, into a special setting in `allauth`. Initially, I had thought it could even be made default. (Really, in the end it makes no difference: If you configure a wrong value on GitHub even the coolest `allauth` code will not make you return from GitHub after a successful authentication; only a valid value **on GitHub** will make the auth provider work.)

**Comment by pennersr** [comment]
I prefer to only add settings for warranted configurable functionality. In this particular case, the documentation for this new setting would become:

"Indicates whether or not allauth communicates the redirect URI to github. Whichever way you flip this setting does not matter -- if you do not configure the proper callback URL over at github things simply won't work either way".

That clearly is not warranted.

**Comment by bittner** [comment]
I've raised this issue with GitHub support. This is their answer:

> Date: Fri, 09 Sep 2016 17:14:49 -0700
> From: GitHub Staff <<support@github.com>>
> 
> Hey there Peter -
> 
> Thanks for sharing your thoughts about this!
> 
> That's an interesting question. At this time, we don't publicly discuss why or how a specific GitHub feature is released. We see how it would be a neat idea to accommodate several callback URLs for a GitHub Developer application. We've noted your idea internally so the team working on the GitHub API can see it and consider that while building future iterations. It might be something we support in the future, but we can't promise when it will happen.
> 
> We are always curious to learn more about our users' needs and pain-points as it relates to workflows on GitHub. If there's anything else you'd like to see improved, please feel free to write back!
> 
> All the best,
> GitHub Staff
> 
> -----------------------------------
>> This is a request about your OAuth infrastructure at GitHub.
>> 
>> With other OAuth providers it is usually possible to specify several valid callback URLs (including localhost and 127.0.0.1 URIs for local development). In GitHub developer applications this feature seems to be lacking: Only a single URL can be specified.
>> 
>> Unfortunately, this causes unwanted issues. Can you tell us whether this is a valid design decision of yours, or whether this functionality is going to be changed to accomodate several URLs just as comparable services?
>> 
>> A related issue: https://github.com/pennersr/django-allauth/issues/1483
>> 
>> Thanks in advance for your valued support!
>> Peter

**Comment by pennersr** [comment]
Thanks for sharing. Given that multiple callback URLs may be possible in the future it is important that allauth keeps on communicating the URL to use so that github will know which one to pick in case multiple URLs were configured.

**Comment by solotvun** [comment]
Adding root_url solved my issue. Here is some doco to help out:
https://gist.github.com/buo/a324edf9d22d0a0a1c3043ded79052b2

**Comment by bnisevic** [comment]
If you defined authorization callback in the GitHub UI with https protocol than this setting solves the issue:
ACCOUNT_DEFAULT_HTTP_PROTOCOL='https'

This is coming from the answer found here: https://stackoverflow.com/questions/54784981/django-allauth-google-oauth-redirect-uri-mismatch-error?answertab=votes#tab-top

**Comment by Meet19aug** [comment]
I solved my github login<Social login problem:>

If anyone face these type of problem please check

https and http
<When you create OAuth Apps at url  https://github.com/settings/developers>

#2503 The redirect_uri MUST match the registered callback URL for this application

**Comment by 9mido** [comment]
@Meet19aug can you please share the way that you solved it? Also did you reference the wrong issue? How does 2503 have anything to do with this issue?

**Comment by Meet19aug** [comment]
I correct the url you can go through it

**Comment by ibukun-brain** [comment]
@bittner you're a life saver, this solution works 100% if you're using djoser for github authentication create, your custom backend by inheriting from github backend class, remove the redirect_uri params from both the auth_params and auth_complete_params method, in your get request social endpoint enter your redirect_uri.

**Note: ** after following the instruction the callback_url from github has priority over the redirect_uri provided, because it has been removed from the auth_params and auth_complete_params

**Comment by sdarwin** [comment]
The problem mentioned in the original post here:

> The GitHub auth provider is special in a way that you can only specify a single "Authorization callback URL" for an app in your [developer applications](https://github.com/settings/developers). This is problematic when your website is using
several domains, subdomains, etc., or
http and https interchangeably (i.e. both can be used).
Then the callback URL allauth passes on to GitHub to redirect to will not match in many cases, and you will face:
Social Network Login Failure
An error occurred while attempting to login via your social network account.
Other auth providers solve this by allowing several callback URLs, GitHub doesn't.

can now be solved with the "sites" framework, which django-allauth supports.  

On the GitHub side, set up multiple OAuth Apps, one for each domain.  Configure multiple sites in the django admin interface.    Assign sites to each social application, at `/admin/socialaccount/socialapp/`

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1483
