### ISSUE TITLE
Control of form rendering

### ISSUE THREAD

**Issue by yunti** [pennersr/django-allauth#1484]
i'm trying to precisely control how the forms within django allauth are rendered.  However I'm not clear how I can produce an output like:

    <input id="signup-password" type="password" class="form-control login-password" placeholder="Password">

for the signup form? If I just try to output an individual field from that form eg

{{ form.password1 }}

I can't seem to control the attributes.  What's the best way to achieve this in django allauth?

**Comment by pennersr** [comment]
Closing, this is not a specific issue in allauth.  You can always render the form field manually yourself.. Additionally, there are various Django projects that will assist in tweaking form rendering

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1484
