### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by alex-altay** [pennersr/django-allauth#1485]
First of all, thanks for the such a great tool.

I don't know where to write this bug actually, because it is not about functioning, but about docs.

In subsection 'Sending messages' of this [section](http://django-allauth.readthedocs.io/en/latest/advanced.html) it is said that 

> In case you want to include an HTML representation, add an HTML template as follows:
> account/email/email_confirmation_message.html

whereas actual template's name have to be 'account/email/email_confirmation_**signup**_message.html'

Makes you spend some time to find out why html-version of letters are not being sent. 

Please correct the docs.

**Comment by pennersr** [comment]
While I agree that the documentation is indeed lacking in various areas, I am adhering to the debatable principle that keeping open issues around with respect to documentation is not very helpful in improving things. Feel free to submit a pull request...

**Comment by alex-altay** [comment]
Thank you. I just didn't know I can simply submit it by myself. Now I've made that pull request.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1485
