### ISSUE TITLE
""/accounts/signup returns blank page

### ISSUE THREAD

**Issue by axelerate** [pennersr/django-allauth#1486]
All tutorials seem to indicate that when scaffolding a newly created project, there should be a basic signup page showing up if all settings and configurations are properly adjusted. I receive no such view.

**Comment by pennersr** [comment]
Please only file an issue when you find a concrete issue in allauth that is wrong. It is not feasible to start debugging external tutorials or project specific setups...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1486
