### ISSUE TITLE
Reverse for 'account_email' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried:

### ISSUE THREAD

**Issue by NikosVlagoidis** [pennersr/django-allauth#1488]
I don't even call the 'account_email' url?
![issue](https://cloud.githubusercontent.com/assets/10330520/18446320/816aa8bc-792a-11e6-8cb5-79098e0f5fe4.JPG)

**Comment by NikosVlagoidis** [comment]
I was using wrong namespace :(

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1488
