### ISSUE TITLE
HTML email confirmation template not used on sign up

### ISSUE THREAD

**Issue by userdefinable** [pennersr/django-allauth#1489]
I have a custom email_confirmation_message.html in /templates/account/email and I have deleted the corresponding .txt file.

This version is sent as expected when using the "resend confirmation" button on the /accounts/email page.

However, on sign up, the default allauth .txt version is sent instead.

I am using 0.27.0

**Comment by userdefinable** [comment]
Apologies, just noticed email_confirmation_signup_message.html

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1489
