### ISSUE TITLE
Automatic log in on sign up despite "mandatory" email verification

### ISSUE THREAD

**Issue by userdefinable** [pennersr/django-allauth#1490]
`SOCIALACCOUNT_ENABLED = True

USER_MODEL = 'auth.User'

ACCOUNT_AUTHENTICATION_METHOD = 'email'

ACCOUNT_EMAIL_REQUIRED = True

ACCOUNT_USERNAME_MIN_LENGTH = 4

SOCIALACCOUNT_QUERY_EMAIL = True

SOCIALACCOUNT_EMAIL_REQUIRED = True

SOCIALACCOUNT_EMAIL_VERIFICATION = False

ACCOUNT_EMAIL_VERIFICATION = 'mandatory'

ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True

ACCOUNT_LOGIN_ON_PASSWORD_RESET = True`

I have these directly in my settings.py

It's sending the email confirmation to the user, but it's automatically logging them in even though they are unverified (I checked db to confirm this in account_emailaddress).

I am using 0.27.0

**Comment by pennersr** [comment]
I am quite confident there is no issue in allauth on this matter. It is covered in tests, and there is only one place where as user gets logged in, and as you can see here...

https://github.com/pennersr/django-allauth/blob/master/allauth/account/utils.py#L144

... the mandatory check is in there *before* logging in.

In case you are logging in with Google, you'll automatically receive a verified email (and it is marked as such in the database), which might explain what you are seeing.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1490
