### ISSUE TITLE
Reddit provider is not documented

### ISSUE THREAD

**Issue by johndark** [pennersr/django-allauth#1494]
Hi,
there is no any words about Reddit provider in [documentation](django-allauth.readthedocs.io/en/latest/providers.html).

**Comment by pennersr** [comment]
https://django-allauth.readthedocs.io/en/latest/faq.html#why-did-you-just-close-my-issue

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1494
