### ISSUE TITLE
Put setting on urls.py to prevent `include('allauth.account.urls')`

### ISSUE THREAD

**Issue by fjsj** [pennersr/django-allauth#1497]
For very simple apps with third-party logins, only login and logout are necessary.  
Pages like `password/change/` or `confirm-email/` aren't desirable. Thus it would be great to have a setting to disable `urlpatterns = [url('^', include('allauth.account.urls'))]`.

Are you open to a PR addressing this?

**Comment by pennersr** [comment]
This will easily get out of hand. Some people want to disable password change, others, confirm email, and another group of wants to easily disable them both, and there are some other URLs as well. Basically, it would boil down to introducing a setting per URL to please everybody.  I would prefer to stick to the regular way of working in Django: if you don't like the urls that are offered out of the box, don't use them and provide your own urls.py where you have fine grained control to whatever routing you want to realize...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1497
