### ISSUE TITLE
Link social accounts

### ISSUE THREAD

**Issue by rakanalh** [pennersr/django-allauth#1499]
Hello,

I am working on an app that enables the users to sign up using any social accounts or sign up the regular way (email, password) which is provided by allauth (Thank you!).

However, if the user signs up using an email & password as an example, and then tries to link other social accounts such as google or facebook for example, the unique email validation kicks in with "email not unique" error.

Is what i am trying to achieve possible? i have gone through the list of configuration but it doesn't seem like anything is provided. 

Please advise.
Thanks

**Comment by rakanalh** [comment]
nevermind, i should have searched before asking here.

**Comment by steverecio** [comment]
@rakanalh where did you find the solution to this? I have the same exact issue but can't find the answer anywhere

**Comment by steverecio** [comment]
Answere is here for anyone else looking: https://github.com/pennersr/django-allauth/issues/418

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1499
