### ISSUE TITLE
BaseSignupForm overrides fields and logic on custom signup forms.

### ISSUE THREAD

**Issue by folz** [pennersr/django-allauth#1501]
Given this custom.SignupForm:

```
# custom.py

class SignupForm(forms.Form):
    email = forms.EmailField(label=_('email address'))
    email2 = forms.EmailField(label=_('re-enter email'))
    password = forms.CharField(label=_('new password'), widget=forms.PasswordInput)

    def signup(self, request):
        pass
```

When it is rendered in accounts.views.SignUpView, the label for email2 will always be set to `_('E-mail address confirmation')` and never `_('re-enter email')`. The widgets for email and email2 will always be `TextField()`, not `EmailField()`. The `password` field will be inserted in between email and email2. This is very inflexible for rendering forms/help-text, collecting data, and translating strings.

![screenshot from 2016-09-26 13-37-40](https://cloud.githubusercontent.com/assets/299281/18850921/785ab3a6-83ee-11e6-8fab-f537d0842e13.png)

This is because the view loads  `SignupForm`, which treats the `custom.SignupForm` as a parent class (and overrides custom fields, `__init__()`, `clean()`, etc).

One possible solution: have the built-in SignupForm and custom.SignupForms inherit from BaseSignupForm. Require custom.SignupForms to provide username/email/email2 as declared by settings. Do not modify fields in BaseSignupForm's `__init__()` -- the logic for default forms can be moved to SignupForm; otherwise, assume the author of the custom form has provided all necessary fields for their settings. In the default signup View, have a `form = get_signup_form()` function similar to get_user_model() that loads either the custom form or the default form, depending on settings.

**Comment by pennersr** [comment]
Custom signup forms, by design, are only intended to ask additional questions, not for adding fields that are already handled by allauth. If you want to alter the forms allauth itself uses, including all the password/email fields, see the setting (SOCIAL)ACCOUNT_FORMS.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1501
