### ISSUE TITLE
DataError at /accounts/google/login/callback/ value too long for type character varying(1)

### ISSUE THREAD

**Issue by flexpeace** [pennersr/django-allauth#1502]
I just upgraded my Django version to 1.10.2 and l am using PostGresSQL and am getting the attached error after successful callback from either Facebook or Google.  i am using allauth 0.27.0

I need help

![screen shot 2016-10-02 at 7 09 16 pm](https://cloud.githubusercontent.com/assets/5002192/19021878/d603622a-88d3-11e6-91f9-30280b8e029e.png)

**Comment by flexpeace** [comment]
![screen shot 2016-10-02 at 7 40 43 pm](https://cloud.githubusercontent.com/assets/5002192/19022085/2d554abc-88d8-11e6-9fa7-3818435eb0b6.png)

**Comment by flexpeace** [comment]
Issue fixed. Thanks

**Comment by vpsinghg** [comment]
@flexpeace can you tell me how to fix this issue ?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1502
