### ISSUE TITLE
DefaultAccountAdapter breaks when AUTH_USER_MODEL is set

### ISSUE THREAD

**Issue by folz** [pennersr/django-allauth#1503]
Allauth hardcodes the field names of a generic User modelform.

This breaks AUTH_USER_MODEL. In my use case, I renamed first_name and last_name to given_name and family_name, and was confused why it wasn't set.

From account/adapter.py#228:
```
        data = form.cleaned_data
        first_name = data.get('first_name')
        last_name = data.get('last_name')
        email = data.get('email')
        username = data.get('username')
        user_email(user, email)
        user_username(user, username)
        if first_name:
            user_field(user, 'first_name', first_name)
        if last_name:
            user_field(user, 'last_name', last_name)
        if 'password1' in data:
            user.set_password(data["password1"])
        else:
            user.set_unusable_password()
```

**Comment by pennersr** [comment]
If you customize things, allauth has no way of knowing how things are named. Exactly for that purpose the adapters are there, you should provide your own adapter and adjust things to your particular project specific customizations.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1503
