### ISSUE TITLE
pypi version appears to be version prior to 0.8.2 release

### ISSUE THREAD

**Issue by devdave** [pennersr/django-allauth#151]
http://pypi.python.org/pypi/django-allauth/0.8.2

0.8.2 is supposed to have the modified ACCOUNT_EMAIL_VERIFICATION

but it looks like the source code checked into PyPI is still 0.8.1.

Any chance going forward you could also tag your releases in github?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/151
