### ISSUE TITLE
Password Reset Timeout

### ISSUE THREAD

**Issue by krippee** [pennersr/django-allauth#1513]
I am not seeing a setting for PASSWORD_RESET_TIMEOUT anywhere in the code, is that because the default django password reset is being used or does allauth simply not support this?

**Comment by pennersr** [comment]
allauth uses the Django `default_token_generator`, which by default equals`PasswordResetTokenGenerator()`. So, the timeout is supported but resides in the Django code....

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1513
