### ISSUE TITLE
How to force user to pick a new username during sociallogin?

### ISSUE THREAD

**Issue by jleclanche** [pennersr/django-allauth#1516]
Is there a way to raise a condition from a social login adapter that will _require_ the user to pick a new username (eg. through a form)? How would I go about doing that?

The problem being that if the user's name already exists, or I don't receive a valid username from the upstream API, I don't want my users hanging around with the username `user1`.

**Comment by myvirtualarena** [comment]
Yes, we are also wondering if there is a solution for this. In this case, for Facebook social login

**Comment by pennersr** [comment]
You can override the `is_auto_signup_allowed` in the social adapter.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1516
