### ISSUE TITLE
User without confirmed email can login

### ISSUE THREAD

**Issue by BenDevelopment** [pennersr/django-allauth#1518]
Here is my settings:

```
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = "my_email@gmail.com"
EMAIL_HOST_PASSWORD = "my_password"
EMAIL_PORT = 465
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_CONFIRMATION_SIGNUP = False
CONFIRM_EMAIL_ON_GET = False
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True   
ACCOUNT_USERNAME_REQUIRED = False
```
When I create an account, I want the user to not be authorized to login before the email is confirmed.
It works like a charm on my local machine (localhost), but it doesn't works on my digital ocean server. On my server, the user can login even if the email is not confirmed. Any idea to fix this?
(And another problem is that the email is not sent on me version server, but is it on my localhost, but maybe this problem comes from another part of Django)

**Comment by pennersr** [comment]
Sorry, I will have to close this as I am convinced this is an issue in your server deployment, not in allauth. Btw, these settings are not from allauth, not sure if they are misspelled:

```
EMAIL_CONFIRMATION_SIGNUP = False
CONFIRM_EMAIL_ON_GET = False\
```

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1518
