### ISSUE TITLE
Office 365

### ISSUE THREAD

**Issue by oscarmcm** [pennersr/django-allauth#1519]
Hi, there is a possibility to add support for Office 365?

I found one tutorial here

https://blogs.msdn.microsoft.com/exchangedev/2015/01/05/office-365-apis-and-python-part-1-oauth2/

**Comment by pennersr** [comment]
allauth is about authentication, and Windows Live is already supported. The Office365 APIs you are linking to are not related to authentication. You'll have to hook these up yourself, but you can build on the fact that allauth already allows users to authenticate with Windows Live.

**Comment by jeanbaptistelab** [comment]
I've implemented an allauth provider for Office 365 as we needed this for an internal app at work, if there's still an interest, I'll see how I can get this under the MIT license for public release.

@pennersr would you be OK absorbing this into the allauth code base or would you rather have it in a separate repo as a plugin?

Cheers,

JB

**Comment by pennersr** [comment]
I was hoping that the Office 365 oauth flow was unifiable somehow with that of the Windows live, but I must admit that I have not done any research on this topic. In any case, I am definitely interested in providing out of the box support for Office 365...

**Comment by azolson** [comment]
thanks for all of your work on Django-allauth 
any updates on Office 365? would be nice to have it supported

**Comment by mosspaper** [comment]
+1 on Office 365 oauth provider

**Comment by jmkovachi** [comment]
Are there any updates on office 365 support? Thanks

**Comment by dwasyl** [comment]
+1 and I'll throw in that while not quite Office 365, I recently stumbled across [https://github.com/thenewguy/django-allauth-adfs](https://github.com/thenewguy/django-allauth-adfs) which has oauth code for ADFS (which I think is the same authentication engine as Office 365)

**Comment by chadgates** [comment]
+1 for Office365

**Comment by xandervolt** [comment]
I'd also like Office365 support. Thanks for the awesome app

**Comment by Lamelos** [comment]
Using https://github.com/thenewguy/django-allauth-adfs
I implemented an office365 provider, available here: https://github.com/Lamelos/django-allauth-office365
Got it working locally. PR's are welcome.

Important, create your tokens through: https://apps.dev.microsoft.com

**Comment by xandervolt** [comment]
Awesome! Thank you very much!



Sent from my Sprint Samsung Galaxy S7.


-------- Original message --------

**Comment by alfonsrv** [comment]
M365 is now officially supported, even though it's not mentioned on the [website](https://www.intenct.nl/projects/django-allauth/). This issue can be closed.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1519
