### ISSUE TITLE
Soundcloud provider

### ISSUE THREAD

**Issue by subha-py** [pennersr/django-allauth#1520]
Hi, I am new to django all auth. I would like to advise a feature enhancement to django all auth.
I would be good if you add soundcloud in a provider. Or you can help me to show how to integrate soundcloud as a provider in django all auth. I will fork and pull request if I can do it successfully.

[soundcloud api](https://developers.soundcloud.com/docs/api/guide) this is a link I think would be useful
Thanx

**Comment by pennersr** [comment]
See: https://github.com/pennersr/django-allauth/tree/master/allauth/socialaccount/providers/soundcloud

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1520
