### ISSUE TITLE
Battle.net China implementation

### ISSUE THREAD

**Issue by jleclanche** [pennersr/django-allauth#1521]
Hey @pennersr, I need your thoughts on this.

Here's how the Battle.net API works:
- You can contact any of a handful of regions (`us`, `eu`, `sea`, `kr`, `tw`), all of them have the same API layout
- Accounts across _all_ regions are shared, thus you can make requests against `us.battle.net` for `eu` accounts, and vice versa.
- There is an additional API region, `cn`, which uses mostly the same API layout but a different base URL for API and Account API (this is correctly handled in allauth 0.28). The accounts in the `cn` region are _not_ shared across the other regions - it's a different database.
- The account API sends a dict with an `id` (the UID) and, most of the time, a battletag (username). The `id` is guaranteed unique across regions, but I do _not_ think it is unique across china and the other regions

My plan right now is to publish a test instance of my site using the China-specific endpoints and observe what happens and how the API behaves. I want to do it as close to the way we'll end up implementing it upstream. This is where I need some help.

My current thinking: I have created a custom, china-specific provider and adapter, which subclass their respective BattleNet classes.

Now, despite using a (suspected) different account database, the OAuth database is _synced_ across China and ROTW. That means the SocialApp API keys are the same across all regions. This means we can't straight up create a separate provider... right?

So considering all this... how would I do the following and actually be able to use it for the battlenet app?

``` py
from allauth.socialaccount.providers.battlenet.provider import BattleNetProvider
from allauth.socialaccount.providers.battlenet.views import BattleNetAdapter


class BattleNetChinaProvider(BattleNetProvider):
    id = "battlenet_cn"
    name = "Battle.net (China)"

    def extract_uid(self, data):
        return str(data["id"]) + "-cn"


class BattleNetChinaOAuth2Adapter(BattleNetAdapter):
    battlenet_region = "cn"
    battlenet_base_url = "https://www.battlenet.com.cn"
    battlenet_api_url = battlenet_base_url + "/api"

    def get_provider(self):
        return BattleNetChinaProvider(request=self.request)
```

**Comment by jleclanche** [comment]
I guess that, if we make an *explicitly separate* `battlenet_cn` socialaccount provider, then all I would need is a way to override whatever mechanism gets the matching socialapp from `battlenet` instead of requiring creation of a separate `battlenet_cn` socialapp. But how?

**Comment by pennersr** [comment]
@derek-adair  See: https://github.com/pennersr/django-allauth/discussions

**Comment by derek-adair** [comment]
Oh! this is fantastic i wasn't aware of this.

**Comment by pennersr** [comment]
@jleclanche Is this still relevant? Preferably, I would stick to having just one Battlenet provider and use settings to configure things.

**Comment by pennersr** [comment]
Moved to https://codeberg.org/allauth/django-allauth/issues/1521
