### ISSUE TITLE
How about add to provider information?

### ISSUE THREAD

**Issue by zgraywolfz** [pennersr/django-allauth#1525]
Hi.
first...my english skill is low
understand to this

I have a question and ask to this

used to this - django-allauth
now access to facebook, google, instagram

first success to login - socialaccount
and (local or django access to DB) - account is find to this info
account - admin page login and Auth User page
this point...my question
3 providers possible
but account not find to providers info

I want to look at account page add to providers
only add to provider name

thanks

**Comment by pennersr** [comment]
https://django-allauth.readthedocs.io/en/latest/faq.html#why-did-you-just-close-my-issue

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1525
