### ISSUE TITLE
Django all_auth and custom form compatibility

### ISSUE THREAD

**Issue by prafulbagai** [pennersr/django-allauth#1526]
I'm using [django allauth]() for social login/signup. Also, I've my own signup form as an alternate login/signup. Following are the fields that I'm fetching from the user in the alternate form.

    class Profile(models.Model):
        col1 = models.CharField(max_length=50, blank=True, null=True)
        col2 = models.CharField(max_length=50, blank=True, null=True)
        user = models.OneToOneField(User)

So, when the user signs up, it asks for additional fields as well(`col1`, `col2`), apart from `username`, `email` and `password`.

Following is the signup view.

    user = User.objects.create_user(username, user_email, user_pass)
    Profile.objects.create(user=user, col1=col1, col2=col2)
    return

So, whenever the user signs up via the alternate form, the above view is called up.

Now, in contrast, when the user signs up from social account FB, it does not ask for extra info, ie `col1/col2`. It directly signs up without asking for extra info, neither I want it to ask. 

I then create a row in `Profile` model post signup using signals.

    @receiver(user_signed_up)
    def create_profile(request, user, sociallogin=None, **kwargs):
        if sociallogin:
            if sociallogin.account.provider == 'facebook':
                data = sociallogin.account.extra_data
                col1 = data.get('col1')
                col2 = data.get('col2')
                Profile.objects.create(user=user, col1=col1, col2=col2)

So, (1) my problem is when creating a user using alternate form, no record is inserted in `allauth` tables, *which i find weird*. 

(2) Consider, I signed up using alternate form using E1 as email id. Now I signup via `allauth(FB)` with the same id. how do I make sure it throws an error of already signed up.? Currently it asks for a new username.

(3) How do I send confirmation mail to the users who signed up in alternate form using `all_auth`.

**Comment by prafulbagai** [comment]
@pennersr - Please share your valuable thoughts on it.

**Comment by pennersr** [comment]
In order to implement the above you do not need to create your own signup views/forms. Simply define a form containing fields for col1 and col2, similar to what is suggested here:

http://stackoverflow.com/questions/12303478/how-to-customize-user-profile-when-using-django-allauth/12308807#12308807

Then, make sure that `SOCIALACCOUNT_AUTO_SIGNUP` is set to `False` -- otherwise the form is bypassed for social users. In the `signup` method of the form, you can create the user profile...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1526
