### ISSUE TITLE
return error if permission is not provided by the user.

### ISSUE THREAD

**Issue by prafulbagai** [pennersr/django-allauth#1527]
Is there any setting that returns an error if user does not provides me the permission to fetch details of his/her profile? For eg:- `email` in FB login. Now, when a user does not `tick` the email permission field, allauth asks for email spearately. 

Can I return an error saying, `unable to login because the required permissions were not provided`.??

**Comment by prafulbagai** [comment]
@pennersr - Please share your valuable thoughts on it.

**Comment by pennersr** [comment]
This is not something offered out of the box. Yet, you can hook up to the `pre_social_login` signal which contains all info on the social account that is in the process of being logged in. Here, you could check for email, and abort if not present.

**Comment by zgraywolfz** [comment]
HI. allauth master

so sorry
used to github my skill very low

thanks for your help


2016-11-10 5:41 GMT+09:00 Raymond Penners <notifications@github.com>:

**Comment by prafulbagai** [comment]
Thanks @pennersr.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1527
