### ISSUE TITLE
Facebook js_sdk not working

### ISSUE THREAD

**Issue by JetUni** [pennersr/django-allauth#1529]
I'm not sure why this isn't working. I was using oauth2 and everything was working great with it, but it was decided that we want to use the `js_sdk` instead because of its benefits.

`settings.py`
```
SOCIALACCOUNT_PROVIDERS = \
    {'facebook':
        {'METHOD': 'js_sdk',
         'SCOPE': ['email', 'public_profile'],
         'FIELDS': [
             'id',
             'email',
             'name',
             'first_name',
             'last_name',
             'verified'],
         }
     }
```

`login.html`
```
{% extends "base.html" %}
{% load socialaccount %}
{% providers_media_js %}
...
<a href="{% provider_login_url "facebook" method="js_sdk" %}" class="col-md-offset-2">
    OR Login with Facebook
</a>
...
```

And this is the error I get in the console when I click on that link:
`Uncaught ReferenceError: allauth is not defined(…)(anonymous function) @ VM2574:1`

**Comment by pennersr** [comment]
You'll need to debug your HTML a bit, double check that the allauth fbconnect.js script is loaded (providers_media_js should normally output that).

**Comment by JetUni** [comment]
providers_media_js should normally output facebook.js? And if so, are you talking about output to the console? I'm looking in Sources with Chrome's debugging tools and I don't see any "fbconnect.js" there.

**Comment by SurajT22** [comment]
{% load socialaccount %}
{% providers_media_js %}
use this loader in register.html and login.html files
and the  settings.py file you used INSTALLED_APPS = [
#social account login
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.google',


]

#Facebook & Google
SITE_ID = 1

it is work for me

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1529
