### ISSUE TITLE
Custom fields in user model

### ISSUE THREAD

**Issue by arkkanoid** [pennersr/django-allauth#1530]
I've created a custom user model with two extra-fields: 'is_company' and 'company'. When I sign up, In the database I see two entries in the user's table: One without the extra-fields and another with the extra-fields. 
It seems like first allauth save the user and then my custom user form saves another.

models.py:

    from django.contrib.auth.models import AbstractUser
    
    class hcuser(AbstractUser):
        company = models.CharField(max_length=30, null=True, blank=True)
        is_company = models.BooleanField(default=False)

forms.py:

    from django.db import models
    from django.forms import ModelForm
    from django import forms
    
    from django.contrib.auth.forms import UserCreationForm
    from hc.models import hcuser
    
    class LocalSignupForm(UserCreationForm):
    	email = forms.EmailField(required=True)
    
    	class Meta(UserCreationForm.Meta):
    		model = hcuser
    		fields = ('last_login', 'email', 'first_name', 'last_name', 'company','is_company')
    
    	def save(self, commit=True):
    		user = super(LocalSignupForm, self).save(commit=False)
    		user.email = self.cleaned_data["email"]
    		if commit:
    			user.save()
    		return user

Also I replaced save() to: 

    def signup(self, request, user):
    	user = super(LocalSignupForm, self).save(commit=False)
    	user.email = self.cleaned_data["email"]
    	user.save()	

With the same result.

**Comment by pennersr** [comment]
The custom signup form should be a simple form that only contains the additional fields to query for, it should not contain user model related fields or be a user based model form.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1530
