### ISSUE TITLE
facebook require password prompt

### ISSUE THREAD

**Issue by andrewt82** [pennersr/django-allauth#1531]
How to disable password prompt for users via facebook auntefication?
![fb_pass](https://cloud.githubusercontent.com/assets/15378087/20247511/0a4ac592-a9df-11e6-8a78-bc69d67aacb9.png)

**Comment by prafulbagai** [comment]
'AUTH_PARAMS': {'auth_type': 'rerequest'},

**Comment by ck9sky** [comment]
Thank you so much!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1531
