### ISSUE TITLE
django cannot serialize <owslib.wps.Process object at 0x7f7f880e02b0> (type Process)

### ISSUE THREAD

**Issue by elnazazmi** [pennersr/django-allauth#1535]
Hello!

I use django 1.10 and execute a WebProcessingService using owslib in a django view. 
It works very well when I run my code in a separate python file. But when I run it in django it displays an error "cannot serialize <owslib.wps.Process object at 0x7f7f880e02b0> (type Process)".
In debug mode I see that the error raises in the "django/core/handlers/base.py" at the "_get_response()".
This is my code:

from owslib.wps import WebProcessingService
wps = WebProcessingService('http://localhost:8094/wps', verbose=False, skip_caps=True)
input = [('user', 'Hello')]
execution = wps.execute('helloworld', input, output=None)
print(execution.status)

This is an screen-shot of the debug mode:
![django_debug](https://cloud.githubusercontent.com/assets/20579300/20425750/4452372a-ad7c-11e6-8123-a1c2c6e08869.png)

**Comment by elnazazmi** [comment]
Hello,

I found the cause of the error, that was in my process identifier.
Then I close this issue :-)

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1535
