### ISSUE TITLE
Confirm email in french wrong page redirect

### ISSUE THREAD

**Issue by retosteffen** [pennersr/django-allauth#1536]
After clicking on the link in the email to confirm ownership of the email I get sent to
/fr/comptes/confirm-email/TOKEN
Then clicking on the confirm button sends me to:
/accounts/login/ (which doesn't exist)
instead of:
/en/accounts/login/
or even better
/fr/comptes/login

All this works perfectly in english!

**Comment by pennersr** [comment]
Related #1330

**Comment by retosteffen** [comment]
Yes that was it.
Perfect! Thanks.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1536
