### ISSUE TITLE
SocialAccount.uid: max_length 255 still present - MySQL utf8mb4

### ISSUE THREAD

**Issue by acenario** [pennersr/django-allauth#1539]
Hi,

I noticed that in commit [faf4ca5](https://github.com/pennersr/django-allauth/commit/faf4ca57bc8d2c03104b5bed7809ad7074f94825) you fixed social_account uid with a max length of 191. You also made a second migration to address this. 

However, when running on a new project and migrating for the first time with a MySQL schema using a utf8mb4 collation, the initial migration ignores the setting and still uses a 255 limit. 

This breaks the initial migrate command, turning it into a manual fix. To fix this, the initial migration would also need to implement the `SOCIALACCOUNT_UID_MAX_LENGTH`. 

I fixed this by going into site-packages directory and manually editing the initial 0001 migration file. I can turn this into a pull request in a little bit. 

Thanks,

Arjun

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1539
