### ISSUE TITLE
 Can we override the way all-auth selects Provider

### ISSUE THREAD

**Issue by veris-neerajdhiman** [pennersr/django-allauth#1542]
This is a  wearied requirement but somehow I have this 

- I wants users to enables same provider with different credentials in their apps. 
- Like if user wants to add goggle provider in their account he wants to register two apps with google provider, then he adds two social apps `Google_1, Google_2` from admin panel. 
- On signIn form user sees google sign in button , but when he clicks on that button , he will receive an error saying `MultipleObjectsReturned` , which is true according to current implementation. 

One way of solving this with current functions to 
- add both providers google_1 and google_2 in different site domains. 
- Second possible way (if you want both providers on same domain name ) will be to somehow you know which providers will be return on signin click. 

I was thinking to change the url  `/accounts/<some_key>/google/login/?process=login` and based on `<some_key>` in url I can select the provider

So If there is any way to update Provider selecting method please let me know.

**Comment by pennersr** [comment]
Having multiple providers of the same kind active for one and the same site is currently not possible. I am really doubting if there is an actual valid use case for this, so I prefer to not introduce this level of complexity in the code.

**Comment by veris-neerajdhiman** [comment]
@pennersr 

- No problem at all and I absolutely agree with you until there is any valid use case, no need to introduce unwanted complexity.
- So talking about the use case, Let me give you an example may be it gives you a clear idea.
- Lets take [`Auth0`](https://auth0.com/) as use case. 
   - It allows users to add their social accounts. Now here anyone can select `Google` as a provider (save their app details and all that). 
  - I don't know how they are handling this at backend, but if we talk w.r.t `all-auth`, either they are issuing separate domains (and users have no idea about this) to users whoever choose `Google` as a Provider and somehow using `middlewares` to redirect common url (auth0.com) to user specific url so that `all-auth` can determine which `Google` Account user is using and validate the request. 

  - Similarly to Auth0 but in my case instead of users I have `organizations`, each `organization` can enable some `Providers` from using those organization members can login to organization. Now here `site-provider` tight coupling becomes an issue. So to solve this problem , I have issued sub-domains to organization and that solved my problem for now.

- I am not sure whether taking `Auth0` as an example is a good idea or not. But I hope at-least you get an idea what I am thinking or trying to explain to you and I am not hoping you will introduce such complexity in this `lib` but at least if you can confirm that `Auth0` was  a valid use case or not will be enough for me. 

Thanks

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1542
