### ISSUE TITLE
This is a non-secure form.

### ISSUE THREAD

**Issue by macmichael01** [pennersr/django-allauth#1543]
Hello, I think my team may have found a bug but perhaps my engineers forgot to enable a setting on the backend.

When trying to login through Facebook my team is receiving the following message in Safari (and only in Safari):

> This form will be sent in a way that is not secure. Are you sure you want to send it?

It may be helpful to note that we are using SSL.

Digging through the web console I see the following error:

The page at https://example.com/sign-in/ contains a form which targets an insecure URL http://example.com/facebook/login/token/.

The line in JS that it's referring to is: `this.opts.loginByTokenUrl`

```
        onLoginSuccess: function(response, nextUrl, process) {
            var data = {
                next: nextUrl || '',
                process: process,
                access_token: response.authResponse.accessToken,
                expires_in: response.authResponse.expiresIn,
                csrfmiddlewaretoken: this.opts.csrfToken
            };

            postForm(this.opts.loginByTokenUrl, data);
        },
```

We even tried setting this variable to https with the same results:
ACCOUNT_DEFAULT_HTTP_PROTOCOL = "https"

Is there something obvious that we could be doing wrong here? This only happens in Safari as well.

**Comment by pennersr** [comment]
Closing, this is unlikely to be an allauth issue. For example, /sign-in/ is not a page offered by allauth.

**Comment by macmichael01** [comment]
Sorry, that should refer to the default allauth login url (that was my custom url pattern).

**Comment by macmichael01** [comment]
Please re-open. This is a bug.

**Comment by pennersr** [comment]
In your case, `loginByTokenUrl`, is a non-secure URL. It is assembled like this:

```
"loginByTokenUrl": abs_uri('facebook_login_by_token')
...
def abs_uri(name):
    return request.build_absolute_uri(reverse(name))
```

So, as far as allauth is concerned, the protocol of the `request` is used. I cannot conclude there is a bug here on the side of allauth.

**Comment by macmichael01** [comment]
Ok, I see issue. My apologies. That was a tricky issue. For anyone else having this problem, solutions may vary depending on how your Django app has been configured in a production setting.

We were using nginx + uwsgi and our solution was to set `SECURE_SSL_REDIRECT = True` under `settings.py` and to add the following param to our nginx config `uwsgi_param HTTP_X_FORWARDED_PROTO  $scheme;` so that nginx + uwsgi does not get caught up in a redirect loop.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1543
