### ISSUE TITLE
Allauth is not used by django admin

### ISSUE THREAD

**Issue by JelteF** [pennersr/django-allauth#1544]
If you go to django admin without being logged in you cannot log in using a provider except for password, because it has a custom login page. This can be fixed in the following way:

```
admin.site.login = login_required(admin.site.login)
```

I'm unsure if this can be fixed automatically but it should at least be added to the README. I reported this originally to https://github.com/percipient/django-allauth-2fa/issues/40, because it's a security issue there. But I agree with the author that allauth itself would be a better place to fix it.

**Comment by pennersr** [comment]
I wouldn't want to go as far as to do this by default out of the box, but documenting it is of course nice. Feel free to submit a pull request on the documentation ...

**Comment by clokep** [comment]
I wonder if the class-based auth views being added to Django 1.11 would help with this at all?

**Comment by JelteF** [comment]
What's the issue with doing this by default if there's a setting with which you can turn it off? It seems like this would be the desired behaviour. Otherwise an admin with only oauth login cannot access the admin without manually going to the allauth login page.

**Comment by pennersr** [comment]
Sorry guys, but I don't like to start monkey patching default Django behavior, nor is it warranted to add a setting for something a one liner like this. Feel free to submit a PR on documentation, other than that, I am closing this issue...

**Comment by ivanvenosdel** [comment]
@JelteF Thanks for your sample it was very helpful. Having it in the docs would be a big improvement.

**Comment by clokep** [comment]
Note that this is vaguely documented in the [release notes for 0.25](http://django-allauth.readthedocs.io/en/latest/release-notes.html?highlight=admin#id17):

> In order to be secure by default, users are now blocked from logging in after exceeding a maximum number of failed login attempts (see `ACCOUNT_LOGIN_ATTEMPTS_LIMIT`, `ACCOUNT_LOGIN_ATTEMPTS_TIMEOUT`). Set `ACCOUNT_LOGIN_ATTEMPTS_LIMIT` to `None` to disable this functionality. Important: while this protects the allauth login view, it does not protect Django’s admin login from being brute forced.

I've put up a PR for adding this to the full documentation. Please feel free to suggest changes!

**Comment by JelteF** [comment]
I didn't know setting existed, so that means it's also a security issue in regular allauth.

**Comment by pennersr** [comment]
That is a matter of perspective. Django ships without any such protection, so apparently the Django developers do not regard this as a security issue. Therefore, I am not picking this up as a security issue for allauth.

**Comment by JelteF** [comment]
Alright, although I do not agree. Allauth is adding extra security features and being able to bypass those is IMHO definitely a security problem, regardless of the fact that django itself has these features or not. People might expect to have improved security by installing this library because it has the `ACCOUNT_LOGIN_ATTEMPTS_LIMIT` setting, but that is not actually the case because the Django "backdoor" is not removed.

**Comment by ivanvenosdel** [comment]
@JelteF Though your point, arguably, falls into a grey area with django-allauth it most certainly applies to the need for Django adding brute force protection to the admin login. If you decide to direct your passion to improving Django itself (where it will have a much bigger impact anyway) and link the ticket here I will happily add my support in it's comments. :)

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1544
