### ISSUE TITLE
Email confirmation field not ordered correctly

### ISSUE THREAD

**Issue by 29axe** [pennersr/django-allauth#1552]
Hi, 

I'm having a problem with the signup page. 
When I set `ACCOUNT_EMAIL_VERIFICATION = 'mandatory'`, the field `email2 ` is printed after `password2` field, which is not where it's supposed to be. (cf. image)

Does anybody noticed this behavior or has a solution to reorder it?

Thank you

![django-allauth](https://cloud.githubusercontent.com/assets/8787921/20877193/3dc94ca6-bac7-11e6-9973-bf43216f1cb1.PNG)

Django: 1.10
Allauth: 0.29
Python: 3.5.2

**Comment by juandgc** [comment]
Same here

**Comment by pennersr** [comment]
Closed via 882030ced0584457448bdcf548a6c482fd66a827

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1552
