### ISSUE TITLE
Key (username)=() already exists.

### ISSUE THREAD

**Issue by mullerivan** [pennersr/django-allauth#1554]
I just have an empty app, when trying to create the second user i got the  username error.
i dont wanna  user username anymore....

Settings.py

`
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_UNIQUE_USERNAME = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'

SOCIALACCOUNT_AUTO_SIGNUP = False
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_LOGIN_ATTEMPTS_LIMIT = 5
ACCOUNT_LOGIN_ATTEMPTS_TIMEOUT = 300
`

any clue  of what im doing wrong?

**Comment by pennersr** [comment]
Apparently, `ACCOUNT_USER_MODEL_USERNAME_FIELD = None` is not correct, it basically instructs allauth that there is no `username` column. Put it to `"username"`

**Comment by mullerivan** [comment]
well sounds more sense like i shall set it to "email"....

**Comment by pennersr** [comment]
No, don't set it to `email`... your database has a `username` column that needs to be filled. Only set it to `None` if your user model does not have any `username` at all.

**Comment by mullerivan** [comment]
Gracias amigo

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1554
