### ISSUE TITLE
Once Email Confirmation is Clicked, skipped immediately to LOGIN_REDIRECT_URL

### ISSUE THREAD

**Issue by myvirtualarena** [pennersr/django-allauth#1559]
Is there a way to skip the step of "Email_confirm.html"? Once a user receives an email with the token. He clicks and straightaway gets verified and login without hitting the "confirm email"?

**Comment by pennersr** [comment]
See ACCOUNT_CONFIRM_EMAIL_ON_GET

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1559
