### ISSUE TITLE
Add support for JustGiving and Virgin Money Giving

### ISSUE THREAD

**Issue by spool** [pennersr/django-allauth#1561]
Hi! Thanks for developing and maintaining such a useful library 👍 

Could support for [JustGiving](https://api.justgiving.com/) be added, perhaps following: https://github.com/omab/python-social-auth/pull/728 

If possible (though I'm guessing trickier) [Virgin Money Giving](https://developer.virginmoneygiving.com/our_apis) would be great as well.

**Comment by pennersr** [comment]
Support can surely be added, though it's not something I am planning to work on myself... feel free to open a pull request.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1561
