### ISSUE TITLE
overriding default templates of django-allauth

### ISSUE THREAD

**Issue by mariammwanje** [pennersr/django-allauth#1564]
Hello,
Am new to django and l was trying out the allauth authentication but , I can't get my templates to work as l expect them to, I can display my templates normally using accounts/login , accounts/logout or accounts/signup, properly.I would like to change there display but it seems not to work even if I clone the repo in my project directory.

**Comment by kas** [comment]
This should help you
https://stackoverflow.com/questions/9437545/overriding-default-templates-of-django-allauth

**Comment by pennersr** [comment]
https://django-allauth.readthedocs.io/en/latest/faq.html#why-did-you-just-close-my-issue

**Comment by mariammwanje** [comment]
It worked ....thanks

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1564
