### ISSUE TITLE
Activate URL creates security risk on Azure server

### ISSUE THREAD

**Issue by hassanabidpk** [pennersr/django-allauth#1568]
I am getting a security error when user clicks on the activate URL. I think it is happening because of some special characters in the KEY such as `:` . Is there any way to create the key without special characters.

You can check this special  URL : http://www.umapit.co/accounts/confirm-email/NQ:1cJZW8:rGof7zGm1ZsdawaCEMieOvJ-pdc/

If I remove `:` from the URL. then it behaves normally.

**Comment by pennersr** [comment]
https://www.quora.com/Is-it-safe-to-use-a-colon-in-the-path-of-a-URL

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1568
