### ISSUE TITLE
Facebook User Likes Requires Review

### ISSUE THREAD

**Issue by heyamykate** [pennersr/django-allauth#1571]
Just a heads up - accessing user likes via the Facebook API now requires you to submit a formal request to Facebook with a screencast and explanation of why you need that permission (they seem to be matching Instagram's new policy), so no matter what you put in the scope for Facebook in settings.py, you will not be able to access user likes.
Here is the link for their new guidelines: https://developers.facebook.com/docs/facebook-login/permissions/#reference-user_likes

**Comment by pennersr** [comment]
Thanks for the heds up. Closing, as this is not an allauth issue...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1571
