### ISSUE TITLE
Social login appending fragment to redirect URL.

### ISSUE THREAD

**Issue by mokibenjak** [pennersr/django-allauth#1579]
Upon logging in with some social network accounts, the redirect URL gets a fragment appended. For example, Facebook is appending `#_=_` (see here for more details: #241). Similarly, LinkedIn is adding `#!` and Google `#`. The problem is that sometimes these fragments break website-specific JavaScript code, or initiate some weird page scrolling. The Facebook/LinkedIn fragments can be dealt with on the client-side (see again #241), but I would prefer to be able to deal with the fragments on the server. Is there a possibility to modify the redirect URL (i.e. remove the URL fragment) after successful social login in allauth/Django? Any comment on the issue would be appreciated.

**Comment by tanzaho** [comment]
Yes, you can create a custom adapter `MySocialAccountAdapter` (set it in your settings : `SOCIALACCOUNT_ADAPTER = 'yourapp.adapter.MySocialAccountAdapter'`) and in this adapter, define your own `get_connect_redirect_url()` function. 

For instance, mine is :

```
def get_connect_redirect_url(self, request, socialaccount):
	"""
	The user should already be connected, let's redirect to the settings page
	"""
	dashboard_url = "http://mysite.com"

	if (socialaccount.provider == "linkedin"):
		redirect_url = unicode(dashboard_url) + "/#/linkedin/select_account"
	elif (socialaccount.provider == "facebook"):
		redirect_url = unicode(dashboard_url) + "/#/facebook/select_account"
	else:
		redirect_url = unicode(dashboard_url) + "/#/repost?connected=new"
	return redirect_url
```

**Comment by tanzaho** [comment]
Read this : http://stackoverflow.com/a/21193941/2550237

**Comment by mokibenjak** [comment]
It seems that the fragment cannot be removed on the server side. For more details see here: http://stackoverflow.com/questions/7131909/facebook-callback-appends-to-return-url#comment22255626_7131909
Finally, I ended up using this solution, which seems to work quite nice: https://github.com/jaredhanson/passport-facebook/issues/12#issuecomment-39133576

Closing this since there is nothing that can be done in django-allauth.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1579
