### ISSUE TITLE
Unicode issue

### ISSUE THREAD

**Issue by muminoff** [pennersr/django-allauth#1585]
Hi there. Great project.

But, I am having issue with unicode characters. Form field with `Extra data` label has `<textarea>` element, and it is not decoding unicode characters when viewing social account models in admin page.

Btw, I have a few social account models from `Facebook` provider. I don't think it is django's issue.

Attaching screenshot which describes issue better.
![screen shot 2017-01-10 at 12 41 16 pm](https://cloud.githubusercontent.com/assets/1235454/21793174/5f5e6e32-d732-11e6-9116-866c20e36cb0.jpg)

**Comment by pennersr** [comment]
This is working as implemented -- the extra data contains a JSON blob representing the data the social provider handed over. The screenshot you are showing is proper JSON. I admit that this is not ideal, but there is not much more we can do here... given that it is a blob containing any data the social provider happens to hand over, it is not really feasible to provide a friendly admin for this. Anyway, the social account model is not really intended to be managed by admins anyway... if the data contains any items that are important within your project scope, you should add a dedicated user-model field for these and copy the data over to the user model.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1585
