### ISSUE TITLE
How to avoid sending email on ACCOUNT_EMAIL_VERIFICATION = 'mandatory' settings?

### ISSUE THREAD

**Issue by chika-kasymov** [pennersr/django-allauth#1587]
I want to have registration and login flows as default, but confirm user's email only by admin. Is it possible to achieve this kind of thing?

**Comment by chika-kasymov** [comment]
I solved my issue by settings `ACCOUNT_EMAIL_VERIFICATION = 'none'` and overriding `DefaultAccountAdapter` so that initially `user.is_active = False`.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1587
