### ISSUE TITLE
LANGUAGE_CODE defined in settings but the emails are sent in english

### ISSUE THREAD

**Issue by cbanicolas** [pennersr/django-allauth#1588]
Hi, for some reason all the emails are being sent in English, even when LANGUAGE_CODE it is defined with my lang (es-ES, i tried only "es" too) at my project settings file.

I am using django 1.10.2 and allauth 0.27.0

What can be the problem? Thanks a lot!

**Comment by pennersr** [comment]
https://django-allauth.readthedocs.io/en/latest/faq.html#why-did-you-just-close-my-issue

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1588
