### ISSUE TITLE
Add "requests" dependency

### ISSUE THREAD

**Issue by fabiosantoscode** [pennersr/django-allauth#159]
I'm not sure how this is done, or if it should be done, or I would've done it myself, but...

Shouldn't 'requests' be listed as a dependency in setup.py, so pip can find the dependency properly on install? This stumped me when I upgraded all the packages in requirements.txt and started having ImportErrors.

Thank you.

PS: I'm doing a Portuguese translation of this app in my fork, I will pull request soon when I test it.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/159
