### ISSUE TITLE
Unique Email: Error Message translation removed

### ISSUE THREAD

**Issue by aritas1** [pennersr/django-allauth#1590]
The translation for the [email_taken](https://github.com/pennersr/django-allauth/blob/master/allauth/account/adapter.py#L47) (unique email error) was dropped.

In the commit fd1961dccbe2bc253c273972b862304e047ea604, for all languages, the key was moved into the comment section at the bottom of the file.

Maybe this is related to #1449 and the commit 0e62e7be524168b19dd18bb617e661a61f5a63e0?

**Comment by pennersr** [comment]
#1449 is closed...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1590
