### ISSUE TITLE
Twitch: Redirect loop

### ISSUE THREAD

**Issue by youngvenus** [pennersr/django-allauth#1591]
I'm trying to connect my website to the twitch API
I created an application on the twitch developers API and created a new social application on django administration, and when i try to login through twitch i get a redirect loop and on chrome the error goes
ERR_TOO_MANY_REDIRECTS
and powershell goes

```
[16/Jan/2017 18:20:25] "GET /accounts/twitch/login/?process=login&error=redirect_mismatch&error_description=Parameter+re
direct_uri+does+not+match+registered+URI&state=dKYixsuL0j8f HTTP/1.1" 302 0
[16/Jan/2017 18:20:25] "GET /accounts/twitch/login/?process=login&error=redirect_mismatch&error_description=Parameter+re
direct_uri+does+not+match+registered+URI&state=I4KIU8vWn1wO HTTP/1.1" 302 0
```
over and over
my redirect URI on the twitch API dashboard is:
http://localhost:8000/accounts/twitch/login/?process=login
and that's probably where i messed up, but i don't know the correct redirect URI.

I've read several forums/discussions for help but there's not much for django-allauth with twitch.

EDIT:
so i tried a couple of different URIs by taking samples from other networks i succesfully installed and now i can kind of authenticate the twitch account with this URI:
http://localhost:8000/accounts/twitch/login/callback/
 but i end up in a screen that asks for a new username and email rather than just signing them into the system:
**Sign Up**
You are about to use your Twitch account to login to FB login. As a final step, please complete the following form:
EDIT:
so i got it right by switching the ACCOUNT_EMAIL_VERIFICATION to null

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1591
