### ISSUE TITLE
install error at migrate: _IterParseIterator

### ISSUE THREAD

**Issue by jfeldman777** [pennersr/django-allauth#1599]
I install django-allauth on django 1.10 according to
[this page](https://django-allauth.readthedocs.io/en/latest/installation.html)

and  when I come to MIGRATE command I get (last in list means first in time)

  File "D:\Python3\lib\site-packages\defusedxml\ElementTree.py", line 56, in _get_py3_cls
    _IterParseIterator = pure_pymod._IterParseIterator
AttributeError: module 'xml.etree.ElementTree' has no attribute '_IterParseIterator'

see full list of errors in
[allauth-iinstall-err.txt](https://github.com/pennersr/django-allauth/files/749839/allauth-iinstall-err.txt)
 attached file

Probably it is about new django version?

**Comment by jfeldman777** [comment]
solved: 
I copied fresh version of 2 files of the last patch from gitHub and updated these files -- and it works

https://github.com/tiran/defusedxml/blob/master/defusedxml/common.py https://github.com/tiran/defusedxml/blob/master/defusedxml/ElementTree.py

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1599
