### ISSUE TITLE
Error on Social Connections Page

### ISSUE THREAD

**Issue by cademan** [pennersr/django-allauth#16]
The page loads fine at first. Then I add a google account connection and receive this error. The error goes away when the google connection is deleted. This error only shows up when twitter login is disabled. Any ideas?

TemplateSyntaxError at /accounts/social/connections/
Caught FieldDoesNotExist while rendering: SocialAccount has no field named 'twitteraccount'

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/16
