### ISSUE TITLE
I would like to know the next version release schedule.

### ISSUE THREAD

**Issue by shlee322** [pennersr/django-allauth#1603]
I would like to know the next version release schedule.
Can you tell when the next version will be released?

**Comment by pennersr** [comment]
https://django-allauth.readthedocs.io/en/latest/faq.html#why-did-you-just-close-my-issue

(no concrete plan atm -- note that you can always pip install from git directly)

**Comment by shlee322** [comment]
@pennersr Oops ... I'm sorry.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1603
