### ISSUE TITLE
ACCOUNT_SIGNUP_FORM_CLASS not firing

### ISSUE THREAD

**Issue by lightninglu10** [pennersr/django-allauth#1604]
Hey guys, I've set ACCOUNT_SIGNUP_FORM_CLASS='contacts.forms.SignupForm' 

I've defined that class to be a basic way to capture first and last name as below:

`class SignupForm(forms.Form):
    first_name = forms.CharField(max_length=300, label='first_name')
    last_name = forms.CharField(max_length=300, label='last_name')

    def signup(self, request, user):
        import pdb; pdb.set_trace()
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.save()`

The form is not saving first and last name though and I put that debugger statement in there to see if it's firing at all and it's not.

After signup, the code never reaches here.

**Comment by pennersr** [comment]
The above looks sound, I cannot find any problem in that. I suspect that there is some other issue in your project, it is very unlikely to be caused by an issue in allauth. You may want to set a breakpoint over at `custom_signup` (account/forms.py)...

**Comment by lightninglu10** [comment]
Set a breakpoint inside of the allauth package at account/forms.py?

And also I set a breakpoint with a decorator using the signal user_signed_up and it wasn't fired either.

**Comment by lightninglu10** [comment]
Actually this isn't an issue with allauth, but a package that is utilizing allauth -- django rest-auth

**Comment by prafulbagai** [comment]
I'm facing the same issue. What was the resolution? Kindly elaborate

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1604
