### ISSUE TITLE
Login view facebook and twitter links on Safari browser invisible

### ISSUE THREAD

**Issue by Qurus** [pennersr/django-allauth#1605]
Login links for facebook and twitter on Safari browser invisible. I did try on other browsers working fine.

**Comment by pennersr** [comment]
What templates are you using? Could you add a screenshot?

**Comment by pennersr** [comment]
Closing, time-out, unlikely an issue in allauth

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1605
