### ISSUE TITLE
Table 'navi.socialaccount_socialapp_sites' doesn't exist

### ISSUE THREAD

**Issue by rohit-nsit08** [pennersr/django-allauth#161]
Hi devs, got this error when tried to connect to facebook on my site [ navi is my database name] . 
after searching for the table It looks like it shouldn't have asked for it . 
I'm using django 1.4.3 and latest version of allauth. I can give the full stack trace if it is needed.

**Comment by jairoDO** [comment]
I fixed creating the table manually
create table socialaccount_socialapp_sites (
    site_id integer,
    socialapp_id integer

)

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/161
