### ISSUE TITLE
Cannot disable username?

### ISSUE THREAD

**Issue by jacopsd** [pennersr/django-allauth#1611]
Django 1.8.16 django-allauth 0.27.0 Using postgres as database.

My application does not use usernames, only e-mail addresses as user id. So I use following settings:

```
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_USER_MODEL_EMAIL_FIELD = 'email'

```
Now when a new user registers, he uses his e-mail address. But when submitting the registration form, I get this error:

> IntegrityError at /accounts/signup/
> duplicate key value violates unique constraint "auth_user_username_key"
> DETAIL:  Key (username)=() already exists.
> Request Method: POST
> Request URL:    http://swd.localhost:8000/accounts/signup/
> Django Version: 1.8.16
> Exception Type: IntegrityError
> Exception Value:    
> duplicate key value violates unique constraint "auth_user_username_key"
> DETAIL:  Key (username)=() already exists.
> 

This says exactly what is wrong: The empty username already exists in the auth_user table, field "username", and it seems this is not allowed? But problem is that the username field is ALWAYS empty using above settings. 

Note: user model is not adapted

In the DB, the field 'username' is marked as 'unique'. So this means indeed that it cannot be Null for all users. Removing this at DB level seems not straightforward, and is not the right thing to do. So how can we get around this? 

Thx for your help

See also: 
http://stackoverflow.com/questions/42160475/django-allauth-empty-username-causes-duplicate-key-in-postgress-db

**Comment by jacopsd** [comment]
Could work around this using an account adapter.

For more details, see:
http://stackoverflow.com/questions/42160475/django-allauth-empty-username-causes-duplicate-key-in-postgress-db

**Comment by pennersr** [comment]
Apparently, your model does have a `username` field... so this is wrong:

`ACCOUNT_USER_MODEL_USERNAME_FIELD = None`

Set it to `"username"` so that allauth will take care of populating it correctly.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1611
