### ISSUE TITLE
DigitalOcean missing in provider docs

### ISSUE THREAD

**Issue by bittner** [pennersr/django-allauth#1612]
I've noticed that [DigitalOcean](https://github.com/pennersr/django-allauth/tree/master/allauth/socialaccount/providers/digitalocean) is missing completely in the [provider docs](https://github.com/pennersr/django-allauth/blob/master/docs/providers.rst#bitbucket). Is this on purpose or has this been forgotten?

I found a somewhat [OAuth2 tutorial](https://www.digitalocean.com/community/tutorials/an-introduction-to-oauth-2) on the DigitalOcean community website, just in case some configuration details need to be reconstructed.

**Comment by pennersr** [comment]
https://django-allauth.readthedocs.io/en/latest/faq.html#why-did-you-just-close-my-issue

(lack of documentation is not intentional)

**Comment by bittner** [comment]
Alright. This was not a complaint. This was an attempt to clarify whether a PR adding the missing section would be appreciated. I guess, the answer is yes.

**Comment by pennersr** [comment]
Yes -- pardon my brevity, a PR is welcome!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1612
