### ISSUE TITLE
Wrong domain redirect

### ISSUE THREAD

**Issue by lucawen** [pennersr/django-allauth#1613]
I Have a facebook app configured.

My domain is 'http://projeto.website.com'
I Try do login, facebook returns and stop on http://projeto/accounts/facebook/login/token/. Why? This is not a problen in facebook url/domain callback...

**Comment by pennersr** [comment]
https://django-allauth.readthedocs.io/en/latest/faq.html#why-did-you-just-close-my-issue

**Comment by lucawen** [comment]
You can't help and check if this is a real problen in allauth? Thanks..

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1613
