### ISSUE TITLE
Allow for easier subclassing of providers

### ISSUE THREAD

**Issue by lukeburden** [pennersr/django-allauth#1632]
Hi there,

I'd like to propose a change and will follow approval/agreement here with a PR.

**The problem**

I've recently had to subclass Google, WindowsLive and PayPal providers to achieve a range of effects:
- OAuth2 flow without creation of a SocialAccount
- Overriding non-empty default scope
- Mark subclasses as not usable for login purposes, but OK for connection

My initial approach was to subclass the provided provider implementations to keep things DRY in terms of URLs and custom behaviour. This standard approach proves impossible due to the registration call for providers appearing in the same file as the provider class definitions.

Ie, if I define a customer provider as below:

```
from allauth.socialaccount.providers.google.provider import GoogleProvider
from wherever.mixins import NonLoginProviderMixin

class GoogleNonLoginProvider(NonLoginProviderMixin, GoogleProvider):
    id = 'google_non_login'

```

The import of GoogleProvider will result in that same class being registered, which is clearly not the intention. There is no way to subclass GoogleProvider without having it be unintentionally registered.

**My proposal:**

In each provider definition, expose the defined provider classes such that in the [load](https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/providers/__init__.py#L31) method the registration can be performed. For example:

```
from allauth.socialaccount.providers.google.provider import GoogleProvider
from wherever.mixins import NonLoginProviderMixin

class GoogleNonLoginProvider(NonLoginProviderMixin, GoogleProvider):
    id = 'google_non_login'

provider_classes = [GoogleNonLoginProvider]

```

Then in allauth/socialaccount/providers/__init__.py:def load:

```
for app in settings.INSTALLED_APPS:
        provider_module = app + '.provider'
        try:
            for cls in importlib.import_module(provider_module).provider_classes:
                self.register(cls)
        except ImportError:
            pass
    self.loaded = True
```

This change would allow us to properly subclass providers. Let me know what you think!

**Comment by pennersr** [comment]
This is indeed a paint point, I have been wanting to refactor all of this completely, perhaps even to go as far as to have just one Django app per protocol (e.g. OAuth, OAuth2, OpenID) and make things easier to subclass... but I am currently lacking the time to do all of that. Your proposal seems like a fair non-intrusive change that can easily be done without breaking too much, so :+1: for me

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1632
