### ISSUE TITLE
Get template for /accounts/social/connections/#!

### ISSUE THREAD

**Issue by Six-wars** [pennersr/django-allauth#1635]
I'd like to edit the template for accounts social connections can you assist me with it's location in the account template folder.

**Comment by pennersr** [comment]
https://django-allauth.readthedocs.io/en/latest/faq.html#why-did-you-just-close-my-issue

(socialaccount/connections.html)

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1635
