### ISSUE TITLE
facebook connect link issue

### ISSUE THREAD

**Issue by sam-thecoder** [pennersr/django-allauth#1636]
Apart from facebook adding a social link to a logged in user works, facebook however fails to create the account (in the db) after verification [video here](https://www.youtube.com/watch?v=rDb_hFi21x0&feature=youtu.be)

**Comment by derek-adair** [comment]
Cose as stale.  The video is down and this is 6 years old.  I am feeling older by the issue.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1636
