### ISSUE TITLE
settings.LOGIN_REDIRECT_URL to format strings as %(username)s

### ISSUE THREAD

**Issue by shackra** [pennersr/django-allauth#164]
Hello!

I would like to have formated the variable settings.LOGIN_REDIRECT_URL as django-userena does for settings.USERENA_SIGNIN_REDIRECT_URL

I am unsure how easy or hard will be this feature to implement, however, I'll like to try and do a pull request.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/164
