### ISSUE TITLE
Cannot login with linkedin/linkedin_oauth2

### ISSUE THREAD

**Issue by RamizSami** [pennersr/django-allauth#1641]
I configured linkedin social application and tried to integrate it with both, 'allauth.socialaccount.providers.linkedin' and 'allauth.socialaccount.providers.linkedin_oauth2' but cannot login. This is my settings for both:
`'linkedin': {
        'SCOPE': [
            'r_emailaddress', 'r_basicprofile',
        ],
        'PROFILE_FIELDS': [
            'id',
            'first-name',
            'last-name',
            'email-address',
            'picture-url',
            'public-profile-url',
        ]
    },
    'linkedin_oauth2': {'SCOPE': ['r_basicprofile', 'r_emailaddress'],
                  'PROFILE_FIELDS': ['id', 'first-name',
                              'last-name',
                              'email-address',
                              'picture-url',
                              'public-profile-url',
                              'skills', 'headline']},`
and this is my code in template:
for linkedin oauth2:
`<a href="{% provider_login_url 'linkedin_oauth2' %}" next="/">
    <button type="button" class="btn btn-linkedin waves-effect waves-light m-t-20">
       <i class="fa fa-linkedin m-r-5"></i> Linkedin
    </button>
</a>`
for linkedin:
`<a href="{% provider_login_url 'linkedin' %}" next="/">
    <button type="button" class="btn btn-linkedin waves-effect waves-light m-t-20">
       <i class="fa fa-linkedin m-r-5"></i> Linkedin
    </button>
</a>`

When using linkedin provider, the url /accounts/linkedin/login/ displays error message that there was an error while logging in.
When using likedin_oauth2 provider, the url /accounts/linkedin_oauth2/login/ redirects to https://www.linkedin.com/uas/oauth2/authorization?scope=&state=uCBu7AwHib3H&redirect_uri=http%3A%2F%2Flocalhost%3A8000%2Faccounts%2Flinkedin_oauth2%2Flogin%2Fcallback%2F&response_type=code&client_id=78ooxchybs44b and this URL cannot be decoded.
Please guide me what I am doing wrong?

**Comment by pennersr** [comment]
Please upgrade to 0.37.1

**Comment by fab10m** [comment]
Hello,

since yesterday I can't signin with linkedin connector anymore. I've been using the linkedin_oauth2 provider for about 2 years and I've already:
- done the upgrade to the last release 0.39.1
- checked that my app is verified by linkedin  

This is the error I get 
`{
    "error": "invalid_request",
    "error_description": "Unable to retrieve access token: appid/redirect uri/code verifier does not match authorization code. Or authorization code expired. Or external member binding exists"
}`

Does anyboby have the same issue?

Regards,
Fabio

**Comment by Bragegs** [comment]
@fab10m Hi, did you manage to figure out what went wrong? Having the same issue

**Comment by fab10m** [comment]
Yes, I did. In my case the error was originated by the request for a field no longer supported by LinkedIn and the presence of the header's variable "x-li-src: msdk.

**Comment by ibrahimsamson** [comment]
@Bragegs  Hi, did you manage to figure out what went wrong. I'm stuck too

**Comment by sainyamcc** [comment]
This still is there, django-allauth = "~=0.45.0" I am on.

**Comment by MahmoudBayoumi19** [comment]
i am have same issue:
I configured linkedin social application and tried to integrate it with both, 'allauth.socialaccount.providers.linkedin' and 'allauth.socialaccount.providers.linkedin_oauth2' but cannot login. This is my settings for both:
'linkedin_oauth2': {
        'SCOPE': [
            'openid',
            'profile',
            'w_member_social',
            'email'
        ],
        'APP': {
            'client_id': '78na9m2trtpfji',
            'secret': 'ysjmzp6lwKlrgNT1',
            'key': ''
        }
    }
this url: /accounts/linkedin_oauth2/login/?process=login redirect to:
http://127.0.0.1:8000/accounts/linkedin_oauth2/login/callback/?code=AQQo34wWQ19rSQZy2D6ZT7i_sf2nEhT6HoYnxtwluOvh60Y5XVoEVDHNTmsX9RG5VDpv52PrtuPIsP5YXVGzuJOW3PwLJSbHWUumPHXtUcdrjg_gTaFDuPQwn_h2fsEsrY0BlibuxM5PR7mF34AuBMs5Hai1xF8rJaZUTLotaCMtdfOH-kc0sp8isDLc4R492gyY51fctE7ChVNZLZE&state=pnyyh12BgUsWAJ9l

**Comment by mohebmithani** [comment]
The flow implemented in this library needs to access **me** api of linkedin to get user details but i think linkedin has removed the access of these apis as per their new restrictions. Their new flow requires to use **https://api.linkedin.com/v2/userinfo** api.

I created my custom linkedin adapter using `LinkedInOAuth2Adapter` and overrode this method: `get_user_info`. I called the appropriate api inside this method and then transformed the data i got from linkedin to the format this library requires and things started to work. I am not sure if this is a good approach but it WORKED!.

The document for their new flow, OpenID is below:
https://learn.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/sign-in-with-linkedin-v2?context=linkedin%2Fconsumer%2Fcontext

**Comment by MahmoudBayoumi58** [comment]
new app in linkedin used openid_connect instead of use oauth2 so u need to use openid_connect config:
"openid_connect": {
        "APPS": [
            {
                "provider_id": "oidc_linkedin",
                "name": "LinkedIn",
                "client_id": "",
                "secret": "",
                "settings": {
                    "server_url": "https://www.linkedin.com/oauth/.well-known/openid-configuration",
                },
            }
        ]
    }
this worked for me

**Comment by imane-aj** [comment]
> new app in linkedin used openid_connect instead of use oauth2 so u need to use openid_connect config: "openid_connect": { "APPS": [ { "provider_id": "oidc_linkedin", "name": "LinkedIn", "client_id": "", "secret": "", "settings": { "server_url": "https://www.linkedin.com/oauth/.well-known/openid-configuration", }, } ] } this worked for me

i used this settings but i have error OpenIDConnectAdapter.__init__() missing 1 required positional argument: 'provider_id'
, this is my code     
class LinkediConnect(SocialConnectView):
    adapter_class = OpenIDConnectAdapter

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1641
