### ISSUE TITLE
Attach methods or attributes to SocialToken, Provider or provider implementation classes 

### ISSUE THREAD

**Issue by bittner** [pennersr/django-allauth#1643]
I would need to attach a few attributes to the [providers](https://github.com/pennersr/django-allauth/tree/master/allauth/socialaccount/providers) I use (e.g. an `icon` to show on the UI, an `api_class` which implements access using the token, and some other proprietary data) and helper functions to the [SocialToken](https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/models.py#L135) or the [Provider](https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/providers/base.py#L30) class.

In any case, I would need some possibility to either add a mixin class to `Provider` and the single provider implementations, or have them swappable (so I can tell `allauth` to use a class that extends from the original class). In the case of `SocialToken` I would need to be able to swap the implementation with a [proxy model](https://docs.djangoproject.com/en/1.10/topics/db/models/#proxy-models).

Is this something that we should add, i.e. you would accept a PR for, or can this already be achieved in some way I've not yet considered? Is PR #1318 meant to address this problem, too? (In this case, note that having `SocialToken` swappable is not yet addressed there, as far as I can see.)

**Comment by pennersr** [comment]
Would the changes made in https://github.com/pennersr/django-allauth/issues/1632 be of any help for your case?

**Comment by bittner** [comment]
I'm not sure. Maybe I just don't understand the approach in #1632. It seems to me that what it targets is subclassing and, probably, registering that new, custom provider.

What I need is simply attaching methods and attributes to the `SocialToken` and provider classes (and leave everything else untouched). That can be done with monkey patching to a certain extent, but as soon as the provider classes are instantiated via the models themselves I get the _original_ classes returned instead of the patched ones, e.g.

``` python
BitbucketOAuth2Provider.api_class = BitbucketAPI
GitHubProvider.api_class = GitHubAPI
GitLabProvider.api_class = GitLabAPI

# not available when SocialToken instance comes from inside allauth
def get_service_api(self):
    # not available when provider instance comes from inside allauth
    api_class = self.app.provider.api_class
    return api_class(self.token)

SocialToken.get_service_api = get_service_api
```

Am I missing something?

Should I create 3 custom provider classes that inherit from the above mentioned ones, and add _their_ references to `INSTALLED_APPS` instead? Would that work?

**Comment by bittner** [comment]
I've looked a bit deeper into subclassing providers. For applying a simple change, such as adding a class attribute, I need to create a directory structure for each provider implementation (`providers/someprovider/provider.py`) due to the [hardwired nature of the import mechanism](https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/providers/__init__.py#L41-L43) in `load`.

This feels heavy for a single, unobtrusive change. Reminds me of Java, but maybe I'm wrong.

It would be nice if simple customization required not much more code than monkey patching, and the freedom to apply those changes in a single module (even for multiple classes).

**Comment by derek-adair** [comment]
seems like a worthy feature request here although I have am unsure of the scope of the changes required here.  Leave open and tag as "PR welcome" or whatever.

**Comment by pennersr** [comment]
Closing as dupe -- let's keep everything related to swapping/extending functionality in this ticket: https://github.com/pennersr/django-allauth/issues/2997

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1643
