### ISSUE TITLE
Update Facebook Graph API v2.8 from v2.2

### ISSUE THREAD

**Issue by idesoto** [pennersr/django-allauth#1654]
Hi,

I'm using currently Graph API v2.2 and want to upgrade to the latest, v2.8. Do I need to change anything else besides the version I set for the facebook socialaccount provider? Since which version of django-allauth is v2.8 supported? I'm currently using v0.27.0, do I need to update it?

Thanks.

**Comment by pennersr** [comment]
https://django-allauth.readthedocs.io/en/latest/faq.html#why-did-you-just-close-my-issue

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1654
