### ISSUE TITLE
Proxy server kwargs for requests from allauth so it goes through single whitelisted static IP

### ISSUE THREAD

**Issue by tai-rinse** [pennersr/django-allauth#1656]
I'm trying to deploy allauth to Heroku using PROXIMO proxy server configuration which allows for a single static IP sitting in front of web server workers. This necessitates the addition of kwargs['proxies'] to all requests from allauth to FB. We need this so we can use 'Server IP Whitelist' FB feature for our server addresses from FB advanced settings which is used for other applications already.

Is there an easier way to do this? Could I request an allauth setting to configure proxy servers in future release?

What I had to do was write my own login_by_token that adds kwargs['proxies'] in requests.get call from my PROXIMO_URL setting to get around this, but now I realize I have to do this for all requests.get and posts from allauth for website. It would help deployment a lot if there was a configurable option for proxy server which defaults to no proxy for these cases. Thank you.

**Comment by pennersr** [comment]
If the account adapter had a method like below, and it was used throughout all of allauth, would that tackle your use case?

```
import requests

class DefaultAccountAdapter():
    def get_requests_session(self):
        return requests.Session()
```

Then, instead of:

```
import requests
requests.get(...)
```

we would need to do:

```
get_adapter().get_requests_session().get(...)
```

**Comment by derek-adair** [comment]
Close as stale.  If this hasn't come up again in 6 years it's clearly not a highly sought after feature.  Besides this seems like something that could be implemented in a more reusable way than described w/o altering allauth.

**Comment by pennersr** [comment]
True, though having a centralized session would make it much easier to implement #1832. So it would make for a nice refactor...

**Comment by pennersr** [comment]
Completed via 170530a7

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1656
