### ISSUE TITLE
Tag releases so that readthedocs stays up-to-date

### ISSUE THREAD

**Issue by Flimm** [pennersr/django-allauth#1659]
If you go to the readthedocs page for this project, you can see:

http://django-allauth.readthedocs.io/en/stable/

> This is a fork of https://github.com/pennersr/django-allauth that is focused on supporting multiple SocialApp‘s of the same type.

What, this is a fork? How confusing!

If you go to `letest` instead of `stable`, you get this intro instead:

http://django-allauth.readthedocs.io/en/latest/

> Integrated set of Django applications addressing authentication, registration, account management as well as 3rd party (social) account authentication.

That makes more sense.

So it's clear that the docs for `stable` are very out-of-date! Here's the documentation on which version is chosens for `stable`: http://docs.readthedocs.io/en/latest/versions.html

So there seems to me to be two solutions:

- Tag the latest releases regularly in Git.
- Or delete all the tags, and hope that all the contributors don't accidentally repush the tags.

**Comment by pennersr** [comment]
I have to do some reading up on how readthedocs picks these up. The releases are already tagged properly, so I am not sure what logic it uses to figure out which version tag to map stable to. As a quick "fix" I have temporarily disabled the stable branch until this is sorted out...

**Comment by Flimm** [comment]
Disabling the `stable` branch is a good enough fix for me. :)

Here are the tags I see:

![Screenshot](https://cloud.githubusercontent.com/assets/355454/23846574/56e9b744-07ce-11e7-8913-6f3526404fb5.png)

The [latest version on PyPI ](https://pypi.python.org/pypi/django-allauth) is 0.31.0, not 1.0.1.

**Comment by pennersr** [comment]
1.x tags removed, thanks

**Comment by Flimm** [comment]
I guess that should fix it.

I would keep an eye out for these tags reappearing though. If some has cloned this repo in the past, they still have a copy of the old tags, and if they ever do `git push --tags` again, the `1.x` tags will get recreated in GitHub.

**Comment by pennersr** [comment]
Thanks for the heads up...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1659
