### ISSUE TITLE
Username unique check in adapter

### ISSUE THREAD

**Issue by chubz** [pennersr/django-allauth#1661]
Hi,

I've got a question regarding the check in clean_username in default adapter.
Since it is possible to configure most of behavior regarding usernames/emails etc would it be a good proposal to have a setting that would disable uniqueness check?

Case for it is:
Using a custom model which has username field but does not enforce username to be unique. Any other field is used as identifier and it is configured as such.
Username is required to be provided while user is signing up. Meaning that multiple users can have the same username. But some other field would be unique so it is fine.

Currently to route around this clean_username on SignupForm or clean_username in the adapter have to be overridden but it seems like it could be a setting similar to:
ACCOUNT_USERNAME_REQUIRED = True

so if we would have something like this:
ACCOUNT_USERNAME_UNIQUE = False (default: True)

then in the adapter [@L:269](https://github.com/pennersr/django-allauth/blob/master/allauth/account/adapter.py#L269) we could skip this check completely.

It could be also okay to check if username field exists or if designated username field in ACCOUNT_USER_MODEL_USERNAME_FIELD has unique=True property set to skip the uniqueness check
I don't know how it would affect the rest of username related functionality but if you have any counters for this I'd love to hear them.

**Comment by pennersr** [comment]
The semantics for an allauth/django user name is for it to be a unique ID using which you can login. Clearly, your username does not obey by these rules. So, as far as allauth/django is concerned, you do not have a username within your project. In your case, you have an additional field, on the same level as e.g. first_name, that happens to be called username, but does not function as such. So in order not to row up against the stream, I would put ACCOUNT_USER_MODEL_USERNAME_FIELD to `None` as you don't have one. Then, put in a custom signup field that asks for the additional username-like field during signup.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1661
