### ISSUE TITLE
Moving setup data to setup.cfg

### ISSUE THREAD

**Issue by jleclanche** [pennersr/django-allauth#1672]
I recently revamped all my django packages to follow the following pattern:

* [setup.cfg](https://github.com/jleclanche/django-push-notifications/blob/master/setup.cfg)
* [setup.py (empty)](https://github.com/jleclanche/django-push-notifications/blob/master/setup.py)

I have applied that pattern to other django libs such as [dj-stripe](https://github.com/kavdev/dj-stripe), [django-push-notifications](https://github.com/jleclanche/django-push-notifications), [django-intenumfield](https://github.com/hearthsim/django-intenumfield) etc.

The advantage is that the setup data is readable without executing a python script, there is a single source of truth for all requirements, metadata etc and it becomes possible to gather the data externally (as you don't need to parse Python). The only drawback is that it hard-requires a recent setuptools.

Do you want me to file a PR that does all this for allauth?

**Comment by pennersr** [comment]
I am still pondering about this open issue:

https://github.com/pennersr/django-allauth/issues/1032#issuecomment-127564894

As you can see, one of the solutions there is to compile the .po files is by adding logic to the setup.py -- which collides with the concept of an empty setup.py. Does this have to be a black and white approach, or can some parts remain in a "less empty" setup.py ?

**Comment by jleclanche** [comment]
Some parts can remain in the setup.py yes, it doesn't have to be black and white.

**Comment by jleclanche** [comment]
Example in dj-stripe: https://github.com/kavdev/dj-stripe/blob/1.0.0/setup.py

**Comment by jleclanche** [comment]
I do not. On my machine with Python 3.6 though everything installs out of the box.

**Comment by pennersr** [comment]
Closing -- this is implemented by now.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1672
