### ISSUE TITLE
Typo in flash message after incorrect login.

### ISSUE THREAD

**Issue by rishabhiitbhu** [pennersr/django-allauth#1673]
The `LoginForm` Class of `account/forms.py` ([link](https://github.com/pennersr/django-allauth/blob/master/allauth/account/forms.py#L69)) has `error_messages` for different login error situations.

`username_email_password_mismatch` key of `error_message` has value `"The login and/or password you specified are not correct."`. I think I should explicitly say that "The login username/email and/or password you specified are not correct".

Open for reviews.

**Comment by pennersr** [comment]
"username/email" is not correct in the case login is configured to be by email only. So in order to be truly explicit we need different messages depending on `ACCOUNT_AUTHENTICATION_METHOD`

**Comment by rishabhiitbhu** [comment]
@pennersr suppose `ACCOUNT_AUTHENTICATION_METHOD` is set to `username_email`, according to [docs](http://django-allauth.readthedocs.io/en/latest/configuration.html) user login method is either username or email. So, how can we figure it out whether login is explicitly username or email?

**Comment by pennersr** [comment]
When it is set to `username_email`, it is okay to report `"The username/e-mail and or password..."`, but when it is set to just `username` or `email`, it should be explicit...

**Comment by rishabhiitbhu** [comment]
@pennersr We do have explicit messages for such cases [look](https://github.com/pennersr/django-allauth/blob/master/allauth/account/forms.py#L76)

**Comment by pennersr** [comment]
Duh! :) 

So your proposal is to change:

    "The login and/or ..."

to

    "The login username/email ..."

I am okay with that, but shouldn't that be just 

    "The username/e-mail ..." ?

**Comment by rishabhiitbhu** [comment]
Cool. Should I go ahead to open a PR?

**Comment by pennersr** [comment]
Please do...

(do note the email vs e-mail -- allauth uses the latter form)

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1673
