### ISSUE TITLE
`next` parameter not respected on login 

### ISSUE THREAD

**Issue by jeremybmerrill** [pennersr/django-allauth#1681]
In some cases, when a user is logging into my app with Google Oauth / Django all-auth, the `next` parameter is properly set on the URL as expected, but the page generates a 302 to the wrong place.

To reproduce, I:

1. log out
2. go to the root of my app
3. click a link to go to the Django Admin
4. it sends me to the Google login flow
5. which (correctly, I think), redirects me to:
`http://localhost.mydomain.com:8000/admin/login/?next=/admin/myapp/myappmodel/6/change/`

However, that request generates a 302 with the response header `Location:/admin/`. I'm not sure where that choice of URL is coming from. I'd like for the `next` parameter to be what's redirected-to.

I've tried setting a custom `AccountAdapter`, but its `get_login_redirect_url` method never gets called in this scenario.

I will note that I've got an odd Google Oauth setup, where the whole app is protected by another Google OAuth proxy with the same set of credentials. So, that means that, no matter what, the user has an active session for Google OAuth when they hit the app, but django-allauth may not know about them yet. When there's only one proxy, this error does not occur.

I appreciate your help and am happy to answer any questions or do whatever I can to help figure out this issue. Thanks!

Django version is 1.10.6
django-allauth version is 0.31.0

**Comment by jochenklar** [comment]
I have a similar problem and I think I found the problem. When logged in, "next" after a get to the login url is not respected if it starts with http://, e.g.: http://localhost:8000/accounts/login/?next=http://localhost:8000/foo/ redirects to http://localhost:8000 not to http://localhost:8000/foo/.

I think the reason is that in https://github.com/pennersr/django-allauth/blob/master/allauth/account/adapter.py#L420 `allowed_hosts` is not passed to django.utils.http.is_safe_url.

I fixed it my custom adapter using:

```
    def is_safe_url(self, url):
        from django.utils.http import is_safe_url
        return is_safe_url(url, allowed_hosts=settings.ALLOWED_HOSTS)
```

**Comment by jochenklar** [comment]
After reading the original issue again, I think its not the same problem, so I filed a new issue: https://github.com/pennersr/django-allauth/issues/1766.

Sorry for the mess.

**Comment by derek-adair** [comment]
Close as stale.  If @jeremybmerrill (still active) can...

1. Confirm this is not a duplicate / fixed by #1766 (it could be).
2. provide the settings so we can easily / accurately reproduce his bug

It's very much worth fixing if this is still a thing.

**Comment by jeremybmerrill** [comment]
I've switched jobs a few times since 2017 and, as far as I can tell, this project is dormant at my old employer (whose OAuth setup I was configuring django-allauth to use), so unfortunately I'm unable to reproduce this issue or check it. Agree that closing as stale would be appropriate, although I'll leave that up to the maintainers.

**Comment by iamunadike** [comment]
Next is not working , fix this stupid bug , its empty in custom adapter using get_login_redirect_url

**Comment by derek-adair** [comment]
@iamunadike submit a STUPID pull request or AT LEAST provide a reliable way to reproduce this STUPID bug.

Lazy comments like this make me glad I'm no longer an open source maintainer.

**Comment by hanatole** [comment]
> [@iamunadike](https://github.com/iamunadike) submit a STUPID pull request or AT LEAST provide a reliable way to reproduce this STUPID bug.
> 
> Lazy comments like this make me glad I'm no longer an open source maintainer.

[This should help you](https://youtu.be/femLt5sl3-o?si=ZhQbVU9uBh2iqWas)

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1681
