### ISSUE TITLE
Social Network Login Failure

### ISSUE THREAD

**Issue by Six-wars** [pennersr/django-allauth#1682]
Using django-allauth latest version and getting error snapshot here
![screenshot from 2017-03-25 19-18-00](https://cloud.githubusercontent.com/assets/15666437/24324043/038df7b0-1190-11e7-810d-e0b167e4d009.png)

got debug set to true and not getting any errors.

**Comment by pennersr** [comment]
Dupe of #1120

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1682
