### ISSUE TITLE
Odnoklassniki login error.

### ISSUE THREAD

**Issue by qstwx1** [pennersr/django-allauth#1684]
KeyError at /accounts/odnoklassniki/login/callback/

'uid'

![image](https://cloud.githubusercontent.com/assets/26348697/24347268/28d78060-12f1-11e7-8b32-f75ccb2cfaea.png)

**Comment by Pymancer** [comment]
For those who also stumbled on this error: just fill out social app public key in your Django admin panel.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1684
