### ISSUE TITLE
Make user_display templatetag use email address

### ISSUE THREAD

**Issue by johndoefromhere** [pennersr/django-allauth#1686]
Default templates often use `{% user_display user as user_display %}`, resulting in showing the user his username. How can I change it to use e-mails instead? I don't want to use generated usernames at all.

My settings:

```
ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = "optional"
ACCOUNT_USERNAME_REQUIRED = False
```

**Comment by pennersr** [comment]
See `ACCOUNT_USER_DISPLAY`

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1686
