### ISSUE TITLE
different SocialApp providers on different sites

### ISSUE THREAD

**Issue by velis74** [pennersr/django-allauth#1688]
I'm having problems where my app is handling multiple sites and not all of them use the same social providers:

INSTALLED_APPS = (
    ....
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.twitter',
    'django.contrib.sites',
    ....
)

When looked at socialaccount_socialapp_sites table, I have the following mappings:
site 1: facebook, google, twitter (the "intended" scenario)
site 2: facebook, google
site 3: google

I have two distinct problems / issues with this:

1. Login screen lists all three providers regardless of what's specified in the socialapps_sites table. This is because get_providers tag simply gets list of all installed providers, not providers mapped to the site. My further inquiry shows that providing context to this tag (takes_context=True) would allow request to be passed into the registry.get_list() function which could then retrieve mapping-relevant list

2. while twitter provider makes no check on mapping (and only the actual attempt at logging-in with twitter would fail), facebook provider checks for the mapping immediately, and of course fails when mapping is not present (ImproperlyConfigured, provider.py, media_js, except SocialApp.DoesNotExist). I believe this one would be "solved" simply by solving issue 1. Not tested yet.

Question:
Is my reasoning that different sites might not all use the same providers correct? Would a patch solving this issue be even considered?

I will update the issue with my findings later.

**Comment by velis74** [comment]
It would seem that my solution works nicely. I only get the icons for the providers, registered for a particular site. Additionally, I don't get ImproperlyConfigured any more.

Preparing a pull request for @pennersr to evaluate.

**Comment by pennersr** [comment]
In the current main branch `{% get_providers %}` respects what the sites framework.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1688
