### ISSUE TITLE
Trouble understanding socialaccount login redirect 

### ISSUE THREAD

**Issue by scutler19** [pennersr/django-allauth#1690]
Still new to Django.

I have socialaccount login working as far as being able to click "Login with Facebook", making a successful GET request to "/accounts/facebook/login/", making a successful GET request to "/accounts/facebook/login/callback/?code=...big string of token chars..."

Immediately after, Django starts making repeated failing GET requests to "/accounts/social/signup/static/templates/home.html"

I've spent hours looking through each of the allauth code files trying to find where/why it's making the request to that URL and I'm not coming up with anything. I'd like it to load "home.html" post login, but can't understand why it looks in "accounts/social/signup/..." 

Can anyone help me understand?

**Comment by pennersr** [comment]
allauth is definitely not making GET requests to a template URL, the home.html is not even part of allauth. So I am afraid I am unable to help you here, it appears that this is a project specific issue... try starting small with just default allauth and then gradually add your own features.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1690
