### ISSUE TITLE
VKOAuth2Adapter doesn't work

### ISSUE THREAD

**Issue by OlzhasAlexandrov** [pennersr/django-allauth#1691]
I tried to pass access_token using two different methods ([first](https://vk.com/dev/implicit_flow_user), [second](https://vk.com/dev/authcode_flow_group))
For the code I pass my app_id

However, it breaks on the following line:

Exception Location:	.../api/views.py in complete_login, line 42

uid = kwargs['response']['user_id']
Exception Type: TypeError at /api/vk/
Exception Value: string indices must be integers

Can you please let me know what should I do?

It breaks on the third line of your adapter:
```
class VKOAuth2Adapter(VKOAuth2Adapter):
    def complete_login(self, request, app, token, **kwargs):
        uid = kwargs['response']['user_id']
        resp = requests.get(self.profile_url,
                            params={'access_token': token.token,
                                    'fields': ','.join(USER_FIELDS),
                                    'user_ids': uid})
        resp.raise_for_status()
        extra_data = resp.json()['response'][0]
        email = kwargs['response'].get('email')
        if email:
            extra_data['email'] = email
        return self.get_provider().sociallogin_from_response(request, extra_data)
```

**Comment by OlzhasAlexandrov** [comment]
Thank you, it works now!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1691
