### ISSUE TITLE
No confirmation email sent for Google+ Login (ACCOUNT_EMAIL_VERIFICATION=OPTIONAL)

### ISSUE THREAD

**Issue by vaimdev** [pennersr/django-allauth#1692]
For user sign up with FB , confirmation email is sent. Not for Google+.

After tracing the code, found that the Google+ provider created EmailAddress default the verified=True, and in the later process ,   perform_login in  account/utils.py , the logic bypass sending email confirmation because email address already marked as verified.

I am not sure whether this is "feature" or "bug" ?  

I am currently use a workaround to solve this.

**Comment by pennersr** [comment]
Feature. The email address is already properly validated (by Google), there is no need to bother the user with this again...

**Comment by charleshan** [comment]
I'm also experiencing this issue with `ACCOUNT_EMAIL_VERIFICATION` and `SOCIALACCOUNT_EMAIL_VERIFICATION` set to `mandatory`. I understand where @pennersr coming from, although I wish there was an easier way to override this behavior. A lot of none tech folks seem to forget that a lot of applications use emails as the main channel of communication.

What's your workaround @vaimdev?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1692
