### ISSUE TITLE
About weixin  two kinds of oauth2 authorization

### ISSUE THREAD

**Issue by cestq** [pennersr/django-allauth#1694]
Weixin supports two kinds of oauth2 authorization, one for open platform and one for media platform.
If I use

SOCIALACCOUNT_PROVIDERS = {
    'weixin': {
        'AUTHORIZE_URL': 'https://open.weixin.qq.com/connect/oauth2/authorize',  # for media platform
    }
}

I can't use it for open platform at the same time。

I want to use two kinds of oauth2 authorization at the same time，Users choose it according to their own situation。

How to do？

**Comment by derek-adair** [comment]
Probably worth leaving open + welcoming a PR.  Looks like there could be another provider candidate here.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1694
