### ISSUE TITLE
Slack OAuth Returning Empty Error & Exception After Handshake

### ISSUE THREAD

**Issue by alfredn** [pennersr/django-allauth#1696]
When using Slack to authenticate users using django-allauth, after authorization django-allauth fails. I overrode the default socialaccount/authentication_error.html template to read as:

```Code: {{ auth_error.code }}, Error: {{ auth_error.exception }}```

And what is returned is:

```Code: unknown, Error:```

Which is essentially:
code: Unknown 
error: None

There is no traceback returned or shown upon error. It would be nice to either get some help on this or either have some way to debug this issue in a more verbose manner. Thanks!

**Comment by alfredn** [comment]
Turns out this was a 403 issue with 'socialaccount_state' after further debugging.

**Comment by alfredn** [comment]
After debugging:

`socialaccount_state` is empty, causing a `PermissionDenied()` error, very similar to https://github.com/pennersr/django-allauth/issues/583

**Comment by alfredn** [comment]
#583

**Comment by alfredn** [comment]
Figured it out, using wrong url. Thanks.

**Comment by ManuelBuri** [comment]
@alfredn I have the same error... what did you mean by using wrong URL?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1696
