### ISSUE TITLE
Facebook login is logging me in facebook too

### ISSUE THREAD

**Issue by destroyer08** [pennersr/django-allauth#1697]
Hi

When I am logging in to my app using facebook, It is also logging me in facebook but for linkedin everything is working fine.
When I login to my app it should not login to platform (facebook/linkedin). I am using following url for both linkedin and facebook.

'{% provider_login_url "facebook" %}'

Thanks!

**Comment by pennersr** [comment]
This is default FB behavior, beyond scope of allauth.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1697
