### ISSUE TITLE
Signup using phone number instead of email

### ISSUE THREAD

**Issue by gabn88** [pennersr/django-allauth#1700]
I'm wondering where to start to allow users to signup using the (mobile) phone with text message verification instead of email verfication.

Is there some hook I can attach allauth to? Or maybe should I write a provider for it?

**Comment by Misaghlb** [comment]
its my question too

**Comment by fangaofeng** [comment]
i need it .
  [for example, django-phoneuser](https://github.com/kunalgrover05/django-phoneuser)

**Comment by pennersr** [comment]
For now, this is not in scope of allauth. Though I think it should be quite doable to implement this on top of allauth -- something to be picked up as a separate project.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1700
