### ISSUE TITLE
Unnecessary fbsr facebook cookie

### ISSUE THREAD

**Issue by vsemionov** [pennersr/django-allauth#1701]
After visiting the login page, the fbsr_<appID> cookie is set if the facebook provider is available. It is never cleared and sent with every subsequent request to the application. This only happens if I currently have an active facebook session.

The cookie value is quite large and significantly increases the request size. The request becomes more difficult to read. I am not sure if setting the cookie has security implications.

I was able to workaround this by setting the cookie parameter of FB.init() to false in fbconnect.js.

**Comment by pennersr** [comment]
See 5916e90487fe815acc60ff744ff05bbdb05fa3d4

**Comment by vsemionov** [comment]
Thanks, Raymond

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1701
