### ISSUE TITLE
How change access permission for user's token?

### ISSUE THREAD

**Issue by russtanevich** [pennersr/django-allauth#1703]
use for VK
- for getting user token need send from server request like
https://oauth.vk.com/access_token?client_id={{....}}&client_secret={{...}}&redirect_uri={{...}}&code={{...}}

- the last parameter of url request, CODE, we get from request like
https://oauth.vk.com/authorize?client_id={{...}}&display={{...}}&redirect_uri={{...}}&scope={{...}}&response_type=code&v=5.63

OK. I use django-allauth library. I get user token. And this token don't allow some action with user VK groups.
Token permission define in the fourth parameter of  CODE url request  "scope". For my case need "group" into "scope" parameter.
Because I want to change for my application this parameter.

Tell me please, where I can change this parameter. Thank you.

**Comment by russtanevich** [comment]
I find one method to change permission for user's token
copy 'allauth' folder to your project and delete from envairoment
`$ pip3 uninstall django-allauth`
restart computer
go to ` {your_project_folder} / allauth / socialaccount / providers / vk / provider.py`

Find class:
```
class VKProvider(OAuth2Provider):
    id = 'vk'
    name = 'VK'
    account_class = VKAccount

    def get_default_scope(self):
        scope = []
        if app_settings.QUERY_EMAIL:
            scope.append('email')
        return scope
```
Read about permissions at `https://vk.com/dev/permissions`
And, for example, you may add into list `scope = ['groups']`

That token (which you get from user) will have more permissions.
It is fit for me

**Comment by pennersr** [comment]
You can configure the scope per provider using the SOCIALACCOUNT_PROVIDERS settings. There is no need to alter that method.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1703
