### ISSUE TITLE
[Need Help] How can I change order of fields in SignupForm?

### ISSUE THREAD

**Issue by ravinimmi** [pennersr/django-allauth#1706]
I am trying to extend `SignupForm` by including extra fields. I am following [this stackoverflow answer ](http://stackoverflow.com/a/12308807/5677984). Everything is working fine but the fields `first_name` and `last_name` appear before all other fields in the form. I want to change the order of these fields. How Can I proceed to do that?

Thanks,
Ravi

**Comment by danidee10** [comment]
@ravinimmi are you rendering unpacking the form manually or are you using `{{ form.as_p }}`?. If you aren't unpacking it manually i'll advice that you do that as that is the most flexible way to customize forms in django

**Comment by pennersr** [comment]
See #1226 -- use field_order.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1706
