### ISSUE TITLE
Got IntegrityError

### ISSUE THREAD

**Issue by PureWhiteWu** [pennersr/django-allauth#1707]
i'm always having IntegrityError when using django1.8 and allauth 0.31

i think this may be caused by a user clicking too fast when signin or signup.

**Comment by daniel48** [comment]
![error](https://cloud.githubusercontent.com/assets/3314335/25140539/4c98e9f4-2493-11e7-93b8-309051301f62.jpg)

**Comment by pennersr** [comment]
You may want to add a bit of JS to your pages to disable post buttons while the submit is ongoing. Closing this, as this goes beyond auth scope ...

**Comment by PureWhiteWu** [comment]
i think backend should handle this. 
You know, frontend is not trustable.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1707
