### ISSUE TITLE
Connect existing django's account to social login

### ISSUE THREAD

**Issue by denisviklov** [pennersr/django-allauth#1715]
Hi guys, I'm using your package and my aim to tie social login to existing django's account,
The scenario is: 1. User login with his django's credentials, 2. Proceed to profile page, 3. Connect his google/facebook or whatever account to existing and be able login with it.

I just surprised when I find things like that in the code
`        if connect:
            # TODO: Add any new email addresses automatically?
            pass`

and that's this mean? I cant do very basic thing with your package, maybe you can explain me for that reason it exists?

**Comment by pennersr** [comment]
Your scenario is covered, after logging in, visit `/accounts/social/connections/`

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1715
