### ISSUE TITLE
Verification email not sent right after signup, it is sent only if I try to log in:

### ISSUE THREAD

**Issue by survivor956** [pennersr/django-allauth#1719]
Hello I am using allauth with:
* custom Django user:  `class Profile(AbstractUser)`
* Custom Signup form:  `class ProfileForm(UserCreationForm)`
*  Alluth account adapter: `AccountAdapter(DefaultAccountAdapter)`

And these are my settings:
```
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Some really nice defaults
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'

ACCOUNT_ALLOW_REGISTRATION = env.bool('DJANGO_ACCOUNT_ALLOW_REGISTRATION', True)
ACCOUNT_ADAPTER = 'strateole2.profiles.adapters.AccountAdapter'
# SOCIALACCOUNT_ADAPTER = 'strateole2.profiles.adapters.SocialAccountAdapter'

# Custom user app defaults
# Select the correct user model
AUTH_USER_MODEL = 'profiles.Profile'
ACCOUNT_SIGNUP_FORM_CLASS = "strateole2.profiles.forms.ProfileForm"
LOGIN_REDIRECT_URL = '/'
LOGIN_URL = 'account_login'

# SLUGLIFIER
AUTOSLUG_SLUGIFY_FUNCTION = 'slugify.slugify'
```
When I fill the sgnup form and hit signup, the user is created and I it tells me "We have sent an e-mail to you for verification" like this:
 https://www.dropbox.com/s/0lk4osoeuoswt9k/Capture%20du%202017-04-25%2012-47-27.png?dl=0
But the e-mail is not sent.

But then, when I try to log in with the newly created profile, the email is SENT correctly and I get this:
https://www.dropbox.com/s/r9ty3jxvbj7lm1p/Capture%20du%202017-04-25%2012-50-45.png?dl=0

You can see that in the second picture that there is a message in blue that is not there in the first picture.

I use `console.EmailBackend` locally and `mailgun.MailgunBackend` with `anymail` on dev server.
Please help, the issue is very inconvenient to me and to future users.

**Comment by survivor956** [comment]
Figured out the problem was that I had a problem (email is saved before user) and then I did some work-around to make the e-mail be saved after user, but that fix caused that the email was not available to [complete_signup](https://github.com/pennersr/django-allauth/blob/55965c961f0aec2cf2643bf278cd00bd91f8bc80/allauth/account/utils.py#L171) but. 
I solved the issue by adding `save` method to the custom form, in save method I just save the user to make it ready to be used for relationships.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1719
