### ISSUE TITLE
.mo files ignored

### ISSUE THREAD

**Issue by eriktelepovsky** [pennersr/django-allauth#1721]
I noticed the *.mo is present in the .gitignore file. Is there any particular reason for this?

Wouldn't be more convenient to put .mo files into repository too?

**Comment by pennersr** [comment]
The .mo files are machine object files, they are not checked in for the same reason .pyc files are not checked in: they do not represent source code.

**Comment by eriktelepovsky** [comment]
So what is your recommended way of compiling and using .po files of third-party apps into the project?

All famous libs are including .mo files in their repositories, including:
- django-debug-toolbar
- django-filter
- django-formtools
- django-rosetta

... and, wait for it.... DJANGO itself!

I don't see anything bad of putting compiled .mo catalogs into the package. The translation should actually work automatically once the package is installed...

**Comment by pennersr** [comment]
Could you elaborate a bit on the problem you are trying to tackle? I do not see how adding .mo files would help with "compiling and using .po files of third-party apps into the project" ?

**Comment by jonashaag** [comment]
This affects me too. How are you supposed to use translations in your project? Django needs them in compiled .mo form.

Yes you could run `compilemessages` in the source directory where allauth is installed (i.e. `cd venv/lib/pythonX.Y/site-packages/allauth; django-admin compilemessages`) but that's very cumbersome.

You'd expect that `pip install` also installs the package's translation files in a form ready for use in your deployment.

**Comment by pennersr** [comment]
If you pip install the package, the .mo files are installed.

**Comment by jonashaag** [comment]
I see; translation files are included in the PyPI upload but not in the repository, so if you install from Git they're not included, which is perfectly reasonable.

**Comment by lukeburden** [comment]
What negatives are there to including .mo files in the repo? As observed earlier in this thread, most prominent Django projects, including Django itself, include them.

I suspect most prominent Django projects, including Django itself, include them because:
- there are no real negatives
- it avoids translation side-effects that are specific to *how* you obtain and run the code

The second is a real benefit, as in the real world code does end up being run other than just being pip installed. A simple example would be someone cloning directly from Github. Another might be using pip install, but using the git/ssh format to install a specific commit:

> pip install git+https://github.com/pennersr/django-allauth.git@55e12f9ec1f83f82a2013a9a840ab71e596c0aac

I'd suggest just including the .mo files; there don't seem to be any downsides and ultimately it will save some non-zero amount of developer effort debugging translations. What do you think, 
 @pennersr ?

**Comment by pennersr** [comment]
Including the .mo files would indeed make sure that pip installing directly from the repo directly installs the .mo files, but, it is possible to achieve the same result by doing something like this in the setup.py: https://stackoverflow.com/questions/34070103/how-to-compile-po-gettext-translations-in-setup-py-python-script

As for negatives, what are the negatives of including any source-derived file in the repository (say .pyc, webpack bundles, minified js/css, other binaries and executables, ...)? Having these in there, while sometimes handy, is IMHO not correct and will grow the repo size.

Though I must admit, I haven't looked into how viable it is to compile these from within the setup.py. If that really is messy and impractical, then there is little choice left but to put them inside the repo.

**Comment by pennersr** [comment]
Btw, issue #1032 is still open to look into this further. Also see the example setup.py mentioned over there:

https://github.com/slav0nic/DjangoBB/blob/master/setup.py#L9-L31

**Comment by lukeburden** [comment]
Ah right, will leave this issue be then and comment further there .. ta!

**Comment by allexiusw** [comment]
> Btw, issue #1032 is still open to look into this further. Also see the example setup.py mentioned over there:
> 
> https://github.com/slav0nic/DjangoBB/blob/master/setup.py#L9-L31

I see this way as reasonably solution, using pip you will have translations but it doesn't mean that they are in the repository hosted, I'm not the one that likes binary code in my repo, that's why I will use this approach in my projects.

**Comment by eriktelepovsky** [comment]
Please include .mo files in the repository or add compile script into setup.py. It would be really useful. Thank you very much!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1721
