### ISSUE TITLE
Update .po

### ISSUE THREAD

**Issue by tishibas** [pennersr/django-allauth#1724]
Messages were changed in https://github.com/pennersr/django-allauth/commit/79026f3f1943c39ee3f3cd6612d3a0b7e89a3d16 ,
But .po files have not been updated yet.

ex. https://github.com/pennersr/django-allauth/blob/abf0e802459579b20c10e91ad564b62ed0da6a91/allauth/locale/ar/LC_MESSAGES/django.po#L415-L417

Please update .po files

**Comment by pennersr** [comment]
Closed via 1e526edc23ef8267637ba6a1af838002c364a9a3

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1724
