### ISSUE TITLE
KeyError at /accounts/twitch/login/callback/

### ISSUE THREAD

**Issue by youngvenus** [pennersr/django-allauth#1725]
I'm already using the google social authenticator and it works just  fine, now i'm trying to set up twitch login, all the credentials and the redirect URL check out, and i wound up in this error with debug.
 
The URI that shows this error screen is this one:
http://localhost:8000/accounts/twitch/login/callback/?code=98pz0cifj9pkqdcdeqhys85php6b5y&scope=&state=OrDxInT4PhFz

```
Request Method:	GET
Request URL:	http://localhost:8000/accounts/twitch/login/callback/?code=98pz0cifj9pkqdcdeqhys85php6b5y&scope=&state=OrDxInT4PhFz
Django Version:	1.11
Exception Type:	KeyError
Exception Value:	
'_id'
Exception Location:	C:\Python34\lib\site-packages\allauth\socialaccount\providers\twitch\provider.py in extract_uid, line 23
Python Executable:	C:\Python34\python.exe
Python Version:	3.4.4
```

And when i reproduce this error without debug mode, i end up in the exact same URI and i just says 
"Internal server error(500)"

I have Google plus authentication and it works perfectly and i never saw any errors like that.

**Comment by eisenheimjelid** [comment]
Hi!

Did you solve it? I think you need made first the migration on the database, maybe the error is about  the django can't find the model where save the key from twitch.

Regards.

**Comment by sydhenry** [comment]
I had the same issue as you did. That `KeyError` happens when the Twitch API has an error. The error I got was:

```
{'error': 'Unauthorized', 'status': 401, 'message': 'authentication failed'}
```

When I added 

```
SOCIALACCOUNT_PROVIDERS = {
    'twitch': {
        'SCOPE': ['user_read',]
    },
}
```

to my settings.py it then worked. This makes me think that the issue is not having the scope to get login information.

**Comment by derek-adair** [comment]
Worth looking into @pennersr -- i'm not in a position to verify this bug or not.

**Comment by pennersr** [comment]
The key error is about `'_id'` -- earlier versions used that, current Twitch uses `'id'`.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1725
