### ISSUE TITLE
protocol http but port 443

### ISSUE THREAD

**Issue by andreav** [pennersr/django-allauth#1726]
Hi,
I successfully set up allauth with twitter, google plus, facebook.

However after a strange django error 

```
[Django] ERROR (EXTERNAL IP): Invalid HTTP_HOST header: 'www.facebook.com:443'. You may need to add u'www.facebook.com' to ALLOWED_HOSTS.
T
```

I debugged login.

For example, for twitter login, I get this strange callback, note http as protocol but 443 as port (from Chrome debug console):

```
Request URL:https://api.twitter.com/oauth/authenticate?oauth_token=DqbhTwAAAAAAxYnUAAABW9AwtPM&oauth_callback=http%3A%2F%2Ftrip2go.tours%3A443%2Faccounts%2Ftwitter%2Flogin%2Fcallback%2F
Request Method:GET
Status Code:200 

```

And I'm supposing this is sometimes confusing my week nginx server blocks configuration, so the django error.

By the way, I can login anyway, I woul like to know if this could be an issue.

Moreover, also Facebook behaves the same.
Google, instead, is working correctly.

----------- Additiona infos:

My site is entirely on https (and 301 redirects http to https)

My allauth configuration:

`django-allauth==0.32.0`

```
LOGIN_REDIRECT_URL = '/'

ACCOUNT_AUTHENTICATION_METHOD = "username_email"
ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = "optional"
ACCOUNT_USERNAME_MIN_LENGTH = 2
ACCOUNT_LOGOUT_ON_GET = True

ACCOUNT_DEFAULT_HTTP_PROTOCOL = "https"
```

Thank you.

**Comment by eisenheimjelid** [comment]
Hi!,

Did you solve it? That is a common error when we put django on the "real world", for make it simple, you need to change that in your settings.py:
```
ALLOWED_HOSTS = ['*']
```
Is only a restriction for security, you can read more about that in: https://docs.djangoproject.com/en/1.11/ref/settings/#allowed-hosts

**Comment by andreav** [comment]
Hi, thank you.
Opening ALLOWED_HOSTS does not seem to be a good idea (at least according
to those links you referenced).
I'm a bit worried by those security issues...

Anyway I'll try this, thank you.



Il 12/mag/2017 15:11, "Jelid Leon" <notifications@github.com> ha scritto:

Hi!,

Did you solve it? That is a common error when we put django on the "real
world", for make it simple, you need to change that in your settings.py:

ALLOWED_HOSTS = ['*']

Is only a restriction for security, you can read more about that in:
https://docs.djangoproject.com/en/1.11/ref/settings/#allowed-hosts

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/pennersr/django-allauth/issues/1726#issuecomment-301072254>,
or mute the thread

**Comment by eisenheimjelid** [comment]
Sure!, but if you want to test, and works with '*' on ALLOWED_HOSTS, you only need add www.facebook.com to your ALLOWED_HOSTS

**Comment by pennersr** [comment]
Closing deployment related issue https://django-allauth.readthedocs.io/en/latest/faq.html#why-did-you-just-close-my-issue

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1726
