### ISSUE TITLE
How to edit the original templates and to use them into my project

### ISSUE THREAD

**Issue by ZaibiMughal** [pennersr/django-allauth#1727]
From the past 3 days i have been trying very hard to use the original templates into my project but i am unable to do that. Please help me out. How can  do that. You have written a doc about templates on which you have told that when you will have a template named 'login.html' into your project then it will override the existing one. It's not working!

**Comment by Alexeyisme** [comment]
1. Create `account` folder in your project's `templates` folder
2. Add there the templates you want to change from `site-packages/allauth/templates/account`
3. Modify added templates.

**Comment by pennersr** [comment]
Thanks @Alexeyisme .... closing, not an issue in allauth.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1727
