### ISSUE TITLE
strange user auth bug

### ISSUE THREAD

**Issue by mengkheang** [pennersr/django-allauth#1729]
I have `base.html` that include my `header.html` which all templates are extending from.

In `header.html`

```
{% if user.is_authenticated %}
    <li><a href="#"><i class="fa fa-user" aria-hidden="true"></i> {% user_display user %}</a></li>
    <li><a href="{% url 'account_logout' %}"><i class="fa fa-sign-out" aria-hidden="true"></i>Sign Out</a></li>
    {% else %}
    <li><a href="{% url 'account_login' %}"><i class="fa fa-sign-in" aria-hidden="true"></i> Sign In </a></li>
    <li><a href="{% url 'account_signup' %}"><i class="fa fa-user" aria-hidden="true"></i> Register</a></li>
{% endif %}
```

https://media.giphy.com/media/l4FGp1diAxEhRmBPi/giphy.gif

As you can see in the gif I'm already sign out but at `home` page I still got the username and sign out button but when I go to `contact` page it shows sign in and register. I'm out of idea.

**Comment by mengkheang** [comment]
I found the solution I just put the Django cache in the wrong order.

```python
MIDDLEWARE = [
    'django.middleware.cache.UpdateCacheMiddleware', # must be first order
    ...
    'django.middleware.cache.FetchFromCacheMiddleware', # must be in the last order
]
```

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1729
