### ISSUE TITLE
SocialApp matching query does not exist. (Using LinkedIn)

### ISSUE THREAD

**Issue by civilian-** [pennersr/django-allauth#173]
I tried grabbing the /example app and am trying a LinkedIn login, however I keep recieving this error when trying to navigate to `localhost:8000/accounts/linkedin/login/`.

```
DoesNotExist at /accounts/linkedin/login/
SocialApp matching query does not exist.
Request Method: GET
Request URL:    http://localhost:8000/accounts/linkedin/login/
Django Version: 1.4.3
Exception Type: DoesNotExist
Exception Value:    
SocialApp matching query does not exist.
```

My `INSTALLED_APPS` has the following `'allauth.socialaccount.providers.linkedin'` as well, so I'm not quite sure what is wrong. Any thoughts?

**Comment by tweep** [comment]
I added some comments to this ticket which addresses a similar issue: 
https://github.com/rtfd/readthedocs.org/issues/2243

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/173
