### ISSUE TITLE
URL Blocked: This redirect failed because the redirect URI is not whitelisted in the app’s Client OAuth Settings. Make sure Client and Web OAuth Login are on and add all your app domains as Valid OAuth Redirect URIs.

### ISSUE THREAD

**Issue by zumzar96** [pennersr/django-allauth#1730]
I'm trying to allow users to login with facebook to my website but I am getting the following error:
URL Blocked: This redirect failed because the redirect URI is not whitelisted in the app’s Client OAuth Settings. Make sure Client and Web OAuth Login are on and add all your app domains as Valid OAuth Redirect URIs.
I configured my Facebook app like this:
1.Made it Public
2.Website
site URL: http://localhost:8000/ (since I'm running locally)
3. App Domains:Empty
4.Client OAuth Login -ON
Web OAuth Login -ON
5.Valid OAuth redirect URIs: http://localhost:8000/

**Comment by pennersr** [comment]
https://django-allauth.readthedocs.io/en/latest/faq.html#why-did-you-just-close-my-issue

**Comment by kerkeslager** [comment]
The short summary is you need to whitelist `http://localhost:8000/accounts/facebook/login/callback/` (replace `http://localhost:8000` with the URL of your site, including `https://`, if you're running into this problem in production).

**Comment by Praveenmendegar4** [comment]
After continue as facebook account, it displaying site -->> This site can’t be reached.

**Comment by 2015pgcaca44** [comment]
i am getting this error to loggin into facebook from my laravel code.
URL blocked: This redirect failed because the redirect URI is not white-listed in the app's client OAuth settings. Make sure that the client and web OAuth logins are on and add all your app domains as valid OAuth redirect URIs.

I configured my Facebook app like this:
1.Made it Public
2.Website
site URL: http://localhost:8000/ (since I'm running locally)
3. App Domains:Empty
4.Client OAuth Login -ON
Web OAuth Login -ON
5.Valid OAuth redirect URIs: http://localhost/callback

plz help

**Comment by morenoh149** [comment]
@2015pgcaca44 this repo is for a django app not laravel.

+1 @kerkeslager I have to specify `https://<your domain>/accounts/facebook/login/callback/` in the facebook app dashboard > Facebook Login > Settings > Valid OAuth Redirect URIs section. Fyi facebook will remove any uris that are not https for you.

**Comment by Dihfahsih1** [comment]
> @2015pgcaca44 this repo is for a django app not laravel.
> 
> +1 @kerkeslager I have to specify `https://<your domain>/accounts/facebook/login/callback/` in the facebook app dashboard > Facebook Login > Settings > Valid OAuth Redirect URIs section. Fyi facebook will remove any uris that are not https for you.

Thanks, this was helpful

**Comment by lifeofsa** [comment]
> i am getting this error to loggin into facebook from my laravel code. URL blocked: This redirect failed because the redirect URI is not white-listed in the app's client OAuth settings. Make sure that the client and web OAuth logins are on and add all your app domains as valid OAuth redirect URIs.
> 
> I configured my Facebook app like this: 1.Made it Public 2.Website site URL: http://localhost:8000/ (since I'm running locally) 3. App Domains:Empty 4.Client OAuth Login -ON Web OAuth Login -ON 5.Valid OAuth redirect URIs: http://localhost/callback
> 
> this is my services.php 'facebook' => [ 'client_id' => '*****************', 'client_secret' => '*************************************', 'redirect' => 'https://localhost:8000/callback', 'default_graph_version' => 'v4.0', ],
> 
> this is my controller
> 
> redirect(); } public function callback() { return Socialite::driver('facebook')->redirect(); // return redirect()->to('http://localhost:8000/callback'); } } and this is web.php name('home'); plz help

remove https in redirect and write http

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1730
