### ISSUE TITLE
Double-clicking on the sign up button returns an error and doesn't log the user in

### ISSUE THREAD

**Issue by boosh** [pennersr/django-allauth#1731]
When I sign up if I accidentally double click the "Sign up" button, I get an error that the user already exists.

The sign up form should really check whether, if the user name exists, the email matches and the password is valid just log the user in.

**Comment by pennersr** [comment]
I have to disagree here. A signup process should not implicitly start behaving like a login page. To prevent double click problems, make sure you disable the button using a bit of JS.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1731
