### ISSUE TITLE
How to use allauth with Jinja2 Templates ?

### ISSUE THREAD

**Issue by subhajeet2107** [pennersr/django-allauth#1732]
I can see there is a ACCOUNT_TEMPLATE_EXTENSION settings, but the templates which are loaded in views only support django templates, or am i missing something ?

**Comment by pennersr** [comment]
There is nothing specific with respect to allauth and Jinja2, please consult the regular Django documentation. That setting can be set to '.j2' so that allauth will search for such files instead of the regular '.html'.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1732
