### ISSUE TITLE
Form Errors on Custom SignUp

### ISSUE THREAD

**Issue by formatically** [pennersr/django-allauth#1736]
Hi!  I've been using allauth for a few days now and absolutely love it!  I am however stuck on a slight problem.

I made custom login and signup pages and the login page is working great.  I have everything working with it including form errors.  However form errors on the custom signup page are not showing up.  

In my login form I have the following placed in the form.  
          {{form.non_field_errors}}
          {{ form.login.errors }}

I tried doing the same in the SignUp form with no luck.   Even tried form.signup.errors, if that is even a thing.   Anytime there is a form error, such as "email already exists, etc" the page just reloads and no errors are shown.  

Any help would be appreciated!

**Comment by formatically** [comment]
Okay I found that using {{ form.errors }} fixed the issue.  However can edits be made to the errors?  For example, a password too short returns "Password1:  This password is too short. It must contain at least 8 characters."   To users, "password1" wouldn't make much sense I don't think.    Much rather it say just "password" or remove it all together.  Any way to achieve this? Thanks!

**Comment by formatically** [comment]
Sorry, I just found the solution.  Found this snippet of code that works perfectly in displaying proper error messages! Hopefully this post will help someone in the future.

The code is in the answer of this stackoverflow question: https://stackoverflow.com/questions/24273839/django-allauth-custom-login-does-not-show-errors

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1736
