### ISSUE TITLE
PasswordField is failing in django master

### ISSUE THREAD

**Issue by laevilgenius** [pennersr/django-allauth#1738]
PasswordField applies translation to already translated label [here](https://github.com/pennersr/django-allauth/blob/625be21b66d01bb6a6a4b82159cc40a03f326644/allauth/account/forms.py#L53), which makes Django 2.0.dev to fail with `TypeError: __str__ returned non-string (type __proxy__)`

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1738
