### ISSUE TITLE
Update the details each time when the user is logged in?

### ISSUE THREAD

**Issue by avinassh** [pennersr/django-allauth#1742]
My settings:

```python
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
SOCIALACCOUNT_AUTO_SIGNUP = False
```

Used Github for testing. Consider this scenario:

1. On my Github, I had email, `1@email.com`
2. When I logged into my app, it created an account and used email as `1@email.com`
3. Now I changed my email on Github with `2@email.com`
4. When I logged into my app, I logged into same account but the email remains unchanged i.e. `1@email.com`

Is this expected behaviour? Do I need to write a custom adapter to handle this case?

**Comment by pennersr** [comment]
This situation is similar to this open issue: https://github.com/pennersr/django-allauth/issues/114#issuecomment-8576150 

Marking this as a duplicate.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1742
