### ISSUE TITLE
Avoid email verification if the user's email is already verified on the provider?

### ISSUE THREAD

**Issue by avinassh** [pennersr/django-allauth#1743]
I am using Github and I want verified email addresses. If Github is already verifying the emails, then why do I have to send verification emails? 

Is this expected behaviour? Is there any reason behind this? 

Or shall I write a custom adapter and check myself?

**Comment by skrivanos** [comment]
There's a setting for that on the providers called VERIFIED_EMAIL.

```
SOCIALACCOUNT_PROVIDERS = {
    'github': {
        'VERIFIED_EMAIL': True
    }
}
```

**Comment by pennersr** [comment]
Correct - Thanks @skrivanos

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1743
