### ISSUE TITLE
Going from ACCOUNT_EMAIL_VERIFICATION "optional" to "mandatory"

### ISSUE THREAD

**Issue by skrivanos** [pennersr/django-allauth#1744]
Is there a way to do this so that the mandatory verification only applies to new users? Of course I could in theory update the database and set verified to True on all emails but that would be corrupting the data.

**Comment by pennersr** [comment]
What is needed here is to add some kind of get_email_verification_mode(user) to the adapter class, instead of looking it up at a fixed setting. Then, you would be able to put any kind of logic in there, like if user.date_joined >= 2017-07-25 and so on...

**Comment by pennersr** [comment]
Marking as duplicate of #1776

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1744
