### ISSUE TITLE
Manual user creation

### ISSUE THREAD

**Issue by johndoefromhere** [pennersr/django-allauth#1748]
Is there any way to create a user manually and send him a set-password email?

`User.objects.create(email=email)`

The above code ends with `Duplicate entry '' for key 'username'` as it tries to save username as empty string. Any suggestions?

I'm using emails as usernames, while email activation is optional:

```
ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = "optional"
ACCOUNT_USERNAME_REQUIRED = False
```

**Comment by JooeunAhn** [comment]
Use create_user method in django.contrib.auth.models.UserManager

https://docs.djangoproject.com/en/1.11/ref/contrib/auth/#django.contrib.auth.models.UserManager.create_user.

and then,  read these docs,
https://docs.djangoproject.com/en/1.11/ref/contrib/auth/#django.contrib.auth.models.User.set_unusable_password
https://docs.djangoproject.com/en/1.11/topics/auth/default/#django.contrib.auth.views.PasswordResetView

**Comment by pennersr** [comment]
This is not something that allauth facilitates (nor should there be), nor is there anything in allauth that prevents you from manually doing this. So I am closing this...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1748
