### ISSUE TITLE
ACCOUNT_SIGNUP_FORM_CLASS, django.core.exceptions.ImproperlyConfigured: Module "" does not define a "" class

### ISSUE THREAD

**Issue by khorolets** [pennersr/django-allauth#1749]
Hi guys! Can someone help me to figure out what am I doing wrong?

I have `profiles.forms.ExtraDataSignupForm`:

```python
from django import forms


class ExtraDataSignupForm(forms.Form):
    country = forms.CharField(required=False)
    about = forms.CharField(required=False)
```

*NB* I know about required `signup` method, I'm not defining it to catch an exception about it.

In my `settings.py` I have:

```
ACCOUNT_SIGNUP_FORM_CLASS = 'profiles.forms.ExtraDataSignupForm'
```

And on running project I'm getting `django.core.exceptions.ImproperlyConfigured`:

```
django.core.exceptions.ImproperlyConfigured: Module "profiles.forms" does not define a "ExtraDataSignupForm" class
```

If I comment `ACCOUNT_SIGNUP_FORM_CLASS` in settings and try from shell:

```python
In [1]: from importlib import import_module

In [2]: f = import_module('profiles.forms')

In [3]: c = getattr(f, 'ExtraDataSignupForm')

In [4]: c
Out[4]: profiles.forms.ExtraDataSignupForm
```

Everything importing fine without errors.

What am I doing wrong? Could anyone help me?

Thanks!

**UPDATE**

Seems the problem is because I have also inherited from `SignupForm` and other custom forms for login, password reset and others.

**Comment by khorolets** [comment]
BTW is there a way to implement `ACCOUNT_FORMS` and `ACCOUNT_SIGNUP_FORM_CLASS` in the same time?

**Comment by khorolets** [comment]
So, for those who would suffer with the same issue:

The issue occurs if you have customized `SignupForm` with `ACCOUNT_FORMS` and extended the signup form with `ACCOUNT_SIGNUP_FORM_CLASS`. Make sure your custom `SignupForm` and your form for extension defined in different files.

In my case, I had them in the one file `profiles.forms` and there was a cycling import (I guess). I've moved my `ExtraDataSignupForm` to separate file and point to in in `ACCOUNT_SIGNUP_FORM_CLASS`, everything works like a charm. 

Good luck!

**Comment by nortigo** [comment]
I have no clue of what you did. For me it's not working. I know it's been a while but do you remember what you did?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1749
