### ISSUE TITLE
Is there a workflow that when user login with a social account, we prompt him bind an existed local account or just login directly(create a new user)

### ISSUE THREAD

**Issue by ghost** [pennersr/django-allauth#1751]
The scenario is:

An anonymous user login with a social account. When this done(before create a new user), we redirect him to a page that prompt him bind an existed local account(by typing his username/email and password in a form, and connet his local account to the social account), or just click the login directly button(then we create a new user).

I read the source codes but can not find a way to replace the default workflow to this. The default workflow is redirect a user to a signup page or auto signup a user(would create a new user).

**Comment by pennersr** [comment]
No, what is supported is the other way around: the user logs in ("by typing his username/email and password in a form") and then connects a new social account to his account.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1751
