### ISSUE TITLE
dynamic user_id on profile_url

### ISSUE THREAD

**Issue by MIKNOTAURO** [pennersr/django-allauth#1753]
Hi guys, I'm working with django-allauth and I'm trying to make my own provider for my oauth2 server (django-oauth-toolkit).
I have this url :
https://myserver.com/users/<user_id>/
From my API endpoint to get the user details.
My question is, 
How can I build this url on "profile_url" variable inside OAuth2Adapter subclass?
I just need to know how can I retrive the user_id to add it to the string.

Also I want to replace /accounts/login/ from allauth.account.views.LoginView just for /login/
#
any help will be appreciated
thanks.

**Comment by pennersr** [comment]
I think you need 2 separate Django projects for this. One, containing allauth, over at www.myserver.com, and the other, containing your own oauth2 provider, over at yourauth.myserver.com. Then, the allauth login remains as is, and when clicking your provider the user is redirected to yourauth.myserver.com, containing some way of authenticating (so a login of some sorts).

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1753
