### ISSUE TITLE
Add ACCOUNT_PASSWORD_REQUIRED

### ISSUE THREAD

**Issue by lorddaedra** [pennersr/django-allauth#1758]
Add ACCOUNT_PASSWORD_REQUIRED. If set to False, it's possible to create user without entering password on sign up page. (Going to do it later after email verification)... So will just email field on Sign Up page, currently it's not possible in default behavior...

**Comment by lorddaedra** [comment]
Solution looks simple, just change signup form __init__ method and add docs about ACCOUNT_PASSWORD_REQUIRED in settings.

@pennersr Are you interested in this patch?.. [Also I see my other 2 PRs, they are not merged for 2 weeks.. Check, please, #1746, #1747 ]

**Comment by 9mido** [comment]
@lorddaedra please make the patch. Other users have also expressed interest.

**Comment by derek-adair** [comment]
I set a random password and send an email w/ a link for them to set their password.  I can add this to the [list of recipe's](https://github.com/pennersr/django-allauth/discussions/3427)... but if there is an elegant solution to this it's probably worth adding. MAYBE as a config option but simply just supporting such a thing by making password not required on the user model may be nice.

**Comment by pennersr** [comment]
Just adding this setting and removing the password field leaves the system in an odd state, so it would also require adding some sort of forced password input when doing email verification. This scenario is not very common, not sure if it is worthwhile to add support for that out of the box given that you can already build this on top of allauth. If you want to use something like this, I suspect it would make for a better UX to use a magic link for signing in as well, so no password during signup AND login. All in all, this is quite a specific scenario, I think it is better handled elsewhere.

**Comment by derek-adair** [comment]
I tend to agree.  Also the workaround of setting a random password _(in the adapter btw in case anyone is wondering)_ and sending the set password link is a sufficient UX.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1758
