### ISSUE TITLE
ValueError: Base36 conversion input too large on utils.py

### ISSUE THREAD

**Issue by briva** [pennersr/django-allauth#1759]
Using https://github.com/potatolondon/djangae :

My id looks like that : 5579867965882368

I got error 500 on :

allauth/account/utils.py:393 :

```
if isinstance(ret, six.integer_types):
        ret = int_to_base36(user.pk)
```

ValueError: Base36 conversion input too large on utils.py

**Comment by pennersr** [comment]
This is a Python 2 specific issue, on Python 3 things are fine.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1759
