### ISSUE TITLE
Allow trusted providers to link different Uids to the same account

### ISSUE THREAD

**Issue by stanhu** [pennersr/django-allauth#176]
I would like the ability to trust certain providers (e.g. Google OpenID) to supply a verified e-mail address so that I can access the system from different URLs without having to create a new account.  Another words, I'm trying to solve the problem where if you login successfully with, say, http://localhost:8000 one day, and then decide to run the same server as http://localhost:9000 another day, that the different Uids generated from these URLs will still point to the same account.

StackOverflow has the best overview about the problem and what they did:

http://blog.stackoverflow.com/2010/04/openid-one-year-later/

"That’s a major bummer for site networks like us with multiple domains. We use the OpenID string as your user “fingerprint”, so if your “fingerprint” changes, we can’t tell who you are any more. It’s a frustrating problem, but we think we’ve finally come up with a fix: we demand email from Google GMail OpenIDs!

If we have an email address from a verified OpenID email provider (that is, an OpenID from a large email service we trust, like Google or Yahoo), then it’s guaranteed to be a globally unique string. We treat this as part of the identifying user token, attached only at login time, that is not editable by the user.

So our cross-site user account matching now works this way:

Match by GUID. This is something we generate and assign during account association, so it’s a perfect fingerprint.
Match by OpenID URL. This works for the vast majority of OpenID providers.
Match by OpenID provided email address … if you are on our trust whitelist. This works for those rare OpenID providers (currently, only Google GMail) who generate domain-specific identifiers.
This satisfies all known OpenID providers, so we can now potentially associate your accounts, across all of our websites, automatically. You’ll still have to log in, of course, but the login itself could trigger account association for every site in the network.

There is one, and only one downside: we must demand email from Google OpenIDs. Email is not usually required to use our sites, but you can’t log in via Google if you refuse to provide email to us. You can always switch OpenID providers, of course, but we regretfully must make the email demand mandatory in the case of Google."

I took a pass at hacking django-allauth to do something like this, but I don't think it's quite secure:

https://github.com/stanhu/django-allauth/commits/master

Do you have any opinions on:

1) Is this a good idea to provide a similar feature?
2) If so, what is the best approach?
3) How to improve upon what I attempted?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/176
