### ISSUE TITLE
Dropbox Oauth1 and v1 API is obsolete at June 28, 2017

### ISSUE THREAD

**Issue by pztrick** [pennersr/django-allauth#1760]
The `dropbox` OAuth1 provider will no longer work after June 28.

The `dropbox_oauth2` provider will also probably crash after June 28 as the `v1` API URIs are changing for both oauth2 flow and accessing user account info:
https://www.dropbox.com/developers/reference/migration-guide

My own project is hard-coded to rely on the provider name being `dropbox` and not `dropbox_oauth2` so I opted to just clobber the `dropbox/` provider with the workable `dropbox_oauth2/` code and then update this new oauth2 provider to use the newer Dropbox v2 API endpoints.

https://github.com/pztrick/django-allauth/commit/03f27e174d58b9204777186f6d15a6109ff1e21a

The commit above is working with Dropbox v2 API/OAuth2 but few problems:

1. I'm several hundred commits behind
2. We probably want to remove the redundant `dropbox_oauth2` provider OR refactor so that it uses same code / is backwards-compatible if people just to upgrade `allauth`.

I don't have time today to go all the way and a simple rebase against `upstream/master` produced errors so I can't make a clean P/R right now. Just wanted to share my commit here in case anyone else wants to take it up before I can get back to making a P/R. (I do expect the `dropbox_oauth2` to throw error retrieving account info like `display_name` after June 28.)

**Comment by pztrick** [comment]
Just added v2 API mocked response.

**Comment by pztrick** [comment]
Dropbox extended end-of-life for `v1` API to September 28, but I still think we should just remove the deprecated providers ASAP.

I am working on this today. I will use the `providers/dropbox/` path as the `dropbox_oauth2` path is also broken as the `uid` API is also changed in new `v2` API.

https://github.com/pztrick/django-allauth/commit/185506a2ab0b456e58b0fdc12b26277f6eef3248#diff-e4f0354a5c0f9c199d925730639f9bd7R17

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1760
