### ISSUE TITLE
django allauth custom validation

### ISSUE THREAD

**Issue by karthikrajender28** [pennersr/django-allauth#1761]
I used django-allauth extension and it is very useful, but i don't need to use clean_username() and  clean_email()  but i need to use my custom validations to check username and email and one more custom field to be validated at the same. let say : check username, emailid and custom field say for example: phone at the same time.  is it good to edit the adapter.py in allauth or i need to override the adapter in my app. kindly give me a solution.

How can I get my custom field say phone no in clean_username and clean_email function so that i can validate it in that function itself. I have created a custom model to include the phone no field

**Comment by pennersr** [comment]
If you need to add validation that spawns multiple fields, you'll need to add a `def clean()` method to the custom signup form. Here, you are free to validate and raise errors as you see fit.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1761
