### ISSUE TITLE
Bug with removing EmailAddresses

### ISSUE THREAD

**Issue by lorddaedra** [pennersr/django-allauth#1762]
Steps to reproduce bug:
Register new user via sign up form. With user.email = 'myuser@example.com'. After that allauth will create new EmailAddress email='myuser@example.com',  'verified': False, 'primary': False, 

Combination of not empty user.email with 'primary': False for that email, will create this bug...

What do I expect:
User can go to /accounts/email/ and remove E-mail addresses. He/she can not remove primary E-mail.

What do I see:
User click to remove button and remove his/her last E-mail with success message. After that system create new EmailAddress object (with another id) and same E-mail. It mean, user see success message about he/she deletes that email and see same E-mail in list of E-mail addresses again. And, it's more dangerous, he can break all relationships, if he/she has any with old EmailAddress object and will not understand, why...

Solution:
So during registration step system should create EmailAddress with 'primary': True, 

Some questions about design:

1. If go deeper, why do the duplicate primary email mechanism?.. 
I mean what is primary email? 
E-mail, which set in user model for that User?
Email, which has EmailAddress object with  'primary': True, ?

2. What if E-mail not in user.email but has has EmailAddress object with  'primary': True, ?

3. What if E-mail in user.email but user has no related EmailAddress object or EmailAddress with 'primary': False, ? [this is my case, this bug about it]

4. What do we lose if we will remove 'primary' attribute from EmailAddress model at all?..

**Comment by lorddaedra** [comment]
> What do we lose if we will remove 'primary' attribute from EmailAddress model at all?
Even better create primary_email = ForeignKey(EmailAddress) in User model.

**Comment by lorddaedra** [comment]
Okay, you will see this bug only if you use custom register form, which will not create EmailAddresses.

And later after you will EmailView page (/accounts/email), system will try to sync emails and create new EmailAddress with primary is False... 

It's possible to fix this issue by overriding _action_remove in EmailView,
replace `if email_address.primary:` line to `if email_address.primary or EmailAddress.objects.filter(user=request.user).count() == 1:`

Also it's possible to change `sync_user_email_addresses` function in utils.py and set `primary=True,` there instead of `primary=False,`

**Comment by pennersr** [comment]
> Okay, you will see this bug only if you use custom register form, which will not create EmailAddresses.

IMHO this is the root cause of the issue. You should not stop allauth from creating the required email records.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1762
