### ISSUE TITLE
Bug with email confirmation of another user

### ISSUE THREAD

**Issue by stereoshoots** [pennersr/django-allauth#1765]
Hello!
Steps to reproduce the bug: 
1) Register user A
2) Register user B
3) Log in with user A
4) Click on User B confirmation link
5) Click on submit button

This way, user A which has no connection with User B can confirm his email.

Solution:
User should be logged on same user or should be AnonymousUser

**Comment by pennersr** [comment]
With email confirmation links, anybody who gains control of the link is able to confirm the email address. In your scenario above, it is not user A who is confirming the email address. It is the person clicking on the link in step 4. User A just happens to be the user that was logged in while the user (could be user A/B or even C/D) clicked the link. So I don't see an issue here.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1765
