### ISSUE TITLE
`next` parameter not respected on login, when using an absolute URL

### ISSUE THREAD

**Issue by jochenklar** [pennersr/django-allauth#1766]
When logged in, "next" after a GET to the login url is not respected if it starts with http://, e.g.: http://localhost:8000/accounts/login/?next=http://localhost:8000/foo/ redirects to http://localhost:8000 not to http://localhost:8000/foo/.

I think the reason is that in https://github.com/pennersr/django-allauth/blob/master/allauth/account/adapter.py#L420 allowed_hosts is not passed to django.utils.http.is_safe_url.

I fixed it in my custom adapter using:

    def is_safe_url(self, url):
        from django.utils.http import is_safe_url
        return is_safe_url(url, allowed_hosts=settings.ALLOWED_HOSTS)

**Comment by kateEcobb** [comment]
Submitted another PR with support for wildcard matching as well: https://github.com/pennersr/django-allauth/pull/3329

**Comment by pennersr** [comment]
Closing -- #3329 is merged

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1766
