### ISSUE TITLE
Ability to merge accounts

### ISSUE THREAD

**Issue by duck-rh** [pennersr/django-allauth#1767]
Quack,

There is a need to merge accounts, as explained in this ticket for Mailman3/Postorius: https://gitlab.com/mailman/postorius/issues/198

People can miss the feature to connect other social account to the allauth account, or simply make mistakes, but there's no easy way to do fix the situation.

\_o<

**Comment by malavwarke** [comment]
Yeah, the same thing making problem for me.
If a user logins with Facebook and then log out and later logins by google the two different users are created thus how to map that these two are the same users?

**Comment by pennersr** [comment]
See:
https://github.com/pennersr/django-allauth/issues/1264#issuecomment-175203546

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1767
