### ISSUE TITLE
Override `next` GET parameter

### ISSUE THREAD

**Issue by Ashish-Bansal** [pennersr/django-allauth#1768]
Quoting from here[0] : 
>    def get_login_redirect_url(self, request):
        """
        Returns the default URL to redirect to after logging in.  Note
        that URLs passed explicitly (e.g. by passing along a `next`
        GET parameter) take precedence over the value returned here.
        """

`next` GET parameter takes precedence over the value returned.
So, Is there any way I can override `next` GET parameter ? 

Not sure if `allauth.account.signals.user_logged_in` will be emitted after this and if using it for this purpose is a good practise.

Usecase : I want to redirect a special group of users to a specific page even if next parameter is present.

[0] https://github.com/pennersr/django-allauth/blob/master/allauth/account/adapter.py#L146

**Comment by derek-adair** [comment]
Close as out of scope / off topic.  This type of question can be directed to a chatroom (if we make one) or just stackoverflow / programmers exchange.  This is effectively a question about django [requests](https://docs.djangoproject.com/en/4.2/ref/request-response/).

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1768
