### ISSUE TITLE
Mock complete_social_login()

### ISSUE THREAD

**Issue by jonperron** [pennersr/django-allauth#1773]
Hello,

Mocking complete_social_login() does not seem straightforward to me. 
Considering the following test case, which **must be able** to be performed without an internet connection:
```
        account = SocialAccount(provider='google', uid='1234')
        sociallogin = SocialLogin(user=self.user, account=account)
        complete_social_login(self.request, sociallogin)
```

What seems the more logical to me was to use the `allauth.account.signals.user_logged_in(request, user)` signal. I ended up writing : 
```
        account = SocialAccount(provider='google', uid='1234',)
        sociallogin = SocialLogin(user=self.user, account=account)
        allauth.account.signals.user_logged_in.send(sender=self, request=self.request, user=self.user)
```
which leads to `ValueError: Cannot force an update in save() with no primary key.`

Am I missing something or this is a missing feature ? I looked at every test available in django-allauth and was unable to find a solution to mock this function offline.

**Comment by pennersr** [comment]
I am not sure what you are trying to do. If you need to mock that method, you could use something like https://docs.python.org/3/library/unittest.mock.html#unittest.mock.patch ?

**Comment by jonperron** [comment]
We decided not to go this way, so this issue can be safely closed !

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1773
