### ISSUE TITLE
Make email confirmation depend on the user

### ISSUE THREAD

**Issue by primal100** [pennersr/django-allauth#1776]
For many websites, it's typical to require regular users to confirm their email, but not staff or superusers which are not normally creating by registering but by other staff users. Would be great to have an easier way of implementing this in allauth (right now I can do it done by subclassing the LoginForm and overriding the login method, checking if email confirmation is needed for that user and passing that value to the user.

One way of implementing it would be to modify the login method to check if ACCOUNT_EMAIL_VERIFICATION is a callable and if so run the callable with the user as a paramater, which needs to return mandatory, optional or none, and then pass that value to perform_login.

**Comment by pennersr** [comment]
I am not sure your requirement is clear to me. If staff users are created by other staff users, then why do these newly created staff members have to validate their account at all? I would expect their newly created account to be all setup and ready to login?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1776
