### ISSUE TITLE
Authentication succeeds but also returns "Social Login Network Failure"

### ISSUE THREAD

**Issue by snawpy** [pennersr/django-allauth#1777]
Getting this issue with reddit authentication shown here: http://i.imgur.com/z8VTHDN.png

I get "Successfully signed in as poopoodeck." and the app gets added to my reddit's list of authorized applications perfectly fine. I don't think it can be a uri issue as that seems to make the request to reddit it self completely fail. 

In authentication_error.html I added:
Code: {{ auth_error.code }}, Error: {{ auth_error.exception }} and as you can see in the output it simply displays unknown and none so I'm pretty clueless on what the issue could be.

**Comment by pennersr** [comment]
Could it be that you were already logged in at the time of trying to login a second time?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1777
