### ISSUE TITLE
Error at /account/login in django allauth

### ISSUE THREAD

**Issue by ghost** [pennersr/django-allauth#178]
I have followed tutorial http://techstricks.com/django-allauth-tutorial-step-by-step/ and i open /account/login i encounter problem saying views ImportError at /accounts/login,
No module named views. My error trace's html is https://www.dropbox.com/s/2sawzbeyt57wkbp/ImportError%20at%20%20accounts%20login.html

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/178
