### ISSUE TITLE
Slack sign-in and email address 

### ISSUE THREAD

**Issue by peterbispham** [pennersr/django-allauth#1780]
I'm using allauth for Slack signin and collect user email addresses. I require the email as part of signup and the Slack app is configured to share email address. All works fine with version 0.30.0 and the email is collected okay (automatically during the signup flow).

However, in versions 0.31 and 0.32 the user is asked to enter their email address as a final step in the login flow. It seems the email isn't collected automatically from Slack responses anymore.

Couldn't find any extra requirements for Slack signup flow in the new versions, or any existing issues,  so thought I'd let you know.

Thanks :)

**Comment by pennersr** [comment]
Haven't actually tested this myself, but allauth is passing `identity` as scope, but is seems it should be `identity.basic` and, to get to the email, `identity.email`. You can check if this fixes things by adding a custom scope in the SOCIALACCOUNT_PROVIDERS settings for slack. Could you please report back if this is indeed the issue?

**Comment by peterbispham** [comment]
Thanks for your reply. Sorry for the late response.

Just done some testing. If I use django-allauth==0.30.0 all works fine in that I'm not asked for the email address on return to the app.

I have set 
SOCIALACCOUNT_PROVIDERS = {
     'slack': {
        'SCOPE': ['identity.basic', 'identity.email'],
    }
}

And although I am told when I sign into Slack that my app wants to:
"Confirm your identity and view your email address"

... I am still asked to manually input the email address on return to the app, even with the above scope setting when I use version 0.31 or 0.32.

Hope it helps. I can work with 0.30 :)

**Comment by melvyn-sopacua** [comment]
There's an actual bug here I think:

diff --git a/allauth/socialaccount/providers/slack/provider.py b/allauth/sociala
index b09321c..f99ca40 100644
--- a/allauth/socialaccount/providers/slack/provider.py
+++ b/allauth/socialaccount/providers/slack/provider.py
@@ -1,4 +1,3 @@
-from allauth.socialaccount import providers
 from allauth.socialaccount.providers.base import ProviderAccount
 from allauth.socialaccount.providers.oauth2.provider import OAuth2Provider

@@ -29,8 +28,7 @@ class SlackProvider(OAuth2Provider):
                     email=data.get('user').get('email', None))

     def get_default_scope(self):
-        return ['identity.basic', 'identity.email',
-                'identity.avatar', 'identity.team']
+        return ['identify']

Notice the "ef" versus the "tee" in "identify". Diff is 0.30.0..0.32.0 (tags).

**Comment by LukGerman** [comment]
Identify scope is too limited to get users email. You probably should use Custom adapter class. Here is snippet from my code:
`class CustomSlackOAuth2Adapter(SlackOAuth2Adapter):
    identity_url = 'https://slack.com/api/users.identity'

    def get_data(self, token):
        # Verify the user first
        resp = requests.get(
            self.identity_url,
            params={'token': token}
        )
        resp = resp.json()

        if not resp.get('ok'):
            raise OAuth2Error()

        # Fill in their generic info
        info = {
            'name': resp.get('user', {}).get('name'),
            'email': resp.get('user', {}).get('email'),
            'user': {
                'email': resp.get('user', {}).get('email'),
                'name': resp.get('user', {}).get('name'),
                'id': resp.get('user', {}).get('id')
            },
            'team': {
                'id': resp.get('team', {}).get('id')
            }
        }
        return info


oauth2_login = OAuth2LoginView.adapter_view(JogSlackOAuth2Adapter)
oauth2_callback = OAuth2CallbackView.adapter_view(JogSlackOAuth2Adapter)
`
and use your custom adapter on view:
`class SlackLogin(SocialLoginView):
    adapter_class = CustomeSlackOAuth2Adapter`

**Comment by ManuelBuri** [comment]
@LukGerman are you still using Slack as a Provider in your project?

**Comment by derek-adair** [comment]
Bump... 

[code looks the same](https://github.com/pennersr/django-allauth/blob/ba92ef383865ea3f529fa9b972ee615756b573fa/allauth/socialaccount/providers/slack/provider.py#L32).  Seems like it's still valid.

Any reason not to modify the slack adapter's get_data method to work like this?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1780
