### ISSUE TITLE
social_account_added is not sent when new user from social login is created

### ISSUE THREAD

**Issue by cypreess** [pennersr/django-allauth#1781]
I am pretty sure that signal `social_account_added` is never send in the scenario of creating new user while trying to login in using social adapter.

I had debugged it using pycharm debugger and this does not happen. My rationale is that social account is created (for just newly created account) and signal should be sent.

**Comment by derek-adair** [comment]
This seems to have been fixed [five months ago](https://github.com/pennersr/django-allauth/commit/da5ccdcf171e32ab1a438add3af38957f5a0659a)

**Comment by pennersr** [comment]
No, `social_account_added` is documented as:

```
# Sent after a user connects a social account to a their local account.
# Provides the arguments "request", "sociallogin"
```

For new users, `user_signed_up` is emitted.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1781
