### ISSUE TITLE
Jinja2 support

### ISSUE THREAD

**Issue by Pithikos** [pennersr/django-allauth#1784]
Thanks for the work on this great tool.

I used it for the last months fine but recently I am forced to switch to Jinja2 and I can't figure out how to get `django-allauth` to work. The main problem is mainly the templatetags which don't work with Jinja2. Is there a way to get this working? There's not much info out there on this.

**Comment by pennersr** [comment]
There is an open feature request on this: #1252

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1784
