### ISSUE TITLE
Is possible to update translations from https://www.transifex.com/django-allauth/django-allauth/

### ISSUE THREAD

**Issue by pycarlos** [pennersr/django-allauth#1785]
Hi,
I need the ES language and I can see 100% translated in https://www.transifex.com/django-allauth/django-allauth/ but the .po files aren't updated.

**Comment by pennersr** [comment]
Can you please file a pull request?

**Comment by pycarlos** [comment]
I don't know how to download this file, I am registered but I cannot found the download button.

**Comment by pennersr** [comment]
I am sorry, I cannot help you here... I am not using/actively supporting transifex myself.

**Comment by pycarlos** [comment]
For download this file, I need be a project member in transifex, I was added a request but you need add me

The guide:
https://docs.transifex.com/projects/downloading-translations#section-downloading-a-zip-file-with-all-translation-files

The screenshot with my request:
![image](https://user-images.githubusercontent.com/4006316/28652243-4d689a94-724c-11e7-974e-a9051fbe6d60.png)

Thank you.

**Comment by pycarlos** [comment]
Hi @pennersr There is something that you can do it?

**Comment by pennersr** [comment]
Does it work for you now?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1785
