### ISSUE TITLE
About user_logged_out signal

### ISSUE THREAD

**Issue by aureplop** [pennersr/django-allauth#1787]
Hi everyone,

Using the default account adapter, allauth [sends](https://github.com/pennersr/django-allauth/blob/81af6a54be579a565b3eef1766642cbaca7ee5a3/allauth/account/adapter.py#L395) the ``allauth.account.signal.user_logged_out`` signal on logout. But this signal is sent after the call to the classical django' logout function. So it misses a few things, e.g. `request.session` has already been flushed when this signal is emitted.

Maybe the docs could:
- specify when the signal is sent, i.e. at the (very) end of the logout flow,
- say [`django.contrib.auth.signals.user_logged_out`](https://docs.djangoproject.com/en/dev/ref/contrib/auth/#django.contrib.auth.signals.user_logged_out) is still sent on logout. This signal is sent earlier in the logout flow, such as listeners can still accessed the content of `request.session` before it has been flushed.

Just to say, initially i was doubting this signal (allauth' one) is worthwhile, because it seems like a messier copy of the django' one. But in fact they provide multiple listening points in the logout flow, namingly pre/post logout. With django' signal, you can access the session before it has been flushed, but it's useless to set session value. With allauth' one, session will be empty, but you can set session values and they will be kept. So "why not".

**Comment by pennersr** [comment]
True, this is confusing... allauth should be compliant to the behavior of the Django signal.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1787
