### ISSUE TITLE
Harden the tip on protecting admin with allauth

### ISSUE THREAD

**Issue by ishitatsuyuki** [pennersr/django-allauth#1789]
See https://stackoverflow.com/a/45328687/2484972 for details. The docs were added in #1562.

**Comment by blueyed** [comment]
See https://github.com/pennersr/django-allauth/pull/2287 - needed an adjustment to the StackOverflow answer (see my comment there).

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1789
