### ISSUE TITLE
Validation error in persona_login

### ISSUE THREAD

**Issue by patjdor** [pennersr/django-allauth#179]
In [persona/views.py](https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/providers/persona/views.py), I believe line 21 should read:
extra_data = resp.json()

instead of:
extra_data = resp.json

Otherwise you get "ValidationError at /accounts/persona/login/"

It looks like it was missed in commit [93eca00adbcfd33deaf8cfd93b1871817b8cbddb](https://github.com/pennersr/django-allauth/commit/93eca00adbcfd33deaf8cfd93b1871817b8cbddb)

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/179
