### ISSUE TITLE
Login w/ Facebook creates a user based on firstname

### ISSUE THREAD

**Issue by sebst** [pennersr/django-allauth#1794]
When using all auth Facebook Provider for sign up it will create a django user with the Facebook account's first_name as username. Even for small apps, this will cause collision very soon. With Twitter signups it uses the twitter user name as django's username.
Is it possible to change that behaviour?

**Comment by pennersr** [comment]
Yes, see SocialAccountAdapter.populate_user()

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1794
