### ISSUE TITLE
LINE web login api is going to be deprecated

### ISSUE THREAD

**Issue by JmeHsieh** [pennersr/django-allauth#1795]
As mentioned in the doc:
https://developers.line.me/web-api/integrating-web-login
> Note: Web Login v1 will only be supported until January 2018 and it is recommended that you use Web Login v2.

We should start moving toward LINE v2 api.

**Comment by JooeunAhn** [comment]
I'll fix it this week. Thanks for reporting!

**Comment by pennersr** [comment]
Closing, line is on v2 these days.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1795
