### ISSUE TITLE
how to call login function from custom adapter

### ISSUE THREAD

**Issue by karthikrajender** [pennersr/django-allauth#1798]
I am using custom adapter to register a user by using django rest auth, in my custom adapter i am validating the user registered data i need to login the user automatically if he already exist and registering second time..

i have used authenticate and login function:

new_user = authenticate(username=username, password=password) login(self,new_user)

i am getting server error(500), and the exception is

AttributeError: 'AccountAdapter' object has no attribute 'session'

so if i put self.request - account adpater object has no attribute request, how can i login the user if he try to register for second time.

**Comment by pennersr** [comment]
Use `get_adapter(request).authenticate(...)`

**Comment by karthikrajender** [comment]
Hi Pennersr

Thanks for your reply in authenticate function what are the parameters which i need to pass

case 1:  check for user already exist and making that user to login when the user is already exist

**Comment by karthikrajender** [comment]
I am getting the following error

AttributeError: 'AccountAdapter' object has no attribute authenticate

**Comment by pennersr** [comment]
It's here: https://github.com/pennersr/django-allauth/blob/master/allauth/account/adapter.py#L480 ... you're likely not inheriting from the default adapter.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1798
