### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by jleclanche** [pennersr/django-allauth#1799]
There hasn't been commit activity lately and I think the current master is releasable. Thoughts @pennersr ?

**Comment by irconan** [comment]
Can't speak for current master HEAD but I am currently building using f1b5d4bd7216dad9670be22ae0c2ea29ba0fccfa since it resolves a bug we were facing.

Looking at the commit log I think getting a new release tagged would be great!

**Comment by pennersr** [comment]
0.33.0 is out now...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1799
