### ISSUE TITLE
HTTP method acquiring twitter request token

### ISSUE THREAD

**Issue by ghost** [pennersr/django-allauth#18]
When I try to login via twitter I get the following error:

OAuthError at /accounts/twitter/login/
Invalid response while obtaining request token from "api.twitter.com".

Request Method:     GET
Request URL:    http://mydomain/accounts/twitter/login/
Django Version:     1.3.1
Exception Type:     OAuthError
Exception Value: Invalid response while obtaining request token from "api.twitter.com".

According with twitter documentation you should use the POST HTTP method. Maybe this can fix this issue.

TIA,
P.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/18
