### ISSUE TITLE
How to custom send email handler

### ISSUE THREAD

**Issue by jarrekk** [pennersr/django-allauth#1800]
Hi, I have searched many documents about django-allauth, but can't find a way to custom email handler, I rewrite a email handler like [this](https://github.com/jarrekk/django-tmpl/blob/Generic_views/application/app_utils/async_email.py) but I can only use it to send an email normally and django logs support custom [email handler](https://github.com/jarrekk/django-tmpl/blob/Generic_views/application/settings/base.py#L215), is there any way to set up this?

Now my email backhend is [django-anymail](https://github.com/anymail/django-anymail) with MailGun.

Many thanks.

**Comment by pennersr** [comment]
All mail sent by allauth is channeled through this adapter method:

    def send_mail(self, template_prefix, email, context):


You are free to completely override this method.

**Comment by jarrekk** [comment]
@pennersr Thanks, I found it.

**Comment by jarrekk** [comment]
But when I overwrite this method, django-allauth still uses the original method  
```
def send_mail(self, template_prefix, email, context):
```
If we can config it in **settings.py** the specify the send_mail class, it will be better.

**Comment by pennersr** [comment]
In the settings you can already configure a new adapter, allowing you to override all methods, including the send_mail method.

**Comment by jarrekk** [comment]
Nice, Mant thanks!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1800
