### ISSUE TITLE
Unable to resend reset-password email

### ISSUE THREAD

**Issue by deepak1725** [pennersr/django-allauth#1801]
Set `ACCOUNT_EMAIL_CONFIRMATION_COOLDOWN = 0`
don't know where it matters or not.. but on signup with new account , user can send reset-password email only once..?? On next click , though _allauth_ returns success, but no email is sent furthermore..

**Comment by pennersr** [comment]
The cooldown is for email confirmation, not password reset. Password resets are always sent, at least from an allauth perspective. If it is not working for you it is likely not an issue in allauth, but a configuration problem. Check your email backend, spam, ...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1801
