### ISSUE TITLE
Assertion error with duplicate email in account_emailaddress table

### ISSUE THREAD

**Issue by rajsquid** [pennersr/django-allauth#1802]
Hi there

I am getting an error while signing up from frontend. 

```
File "C:\virtualenvs\ciasenv\lib\site-packages\allauth\account\utils.py", line 257, in setup_user_email
   assert not EmailAddress.objects.filter(user=user).exists()
AssertionError
```

This is because I have modified models.py with the following code --

```
class adminadduser(models.Model):
    user = models.OneToOneField(User, unique=True, related_name ='eaddress')
    email = models.EmailField()
    verified = models.BooleanField(verbose_name=_('verified'), default=True)
    primary = models.BooleanField(verbose_name=_('primary'), default=True)

    class Meta:
        db_table = 'account_emailaddress'

@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
    if created:
        adminadduser.objects.create(user=instance, email=instance.email)
```

settings.py--

```
ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
```

The purpose is when admin creates a user then there is no need to do email confirmation. The user can direct login to his account. It works fine when admin adds a user but when a user tries to register then the error pops up.

Is there any way out. Any hints or suggestion is highly appreciated.

**Comment by pennersr** [comment]
I am not fully grasping what you are doing here. You've created a new `adminuser` model that reuses the database tables of the EmailAddress model from allauth? Why do that? If you don't want email verification to kick in, I would say that you simply flip the `verified` switch in the existing allauth email record instead of manually trying to create these records yourself.

**Comment by rajsquid** [comment]
Thanks pennersr for your reply. I want the verification to be there for the users who are trying to register from the frontend. But if the admin adds a user then the account needs to be auto verified. Is this at all possible with the app.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1802
