### ISSUE TITLE
Signal social_account_added in all auth social account not working

### ISSUE THREAD

**Issue by karthikrajender** [pennersr/django-allauth#1804]
Hi All,

I am using custom social account adapter,  and added the signal function social_account|_added function and tested whether this signal is working or not by printing social account details but nothing works             
kindly tell me in which scenario this signal works and is there any signal i need to check custom table authentication after save_user function in adapter

Is there any signal while connecting a social account to user account

**Comment by pennersr** [comment]
See here -- the signal is definitely emitted:

```
def _add_social_account(request, sociallogin):
        ....
        # New account, let's connect
        action = "added"
        sociallogin.connect(request, request.user)
        signals.social_account_added.send(
            sender=SocialLogin, request=request, sociallogin=sociallogin
        )

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1804
