### ISSUE TITLE
What is the password set in user table when user is signup using google and facebook

### ISSUE THREAD

**Issue by karthikrajender** [pennersr/django-allauth#1805]
Hi All,

what is the password which get's stored in the password field while user signup using facebook and google social login, if a user want to login with email and password through a dedicated login page how can they do it.

**Comment by pennersr** [comment]
None, there is no password set.

**Comment by edwinbbu** [comment]
how to set password on signup with facebook/google

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1805
