### ISSUE TITLE
Site matching query does not exist

### ISSUE THREAD

**Issue by AlexCreamer** [pennersr/django-allauth#1806]
I recently decided to add django-allauth to my application and it requires that I include 'django.contrib.sites' inside my settings.INSTALLED.APPS. This is causing my program to break with error `Site matching query does not exist`. I tried creating a new site and then using that site_id in my settings and that didn't solve the problem.

**Comment by pennersr** [comment]
This is not a bug in allauth, it is a configuration problem. Check settings.SITE_ID ...

**Comment by AlexCreamer** [comment]
That was it, my site_id part wasn't capitalized. Thanks a bunch!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1806
