### ISSUE TITLE
Distinguish between a social signup or a regular signup

### ISSUE THREAD

**Issue by tomersimis-zz** [pennersr/django-allauth#181]
Is there any way to distinguish between these two types of signup?
I need to create and populate the user profile only if it's an social signup

from allauth.account.signals import user_signed_up

@receiver(user_signed_up)
def populate_profile(sender, **kwargs):
    if social signup:
            CREATE PROFILE

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/181
