### ISSUE TITLE
Strange field order in signup form

### ISSUE THREAD

**Issue by vsemionov** [pennersr/django-allauth#1810]
After upgrading from 0.32.0 to 0.33.0, the signup form shows the email field before the username field. However, the keyboard focus remains on the username field. Is this intentional?

**Comment by derek-adair** [comment]
Maybe worth adding an autofocus property to username and telling users to override this manually if they want... i'm leaning towards just saying this isn't allauth's problem.  I am indifferent to this one but at a minimum tag as help wanted / low priority.

**Comment by pennersr** [comment]
Closing -- dated.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1810
