### ISSUE TITLE
social account adapter override save_user

### ISSUE THREAD

**Issue by peterhn** [pennersr/django-allauth#1813]
I'm trying to override the save user method in account adapter, but the save_user method never seems to get hit.

adapter.py
```
class DefaultOverrideAccountAdapter(DefaultAccountAdapter):
    def save_user(self, request, user, form, commit=False):
        user = super(DefaultOverrideAccountAdapter, self).save_user(request, user, form, commit)
        user.gender = form.cleaned_data.get('gender')
        user.date_of_birth = form.cleaned_data.get('date_of_birth')
        if commit:
            user.save()
```

settings.py
`ACCOUNT_ADAPTER = 'adapter.DefaultOverrideAccountAdapter'`

**Comment by freepeace13** [comment]
I have the same issue. Is there any workarounds?

**Comment by freepeace13** [comment]
I know it's too late for this but hopefully will be useful for somebody. Here's my workaround:

`
from allauth.socialaccount.adapter import DefaultSocialAccountAdapter

class CustomSocialAccountAdapter(DefaultSocialAccountAdapter):
    def save_user(self, request, sociallogin, form):
        user = super(CustomSocialAccountAdapter, self).save_user(request, sociallogin, form)
        # Do what ever you want with the user
        return user
`

settings.py
SOCIALACCOUNT_ADAPTER = 'path.for.CustomSocialAccountAdapter'

**Comment by pennersr** [comment]
I don't think there is an issue in allauth here. For example, try putting a pdb into the save_user method and run the test suite. You'll clearly see it being hit.

**Comment by rammanoj** [comment]
I am not sure why overriding save_user is returning me a server error (500) in its callback URL.

**Comment by gabrielfrischer** [comment]
> I am not sure why overriding save_user is returning me a server error (500) in its callback URL. I am not sure why this is happening!!

Make sure your client id and client secret are being used!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1813
