### ISSUE TITLE
Refactor pass reset key URL

### ISSUE THREAD

**Issue by pokluda** [pennersr/django-allauth#1815]
Hey Raymond,

the recent changes to hide token from URL didn't update the pass reset key URL.

[django-allauth/allauth/account/urls.py](https://github.com/pennersr/django-allauth/blob/master/allauth/account/urls.py)
```
url(r"^password/reset/key/(?P<uidb36>[0-9A-Za-z]+)-(?P<key>.+)/$",
        views.password_reset_from_key,
        name="account_reset_password_from_key"),
```
It obviously still lets the new URL structure through (password/reset/key/X-set-password) but should be refactored imho.

Cheers,
Jacob

**Comment by pennersr** [comment]
That URL needs to handle both the encoded token and the 'set-password' key, so I am not sure what could be refactored here?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1815
