### ISSUE TITLE
password reset partial translation in spanish

### ISSUE THREAD

**Issue by clustersnake** [pennersr/django-allauth#1819]
I'm using allauth and works pretty well for a newbie like me, but I've found a very difficult issue with translations. As you can see in the reset email below, only one paragraph is translated and the confirmation email is completely in english. I'm really confused about it.
In a related topic, is there a visual way to edit the password_reset_key_message.txt from django-admin?

`Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Subject:
 =?utf-8?q?=5Btesting=2Ecom=5D_Correo_para_restablecer_contrase=C3=B1a?=
From: webmaster@localhost
To: telesnake45@hotmail.com
Date: Mon, 04 Sep 2017 21:37:29 -0000
Message-ID: <20170904213729.6940.95397@DESKTOP-I0R48N6>

Hello from testing.com!

You're receiving this e-mail because you or someone else has requested a password for your user account.
It can be safely ignored if you did not request a password reset. Click the link below to reset your password.

http://localhost:8000/api/accounts/password/reset/key/78-4p6-93a5be6729be8b327b13/

En caso de haber olvidado su nombre de usuario, es telesnake45@hotmail.com.

Thank you for using testing.com!
testing.com
-------------------------------------------------------------------------------`

**Comment by melvyn-sopacua** [comment]
I can confirm that partial translation of the password reset message applies to Dutch as well. Looking in the `.mo` the string "Hello from" or any distinct phrases from this email are not found in the file, so there must be something not correct in the po or the template. Perhaps having `site_domain` in the `blocktrans` tag but not used in translation breaks this?

**Comment by melvyn-sopacua** [comment]
Just added a comment to 1e526ed. I initially read it wrong, but only the translation string was updated and not the translation itself, which still contains a reference to site_domain.

I made this work by overriding the template, removing the `site_domain` reference from the `blocktrans` tag and running `makemessages` on the project template directory. Then copied the translated string from allauth 0.33, removed `site_domain` from that translated string and didn't override any other translations after which I ran `compilemessages`.

**Comment by melvyn-sopacua** [comment]
Similar issue at [this line](https://github.com/pennersr/django-allauth/blob/master/allauth/templates/account/email_confirm.html#L16). I've cut off the blocktrans before user_email and updated translation string to make it work. In this case, user_email is not passed in the with statement of the blocktrans tag.

**Comment by clustersnake** [comment]
the folowing code in django.po leaves an empty message with an empty translation, I'm just removing the empty quotes and compiling the messages again from allauth main directory, this way all works fine, but I think I have to do this every time I update the allauth package
`
#: socialaccount/adapter.py:26
#, python-format
msgid ""
"An account already exists with this e-mail address. Please sign in to that "
"account first, then connect your %s account."
msgstr ""
"Ya existe una cuenta asociada a esta dirección de correo electrónico. Por "
"favor, autentíquese usando esa cuenta, y luego vincule su cuenta de %s."
`

**Comment by pennersr** [comment]
To improve translations, please file a PR.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1819
