### ISSUE TITLE
compatibility with django APPEND_SLASH=False setting

### ISSUE THREAD

**Issue by flyingeek** [pennersr/django-allauth#182]
You just need to change all allauth urls by replacing the trailing /$ by /?$

So url(r"^email/$", views.email, name="account_email"), becomes:
url(r"^email/?$", views.email, name="account_email"),

APPEND_SLASH = False is useful for legacy sometimes

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/182
