### ISSUE TITLE
User being created with blank username

### ISSUE THREAD

**Issue by hgezim** [pennersr/django-allauth#1821]
I'm using DRF. Here's the relevant part of my `urls.py`:

```python
url(r'^rest-auth/facebook/$', FacebookLogin.as_view(), name='fb_login'),
```

FacebookLogin defined here:

```python
from allauth.socialaccount.providers.facebook.views import FacebookOAuth2Adapter
...
class FacebookLogin(SocialLoginView):
    adapter_class = FacebookOAuth2Adapter
```

Seems to me that `def sociallogin_from_response(self, request, response)` in `socialaccount/providers/base.py` just doesn't generate a username.

The `rest_auth` module does this properly because it calls `allauth/account/adapter.py`'s `save_user` which calls `populate_username`.

`FacebookOAuth2Adapter` does not even inherit from `DefaultAccountAdapter`.

What do you recommend?

**Comment by Bulva** [comment]
I have very similar problem but with an email. I got this error when I was trying to authenticate first time to Facebook:
```
NoReverseMatch at /rest-auth/facebook/

Reverse for 'socialaccount_signup' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: [] 
```

It is working fine on Facebook api version 2.7, but not with 2.10 version. When I set ACCOUNT_EMAIL_REQUIRED then it is working but email si blank.

**Comment by pennersr** [comment]
These two adapters have different purposes. As for the the bug report, given that you are using a mixture of allauth and rest auth, the issue is not clear to me. I would like to see a problem description demonstrating an issue when using allauth only.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1821
