### ISSUE TITLE
Upgrade Facebook GRAPH API

### ISSUE THREAD

**Issue by karthikrajender** [pennersr/django-allauth#1829]
Hi all,

I have saw the update from GRAPH API version from 2.4 to 2.5, whether this is compatible for the facebook APP with version of 2.10 or higher, and the token will get validated  or not ?

**Comment by karthikrajender** [comment]
could any one guide me how to upgrade the GRAPH API, i have facebook app version 2.4 now, but i am getting message from facebook about upgrading the GRAPH api, if i create a new app in facebook it defaults to version 2.10 , and that access token is not validated properly with facebook provider

**Comment by jvilaikeo** [comment]
I'm having this issue too

**Comment by pennersr** [comment]
I am sorry, but I don't think this is an issue allauth can solve. It is not using the token directly -- it is only storing it. Dealing with FB graph API version issues is beyond scope...

**Comment by jvilaikeo** [comment]
Isn't that part of the allauth module? The validation issue is due to a change in api, which will invalidate the fb module once FB has deprecates the older API version. This is in the providers portion and not the api itself.

**Comment by timdrijvers** [comment]
Facebook will be closing the 2.5 API as of 12 April, 2018.

**Comment by pennersr** [comment]
@timdrijvers  You can easily choose the Facebook version using something like `SOCIALACCOUNT_PROVIDERS = {'facebook':  { 'VERSION': 'v2.6'}}` in your `settings.py`.

allauth currently defaults to 2.5, so that should obviously change. Though, I am not sure what people are referring to above (compatibility of tokens et al).

**Comment by timdrijvers** [comment]
User access tokens are bound to one specific Facebook app and can not be transferred to an other app. If you create a new app and use this, all the previous user access token will not work. Facebook allows to transition to new version of their API with the same app. As far as i know there are no breaking changes in version 2.0 and up that break this behavior (https://developers.facebook.com/docs/graph-api/changelog/breaking-changes)

**Comment by pennersr** [comment]
As per 77c77e5, the API has been upgraded to v2.12.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1829
