### ISSUE TITLE
Bitbucket doesn't provide email

### ISSUE THREAD

**Issue by gdavoianb** [pennersr/django-allauth#1831]
Hi, folks.
I'm using your library for allowing users to login via their GitHub, Bitbucket and GitLab accounts. So I created the same OAuth apps for all three providers, also created the corresponding social apps. Everything works fine, but still there is a problem: the Bitbucket app doesn't fetch any emails (tried different combinations of possible app permissions), as a result I have some group of signed up users without emails. I'm not sure, but mb some changes were made in the Bitbucket API, which aren't handled by the library yet. E.g. http://api.bitbucket.org/2.0/user/ doesn't return any email, though there is a specified endpoint for that: http://api.bitbucket.org/2.0/user/emails. 
Thank you.

**Comment by gdavoianb** [comment]
Managed to solve the initial problem by using the `bitbucket_oauth2` provided instead of the `bitbucket` provided. But another problem occurred: instead of the actual Bitbucket username each user gets signed up with some strange username.

**Comment by derek-adair** [comment]
Bitbucket is probably a pretty big one to support, worth your attention if this hasn't been fixed on their end or your end.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1831
