### ISSUE TITLE
No timeouts in requests.get is causing server to hang when social provider taking too long to respond

### ISSUE THREAD

**Issue by vinodpandey** [pennersr/django-allauth#1832]
We have not specified timeouts in requests.get which causes the server to hang in the scenario where social provider is taking too long to respond. The other scenario is when the server looses external connectivity, as there is no timeout specified, all socialprovider get requests keep piling up causing the server to hang.

E.g. django-allauth/allauth/socialaccount/providers/google/views.py
Line no. 18
`
def complete_login(self, request, app, token, **kwargs):
        resp = requests.get(self.profile_url,
                            params={'access_token': token.token,
                                    'alt': 'json'})
        resp.raise_for_status()
        extra_data = resp.json()
`

From documentation:
http://docs.python-requests.org/en/master/user/quickstart/

> You can tell Requests to stop waiting for a response after a given number of seconds with the timeout parameter. Nearly all production code should use this parameter in nearly all requests. Failure to do so can cause your program to hang indefinitely:

**Comment by pennersr** [comment]
Valid point. We need:

- [ ] Introduce a new setting: SOCIALACCOUNT_REQUESTS_TIMEOUT
- [ ] Use this setting in *all* providers.

**Comment by derek-adair** [comment]
Tag as PR welcome.  Again the PR welcome can easily signify to you and your users where a user can jump in and what you are certainly not any planned efforts towards this end.

**Comment by pennersr** [comment]
Closed via 0bb5032b

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1832
