### ISSUE TITLE
KeyError in password reset

### ISSUE THREAD

**Issue by vasofi** [pennersr/django-allauth#1833]
A KeyError is thrown in the `PasswordResetFromKeyView` if the `key` parameter doesn't exist in the session.

This might happen, for example, if a user clicks the "reset password" link and gets re-directed to the "INTERNAL_RESET_SESSION_KEY" mechanism and doesn't complete the process.
If the user copies the link from the browser address bar (it doesn't contain the key anymore) and opens it in another device (in which case this is another session and the key doesn't exist in it).

Currently the form validation throws an error instead of handling this and raising a ValidationError that in turn will cause the view to set the 'token failed' context.

Making sure the `key` and `uidb36` keys exist in the session (or the form cleaned_data) and then raising a ValidationError fixes the problem.

**Comment by dkarchmer** [comment]
And somebody out there seems to be trying to attach sites with such strings. e.g.
```
https://example.com/account/password/reset/key/33-set-password/
```

**Comment by JetUni** [comment]
This is a problem for us as well. Any update on when this will be fixed?

**Comment by vinicius-ronconi** [comment]
Hi guys! I'm facing the same problem. Is there any estimated date for next release?

**Comment by two9seven** [comment]
So is this a security risk or vulnerability?

**Comment by pennersr** [comment]
It's not. The issue has been fixed in a821c53  ... closing.

**Comment by vinicius-ronconi** [comment]
@pennersr ,
Is it possible to create a new release? Besides it is fixed, when we add django-allauth to a requirements.txt, we get a version without the fix.

Thanks!

**Comment by pennersr** [comment]
Coming soonⓇ

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1833
