### ISSUE TITLE
how to configure wechat service number's 'token' when modify server config 

### ISSUE THREAD

**Issue by opscolin** [pennersr/django-allauth#1837]
I checked allauth package and found provider weixin's callback address is 'accouts/weixin/login/callback'  

but when I modify server config  in wechat service platform, except 'URL' (I guess here is weixin callback address http://xxxx/accouts/weixin/login/callback) , but there is a 'token' input need to fill in , so how do I config it ,I can not find any configuration about it in allauth package

**Comment by pennersr** [comment]
Sorry, unable to help out here, but this is not really a bug, mostly lacking documentation. Please file a pull request to up the documentation once you get things going.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1837
