### ISSUE TITLE
The request's session was deleted before the request completed. 

### ISSUE THREAD

**Issue by qari** [pennersr/django-allauth#1838]
When I wanna reset password I get URL and after click not more 10 second I have:

The request's session was deleted before the request completed. The user may have logged out in a concurrent request, for example.

**Comment by pennersr** [comment]
I really think this is a local issue, not something wrong in allauth.

**Comment by MSchietzsch** [comment]
got the same, was a problem with the cache, maybe check SESSION_ENGINE settings. Was no problem at all on allauth

**Comment by kazisabuz** [comment]
"The request's session was deleted before the request completed. The user may have logged out in a concurrent request" I am facing this error when I have to login into my Django app. Please give a solution.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1838
