### ISSUE TITLE
Email verification is OFF, but still sending email for verification

### ISSUE THREAD

**Issue by karambir** [pennersr/django-allauth#184]
I have enabled sign in with Google and using email as the base login users. Also I have turned off any email verification after signup. But when I'm trying to login with Google in my app, it is sending an email and not allowing user to login. My settings are: 

```
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_PASSWORD_MIN_LENGTH = 6
SOCIALACCOUNT_QUERY_EMAIL = ACCOUNT_EMAIL_REQUIRED
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_PROVIDERS = \
    { 'google':
                    { 'SCOPE': ['https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email'] } }
```

_All other settings are commented._

Why is email verification still kicking in?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/184
