### ISSUE TITLE
Facebook allauth https javascript

### ISSUE THREAD

**Issue by mattmillen888** [pennersr/django-allauth#1844]
We are having issues with facebook all auth. basically the self generated urls in js JSON on page are being generated as http not https this causes an issue on my page as the browser is saying

"logoutUrl":
"cancelUrl":
"errorUrl":
"loginUrl":
"loginByTokenUrl":

if i go to any of the urls direct they will redirect to https however facebook for some reason is giving login errors as it says we are posting and unsecure form.

This is the data outputted from {% providers_media_js %}

I have changed facebook id and urls as I didn't want to post.

<script id="allauth-facebook-settings" type="application/json">
{
	"initParams": {
		"cookie": true,
		"version": "v2.4",
		"appId": "11111111111111"
	},
	"csrfToken": "PqUXDw8FHMEwWWO7fFkPi76InLcEhD33UK203Vn0TBtOfHcaQb06m0h388RHg6SW",
	"version": "v2.4",
	"logoutUrl": "http://www.domain.com/accounts/logout/",
	"loginOptions": {
		"scope": "email,public_profile,user_friends",
		"auth_nonce": "yhtJ61QlsujgztLKVchDCRtVpj95eEwx",
		"auth_type": "reauthenticate"
	},
	"locale": "en_GB",
	"cancelUrl": "http://www.domain.com/accounts/social/login/cancelled/",
	"errorUrl": "http://www.domain.com/accounts/social/login/error/",
	"loginUrl": "http://www.domain.com/accounts/facebook/login/",
	"loginByTokenUrl": "http://www.domain.com/accounts/facebook/login/token/",
	"appId": "11111111111111"
}
</script><script type="text/javascript" src="https://s3bucket.s3.amazonaws.com:443/assets/facebook/js/fbconnect.js">
</script>

how can i get all these urls to output https? as they are in the json

![mixedcontent](https://user-images.githubusercontent.com/25214970/31321034-7c022ee8-acca-11e7-815c-455b34922631.png)

This is what happens on safari:

![screen shot 2017-10-09 at 08 20 00](https://user-images.githubusercontent.com/25214970/31321048-b0795084-acca-11e7-9192-d5aee0366659.png)

Yet if i go to any of the urls directly then the redirect to https. I need them to be https to start with

Any help would be great appreciated

**Comment by celestinosalim** [comment]
I just add this to my settings.py. 
ACCOUNT_DEFAULT_HTTP_PROTOCOL = "https"
DEFAULT_HTTP_PROTOCOL = "https"

and it work properly.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1844
