### ISSUE TITLE
How to properly extend user model and registration?

### ISSUE THREAD

**Issue by dperconti** [pennersr/django-allauth#1846]
Given the following user object, how can I go about properly adding optional and required parameters to the API?

```
class Profile(AbstractUser):
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=40, unique=True, blank=True)

    first_name = models.CharField(max_length=40, blank=True)
    last_name = models.CharField(max_length=40, blank=True)
```

How can I enable allauth to receive those as parameters via an API call to then clean/store them? In other words, what I want to be able to do, is call the /rest-auth/registration/ endpoint with a body like such;

```
{
  "username": "foo",
  "email": "bar@mail.com",
  "password1": "fooBar!@",
  "password2": "fooBar!@",
  "first_name": "first",
  "last_name": "last"
} 
```

and have first_name and last_name stored as a Profile object. Again, I want to be able to do this via the API and not via a form.

Environment:
```
Django==1.11.3
django-allauth==0.33.0
django-environ==0.4.4
django-rest-auth==0.9.1
django-storages==1.6.5
django-taggit==0.22.1
djangorestframework==3.6.4
...

$ python --version
Python 2.7.11
```

**Comment by pennersr** [comment]
https://django-allauth.readthedocs.io/en/latest/faq.html#why-did-you-just-close-my-issue

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1846
