### ISSUE TITLE
Username uniqueness broken

### ISSUE THREAD

**Issue by gjcourt** [pennersr/django-allauth#1849]
I recently upgraded from 0.19 to 0.33 and noticed a large increase in exceptions around user creation due to social login. It appears that [this](https://github.com/pennersr/django-allauth/blob/92810c9134389a26bf32ce2a8dd5fb68e1182bbe/allauth/utils.py#L108) is the offending code. The old behavior was the test `__iexact` however this code seems to be comparing username strings to a list of case sensitive user names.

**Comment by Jafnee** [comment]
Tracing the code through it looks like the `__iexact` is still being used [here](https://github.com/pennersr/django-allauth/blob/master/allauth/account/utils.py#L367)

**Comment by pennersr** [comment]
Closed in 74abfbe35fb2fb498d480bc6d1fc4e4330b086bf

**Comment by gjcourt** [comment]
Thanks!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1849
