### ISSUE TITLE
Pre-create account associations for people?

### ISSUE THREAD

**Issue by bsquidwrd** [pennersr/django-allauth#1857]
I have an environment where I only allow Social Authentication (other than for admins) and I'd like to pre-create users and assign them permissions so when I go do a training, they can login and follow along right away.

Is it possible to create a user account for them and assign a social account which I don't know the ID for and associate it for them or should I look for an invite system to hook into allauth?

**Comment by pennersr** [comment]
There is nothing stopping you from pre-creating users with predetermined passwords and so on, but this is all beyond scope of allauth.

**Comment by bsquidwrd** [comment]
Thank you for the response. I understand it is out of the scope of allauth.

I guess my real question is how could I go about manually creating social account records for a specific user to automate the social linking for them?

**Comment by li5tun** [comment]
@bsquidwrd Do you find an answer for your question, I am looking into it as well.

**Comment by bsquidwrd** [comment]
No I did not, sadly.

The closest thing I could think of doing was to create the accounts and have users login then create their own association.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1857
