### ISSUE TITLE
Google sign out remembers users

### ISSUE THREAD

**Issue by hantaowang** [pennersr/django-allauth#1858]
I am not sure if this is a google problem or an allauth problem but whenever I try to sign out of google and login with a new account, the login skips the authentication phase and directly signs me into the account that I just logged out of. Thus I am unable to switch between accounts. Does anyone know if there is anything I can do to prevent this? 

I am using Django-allauth 0.21.0 because the backend uses Django 6.0. Thanks in advance.

**Comment by hiporox** [comment]
This is an issue with your logout flow on the front end. You have to sign the user out of Google (https://developers.google.com/identity/sign-in/web/sign-in#sign_out_a_user). All Auth is doing what it should

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1858
