### ISSUE TITLE
'AppSettings' object has no attribute '__name__'

### ISSUE THREAD

**Issue by alexarsh** [pennersr/django-allauth#186]
Hi,

I'm using django-allauth with app engine and when I add login_required decorator to my view I get the following error: 'AppSettings' object has no attribute '**name**'
The full traceback is here: http://slexy.org/view/s20CZWVMCP

My settings:

TEMPLATE_CONTEXT_PROCESSORS = (...,
    "allauth.account.context_processors.account",
    "allauth.socialaccount.context_processors.socialaccount",
)

AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
)

INSTALLED_APPS = (
    ...,
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.facebook',
)

When I go to 'account' dir, I can do the import manually without problems.
Any ideas?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/186
