### ISSUE TITLE
How to set up password in user model when signing up with facebook/ google

### ISSUE THREAD

**Issue by edwinbbu** [pennersr/django-allauth#1863]
def save_user(self, request, sociallogin, form=None):
        """
        Saves a newly signed up social login. In case of auto-signup,
        the signup form is not available.
        """
        u = sociallogin.user
        u.set_unusable_password()
        if form:
            get_account_adapter().save_user(request, u, form)
        else:
            get_account_adapter().populate_username(request, u)
        sociallogin.save(request)
       return u

By overriding this method

**Comment by pennersr** [comment]
The whole point of signing up using the social providers is to not have to setup a password. So I am not sure what you are trying to accomplish...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1863
