### ISSUE TITLE
Field._get_val_from_obj is deprecated and removed in Django 2.0

### ISSUE THREAD

**Issue by linaskilius** [pennersr/django-allauth#1865]
Field._get_val_from_obj method has been deprecated and is removed from Django 2.0.  This breaks allauth for Django 2.0 when accessing an instance of SocialAccount in the admin backend.

Reference for deprecation of Field._get_val_from_obj() : [https://code.djangoproject.com/ticket/24716](https://code.djangoproject.com/ticket/24716)

This method is called in a couple places in the following file:
[https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/fields.py](https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/fields.py)

Code snippet for the affected section.
>     def value_to_string(self, obj):
>         """Return value from object converted to string properly"""
>         return smart_text(self.get_prep_value(self._get_val_from_obj(obj)))
> 
>     def value_from_object(self, obj):
>         """Return value dumped to string."""
>         return self.get_prep_value(self._get_val_from_obj(obj))

Django recommends using the Field.value_from_object() instead.

**Comment by timgraham** [comment]
https://github.com/pennersr/django-allauth/pull/1878 address this.

**Comment by jamesabc** [comment]
Is it possible to release this yet?

**Comment by JGSweets** [comment]
can be fixed with `models.Field.value_from_object(self, obj)`
though not ideal

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1865
