### ISSUE TITLE
MultipleObjectsReturned on login when using case sensitive usernames

### ISSUE THREAD

**Issue by robwa** [pennersr/django-allauth#1868]
We use allauth with unchanged default setting `ACCOUNT_PRESERVE_USERNAME_CASING = True`. This may lead to two different usernames *marc* and *Marc* (which is horrible, of course, see #1122). When logging in, we now get `MultipleObjectsReturned` because of case insensitive username filtering in [`AuthenticationBackend`](https://github.com/pennersr/django-allauth/blob/8b95481e8c03441b06256cd7497519acdd86003a/allauth/account/auth_backends.py#L35).

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1868
