### ISSUE TITLE
Documentation for Stripe provider could be clearer about source of the secret key

### ISSUE THREAD

**Issue by pjmcdermott** [pennersr/django-allauth#1870]
I've just spent a while trying to find the source of the secret key for use with OAuth2 on Stripe.

The client IDs are found on the [settings page](https://dashboard.stripe.com/account/applications/settings) (login required) of the Stripe dashboard. But unlike most other OAuth2 providers, the page does not mention any secret keys.

It took me a while to realise that the secret keys for OAuth2 are the very same secret key that is provided by Stripe for other uses of the Stripe API. These can be found on the [API page](https://dashboard.stripe.com/account/apikeys) of the Stripe dashboard.

It would be better if the [allauth Stripe documentation](https://django-allauth.readthedocs.io/en/latest/providers.html#stripe) made this clearer.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1870
