### ISSUE TITLE
StripeAccount does not implement to_str method

### ISSUE THREAD

**Issue by pjmcdermott** [pennersr/django-allauth#1871]
Implementation of `StripeAccount` in `allauth/socialaccount/providers/stripe/provider.py` uses parent class `ProvderAccount` default stringification, which just returns the provider brand name. This means that in the list of connected accounts in `templates/socialaccount/connections.html` shows "Stripe Stripe", whereas e.g. Google says "Google <user's name>".

Looking at the `extra data` in my test connection I can see `business_name` and `display_name` as candidate fields. But this is because I have a "business" Stripe account--there may be a "consumer" Stripe account that has different fields.

I would suggest implementing a StripeAccount.to_str() which uses the `business_name`, and maybe another field could be used as an alternative if it turns out there is a "consumer" Stripe account type also.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1871
