### ISSUE TITLE
Deprecation of Windows Live SDK to Microsoft Graph

### ISSUE THREAD

**Issue by humrochagf** [pennersr/django-allauth#1884]
As i found out at this link:
https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/migrating-from-live-sdk

Microsoft will drop auth support at Windows Live SDK in favor of Microsoft Graph Api.
I am already using Microsoft Graph at my local branch of allauth and i want to prepare a PR to add this support to the main repo. What do you think its the best approach on that?

1 - Create a `settings` variable that toggles between endpoints.
2 - Create a separate Microsoft Graph provider.

**Comment by jakob-stoeck** [comment]
I’m for 2, a separate provider. The Graph API is much more than the Live SDK.

**Comment by pennersr** [comment]
I would opt for 2 as well... looking forward to see a pull request. Until then, closing this issue.

**Comment by pennersr** [comment]
Merged, thanks.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1884
