### ISSUE TITLE
Can't override "password_reset_key_message.txt"

### ISSUE THREAD

**Issue by MadReal** [pennersr/django-allauth#1885]
Hello, I'm having issues override the default email for the "forgot password". I can override the 2 email for "email confirmation" without any issue but not with this one.

Not matter the extension, the one sent is always the default one that comes with the package.

Thanks

**Comment by pennersr** [comment]
I am sorry, I am quite sure this is not a bug in allauth, but rather an issue in your deployment. So I will have to close this issue.

**Comment by Koomook** [comment]
I got same issue. any improvement here?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1885
