### ISSUE TITLE
Using ModelForm with AjaxCapableProcessFormViewMixin

### ISSUE THREAD

**Issue by ntbrown** [pennersr/django-allauth#1886]
Attempting to use a ModelForm form with AjaxCapableProcessFormViewMixin / FormView. 

Everything works fine (in the sense errors aren't hit in the ajax, but the files don't save) when the ModelForm instance isn't passed in from get_form_kwargs.

Whenever the instance is passed in the ajax_response in allauth.account.adapter runs into problems when iterating the fields since it says the ImageField isn't JSON seriazable.

Will there be default support for this so the mixin can be simply be added in w/ class based views?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1886
