### ISSUE TITLE
EmailAddress does not exist error

### ISSUE THREAD

**Issue by psychok7** [pennersr/django-allauth#1890]
So i am using `django-allauth==0.34.0` with `django==1.11.7` and every time a new user signs up with a facebook or google account, i get a `EmailAddress does not exist: xx@example.com` error on the url:  `/accounts/facebook/login/callback/` or `/accounts/google/login/callback/`.  
I get this error, but the user stays registered and works fine.

I have applied all migrations as well.

Some traceback from my sentry error:

```sql
SELECT "socialaccount_socialaccount"."id", "socialaccount_socialaccount"."user_id", "socialaccount_socialaccount"."provider", "socialaccount_socialaccount"."uid", "socialaccount_socialaccount"."last_login", "socialaccount_socialaccount"."date_joined", "socialaccount_socialaccount"."extra_data" FROM "socialaccount_socialaccount" WHERE ("socialaccount_socialaccount"."provider" = 'google' AND "socialaccount_socialaccount"."uid" = '100000')
```
and 
```sql
SELECT "account_emailaddress"."id", "account_emailaddress"."user_id", "account_emailaddress"."email", "account_emailaddress"."verified", "account_emailaddress"."primary" FROM "account_emailaddress" WHERE UPPER("account_emailaddress"."email"::text) = UPPER('xx@example.com')
```
Any ideas how i can fix this?

**Comment by psychok7** [comment]
The issue was in my own override of `pre_social_login`.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1890
