### ISSUE TITLE
redirect to different domain using {% provider_login_url "facebook" method="oauth2" next='newdomain' %}

### ISSUE THREAD

**Issue by ntbrown** [pennersr/django-allauth#1894]
Whenever redirecting by passing next to a provider oauth2 url such as:

```
{% load socialaccount %}

<a href="{% provider_login_url 'facebook' method='oauth2' next='/my-bogus-url/' %}">Click Me</a>
```

The url can be replaced dynamically through js if you want to attach allauth handling to links which require social login, but this only works with the prepended slash. 

What about redirecting to a different domain which is controlled by the same code base. Allauth refuses to pick up the 'next' in this case.

i.e. - This will break next redirection:

`{% provider_login_url 'facebook' method='oauth2' next='https://www.mydomain.com/' %}`

Overriding the adapter etcetera doesn't even pick up `next` in `request.GET` in this case in the pre social login.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1894
