### ISSUE TITLE
Allow toggling automatic ajax support in views?

### ISSUE THREAD

**Issue by tony** [pennersr/django-allauth#1895]
This breaks PJAX (https://github.com/nigma/django-easy-pjax)

Is there a way to not have JSON return? I can't help is ``.is_ajax`` is triggered. 

Can there be a setting to disable it?

https://stackoverflow.com/questions/6432320/how-to-make-an-ajax-request-look-like-a-regular-normal-request

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1895
