### ISSUE TITLE
Reverse match seems bugged in latest version

### ISSUE THREAD

**Issue by houmie** [pennersr/django-allauth#190]
The reverse match is bugged 

I experience the problem with google:
http://stackoverflow.com/questions/14842275/django-allauth-cant-reverse-match-url

And another guy with facebook:
http://stackoverflow.com/questions/14797258/reverse-for-facebook-login-in-django-allauth

Can anyone confirm this please?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/190
