### ISSUE TITLE
Do not login after signup and customize verification email

### ISSUE THREAD

**Issue by atabekm** [pennersr/django-allauth#1900]
Hi,

I was wondering whether it is possible to not to login right after the signup, when `ACCOUNT_EMAIL_VERIFICATION` is set to `none`?

Another questions is, how difficult it would be to customize the verification email with some dynamic content. I know that we can redefine the template file, and when the content is static it is totally fine. However, if we need to do some custom actions before sending the verification, is there any simple ways?

Thanks.

**Comment by pennersr** [comment]
Currently that's not possible, sounds like a non standard use case.

You can always use template tags to have dynamic content, and/or override the send mail method of the adapter to poke in custom template context.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1900
