### ISSUE TITLE
Fix supported Django versions

### ISSUE THREAD

**Issue by washeck** [pennersr/django-allauth#1902]
There is a bit of confusion about required Django version. 0.33.0 release notes say Django 1.9 support was dropped but Overview section of the latest doc claims support for Django 1.8+.

@pennersr Now, when Django 2.0 was released, does it make sense to you to release new django-allauth version with timgraham's commits making only Django 1.11 and 2.0 supported?

**Comment by JoshData** [comment]
Maybe add this to the 0.35 changelog?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1902
