### ISSUE TITLE
Deprecated warning for field.rel

### ISSUE THREAD

**Issue by tangorboyz** [pennersr/django-allauth#1904]
`allauth/account/utils.py:425: RemovedInDjango20Warning: Usage of field.rel has been deprecated. Use field.remote_field instead.`

**Comment by pennersr** [comment]
519f1f2026691a98e76f5fc3d998d235e53cfe57

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1904
