### ISSUE TITLE
Emails not being translated

### ISSUE THREAD

**Issue by mbaragiola** [pennersr/django-allauth#1905]
Hello, I have translated my project to Spanish I have ran `python manage.py makemessages -l es` and `python manage.py compilemessages -l es` both.

My project strings are properly translated and shown when user has language set to `es`, but emails from `django-allauth` are sent in English. What am I missing?

Thanks in advance.

**Comment by pennersr** [comment]
https://django-allauth.readthedocs.io/en/latest/faq.html#why-did-you-just-close-my-issue

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1905
