### ISSUE TITLE
Django 2.0 support?

### ISSUE THREAD

**Issue by koddr** [pennersr/django-allauth#1906]
Hello.

Is `django-allauth` official supports new Django 2.0 at last release `0.34.0` (29 Oct)?
I want to know that, before trying on my huge project...

**Comment by hangya** [comment]
Fixes addressing Django 2.0 compatibility were merged in  #1878 but there were no new release since then.

**Comment by pennersr** [comment]
https://django-allauth.readthedocs.io/en/latest/faq.html#why-did-you-just-close-my-issue

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1906
