### ISSUE TITLE
EmailMultiAlternatives with headers

### ISSUE THREAD

**Issue by za** [pennersr/django-allauth#1908]
Hi there, 

Do you support sending email with headers? I'd like to send email but adding `extra_headers` such as: 
* Reply-To
* X-Redirect-Original-Recipient
* Categories
* ...etc

Because I don't see `headers` argument being passed here in [adapter.py](https://github.com/pennersr/django-allauth/blob/c4864dc217ef4a106e58d5ddabe88fba1dae1a4c/allauth/account/adapter.py#L120)

**Comment by pennersr** [comment]
You can easily set this up by tweaking the adapter:

```
    def send_mail(self, template_prefix, email, context):
        msg = self.render_mail(template_prefix, email, context)
        msg.extra_headers = { ... }
        msg.send()
```

Though, it would be goot if `render_mail` offered an optional headers parameter directly...

**Comment by pennersr** [comment]
> Though, it would be good if render_mail offered an optional headers parameter directly...

Done via ced1ddc7

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1908
