### ISSUE TITLE
[Debian] Releases: please, provide the same tarballs in pypi.python.org and github

### ISSUE THREAD

**Issue by P-EB** [pennersr/django-allauth#1909]
Hi !

For debian packaging of this software, we rely on pypi.python.org, but recently I tried to diff the tarballs between github and pypi. It appears they are quite different.

As you can't tell which website will be used by any user, it'd be sane to have the same release process when you build a tarball for Github and for pypi.python.org.

Cheers. :)

**Comment by pennersr** [comment]
There are no tarballs being releasted for GitHub, except for perhaps what GitHub does automatically -- tarring all files of the repo. And then indeed, differences are to be expected, as e.g. the repo does not include derived files such as .mo, whereas the pypi distribution does.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1909
