### ISSUE TITLE
Linking multiple social accounts to primary site account

### ISSUE THREAD

**Issue by gitdeepak** [pennersr/django-allauth#191]
I am wondering if allauth supports this scenarios: 
- if a user logs in using a social account - does this app have the ability to ask the user if he already has a site specific account -  if (yes) - link the social account to site specific account  -- if (no) then create a brand new account using social account. 

Thus the user can have multiple social account linked to a single primary site specific account and it eliminates the user having multiple accounts in the site. Thus multiple emails from the several social accounts will point to a single site specific account and the user has the ability to login from any of his accounts BUT logins into the primary account.

Thanks
Deepak

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/191
