### ISSUE TITLE
Duplicate Key Value Error When User Creates Account Twice

### ISSUE THREAD

**Issue by jplehmann** [pennersr/django-allauth#1911]
I've been running AllAuth for more than a year now in a production environment (Django 1.8), and this error occurs for about 1.5% of the signups that I get.  I was able to upgrade to a recent version (0.32) to make sure this issue wasn't fixed before reporting it. `IntegrityError: duplicate key value violates unique constraint...DETAIL:  Key (provider, uid)=(facebook, 1234...) already exists.` 

Until this week I was unable to reproduce the error but I came about a sequence that seems to be what happens:
* Click Sign up
* Click Facebook logo to connect account
* Fill in username/confirm email
* Account is successfully created and presumably shows verification email sent page. (And verification email is successfully sent).
* *User enters a second username and email combination and clicks submit* (presumably after backing up or perhaps after browser never going to the verification page)
* In my Database, I can see the second account sometimes created in the same minute as the first one, so I know these come in quick succession.

I do not exactly know why the users are choosing to enter a second username/password combination, but one theory is they get a second though about the email they put in and decide they need it sent to another email address so they go back and change it.  Or, for some reason their browser never takes them to the verification page. I have emailed several users to try to get more info on what is happening to them. 

Other settings: 
* `ACCOUNT_EMAIL_REQUIRED=True`
* `SOCIALACCOUNT_AUTO_SIGNUP=False`
* This last week I converted my usernames to the preferred `ACCOUNT_PRESERVE_USERNAME_CASING=False` so that is in no way related.
* This error is the same as #411 but I'm only running a single PG database, so cause seems unrelated.

Questions:
* This "flow" seems to be totally allowed in the system for years, leading to the error.  Why am I the only one who has ever reported this problem?
* I am trying to find out the underlying cause why users do this.
* What behavior should `allauth` exhibit in this situation?  If nothing else, I think it should catch the integrity error, and report to the user that their Social account has already been assigned to another user, and to contact the admin if they need it reassigned (this is obviously far from ideal).

Full stack:
```
Internal Server Error: /accounts/social/signup/
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/newrelic-2.60.0.46/newrelic/hooks/framework_django.py", line 499, in wrapper
    return wrapped(*args, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/allauth/socialaccount/views.py", line 37, in dispatch
    return super(SignupView, self).dispatch(request, *args, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/allauth/account/views.py", line 62, in dispatch
    **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/allauth/account/views.py", line 145, in dispatch
    **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/newrelic-2.60.0.46/newrelic/hooks/framework_django.py", line 872, in wrapper
    return wrapped(*args, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/views/generic/edit.py", line 215, in post
    return self.form_valid(form)
  File "/app/.heroku/python/lib/python2.7/site-packages/allauth/socialaccount/views.py", line 49, in form_valid
    form.save(self.request)
  File "/app/.heroku/python/lib/python2.7/site-packages/allauth/socialaccount/forms.py", line 35, in save
    user = adapter.save_user(request, self.sociallogin, form=self)
  File "/app/.heroku/python/lib/python2.7/site-packages/allauth/socialaccount/adapter.py", line 68, in save_user
    sociallogin.save(request)
  File "/app/.heroku/python/lib/python2.7/site-packages/allauth/socialaccount/models.py", line 224, in save
    self.account.save()
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/base.py", line 710, in save
    force_update=force_update, update_fields=update_fields)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/base.py", line 738, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/base.py", line 822, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/base.py", line 861, in _do_insert
    using=using, raw=raw)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/app/.heroku/python/lib/python2.7/site-packages/newrelic-2.60.0.46/newrelic/hooks/database_dbapi2.py", line 22, in execute
    *args, **kwargs)
IntegrityError: duplicate key value violates unique constraint "socialaccount_socialaccount_provider_1234_uniq"
DETAIL:  Key (provider, uid)=(facebook, 1234...) already exists.
```

**Comment by jplehmann** [comment]
@pennersr Any thoughts?  

Thanks!

**Comment by jplehmann** [comment]
@pennersr thank you for responding.

Yes this is similar, however that issue is the standard "double tap" which is simply addressed in JS.  In this issue, double-tapping is actually handled correctly because the response will be error messages about the username and/or email already existing.

The 500 integrity error happens when they *change* the values to a new username/email and submit.  The problem is the same social account is used again.  It would be much friendly for this to produce a response similar to the other situation, by giving a friendly error message that says "This social account has already been used for user" as opposed to a 500.

I think the difference is illustrated by thinking about the user's point of view.  Let's say that we freeze the submit button after they submit once (using the solution to the double-tap problem).  When they backup, I think the user will be confused about why they can't modify and submit.  Should we then provide a button "create a new user" which goes back to the original signup page (thus resetting the social info)?

On that note, if the user botches their email address and realizes it on the verification screen, it looks like they will have lost permanent ability to use their social account without an administrator removing it from the "dead" (unverifiable) account.

Thanks for your advice.

**Comment by jplehmann** [comment]
@pennersr Would love to hear your thoughts on my response above on how this is not the same issue at all.

To elaborate a bit more.  Here's what I see happening:
1. The user starts the signup process with FB account
2. On second page they pick username1 and email1.
3. On verification page, they realize for some reason that email address isn't one that will work. *
4. They press back button.
5. They enter username2 and email2.  (Attempts to re-use username1 and email1 are correctly handled).
6. They submit and get 500 error because the FB account is already associated with username/email1.

Now they have their FB account associated and locked into to email1 which they realized they can't use.  And second the email they want to use email2 is also unusable now, because the verification email was never sent.  Not to mention they got an error message.

\* Why they are changing emails I do not understand.  One way this could happen is with a typo, but what I am seeing is that they are always changing to a different domain, like yahoo to gmail, so it does not look like they think they entered an invalid email address.

A. I do not see how this can or should be handled with Javascript outside the framework. This seems like a bug to not catch the error and report to user.
B. I'm still wondering how a user can reassociate their FB account. I think the message from (A) would just need to say contact the administrator to fix this.

**Comment by jplehmann** [comment]
Now I have a good explanation as to what's going on, from a real user.  They connect their FB account, add a username and **ignore the email that has been auto-populated from the FB account** -- one which is an old email they don't use anymore.  Once they hit the verification screen they realize it and back up to correct the email address.  (I guess that for Facebook turning off  `SOCIALACCOUNT_QUERY_EMAIL` might help avoid this problem, but I don't want this behavior for Google).

Here's what I think we need to do: At a minimum, 1) catch the integrity error, and 2) give a message telling the user to contact an admin to re-associate their social account, and 3) let them know they can sign up without the social account and their actual email right now (with link).

I would consider taking a shot at fixing this if @pennersr would read over what I've written and verify that it's the right approach.

**Comment by jplehmann** [comment]
Oh, I think this is even better --

When they try to recreate an account using an EXISTING username, and EXISTING FB login that is associated to that username, and a NEW email, then simply add that new email to that account, make it primary and send the verification email.  That is the behavior they want, and I don't see why it would be insecure given that they are still using the same FB login.

Does that sound secure and is there any problem with this @pennersr ?

**Comment by jplehmann** [comment]
@pennersr To be clear, I would like to submit a PR for this work but I first want to make sure you approve of the this approach.  

Please review my last 3 comments and proposal in the last comment.  Thanks.

**Comment by pennersr** [comment]
I am still a bit puzzled by the exact scenario in which this takes place. If users go back and try to signup again, the username generation should be smart enough to pick a new username, and the duplicate email address checking should also stop things from going wrong. 

Can you please provide a test case that covers your scenario? I think that once we have a test case that clearly demonstrates the issue we can have a more solid discussion on how to fix it.

**Comment by jplehmann** [comment]
@pennersr Thank you for the response.  I can try to create a test case if needed, but I can easily answer your question.  The issue happens when they *change* their username and email on the second pass. I've tried to clearly lay this out above multiple times, such as in the step by step description here:  https://github.com/pennersr/django-allauth/issues/1911#issuecomment-369605327

**Comment by pennersr** [comment]
If you can, please create a test case first. Whatever solution we end up with, it needs to be covered by a unit test anyway.

**Comment by pennersr** [comment]
825920d9f0e5461b3ebb29f8e84f530d0fd98635

**Comment by jplehmann** [comment]
@pennersr Thanks for your quick response once I wrote the test.  This will certainly address the worst part of the issue.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1911
