### ISSUE TITLE
Strengthen password in change password page

### ISSUE THREAD

**Issue by teckkimlee** [pennersr/django-allauth#1913]
I can't find any mechanism to restrict any character in the change password page. My django user model is done by all-auth. Have tried validator but doesn't work

Password requirement

- Minimum 8 Characters
- At least 1 uppercase and lowercase letter
- At least 1 number

**Comment by pennersr** [comment]
The adapter has a clean_password method,  you can also use Django password validators.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1913
