### ISSUE TITLE
Xing Provider Broken due to closed API

### ISSUE THREAD

**Issue by rotherfuchs** [pennersr/django-allauth#1917]
Hey,

Xing has closed their API due to which allauth's respective provider is not working anymore. However, Xing provides a alternative login method:

https://dev.xing.com/plugins/login_with/docs#get-started

Can you implement support for that?

**Comment by pennersr** [comment]
I would gladly accept pull requests, it is not something I will be actively working on.

**Comment by pennersr** [comment]
Indeed, I myself am unsure what the current status of Xing is, but if nobody offered help to look into this or even bump the issue over the course of 5 years it's not worth to keep this open.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1917
