### ISSUE TITLE
form key not included in ajax POST response

### ISSUE THREAD

**Issue by DanielSwain** [pennersr/django-allauth#1920]
I am making an ajax call to `/accounts/password/set/`.  The response is coming through OK with a 200 status code.  While the [Release Notes clearly state](http://django-allauth.readthedocs.io/en/latest/release-notes.html?highlight=ajax#id8) that a `form` key is included in the response to an ajax call, when I `console.log(response.form)`, I get "undefined".  I also tried making the ajax call to `/accounts/password/change/`, but the `form` key is just not there in the response from either call.

**Comment by DanAtShenTech** [comment]
Looks like `AjaxCapableProcessFormViewMixin()` calls `form_invalid()`, but `form_invalid()` is not defined anywhere in either `PasswordChangeView()` or `PasswordSetView()`, so there will never be a form returned or an invalid message returned if the form validation fails.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1920
