### ISSUE TITLE
ACCOUNT_EMAIL_CONFIRMATION_COOLDOWN not respected for login with not yet activated account

### ISSUE THREAD

**Issue by BernhardPosselt** [pennersr/django-allauth#1921]
When registering a new account you can log in before confirming your e-mail address. This sends another email confirmation for every login attempt. The cool down does not seem to be respected, I was able to send over 20 E-Mails to my mail account in 30 seconds.

**Comment by iloveyo123u1** [comment]
ACCOUNT_EMAIL_VERIFICATION = 'optional' 

can fix it , but this is not perfect

**Comment by tanoabeleyra** [comment]
@BernhardPosselt It seems that there isn't any cooldown if you're using [HMAC](https://en.wikipedia.org/wiki/HMAC) (which is the default method): https://github.com/pennersr/django-allauth/blob/master/allauth/account/utils.py#L306
I guess it's impossible to implement a cooldown with HMAC given that there's no record of the date of the (last) confirmation email, it would be necessary to use a DB and the goal with HMAC is to avoid it.

Disable HMAC with `ACCOUNT_EMAIL_CONFIRMATION_HMAC=False` if you don't care about the DB hit.

**Comment by BernhardPosselt** [comment]
@tanoabeleyra needs docs probably as well. Can I do that on a production server without doing anything special?

**Comment by tanoabeleyra** [comment]
@BernhardPosselt Yes, as far as I can tell you can disable HMAC safely. Every pending HMAC confirmation key will still work: https://github.com/pennersr/django-allauth/blob/master/allauth/account/views.py#L342

**Comment by banagale** [comment]
This confused me as well. I was building UI that would hide the re-send email confirmation if cooldown had not yet been exceeded.

I went through the code when I noticed `EmailConfirmation` objects were not being created to query off of and then saw `EmailConfiration` model was not being used at all. 

I'd recommend a comment in the EmailConfirmation model at least that explains the model is not used with default settings.

**Comment by 9mido** [comment]
Correct me if I am wrong, but wouldn't PR #2631 solve all of these problems if merged? 

To me it seems like that PR would be better than having a cooldown setting. The timeouts can be controlled for pretty much anything. I have tested that timeout PR and confirm that it works for preventing users from abusing your allauth email sending.

**Comment by derek-adair** [comment]
Pretty sure this is closable as per the conversation in https://github.com/pennersr/django-allauth/pull/2631 and the implementation of [rate limiting.](https://github.com/pennersr/django-allauth/commit/116b7a89c37149aeab083d1542539e6c99ba91a7)

**Comment by pennersr** [comment]
Indeed, see implementation of `should_send_confirmation_mail()` -- in case of HMAC, it uses rate limiting.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1921
