### ISSUE TITLE
Fix RemovedInDjango21Warnings

### ISSUE THREAD

**Issue by 9dev** [pennersr/django-allauth#1926]
@pennersr 

With Python 3.4, Django 1.11.9 and django-allauth 0.34.0 I'm getting the following warning:

`.../python3.4/site-packages/django/contrib/auth/__init__.py:96: RemovedInDjango21Warning: In allauth.account.auth_backends.AuthenticationBackend.authenticate(), move the `request` keyword argument to the first positional argument.`

To reproduce please add `-Wall` to your python command.

Note this is not a duplicate. Similar issue was closed as resolved, but the warning persists.

**Comment by pennersr** [comment]
Fixed in 0.35.0

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1926
