### ISSUE TITLE
How to make a new or customize existing provider without touch the allauth app?

### ISSUE THREAD

**Issue by umarmughal824** [pennersr/django-allauth#1927]
Hi, I want to customize the google provide to deal with id_token. If I keep the entire allauth library in my project and then update the file. It works but I don't want to do it that way of customization becasue if I customize the allauth itself then how will I be able to get upgrades of allauth later.

So I want to make a separate standalone app in my project and which I could plug with allauth without touching allauth so that later I can easily get upgrades from allauth. But as in documentation there its possible to customize it but no documentation is provided about this customization except just a line of customization.

So if Its not possible to customize existing then at least tell me about creating new provider so that I could make new customized google provider for my usage.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1927
