### ISSUE TITLE
Unexpected unique-key constraint error on "account_emailaddress" table

### ISSUE THREAD

**Issue by SundialServices** [pennersr/django-allauth#1930]
During testing to try to get email confirmation set up, I unexpectedly got this _crash_:

`_mysql_exceptions.IntegrityError: (1062, "Duplicate entry 'foo@bar.com' for key 'email'")`

... which originated at:

`allauth/account/views.py", line 210, in dispatch`

I use these settings:

```
ACCOUNT_AUTHENTICATION_METHOD = "username"
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_CONFIRM_EMAIL_ON_GET = False
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_SIGNUP_EMAIL_ENTER_TWICE = True
ACCOUNT_UNIQUE_EMAIL = False
```

I was able to circumvent the problem with this SQL command:

`alter table account_emailaddress drop index email;
`

... but this approach doesn't "feel right" to me.  I _do_ want to have more than one account with the same e-mail address, and it would appear from the docs that the `ACCOUNT_UNIQUE_EMAIL` option should do it.  But the SQL schema suggests otherwise:  it has a unique index.

With this constraint removed from the table, I now have two table-rows, with different user-ids, referencing the same e-mail address, as I intended.  _Should_ this table have this SQL constraint?

**Comment by pennersr** [comment]
Closing, too little to go on. Perhaps related to #2299

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1930
