### ISSUE TITLE
How can I list all connected social accounts nad save they to project?

### ISSUE THREAD

**Issue by ensofter** [pennersr/django-allauth#1931]
Hello! First of all I want to thank you for this app.

I use it capable to attach social accounts to a local account (email + password). Suddenly, I needed to add new functionality and share social accounts into groups.

I did **models.py**

class AddProject(models.Model):
____author = models.ForeignKey(User)
____title = models.CharField(max_length=200, verbose_name=u"Назние проекта")
____def __str__(self):
________return self.title

**forms.py**

class AddProjectForm(forms.ModelForm):
____class Meta:
________model = AddProject
________fields = ('title',)

And **views.py**

def page_add_project(request):
____project = AddProject.objects.filter(author=request.user)
____if request.method == "POST":
________form = AddProjectForm(request.POST)
________if form.is_valid():
____________project = form.save(commit=False)
____________project.author = request.user
____________project.save()
____________return redirect('projects')
____else:
________form = AddProjectForm
____return render(request, 'adminlte/project.html', {'form': form, 'projects': project})

In **project.htm**l i did

<form method="POST" class="post-form">
{% csrf_token %}
{{ form|as_bootstrap }}
<button type="submit" class="btn btn-default btn-sm">Save</button>
</form>

{% for project in projects %}
<div>
{{ project.title }}
</div>
{% endfor %}

Maybe you help me please. How can I list all connected social accounts to this local account  and attach them to the new project.

Thank you very muth!

**Comment by pennersr** [comment]
Closing -- please reformulate into something that clearly points to an issue in allauth.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1931
