### ISSUE TITLE
What is it blank.html for redirect URI?

### ISSUE THREAD

**Issue by gukobrist** [pennersr/django-allauth#1935]
I use allauth for autentification.

But now i try send nessages to wall on VK.

in provider a take scope for this operation in socialaccounts/providers/vk/providers.py

scope = ['groups', 'notify ', 'friends', 'photos', 'audio', 'video', 'pages', '+256', 'status', 'notes', 'wall', 'ads', 'wall', 'offline', 'messages', 'ads', 'docs', 'notifications', 'stats', 'email', 'market',]

then i take access_token

access_token = SocialToken.objects.filter(account__user=request.user, account__provider='vk')

then i use vk api

    session = vk.Session(access_token=access_token)
    api = vk.API(session)
    api.wall.post(message='Hello, World!')

Then i try connect socialaccount -  /accounts/vk/login/?process=connect

And have error 
{"error":"invalid_scope","error_description":"standalone applications should use blank.html as redirect_uri to access messages"}

Can you help me? What wrong? Thank you

**Comment by pennersr** [comment]
Sorry, your issue is not about authentication but about specific further use of VK. This goes beyond scope, I'll have to close it.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1935
