### ISSUE TITLE
Version 0.35 drops support for Django < 1.11

### ISSUE THREAD

**Issue by gdvalderrama** [pennersr/django-allauth#1944]
Version 0.35 drops support for Django < 1.11 add adds support for Django 2.0.

I think this is more than worth mentioning in the changelog.

Introduced in commit: cfc5112bf474af2cbb16e4b4a36708e8949a2105

**Comment by miraculixx** [comment]
> I think this is more than worth mentioning in the changelog.

agree, in particular since Django 1.8 is LTS until "at least April 2018", see https://www.djangoproject.com/download/

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1944
