### ISSUE TITLE
Add confirguration variable to enforce verification before setting new primary email even if all emails are not verified

### ISSUE THREAD

**Issue by barsch** [pennersr/django-allauth#1945]
In a current project I really want to encourage email verification - so people who want to set a new primary email should verify the new email before setting it primary - currently you can set primary emails freely as long none of the existing emails are verified, see https://github.com/pennersr/django-allauth/blob/master/allauth/account/views.py#L478-L509

**Comment by derek-adair** [comment]
This feature does not make sense to add.  Either require verification or dont.  This would be poor UX (IMO).

**Comment by derek-adair** [comment]
Close this.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1945
