### ISSUE TITLE
ACCOUNT_EMAIL_VERIFICATION customizable dinamically in AccountAdapter

### ISSUE THREAD

**Issue by rocchidavide** [pennersr/django-allauth#1946]
Is it possible to set or change ACCOUNT_EMAIL_VERIFICATION in AccountAdapter? I'm trying to set as 'mandatory' for the company user profile, and 'optional' for the private user profile.

**Comment by derek-adair** [comment]
I solved this w/ a single account adapter that has logic for this by reading an account_type field.  Not sure how worthy this is to add BUT i would use it.

Would it be silly to have it look for a defined field and let users override w/ a form defaulting to the setting?  How else might this be achieved?

**Comment by pennersr** [comment]
It would definitely be useful to have a `adapter.get_email_verification_method(user)` method available.

**Comment by derek-adair** [comment]
Could probably add "help wanted" tag, this *seems* like a good entry level PR for someone looking to get involved.

**Comment by Hk669** [comment]
hey @pennersr can you give me a brief on this issue, i wanna work on this issue.

**Comment by pennersr** [comment]
This should be it:
- Add a `get_email_verification_method(self, email): return app_settings.app_settings.EMAIL_VERIFICATION` to the account adapter
- Replace references to `app_settings.EMAIL_VERIFICATION` with a call to that method.

**Comment by muneeb706** [comment]
I have tried adding this feature in PR: https://github.com/pennersr/django-allauth/pull/3648

**Comment by pennersr** [comment]
Moved to https://codeberg.org/allauth/django-allauth/issues/1946
