### ISSUE TITLE
Improved documentation for routing

### ISSUE THREAD

**Issue by commadelimited** [pennersr/django-allauth#195]
We've started to use AllAuth for a project at my work and it's been great so far. Lots of functionality wrapped up in a relatively easy to use package. My only criticism thus far is one of documentation.

For example, the example we were give here includes a line like this:

`<a href="{% url 'account_email' %}">Account Settings</a>`

But I can't find that in the documentation anywhere. I know that the source code is out there, and developers should be willing to read it, but they shouldn't have to since you have actual documentation available. Additionally we're working with a pure front end developer who doesn't understand Django at all. Should he have to read the source code to figure out what's baked into the framework?

Anyway, this is a relatively minor point but one that would greatly improve the usefulness and usability of AllAuth. Well done.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/195
