### ISSUE TITLE
Email as a login and <input name='login'>

### ISSUE THREAD

**Issue by coobit** [pennersr/django-allauth#1951]
Having problems with allauth:
1)I create custom user class
2)I user email as a USERNAME_FIELD
3)now the allauth login form works great, but the email input tag looks like this

 <input type='email' name='login'> 

and my browser (chrome) always tryies to put a login (from browser cache) there and not the email. Looks like I need to change name='login' some how.
I can't find a way to change this behavior exept for manual login template rewriting.

**Comment by pennersr** [comment]
Please check the documentation, 2) is wrong. Don't put email in username.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1951
