### ISSUE TITLE
How to use Alluath with Firebase Auth

### ISSUE THREAD

**Issue by softmarshmallow** [pennersr/django-allauth#1952]
Simple Query...
I want to authenticate , login, logout with a Unique Token.
using
`firebase.auth().currentUser.getIdToken()`

any solutions for this?

**Comment by pennersr** [comment]
https://django-allauth.readthedocs.io/en/latest/faq.html#why-did-you-just-close-my-issue

**Comment by romelgomez** [comment]
Hi, @softmarshmallow 

I found this stackoverflow question >> 

https://stackoverflow.com/questions/48232029/using-firebase-auth-with-django

The next part is not cleat to me, if your have any more info, please, I like to look it.  

> get the ID token by calling firebase.auth().currentUser.getIdToken()

Thanks

**Comment by Sirus-store** [comment]
how do you specificly use firebase with django-allauth

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1952
