### ISSUE TITLE
Cannot get email and user friend from Facebook Profile

### ISSUE THREAD

**Issue by brollylssj** [pennersr/django-allauth#1953]
settings.py
```
SOCIALACCOUNT_PROVIDERS = {
    'facebook': {
        'METHOD': 'js_jdk',
        'SCOPE': ['email', 'public_profile', 'user_friends'],
        'AUTH_PARAMS': {'auth_type': 'reauthenticate'},
        'FIELDS': [
            'id',
            'email',
            'name',
            'first_name',
            'last_name',
            'verified',
            'locale',
            'timezone',
            'link',
            'gender',
            'updated_time'],
        'EXCHANGE_TOKEN': True,
        'LOCALE_FUNC': lambda request: 'en_US',
        'VERIFIED_EMAIL': False,
        'VERSION': 'v2.12'}
}
SOCIALACCOUNT_EMAIL_REQUIRED = False
SOCIALACCOUNT_QUERY_EMAIL = True
```

After making the request to FB API I get only information about public_profile. (email and user_friends are not fetched) 
![image](https://user-images.githubusercontent.com/9872727/36442093-eb77ea6a-1674-11e8-89ec-1788db328ee3.png)

**Comment by pennersr** [comment]
For some Facebook permissions you will need to have your FB app reviewed. All of this goes beyond scope of allauth, hence closing this issue.

**Comment by brollylssj** [comment]
Permissions are approved 
![image](https://user-images.githubusercontent.com/9872727/36443531-550254f8-1679-11e8-8aae-61db4d7052bf.png)

**Comment by pennersr** [comment]
Even if approved: "In order for a person to show up in one person's friend list, both people must have decided to share their list of friends with your app and not disabled that permission during login. Also both friends must have been asked for user_friends during the login process."

**Comment by brollylssj** [comment]
@pennersr 
According to FB documentation email, public_profile and user_friends do not need require review.
The root of the problem is that when we are redirected to FB auth page we can not pick/unpick email and user_friends permissions.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1953
