### ISSUE TITLE
allauth should call user.full_clean()

### ISSUE THREAD

**Issue by marfire** [pennersr/django-allauth#1957]
Before saving a `user` instance allauth should call `user.full_clean()`. Of course, allauth has its own hooks for cleaning various things, but it shouldn't ignore what's been defined on the `User` model. Especially since Django [does some cleaning by default](https://docs.djangoproject.com/en/dev/topics/auth/customizing/#django.contrib.auth.models.AbstractUser.clean) (e.g.  `normalize_email()`).

The natural place for this would seem to be in `DefaultAccountAdapter.save_user()`:

    if commit:
        user.full_clean()
        user.save()

However, there may be other paths for saving user objects (e.g. for social accounts?).

**Comment by derek-adair** [comment]
As far as i'm concerned this is a valid proposal.  What reasons would there be to not do this?

**Comment by pennersr** [comment]
It's not just a matter of calling `full_clean()` -- as that potentially raises `ValidationError`. When we're in `save_user()` we've passed the point of validation I am afraid, so `full_clean()` would have to be called elsewhere.

**Comment by derek-adair** [comment]
Where would it go? Should it go there?

**Comment by pennersr** [comment]
I haven't researched this yet, so I don't have the answer. In any case, it must be a piece of code, likely form related, that handles `ValidationError`.

**Comment by pennersr** [comment]
Moved to https://codeberg.org/allauth/django-allauth/issues/1957
