### ISSUE TITLE
Optional variable for logout route?

### ISSUE THREAD

**Issue by commadelimited** [pennersr/django-allauth#196]
We've just started using AllAuth and it's been great, but I have a question about the logout route. When clicked, this link:

`<a href="{% url 'account_logout' %}">Logout</a>`

logs me out, then lands me on `/accounts/logout/`. I would prefer that it redirect me back to the index page: `/` instead. I reviewed the docs and found `LOGIN_REDIRECT_URL` which directs you to a specific page on login. I could not, however, find a corresponding `LOGOUT_REDIRECT_URL` option. How would go about achieving this functionality within version `0.9.0`?

Regards

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/196
