### ISSUE TITLE
How to use transactional e-mail provider

### ISSUE THREAD

**Issue by sowinski** [pennersr/django-allauth#1961]
Hi,

I would like to use a transactional e-mail provider to style my templates. So I have to implement there api calls.

What is the best way to do that?

I would Overwrite the DefaultAccountAdapter and modify send_mail? Depending on the template_prefix I would decide which kind of email has to be send. 

What do you think?

**Comment by pennersr** [comment]
Indeed, or, write an email backend (https://docs.djangoproject.com/en/2.0/topics/email/#topic-email-backends)

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1961
