### ISSUE TITLE
Changes in VK API. Application does not work for VK.

### ISSUE THREAD

**Issue by rivmar** [pennersr/django-allauth#1962]
VK changed requirements to api url. Version is required parameter now.
Detailes: https://vk.com/dev/api_requests :

> v – marks the used API version. Using this parameter may change different methods' reply formats. For the moment actual API version is 5.21. This parameter should be sent with all API requests.

Currently VKOAuth2Adapter returns error:

> File "/home/maria/job/venvs/optoVE/lib/python3.5/site-packages/allauth/socialaccount/providers/vk/views.py", line 53, in complete_login
    extra_data = resp.json()['response'][0]
KeyError: 'response'

resp.json() = {'error': {'error_msg': 'Invalid request: v (version) is required', 'error_code': 8, 'request_params': [{'key': 'oauth', 'value': '1'}, {'key': 'method', 'value': 'users.get'}, {'key': 'fields', 'value': 'first_name,last_name,nickname,screen_name,sex,bdate,city,country,timezone,photo,photo_medium,photo_big,photo_max_orig,has_mobile,contacts,education,online,counters,relation,last_seen,activity,universities'}, {'key': 'user_ids', 'value': '59610393'}]}}

Add:
'v': '1.0'
to params.

**Comment by romvano** [comment]
Also returned paramter 'uid' is now called 'id'

**Comment by citxx** [comment]
This issue was addressed in e7b03cc379e4527cb8b821f54768635ed95f4c6e, but it was too late for the latest release. I asked for the new release in #1965. You can find a workaround in the comments.

**Comment by taime** [comment]
The issue fixed, but we do not get this fix with `pip install django-allauth`
Please update pip package!

**Comment by k-solnushkin** [comment]
@pennersr Dear Raymond,

I just wanted to thank you for making *django-allauth* available to the community. It is a great package, and an immense help to many Django developers dealing with various authentication systems of the Internet!

**Comment by last-partizan** [comment]
Will be fixed by https://github.com/pennersr/django-allauth/pull/2307

**Comment by kastielspb** [comment]
When package will be updated on pypi?

**Comment by derek-adair** [comment]
This is likely fixed.

**Comment by pennersr** [comment]
Closing -- dated

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1962
