### ISSUE TITLE
Optionally require approval from authorized user before enabling account login. 

### ISSUE THREAD

**Issue by rcooke** [pennersr/django-allauth#1964]
For closed sites, they would need an additional approval step for new accounts.

One where a special user (or any Superuser) would see a list of persons requesting an account, and their e-mail verification status (if enabled).  And they would approve individually or in groups the users that met whatever membership criterion they have.  This could also be automated based on payment success, or their address, or anything else in their profile.

And the ability to REJECT any application.  Which would at least send a reject message to the applicant.  Possibly also delete the account.

**Comment by JayTurnr** [comment]
Ditto.

**Comment by pennersr** [comment]
This goes beyond allauth scope. It should be possible to create an app that builds on top of allauth that provides exactly this functionality. If there is anything in allauth that complicates building such an app then feel free to reopen this ticket.

**Comment by rcooke** [comment]
Challenge Accepted!

**Comment by johanneswilm** [comment]
@rcooke Did you come with anything?

**Comment by rcooke** [comment]
For the site I was working on at the time (www.cadwatch.ca) I have implemented an approval process. Anybody can apply for a user ID, they have to enter some required information (postal code) that is used to decide if they should be approved.  Approval triggers the email with login info.  Approval is manual and done by any user with the user add permission.  The site is still growing, so far so good!

**Comment by khashashin** [comment]
@rcooke how did you solve this problem? I've currently same issue: https://stackoverflow.com/questions/63133088/change-django-allauth-email-verification-behaivior

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1964
