### ISSUE TITLE
VK provider is broken in 0.35.0

### ISSUE THREAD

**Issue by citxx** [pennersr/django-allauth#1965]
Some time ago VK announced, that the previously optional parameter (API version) will become required. For django-allauth this issue was addressed in e7b03cc379e4527cb8b821f54768635ed95f4c6e, but it was 4 days late for the 0.35.0 release.

Several days ago VK started rejecting requests without API version. It means, that all apps using django-allauth with VK produce 500 errors on each login attempt.

Is it possible to make a new release now?

**Comment by dgorobets** [comment]
For workaround you can install allauth from master branch:
git+https://github.com/pennersr/django-allauth.git@master

**Comment by citxx** [comment]
@pennersr Can you please comment why have you closed the issue? I don't see the new release out there.

Yes, I can use @dgorobets' advice to bypass the issue and it partially solves the issue for myself, but the latest release is still broken for everyone else.

**Comment by pennersr** [comment]
In order to keep things manageable I keep the policy of closing issues that are not pointing to a real issue in allauth. Yours is more of a general question.  

http://django-allauth.readthedocs.io/en/latest/faq.html#why-did-you-just-close-my-issue

(as for a release, I have no date currently)

**Comment by lokkomokko** [comment]
@dgorobets why after your branch allauth stoped translate to other languages? Only english

**Comment by last-partizan** [comment]
@lokkomokko 
```
cd virtualenv/src/django-allauth/allauth && django-admin compilemessages
```

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1965
