### ISSUE TITLE
ORCID provider api change

### ISSUE THREAD

**Issue by knirirr** [pennersr/django-allauth#1966]
ORCID have changed their API, which has produced some interesting effects on an application I have to maintain. Somehow, a user has managed to create a SocialAccount with an empty UID and the following additional information:

`{"orcidProfile": null, "errorDesc": {"content": "API 1.2 is disabled, please upgrade to the 2.0 API https://members.orcid.org/api/news/xsd-20-update"}, "messageVersion": "", "orcidSearchResults": null}`

Now, any time a user authenticates with ORCID they are logged in as this user. Deleting the offending SocialAccount instead causes django-allauth to act as if an ORCID authentication is for a new account  rather than logging in an existing user, and asks them to supply a username. 

I'll have a look through the django-allauth code just in case I can work out how to fix this, but any assistance/suggestions would be appreciated.

**Comment by knirirr** [comment]
Luckily, it turns out that this commit fixes the issue:

https://github.com/pennersr/django-allauth/commit/0780642c9cab06894641ed592947978470d338f5

Although apparently not yet in a release, installing this directly from master on Github was fine.  Apologies for the unnecessary ticket, and thanks for the fix.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1966
