### ISSUE TITLE
relative imports error 

### ISSUE THREAD

**Issue by codaba** [pennersr/django-allauth#1967]
On form submission (POST action) in accounts/login, accounts/signup, accounts/password/reset, page is sent to nonexistent login, signup and password/reset.

Trace shows that "from . import app_settings, signals" in account/views.py issues an 

> ImportError: attempted relative import with no known parent package.

**Comment by pennersr** [comment]
There is definitely nothing wrong in allauth here. If import errors occur, it is typically caused by custom PYTHONPATH setups or duplicate python module names being installed.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1967
