### ISSUE TITLE
SocialAccount EventBrite does not work

### ISSUE THREAD

**Issue by gabriel-amram** [pennersr/django-allauth#1968]
When trying to connect through EventBrite the response is built as a `dict` with a key `emails` which in turn is an array of objects consisting of `email` (<email>), `verified` (<bool>) and `primary` (<bool>)

the `extract_common_fields` of the provider doesn't return an `email` key as the `sociallogin_from_response` requires and instead returns a `emails` key with the aforementioned `dict`.

Instead, `extract_common_fields` should  return an `email` key with the primary email in the emails array, and should create `EmailAddress` model-objects in `extract_email_addresses` to use later on in `sociallogin_from_response`.

Test should have failed, and no matter how I change the Mock it still works (even if I remove the `email` field altogether from the Mock response)

**Comment by gabriel-amram** [comment]
fixed in PR #1969

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1968
