### ISSUE TITLE
Email verification for normal accounts only.

### ISSUE THREAD

**Issue by michaelfillier** [pennersr/django-allauth#197]
I want to have email confirmations for "standard" accounts only. If I enable that right now, users who authorize still need to confirm their email address. This is unnecessary for our purposes and I could see other sites with the same requirements.

If I make email confirm optional or none, users signing up without social media can create multiple accounts using fake emails.

Our site functions using the account as a way to limit certain interactions, so confirming the email address is important for those users who are not authorizing with a third party.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/197
