### ISSUE TITLE
installation, migrate: relation "account_emailaddress" does not exist

### ISSUE THREAD

**Issue by haolle** [pennersr/django-allauth#1973]
Following the installation steps, after "./manage.py migrate" command, it reports "relation 'account_emailaddress' doesn't exist".
I believe relevant settings have been done. The platform: django1.11.10, allauth0.35.0, postgresql.

In database, I couldn't find "allauth_emailaddress" and "allauth_emailconfirmation" tables. But I found relevant records in django_content_type.
Seems 'allauth.account' couldn't pass the "migrate" command.

Anyone can help? Thanks in advance.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1973
