### ISSUE TITLE
Bug: SOCIALACCOUNT_AUTO_SIGNUP is not respected

### ISSUE THREAD

**Issue by JayTurnr** [pennersr/django-allauth#1978]
`SOCIALACCOUNT_AUTO_SIGNUP = False` is not respected when a unregistered user tries to log in via social media

**Comment by pennersr** [comment]
Could you please be a little bit more specific? Under what exact scenario does auto signup not work properly?

**Comment by JayTurnr** [comment]
Setting: `SOCIALACCOUNT_AUTO_SIGNUP = False`
Scenario: User A has never signed up to my website before. They go onto the log in page, and choose 'Log In via Discord'
Expected outcome: Sign in rejected, user redirected to registration URL
Actual outcome: Auto-signup script is ran and a user is issued an account without all the extra models that are created during the actual signup script.

**Comment by pennersr** [comment]
Auto signup is covered in a unit test. I am not sure why this is not working for you. You might want to set a breakpoint in allauth/socialaccount/helpers.py::_process_signup(). If you find anything wrong in allauth, please report back.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1978
