### ISSUE TITLE
Facebook login does not work

### ISSUE THREAD

**Issue by mejmo** [pennersr/django-allauth#1980]
Hi, 
I'm not that type of guy that needs help without trying, but I am struggling to get facebook login running for almost 2 days. Thing is... I cannot find any reliable tutorial about this - facebook changed UI and provides Facebook Login and Account kit (I am using Facebook Login). Thing is, if I copy all settings from other tutorial I am getting:

Django version: 2.0.3
FB App settings: App domains: localhost
FB App settings: Site URL: http://localhost:8000
Django setting: Site ID = 1 (domain http://localhost)

```
Can't Load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and subdomains of your app to the App Domains field in your app settings.
```

If I add something like this into Valid OAuth redirect uri in Facebook Login Settings  http://localhost:8000/accounts/facebook/login/callback

```
URL Blocked: This redirect failed because the redirect URI is not whitelisted in the app’s Client OAuth Settings. Make sure Client and Web OAuth Login are on and add all your app domains as Valid OAuth Redirect URIs.
```

Did change something in fb API in last days? What I am doing wrong?

**Comment by mejmo** [comment]
Ok... I have it, http://localhost:8000/accounts/facebook/login/callback.. `/` was missing at the end.

**Comment by akashkumarhd** [comment]
@mejmo have you used facebook Account kit login or it is possible with this plugin? If yes then any suggestion for any changes other than all-auth documentation.

**Comment by PchopL** [comment]
Update (Sep 1, 2019): Facebook no longer accepts non-secure http domains in Facebook Login > Settings > Valid OAuth Redirect URIs, so it doesn't appear testing can be done via a local host anymore.

**Comment by MillieNakiganda** [comment]
You can create a certificate for localhost for development

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1980
