### ISSUE TITLE
How to authenticate users via Chrome extension?

### ISSUE THREAD

**Issue by evilplanet** [pennersr/django-allauth#1981]
As title, how do you expose a RESTful API to authenticate users from a Chrome extension? Taking into account of both locally stored username & password hash strings and third party log-in providers?

**Comment by evilplanet** [comment]
Or by reading cookies? How this might be achieved? Thank you!

**Comment by pennersr** [comment]
https://django-allauth.readthedocs.io/en/latest/faq.html#why-did-you-just-close-my-issue

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1981
