### ISSUE TITLE
Anonymise users when using email as username

### ISSUE THREAD

**Issue by bodgerbarnett** [pennersr/django-allauth#1982]
If using allauth with email addresses as the username, what is the best way to anonymise users, if requested?

Obviously, I can't set their email address to be blank because that won't work.

The only thing I can think of would be to set their email address to be something pseudo-random which the system is aware of so that it won't send emails to. But that seems very wrong to me.

**Comment by ddehghan** [comment]
This is a good idea specially for compliance with General Data Protection Regulation (GDPR) requirements of EU which is approaching quickly. 

There should be a way to one way hash name and email in the database so it wont be meaningful in case the data exposed.

**Comment by gajeshbhat** [comment]
@bodgerbarnett I think the way would be to create a list of anonymous users which are completely kept separate by a password or some encryption method. I have not yet gone through the GDPR in detail. But sooner or later I hope that django-core team will take up the issue.

**Comment by TobitRE** [comment]
Another idea:

you can choose between 'generate_unique_username' and 'generate_random_username'
The email for login is saved in the email value of the user so if you need to 'delete' a user you only have to remove the email and name from the user.

This will be also GDPR conform if you do not store additional personal information about the person.

Here a idea for the function (not mine https://gist.github.com/jcinis/2866253)

```
def generate_random_username(length=16, chars=ascii_lowercase+digits, split=4, delimiter='-'):
    username = ''.join([choice(chars) for i in range(length)])

    if split:
        username = delimiter.join([username[start:start+split] for start in range(0, len(username), split)])

    try:
        User.objects.get(username=username)
        return generate_random_username(length=length, chars=chars, split=split, delimiter=delimiter)
    except User.DoesNotExist:
        return username;
```

**Comment by 9mido** [comment]
I was able to figure this out with #2494 but it uses a third party library. Would be better if this was built into allauth with public/private key asymmetric encryption.

**Comment by pennersr** [comment]
Closing -- anonymization is beyond scope.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1982
