### ISSUE TITLE
Twitter get_avatar_url() in HTTPS?

### ISSUE THREAD

**Issue by ronaldlangeveld** [pennersr/django-allauth#1984]
Not sure if I'm missing something, but is there a way I can grab the twitter profile pics via HTTPS instead of the default HTTP?

**Comment by derek-adair** [comment]
This has been fixed if i'm not mistaken.

**Comment by vue-chartjsfierce603** [comment]
I retrieved the answer https://urlrequestedgar40.github.io/menial/

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1984
