### ISSUE TITLE
Problems with Line Login

### ISSUE THREAD

**Issue by han950307** [pennersr/django-allauth#1985]
Hello, first, this is a really cool project, and I really like how it has so many providers!
Anyhow, I'm trying to use Line login with this application, but I'm not sure why it is not working.
I got facebook login to work, then I followed the steps outlined in the documentation with Line login, but I'm getting the "Social Network Login Failure" (An error occurred while attempting to login via your social network account) error.

Some information I can give you here, but perhaps not that helpful.
My callback URL: `http://127.0.0.1:8000/accounts/line/login/callback/`
On my channel settings, OpenID Connect is `Applied`
In `settings.py` under `SOCIALACCOUNT_PROVIDERS` I do not have an entry for `line`

Any ideas why I might be getting this error? or pointers to how to debug & what else I should check?

Thanks a lot!

**Comment by pennersr** [comment]
You can try and debug things by putting a breakpoint in allauth/socialaccount/providers/oauth2/views.y::OAuth2CallbackView::dispatch -- see the `except` clause there. If you find anything that requires fixing, please let me know.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1985
