### ISSUE TITLE
problems provider facebook v2.12

### ISSUE THREAD

**Issue by vitorluz** [pennersr/django-allauth#1986]
Unable to load URL: The domain for this URL is not included in the application domains. In order to load this URL, add all domains and subdomains to the Application Domains field in the application settings.

**Comment by pennersr** [comment]
I have successfully converted projects to v2.12 by just putting `SOCIALACCOUNT_PROVIDERS = { 'facebook': { 'VERSION': 'v2.12' } } ` in the settings (which is now the default in allauth). As far as I can tell, there is nothing in allauth that needs to be changed. I suspect you need to check your FB settings.

Closing this, if you do find an issue in allauth, feel free to reopen.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1986
