### ISSUE TITLE
WeixinProvider should take unionid as uid 

### ISSUE THREAD

**Issue by DrChai** [pennersr/django-allauth#1988]
Weixin(Wechat) generates **openid**  only unique to a single application. If you has more than one app such as two apps one is Website Login and Mobile Login. it looks like only **unionid** from two different clientId‘s response are same. Although u may only need to create one wechat social app using your websiteApplication's client_id and secret_key, it can validate both code from website request and access_token from you Wechat app sdk

**Comment by ChainNewsYan** [comment]
```
class WeixinProvider(OAuth2Provider):
    id = 'weixin'
    name = 'Weixin'
    account_class = WeixinAccount

    def extract_uid(self, data):
        return data['unionid'] # here!!!

    def get_default_scope(self):
        return ['snsapi_login']

    def extract_common_fields(self, data):
        return dict(username=data.get('nickname'),
                    name=data.get('nickname'))
```

**Comment by derek-adair** [comment]
Worth closing / help wanted.  Looks like another WeiXin bug/feature request/whatever. This will likely be relevant if anyone wishes to use WeiXin in this manner.  It's _probably_ worth fixing after some of the more important features are implemented.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1988
