### ISSUE TITLE
allauth incompatible with auth-ldap

### ISSUE THREAD

**Issue by jbazik** [pennersr/django-allauth#199]
I'd like to run allauth side-by-side with auth-ldap.  I have local ldap users, but I'd like also
to support non-local and social network logins.

The problem is that the User model requires a unique username, and allauth provides one
(if not supplied by the user) by generating it based on varying seed values (which depend
on whether it is a social network or email login).  Because ldap usernames are externally
defined, there is a potential for conflicts.

My problem can be solved simply if allauth could take a configuration option to
provide that seed value.  Then I can carefully choose it to not ever conflict with my
ldap username values.

So, if I offer a patch that introduces configuration options such as
ACCOUNT_USERNAME_PREFIX and SOCIALACCOUNT_USERNAME_PREFIX,
which would be used by generate_unique_username to create a unique username,
would you consider a pull request?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/199
