### ISSUE TITLE
vk: Permission denied

### ISSUE THREAD

**Issue by pashinin** [pennersr/django-allauth#1990]
I've met every other error that was written in the internet. But now:

```
{'provider': 'vk', 'code': 'unknown', 'exception': PermissionDenied()}
```

So everything was ok, but callback url fails with this "wtf" error somewhere [here](https://github.com/pennersr/django-allauth/blob/cfc5112bf474af2cbb16e4b4a36708e8949a2105/allauth/socialaccount/providers/oauth2/views.py#L112).

I do have a "code" parameter in callback url. What can go wrong?

UPD:

There is no 'socialaccount_state' in request.session. And even if I set it manually in some Django view allauth can't see it. Don't know why. When I `log.debug(self.request.session['socialaccount_state'])` in my view I can see contents.

**Comment by last-partizan** [comment]
https://github.com/pennersr/django-allauth/issues/1965

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1990
