### ISSUE TITLE
Persisting session for social login

### ISSUE THREAD

**Issue by oddlog** [pennersr/django-allauth#1991]
Hi, I was trying hard to make session data persistent after social account login for the first time.

Everything is fine if social account exists, then Anonymous -> Logged in session gets transferred fine. 

Only in case first time login with social account I am unable to keep session data. Session.flush() gets called no matter what I tried.

This solution is probably right one, but I guess I need to decorate "SocialLogin" view, which I was unable to find since different providers use different login procedure
[https://stackoverflow.com/questions/8256566/persisting-session-variables-across-login/41849076#41849076 ](https://stackoverflow.com/questions/8256566/persisting-session-variables-across-login/41849076#41849076 )

Any help appreciated.

**Comment by pennersr** [comment]
Closing -- dated

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1991
