### ISSUE TITLE
Email authentication across multiple sites

### ISSUE THREAD

**Issue by bodgerbarnett** [pennersr/django-allauth#1997]
Is it possible to use allauth with email authentication across multiple sites using the sites framework?

In order to use email authentication, I need to set:-

ACCOUNT_AUTHENTICATION_METHOD = 'email'

but in order to allow the same email address to be used for different accounts on different sites, I need to set:-

ACCOUNT_UNIQUE_EMAIL = False

but if I do that, the assertion on line 25 of accounts/app_settings.py breaks.

Furthermore, it looks like users are always filtered based on their email address - not a combination of email address and user. This causes the duplicate address error when registering.

Maybe this combination of things isn't possible with allauth?

**Comment by bodgerbarnett** [comment]
Any update on this please?

**Comment by irfanka** [comment]
Hey @bodgerbarnett , did you find a way to do this?

**Comment by bodgerbarnett** [comment]
I did - each UserProfile has a Site attached to it - so I allowed non-unique email addresses and overrode email_address_exists to do the extra check to make sure that the email address doesn't already exist in combination with the particular site that's being used. You might have to do checks in a few other places but that was the crux of it.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1997
