### ISSUE TITLE
Http protocol in trusted sites

### ISSUE THREAD

**Issue by kirya-dev** [pennersr/django-allauth#1999]
So question. 
Is it permissible http(or https) protocol in trusted sites?
For example: http://localhost or http://realsitename.org, but not localhost or realsitename.org respectively?

**Comment by pennersr** [comment]
Whether or not http may depend on your OAuth provider -- some do not support inputting http based callback urls. Closing, this is not an issue in allauth.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1999
