### ISSUE TITLE
Dropbox support.

### ISSUE THREAD

**Issue by rob-balfre** [pennersr/django-allauth#200]
I've been trying to get a simple Django / Dropbox app up and running and having attempted and failed to use their Python SDK I turned to allauth (which I love) and added Dropbox support, seems to work but still experimental (see my fork). 

I'm new to OAuth and not sure how Django should actually access any of the protected resources once I have the correct tokens.   I know it's out of scope for allauth but I'd really appreciate some pointers on how to extend the code. I noticed after signup Django immediately gains access to the user info (which is Dropbox's case is via https://api.dropbox.com/1/account/info) so I'm thinking getting additional info shouldn't be too difficult?!!

Thanks,
Rob

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/200
