### ISSUE TITLE
USERNAME_FIELD, Credentials and ACCOUNT_AUTHENTICATION_METHOD

### ISSUE THREAD

**Issue by dwasyl** [pennersr/django-allauth#2002]
Hi there,

I have a system that catches `user_login_failed` and records the attempted username by using:
```
    UserModel = get_user_model()
    username = credentials.get(UserModel.USERNAME_FIELD)
```

Which works fine when `ACCOUNT_AUTHENTICATION_METHOD = "username_email"`. However, when `ACCOUNT_AUTHENTICATION_METHOD = "email"`, `credentials.get(UserModel.USERNAME_FIELD)` returns `None`.

`credentials.get(UserModel.USERNAME_FIELD)` should always return the value of the username used for the authentication. In the meantime, I've worked around this by checking both `credentials.get("username")` and `credentials.get("email")`.

This was tested with Django 1.11 and Allauth 0.35.0.

**Comment by derek-adair** [comment]
Pretty old but worth looking at -- i'm quite frankly out of my element when it comes to interacting w/ the django core auth system or i'd offer you more insight.

**Comment by pennersr** [comment]
> should always return the value of the username

But there is no username, only email. So your workaround looks like a proper WoW to me.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2002
