### ISSUE TITLE
Refactor allauth.account.utils.user_pk_to_url_str to use custom unique user field instead of pk

### ISSUE THREAD

**Issue by lorddaedra** [pennersr/django-allauth#2004]
Refactor allauth.account.utils.user_pk_to_url_str to use custom unique user field instead of pk.

I would like do not use pk (`integer` in my case) field in any external links to reset user password etc. I have unique uuid field for every user but it is not pk for performance reasons.

Main reason to hide real pk is to hide difference between id in start of month and end of month for some test new users. In can give some marketing internal information about how many new users have registered on service. So better to use `uuid` type here. But for performance reasons it is not good idea to make it pk. For pk better use integers and for uuid use some separate field...

It can be added as config variable
`ACCOUNT_USER_EXTERNAL_ID_FIELD = 'pk'  # default or 'uuid', for example, in my case`
or as adapter method (rename and move `user_pk_to_url_str` and `url_str_to_user_pk` to adapter).

**Comment by ivanfr90** [comment]
I'm using the [hashid-field](https://github.com/nshafer/django-hashid-field) type field for the pk of my User model.

I've detected that when user ask for reset his password, at the end of verification process this function `user_pk_to_url_str` is used in the url reset process verification. 

```
def url_str_to_user_pk(s):
    User = get_user_model()
    # TODO: Ugh, isn't there a cleaner way to determine whether or not
    # the PK is a str-like field?
    if getattr(User._meta.pk, 'remote_field', None):
        pk_field = User._meta.pk.remote_field.to._meta.pk
    else:
        pk_field = User._meta.pk
    if issubclass(type(pk_field), models.UUIDField):
        return s
    try:
        pk_field.to_python('a')
        pk = s
    except ValidationError:
        pk = base36_to_int(s)
    return pk
```
As HashId is an unknown instance of the `pk_field`, tries to convert to a python value using to_python. This conversion fails and at last convert the value to an non existent pk using `base36_to_int`. So at this point starts the problem to validate the reset email url.

**Comment by pulse-mind** [comment]
These issues are probably related : https://github.com/pennersr/django-allauth/issues/2156

**Comment by derek-adair** [comment]
This indeed does seem to be solved by https://github.com/pennersr/django-allauth/commit/6680a2a1a474139d9c8ad10fa19617d1db203c99 as per https://github.com/pennersr/django-allauth/issues/2156

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2004
