### ISSUE TITLE
Korean social provider `Daum` is now deprecated.

### ISSUE THREAD

**Issue by gyukebox** [pennersr/django-allauth#2018]
<img width="597" alt="2018-05-05 2 38 57" src="https://user-images.githubusercontent.com/20885668/39665203-3365aeda-50cb-11e8-944a-c1cd8ca6bc38.png">

TRANSLATION - The above picture says:  
Thank you for using Daum Developers.  
From July 18, 2017, Daum API will be integrated into Kakao API. We notify you that new Daum app will not be able to create from August 1st, 2017.

- By March 31st, 2018 : [Daum developers site](https://developers.daum.net/console) will be unavailable to access.
- By December 31st, 2018 : Requests to apis.daum.net will not be receieved.

By March 31, 2018, [Daum developers site](https://developers.daum.net/console) went unavailable.  
The reason is that the Daum API has been merged into [Kakao API](https://developers.kakao.com/docs/restapi/user-management)  
(Sorry about translation not being available)

I suggest updating previout `Daum` provider to newer `Kakao`, and update documentation according that.

**Comment by gyukebox** [comment]
Closing this issue since previous PRs have been open regarding to `Kakao` provider.  
Sorry for confuse :(

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2018
