### ISSUE TITLE
How can users update an incorrect email if verification is mandatory?

### ISSUE THREAD

**Issue by jleclanche** [pennersr/django-allauth#2019]
I run a site that does not have email/password signup, only social auth. Unfortunately, the social provider in question does not provide a confirmed email, so I have to ask users for it.

I already ask users for their email. Now, if I want to make email confirmation mandatory, I run the risk that users enter the wrong email during signup. If they do, they are straight up locked out of their account, because when they sign back in (with their social login), they hit the same account and are unable to update their email.

How can I give users a form to re-enter their email if they got it wrong? Example with Facebook:

![image](https://user-images.githubusercontent.com/235410/39665600-bb328f26-509f-11e8-9f38-dd52ca6375f1.png)

![image](https://user-images.githubusercontent.com/235410/39665610-d06e830e-509f-11e8-8d06-71b8874c2aea.png)

**Comment by jleclanche** [comment]
Worth noting that the way Facebook does it is by having the email confirmation page require authentication in the first place.

**Comment by jleclanche** [comment]
Since this doesn't seem to be possible btw, I might work on a patch to implement this. But I want to sanity check that I'm not missing something.

**Comment by derek-adair** [comment]
SEEMS like a corner case where the user (@jleclanche) can extend allauth and provide their own custom views for such a thing.

HOWEVER... man what a corner case.  What _do_ we do when we would like to require a validated email and the social provider doesn't do so.... hmmm...

@jleclanche, i know it's been 6 years but we are doing some house cleaning / feature organizing.  What, if anything, did you implement to get around this issue?

**Comment by pennersr** [comment]
Moved to https://codeberg.org/allauth/django-allauth/issues/2019
