### ISSUE TITLE
Reset password always fails in common user flow

### ISSUE THREAD

**Issue by danra** [pennersr/django-allauth#2020]
Consider the following common scenario:

1) User ask to reset his password, receives an email with a reset url to his email address.
2) User clicks the reset url from his mail client (e.g. outlook) which automatically opens in the default browser (e.g. IE)
3) The original URL containing the token redirects to a URL without the token after storing the token in the session. (this redirect mechanism was first introduced in commit 7c2b13c9d9356649fe9b09db5ea0d6f73166f192 . IIUC prior to this commit the token was left alone in the URL in the browser )
4) The user likes Chrome better so he copies the URL and pastes it in Chrome.
5) Submitting his new password fails because Chrome session doesn't include the token. This used to be a hard error and was fixed in a821c537dd213425990cc8c8f2549e26ff58a499 so an error view is shown instead)

I've just updated to 0.35 but before that I got error reports whenever the hard error occurred, and I saw it quite often.

Perhaps there is a way to solve the security concern in a different way without sacrificing usability (e.g. keep the token in the URL, but don't pass it in the HTTP_REFERRER?).

**Comment by tysonclugg** [comment]
This also affects users who start the password reset process on one device (eg: mobile), then receive the email on another (eg: laptop).  For some users, this isn't a matter of personal preference, rather limitations of using locked down "enterprise" mail and web proxy servers.

**Comment by pennersr** [comment]
AFAIK there is no other way of doing this. Users that switch browsers half way during a session will always get their hands burned. I do not think there is much you can do about this...

**Comment by danra** [comment]
@pennersr How about adding a setting for whether the token should remain in the url (as it used to work previously in this package) or be stored in the session (as it works now)?

Keeping the token in the URL might be less secure but it is more usable - will allow switching browsers / copying link from phone to computer etc.

**Comment by sunnyseeds** [comment]
I'm having this same issue. Anyone found a clean work around?

**Comment by sunnyseeds** [comment]
> AFAIK there is no other way of doing this. Users that switch browsers half way during a session will always get their hands burned. I do not think there is much you can do about this...

That's such a weak response. This is a common user flow for reset password and you're suggesting nothing can be done about it meanwhile it has to be made to work otherwise it causes a major headache for users.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2020
