### ISSUE TITLE
SECURITY: Release 0.36

### ISSUE THREAD

**Issue by tysonclugg** [pennersr/django-allauth#2021]
The current [change log in master](https://github.com/pennersr/django-allauth/blob/master/ChangeLog.rst) refers to version 0.36, which includes a [security fix](https://github.com/pennersr/django-allauth/commit/9c080bcd8463c10a605ace4b317d575450f3a20e#diff-a136a3ab0403c35496be1955335be9d9) added on 19 March (50 days ago).  Sadly, the [latest version released to pypi](https://pypi.org/pypi/django-allauth) is 0.35.

Here's a shields.io badge showing the current version released to pypi.org: ![pypi: django-allauth](https://img.shields.io/pypi/v/django-allauth.svg)

**First priority:** Make a release.

**Second priority:** Figure out how to ensure security fixes are released in a timely manner.  Perhaps moving the project to @jazzband would help?

**Comment by pennersr** [comment]
261e2e7b7956880afb745b225ec4081f40e2e52d

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2021
