### ISSUE TITLE
For what is /templates/account/messages/password_changed.txt

### ISSUE THREAD

**Issue by sowinski** [pennersr/django-allauth#2022]
Hi,

a lot of people talk about the password change implementation, because there is no success message or anything else. I was wondering what this file is for? 
/templates/account/messages/password_changed.txt

Why is it not displayed after changing the password?

**Comment by andreyshipilov** [comment]
Are you using this or not? https://docs.djangoproject.com/en/2.0/ref/contrib/messages/

**Comment by sowinski** [comment]
Ahh okay. No I haven't used this.

**Comment by andreyshipilov** [comment]
Well it's a message for that framework.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2022
