### ISSUE TITLE
Unknown error at the callback step

### ISSUE THREAD

**Issue by raphaelyancey** [pennersr/django-allauth#2023]
I got a rather mysterious error in the Django context of `/accounts/customauth/login/callback/?code=BsqV39Vir0P55Qekz5gv6l80F1T3x7&state=1cgQVlj0p5MD`.

```
{'auth_error': {'code': 'unknown',
                'exception': ConnectionError(MaxRetryError("HTTPConnectionPool(host='localhost', port=9050): Max retries exceeded with url: /o/token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcb6f2a33c8>: Failed to establish a new connection: [Errno 111] Connection refused',))",),),
                'provider': 'customauth'}}
```

The OAuth2 server is `django-oauth-toolkit` and works perfect with its test client (http://django-oauth-toolkit.herokuapp.com/consumer) with which I was able to issue a token.

Client app with `django-allauth` lives at http://localhost:9040
OAuth2 server with `django-oauth-toolkit` lives at http://localhost:9050

The host, port, path and IDs/secrets are fine, and neither `django-allauth` nor `django-oauth-toolkit` raise errors in the logs.

**Comment by raphaelyancey** [comment]
Indeed http://localhost:9050 wasn't reachable from inside the oauth server container (using Docker) thus the error. Tweaked Docker networks a bit and got rid of it.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2023
