### ISSUE TITLE
Sign up screen is skipped when a previously deleted user tries to login

### ISSUE THREAD

**Issue by hmhrex** [pennersr/django-allauth#2024]
I'm using the Spotify provider. When a social user disconnects, I also delete their user and any info related to that user (I like privacy 😄). However, in testing the sign up form, I've come across a weird issue.

**Actions taken:**
1. Create a new Spotify account.
2. Use this account to login to my site via the login button (noted below)
3. Fill out and submit sign up form.
4. Delete the `SocialAccount`, `SocialToken`, `User`, and related objects, either programmatically or from the admin pages.
5. Delete all sessions from the database (in a dev environment of course).
6. Check database to make sure there is no trace of the user.
7. Revoke app access from the social application.
8. Login using the same Spotify account created in step 1 via the login button (noted below)

**What is expected:** To be met with a sign page to create a username, etc.

**Result:** The sign up page is skipped completely and I'm redirected to the value in my next url argument.

**My login button:**
```html
<a href="{% provider_login_url 'spotify' %}?next=/app/">
```

I'm also trying to create an application where the local django auth account is basically just a shadow account. I want all login/logout functionality to happen via the `SocialAccount`. Not sure if skipping the normal account login process is messing with this at all.

**Comment by hmhrex** [comment]
Wow. I feel pretty dumb after trying to fix this over a couple hours. I didn't realize that `SOCIALACCOUNT_AUTO_SIGNUP` was set to `True` by default. 🤦‍♂️

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2024
