### ISSUE TITLE
Request for clarification around scopes/fields (I'll write docs)

### ISSUE THREAD

**Issue by kerkeslager** [pennersr/django-allauth#2025]
First off, I'd like to say thank you for writing this library and open sourcing it.

This "issue" is mainly a question. I'd be happy to submit a pull request with updates to the docs, but I want verification that my understanding of the code is correct from someone who knows the codebase better.

Facebook is introducing some changes to their permission system and requiring that apps go through a review process if they want access to certain pieces of data. I'm currently trying to verify that our app *doesn't* use those permissions, but had trouble tracing the code to see what the fields in the configuration correspond to in requests made to Facebook.

The specific message from facebook was:

> In order to maintain your current API access, your app will need to be submitted for review by August 1, 2018. If your app is not submitted for review, you will lose access to these permissions and features.
> - `user_friends`
> - `user_link`
> - `user_gender`
> - `user_age_range`

It's not clear in the AllAuth docs whether these correspond to the `SCOPE` or the `FIELDS` variable--for example, it's unclear if the following requests `user_gender`:

```
SOCIALACCOUNT_PROVIDERS = {
    'facebook': {
        'METHOD': 'oauth2',
        'SCOPE': ['email','public_profile'],
        'FIELDS': [
            'id',
            'gender'
        ],
        ...
    }
}
```

From reading the code, I *think* that `user_gender` is a scope, and `gender` under `FIELDS` is just requesting the gender from the `public_profile` scope (if it exists).

If someone can verify that I'm understanding this correctly, as I said, I'll submit a pull request with additions to the docs to clarify this. I'm sure a lot of people have this concern with major changes to the Facebook permissions coming August 1.

**Comment by kerkeslager** [comment]
I don't have a way to test this works for sure until the changes are released August 1, hence wanting to make sure. :)

**Comment by kerkeslager** [comment]
Are we going to get clarification on this? August 1 is rapidly approaching.

**Comment by pennersr** [comment]
I would gladly accept a PR that improves the documentation, though, keeping this ticket open is not really going to move things forward. Closing...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2025
