### ISSUE TITLE
'OneToOneRel' object has no attribute 'to' while using password reset (custom template)

### ISSUE THREAD

**Issue by ghost** [pennersr/django-allauth#2027]
`/home/patryk/workspace/.virtualenvs/project/lib/python3.6/site-packages/allauth/account/utils.py in url_str_to_user_pk, line 421`

Python 3.6.5, 3.5.5 doesn't work too.

**Comment by zvolsky** [comment]
Same with Email Confirmation after SignUp.
In current allauth version 0.43.0 the code is on the line 470.
This change would help:
if getattr(User._meta.pk, "remote_field", None) and getattr(User._meta.pk.remote_field, "to", None):

**Comment by pennersr** [comment]
Closed via f4618614

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2027
