### ISSUE TITLE
GDPR

### ISSUE THREAD

**Issue by chubz** [pennersr/django-allauth#2028]
What would be the best approach to ensure that allauth Email Addresses Model is GDPR compliant?
Issues:
Encryption - This seems problematic since it seems hard to change the current model to support it outside of allauth core package
Deletion - seems fine to me since this is tied to the user so how you handle user deletion you can change the email field value.
Anonymization - This seems fine to me since you can set unique value that has nothing to do with user.

What worries me is the part where email is stored in a separate model where you cannot encrypt the field.

**Comment by pennersr** [comment]
Encrypting the email address is not something the GDPR mandates. All the GDPR is about is that you as a business are upfront about what personal data you store, and for what purposes. Furthermore, upon user request you should hand over a dump of this data to the user and respect the user's request to be erased from your database. All of these are business processes that you can build on top of allauth....

**Comment by chubz** [comment]
You are right, though it is a recommended procedure that personal information fields be protected even if someone obtains a copy of stored data as not to leak sensitive information by having those stored in plain text. It's a long shot that someone having hard data copy did not breach your codebase too (and could decrypt), but my ticket was more along those lines.

Closing it is valid as is your explanation to why you closed it. Good to have such an answer about for others questioning what lengths to go to while complying.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2028
