### ISSUE TITLE
Adding a unique_together on emailaddress user_id and primary

### ISSUE THREAD

**Issue by jleclanche** [pennersr/django-allauth#2030]
Allauth currently does not set a unique together constraint on user_id and primary. That means a user can end up with multiple primary emails.
Should we add one?

**Comment by pennersr** [comment]
Duplicate of: https://github.com/pennersr/django-allauth/issues/225

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2030
