### ISSUE TITLE
Django allauth activation code during registration

### ISSUE THREAD

**Issue by rtiwarihr** [pennersr/django-allauth#2033]
I am using Django allauth for authentication to my rest api. I have the whole process working as expected (login, registration, password reset) with email confirmation ..etc.

My question is when a user register the user receives an email with the link that user need to click and confirm to get access to the website. However, i want to use allauth but instead of a link I want a randomly generated activation code (example: 123456). That user can post via rest to confirm.

**Comment by chubz** [comment]
I think that confirmation page checks the url token, and marks EmailAddress db entry as verified.
If you want a custom check you should look into that process.

Try making a custom endpoint, post method restricted, that receives the code and resolves user from it.
Then checks EmailAddress for that user and marks it as verified.
If you don't store the connection between code and user then you can see the HMAC procedure allauth does for generating a token that resolves into a user id and try to use something like that.

**Comment by derek-adair** [comment]
Close as "help wanted".  This would be a neat feature that you shouldn't focus on right now.

**Comment by pennersr** [comment]
This is already supported, ingredients:

- Don't use HMAC email confirmation.
- Populate `get_adapter().generate_emailconfirmation_key(email)` to your own liking (have it return `123456`)

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2033
