### ISSUE TITLE
Proper way to check if user is activated?

### ISSUE THREAD

**Issue by sowinski** [pennersr/django-allauth#2037]
Hi,

I already found out that user.is_active is not touched by django-allauth. (This was my first thought)

But how can I check whether a user is already activated or not?

Thx

**Comment by pennersr** [comment]
Define "activated" -- what does this mean? From an authentication point of view this is a meaningless concept and hence not used by allauth.

**Comment by sowinski** [comment]
> Define "activated" -- what does this mean?
I want to know which users activated there account by opening the activation link and click afterwards on accept. (So they can login)

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2037
