### ISSUE TITLE
Google - error in documentation

### ISSUE THREAD

**Issue by Ondrysak** [pennersr/django-allauth#2047]
http://django-allauth.readthedocs.io/en/latest/providers.html#google

it says 

>Key, is not needed, leave blank.

but it actually is needed, without it API calls return error.

`INVALID_TOKEN_HEADER`

https://developers.google.com/adwords/api/docs/common-errors#QuotaCheckError.INVALID_TOKEN_HEADER

**Comment by danielMicallef** [comment]
Having the `Client Id` and `Secret Key` seem to be enough to retrieve data from Google. In any case no other `Key` is given in their console afaik.

**Comment by pennersr** [comment]
https://django-allauth.readthedocs.io/en/latest/faq.html#why-did-you-just-close-my-issue

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2047
