### ISSUE TITLE
User email address should be unique only after email confirmation link clicked

### ISSUE THREAD

**Issue by easternsun** [pennersr/django-allauth#2049]
Currently anyone can sign up with anyone elses random email and that authentic owner would now be blocked from using it even though the fake user never confirms that email.
e.g. 
User A uses example1@gmail.com as their email but never confirms because they don't have access to it. User B, the rightful owner of example1@gmail.com signs up using that same email but finds they can't use it as its already in use by User A, who is falsely using it but has never confirmed it. 
Would it be better to only allow a unique email AFTER a user has confirmed it through clicking the email link to activate it?

**Comment by gajeshbhat** [comment]
One solution to this would be to set a short period of time for confirm email expiration and set the account email confirmation mandatory for login. These both things can be accomplished by setting `ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS` and `ACCOUNT_EMAIL_VERIFICATION` in settings.py to values required.
For details refer : http://django-allauth.readthedocs.io/en/latest/configuration.html

**Comment by pennersr** [comment]
Why would the real user be blocked? He can use password reset and gain control of the account.

**Comment by easternsun** [comment]
@gajeshbhat thank you yes that would have been a good way to solve the problem.
@pennersr you are correct :/ I'm going to quietly close this issue and pretend it didn't happen. Apologies and thank you.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2049
