### ISSUE TITLE
Database constraint error with Django 1.5 and custom user object

### ISSUE THREAD

**Issue by robert-osborne** [pennersr/django-allauth#205]
I have a new project using Django 1.5 a custom user object and, hopefully, django-allauth.

Everything seems to work fine (including creating local accounts, verifying emails etc.) until I try to create an account using facebook, then I get the following database constraint:

(1452, 'Cannot add or update a child row: a foreign key constraint fails (`myproject`.`socialaccount_socialaccount`, CONSTRAINT `user_id_refs_id_1d22aaf0651975b6` FOREIGN KEY (`user_id`) REFERENCES `auth_user` (`id`))'

/Users/robert/.virtualenvs/myproject/lib/python2.7/site-packages/allauth/socialaccount/providers/oauth2/views.py in view
            return self.dispatch(request, _args, *_kwargs) ...
/Users/robert/.virtualenvs/myproject/lib/python2.7/site-packages/allauth/socialaccount/providers/oauth2/views.py in dispatch
            return complete_social_login(request, login) ...
/Users/robert/.virtualenvs/myproject/lib/python2.7/site-packages/allauth/socialaccount/helpers.py in complete_social_login
            ret = _process_signup(request, sociallogin) ...
/Users/robert/.virtualenvs/myproject/lib/python2.7/site-packages/allauth/socialaccount/helpers.py in _process_signup
        sociallogin.save() ...
/Users/robert/.virtualenvs/myproject/lib/python2.7/site-packages/allauth/socialaccount/models.py in save
        self.account.save() ...

I note that the socialaccount app is using migrations while account is merely syncdb ...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/205
