### ISSUE TITLE
kakao profile_url api version up

### ISSUE THREAD

**Issue by kdc0110** [pennersr/django-allauth#2050]
Hello,

https://github.com/pennersr/django-allauth/blob/41f84f5530b75431cfd4cf2b89cd805ced009e7d/allauth/socialaccount/providers/kakao/views.py#L16

Now kakao api provide v2 version.

Change log(translation):

* When auto signup is off, get only token. `NotRegisteredException` occurred when requesting v1 user information without explicitly calling app connection, but it does not occur when v2 user information is requested.
* The parameter name to use when you want to take only certain properties has been changed. propertyKeys -> property_keys.
* Among the keys of the response, the key with the kaccount prefix has a hierarchy under kakao_account.
* Add new values: age, birthday, gender.
* Add hasXXXX responses for age, birthday, gender that require additional information consent.
* If response does not exist, the key dose not exist.
* If the server is unstable, it will not cause an error even if it does not return a value under kakao_account. If it is absolutely necessary, you must request it again.

reference url:
https://developers.kakao.com/docs/restapi/user-management#사용자-정보-요청
https://developers.kakao.com/docs/restapi/user-management#v1-사용자-정보-요청

Thank you!

**Comment by punkyoon** [comment]
looks good to close this issue now :)

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2050
