### ISSUE TITLE
I have some questions about "Remember Me"

### ISSUE THREAD

**Issue by BadGrem** [pennersr/django-allauth#2052]
- Does this "Remember Me" use cookies to save the user's login information on the client side so that the user can log in again?
- Do I need to use JS to realize this "Remember Me"?

**Comment by pennersr** [comment]
https://django-allauth.readthedocs.io/en/latest/faq.html#why-did-you-just-close-my-issue

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2052
