### ISSUE TITLE
error[10061] after signup

### ISSUE THREAD

**Issue by zzm88** [pennersr/django-allauth#2053]
> error at /accounts/signup/
> [Errno 10061] 
> Request Method:	POST
> Request URL:	http://127.0.0.1:8000/accounts/signup/
> Django Version:	1.11.13
> Exception Type:	error
> Exception Value:	
> [Errno 10061] 
> Exception Location:	c:\python27\Lib\socket.py in create_connection, line 575
> Python Executable:	C:\Users\zzm\OneDrive\django-generic-scaffold\getsms\Scripts\python.exe
> Python Version:	2.7.13
> Python Path:	
> ['C:\\Users\\zzm\\OneDrive\\django-generic-scaffold/example',
>  'C:\\Users\\zzm\\OneDrive\\django-generic-scaffold\\example\\..',
>  'C:\\WINDOWS\\SYSTEM32\\python27.zip',
>  'C:\\Users\\zzm\\OneDrive\\django-generic-scaffold\\getsms\\DLLs',
>  'C:\\Users\\zzm\\OneDrive\\django-generic-scaffold\\getsms\\lib',
>  'C:\\Users\\zzm\\OneDrive\\django-generic-scaffold\\getsms\\lib\\plat-win',
>  'C:\\Users\\zzm\\OneDrive\\django-generic-scaffold\\getsms\\lib\\lib-tk',
>  'C:\\Users\\zzm\\OneDrive\\django-generic-scaffold\\getsms\\Scripts',
>  'c:\\python27\\Lib',
>  'c:\\python27\\DLLs',
>  'c:\\python27\\Lib\\lib-tk',
>  'C:\\Users\\zzm\\OneDrive\\django-generic-scaffold\\getsms',
>  'C:\\Users\\zzm\\OneDrive\\django-generic-scaffold\\getsms\\lib\\site-packages']
> Server time:	Sun, 24 Jun 2018 16:12:12 +0000
> Traceback Switch to copy-and-paste view
> C:\Users\zzm\OneDrive\django-generic-scaffold\getsms\lib\site-packages\django\core\handlers\exception.py in inner
>             response = get_response(request) ...
> ▶ Local vars
> C:\Users\zzm\OneDrive\django-generic-scaffold\getsms\lib\site-packages\django\core\handlers\base.py in _legacy_get_response
>             response = self._get_response(request) ...
> ▶ Local vars
> C:\Users\zzm\OneDrive\django-generic-scaffold\getsms\lib\site-packages\django\core\handlers\base.py in _get_response
>                 response = self.process_exception_by_middleware(e, request) ...
> ▶ Local vars
> C:\Users\zzm\OneDrive\django-generic-scaffold\getsms\lib\site-packages\django\core\handlers\base.py in _get_response
>                 response = wrapped_callback(request, *callback_args, **callback_kwargs) ...
> ▶ Local vars
> C:\Users\zzm\OneDrive\django-generic-scaffold\getsms\lib\site-packages\django\views\generic\base.py in view
>             return self.dispatch(request, *args, **kwargs) ...
> ▶ Local vars
> C:\Users\zzm\OneDrive\django-generic-scaffold\getsms\lib\site-packages\django\utils\decorators.py in _wrapper
>             return bound_func(*args, **kwargs) ...
> ▶ Local vars
> C:\Users\zzm\OneDrive\django-generic-scaffold\getsms\lib\site-packages\django\views\decorators\debug.py in sensitive_post_parameters_wrapper
>             return view(request, *args, **kwargs) ...
> ▶ Local vars
> C:\Users\zzm\OneDrive\django-generic-scaffold\getsms\lib\site-packages\django\utils\decorators.py in bound_func
>                 return func.__get__(self, type(self))(*args2, **kwargs2) ...
> ▶ Local vars
> C:\Users\zzm\OneDrive\django-generic-scaffold\getsms\lib\site-packages\allauth\account\views.py in dispatch
>         return super(SignupView, self).dispatch(request, *args, **kwargs) ...
> ▶ Local vars
> C:\Users\zzm\OneDrive\django-generic-scaffold\getsms\lib\site-packages\allauth\account\views.py in dispatch
>                                             **kwargs) ...
> ▶ Local vars
> C:\Users\zzm\OneDrive\django-generic-scaffold\getsms\lib\site-packages\allauth\account\views.py in dispatch
>                                                           **kwargs) ...
> ▶ Local vars
> C:\Users\zzm\OneDrive\django-generic-scaffold\getsms\lib\site-packages\django\views\generic\base.py in dispatch
>         return handler(request, *args, **kwargs) ...
> ▶ Local vars
> C:\Users\zzm\OneDrive\django-generic-scaffold\getsms\lib\site-packages\allauth\account\views.py in post
>             response = self.form_valid(form) ...
> ▶ Local vars
> C:\Users\zzm\OneDrive\django-generic-scaffold\getsms\lib\site-packages\allauth\account\views.py in form_valid
>                 self.get_success_url()) ...
> ▶ Local vars
> C:\Users\zzm\OneDrive\django-generic-scaffold\getsms\lib\site-packages\allauth\account\utils.py in complete_signup
>                          signal_kwargs=signal_kwargs) ...
> ▶ Local vars
> C:\Users\zzm\OneDrive\django-generic-scaffold\getsms\lib\site-packages\allauth\account\utils.py in perform_login
>             send_email_confirmation(request, user, signup=signup) ...
> ▶ Local vars
> C:\Users\zzm\OneDrive\django-generic-scaffold\getsms\lib\site-packages\allauth\account\utils.py in send_email_confirmation
>                                                     signup=signup) ...
> ▶ Local vars
> C:\Users\zzm\OneDrive\django-generic-scaffold\getsms\lib\site-packages\allauth\account\models.py in send_confirmation
>         confirmation.send(request, signup=signup) ...
> ▶ Local vars
> C:\Users\zzm\OneDrive\django-generic-scaffold\getsms\lib\site-packages\allauth\account\models.py in send
>         get_adapter(request).send_confirmation_mail(request, self, signup) ...
> ▶ Local vars
> C:\Users\zzm\OneDrive\django-generic-scaffold\getsms\lib\site-packages\allauth\account\adapter.py in send_confirmation_mail
>                        ctx) ...
> ▶ Local vars
> C:\Users\zzm\OneDrive\django-generic-scaffold\getsms\lib\site-packages\allauth\account\adapter.py in send_mail
>         msg.send() ...
> ▶ Local vars
> C:\Users\zzm\OneDrive\django-generic-scaffold\getsms\lib\site-packages\django\core\mail\message.py in send
>         return self.get_connection(fail_silently).send_messages([self]) ...
> ▶ Local vars
> C:\Users\zzm\OneDrive\django-generic-scaffold\getsms\lib\site-packages\django\core\mail\backends\smtp.py in send_messages
>             new_conn_created = self.open() ...
> ▶ Local vars
> C:\Users\zzm\OneDrive\django-generic-scaffold\getsms\lib\site-packages\django\core\mail\backends\smtp.py in open
>             self.connection = self.connection_class(self.host, self.port, **connection_params) ...
> ▶ Local vars
> c:\python27\Lib\smtplib.py in __init__
>             (code, msg) = self.connect(host, port) ...
> ▶ Local vars
> c:\python27\Lib\smtplib.py in connect
>         self.sock = self._get_socket(host, port, self.timeout) ...
> ▶ Local vars
> c:\python27\Lib\smtplib.py in _get_socket
>         return socket.create_connection((host, port), timeout) ...
> ▶ Local vars
> c:\python27\Lib\socket.py in create_connection
>         raise err ...
> ▶ Local vars
> Request information
> USER
> AnonymousUser
> 
> GET
> No GET data
> 
> POST
> Variable	Value
> username	
> u'zzm3'
> password1	
> u'liufei921'
> csrfmiddlewaretoken	
> u'cdL4gXysrDXOX6qECOqZT3djrxmTTaF8X27lGKcNiwAvYA6Ip6lLEjtKKIYm92tn'
> email	
> u'3533522203@qq.com'
> password2	
> u'liufei921'
> FILES
> No FILES data
> 
> COOKIES
> Variable	Value
> csrftoken	
> 'whG8C56OQWp8D6FeGjbdk11OU3kbpgh2h62p2SK9HP2PEAlitB6Z5hhfdeWEF85h'
> META
> Variable	Value
> ALLUSERSPROFILE	
> 'C:\\ProgramData'
> APPDATA	
> 'C:\\Users\\zzm\\AppData\\Roaming'
> ASL.LOG	
> 'Destination=file'
> COMMONPROGRAMFILES	
> 'C:\\Program Files (x86)\\Common Files'
> COMMONPROGRAMFILES(X86)	
> 'C:\\Program Files (x86)\\Common Files'
> COMMONPROGRAMW6432	
> 'C:\\Program Files\\Common Files'
> COMPUTERNAME	
> 'DESKTOP-K45OBG0'
> COMSPEC	
> 'C:\\WINDOWS\\system32\\cmd.exe'
> CONTENT_LENGTH	
> '164'
> CONTENT_TYPE	
> 'application/x-www-form-urlencoded'
> CSRF_COOKIE	
> 'whG8C56OQWp8D6FeGjbdk11OU3kbpgh2h62p2SK9HP2PEAlitB6Z5hhfdeWEF85h'
> DJANGO_SETTINGS_MODULE	
> 'example.settings'
> DRIVERDATA	
> 'C:\\Windows\\System32\\Drivers\\DriverData'
> EXEPATH	
> 'C:\\Program Files\\Git\\bin'
> FPS_BROWSER_APP_PROFILE_STRING	
> 'Internet Explorer'
> FPS_BROWSER_USER_PROFILE_STRING	
> 'Default'
> GATEWAY_INTERFACE	
> 'CGI/1.1'
> HOME	
> 'C:\\Users\\zzm'
> HOMEDRIVE	
> 'C:'
> HOMEPATH	
> '\\Users\\zzm'
> HTTP_ACCEPT	
> 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8'
> HTTP_ACCEPT_ENCODING	
> 'gzip, deflate, br'
> HTTP_ACCEPT_LANGUAGE	
> 'zh-CN,zh;q=0.9,en;q=0.8'
> HTTP_CACHE_CONTROL	
> 'max-age=0'
> HTTP_CONNECTION	
> 'keep-alive'
> HTTP_COOKIE	
> 'csrftoken=whG8C56OQWp8D6FeGjbdk11OU3kbpgh2h62p2SK9HP2PEAlitB6Z5hhfdeWEF85h'
> HTTP_HOST	
> '127.0.0.1:8000'
> HTTP_ORIGIN	
> 'http://127.0.0.1:8000'
> HTTP_REFERER	
> 'http://127.0.0.1:8000/accounts/signup/'
> HTTP_UPGRADE_INSECURE_REQUESTS	
> '1'
> HTTP_USER_AGENT	
> 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36'
> LANG	
> 'en_US.UTF-8'
> LOCALAPPDATA	
> 'C:\\Users\\zzm\\AppData\\Local'
> LOGONSERVER	
> '\\\\DESKTOP-K45OBG0'
> MSYSTEM	
> 'MINGW64'
> NUMBER_OF_PROCESSORS	
> '4'
> OLDPWD	
> 'C:/Users/zzm/OneDrive/django-generic-scaffold'
> ONEDRIVE	
> 'C:\\Users\\zzm\\OneDrive'
> OS	
> 'Windows_NT'
> PATH	
> 'C:\\Program Files\\Git\\mingw64\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Users\\zzm\\bin;C:\\Program Files (x86)\\Intel\\iCLS Client;C:\\Program Files\\Intel\\iCLS Client;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Python27;C:\\Users\\zzm;C:\\Program Files\\TortoiseGit\\bin;C:\\Program Files\\Git\\cmd;C:\\Program Files\\PuTTY;C:\\Python27\\Scripts;C:\\Users\\zzm\\AppData\\Local\\Programs\\Python\\Python36-32\\Scripts;C:\\Users\\zzm\\AppData\\Local\\Programs\\Python\\Python36-32;C:\\Program Files\\MySQL\\MySQL Utilities 1.6;C:\\Program Files\\nodejs;C:\\curl-7.59.0-win64-mingw\\bin;C:\\Program Files (x86)\\Common Files\\Propellerhead Software\\ReWire;C:\\Program Files\\Common Files\\Propellerhead Software\\ReWire;C:\\WINDOWS\\System32\\OpenSSH;C:\\Users\\zzm\\AppData\\Local\\Programs\\Python\\Python36-32\\Scripts;C:\\Users\\zzm\\AppData\\Local\\Programs\\Python\\Python36-32;C:\\Users\\zzm\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Python27\\Scripts;C:\\Users\\zzm\\AppData\\Local\\Programs\\Fiddler;C:\\Users\\zzm\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\zzm\\AppData\\Roaming\\npm;C:\\Program Files\\Microsoft VS Code\\bin'
> PATHEXT	
> '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC'
> PATH_INFO	
> u'/accounts/signup/'
> PLINK_PROTOCOL	
> 'ssh'
> PROCESSOR_ARCHITECTURE	
> 'x86'
> PROCESSOR_ARCHITEW6432	
> 'AMD64'
> PROCESSOR_IDENTIFIER	
> 'Intel64 Family 6 Model 142 Stepping 9, GenuineIntel'
> PROCESSOR_LEVEL	
> '6'
> PROCESSOR_REVISION	
> '8e09'
> PROGRAMDATA	
> 'C:\\ProgramData'
> PROGRAMFILES	
> 'C:\\Program Files (x86)'
> PROGRAMFILES(X86)	
> 'C:\\Program Files (x86)'
> PROGRAMW6432	
> 'C:\\Program Files'
> PS1	
> '\\[\\033]0;$TITLEPREFIX:${PWD//[^[:ascii:]]/?}\\007\\]\\n\\[\\033[32m\\]\\u@\\h \\[\\033[35m\\]$MSYSTEM \\[\\033[33m\\]\\w\\[\\033[36m\\]`__git_ps1`\\[\\033[0m\\]\\n$ '
> PSMODULEPATH	
> 'C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules'
> PUBLIC	
> 'C:\\Users\\Public'
> PWD	
> 'C:/Users/zzm/OneDrive/django-generic-scaffold'
> PYTHONIOENCODING	
> 'UTF-8'
> PYTHONUNBUFFERED	
> '1'
> QUERY_STRING	
> ''
> REMOTE_ADDR	
> '127.0.0.1'
> REMOTE_HOST	
> ''
> REQUEST_METHOD	
> 'POST'
> SCRIPT_NAME	
> u''
> SERVER_NAME	
> 'DESKTOP-K45OBG0'
> SERVER_PORT	
> '8000'
> SERVER_PROTOCOL	
> 'HTTP/1.1'
> SERVER_SOFTWARE	
> 'WSGIServer/0.1 Python/2.7.13'
> SESSIONNAME	
> 'Console'
> SHLVL	
> '1'
> SPLICE_FOLDER	
> 'C:\\Users\\zzm\\Documents\\Splice'
> SYSTEMDRIVE	
> 'C:'
> SYSTEMROOT	
> 'C:\\WINDOWS'
> TEMP	
> 'C:\\Users\\zzm\\AppData\\Local\\Temp'
> TERM	
> 'cygwin'
> TERM_PROGRAM	
> 'vscode'
> TERM_PROGRAM_VERSION	
> '1.24.0'
> TMP	
> 'C:\\Users\\zzm\\AppData\\Local\\Temp'
> USERDOMAIN	
> 'DESKTOP-K45OBG0'
> USERDOMAIN_ROAMINGPROFILE	
> 'DESKTOP-K45OBG0'
> USERNAME	
> 'zzm'
> USERPROFILE	
> 'C:\\Users\\zzm'
> VSCODE_CWD	
> 'C:\\Program Files\\Microsoft VS Code'
> VSCODE_IPC_HOOK	
> '\\\\.\\pipe\\397e7c5005aca3723e06664c519f9d84-1.24.0-main-sock'
> VSCODE_NLS_CONFIG	
> '{"locale":"en","availableLanguages":{}}'
> VSCODE_NODE_CACHED_DATA_DIR_16692	
> 'C:\\Users\\zzm\\AppData\\Roaming\\Code\\CachedData\\6a6e02cef0f2122ee1469765b704faf5d0e0d859'
> VSCODE_PID	
> '16692'
> WINDIR	
> 'C:\\WINDOWS'
> _	
> 'C:/Program Files/Git/usr/bin/env'
> wsgi.errors	
> <open file '<stderr>', mode 'w' at 0x0374D0D0>
> wsgi.file_wrapper	
> ''
> wsgi.input	
> <socket._fileobject object at 0x04B06070>
> wsgi.multiprocess	
> False
> wsgi.multithread	
> True
> wsgi.run_once	
> False
> wsgi.url_scheme	
> 'http'
> wsgi.version	
> (1, 0)
> Settings
> Using settings module example.settings
> Setting	Value
> ABSOLUTE_URL_OVERRIDES	
> {}
> ADMINS	
> []
> ALLOWED_HOSTS	
> []
> APPEND_SLASH	
> True
> AUTHENTICATION_BACKENDS	
> ('django.contrib.auth.backends.ModelBackend',
>  'allauth.account.auth_backends.AuthenticationBackend')
> AUTH_PASSWORD_VALIDATORS	
> u'********************'
> AUTH_USER_MODEL	
> u'auth.User'
> BASE_DIR	
> 'C:\\Users\\zzm\\OneDrive\\django-generic-scaffold\\example'
> CACHES	
> {u'default': {u'BACKEND': u'django.core.cache.backends.locmem.LocMemCache'}}
> CACHE_MIDDLEWARE_ALIAS	
> u'default'
> CACHE_MIDDLEWARE_KEY_PREFIX	
> u'********************'
> CACHE_MIDDLEWARE_SECONDS	
> 600
> CSRF_COOKIE_AGE	
> 31449600
> CSRF_COOKIE_DOMAIN	
> None
> CSRF_COOKIE_HTTPONLY	
> False
> CSRF_COOKIE_NAME	
> u'csrftoken'
> CSRF_COOKIE_PATH	
> u'/'
> CSRF_COOKIE_SECURE	
> False
> CSRF_FAILURE_VIEW	
> u'django.views.csrf.csrf_failure'
> CSRF_HEADER_NAME	
> u'HTTP_X_CSRFTOKEN'
> CSRF_TRUSTED_ORIGINS	
> []
> CSRF_USE_SESSIONS	
> False
> DATABASES	
> {'default': {'ATOMIC_REQUESTS': False,
>              'AUTOCOMMIT': True,
>              'CONN_MAX_AGE': 0,
>              'ENGINE': 'django.db.backends.sqlite3',
>              'HOST': '',
>              'NAME': 'C:\\Users\\zzm\\OneDrive\\django-generic-scaffold\\example\\db.sqlite3',
>              'OPTIONS': {},
>              'PASSWORD': u'********************',
>              'PORT': '',
>              'TEST': {'CHARSET': None,
>                       'COLLATION': None,
>                       'MIRROR': None,
>                       'NAME': None},
>              'TIME_ZONE': None,
>              'USER': ''}}
> DATABASE_ROUTERS	
> []
> DATA_UPLOAD_MAX_MEMORY_SIZE	
> 2621440
> DATA_UPLOAD_MAX_NUMBER_FIELDS	
> 1000
> DATETIME_FORMAT	
> u'N j, Y, P'
> DATETIME_INPUT_FORMATS	
> [u'%Y-%m-%d %H:%M:%S',
>  u'%Y-%m-%d %H:%M:%S.%f',
>  u'%Y-%m-%d %H:%M',
>  u'%Y-%m-%d',
>  u'%m/%d/%Y %H:%M:%S',
>  u'%m/%d/%Y %H:%M:%S.%f',
>  u'%m/%d/%Y %H:%M',
>  u'%m/%d/%Y',
>  u'%m/%d/%y %H:%M:%S',
>  u'%m/%d/%y %H:%M:%S.%f',
>  u'%m/%d/%y %H:%M',
>  u'%m/%d/%y']
> DATE_FORMAT	
> u'N j, Y'
> DATE_INPUT_FORMATS	
> [u'%Y-%m-%d',
>  u'%m/%d/%Y',
>  u'%m/%d/%y',
>  u'%b %d %Y',
>  u'%b %d, %Y',
>  u'%d %b %Y',
>  u'%d %b, %Y',
>  u'%B %d %Y',
>  u'%B %d, %Y',
>  u'%d %B %Y',
>  u'%d %B, %Y']
> DEBUG	
> True
> DEBUG_PROPAGATE_EXCEPTIONS	
> False
> DECIMAL_SEPARATOR	
> u'.'
> DEFAULT_CHARSET	
> u'utf-8'
> DEFAULT_CONTENT_TYPE	
> u'text/html'
> DEFAULT_EXCEPTION_REPORTER_FILTER	
> u'django.views.debug.SafeExceptionReporterFilter'
> DEFAULT_FILE_STORAGE	
> u'django.core.files.storage.FileSystemStorage'
> DEFAULT_FROM_EMAIL	
> u'webmaster@localhost'
> DEFAULT_INDEX_TABLESPACE	
> u''
> DEFAULT_TABLESPACE	
> u''
> DISALLOWED_USER_AGENTS	
> []
> EMAIL_BACKEND	
> u'django.core.mail.backends.smtp.EmailBackend'
> EMAIL_HOST	
> u'localhost'
> EMAIL_HOST_PASSWORD	
> u'********************'
> EMAIL_HOST_USER	
> u''
> EMAIL_PORT	
> 25
> EMAIL_SSL_CERTFILE	
> None
> EMAIL_SSL_KEYFILE	
> u'********************'
> EMAIL_SUBJECT_PREFIX	
> u'[Django] '
> EMAIL_TIMEOUT	
> None
> EMAIL_USE_LOCALTIME	
> False
> EMAIL_USE_SSL	
> False
> EMAIL_USE_TLS	
> False
> FILE_CHARSET	
> u'utf-8'
> FILE_UPLOAD_DIRECTORY_PERMISSIONS	
> None
> FILE_UPLOAD_HANDLERS	
> [u'django.core.files.uploadhandler.MemoryFileUploadHandler',
>  u'django.core.files.uploadhandler.TemporaryFileUploadHandler']
> FILE_UPLOAD_MAX_MEMORY_SIZE	
> 2621440
> FILE_UPLOAD_PERMISSIONS	
> None
> FILE_UPLOAD_TEMP_DIR	
> None
> FIRST_DAY_OF_WEEK	
> 0
> FIXTURE_DIRS	
> []
> FORCE_SCRIPT_NAME	
> None
> FORMAT_MODULE_PATH	
> None
> FORM_RENDERER	
> u'django.forms.renderers.DjangoTemplates'
> IGNORABLE_404_URLS	
> []
> INSTALLED_APPS	
> ['django.contrib.admin',
>  'django.contrib.auth',
>  'django.contrib.contenttypes',
>  'django.contrib.sessions',
>  'django.contrib.messages',
>  'django.contrib.staticfiles',
>  'generic_scaffold',
>  'books',
>  'django.contrib.sites',
>  'allauth',
>  'allauth.account',
>  'allauth.socialaccount',
>  'allauth.socialaccount.providers.weixin']
> INTERNAL_IPS	
> []
> LANGUAGES	
> [(u'af', u'Afrikaans'),
>  (u'ar', u'Arabic'),
>  (u'ast', u'Asturian'),
>  (u'az', u'Azerbaijani'),
>  (u'bg', u'Bulgarian'),
>  (u'be', u'Belarusian'),
>  (u'bn', u'Bengali'),
>  (u'br', u'Breton'),
>  (u'bs', u'Bosnian'),
>  (u'ca', u'Catalan'),
>  (u'cs', u'Czech'),
>  (u'cy', u'Welsh'),
>  (u'da', u'Danish'),
>  (u'de', u'German'),
>  (u'dsb', u'Lower Sorbian'),
>  (u'el', u'Greek'),
>  (u'en', u'English'),
>  (u'en-au', u'Australian English'),
>  (u'en-gb', u'British English'),
>  (u'eo', u'Esperanto'),
>  (u'es', u'Spanish'),
>  (u'es-ar', u'Argentinian Spanish'),
>  (u'es-co', u'Colombian Spanish'),
>  (u'es-mx', u'Mexican Spanish'),
>  (u'es-ni', u'Nicaraguan Spanish'),
>  (u'es-ve', u'Venezuelan Spanish'),
>  (u'et', u'Estonian'),
>  (u'eu', u'Basque'),
>  (u'fa', u'Persian'),
>  (u'fi', u'Finnish'),
>  (u'fr', u'French'),
>  (u'fy', u'Frisian'),
>  (u'ga', u'Irish'),
>  (u'gd', u'Scottish Gaelic'),
>  (u'gl', u'Galician'),
>  (u'he', u'Hebrew'),
>  (u'hi', u'Hindi'),
>  (u'hr', u'Croatian'),
>  (u'hsb', u'Upper Sorbian'),
>  (u'hu', u'Hungarian'),
>  (u'ia', u'Interlingua'),
>  (u'id', u'Indonesian'),
>  (u'io', u'Ido'),
>  (u'is', u'Icelandic'),
>  (u'it', u'Italian'),
>  (u'ja', u'Japanese'),
>  (u'ka', u'Georgian'),
>  (u'kk', u'Kazakh'),
>  (u'km', u'Khmer'),
>  (u'kn', u'Kannada'),
>  (u'ko', u'Korean'),
>  (u'lb', u'Luxembourgish'),
>  (u'lt', u'Lithuanian'),
>  (u'lv', u'Latvian'),
>  (u'mk', u'Macedonian'),
>  (u'ml', u'Malayalam'),
>  (u'mn', u'Mongolian'),
>  (u'mr', u'Marathi'),
>  (u'my', u'Burmese'),
>  (u'nb', u'Norwegian Bokm\xe5l'),
>  (u'ne', u'Nepali'),
>  (u'nl', u'Dutch'),
>  (u'nn', u'Norwegian Nynorsk'),
>  (u'os', u'Ossetic'),
>  (u'pa', u'Punjabi'),
>  (u'pl', u'Polish'),
>  (u'pt', u'Portuguese'),
>  (u'pt-br', u'Brazilian Portuguese'),
>  (u'ro', u'Romanian'),
>  (u'ru', u'Russian'),
>  (u'sk', u'Slovak'),
>  (u'sl', u'Slovenian'),
>  (u'sq', u'Albanian'),
>  (u'sr', u'Serbian'),
>  (u'sr-latn', u'Serbian Latin'),
>  (u'sv', u'Swedish'),
>  (u'sw', u'Swahili'),
>  (u'ta', u'Tamil'),
>  (u'te', u'Telugu'),
>  (u'th', u'Thai'),
>  (u'tr', u'Turkish'),
>  (u'tt', u'Tatar'),
>  (u'udm', u'Udmurt'),
>  (u'uk', u'Ukrainian'),
>  (u'ur', u'Urdu'),
>  (u'vi', u'Vietnamese'),
>  (u'zh-hans', u'Simplified Chinese'),
>  (u'zh-hant', u'Traditional Chinese')]
> LANGUAGES_BIDI	
> [u'he', u'ar', u'fa', u'ur']
> LANGUAGE_CODE	
> 'en-us'
> LANGUAGE_COOKIE_AGE	
> None
> LANGUAGE_COOKIE_DOMAIN	
> None
> LANGUAGE_COOKIE_NAME	
> u'django_language'
> LANGUAGE_COOKIE_PATH	
> u'/'
> LOCALE_PATHS	
> []
> LOGGING	
> {}
> LOGGING_CONFIG	
> u'logging.config.dictConfig'
> LOGIN_REDIRECT_URL	
> u'/accounts/profile/'
> LOGIN_URL	
> u'/accounts/login/'
> LOGOUT_REDIRECT_URL	
> None
> MANAGERS	
> []
> MEDIA_ROOT	
> u''
> MEDIA_URL	
> u''
> MESSAGE_STORAGE	
> u'django.contrib.messages.storage.fallback.FallbackStorage'
> MIDDLEWARE	
> None
> MIDDLEWARE_CLASSES	
> ['django.middleware.security.SecurityMiddleware',
>  'django.contrib.sessions.middleware.SessionMiddleware',
>  'django.middleware.common.CommonMiddleware',
>  'django.middleware.csrf.CsrfViewMiddleware',
>  'django.contrib.auth.middleware.AuthenticationMiddleware',
>  'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
>  'django.contrib.messages.middleware.MessageMiddleware',
>  'django.middleware.clickjacking.XFrameOptionsMiddleware']
> MIGRATION_MODULES	
> {}
> MONTH_DAY_FORMAT	
> u'F j'
> NUMBER_GROUPING	
> 0
> PASSWORD_HASHERS	
> u'********************'
> PASSWORD_RESET_TIMEOUT_DAYS	
> u'********************'
> PREPEND_WWW	
> False
> ROOT_URLCONF	
> 'example.urls'
> SECRET_KEY	
> u'********************'
> SECURE_BROWSER_XSS_FILTER	
> False
> SECURE_CONTENT_TYPE_NOSNIFF	
> False
> SECURE_HSTS_INCLUDE_SUBDOMAINS	
> False
> SECURE_HSTS_PRELOAD	
> False
> SECURE_HSTS_SECONDS	
> 0
> SECURE_PROXY_SSL_HEADER	
> None
> SECURE_REDIRECT_EXEMPT	
> []
> SECURE_SSL_HOST	
> None
> SECURE_SSL_REDIRECT	
> False
> SERVER_EMAIL	
> u'root@localhost'
> SESSION_CACHE_ALIAS	
> u'default'
> SESSION_COOKIE_AGE	
> 1209600
> SESSION_COOKIE_DOMAIN	
> None
> SESSION_COOKIE_HTTPONLY	
> True
> SESSION_COOKIE_NAME	
> u'sessionid'
> SESSION_COOKIE_PATH	
> u'/'
> SESSION_COOKIE_SECURE	
> False
> SESSION_ENGINE	
> u'django.contrib.sessions.backends.db'
> SESSION_EXPIRE_AT_BROWSER_CLOSE	
> False
> SESSION_FILE_PATH	
> None
> SESSION_SAVE_EVERY_REQUEST	
> False
> SESSION_SERIALIZER	
> u'django.contrib.sessions.serializers.JSONSerializer'
> SETTINGS_MODULE	
> 'example.settings'
> SHORT_DATETIME_FORMAT	
> u'm/d/Y P'
> SHORT_DATE_FORMAT	
> u'm/d/Y'
> SIGNING_BACKEND	
> u'django.core.signing.TimestampSigner'
> SILENCED_SYSTEM_CHECKS	
> []
> SITE_ID	
> 1
> STATICFILES_DIRS	
> []
> STATICFILES_FINDERS	
> [u'django.contrib.staticfiles.finders.FileSystemFinder',
>  u'django.contrib.staticfiles.finders.AppDirectoriesFinder']
> STATICFILES_STORAGE	
> u'django.contrib.staticfiles.storage.StaticFilesStorage'
> STATIC_ROOT	
> None
> STATIC_URL	
> '/static/'
> TEMPLATES	
> [{'APP_DIRS': True,
>   'BACKEND': 'django.template.backends.django.DjangoTemplates',
>   'DIRS': [],
>   'OPTIONS': {'context_processors': ['django.template.context_processors.debug',
>                                      'django.template.context_processors.request',
>                                      'django.contrib.auth.context_processors.auth',
>                                      'django.contrib.messages.context_processors.messages']}}]
> TEST_NON_SERIALIZED_APPS	
> []
> TEST_RUNNER	
> u'django.test.runner.DiscoverRunner'
> THOUSAND_SEPARATOR	
> u','
> TIME_FORMAT	
> u'P'
> TIME_INPUT_FORMATS	
> [u'%H:%M:%S', u'%H:%M:%S.%f', u'%H:%M']
> TIME_ZONE	
> 'UTC'
> USE_ETAGS	
> False
> USE_I18N	
> True
> USE_L10N	
> True
> USE_THOUSAND_SEPARATOR	
> False
> USE_TZ	
> True
> USE_X_FORWARDED_HOST	
> False
> USE_X_FORWARDED_PORT	
> False
> WSGI_APPLICATION	
> 'example.wsgi.application'
> X_FRAME_OPTIONS	
> u'SAMEORIGIN'
> YEAR_MONTH_FORMAT	
> u'F Y'
> You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard page generated by the handler for this status code.

**Comment by DanAtShenTech** [comment]
See [this issue](https://github.com/pennersr/django-allauth/issues/726).  You probably need set a DEFAULT_FROM_EMAIL in settings.

**Comment by pennersr** [comment]
Closing -- mail configuration problem, not an allauth issue.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2053
