### ISSUE TITLE
emails sent from locahost instead of email_host_user

### ISSUE THREAD

**Issue by addsimm** [pennersr/django-allauth#2055]
Hi 
I have set up all auth and everything is working fine with one exception.  All the emails generated, for example from reset password, come from localhost instead of the sender I want.  

I am using sendgrid and when I use the send_mail command from from django.core.mail in a test email, it comes from the sender specified  in the from parameter.

Is there a setting I am missing?

These are the ones I have (along with a sendgrid password): 

EMAIL_HOST = 'smtp.sendgrid.net'
EMAIL_HOST_USER = 'joinus@joinourstory.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

ACCOUNT_LOGIN_ATTEMPTS_LIMIT = 10
ACCOUNT_SIGNUP_FORM_CLASS = 'jos_members.views.SignupForm'
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_EMAIL_VERIFICATION = 'none'

Thank you!

**Comment by doganmeh** [comment]
my emails also come from webmaster@localhost which sometimes end up in spam.

**Comment by nibrahim** [comment]
A solution to this has been documented over [here](https://stackoverflow.com/questions/22700041/django-allauth-sends-verification-emails-from-webmasterservername). Basically, you have to set 

      DEFAULT_FROM_EMAIL = "info@website.com"

in your `settings.py`.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2055
