### ISSUE TITLE
production environment RuntimeError: populate() isn't reentrant

### ISSUE THREAD

**Issue by zzm88** [pennersr/django-allauth#2056]
It works fine in local environment.
but it turns out "RuntimeError: populate() isn't reentrant" in production.

the problem lies in settings.py
```
INSTALLED_APPS = [
     'allauth',
    #'allauth.account',
     #'allauth.socialaccount',
]
```
only when I comment the last two app it doesn't throw an error.

**Comment by gajeshbhat** [comment]
@zzm88 Can you be more descriptive? What were you trying to do?  Please provide the full stack trace. If you have found a StackOverflow thread for the above issue please post or ask a question in StackOverflow under `django-allauth` tag and post the link here.

**Comment by pennersr** [comment]
Closing -- unclear.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2056
