### ISSUE TITLE
Connect 2nd account while logged in to my first account

### ISSUE THREAD

**Issue by commadelimited** [pennersr/django-allauth#206]
I'm doing some testing on connecting multiple accounts using AllAuth. Here's my process:
- I click our "connect to twitter" button (URL: /accounts/twitter/login/) using username1
- I approve the app on Twitter.com and get redirected back.
- While still logged into our app, I log out from Twitter.com in another tab and log in as username2.
- I hit the same endpoint as previous, approve the app and get redirected.

Rather than having 2 accounts displayed, the second account has now taken over the first. Using the Django admin panel I look at username1 who has the id of 4, and username2 has the id of 5.

Is there a process by which we add second accounts from the same platform? Is this even possible? Note that I'm not talking about Twitter and Facebook. I'm talking about 2 Twitter accounts.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/206
