### ISSUE TITLE
6 digit verification for email address verification

### ISSUE THREAD

**Issue by webpn** [pennersr/django-allauth#2061]
_feature-request_

6 digit code verification has recently become a common practice: instead of having the user click on a verification link, you email him a 6 digits code that he has to write down in the final step of the sign-up form. This is quite useful when the user is using a computer where he cannot easily read his email (so he could read the 6 digits code on his phone), or vice versa.

Ideally, it would be great to enable both methods: in order to verify the user email address you send him the verification link and the 6 digits code, so that the user can choose which method is easier for him.

**Comment by hafizSiddiq7675** [comment]
Any workaround for this?

**Comment by ayushin** [comment]
anybody working on this?

**Comment by khylbom** [comment]
I'm also looking to try and do the same thing. If anyone comes up with a clean production-ready solution, please share!

**Comment by ebarojas** [comment]
I think this is critical to avoid users losing track of the confirmation email and if it's going to SPAM, catching it early on.

**Comment by 9mido** [comment]
Linking the following issue since it relates:

https://github.com/pennersr/django-allauth/issues/2814

**Comment by bene25** [comment]
+1

**Comment by ayushin** [comment]
we use django-otp

**Comment by bene25** [comment]
> django-otp

are you using it with rest?

**Comment by ayushin** [comment]
yes, but allauth + dj-rest-auth + otp requires a lot of tweaking as we use it together with drf-yasg

basically allauth is not really drf friendly and dj-rest-auth breaks all drf-yasg shemas

time for a big refactor?

**Comment by derek-adair** [comment]
This issue is a good feature request.

@pennersr how do you feel about moderating off topic comments?  Pretty uncommon in your project but this issue is full of it.

**Comment by ayushin** [comment]
One should check django-otp and django-df-auth

**Comment by derek-adair** [comment]
If django-allauth integrates with that out of the box this can probably be closed and mentioned in the docs as the recommended solution for such a thing.

**Comment by olarcher** [comment]
@derek-adair I would argue that a lot more people use dj-rest-auth than django-df-auth, so it would be great to have a solution that works with dj-rest-auth as well.

**Comment by derek-adair** [comment]
Not sure what you are arguing.  I'm dispassionate about which of these allauth would support.

**Comment by josylad** [comment]
Hello, 
Can anyone who has successfully integrated django OTP and allauth share some code samples? 
I want to send OTP on user login, redirect them to OTP confirmation page, verify the OTP and then send them to their dashboard. 

This system works in allauth right now, except for the login OTP part. @ayushin @webpn @derek-adair 

P.S. I am using Django template, not DRF.

**Comment by pennersr** [comment]
@josylad Just to be sure I fully understand, @josylad, what you are referring to -- sending a OTP on login -- is something different from using a OTP for email verification, right? So, I think there are 2 distinct feature requests here:

- Being able to confirm email addresses with a simple code (instead of following a link as is now).
- Using your email as a 2nd factor, so that on each login you are sent a OTP that you will have to confirm.

**Comment by josylad** [comment]
> @josylad Just to be sure I fully understand, what you are referring to -- sending a OTP on login -- is something different from using a OTP for email verification, right? So, I think there are 2 distinct feature requests here:
> 
> * Being able to confirm email addresses with a simple code (instead of following a link as is now).
> * Using your email as a 2nd factor, so that on each login you are sent a OTP that you will have to confirm.

Yes, you are correct. @pennersr

**Comment by josylad** [comment]
> @josylad See #3550 -- feel free to provide your use case specifics there.

Done, thanks.

**Comment by francosbenitez** [comment]
This would be awesome.

**Comment by krystofbe** [comment]
I've been following the discussion on implementing a one-time code for email verification in django-allauth, and I'd like to offer a summary and some thoughts for further consideration.

In modern web applications, it's becoming increasingly common to verify a user's email address through a one-time code, as opposed to the traditional confirmation link. This approach ensures real-time verification of the email address before the completion of the registration process. It's particularly useful in scenarios where immediate verification is crucial and adds an additional layer of security.

A key point for discussion is whether entering this verification code should be mandatory or configurable via Django settings. This raises questions about how it would interact with the existing functionality of django-allauth.

**Comment by pennersr** [comment]
> A key point for discussion is whether entering this verification code should be mandatory or configurable

Definitely configurable, as allauth is used in all sorts of context, and mandatory email verification by code is not applicable everywhere.

**Comment by pennersr** [comment]
I would like to see this implemented in allauth. For that to happen, we need to
make a few decisions.

When email verification by code is enabled, do we still send the link as well?
Or, do we need to support three options for verification: link only, link +
code, code only.

You could argue that one reason for sending the code is that users are trained
not to click on links in mails, so sending a link and code in one and the same
email does not make sense. But, I would like to know what your thoughts are, and
what is most commonly required.

Any input is welcome.

**Comment by PabloCastellano** [comment]
@pennersr My two cents:

I am eager to see this feature implemented in django-allauth. In my case, I would simply configure it to only send the code. Having the link sent along with the code seems unnecessary to me. The code-based solution is preferable because it allows me to easily switch between devices; I can open my email on my phone and enter the code on my laptop without losing focus on the signup process.

Thank you for your work! By the way, I've just become your 20th sponsor ❤️

**Comment by pennersr** [comment]
>  I would simply configure it to only send the code

I concur -- I envision a simple setting, something along the lines `ACCOUNT_EMAIL_VERIFICATION_BY_CODE = True` to flip the current behavior over from sending links to using codes. 

> I've just become your 20th sponsor

@PabloCastellano Much appreciated, that really helps -- in any case, this topic will get traction in the upcoming future. Thanks!

**Comment by PabloCastellano** [comment]
@pennersr Is there anything I can help you with to ship this feature faster?

**Comment by pennersr** [comment]
Work is currently ongoing to get webauthn support in, and I do expect to be able to look into this after that, but I cannot give any ETAs. Unless anybody is willing to contribute this feature, for me the only way to make it ship faster is more sponsors as that implies more time can be dedicated towards allauth development.

**Comment by pennersr** [comment]
This is up for testing over at #4040 4040

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2061
