### ISSUE TITLE
New provider SteadyHQ.com

### ISSUE THREAD

**Issue by TobitRE** [pennersr/django-allauth#2064]
Hi,

first, thank you all for this great project! I have used it several times and it works great!

Now I want to add a new provider [SteadyHQ.com](https://www.steadyhq.com).
I have made a [fork](https://github.com/TobitRE/django-allauth/tree/Dev-steadyhq.com).

Unfortunately I stuck with the implementation :(

You can finde the documentation of the [SteadyHQ API here](https://developers.steadyhq.com/#introduction).

I have create a new [provider](https://github.com/TobitRE/django-allauth/tree/Dev-steadyhq.com/allauth/socialaccount/providers/steadyhq) and create the social account with my client ID and Security Code.

Additional I have add the following code to my settings.py:
`SOCIALACCOUNT_PROVIDERS = {
    'steadyhq': {
      'SCOPE': ['read']
    }
}`

For testing I have to use [ngrok](https://ngrok.com) because it is not possible to use "localhost:XXXX" as redirect url. Now the redirect URL looks like http://personallink.ngrok.io/accounts/steadyhq/login/callback/

If I try to login with SteadyHQ.com I come to the access grant page from SteadyHQ.com. I give my APP full access and get following callback:
http://personallink.ngrok.io/accounts/steadyhq/login/callback/?code=SomeSpezialCode&state=SomeSpecialState

BUT my site show an "Social Network Login Failure. An error occurred while attempting to login via your social network account.".

I have no Idea how to deal with it and get the other parts to work...

I hope someone can help my with than.

Thank you very much!

Best regards

Tobit

**Comment by pennersr** [comment]
You'll likely need to step through the "complete_login" method, see your views.py. It's really not feasible for me assist in debugging, so I will have to close this issue. If you manage to complete the provider, feel free to file a PR.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2064
