### ISSUE TITLE
Feature request: add ORCID as a new provider

### ISSUE THREAD

**Issue by hsiaoyi0504** [pennersr/django-allauth#2066]
It would be pretty awesome if django-allauth support ORID. That will benefit researcher society a lot.

https://orcid.org/
> ORCID provides a persistent digital identifier that distinguishes you from every other researcher and, through integration in key research workflows such as manuscript and grant submission, supports automated linkages between you and your professional activities ensuring that your work is recognized.

**Comment by hsiaoyi0504** [comment]
Oops, I didn't find that it's listed in https://django-allauth.readthedocs.io/en/latest/index.html
but not listed in https://www.intenct.nl/projects/django-allauth/.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2066
