### ISSUE TITLE
Disconnect hook for deleting account

### ISSUE THREAD

**Issue by commadelimited** [pennersr/django-allauth#207]
We're using AllAuth for our app and it's working great so far. As we work towards our 1.0 release we'd like a user to be able to completely delete any trace of their account. We're not using any sort of confirmation for signup other than the "sign in to twitter" button on the front page of the site. Our intent is to have this be as seamless and pain-free as possible.

The only mention I can find of disconnecting an account is in conjunction with a DisconnectForm which requires an email address. We just want the user to be able to click a button, see a confirmation page, then click yes or no.

Is something like this already built in? If so, where do I find it?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/207
