### ISSUE TITLE
OpenID for Yahoo broken unless `next` parameter has value

### ISSUE THREAD

**Issue by pydolan** [pennersr/django-allauth#2072]
As described in [this SO post](https://stackoverflow.com/questions/47418261/i-cant-get-openid-to-work-openid-consumer-consumer-protocolerror-parameter-ne), an error appears "Parameter next not in return_to URL".  

It appears that the fix for issue #1523 introduced this bug.  I'll submit a PR to fix this

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2072
