### ISSUE TITLE
Cancel and Redirect to Custom URL Social Login

### ISSUE THREAD

**Issue by rmad17** [pennersr/django-allauth#2075]
I am trying to login via social login. However in some cases I need to stop the login and redirect to custom page if some specific validations fail. I have written a custom adapter and using `pre_social_login` to handle all these customizations. However raising an ImmidiateHttpResponse or a `redirect` does not help me redirect to my custom page.

**Comment by rmad17** [comment]
I figured the mistake I did was the way I was raising the exception. It has to be 
```python
raise ImmidiateHttpResponse(redirect('some_url_name'))
```

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2075
