### ISSUE TITLE
Django allauth Social application extra data

### ISSUE THREAD

**Issue by neridoro** [pennersr/django-allauth#2076]
so I have set up Django allauth on my Django project and connected to Instagram, when doing so I have now on my admin site Social accounts category with my account registers, all good so far

on the lower page, I can see a field called extra data, how can I put it inside the normal Users database so I can use it to take how many followers I got out of the extra data? can I request the followers with the Token i have maybe?

![screenshot_8](https://user-images.githubusercontent.com/42244232/43997389-46cff85e-9de2-11e8-8af2-548b671c9ad2.png)

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2076
