### ISSUE TITLE
Email Verification by only the requested user

### ISSUE THREAD

**Issue by bilgigouda** [pennersr/django-allauth#2080]
I am not sure if this was intentional, but any logged in users can verify by clinking on the email verification link

User 1 when logged in and having access to verification email of User 2 can click on the link and verify the email. Even if User 1 is signed out, after clicking on verification link on User 2, and redirected to login page, User 1 can login and verify

Does not look like a security issue, because goal is to verify email, does not matter who logs in to verify that email. But, maybe restrict who can verify the email?

**Comment by github-account-because-they-want-it** [comment]
Noobs talking about security 💤🛌😴

**Comment by bilgigouda** [comment]
Sorry, I was using a source from someone who was using this package and made some changes. This is not an issue. 

The default allauth behaviou does not ask to login to verify the email address. 

My apologies again, I am closing the issue

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2080
