### ISSUE TITLE
Use email in the social account as email and skip signup form altogether

### ISSUE THREAD

**Issue by tcalasans** [pennersr/django-allauth#2081]
Whenever my users sign up using Microsoft Outlook, after the sign in process, the user is prompted for the email in a form. Is there a way to prevent that and, instead, use the microsoft email that is returned by the social provider as the user's email?? I am currently using sign in using email+password or social login, and giving the user the ability to register with a different email than the one he signed in can pose a huge breach, as I also restrict domains.

Thank you.

**Comment by pennersr** [comment]
Closing -- dated.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2081
