### ISSUE TITLE
Postgres Native JSONField

### ISSUE THREAD

**Issue by JayTurnr** [pennersr/django-allauth#2083]
https://github.com/pennersr/django-allauth/blob/9c31b6576628e9d6971349abc189dfd613d6591e/allauth/socialaccount/models.py#L102

If it possible to make this use Postgres native JSONField if the user is on Postgres?
https://docs.djangoproject.com/en/2.1/ref/contrib/postgres/fields/#jsonfield

**Comment by jleclanche** [comment]
Dupe of #598.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2083
