### ISSUE TITLE
LinkedIn - Changes to OAuth 2.0 URLs

### ISSUE THREAD

**Issue by thomascenni** [pennersr/django-allauth#2086]
LinkedIn flow is broken due to these changes (from August 6, 2018):
https://developer.linkedin.com/blog/posts/2018/redirecting-oauth-uas

So: 
access_token_url = 'https://api.linkedin.com/uas/oauth2/accessToken'
authorize_url = 'https://www.linkedin.com/uas/oauth2/authorization'

need to be changed to:
access_token_url = 'https://www.linkedin.com/oauth/v2/accessToken'
authorize_url = 'https://www.linkedin.com/oauth/v2/authorization'

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2086
