### ISSUE TITLE
How to have django-allauth only generate necessary table columns when login via email

### ISSUE THREAD

**Issue by yccheok** [pennersr/django-allauth#2089]
Currently, we would like to let user

 - Login via email and password
 - Login via Google

The implementation of this project pretty much suit our requirement.

https://github.com/wsvincent/djangox

However, when we exam the generated DB table, it contains a lot of unnecessary fields

     id | password |  last_login  | is_superuser | username | first_name | last_name | email | is_staff | is_active | date_joined

----------

We refer to this example too

https://docs.djangoproject.com/en/2.1/topics/auth/customizing/#a-full-example

It allows Login via email and password (But not with Google)

The generated table is pretty minimalist

    id | password | last_login | email | is_active | is_admin

We tried to replace custom user model (inherited from `AbstractUser`) from djangox with custom user model (inherited from `AbstractBaseUser`) from official Django guideline.

However, we get the following error

    django_1     | Traceback (most recent call last):
    django_1     |   File "manage.py", line 15, in <module>
    django_1     |     execute_from_command_line(sys.argv)
    django_1     |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    django_1     |     utility.execute()
    django_1     |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    django_1     |     django.setup()
    django_1     |   File "/usr/local/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    django_1     |     apps.populate(settings.INSTALLED_APPS)
    django_1     |   File "/usr/local/lib/python3.6/site-packages/django/apps/registry.py", line 120, in populate
    django_1     |     app_config.ready()
    django_1     |   File "/usr/local/lib/python3.6/site-packages/django/contrib/admin/apps.py", line 24, in ready
    django_1     |     self.module.autodiscover()
    django_1     |   File "/usr/local/lib/python3.6/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    django_1     |     autodiscover_modules('admin', register_to=site)
    django_1     |   File "/usr/local/lib/python3.6/site-packages/django/utils/module_loading.py", line 47, in autodiscover_modules
    django_1     |     import_module('%s.%s' % (app_config.name, module_to_search))
    django_1     |   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    django_1     |     return _bootstrap._gcd_import(name[level:], package, level)
    django_1     |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
    django_1     |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
    django_1     |   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
    django_1     |   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
    django_1     |   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
    django_1     |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    django_1     |   File "/app/users/admin.py", line 5, in <module>
    django_1     |     from .forms import CustomUserCreationForm, CustomUserChangeForm
    django_1     |   File "/app/users/forms.py", line 6, in <module>
    django_1     |     class CustomUserCreationForm(UserCreationForm):
    django_1     |   File "/usr/local/lib/python3.6/site-packages/django/forms/models.py", line 266, in __new__
    django_1     |     raise FieldError(message)
    django_1     | django.core.exceptions.FieldError: Unknown field(s) (username) specified for CustomUser

I was wondering, how can we have a minimalist table, when using `django-allauth`, to implement login via email?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2089
