### ISSUE TITLE
format_email_subject and UnicodeDecodeError

### ISSUE THREAD

**Issue by XMLSDK** [pennersr/django-allauth#209]
If `settings.py` is UTF-8 encoded (`# encoding: utf-8`), and `EMAIL_SUBJECT_PREFIX` is assigned non-ascii characters, sending confirmation email will raise error: `UnicodeDecodeError: 'ascii' codec can't decode...`

Site Name may also be the source of error:
site-packages/allauth/account/utils.py in format_email_subject:

```
def format_email_subject(subject):
    prefix = app_settings.EMAIL_SUBJECT_PREFIX
    if prefix is None:
        site = Site.objects.get_current()
        prefix = "[{name}] ".format(name=site.name) ... # UnicodeDecodeError 
    return prefix + unicode(subject)
```

It's strange that my settings.EMAIL_SUBJECT_PREFIX is actually not None.

Edit: I then find that I had not set `settings.ACCOUNT_EMAIL_SUBJECT_PREFIX`, and allauth does not use `settings.EMAIL_SUBJECT_PREFIX`. Still `site.name` encoding should be handled.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/209
