### ISSUE TITLE
Access user data inside pre_social_login

### ISSUE THREAD

**Issue by rammanoj** [pennersr/django-allauth#2092]
I am not sure if it is possible. I am trying to access the email of the user signed using google at the pre_social_login adapter. But, I don't know how to access it, or I am not sure if it is possible to access email there. So, Is there any way to access the user information in pre_social_loign adapter ??

Presently, I referred through the documentation but I am unable to find any relevant information to it.\

According to the documentation at https://django-allauth.readthedocs.io/en/latest/advanced.html?highlight=adapters#custom-redirects

It is possible to use `request.user`. As in code sample given below, they used `request.user` in get_login_redirect_url adapter. But When I try to use `request.user` in the pre_social_login adapter it is giving me an 'AnonymousUser' ??

pre_social_login adapter-

    def pre_social_login(self, request, sociallogin):
        user = sociallogin.user
        if user.id:
            return
        try:
            existing_user = User.objects.get(email=request.user.email) # if user is logging for first time, its giving an anonymous user
        except ObjectDoesNotExist:
            pass
        if not user.id:
            print("not in sociallogin so connecting")
            sociallogin.connect(request, existing_user)

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2092
