### ISSUE TITLE
Password reset key subject partially uncustomizable

### ISSUE THREAD

**Issue by shacker** [pennersr/django-allauth#2095]
What appears in the password_reset_key_subject.txt template:

`{% blocktrans %}Password Reset E-mail{% endblocktrans %}`

What appears in generated emails:

`Subject: [My Site Display Name] Password Reset E-mail`

"[My Site Display Name]" is inserted by allauth, and cannot be overridden or removed at the template level.

Can that variable be moved into the template layer for full customizability? Thanks.

**Comment by TheBoroer** [comment]
I know this is an old issue but if anyone's still looking to fix this, add/set `ACCOUNT_EMAIL_SUBJECT_PREFIX=""` in your `settings.py`.

It's probably worth mentioning too that it's super useful to have a quick browse through all the settings vars available: https://django-allauth.readthedocs.io/en/latest/configuration.html

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2095
