### ISSUE TITLE
Google EmailAddresses are all primary by default

### ISSUE THREAD

**Issue by sssbox** [pennersr/django-allauth#210]
I've finally gotten around to looking into an error that pops every once in a while:

``` python
MultipleObjectsReturned: get() returned more than one EmailAddress
-- it returned 2! Lookup parameters were 
{'user': <User: <redacted>>, 'primary': True}
```

I think I found the cause:

https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/providers/google/views.py#L42

and

https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/models.py#L156

This is probably not normally an issue because I'm guessing verified_email is usually only one item and most people probably don't add multiple social accounts. But when someone adds a google account as a social account to an existing account I believe it still gets blindly saved as the primary email address.

I can fix this but wanted to know which solution you thought was best:
1. Add primary dynamically on save (with no extra queries)
   1. In the google provider, mark all as non-primary.
   2. In SocialLogin.save(self): `new_account = not SocialLogin.is_existing()` before saving anything.
   3. Pass `new_account` to `_save_email_addresses`
   4. Add `has_primary = False` variable at the top
   5. If the `user.email` isn't in the list of email addresses to save and `new_account` add it as the primary email address, otherwise add it as non-primary, set `has_primary = True`
   6. In the loop of email addresses, `if new_account and not has_primary:` set the current address (most likely only address) to primary and set `has_primary = True`
2. Add primary dynamically on save (with extra query)
   - Same as 1. except don't assume that only new accounts need primary email addresses:
     - Skip 1.2 and 1.3
     - Change 1.4 to `has_primary = EmailAddress.objects.filter(user=user, primary=True).exists()`
3. Set all to non-primary and call it a day.

For both 1 and 2 it is probably necessary to add some code to try to make sure user.email is the same as whatever the current primary email address is.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/210
