### ISSUE TITLE
Facebook js_sdk "data-" attributes for login button

### ISSUE THREAD

**Issue by ulgens** [pennersr/django-allauth#2100]
Hello everyone,

I want to use Facebook's "continue with" button from https://developers.facebook.com/docs/facebook-login/web/login-button/ with " Show Friends' Faces" parameter. Facebook's JS code provides this functionality with `data-show-faces="true"` attribute.

I couldn't find a way to use Facebook's js_sdk login button code from link above with allauth. I can embed Facebook's button on my page, get permission approval from Facebook but in the end, it doesn't trigger anything on allauth. I tried to customize button with parameters from providers_media_js but nothing has changed.

I found this very similar question in email list but it has no answer: https://groups.google.com/forum/#!topic/django-allauth/hxCnW5kQMxU

And an additional question, i couldn't understand the difference between `method="js_sdk"` and `method="oauth2"` options. I'm prettry sure things are changing in background what does this change provide to developer/user?

**Comment by ulgens** [comment]
Anybody?

**Comment by derek-adair** [comment]
Probably close this??

I could be wrong, but I don't think this is in the scope of AllAuth.  For example, this link clearly states, "The Login button is only designed to work in connection with the [JavaScript SDK](https://developers.facebook.com/docs/facebook-login/login-flow-for-web/)" and points to you "should follow the [login flow guide for that type of app](https://developers.facebook.com/docs/facebook-login/) instead".

**Comment by pennersr** [comment]
Closing, also dated.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2100
