### ISSUE TITLE
Redirect in adapters

### ISSUE THREAD

**Issue by rammanoj** [pennersr/django-allauth#2102]
I closed the signup in for my site. So whoever signs up it is getting redirected to `/accounts/social/signup` page. Is there any way to make a custom redirect there. I even tried to make a custom redirect in adapter `pre_social_login` but I it is not getting redirected. So, is there any way to redirect in pre_social_login adapter or override  `/accounts/social/signup` to some other URL. I tried by importing and extending views. Even I am unable to solve it

**Comment by pennersr** [comment]
See this in the socialaccount adapter:
![image](https://user-images.githubusercontent.com/201022/70896732-8f4d2b00-1ff1-11ea-8636-660104d15b0a.png)

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2102
