### ISSUE TITLE
User not able to sign up if someone else tried to add their email to an account

### ISSUE THREAD

**Issue by treyhunner** [pennersr/django-allauth#2103]
On my website, someone attempted to add one of my email addresses to their account. I don't know if this was by mistake or if they were seeing whether they could somehow gain access to my account this way.

This was an email address that I had not yet associated with my account, but that I'd like to associate with my account.

Unless an admin manually logs in and deletes the unverified email account from the account that attempted to add it, that email address cannot be added to another account and cannot be used to register.

I realize that this bug may be seen as something to resolve outside the scope of django-allauth. I do think the documentation should probably address the recommended path for resolving this situation gracefully though.

Thoughts on whether this could be fixed within allauth itself and what I should do in the meantime?

**Comment by codescribblr** [comment]
On a related note, if the user that added your email address to their account has another verified email address, they can actually login using _your_ email address (unverified in their account) and their password. It still logs them into their own account, but this seems problematic at best.

**Comment by 9mido** [comment]
Linking #2699 and #2360 and the solutions to this issue contained in both issue comment sections. The solutions in the comments needs PRs with configurable settings. 

Related issue: #2627

**Comment by pennersr** [comment]
> Unless an admin manually logs in and deletes the unverified email account from the account that attempted to add it, that email address cannot be added to another account and cannot be used to register.

This is not true. If someone adds your email to their account, by doing so, that person gives you full access to their account. Meaning, you as a user can use the password reset functionality to take over their account and remove the email as you see fit. It does not at all require an admin to fix things. There is really not much you can do here, the email address is the key to the account, and if somebody adds your key to their account you will have access. In this scenario, a user is either sloppy with security, or perhaps intentionally wants to give you ownership of an account, but all in all this works as intended.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2103
