### ISSUE TITLE
Wrong signup text: "you can still change your e-mail address"

### ISSUE THREAD

**Issue by jonashaag** [pennersr/django-allauth#2105]
Scenario: You sign up and end up on the `/confirm-email/` page. It says "you can still change your-email address", with a link to `/email/`. However, the `email` view is password-protected (`login_required`).

My settings:

```py
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_SESSION_REMEMBER = True
ACCOUNT_USERNAME_REQUIRED = False
```

**Comment by derek-adair** [comment]
@jonashaag can you provide relevant templates?  I am not getting this (but it's been 5 years since u submitted this :P)

@pennersr does this seem like something outside of a user config error?

**Comment by pennersr** [comment]
This is valid -- `verified_email_required.html` contains:

```<p>{% blocktrans %}<strong>Note:</strong> you can still <a href="{{ email_url }}">change your email address</a>.{% endblocktrans %}</p>```

**Comment by derek-adair** [comment]
Ah, i see now.  I actually didn't realize there were two distinct templates between `verified_email_required.html` and `verification_sent.html`.

It seems like the logic here could be improved.

**User tries to access a page w/ verified required**
1. If the user is not logged in -> Send to login 
2. If user is logge din -> Serve this page w/ link to emaiol.

OR 

Throw `{% if not user.is_anonymous %}` around that bit and call it good.

**Comment by pennersr** [comment]
The "you can still..." message is only rendered by the `@verified_email_required` decorator, which is not used anywhere, but is only offered to allow your project to close off certain views until you have verified your email. So, that statement "you can still..." is actually correct for this context.

The bug report is about this message appearing in the `/confirm-email/` view -- that is not correct, perhaps that message was there in 2018, but these days it is not. Closing.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2105
