### ISSUE TITLE
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION does not log the user in after confirmation since 0.37

### ISSUE THREAD

**Issue by bastbnl** [pennersr/django-allauth#2106]
First of all I'd like to thank you and the maintainers for the hard work you're been doing making it easy for me to add social login. 

I just upgraded to `django-allauth==0.37.1` and noticed that users are no longer signed in after confirming their email address, with the `ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION` option set. Instead I end up with the sign-in page, which I was trying to prevent. It used to work on 0.36.

I browsed through the code and found that the `login_on_confirm` expects the user id to be stashed prior to logging the user in (https://github.com/pennersr/django-allauth/blob/0.37.0/allauth/account/views.py#L326). I did not find any reference in the confirmation view that actually stashes the user id. I worked around it by adding the stashing code in the adapter which is specific for the project I'm working on:

```
    def confirm_email(self, request, email_address):

        self.stash_user(
            request,
            user_pk_to_url_str(
                email_address.user
            )
        )
        return super(InviteAccountAdapter, self).confirm_email(request, email_address)
```

Is this correct and intentional? I can think of a PR which eliminates the need for stashing in the custom adapter. I'll be happy to create it.

**Comment by an-dev** [comment]
@pennersr any luck merging this one in? :)

**Comment by pennersr** [comment]
@an-dev No, see: https://github.com/pennersr/django-allauth/pull/2107#issuecomment-437674355

**Comment by bastbnl** [comment]
So I just noticed this comment. I understand your reasoning and your concerns, but what is the best way forward? Closing the issue obviously does not solve the issue itself.  

Let's assume that someone who configures `ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION` to `True` is likely to understand the consequences. That could be achieved via documentation or something that's raised when another flag is not set. From the text on `login_on_confirm`, I understand that the main concern is somebody taking over another persons' account via a link when login confirmation tokens are not dealt with correctly. 

You can't reach a 100% solution here since timing may always be an issue. So I can imagine a couple of solutions:
- Drop the ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION option. Just don't allow it. That's basically what's happening right now, without the flag.
- Keep the ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION option and add another option indicating that the user understands the consequences. Raise an exception when this flag is not set. Obviously, this does not solve any technical issue. 
- Keep the ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION option and mark the confirmation token used once it's used. Also, add expiry to confirmation token. Render a different template when the confirmation token is used or when it's expired. Timing could still be an issue though.
- Keep the ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION option and add additional logic to the confirmation, something like a session key, an IP address, etc.. I can think of multiple reasons why this would introduce new failures, but it may just as well remove a couple of the concerns. 

In this patch I only stashed the user when `LOGIN_ON_EMAIL_CONFIRMATION` has been set, making it a consequence of a configuration option. 

@pennersr  What's the next step fixing this issue?

**Comment by bastbnl** [comment]
Your thoughts? Anything I can do @pennersr?

**Comment by pennersr** [comment]
@bastbnl Before diving into possible solutions, I would like to understand the problem we're trying to solve here. For regular flows, logging in on email confirmation simply works, at least, that is my understanding. As documented in the code, only if browser sessions get lost along the way, things may start breaking down. But, this should really not be the common case.  I would really like to stay away from introducing all sorts of new options, some of which would possibly have security consequences as well, unless there is a good reason.

**Comment by bastbnl** [comment]
@pennersr Well, the regular flow did not work for me and I guess that's where the problem is. The user is simply not logged in after confirming the email via GET. I tested this on a desktop.

**Comment by pennersr** [comment]
@bastbnl It would be helpful to know why the regular flow did not work for you. If there is something wrong there this needs to be fixed, let's analyse that first. FWIW, there is a test case covering this: test_login_on_confirm_uuid_user

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2106
