### ISSUE TITLE
session expired after browser close when logged in with account_login

### ISSUE THREAD

**Issue by wizbaselc** [pennersr/django-allauth#2111]
Hi,

There is no problem with social login which means the session remains even the browser re-opened.
But when I do login with email and password directly to my site by using account_login url, the session is expired after re-open browser.

Is there a way to keep session for direct logged in user after browser re-open?

**Comment by derek-adair** [comment]
1. The "remember me" checkbox works for me with direct account login.
2. This issue makes me suspect that social accounts are always stored in a django session, which is concerning.  I don't have a social login app ready to test this... but if the "remember me" works as intended this can be closed.

**Comment by pennersr** [comment]
Closing as dated.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2111
