### ISSUE TITLE
Security: ACCOUNT_LOGIN_ATTEMPTS_TIMEOUT is not respected

### ISSUE THREAD

**Issue by BernhardPosselt** [pennersr/django-allauth#2119]
I'm using the latest version of allauth with default configuration and I can successfully log in after making 5 failed login attempts.

**Comment by rtiwarihr** [comment]
I am facing the same issue as well. Here is param from my settings file.

ACCOUNT_LOGIN_ATTEMPTS_LIMIT = 5
ACCOUNT_LOGIN_ATTEMPTS_TIMEOUT = 3600

**Comment by pennersr** [comment]
For this to work you need a cache backend, which is where it stores the login state:

![image](https://user-images.githubusercontent.com/201022/70895222-d1c13880-1fee-11ea-8c14-8b1e5a5d61ba.png)

Given that you mention it does not work with the "default configuration" -- it is likely due to this.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2119
