### ISSUE TITLE
Unable to login with provided credentials Django 2.1.1

### ISSUE THREAD

**Issue by sukianto** [pennersr/django-allauth#2120]
All working fine when using Django 1.11.xx after update to django 2.1.1 social and email login not working. For email I can fix it using my own `authentication_backends`, overriding the allauth backend
and modify it to `def authenticate(self, request, **credentials):` just add the `request` word. But social login have problem that I can't fix it, about the allowed_hosts param, even I already set the ALLOWED_HOSTS in Django settings.

**Comment by pennersr** [comment]
This is a bit too little to go on. Will have to close it. If you find anything concretely wrong in allauth, feel free to reopen.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2120
