### ISSUE TITLE
ACCOUNT_AUTHENTICATION_METHOD is ignored, always logs in for username or email

### ISSUE THREAD

**Issue by jhdulaney** [pennersr/django-allauth#2121]
Hi, there!

No matter what I set ACCOUNT_AUTHENTICATION_METHOD to, it always allows login via username or email.

In __init__ of LoginForm, it even properly tests through the if then statements.  However, this gets ignored further down the line.

**Comment by jhdulaney** [comment]
Nevermind

**Comment by nkay08** [comment]
How did you fix this issue?
I currently have the same problem

**Comment by devraj** [comment]
`settings.py` should have the following set:

```python
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'
```

see [this Stackoverflow thread](https://stackoverflow.com/questions/23956288/django-all-auth-email-required)

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2121
