### ISSUE TITLE
New Blizzard login

### ISSUE THREAD

**Issue by jleclanche** [pennersr/django-allauth#2125]
The current `battlenet` provider is getting shut down on January 6, 2019. There's a migration in place.

https://develop.battle.net/documentation
https://develop.battle.net/documentation/guides/migration-guide

I think the migration path for allauth is to implement a new provider called "blizzard" with the updated URLs etc, and deprecate the battlenet provider in favour of that one.

I'll probably do it unless someone else wants to.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2125
