### ISSUE TITLE
In token generator, reference to `user.email` should honor customizations to USER_MODEL_EMAIL_FIELD

### ISSUE THREAD

**Issue by bpartridge** [pennersr/django-allauth#2131]
https://github.com/pennersr/django-allauth/blob/bd1d4a83b2490b7929310f9301ae8a1d4db7d54a/allauth/account/forms.py#L42

**Comment by pennersr** [comment]
Closing -- outdated.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2131
