### ISSUE TITLE
can you update LINE social login from ver1 to ver 2 ? 

### ISSUE THREAD

**Issue by gooslab** [pennersr/django-allauth#2134]
django-allauth/allauth/socialaccount/providers/line/views.py

class LineOAuth2Adapter(OAuth2Adapter):
    provider_id = LineProvider.id
    access_token_url = 'https://api.line.me/v1/oauth/accessToken'
    authorize_url = 'https://access.line.me/dialog/oauth/weblogin'
    profile_url = 'https://api.line.me/v1/profile'

Line API updated : 
access_token_url = 'https://api.line.me/oauth2/v2.1/token'
access_token_url = 'https://api.line.me/v2/oauth/accessToken'
profile_url = 'https://api.line.me/v2/profile'

> https://developers.line.me/en/reference/social-api/

**Comment by CaptainGoos** [comment]
i modified source like that. 

**allauth/socialaccount/providers/line/provider.py**
![image](https://user-images.githubusercontent.com/6458969/47254097-6251c680-d487-11e8-87b8-f14e66eded50.png)


**allauth/socialaccount/providers/line/views.py**
![image](https://user-images.githubusercontent.com/6458969/47254284-b4481b80-d48a-11e8-895d-f1b6ae9f2a15.png)

**Comment by pennersr** [comment]
Line is on v2 these days.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2134
