### ISSUE TITLE
Page not found  django2.1

### ISSUE THREAD

**Issue by zhibeen** [pennersr/django-allauth#2135]
i use the django2.1 and python3.6

i set the urls.py like this

from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admins/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
]

i bowse the http://127.0.0.1:8000/accounts

the page shows that 

Using the URLconf defined in mysite.urls, Django tried these URL patterns, in this order:

^admins/
^accounts/
The current path, accounts, didn't match any of these.

i don't find the error

do the django2.1 use the django-allauth ?

the error:

Using the URLconf defined in mysite.urls, Django tried these URL patterns, in this order:

admin/
accounts/ ^ ^signup/$ [name='account_signup']
accounts/ ^ ^login/$ [name='account_login']
accounts/ ^ ^logout/$ [name='account_logout']
accounts/ ^ ^password/change/$ [name='account_change_password']
accounts/ ^ ^password/set/$ [name='account_set_password']
accounts/ ^ ^inactive/$ [name='account_inactive']
accounts/ ^ ^email/$ [name='account_email']
accounts/ ^ ^confirm-email/$ [name='account_email_verification_sent']
accounts/ ^ ^confirm-email/(?P<key>[-:\w]+)/$ [name='account_confirm_email']
accounts/ ^ ^password/reset/$ [name='account_reset_password']
accounts/ ^ ^password/reset/done/$ [name='account_reset_password_done']
accounts/ ^ ^password/reset/key/(?P<uidb36>[0-9A-Za-z]+)-(?P<key>.+)/$ [name='account_reset_password_from_key']
accounts/ ^ ^password/reset/key/done/$ [name='account_reset_password_from_key_done']
accounts/ ^social/
accounts/ ^github/
The current path, accounts/profile/, didn't match any of these.

**Comment by pennersr** [comment]
There is no /accounts/ view in allauth, so this is to be expected. As for the profile URL, see: https://docs.djangoproject.com/en/3.0/ref/settings/#login-redirect-url

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2135
