### ISSUE TITLE
MockedResponse doesn't have text

### ISSUE THREAD

**Issue by orblivion** [pennersr/django-allauth#214]
I just pulled the latest allauth, and some of my tests failed. These are tests that run a view that call on an allauth view with a mocked response. At some point it calls `resp.text` which fails. I saw that you replicated Requests' `json` method in a crude way. Perhaps you want to do the same for text:

https://github.com/kennethreitz/requests/blob/master/requests/models.py#L582

Just casting self.content to unicode may be sufficient.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/214
