### ISSUE TITLE
Group settings in settings.py

### ISSUE THREAD

**Issue by makerGeek** [pennersr/django-allauth#2141]
Since allauth has many settings, I suggest to group them in a single dict [like this](https://github.com/AltSchool/dynamic-rest#settings) in settings.py in order for the file not to become messy.

**Comment by pennersr** [comment]
We would be breaking a lot of deployments for negligible gains.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2141
