### ISSUE TITLE
[twitter] Social Network Login Failure - provider.get_auth_params(request,action) returns {}

### ISSUE THREAD

**Issue by derek-adair** [pennersr/django-allauth#2143]
Django: 2.0.8
Python: 3.5

Having trouble integrating w/ Twitter and I suspect a bug.   I've integrated w/ google no problemo and i'm stuck on twitter.  I'm not 100% on how the flow works yet but i've started some debugging efforts that have been unfruitful.

**Comment by derek-adair** [comment]
[Relevant bit that is returning {}](https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/providers/oauth/views.py#L67)

**Comment by derek-adair** [comment]
Inspecting w/ pdb gives me clues;

1) client.errors = No request token saved for "api.twitter.com"

2) client.consumer_key and client.consumer_secret both have the correct values.  
3) client.request_token is in fact blank

**Comment by woutor** [comment]
Same issue here..

**Comment by iarp** [comment]
Is this still an issue for you? I just created a twitter app to test and no issue here.

**Comment by woutor** [comment]
Thanks for the follow up. I can confirm that Twitter login works on a live site. Unfortunately not on localhost with a callback url like https://www.example.localhost/social/twitter/login/callback/. Apparently that's [an issue](https://twittercommunity.com/t/why-cant-i-use-localhost-as-my-oauth-callback/708) related to Twitter itself.

**Comment by derek-adair** [comment]
This was on a publicly accessible IP/domain.  So not related to that localhost issue.

I've actually swapped auth apps to [djoser ](https://github.com/sunscrapers/djoser)(i'm lazy and it works w/ JWT out of the gate), and had similar problems... Very likely i didn't have my redirect url match EXACTLY.

Closing because almost certainly a config issue.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2143
