### ISSUE TITLE
Slack Adapter Fix

### ISSUE THREAD

**Issue by dustinnewman** [pennersr/django-allauth#2144]
I think the `SlackOAuth2Adapter` could use an endpoint other than `auth.test` for Slack. An app I'm working on uses Slack integration and the `auth.test` endpoint does not contain an `email` field. This will result in the `SlackProvider` receiving null for email (see [here](https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/providers/slack/provider.py#L28)). Because of this, any app using Slack integration will only be able to support one user authenticated through Slack, because the second user will also have an email set to null and this will throw an error because the null email is already "taken."

For reference, I find the [`user.identity`](https://api.slack.com/methods/users.identity) method more helpful!

Let me know if I simply misunderstood something!

**Comment by pennersr** [comment]
Please file a pull request for things that you find missing...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2144
