### ISSUE TITLE
Soon will no longer be able to load Facebook Customer Chat Plugin

### ISSUE THREAD

**Issue by jeffbowen** [pennersr/django-allauth#2147]
Facebook [is changing](https://developers.facebook.com/docs/messenger-platform/discovery/customer-chat-plugin/sdk#install) how you must load the JS SDK if you want to be able to use the Customer Chat Plugin. It requires using `https://connect.facebook.net/en_US/sdk/xfbml.customerchat.js` as the `js.src` argument instead of `https://connect.facebook.net/en_US/sdk/sdk.js`. If you use the latter, the Customer Chat Plugin soon will no longer load.

As such, there should be a way to specify this such that it's reflected in https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/providers/facebook/static/facebook/js/fbconnect.js#L51.

Maybe a setting in the Facebook section of `SOCIALACCOUNT_PROVIDERS` like `JS_SDK_SRC` or `ALLOW_CUSTOMER_CHAT_PLUGIN`?

There's not currently a date as to when the Customer Chat Plugin will no longer load without this change but they're warning about it in the Console on any page loading the Customer Chat Plugin.

```
#  The CustomerChat plugin will soon be removed from the main Facebook SDK.
#  To continue using it please use the correct SDK URL.
#  For more details see https://developers.facebook.com/docs/messenger-platform/discovery/customer-chat-plugin/sdk
```

P.S. If testing, be aware, the Customer Chat Plugin currently doesn't work at all in Safari 12 (Facebook's own issue).

**Comment by MhjnSamir** [comment]
How to change js.src data  of facebook customer chat plugin? Please recommend me the location of file to edit it .

**Comment by pennersr** [comment]
`fbconnect.js` has this line:

`js.src = '//connect.facebook.net/' + opts.locale + '/sdk.js'`

Here, `opts` is being filled over at `provider.py`: see `fb_data = {...}`.

So you could add `sdkUrl` to `fb_data`.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2147
