### ISSUE TITLE
Social Sign In for existing local user causes confusion (suggested solution):

### ISSUE THREAD

**Issue by arctelix** [pennersr/django-allauth#215]
If an existing local user tries to sign with a social account and the social email or user name conflicts with the local user they will not be able to proceed unless they create a new user by providing a unique username & email.  I think this will be confusing for users and have many new accounts created unintentionally. The flowing would seem to make more sense:

Upon social log in: First check to see if the social email & or username are already assigned to a user.  If so, confirm that the user intended to link this social account to their local account with a simple yes no form.  If yes add it to the user's connections and log them in.  If no, redirect to the social sign up form where they can create a new local user.

Does this make sense? If so i would be happy to work on it.

**Comment by babus** [comment]
@dgmdan Your solution works! But just to be mentioned there a huge security hole is introduced as from allauth docs, http://django-allauth.readthedocs.org/en/latest/providers.html#facebook

"It is not clear from the Facebook documentation whether or not the fact that the account is verified implies that the e-mail address is verified as well. For example, verification could also be done by phone or credit card. To be on the safe side, the default is to treat e-mail addresses from Facebook as unverified." 

Saying so, I can signup in facebook with your email ID or change my email to yours in facebook and login to the website to get access to your account.

**Comment by lacabra** [comment]
Incorporating @babus observation to the back and forth on [this other related thread](http://stackoverflow.com/questions/19354009/django-allauth-social-login-automatically-linking-social-site-profiles-using-th), I came up with [the following adapter.py](http://stackoverflow.com/questions/19354009/django-allauth-social-login-automatically-linking-social-site-profiles-using-th/35204927#35204927) to address the issue at hand.

``

**Comment by RobertoMaurizzi** [comment]
Update: it looks that now Facebook guarantees that all emails returned are verified (unverified ones won't be returned), from: https://stackoverflow.com/questions/14280535/is-it-possible-to-check-if-an-email-is-confirmed-on-facebook that someone linked under @lacabra post on SO.

At this point using account.connect() instead of redirecting using the ImmediateHttpResponse exception logs the user in *and* display a warning message about what happened.

I was honestly confused by the previous flow, because "Log In" was redirecting to the "Sign Up" flow then throwing an error.

**Comment by EvanZ** [comment]
@RobertoMaurizzi I think they have "guaranteed" it for many years. I don't understand why this project (and django-rest-auth which depends on it) still thinks it's a security issue. The whole point of social authentication is that you have trusted providers to authenticate. If you don't trust FB, what's the point?

**Comment by NourEldin-Osama** [comment]
> I agree that this is confusing for users. Since I'm only using the Facebook and Google providers and I know that these sites verify user email addresses, I've opted to trust the email address I receive from the provider and attach it to any local account with a matching email. I'm doing this by catching the `pre_social_login`signal and logging into the local user if it exists:
> 
> ```
> @receiver(pre_social_login)
> def link_to_local_user(sender, request, sociallogin, **kwargs):
>     email_address = sociallogin.account.extra_data['email']
>     users = User.objects.filter(email=email_address)
>     if users:
>         perform_login(request, users[0], email_verification=app_settings.EMAIL_VERIFICATION)
> ```
> 
> I realize this issue is getting old but hopefully this will help someone.

please can you tell me where to put this code

**Comment by aehlke** [comment]
Facebook does not strictly verify emails

**Comment by aehlke** [comment]
"If you use an email address as the unique credential which identifies each account, your app should verify that the email address associated with the person's Facebook account (and obtained during Facebook Login) is valid. You can do this by creating code in your app to send a verification email to the address obtained after Facebook Login (you will probably need to have this step as part of your regular login system anyway)."

Facebook says we need to verify independently

**Comment by pennersr** [comment]
Closing -- see SOCIALACCOUNT_EMAIL_AUTHENTICATION.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/215
