### ISSUE TITLE
create new rest API for password reset

### ISSUE THREAD

**Issue by prologic-dev** [pennersr/django-allauth#2152]
how can we create create custom API which take key from email id and password1 ,passowrd 2 as parameters to directly reset the password, I am using the angular 6 as frontend and django as backend. I want that both  django and angular are in different folders .and i dont want to use django templates for reset passwod

need a end point that will take key that is received in the email along with password1 and password 2 as parameters

**Comment by stfenjobs** [comment]
https://github.com/jazzband/dj-rest-auth

@prologic-dev   please close this issues  if helped you

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2152
