### ISSUE TITLE
The url "/accounts/confirm-email/" can always be accessed

### ISSUE THREAD

**Issue by ctudoudou** [pennersr/django-allauth#2153]
When I do nothing, I can still access this link normally, although the website will not do anything, but I think this is unreasonable.

Thanks.

**Comment by blueyed** [comment]
What do you suggest?  Should it 404 or error in another way without expected params?

**Comment by pennersr** [comment]
I do not such much harm in this. We could of course start fiddling with the session et al to see if this view should really be accessable, but that has its own issues. So I would rather keep it simple as is...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2153
