### ISSUE TITLE
allauth.account.utils.user_pk_to_url_str doesn't work with Hashid pks

### ISSUE THREAD

**Issue by eli85elle** [pennersr/django-allauth#2156]
Hi, I'm using Hashid for User pk model. This type is just a generated alphanumeric id by encoding my user pk autofield, provided by an open-source library. 
 
Password reset is not working with my Hashid pks because user_pk_to_url view is trying to convert 'a' into the pk_field type:
```
  try:
      pk_field.to_python('a')
      pk = s
  except ValidationError:
      pk = base36_to_int(s)
```

As pk_field is a Hashid instance, the conversion throws the exception like whether it tried to convert 'a' into a number. I think it would be enough to try to convert 's' value into pk_field type instead of 'a':

```
  try:
      pk_field.to_python(s)
      pk = s
  except ValidationError:
      pk = base36_to_int(s)
```
With this, if 's' parameter is '2', even if pk_field is an instance of int type, it'd still work because Base-10 to Base-36 conversion wouldn't be necessary. However, if 's' value is '3P', the conversion will throw the validation error exception and it'll call to base36_to_int function to decode the parameter.
In case 's' parameter is a Hashid instance, the view will return the value without decoding and it will work for me as well.

Is it possible to change just this line in utils.py? I think it will help to other developers with special pk types.

Thanks!

**Comment by CleitonDeLima** [comment]
this problem still exists, any alternative?

**Comment by pulse-mind** [comment]
Same here

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2156
