### ISSUE TITLE
ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE not respected

### ISSUE THREAD

**Issue by steverecio** [pennersr/django-allauth#2157]
ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE setting is not respected. Setting value to False still requires password confirmation.

**Comment by milossh** [comment]
Same error for me. Will someone please take a look?

**Comment by pennersr** [comment]
I cannot confirm this. See the signup POST in `test_optional_email_verification` -- it clearly only posts 1 password while the setting is set to `False` and this test case passes.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2157
