### ISSUE TITLE
How to configure a Facebook app to django-allauth work fine.  

### ISSUE THREAD

**Issue by mevangelista-alvarado** [pennersr/django-allauth#2161]
I use 
django-allauth == 0.24.1 
Django 1.11 
Python 2.7.15 

**Django-allauth configuration in my app**

 __settings.py__
INSTALLED_APPS = (
    # allauth shite
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.facebook',
)
AUTHENTICATION_BACKENDS = (
    'allauth.account.auth_backends.AuthenticationBackend',
)

SOCIALACCOUNT_PROVIDERS = {
    'facebook': {
        'METHOD': 'oauth2',
        'SCOPE': ['email', 'public_profile', 'user_friends'],
        'AUTH_PARAMS': {'auth_type': 'reauthenticate'},
        'INIT_PARAMS': {'cookie': True},
        'FIELDS': [
            'id',
            'email',
            'name',
        ],
        'EXCHANGE_TOKEN': True,
        'LOCALE_FUNC': 'path.to.callable',
        'VERIFIED_EMAIL': False,
        'VERSION': 'v2.8',
    }
}

__Social applications__

![screen shot 2018-12-06 at 12 59 01 pm](https://user-images.githubusercontent.com/28746720/49605697-d4f30480-f956-11e8-8c8c-14db22493276.png)

Error when I to make login with Facebook 

<img width="445" alt="screen shot 2018-12-03 at 2 15 35 pm" src="https://user-images.githubusercontent.com/28746720/49605769-0a97ed80-f957-11e8-9dc9-559d19ccf1e7.png">

Configuration of __Facebook app__

![screen shot 2018-12-06 at 1 02 46 pm](https://user-images.githubusercontent.com/28746720/49605883-64001c80-f957-11e8-9286-51c1140a17e7.png)

The question is What can I url put in the field "URI de redireccionamiento de OAuth válidos"?
I tried with  
 * https://mysite.com/
 * https://mysite.com/accounts/facebook/login
 * https://mysite.com/accounts/facebook/callback 
 * https://mysite.com/facebook/callback
 * https://mysite.com/login/callback
 * https://mysite.com/login/facebook/callback

**Comment by iarp** [comment]
Did you solve this one? If you used the default url allauth uses in the documentation, it should be https://mysite.com/accounts/facebook/login/callback/

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2161
