### ISSUE TITLE
[suggestion] Store the settings in a single dict, same as DRF

### ISSUE THREAD

**Issue by snirp** [pennersr/django-allauth#2163]
Django Rest Framework stores its settings in a single dictionary in settings.py. As this library has quite a few settings itself, it would be great to follow that standard.

**Comment by pennersr** [comment]
This would be a major backwards incompatible change, I really do not think it is worth pursuing that route.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2163
