### ISSUE TITLE
Password Reset Emails Not Subject to Cooldown

### ISSUE THREAD

**Issue by jplehmann** [pennersr/django-allauth#2167]
There appears to be no rate-limiting for password resets.

I just got hit by a bot who sent themselves 5,000 confirmation emails and got my email service to temporarily suspend me, due to #1921.  Now that I got that worked around by disabling email HMAC as described in that issue, I was testing things and noticed that even though those confirm emails are now rate limited -- the password reset emails do NOT appear to be rate-limited.  This is a vulnerability which we should consider protecting in similar manner. However this feature would probably require another DB table.

Using allauth 0.38.

**Comment by DanAtShenTech** [comment]
Same thing happened to us.  I've set ACCOUNT_EMAIL_CONFIRMATION_COOLDOWN and will really need rate limiting on password reset emails as well.

**Comment by 9mido** [comment]
What if you did something like this? This way, the same email address cannot be issued another reset email again if the time in the database did not expire yet. In order to still spam you, a spammer would need to guess/know other valid emails that have already signed up on your website. 

A pull request to make this better would be to allow for a custom setting to be able to specify the period of time you want to prevent users from re-submitting the password reset form again. e.g. timezone.timedelta(minutes=SETTING). But I am not sure how to do that.

Model:

```
class ResetRequestModel(models.Model):
    email = models.EmailField()
    inserted = models.DateTimeField(auto_now_add=True)
```

Form:

```
from allauth.account.forms import ResetPasswordForm
from app.model import ResetRequestModel
import datetime
from django.utils import timezone
import pytz

class CustomResetForm(ResetPasswordForm):

    def clean_email(self):
        email = super().clean_email()
        if ResetRequestModel.objects.filter(email=email, inserted__gt=datetime.datetime.now(tz=timezone.utc) - timezone.timedelta(minutes=1)):
            raise forms.ValidationError('you cannot submit password reset requests that fast, please wait')
        if ResetRequestModel.objects.filter(email=email, inserted__lt=datetime.datetime.now(tz=timezone.utc) - timezone.timedelta(minutes=1)):
            ResetRequestModel.objects.filter(email=email, inserted__lt=datetime.datetime.now(tz=timezone.utc) - timezone.timedelta(minutes=1)).delete()
        return email

    def save(self, request, **kwargs):
        ret = super().save(request=request, **kwargs)
        ResetRequestModel.objects.create(email=self.cleaned_data['email'])
        return ret

```

**Comment by pennersr** [comment]
Closing -- rate limits are now in place.

**Comment by jplehmann** [comment]
Thank you!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2167
