### ISSUE TITLE
AWS Cognito support?

### ISSUE THREAD

**Issue by brylie** [pennersr/django-allauth#2172]
Our systems admin is moving our user management to [AWS Cognito](https://aws.amazon.com/cognito/) and I would like to align with their efforts. Is it possible to authenticate usung AWS Cognito?

**Comment by kaidokert** [comment]
https://github.com/MetaMetricsInc/django-warrant seems to address this.

**Comment by brylie** [comment]
Yeah, I was a bit concerned by the lack of recent release for the Django Warrant project.

**Comment by pennersr** [comment]
I would be happy to accept any new provider. Looking forward to a pull request. Other than that, I am closing this issue...

**Comment by francisbrito** [comment]
I opened a PR for adding support to Amazon Cognito (#2400). cc @pennersr 

Please let me know if you'd like me to change anything about it

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2172
