### ISSUE TITLE
Overide allauth signup/login views for Firebase auth check

### ISSUE THREAD

**Issue by mreguly** [pennersr/django-allauth#2173]
Is there any way to overide signup/login views? I need to check if user exists in firebase DB when logging in or if the user isn't already registered. 

Should I use custom ACCOUNT_SIGNUP_FORM_CLASS and check it in signin method? Or should I use Custom views for this and call allauth methods for signup/login?

**Comment by romelgomez** [comment]
How to use Alluath with Firebase Auth  https://github.com/pennersr/django-allauth/issues/1952

**Comment by derek-adair** [comment]
Close / encourage move to https://github.com/pennersr/django-allauth/discussions

**Comment by derek-adair** [comment]
also a duplicate :P

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2173
