### ISSUE TITLE
Per-request locale does not affect messages

### ISSUE THREAD

**Issue by kyegupov** [pennersr/django-allauth#2174]
In a project with a per-request locale (see https://docs.djangoproject.com/en/2.1/topics/i18n/translation/#how-django-discovers-language-preference about LocaleMiddleware), that locale doesn't seem to be used in allauth messages.

Correct me if I'm wrong, but I think the problem is in https://github.com/pennersr/django-allauth/blob/9614b862932a63eb1242a31e601cd6075eff45b7/allauth/account/adapter.py#L314 : it should pass request parameter to `render_to_string` for translation using the per-request locale to work.

**Comment by pennersr** [comment]
That should not be necessary. LocaleMiddleware activates the locale:

https://github.com/django/django/blob/master/django/middleware/locale.py#L25

From that point on, request is not required.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2174
