### ISSUE TITLE
LinkedIn V1 API deprecated March 1 2019

### ISSUE THREAD

**Issue by PaulH12355** [pennersr/django-allauth#2177]
All new applications created on the LinkedIn Developer Platform as of January 14, 2019 can use LinkedIn's v2 APIs. Starting March 1, 2019, LinkedIn will deprecate use of its v1 APIs. 

Will django-allauth be updated to handle this deprecation?

**Comment by PaulH12355** [comment]
Anybody else have concerns about this ?

**Comment by pennersr** [comment]
There already is support for v2 -- we have two linkedin providers: `linkedin`, and, `linkedin_oauth2`. The latter uses v2 endpoints such as https://www.linkedin.com/oauth/v2/accessToken, though I notice that it is also using this v1 endpoint https://api.linkedin.com/v1/people/~ ...  to be addressed.

**Comment by PaulH12355** [comment]
@pennersr OK thanks.

**Comment by kmctown** [comment]
Has anyone started on this? I'm going to start looking at it now. It looks like it's more than just swapping endpoints. It's an entirely new permissions structure, field name changes, etc.

**Comment by PaulH12355** [comment]
These look like the V2 endpoints for details etc after auth:
"https://api.linkedin.com/v2/me"
"https://api.linkedin.com/v2/clientAwareMemberHandles?q=members&projection=(elements*(primary,type,handle~))"

**Comment by kmctown** [comment]
Making some progress. Looking like it's going to be:

Profile:
```
https://api.linkedin.com/v2/me
```

Email:
```
https://api.linkedin.com/v2/emailAddress?q=members&projection=(elements*(handle~))
```

**Comment by kmctown** [comment]
@PaulH12355 I'm through the brunt of it in #2216. I've manually tested it while connected to my app as well, which appears to now be operational against the v2 API.

The unit tests are not passing yet. I spent a little bit of time looking at the tests and it wasn't terribly obvious to me, as this is my first time working on the codebase. Need to focus on getting my app in the safe zone before the deadline before spending more time polishing the PR.

**Comment by PaulH12355** [comment]
@kmctown This is good news. Thanks for your work on this.

**Comment by pennersr** [comment]
I have just comitted 5f90cc358a1847e06cb3577e897f8361f490f46d -- it is a bit of a mixture of @kmctown 's changes and mine.  "Works for me" and about to go into production, but please let me know if I missed something.

**Comment by kmctown** [comment]
Thanks, @pennersr! I will integrate the new version and let you know if I find anything.

**Comment by pennersr** [comment]
@kmctown Thanks. If you can, also report back if all is well... I am withholding the new allauth release until there is a little bit of confidence in these changes.

**Comment by kmctown** [comment]
> @kmctown Thanks. If you can, also report back if all is well... I am withholding the new allauth release until there is a little bit of confidence in these changes.

Will do. Spending most of today (ET time) testing this and will get back to you either way.

**Comment by kmctown** [comment]
@pennersr Not major, but I'm running into this (I use `allauth.tests.MockedResponse` to test some refresh token middleware)

```
line 40, in get_user_info
    if resp.ok:
AttributeError: 'MockedResponse' object has no attribute 'ok'
```

Not sure if that will crop up elsewhere as well.

**Comment by pennersr** [comment]
@kmctown A "real" `requests` response has an `ok` property. The `MockedResponse` is apparently incomplete on this point, but at least sufficiently complete for allauth testing purposes (as the tests do pass). Might look into that at a later time, for now I'll start looking into the release...

**Comment by kmctown** [comment]
Yep, just reporting what I'm finding. I'm handling it on my side, but as far as the actual provider, it's looking solid to me so far.

**Comment by PaulH12355** [comment]
@pennersr @kmctown Great work. If this gets pushed just before March 1st I can test it out on my staging platform. Already was using linkedin_oauth2 for the auth but it was obviously the V1 for profile/email that's going V2. I assume this should therefore be a seamless fix.

**Comment by PaulH12355** [comment]
@pennersr @kmctown Actually, is it possible to pip install a test versions of your releases. i.e do you have test versions before you go prod?

**Comment by kmctown** [comment]
> @pennersr @kmctown Actually, is it possible to pip install a test versions of your releases. i.e do you have test versions before you go prod?

@PaulH12355 You can install the current version by using the commit `sha` before it goes to PyPI. Put this in your `requirements.txt` instead of `django-allauth==version`:

```
-e git+https://github.com/pennersr/django-allauth.git@929da1188ff71b4f37b3d29ae4cc75c0f5928cbc#egg=django-allauth`
```

**Comment by PaulH12355** [comment]
@kmctown Thanks for that! I haven't dealt with test releases before. I will give this a try this week and report back.

**Comment by kmctown** [comment]
No prob. You can directory install against any commit `sha` for any repo on GitHub using that approach. Handy if you need to fork something and get a fix in place in your app before the repo has a new version released (which is what I was going to do with this until Raymond stepped in).

**Comment by PaulH12355** [comment]
@kmctown Thanks. So then does Raymond eventually do a formal prod branch release when all  tests/feedback is good?

**Comment by kmctown** [comment]
Looks like it's done actually. `0.39.0` is released.

**Comment by PaulH12355** [comment]
OK will test first thing tomorrow and report back.

**Comment by PaulH12355** [comment]
@kmctown @pennersr Hi both. The Linkedin V2 changes are working for me, I just needed to tweak my SocialAdaptor to get the new email field from extra_data. Thanks for the work.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2177
