### ISSUE TITLE
Google+ Sign-in  deprecation

### ISSUE THREAD

**Issue by simonleekr** [pennersr/django-allauth#2183]
Google reported
"The Google+ Sign-in feature is fully deprecated and is being shut down on March 7, 2019. This will be a progressive shutdown, with intermittent failures starting as early as January 28, 2019.
Developers should migrate to the more comprehensive Google Sign-in authentication system."

How to migrate  to Google Sign-in from Google+ Sign-in for the Web using django-allauth?

**Comment by rustanacexd** [comment]
Anyone?

**Comment by iarp** [comment]
Accordingto the [documentation](https://developers.google.com/identity/protocols/googlescopes#plusv1) the Google+ API is just a series of scopes built on to of a regular google authentication.

It should be a simple matter of making sure you have the [correct scopes enabled](https://developers.google.com/identity/protocols/googlescopes#oauth2v2) for your [projects credentials](https://console.cloud.google.com/apis/credentials/consent). Looking at my own standard google login project I only have userinfo.email, userinfo.profile, and openid selected. If you add any new scopes, the user may be asked on their next login to confirm the newly added scopes.

**Comment by pennersr** [comment]
Indeed, there is not much to address within allauth.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2183
