### ISSUE TITLE
Facebook js connection bug.

### ISSUE THREAD

**Issue by arctelix** [pennersr/django-allauth#219]
When logging in via facebook js the pop up opens and asks for a password when the user is already logged into facebook.  The window can be closed without entering an email and the user is still logged in.

The facebook popup indicates that the site is requesting that an email is entered...

I believe the 0.9.0 version closes the window automatically, and this way is quite annoying so i imagine that its just a JavaScript call to close the window when logged in that is missing?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/219
