### ISSUE TITLE
How force *only* social login

### ISSUE THREAD

**Issue by wgordon17** [pennersr/django-allauth#2191]
Is there a way to prevent normal account creation, and only rely on Social Account creation?

**Comment by hiimdoublej** [comment]
+1 would like this feature as well.

**Comment by wgordon17** [comment]
Nvm, it looks like this has already been discussed previously:

+ #345 
+ #1227 

Therefore, I'm closing my issue in favor of those

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2191
