### ISSUE TITLE
windowslive provider failing on complete_login, profile_url returns 401 "The access token isn't valid."

### ISSUE THREAD

**Issue by iarp** [pennersr/django-allauth#2194]
I was looking at adding windowslive as a provider for login, I could not get beyond the Social Network Failure message. Digging around I found the request.get within complete_login to https://apis.live.net/v5.0/me is returning:

`{
    "error": {
        "code": "request_token_invalid",
        "message": "The access token isn't valid."
    }
}`

I've been trying to find documentation online about things that have changed..etc and cannot find a whole lot that describes the apis.live.net urls. The best I could find was this [SO comment](https://stackoverflow.com/a/51366553/586162) that lead me to https://graph.microsoft.com/v1.0/me which does return data, however it is not the exact same data so I don't know what it would break if I changed that for things down the line.

Does anyone know this api better or know of some documentation buried somewhere?

**Comment by iarp** [comment]
I'll close this issue later in case anyone else knows whats up. I can only recommend using the Microsoft provider within allauth. It only required changing the INSTALLED_APPS provider and the SocialApp uses the same client id and secret.

**Comment by pennersr** [comment]
This is not really actionable. If you find something tangible that points to a bug in allauth, feel free to reopen.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2194
