### ISSUE TITLE
Sending email to multiple ids in adapter.render_mail()

### ISSUE THREAD

**Issue by AbdealiJK** [pennersr/django-allauth#2198]
https://github.com/pennersr/django-allauth/blob/41f84f5530b75431cfd4cf2b89cd805ced009e7d/allauth/account/adapter.py#L97

Currently, `render_mail()` supports sending an email to only 1 emailID.
There are some cases where it can be useful to send mails to multiple IDs (like overriding the adapter to send emails to an admin account and the user)
Or sending an email to add admins when the user subscribed successfully.

While currently this can be easily overridden to add this functionality, it would be awesome if the multi email support could be added into this function to simplify usability.

As I see it - it is a simple:
```
if isintsance(email, str):
    email = [email]
```
at the top of the function.
I could make a PR if the proposal seems fine.

**Comment by iarp** [comment]
If you look a couple of lines below the def you'll see that it is passing `[email]` into the EmailMessage and EmailMultiAlternatives classes. I think it needs to be compared to `six.string_types` though.

**Comment by pennersr** [comment]
Closed via 4abf3f8b

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2198
