### ISSUE TITLE
Trello User Info

### ISSUE THREAD

**Issue by unformatt** [pennersr/django-allauth#2200]
I noticed in Trello provider that username and email is not available and that user ends up with username `user` in django. Doesn't look like an easy fix as we need to hit the Trello API to get the user info and the provider does not have access to the API keys (although it can get the token from the request). I guess the best method is to listen for `allauth.account.signals.user_signed_up` and implement it myself?

**Comment by pennersr** [comment]
Closed via 10edf1aef8693f68d203273be5e1a5124798b95e

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2200
