### ISSUE TITLE
Admin approval inserted into email verification 

### ISSUE THREAD

**Issue by nevpilot** [pennersr/django-allauth#2208]
As it was suggested in #975, I am trying to use the email verification to insert admin's approval for signup process. In this hypothetical scheme, the email with confirmation-link and user's email address goes to admin instead of the user. Then, if admin decides to approve the user, admin can forward that email to the user with the link and additional modifications and instructions. Is this possible? Can the confirmation email be redirected to different addresses that are specified in the settings or somewhere else?

**Comment by pennersr** [comment]
In the adapter, make sure the user is created with is_active=False. Then he won't be able to sign in unless the admin flips the switch.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2208
