### ISSUE TITLE
ProgrammingError at /es/admin/socialaccount/socialaccount/ relation "socialaccount_socialaccount" does not exist LINE 1: SELECT COUNT(*) AS "__count" FROM "socialaccount_socialaccou...

### ISSUE THREAD

**Issue by beren5000** [pennersr/django-allauth#2209]
Greetings
Im having this issue, with django 2.1.7 and python 3, im using the migrate command, but with django-tenant-schemas, so i use migrate schemas, i try to put all auth apps in shared and tenant apps, in the settings, but when i try to access to the admin to create my credentials, i get the same error
ProgrammingError at /es/admin/socialaccount/socialaccount/
relation "socialaccount_socialaccount" does not exist
LINE 1: SELECT COUNT(*) AS "__count" FROM "socialaccount_socialaccou...

there is something i can do with this?

**Comment by beren5000** [comment]
for some reason i recreate the database again it works.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2209
