### ISSUE TITLE
Social Network Login Failure-Linkedin_oauth2 r_basicprofile on 0.39.0 

### ISSUE THREAD

**Issue by jhancia** [pennersr/django-allauth#2218]
Just upgraded to 0.39.0 and now can't login using linkedin_oauth2 with scope 'r_basicprofile.' I didn't change any settings and have been using linkedin_oauth2 already with the PROFILE_FIELDS listed in the docs. Is there something new in the PROFILE_FIELDS or scope that I need to change?  

I noticed that when I changed the scope to 'r_liteprofile', the login callback works and pulls in the email address only, but I need 'r_basicprofile' to pull in other info like picture, positions, and summary. Commented out everywhere I access the 'extra_data' field but it doesn't render the initial SignupForm.

I made a new linkedin app to test it out if that would help but no. Any ideas on what is causing this problem? Can't figure it out since the Social Network Login Failure error page doesn't say what is wrong. Thanks

**Comment by pennersr** [comment]
https://docs.microsoft.com/en-us/linkedin/shared/integrations/people/profile-api

By default, only the Lite Profile Fields are returned for a profile request. See the Profile Fields document for a full list of supported fields.

To request more or less fields, **you must have additional permissions that are only granted to select partners.**

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2218
