### ISSUE TITLE
Error on sending confirmation email after signup

### ISSUE THREAD

**Issue by danfreak** [pennersr/django-allauth#222]
I ask the user to provide 2 info after signing up with a social account:
- username
- email

My settings

``` python
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = True
SOCIALACCOUNT_AUTO_SIGNUP = False
```

After he provides this 2 arguments allauth tries to send a confirmation email, and I get the following error:

```
send_confirmation() takes exactly 1 argument (2 given)
```

The full traceback is here: http://dpaste.com/hold/1034551/

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/222
