### ISSUE TITLE
Redirect using a hidden next input

### ISSUE THREAD

**Issue by charleshan** [pennersr/django-allauth#2221]
I think we should add this to make it easier to control the redirect behavior.
```<input type="hidden" name="next" value="{{ next }}">```
https://docs.djangoproject.com/en/dev/topics/auth/default/#all-authentication-view

**Comment by pennersr** [comment]
Feel free to submit a pull request...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2221
