### ISSUE TITLE
SOCIALACCOUNT_FORMS not work   when SOCIALACCOUNT_AUTO_SIGNUP (=True)

### ISSUE THREAD

**Issue by find456789** [pennersr/django-allauth#2222]
sorry , my english is not well

when user  used github login to my site

i hope that auto create user profile,  

this is my code 

```
# settings.py
SOCIALACCOUNT_FORMS = {
    'signup': 'XX.XX.forms.MyCustomSocialSignupForm',
}
```
```
# XX.XX.forms.py
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
class MyCustomSocialSignupForm(SocialSignupForm):

    def save(self, request):
   
        # Ensure you call the parent classes save.
        # .save() returns a User object.
        user = super().save(request)

        # Add your own processing here.
        user_profile = UserProfile()
        user_profile.user = user
        user_profile.ip = get_ip(request)
        user_profile.save()
        # You must return the original result.
        return user
```

but that can not create user profile

--------

 then i add  `SOCIALACCOUNT_AUTO_SIGNUP = False ` to   `settings.py`

its work,  it can create user profile

i hope 

can you help me?  

thank you very much

**Comment by pennersr** [comment]
This is by design. With auto signup turned on, the user is not submiting some custom signup form, hence that code will logically not trigger.

**Comment by doomedraven** [comment]
oh somehow i got the same, it was working till midday, and after that stopped, and i missed this option, it helped me to figurate what was wrong

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2222
