### ISSUE TITLE
Problem with Facebook: Social Network Login Failure

### ISSUE THREAD

**Issue by vadymkono** [pennersr/django-allauth#2224]
Provider = Facebook.

Problem = Social Network Login Failure. An error occurred while attempting to login via your social network account.

Error = https://www.facebook.com/v3.2/dialog/oauth?client_id=...&redirect_uri=http:

Ok = https://www.facebook.com/v3.2/dialog/oauth?client_id=...&redirect_uri=https:

Quick fix (sorry, still studying) = lib/python3.6/site-packages/allauth/socialaccount/providers/oauth2/views.py:
callback_url = self.adapter.get_callback_url(request, app).replace("http:", "https:")

Now "Valid OAuth Redirect URIs" on FB App only "https:".

Thanks for django-allauth! works!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2224
