### ISSUE TITLE
Special character `ñ` breaks username validation

### ISSUE THREAD

**Issue by eillarra** [pennersr/django-allauth#2225]
If a user has a spanish `ñ` in his name, then username validation breaks. Basically, as far as I can see, the `allauth.account.utils.filter_users_by_username()` function is not checking if a username is taken using a BINARY search.

These two give different results in MYSQL:
```mysql
SELECT username FROM auth_user WHERE username LIKE '%ñame%';
SELECT username FROM auth_user WHERE username LIKE BINARY '%ñame%';
```

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2225
