### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by stsewd** [pennersr/django-allauth#2231]
Hi, the docs hosted in rtd haven't been built in a while https://readthedocs.org/projects/django-allauth/builds/ (~2months)

I'm guessing this is because of https://docs.readthedocs.io/en/stable/webhooks.html#i-was-warned-i-shouldn-t-use-github-services

**Comment by pennersr** [comment]
Fixed

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2231
