### ISSUE TITLE
Password value sent back on response when form invalid

### ISSUE THREAD

**Issue by gabriel-amram** [pennersr/django-allauth#2235]
When using AJAX, the `DefaultAccountAdapter.ajax_response_form` adds each field's value to the response that will be sent back to the client when the form is invalid.

One of these fields might be sensitive - such as password, which is bad practice to send back to the client for security reasons.

It doesn't respect the `ACCOUNT_PASSWORD_INPUT_RENDER_VALUE` setting which would normally prevent the value from being rendered in the template.

**Comment by pennersr** [comment]
Why is it bad to send it back to the client? The client already knows the value, and either the connection is encrypted or not. If not, then not sending it back won't address a security issue, and if it is encrypted, there is no issue.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2235
