### ISSUE TITLE
Paypal integration seems outdated - paypal server URL error

### ISSUE THREAD

**Issue by grybkin** [pennersr/django-allauth#2242]
https://www.sandbox.paypal.com/webapps/auth/protocol/openidconnect/v1/authorize

cannot be reached. All parameters passed from allauth - scope, client_id, state - seem correct.

The built-in "Connect with PayPal" button works okay.

**Comment by grybkin** [comment]
This issue has resolved itself for me - working now. Likely, paypal was being slow in creating an app and making the url available for login.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2242
