### ISSUE TITLE
openid redirect issue with okta

### ISSUE THREAD

**Issue by kishorpawar** [pennersr/django-allauth#2245]
I am following [this](https://django-allauth.readthedocs.io/en/latest/providers.html#openid) document. 

I added `'allauth.socialaccount.providers.openid',` in `INSTALLED_APPS`, and also added 

```
SOCIALACCOUNT_PROVIDERS = {
    'openid': {
        'SERVERS': [
            dict(id='okta',
                 name='Okta',
                 openid_url='https://dev-264599.okta.com/oauth2/default/v1/authorize'),
        ]
    }
}
```

After this has been done I added following in my login page.

```
{% load socialaccount %}
<a href="{% provider_login_url "openid" openid="https://dev-264599.okta.com/oauth2/default/v1/authorize" next="/success/url/" %}">Okta OpenID</a>
```

Besides this I have created social app in to db with `client_id` and `secret`.

With this setup I get following error when I click on the link created in login page.

`HTTP Response status from identity URL host is not 200. Got status 404` 

may be because the Url is not formed correctly?

**Comment by pennersr** [comment]
Questions are better served at sites like stackoverflow.

**Comment by Cabalist** [comment]
It is too bad no one helped him on StackOverflow....
https://stackoverflow.com/questions/55200364/django-allauth-openid-implementation-for-okta

**Comment by kishorpawar** [comment]
Thank you @Cabalist, I actually got it working. I wrote the server-side code to do the redirection and all.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2245
