### ISSUE TITLE
Tumblr provider does not correctly handle login cancellation

### ISSUE THREAD

**Issue by Foxbud** [pennersr/django-allauth#2246]
As I understand it, when a website visitor chooses to cancel their login on the provider's confirmation screen, Allauth redirects them to the `socialaccount_login_cancelled` view. The Reddit provider is a good example of this functionality.

The Tumblr provider does not, however, follow this pattern. In its current iteration, the Tumblr OAuth confirmation screen offers the visitor a choice of allowing or declining. If they allow the login then it works as expected. If they decline, on the other hand, instead of redirecting the visitor to the `socialaccount_login_cancelled` view, Allauth displays the content of the `socialaccount_login_error` view while being on the url of the `tumblr_callback` view with the fragment identifier `#_=_` appended to the end.

**Comment by iarp** [comment]
This comes down to Tumblr not sending anything with the user indicating that they cancelled. It's no different than someone figuring out the url structure and visiting `/accounts/tumblr/login/callback/` directly.

If you wanted to you could override `authentication_error` on the socialaccount adapter to redirect the user to somewhere else.

**Comment by derek-adair** [comment]
Close as won't fix.  This is up to the user to implement and not worth supporting.

**Comment by pennersr** [comment]
Given that the help wanted label did not result in any help since 2019 I am going to close this. If there is a way to reliably recognize a cancel, then please feel free to reopen...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2246
