### ISSUE TITLE
Can't import ResetPasswordForm

### ISSUE THREAD

**Issue by ChrisPappalardo** [pennersr/django-allauth#2247]
Adding the following line to users/forms.py in a django project with allauth properly installed and working:

`from allauth.account.forms import ResetPasswordForm`

... produces the following error:

`ImportError: cannot import name 'ResetPasswordForm' from 'allauth.account.forms' (/usr/local/lib/python3.7/site-packages/allauth/account/forms.py)`

**Comment by pennersr** [comment]
If you have something tangible that points to a bug in allauth, feel free to reopen. Otherwise, this issue is not actionable.

**Comment by ChrisPappalardo** [comment]
Shouldn't I be able to import (and extend) that form the way I have described?  External security reviews have noted that Allauth's password reset form is a security vulnerability because it discloses whether or not an email address is associated with a user.  I wanted to add a captcha field to the password reset form to prevent scripted attacks to determine valid email addresses of existing users and/or override the clean_email method to remove/revise the error message.

**Comment by pennersr** [comment]
For the disclosure, see #1307. As for your specific issue, in order to keep things manageable we really need clear actionable bugs.  Problem descriptions depending on project specific code is simply not debuggable and often ends up being an issue in the project/deployment/configuration itself.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2247
