### ISSUE TITLE
RelatedObjectDoesNotExist  SocialAccount has no user.

### ISSUE THREAD

**Issue by rashed-khan-arif** [pennersr/django-allauth#2252]
I am in a trouble with this problem, it kills me inside. The problem is when i'm going to sign in using social account it returned the following message, that means it says "SocialAccount" has no "User". But how can i solve this problem, it should automatically save the socialaccount and user but it doesn't. that's why it can't login. But if i insert a social account from admin panel then it works perfectly.

Somebody please help to get rid from this pain, i'm suffering from last one week.

**Comment by rashed-khan-arif** [comment]
Hey, @pennersr  please take a look

**Comment by pennersr** [comment]
I am sorry, but it is not viable for me to assist in project specific bug hunts...

**Comment by MuhammadAli-M** [comment]
Hey @rashed-khan-arif 

I faced a similar issue.

Please make sure the ```sociallogin.user``` is not called before it's set.
You may override the `DefaultSocialAccountAdapter.new_user` without returning the `DefaultSocialAccountAdapter.new_user`.

**Comment by tymiao1220** [comment]
@rashed-khan-arif I am facing the same issue when using auto signup for the social account, have you solved the problem?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2252
