### ISSUE TITLE
Twitter api error  OAuthError('Invalid response while obtaining request token from "api.twitter.com".')

### ISSUE THREAD

**Issue by nlubega** [pennersr/django-allauth#2254]
I followed all the steps for twitter social media login in django-allauth documentation. I get the following error when I try to login with twitter:

An error occurred while attempting to login via your social network account.
{'provider': 'twitter', 'code': 'unknown', 'exception': OAuthError('Invalid response while obtaining request token from "api.twitter.com".')}

**Comment by johanneswilm** [comment]
Same here.

**Comment by pennersr** [comment]
Sorry, but this is a misconfiguration/deployment issue somewhere. Twitter is working.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2254
