### ISSUE TITLE
I get  "accounts/social/login/cancelled/" on Instagram register.

### ISSUE THREAD

**Issue by TheOneWayTruth** [pennersr/django-allauth#2260]
Video: https://streamable.com/blch2
My App is approved, and the callback is 
https://www.mywebsite.de/accounts/instagram/login/callback/

All other logins work

**Comment by cavb** [comment]
Same here. Did work correctly previously on sandbox users.

**Comment by pennersr** [comment]
https://django-allauth.readthedocs.io/en/latest/faq.html#why-did-you-just-close-my-issue

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2260
