### ISSUE TITLE
Prepopulate signup form based on request (Based on invitation)

### ISSUE THREAD

**Issue by metemaddar** [pennersr/django-allauth#2261]
I send invitation to users and I want to pre-populate the signup form based on invitation code. In fact I need to set initial of signup form (set email).
Where is best place to do set initial of signup form based on request?

**Comment by pennersr** [comment]
https://django-allauth.readthedocs.io/en/latest/faq.html#why-did-you-just-close-my-issue

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2261
