### ISSUE TITLE
missing 1 required positional argument: 'allowed_hosts'

### ISSUE THREAD

**Issue by sodrooome** [pennersr/django-allauth#2262]
so I tried to login via a github account but suddenly there was an error message like this `TypeError: is_safe_url() missing 1 required positional argument: 'allowed_hosts'`.

I have followed the latest documentation that all auth now requires private API but still got the error.

Can anyone help with this?

**Comment by iarp** [comment]
Do you have the full stack trace? Also what versions of allauth and django?

**Comment by pennersr** [comment]
There is only one place in allauth where is_safe_url() is invoked, and there allowed_hosts is passed.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2262
