### ISSUE TITLE
Identity spoofing via additional email confirmed by primary

### ISSUE THREAD

**Issue by treba123** [pennersr/django-allauth#2265]
As of 0.39.1, it's very easy to spoof the identity of some random person by

1. Registering with your own email address me@me.me
2. Confirm email (sent to me@me.me)
3. Add additional email address obama@gov.us
4. Confirm email (again sent to me@me.me as it's the primary email address)
5. Set obama@gov.us as the primary email address
6. Delete original email address me@me.me
7. Post "I will drop a nuke on russia" with your confirmed email address obama@gov.us

This is not strictly security relevant, but is there a reason why new confirmation emails are sent to the primary address?

**Comment by pnwparksfan** [comment]
You sure about that? I can't reproduce this, when I add a new email address the verification email gets sent to the newly added address, not to the existing primary email.

**Comment by treba123** [comment]
Right, this was our fault :)
Thanks for the answer!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2265
