### ISSUE TITLE
SocialAccount model's is_existing should always return a boolean

### ISSUE THREAD

**Issue by horida** [pennersr/django-allauth#2269]
Currently, the property `is_existing` of the SocialAccount model returns None or a primary key, which is misleading given the name of the property.

Better return a `return self.account.pk is not None`

See: https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/models.py#L245

**Comment by pennersr** [comment]
Feel free to submit a pull request, keeping issues open for this is not very productive.

**Comment by horida** [comment]
@pennersr sure thing! Here you go: https://github.com/pennersr/django-allauth/pull/2293

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2269
