### ISSUE TITLE
Successful authentication to Twitter redirects to /accounts/social/connections/

### ISSUE THREAD

**Issue by commadelimited** [pennersr/django-allauth#227]
After a successful authentication to Twitter users are redirected back to `/accounts/social/connections/`.

We don't plan on implementing this for our users, instead we're allowing them to log out one at a time via AJAX. How can I alter the settings for our app to redirect users somewhere else? I've searched our local app, as well as forking this repo and searching through it, but I can't find where in the code this is being implemented.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/227
