### ISSUE TITLE
Linkedin signup issue

### ISSUE THREAD

**Issue by mrsdz** [pennersr/django-allauth#2272]
Hi, when I sign up with linkedin, if the user already exists with another provider, sign up flow stuck on `/accounts/social/signup/`.

My settings:
```python
SOCIALACCOUNT_PROVIDERS = {
    'linkedin': {
        'SCOPE': [
            'r_basicprofile',
            'r_emailaddress'
        ],
        'PROFILE_FIELDS': [
            'id',
            'first-name',
            'last-name',
            'email-address',
            'picture-url',
            'public-profile-url',
            'gender',
            'birthday'
        ],
        'HEADERS': {
            'x-li-src': 'msdk'
        }
    }
}

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 1
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = "none"
ACCOUNT_LOGIN_ATTEMPTS_LIMIT = 10
ACCOUNT_LOGIN_ATTEMPTS_TIMEOUT = 86400
ACCOUNT_LOGOUT_REDIRECT_URL = '/'
LOGIN_REDIRECT_URL = '/'
AUTH_USER_MODEL = 'profile.CustomUSER'
```

**Comment by AlecsGherghel** [comment]
Seems that you only have one provider, so, the issue description is quite off.

Do you have a user signed up through email who now tries to signup through LinkedIn?

Doesn't seem to be a problem related with the package, though.

**Comment by mrsdz** [comment]
This issue happens when a user that signed up with Google, trying to sign in with linkedin or conversely.

**Comment by pennersr** [comment]
This issue is not actionable -- what does "stuck" mean. https://django-allauth.readthedocs.io/en/latest/faq.html#why-did-you-just-close-my-issue

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2272
