### ISSUE TITLE
Django authentication emails not working + pass reset brings error 111 

### ISSUE THREAD

**Issue by G-biin** [pennersr/django-allauth#2273]
Hi Not sure if you can assist, but i see you commented on password reset. Challenge i'm having is users of my app cannot receive authentication emails, although they can log in successfully. Also password reset isn't working. I get a connection refused errorno 111.

Can you help or show me who I can raise this issue with? Below is the traceback:

Environment:

Request Method: POST

Django Version: 1.10.6
Python Version: 3.6.6
Installed Applications:
['django.contrib.admin',
'django.contrib.auth',
'django.contrib.contenttypes',
'django.contrib.sessions',
'django.contrib.messages',
'django.contrib.staticfiles',
'authtools',
'crispy_forms',
'easy_thumbnails',
'django_admin_bootstrapped',
'profiles',
'accounts',
'debug_toolbar',
'pagedown',
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
'django.contrib.sessions.middleware.SessionMiddleware',
'django.middleware.common.CommonMiddleware',
'django.middleware.csrf.CsrfViewMiddleware',
'django.contrib.auth.middleware.AuthenticationMiddleware',
'django.contrib.messages.middleware.MessageMiddleware',
'django.middleware.clickjacking.XFrameOptionsMiddleware',
'debug_toolbar.middleware.DebugToolbarMiddleware']

Traceback:

File "/home/biin/.virtualenvs/django11/lib/python3.6/site-packages/django/core/handlers/exception.py" in inner
42. response = get_response(request)

File "/home/biin/.virtualenvs/django11/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
187. response = self.process_exception_by_middleware(e, request)

File "/home/biin/.virtualenvs/django11/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
185. response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/home/biin/.virtualenvs/django11/lib/python3.6/site-packages/django/utils/decorators.py" in _wrapped_view
149. response = view_func(request, *args, **kwargs)

File "/home/biin/.virtualenvs/django11/lib/python3.6/site-packages/django/views/generic/base.py" in view
68. return self.dispatch(request, *args, **kwargs)

File "/home/biin/.virtualenvs/django11/lib/python3.6/site-packages/django/views/generic/base.py" in dispatch
88. return handler(request, *args, **kwargs)

File "/home/biin/.virtualenvs/django11/lib/python3.6/site-packages/django/views/generic/edit.py" in post
183. return self.form_valid(form)

File "/home/biin/.virtualenvs/django11/lib/python3.6/site-packages/authtools/views.py" in form_valid
239. html_email_template_name=self.html_email_template_name,

File "/home/biin/.virtualenvs/django11/lib/python3.6/site-packages/django/contrib/auth/forms.py" in save
291. user.email, html_email_template_name=html_email_template_name,

File "/home/biin/.virtualenvs/django11/lib/python3.6/site-packages/django/contrib/auth/forms.py" in send_mail
247. email_message.send()

File "/home/biin/.virtualenvs/django11/lib/python3.6/site-packages/django/core/mail/message.py" in send
342. return self.get_connection(fail_silently).send_messages([self])

File "/home/biin/.virtualenvs/django11/lib/python3.6/site-packages/django/core/mail/backends/smtp.py" in send_messages
100. new_conn_created = self.open()

File "/home/biin/.virtualenvs/django11/lib/python3.6/site-packages/django/core/mail/backends/smtp.py" in open
58. self.connection = connection_class(self.host, self.port, **connection_params)

File "/usr/lib/python3.6/smtplib.py" in init
251. (code, msg) = self.connect(host, port)

File "/usr/lib/python3.6/smtplib.py" in connect
336. self.sock = self._get_socket(host, port, self.timeout)

File "/usr/lib/python3.6/smtplib.py" in _get_socket
307. self.source_address)

File "/usr/lib/python3.6/socket.py" in create_connection
724. raise err

File "/usr/lib/python3.6/socket.py" in create_connection
713. sock.connect(sa)

Exception Type: ConnectionRefusedError at /password-reset/
Exception Value: [Errno 111] Connection refused

**Comment by AlecsGherghel** [comment]
This doesn't look like a specific problem of the package.

The SMTP server seems to be down. Not sure what exactly you're using in your `settings.py`

**Comment by G-biin** [comment]
See below my settings.py. My apologies if it looks messy.

from django.core.urlresolvers import reverse_lazy
import os
from os.path import dirname, join, exists


# Build paths inside the project like this: join(BASE_DIR, "directory")
BASE_DIR = dirname(dirname(dirname(__file__)))
#STATICFILES_DIRS = [join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
MEDIA_ROOT = join(BASE_DIR, 'media')
MEDIA_URL = "/media/"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'SECRET_KEY'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1',
                 'www.MYSITE.com'
                ]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'authtools',
    'crispy_forms',
    'easy_thumbnails',
    'django_admin_bootstrapped',
    'profiles',
    'accounts',
    'debug_toolbar',
    'pagedown',
    'notes'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

ROOT_URLCONF = 'myapp.urls'


# Use Django templates using the new Django 1.8 TEMPLATES settings
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            join(BASE_DIR, 'templates'),
            # insert more TEMPLATE_DIRS here
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                # Insert your TEMPLATE_CONTEXT_PROCESSORS here or use this
                # list if you haven't customized them:
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.debug',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'django.template.context_processors.tz',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myapp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'

CRISPY_TEMPLATE_PACK = 'bootstrap4'

# For Bootstrap 4, change error alert to 'danger'
from django.contrib import messages
MESSAGE_TAGS = {
    messages.ERROR: 'danger'
}

# Authentication Settings
AUTH_USER_MODEL = 'authtools.User'
LOGIN_REDIRECT_URL = '/notes/'
EMAIL_BACKEND = "django.core.mail.backends.filebased.EmailBackend"
EMAIL_FILE_PATH = os.path.join(BASE_DIR, "sent_emails")
LOGIN_URL = reverse_lazy("accounts:login")

THUMBNAIL_EXTENSION = 'png'     # Or any extn for your thumbnails

**Comment by blueyed** [comment]
What host does it use?

> File "/usr/lib/python3.6/smtplib.py" in init
> 251. (code, msg) = self.connect(host, port)

By default this will be localhost.

I wonder if this should also be handled in https://github.com/pennersr/django-allauth/blob/c19b849f78c43167f49034990c1ee446f35f060e/allauth/socialaccount/providers/oauth2/views.py#L144-L153 - or rather more exception in general?  It would be better to wrap it tighter around sending the email of course, but currently (temporary) connection problems would result in server error pages, although the account would have been created, but "only" sending the (not required by default) email verification failed.

**Comment by AlecsGherghel** [comment]
I think that the responsibility of making sure the proper configurations needed for email sending should lay on the person using `all-auth` not on `all-auth` as a library.

From what I can see, in this specific case, he's using `django.core.mail.backends.filebased.EmailBackend` as an email backend which, should only save emails to a directory rather than trying to send them over an SMTP.

In this case, I don't see why `smtplib.py` would fail, if, theoretically, the actual email won't reach that because it's not sent.

Maybe he's using a different `settings.py` file for the environment where the issue occurs.

**Comment by blueyed** [comment]
> I think that the responsibility of making sure the proper configurations needed for email sending should lay on the person using `all-auth` not on `all-auth` as a library.

Yes, but especially with SMTP, but also file-based backends, there might be (temporary) exceptions.
ConnectionRefusedError might be only temporary also after all.
I think those are errors that the user cannot fix (i.e. should probably not get details about), but it should not result in an "internal server error" for him - those cannot be handled in the app itself (apart from reporting/logging/display), but allauth could continue in this case (which still allowing them to be logged).
I can see that `render_authentication_error` is probably not the correct place for it, and it should be nearer to where it happened anyway.

**Comment by G-biin** [comment]
Thanks guys for helping out with this. What would you suggest I do?

**Comment by G-biin** [comment]
**UPDATE**
@AlecsGherghel @blueyed small update, No more errors, but email itself not being received. Any pointers?

**Comment by pennersr** [comment]
This is a deployment issue, not a bug in allauth. Closing.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2273
