### ISSUE TITLE
 Object of type PngImageFile is not JSON serializable

### ISSUE THREAD

**Issue by Antonino22** [pennersr/django-allauth#2276]
Im trying to do an image overlay. Im using satellite data to study a phenomenon over Argentina, but I really wanted to use the interactive map through folium. So far, when creating an image, Im getting an output. But, when I try to overly the satellite image on to base map, im getting an error code:  Object of type PngImageFile is not JSON serializable. I don't have a clue of how to fix it.

import netCDF4
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np
import os,errno
import glob
import shutil

directory1 = '/Volumes/Anthonys_backup/Masters_Thesis/Satellite_Data/new/C13/*'

listofallthefiles = glob.glob(directory1)

    
f = netCDF4.Dataset(listofallthefiles[0],'r') #f is like a dataframe in pandas... but it's better because netcdf

data_var = f.variables['CMI'][:]
a = data_var

xa = f.variables['x'][:]
ya = f.variables['y'][:]

#print("satellite height", f.variables['nominal_satellite_height'][0])
xa = xa*35785831
ya = ya*35785831

import cartopy.crs as ccrs

globe = ccrs.Globe(semimajor_axis=6378137.,semiminor_axis=6356752.)

proj = ccrs.Geostationary(central_longitude=f.variables['nominal_satellite_subpoint_lon'][0],
                                satellite_height=f.variables['nominal_satellite_height'][0] * 1000,
                                globe=globe,sweep_axis='x')

image_rows=f.dimensions["y"].size
image_columns=f.dimensions["x"].size
#namer_image_crop_top=3000
#namer_image_crop_bottom=-100
#namer_image_crop_left=2000
#namer_image_crop_right=-700

namer_image_size_y=(image_rows)
namer_image_size_x=(image_columns)

print("namer image size")
print(namer_image_size_x, namer_image_size_y)

namer_image_size_x=15.1
namer_image_size_y=12.6

fig = plt.figure(figsize=(namer_image_size_x,namer_image_size_y),dpi=80.)

ax = fig.add_subplot(1, 1, 1, projection=proj)
ax.outline_patch.set_edgecolor('none')

import matplotlib as mpl

cdict = {'red': ((0.0, 0.0, 0.0),
                     (.001, 1.00, 1.00),
                     (.107, 1.00, 1.00),
                     (.113, 0.498, 0.498),
                     (.173, 1.00, 1.00),
                     (.179, 0.902, 0.902),
                     (.227, 0.102, 0.102),
                     (.233, 0.00, 0.00),
                     (.287, 0.902, 0.902),
                     (.293, 1.00, 1.00),
                     (.346, 1.00, 1.00),
                     (.352, 1.00, 1.00),
                     (.406, 0.101, 0.101),
                     (.412, 0.00, 0.00),
                     (.481, 0.00, 0.00),
                     (.484, 0.00, 0.00),
                     (.543, 0.00, 0.00),
                     (.546, 0.773, 0.773),
                     (.994, 0.012, 0.012),
                     (.997, 0.004, 0.004),
                     (1.0, 0.0, 0.0)),
             'green': ((0.0, 0.0, 0.0),
                     (.001, 1.00, 1.00),
                     (.107, 1.00, 1.00),
                     (.113, 0.00, 0.00),
                     (.173, 0.498, 0.498),
                     (.179, 0.902, 0.902),
                     (.227, 0.102, 0.102),
                     (.233, 0.00, 0.00),
                     (.287, 0.00, 0.00),
                     (.293, 0.00, 0.00),
                     (.346, 0.902, 0.902),
                     (.352, 1.00, 1.00),
                     (.406, 1.00, 1.00),
                     (.412, 1.00, 1.00),
                     (.481, 0.00, 0.00),
                     (.484, 0.00, 0.00),
                     (.543, 1.00, 1.00),
                     (.546, 0.773, 0.773),
                     (.994, 0.012, 0.012),
                     (.997, 0.004, 0.004),
                     (1.0, 0.0, 0.0)),
             'blue': ((0.0, 0.00, 0.00),
                     (.001, 1.00, 1.00),
                     (.107, 0.00, 0.00),
                     (.113, 0.498, 0.498),
                     (.173, 0.786, 0.786),
                     (.179, 0.902, 0.902),
                     (.227, 0.102, 0.102),
                     (.233, 0.00, 0.00),
                     (.287, 0.00, 0.00),
                     (.293, 0.00, 0.00),
                     (.346, 0.00, 0.00),
                     (.352, 0.00, 0.00),
                     (.406, 0.00, 0.00),
                     (.412, 0.00, 0.00),
                     (.481, 0.451, 0.451),
                     (.484, 0.451, 0.451),
                     (.543, 1.00, 1.00),
                     (.546, 0.773, 0.773),
                     (.994, 0.012, 0.012),
                     (.997, 0.004, 0.004),
                      (1.0, 0.0, 0.0))}

my_cmap = mpl.colors.LinearSegmentedColormap('my_colormap',cdict,2048)

im = ax.imshow(a[namer_image_crop_top:namer_image_crop_bottom,namer_image_crop_left:namer_image_crop_right], extent=(xa[namer_image_crop_left],xa[namer_image_crop_right],ya[namer_image_crop_bottom],ya[namer_image_crop_top]), origin='upper',cmap=my_cmap, vmin=162., vmax=330.)

ax.coastlines(resolution='50m', color='green')

import cartopy.feature as cfeat
    
# Add country borders with a thick line.
ax.add_feature(cfeat.BORDERS, linewidth=1, edgecolor='green')

# Set up a feature for the state/province lines. Tell cartopy not to fill in the polygons
states_provinces = cfeat.NaturalEarthFeature(category='cultural',
                                                 name='admin_1_states_provinces_lines',
                                                 scale='10m',
                                                 facecolor='none', edgecolor='red')

# Add the feature with dotted lines, denoted by ':'
ax.add_feature(states_provinces, linestyle="solid", linewidth=2)

# axes for wi
cbaxes1 = fig.add_axes([0.135,0.12,0.755,0.02])
cbar1 = fig.colorbar(im, cax=cbaxes1, orientation='horizontal')
font_size = 14
cbar1.ax.tick_params(labelsize=font_size, labelcolor='yellow')
cbar1.ax.xaxis.set_ticks_position('top')
cbar1.ax.xaxis.set_label_position('top')
    
#Add's a dot on top of Cordoba
co_lat, co_lon = -31.416016, -64.188929
ax.plot([co_lon], [co_lat], color='white', linewidth=.5, marker='o', transform=ccrs.Geodetic(),)

import datetime
    
time_var = f.time_coverage_start
iyear = time_var[0:4]
print("iyear ",iyear)
imonth = time_var[5:7]
print("imonth ",imonth)
    
import calendar
    
cmonth = calendar.month_abbr[int(imonth)]
print("cmonth ",cmonth)
iday = time_var[8:10]
print("iday ",iday)
itime = time_var[11:19]
itimehr = time_var[11:13]
itimemn = time_var[14:16]

ctime_string = iyear +' '+cmonth+' '+iday+'  '+itime+' GMT'
ctime_file_string = iyear + imonth + iday + itimehr + itimemn

filestring = "C13_" + iyear + imonth + iday + "_" + itimehr + itimemn + ".jpg"
time_string = 'GOES-16 Band 13\n"Clean" LW IR Window\n%s '%ctime_string

from matplotlib import patheffects
    
    
#Text on top left corner 
outline_effect = [patheffects.withStroke(linewidth=2, foreground='black')]
text = ax.text(0.005, 0.90, time_string,
        horizontalalignment='left', transform = ax.transAxes,
        color='yellow', fontsize='small', weight='bold')
text.set_path_effects(outline_effect)
    
    
#Text on top of Cordoba 
text2 =  ax.text(co_lon +1.5 , co_lat +1 , 'Cordoba', color='yellow', weight='bold', 
                     horizontalalignment='right', transform=ccrs.Geodetic())
    
text2.set_path_effects(outline_effect)

from PIL import Image

fig.savefig('GS.png', transparent=True)

img = Image.open("GS.png")

import folium
from folium import plugins

m = folium.Map(location=[-31.416016, -64.188929],  tiles = 'Stamen Terrain')

folium.raster_layers.ImageOverlay(img,
                     [[ya.min(), xa.min()], [ya.max(), xa.max()]],
                     opacity=0.5).add_to(mapa)

mapa

**Comment by pennersr** [comment]
This does not seem to be allauth related.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2276
