### ISSUE TITLE
Custom Password Reset form: save() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by Danos2000** [pennersr/django-allauth#2277]
I'm using allauth 0.38.0 and Django 2.1.7

I've defined a couple of custom forms as described in the docs (to add ReCaptcha). In **forms.py**:

```
from allauth.account.forms import ChangePasswordForm, ResetPasswordForm

class CustomChangePasswordForm(ChangePasswordForm):
    captcha = ReCaptchaField()
    def save(self):
        super(CustomChangePasswordForm, self).save()

class CustomResetPasswordForm(ResetPasswordForm):
    captcha = ReCaptchaField()
    def save(self):
        email_address = super(CustomResetPasswordForm, self).save()
        return email_address

```

and in **settings.py**:

```
ACCOUNT_FORMS = {'change_password':'myapp.forms.CustomChangePasswordForm',
                 'reset_password':'myapp.forms.CustomResetPasswordForm',
}
```

The change password form works as expected. The reset password form, however, gives the following error:

```
TypeError at /accounts/password/reset/
save() takes 1 positional argument but 2 were given
```

With the following stack trace:

```
Django Version: 2.1.7
Python Version: 3.7.3

Traceback:

File "/home/corndog/webapps/test_phagesdb2/lib/python3.7/Django-2.1.7-py3.7.egg/django/core/handlers/exception.py" in inner
  34.             response = get_response(request)

File "/home/corndog/webapps/test_phagesdb2/lib/python3.7/Django-2.1.7-py3.7.egg/django/core/handlers/base.py" in _get_response
  126.                 response = self.process_exception_by_middleware(e, request)

File "/home/corndog/webapps/test_phagesdb2/lib/python3.7/Django-2.1.7-py3.7.egg/django/core/handlers/base.py" in _get_response
  124.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/home/corndog/webapps/test_phagesdb2/lib/python3.7/Django-2.1.7-py3.7.egg/django/views/generic/base.py" in view
  68.             return self.dispatch(request, *args, **kwargs)

File "/home/corndog/webapps/test_phagesdb2/lib/python3.7/Django-2.1.7-py3.7.egg/django/views/generic/base.py" in dispatch
  88.         return handler(request, *args, **kwargs)

File "/home/corndog/lib/python3.7/allauth/account/views.py" in post
  103.             response = self.form_valid(form)

File "/home/corndog/lib/python3.7/allauth/account/views.py" in form_valid
  644.         form.save(self.request)

Exception Type: TypeError at /accounts/password/reset/
Exception Value: save() takes 1 positional argument but 2 were given

```

Any idea why this is not working for the Reset form but is working for the Change form? 

(I've tried removing the recaptcha field and it still has the same error, despite only having the text [from the docs here](https://django-allauth.readthedocs.io/en/latest/forms.html#reset-password-allauth-account-forms-resetpasswordform).)

**Comment by hemanth-sp** [comment]
sorry i did not get what is the use of the this code`def save(self):
        email_address = super(CustomResetPasswordForm, self).save()
        return email_address
`

**Comment by pennersr** [comment]
Questions are better served at sites like stackoverflow...

**Comment by Danos2000** [comment]
That code is literally taken character from character from the docs as an example of how to do what I'm trying to do. At least consider this a request to take out incorrect information from the docs then.

Relevant docs:

https://django-allauth.readthedocs.io/en/latest/forms.html#reset-password-allauth-account-forms-resetpasswordform

My code:
```
from allauth.account.forms import ResetPasswordForm
class CustomResetPasswordForm(ResetPasswordForm):
#    captcha = ReCaptchaField()
    def save(self):
        email_address = super(CustomResetPasswordForm, self).save()
        return email_address
```

Does not work. Despite being identical to docs.

**Comment by Danos2000** [comment]
Please see updated comment.
    On Friday, April 26, 2019, 2:33:57 AM EDT, Raymond Penners <notifications@github.com> wrote:  
 
 
Questions are better served at sites like stackoverflow...

**Comment by pennersr** [comment]
The docs you are pointing to are not of the reset password form, but of the set password form. The signature is different: `def save(self, request, **kwargs)`

**Comment by Danos2000** [comment]
This is copied and pasted from the docs section on [reset password form](https://django-allauth.readthedocs.io/en/latest/forms.html#reset-password-allauth-account-forms-resetpasswordform). You're saying the section titled "reset_password" applies to set password, not reset password? That's confusing. And you're also saying that the docs are correct as is, and don't require any adjustment (even though the `ACCOUNT_FORMS` setting at the bottom of this section lists "MyCustom**Reset**PasswordForm" whereas the class is defined as "MyCustom**Set**PasswordForm")?

```
reset_password (allauth.account.forms.ResetPasswordForm)
Used on account_reset_password view.

from allauth.account.forms import ResetPasswordForm
class MyCustomSetPasswordForm(ResetPasswordForm):

    def save(self):

        # Ensure you call the parent class's save.
        # .save() returns a string containing the email address supplied
        email_address = super(MyCustomResetPasswordForm, self).save()

        # Add your own processing here.

        # Ensure you return the original result
        return email_address
You have access to the following:

self.users is a list of all possible User objects with matching email address.
settings.py:

ACCOUNT_FORMS = {'reset_password': 'mysite.forms.MyCustomResetPasswordForm'}
```

Thanks.

**Comment by awhileback** [comment]
Arrived here from google, same issue, on Django v3.1.

Why is a fix to incorrect examples in the docs not being merged?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2277
