### ISSUE TITLE
convert http to https in account_confirm_email in django rest auth??

### ISSUE THREAD

**Issue by hemanth-sp** [pennersr/django-allauth#2278]
i am using `path('rest-auth/registration/', include('rest_auth.registration.urls')),` it send email to user  http://www.v...... like this but i need https in production also it uses http instead of https

**Comment by pennersr** [comment]
This does not seem to be pointing to a bug in allauth. Closing ...

**Comment by hemanth-sp** [comment]
so what is the reason i am getting activation url as http?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2278
