### ISSUE TITLE
Question: Redirect user to ID of account user logged in with.

### ISSUE THREAD

**Issue by commadelimited** [pennersr/django-allauth#228]
We're exploring what we'd like to have happen when a user logs in. Right now we direct them into the application with their first account selected. What we'd like to do is auto-select the account which the user provided on login. In pseudo code that might look like this:

1) User logs in, authenticates against 3rd party, gets redirected back to the app.
2) When a successful login is detected, query the database for the db id of the activated user.
3) Redirect them to that route.

In our case our `LOGIN_REDIRECT_URL = '/timeline/'
When the user lands on`/timeline`our JavaScript framework picks it from there and takes the user to`/timeline/#/account/74`, or 12, or 53, whichever happens to be first in the list.

Instead I'd like to simply override LOGIN_REDIRECT_URL and append the following:

`#/account/<account_id>`

I'm searching through the Allauth code and I can't seem to find where that redirect is located so that I can override it in our code. Could you offer a pointer?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/228
