### ISSUE TITLE
Patreon connection works only with their API v1

### ISSUE THREAD

**Issue by Bloodmallet** [pennersr/django-allauth#2282]
Greetings,
connecting to Patreon only works with their v1 API. It would be great, if that could be mentioned in the docs: https://django-allauth.readthedocs.io/en/latest/providers.html#patreon

**Comment by pennersr** [comment]
While I agree that the documentation is indeed lacking in various areas, I am adhering to the debatable principle that keeping open issues around with respect to documentation is not very helpful in improving things. Feel free to submit a pull request...

**Comment by PSNick** [comment]
Hi @Bloodmallet , did you manage to make it work with API v2 by any chance?

**Comment by Bloodmallet** [comment]
I didn't invest additional time, So sadly, no.

**Comment by PSNick** [comment]
@Bloodmallet I don't know if you had to, but if you need to request something from the v2 endpoints I played around with the code until I found a solution:

https://stackoverflow.com/questions/56229785/how-to-find-users-patreon-pledge-tier-using-django-allauth-for-authentication

Hope that helps!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2282
