### ISSUE TITLE
Disable email management

### ISSUE THREAD

**Issue by FranciscoPinto** [pennersr/django-allauth#2294]
Hello,

Thanks for the great app. I'm wondering what The Right Way™️ to disable email management is. Some context: accounts are created on behalf of users, and they should stick to their (institutional) email address.

Should I just override the templates and remove `accounts/email` from `allauth.urls` or is there a more elegant way?

Cheers & thanks once more!

**Comment by FranciscoPinto** [comment]
Closing as per https://django-allauth.readthedocs.io/en/latest/faq.html#why-did-you-just-close-my-issue

**Comment by FranciscoPinto** [comment]
Any interested users please see: https://stackoverflow.com/questions/55908683/disable-email-management-in-django-allauth

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2294
