### ISSUE TITLE
Retrieve logout form via ajax

### ISSUE THREAD

**Issue by ivan-katkov** [pennersr/django-allauth#2295]
Hi all,

I'm trying to retrieve the main forms (`/accounts/login/`, `/accounts/logout/`, `/accounts/signup/`) via ajax request to show them in the modal window. The `login` and `signup` work pretty well, but `logout` gives an empty response with OK status 200. By the way, `curl -v  http://127.0.0.1:8001/accounts/logout/` shows that response  has been redirected `HTTP/1.1 302 Found`.

Any advices?

**Comment by ivan-katkov** [comment]
Diving into the problem I found that responses of the `/accounts/login/`, `/accounts/signup/` are containing form data which are correctly treated by `ajax_response()` function from `adapter.py`.

```
    def ajax_response(self, request, response, redirect_to=None, form=None,
                      data=None):
        resp = {}
        status = response.status_code

        if redirect_to:
            status = 200
            resp['location'] = redirect_to
        if form:
            if request.method == 'POST':
                if form.is_valid():
                    status = 200
                else:
                    status = 400
            else:
                status = 200
            resp['form'] = self.ajax_response_form(form)
            if hasattr(response, 'render'):
                response.render()
            resp['html'] = response.content.decode('utf8')
        if data is not None:
            resp['data'] = data
        return HttpResponse(json.dumps(resp),
                            status=status,
                            content_type='application/json')
```

But in case of `/accounts/logout/` `form=None` and `ajax_response()` return empty `resp`. 

Is this a bug?

**Comment by simo97** [comment]
Hi @ivan-katkov , what are you expecting in fact from this query ?
It seem normal for me, at least to be empty. Maybe you should directly send a POST request to logout the user directly.

**Comment by pennersr** [comment]
Your `curl` example is not doing an AJAX call, this is:

```
curl -X  POST -H "Accept: application/json" http://127.0.0.1:8000/accounts/logout/
{"location": "/"}
```

As you can see, you'll get a JSON response. Not sure what additional data you would expect in that response? Closing for now...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2295
