### ISSUE TITLE
Passwords not hashed

### ISSUE THREAD

**Issue by milossh** [pennersr/django-allauth#2296]
I'm using Django AllAuth for my social login. I don't have custom User signup form, but I do use custom User model. Here's my user model:

```python
class User(AbstractUser):
    is_candidate = models.BooleanField(default=True)
    is_employer = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)

    username = models.CharField(max_length=40, unique=False, default='')

    first_name = models.CharField(_("Ime"), max_length=50, null=True)
    last_name = models.CharField(_("Prezime"), max_length=50, null=True)

    mobile =  models.CharField(_("Telefon"), max_length=20,null=True, blank=True, unique=True)
    address = models.CharField(_("Adresa"), max_length=250, null=True, blank=True)

    def __str__(self):
        return self.email
```

Now, after getting errors that user/password combo on login is not correct for any and all users I tried, I inspected database and noticed that passwords for users registered are not hashed at all. Note that passwords for superusers, the ones I create with _python manage.py createsuperuser_, are hashed properly.

So, after Googling around, I found that I need to override AllAuth's `save_user()` method, so I've set `ACCOUNT_ADAPTER = 'core.social_adapter.UserAccountAdapter'` in my **settings.py**, and added following code to **myproject/core/social_adapter.py**:

```python
class UserAccountAdapter(DefaultAccountAdapter):
    print("using account adapter")
    def save_user(self, request, user, form, commit=True):
        user = super(UserAccountAdapter, self).save_user(request, user, form, commit=False)
        user.is_candidate = True
        user.password = makepassword( form.cleaned_data['password'] )
        print('in custom adapter save_user method')
        print(user.password)
        user.save()
        return user
```

This, however, didn't help at all. Moreover, said `save_user` method doesn't seem to be used at all, as I only get "using account adapter" printed in console.

Did I miss something, or I got this process all wrong now?

**Comment by pennersr** [comment]
https://django-allauth.readthedocs.io/en/latest/faq.html#why-did-you-just-close-my-issue

(FWIW -- allauth properly uses User.set_password() which takes care of all the hashing)

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2296
