### ISSUE TITLE
Compatibility with Bootstrap modals

### ISSUE THREAD

**Issue by alexjayclark** [pennersr/django-allauth#2297]
I've found a great looking package which integrates Django with AJAX-driven forms in Bootstrap 4 modals, but I'm struggling to get it to work with allauth.

One example in the modal package documentation uses the default django signup form, which you can see at the live demo here: https://github.com/trco/django-bootstrap-modal-forms

I've tried to copy the package's signup example by substituting out the default signup form with allauth's signup form, but with no luck.

I thought the issue must be in part because the default signup form is a ModelForm, while allauth's isn't.

So I had a go at turning the django allauth signup form into a ModelForm and then figuring out if there's a way to override the allauth signup form save method but, again, no luck. 

Here's some of my code plus the package's mixin and the allauth signup form save method - any ideas how allauth could be integrated with this package, if at all?

`
# forms.py

    from bootstrap_modal_forms.mixins import PopRequestMixin, CreateUpdateAjaxMixin
    from allauth.account.forms import SignupForm

    class CustomSignupForm(PopRequestMixin, CreateUpdateAjaxMixin, SignupForm, forms.ModelForm):

        class Meta:
            model = CustomUser
            fields = ('username', 'email')

# views.py

    from bootstrap_modal_forms.generic import BSModalCreateView

    class signup(BSModalCreateView):
        form_class = CustomSignupForm
        template_name = 'users/signup2.html'
        success_message = 'Success: Sign up succeeded. You can now Log in.'
        success_url = reverse_lazy('test')

# modal package mixins

    class CreateUpdateAjaxMixin(object):
        """
        Mixin which passes or saves object based on request type.
        """

        def save(self, commit=True):
            if not self.request.is_ajax():
                instance = super(CreateUpdateAjaxMixin, self).save(commit=commit)
            else:
                instance = super(CreateUpdateAjaxMixin, self).save(commit=False)
            return instance

# allauth signup save method

    def save(self, request):
            adapter = get_adapter(request)
            user = adapter.new_user(request)
            adapter.save_user(request, user, self)
            self.custom_signup(request, user)
            # TODO: Move into adapter `save_user` ?
            setup_user_email(request, user, [])
            return user

`

**Comment by pennersr** [comment]
https://django-allauth.readthedocs.io/en/latest/faq.html#why-did-you-just-close-my-issue

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2297
