### ISSUE TITLE
TemplateSyntaxError at /accounts/login/

### ISSUE THREAD

**Issue by MichaelCereda** [pennersr/django-allauth#23]
Hello, i can't fix this error...

'allauth_tags' is not a valid tag library: ImportError raised loading allauth.templatetags.allauth_tags: cannot import name token_kwargs

Template error

In template /home/krilluser/krill_emb/lib/python2.6/site-packages/allauth/templates/socialaccount/snippets/provider_list.html, error at line 1
'allauth_tags' is not a valid tag library: ImportError raised loading allauth.templatetags.allauth_tags: cannot import name  token_kwargs

Seems that there is something wrong with the templatetags....
i have already created the Facebook and twitter apps and installed the app correctly ....

Thanks

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/23
