### ISSUE TITLE
RuntimeError at /accounts/social/connections/

### ISSUE THREAD

**Issue by arctelix** [pennersr/django-allauth#230]
running the latest commit causes:

RuntimeError at /accounts/social/connections/
maximum recursion depth exceeded in **subclasscheck**
Request Method: GET
Request URL:    http://pinimatic-t.herokuapp.com/accounts/social/connections/
Django Version: 1.4.3
Exception Type: RuntimeError
Exception Value:  
maximum recursion depth exceeded in **subclasscheck**
Exception Location: /app/.heroku/python/lib/python2.7/site-packages/django/utils/encoding.py in <lambda>, line 192
Python Executable:  /app/.heroku/python/bin/python
Python Version: 2.7.3

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/230
