### ISSUE TITLE
linkedin login v2 not working (OAuth2Client)

### ISSUE THREAD

**Issue by maxim25** [pennersr/django-allauth#2300]
Started getting the following error this month:

http_error_msg 403 Client Error: Forbidden for url: https://api.linkedin.com/v2/me?projection=(id,firstName,lastName)

Using django-allauth 0.39.1  

My LinkedIn Permissions:
r_emailaddress 3-legged member permission
r_liteprofile 3-legged member permission
w_member_social 3-legged member permission

**Comment by ricardogsilva** [comment]
linkedin recently changed its API [1] and the way allauth was trying to retrieve the `firstName`, `lastName` and `email` in v0.39.1 no longer works. This is already fixed on master, but seems like it was not featured in an official release yet.


[1] - sorry but I can't seem to find any official source for this at the moment

**Comment by ricardogsilva** [comment]
so @pennersr can we humbly ask for a shinny new allauth release?

**Comment by fab10m** [comment]
I have the same issue.

**Comment by fab10m** [comment]
I have the same issue.

**Comment by jhancia** [comment]
Same, a new allauth release to fix this would be great.

**Comment by kiranchari** [comment]
Hi, may I know if this was fixed only in v0.41.0? Thanks

**Comment by kiranchari** [comment]
@ricardogsilva may I ask how you solved this issue? I am on v0.41.0 and still experiencing this. Thanks

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2300
