### ISSUE TITLE
GitHub provider: complete_login assumes the request worked

### ISSUE THREAD

**Issue by peterbe** [pennersr/django-allauth#2301]
See https://github.com/pennersr/django-allauth/blob/f70cb3d622f992f15fe9b57098e0b328445b664e/allauth/socialaccount/providers/github/views.py#L28-L36

It looks like this:

```python
params = {'access_token': token.token}
resp = requests.get(self.profile_url, params=params)
extra_data = resp.json()
```

If that `requests.get` returns a response whose `status_code` is *not* 200, it won't notice. 
Ideally, this should result in some sort of error handling that simply says the login failed. 

As an immediate step, we should inject a `resp.raise_for_status()` in there.

**Comment by pennersr** [comment]
This is already fixed by calling raise_for_status()

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2301
