### ISSUE TITLE
How can I receive user data upon successful login?

### ISSUE THREAD

**Issue by shlomitsur** [pennersr/django-allauth#2302]
Currently I can pass it in the logged_in.txt and into a messages cookie, I would like to return the user data as a json response.like to return the user data as a json response.

**Comment by pennersr** [comment]
https://django-allauth.readthedocs.io/en/latest/faq.html#why-did-you-just-close-my-issue

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2302
