### ISSUE TITLE
Password reset when another user is logged-in

### ISSUE THREAD

**Issue by bitcity** [pennersr/django-allauth#2303]
If user-A is logged-in and another user-B attempts to reset their password, it succeeds while user-A stays logged-in. It is a bit confusing, although I'm not sure if there's a security issue here. It would be better to invalidate the current active session in such case. 

Somewhat like this issue : https://github.com/pennersr/django-allauth/issues/615

**Comment by derek-adair** [comment]
A prompt to clear/invalidate user sessions on password reset would be nice.  Sometimes I would want to keep my sessions logged in on other devices after a password reset, sometimes I want to cleanse the sessions.

@pennersr are there any concerted efforts/feature requests for session management? The ability for users to see what devices are actively logged in could prove useful.

**Comment by pennersr** [comment]
@derek-adair Definitely useful, but there is no feature request about this, yet.

**Comment by derek-adair** [comment]
Would this be related/affected by a centralized session (#1656 / #1832 )?

**Comment by pennersr** [comment]
@derek-adair No, the centralized session is just a `requests` session for outgoing requests executed by the `socialaccount` app, the sessions referred to here are regular `django.contrib.session.Session` sessions.

**Comment by pennersr** [comment]
This is long fixed (110d9b5d3c6195c7777c5b7ebb14c5254afdceca)

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2303
