### ISSUE TITLE
linkedin_oauth2 stopped working

### ISSUE THREAD

**Issue by fab10m** [pennersr/django-allauth#2304]
Hello,

since yesterday I can't signin with linkedin connector anymore. I've been using the linkedin_oauth2 provider for about 2 years and I've already:
- done the upgrade to the last release 0.39.1
- checked that my app is verified by linkedin

This is the error I get
`{ "error": "invalid_request", "error_description": "Unable to retrieve access token: appid/redirect uri/code verifier does not match authorization code. Or authorization code expired. Or external member binding exists" }`

Does anyboby have the same issue?

Regards,
Fabio

**Comment by soccer99** [comment]
Same issue!  Site randomly stopped working with linkedin login.

**Comment by fab10m** [comment]
Sorry for reporting the error.  Actually, the library has not any problem.  The error was originated by the request for a field no longer supported by LinkedIn and the presence of the header's variable "x-li-src: msdk".

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2304
