### ISSUE TITLE
[Question] Is the token's scope/permissions stored anywhere?

### ISSUE THREAD

**Issue by RoryOfByrne** [pennersr/django-allauth#2305]
As part of the signup process, my app acquires a social token with simple permissions. Users can activate extra functionality in my app, which requires extra permissions from Spotify.

I'd like to be able to see which permissions the user's existing token has, so that I can decide if I need to request a new higher-permission token before activating the extra functionality in my app.

Is the scope of a token stored anywhere? If not then I'd like some advice on how best to extend AllAuth to do it myself. I can work on a PR based on my extension, if it's a useful feature.

**Comment by pennersr** [comment]
You can hookup to the user_logged_in signal and inspect the sociallogin passed there....

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2305
