### ISSUE TITLE
AttributeError: 'ModelBackend' object has no attribute 'validate'

### ISSUE THREAD

**Issue by HelloGit100** [pennersr/django-allauth#2306]
Django 2.2.1
Python 3.7.3

settings.py file added the following content:
```
AUTHENTICATION_BACKENDS = (
...
# Needed to login by username in Django admin, regardless of `allauth`
'django.contrib.auth.backends.ModelBackend',
# `allauth` specific authentication methods, such as login by e-mail
'allauth.account.auth_backends.AuthenticationBackend',
...
)
```

- I have set up django-allauth, not create the superuser,

then executed `python manage.py makemigrations && python manage.py migrate`,

Executed `python manage.py createsuperuser --username admin --email admin@admin.com`,
, an error occurred:

> Traceback (most recent call last):
>   File "manage.py", line 21, in <module>
>     main()
>   File "manage.py", line 17, in main
>     execute_from_command_line(sys.argv)
>   File "/home/web/venv_a/lib/python3.7/site-packages/django/core/management/__init__.py", > line 381, in execute_from_command_line
>     utility.execute()
>   File "/home/web/venv_a/lib/python3.7/site-packages/django/core/management/__init__.py", > line 375, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/home/web/venv_a/lib/python3.7/site-packages/django/core/management/base.py", > line 323, in run_from_argv
>     self.execute(*args, **cmd_options)
>   File "/home/web/venv_a/lib/python3.7/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 61, in execute
>     return super().execute(*args, **options)
>   File "/home/web/venv_a/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
>     output = self.handle(*args, **options)
>   File "/home/web/venv_a/lib/python3.7/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 132, in handle
>    validate_password(password2, self.UserModel(**fake_user_data))
>   File "/home/web/venv_a/lib/python3.7/site-packages/django/contrib/auth/password_validation.py", line 47, in validate_password
>     validator.validate(password, user)
> **AttributeError: 'ModelBackend' object has no attribute 'validate'**

- After I created the superuser, then set django-allauth, open url: http://127.0.0.1:8000/admin/auth/user/add/, the following error occurred:

> AttributeError at /admin/auth/user/add/
> 'ModelBackend' object has no attribute 'get_help_text'

How to solve it? Thank you.

**Comment by pennersr** [comment]
Closing -- not clear that this is a bug in allauth.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2306
