### ISSUE TITLE
Small mistake in WeixinOAuth2ClientMixin

### ISSUE THREAD

**Issue by dperetti** [pennersr/django-allauth#2311]
`request`, not `self.request` should be used in `WeixinOAuth2ClientMixin.get_client()`.
It works, but it's inconsistent and requires a workaround if you need to use the mixin in a context where `self.request` is not set.
https://github.com/pennersr/django-allauth/blob/41f84f5530b75431cfd4cf2b89cd805ced009e7d/allauth/socialaccount/providers/weixin/views.py#L56

**Comment by mario** [comment]
Do you have a PR ready? :)

**Comment by pennersr** [comment]
Closed via 8d696fd8

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2311
