### ISSUE TITLE
Global settings not found

### ISSUE THREAD

**Issue by amardesi** [pennersr/django-allauth#2313]
Django version: 1.11.20

I've just installed django-allauth. I'm using the **orcid** provider. I'd like to use the sandbox.orcid.org endpoint, but nothing in `SOCIALACCOUNT_PROVIDERS` is being found, so it's defaulting to default domain orcid.org. 

The issue is that **none** of my `django.conf.settings` have been brought into app_settings

```
(Pdb) p app_settings.__dict__
{'prefix': 'SOCIALACCOUNT_', '__name__': 'allauth.socialaccount.app_settings'}
```

I'm not sure why the app doesn't see my global settings.

**Comment by amardesi** [comment]
Somehow things were resolved after restarting my instance. And I see it's calling things properly now. 
```
(Pdb) p app_settings.PROVIDERS.get(provider_id, {})
{'BASE_DOMAIN': 'sandbox.orcid.org', 'MEMBER_API': False}
```

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2313
