### ISSUE TITLE
How to validate extra field of custom user signup

### ISSUE THREAD

**Issue by gonzaloamadio** [pennersr/django-allauth#2316]
I am using allauth along with django-rest-auth, because I am using django to build an API. So all my process are requests, no django website.

I have my user that has an extra field user_type, and it is a required field for the signup.
So I have overridden the ACCOUNT_ADDAPTER like this

class CustomUserAccountAdapter(DefaultAccountAdapter):                 
    """Override of save method of django-allauth.                      
                                                                       
    As we have an extra field that is required, and we need to save    
    when we register a new user, we need to override the functionality 
    of the DefaultAccountAdapter.                                      
    """                                                                
                                                                       
    def save_user(self, request, user, form, commit=True):             
        """                                                            
        Saves a new `User` instance using information provided in the  
        signup form.                                                   
        """                                                            
        utype = request.data.get('user_type', '')                               
        # As the user_type is required, check it                       
        if not utype:                                                       
            raise ValueError("User Type is required")                  
        user = super().save_user(request, user, form, False)           
        user.user_type = utype                                         
        user.save()                                                    
        return user                                                    

But I think it is not the correct way of raising the error, as it fails with the ValueError. And it is not the proper way of getting the response on my API. I should get a Response and not an Exception

**Comment by gonzaloamadio** [comment]
I have solved it.. the exception should be raised with django rest framework serializers. Like this>

`raise serializers.ValidationError(_("User Type unknown"))`

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2316
