### ISSUE TITLE
OAuth 1 callback URIs seem to ignore settings.ACCOUNT_DEFAULT_HTTP_PROTOCOL

### ISSUE THREAD

**Issue by pacesm** [pennersr/django-allauth#2319]
The OAuth1 renders absolute callback URLs using the django request ignoring the `settings.ACCOUNT_DEFAULT_HTTP_PROTOCOL` configuration.

see https://github.com/pennersr/django-allauth/blob/f70cb3d622f992f15fe9b57098e0b328445b664e/allauth/socialaccount/providers/oauth/client.py#L71

while the OAuth2 callbacks are constructed differently 

https://github.com/pennersr/django-allauth/blob/f70cb3d622f992f15fe9b57098e0b328445b664e/allauth/utils.py#L259

This leads to inconsistent behavior when running the service behind a reverse proxy. The a OAuth2 use HTTPS as configured in the settings while OAuth1 uses HTTP.

It seems to me that both providers should use the same utility method.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2319
