### ISSUE TITLE
Soundcloud no longer uses apps

### ISSUE THREAD

**Issue by morenoh149** [pennersr/django-allauth#2322]
Following the link in the all-auth docs shows message from Soundcloud.

```
SoundCloud Application Registration
Due to the high amount of requests recently received, we will no longer be processing API application requests at this time. We are working to re-evaluate our process to make it more efficient.
```
https://docs.google.com/forms/d/e/1FAIpQLSfNxc82RJuzC0DnISat7n4H-G7IsPQIdaMpe202iiHZEoso9w/closedform

should all-auth change it's soundcloud provider code to use the http api? https://developers.soundcloud.com/docs/api/guide

**Comment by iarp** [comment]
It's not a matter of changing anything, they've stopped allowing people to create apps. If you don't already have an active app you're out of luck at this time.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2322
