### ISSUE TITLE
provider_list.html references undefined variables 

### ISSUE THREAD

**Issue by luto** [pennersr/django-allauth#2324]
Running allauths LoginView with pytests `--fail-on-template-vars` yields the following error:

```
    def __mod__(self, var):
        """Handle TEMPLATE_STRING_IF_INVALID % var."""
        origin = self._get_origin()
        if origin:
            msg = "Undefined template variable '%s' in '%s'" % (var, origin)
        else:
            msg = "Undefined template variable '%s'" % var
        if self.fail:
>           pytest.fail(msg)
E           Failed: Undefined template variable 'scope' in '/tmp/allauthcrash/venv/lib/python3.7/site-packages/allauth/templates/socialaccount/snippets/provider_list.html'
```

I prepared a repo with a full setup and repro-instructions: https://github.com/luto/allauthcrash

**Comment by derek-adair** [comment]
Are tests supposed to pass w/ this flag? Should they?

unsure of the implicaitons here but this is probably closed as a "discussion"

**Comment by luto** [comment]
Code in general and by extension templates should only use variables that actually exists. So I'd argue that tests are supposed to pass with this flag, yes.

**Comment by derek-adair** [comment]
Thanks for your quick response @luto, just doing some triage here for @pennersr and bringing this to his attention.  I would agree that it *should* pass with this flag and I should have been more specific... *Was this written* to pass with this flag and *should it be refactored to be*.  I'd lean on the side of yes as well.

If you would care to take this issue further, which i'd encourage you to, we will need some more detail.

-------------

Please provide details about your environment.

1. Python version
2. Django Allauth Version
3. Relevant configuration (for allauth and providers alike).

**Comment by derek-adair** [comment]
Also I cannot speak for @pennersr, but personally, I **welcome** with open arms any refactoring to make higher quality or more robust tests.... it's hard enough to get users to submit tested code to begin with!

**Comment by luto** [comment]
As this is from 2019 and I currently don't use allauth anywhere I can't help with a python/django version or config specifics. You can probably find everything you need in this repo, should you want to fix this: https://github.com/luto/allauthcrash I agree though that there might be more important things to tackle.

**Comment by pennersr** [comment]
Won't fix for reasons mentioned here: https://github.com/pennersr/django-allauth/issues/1427#issuecomment-1694746219

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2324
