### ISSUE TITLE
Greek locale

### ISSUE THREAD

**Issue by TsimpDim** [pennersr/django-allauth#2327]
Hey there, we are using `django-allauth` on our project and it is really helpful.

However, we want to use the Greek locale and as of now it seems that the translation (and the whole `.po` file itself) is really sloppy. 

We already translated `django-rest-auth` so it would be of great help if we translated the `el` locale anew.

Thanks!

**Comment by gilou** [comment]
Hi, we're having the same issue, and updated the FR translation (which wasn't as sloppy, just outdated) in #2338 so just linking the two PR/issues...

**Comment by TsimpDim** [comment]
Awesome, thanks!

**Comment by pennersr** [comment]
Closing now that #2339 is merged

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2327
