### ISSUE TITLE
Map 'properties' is allowed not to exist as user information in social login user.

### ISSUE THREAD

**Issue by TimelyManner** [pennersr/django-allauth#2331]
Map 'properties' is allowed not to exist as user information in a social login. I've experienced this case so for a while some users were abandoned ever suffering from the unavailability for Kakao social login.

https://github.com/pennersr/django-allauth/blob/543289e0231244a1a64ed0699470956c396ad68f/allauth/socialaccount/providers/kakao/provider.py#L29

This issue has been recognized by the provider, and is guided to use the latest provider's API.  But I think some handling code is still needed for compatibility for the old version of that API.  

I suggest the changed lines of code below can fix this issue. 

`        if 'properties' in data:
            nickname = data['properties'].get('nickname')
        else:   
            nickname = None`

**Comment by pennersr** [comment]
Closed via dc66e01d

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2331
