### ISSUE TITLE
Is it possible to just fill out sign up form with a Provider

### ISSUE THREAD

**Issue by apowell656** [pennersr/django-allauth#2333]
I would really like to just use a provider (like Google) to fill out information because I still need users to provide credit card information for a payment processor.

Any suggestions?

**Comment by AWinterman** [comment]
Unless you want to use javascript to serialize the whole state of your form and then send it to the server before unload, I would recommend just doing sign up/in on a different page from the entry of your sensitive information.

**Comment by pennersr** [comment]
You can use a custom signup form to ask for additional questions...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2333
