### ISSUE TITLE
JWT support with LINE social account

### ISSUE THREAD

**Issue by pincoin** [pennersr/django-allauth#2337]
Hello,

I installed LINE social account, but I was not able to retrieve email address because the its response is JWT.

https://developers.line.biz/en/docs/line-login/web/integrate-line-login/

You can check the section "Decoding and validating ID tokens".

I changed your `allauth/socialaccount/providers/line/views.py` files as follows:

```python
import jwt
import requests
from allauth.socialaccount.providers.oauth2.views import (
    OAuth2Adapter,
    OAuth2CallbackView,
    OAuth2LoginView,
)

from .provider import LineProvider


class LineOAuth2Adapter(OAuth2Adapter):
    provider_id = LineProvider.id
    access_token_url = 'https://api.line.me/oauth2/v2.1/token'
    authorize_url = 'https://access.line.me/oauth2/v2.1/authorize'
    profile_url = 'https://api.line.me/v2/profile'

    decoded_email = ''

    def parse_token(self, data):
        token = super(LineOAuth2Adapter, self).parse_token(data)

        app = self.get_provider().get_app(request=None)

        id_token = data.get('id_token', '')

        decoded_id_token = jwt.decode(id_token,
                                      app.secret,
                                      audience=app.client_id,
                                      issuer='https://access.line.me',
                                      algorithms=['HS256'])

        self.decoded_email = decoded_id_token['email']

        return token

    def complete_login(self, request, app, token, **kwargs):
        headers = {'Authorization': 'Bearer {0}'.format(token.token)}
        resp = requests.get(self.profile_url, headers=headers)
        extra_data = resp.json()
        extra_data['email'] = self.decoded_email
        return self.get_provider().sociallogin_from_response(request,
                                                             extra_data)


oauth2_login = OAuth2LoginView.adapter_view(LineOAuth2Adapter)
oauth2_callback = OAuth2CallbackView.adapter_view(LineOAuth2Adapter)
```

It works fine in my case, but I think it must be improved because of the following reasons:

- It requires an additional package "PyJWT"
- I added an additional field `decoded_email` in order to pass it to `complete_login`.
- `request=None` was passed to get app.
- If `scope` doesn't have `email`, my code doesn't have to be run. 

My code is a concept, but I think you may consider JWT support sooner or later.

Thank you.

**Comment by mbucknell** [comment]
Similarily, I am trying to use Keycloak with jwt tokens and get the JSONDecode error on line 33 of allauth.providers.keycloak.view.py.

Please note that in the current version of django-allauth on pypi, the keycloak provider is in the install. I saw a note on another issue,  https://github.com/pennersr/django-allauth/issues/2545 , that said keycloak had not yet been release but it is there.

Thank you

**Comment by pennersr** [comment]
These days, `pyjwt` is a dependency, so feel free to file a PR in case anything still needs changing. Closing for now.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2337
