### ISSUE TITLE
Change user Group after successful email confirmation

### ISSUE THREAD

**Issue by erev0s** [pennersr/django-allauth#2340]
I am looking into on how can i move a user to a different group after there is a successful confirmation of the email used. 

Any ideas?

**Comment by mario** [comment]
```
@receiver(email_confirmed)
def email_confirmed_(request, email_address, **kwargs):
    user = User.objects.get(email=email_address.email)
```

And then do whatever you want with the user, including changing a group.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2340
