### ISSUE TITLE
Password Reset form exposes registered E-Mails

### ISSUE THREAD

**Issue by BernhardPosselt** [pennersr/django-allauth#2341]
The current reset form tells you if an address does not exist which is problematic if you are using your E-Mail to log in. By default you should get a message that an E-Mail was sent to that address regardless if the user exists or doesn't.

Would you be open for accepting a pull request for this issue?

**Comment by giant995** [comment]
I was about to create the same issue, so I will contribute with the [OWASP guide](https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html#incorrect-and-correct-response-examples) which proposes a correct response:

> If that email address is in our database, we will send you an email to reset your password

**Comment by pennersr** [comment]
This does not address the whole story. Closing -- #1307 is tracking these issues.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2341
