### ISSUE TITLE
Can allauth refer to another allauth provider?

### ISSUE THREAD

**Issue by groundswel** [pennersr/django-allauth#2345]
Can one allauth installation refer to another allauth provider? This will allow to break up a monolithic django application to multiple micro services.

**Comment by pennersr** [comment]
https://django-allauth.readthedocs.io/en/latest/faq.html#why-did-you-just-close-my-issue

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2345
