### ISSUE TITLE
Twitch Kraken API 

### ISSUE THREAD

**Issue by JayCarney** [pennersr/django-allauth#2348]
Noticed the repo's been updated to no longer use the twitch kraken API, but the version of the package in pypi doesn't have these changes. [Deprecated kraken API update from Twitch](https://discuss.dev.twitch.tv/t/change-in-access-to-deprecated-kraken-twitch-apis/22241)

August 21 2019 - Twitch test breaking the existing behavior
August 22 2019 - Planned 24hr test that will break the API again

Not sure what their real cut-off date is for the API, but looks like just publishing a new release should move over to the new API

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2348
