### ISSUE TITLE
Password change template needs to include link for resetting forgotten password

### ISSUE THREAD

**Issue by Flimm** [pennersr/django-allauth#2349]
The `account_change_password` view asks for your current password, and the new password that you want to set. However, what if you have forgotten your password? You could log out and then click on the "forgotten password" link, but this may not be obvious to all users.

I suggest adding a link in the `account_change_password` template, linking to the `account_reset_password` view.

**Comment by pennersr** [comment]
Closed via d6dbec11

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2349
