### ISSUE TITLE
Populating users' data from a social login's extra info after they sign up is painful

### ISSUE THREAD

**Issue by gcbirzan** [pennersr/django-allauth#235]
While I can do it in the view after linking an account, last and first names have different names in different providers, and this info is thrown away after the link.

Ideally, there should be a way to add a callback to the 'linking' process, via the adapter I guess.

**Comment by prackels** [comment]
Hello, 
i want to get the data of user signed in profile from extra_data
how to get it??

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/235
