### ISSUE TITLE
Twitch Social Network Login Failure

### ISSUE THREAD

**Issue by ckp1701** [pennersr/django-allauth#2350]
0.39.1

![image](https://user-images.githubusercontent.com/14226241/63595581-90c59400-c5b9-11e9-982e-dcc91fb3637b.png)

**Comment by pennersr** [comment]
It is not obvious from this bug report that there is an issue in allauth, could be misconfiguration just as well. Will have to close this.

**Comment by ckp1701** [comment]
Updated allauth to v 0.40.0 fixed this error. There was no need to update configuration.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2350
