### ISSUE TITLE
OpenID Installation issue

### ISSUE THREAD

**Issue by stuck1233333** [pennersr/django-allauth#2351]
Under settings.py, if I add 'allauth.socialaccount.providers.openid' to INSTALLED_APPS,
I get the following error: 

ModuleNotFoundError: No module named 'allauth.socialaccount.providers.openidcorsheaders'

Any recommendations?
Thanks!

**Comment by pennersr** [comment]
Likely you are missing a comma in your settings somewhere. Closing, not a bug in allauth.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2351
