### ISSUE TITLE
Attempting to add Vimeo Support

### ISSUE THREAD

**Issue by Enigmatical** [pennersr/django-allauth#236]
Hi,

I am attempting to add Vimeo support to allauth by duplicating the LinkedIn provider (which uses OAuth 1.0) and adapting it for Vimeo (https://developer.vimeo.com/apis/advanced).

While everything appeared to be functioning correctly, I have ran into a considerable snag when attempting to log in.  I keep repeatedly getting this error:

SSLHandshakeError at /accounts/vimeo/login/

[Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

I found that this issue seems very similar to #113.  I tested both hitting Vimeo's OAuth endpoints with requests and httplib2 and found that requests works and httplib2 does not from my AWS instance.

It appears that while you ended up fixing the OAuth 2.0 providers to use requests, the OAuth 1.0 providers (using python-oauth2) are still using httplib2 which is known to have problems in virtualenv.

So my question is two-fold:  Is there anything I can do to work out the root cause of this problem?  I had the belief that configuring a provider outside the provided ones would not be terribly difficult.

Second, if my first issue seems too difficult to diagnose, would you be interested in adding Vimeo support to allauth?  As stated, it seemed relatively straightforward until I hit the snag.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/236
