### ISSUE TITLE
Send password reset to verified emails

### ISSUE THREAD

**Issue by vsemionov** [pennersr/django-allauth#2360]
Hi @pennersr  and other authors,

Thank you very much for this wonderful project!

I see that `ResetPasswordForm` may send password reset links to any registered emails, not just verified ones. A user could enter an incorrect email address during registration. If `ACCOUNT_EMAIL_VERIFICATION` is not `mandatory`, the user may keep using their account for a while. Later, someone could enter the same same email in the password reset form. It could either be the registered user, whose browser autocompleted the stored incorrect email. But it could also be a malicious person who owns the entered email. In both cases, the owner of the email will now have access to another person's account.

What is your opinion about this scenario? Is it a missed case, or is the behavior of `allauth` intentional?

I also think that even if password reset emails are sent to verified emails, that would still not be completely secure. Currently, anyone with the email confirmation link can verify the email and send the password reset link to themself (if they open the link before it expires). To prevent this, the email verification should be made more "real" (by guaranteeing the person opening the link is the account owner). For example, `ConfirmEmailView` could require that the owner of the email is logged in before confirming the email.

What do you think?

Best regards,
Victor

**Comment by pennersr** [comment]
The email address is the key to the account. If a user adds somebody else's email to his account, he is indeed handing over his account key to that user. I do not consider that a security issue, but rather an error on the side of the user.

Your second part I do not fully comprehend. You mention "anyone with the email confirmation link". That assumes that malicious users have access to the user's mailbox. If that is the case, whatever you would change in the confirm email view is not going to help, as the malicious user can always kick off the password reset flow, intercept the mail, and change the password.

**Comment by vsemionov** [comment]
Thank you for responding.

Indeed, adding someone else's email address to your account is an error (unless done deliberately). However, I am trying to protect users from as many mistakes as possible.

By "anyone with the email confirmation link", I meant someone whose address was added (by mistake). Let me explain my concern with an example. A new user (person A) creates an account and makes a typo in their email address. By coincidence, the mistyped address actually exists, and belongs to person B (whose name is similar). Person B could verify the email address by following the link in the email. Person A does not notice that the email is now verified, despite that they didn't receive a confirmation email). All parts of the website, that require a verified email, are now accessible, so person A engages further and enters sensitive information. Person B now resets the password (by requesting a password reset email to their own address) and locks person A out. He gains full control of the account with all its data.

I have tested this scenario and I think currently there is no built-in mechanism to prevent it. I would like to have as much confidence as possible, that a verified address truly belongs to the account owner, and only they could reset the password. In my application, I tweaked the behavior of allauth to address the two points, by:
* Requiring authentication in the email confirmation view, and checking that the authenticated user is the owner of the confirmed email (request.user.id == email_confirmation.email.user.id). The downside is that the user could be required to enter credentials. But that would only be a problem if they have logged out.
* In the reset password form, find users with an email that not only matches the requested one, but it also verified. The downside is that an unverified user could be permanently locked out. But my application requires verification before adding any valuable data, so losing an unverified account would not be a big deal.

If I made these changes to allauth, I would probably make both of them configurable. I would either keep the current behavior by default, or clearly note the changes.

Maybe I am too careful, but I also saw your (or another author's) comment in `allauth.account.views.login_on_confirm()`. I found it very cool that corner cases like this are predicted and addressed. I was surprised that allauth simply accepts the verification without somehow checking if it is authentic. But maybe it's just me, being too careful. I checked Facebook's verification process. If I recall correctly, they send you a verification code in the confirmation email. They also associate your browser with the new account (either by a cookie or session data), so most users could simply click the link to verify. On the other hand, I came across a post in a 3rd party website with instructions how to take ownership of accounts of another big social application, if your email was added by mistake (I cannot confirm this is true).

Sorry for the long comment. I hope it helps to explain my concerns.

Best regards,
Victor

**Comment by pennersr** [comment]
Thanks for your elaborate response. 

What I do not understand is that if your goal is to "...protect users from as many mistakes as possible..." -- then why are you not using mandatory email confirmation in the first place? Because that option is by definition the safest way of configuring things, and it would prevent all of these scenario's from happening.

While this may not be a big deal for your project, from allauth perspective it is not acceptable to offer an out-of-the-box scenario where users can become locked out. So I would not be in favor of changing the default behavior when mandatory email verification is not used. Though, I am not against adding new configuration options to handle your use case (e.g. something like ACCOUNT_PASSWORD_RESET_VERIFIED_ONLY=True|False and ACCOUNT_EMAIL_CONFIRMATION_REQUIRES_LOGIN=True|False),

**Comment by vsemionov** [comment]
Sorry for the delayed response.

I am not using mandatory email confirmation, because I want the signup process to be as easy as possible. Some features are accessible to unverified users. But other features, which involve communication, require a verified address.

You made a good point about having a scenario, where users can become locked out, even if they are just 'light' users, from my project's perspective. To alleviate that, I made the following change. Password reset links can now be sent to unverified emails, but **only** if the account doesn't have any verified emails. If the requested email is unverified, but the account has a verified one, a message is returned, asking to specify the user's verified email.

I am not able to implement the confirmation and password reset changes in `allauth` directly. But I can send you snippets from my code, which tweak the behavior of `allauth`.

Here's how I tweaked it to require the user to login to confirm their email:
```python
_default_confirm_email = ConfirmEmailView.dispatch

def _confirm_email(self, request, *args, **kwargs):
    try:
        confirmation = self.get_object()

        if request.user.id != confirmation.email_address.user_id:
            # the login template will see that the user is already authenticated
            # and will ask them to login with the user that has access to the requested URL
            next = request.get_full_path()
            return redirect_to_login(next)

    except Http404:
        # invalid/expired signatures and missing emails will be handled by the default view
        # this does not give up the existence of the email, because its signature is checked first
        pass

    return _default_confirm_email(self, request, *args, **kwargs)

ConfirmEmailView.dispatch = _confirm_email

ConfirmEmailView.dispatch = method_decorator(login_required)(ConfirmEmailView.dispatch)
```

Here's my (now replaced) code to send password reset links only to verified emails:
```python
class CustomResetPasswordForm(ResetPasswordForm):
    @staticmethod
    def _filter_users_by_verified_email(email):
        users = User.objects.filter(emailaddress__verified=True, emailaddress__email__iexact=email)
        users = tuple(users)
        return users

    def clean_email(self):
        # send password reset links only to verified emails

        email = self.cleaned_data['email']

        email = get_adapter().clean_email(email)

        self.users = self._filter_users_by_verified_email(email)

        assert len(self.users) <= 1, 'Cannot reset the passwords of multiple accounts.'

        if not self.users:
            raise ValidationError('The email address is unknown or unverified.')

        return self.cleaned_data['email']
```

And here's the code to send password reset links to unverified emails only if the user doesn't have a verified one:
```python
class CustomResetPasswordForm(ResetPasswordForm):
    def clean_email(self):
        # send password reset links to unverified emails only if the user doesn't have a verified one

        email = super().clean_email()

        assert len(self.users) == 1, 'Cannot reset the passwords of multiple accounts.'

        user = self.users[0]

        email_filter = Q(email__iexact=email)
        verified_addresses = user.emailaddress_set.filter(verified=True)
        verifications = verified_addresses.aggregate(total=Count('*'), matching=Count('email', filter=email_filter))

        if verifications['total'] and not verifications['matching']:
            # the user has verified addresses, but requested an unverified one
            raise ValidationError('Please specify a verified email address.')

        return email
```

I hope this helps. I am fine if these changes are not suitable for `allauth`, or not a priority. If you need any additional information, please let me know.

Best regards,
Victor

**Comment by 9mido** [comment]
In the code below I am not using a CustomResetPasswordForm like vsemionov did. I am editing the main allauth forms.py ResetPasswordForm. If anyone could assist by making a setting to turn this on or off, please submit a PR using this method. 

I was getting an error using vsemionov's code on the main allauth forms.py ResetPasswordForm. 

Here is my solution:

Forms.py ResetPasswordForm class:

```
from allauth.account.models import EmailAddress
from django.contrib.auth.models import User

    def clean_email(self):
        email = self.cleaned_data["email"]
        email = get_adapter().clean_email(email)
        self.users = filter_users_by_email(email, is_active=True)
        unverified_emails = tuple(EmailAddress.objects.filter(verified=False).values_list('email', flat=True))
        if email in unverified_emails:
            raise forms.ValidationError("Only verified e-mails can reset passwords")
        return self.cleaned_data["email"]
```

**Comment by pennersr** [comment]
Closing for reasons mentioned here: https://github.com/pennersr/django-allauth/issues/2360#issuecomment-534259235

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2360
