### ISSUE TITLE
SignUp Setting Session ID in Cookie

### ISSUE THREAD

**Issue by srinivasaravind5** [pennersr/django-allauth#2366]
I have the setting to of email confirmation to mandatory, still after signup allauth sets the session id in the cookie.

**Comment by muhalitas** [comment]
no one cares issues. what a package ha.

**Comment by pennersr** [comment]
The signup view is accessing the session, for example to unstash a verified email address. Though, accessing the session should not be mistaken with getting incorrectly authenticated while the email is not confirmed. Closing -- not clear what the issue is here.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2366
