### ISSUE TITLE
Auth0 provider does not extract picture URL from User profile when creating SocialAccount

### ISSUE THREAD

**Issue by bhatt40** [pennersr/django-allauth#2370]
The issue appears to occur in line 28: `allauth/socialaccount/providers/auth0/views.py`

The data returned from the Auth0 profile includes the picture URL, but this is not extracted when creating the extra_data field in the SocialAccount instance.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2370
