### ISSUE TITLE
Social Network Login Failure: The domain of this URL isn't included

### ISSUE THREAD

**Issue by RayChao2016** [pennersr/django-allauth#2371]
Hi 
I used django-allauth to login my website via Facebook.
I did login with Facebook successfully from 2019/Aug., but I encountered "Social Network Login Failure" from this week.
I searched several blogs and questions on stackoverflow, and didn't find a way to fix this.

I added Code: {{ auth_error.code }}, Error: {{ auth_error.exception }} to show the error codes:
Here is the result:

Code: unknown 
Error: Error retrieving access token: b'{"error":{"message":"Can\'t load URL: The domain of this URL isn\'t included in the app\'s domains. To be able to load this URL, add all domains and sub-domains of your app to the App Domains field in your app settings.","type":"OAuthException","code":191,"fbtrace_id":"xxxxxxxx"}}'

This one is the same as my problem:
https://stackoverflow.com/questions/55207178/social-network-login-failure-the-domain-of-this-url-isnt-included

Can anyone give me some suggestions? thanks!

**Comment by pennersr** [comment]
https://django-allauth.readthedocs.io/en/latest/faq.html#why-did-you-just-close-my-issue

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2371
