### ISSUE TITLE
Allow Social Application secret key to be blank in admin

### ISSUE THREAD

**Issue by thenewguy** [pennersr/django-allauth#2372]
Connecting with ADFS does not require a secret key.  With older versions of ADFS it was ignored when a secret key was provided but not needed, so the admin could be set to anything, like "this-key-is-not-used".  However, the newest version of ADFS responds with an error when providing a secret key.

Here is my ADFS allauth provider: https://github.com/thenewguy/django-allauth-adfs

It would be helpful to mark secret key on the SocialApplication model as blank=True.  Right now, secret key has to be stripped at the command line and the SocialApplication for adfs cannot be edited in the admin as a result.

**Comment by thenewguy** [comment]
Please let me know if this issue is accepted and I will create a patch and PR

**Comment by pennersr** [comment]
Closed via 93eed9e2

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2372
