### ISSUE TITLE
Unicode normalization for username

### ISSUE THREAD

**Issue by getup8** [pennersr/django-allauth#2377]
In Django's sign up and user authentication forms, they use a custom field called `UsernameField` for the username which unicode-normalizes the username:
https://github.com/django/django/blob/6c9778a58e4f680db180d4cc9dc5639d2ec1b40c/django/contrib/auth/forms.py#L62

```python
unicodedata.normalize('NFKC', super().to_python(value))
```

It doesn't seem like this is currently implemented here, but wondering if it should / could be?

**Comment by pennersr** [comment]
See: https://github.com/pennersr/django-allauth/blob/master/allauth/utils.py#L44

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2377
