### ISSUE TITLE
Session Id / CSRF Token issue with bookmarklets

### ISSUE THREAD

**Issue by arctelix** [pennersr/django-allauth#238]
I'm not sure exactly what is going on yet, but i just realized that there is an issue with session id's and csrf tokens when you have a bookmarklet.

My site uses a bookmarklet that logs in via ajax with CORS.

Prior to installing allauth when a user was logged in or out of the site and they attempted to use the bookmarket the same session and csrf token would be used and they would not have to log in via the bookmarklet.

Now if a user is logged in to the site they are promoted to log in again via the bookmarkelt.  While testing i could be logged into the bookmarklet as one user and logged into the site as another user simultaneously. The worst part is there is no way to log out with the bookmarklet unless you clear the browser cookies.  This could leave a user account vulnerable.

Unfortunately i just don't know enough about session's and tokens to trouble shoot this.  If you point me in the right direction id be happy to give it a shot.

UPDATE: Actually it's working fine with IE & Safari, Chrome has the issue...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/238
