### ISSUE TITLE
using {% url %} in {% provider_login_url  next="{% url %}" %}

### ISSUE THREAD

**Issue by harem234** [pennersr/django-allauth#2382]
it is not possible to use next without hardcoding the url!
even {% url 'someexample' as next %} won't parse: {% provider_login_url  next="{{ next }}" %}

**Comment by pennersr** [comment]
Not sure what you mean, but that is invalid Django template syntax. Given a next variable, you would need to do {% foo next=next %}

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2382
