### ISSUE TITLE
Duplicate message being displayed to user in EmailView

### ISSUE THREAD

**Issue by scottwoodall** [pennersr/django-allauth#2385]
While working with adding/verifying/removing email addresses I was receiving duplicate messages being displayed back to the user. These lines of code seem to be applicable to this scenario:

- https://github.com/pennersr/django-allauth/blob/416b5fb8ecb2a54139e992f67201b9b6038c54fa/allauth/account/views.py#L391
- https://github.com/pennersr/django-allauth/blob/416b5fb8ecb2a54139e992f67201b9b6038c54fa/allauth/account/views.py#L431

**Comment by scottwoodall** [comment]
This ended up not being an issue. I had the messages template included twice.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2385
