### ISSUE TITLE
Logout via AJAX results in empty content

### ISSUE THREAD

**Issue by cassandra** [pennersr/django-allauth#2386]
I had code that worked in v0.31.0 and not in v0.39.1 in terms of the response for the LogoutView from an AJAX request.  I realize that there was a change so that it now returns JSON instead of HTML, but what I am finding is that the JSON it returns is an empty dictionary.  Tracing through the code, I think I understand why.

* In views.py:772:LogoutView, it calls _ajax_response() with only a request and response and no form or data argument.
* In views.py:59 inside _ajax_response(), it calls the adapter.py:332:ajax_response() passing along the same empty form and data.
* At adapter.py:341 is the place that would render the content of the response, but it is nested inside a conditional on there being a non-empty form.
* In fact, the only way that the "resp" JSON can become non-empty is if "form" and/or "data" is non "None".
* Thus, it seems like the LogoutView will always result in empty content in the AJAX context.

**Comment by pennersr** [comment]
You only end up at line 772 of views.py if you are doing a GET request while logging out is confirmed to expect POST requests. So, no logout happens in that case. In case a logout occurs, you'll get a redirect  URL passed back.

**Comment by cassandra** [comment]
I was not expecting the GET to result in a logout, but to render the logout confirmation dialog.  Maybe this is particular to my case where I call GET itself from an AJAX context and need that to return my confirm dialog content (from an overridden template of mine).

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2386
