### ISSUE TITLE
Language switches to EN-US right after posting SignupForm

### ISSUE THREAD

**Issue by lggwettmann** [pennersr/django-allauth#2393]
Hey guys,

I have django set up for the languages en, nl and de, but not for en-us, en-gb etc. I have a custom sign up form:
```
class SignupForm(forms.ModelForm):
    receive_newsletters = forms.BooleanField(initial=True, required=False)

    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name',]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        ...       

    def signup(self, request, user):
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.save()
        if self.cleaned_data['receive_newsletters'] == True:
            subscribe_to_basic_newsletters.apply_async([user.pk], countdown=60)
```
Everytime a user signs up from 'en/accounts/signup/' or 'nl/accounts/signup/' and posts the data, they get redirected to '/en-us/accounts/confirm-email/' instead of '/en/accounts/confirm-email/' or ''/nl/accounts/confirm-email' - what could the reason be for that?

All other language-related functions work great on my site. Thanks for any help.

**Comment by lggwettmann** [comment]
Any idea on why this is anyone?

**Comment by lggwettmann** [comment]
Has anyone any idea on how to debug this?

**Comment by IProudNoob** [comment]
I have this problem to.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2393
