### ISSUE TITLE
PermissionDenied exception with Discord

### ISSUE THREAD

**Issue by LucasCoderT** [pennersr/django-allauth#2394]
version: ``0.40.0``

Hi, I'm new to allauth,

When trying to authenticate with the `DiscordOAuth2Adapter`  I've ran into an interesting issue where I would get a ``PermissionDenied`` error and I've managed to track it down to:
https://github.com/pennersr/django-allauth/blob/dac31fdac2c13a97829e6879e09431c735abab4e/allauth/socialaccount/models.py#L318-L319
It seems that happens because in `OAuth2CallbackView.dispatch` `SocialLogin.stash_state`` is never called. 

I tried adding a call to stash_state inside and then https://github.com/pennersr/django-allauth/blob/dac31fdac2c13a97829e6879e09431c735abab4e/allauth/socialaccount/providers/oauth2/views.py#L140 ``returns None`` because The request returned by discord has no ``state`` key.

**Comment by Bragegs** [comment]
I am experiencing the same with linkedin_oauth2 and feel like I am missing something basic🤔

**Comment by pennersr** [comment]
https://django-allauth.readthedocs.io/en/latest/faq.html#why-did-you-just-close-my-issue

**Comment by Subash0711** [comment]
I am facing the same issue with Azure. How can I resolve this issue?,its returns same PermissionDenied exception.
`            if self.adapter.supports_state:
                login.state = SocialLogin.verify_and_unstash_state(
                    request, get_request_param(request, "state")
                )
            else:
                login.state = SocialLogin.unstash_state(request)  
            return complete_social_login(request, login)
        except (
            PermissionDenied,
            OAuth2Error,
            RequestException,
            ProviderException,
        ) as e:
            return render_authentication_error(
                request, self.adapter.provider_id, exception=e
            )`

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2394
