### ISSUE TITLE
Template issues

### ISSUE THREAD

**Issue by Heldroe** [pennersr/django-allauth#24]
Hi.

I've got the exact same problem as [Issue #19](https://github.com/pennersr/django-allauth/issues/19) but it is closed and no answer about the problem.

It is not limited to the login page.

The line causing the error in the template is :
`{% openid_login_url openid="https://www.google.com/accounts/o8/id" %}`

Exception returned is "KeyError" at line 17 of [allauth/openid/templatetags/openid_tags.py](https://github.com/pennersr/django-allauth/blob/master/allauth/openid/templatetags/openid_tags.py) : 
`request = context['request']`

I can't find what is causing this.

Thanks.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/24
