### ISSUE TITLE
gmail dot "." problem

### ISSUE THREAD

**Issue by fanckush** [pennersr/django-allauth#2402]
I have a social login (google login button among others). As you know google doesn't take into account dots. (some.email@gmail.com is the same as someemail@gmail.com)
somehow a logged out user clicked on the "connect with google" button and typed his email without a dot and it got registered as a new user. I don't use usernames cuz i have 
```  python
USERNAME_FIELD = 'email' #in my custom user model
```

I understand that this is not a issue with allauth itself but how can I fix this problem? I don't have access to the part that validates if the email already exists since that is done by allauth automatically. 
The "connect with google button" will create an account if the user never logged in before, and if the user has logged in before then it will simply log them in.

**Comment by safwanrahman** [comment]
I think you can extend the adapter and overwrite the `clean_email` method.
```python
    def clean_email(self, email):
        email = email.replace("+", "") 
        return email.lower()
```

**Comment by fanckush** [comment]
Thanks. but why are you replacing "+" with ""? shouldn't it be:
`email = email.replace(".", "")` ?

**Comment by pennersr** [comment]
For gmail, a user can create multiple addresses using dots and plus all leading to the same physical mailbox. Now, you could argue that the user might have good reasons to want to both a "johndoe@gmail.com" account, and a "john.doe@gmail.com" as well as a "john.doe+betatest@gmail.com". I don't think it would make a good default to prevent users from doing so. If they want a second account, they will always find a way to do so. And as @safwanrahman mentions, if you really have project specific requirements that would require canonicalized email addresses, then you can set this up via the adapter method.

**Comment by alpha-nome** [comment]
> I think you can extend the adapter and overwrite the `clean_email` method to something like following.
> 
> ```python
>     def clean_email(self, email):
>         email = email.replace("+", "") 
>         return email.lower()
> ```

Can you please explain in detail in how to which adapter to extend and overwrite? Thanks

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2402
