### ISSUE TITLE
Can't set ACCOUNT_EMAIL_SUBJECT_PREFIX to None (or empty)

### ISSUE THREAD

**Issue by taewookim** [pennersr/django-allauth#2409]
Version - Latest (as of 12/13/2019) via pip install, for both django and django-allauth

Issue - Emails are still showing default site ("[example.com")

```
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = False
ACCOUNT_SESSION_REMEMBER = True
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USER_MODEL_USERNAME_FIELD ="username"
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_EMAIL_SUBJECT_PREFIX=None # tried "" as well
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION=True
```

Thought it was cache issue, so I tried clearing cache via

`python` manage.py clear_cache 

and 

`Site.objects.clear_cache()`

Emails are still showing "[example.com]" prefix.

**Comment by pennersr** [comment]
Please put a breakpoint here, setting it to None should really work:

![image](https://user-images.githubusercontent.com/201022/70847899-2d15ee00-1e6a-11ea-8ce8-c48a3fea3048.png)

Closing this for now, if while debugging you find anything indicating allauth is wrong somewhere, please reopen.

**Comment by bmsleight** [comment]
Wow this was a fun bug - I'd like to reopen.
Setting:-
ACCOUNT_EMAIL_SUBJECT_PREFIX = '[FiveFunThings]'
Gives me emails with subject of 
"[example.com] Password Reset E-mai"

Setting:-
ACCOUNT_EMAIL_SUBJECT_PREFIX = 'FiveFunThings '
Gives me emails with subject of (nb no space):-
FiveFunThingsPassword Reset E-mail

Setting:-
ACCOUNT_EMAIL_SUBJECT_PREFIX = 'FiveFunThings >'
Gives me emails with subject of:-
FiveFunThings >Password Reset E-mail



Note I changed  format_email_subject(self, subject):
 to 
return force_str(subject)  - I stil got [Example.com] 
return str("[Fun]") + force_str(subject) - I stil got [Example.com]
return str("123[Fun]") + force_str(subject) - I then got the subject changed/

Thanks for django-allauth, makes my projects better,

**Comment by DirectDuck** [comment]
I have the same problem, the only workaround I found is overriding **render_mail** in custom account adapter:
`def render_mail(self, template_prefix, email, context):
        msg = super().render_mail(template_prefix, email, context)
        msg.subject = "Message from *CHANGE_TO_YOUR_PREFERENCE*"
        return msg`

**Comment by rzwink** [comment]
After many similar iterations, I found that gmail was displaying the wrong subject line, despite having changed it my Sites object and prefix setting.  Meaning, when I select "View Original" within gmail, I see the expected subject line.  Posting here in case it helps another poor soul.

**Comment by angryjoker4** [comment]
You can use a char invisible that string not be empty and allauth don't use default settings

ACCOUNT_EMAIL_SUBJECT_PREFIX = "\u200B"

**Comment by syedhaideralizaidi** [comment]
Just go to your base settings file and add this line:
ACCOUNT_EMAIL_SUBJECT_PREFIX = "\u200B"

This will work.

**Comment by pennersr** [comment]
For the record:

- `ACCOUNT_EMAIL_SUBJECT_PREFIX = None` means allauth will do its default, and generate `[Site] Subject` style subjects.
- `ACCOUNT_EMAIL_SUBJECT_PREFIX = ""`, or any other string, means allauth will just use that as is. So, `""` results in no prefix at all.

There is no need to use constructs like `"\u200B"`

**Comment by khalidelassaad** [comment]
For other travelers who arrive here, this is the experience I have on the following installation:
```
Django==5.1.4
django-allauth==65.3.0
django-allauth-ui==1.5.3
```
- `ACCOUNT_EMAIL_SUBJECT_PREFIX = ""` TWO different unexpected behaviors
  - email failing to send altogether
  - default subject prefix still used
- `ACCOUNT_EMAIL_SUBJECT_PREFIX = "\u200B"`
  - Removed the email prefix, email subject now displayed as I expected.
  
The issue persists, the `\u200B` workaround seems sketchy, but delivers the desired results. 🙃

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2409
