### ISSUE TITLE
Facebook redirect appending #_=_ to the URL.

### ISSUE THREAD

**Issue by commadelimited** [pennersr/django-allauth#241]
It looks like there's something going on with Facebook's redirect scheme which appends the string `#_=_` to the URL of the redirect.

In other words, rather than dropping me onto my applications `LOGIN_REDIRECT_URL` of `/timeline/, I'm being taken to`/timeline/#_=_`.

The docs on Facebook (https://developers.facebook.com/blog/post/552/) indicate they made a change in 2011 relating to this:

`This week, we started adding a fragment #_=_ to the redirect_uri when this field is left blank. Please ensure that your app can handle this behavior.`

I'm unsure what `redirect_uri` is suppose to be though. Is that an app setting on facebook.com or is that a value in our Django app that isn't being properly passed?

**Comment by JulianSchneider** [comment]
Its 2016 and I'm having the same issue, managed to get it removed with the javascript, that still leaves the hashtag though. Anyone found out why this is happening? I'm basically using vanilla allauth.

**Comment by rishabhiitbhu** [comment]
@ACPK for me it was `#_=_` that was being appended, modified your js code with `indexOf("#_=_")` and it works!.
thanks :)

**Comment by SimeonVSimeonov** [comment]
> Its 2016 and I'm having the same issue, managed to get it removed with the javascript, that still leaves the hashtag though. Anyone found out why this is happening? I'm basically using vanilla allauth.

`  <script type="text/javascript">
    if (window.location.hash && window.location.hash === '#_=_') {
      window.location.hash = '';
      history.pushState('', document.title, window.location.pathname);
    }
  </script>`

It will remove and hashtag.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/241
