### ISSUE TITLE
REST: Change password and email

### ISSUE THREAD

**Issue by sowinski** [pennersr/django-allauth#2410]
Hi,

I build a frontend with VueJS/Nuxt. Is it possible to talk over REST with django-allauth to change the password or to change the e-mail adresse?

If not, how would you do this?

**Comment by pennersr** [comment]
Yes, simply post AJAX requests to the regular views and you will get a JSON response back in return.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2410
