### ISSUE TITLE
Custom OAuth Provider

### ISSUE THREAD

**Issue by mbrahimi617** [pennersr/django-allauth#2415]
Is there a way to use this package to authenticate a Django user via a custom OAuth provider? I could probably write a custom authentication backend to exchange a code query parameter for a token, then decode it and map the attributes to the User model which I either get or create, then login. However, I'd like to know if this functionality exists for private providers that aren't Google, Facebook, etc.

**Comment by deegeenl** [comment]
There are `oauth` and `oauth2` generic providers built-in, can't you use those? If your custom provider conforms to either then they should just work. Most of the other providers are built as subclasses of `OAuth2Provider` so just take a look how it's done and do the same for your provider.

**Comment by mbrahimi617** [comment]
I'm not looking for a provider. I'm an intern at HPE which has a portal to provision OAuth client keys and secrets with their respective authorization, token, and redirect  URLs. I have no idea where to start aside from writing endpoints myself but I'd like to authenticate via SSO in my frontend and sign in an associated Django User object by handling the redirect URL passing the code query param from the SSO.

**Comment by pennersr** [comment]
So, HPE offers an OAuth provider and you would like to use that with allauth just like one of the many builtin ones? That is definitely possible. You could start by simply copying one of the existing ones, say allauth.socialaccount.providers.google as a starting point, end then modify that to match the HPE endpoints. Your code need not reside within the allauth repo, you can put it in yourproject.apps.whatever and it should just work. Closing, not an issue in allauth.

**Comment by mbrahimi617** [comment]
There is nothing about the oauth and oauth2 providers in the documentation under providers so I have no idea how to use it, but I'm sure there are others who would want a more open ended solution for private or less well known providers that aren't the likes of Google and Facebook. Of course, you would need to manually provide the endpoints and client details. Furthermore, does allauth simply authenticate or does it authorize as well? Ideally I'd like the authentication to associate with a Django User via get or create so I can use permissions on my API.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2415
