### ISSUE TITLE
How to retrieve the Facebook app ID

### ISSUE THREAD

**Issue by danihodovic** [pennersr/django-allauth#2416]
When using the Facebook python business SDK (https://github.com/facebook/facebook-python-business-sdk) it requires the App ID in API calls. Is it possible to retrieve this using allauth?

Here is the getting started example which requires the app ID:
https://developers.facebook.com/docs/business-sdk/getting-started#python

```py
import sys
sys.path.append('/opt/homebrew/lib/python2.7/site-packages') # Replace this with the place you installed facebookads using pip
sys.path.append('/opt/homebrew/lib/python2.7/site-packages/facebook_business-3.0.0-py2.7.egg-info') # same as above

from facebook_business.api import FacebookAdsApi
from facebook_business.adobjects.adaccount import AdAccount

my_app_id = '{app-id}'
my_app_secret = '{appsecret}'
my_access_token = '{access-token}'
FacebookAdsApi.init(my_app_id, my_app_secret, my_access_token)
my_account = AdAccount('act_{{adaccount-id}}')
campaigns = my_account.get_campaigns()
print(campaigns
```

**Comment by pennersr** [comment]
https://django-allauth.readthedocs.io/en/latest/faq.html#why-did-you-just-close-my-issue

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2416
