### ISSUE TITLE
Copyright year in LICENSE file is outdated

### ISSUE THREAD

**Issue by jklardie** [pennersr/django-allauth#2418]
The copyright line in the LICENSE file reads: 
`Copyright (c) 2010-2017 Raymond Penners and contributors`

2017 is obviously outdated. 

Give it a few more days and it can be updated to 2020.

**Comment by pennersr** [comment]
Closed via 3dd01b09

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2418
