### ISSUE TITLE
Norwegian locale should be "nb", not "no"

### ISSUE THREAD

**Issue by oal** [pennersr/django-allauth#2419]
Norwegian has two variants, "Bokmål" (the most common), and "Nynorsk". In Django 3.0 it's illegal to use a `LANGUAGE_CODE` not specified in `LANGUAGES` (`global_settings.py`). Only `nb` and `nn` is listed there, not `no`, which `django-allauth` uses for the Norwegian locale:

https://github.com/pennersr/django-allauth/tree/master/allauth/locale/no

https://github.com/django/django/blob/master/django/conf/global_settings.py#L114

Using `LANGUAGE_CODE = 'no'` results in
```
(translation.E004) You have provided a value for the LANGUAGE_CODE setting that is not in the LANGUAGES setting.
```

Should I open a pull request and have it moved?

**Comment by ggjersund** [comment]
I'm not responsible for this repository, but I'd really like to see this change done quickly as there are only a minor change required. So please open a pull request :+1:

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2419
