### ISSUE TITLE
PyPI has version 0.9.0, not 0.10.0

### ISSUE THREAD

**Issue by amfarrell** [pennersr/django-allauth#242]
https://pypi.python.org/pypi/django-allauth/ still refers to version 0.9.0
This means that pip install django-allauth will pull down that version. Since the documentation does not list another installation method, it is likely that other new users will default to installing that version if they miss the fact that the existence of an "upgrading from 0.9.0" section in the docs means that there is a newer version.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/242
