### ISSUE TITLE
Add an anchor for each release in the ChangeLog.rst

### ISSUE THREAD

**Issue by Bartleby2718** [pennersr/django-allauth#2420]
- Motivation: I wanted to add a hyperlink to the most recent release (0.41.0) in the release notes, but it seems like the "permalink" isn't permanent. The permalink for 0.41.0 is https://django-allauth.readthedocs.io/en/latest/release-notes.html#id1 right now, which means it will become `#id2` in the next release.
- Suggestion: I think every release should have a real permalink to it, something like `#0.41.0` or `#2019-12-19`. ([It seems like both period and dash are valid characters in a fragment.](https://stackoverflow.com/questions/2849756/list-of-valid-characters-for-the-fragment-identifier-in-an-url)). The problem is that 1) I don't know which makes more sense to everyone and 2) I have no experience in RST before (I can add hyperlinks, but I don't want to make all the headers blue).

Does anyone have any opinions or ideas?

**Comment by pennersr** [comment]
Having permalinks with the version in there makes sense -- I would not opt for the date. Feel free to experiment with getting "#0.42.0" in there instead of "#id2" -- looking forward to see a PR. Closing until then...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2420
