### ISSUE TITLE
Custom OAuth Provider

### ISSUE THREAD

**Issue by mbrahimi617** [pennersr/django-allauth#2425]
Refers to #2415 

There is nothing about the oauth and oauth2 providers in the documentation under providers so I have no idea how to use it, but I'm sure there are others who would want a more open ended solution for private or less well known providers that aren't the likes of Google and Facebook. Of course, you would need to manually provide the endpoints and client details. Does allauth simply authenticate or does it authorize as well? Ideally I'd like the authentication to associate with a Django User via get or create so I can use permissions on my API.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2425
