### ISSUE TITLE
Ping Federate Integration

### ISSUE THREAD

**Issue by mbrahimi617** [pennersr/django-allauth#2426]
The All Auth OpenID docs are really sparse and I don't know what many of the fields mean such as handler, issued, association type etc. My application is provisioned from Ping Federate which is an OIDC provider which of course is written on top of OAuth2. As a subset of OAuth2 it's authorization and token endpoints are relative to a base URL like so:

```
TENDPOINT = /as/token.oauth2

AENDPOINT = /as/authorization.oauth2
```

The client id and redirect URL are selected by the developer in the provisioning portal which generates a client secret as well following this [spec](https://www.pingidentity.com/developer/en/resources/openid-connect-developers-guide.html) here. I'm just confused as to how I should supply these values because I don't see any clear fields to supply client id, client secret, base URL, redirect URL, and optional user mapping from the id token. Is there anyway to use the existing OpenID provider or include a Ping Federate provider? As far as I know PF ranks among Okta and Auth0 and should definitely be included as well.

**Comment by mbrahimi617** [comment]
Oh ok I think that's probably all internal use although if that was the case I don't know why it would be registered in the Django admin. Anyway, it looks like I'm supposed to set things up via Django settings but looking through the docs I don't see any mention of the parameters I can specify. Or how to best handle redirection alongside my decoupled React frontend.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2426
