### ISSUE TITLE
TelegramProvider `extra_data` contains `common_fields`

### ISSUE THREAD

**Issue by gasabr** [pennersr/django-allauth#2431]
Thanks for the project first of all!

I was able to make Telegram authentication work with Login widget, but have noticed that data provided by telegram (username, first and second names) stays in `extra_data` field of SocialLogin. It looks like it can be easily extracted in method `get_common_fields` ([method in a base class](https://github.com/pennersr/django-allauth/blob/e5b7a96e0e982f8252e9b016de2960e8a7481507/allauth/socialaccount/providers/base.py#L119)) rewritten for TelegramProvider.

If anyone is interested and it does not break any concepts on the library, I could implement that.

**Comment by AlexDeltax** [comment]
May I ask you to share an example?

**Comment by gasabr** [comment]
Will the screenshot of django admin after successful creation be enough?

**Comment by gasabr** [comment]
I ended up writing my own provider and it works, creating users with `first_name`, `last_name` and `user_name`.

Suggested content of `telegram/provider.py`
```
from allauth.socialaccount import providers
from allauth.socialaccount.providers.base import Provider, ProviderAccount


class TelegramAccount(ProviderAccount):
    pass


class TelegramProvider(Provider):
    id = 'telegram_updated'
    name = 'Telegram_updated'
    account_class = TelegramAccount

    def get_login_url(self, request, **kwargs):
        # TODO: Find a way to better wrap the iframed button
        return '#'

    def extract_uid(self, data):
        return data['id']

    def extract_common_fields(self, data):
        print('asasddsd', data)
        return {
            'first_name': data['first_name'],
            'last_name': data['last_name'],
            'username': data['username'],
        }


provider_classes = [TelegramProvider]
providers.registry.register(TelegramProvider)
```

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2431
