### ISSUE TITLE
Id fields obfuscation

### ISSUE THREAD

**Issue by frossigneux** [pennersr/django-allauth#2436]
It would be great to use https://github.com/nshafer/django-hashid-field to obfuscate id fields.
Otherwise, it should at least be possible to allow the user to override the id fields by using custom models (like for EmailAddress).

**Comment by pennersr** [comment]
Supported via 32c9eaf2

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2436
