### ISSUE TITLE
tests are not available in pypi sdist

### ISSUE THREAD

**Issue by dvzrv** [pennersr/django-allauth#2439]
Hi! I'm packaging django-allauth for Arch Linux. To ensure integration for python packages, we usually run the provided tests.
We usually use pypi.org as upstream for tracking new versions and to build against.

However, when trying to build and test 0.41.0, I realized, that the sdist on pypi doesn't provide the necessary scripts to test the library.
It would be really cool, if the required files (e.g. manage.py, etc.) could be added. Thank you!

**Comment by dvzrv** [comment]
Any news on this? :)

**Comment by dvzrv** [comment]
@pennersr ping :)

**Comment by dvzrv** [comment]
@pennersr This has been open for two years now? Will this ever be decided upon?

**Comment by pennersr** [comment]
You mention "manage.py, **etc**" -- `manage.py` is indeed missing, but what other files are missing?

**Comment by dvzrv** [comment]
This can be easily tested by creating a local sdist tarball, extracting it and trying to run tests in it.
The 0.53.1 sdist tarball on pypi.org still does not have all files required to run tests :cry: 
Adding the manage.py would have been a good first start :)

**Comment by dvzrv** [comment]
As this (trivial change) hasn't been prioritized since 2020 and I have in the meantime gotten an [RFC for Arch Linux ratified to move away from PyPI sdist tarballs](https://rfc.archlinux.page/0020-sources-for-python-packaging/), I'll close this issue.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2439
