### ISSUE TITLE
OperationalError at /accounts/twitter/login/callback/

### ISSUE THREAD

**Issue by surinderdeveloper** [pennersr/django-allauth#2440]
Hello Team,

I am using django-allauth for Twitter login and getting for error when login with a user who has name in different language. Here is twitter user (https://twitter.com/87VKYsIFfhHKjcM)

I am using MariaDB AWS RDS server, I tried with changed charset to utf8mb4 etc. but nothing worked for me.
Can anybody help to solve this.

(1366, "Incorrect string value: '\\xE3\\x82\\xB8\\xE3\\x83\\xA1...' for column `demo`.`auth_user`.`first_name` at row 1")

**Comment by derek-adair** [comment]
Almost certainly a database encoding error and out of scope of django-allauth.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2440
