### ISSUE TITLE
The Redirect URI must match Error 

### ISSUE THREAD

**Issue by iammujtaba** [pennersr/django-allauth#2445]
I am using django-allauth for github login
my urls.py design is-- path('accounts/', include('allauth.urls'))
callback url in github is https://zeroku.online/accounts/github/login/callback
and in login template link is {% provider_login_url 'github' %} 
and this is working if I replace zeroku.online with localhost:8000 in github callback url and run the project on local localhost server .
But when I am trying on my production server it is not working. Please tell me why? what I am missing here...

**Comment by pennersr** [comment]
Closing -- your redirect URL specified over at Github does not match the one actually used during your test run.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2445
