### ISSUE TITLE
Feature Request: Zoho OAuth2 Integration

### ISSUE THREAD

**Issue by rasulkireev** [pennersr/django-allauth#2446]
I understand it might be easy to just ask for more features, but it would be awesome to have that too. I am learning Django at a high rate as we speak, but understand all the things. If this does not get resolved, eventually, I will try to add this integrations myself. 

Meanwhile, thanks for reading this and for taking the time to think about this.

Best,
Rasul

**Comment by rasulkireev** [comment]
❤️

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2446
