### ISSUE TITLE
Feature request: Store IP address

### ISSUE THREAD

**Issue by sowinski** [pennersr/django-allauth#2448]
Hi,

what could be a good way of storing the IP of a customer during the registration process or even store a history of all login / fails / registration attempts.

Is there maybe allready a plugin for django-allauth?

Thank you

**Comment by 9mido** [comment]
If someone does this, please make it GDPR / PII compliant and encrypt the IP address.

**Comment by pennersr** [comment]
Closing, beyond scope of allauth.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2448
