### ISSUE TITLE
Feature Request: Nylas Integration

### ISSUE THREAD

**Issue by 2019342a** [pennersr/django-allauth#2449]
Hi there,

Would it be possible to integrate [Nylas](https://www.nylas.com/) into django-allauth? It is not a social authentication but it is a wrapper for email providers. The workflow for signing fits django-allauth really well. I could provide a PR if it is relevant.

Thanks,
Theo

**Comment by pennersr** [comment]
Seems possible https://docs.nylas.com/reference#oauthauthorize -- pull requests are welcome. Closing until then...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2449
