### ISSUE TITLE
Accessing Facebook pages in addition to master account?

### ISSUE THREAD

**Issue by commadelimited** [pennersr/django-allauth#245]
For the app we're writing we've been tasked with accessing the Facebook pages of a connected account in addition to the account itself. I wondered if Allauth already does that, or if it's something that needs to be written manually?

In other words, if I'm a business owner, I'd have a master FB account, and then `n` number of pages relating to my business. When logging in we want to create distinct social accounts for each page in addition to the master account.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/245
