### ISSUE TITLE
Is there any support for changing the EmailAddress model?

### ISSUE THREAD

**Issue by adamb70** [pennersr/django-allauth#2450]
I'd like to change the unique together constraint on the EmailAddress model and possibly add a new field. Is there any option built into Allauth to make this possible?

I know can get it working with a monkey patch, but it then won't reflect the changes in migrations.

**Comment by Lucky3337** [comment]
Hello, i need to change this model too. Have you already got this issue?

**Comment by pennersr** [comment]
No, the models are not replaceable.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2450
