### ISSUE TITLE
Add Signal for Email Verified

### ISSUE THREAD

**Issue by steverecio** [pennersr/django-allauth#2453]
There's already a signal for `email_confirmed` however this implied that an official email confirmation was sent and verified. However, when using social auth, an email address with `verified=True` is added to the database but this does not fire the `email_confirmed` signal. There is an `email_added` signal but that would not work to catch the case where an email is added initially as unverified and later modified to verified.

I'd propose adding a new signal for `email_verified` that is fired from the `save()` function on the `EmailAddress` model whenever the verified field is set to True. This way we can know for sure that the user has a verified email whether or not they have clicked through the confirmation email sent to their inbox.

**Comment by steverecio** [comment]
Workaround is checking for a verified email on `user_signed_up` signal and using `email_confirmed` signal.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2453
