### ISSUE TITLE
github provider should use Authorization header instead

### ISSUE THREAD

**Issue by alee** [pennersr/django-allauth#2457]
GitHub is deprecating their query parameter access token based authentication in favor of setting an `Authorization:` header in the request. I *think* this should be a fairly simple change to the [GitHub provider](https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/providers/github/views.py#L30) and adding the header to the `requests.get()` call. Happy to submit a PR for this but I'm not sure if there's anything else needed..

https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters

**Comment by peterbe** [comment]
I suspect that https://github.com/pennersr/django-allauth/blob/5b9b85593e683da28897635e9179b41f7db95ee1/allauth/socialaccount/providers/github/views.py#L30 and https://github.com/pennersr/django-allauth/blob/5b9b85593e683da28897635e9179b41f7db95ee1/allauth/socialaccount/providers/github/views.py#L42 need to change to something else. 
What I can't see (and I've never actually worked on this code) is that we're not even using any form of authentication when we do those `requests.get(...)` calls.

**Comment by alee** [comment]
I did a little more spelunking and it looks like authentication happens in the [OAuth2LoginView](https://github.com/pennersr/django-allauth/blob/5b9b85593e683da28897635e9179b41f7db95ee1/allauth/socialaccount/providers/oauth2/views.py#L93) but we shouldn't have to deal with that since the rest of the [oauth2 flow](https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/#web-application-flow) remains unchanged, GitHub is changing how it handles api requests using the oauth2 access token. 

Looking at other providers that also set the Authorization header I think it is as simple as setting

`headers={'Authorization': 'token ' + token.token})` in when make the followup GET requests. I made a PR #2458 for this

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2457
