### ISSUE TITLE
Linkedin oauth2 error 403 Client Error: Forbidden for url

### ISSUE THREAD

**Issue by kiranchari** [pennersr/django-allauth#2460]
403 Client Error: Forbidden for url: https://api.linkedin.com/v2/me?projection=(id,first-name,last-name,email-address)

"Linkedin oauth2 error 403 Client Error: Forbidden for url" - I keep running into this error with Linkedin Login even though my linkedin app has the required permissions (r_emailaddress, r_liteprofile, w_member_social)

I am using allauth v0.41.0

**Comment by ibrahimsamson** [comment]
can show the code possibly causing the error

**Comment by kiranchari** [comment]
I am not sure which script in django-allauth makes the request to the linkedin api. But my linkedin login setup is standard and it used to work. Related issue is here: https://github.com/pennersr/django-allauth/issues/2300, but I don't know what the fix is

**Comment by ibrahimsamson** [comment]
check if you are passing the right token

**Comment by kiranchari** [comment]
Which token are you referring to? Thanks

**Comment by pennersr** [comment]
Closing -- if you find a concrete issue in allauth, feel free to reopen.

**Comment by anurag-git1** [comment]
still facing this issue 
403 Client Error: Forbidden for url: https://api.linkedin.com/v2/me?projection=(id,first-name,last-name)

**Comment by tmabs-94** [comment]
still facing this issue
403 Client Error: Forbidden for url: https://api.linkedin.com/v2/me?projection=(id,first-name,last-name)

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2460
