### ISSUE TITLE
KeyError at /accounts/login/ 'BACKEND'

### ISSUE THREAD

**Issue by MrAlexWinkler** [pennersr/django-allauth#2461]
When I log in with wrong credentials I don't just get a simple form error I go a full debug error:

https://imgur.com/a/KxR5pIo

I have all auth fully installed and provider Google is working for signup and login. I'm also doing this on the allauth standardized login form and URL. Please let me know if I should post any more info besides the pictures.

**Comment by pennersr** [comment]
The pictures are too little to go on. Please post a small example project demonstrating the issue. Closing until then.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2461
