### ISSUE TITLE
Are you aware of social-core? Join force. Base on it.

### ISSUE THREAD

**Issue by rpuntaie** [pennersr/django-allauth#2462]
I came across your library, while getting up to speed with OAuth.
I found out that

- [oauthlib](https://github.com/oauthlib/oauthlib) with
  [requests-oauthlib](https://github.com/requests/requests-oauthlib)
  are the current authoritative implementations.

They have no provider data, though.
You use them and provide provider data.
But, I *could not use your library*, since it is locked to Django,
and I happen not to use Django.

Interesting that my first searches did not turn up
[social-core](https://github.com/python-social-auth/social-core).
Only later, scanning through the packages using ``requests-oauthlib``, I stumbled across it.
That was luck,
because I had started to extract the essential oauth provider data from your library into a separate independent library, already.
I stopped with that, happy not to have invested more effort,
because [someone else already did](https://python-social-auth.readthedocs.io/en/latest/).

Testing all backends and adapting to provider changes to their API
is a massive undertaking, best handled by a community.
So I thought, like me, maybe you are not aware of
[social-core](https://github.com/python-social-auth/social-core).

Like me, lot of people have found your library,
and there is a community around it now.
Provider data and OAuth is not django-specific, though.
Implementing that independently is a better choice.
This was the [path of social-core, too](https://python-social-auth.readthedocs.io/en/latest/).
Your library would be better based on
[social-core](https://github.com/python-social-auth/social-core).
So your community could add to that of
[social-core](https://github.com/python-social-auth/social-core),
directly there, or in your fork of it.
This would make sure that the provider specific code gets checked and fixed by a lot of people.
It would also free you for other projects.

Else maybe you link to
[social-core](https://github.com/python-social-auth/social-core)
in your README.rst,
so that people in search of a 
non-django-specific implementation for social login
get lucky.

**Comment by rpuntaie** [comment]
I've created a [gist](https://gist.github.com/rpuntaie/7148c2295e0852a98e219a211b812e79
)

- with my attempt to create a library with just login.
  Such a library design would be desirable,
  but I dropped it because I found social-core.

- with a stubbing of the social-core framework callbacks to use it like a library

**Comment by Andrew-Chen-Wang** [comment]
This library is very Django specific and if you're no using Django, then don't bother trying to use this. It uses Django's framework for emailing, templates, settings, User models, regular Django models, etc.

**Comment by pennersr** [comment]
Closing, see previous comment.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2462
