### ISSUE TITLE
login attempts blocked user....unblock

### ISSUE THREAD

**Issue by yooyoyo** [pennersr/django-allauth#2463]
where is the data stored for login attempts made by the users?? How do you clear that? or unblock blocked users?

**Comment by 9mido** [comment]
I also have the same question. This would be a good candidate for a feature request / pull request.

Even after going through the "Forgot Password" process for a locked out user with the ACCOUNT_LOGIN_ATTEMPTS_LIMIT and ACCOUNT_LOGIN_ATTEMPTS_TIMEOUT enabled in settings, a user still needs to wait the allotted time until they are able to login again even after they enter their new password they just changed.

**Comment by iarp** [comment]
[allauth code](https://github.com/pennersr/django-allauth/blob/master/allauth/account/adapter.py#L513) uses the [django cache system](https://docs.djangoproject.com/en/3.0/ref/settings/#std:setting-CACHES) which defaults to an in-memory system. in-memory means restarting the process wipes anything in cache out.

**Comment by 9mido** [comment]
@iarp I see. I did control+c to stop python3 manage.py runserver then re-ran python3 manage.py runserver again and that seemed to unblock the locked out user. Is there another way to clear the cache instead of stopping the entire server?

**Comment by iarp** [comment]
Would password reset be enough?

**Comment by 9mido** [comment]
@iarp  Oh like a snippet of code to clear the cache after every password reset? That seems like a reasonable approach. Is that what you mean? Currently successful password reset keeps the user blocked out even when using the new reset password.

```
from django.core.cache import cache
cache.clear()
```

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2463
