### ISSUE TITLE
REDIRECT_URL_ON_CONFIRM

### ISSUE THREAD

**Issue by jameskomo** [pennersr/django-allauth#2468]
I am trying to have two different redirects...one for normal login and another for redirect after email confirmation

`ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = '/profile'
LOGIN_REDIRECT_URL = '/'
`

But when I enable login, AUTHENTICATED REDIRECT goes to LOGIN_REDIRECT but when I disable Login it goes to the EMAIL_CONFIRMATION_REDIRECT route.

When I try printing the adapter settings for email_confirmation redirect url below it shows only the LOGIN_REDIRECT

`def get_email_confirmation_redirect_url(self, request):
        """
        The URL to return to after successful e-mail confirmation.
        """
        if request.user.is_authenticated:
            if app_settings.EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL:
                return  \
                    app_settings.EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL
            else:
                return self.get_login_redirect_url(request)
        else:
            return app_settings.EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL`

I tried changing the account settings below but wont work as well

` @property
    def EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL(self):
        """
        The URL to redirect to after a successful e-mail confirmation, in
        case of an authenticated user
        """
        return self._setting("EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL",
                             None)`

**Comment by jameskomo** [comment]
When I print `request.user` in adapters.py, it shows 'AnanymousUser' yest my expectation is that at that point before I login the user should be the verified user even before login?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2468
