### ISSUE TITLE
can't I access the user object just after signup but before login

### ISSUE THREAD

**Issue by ibrahimsamson** [pennersr/django-allauth#2469]
I have been trying to populate some user fields by using celery and signals but it seems like the signals aren't triggered. When the `social_account_added signal` is emitted I then call a background task to download the user's profile picture from Linkedin and upload it to my oss bucket. But the signals aren't emitted so this function is never called. Here is what i have done
```
from allauth.socialaccount.signals import social_account_added
from django.dispatch import receiver
@receiver(social_account_added)
def social_user_connected(request, sociallogin, **kwargs):
    update_profile_picture.delay(str(sociallogin.user))
    return redirect("app:home")
```

**Comment by ibrahimsamson** [comment]
after a close lookup I decided to use a different signal,` from allauth.account.signals import user_signed_up`  which was actually emitted and I think more suitable for my needs,

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2469
