### ISSUE TITLE
Issue with refresh token not being saved 

### ISSUE THREAD

**Issue by lavafactory** [pennersr/django-allauth#2470]
Having an issue with a particular user in allauth that for whatever reason has the blank token_secret / refresh_token for a google auth.  I followed #403 to try and reset the refresh token, and while the code does pull a new refresh token, it doesn't actually save it back to the model.  

Having a hard time figuring out where the code is that actually does the save, and could use some help.

**Comment by lavafactory** [comment]
Closing this issue... User error.

**Comment by usamamashkoor** [comment]
@lavafactory can you please let me know how did you get the access token and how did you get the referesh token and then referesh your google OAuth token?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2470
