### ISSUE TITLE
Robinhood OAuth2 Details?

### ISSUE THREAD

**Issue by flxfxp** [pennersr/django-allauth#2471]
I'd like to use Robinhood for auth, but I can't seem to figure out the OAuth2 settings.
@joshowen as you submitted the PR for this, could you please give more information on what to use for `client_id`, `secret`, etc? I can't seem to create a developer app for Robinhood that specifically sets these settings.

Thank you,
Dennis

**Comment by joshowen** [comment]
@flxfxp I don't think this API was every launched publicly or is currently supported.  Sorry!

**Comment by flxfxp** [comment]
Understood. After further research I've been able to implement Robinhood login outside of django-allauth, and as the APIs are private, I would suggest to remove this provider for now.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2471
