### ISSUE TITLE
Feature Request: Garmin Integration

### ISSUE THREAD

**Issue by ethanopp** [pennersr/django-allauth#2473]
We have strava... why not garmin as well! :)

**Comment by Epagelmatias** [comment]
Is there a general guide we could follow to integrate garmin?

**Comment by ethanopp** [comment]
After opening this, I did some further digging and it seems you have to get approved prior to using their api...

https://developer.garmin.com/health-api/overview/

**Comment by pennersr** [comment]
Garmin support would be nice -- feel free to file a pull request. Closing this though...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2473
