### ISSUE TITLE
POST data missing in pre_social_login

### ISSUE THREAD

**Issue by steverecio** [pennersr/django-allauth#2474]
As part of my MFA logic, I want to block social login in the event that an MFA device is set. I have the pre_social_login signal set up but the request object passed in doesn't have the POST data attached. I need to do this in the pre_social_login handler because I need access to the user object in order to look up whether the MFA device is set. Is this a bug that the POST data is missing from the request object passed into the signal handler?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2474
