### ISSUE TITLE
Support for Django >3.0

### ISSUE THREAD

**Issue by adremides** [pennersr/django-allauth#2478]
It seems not to be working on versions newer than 2.x. I was not able to discover the problem. Log didn't show me any error but an empty django project crash after credentials are sent on the login screen.

Last line in log with version >=3.0 is:
```
(0.000) SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 1 LIMIT 21; args=(1,)
```

Past this line in the log with version <3.0 (where it works) are following info:
```
(0.000) SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 1; args=(1,)
(0.000) SELECT "django_admin_log"."id", "django_admin_log"."action_time", "django_admin_log"."user_id", "django_admin_log"."content_type_id", "django_admin_log"."object_id", "django_admin_log"."object_repr", "django_admin_log"."action_flag", "django_admin_log"."change_message", "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined", "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_admin_log" INNER JOIN "auth_user" ON ("django_admin_log"."user_id" = "auth_user"."id") LEFT OUTER JOIN "django_content_type" ON ("django_admin_log"."content_type_id" = "django_content_type"."id") WHERE "django_admin_log"."user_id" = 1 ORDER BY "django_admin_log"."action_time" DESC  LIMIT 10; args=(1,)
"GET /admin/ HTTP/1.1" 200 3042
"GET /static/admin/css/responsive.css HTTP/1.1" 200 17944
"GET /static/admin/css/base.css HTTP/1.1" 200 16378
"GET /static/admin/css/dashboard.css HTTP/1.1" 200 412
"GET /static/admin/css/fonts.css HTTP/1.1" 200 423
"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
"GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
"GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 86184
"GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
"GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
```
To reproduce the error simply create new django project with a version 3.0 or greater, do a `python manage.py migrate`, create a new superuser `python manage.py createsuperuser`, run server and try to login in django admin.

UPDATE: After make some replacement of the files changed in version 3.0a1 with same in version 2.2.11, track the issue in the file `..\site-packages\django\contrib\admin\templates\admin\index.html` line 76:
`                    <span class="mini quiet">{% filter capfirst %}{{ entry.content_type.name }}{% endfilter %}</span>`
If `entry.content_type.name` is changed by `entry.content_type`, it works again. I don't know how to fix it in the module anyway so I wait for someone who know more about it than me, or continue to try to figure it out.

UPDATE2: I tested it in a computer with Ubuntu 19.10 and it works. I will continue to trying the problem in the computer with windows that gives me the problem tomorrow

UPDATE3: Problem was the interpreter version. I was using 32 bit one in windows.

**Comment by raratiru** [comment]
According to updates 2&3 it works, doesn't it?

**Comment by adremides** [comment]
That's right @raratiru it works just fine, it was my environment. I Close this and leave it as historical for anyone with a similar problem.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2478
