### ISSUE TITLE
Facebook button should not track my visitors

### ISSUE THREAD

**Issue by bittner** [pennersr/django-allauth#2479]
When we offer Facebook login (via django-allauth) on our website every visitor gets track already when they are just landing on our page.

This is technically due to the [fbconnect.js](https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/providers/facebook/templates/facebook/fbconnect.html#L6) that is loaded by allauth and ultimately calls a URL such as https://connect.facebook.net/en_US/sdk.js (as seen in the web browsers network tab).

I'm worried about this for two reasons:

1. **Privacy:** My visitors deserve to not be tracked. I do not intend to track them, neither am I interested in their data being sent to Facebook.
2. **Performance:** My website gets slower for no good reason. We're loading external content and the user may not even want to use the login button.

Is there a technical reason that requires us to load external resources from a third party, _here_ Facebook, to initialize social login _before_ a user initiates the login action? That would surprise me. Can we replace that code by some, less invading, more performant code?

In an older version of allauth there was simply a URL path that would go into our template code. That didn't load _anything_ from Facebook:
```html
<a title="Facebook" class="socialaccount_provider facebook" 
     href="/facebook/login/?process=login&next=%2F">Facebook</a>
```
Can't we continue to use this approach?

We're just making henchmen for Facebook to collect data from Django websites, otherwise. And we're doing the brand "Django" a bad service when "all Django websites are slow". I don't want neither.

**Comment by pennersr** [comment]
There are two ways of doing things:

```
    {% providers_media_js %}
    <a href="{% provider_login_url "facebook" method="js_sdk" %}">Facebook Connect</a>
```

and

```
    {% load socialaccount %}
    <a href="{% provider_login_url "facebook" method="oauth2" %}">Facebook OAuth2</a>
```

The latter does not use the JS approach. Doesn't that solve the issue?

**Comment by bittner** [comment]
This is true, and the method [must be consciously chosen](https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/providers/facebook/provider.py#L70-L83), which is good.

However, the [related JavaScript](https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/providers/facebook/static/facebook/js/fbconnect.js) code [is included](https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/providers/facebook/templates/facebook/fbconnect.html#L6) (via [[1](https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/templatetags/socialaccount.py#L55-L66)], [[2](https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/providers/facebook/provider.py#L153-L185)]) even with `method="oath2"`, and that code is automatically triggered, so that a request to Facebook is still made:

> GET  https://connect.facebook.net/de_DE/sdk.js  Blocked By Extension

Is what shows up in my Web browser's console.

We should not include that JavaScript code unless a developer consciously chooses to have their users tracked by Facebook! Maybe even a related warning [in the docs](https://django-allauth.readthedocs.io/en/latest/providers.html#facebook) should be added to make clear that we're not careless of users being victims when developers deploy Allauth in their solutions.

**Comment by pennersr** [comment]
Fixed via 934955f5

**Comment by bittner** [comment]
Thank you, Raymond! 🥇

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2479
