### ISSUE TITLE
OpenID example and Google

### ISSUE THREAD

**Issue by typonaut** [pennersr/django-allauth#2482]
The documents give this as an example of configuring OpenID in SOCIALACCOUNT_PROVIDERS:

`'openid': {'SERVERS': [
            dict(id='yahoo',
                 name='Yahoo',
                 openid_url='http://me.yahoo.com'),
            dict(id='hyves',
                 name='Hyves',
                 openid_url='http://hyves.nl'),
            dict(id='google',
                 name='Google',
                 openid_url='https://www.google.com/accounts/o8/id')]
    },`

The first issue is that `https://www.google.com/accounts/o8/id` gives a 404 error. What is the correct URL to use here?

Also, how does one access the OpenID `SERVERS` in a template?

Thanks

**Comment by pennersr** [comment]
Closing -- `openid` is outdated.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2482
