### ISSUE TITLE
Feature Request: Pocket Integration

### ISSUE THREAD

**Issue by rasulkireev** [pennersr/django-allauth#2483]
I think there is some cool stuff that can be done with Pocket API. 

I haven't attempted to do this myself, but am planning to, soon. Will let you guy know if there is any progress. If anyone had experience with that, would be cool to integrate with django-allauth. 

https://getpocket.com/developer/

Their API seems pretty straight forward.

Thanks in advance.

**Comment by winnerNick** [comment]
Hi, I am also looking for a solution to add this provider in django-allauth.

Have you done any progress? Can I help?

**Comment by pennersr** [comment]
Pull requests are welcome. Alternatively, you could sponsor this feature request.

**Comment by pennersr** [comment]
Closing, keeping feature requests open for providers is not getting any work done.

https://github.com/sponsors/pennersr

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2483
