### ISSUE TITLE
github auth

### ISSUE THREAD

**Issue by luckrill** [pennersr/django-allauth#2487]
Development  is pass.
http://127.0.0.1:8000
http://127.0.0.1:8000/accounts/github/login/callback/

but with go.readmorejoy.com online domain, the result is failed.
https://go.readmorejoy.com/
https://go.readmorejoy.com/user/github/login/callback/

why?  How to use allauth with go.readmorejoy.com domain. 

thanks

**Comment by tonythomas01** [comment]
Do you have 2 different Github OAuth apps and App clients configured through admin panel for both ?

**Comment by pennersr** [comment]
https://django-allauth.readthedocs.io/en/latest/faq.html#why-did-you-just-close-my-issue

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2487
