### ISSUE TITLE
get_avatar_url for facebook provider is failing

### ISSUE THREAD

**Issue by fbadin-divnotes** [pennersr/django-allauth#2488]
When my app tries to load the following user avatar

`https://graph.facebook.com/v2.12/10204958011707924/picture?type=square&height=600&width=600&return_ssl_resources=1`

facebook responds with a json error

```
{
   "error": {
      "message": "An access token is required to request this resource.",
      "type": "OAuthException",
      "code": 104,
      "fbtrace_id": "ATYdkIr6TZC7wk94YPzEV8_"
   }
}
```

I tried to check it by validating the expired_at on social token, but looks like it behaves differently about the pictures. I have a case that even though the account is expired, the picture is still available (on google provider).

**Comment by Gandi24** [comment]
I believe this is related to the changes in facebook API for profile images:
https://stackoverflow.com/questions/64434913/get-facebook-user-profile-image-after-facebook-changesoctober-24

If you want to manually override the issue, adding `&token={token}` to the avatar url seems to solve the problem, but the `get_avatar_url` method should definitely include that.

**Comment by derek-adair** [comment]
@pennersr config error it would seem... but I dont use this provider so... maybe?

**Comment by pennersr** [comment]
No, valid. Facebook `FacebookAccount.get_avatar_url()` generates that URL, and a long time ago, that would work, but these days FB requires an access token for that.

**Comment by pennersr** [comment]
Moved to https://codeberg.org/allauth/django-allauth/issues/2488
