### ISSUE TITLE
Issue with socialaccount provider microsoft graph (provider.py)

### ISSUE THREAD

**Issue by LunatikCoder** [pennersr/django-allauth#2492]
Hi, i found a bug when accessing the page {% url 'socialaccount_connections' %} (/social/connections/) it gave me a 'NoneType' object has no attribute 'strip' and the culprit is provider.py. The problem is that this file calls the strip() function on a null value and python being python doesn't like it ;) The solution i found is quite simple, in the provider.py file the MicrosoftGraphAccount class should be updated from this:
`class MicrosoftGraphAccount(ProviderAccount):
     def to_str(self):
        name = self.account.extra_data.get('displayName')
        if name.strip() != '':
            return name
        return super(MicrosoftGraphAccount, self).to_str()`

to this:

`class MicrosoftGraphAccount(ProviderAccount):
    def to_str(self):
        name = self.account.extra_data.get('displayName')
        if not name is None:
            if name.strip() != '':
                return name
        return super(MicrosoftGraphAccount, self).to_str()`

I would like to add this change myself to the project if i can but i don't really know how to proceed. I decided to report the bug instead. Thank you !

**Comment by LunatikCoder** [comment]
i have managed to create a pull request for this, so i will close this issue now!

**Comment by LunatikCoder** [comment]
reopened issue because pull request didn't work and this is something that needs to be fixed

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2492
