### ISSUE TITLE
Encrypt Email Address

### ISSUE THREAD

**Issue by 9mido** [pennersr/django-allauth#2494]
https://gdpr.eu/email-encryption/

Related:  #1982

I was trying to encrypt emails every time a user signs up using allauth to protect my database from PII compliance and GDPR. 

I tried both django-fernet-fields and django-cryptography github projects with a custom user model

django-cryptography:
Unsupported lookup 'iexact' for EncryptedEmailField or join on the field not permitted, perhaps you meant iexact or exact?

django-fernet-fields:
django.core.exceptions.FieldError: EncryptedEmailField 'iexact' does not support lookups

Both of these packages work only if I create a user from the command line or admin interface not from my allauth sign up form. 

I have commented both email fields below to show you how I am using both of these encryption packages one at a time. 

Create the user app:

`python3 manage.py startapp user`

Install pgcrypto in postgres:

`psql -d database_name -c 'CREATE EXTENSION pgcrypto'`
or
`CREATE EXTENSION pgcrypto;`

Settings.py:

```
AUTH_USER_MODEL = 'user.CustomUser'
INSTALLED_APPS = [ 'user', 'pgcrypto',]
```

user app models.py (this is the cause of the error above):

```
from fernet_fields import EncryptedEmailField
from django_cryptography.fields import encrypt

class CustomUserManager(BaseUserManager):
    def _create_user(self, email, password,is_staff, is_superuser, **extra_fields):
        now = timezone.now()
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email,is_staff=is_staff, is_active=True,is_superuser=is_superuser, last_login=now,**extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user
    def create_user(self, email, password=None, **extra_fields):
        return self._create_user(email, password, False, False,**extra_fields)
    def create_superuser(self, email, password, **extra_fields):
        return self._create_user(email, password, True, True,**extra_fields)

class CustomUser(AbstractBaseUser, PermissionsMixin):
    objects = CustomUserManager()
    email = fields.EmailPGPSymmetricKeyField()
    #email = models.EmailField(_('email address'), max_length=254, unique=True)
    #identifier = models.CharField(unique=True, max_length=50, default=uuid.uuid1)
    username = models.CharField(_('username'), max_length=30, blank=True, default='', unique=True)
    USERNAME_FIELD = 'username'
    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=30, blank=True)
    is_staff = models.BooleanField(_('staff status'), default=False,
        help_text=_('Designates whether the user can log into this admin '
                    'site.'))
    #is_mod = models.BooleanField(_('moderator status'), default=False,help_text=_('Designates whether the user can access mod pages and do mod things.'))
    is_active = models.BooleanField(_('active'), default=True,help_text=_('Designates whether this user should be treated as ''active. Unselect this instead of deleting accounts.'))
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = ['email']


```

user app admin.py:

```
from django.contrib.auth.admin import UserAdmin
from django.contrib import admin

from .forms import CustomUserCreationForm, CustomUserChangeForm
from .models import CustomUser

class CustomUserAdmin(UserAdmin):
    add_form = CustomUserCreationForm
    form = CustomUserChangeForm
    model = CustomUser
    list_display = ('username', 'email', 'is_staff', 'is_active', 'is_superuser')
    list_filter = ('username', 'email', 'is_staff', 'is_active', 'is_superuser')
    fieldsets = (
        (None, {'fields': ('username', 'email', 'password')}),
        (('Personal info'), {'fields': ('first_name', 'last_name')}),
        (('Permissions'), {'fields': ('is_active', 'is_staff', 'is_superuser',
                                       'groups', 'user_permissions')}),
        (('Important dates'), {'fields': ('last_login', 'date_joined')}),
    )
    add_fieldsets = (
        (None, {
            'classes': ('wide',),
            'fields': ('username', 'email', 'password1', 'password2')}
        ),
    )
    search_fields = ('username', 'email',)
    ordering = ('username', 'email',)
    filter_horizontal = ()

admin.site.register(CustomUser, CustomUserAdmin)
```

user app forms.py:

```
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = CustomUser
        fields = ('username', 'email',)


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'email',)

```

Allauth files interfering with this:

https://github.com/pennersr/django-allauth/blob/master/allauth/utils.py#L145

https://github.com/pennersr/django-allauth/blob/master/allauth/account/forms.py#L336

https://github.com/pennersr/django-allauth/blob/master/allauth/account/adapter.py#L300

More details:

https://www.reddit.com/r/djangolearning/comments/fm7cnt/custom_user_model_encrypt_email/

I also made this issue on the django-fernet-fields github page.

Update:

I was able to figure out how to encrypt the allauth stored email from the sign up form using a custom user model and https://github.com/incuna/django-pgcrypto-fields.

```
Django Settings:

PGCRYPTO_KEY = 'hello'
​
INSTALLED_APPS = [
   'user',
    'pgcrypto',
]

#use the same custom user model code above but add/change these lines:
from pgcrypto import fields
#This should encrypt the auth_user table for the custom user model
email = fields.EmailPGPSymmetricKeyField()
```

https://github.com/pennersr/django-allauth/blob/master/allauth/account/models.py#L18-L72

```
from pgcrypto import fields

#This should encrypt the email in allauth's account_emailaddress table
class EmailAddress(models.Model):

	email = fields.EmailPGPSymmetricKeyField(unique=True)

#do not change this class otherwise email confirmations will not send
class EmailConfirmation(models.Model):

	email_address = models.ForeignKey(EmailAddress,verbose_name=_('e-mail address'),on_delete=models.CASCADE)
```

Use everywhere to prevent "Manager isn't available; 'auth.User' has been swapped for 'CustomUser.User' " errors.

See: https://stackoverflow.com/a/48823691

```
from django.contrib.auth import get_user_model
User = get_user_model()
```

Some parts of allauth will need to be changed in order for this to work. You should not need to do any SQL ALTER table/column commands. The data that gets encrypted will show in pgadmin as [binary data]. 

Sql Result:
​
```
This is old -> database_name=# select * from auth_user;
database_name=# select * from user_customuser;
 id |                                    password                                    |          last_login           | is_superuser |                                                                                     email                                                                                      |              identifier              | username | first_name | last_name | is_staff | is_mod | is_active 
----+--------------------------------------------------------------------------------+-------------------------------+--------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------+----------+------------+-----------+----------+--------+-----------
  5 | pbkdf2_sha256$180000$6D1SHJdM1DCm$72vBud5ji4S4v3Md2I7Ty8pnq91TEjwBVMb+Nu4lrnI= | 2020-03-21 22:59:45.127628+00 | f            | \xc30d0407030286e239c36fe48d126dd24401086aecb7805d0e52fc77c32bc341f566153ee9e291d11f8972a6fd63a44282b5a7df09fad63d0bbd1eb1374980a9e10e13d2987a1289e193a749f496aec0195e1eb5e3   | a6c7d862-6bc7-11ea-a370-fcaa1473e99f | test56   |            |           | f        | f      | t
  6 | pbkdf2_sha256$180000$WambLS3EnC5D$V+sBNopzxdRG4alBDU3Vf9kNsFnbs5gL5Kpb8vLeDes= | 2020-03-21 23:00:51.245735+00 | t            | \xc30d04070302b53e0d09ee68807e73d245014797a80f79f8099bc887a1596ad684d760d2d1a18f7c6261ab3942202241d9c20a4d0c17bd5c165084e92e49d37c75f8f4ae1c4fbca80c09e344d06c56b2f9c9dc61b0a6 | c397b386-6bc7-11ea-a370-fcaa1473e99f | admin    |            |           | t        | f      | t
(2 rows)


database_name=# select * from account_emailaddress;
 id |        email         | verified | primary | user_id 
----+----------------------+----------+---------+---------
  3 | \xc30d0407030286e239c36fe48d126dd24401086aecb7805d0e52fc77c32bc341f566153ee9e291d11f8972a6fd63a44282b5a7df09fad63d0bbd1eb1374980a9e10e13d2987a1289e193a749f496aec0195e1eb5e3  | f        | t       |       5
  4 | \xc30d04070302b53e0d09ee68807e73d245014797a80f79f8099bc887a1596ad684d760d2d1a18f7c6261ab3942202241d9c20a4d0c17bd5c165084e92e49d37c75f8f4ae1c4fbca80c09e344d06c56b2f9c9dc61b0a6 | t        | t       |       6
(2 rows)
```

Decrypt Query:

`select PGP_SYM_DECRYPT(email::bytea, 'hello') from user_user;`

hello is the key that we specified earlier in settings. 

https://marcopeg.com/2019/per-user-encryption-in-postgres

If we were to make a PR we could do this:

app_settings.py:
```
    @property
    def EMAIL_ENCRYPTED(self):
        return  self._setting('EMAIL_ENCRYPTED', True)
```

Settings.py:

`ACCOUNT_EMAIL_ENCRYPTED = True`

Allauth models.py:

```
from django.conf import settings
if settings.PGCRYPTO_KEY:
    from pgcrypto import fields

class EmailAddress(models.Model):

    if app_settings.EMAIL_ENCRYPTED is True:
        email = fields.EmailPGPSymmetricKeyField(unique=app_settings.UNIQUE_EMAIL,max_length=app_settings.EMAIL_MAX_LENGTH,verbose_name=_('e-mail address'))
    else:
        email = models.EmailField(unique=app_settings.UNIQUE_EMAIL,max_length=app_settings.EMAIL_MAX_LENGTH,verbose_name=_('e-mail address'))
```

These settings may need to be changed:

ACCOUNT_USER_MODEL_EMAIL_FIELD = ”email”
ACCOUNT_USER_MODEL_USERNAME_FIELD =”username”

**Comment by 9mido** [comment]
@iarp 

I just realized that this kind of goes along with the recent PRs you just made about the email address since you introduced new tables for the email address.

Others (and including me) have requested something like encrypting the email (issues 2028 and 1982) in relation to GDPR and PII laws or people who just want to encrypt their email address to be lawful/secure). 

Although I figured out a solution with a third party package above to help people to encrypt email addresses in allauth and in their custom user model, it involves overriding the django-allauth app which sucks because any updates to the allauth package means needing to override allauth package again with the third party encryption code. 

Would it make sense to encrypt the email address within allauth itself using methods like the links below and provide an optional setting to encrypt the email address or leave it as plain text in the database since the only PII allauth stores is the email address? SQL queries for email address data analysis and anything else regarding emails within allauth like password resets/confirmations would need to be decrypted from the database as well to prevent some of the errors the other encryption packages threw above.

Wondering if a proxy model could be used within your own project's app to inherit the allauth EmailAddress model?

Research:

https://stackoverflow.com/questions/27335726/how-do-i-encrypt-and-decrypt-a-string-in-python

https://djangosnippets.org/snippets/1095/

http://www.pythondiary.com/blog/Jan.13,2020/creating-transparently-encrypted-field-django.html

https://web.archive.org/web/20190123103707/https://www.bryanhelmig.com/django-encryption/

https://stackoverflow.com/questions/1743764/how-can-i-pass-a-user-model-into-a-form-field-django

**Comment by iarp** [comment]
That sort of thing would require a massive change in just about every aspect. I mean you're talking about changing every queryset ever used anywhere, breaking anything that deals with unique email values, model constraints...etc. Way above me here.

As far as I'm aware or have cared to look into this (I don't do anything EU), I have yet to see evidence that GDPR or PII actually require data at rest (as in within the *sql server itself) to be encrypted. Data at rest in a backup should be encrypted via the actual backup file being encrypted. Data in transit is a different thing and as long as you're using https that should be fine.

**Comment by 9mido** [comment]
@iarp Thanks for the feedback. Didn't realize it would be that big of a change. I will ask a lawyer when I get to that point and report back. To my understanding, since websites are available worldwide, EU laws come into play and if not abiding by them huge fines are a possibility which could wipe out smaller site owner's bank account. It is a complicated matter and laws change all the time - just wanted to be safe. I understand other security mechanisms could be used like you stated on the server side but we can't be to sure. 

In the meantime, when upgrading allauth to newer versions, the site would require downtime and overriding the allauth models like above each and every time? I wish there was some way with a proxy model to be able to keep the parent model change within my own child app so upgrading to newer allauth versions would be more seamless without the need to override.

**Comment by 9mido** [comment]
Maybe something like this could be done? 

https://stackoverflow.com/questions/1743764/how-can-i-pass-a-user-model-into-a-form-field-django

**Comment by derek-adair** [comment]
This can be closed as discussion / off topic.  I would welcome encrypted emails in the DB, but that is a larger discussion and probably best left out of allauth.  Any integration problems, however, can be addressed here.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2494
