### ISSUE TITLE
Feature Request: Weixin Integration

### ISSUE THREAD

**Issue by 0x100cc** [pennersr/django-allauth#2495]
Allauth has already supported weixin authentication for normal users, however, recently Official Accounts and Mini Programs are very popular in weixin, so could anyone help to integrate authentication for Official Account and Mini Program operators with django-allauth?
I have found the guide:
https://developers.weixin.qq.com/doc/oplatform/en/Third-party_Platforms/Authorization_Process_Technical_Description.html
I know it might be easy to just ask for more features, but it would be awesome to have that too.
Thanks for reading this !
Best
Haynar

**Comment by pennersr** [comment]
Closing -- keeping feature requests open for new providers is not going to move things forward.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2495
