### ISSUE TITLE
What elicits the email_verification_sent view?

### ISSUE THREAD

**Issue by rossm6** [pennersr/django-allauth#2498]
Account.urls contains this url and view function -

path("confirm-email/", views.email_verification_sent,
         name="account_email_verification_sent"),

What actually calls this view?  I thought when the user signed up but it's not happening for me.  I can't see it documented anywhere.  Moreover the name isn't anywhere in accounts.views.

**Comment by rossm6** [comment]
Solved.  Set this ACCOUNT_EMAIL_VERIFICATION = 'mandatory' and the user is redirected to account_email_verification_sent after they have signed up.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2498
