### ISSUE TITLE
Account confirmation e-mails are now failing

### ISSUE THREAD

**Issue by SundialServices** [pennersr/django-allauth#2509]
This now occurs:

```
2020-04-14 13:08:17,667: Internal Server Error: /accounts/confirm-email/MjI1Mw:1jAf15:quU0jQ12pVg--QdD2ncxKwu1GV0/
django.urls.exceptions.NoReverseMatch: Reverse for 'account_confirm_email' with keyword arguments '{'key': ''}' not found. 1 pattern(s) tried: ['accounts\\/confirm-email/(?P<key>[-:\\w]+)/$']
```

The URL tag is as in the published template:

`{% url 'account_confirm_email' confirmation.key %}`

but it appears from the source-code that a keyword is now required.

**Comment by galileoguzman** [comment]
I am running with the same issue, not sure why is happening I am just using

```
path('accounts/', include('allauth.urls')),
```

**Comment by dr-alberto** [comment]
> This now occurs:
> 
> ```
> 2020-04-14 13:08:17,667: Internal Server Error: /accounts/confirm-email/MjI1Mw:1jAf15:quU0jQ12pVg--QdD2ncxKwu1GV0/
> django.urls.exceptions.NoReverseMatch: Reverse for 'account_confirm_email' with keyword arguments '{'key': ''}' not found. 1 pattern(s) tried: ['accounts\\/confirm-email/(?P<key>[-:\\w]+)/$']
> ```
> 
> The URL tag is as in the published template:
> 
> `{% url 'account_confirm_email' confirmation.key %}`
> 
> but it appears from the source-code that a keyword is now required.

I have the exact  same issue, I inlcude `allauth.ulr` on my urls:
`path('accounts/', include('allauth.urls')),`

But then in my index.html I call:
`<a href="{% provider_login_url 'google' %}">Login with Google</a>`

with the following error:
`NoReverseMatch at /
Reverse for 'google_login' not found. 'google_login' is not a valid view function or pattern name.`

**Comment by dr-alberto** [comment]
### Issue solved

You need to add `path('accounts/', include('allauth.urls')),` to your **project.urls**, not **app.urls**.
That solved the issue for me.

**Comment by galileoguzman** [comment]
It's what I have actually.

Jus for the record this error does not appear every time it seems like for some users that have refreshed the page or closed the browser and then opened again.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2509
