### ISSUE TITLE
Usernames with both '@' and '.' will not work unless the primary email address matches exactly

### ISSUE THREAD

**Issue by bsmartt13** [pennersr/django-allauth#251]
If the user signs up for a local account with a username containing '@' and '.', unless it's identical to the email they provide, they will be stuck in a situation where their username will not work.  Perhaps this could happen if I want to register a local account and when you ask me to supply a username, I decide my twitter handle is what I'll use: @joe.schmoe (not actually my twitter handle :() ).

The offending code is line 74 of allauth/account/forms.py:

``` python
        else:
            if "@" in login and "." in login:
                credentials["email"] = login
            else:
                credentials["username"] = login
```

There are multiple ways this could be dealt with, possibly most easily just restricting the characters allowed in a username.  Also could be implemented such that if any string we guess to be an email credential fails to work, it could be tried as a username credential.  I'm not familiar enough with django do determine which is easier.  As far as I'm aware, there's no setting offered by django-allauth to easily blacklist characters allowable in usernames.

This is the first time I'm reporting an issue to a github repository.  I appologize in advance if this was obvious and/or not an issue. Also newish to django.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/251
