### ISSUE TITLE
Upload the version with Yandex provider to PyPI

### ISSUE THREAD

**Issue by ArtyIF** [pennersr/django-allauth#2511]
The latest version of django-allauth available on PyPI, 0.41.0, does not have a Yandex.OAuth provider. I need it for my programming school project - integrating a Yandex product into them is kind of an unwritten rule there (mostly because my school is partnered with Yandex). For now I have to install it through a .zip archive for GitHub which is pretty inconvenient.

**Comment by trhr** [comment]
+1

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2511
