### ISSUE TITLE
How to show the user_name in home page? 

### ISSUE THREAD

**Issue by smallnine9** [pennersr/django-allauth#2512]
I have used all-auth as the AUTHENTICATION_BACKENDS of my site, and I can login from my index.html.
Now I want to display current already logged in account‘s username, what should I do in index.html?

**Comment by stfenjobs** [comment]
`request.user.username`

**Comment by stfenjobs** [comment]
https://www.google.com/search?q=django+request+username+in+template

**Comment by smallnine9** [comment]
Yes，I got it， very thanks

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2512
