### ISSUE TITLE
Login using GitHub to be deprecated via URL query parameters

### ISSUE THREAD

**Issue by Jayesh-Mahato** [pennersr/django-allauth#2515]
I am using GitHub as one of the authentication provider. However I have received alerts from GitHub stating that the application has used an access token as pa part of a query parameter to access an endpoint through the GitHub API:

https://api.github.com/user

Please use the Authorization HTTP header instead as using the `access_token` query parameter is deprecated.

Depending on your API usage, we'll be sending you this email reminder on a monthly basis.

Please check this.

**Comment by wmorrell** [comment]
This is a duplicate, #2457 and fixed in #2458 just not included in any release yet.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2515
