### ISSUE TITLE
why doesn't render_to_string() inside render_mail() have access to request?

### ISSUE THREAD

**Issue by dangelsaurus** [pennersr/django-allauth#2516]
I tried to use `...{{ request.get_host }}{% url 'unsubscribe' %}...` inside a custom email template (email_confirmation_message.html), only to learn (unless I'm doing something wrong) that request wasn't available to the template.

digging into `render_mail` inside of `allauth.account.adapter.DefaultAccountAdapter` I see that the `render_to_string` method is missing the optional request parameter.

overriding the method and changing 
```
bodies[ext] = render_to_string(template_name,
                                               context).strip()
```

to 

```
bodies[ext] = render_to_string(template_name,
                                               context, self.request).strip()
```

fixes my problem. But I'm curious if

1.  I'm trying to get access to request the wrong way?
2. There's a reason why request isn't made available to the template?
3. What do I risk breaking?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2516
