### ISSUE TITLE
duplicate key value violates unique constraint "account_emailaddress_email_key"

### ISSUE THREAD

**Issue by harunurkst** [pennersr/django-allauth#2517]
If any user try to signup using same email address, It is raising _IntegrityError at /accounts/signup/_
I have set this conf in settings.py

```
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_UNIQUE_EMAIL = False
```

**Comment by TylerKostuch** [comment]
Just experienced this as well, it's from `ACCOUNT_UNIQUE_EMAIL = False`

After some digging, this setting is used in two migration files. See [account migration 0002](https://github.com/pennersr/django-allauth/blob/master/allauth/account/migrations/0002_email_max_length.py). This means that the table `account_emailaddress` will have a unique restraint in the DB based on this setting.

So, in order for this setting to take effect, we have to perform a migration:

1. Comment out `ACCOUNT_UNIQUE_EMAIL = False`
1. `./manage.py migrate account 0001`
1. Uncomment `ACCOUNT_UNIQUE_EMAIL = False`
1. Run account migrations

Hope this helps :)

**Comment by lucas03** [comment]
I still experience this :(

**Comment by pennersr** [comment]
Closing -- deployment/setup issue.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2517
