### ISSUE TITLE
Email Template working for Temp Mail but not for popular email providers like gmail.

### ISSUE THREAD

**Issue by Hardeepsingh980** [pennersr/django-allauth#2518]
Hey! When we register for a new user. The email is sent but email contains HTML. If the register with email from Temp Mail we get our correct template. Why this issue. Can you please help me out. thanks in advance.

**Comment by pennersr** [comment]
Closing. This does not seem to be pointing to an issue in allauth, but rather an issue in your project specific email templates.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2518
