### ISSUE TITLE
URL paths `/accounts` and `/accounts/social` yield 404 Not Found

### ISSUE THREAD

**Issue by bittner** [pennersr/django-allauth#2524]
> **Disclaimer:** I think this issue has been discussed before, but I can't find any trace of it. So, forgive me if there is actually a duplicate somewhere.

## Hackable URLs

The default URL configuration of allauth is made in a way that doesn't allow users to "hack" the URL path, the address bar of their browsers. This is, in a certain way, a usability concern ("[URLs should be hackable](https://www.nngroup.com/articles/url-as-ui/)", says Jakob Nielsen).

## Current state

- `/accounts` ➜ 404
- `/accounts/email` ➜ list all email addresses + allow adding a new email address
- `/accounts/social` ➜ 404
- `/accounts/social/connections` ➜ list all connected social accounts + allow adding a new social account

The URL path design breaks the user's mental model in two ways:

1. It's inconsistent ("email" vs. "social")
2. It's contradicting ("accounts" and "accounts/social" say, 'there are no accounts')

## Analysis

The choice of this solution seems arbitrary, though I can understand the motivation for the implementation: It seems all technical (e.g. "as a software developer I want to implement 'connections' of social accounts). I do think this can easily be - and should be - corrected. To the benefit of the user.

## Proposed solution

- `/accounts` ➜ show all available options in a single page (possibly similar to the [Sign up](https://github.com/pennersr/django-allauth/blob/master/allauth/templates/account/login.html#L12-L44) page)
- `/accounts/email` ➜ list + manage email accounts (fine as it is)
- `/accounts/social` ➜ list + manage social accounts
- `/accounts/social/connections` ➜ (likely unnecessary, could be deprecated, may redirect permanently to `accounts/social`)

By use of includes for template code it's unlikely that the change for "accounts" would create additional maintenance overhead.

IIUC, the [patterns in the URL configuration](https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/urls.py#L6-L13) for social accounts wouldn't contradict replacing `"connections"` by the empty `""` fallback path.

Would you accept a related PR?

**Comment by derek-adair** [comment]
Hey! +1!!

This should be left open as a "help wanted".  Yes, @bittner, by all means submit a PR this would be great.

**Comment by pennersr** [comment]
I think it's best to move forward with:
- `/accounts/` -➜ Redirect to `/accounts/email/`. I really don't think adding a new overview page that no one would normally use just to get rid of the 404 makes much sense. A redirect will help the user find his/her way.
- `/accounts/sociall/connections/` -➜ Agreed. Though, let's move away from the use of "social". There's not much social about these providers these days, and it also misses the mark when dealing with e.g. SAML. `/accounts/third-party/` ? `/accounts/3rdparty-providers/` ?

**Comment by pennersr** [comment]
Actually, there is a complication here. It is the projects that are integrating allauth that are doing this:

```
    path("accounts/", include("allauth.urls")),
```

But, there are also instances doing:

```
    path("", include("allauth.urls")),
```

The above results in simpleURLs like https://project.org/login -- so there is no intermediate `/accounts/` level. That complicates our discussion:

- We cannot add a `/accounts/` redirect (nor a view) as that would collide with the https://project.org/ landing page.
- The URLs `/third-party/` or `/social/`, while short, don't convey much meaning -- https://project.org/third-party/ ? 

As for the former, the only way of fixing that is by documenting this.

As for the latter, it needs a clear, short, meaningful path:
- `/3rdparty-accounts/` (downside: duplicates the accounts part when used as `/accounts/3rdparty-accounts/`)
- `/3rdparty-providers/` (downside: it actually lists provider *accounts*, not providers, but this does avoid the duplication concern above).

**Comment by pennersr** [comment]
As for the complication, the first bullet is actually detectable. That is addressed here now: b72e6755

As for the second point, the empty prefix situation is mostly used in contexts where the fact that the URL is account related can be derived from the domain name, e.g.: https://account.project.org/email/. For cases where this is not the case, it does not make much sense to put much weight on the issue, as `/email/` would already be an awkard top-level path.

So will opt for the short `/accounts/3rdparty/` URL soon after this.

**Comment by pennersr** [comment]
The above is now completed, see: 5d5d287d

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2524
