### ISSUE TITLE
Paypal oauth has changed and module is out of date

### ISSUE THREAD

**Issue by dnpthree** [pennersr/django-allauth#2534]
I've tried to get paypal oauth to work on multiple devices and I believe the module is out of date.

`Sorry about that
Looks like this action is not supported. Please return and report this error so that we can support it in the future. (invalid client_id or redirect_uri)`

**Comment by AAbouseada** [comment]
I have the same problem as well. The login URL being sent is incorrect as paypal has updated the login paypal application

**Comment by pennersr** [comment]
If there is anything wrong with a provider, please file a PR. The list of providers is way too long, and filing tickets about what is wrong and what could be improved is not really moving things forward.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2534
