### ISSUE TITLE
Messages not sent

### ISSUE THREAD

**Issue by artel1992** [pennersr/django-allauth#2535]
I use these settings and don’t understand why messages are not sent through your library. Django's standard facilities send them

EMAIL_HOST = 'somehost.com'
EMAIL_PORT = 25 # i use other
EMAIL_HOST_USER = 'someusername'
EMAIL_HOST_PASSWORD = 'passwd'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = reverse_lazy('account_confirm_complete')
ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = reverse_lazy('account_confirm_complete')
ACCOUNT_USERNAME_REQUIRED = True

**Comment by pennersr** [comment]
Closing -- there really is no bug in allauth that results in mails not being sent.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2535
