### ISSUE TITLE
Exception: AttributeError: 'OneToOneRel' object has no attribute 'to'

### ISSUE THREAD

**Issue by afabiani** [pennersr/django-allauth#2536]
This happens whenever we have a user model that inherits from an already defined one.

In particular, the `to` property does not exist anymore for `OneToOneRel`, see:

https://github.com/pennersr/django-allauth/blob/master/allauth/account/utils.py#L441

That should be replaced by `related_model` instead, e.g.:

` 
       pk_field = User._meta.pk.remote_field.related_model._meta.pk
`

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2536
