### ISSUE TITLE
Alternative to X-REQUESTED-WITH for `fetch`

### ISSUE THREAD

**Issue by mustafa0x** [pennersr/django-allauth#2538]
As `fetch` doesn't send that header. This confused me for a while, as I wasn't able to get any JSON responses.

I suggest that if the _request_'s content type is `application/json` then it is treated as an ajax/fetch request.

**Comment by pennersr** [comment]
Django documents this:

> The HttpRequest.is_ajax() method is deprecated as it relied on a jQuery-specific way of signifying AJAX calls, while current usage tends to use the JavaScript Fetch API. Depending on your use case, you can either write your own AJAX detection method, or use the new HttpRequest.accepts() method if your code depends on the client Accept HTTP header.

I think that the request should be considered ajax if one of the following holds:

- X-REQUESTED-WITH points to XMLHttpRequest

- The request content type is `application/json`.

- The accept header does not contain `text/html`.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2538
