### ISSUE TITLE
Don't allow users to login with unconfirmed secondary email address

### ISSUE THREAD

**Issue by mbaechtold** [pennersr/django-allauth#254]
I don't know if this is intentional or if I just found a bug?
1. User Bob creates an account by signing up for an account
2. Bob receives a confirmation mail and confirms his address
3. Bob logs in and adds a secondary email address
4. Bob never confirms this secondary address
5. Bob logs out
6. Bob can login with the (never confirmed) secondary address

These are my settings:

```
ACCOUNT_AUTHENTICATION_METHOD = 'email' 
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = 'mandatory' 
ACCOUNT_USERNAME_REQUIRED = False
```

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/254
