### ISSUE TITLE
Login form class not overrideable

### ISSUE THREAD

**Issue by mkmukund19** [pennersr/django-allauth#2540]
This is my Custom Login form:

class CustomLoginForm(LoginForm):

    def login(self, *args, **kwargs):
		self.user.fields['email'].widget.attrs.update({'class': 'js--email'})
		self.user.fields['password'].widget.attrs.update({'class': 'js--password'})
        return super(CustomLoginForm, self).login(*args, **kwargs)

The class is not being overriden any method on how to do it?

**Comment by mkmukund19** [comment]
@pennersr Is there a way to do it from the view or can we directly go to the package form alter it in the package and the required files. Since all auth basically works like an app when you call it in Installed apps. It saves the hassle as well.

**Comment by mkmukund19** [comment]
### Changes to LoginForm fields

`class CustomLoginForm(LoginForm):

	def __init__(self, *args, **kwargs):
		super(CustomLoginForm, self).__init__(*args, **kwargs)
		self.fields['login'].widget.attrs.update({'placeholder': 'Enter Email', 'class': 'js--email'})
		self.fields['password'].widget.attrs.update({'placeholder': 'Enter Password', 'class': 'js--password'})
`
All changes will be reflected when overriding the def __init__ of the class LoginForm. One can use more of the form functions to change the fields for the LoginForm.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2540
