### ISSUE TITLE
Trello Invalid scope in auth - provider bug encodes scope as list

### ISSUE THREAD

**Issue by davidjspooner** [pennersr/django-allauth#2542]
I ran into the same problem as https://github.com/pennersr/django-allauth/issues/2378 

I went digging a little and found that the trello provider overrides get_auth_params to set the scope to the return value from get_scope. That by default returns ['read']. ( which as you point out is expected )

![image](https://user-images.githubusercontent.com/20495185/82132790-7bde0000-97db-11ea-939b-963c70809900.png)

the trouble is that in the view class that "data" dictionary is assumed to be a dictionary of strings and passed to get_redirect which then url encodes it...

![image](https://user-images.githubusercontent.com/20495185/82132791-80a2b400-97db-11ea-9c29-0adbe97797a6.png)

I'd suggest the fix would be in the trello provider to join the array of scopes into a single string for data["scope"] when returning the get_auth_params result

**Comment by derek-adair** [comment]
3 years old -- is this still valid?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2542
