### ISSUE TITLE
Recaptcha on Social login

### ISSUE THREAD

**Issue by ledzgio** [pennersr/django-allauth#2546]
How can I ask users to pass recaptcha before to proceed with social login callback? is it possible to avoid calling the callback prior to pass recaptcha?

**Comment by pennersr** [comment]
It is the social provider that calls the callback. But, if you want to intervene between receipt of that callback and actually signing up using the social provider, I would use a custom signup form where you ask for the recaptcha token and do the backend upstream validation as part of the form validation.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2546
