### ISSUE TITLE
Unable to use with django-two-factor-auth

### ISSUE THREAD

**Issue by 9mido** [pennersr/django-allauth#2547]
I have also referenced this issue on [django-two-factor-auth](https://github.com/Bouke/django-two-factor-auth/issues/357).

My use case is I want to be able to use django-two-factor-auth for my admin login page.

I am also using django-allauth for regular logging in for my superuser and non-superuser users for my front-end site. Django-two-factor-auth's URL is very similar to allauth's URL of /accounts/. A hacker could simply remove the 's' from /accounts/ to gain access to the admin login page.

When I followed this guide exactly: https://github.com/renjithsraj/twofactordjango it allowed me to have 2 factor authentication on my admin site, but I had a problem where if the user was logged out and tried to access a valid login required view on my site, they were redirected back to the admin login page. I could still login with allauth on my front end site for my superuser and non-superusers through the normal front-end site login process.

For example, when logged out and I try navigating to /accounts/password/change/ I get redirected to my admin login page.

I got rid of @login_required decorators for my login only views and replaced them with if request.user.is_authenticated: and elsing a 404 page and it worked but just for my site's views. I am worried about a hacker being able to get to my admin login page via third party package (like allauth and others) URLs if they are logged out since there is less control unless you override all of those third party packages.

I would also like to be able to use django-two-factor-auth, django-allauth, and django-admin-honeypot for more security but unsure how to do that with the stuff going on above.

**Comment by 9mido** [comment]
Update:

I have found a workaround. Use django-otp instead.

**Comment by pennersr** [comment]
If there is a specific problem in allauth that makes integration with django-two-factor-auth troublesome, feel free to reopen. Otherwise, I am going to close this....

**Comment by 9mido** [comment]
I wonder if #1789 had anything to do with this?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2547
