### ISSUE TITLE
Prevent allauth to not verify superuser email

### ISSUE THREAD

**Issue by sajjudroid** [pennersr/django-allauth#2548]
Hi.
I have a situation here.
First i created a superuser using 
python manage.exe createsuperuser

After creating superuser now i am trying to login in in a custom user form.
It redirect me to the email verification page.
I don't want to verify the superuser.

In case other then superuser when want to login in and if they don't verify there email they should be redirect to the email verification.

Please any help in this scenario.

**Comment by sajjudroid** [comment]
Ok i am closing this issue i resloved it by using signals after sign up create an entry in EmailAddress model of allauth and set verify to true.
just copy this code in the model.py file


`
from allauth.account.models import EmailAddress

def userprofile_receiver(sender, instance, created, *args, **kwargs):
    if created:
        if sender is User and instance.is_superuser:
            user_object = User.objects.get(email=instance.email)
            email_addres = EmailAddress()
            email_addres.user = user_object
            email_addres.email = user_object.email
            email_addres.verified = True
            email_addres.primary = False
            email_addres.save()
            return

post_save.connect(userprofile_receiver, sender=User)`

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2548
