### ISSUE TITLE
What's the difference between Azure and Microsoft providers?

### ISSUE THREAD

**Issue by divurgentuser** [pennersr/django-allauth#2550]
What's the difference between Azure and Microsoft providers (and their respective folders in this project?

Azure isn't even listed here - https://django-allauth.readthedocs.io/en/latest/providers.html

Because even when you use Microsoft allauth, your still spinning up in managing the auth in Azure

**Comment by mjmare** [comment]
A little more guidance would indeed be helpful. 

Azure is mentioned on: https://django-allauth.readthedocs.io/en/latest/overview.html
But not here https://django-allauth.readthedocs.io/en/latest/providers.html as mentioned before. 

TIA

**Comment by pennersr** [comment]
Closed via fb53688e

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2550
