### ISSUE TITLE
Confirmation email not sent after signing up

### ISSUE THREAD

**Issue by josylad** [pennersr/django-allauth#2551]
Hi, 
I am using a Custom user model and so far I have been able to hook it into the allauth package extending the "SignupForm" 

here is what my signup form looks like 

**Forms.py**
```
class StudentSignUpForm(SignupForm): 

    @transaction.atomic
    def save(self, request):
        user = super(StudentSignUpForm, self).save(request)
        user.is_student = True
        user.save()
        student = StudentProfile.objects.create(user=user)
        return user
```
**views.py**
```
def student_profile_view(request):
	
    if request.method == 'POST':
		
        user_form = StudentSignUpForm(request.POST, prefix='UF')
		
        if user_form.is_valid():
            user_form.save(request)
            return redirect('/') 
        
    else: 
        user_form = StudentSignUpForm(prefix='UF')
    
    return render(request, 'registration/student-profile.html', {'user_form': user_form,})
```

This works for creating the Custom User as well as creating the user under All auth, the registered email address shows in the "/admin/" under accounts/emails_address but no confirmation emails are being sent to newly registered users. 

How do I fix this??

**Comment by josylad** [comment]
Hey, 
I fixed it. 
The problem was with the views, all I needed to do was to change into a class-based view with the allauth signupview. 

**In views.py**
```
from allauth.account.views import SignupView


class student_profile_view(SignupView):
	
    # The referenced HTML content can be copied from the signup.html
    # in the django-allauth template folder

    template_name = 'registration/student-profile.html'

    # the previously created form class
    form_class = StudentSignUpForm
```

then in my custom signup template, I just passed in "form" to render the registration form. 

**in urls.py**
```
    path('register/student/', student_profile_view.as_view(), name='intern_register'),

```

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2551
