### ISSUE TITLE
How to redirect user to previous page after successful login

### ISSUE THREAD

**Issue by saileshkush95** [pennersr/django-allauth#2554]
Thanks for this amazing package, It working perfectly in my project. But I've have one issue , that is user didn't redirect it its previous page after successful login. Actually it redirect to the homepage. This is because i've used LOGIN_REDIRECT_URL = '/' in my settings file. But i didn't know how to redirect user to its previous page after successful login.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2554
