### ISSUE TITLE
Sign Up Error

### ISSUE THREAD

**Issue by CMNDER** [pennersr/django-allauth#2556]
when i try to sign up i meetup with this error although the user account is created 
[WinError 10061] No connection could be made because the target machine actively refused it

**Comment by 0leg5ergeev** [comment]
Try to declare an `EMAIL_BACKEND` for your project in settings.py (for example [`django.core.mail.backends.console.EmailBackend`](https://docs.djangoproject.com/en/3.0/topics/email/#console-backend) ) or just disable allauth's emails with [ACCOUNT_EMAIL_VERIFICATION = "none"](https://django-allauth.readthedocs.io/en/latest/configuration.html) in same file.

**Comment by pennersr** [comment]
https://django-allauth.readthedocs.io/en/latest/faq.html#why-did-you-just-close-my-issue

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2556
