### ISSUE TITLE
Crash on back button after login

### ISSUE THREAD

**Issue by arctelix** [pennersr/django-allauth#256]
I am experiencing a bug where pressing the back button after log in causes an error. It is cause by get_authenticated_redirect_url()=None.  I have fixed the issue in the commit below:

https://github.com/arctelix/django-allauth.git@4ccd03ad53bce1518955945bdd5e17a573c24717

I have recently implemented SSL middle-ware that redirects all /accounts/ urls to https and http when laving /accounts/.  I'm not sure if my middle ware is causing the issue or not but just in case others run into this.

The above commit redirects to the default log in in URL if you try and back up to the log in url.  I am not sure if this is what you intended or if the intended behavior would be to just allow the user to back up to the log in url.  I'm not a big fan of sites preventing me from reversing out....

Can anybody confirm that this bug exists in the current master branch of allauth?

**Comment by Bartleby2718** [comment]
Is this fixed for `socialaccount` as well? I have the same problem, and it doesn't give me any error message even though I followed [this StackOverflow answer](https://stackoverflow.com/questions/36728887/debugging-django-allauth-social-network-login-failure).
The `get_authenticated_redirect_url` method for `socialaccount` is in this line: https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/views.py#L65

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/256
