### ISSUE TITLE
Can I use django-allauth to social accounts API access?

### ISSUE THREAD

**Issue by tomasz-grzesik** [pennersr/django-allauth#2561]
Hi,

i am using django-allauth to account registration.
I would like to allow my logged users to add some social accounts.
I need authorize my users social accounts with special scope.
Is it possible?

**Comment by efojs** [comment]
I'm not sure I get you, but what you ask seems to be built in  

[Supported Flows](https://django-allauth.readthedocs.io/en/latest/overview.html#supported-flows):
> - Signup of both local and social accounts
> - Connecting more than one social account to a local account
> - Disconnecting a social account – requires setting a password if only the local account remains
> - Optional instant-signup for social accounts – no questions asked

Basics (bottom of the [Installation](https://django-allauth.readthedocs.io/en/latest/installation.html#post-installation) page):
> For each OAuth based provider, either add a SocialApp (socialaccount app) containing the required client credentials, or, make make sure that these are configured via the SOCIALACCOUNT_PROVIDERS[<provider>]['APP'] setting.

[Details and list of prooviders](https://django-allauth.readthedocs.io/en/latest/providers.html)

**Comment by pennersr** [comment]
https://django-allauth.readthedocs.io/en/latest/faq.html#why-did-you-just-close-my-issue

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2561
