### ISSUE TITLE
Option to increase scope (or broaden default scope) for Patreon (or all providers)?

### ISSUE THREAD

**Issue by nstephenh** [pennersr/django-allauth#2563]
Hello! I'm using allauth for patreon authentication, and was wondering if there was any reason for the current scope, any way to increase it in my application without forking allauth, and if not whether it should be increased. Ideally I would like campaigns.members[email] added to the current scope, and I'm sure that other people might need campaigns.members.address.

Thank you.

**Comment by iarp** [comment]
```
SOCIALACCOUNT_PROVIDERS = {
    'patreon': {
        'SCOPE': [...],
    }
}
````

Depending on the API version you use (default is v1) you need to add the scopes [found on these lines](https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/providers/patreon/provider.py#L32) or lines 30,31 if using v2.

**Comment by nstephenh** [comment]
While I understand I could fork the library for this, It would be nice to be able to change these options without forking. I ended up finding a different solution anyway, but thank you.

Leaving this open as I believe the question/suggestion is still valid.

**Comment by iarp** [comment]
Nothing is being forked, its a setting set in your [projects settings.py](https://django-allauth.readthedocs.io/en/latest/configuration.html)

**Comment by nstephenh** [comment]
Ahhhh I see. Thanks

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2563
