### ISSUE TITLE
Feature Request: Add more flexibility for error handing

### ISSUE THREAD

**Issue by Ri-Dearg** [pennersr/django-allauth#2564]
The app, while full of features, seems to have a glaring omission in the area of error handing customisation.
For instance, none of the Configuration settings are based on error handling, none of the adaptors are based on error handling and none of the signals are about handling errors either. Even writing custom class views make it very difficult to intercept them.

I'm trying to redirect to a custom template after a validation error, No matter what I do, on error, I am redirected to the stock template URLs like "accounts/login". I'm sure it has to do with the `response['Location']` attribute. However, any way of doing it seems to require that I dive deep into the code, changing classes buried within classes, which seems unnecessarily obtuse. Alternatively, I could inherit and rewrite views, etc. I think some simple settings added to the project would be much appreciated. I'd contribute but I'm really not experienced enough to do that.

**Comment by derek-adair** [comment]
This is a bit confusing to me.  It's *very* possible I do not understand the use case @Ri-Dearg is suggesting.

1. Do you have a specific way you would like to invoke error handling?  Examples in other apps?
2. Why would you want to redirect on a form submission error to the page other than the page it was submitted?

If you have an improvement in mind pull requests are a really great place to succinctly communicate and collaborate.

--------------
aside for @pennersr -- probably close as help wanted?  It's also possible this is a suggestion for something out of scope; allauth should do nothing outside of stock form use and any custom form things should exist elsewhere.

**Comment by pennersr** [comment]
Issue is unclear to me as well, e.g.:

> I'm trying to redirect to a custom template after a validation error

What kind of validation error is this, a form validation error? And you want to not present those field errors but immediately redirect? Perhaps `ImmediateHttpResponse` can be used, but without a very clear use case scenario we need to close this.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2564
