### ISSUE TITLE
How to use an email alias when sending verification mail? 

### ISSUE THREAD

**Issue by TotallyNotChase** [pennersr/django-allauth#2566]
Is there a way to specify the email alias I'd like to use when sending the verification email? I've the email host setup but I need to use an alias for the `send_mail` itself.

I know I can do this using the `from` parameter in django's `send_mail` but how can I integrate this with allauth?

**Comment by TotallyNotChase** [comment]
Looks like I can achieve this by setting django's `DEFAULT_FROM_EMAIL` to my alias.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2566
