### ISSUE TITLE
Google Credentials refresh token_uri blocked by CSRF

### ISSUE THREAD

**Issue by 72L** [pennersr/django-allauth#2570]
Hello, I'm using Google's  google.oauth2.credentials.Credentials, like this:
```
from google.oauth2.credentials import Credentials
social_token = SocialToken.objects.filter(account__user=request.user).first()
Credentials(
        token=social_token.token,
        refresh_token=social_token.token_secret,
        token_uri='http://localhost:8000/accounts/google/login/callback/',
        client_id=social_token.app.client_id,
        client_secret=social_token.app.secret
)
```
It looks like the Credentials object will refresh the token using the given parameters. However, it looks like the callback URL is being protected with CSRF. This is the error message:

```
Forbidden (CSRF cookie not set.): /accounts/google/login/callback/
"POST /accounts/google/login/callback/ HTTP/1.1" 403 2864
```
Is there any way to turn off CSRF, or pass in a CSRF token to the callback URI?

**Comment by usamamashkoor** [comment]
@72L  did you find any solution, I am facing the same issue here?

**Comment by iarp** [comment]
`token_uri` on Credentials is expected to be a url to the oauth2 provider's endpoint for token refreshing. For google it should be `https://accounts.google.com/o/oauth2/token`

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2570
