### ISSUE TITLE
socialtoken table got delete every time when server restart

### ISSUE THREAD

**Issue by Rixkz** [pennersr/django-allauth#2571]
Hi, I have a question about socialtoken table, when i run "python manage.py runserver" all of record in table socialtoken got disappear, if i don't want to  delete data every time when my server has rerun, how can i handle it ?

Thanks

**Comment by pennersr** [comment]
I am sorry, this looks like a project specific question, cannot help you there.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2571
