### ISSUE TITLE
KeyError at /accounts/signup/ 'sociallogin'

### ISSUE THREAD

**Issue by Daveson217** [pennersr/django-allauth#2572]
This is my first time using Django All Auth. I have set up all the urls and settings. I haven't setup any social network provider though. The login works, but when I click on the signup it comes up with an error (See Image). Is it because I didn't setup any social network provider?
I am using Django AllAuth 0.42.

![exception](https://user-images.githubusercontent.com/44535844/85229800-ceff3000-b3e3-11ea-980e-f02929343ec9.JPG)

**Comment by pennersr** [comment]
Not sure what is going on here. This is too little to go on, might be an issue in your settings. Closing, if you do feel there is an issue in allauth, please provide a small example project demonstrating the issue.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2572
