### ISSUE TITLE
How to deactivate CSRF for registration form

### ISSUE THREAD

**Issue by sowinski** [pennersr/django-allauth#2573]
Hi,

how can I deactivate the CSRF verification for the registration form? 

I build some landingpages on the same domain not using django / python and the post request fails of course.

Is this possible?

Thank you

**Comment by sowinski** [comment]
```
from allauth.account.views import SignupView
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator

@method_decorator(csrf_exempt, name='dispatch')
class MySignupView(SignupView):
    pass
```

I just did it like described above.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2573
