### ISSUE TITLE
How can I use google calendar api with Django AllAuth ?

### ISSUE THREAD

**Issue by usamamashkoor** [pennersr/django-allauth#2574]
Hi, I want to use to Django AllAuth for google OAuth Login, after the google OAuth login I want to access user calendar events, Can anyone let me know How can I do this using Django AllAuth?

I have implemented the Google OAuth login but I don't know how can I access google calendar using the API?

I also want to access the google access token and want to refresh the access token to if it is expired because I want to use the tokens offline too.
Here is my code 
```

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
            'https://www.googleapis.com/auth/calendar',
            'https://www.googleapis.com/auth/calendar.readonly',
        ],
        'AUTH_PARAMS': {
            'access_type': 'offline',
            # 'access_type': 'online', 
        }
    }
}
```

**Comment by iarp** [comment]
allauth will get you the token and refresh token (see SocialToken table) it does not manage expiry. You can use those tokens to build a [Credential instance](https://google-auth.readthedocs.io/en/latest/reference/google.oauth2.credentials.html) which can then be used to refresh tokens and apply credentials for api calls.

**Comment by pennersr** [comment]
https://django-allauth.readthedocs.io/en/latest/faq.html#why-did-you-just-close-my-issue

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2574
