### ISSUE TITLE
Get the access token of google OAuth

### ISSUE THREAD

**Issue by usamamashkoor** [pennersr/django-allauth#2575]
Hi, I am successfully logged in using Google OAuth and a user is also created in my database, but now I want to access the user access token to make a request to the google calender API.

Can anyone let me know how I can get the google access token from Django All Auth so that I can make a request to the google calender API.?

Any kind of help will be really appreicated.

**Comment by iarp** [comment]
All tokens you need are stored in the SocialToken table.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2575
