### ISSUE TITLE
Django allauth - custom email verification url does not verify

### ISSUE THREAD

**Issue by eakenbor** [pennersr/django-allauth#2576]
I created a custom email verification url so that the user can be redirected to my react frontend before a get request will be sent. However, on sending the get request, a 200 status code is sent back but no email verification takes place. The url sent looks like this:

```http://localhost:8000/verify-email/Mw:1joams:KRlaiGKPx7fhQ6fHVYRtxvYo_v4/``` and I am not sure if that key looks right.

My codes look like these:

```
#Adapter.py
from allauth.account.adapter import DefaultAccountAdapter
from django.conf import settings

class DefaultAccountAdapterCustom(DefaultAccountAdapter):

    def send_mail(self, template_prefix, email, context):
        context['activate_url'] = settings.URL_FRONT + \
            'verify-email/' + context['key']
        msg = self.render_mail(template_prefix, email, context)
        msg.send()
```

```
#Urls.py
from allauth.account.views import confirm_email

url(r'^verify-email/(?P<key>\w+)/$',
        confirm_email, name="account_confirm_email"),
```

```#Settings.py

ACCOUNT_ADAPTER = 'users.adapter.DefaultAccountAdapterCustom' 
```

Please can someone tell me what I am doing wrong?

**Comment by iarp** [comment]
Do you have ``ACCOUNT_CONFIRM_EMAIL_ON_GET = True`` ? If not it's expecting the user to click on a button before confirmation actually happens.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2576
