### ISSUE TITLE
I implemented Django i18n to my app and Allauth login stopped working

### ISSUE THREAD

**Issue by goromachine** [pennersr/django-allauth#2577]
I have implemented Allauth since few moths ago and everything was working fine. 

Without making any change on the login code and just by implementing i18n on the whole application, my login forms stopped working at all. I can see the template, I can fill the input, but either if I use correct or wrong credentials when I click on the button to log in it just seems to refresh the page and do not log in nor show error messages. The input fields are also empty.

If I go to django admin and I log in with the default django admin login, it works fine and I can enter with my admin user.

I checked the installation guide and the configuration steps two more times but there is nothing changed and everything seems to be on it's place. I tried updating from django allauth 0.42.0 to 0.43.0 but the problem is not solved.

The register, passwd recovery and email verification works fine. It's just the login.

I have a custom login form, but as I said it was working fine. The only thing I do is modify the layout with crispy-forms:

```
class CustomLoginForm(LoginForm):
    def __init__(self, *args, **kwargs):
        super(CustomLoginForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        # Add magic stuff to redirect back.
        self.helper.layout.append(
            HTML(
                "{% if redirect_field_value %}"
                "<input type='hidden' name='{{ redirect_field_name }}'"
                " value='{{ redirect_field_value }}' />"
                "{% endif %}"
            )
        )
        # Add password reset link.
        self.helper.layout.append(
            HTML(
                "<p><a class='button' href={url}>{text}</a></p>".format(
                    url=reverse('account_reset_password'),
                    text=_('Forgot Password?')
                )
            )
        )
        # Add submit button like in original form.
        self.helper.layout.append(
            HTML(
                '<button class="btn btn-secondary btn-main btn-block" type="submit">'
                '%s</button>' % _('Sign In')
            )
        )

        self.helper.form_class = 'login'
        self.helper.form_action = '/login/'
        self.helper.label_class = 'col-xs-2 d-none'
        self.helper.field_class = 'col-xs-8'
```

and on the settings.py I have:

`ACCOUNT_FORMS = {
    "login": "users.forms.CustomLoginForm"
}`

Any Ideas? 
Thank you.

**Comment by pennersr** [comment]
https://django-allauth.readthedocs.io/en/latest/faq.html#why-did-you-just-close-my-issue

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2577
