### ISSUE TITLE
if user.is_authenticated not recognizing that user is logged in

### ISSUE THREAD

**Issue by Ces-D** [pennersr/django-allauth#2579]
After logging in, the app does not recognize that the user.is_authenticated. It realizes that user is authenticated when using the built-in templates, but when creating unique template, the app does not load user. 

![image](https://user-images.githubusercontent.com/58753718/85906157-73fe7c00-b7db-11ea-8ec1-d0a801c2594c.png)

![image](https://user-images.githubusercontent.com/58753718/85906183-88427900-b7db-11ea-97d0-d56048370365.png)

**Comment by Lord-sarcastic** [comment]
Try using `request.user` in place of `user`.

**Comment by pennersr** [comment]
Closing -- not an issue in allauth

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2579
