### ISSUE TITLE
How can I translate this package in my project?

### ISSUE THREAD

**Issue by hakhsin** [pennersr/django-allauth#2581]
Hi, I copied all allauth templates into `my-project/templates/account` and retranslate all translatable. But my translate doesn't work.
[stackoverflow](https://stackoverflow.com/questions/62571086/translate-django-allauth)
Now, how can I translate this package in my project?

**Comment by pennersr** [comment]
https://django-allauth.readthedocs.io/en/latest/faq.html#why-did-you-just-close-my-issue

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2581
