### ISSUE TITLE
Remove email subject prefix

### ISSUE THREAD

**Issue by anuj9196** [pennersr/django-allauth#2587]
For every email sent via `allauth`, the email subject is prefixed with `[Site Name]`.

I do not want to add the prefix to the subject as I'm using a custom email subject. I tried removing it by setting
```
ACCOUNT_EMAIL_SUBJECT_PREFIX = None
# and
ACCOUNT_EMAIL_SUBJECT_PREFIX = ''
# and
ACCOUNT_EMAIL_SUBJECT_PREFIX = ' '     # one space
```

But not is working and the subject is still prefixed with the subject name.

**Comment by utrejakash** [comment]
Hi @anuj9196 ,
I think right now if you try to do configuration like below.
EMAIL_SUBJECT_PREFIX = None
ACCOUNT_EMAIL_SUBJECT_PREFIX = None
then you will get subject as [Site_NAME]  Please Confirm Your E-mail Address like this.

but make sure you don't have any email with this subject in your gmail "[127.0.0.1:800] Please Confirm Your E-mail Address"
even in the trash as well.

**Comment by anuj9196** [comment]
@utrejakash I don't want to add any prefix to the subject. I want to remove the prefix totally and only use what is in the subject txt file.

**Comment by iarp** [comment]
`ACCOUNT_EMAIL_SUBJECT_PREFIX = ''`

None is default and assumes you want the site name as the prefix.

**Comment by anuj9196** [comment]
@iarp Already tried it. Already mentioned it is not working in the question.

**Comment by iarp** [comment]
Do you know what version of allauth you have installed? ``pip show django-allauth``.

Just to be sure double check you only have one ``ACCOUNT_EMAIL_SUBJECT_PREFIX`` in settings.

Are you using a default backend like ``smtp.EmailBackend`` or something similar?

**Comment by anuj9196** [comment]
allauth version: `django-allauth==0.42.0`

Yes only one entry for `ACCOUNT_EMAIL_SUBJECT_PREFIX` in settings

Email bacend is `EMAIL_BACKEND = "anymail.backends.amazon_ses.EmailBackend"`

**Comment by iarp** [comment]
I've had no luck with this unfortunately. I've tried many setting combinations and the subject always comes out as expected. Something else is up. If you can, do a breakpoint in the format_email_subject [found in the account adapter](https://github.com/pennersr/django-allauth/blob/master/allauth/account/adapter.py#L83) and see what is being set. If it comes out as you expect then something else is adding the prefix.

If breakpoint is not an option then you can temporarily add a custom adapter and print its output:

Within your projects settings.py file

```python
ACCOUNT_ADAPTER = 'adapter.CustomAccountAdapter'
```

In the root of your django projects folder create a new file called adapter.py with these contents

```python
from allauth.account.adapter import DefaultAccountAdapter

class CustomAccountAdapter(DefaultAccountAdapter):
    def format_email_subject(self, subject):
        subject = super().format_email_subject(subject)
        print(subject)
        return subject
```

and see what you get in console.

**Comment by pennersr** [comment]
The `format_email_subject` method is correct -- as @iarp  mentions, when ACCOUNT_EMAIL_SUBJECT_PREFIX is set to the empty string, no prefix will be added.  If it is not working for you, please check your settings and/or try stepping through that method to see why it is not working for you.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2587
