### ISSUE TITLE
Integrity error at Signup

### ISSUE THREAD

**Issue by davidecosta** [pennersr/django-allauth#259]
Hello everybody,
I am trying to figure if I encountered a real issue or is simply my lack of experience.
The problem is the following during signup with NO social account:
![Screen Shot 2013-04-26 at 5 24 55 PM](https://f.cloud.github.com/assets/759661/431323/89501634-ae85-11e2-8ad7-725463e15796.png)

I solved it commenting line 279 in allauth/account/forms.py :
# super(SignupForm, self).save(new_user)

Is that right?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/259
