### ISSUE TITLE
Preventing a save

### ISSUE THREAD

**Issue by zappycode** [pennersr/django-allauth#2590]
I am customizing my signup form such that when a user signs up they also have to provide their credit card information. I am using this custom form to override the `save()` function [https://django-allauth.readthedocs.io/en/latest/forms.html#signup-allauth-account-forms-signupform](https://django-allauth.readthedocs.io/en/latest/forms.html#signup-allauth-account-forms-signupform)

My question is, if the payment is declined, I'd like to prevent the save from happening and return the user to the signup page with an error message. Do you know how I can prevent the save from happening in the `save()` function?

**Comment by pennersr** [comment]
I would really approach this differently. Payments is typically an asynchronous process, involving callbacks et al -- definitely not something you want synchronously from within a form. You'll have to handle charge backs as well, so then you'll have to handle the scenario of users that are already signed up as well. All in all, closing -- this is not an issue in allauth.

**Comment by zappycode** [comment]
Well if we leave payments out of it, I'm just wondering if there's a way to prevent a signup from happening if you don't like some of the data. 

But lack of responses tells me I'm barking up the wrong tree :) Thanks for the time you've put into AullAuth @pennersr! It's been a great way to get off the ground quickly

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2590
