### ISSUE TITLE
Is there a guide on how to contribute?

### ISSUE THREAD

**Issue by rasulkireev** [pennersr/django-allauth#2593]
I would love to contribute to this library, just not entirely sure how. Is there a guide or an example of how one goes about adding support for more services?

**Comment by 0leg5ergeev** [comment]
1. fork the project
2. develop something
3. create a pull request

**Comment by rasulkireev** [comment]
Yeah, I get that... I meant a process for how to add another social integration. 

People can go through the existing code and figure it out. Sure, but if there was an instruction written it would greatly increase the speed of development and hence make the library better (more social extensions). 

I'll try to write one when I figure it out.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2593
