### ISSUE TITLE
Spam Clicking Email Re-send Verification Button

### ISSUE THREAD

**Issue by 9mido** [pennersr/django-allauth#2595]
Update: A solution for this issue is below and there is a pull request but a merge is needed. 

Clicking really fast on form buttons such as the /accounts/email/ form re-send verification button for example will allow someone to spam a user's inbox over and over and fill it up quickly. 

If using a free email provider like gmail, there is a limit of how many emails you could send per day. But if this bug is abused, a business might get emails temporarily suspended and not be able to send any emails once that limit is reached which could be disastrous. 

There should be a way to disable/hide this button after submitting and after the form's action page refresh. Or set a timer on how long each user has to click that button again. Might need to use localStorage if using JavaScript. Otherwise something on the django side might need to be done which would be better than JavaScript.

Examples of fixing this would be like Reddit and Stackoverflow posts where users are not able to post again until X minutes after the original post. 

https://i.stack.imgur.com/4J3jr.png

If an email address is already confirmed, the re-send verification button should be disabled unless the user adds another email address and selects the radio button to modify the new email address. There is no need for an existing email address to keep getting verification emails if it has already been verified.

**Comment by 9mido** [comment]
Here is a javascript solution to solve this issue which uses localStorage and CSS but it is not ideal because it is client side and not server side. If anyone can provide a django solution to this problem, I as well as others will be thankful for it!

CSS:

```
button.disabled,
button[disabled] {
	box-shadow: none;
	cursor: not-allowed;
	opacity: 0.5;
	pointer-events: none;
}
```

HTML:

`<button id="re-send" class="secondaryAction"  type="submit" name="action_send" >{% trans 'Re-send Verification' %}</button> `

JavaScript:

```
<script>

  const refreshBtn = document.getElementById("re-send");
  refreshBtn.addEventListener("click", refresh);
  disable();

  function disable() {

    if (localStorage.getItem("disableRefresh")) {

      refreshBtn.setAttribute("disabled", ""); 
      setTimeout(enable, 9000); 
    }
  }

  function enable() {
    refreshBtn.removeAttribute("disabled");
    localStorage.removeItem("disableRefresh")
  }

  function refresh() {
    var btn = document.querySelector('#re-send');
    btn.classList.add('disabled');

    localStorage.setItem("key", "value");
    location = location;

  };

</script>
```

**Comment by 9mido** [comment]
Finally figured out a django solution for this. However, if someone could make a PR that allows for customizing a setting for the period of time for timezone.timedelta(minutes=SETTING) to specify how long it will be for the form to re-submit itself again, that would be awesome!

To this function https://github.com/pennersr/django-allauth/blob/master/allauth/account/views.py#L425-L441 add the following code:

View:

```
from app.models import ResendVerificationModel
import datetime
from django.utils import timezone
import pytz
from django.http import HttpResponseServerError

            #if username already exists in the db and the time in the db is greater than now - 1 minute, the form cannot be submitted again
            if ResendVerificationModel.objects.filter(username=request.user, inserted__gt=timezone.now() - timezone.timedelta(minutes=1)):
                return HttpResponseServerError("You already submitted an email request. Please wait to try again.")

            #if email from from the form submission is the same as email in the db and the time in the db is greater than now - 1 minute, the form cannot be submitted again 
            if ResendVerificationModel.objects.filter(email=email, username=request.user, inserted__gt=timezone.now() - timezone.timedelta(minutes=1)):
                print(timezone.now() - timezone.timedelta(minutes=1))
                return HttpResponseServerError("You are only allowed one email verification request per day. Please try again tomorrow.")
            #if email from from the form submission is the same as email in the db and the time in the db is less than now - 1 minute, submit the form again, delete that previous old row
            if ResendVerificationModel.objects.filter(email=email, username=request.user, inserted__lt=timezone.now() - timezone.timedelta(minutes=1)):
                ResendVerificationModel.objects.filter(email=email, username=request.user, inserted__lt=timezone.now() - timezone.timedelta(minutes=1)).delete()

            #create the row in the db
            ResendVerificationModel.objects.create(email=email, username=request.user)
```


Model:

```
from django.conf import settings

class ResendVerificationModel(models.Model):
    email = models.EmailField()
    inserted = models.DateTimeField(auto_now_add=True)
    username = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, on_delete=models.CASCADE)
```

**Comment by pennersr** [comment]
Closed via 825adc67

**Comment by 9mido** [comment]
Thanks @pennersr! Just to confirm, does this change account for all places that involve email sending: password resets, logins with unverified emails, signups, re-send verification emails? What happens now with the timeout PR that is still open? That timeout PR could be used in other places like the change password form as well.

**Comment by pennersr** [comment]
@9mido there is still work to do, but the timeout mechanism can be turned more generic into a rate limit system -- see https://github.com/pennersr/django-allauth/pull/2631#issuecomment-991909992

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2595
