### ISSUE TITLE
Site crashes and is only shown half (like {% extends 'base.html' %} would be ignored)

### ISSUE THREAD

**Issue by snake-soft** [pennersr/django-allauth#2597]
I have a strange error when installing django-allauth.
I'm not sure what exactly causes the error.

After installing django-allauth, the site is cut off.
The head is empty and the page source consists only of parts from the sub template.
All that is in the base template is missing.
As the menu is inside the base template, it is missing, too.
Instead there is a additional menu:
```html
<div>
      <strong>Menu:</strong>
      <ul>
        
        <li><a href="/accounts/login/">Sign In</a></li>
        <li><a href="/accounts/signup/">Sign Up</a></li>
        
      </ul>
    </div>
```
All sites behave like that.
It looks to me, like the {% extends '' %} tag isn't working anymore.

Do you have any idea, what could cause this?

---

settings.py
```python
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.github',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.instagram',
    'allauth.socialaccount.providers.odnoklassniki',
    'allauth.socialaccount.providers.telegram',
    'django_db_logger',
    'channels',
    'analytical',
    'pwa',
    # project apps...
]

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

SITE_ID = 1
```

PS: You can have a look at the source at [https://github.com/snake-soft/nomoney.shop/tree/9dfa312a418e5a5dc610ae0f09efe0ceea0c6fe2](https://github.com/snake-soft/nomoney.shop/tree/9dfa312a418e5a5dc610ae0f09efe0ceea0c6fe2)

Best regards

**Comment by pennersr** [comment]
https://django-allauth.readthedocs.io/en/latest/faq.html#why-did-you-just-close-my-issue

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2597
