### ISSUE TITLE
Prevent Staff Users From Logging In On Front End

### ISSUE THREAD

**Issue by 9mido** [pennersr/django-allauth#2598]
Django's default behavior is to allow admin/staff users to login on the frontend of their site and when navigating to /admin/ page, users are automatically logged into the admin interface.

This is bad because if a hacker knows the admin/staff credentials, they are able to login from the frontend and then access the admin interface even if you setup OTP or other security mechanisms on the admin login page.

Is there a way to restrict admin/staff users from logging in on the frontend? But they are only allowed to login from the /admin/ page?

**Comment by 9mido** [comment]
One option is to use middleware to prevent admins from logging into the frontend of the site:

https://stackoverflow.com/questions/57357274/how-to-manage-the-separate-session-for-same-browser-admin-frontend-in-django

**Comment by marksweb** [comment]
If you use OTP and an admin/staff user logs into the frontend, as they move to `/admin` they wouldn't (shouldn't) have an authenticated device (OTP) so should be prompted to login.

If that isn't happening you're likely missing something in your configuration.

The `django_otp` middleware handles attaching a device to a user; https://github.com/django-otp/django-otp/blob/master/src/django_otp/middleware.py

If you use the OTP admin site then it will ensure users have a device before allowing access to admin; https://django-otp-official.readthedocs.io/en/stable/auth.html#the-admin-site

What you don't want to do is force those users to login via admin if all they want to do is access something on the frontend.

**Comment by 9mido** [comment]
@marksweb Good catch! I was missing 

```
from django_otp.admin import OTPAdminSite
admin.site.__class__ = OTPAdminSite

```
from urls.py.

Thank you! If you want to collaborate with me on /accounts/email/ and /accounts/password/reset/ spam clicking / email sending related issues that this allauth has, please let me know!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2598
