### ISSUE TITLE
facebook token size issue

### ISSUE THREAD

**Issue by gitdeepak** [pennersr/django-allauth#260]
socialaccount - socialtoken model -- has token size set to varchar(200) - Recently i ran into the issue : 
Exception Value:  
value too long for type character varying(200)

The token supplied by facebook was 234 characters.
I changed the model to 300 and did an alter table of my db to 300 and then it worked like a charm.

I am surprised no one here has that issue (because i still see the token size to be 200) 

Do you want me to submit the fix for this ? or feel free to fix it ? or if i am missing something let me know.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/260
