### ISSUE TITLE
Microsoft Azure directory with multi-tenant application pattern

### ISSUE THREAD

**Issue by Gouravchawla** [pennersr/django-allauth#2601]
I've been searching this for a while now. Does anybody here know how to handle the below case.

I have a SaaS app which requires SSO using Azure directory. I'm able to do it with allauth. Now, I need to restrict this to tenants(customers) who have a subscription with us.

To do this, I'm thinking, if I can get the tenantId from Azure directory then I can do a database lookup to see if the customer has a subscription with us. So, does anybody here know how can I accomplish that?

Here is a reference from MS which is not that clear on the `how to get tenantId part`.

https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-convert-app-to-be-multi-tenant#update-your-code-to-handle-multiple-issuer-values

The code from MS for `.net` for doing what I want to do with allauth: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/master/2-WebApp-graph-user/2-3-Multi-Tenant/README.md

**Comment by pennersr** [comment]
https://django-allauth.readthedocs.io/en/latest/faq.html#why-did-you-just-close-my-issue

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2601
