### ISSUE TITLE
Saving images to user model

### ISSUE THREAD

**Issue by Siebe-Tarpit** [pennersr/django-allauth#2602]
I want to save the avatar of people for example when they log in with discord to their wagtail user model.
What's the best place to do this?

**Comment by marksweb** [comment]
On an associated `Profile` model where you can add whatever fields you like.

**Comment by vylmen** [comment]
You [don't need to](https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/providers/discord/provider.py#L11).

**Comment by pennersr** [comment]
https://django-allauth.readthedocs.io/en/latest/faq.html#why-did-you-just-close-my-issue

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2602
