### ISSUE TITLE
Request: ability to configure "email send failures okay" when ACCOUNT_EMAIL_VERIFICATION is 'optional'

### ISSUE THREAD

**Issue by sunweiyang** [pennersr/django-allauth#2605]
For my app, I wish to configure `ACCOUNT_EMAIL_VERIFICATION = 'optional'` while also allowing user registration even when users mis-type their email addresses during signup. Currently, there's no way to do this without the user experience breaking (despite the `User` and `EmailAddress` objects still being created), because this results in an email send error (`AnymailRequestsAPIError` when using django-anymail, for example). Is this something that django-allauth would be willing to support?

**Comment by iarp** [comment]
I just wrote [this](https://github.com/pennersr/django-allauth/issues/2606#issuecomment-663744457) comment to the issue #2606  on how to catch email errors. It would be up to you on what to do with errors.

**Comment by pennersr** [comment]
Also see:

- https://github.com/pennersr/django-allauth/issues/2606#issuecomment-695090123
- Django's `fail_silently` over at https://docs.djangoproject.com/en/4.2/topics/email/

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2605
