### ISSUE TITLE
Catch send email exceptions and act accordingly

### ISSUE THREAD

**Issue by barclaey** [pennersr/django-allauth#2606]
Currently if the sending emails throws an exception this is not catched (f.ex. in the perform_login), this leads to unwanted behavior in some cases.
For example with a user signup with optional email confirmation, this could be gracefully handled without the user having to encounter an error, in fact the user is signed up correctly and could just be logged in and redirected properly in stead of getting a http 500 response.
I know this is solvable with a custom email backend, but this seems a bit dirty as a workaround, plus it does not cover all cases properly where you do want different behavior upon send email exceptions.

**Comment by iarp** [comment]
Create your own account adapter class and override [send_email method](https://github.com/pennersr/django-allauth/blob/master/allauth/account/adapter.py#L135). Set [ACCOUNT_ADAPTER](https://django-allauth.readthedocs.io/en/latest/configuration.html) to that newly created custom adapter class.

That will let you do whatever you wish with attempting to send the email and catching whatever errors you want to catch (or not catch). send_email returns nothing so if you catch and just let the program continue then whatever action the user was doing will keep going.

**Comment by 9mido** [comment]
Please share a solution to this issue here once found so it could help others alleviate this.

**Comment by barclaey** [comment]
Thanks for the reply!

I think catching and 'swallowing' all email failures on whatever action the user is doing, is not the best solution. In some flows it will be best to just let the userflow continue in other cases an alternate flow is advised. Apart from the user getting confronted with a http 500 response, not catching the exceptions may potentially have other side effects like functions/methods that did not complete, singals that may be missed, etc. 

Currently I integrated [django post office](https://github.com/ui/django-post_office) which has a custom email backend catching the exceptions, I manage email problems from there without interrupting the allauth flows. However even when my problem is solved, I believe it is good practice to catch email errors in the package.

**Comment by pennersr** [comment]
All emails sent go via the adapter `send_mail()` method. You're free to add your project specific logic there. I don't see how this can be handled in a generic fashion that would be suitable for all projects. To me, an exception in sending mail truly points to an internal server error. Sending of email is typically an asynchronous process, so if Django is unable to queue the mail for delivery something is seriously wrong.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2606
