### ISSUE TITLE
Discord Oauth Flow now seems to require `code_verifier` parameter.

### ISSUE THREAD

**Issue by daghack** [pennersr/django-allauth#2607]
It seems that the Discord Oauth flow now errors with:
`'{"error": "invalid_request", "error_description": "Missing code_verifier"}`

Would love if I were just missing something, though.

**Comment by iarp** [comment]
Discords documentation does not mention code_verifier anywhere and its working perfectly fine in my testing so far without it. Are you sure this is discord?

**Comment by daghack** [comment]
Ah! Had to search through the code to find that alloauth expected a field `secret` that it would submit as the `client_secret`. I had the field named `client_secret`, to match the discord documentation.

Thank you and sorry!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2607
