### ISSUE TITLE
"Social Network Login Failure" while attempting facebook login.

### ISSUE THREAD

**Issue by krischal** [pennersr/django-allauth#2609]
I am trying to integrate facebook login in django using django-allauth library. Here is my website link, https://thelittlechamp.com/ on the nav bar you can see facebook login button. The problem is when i try to login it says "Social Network Login Failure" even though i have configured all settings properly. Please provide me suggestions where i might have done wrong. I can provide anyother configuration screenshot if necessary.

**Comment by iarp** [comment]
Ensure you have the proper client id, secret, and site selected.

As a temporary solution, copy the [socialaccount/authentication_error.html](https://github.com/pennersr/django-allauth/blob/master/allauth/templates/socialaccount/authentication_error.html) template to your project and you can add something like ``{{ auth_error }}`` in the html to see what error message is appearing. Once fixed remove it.

**Comment by krischal1** [comment]
After following your steps, i got this:
{'provider': 'facebook', 'code': 'unknown', 'exception': None}
From this can you suggest me where i did wrong?

**Comment by krischal1** [comment]
<script id="allauth-facebook-settings" type="application/json">
{"appId": "669910837179987", "version": "v7.0", "sdkUrl": "//connect.facebook.net/en_US/sdk.js", "initParams": {"appId": "669910837179987", "version": "v7.0", "cookie": true}, "loginOptions": {"scope": "email,public_profile"}, "loginByTokenUrl": "http://thelittlechamp.com/accounts/facebook/login/token/", "cancelUrl": "http://thelittlechamp.com/accounts/social/login/cancelled/", "logoutUrl": "http://thelittlechamp.com/accounts/logout/", "loginUrl": "http://thelittlechamp.com/accounts/facebook/login/", "errorUrl": "http://thelittlechamp.com/accounts/social/login/error/", "csrfToken": "Z8NGWyWh9HxaM7BCUfZkdV7WvqYvGiOp5UZz023enBY1SjqwqBcTFRHcjGlbCEcq"}
</script>

In the above code as we can see all the urls have the http protocol but my website is https secured. Is there any way to fix it?

**Comment by iarp** [comment]
Whatever webserver you're using to host the website is not passing the headers that let django know you're using ssl. https://docs.djangoproject.com/en/dev/topics/security/#ssl-https

**Comment by pennersr** [comment]
https://django-allauth.readthedocs.io/en/latest/faq.html#why-did-you-just-close-my-issue

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2609
