### ISSUE TITLE
Signout doesn't work.

### ISSUE THREAD

**Issue by aladagemre** [pennersr/django-allauth#261]
I had realized that we could not perform "sign out" some time ago (a few months). I found the workaround of using version 625c299e2d19e8befcbb955f40caf8afb7fd0341 and it was fine with signing out. 

Now I tried 0.10.0 and 0.10.1 and latest commit 4bb9e0170f37d8196bd0c4a78e83adb7b779c113 and they have the same signout problem.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/261
