### ISSUE TITLE
Can I use this library with django rest framework ?

### ISSUE THREAD

**Issue by ahmedosama5200** [pennersr/django-allauth#2610]

**Comment by Lord-sarcastic** [comment]
There is a wrapper around this package for use with DRF [here](https://github.com/jazzband/dj-rest-auth)

**Comment by Denis-Step** [comment]
I use it without the jazzband project and just implement a User serializer. You want to be careful and avoid leaking User info, but allauth plugs into the default DRF functionality very well.

**Comment by pennersr** [comment]
https://django-allauth.readthedocs.io/en/latest/faq.html#why-did-you-just-close-my-issue

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2610
