### ISSUE TITLE
Is it possible to use only some views?

### ISSUE THREAD

**Issue by lapinvert** [pennersr/django-allauth#2613]
When we do
```
path('accounts/', include('allauth.urls')),
```
that includes *all* django-allauth urls, which includes urls that I don't plan to use.

Somebody may find those urls by accident and I would prefer not to use some.

How can I achieve that?

**Comment by iarp** [comment]
You would most likely have to copy the url patterns you want from allauths account and socialaccount into your root (or a custom apps) urls.py. However any views, templates..etc that try to link to a url you don't include will cause failures.

What urls are you not wanting?

**Comment by lapinvert** [comment]
Few examples:
- Let's say I don't use social accounts for now, this view is included and I am unaware of it `/accounts/social/connections/`. I guess other social views are also included.
- Let's say I want to allow my users to logout by only one click. They click on a "logout" button, and they are redirected to a specific page and logged out. Implementing this is a one-liner with Django's native `LogoutView`. That's the behavior I want. However as I am using django-allauth, an `accounts/logout` view is included and I don't need it. Using it instead of the native one is not an option since this is a 2 steps workflow to logging out. Basically it shows a template from which user still needs to confirm that he wants to logout. 

I see it as a potential issue in the sense that many people using django-allauth may be unaware of all the views included by default, and thus might have some urls unwillingly hanging around. I guess this could lead to potential security issues as well.

**Comment by iarp** [comment]
``ACCOUNT_LOGOUT_ON_GET`` : https://django-allauth.readthedocs.io/en/latest/configuration.html by the technical standards GET requests are not supposed to change anything. Logging out is technically changing something so it requires a POST request. Setting that configuration to True will allow the logout to work without doing anything.

If you do not include ``account.socialaccount`` and any providers in your settings ``INSTALLED_APPS`` then those urls are not included. If you do include it without any providers they'll just see an empty page with nothing on it for them to do.

**Comment by pennersr** [comment]
If you don't want to use all urls, you should not implement the allauth urls and handpick the ones you want. That is a manual chore, I don't think there is much that can be done to avoid that.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2613
