### ISSUE TITLE
Django allauth models in django admin

### ISSUE THREAD

**Issue by galileoguzman** [pennersr/django-allauth#2614]
Hey guys!

I am using django admin site for some of my clients and I would love to have some of the models in the admin site, is there any straightforward way to make it happen?

**Comment by iarp** [comment]
The accessible models allauth uses are already added to admin when you add ``allauth.account`` and ``allauth.socialaccount`` to ``INSTALLED_APPS``

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2614
