### ISSUE TITLE
how to use AllAuth for cutom providers?

### ISSUE THREAD

**Issue by ahamiri1377** [pennersr/django-allauth#2617]
Hello guys!
I'm using django-allauth to authenticate with social media account and I'm okay with google and twitter and ...
but I want to use it for a custom provider that isn't in allauth default providers (in 'allauth.socialaccount.providers')! what should I do?

**Comment by iarp** [comment]
You can create your own provider. It's probably easiest to copy an existing providers folder into your own project and then modify to your needs. A good example might be to copy the google provider folder and rename all instances of Google to your custom providers name. Then in INSTALLED_APPS add the custom provider folder that you copied.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2617
