### ISSUE TITLE
How we return to previous page

### ISSUE THREAD

**Issue by durdenk** [pennersr/django-allauth#262]
Hi,
How we return to previous page?

My last try was:
class MyAccountAdapter(DefaultAccountAdapter):
    def get_login_redirect_url(self, request):
        print request.GET
        if 'next' in request.GET:
            print 'yes'
            return redirect(request.GET['next'])
        else:
            return HttpResponseRedirect(request.META.get('HTTP_REFERER','/'))

it redirects to url in next parameter if found, but next parameters url also sends to the previous page, so I end up with login screen after login.
I can find a solutions here but I need a system wide solution.
Also this HTTP_REFERER is kinda not reliable thing.
thx.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/262
