### ISSUE TITLE
Feature request: Allow choice between using multiple email addresses and a single email address

### ISSUE THREAD

**Issue by Lord-sarcastic** [pennersr/django-allauth#2621]
Not all websites **need** multiple email addresses and this might prove to be overwhelming for some coupled with the user experience in having multiple email addresses. 
I think a setting should exists such as `ACCOUNT_USE_MULTIPLE_EMAILS` with a default value of true which allows websites choose between working with one email address and working with the default multiple email addresses that this package presently provides. 
I have a piece of hacky, untested code that provides this feature together with a patch for an [issue](https://github.com/pennersr/django-allauth/issues/2620) I raised that could solve this problem. 
As stated in the issue, the code is still in its hacky stages and would be improved upon by the community.

**Comment by 9mido** [comment]
@Lord-sarcastic Great idea. Please share your code below so that others could look at it and improve it.

**Comment by Lord-sarcastic** [comment]
Having checked both, I think #650 is a better alternative as it is more flexible than having to choose between 1 and unlimited number of emails.

**Comment by 9mido** [comment]
Fair enough. As long as it gets fixed somehow. I hope you are able to come up with something to resolve this issue that has been left aside for years.

**Comment by 9mido** [comment]
@Lord-sarcastic See pull request #2627 that seems to address this issue.

**Comment by Lord-sarcastic** [comment]
@9mido I've checked it out. It doesn't still address the issue. I'm currently working on something to fix #2620 . I'll work on this once that is done.

**Comment by 9mido** [comment]
@Lord-sarcastic  What about https://github.com/pennersr/django-allauth/pull/2630

**Comment by Lord-sarcastic** [comment]
I think that's it! That should work. I'm waiting to see the final result. There will be no need for me to work on it. 
I'll close this issue once it is merged.

**Comment by 9mido** [comment]
@Lord-sarcastic seems like you can now close this issue now it has been merged.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2621
