### ISSUE TITLE
Adding own field to signup

### ISSUE THREAD

**Issue by 1JeimiP1** [pennersr/django-allauth#2624]
I am sorry if i repeat someone else's issue.
So, the question is how I can add my own fields into the signup form? User must enter his email, token and password, but I can't grasp how I can do that...
I hope for your answer, thank you in advance!

**Comment by Lord-sarcastic** [comment]
This has been addressed in the documentation [here](https://django-allauth.readthedocs.io/en/latest/configuration.html). Do check it out.

**Comment by 1JeimiP1** [comment]
> This has been addressed in the documentation [here](https://django-allauth.readthedocs.io/en/latest/configuration.html). Do check it out.

Ty)

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2624
