### ISSUE TITLE
Cant overwrite the confirmation signup email subject.

### ISSUE THREAD

**Issue by adrenaline681** [pennersr/django-allauth#2625]
I was able to overwrite the HTML template by adding this to my templates folder:
`account/email/email_confirmation_signup_message.html`

But now I'm trying to overwrite the subject of the email by adding this:
`account/email/email_confirmation_signup_subject.txt`

But it doesn't do anything. I still get the same default subject

**Comment by 9mido** [comment]
Watch https://youtu.be/dXZim_jgaiI?t=704

project_name/templates/account should be identical to this:

https://github.com/pennersr/django-allauth/tree/master/allauth/templates/account

project_name/templates/account/email should have this:

https://github.com/pennersr/django-allauth/tree/master/allauth/templates/account/email

Then you should be able to edit them.

**Comment by adrenaline681** [comment]
> Watch https://youtu.be/dXZim_jgaiI?t=704
> 
> project_name/templates/account should be identical to this:
> 
> https://github.com/pennersr/django-allauth/tree/master/allauth/templates/account
> 
> project_name/templates/account/email should have this:
> 
> https://github.com/pennersr/django-allauth/tree/master/allauth/templates/account/email
> 
> Then you should be able to edit them.

I tried copying everything into the templates folder, then I edit the "email_confirmation_signup_subject.txt", also tried  "email_confirmation_subject.txt" and nothing is happenin.
It seems like it's still grabbing the default from Allauth instead of my template. 

It seems to work fine when I add the "email_confirmation_signup_message.html" template but not for the subject.

**Comment by MatheusADias** [comment]
I have the same problem... is there some update?

**Comment by 9mido** [comment]
IIRC it really depends on your project's settings.py for BASE_DIR and TEMPLATES settings. You need to tell your django settings to point to the templates folder inside of your project's directory not in your virtual environment. 

```
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,"templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
```

Otherwise, try going to your virtual environment directory and edit django-allauth directly where django-allauth was installed. It depends on what operating system you use the path of your installed pip packages.

**Comment by pennersr** [comment]
Closing -- unlikely an issue in allauth. Take care of Django's template loading order, that might explain things.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2625
