### ISSUE TITLE
'password_reset_url' replaces https://www.domain with https://url9013.domain

### ISSUE THREAD

**Issue by anthonygoslar** [pennersr/django-allauth#2626]
My password recovery email is replacing the text after `https://www.domain.com `with `https://url9013.domain.com` in the password recovery email.

I've read through the code and traced the url construction to the point that the confirmation email is sent using `adapter.get_adapter()`. The url going into the email constructor is correct but it seems like the adapter or email service provider is altering this url?

With regards to the email adapter, I can't locate `app_settings.ADAPTER`. I am using SendGrid to send emails with the django-sendgrid-v5 app, and their EMAIL_BACKEND settings. 

Do you know where I trace things from here to sort out this issue?

**Comment by iarp** [comment]
The default for [ADAPTER](https://github.com/pennersr/django-allauth/blob/master/allauth/account/app_settings.py#L193) is [allauth.account.adapter.DefaultAccountAdapter](https://github.com/pennersr/django-allauth/blob/master/allauth/account/adapter.py#L41) it uses [allauth.utils.build_absolute_uri](https://github.com/pennersr/django-allauth/blob/master/allauth/utils.py#L264) to build the full url.

**Comment by anthonygoslar** [comment]
Thanks for the help. 

ADAPTER.render_email() printed to the console correctly. Changing the settings to `EMAIL_BACKEND = 'django.core.mail.backends.filebased.EmailBackend'` and` EMAIL_FILE_PATH = '../app-messages'`, and the output to a locally save file is the same.

**The problem is django-sendgrid-v5.** 

It's strange behaviour, the 'password_reset_url' is modified:
**from:** `http://localhost:8000/accounts/password/reset/key/1-5it-0725d8da08e9b9f41f4f/`
**to**: `http://url9013.domain.com/ls/click?upn=LoiyH2LoHK-2FyebPx0DrAmh-2BLXayWqAPFD0GUBlpGYETJZIbQzq5T1P5qodr3cvmqa45H2ALRXsu6dn0wHb1GychiXyHbXcmClFsXM1Ev0Ik4SCVIp9567iz8D652oRNC3uXgqFQ3bFVhdGe1pCKI1A-3D-3DsVxu_MTQeFU9OGQYuK17CNM-2FHMNx7-2FIQ3Ppn2hY8yIwt4EOHYYEscfmfRc0mrxAVn0btqmq5zamAna2e4g6AGmPkur5EZAKhoGAzchKOSHNWVN0c8UhUbprvmwkRvJNbliuXL9-2BCz9IIBNgumYNbpEQdSnL5GWj-2BJ7kkfIH9e8uTsyG5T4AA3a15zMIH7VTzN9uRhxe3Q46z18E-2BKiqdkGY254vsRLZbzmELFiV-2Fk1-2FT-2F1Do-3D`

This is despite my changing the Site name to localhost:8000 from domain.com, and the request being sourced from localhost:8000.

django == 2.2.11
django-Allauth == 0.42.0
django-sendgrid-v5. == 0.8.1
EMAIL_BACKEND = 'sendgrid_backend.SendgridBackend'

**Comment by iarp** [comment]
See SENDGRID_TRACK_CLICKS_HTML https://github.com/sklarsa/django-sendgrid-v5#other-settings

**Comment by anthonygoslar** [comment]
Fixed, thanks.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2626
