### ISSUE TITLE
RuntimeError at /accounts/password/reset/key/2-set-password/ autocomplete=

### ISSUE THREAD

**Issue by 9mido** [pennersr/django-allauth#2632]
Getting the error in the title of the issue above when I go through "Forgot Password" process for a user who got locked out after setting the ACCOUNT_LOGIN_ATTEMPTS_LIMIT and ACCOUNT_LOGIN_ATTEMPTS_TIMEOUT.

Django DEBUG = True says:

You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 127.0.0.1:8000/accounts/password/reset/key/2-set-password/%20autocomplete%3D/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.

Traceback:

```
Internal Server Error: /accounts/password/reset/key/2-set-password/ autocomplete=
Traceback (most recent call last):
  File "/home/user/.local/share/virtualenvs/project_name/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/user/.local/share/virtualenvs/project_name/lib/python3.7/site-packages/django/utils/deprecation.py", line 113, in __call__
    response = self.process_request(request)
  File "/home/user/.local/share/virtualenvs/project_name/lib/python3.7/site-packages/django/middleware/common.py", line 54, in process_request
    path = self.get_full_path_with_slash(request)
  File "/home/user/.local/share/virtualenvs/project_name/lib/python3.7/site-packages/django/middleware/common.py", line 94, in get_full_path_with_slash
    'url': request.get_host() + new_path,
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 127.0.0.1:8000/accounts/password/reset/key/2-set-password/%20autocomplete%3D/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
[08/Aug/2020 00:39:58] "POST /accounts/password/reset/key/2-set-password/%20autocomplete= HTTP/1.1" 500 89207
```

**Comment by iarp** [comment]
Where is autocomplete coming from?

**Comment by 9mido** [comment]
Not sure as soon as I type in the new password twice on /accounts/password/reset/key/2-set-password/ and click submit, it redirects to /accounts/password/reset/key/2-set-password/%20autocomplete=

**Comment by iarp** [comment]
Did you alter the template file? Specifically this line: https://github.com/pennersr/django-allauth/blob/master/allauth/templates/account/password_reset_from_key.html#L14

**Comment by 9mido** [comment]
Yup that was the problem. I will close this issue. Thanks for such the quick reply. And thank you so much for those PRs you sent through these past few days. Helping out all the noobs like me and making the app better for everyone. I will keep looking for bugs as well.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2632
