### ISSUE TITLE
RemovedInDjango40Warning: django.utils.http.is_safe_url() is deprecated in favor of url_has_allowed_host_and_scheme().

### ISSUE THREAD

**Issue by theptrk** [pennersr/django-allauth#2634]
Hi, 

Looks like `is_safe_url` this is deprecated in a future version of Django but works now. 
I'm using python 3.8 and when running pytest, I run into this deprecation warning. 

Is there anyway to remove or ignore this?

**Comment by ipaleka** [comment]
Another deprecation warning is:

> ....../lib/python3.8/site-packages/allauth/socialaccount/signals.py:8: RemovedInDjango40Warning: The providing_args argument is deprecated. As it is purely documentational, it has no replacement. If you rely on this argument as documentation, you can move the text to a code comment or docstring.
>     pre_social_login = Signal(providing_args=["request", "sociallogin"])
>

**Comment by ipaleka** [comment]
@theptrk you may ignore that and similar warnings by creating `pytest.ini` file in the root of your project, having the following content (place a regex pattern after ignore:):

```
[pytest]
filterwarnings =
    ignore:.*is deprecated in favor of url_has_allowed_host_and_scheme.*
```

**Comment by iarp** [comment]
is_safe_url was addressed in PR #2434

**Comment by theptrk** [comment]
Thanks

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2634
