### ISSUE TITLE
stashed_veriified_email and unstash_verified_email should be a staticmethod (or maybe classmethod)

### ISSUE THREAD

**Issue by atleta** [pennersr/django-allauth#2637]
Hi,

`stashed_veriified_email` and `unstash_verified_email` on `DefaultAccountAdapter` only work with `request` (request.session, actually) and does not access self or even class attributes thus could be made into a `staticmethod` (maybe a `classmethod`). This would allow using these from outside of the AccountAdapter, e.g. a `SignupView` descendant. Which is exactly my use case. As long as I just had one such view a passed on the email address (along with other necessary information related to the invitation) in the `form.initial_data` (I've needed that there anyway). 

However, implementing a second signup that works with different data would have made this hacky, so I've looked into how to signal the email was already verified. The current solution is to manually update the request.session, while `stashed_verified_email` does exactly this. Using that would be less fragile (e.g. if the session key changes)

**Comment by iarp** [comment]
Do you have a code example comparing what you currently have to do and what you want to do? ``get_adapter().stash_verified_email(request)`` I'm not sure I see just how you're going to lessen that statement by adding staticmethod. If you're calling DefaultAccountAdapter the ``__init__`` doesn't require a request by default so its just ``DefaultAccountAdapter().stash_verified_email(request)`` and all you would be doing is removing one set of ``()``

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2637
