### ISSUE TITLE
HTML emails

### ISSUE THREAD

**Issue by arctelix** [pennersr/django-allauth#264]
I would like to add the ability for allauth to send HTML formatted email using:
msg = EmailMultiAlternatives(subject, text_content, from_email, to_email)
msg.attach_alternative(html_content, "text/html")

The logic would be: if a the email template exists with an html extension it would be included as attach_alternative.  This way people could choose to use it or not.

Are you open to this modification?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/264
