### ISSUE TITLE
Facebook and Goole login.

### ISSUE THREAD

**Issue by krischal1** [pennersr/django-allauth#2640]
I was wondering if https://github.com/pennersr/django-allauth/issues/145 this feature is available now.
I am integrating facebook and google login. I want users to verify email if they register their account manually but no need to verify account if they are logged in from facebook or google.
Is is possible?

**Comment by Afrowave** [comment]
This is very possible. It is the way django-allath works if you follow the instructions in the docs.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2640
