### ISSUE TITLE
Share authentication between virtual hosts

### ISSUE THREAD

**Issue by aoussarmustapha** [pennersr/django-allauth#265]
I host multiple websites on a single server using <a href="http://httpd.apache.org/docs/2.2/vhosts/">Apache Virtual Hosts</a> (ex: sub1.domain.com, sub2.domain.com, etc) with separate databases.

Can I share authentication between websites with <i>django-allauth</i>?

I'd like that: 1) when a user logs in to <b>sub1.domain.com</b> is automatically able to access <b>sub2.domain.com</b> without logging in again and 2) user that logs in to <b>sub2.domain.com</b> directly is authenticated against <b>sub1.domain.com</b> user db.

Thanks!

**Comment by alexburner** [comment]
I wanted to check in here, just in case anything changed in the last 11 years... 

Is a single auth shared across separate instances still out of scope?

I'm assuming yes — I can't find any mention in the docs, or any GH issues newer than this one.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/265
