### ISSUE TITLE
Safely remove allauth.socialaccount app

### ISSUE THREAD

**Issue by khashashin** [pennersr/django-allauth#2653]
Please Note: I don't use any third party login accounts in my project, therefore I have no entries in my Database regarding socialaccount app.

I would like to remove following tables from my Database:
![image](https://user-images.githubusercontent.com/17837758/91962900-731f2480-ed0d-11ea-9941-95664b660deb.png)

How to do that safely without breaking my currently working app. As I said this tables are empty and does not contain any data.

It also would be better to mention that in the docs that this `allauth.socialaccounts` app is not required if we don't want to use third party accounts to login.

**Comment by iarp** [comment]
You'll need to change the [login.html](https://github.com/pennersr/django-allauth/blob/master/allauth/templates/account/login.html) template and remove socialaccount things and remove allauth.socialaccount items from INSTALLED_APPS.

**Comment by khashashin** [comment]
I use custom `login.html` with custom `allauth.login` and `allauth.signup` forms

**Comment by pennersr** [comment]
https://django-allauth.readthedocs.io/en/latest/faq.html#why-did-you-just-close-my-issue

**Comment by Iazzetta** [comment]
**before** all things of django-allauth of INSTALLED_APPS, remove imports and loads in templates, etc. You need delete all data of models created by django-allauth (delete/cascade). After that, remove django-allauth of your project and drop databases (DROP/CASCADE). Works for me.

**Comment by efojs** [comment]
With what @Iazzetta listed, I've migrated apps to `zero`, to safely remove tables:  
```bash
python manage.py migrate socialaccount zero
python manage.py migrate account zero
```

**Comment by akrish4** [comment]
How can we uninstall django-allauth in windows 64 bit machine , pls let me know

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2653
