### ISSUE TITLE
The verification page should be hidden from verified users

### ISSUE THREAD

**Issue by jolob5l** [pennersr/django-allauth#2655]
If a user requests for the verification page, he can access it after verification is done, should we make it hidden? If not, then why?

**Comment by pennersr** [comment]
Are you referring to /accounts/confirm-email/ or ...?

**Comment by jolob5l** [comment]
> Are you referring to /accounts/confirm-email/ or ...?
yep

**Comment by jolob5l** [comment]
https://github.com/jolob5l/django-allauth/commit/18b88f6b9bb69bcbe95a99a595c9285d430a9d0d 
here is a thing I wrote about, it's only a concept and wasn't tested at all

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2655
