### ISSUE TITLE
Validate Realness Of Emails During Signup

### ISSUE THREAD

**Issue by 9mido** [pennersr/django-allauth#2656]
People could use fake temporary non-real email addresses that can only receive emails to sign up since there is no way to test the realness of an email address. Although using fake temporary email addresses is great for dev testing, in production it might not be so great.

I am not talking about regular email address validation like if a user types in 'test@domain.com' versus 'test@' for example. 

Example of a use case:
https://zoom.us/signup
https://emailfake.com/ (these seem to fail on Zoom's website)
https://www.temporary-mail.net/ (this one passes on Zoom's website but should fail)

Like Zoom, it probably is not possible to catch every non-real temporary email address. But having some type of protection may be helpful? But you don't want to block legit email addresses either if they appear to be fake.

Maybe create a setting like ACCOUNT_EMAIL_REALNESS_VALIDATION = True|False could work. A setting would be good because for dev testing I would definitely want to use a temporary emails like the links above and not go through the hassle of manually creating an email address each time. But in production, don't let users do this since they won't be able to access these email accounts again and reply back to any emails that are sent to them (unless they go through the change email feature of allauth).

**Comment by pennersr** [comment]
You can already reject certain email addresses by implementing your own logic in the `clean_email` adapter method. I think it goes too far to try and build a black list inside allauth itself -- keeping track of those is best served in a project of its own. So I don't think there is much to do from an allauth standpoint -- if a list is there, checking against it is rather trivial inside `clean_email`.

**Comment by 9mido** [comment]
Here is an example:

https://stackoverflow.com/questions/67150177/how-to-add-email-blacklist-option-in-django-allauth

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2656
