### ISSUE TITLE
Google provider sign up

### ISSUE THREAD

**Issue by dhvcc** [pennersr/django-allauth#2657]
I want to have google as a sign in/up option
This works good and all

But when i try to login to an existing account via google i get the "finish sign up" form.
Why?
If you login via google and the account exists i should be logged in

Also on google sign up the email gets confirmed but the "email_confirmed" signal is never triggered

**Comment by iarp** [comment]
When you say

> when i try to login to an existing account via google

Is the google account already connected to the account in your system? 

If the google account is not already associated with the local account, allauth doesn't just match based on email and assume that  the same people owns the existing local account. It asks to make an account (depending on settings it'll auto generate a username or ask for it).

**Comment by dhvcc** [comment]
Thank you

Can i override this logic without going deep in the code?

**Comment by ibrahimsamson** [comment]
I think so, I think you can override it in class `DefaultSocialAccountAdapter`  method `pre_social_login`

**Comment by dhvcc** [comment]
Did it with [signals](https://gist.github.com/dhvcc/1521478609f1c349b3092bcf8d6b3f9e), thanks @ibrahimsamson and @iarp

**Comment by cobyrne09** [comment]
Would you mind sharing how you achieved this @dhvcc?

**Comment by ryanacorn** [comment]
For me, I had to add this to the end to get it to redirect to the URL requested.
```
raise ImmediateHttpResponse(
    redirect(settings.LOGIN_REDIRECT_URL.format(id=request.user.id))
)
```
see: https://stackoverflow.com/a/24358708

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2657
