### ISSUE TITLE
ACCOUNT_SIGNUP_FORM_CLASS and ACCOUNT_FORMS['signup'] are incompatible

### ISSUE THREAD

**Issue by thraxil** [pennersr/django-allauth#2661]
Based on the documentation and the discussion on other issues (such as #2039 and https://github.com/pennersr/django-allauth/issues/1698#issuecomment-293054156) I understand that:

* To *add* additional fields to the signup form, one should create a custom form (subclassing `django.forms.Form`) defining the fields and having a `signup()` method and point `ACCOUNT_SIGNUP_FORM_CLASS` at it.
* To override the default fields or otherwise change the behavior of the signup form, one should make a custom form by sublcassing `allauth.accounts.forms.SignupForm` and making the necessary changes there.

In my case, we needed to do both: we have extra fields to add, and we also needed to delete the `password1` field that the default form adds since we don't use it and validation fails when it isn't set. Based on what I've mentioned, my expectation was that I would be able to do something like:

```
from django import forms
from allauth.accounts.form import SignupForm

class PasswordlessSignupForm(SignupForm):
    def __init__(self, *args, **kwargs):
        super(PasswordlessSignupForm, self).__init__(*args, **kwargs)
        del self.fields['password1']

class MyCustomForm(form.Form):
    first_name = forms.CharField()
    def signup(self, request, user):
        user.first_name = self.cleaned_data['first_name']
        user.save()
```

Then, 

```
ACCOUNT_SIGNUP_FORM_CLASS = 'myapp.forms.MyCustomForm'
ACCOUNT_FORMS = {'signup': 'myapp.forms.PasswordlessSignupForm'}
```

However, doing that results in an import error:

```django.core.exceptions.ImproperlyConfigured: Error importing form class accounts.forms: "cannot import name 'SignupForm'"```

I was able to make things work by creating a single custom form subclassing `SignupForm` that handles both aspects, pointing `ACCOUNT_FORMS['signup']` at it, adding a `save()` override that calls `signup()`, and leaving `ACCOUNT_SIGNUP_FORM_CLASS` unset.

That works but leaves me feeling like there is either a bug here since both can't be set at the same time, or at least that the documentation should mention this limitation and provide more useful information for someone in a similar position of needing to implement custom functionality that would rely on both of those settings.

**Comment by iarp** [comment]
`ACCOUNT_FORMS['signup']` [replaces the form entirely](https://github.com/pennersr/django-allauth/blob/master/allauth/account/views.py#L217).

`ACCOUNT_SIGNUP_FORM_CLASS` [changes the base form](https://github.com/pennersr/django-allauth/blob/f9e0e4eaf4f74b910d0e02df46eb39e8915cd58b/allauth/account/forms.py#L217) that SignupForm inherits from. Technically it changes the inheritance of BaseSignupForm of which SignupForm inherits from.

You should not change both, choose one. Perhaps the documentation could be updated better as such, it'll be up to someone to do a PR for that.

**Comment by thraxil** [comment]
@iarp yes, that's the point that I'm making. The documentation covers both use-cases separately, but if you need both, there is no good solution.

**Comment by iarp** [comment]
What case can be made for requiring both?

**Comment by thraxil** [comment]
I think the case for requiring both is basically what I laid out in the original comment. Eg, it's very common to need to add additional fields to the signup form. Per the documentation and community comments, that should be done via `ACCOUNT_SIGNUP_FORM_CLASS`. Then sometimes, you need to change the behaviour of the built-in fields (eg, removing `password1` in my case) and that should be done via `ACCOUNT_FORMS['signup']`. If you have a need for both of those things (as I do), the obvious approach that you come to from the documentation is to do both and then you run into a very surprising situation where it breaks because of some weird internal inheritance manipulation that isn't documented or expected. The documentation for `ACCOUNT_SIGNUP_FORM_CLASS` just says:

> A string pointing to a custom form class (e.g. 'myapp.forms.SignupForm') that is used during signup to ask the user for additional input (e.g. newsletter signup, birth date). This class should implement a def signup(self, request, user) method, where user represents the newly signed up user.

There is no indication there that it changes a base form or would interfere with other settings.

**Comment by pennersr** [comment]
Note: your import is wrong:

```
from allauth.accounts.form import SignupForm
```

Replace `accounts` by `account` and `form` by `forms`.

**Comment by pennersr** [comment]
Other than those imports, your use case is supported, but, due to load order you will be hitting the import error  because you have both forms defined in the same file: your `myapp.forms` imports `allauth.account.forms`, which in turn tries to load the `myapp.forms` again. So you have a cycle. Try putting `MyCustomForm` and `PasswordlessSignupForm` in separate files and it will work.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2661
