### ISSUE TITLE
SocialApp matching query does not exist. (Using Google) Solved

### ISSUE THREAD

**Issue by OAHC2022** [pennersr/django-allauth#2664]
Recently I tried to incorporate google login into my Django app using all-auth. However, I encountered the error mentioned in title. I looked through the internet and did not find a solution. After a few trial and errors, I got the app working and I thought this might be the place to share my solution, so it might be helpful for others who encountered the error.

The reason I got the error was that I did not put **example.com** to the chosen sites in the social app page. After I moved the **example.com** to the chosen sites, my login worked properly.
![django config](https://user-images.githubusercontent.com/43483555/94033058-967a4400-fd8e-11ea-8c70-d3d837575f52.png)

However, I am not sure why this is the cause of the problem. I have looked at the online documentation and it does not talk about how to handle the sites field. 
![django configuration docs](https://user-images.githubusercontent.com/43483555/94033298-d2150e00-fd8e-11ea-98b8-a25624de93cc.png)

Maybe it is because I am new to Django and all-auth, but I think it might be better if the author can update the documentation to address this problem, so people new to all-auth (like me) do not have to spend too much time grinding through why the app fails. 

Thank you.

**Comment by pennersr** [comment]
I would be happy to accept pull requests improving the documentation. Though, must admit, keeping issues open about documentation is not going to move things forward, hence, closing...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2664
