### ISSUE TITLE
User email empty for GitHub users

### ISSUE THREAD

**Issue by mechtron** [pennersr/django-allauth#2668]
I'm using `django-allauth` 0.42.0 with GitHub and Google OAuth, and my Google flow is working 100% as expected. However, my GitHub sign-ups are creating users with blank email address fields, even though I have the correct scopes setup (and my GitHub prompt lists private email access):

```
SOCIALACCOUNT_PROVIDERS = {
    'github': {
        'SCOPE': [
            'user:email',
        ],
    },
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}
```

```
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_auth',
    'rest_auth.registration',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.github',
    'allauth.socialaccount.providers.google',
]
```

Example login url: `https://github.com/login/oauth/authorize?client_id=<client_id>&redirect_uri=http%3A%2F%2Flocalhost%3A8000%2Fauth%2Fgithub%2Fcallback%2F&scope=user%3Aemail&response_type=code&state=J1BTBwB7iISG`

Example user call w/blank email:  `curl localhost:8000/auth/user/ -H "Authorization: Token <token>"`
Response: `{"pk":17,"username":"expected_username,"email":"","first_name":"","last_name":""}`

Again, my Google flow works fine and populates the email field as expected.

Is this a bug, or am I doing something wrong?

Full code for reference: https://github.com/mechtron/drf-vuejs/tree/master/api

Thanks!

**Comment by mechtron** [comment]
For those who run into this issue too:

I fixed this by adding `SOCIALACCOUNT_QUERY_EMAIL = True` in `settings.py`. One drawback to this is it only works for new users - old users records still have empty email fields.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2668
