### ISSUE TITLE
Cannot subclass SignupForm

### ISSUE THREAD

**Issue by abeals** [pennersr/django-allauth#267]
My understanding of the process for defining a custom signup form (which may be mistaken) is as follows:
1. I define the custom form class in my own forms.py, inheriting from forms.Form
2. I point django-allauth to the custom class in settings.py via ACCOUNT_SIGNUP_FORM_CLASS
3. BaseSignupForm inherits from this class via _base_signup_form_class(), which does some validation (looks for a save method, etc)

If that's correct, the custom form class is actually the superclass of django-allauth's SignupForm.  The issue is that approach prevents me from writing a custom after_signup() method, which (as the docstring says) would be a very helpful extension point to SignupForm.

Either SignupForm's version of the method needs to call super() or we need to be able to define our own custom form classes that are _subclasses_ of SignupForm.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/267
