### ISSUE TITLE
Account already exists error

### ISSUE THREAD

**Issue by dnpthree** [pennersr/django-allauth#2677]
Hello,

I've been troubleshooting this for days and I'm not sure what is going wrong here. 99% of my users login with Twitter just fine, but some get an error where they can't login and are redirected to the "sign up form". When they try to create an account hey get this error: `A user is already registered with this e-mail address`. or` A user with that username already exists`.

On the server I see this 
```
Oct 07 09:23:26 
app/web.1 django.db.utils.IntegrityError: null value in column "user_verified" violates not-null constraint Oct 07 09:23:26 app/web.1 DETAIL:  Failing row contains (11229, null, f, 11230, null, null, null).
```

here are my settings.py
`AUTH_USER_MODEL = 'users.User'
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_PROVIDERS = {
    'twitter': {
        'SCOPE': ['email'],
    },
    'mixer': {
        'SCOPE': [
            'user:details:self',
            'user:update:self',
        ]
    }
}
ACCOUNT_EMAIL_REQUIRED = False
ACCOUNT_EMAIL_VERIFICATION = 'none'`

and I'm using this to create a user profile in my models.py

`
def userprofile_receiver(sender, instance, created, *args, **kwargs):
    if created:
        userprofile = UserProfile.objects.create(user=instance)
post_save.connect(userprofile_receiver, sender=settings.AUTH_USER_MODEL)
`

I'm not sure what else could be causing this but I'm having to provide anything else to help troubleshoot.

**Comment by dnpthree** [comment]
Bump. Please I really need assistance. I'm not sure where else to check.

**Comment by pennersr** [comment]
I am sorry, but this does not seem to point to an issue in allauth, nor is it feasible for me to start debugging project specific integration trouble. I will have to close this.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2677
