### ISSUE TITLE
{% providers_media_js %} causes Exception Value: No module named path.to

### ISSUE THREAD

**Issue by benbowler** [pennersr/django-allauth#268]
Until the {% providers_media_js %} tag is deleted from the view login_extra.html I get the following error:

ImportError at /accounts/login/
No module named path.to
Request Method: GET
Request URL:    http://chew.local:5000/accounts/login/
Django Version: 1.5.1
Exception Type: ImportError
Exception Value:  
No module named path.to
Exception Location: /Users/benbowler/Sites/Repositories/chew/venv/lib/python2.7/site-packages/django/utils/importlib.py in import_module, line 35
Python Executable:  /Users/benbowler/Sites/Repositories/chew/venv/bin/python
Python Version: 2.7.2
Python Path:  
['/Users/benbowler/Sites/Repositories/chew',
 '/Users/benbowler/Sites/Repositories/chew/venv/bin',
 '/Users/benbowler/Sites/Repositories/chew/venv/lib/python2.7/site-packages/distribute-0.6.34-py2.7.egg',
 '/Users/benbowler/Sites/Repositories/chew/venv/lib/python2.7/site-packages/pip-1.3.1-py2.7.egg',
 '/Users/benbowler/Sites/Repositories/chew/venv/lib/python27.zip',
 '/Users/benbowler/Sites/Repositories/chew/venv/lib/python2.7',
 '/Users/benbowler/Sites/Repositories/chew/venv/lib/python2.7/plat-darwin',
 '/Users/benbowler/Sites/Repositories/chew/venv/lib/python2.7/plat-mac',
 '/Users/benbowler/Sites/Repositories/chew/venv/lib/python2.7/plat-mac/lib-scriptpackages',
 '/Users/benbowler/Sites/Repositories/chew/venv/Extras/lib/python',
 '/Users/benbowler/Sites/Repositories/chew/venv/lib/python2.7/lib-tk',
 '/Users/benbowler/Sites/Repositories/chew/venv/lib/python2.7/lib-old',
 '/Users/benbowler/Sites/Repositories/chew/venv/lib/python2.7/lib-dynload',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages',
 '/Users/benbowler/Sites/Repositories/chew/venv/lib/python2.7/site-packages']
Server time:    Thu, 16 May 2013 15:41:00 +0100

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/268
