### ISSUE TITLE
Email verification is not enforced. Disregarding ACCOUNT_EMAIL_VERIFICATION setting

### ISSUE THREAD

**Issue by florianmartens** [pennersr/django-allauth#2684]
I'm using two packages to assist me with authentication. One is js_rest_auth and the other one is allauth.

The latter has a setting to require users to validate their email addresses before a login is possible. I'm setting ACCOUNT_EMAIL_VERIFICATION = "mandatory" but it has no effect. My relevant settings look as follows:

```
INSTALLED_APPS = [
    ...
    "django.contrib.sites",
    "rest_framework.authtoken",
    "allauth.account",
    "allauth.account",
    "allauth.socialaccount",
    "dj_rest_auth",
    ....
]

```
```
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 90
ACCOUNT_USER_MODEL_EMAIL_FIELD = "email"
ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_EMAIL_REQUIRED=True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_REQUIRED=False
ACCOUNT_USER_MODEL_USERNAME_FIELD = "email"
ACCOUNT_PRESERVE_USERNAME_CASING = False
ACCOUNT_ADAPTER = "users.accountadapter.CustomAccountAdapter"
```

```
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

```
```
REST_FRAMEWORK = {
    ....
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ]
}
```

The users I create aren't verified (verified attribute an Email Address Model) but are created with is_active=True. When I send a login request for a non-verified user, a valid token is issued.

**Comment by pennersr** [comment]
There is no issue in allauth related to email verification, this is thoroughly covered in unit tests. So, the issue you are having lies within the integration of the packages you are using. Therefore, I have to close this.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2684
