### ISSUE TITLE
No password set after removing primary email from social login to login locally

### ISSUE THREAD

**Issue by ashmlk** [pennersr/django-allauth#2687]
I am trying to come up with a solution to this problem that I am facing however, I cannot seem to find it. 

Assume a scenario where the user logs into the django website using their Google Gmail account. After logging in the user decided to change the default email from test@gmail.com to one of their other emails: test@test.com. 

The user goes to `accounts/emails/` and adds a new email (*test@test.com*), verifies the email, sets it as primary and deletes the old email **test@gmail.com** which is their Google email. 

I have written an adapter that would link users to their social login if a user already exists so if they log in using the Google account **test@gamil.com** even after changing their email, they will still be redirected to the same user (*test@test.com*).

However, I want to give the user a page to set a password for **test@test.com** in case the user wanted to use the `forget password` option in order to sign in locally. How can I redirect users after deleting their social login email to set a new password for the new email? Or no such functionality is implemented. Since when users are logged in using social login their passwords are set to `unusable` and the forget password option does not work.

**Comment by 9mido** [comment]
@ashmlk Please share your adapter code with us below to give us more context. If you have code that links a social account to the user, that may be helpful to other areas / users of allauth besides just the problem you are facing.

I am not sure how to answer the questions in your last paragraph. Someone else might be able to assist.

**Comment by ashmlk** [comment]
@9mido Here is my adapter code to link Social Login with a local login. 
```
class SocialAccountAdapter(DefaultSocialAccountAdapter):

   
   def pre_social_login(self, request, sociallogin):

        if sociallogin.is_existing:
            return
        if 'email' not in sociallogin.account.extra_data:
            return
        try:
            email = sociallogin.account.extra_data['email'].lower()
            email_address = EmailAddress.objects.get(email__iexact=email)
        except EmailAddress.DoesNotExist:
            return

        user = email_address.user
    
        if not user.is_active: # if the user is inactive
            user.is_active = True # set the user to active (Initiallt on local sign up user's are set to inactive until email verification)
            email_address.verified = True # set their email address as verified
            email_address.save()
            user.save()
            sociallogin.connect(request, user) # connect the local user with social login
        elif user.is_active: 
            if email_address.verified == True:
                sociallogin.connect(request, user) # if the user is active and local email address is verified, connect the user
            elif email_address.verified == False: # if the user is active but email address is not verified, verify user email address again
                return
```


Now the main issue I'm facing is in adding a new email address, from `accounts/emails/` which if a user was initially signed up via social login, they would not have a password. Now the forget password option already prompts them to `SetPasswordView` since they have an unusable password set to `True`. I was thinking if it's a better way that when setting a local email as their primary email(**test@test.com** in my first example), they would also be asked to set a new password.

**Comment by pennersr** [comment]
I have trouble grasping the issue. The trouble is, this:

> I have written an adapter that would link users to their social login...

... means that we're dealing with a customized allauth here. This issue needs to be rephrased such that it is clear what the issue in the plain/standard allauth is, because issues arising from customizations are difficult to reason about.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2687
