### ISSUE TITLE
code to inline social info in admin user interface

### ISSUE THREAD

**Issue by mennucc** [pennersr/django-allauth#2688]
dear all,

I propose this simple patch attached.
[0001-add-InlineSocialAccountAdmin-for-showing-social-acco.patch](https://github.com/pennersr/django-allauth/files/5413843/0001-add-InlineSocialAccountAdmin-for-showing-social-acco.patch.txt)

this creates a new `admin` interface that can be used to show social authentication inside the `user` admin interface

in my project I have a customized user called `ColDocUser` and I use it as follows:
```
from django.contrib.auth.admin import UserAdmin
from ColDocDjango.users import ColDocUser
from allauth.socialaccount.admin  import InlineSocialAccountAdmin
class ColDocUserAdmin(UserAdmin):
        model = ColDocUser
        inlines = [
            InlineSocialAccountAdmin,
        ]
admin.site.register(ColDocUser, ColDocUserAdmin)
```

it is useful

bye . a.

**Comment by pennersr** [comment]
Projects can implements this themselves, there is no need for allauth to force this out of the box.

**Comment by pennersr** [comment]
But, the `SocialAccountAdmin` that is shipped is actually used out of the box. The difference with your `InlineSocialAccountAdmin` is that it is a class that is not used, and projects can easily include something like that themselves.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2688
