### ISSUE TITLE
from_db_value() missing 1 required positional argument: 'context' 

### ISSUE THREAD

**Issue by instantrad** [pennersr/django-allauth#2689]
I am using from django.db.models import JSONField and l suspect that could be the cause

Request Method: | POST
-- | --
http://localhost:8000/admin/login/
3.1.2
TypeError
from_db_value() missing 1 required positional argument: 'context'
/Users/Env/lib/python3.7/site-packages/django/db/models/sql/compiler.py, line 1100, in apply_converters
/Users/Env/bin/python
3.7.9

![Screenshot 2020-10-21 at 9 30 43 AM](https://user-images.githubusercontent.com/66900828/96701717-71262900-1380-11eb-865c-f763d5d1ff05.png)

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2689
