### ISSUE TITLE
get_avatar_url for Facebook is returning anonymous image (based on October 2020 change)

### ISSUE THREAD

**Issue by Gandi24** [pennersr/django-allauth#2693]
This is based on the change in facebook API for profile images described in this thread:
https://stackoverflow.com/questions/64434913/get-facebook-user-profile-image-after-facebook-changesoctober-24

By default the `get_avatar_url` returns the anonymous photo. A manual workaround to the issue is adding `&token={token}` to the avatar url. The `get_avatar_url` method should definitely include that. Not sure if that affects all Facebook API versions, but I've confirmed on both v7.0 and v8.0.

**Comment by ninajlu** [comment]
any update on this?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2693
