### ISSUE TITLE
Verification Emails Not Sending To Changed Email Accounts From Admin

### ISSUE THREAD

**Issue by 9mido** [pennersr/django-allauth#2694]
ACCOUNT_MAX_EMAIL_ADDRESSES = 1 
ACCOUNT_EMAIL_VERIFICATION = "mandatory"

With these settings, I can change the email account of a user from the django admin if the user contacts me. These settings might not have anything to do with the verification problem from django admin, but it presents a bottleneck for people who only want 1 email address per account and they want to make an email account change for a user. 

When the user (superuser in my test walkthrough) logs out from my website after their email is changed to a new one in the django admin, then logs in again, they are redirected to /accounts/confirm-email/ but never receive the confirmation email on the new email account that was just updated in the django admin.

This happens when I leave the verification checkbox unchecked and the primary checkbox is checked in the django admin. Then click save. 

When I logout of django admin as the superuser who I just changed emails for, it shows that the verification email was sent to the original email address that the user wanted to have changed instead of the new one they wanted it replaced with.  

In urls.py I have url('^accounts/email/', page_not_found, {'exception': Exception()}), to prevent a user from accessing this /accounts/email/ page to prevent spam email sending for now until PR 2631 gets implemented. But then the superuser making the email account change or the user requesting the email account change cannot automatically/manually send an email verification.

Yes you could just check the verification checkbox in admin, but then you won't know if that newly updated email is legit or not unless the user sends you proof?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2694
