### ISSUE TITLE
User group as an instance based manager

### ISSUE THREAD

**Issue by 9mido** [pennersr/django-allauth#2696]
If we use a UserGroup model as an instance based manager, we could group different users together and treat the group as one account (think social accounts linked to main website user account). For instance, if you allow users to make multiple accounts, you can link the original account they created to the UserGroup then add any other accounts they make to it. Think of it as an instance based manager.

This way, we can query their related accounts much faster (because we're were querying a table with only that users accounts), if we need to and one of the accounts has a ban then all accounts in the user group can have the ban, we can control all user model instances from one group instance and, for ease of access, you can access all of it by using request.user.user_group.method() or variable.

request.user.user_group - you can easily access the users group this way. If the user model is in the same group as a different one, all the linked accounts get loaded.

Long term groups make users easier to manage because, provided they have multiple accounts, you can access all of them, and control them, through the user group model

Think of it as an instance based manager. There hopefully shouldn't be any circular dependencies either

Integration may be tough unless using signals. Could use a signal to activate the saving of the UserGroup model

**Comment by pennersr** [comment]
I think that the above goes beyond the scope of authentication.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2696
