### ISSUE TITLE
Apple gives "Invalid web redirect url" if the callback url terminate with a slash.

### ISSUE THREAD

**Issue by antoinelefebvre** [pennersr/django-allauth#2697]
I have been trying to add the apple provider but it seems the callback url generated by django-allauth should not have the trailing slash at the end. If I remove it from the url, it then proceeds correctly. I have not found how to fix it.

Let me know what additional info is required.

**Comment by pennersr** [comment]
Likely, your configuration over at Apple does not match -- check that you have added the slash there:

![image](https://user-images.githubusercontent.com/201022/97363984-a6aca400-18a3-11eb-866c-720fa8f31976.png)

**Comment by antoinelefebvre** [comment]
Thanks. That was it.

**Comment by henningbra** [comment]
Thank you for pointing it out @pennersr. Finally got Apple login to work after three years.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2697
