### ISSUE TITLE
Japanese translations

### ISSUE THREAD

**Issue by marksweb** [pennersr/django-allauth#2698]
I'm working on a project which is getting (some) Japanese translation.

They've currently provided translation for the signup page so I've made a start on adding Japanese to the project;

https://github.com/pennersr/django-allauth/compare/master...marksweb:locale/jp

Hopefully I can put together some `.po` files and get some more content added to this

**Comment by marksweb** [comment]
I wow. I really got this wrong.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2698
