### ISSUE TITLE
dry form submissions

### ISSUE THREAD

**Issue by sumanthratna** [pennersr/django-allauth#2700]
I'm using dj-rest-auth with django-allauth for my Django API. On my frontend, I'm posting to my API whenever the user edits the form fields, and if there are errors I display them in the form (for instant feedback on the signup form).

Unfortunately, this doesn't work because if the user enters valid input data, my POST request will actually create the user. It would be nice if all forms had a `drySubmission` boolean input. If it's false, then allauth should use the current functionality. If it's true, then allauth should do everything except for updating the database (e.g., not creating the user for the signup form).

**Comment by pennersr** [comment]
Sounds like this is an issue that should perhaps be raised over at the dj-rest-auth repo. If not, please make sure you make clear what the issue or bug is you are reporting from a pure django-allauth context.

**Comment by sumanthratna** [comment]
Sorry for being unclear! This was a feature request; I was suggesting that allauth add an input option that allows users to submit a form without actually triggering a DB update. This should be possible by overriding allauth's forms, but I'd prefer to not have to override the form for every project. If you'd rather not keep this feature in allauth, I can open a new issue in dj-rest-auth.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2700
