### ISSUE TITLE
force user confirm email to login

### ISSUE THREAD

**Issue by juanremi** [pennersr/django-allauth#2703]
Hi Team,

How can I force the user to confirm the email to access the system?.

in order to block the login if the user has not verified, when the user try to login and get a message like: You must confirm your email in order to login

Thanks

**Comment by 9mido** [comment]
Did you try ACCOUNT_EMAIL_VERIFICATION = "mandatory" in your settings?

**Comment by juanremi** [comment]
yes i have these option on settings, but the users that not vefiry their email can login

**Comment by juanremi** [comment]
this is part of my settings:

```
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'myown_backend',
    'corsheaders',
    'channels',
    'myown_chat',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'rest_auth',
    'rest_auth.registration',
    'rest_framework.authtoken',
]

SITE_ID = 1
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = '/?verification=1'
ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = '/?verification=1'
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
```

**Comment by pennersr** [comment]
I suggest you put a breakpoint and step through the code over at `allauth.account.utils::perform_login` to see why it is not working for you...

**Comment by juanremi** [comment]
I see is working on the allauth.urls, but no on the rest_auth.urls

when i try to login via the allauth.urls and the user has not confirmed their email, The user receives again a confirmation email, but when i try to login via rest_auth.urls i only get the message:
You cannot log in with the provided credentials.
That could be interpreted as the user or password are wrong.

**Comment by pennersr** [comment]
Sorry, cannot help you there -- perhaps discuss this issue over at the `rest_auth` repo issue tracker...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2703
