### ISSUE TITLE
Apple login - _init__() missing 1 required positional argument: 'permitted_methods'

### ISSUE THREAD

**Issue by joon-wyne** [pennersr/django-allauth#2704]
Hello,

I am trying to integrate Apple login to django, but when user login with their id, I see this message on callback url.
https://xxxxxx.com/accounts/apple/login/callback/
```
Request Method: | GET
-- | --
http://xxxxxx.com/accounts/apple/login/callback/
3.1
TypeError
__init__() missing 1 required positional argument: 'permitted_methods'
/usr/local/lib/python3.6/dist-packages/allauth/socialaccount/providers/apple/views.py, line 152, in apple_post_callback
/usr/bin/python3
3.6.9
['/opt/xxxxxx/core',  '/usr/local/bin',  '/usr/lib/python36.zip',  '/usr/lib/python3.6',  '/usr/lib/python3.6/lib-dynload',  '/usr/local/lib/python3.6/dist-packages',  '/usr/lib/python3/dist-packages']
Wed, 04 Nov 2020 02:53:32 +0000
```
Has anyone experience this? Why do I get "GET" method?

**Comment by kelkarajay** [comment]
Hey, I have hit this problem too. It turns out the "Facebook Container" on Firefox was causing this problem. I turned it off and that resolved the problem. I didn't get down to the bottom of this though.

**Comment by pennersr** [comment]
Closed via b00acf49

**Comment by joon-wyne** [comment]
Basically, I missed `ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'https'` :D My bad.

**Comment by joon-wyne** [comment]
@pennersr Apple Login is not synced to 0.43.0 correctly. When user get the package with PyPi, they still need to use `certificate` instead of `certificate_key` FYI

**Comment by kelkarajay** [comment]
That's because there is currently no newer release. You'd see it in 0.44.0

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2704
