### ISSUE TITLE
Polish translation - typo in "Zarejestuj"

### ISSUE THREAD

**Issue by rwakulszowa** [pennersr/django-allauth#2708]
https://github.com/pennersr/django-allauth/blob/master/allauth/locale/pl/LC_MESSAGES/django.po#L639

Should be "Zarejest**r**uj"

I'm aware that those links are in Polish. You gotta trust me on this one.
https://sjp.pl/zarejestruj
https://sjp.pl/zarejestuj

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2708
