### ISSUE TITLE
Fixing a fuzzy translation in Japanese

### ISSUE THREAD

**Issue by andrewhayes1979** [pennersr/django-allauth#2710]
`
#: account/forms.py:299
#, fuzzy
#| msgid "E-mail (optional)"
msgid "E-mail (again)"
msgstr "メールアドレス（オプション）"

#: account/forms.py:311
msgid "E-mail (optional)"
msgstr "メールアドレス（オプション）"
`

...these two different strings have both been translated to the same string in Japanese, Google translate reveals they both say "Email address (optional)"

Providing an alternative translation for "Email (again)" as "メールアドレス（確認用）" which has been provided by a Japanese translator and translates as "Email address (for confirmation)"

Currently, "Email (again)" is not translated unless fuzzy translations are enabled

<img width="428" alt="Screenshot 2020-11-09 at 14 00 53" src="https://user-images.githubusercontent.com/784691/98550505-194e5400-2294-11eb-8cbe-276ce3573fe6.png">

**Comment by andrewhayes1979** [comment]
Pull request added:
https://github.com/pennersr/django-allauth/pull/2711

**Comment by za** [comment]
As the PR has been merged, I think we can close this issue. cc: @andrewhayes1979

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2710
