### ISSUE TITLE
Request: ability to configure admin site where register models

### ISSUE THREAD

**Issue by Delphi251189** [pennersr/django-allauth#2715]
Django supports multiply admin sites:
https://books.agiliq.com/projects/django-admin-cookbook/en/latest/two_admin.html
And in my case, my application has 2 independent sites.

Is it possible to provide way to configure on which admin site register apps models?
(Sory for my bad English!)

**Comment by Delphi251189** [comment]
I edited allauth\account\admin.py 

from . import app_settings
from .adapter import get_adapter
from .models import EmailAddress, EmailConfirmation

 #ADDED THIS LINE
from b2b.admin import b2b_admin  

class EmailAddressAdmin(admin.ModelAdmin):
    list_display = ("email", "user", "primary", "verified")
    list_filter = ("primary", "verified")
    search_fields = []
    raw_id_fields = ("user",)

    def get_search_fields(self, request):
        base_fields = get_adapter(request).get_user_search_fields()
        return ["email"] + list(map(lambda a: "user__" + a, base_fields))


class EmailConfirmationAdmin(admin.ModelAdmin):
    list_display = ("email_address", "created", "sent", "key")
    list_filter = ("sent",)
    raw_id_fields = ("email_address",)

# AND EDITED THIS ONE
if not app_settings.EMAIL_CONFIRMATION_HMAC:
    # admin.site.register(EmailConfirmation, EmailConfirmationAdmin)
    b2b_admin.register(EmailConfirmation, EmailConfirmationAdmin)  

#admin.site.register(EmailAddress, EmailAddressAdmin)
b2b_admin.register(EmailAddress, EmailAddressAdmin)


this works but I need to more flexible  solution.

**Comment by iarp** [comment]
You can unregister an existing model using `admin.site.unregister(User)` and then re-register it with your own custom admin class using `admin.site.register(User, MyCustomAdminClass)`. No need to change allauths code for this.

**Comment by Delphi251189** [comment]
Ok. Thanks!!!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2715
