### ISSUE TITLE
Discord keep saying Invalid OAuth2 redirect_uri

### ISSUE THREAD

**Issue by MarshMello0** [pennersr/django-allauth#2723]
I'm really lost why I can't seem to set up to log in with discord again.

I've matched up these
| allauth | discord |
------------ | -------------
| client id | client id |
| secret key | Client Secret |
| key | Public Key |

And have added `https://vtolvr-mods.com/accounts/discord/login/callback/`

But one day it just broke and I can't set it up again. Just keep getting Invalid OAuth2 redirect_uri

Here is the link allauth takes me to
> https://discord.com/oauth2/authorize?client_id=668116312819761239&redirect_uri=https%3A%2F%2Fvtolvr-mods.com%2Fdiscord%2Flogin%2Fcallback%2F&scope=email+identify&response_type=code&state=EQhui7RXr2VI

and here is the one discord generates
> https://discord.com/api/oauth2/authorize?client_id=668116312819761239&redirect_uri=https%3A%2F%2Fvtolvr-mods.com%2Faccounts%2Fdiscord%2Flogin%2Fcallback%2F&response_type=code&scope=identify%20email

**Comment by iarp** [comment]
https://discord.com/developers/applications go into the app you're working on, select OAuth2 on the left sidebar. Your Redirects section has the incorrect url. You can see that by looking at the redirect_uri found in both urls you pasted above.

**Comment by MarshMello0** [comment]
Thank you so much, I had spotted a difference in that discord login callback part but never understood what it related to. 
Does that mean the docs need to be updated as they say have accounts at the front?

[The part I was copy and pasting](https://github.com/pennersr/django-allauth/blob/master/docs/providers.rst#discord)

**Comment by iarp** [comment]
You need to look at the urls.py section of the [installation documents](https://django-allauth.readthedocs.io/en/latest/installation.html). Default is `accounts/` so all provider examples of callback urls use `/accounts/`. I'd guess you left yours blank, all you need to do is remove `accounts/` from the callback url you pasted in discords settings,

**Comment by MarshMello0** [comment]
ahhh, my bad!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2723
