### ISSUE TITLE
Users can't add additional email

### ISSUE THREAD

**Issue by thomascs** [pennersr/django-allauth#2725]
Somehow my users can't add additional email accounts. But I can't figure out the setting that caused this problem? Searching the issues or the web didn't yield any results. Is this an unknown problem?

These are the settings I use:

```
AUTH_USER_MODEL = "users.Account"  # model is User from your users app
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_SIGNUP_EMAIL_ENTER_TWICE = True
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
```

I did use a costum user model, could that be causing problems?

```
class AccountManager(BaseUserManager):
    def create_user(self, email, username, password=None):
        if not email:
            raise ValueError("Users must have an email address")
        if not username:
            raise ValueError("Users must have a username")

        user = self.model(
            email=self.normalize_email(email),
            username=username
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password):
        user = self.create_user(
            email=self.normalize_email(email),
            username=username,
            password=password
        )

        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class Account(AbstractBaseUser):
    email = models.EmailField(verbose_name='email', max_length=60, unique=True)
    username = models.CharField(max_length=30, unique=True)
    date_joined = models.DateTimeField(
        verbose_name='date joined', auto_now_add=True)
    last_login = models.DateTimeField(
        verbose_name='last login', auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    uuid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    objects = AccountManager()

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return True
```

**Comment by 9mido** [comment]
@thomascs 

Just a guess but try using the latest version of allauth with ACCOUNT_MAX_EMAIL_ADDRESSES and set it to the number of email addresses you want each user to have. 

However, keep in mind that the more email addresses you allow users to have, you are more at risk of having users add unverified emails and being able to login with those unverified emails and the locking users out of their accounts if the unverified email addresses are not their own. 

See closed PR 2627 for a discussion of what happens in that scenario. Possible fixes we would need PRs for would be issues 2699 and 2360.

**Comment by thomascs** [comment]
@9mido Thanks for the quick reply, unfortunatly this didn't help. I'm using the latest version of allauth available on the conda forge channel.

Unless I'm missing something, except for the ability to add an extra email and verify this. Allauth doesn't have a standard procedure to change a users email adress?

**Comment by 9mido** [comment]
Allauth does have a procedure to change a user's email address to a new primary one but you have to add a new email address and make it the primary email address and also verify it for good measure. You can also add as many email addresses as you want. 

Maybe you have a better way/idea on what the procedure should be like?

There is probably something wrong with your code implementation. Hopefully nothing within the allauth code itself should be problematic but you never know. Someone else may be able to help you more with that than I can unfortunately.

**Comment by thomascs** [comment]
Did a clean install and the issue is gone. I think the problem was in an older version of the email template. Apperently the `{% if can_add_email %}` statement is not used anymore. Sorry for bothering you.

I think the current interface and procedure is the most flexible option. A more direct procedure would be to limit a user to one extra unverified email:

- After changing the email, this new email will have to be verified first. 

- Until then, login uses the old email. 

- After verifying, the old email is automatically replaced with the new verified email.

**Comment by 9mido** [comment]
No worries. Just making sure that it wasn't an allauth problem. Glad you figured it out. Thanks for replying with the solution as it may help others with the same problem.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2725
