### ISSUE TITLE
New settings for expiration of password reset link

### ISSUE THREAD

**Issue by lapinvert** [pennersr/django-allauth#2731]
Similarly to `ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS`, I think it would be nice to be able to set an expiration time for the link sent to user when he resets his password with PasswordResetView.

Something like `ACCOUNT_RESET_EMAIL_EXPIRE_HOURS`.
`HOURS` instead of `DAYS` because arguably it is more commonly seen for this kind of link for security reasons.

By the way, I see no usage of `ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS` in the code, only in documentation and tests. Is it deprecated? or should I create an issue for that?

**Comment by lapinvert** [comment]
It already exists natively in Django, `PASSWORD_RESET_TIMEOUT` in seconds, since Django 3.1, and it appears allauth uses the native Django token generation so it should work.

I leave the issue open for the question regarding whether `ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS` is used or not.

**Comment by 9mido** [comment]
Similar to #1522

**Comment by pennersr** [comment]
`PASSWORD_RESET_TIMEOUT` is already supported. As for `ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS`, see here: https://github.com/pennersr/django-allauth/blob/main/allauth/account/models.py#L118

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2731
