### ISSUE TITLE
Facebook oauth login does not work out of box

### ISSUE THREAD

**Issue by yedpodtrzitko** [pennersr/django-allauth#2735]
Hi,
it looks like the default Allauth's configuration prevents Facebook oauth2 login from being functional.

- [Facebook Login Docs says](https://developers.facebook.com/docs/facebook-login/security/#https):

> On October 6, 2018, all apps will be required to use HTTPS.

- Allauth's config option `ACCOUNT_DEFAULT_HTTP_PROTOCOL` is set by default to `http`

- neither `FacebookOAuth2Adapter` nor its parent `OAuth2Adapter` have the attribute `redirect_uri_protocol` set to `https`, so the callback url will be constructed with `http` protocol, and Facebook will return an error response when  `https` is not used there.

None of these things are obvious, the error message a bit is misleading (`Error retrieving access token ...`) and it's a bit difficult to debug the root cause. There are some other issues which look like they are caused by this:  https://github.com/pennersr/django-allauth/issues/2609  https://github.com/pennersr/django-allauth/issues/2161 

Maybe changing `FacebookOAuth2Adapter.redirect_uri_protocol` to `https` would feel like a more sane default value, or adding an explicit note to documentation could be helpful (?)

**Comment by derek-adair** [comment]
[I am pretty sure this was fixed](https://github.com/pennersr/django-allauth/blob/0e4c3141eb2c412a90157fa49f9831fd0abfc63d/allauth/socialaccount/providers/facebook/provider.py#L33)

**Comment by pennersr** [comment]
Closing -- FB OAuth works.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2735
