### ISSUE TITLE
Problem with ACCOUNT_AUTHENTICATION_METHOD = 'email'

### ISSUE THREAD

**Issue by jwierzbo** [pennersr/django-allauth#274]
Hi,
When i trying set ACCOUNT_AUTHENTICATION_METHOD = 'email', i got an error during the starting server:

> pydev debugger: starting
> Validating models...
> 
> AssertionError: 

And nothing more...

Also the problem is when I'm trying do syncdb:

> AssertionError: 
> Finished "/pathtoproject/manage.py syncdb" execution.

I tried install versions: 0.8.3, 0.9.0, 0.10.2?, 0.11.0-dev
But everytime same issue

BTW
Is possible to assign to one user few channels of auth? e.g. if user create standard account and now he would like to link his facebook account to get possibility to log in in the system by standard auth or fb...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/274
