### ISSUE TITLE
[example.com] appearing in the mail title 

### ISSUE THREAD

**Issue by nokemono** [pennersr/django-allauth#2741]
[example.com] appearing in the mail title.

ex)
[example.com] Please Confirm Your E-mail Address

However, the name example.com does not exist in the django admin site.
Moreover, they do not appear every time, but appear randomly and are not reproducible.

Where does the [example.com] in the mail title appear from?

**Comment by 9mido** [comment]
Watch this video. You need to override the templates so that you could customize it. 

https://www.youtube.com/watch?v=dXZim_jgaiI&t=708s

**Comment by nokemono** [comment]
I already did.
I can find the text of the email, but I don't know where the title is.

**Comment by 9mido** [comment]
It may be from the database. Worst cast scenario would be to remove it from showing up in the email message.

**Comment by yedpodtrzitko** [comment]
`example.com` is the default name of object `Site` object matching `settings.SITE_ID`

**Comment by iarp** [comment]
Just set `ACCOUNT_EMAIL_SUBJECT_PREFIX = ''` or if you already have an adapter in use you can override the [format_email_subject](https://github.com/pennersr/django-allauth/blob/master/allauth/account/adapter.py#L85) method.

**Comment by westlepor** [comment]
@iarp I override `format_email_subject` function and also set `ACCOUNT_EMAIL_SUBJECT_PREFIX = ''`, but still `example.com` is in the email title

I override like this
```
def format_email_subject(self, subject):
        return force_str(subject)
```

Please let me know your thoughts :)
Thank you!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2741
