### ISSUE TITLE
Accessing social provider running on the same server

### ISSUE THREAD

**Issue by snorrehu** [pennersr/django-allauth#2742]
Hi,

I have an application running on the same network as the social provider (keycloak) I would like to use for authentication. The problem is I then need to be able to do server-server communication by ip-address and redirect to keycloak login page with external url. Example:

**Setting auth url to keycloak external url:** I press Sign-In and I am redirected to keycloak login, but I cannot sign in because my server cannot communicate with keycloak internally with this url on the same network.

**Setting auth url to keycloak internal ip**: Signing in and server-server communication works when on the same network, but users outside the network cannot reach the login page.

Is there a way to use different auth urls, one for external connection and one for internal, with allauths' current configuration?

**Comment by snorrehu** [comment]
Managed to fix this by creating loopback functionality in the firewall.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2742
