### ISSUE TITLE
how to login/signup using django-allauth without leaving the page.

### ISSUE THREAD

**Issue by aliscie** [pennersr/django-allauth#2744]
![how to make a login popup like this](https://dev-to-uploads.s3.amazonaws.com/i/i915ua838jw1edlztf00.png)
when you go to `localhost:8000/accounts/login` and lick google django-allauth will redirect you to the google login/singup page. But, I want to get all the user accounts inside my page in which I can create the list of the google account so user can click them and login or singup without leaving the page.
Note: I know how to make a popup window where it open the google login/singup page but this is not what I want. I want to get each account separately not an uncontainable google page

**Comment by 9mido** [comment]
Did you try looking at this?

https://stackoverflow.com/questions/38126241/over-riding-django-allauth-login-registration-urls-with-custom-url-pages

**Comment by derek-adair** [comment]
Tag as help wanted.  This seems like a massive undertaking but valid none-the-less.  I can see something like this being added as a specific and configurable user experience. Something configurable like...

```
SOCIAL_ACCOUNT_FLOW=("same_page", "leave_page")
```
... or whatever... you get the idea.

**Comment by pennersr** [comment]
See Google One Tap Sign-In (9246957e)

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2744
