### ISSUE TITLE
How to show errors in template returned by ajax request

### ISSUE THREAD

**Issue by imshubhdj** [pennersr/django-allauth#2745]
Hi,

I am very confused about showing errors that are returned by ajax response (JSON). I want to render form with errors using ajax.
Can you provide with template code.

and one more query ... 
what is the best practise to implement login/signup through modal - ajax or <any other method>?? this is in context with django-allauth.

![image](https://user-images.githubusercontent.com/23445731/102757775-d35ad480-4397-11eb-80eb-7f6e60cb1d86.png)

**Comment by pennersr** [comment]
Closing "How do I..."  -- not an issue in allauth.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2745
