### ISSUE TITLE
pyjwt[crypto] 2.0.0 update incompatible with django-allauth

### ISSUE THREAD

**Issue by erichideki** [pennersr/django-allauth#2746]
Hi, I have a project that uses django-allauth 0.44.0. Yesterday (12/22/20) pyjwt update your version to 2.0.0. When i try to install my dependencies running pip, return this error message, using docker-compose:

Collecting pyjwt[crypto]>=1.7
ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    pyjwt[crypto]>=1.7 from https://files.pythonhosted.org/packages/91/5f/5cff1c3696e0d574f5741396550c9a308dde40704d17e39e94b89c07d789/PyJWT-2.0.0-py3-none-any.whl#sha256=5c.... (from django-allauth==0.44.0->-r requirements-dev.txt (line 125))
ERROR: Service 'web' failed to build: The command '/bin/sh -c pip install -r requirements-dev.txt' returned a non-zero code: 1

In Poetry.lock:

[[package]]
name = "django-allauth"
version = "0.44.0"
description = "Integrated set of Django applications addressing authentication, registration, account management as well as 3rd party (social) account authentication."
category = "main"
optional = false
python-versions = "*"

[package.dependencies]
Django = ">=2.0"
pyjwt = {version = ">=1.7", extras = ["crypto"]}
python3-openid = ">=3.0.8"
requests = "*"
requests-oauthlib = ">=0.3.0" 

[[package]]
name = "pyjwt"
version = "1.7.1"
description = "JSON Web Token implementation in Python"
category = "main"
optional = false
python-versions = "*"

Anybody do have the same issue? Thanks

**Comment by erichideki** [comment]
Update: You must update pyjwt to 2.0.0 and pip install works. But should not break installation by force update packages dependencies

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2746
