### ISSUE TITLE
signup via github still does not retrieve verified email

### ISSUE THREAD

**Issue by simkimsia** [pennersr/django-allauth#2749]
This issue should have been solved https://github.com/pennersr/django-allauth/issues/369, but somehow I am unable to make it work.

the user in question set the github setting to not show email addresses as public.

but I have tried 
![image](https://user-images.githubusercontent.com/245021/103199712-5e9f1180-4926-11eb-9a69-0d772fbe2755.png)

And when I try to authorize it was clear that the private email address will be given

![image](https://user-images.githubusercontent.com/245021/103199791-9d34cc00-4926-11eb-942d-402b4a6709d5.png)

So I'm not sure what I did wrong. 

My version of allauth is `django-allauth==0.43.0`

## Update

When I checked the extra_data

```
{"login": "simkimsia", "id": xxxx, "node_id": "MDQ6VXNlcjI0NTAyMQ==", "avatar_url": "https://avatars1.githubusercontent.com/u/xxxx?v=4", "gravatar_id": "", "url": "https://api.github.com/users/simkimsia", "html_url": "https://github.com/simkimsia", "followers_url": "https://api.github.com/users/simkimsia/followers", "following_url": "https://api.github.com/users/simkimsia/following{/other_user}", "gists_url": "https://api.github.com/users/simkimsia/gists{/gist_id}", "starred_url": "https://api.github.com/users/simkimsia/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/simkimsia/subscriptions", "organizations_url": "https://api.github.com/users/simkimsia/orgs", "repos_url": "https://api.github.com/users/simkimsia/repos", "events_url": "https://api.github.com/users/simkimsia/events{/privacy}", "received_events_url": "https://api.github.com/users/simkimsia/received_events", "type": "User", "site_admin": false, "name": null, "company": null, "blog": "", "location": null, "email": null, "hireable": null, "bio": null, "created_at": "2010-04-15T21:23:27Z", "updated_at": "2020-12-28T07:33:34Z"}
```

This is what I get. So since the email is marked as null, I thought the `/emails` endpoint will be triggered as per the PR https://github.com/pennersr/django-allauth/commit/88e9690701ffd0f213175b015bc162a8abe03951

**Comment by simkimsia** [comment]
Once I added

```
# under https://django-allauth.readthedocs.io/en/latest/configuration.html
SOCIALACCOUNT_EMAIL_REQUIRED = True
```

Now  i will get prompted with this after i authorized

![image](https://user-images.githubusercontent.com/245021/103202608-d290e800-492d-11eb-8c7d-f4ff0e5e43dd.png)

Why won't the email address be auto taken from the socialaccount at GitHub?

**Comment by simkimsia** [comment]
Ok never mind, I now realize the trick is to also turn on `ACCOUNT_EMAIL_REQUIRED = True`

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2749
