### ISSUE TITLE
Microsoft Provider: In extract_uid, handle response when "id" not found.

### ISSUE THREAD

**Issue by snowman2** [pennersr/django-allauth#2754]
https://github.com/pennersr/django-allauth/blob/52978e2e5c7e1755f8b904aea65b3cf305d2c92c/allauth/socialaccount/providers/microsoft/provider.py#L28

Currently it raises a `KeyError` which results in an internal server error. It would be nice to handle that better.

**Comment by snowman2** [comment]
Example response from microsoft:
```
{'error': {'code': 'InvalidAuthenticationToken',
  'message': 'Access token validation failure. Invalid audience.',
  'innerError': {'date': '2021-01-06T14:39:07',
   'request-id': 'aaaaaa-bbbb-cccc',
   'client-request-id': 'aaaaaa-bbbb-cccc'}}}
```

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2754
