### ISSUE TITLE
How can I call EmailView._action_send() from my view ?

### ISSUE THREAD

**Issue by tasiotas** [pennersr/django-allauth#2755]
Hi,

I am trying to implement admin functionality of resending activation email to users.
I know user can use account/email.html view for management, but I need to be able resend emails for them too.

I found EmailView._action_send(), but not sure how can I call it from my view.
How can I call it providing only email address?

Thank you,
Tas

**Comment by iarp** [comment]
Do you need to call that method or do you just want to send the email? You can [see here](https://github.com/pennersr/django-allauth/blob/master/allauth/account/views.py#L466) that it just obtains the EmailAddress object and then calls [send_confirmation](https://github.com/pennersr/django-allauth/blob/master/allauth/account/views.py#L476)

**Comment by tasiotas** [comment]
Perfect, that was so easy. Thank you very much.
Here is code for newbies like me

```
    from allauth.account.models import EmailAddress

    email_address = EmailAddress.objects.get(email='user@email.com')
    email_address.send_confirmation()
```

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2755
