### ISSUE TITLE
django-Allauth with linkedin Rest API getting issues while getting access-token

### ISSUE THREAD

**Issue by akash-s-simformsolutions** [pennersr/django-allauth#2758]
I am trying to implement Django REST Framework with Social login using Linkedin using django-allauth.

I am sending code which i get it from frontend side which will be used to get access_token

Error i am getting : 
```
Error retrieving access token: b'{"error":"invalid_redirect_uri","error_description":"Unable to retrieve access token: appid/redirect uri/code verifier does not match authorization code. Or authorization code expired. Or external member binding exists"}'
```
Please find bellow screenshot for error

Error Screen shot :
![Screenshot 2021-01-07 at 7 52 59 PM](https://user-images.githubusercontent.com/76422838/103905017-181a9580-5124-11eb-8c72-47c293dee11f.png)

I have added below code in our view.py file 
```
from allauth.socialaccount.providers.oauth2.client import OAuth2Client
from dj_rest_auth.registration.views import SocialLoginView
from allauth.socialaccount.providers.linkedin_oauth2.views import LinkedInOAuth2Adapter

class LinkedinLogin(SocialLoginView):
    adapter_class = LinkedInOAuth2Adapter
    callback_url = 'http://localhost:8000/accounts/linkedin/login/callback/'
    client_class = OAuth2Client
```

If anybody can help with this. I want to use code which i get it from frontend to get access_token and login user with the same.

Thanks.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2758
