### ISSUE TITLE
Setting To Block Or Unblock Signups If Traffic Is Or Is Not High

### ISSUE THREAD

**Issue by 9mido** [pennersr/django-allauth#2760]
Smaller sites without scalable infrastructure that have huge spikes in traffic suddenly may want to temporarily block sign ups from happening. This may help the smaller sites by giving them more time to scale up their infrastructure. That way, no more data in the database gets populated. 

My proposal is create a setting to allow developers to block signups temporarily. When there is a huge spike in traffic, the developer could switch on and off this setting to either unblock signups or block them. 

https://stackoverflow.com/questions/29794052/how-could-one-disable-new-account-creation-with-django-allauth-but-still-allow

https://stackoverflow.com/questions/17923692/turn-off-user-social-registration-in-django-allauth

That stackoverflow links uses an Adapter so maybe this issue could be closed but maybe this could be built in?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2760
