### ISSUE TITLE
Calling login endpoint does not send verification email, if the email has not been verified after signup

### ISSUE THREAD

**Issue by azadehrichter** [pennersr/django-allauth#2768]
I tried to call the login endpoint before verifying the email (by clicking on the link in the email, sent after signing up). I receive the  error that "The email is not verified", which is correct. But according to the documentation, another email verification message should be sent, which is not happening.

I set the `ACCOUNT_EMAIL_CONFIRMATION_HMAC` to `False`, and left the `ACCOUNT_EMAIL_CONFIRMATION_COOLDOWN` as it was, 180 seconds.

I also went through the implementation and the logic seems to be correct.

Have I missed something there? I am using Django 3.1.5, djangorestframework 3.12.2, django-allauth 0.44, and dj-rest-auth 2.1.2. Thank you in advance!

**Comment by azadehrichter** [comment]
solved!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2768
