### ISSUE TITLE
Access to fields with social authorization

### ISSUE THREAD

**Issue by ogurec-ogurec** [pennersr/django-allauth#2769]
Hello everyone.
I have such a question, for example, when authorizing (for example, social **VK)** I receive the following user fields:

     "email",
     "first_name",
     "last_name",
     "sex",
     "bdate",
     "city",
     "photo",
     "photo_medium",
     "photo_big",
     "photo_max_orig",

How do I access this data in the template?
For example, {{user.first_name}} - works, but
{{user.photo_medium}} - no.

How can I access the photo that I received after logging in through a social provider?

I would be grateful for any help

**Comment by pennersr** [comment]
See SocialAccount.extra_data -- closing.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2769
