### ISSUE TITLE
Add reconcile account functionality

### ISSUE THREAD

**Issue by commadelimited** [pennersr/django-allauth#277]
**Setup**:
User logs in with SocialAccount A, logs out, then logs in with SocialAccount B.

In the situation above, if user then logs in with either account and attempts to "add" the other account to the existing account, Allauth with replace the currently active account with the new account.

Here's a quick video illustrating what's happening:

http://screencast.com/t/4otMLwNYIDr

Note, that what I expect to happen is that account A & B would both show up in the same screen. I suspect that what's happening is that a Django User account each time the user "logs in" with a different account. This is understandable, but what we're looking for is a way to reconcile accounts AFTER creation, or a way to determine if they should be combined to begin with.

User @orblivion has a pull request (https://github.com/pennersr/django-allauth/pull/272) which would emit signals when a user adds a new SocialAccount.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/277
