### ISSUE TITLE
Keycloak link invalid

### ISSUE THREAD

**Issue by Bergiu** [pennersr/django-allauth#2775]
https://github.com/pennersr/django-allauth/blob/master/docs/providers.rst#keycloak

The link to the keycloak documentation has changed. there is no description on how to create an register the client

**Comment by Bergiu** [comment]
there is also a typo in `KEYCLOAK_REAML`. it should be `KEYCLOAK_REALM`

**Comment by juantxorena** [comment]
2 years later and still open?

**Comment by pennersr** [comment]
Can you send over a PR?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2775
