### ISSUE TITLE
How to distinguish user signed up only by social network from user who signed up via email/password and connected social network?

### ISSUE THREAD

**Issue by anndoc** [pennersr/django-allauth#2776]
Is there a way to distinguish user signed up only by social network from user who signed up via email/password and then connected a social network?

**Comment by pennersr** [comment]
There is a `user_signed_up` signal that you can hook up to and check how the signup was done. Then, use that information as you see fit.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2776
