### ISSUE TITLE
Typo in sk django.po

### ISSUE THREAD

**Issue by eriktelepovsky** [pennersr/django-allauth#2783]
https://github.com/pennersr/django-allauth/blob/7d8676de9b5948c4d505d5a42ca80008cfd0ba4d/allauth/locale/sk/LC_MESSAGES/django.po#L629

nedostalido > nedostali do

**Comment by pennersr** [comment]
Closed via 941cbdd7

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2783
