### ISSUE TITLE
Feature request: TrainingPeaks integration

### ISSUE THREAD

**Issue by squio** [pennersr/django-allauth#2788]
PR #2777 adds TrainingPeaks integration; fully tested with their Sandbox API (which should be equivalent to production).

Api access is on request only though, as is [mentioned in the documentation](https://github.com/pennersr/django-allauth/pull/2777/files#diff-0c5ae732a158140a1834a79bd6b5511801c9b6ce87e3247a1488d699fd6bf588).

**Comment by squio** [comment]
Just a heads up that we have this feature now running in production, after our implementation and test runs have been approved by TrainingPeaks.

**Comment by squio** [comment]
@pennersr can you please give an update when / if this PR #2777 will be merged?

All tests pass, requested changes are made and the provider works well in production (some 20+ user accounts linked and in use). It would be great to have this in the official maintained branch.

**Comment by pennersr** [comment]
Closed via c50a30acc0e4553297b0ddb697d55a290ed6d038

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2788
