### ISSUE TITLE
multiple/different types of signup and profile forms for different types of users: is this possible? 

### ISSUE THREAD

**Issue by kfra436** [pennersr/django-allauth#2789]
I have been trying to figure out a solution, and have tried everything I can think of. Multiple stackoverflow posts mention similar issues but they all either go unanswered or offer outdated solutions (that don't work). This post is similar to the solutions offered in stackoverflow: https://dev.to/gajesh/the-complete-django-allauth-guide-la3 . It works for one signup form, not multiple. 

What I want is users/accounts/signup/ to direct to BasicSignupForm and users/accounts/signup_vendors/ to direct to a vendor specific signup form. Similarly, I need multiple types of profiles. How can this be accomplished? 

Below is what I have for one working signup form. However, if I try to inherit from or extend the working form to create different one, assigned to users/accounts/vendor_signup/ the form renders but upon submission it redirects to accounts/signup/ with a blank default signup form that I don't even use for the general purpose form.

```
#settings.py : assign to custom form
ACCOUNT_SIGNUP_FORM_CLASS = "users.forms.BasicSignupForm"
```

#users.forms.py
```
class BasicSignupForm(forms.Form):
    first_name = forms.CharField(max_length=255, help_text="Your first name")
    last_name = forms.CharField(max_length=150, help_text="Your last name")
    phone = forms.CharField(max_length=150)

    def signup(self, request, user):
        user.first_name = self.cleaned_data["first_name"]
        user.last_name = self.cleaned_data["last_name"]
        user.phone = self.cleaned_data["phone"]
        user.save()
```

#users.views.py
```
class BasicSignupView(SignupView):
    template_name = "account/signup.html"
    form_class = GeneralSignupForm
    redirect_field_name = "next"
    view_name = "signup"
    success_url = None

    def get_context_data(self, **kwargs):
        data = super(GeneralSignupView, self).get_context_data(**kwargs)
        data.update(self.kwargs)
        return data
```

#users.urls.py
`path('accounts/signup/', views.BasicSignupView.as_view(), name='signup'),`

#urls.py
```
	path('users/', include('users.urls')),
	url(r'^accounts/', include('allauth.urls')),
```

**Comment by Usouf** [comment]
I had a similar issue, and you probably have solved it, but here is how I solved it:

1. Create a form for every profile signup. In your case it would 2 forms.
2. Create 2 views that extends 'SignupView' and set the form_class to one of the forms you created.
3. Create a URL that uses the views you have created.
4. You don't have to set 'ACCOUNT_SIGNUP_FORM_CLASS'.

So I think you are going in the right direction.

**Comment by epetrov1** [comment]
I have followed this logic and still cannot render the forms at my templates. Any suggestions?

**Comment by Usouf** [comment]
Can you show us your code?

**Comment by epetrov1** [comment]
Get context data function in my view was the problem. 
[https://stackoverflow.com/questions/67933848/multiple-user-sign-up-with-django-allauth-two-signup-forms-not-render/67943576#67943576](url)

**Comment by derek-adair** [comment]
Close as discussion.

Yes this is possible by custom urls/views/forms.  The key is to look at how signup views are instantiated and then pass additional forms in the views.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2789
