### ISSUE TITLE
Docs for generic oauth and oauth2 provider

### ISSUE THREAD

**Issue by andynd** [pennersr/django-allauth#2790]
There is docu for even obscure stuff like an eve online provider but I had to read the source code to even find out generic oauth is supported at all. Please extend the documentation for those.

relates to #2415 #2425

**Comment by pennersr** [comment]
Feel free to file a PR and contribute to the documentation, but keeping this issue open is not really helpful in that regard.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2790
