### ISSUE TITLE
Django not able to find static files when using allauth

### ISSUE THREAD

**Issue by sachingupta006** [pennersr/django-allauth#28]
When I use allauth, everything seems to work fine except that Django is now unable to find the static files. Without allauth all the static files are being rendered. the settings for allauth requires to add 

TEMPLATE_CONTEXT_PROCESSORS 

I did not have this field in my settings file earlier. Is there something that I am missing? How should I solve this problem. When I see the DEBUG console I can see it is trying to fetch the css file as

"GET /accounts/login/css/contact.css"

whereas it should be doing

"GET /static/css/contact.css"

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/28
