### ISSUE TITLE
Documentation uses deprecated method 

### ISSUE THREAD

**Issue by gal064** [pennersr/django-allauth#2801]
The [official documentation](https://django-allauth.readthedocs.io/en/latest/forms.html#) for forms stills uses the save method, which as far as I know was deprecated past 0.15 version

**Comment by pennersr** [comment]
`save()` is indeed deprecated in favor of `signup()`, but that is only for `ACCOUNT_SIGNUP_FORM_CLASS`. The linked documents overriding existing forms, whereas `ACCOUNT_SIGNUP_FORM_CLASS` is an additional plain `django.forms.Form`.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2801
