### ISSUE TITLE
Cannot POST JSON data and use allauth as JSON API

### ISSUE THREAD

**Issue by mecampbellsoup** [pennersr/django-allauth#2802]
Related: https://github.com/pennersr/django-allauth/issues/799

## Description

My desire is to use allauth endpoints as a sort of auth-specific JSON API.

I am making an AJAX request to my allauth `/accounts/signup` endpoint that contains the following data:

```
curl http://localhost:8000/accounts/signup/ \
  -H 'Content-Type: application/json' \
  -H 'accept: application/json' \
  -H 'x-requested-with: XMLHttpRequest' \
  -d '{"email": "foo@bar.com", "password1": "secretpassword"}'
```

It seems like the `AjaxCapableProcessFormViewMixin` mixin code is definitely running, as you can tell from the following `print` statements that I added to the code (and below the corresponding prints):

```
{'cookie': 'csrftoken=OF3GMjVupCEhzxxpjFdAMJgpKMtAqe2Auajfe5U7ZZk5zbV1DQSHoDQzrsuf13iV', 'connection': 'close', 'content-length': '47', 'origin': 'http://0.0.0.0:8080', 'content-type': 'application/json', 'referer': 'http://0.0.0.0:8080/api/', 'accept-encoding': 'gzip, deflate', 'accept-language': 'en-US,en;q=0.5', 'accept': 'application/json', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.16; rv:86.0) Gecko/20100101 Firefox/86.0', 'host': '0.0.0.0:8080', 'x-requested-with': 'XMLHttpRequest', 'x-csrftoken': 'OF3GMjVupCEhzxxpjFdAMJgpKMtAqe2Auajfe5U7ZZk5zbV1DQSHoDQzrsuf13iV'}
self.request.method POST
In AJAX form view...
b'{"email": "foo@bar.com", "password1": "secret"}'
<QueryDict: {}>
<class 'django.core.handlers.asgi.ASGIRequest'>
<tr><th><label for="id_email">E-mail:</label></th><td><ul class="errorlist"><li>This field is required.</li></ul><input type="email" name="email" placeholder="E-mail address" autocomplete="email" required id="id_email"></td></tr>
<tr><th><label for="id_password1">Password:</label></th><td><ul class="errorlist"><li>This field is required.</li></ul><input type="password" name="password1" placeholder="Password" autocomplete="new-password" required id="id_password1"></td></tr>
<QueryDict: {}>
<class 'allauth.account.forms.SignupForm'>
```

```python3
class AjaxCapableProcessFormViewMixin(object):
    def get(self, request, *args, **kwargs):
        response = super(AjaxCapableProcessFormViewMixin, self).get(
            request, *args, **kwargs
        )
        form = self.get_form()
        return _ajax_response(
            self.request, response, form=form, data=self._get_ajax_data_if()
        )

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        print('In AJAX form view...')
        print(request.body)
        print(request.POST)
        print(request.__class__)
        print(form)
        print(form.data)
        print(form.__class__)
```
How is this supposed to work? Like I said, I'm simply trying to POST the signup form as JSON to register a new user.

**Comment by jberends** [comment]
We also observed this problem for years now as well. using json data is not possible. Only via formdata. Tests on it in the code does not seem to test posting json data against the form.

**Comment by KaczuH** [comment]
Exactly. Test client should set `content_type=`application/json` to properly encode json data in the request.
See documentation: https://docs.djangoproject.com/en/3.2/topics/testing/tools/#django.test.Client.post

Following tests should be reviewed:

- `test_ajax_password_reset`
- `test_ajax_login_fail`
- `test_ajax_login_success`
- `test_ajax_add_invalid`
- `test_ajax_remove_primary`
- `RequestAjaxTests`

**Comment by sowinski** [comment]
So currently it is not possible to use AJAX to signup an user?

**Comment by pennersr** [comment]
You can use AJAX calls to POST data, it's just that the data posted is to be of type `application/x-www-form-urlencoded`, not JSON.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2802
