### ISSUE TITLE
token_secret field on socialaccount_socialtoken too small with linkedin provider

### ISSUE THREAD

**Issue by pg1671** [pennersr/django-allauth#2804]
The field on the table is 200 characters but I have tokens returned by linkedin with 350 characters.

I am then getting this error on signup via linkedin:
/linkedin_oauth2/login/callback/
value too long for type character varying(200)

Can this field be made larger or just a text field.

**Comment by pg1671** [comment]
I just happened to check the code for the model and the field is already set to a text field.

When running migrations my app includes socialaccount in this list of migrations it includes but is not migrating this field.

Not sure why my database field is not being updated from varchar(200) to text during migrations?

I will just update the field manually.

**Comment by pennersr** [comment]
Closing -- not an issue in allauth.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2804
