### ISSUE TITLE
Feature Request / request for help: Add socialprovider for NetIQ/Microfocus AccessManager

### ISSUE THREAD

**Issue by Glowsome** [pennersr/django-allauth#2805]
As the subject stated looking for an implementation of socialprovider for the IDP based on MicroFocus's ( formerly NetIQ)  AccessManager

i have been looking into it and slowly fiddling around with own coding, but still not there ... 

As the social provider auth0 seems to point towards the correct direction it gave me a base, 
Thus creating a providers/netiq/* folder to home my work and have been developing with this as template.

At current i have adapted the provider.py, the urls.py and the views.py. and publishing it so it can be clicked/used as social provider in my lab setup.

Thing i am facing is a 'key-error' after i've authenticated at the IDP in complete_login routine.

This is most likely due to my unfamiliarity with python ... 
Still searching what/where/when is actually offered after authentication from the IDP .. as i cant seem to see it back in logging even if i set logging level to 'DEBUG'
Setup info: i am using a docker setup (as taken from [https://asynchronous.in/docker-mailman/](https://asynchronous.in/docker-mailman/)

**Comment by Glowsome** [comment]
Right... gotten a bit further, changed code a bit around using the OKTA provider next to auth0.

In essence i now have a working (login) provider but i dont see my first name and last name being populated/updated.

**Comment by Glowsome** [comment]
Concerns/Obeservations : 

- if someone authenticates over Oauth2 , meaning authentication is relocated to an IDP fields which are sent over this link should _not_ be editable ( i think this is beyond the plugin ?)
- Logout when linked up over Oauth2 will logout the application, bot does not give a SLO-experience (preferred)
=> meaning when i hit refresh i log in without re-authentication ... as i still have my session at the IDP.
- no means of dictating a configured authentication contract (application-side) on the IDP ( acr_value(s)) - as specified in oauth standards.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2805
