### ISSUE TITLE
How can I save user name when Apple sign in?

### ISSUE THREAD

**Issue by playma** [pennersr/django-allauth#2808]
I use Facebook Login, Google Login, they can save user name and avatar automatically.
But I use Apple login, get nothing...

Can someone else help me? Thanks

This is my setting. 

```
class AppleLogin(SocialLoginView):
    authentication_classes = (JWTAuthentication,)
    adapter_class = AppleOAuth2Adapter
    callback_url = '/api/rest-auth/apple/callback/'
    client_class = AppleOAuth2Client
```

**Comment by pennersr** [comment]
Closing ("How can I..." does not pinpoint an issue)

**Comment by yandiro** [comment]
How did you do to get the name, @playma ? I am having the same issue

**Comment by pfcodes** [comment]
Might be related: `populate_user` isn't setting first and last names when using the Apple provider

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2808
