### ISSUE TITLE
Best place to save IP / Browser fingerprint during registration

### ISSUE THREAD

**Issue by sowinski** [pennersr/django-allauth#2809]
Hi,

I want to detect bots which start the registration process and filter them by IP or a Browser finger print.

Where would you store this information and at where would you place the code?

My idea:
- Create a new Model with a FK to the User object which is created during the Registration process.
- I would extend the SignupView class and implement my logic within the POST method.

What do you think?

**Comment by sowinski** [comment]
That is my solution:

```
# this is where I store informations about a user.
class MyDefaultAccountAdapter(DefaultAccountAdapter):

    def save_user(self, request, user, form, commit=True):
        user = super(MyDefaultAccountAdapter, self).save_user(request, user, form, commit)
        # Store user informations here
        return user
```

And this is where I try to stop a bot.
```
class MySignupView(SignupView):

    def post(self, request, *args, **kwargs):
        honeypot = request.POST.get('password')
        if honeypot:
            return HttpResponseRedirect('/accounts/confirm-email/')
        return super(MySignupView, self).post(request, *args, **kwargs)
```

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2809
