### ISSUE TITLE
Login issues

### ISSUE THREAD

**Issue by AbdealiLoKo** [pennersr/django-allauth#281]
Hi,
I was trying out the example app and am having some trouble with everything except google and twitter.

Things I tried, and errors : 
1. GitHub - Gives 404 error
2. Facebook - Given URL is not permitted by the application configuration. (I tried "Website with Facebook Login" as http://127.0.0.1:8000/accounts/facebook/login and http://127.0.0.1:8000 does not work)
3. Dropbox - Signs me in as root, not a new acct

Is there some fault in my app settings of the provider ? Or something else that I dont get ?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/281
