### ISSUE TITLE
Limit sign up to a specific email domain

### ISSUE THREAD

**Issue by samul-1** [pennersr/django-allauth#2810]
Hello,

I'm getting started with dj-rest-auth and allauth and I have an app which allows user to only sign in via google. However, I want users to only be able to access my service with a specific google apps email domain.

I'm using dj-rest-auth in conjunction with django-allauth.

This is what I tried: I created allauth adapters like this:

```
class CustomAccountAdapter(DefaultAccountAdapter):
    def is_open_for_signup(self, request):
        return False  # No email/password signups allowed


class CustomSocialAccountAdapter(DefaultSocialAccountAdapter):
    def is_open_for_signup(self, request, socialaccount):
        u = socialaccount.user
        return u.email.split("@")[1] == "mydomain.com"
```

and in my settings I have

```
ACCOUNT_ADAPTER = "users.adapters.CustomAccountAdapter"
SOCIALACCOUNT_ADAPTER = "users.adapters.CustomSocialAccountAdapter"
```

With this solution, if the user tries to sign in with a valid email, everything works and their account is created in django and associated with their email.
However, if a user tries to sign in with a non-allowed email address, they end up being signed up via the "non-social" sign in instead of being denied the registration.

I know that their data is going to the regular sign up view instead because if I take away the allauth.urls from my app, when signing in I get this error: `django.urls.exceptions.NoReverseMatch: Reverse for 'account_login' not found. 'account_login' is not a valid view function or pattern name.` which I don't get if I try to sign in wih an allowed email domain.

This is what I'm trying to achieve: users can only sign in using google (no regular sign in/up allowed) and only using a specific email domain. If a user tries to sign in with another email address domain, I want them to be presented with a 403 or similar and a message instructing them to log in with a valid address.

How do I achieve this with allauth + drf?

Here's some more relevant code:

urls
```
urlpatterns = [
    path("", include("dj_rest_auth.urls")),
    path("allauth", include("allauth.urls")),
    path("google", views.google_login, name="google_login"),
]
```
views
```
class GoogleLogin(SocialLoginView):
    adapter_class = GoogleOAuth2Adapter

google_login = GoogleLogin.as_view()
```

**Comment by pennersr** [comment]
In the `pre_social_login` adapter method you can inspect the social login, and abort if it does not match your expectations.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2810
