### ISSUE TITLE
How can i login from Axios?

### ISSUE THREAD

**Issue by Jacks349** [pennersr/django-allauth#2817]
I'm building a fully separated VueJS/Django app, where Vue handles the frontend and Django handles the backend and they communicate using JSON. Since i want to use Django-Allauth and Django's session authentication, i'm going to deploy the two apps on the same server and on the same port. 

Until now, i only used Allauth with standard Django templates, so i'm having some problems doing the same from AJAX/Axios. Now, i read that Allauth supports AJAX requests, so i think it's doable but i'm not sure how. Here is what i tried:

This is my axios code, i'm not sending the CSRF token because i temporarily disabled the CSRF View middleware for developing, i will enable it back on production once i know how to deal with CSRF tokens in separated apps

```
axios({
  method: 'post',
  url: 'http://127.0.0.1:8000/accounts/login/',
  data: {
    'username':'test',
    'password':'test'
  },
  withCredentials: true,
  headers: {
    "content-type": "application/json" 
  }
}).then(function (response) {
  console.log(response)
}).catch(function (error) {
  console.log(error)
});
```

Here is some of my settings.py, notice that these settings are only for my dev environment:

```
CORS_ORIGIN_ALLOW_ALL = True  

CORS_ALLOW_HEADERS = list(default_headers) + [
    'xsrfheadername',
    'xsrfcookiename',
    'content-type',
    'x-csrftoken',
    'X-CSRFTOKEN',
]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = [
    "http://localhost:8080",
    "http://127.0.0.1:8080",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:8080",
    "http://127.0.0.1:8080",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]

CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_HTTPONLY = True
```

Once i perform this request, the response is going to be HTML and i don't get logged in. Am i doing something wrong? How can i get an AJAX response? Thanks in advance and thanks for working on Allauth, i've used it until now without any sort of problem!

**Comment by Andrew-Chen-Wang** [comment]
That's weird. It should just work. This is the `is_ajax` check which gives you the proper response: https://github.com/pennersr/django-allauth/blob/80e07a25803baea4e603251254c7d07ef2ad5bb5/allauth/account/adapter.py#L524-L531

Make sure at least one of those inputs are available in the request.

**Comment by Jacks349** [comment]
@Andrew-Chen-Wang Thank you for your answer and sorry for the late response! I didn't manage to make it work, but i made my own adapter which helped a lot to solve the problem partially, so it's alright! I think the issue can be closed if no one else had this problem

**Comment by nama1arpit** [comment]
Hi @Jacks349, thanks for making this issue. I am facing a very similar problem, can you please discuss in a bit more detail on how you went around solving it?

I have a react frontend and django backend. Apparently the frontend can't see the csrf cookies from the browser, so I made a separate API just to send the CSRF token and then the frontend attaches it to other authetication APIs. Am I doing something wrong? Are there any other resources that I can refer to?

**Comment by RakeshAMD** [comment]
need some good documentation on this. Unable to integrate this with vuejs

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2817
