### ISSUE TITLE
where will i get the uid and token to reset the password?

### ISSUE THREAD

**Issue by MySecondLanguage** [pennersr/django-allauth#2818]
My url: `path("rest-auth/", include("rest_auth.urls"))`
When i  request password reset with this endpoitn: http://127.0.0.1:8000/rest-auth/password/reset/ it sends me an email with an url which is working well to reset password but i don't need need like this way.

I am using http://127.0.0.1:8000/rest-auth/password/reset/confirm/ to confirm the password reset and it expect following data

`{
    "new_password1": "",
    "new_password2": "",
    "uid": "",
    "token": ""
}`

I dont receive uid and token in the mail, only i  receive an url to reset password, anyone there know how can make confirm password reset?

**Comment by pennersr** [comment]
Closing -- please only file issues in allauth.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2818
