### ISSUE TITLE
The redirect_uri does not match the registered value LinkedIn

### ISSUE THREAD

**Issue by societyofai** [pennersr/django-allauth#2822]
The redirect_uri specified in the documentation is not working for Linkedin app. Can anyone please help

**Comment by caiojhonny** [comment]
Verify if your redirect_uri is the same inserted on OAuth 2.0 settings.

I had problems because I was passing along the callback URL the path of the active language of my site. ('/en/', '/it/', etc)

I had to add all possible variants and it worked.

**Comment by pennersr** [comment]
Closing, configuration issue -- not an issue in allauth.

**Comment by derinjohnantony** [comment]
http://localhost:8000/accounts/linkedin_oauth2/login/callback/

please give this as the callback url. It worked for me

**Comment by atharva21-stack** [comment]
@derinjohnantony it didn't work : (

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2822
