### ISSUE TITLE
How do you implement multiusers setup using Django-allauth

### ISSUE THREAD

**Issue by estaar** [pennersr/django-allauth#2824]
How do you make django all auth to create different users. I have a custom User model with four different users and when I create a User they are not automatically put to the respective classes

**Comment by 9mido** [comment]
In your search engine type "django allauth different user signups" or something similar. 

https://stackoverflow.com/questions/44505242/multiple-user-type-sign-up-with-django-allauth

**Comment by quroom** [comment]
@9mido 
Do know how to implement that in social account?
With allauth normal account, It's easy to implement it by using different url path with different form.
But when we use social account, url is fixed. So I don't know how to implement it.
Do we need to send a request parameter to choose which user type is?

**Comment by estaar** [comment]
@quroom even with a normal account I have not been very successful to add the fields that come with the custom user. I have followed the suggestion given by @9mido . If I pass them into the form say firstname, the user gets created but I get an error StudentUser() got an unexpected keyword argument 'first_name'. so I am still stuck with the default email, passwords and the field that is specific to the student user model.

**Comment by 9mido** [comment]
I don't use social accounts so I would not know how to do that.

**Comment by quroom** [comment]
@estaar 
https://stackoverflow.com/questions/44505242/multiple-user-type-sign-up-with-django-allauth
Look mrnfrancesco's answer. not question.
It works well to me.
Just make your own form class for registration form from extending allauth SignupForm.

If you get argument error, maybe you use function not correctly.
Leave your full code and error log for backtrace.
It make easy to answer.

**Comment by pennersr** [comment]
Closing "How do I..." issue...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2824
