### ISSUE TITLE
Update i18n for ko.

### ISSUE THREAD

**Issue by quroom** [pennersr/django-allauth#2825]
[Translate code](https://github.com/pennersr/django-allauth/blob/353386216b79f16709e97bb487c0bbbba2bc0c71/allauth/locale/ko/LC_MESSAGES/django.po#L412) not works for confirm email.
And also some words are not translated in template codes.
eg. [Sign in](https://github.com/pennersr/django-allauth/blob/353386216b79f16709e97bb487c0bbbba2bc0c71/allauth/templates/account/base.html#L26)

I think it's better to support transalation fully in template code.
Does it make sense?

If it's ok, I will make PR ASAP.

**Comment by pennersr** [comment]
Feel free to file a PR with improvements to the translations.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2825
