### ISSUE TITLE
Django 3.2: multiple warnings

### ISSUE THREAD

**Issue by danjac** [pennersr/django-allauth#2826]
Django 3.2 (released today) generates a number of deprecation and other warnings, for example:

`HINT: Configure the DEFAULT_AUTO_FIELD setting or the AccountConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
`

`
RemovedInDjango41Warning: 'allauth.account' defines default_app_config = 'allauth.account.apps.AccountConfig'. Django now detects this configuration automatically. You can remove default_app_config.`

**Comment by djpeacher** [comment]
Looks like adding `DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'` to `settings.py` is a temp solution.

https://docs.djangoproject.com/en/3.2/releases/3.2/#customizing-type-of-auto-created-primary-keys

**Comment by Flimm** [comment]
The trouble with setting `DEFAULT_AUTO_FIELD` to `'django.db.models.BigAutoField'` in `settings.py` is this: when you run `python manage.py makemigrations`, a new migrations file will be created for allauth. If you're using a virtualenv that is not checked into version control, this is not ideal.

Instead, it is better to override `apps.py` in your application code, as explained in this answer: https://stackoverflow.com/a/67007098/247696

I recommend that `django-allauth` modify `apps.py` to avoid this warning. I'll be submitting a pull request soon.

**Comment by 9mido** [comment]
Great job @Flimm that was a perfect explanation and thanks for the PR.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2826
