### ISSUE TITLE
Paypal login

### ISSUE THREAD

**Issue by AAbouseada** [pennersr/django-allauth#2831]
Hey,

It seems that paypal has upgraded their login and allauth is out of date.
The get request should look like this:
https://www.sandbox.paypal.com/connect/?flowEntry=lg&client_id=REDACTED&response_type=code&scope=openid&redirect_uri=http%253A%252F%252F127.0.0.1%253A8000%252F&newUI=Y

Allauth:
https://www.sandbox.paypal.com/connect/?client_id=REDACTED&forwardFrom=idsw&redirect_uri=http%3A%2F%2F127.0.0.1%3A8000%2Faccounts%2Fpaypal%2Flogin%2Fcallback%2F&response_type=code&scope=openid&state=0GDS6fFJuOfL

If you have any quick fixes for this, it would be much appreciated!

**Comment by pennersr** [comment]
Closing, pull requests are welcome.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2831
