### ISSUE TITLE
No module named 'allauth.socialaccount.providers.Apple'

### ISSUE THREAD

**Issue by onshadeep** [pennersr/django-allauth#2832]
from allauth.socialaccount.providers.Apple.views import AppleOAuth2Adapter
ModuleNotFoundError: No module named 'allauth.socialaccount.providers.Apple'

**Comment by Andrew-Chen-Wang** [comment]
Lowercase Apple in `INSTALLED_APPS` to be `allauth.socialaccount.providers.apple`

**Comment by onshadeep** [comment]
@Andrew-Chen-Wang Yeah Thanks!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2832
