### ISSUE TITLE
Apple provider: Error retrieving access token

### ISSUE THREAD

**Issue by antoinelefebvre** [pennersr/django-allauth#2836]
We have been using the apple provider to implement "signin with apple" in our iOS app "Rehearsal Live Share" with success.

Last week, our iOS app was rejected because of an error with the "signin with apple". This is happening to the testers at apple only. We have been unable to reproduce the problem on our side.

I checked the django-allauth code and can't find what causes the problem.

The error returned by apple is the following:
{"error": "invalid_grant", "error_description":"The code has already been used"}

Any idea how to resolve this?

![attachment Screenshot-0417-080157](https://user-images.githubusercontent.com/1648635/115265512-4b969400-a105-11eb-91d6-8391bf998df1.png)

**Comment by antoinelefebvre** [comment]
Apparently, it was an issue on Apple side. We didn't change anything in our code and our app was now approved. We didn't get any explanations from Apple. Closing this.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2836
