### ISSUE TITLE
telegram provider

### ISSUE THREAD

**Issue by hypy13** [pennersr/django-allauth#2837]
the telegram provider link is empty with this code

{% provider_login_url 'telegram' %}

also i filled TOKEN value on settings.py
is there any other option that i missed?

**Comment by demoh2019** [comment]
https://github.com/pennersr/django-allauth/issues/2629#issuecomment-918332353

**Comment by pennersr** [comment]
Fixed via 89944bc2

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2837
