### ISSUE TITLE
[QUESTION] Possible to disable content type?

### ISSUE THREAD

**Issue by mecampbellsoup** [pennersr/django-allauth#2838]
We are using allauth as an AJAX/JSON API and would like to disable HTML responses. Is this possible/supported?

**Comment by pennersr** [comment]
Check the `is_ajax` method in the adapter, and turn it into:

```
    def is_ajax(self, request):
        return True
```

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2838
