### ISSUE TITLE
Does all auth supports django 3 or higher?

### ISSUE THREAD

**Issue by EgorEna** [pennersr/django-allauth#2839]
Hi, I'm not very familiar with your library. All went good when I start project with Django 2 (no higher).
But in django 3 it causes such issue:
`ImportError: cannot import name 'python_2_unicode_compatible' from 'django.utils.encoding' (/home/user/PycharmProjects/armenta-admin/venv/lib/python3.8/site-packages/django/utils/encoding.py)`

So does it support django 3.0 or higher? I will be so greatefull if you help me, thanks!

**Comment by EgorEna** [comment]
> It does support django 3 and higher. You probably need to use python 3 though.
> 
> Did you try this? https://stackoverflow.com/questions/20741754/python-2-unicode-compatible-error
> 
> Try searching your error on your search engine of choice and see what you can learn. Report back if you solved it and provide the solution in this thread so that it can help others.

Sorry I missed one thing about it. All works well, but thank you for your reply!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2839
