### ISSUE TITLE
Is Google scope for Youtube DataAPI supported?

### ISSUE THREAD

**Issue by mhoonjeon** [pennersr/django-allauth#2846]
```python
# settings.py
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        # For each OAuth based provider, either add a ``SocialApp``
        # (``socialaccount`` app) containing the required client
        # credentials, or list them here:
        "APP": {
            "client_id": env("SOCIAL_AUTH_GOOGLE_OAUTH2_KEY"),
            "secret": env("SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET"),
        },
        "SCOPE": [
            "profile",
            "email",
            "https://www.googleapis.com/auth/youtube",
            # or "youtube", "profile", "email"? - but it's not working too
        ],
    }
}
```

I tried with the above settings to include Youtube DataAPI to my app's scope as described [here in the doc](https://django-allauth.readthedocs.io/en/latest/advanced.html?highlight=scope#changing-provider-scopes), but it keeps returning access_tokens without the right permission to access Youtube DataAPI. Is this even supported?

[Python-social-core supports](https://python-social-auth.readthedocs.io/en/latest/backends/google.html) this with the below settings(I have tested it). By the way the `email` and `profile` scopes work, but it seems the youtube-related scope gets ignored.
```python
SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = [
    "email",
    "profile",
    "https://www.googleapis.com/auth/youtube",
]

```

I was trying to migrate to django-allauth+dj_rest_auth from python-social-core but if this is not supported, I have to go back :(
Any ideas?
Thanks.

**Comment by mhoonjeon** [comment]
Closing as our client dev passed on the scope params and it worked fine.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2846
