### ISSUE TITLE
Multiple ACCOUNT_ADAPTER values

### ISSUE THREAD

**Issue by 9mido** [pennersr/django-allauth#2847]
There does not seem to be a way to do something like:

`ACCOUNT_ADAPTER = ["app1.adapter.adapter_class_1",  "app1.adapter.adapter_class_2", "app2.adapter.adapter_class_1",  "app2.adapter.adapter_class_2",   ]`

Where you could add as many adapters from any number of apps as you want. 
`ACCOUNT_ADAPTER` seems limited to just 1 value. 

An AssertionError was returned when trying to add more than 1 value to `ACCOUNT_ADAPTER`.

**Comment by pennersr** [comment]
That's correct and intentional.

**Comment by 9mido** [comment]
Why limit to just 1 adapter and not multiple? I could see many use cases for having multiple adapters.

**Comment by pennersr** [comment]
Many projects have their own app dealing with project specific account related functionality (e.g. `my_prj.accounts`) and that would be a good place for the adapter class as well. Typically, you do not want to spread account related knowledge across various apps anyway... so I don't see those use cases.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2847
