### ISSUE TITLE
Help With Documentation!

### ISSUE THREAD

**Issue by Rowlando13** [pennersr/django-allauth#2848]
Django-allauth is an awesome package, but I think we can all agree that the documentation needs some help. I really would like to use it over python-social because it is updated more regularly, but I am hestitant to use something for authentication that I don't really understand. 

I am willing to help out. I am an intermediate python developer, but very new to django. If someone is willing to help me understand the code base / verify that what I write up is actually correct, then I am willing to write up some documentation. 

I think the first candidate is the intended way to use your own templates. As you can see from the threads, there seems to be some dated general guidance but nothing super specific.  

The tribal knowledge is in the following links: 
https://stackoverflow.com/questions/39009638/how-to-edit-django-allauth-default-templates 
https://stackoverflow.com/questions/18791136/how-to-override-template-in-django-allauth
https://stackoverflow.com/questions/16817157/django-allauth-configuration-doubts
https://stackoverflow.com/questions/9437545/overriding-default-templates-of-django-allauth

Based on what I have seen in the links and a little expiramentation: 

Django-allauth expects templates to be in yourproject/yourproject/templates/allauth or yourproject/yourapp/templates/allauth. As long as your specificy the locations in your yourproject/yourproject/settings.py then you are okay.

For the structure of templates, Django-allauth expects as below. Thus to override any template, simply place it in the templates folder its expected spot. If nothing is present and the corresponding view is called, then it will render the Django-allauth template. 

![django_allauth_structure](https://user-images.githubusercontent.com/67291205/116775582-8d361180-aa18-11eb-9575-d0e85708421f.png)

This is an absolutely enormous structure. That is great. It means a lot is built in, but certain sections are indicative of a specific path the user takes be processed. What is the default path? 

I currently don't understand the purpose of each template and whether the URL is available regardless of if I have a link to anywhere on my website. For example, if someone knows the correct URL, can they get to signup_closed.html via the corresponding view because it is still active? 

I would like to know the default user flow with its corresponding branches, and if this can be configured all once or different things are controlled by individual environment variables as in ACCOUNT_EMAIL_VERIFICATION.

Active maintainer please respond with whether you are interested in my help. 
    If yes, then send me a dm on my twitter @rowlando_13 so that so we can setup a chat and go from there. 
    If no, consider taking the time to write this up. I am grateful for the open source work that you have done. However, large holes in the documentation for something as sensitive as authentication significantly undercut the hard work you have done so far. Please consider making what corrections are necessary and adding it to the documentation.

**Comment by Andrew-Chen-Wang** [comment]
I'm not a maintainer, but an avid Django lover. I learned Django (and code) by seeing how others have been implementing this. I think the docs are ok, but I agree they aren't very beginner friendly, so **I agree that can be fixed** to be more beginner friendly. I'm also not gonna answer some of those questions (sorry) since I don't have time to write much up. In the meantime, take a look at [cokoiecutter-django](https://github.com/pydanny/cookiecutter-django) if you need any help/inspiration for how to work with allauth.

**Comment by Rowlando13** [comment]
The templates structure above should not have the allauth directory in the structure. Account, socialaccount, and openid should be directly in templates.

**Comment by pennersr** [comment]
While I appreciate the initiative to improve the documentation, I am unable to free up sufficient time to help you find your way.  Any pull request to improve the documentation is welcome, but keeping this ticket open is not going to improve things...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2848
