### ISSUE TITLE
Twitter TypeError at /accounts/twitter/login/

### ISSUE THREAD

**Issue by eyalis** [pennersr/django-allauth#2850]
Hi, many social networks (github, facebook) are working for me fine, but I'm having problems with Twitter, I've tried everything but I keep getting this error when trying to log in (I already checked many times my API keys):

Request Method: | GET
-- | --
http://127.0.0.1:8000/accounts/twitter/login/?process=login
3.1.7
TypeError
startswith first arg must be bytes or a tuple of bytes, not str
C:\Users\Usuario\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py, line 738, in get_adapter
C:\Users\Usuario\AppData\Local\Programs\Python\Python39\python.exe
3.9.2
['C:\\Users\\Usuario\\Downloads\\django-allauth-master\\django-allauth-master\\example',  'C:\\Users\\Usuario\\AppData\\Local\\Programs\\Python\\Python39\\python39.zip',  'C:\\Users\\Usuario\\AppData\\Local\\Programs\\Python\\Python39\\DLLs',  'C:\\Users\\Usuario\\AppData\\Local\\Programs\\Python\\Python39\\lib',  'C:\\Users\\Usuario\\AppData\\Local\\Programs\\Python\\Python39',  'C:\\Users\\Usuario\\AppData\\Roaming\\Python\\Python39\\site-packages',  'C:\\Users\\Usuario\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages']

I have no idea how can I fix this.

**Comment by pennersr** [comment]
Sorry, not sure what is going on. I'll have to close this, it does not clearly pinpoint an issue in allauth.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2850
