### ISSUE TITLE
Move tests out of package and convert to pytest

### ISSUE THREAD

**Issue by Andrew-Chen-Wang** [pennersr/django-allauth#2851]
I would like to help implement #345. Just in the meantime, I'd like to convert this to pytest and move the tests.py files out of the package and in a dedicated folder at root dir. To me, moving the tests out and splitting tests into files decreases package size (just that little bit ofc) but also it's just easier to read by file names what I'm looking for rather than a huge test file.

**Comment by pennersr** [comment]
Closing due to lack of traction.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2851
