### ISSUE TITLE
AssertionError at /accounts/login/ No exception message supplied

### ISSUE THREAD

**Issue by philip-kio** [pennersr/django-allauth#2855]
I am currently reading Djagno For Professionals, and I was to set up permissions to restrict public use I realized I had issues with login. 
Prior to this issue, it worked fine. I removed the permissions mixin and it still showed the same error. This is the first time I am encountering this hence I don't know how to resolve this, I have gone through the chapters that dealt with that section again. 

Ironically all other things such as Sign up, log out all work except login. 
I used docker so I could not locate the source code to look closely at line 127 specified in the debug prompt.

No exception message supplied was around the area where one can look at hints as to why there is an error.
`

Request Method: | GET
-- | --
http://127.0.0.1:8000/accounts/login/
3.2.1
AssertionError
/usr/local/lib/python3.8/site-packages/allauth/account/forms.py, line 127, in __init__
/usr/local/bin/python
3.8.7
['/code',  '/usr/local/lib/python38.zip',  '/usr/local/lib/python3.8',  '/usr/local/lib/python3.8/lib-dynload',  '/usr/local/lib/python3.8/site-packages']
Wed, 05 May 2021 16:00:35 +0000
`

**Comment by philip-kio** [comment]
I have seen my error, thank you. The error was setting up my ACCOUNT_AUTHENTICATION_METHOD wrongly. I did 
`ACCOUNT_AUTHENTICATION_METHOD = 'e_mail'`
rather than
`
ACCOUNT_AUTHENTICATION_METHOD = 'email'
`

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2855
