### ISSUE TITLE
send email confirmation in HTML

### ISSUE THREAD

**Issue by juanremi** [pennersr/django-allauth#2856]
hi,

I ​put the txt and html templates in the specified folder 
https://django-allauth.readthedocs.io/en/latest/advanced.html#sending-email

but when a new user is registered, the user receives the email in text plain mode and not using the html template

im using the django-allauth v0.44

any idea?

**Comment by juanremi** [comment]
the error was i named the html
email_confirmation_message.html

and this should be 
email_confirmation_signup_message.html

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2856
