### ISSUE TITLE
Field defines a relation with the model 'auth.User', which has been swapped out.

### ISSUE THREAD

**Issue by ashmlk** [pennersr/django-allauth#2860]
Hello everyone, after creating my custom user model and adding allauth to list of installed apps I get the following error after running `migrate`

```
account.EmailAddress.user: (fields.E301) Field defines a relation with the model 'auth.User', which has been swapped out.
        HINT: Update the relation to point at 'settings.AUTH_USER_MODEL'.
socialaccount.SocialAccount.user: (fields.E301) Field defines a relation with the model 'auth.User', which has been swapped out.
        HINT: Update the relation to point at 'settings.AUTH_USER_MODEL'.
```

I have already deleted the migrations multiple times and deleted the database again and I still get that error.

My custom user model is:

```
class User(AbstractUser):
    
    def save(self, *args, **kwargs):
        self.username = self.username.strip().lower()
        super(User, self).save(*args, **kwargs)
    
    def __str__(self):
        return self.username

```

And I have already set `AUTH_USER_MODEL` in my settings. I am using Django 3.2

**Comment by Usouf** [comment]
Did you have any users registered before creating the migration?

**Comment by 9mido** [comment]
Yea sounds like you should have deleted the migration files, cache files, __init__ files then apply your migration. If you have leftover data from before the custom user model then migrate to the custom user model there will be problems like this.

**Comment by pennersr** [comment]
Closing -- not an issue in allauth

**Comment by Rahul3996** [comment]
Does anyone have other solution

**Comment by rakibulislam8226** [comment]
take a deep look at the error. after changing the auth user models you still didn't change in account.EmailAddress.user and socialaccount.SocialAccount.user where you previously used the auth.user model. so I believe if you change it there, this will be solved.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2860
