### ISSUE TITLE
Bug or feature?: Auto login after registration does not while using a different browser

### ISSUE THREAD

**Issue by sowinski** [pennersr/django-allauth#2862]
Hi,

if I do the registration process with the same browser, everything works fine:
1) sign up
2) click on link in email
3) click on accept email in the website
4) => user is logged in#

but if I click on the link on the email and the page is opened with a different browser then I see the login page after step 3).

Not sure if this is a bug or security related feature?

If this is not a bug. How can I change this behavior?

**Comment by sowinski** [comment]
I have set:
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True

**Comment by pennersr** [comment]
This is by design, not a bug. Explained here: https://github.com/pennersr/django-allauth/blob/master/allauth/account/views.py#L337

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2862
