### ISSUE TITLE
How to check when to serve PasswordChange vs. PasswordReset view?

### ISSUE THREAD

**Issue by mecampbellsoup** [pennersr/django-allauth#2866]
In our app users will sign up via manual (email/password) as well as social provider (e.g. Github) flows.

Upon signing up via social provider and attempting to change the user password, the response seems to _always_ be:

```
[('Please type your current password.', ['oldpassword'])]
```
I believe this is because `user.check_password` always fails (as is expected for social signups).

However, the response is identical for manual signups which mistype or otherwise incorrectly input their "current password".

Is there a way to tell which view should be used - `PasswordChange` or `PasswordSet` - for a particular user?

I'm using allauth as an isolated backend dependency within an ASGI application, so I cannot use e.g. `user.has_usable_password()` unless I write a custom Django view and first request that in my GraphQL mutation or something...

**Comment by pennersr** [comment]
Check the PasswordChangeView implementation. If you end up there without having a password set, it redirects to the PasswordSetView:

```
       if not self.request.user.has_usable_password():
            return HttpResponseRedirect(reverse("account_set_password"))
 ```

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2866
