### ISSUE TITLE
Logged in users could access another user's password reset link to reset their password & could access /accounts/password/reset/

### ISSUE THREAD

**Issue by 9mido** [pennersr/django-allauth#2867]
a@a.com requests a password reset
b@b.com who is logged in tries to access a@a.com's password reset link, and is able to do so and change a@a.com's password
a@a.com's password is changed and they are locked out of their account

But anyone who is logged out can do anything they want as long as they have the password reset link. 

Another thing that happens is a logged in user could access /accounts/password/reset/. There is no need to do this if they are already logged in.

**Comment by jberends** [comment]
why would this be any different than any other password reset link on the planet? This is a default security problem of interception of a password reset link as far as I am aware. 

Some options to harden it

- record IP address from requestee and see if same IP tries to reset pw
- place HTTP cookie on requestee browser and validate if pw is changed in same browser

**Comment by 9mido** [comment]
To prevent logged in users from accessing the password reset page, do the following in class PasswordResetView def get_context_data function:

```
        if self.request.user.is_authenticated:
            raise Http404()
```

**Comment by pennersr** [comment]
If user B has access to user A's inbox, and hence, obtains the password reset link for user A, then all security is lost. Whether or not the password reset view is accessible has nothing to do with does, and trying to hide it does not solve a security issue.

**Comment by jberends** [comment]
Yup. All is lost indeed.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2867
