### ISSUE TITLE
Django AllAuth Facebook: Cant login: Social Network Login Failure An error occurred while attempting to login via your social network account

### ISSUE THREAD

**Issue by ScarletMcLearn** [pennersr/django-allauth#2869]
Please answer this query:

Django AllAuth Facebook: Cant login: Social Network Login Failure An error occurred while attempting to login via your social network account

Details in link below:
https://stackoverflow.com/questions/67704098/django-allauth-facebook-cant-login-social-network-login-failure-an-error-occur

Thank you.

**Comment by pennersr** [comment]
https://django-allauth.readthedocs.io/en/latest/faq.html#why-did-you-just-close-my-issue

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2869
