### ISSUE TITLE
Store arbitrary data before social OAuth flow and use it in `pre_social_login`

### ISSUE THREAD

**Issue by mecampbellsoup** [pennersr/django-allauth#2871]
Hi @pennersr -

I have spent a number of hours now and closely read [this related issue](https://github.com/pennersr/django-allauth/issues/1026) but cannot figure out how to:

1. Add some arbitrary state data to be stored server-side to the social login url e.g. `/accounts/github/login/?state=foo` (I also tried `/accounts/github/login/?auth_params=foo`)
2. Reference that data in [`pre_social_login`](https://github.com/pennersr/django-allauth/blob/80e07a25803baea4e603251254c7d07ef2ad5bb5/allauth/socialaccount/adapter.py#L35) where I will do some custom logic before moving forward with signup.

Specifically we are requiring new signups to have a valid code (i.e. we maintain a signup whitelist). Since I cannot be sure if the user is existing (and just logging in again) or does not exist (and thus signing up) I need to check after the OAuth flow takes place and I have obtained their email identifier before I can run my "has valid signup token" logic.

No matter what I include in the GitHub login URL I cannot seem to get anything stored server-side.

Could you please advise when you have a chance?

**Comment by pennersr** [comment]
Sorry, I have to close this as it does not clear indicate an issue in allauth.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2871
