### ISSUE TITLE
Slack SocialAccount Error bad_redirect_uri

### ISSUE THREAD

**Issue by ManuelBuri** [pennersr/django-allauth#2878]
Hi I am getting the following response as a callback from my call to the slack API:

`Code: unknown, Error: Error retrieving access token: b'{"ok":false,"error":"bad_redirect_uri"}'`

I have specified the redirect_uri in my call and it matches the entry in the slack app settings.

Any idea on how to solve/debug this?

**Comment by pennersr** [comment]
Dupe of #2879

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2878
