### ISSUE TITLE
Facebook Social Login Provider ignores LOCALE language settings from settings dictionary

### ISSUE THREAD

**Issue by RuchitMicro** [pennersr/django-allauth#2880]
```
# Provider specific settings
SOCIALACCOUNT_PROVIDERS = {
    'facebook': {
        'METHOD': 'oauth2',
        'SDK_URL': '//connect.facebook.net/{locale}/sdk.js',
        'SCOPE': ['email', 'public_profile','ads_management'],
        'AUTH_PARAMS': {},
        'INIT_PARAMS': {'cookie': False},
        'FIELDS': [
            'id',
            'first_name',
            'last_name',
            'middle_name',
            'name',
            'name_format',
            'picture',
            'short_name',
        ],
        'EXCHANGE_TOKEN': True,
        'VERIFIED_EMAIL': False,
        'LOCALE_FUNC': lambda request: 'en_US',
        'VERSION': 'v10.0',
        'APP': {
            'client_id': '*******************',  # !!! THIS App ID
            'secret': '****************************',  # !!! THIS App Secret
            'key': ''
        }
    }
}

SOCIALACCOUNT_ADAPTER                   = "project.mysocialaccountadapter.MySocialAccountAdapter"
SOCIALACCOUNT_STORE_TOKENS              = True
ACCOUNT_AUTHENTICATED_LOGIN_REDIRECTS   = False
```

These are my provider settings where I have a callback function in LOCALE_FUNC returning en_US but when I login to facebook this language setting is ignored and local language is selected

**Comment by derek-adair** [comment]
Bumping this... sorry I can't provide more input but this seems valid if its still true / not already fixed.  Very unlikely to be a facebook issue.

**Comment by shehab1994sh** [comment]
> ```
> # Provider specific settings
> SOCIALACCOUNT_PROVIDERS = {
>     'facebook': {
>         'METHOD': 'oauth2',
>         'SDK_URL': '//connect.facebook.net/{locale}/sdk.js',
>         'SCOPE': ['email', 'public_profile','ads_management'],
>         'AUTH_PARAMS': {},
>         'INIT_PARAMS': {'cookie': False},
>         'FIELDS': [
>             'id',
>             'first_name',
>             'last_name',
>             'middle_name',
>             'name',
>             'name_format',
>             'picture',
>             'short_name',
>         ],
>         'EXCHANGE_TOKEN': True,
>         'VERIFIED_EMAIL': False,
>         'LOCALE_FUNC': lambda request: 'en_US',
>         'VERSION': 'v10.0',
>         'APP': {
>             'client_id': '*******************',  # !!! THIS App ID
>             'secret': '****************************',  # !!! THIS App Secret
>             'key': ''
>         }
>     }
> }
> 
> SOCIALACCOUNT_ADAPTER                   = "project.mysocialaccountadapter.MySocialAccountAdapter"
> SOCIALACCOUNT_STORE_TOKENS              = True
> ACCOUNT_AUTHENTICATED_LOGIN_REDIRECTS   = False
> ```
> 
> هذه هي إعدادات الموفر الخاصة بي حيث لدي وظيفة رد الاتصال في LOCALE_FUNC والتي تعود بـ en_US ولكن عندما أقوم بتسجيل الدخول إلى facebook، يتم تجاهل إعداد اللغة هذا ويتم تحديد اللغة المحلية

**Comment by shehab1994sh** [comment]
اريد فتح الفيس بوك ولا استطيع

**Comment by pennersr** [comment]
Moved to https://codeberg.org/allauth/django-allauth/issues/2880
