### ISSUE TITLE
Keycloak provider - setting for alternative URL

### ISSUE THREAD

**Issue by AlexGacon** [pennersr/django-allauth#2883]
Hi,

I am trying to setup a keycloak provider with GeoNode in a docker compose environment and I have an issue with the KEYCLOAK_URL setting : it is used on one side to ask credentials to the user from the frontend and on the other side to retrieve tokens and information from the backend.

For the frontend, I need a URL the browser can understand and for the backend I need a URL compatible with the docker network.

With the current implementation, it is not possible to setup this : I have modified the implementation of the keycloak provider to be able to give another setting for the backend requests.

Should I create a PR to share it ?

**Comment by WernerRaath** [comment]
Also busy with Keycloak and GeoNode integration on my side.

Okay so you've got all of your services in one `docker-compose.yml` file and you want your `KEYCLOAK_URL` parameter to cater for a Docker to Docker host name as well as a DNS defined host name (or localhost).

What is your use case that you need to your the Docker to Docker connection? Is it because of a dynamic IP? Or maybe because you're using localhost and for internal connections localhost doesn't work, but for the UI it does?

**Comment by AlexGacon** [comment]
Hi,

Indeed I am using localhost for now so the login form needs to be exposed by GeoNode with the localhost pattern but for the other calls (profile url and access token url) I need to have the docker connection name, since the calls are done by GeoNode itself.

**Comment by WernerRaath** [comment]
I would suggest using your IP address instead. Thus you only need one URL for both cases, since your Browser and the Docker service can access your IP with no problem

**Comment by AlexGacon** [comment]
Very good suggestion, indeed. It works perfectly and solved other problems I got until now.

**Comment by WernerRaath** [comment]
But yes this could be an enhancement, especially if one's local IP changes often - you don't want to have to change the value every time you connect to a new network.

**Comment by derek-adair** [comment]
Not sure about this one... probably close as a support question?? Not positive this is an issue w/ allauth.

>For the frontend, I need a URL the browser can understand and for the backend I need a URL compatible with the docker network.

Leads me to believe this is a config issue.  I have no clue what these services do so this may be valid.

**Comment by pennersr** [comment]
Closing -- the Keycloak provider has been removed.

**Comment by browser-bug** [comment]
Sorry to reopen this but I'm facing the exact same problem with the current version using openid_connect. 
I didn't find a solution to make Allauth use the internal docker hostname of the service while both using a browser compatible Keycloak hostname for the landing pages etc. With this mismatch the only thing I get is this screen without any logs or exceptions I could find.

<img width="651" height="301" alt="Image" src="https://github.com/user-attachments/assets/56dbbb70-c08a-4dc6-9776-e3f21996a7ff" />

Of course using the machine IP (which changes over time tho) or an external service like Ngrok works, but I don't see it as a real solution.
Is there a configuration that could work this out?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2883
