### ISSUE TITLE
When Sign in with Slack, see "Social Network Login Failure"

### ISSUE THREAD

**Issue by ftnext** [pennersr/django-allauth#2884]
## Describe the bug
I've tried Sign in with Slack, then I encountered "Social Network Login Failure."

<img width="638" alt="3-failure" src="https://user-images.githubusercontent.com/21273221/121564583-94f4c700-ca56-11eb-98ea-d2bab516628a.png">

## Rough procedure

(I'm developing Django app in private repository, so it is difficult right now to share exactly the same procedure.)

1. Create Slack App
2. Set up Django project (like https://github.com/ftnext/practice-django-allauth)
3. `python manage.py runsslserver` with https://github.com/teddziuba/django-sslserver
4. Go https://127.0.0.1:8000/

Click Slack login link:
<img width="427" alt="1-slack-login" src="https://user-images.githubusercontent.com/21273221/121564866-db4a2600-ca56-11eb-92f9-41f7d22b99c9.png">

Click Green button (許可する means permit)
<img width="592" alt="2-oauth" src="https://user-images.githubusercontent.com/21273221/121565062-12203c00-ca57-11eb-8bf7-133aeb7a863f.png">

then "Social Network Login Failure" (the first screenshot).

## Expected behavior

Success to login

## Environment

- macOS
- Python 3.9.4
- Django 3.2.4
- django-allauth 0.44.0

## Workaround

Edit `SlackOAuth2Adapter` in allauth/socialaccount/providers/slack/views.py

```python
    def get_data(self, token):
        # Verify the user first
        # resp = requests.get(self.identity_url, params={"token": token})
        resp = requests.get(self.identity_url, headers={"Authorization": f"Bearer {token}"})
        resp = resp.json()
        
        # omitted
```

### Error cause

```python
resp = requests.get(self.identity_url, params={"token": token})
print(resp.json())  # {'ok': False, 'error': 'invalid_auth'}

# OAuth2Error is raised
```

### Documents
I saw 2 documents:

1. https://api.slack.com/methods/users.identity (the `identity_url`)

> Tokens should be passed as an HTTP Authorization header ...

2. https://api.slack.com/docs/sign-in-with-slack#sign-in-with-slack__details__using-tokens-to-retrieve-user-and-team-information

```
GET https://slack.com/api/users.identity
Authorization: Bearer xoxp-1111827393-16111519414-20367011469-5f89a31i07
```

I thought the token needs to be set at the Authorization header, and it works 🙌

**Comment by ftnext** [comment]
This bug was fixed at https://github.com/pennersr/django-allauth/commit/53c543432c3c2c97812ba168118f69d198c3e8a5#diff-21b664182f4ff836a31f484e97fa60689adf5e32e4a9a535d5a599e11e95027f
Thanks!

The solution is `pip install git+https://github.com/pennersr/django-allauth` (not install from PyPI)

**Comment by a14d** [comment]
Sadly, his is still not working, is there any workaround or something ?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2884
