### ISSUE TITLE
Automatic build by travis-ci

### ISSUE THREAD

**Issue by AlexGacon** [pennersr/django-allauth#2888]
As stated on travis-ci.org:

Since June 15th, 2021, the building on travis-ci.org is ceased. Please use travis-ci.com from now on.

Could you please migrate to travis-ci.com to repair automatic building?

**Comment by pennersr** [comment]
Travis has been dropped.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2888
