### ISSUE TITLE
Example of custom form with save method?

### ISSUE THREAD

**Issue by PchopL** [pennersr/django-allauth#289]
I am new to Django and have implemented Allauth on a local dev project. It has saved me a ton of time, so thank you. I have it authenticating properly using the out-of-the-box fields. I got stuck in attempting to implement the ACCOUNT_SIGNUP_FORM_CLASS with a couple of extra fields needed for my app.

Could you provide an example of a form class with a save() method implemented, as mentioned in the docs?

Is it something like this? I'm getting hung up on how to pass a user object into a Django form class. (Pardon my Django/Python noobness)

```
# in myapp/forms.py

class ProfileForm(forms.Form):
    custom_field = forms.CharField(max_length=30,required=True)

    # Do I need a def here?
    u = Foo.objects.get(pk=bar) #what do I need to import for this?
    f = ProfileForm(instance=u)
    f.save()
```

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/289
