### ISSUE TITLE
Allowing specyfing a token parameter displayed in password reset URLs.

### ISSUE THREAD

**Issue by DmytroLitvinov** [pennersr/django-allauth#2892]
### Allow customizing PasswordResetConfirmView's INTERNAL_RESET_URL_TOKEN

I propose to update [PasswordResetFromKeyView](https://github.com/pennersr/django-allauth/blob/c50a30acc0e4553297b0ddb697d55a290ed6d038/allauth/account/views.py#L715) according to [Django ticket](https://code.djangoproject.com/ticket/28780) with [related PR to it](https://github.com/django/django/commit/58df8aa40fe88f753ba79e091a52f236246260b3).

Also, for me it was important to extend `PasswordResetFromKeyView` view and I found out that it uses internally in dispatch method [self.request.path.replace()](https://github.com/pennersr/django-allauth/blob/c50a30acc0e4553297b0ddb697d55a290ed6d038/allauth/account/views.py#L759) instead of `self.request.get_full_path()` for keeping my query string in URL after redirecting for hiding key in session.

**Comment by DmytroLitvinov** [comment]
Hi @pennersr ,
Sure, I can. I will ping you when it will be ready.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2892
