### ISSUE TITLE
Will you push the new updates to PyPi soon?

### ISSUE THREAD

**Issue by shuki25** [pennersr/django-allauth#2893]
I'm trying to set up a docker image for my django app using allauth with my contribution to your source tree.  At this time it is still pulling previous version and I'm unable to use the frontier plug-in in the docker image. How soon will you push the current master branch to PyPI?  I see your last update (v0.44) push was back in November 2020. It would be great if you could make another push with new OAuth providers and other bug fixes.

Thanks!

**Comment by derek-adair** [comment]
If you need a release and cannot wait you may consider forking and releasing on pypi yourself, its pretty straight forward with something like [twine](https://pypi.org/project/twine/).  You can even release it privately with something like [s3pypi](https://www.novemberfive.co/blog/opensource-pypi-package-repository-tutorial).

**Comment by 9mido** [comment]
In the meantime before a new PyPi release, you can do this:

In your requirements.txt make sure you include this:

`git+https://github.com/pennersr/django-allauth`

Then run `pip3 install -r requirements.txt`

Or separately without a requirements.txt file run this:

`pip3 install git+https://github.com/pennersr/django-allauth`

**Comment by pennersr** [comment]
0.45 is released

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2893
