### ISSUE TITLE
Schoology Provider

### ISSUE THREAD

**Issue by jwizenfeld04** [pennersr/django-allauth#2894]
Can you add schoology as one of the providers for the social accounts in allauth. Here is their api documentation: https://developers.schoology.com/api

**Comment by jwizenfeld04** [comment]
I've tried to create my own modelling another provider using OAuth1 but it doesn't seem to work. I'm getting the following error message: {'provider': 'schoology', 'code': 'unknown', 'exception': OAuthError('Invalid response while obtaining request token from "api.schoology.com".')}. I checked and it was a 405 error.

**Comment by pennersr** [comment]
Feel free to submit a PR. Closing -- keeping this ticket open is not going to solve the issue.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2894
