### ISSUE TITLE
email_changed signal should be sent when changing a primary email using EmailAddress.change

### ISSUE THREAD

**Issue by prakhar1144** [pennersr/django-allauth#2897]
When changing an email using `EmailAddress.change()`
https://github.com/pennersr/django-allauth/blob/c50a30acc0e4553297b0ddb697d55a290ed6d038/allauth/account/models.py#L65

There should be a condition as follows:
 If the email being changed is a `primary email` then `email_changed` signal should be sent.
As of now it doesn't happens.

**Comment by pennersr** [comment]
That `change()` method is actually dead code and not used by allauth at al. It should be removed altogether.

**Comment by arthtyagi** [comment]
I think `add_email` should be used for any use-case stemming from your need to use `change` method @prakhar1144

**Comment by pennersr** [comment]
The `change()` method is no longer present.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2897
