### ISSUE TITLE
Users have no social token using Twitch as provider

### ISSUE THREAD

**Issue by HosseinMirjalali** [pennersr/django-allauth#2898]
So I've been developing this service that interacts with Twitch API and the authentication process has no issues, however, when I get to making requests to Twitch API that require [user access Token](https://dev.twitch.tv/docs/authentication#types-of-tokens), I don't seem to be able to find a way to do that. There is no user OAuth token in SocialToken model, and there is no way to populate it, apparently. 
Looking at [this issue](https://github.com/pennersr/django-allauth/issues/122#issue-7124838), it seems like there has to be a token associated to the user in the SocialToken model database, but there is none in my case. 
Not sure whether this is a bug or I simply can't understand how it actually works and I'm missing something.

Edit: 
Django-Allauth version: 0.44.0
Django version: 3.1.12
Python: 3.9

SOCIALACCOUNT_STORE_TOKENS is set to True

**Comment by HosseinMirjalali** [comment]
Okay so tokens are not stored when you set Twitch keys in your env/settings.py, but if you store them in django admin panel, user's tokens will be stored.
However, refresh token is basically useless since the logic to actually refresh the access token is not implemented, but that's for another issue.

**Comment by kweku-45** [comment]
@HosseinMirjalali where did you get the information about tokens not stored in the database when you store them in `settings.py`?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2898
