### ISSUE TITLE
The signup form does not render properly when included in the login template

### ISSUE THREAD

**Issue by sachingupta006** [pennersr/django-allauth#29]
The current template structure that has been given, has a separate page for all the login signin and signup processes. But I wanted to keep the signup form via username/password in the same template as the login template. So instead of just giving a link to the signup form, I copied the whole form in login template.

However the problem with this is that the signup form is not being rendered correctly. It does not have the confirm password and email field even though I have set it in the settings file. However when I visit the signup template from the url, then I see the correct form.

It must be since the settings are checked in the signup view and when I visit login template I do not go through the signup view, isn't there a way that I could combine the two.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/29
