### ISSUE TITLE
Uninstall Django-allauth

### ISSUE THREAD

**Issue by akrish4** [pennersr/django-allauth#2901]
Hi there

I am using windows 10 , 
How can we uninstall django-allauth in windows 64 bit machine , pls let me know.

Thanks

**Comment by 9mido** [comment]
Not sure about how Windows does things but normally you would do:

pip uninstall django-allauth
Remove django-allauth from INSTALLED_APPS
Remove associated code in settings.py, views, forms, etc with django-allauth code and django-allauth settings.

If you want to delete the django-allauth database tables and the associated data within it, try this:

https://patrick.cloke.us/posts/2020/01/23/cleanly-removing-a-django-app-with-models/

There is a specific folder on your system that stores all of your pip apps like django-allauth. Try installing something with pip and the output of pip should tell you what path on your system that installed pip app was stored in. If pip uninstall django-allauth does not work, you will have to manually delete the django-allauth code located in your system's path where all of the pip apps are stored.

https://stackoverflow.com/questions/29980798/where-does-pip-install-its-packages

The location for the pip apps also depends on what type of virtual environment you are using. Each virtual environment has a different way of doing things such as where it decides to place pip apps.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2901
