### ISSUE TITLE
Receive confirm  Email   on my email address

### ISSUE THREAD

**Issue by AREEG94FAHAD** [pennersr/django-allauth#2902]
How can a user get a confirmation email on their email address after registration? 
it shows me on the console I want to receive it using an email address

**Comment by raunaqss** [comment]
Change your email backend to `SMTP`. Not an appropriate question for this issue board.

**Comment by pennersr** [comment]
https://docs.djangoproject.com/en/3.2/ref/settings/#std:setting-EMAIL_BACKEND

**Comment by AREEG94FAHAD** [comment]
It worked after removed 
 `# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'`

from settings.py

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2902
