### ISSUE TITLE
Spotify listed as a provider in documentation but not information about setting it up is written in the documentation.

### ISSUE THREAD

**Issue by kweku-45** [pennersr/django-allauth#2906]
You must add a SocialApp record per provider via the Django admin containing these app credentials but then it does not show to setup for Spotify. 
![Screenshot (282)](https://user-images.githubusercontent.com/71296367/126063745-fb8e795a-a0fa-4581-93ff-3b0225e798c7.png)

Any help? Or does it's setup follow one of the listed providers?

**Comment by kweku-45** [comment]
I followed the docs and got it running. 

Added the following to my `settings.py`

`INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.sites',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Sparison',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.spotify',
]

SITE_ID=1

SOCIALACCOUNT_PROVIDERS = {
    "spotify": {
        "APP": {
            "client_id": os.environ.get("SPOTIPY_CLIENT_ID"),
            "secret": os.environ.get("SPOTIPY_CLIENT_SECRET")
        },
}}
`
where `SPOTIPY_CLIENT_ID` is my Spotify client ID and `SPOTIPY_CLIENT_SECRET` is my Spotify client secret. Added these in admin as well.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2906
