### ISSUE TITLE
Unable to use Salesforce as auth provider

### ISSUE THREAD

**Issue by snorrehu** [pennersr/django-allauth#2908]
Hi,

I'm getting "No_Oauth_State: State was not valid" from Salesforce when logging into my Django application using Allauth. **I think** I have it all setup correctly. Upon logging in my app returns a redirect to:

https://my.sf.domain/services/authcallback/salesforce/services/oauth2/authorize?client_id={super_secret}&redirect_uri=http://my.django.app.domain/accounts/salesforce/login/callback/&scope=id+openid&response_type=code&state={a_random_string_of_length_12} 

.. after which Salesforce redirects me to:
https://my.sf.domain/_nc_external/identity/sso/ui/AuthorizationError?ErrorCode=No_Oauth_State&ErrorDescription=State+was+not+valid&ProviderId={auth_provider_id}

What am I missing here? Why does Salesforce see the state as invalid?

([Link](https://stackoverflow.com/questions/68405984/django-allauth-and-salesforce-no-oauth-state-state-was-not-valid) to StackOverflow Question)

Thanks.

**Comment by pennersr** [comment]
Closing -- it is not possible to debug this without going into your project specific settings & app credentials.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2908
