### ISSUE TITLE
[Azure] Add possibility to change LOGIN_URL

### ISSUE THREAD

**Issue by fastlorenzo** [pennersr/django-allauth#2911]
Currently, when using Azure module, the `LOGIN_URL` is hardcoded to `https://login.microsoftonline.com/common/oauth2/v2.0`
https://github.com/pennersr/django-allauth/blob/cc0dfb7b30b22a8e68eaa35019515c5180e183f0/allauth/socialaccount/providers/azure/views.py#L14

There should be a possibility to override it with another one, to be able to restrict authentication to a single tenant.

More specifically, the `common` parameter used "Allows users with both personal Microsoft accounts and work/school accounts from Azure AD to sign into the application."

More information: https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-protocols#endpoints

**Comment by mateokurti** [comment]
I'm finding it hard to find an example about the usage of Azure AD on django-allauth. I know this is not directly related to this issue, but if you have an example, could you please provide it to me?

**Comment by Ahuahuachi** [comment]
@fastlorenzo I don´t know why it is a separated provider azure and microsoft, but if you use the microsoft provider and in the settings you configure your specific tenant, that should cover your use case. The settings should be something like this:
```
SOCIALACCOUNT_PROVIDERS = {
    'microsoft': {
        'tenant': '{tenant-id}',
    }
}
```

**Comment by mjmare** [comment]
Should that be TENANT? See https://django-allauth.readthedocs.io/en/latest/release-notes.html#section-6

But I'm confused about the azure vs microsoft provider.

**Comment by jmartens** [comment]
AFAIK they are merged and the only one existing currently is the microsoft provider. Not sure if this issue is still relevant, do you @pennersr ?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2911
