### ISSUE TITLE
How to use Google One Tap login with django-allauth?

### ISSUE THREAD

**Issue by anilshanbhag** [pennersr/django-allauth#2913]
Google One Tap login doesn't use an oauth flow. My question is how to integrate it into a django app that uses allauth for authentication?

I found a tutorial through which you can get the basic details like email, name from the one tap login [https://developers.onelogin.com/quickstart/google-ontap-with-onelogin
](https://developers.onelogin.com/quickstart/google-ontap-with-onelogin
)
How does one integrate it to complete the login?

**Comment by anuzis** [comment]
Asked a similar question on Stackoverflow a while back and received a helpful answer: https://stackoverflow.com/questions/64234915/how-to-integrate-google-one-tap-login-with-django-allauth

**Comment by derek-adair** [comment]
Probably close as discussion

**Comment by pennersr** [comment]
Now supported via 9246957e

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2913
