### ISSUE TITLE
Code Verifier not being sent to the access_token_url ?

### ISSUE THREAD

**Issue by mateokurti** [pennersr/django-allauth#2916]
When trying to use Azure AD authentication, I'm getting the following error from the Microsoft side. 
```
Error retrieving access token: b'{"error":"invalid_grant","error_description":"AADSTS50148: The code_verifier does not match the code_challenge supplied in the authorization request for PKCE."}
```

The original request that I am sending to the Azure authorize endpoint is:

```
// Line breaks for legibility only

https://login.microsoftonline.com/{tenant}/oauth2/v2.0/authorize?
client_id={client_id}
&response_type=code
&redirect_uri=http%3A%2F%2Flocalhost%2Fmyapp%2F
&response_mode=form_post
&scope={scope}
&state=12345
&nonce=12345
&code_challenge=RmVbjjBv5x0jFEncevJtp444WxmduBUvP5CPSPjepAA
&code_challenge_method=S256
```

The code_verifier of this code_challenge should've been sent to the `access_token_url`, but I think it is not being sent at all. I am sure there should be an solution, but I don't know how to achieve this.

**Comment by mateokurti** [comment]
It is called `client_secret` instead of `code_verifier` and it was my mistake why it wasn't working.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2916
