### ISSUE TITLE
Deleting primary email fails silently

### ISSUE THREAD

**Issue by pjreddie** [pennersr/django-allauth#292]
Primary emails cannot be deleted and messages are not displayed by default. Using just the standard templates and trying to delete a primary email, it is tough to know why nothing is happening since the page just reloads without any errors but still with a primary email. Messages could be displayed in the standard base template at least so that it doesn't fail silently.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/292
