### ISSUE TITLE
No error feedback displayed when connecting to a social account already linked to another account

### ISSUE THREAD

**Issue by enzedonline** [pennersr/django-allauth#2922]
There seems to be some error feedback missing from the form on connections.html.

When you try to link your local account to a social account already linked to another local account, the page simply refreshes with no feedback to the user, no error displayed. 

For example:
![image](https://user-images.githubusercontent.com/72310199/128328832-eae7c9d1-75e6-422a-bb15-7ccadd3a1015.png)

If I try to connect to my Google account (already linked to another local account), the page will just refresh and display the same again. It comes across as a bug rather than an expected user error.

Well, I got as far as tracing it back to ConnectionsView in \allauth\socialaccount\views.py but lost the process there. I could add some custom code into the front end to check this but better off in the backend.

**Comment by derek-adair** [comment]
Under the assumption that this is still valid (2 year old submission)... this looks to be a biggun... maybe?

---------------
Unsure how this owrks... but **should users be able to disconnect a social account from another one??**  Seems like this would be a better UX considering the user *may* have their account in an unrecoverable state w/ a social account associated with it.  I wouldn't have a problem with this.  I can see two scenario's off the top of my head where this would avoid complications;

1. A user loses access to a local account which is associated w/ a social account.
2. A users social account was used fraudulently to create an account.

**Comment by pennersr** [comment]
See:

```def _add_social_account(request, sociallogin):```

There:

```
    if sociallogin.is_existing:
        if sociallogin.user != request.user:
            # Social account of other user. For now, this scenario
            # is not supported. Issue is that one cannot simply
            # remove the social account from the other user, as
            # that may render the account unusable.
            level = messages.ERROR
            message = "socialaccount/messages/account_connected_other.txt"
```

Meaning, an error message is emitted. So I think this issue is dated and this works properly.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2922
