### ISSUE TITLE
Facebook Access is not getting saved in Access Token Table

### ISSUE THREAD

**Issue by sk1122** [pennersr/django-allauth#2924]
I am trying get the facebook's access_token but for some reason it is not saving it automatically.

I had created my own AccessToken model and decided to save facebook's access token in it by reverse engineering allauth.

But it is a temporary solution and I need permanent.

Can anybody help? 
I saw the codebase but it doesn't have `.save()` for SocialToken model in `oauth2/views.py`.

**Comment by HosseinMirjalali** [comment]
Are you storing Facebook's API credentials in form of environment variables?

**Comment by sk1122** [comment]
@HosseinMirjalali I have currently stored it in env variables

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2924
