### ISSUE TITLE
password reset email lands in spam

### ISSUE THREAD

**Issue by mukit24** [pennersr/django-allauth#2926]
I am having some troubles with Django-allauth password reset email. When a user clicks forget password and requests a password reset then the user got his/her email in spam.
NB: I haven't change the default template for email.

**Comment by 9mido** [comment]
Try overriding this template and make sure you write for your users to check their spam folder in case they did not receive it. 

https://github.com/pennersr/django-allauth/blob/master/allauth/templates/account/password_reset_done.html

It should probably be an allauth default for password reset and signup emails to have the templates say to check your spam folder to make it easy for users.

**Comment by mukit24** [comment]
> Try overriding this template and make sure you write for your users to check their spam folder in case they did not receive it.
> 
> https://github.com/pennersr/django-allauth/blob/master/allauth/templates/account/password_reset_done.html
> 
> It should probably be an allauth default for password reset and verification emails to have the templates say to check your spam folder to make it easy for users.



> Try overriding this template and make sure you write for your users to check their spam folder in case they did not receive it.
> 
> https://github.com/pennersr/django-allauth/blob/master/allauth/templates/account/password_reset_done.html
> 
> It should probably be an allauth default for password reset and verification emails to have the templates say to check your spam folder to make it easy for users.

is there any way that can prevent it from being in spam?

**Comment by 9mido** [comment]
Depends on what email provider you use. You may need to buy something like sendgrid and pay for a dedicated IP to send emails. You need a dedicated IP because with a shared IP, you will have to deal with other people who may be spammers themselves which causes your emails to automatically be sent to spam.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2926
