### ISSUE TITLE
specifying DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField' triggers migration

### ISSUE THREAD

**Issue by brownaa** [pennersr/django-allauth#2929]
New to Django 3.2 the default for primary keys is `BigAutoField` which changed from previous versions of Django where it was `AutoField`. Some additional background on this [here](https://dev.to/weplayinternet/upgrading-to-django-3-2-and-fixing-defaultautofield-warnings-518n).

After running `python manage.py makemigrations` this creates a new migration for allauth `account` and `socialaccount` apps.

### Proposed fix:

 - update `apps.py` in these two apps (`account` and `socialaccount`).

**[account](https://github.com/pennersr/django-allauth/blob/cc0dfb7b30b22a8e68eaa35019515c5180e183f0/allauth/account/apps.py#L5-L7)**
```
class AccountConfig(AppConfig):
    name = "allauth.account"
    verbose_name = _("Accounts")
    default_auto_field = 'django.db.models.AutoField'   # new
```

**[socialaccount](https://github.com/pennersr/django-allauth/blob/cc0dfb7b30b22a8e68eaa35019515c5180e183f0/allauth/socialaccount/apps.py#L5-L7)**
```
class SocialAccountConfig(AppConfig):
    name = "allauth.socialaccount"
    verbose_name = _("Social Accounts")
    default_auto_field = 'django.db.models.AutoField'   # new
```

**Comment by 9mido** [comment]
Isn't this a duplicate of #2829?

**Comment by brownaa** [comment]
yes indeed.

**Comment by brownaa** [comment]
closed corresponding PR as well.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2929
