### ISSUE TITLE
Connecting multiple accounts from same provider while logged in

### ISSUE THREAD

**Issue by pjreddie** [pennersr/django-allauth#293]
There is a flow issue if you try to connect a secondary social account with the same provider.
- Logged in to Gmail_1
- Logged in to site
- Want to connect Gmail_2
- Click on gmail in .../connections/
- Redirect to profile since you are already logged in to Gmail_1, doesn't prompt to log in to Gmail_2 or use one of the other Gmail accounts you are already logged in as.

Not sure if this is fixable within allauth. Haven't explored how oauth works too much to know if this is possible with different urls or something (that's why i'm using allauth!)

The current workaround is to log out of the external account before you try to connect another one.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/293
