### ISSUE TITLE
Can I disable SSL verification?

### ISSUE THREAD

**Issue by sergey-jr** [pennersr/django-allauth#2933]
Can I do it for any reason?

**Comment by sergey-jr** [comment]
Or can you add some settings variable for it?

**Comment by 9mido** [comment]
Maybe you could try this:

https://docs.djangoproject.com/en/3.2/ref/settings/#secure-redirect-exempt

But not sure why you would want to make your django app less secure.

**Comment by AniPython** [comment]
SITE_ID = 3

# EMAIL_USE_TLS = True 
EMAIL_USE_SSL = True

# EMAIL_PORT = 25
EMAIL_PORT = 465

**Comment by cyberb** [comment]
I have a test env where I use authelia with paperless (allauth) to test if my OIDC config is correct, but server_url https cert is self signed, it would be nice to disable ssl verify in that case (pure development env)

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2933
