### ISSUE TITLE
Handling multiple client ids for an auth provider

### ISSUE THREAD

**Issue by pythad** [pennersr/django-allauth#2936]
I am trying to implement Google auth for my backend for a mobile app on different platforms (IOS, Android). This requires having multiple client ids for each of them. That said I cannot have more than one pair of `(site.id, provider)` as the module fetches SocialApp with the query:

`app = self.get(sites__id=site.id, provider=provider)`.

Can `django-allauth` handle multiple Client IDs for a single provider?

**Comment by pythad** [comment]
Google does not require `client_id` to be the same as long as they're in the same organization.

That said for a two platform setup you need to have two `client_id` s for each platform plus `client_id/secret` pair for an api.

It works out of the box using `django-allauth` actually.

**Comment by Terspychore** [comment]
Hello,
How did you manage to solve the issue with multiple clients IDs for one provider (web, ios, android) ?

I have successfully done it with Apple using `client_id = '<app_id>, <service_id>'`, but when using this syntax for Google it does not work. (`"The OAuth client was not found."`).

Moreover, only using one `client_id` does not work even if all of my IDs are in the same Google project. (`"error": "unauthorized_client"`).

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2936
