### ISSUE TITLE
default_auto_field for all models

### ISSUE THREAD

**Issue by mohammad2goodarzi** [pennersr/django-allauth#2939]
All models have IDs. But django-allauth models do not.
So when we use django-allauth in our project, it creates a migration file which leads to some problems.

**Comment by 9mido** [comment]
Isn't this a duplicate of #2829 and #2826?

**Comment by mohammad2goodarzi** [comment]
No. I tried their method. It does not solve the problem.
The problem is that migrations files must already exist in django-allauth.

**Comment by pennersr** [comment]
Closing, it's there now.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2939
