### ISSUE TITLE
A place to specify account adapter

### ISSUE THREAD

**Issue by mgoldenbe** [pennersr/django-allauth#2940]
I have created a fresh new Django project, followed instructions for installing `django-allauth` and added the following at the end of `settings.py`:

```
from allauth.account.adapter import DefaultAccountAdapter

class CustomAllauthAdapter(DefaultAccountAdapter):
    pass

ACCOUNT_ADAPTER = CustomAllauthAdapter
```

I am getting the error `django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet`, which I interpret to mean that I am trying to import from `allauth.account.adapter` before `django-allauth` (which is in installed apps, of course) is loaded. Then what is the proper place to specify an account adapter?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2940
