### ISSUE TITLE
[Microsoft] Use Microsoft Graph's mailNickname for User.username

### ISSUE THREAD

**Issue by Ahuahuachi** [pennersr/django-allauth#2944]
Microsoft provider uses Microsoft Graph's givenName property which represents the user's first name to populate django's username. This opens up the possibility for errors at login.
Instead Microsoft Graph's mailNickname could be used as username, as it holds the mail alias which is far less likely to get duplicated.

Documentation for MS Graph's properties: https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0#properties

**Comment by Ahuahuachi** [comment]
closed by #2945

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2944
