### ISSUE TITLE
Unable to override the pre-authenticate and authenticate methods in adapters

### ISSUE THREAD

**Issue by eakenbor** [pennersr/django-allauth#2948]
Unlike save_user and send_email in DefaultAccountAdapter, I am unable to override the pre_authenticate and authenticate methods. Please can someone explain why or how I can achieve these?

````
class DefaultAccountAdapterCustom(DefaultAccountAdapter):
    def pre_authenticate(self,  request, **credentials):
        # Do something before authenticating
    
    def authenticate(self,  request, **credentials):
          # Do something after authenticating
````

**Comment by pennersr** [comment]
Overriding `pre_authenticate` should be the same as overriding `save_user` -- no idea why it is not working for you, that code snippet above is likely not complete. In any case, don't think this is an issue in allauth.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2948
