### ISSUE TITLE
[Quick Question] Custom  urls in adapter 

### ISSUE THREAD

**Issue by roman-rr** [pennersr/django-allauth#2949]
Please advice for me fast and correct way to change scheme [here](https://github.com/pennersr/django-allauth/blob/353386216b79f16709e97bb487c0bbbba2bc0c71/allauth/socialaccount/providers/odnoklassniki/views.py#L37) from `http` to `https` for all urls

```python
access_token_url = "http://api.odnoklassniki.ru/oauth/token.do"
authorize_url = "http://www.odnoklassniki.ru/oauth/authorize"
profile_url = "http://api.odnoklassniki.ru/fb.do"
```

Create custom adapter ? Custom provider ? Some function ? Make pull request ?

**Comment by roman-rr** [comment]
@za Yes, it is. 
Random SEO checkers also have warning of redirects to not-secure http.

**Comment by pennersr** [comment]
Closing -- #2964 is merged.

**Comment by za** [comment]
Thank you @pennersr

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2949
