### ISSUE TITLE
The e-mail verification text may not tell the truth

### ISSUE THREAD

**Issue by i5ar** [pennersr/django-allauth#2950]
Using the following configuration:

```py
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
```

When a user tries to log in is redirected to the `confirm-email` page: `We have sent an e-mail to you for verification. Follow the link provided to finalize the signup process. Please contact us if you do not receive it within a few minutes.`

## Problem
Sometimes the user doesn't have an e-mail (maybe the user was created in the admin panel) but he may still try to log in with a username and a password.

## Solution
Check if the user has an e-mail and change the text accordingly:
if the user has an e-mail: `We have sent an e-mail to you...`;
else: `E-mail required, Please contact us.` or something like that.

Thank you

**Comment by foad-heidari** [comment]
if`ACCOUNT_EMAIL_REQUIRED=True` we shouldn't allow the creation of users without email, and email should be required also in the admin panel.

**Comment by 9mido** [comment]
@i5ar 

Views.py:

```
class EmailVerificationSentView(TemplateView):
    template_name = "account/verification_sent." + app_settings.TEMPLATE_EXTENSION

    def get_context_data(self, **kwargs):
        context = super(EmailVerificationSentView, self).get_context_data(**kwargs)
        email = self.request.user.email
        if EmailAddress.objects.filter(email=email, verified=False).exists() is True:
            context['user_email_address_exists'] = 'true'
            return context

email_verification_sent = EmailVerificationSentView.as_view()
```

verification_sent.html:

```
{% if user_email_address_exists == 'true' %}
<p>{% blocktrans %}We have sent an e-mail to you for verification. Follow the link provided to finalize the signup process. Please contact us if you do not receive it within a few minutes.{% endblocktrans %}</p>
{% else %}
<p>{% blocktrans %}E-mail required. Please contact us.{% endblocktrans %}</p>
{% endif %}
```

**Comment by pennersr** [comment]
Closing -- within your project you could provide your own template checking if the user has an email.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2950
