### ISSUE TITLE
Eve Online and reusing token for doing requests

### ISSUE THREAD

**Issue by mpsk2** [pennersr/django-allauth#2952]
I have wrote short and small django app with rest_auth and allauth, which just logs in with Eve Online. The app stores the token in default way.

I would like to reuse the stored information to access EVE ESI, but I do not know how.

Can we::
1) Update documentation on how to access the EVE Esi
2) Describe it here, as it would be very helpful. 

Here is an article how to log into eve online: https://developers.eveonline.com/blog/article/sso-to-authenticated-calls

**Comment by pennersr** [comment]
This ticket is not actionable, closing. https://django-allauth.readthedocs.io/en/latest/faq.html#why-did-you-just-close-my-issue

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2952
