### ISSUE TITLE
Shopify Multipass support

### ISSUE THREAD

**Issue by shawaj** [pennersr/django-allauth#2954]
The existing Shopify OAuth2 plugin works nicely for shopify app developers to enable single sign on for apps within shopify, where the user will have a login directly at shopify.

However, this does not cater for single sign on for customers placing orders at that specific Shopify store.

For this, it is required to use [Shopify Multipass](https://shopify.dev/api/admin/rest/reference/plus/multipass) 

It would be great to add support for shopify Multipass as a provider.

**Comment by pennersr** [comment]
I would be happy to accept a pull request, but keeping this ticket open is not going to help in getting it resolved. Hence, closing it.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2954
