### ISSUE TITLE
"email_address.for_new_user" is missing in social signup form

### ISSUE THREAD

**Issue by mbaechtold** [pennersr/django-allauth#296]
Please correct me if this behaviour has been implemented intentionally...

Let's have a look at the `save()` method of the `allauth.account.forms.SignupForm` form class to see that new users a treated in a special way:

``` python
def save(self, request):
    new_user = self.create_user()
    super(SignupForm, self).save(new_user)
    email_address = setup_user_email(request, new_user, [])
    if email_address:
        email_address.for_new_user = True
    send_email_confirmation(request, new_user, email_address=email_address)
    self.after_signup(new_user)
    return new_user
```

The property `email_address.for_new_user` will then be used to load a different template for the mail:

``` python
if (hasattr(self.email_address, 'for_new_user')
        and self.email_address.for_new_user):
    email_template = 'account/email/email_confirmation_signup'
else:
    email_template = 'account/email/email_confirmation'
```

This distinction is not done in the "social" counterpart as we can see by having a look at the `save()` method of the `allauth.socialaccount.forms.SignupForm` form class:

``` python
def save(self, request):
    new_user = self.create_user()
    self.sociallogin.account.user = new_user
    self.sociallogin.save(request)
    super(SignupForm, self).save(new_user) 
    # Confirmation last (save may alter first_name etc -- used in mail)
    send_email_confirmation(request, new_user)
    return new_user
```

A user who does a social signup will therefore not get the special "account/email/email_confirmation_signup.txt" template.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/296
