### ISSUE TITLE
Why does django-allauth provide views that are already available in Django natively?

### ISSUE THREAD

**Issue by lapinvert** [pennersr/django-allauth#2961]
I would like to understand why, what is the rationale behind it, so that I can make more educated choice on which one to use.

Specifically, when comparing Django native views (`django.contrib.auth.views`) and , Allauth views (`allauth.account.views`), we find the following views that have the same purpose:

| Django Native  | Allauth |
| ------------- | ------------- |
| `PasswordChangeView`  | `PasswordChangeView`   |
| `PasswordChangeDoneView`  | None (same view used)  |
| `PasswordResetView`  | `PasswordResetView`  |
| `PasswordResetDoneView`  | `PasswordResetDoneView`  |
| `PasswordResetConfirmView`  | `PasswordResetFromKeyView`  |
| `PasswordResetCompleteView`  | `PasswordResetFromKeyDoneView` |

Are there any reasons for this? Also any reasons to prefer using the allauth views over the native views (given the fact that we already use allauth for signup for example).

Thank you,

**Comment by pennersr** [comment]
allauth is over 11 years old, back then those views where not there.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2961
