### ISSUE TITLE
Request: allow alternative text to provider name for login form

### ISSUE THREAD

**Issue by pcolmer** [pennersr/django-allauth#2963]
For a lot of the social account providers, displaying the provider name is the sensible and appropriate thing to do.

However, for other providers - and I'm specifically thinking of Keycloak here - the provider name itself may not make any sense to the person logging in. That is the name of the technology behind the scenes. The user may be used to seeing something like "XYZ Company SSO" elsewhere.

There is a Name field when configuring the social applications and that value could be used in this instance but it doesn't seem to be accessible from the provider object (see https://github.com/pennersr/django-allauth/blob/master/allauth/templates/socialaccount/snippets/provider_list.html).

A possible alternative approach would be to provide the alternative text in the configuration block for the provider.

I'd be happy to consider making the changes myself but I'm struggling to unpick the way it all hangs together.

**Comment by pennersr** [comment]
Closing -- #2965 is merged

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2963
