### ISSUE TITLE
CUSTOM_USERNAME_VALIDATOR being set but not being working when trying form

### ISSUE THREAD

**Issue by thebr0wnguy** [pennersr/django-allauth#2966]
Hi, I'm running into a bug when I try and use a custom username validator setting. As you can see it is being set, and is being referenced correctly, but it doesn't work when i check my edit profile form.

"Python manage.py shell"
```
>>> settings.ACCOUNT_USERNAME_VALIDATORS
'accounts.validators.custom_username_validators'

>>> from allauth.account import app_settings
>>> app_settings.USERNAME_VALIDATORS
[<accounts.validators.CustomUsernameValidator object at 0x10ea328e0>]
```

```@login_required
def edit_profile_view(request,username):
	if request.method == 'POST':
		form = CustomUserChangeForm(request.POST, instance=request.user)

		if form.is_valid():
			form.save()
			return redirect(reverse('profile_view', kwargs={"username": request.user.username } ))
		else:
			args = {"form": form}
			return render(request, 'account/edit_profile.html', args)

	else:
		if username == request.user.username:
			form = CustomUserChangeForm(instance=request.user)
			args = {'form': form}
			return render(request, 'account/edit_profile.html', args)
		else:
			return redirect(reverse('profile_view', kwargs={'username': request.user.username}))
```

I'm not sure why it's not working, everything is being set correctly but whenever i test the form, it still allows special characters.

I'm also using the djangox starter project that comes with allauth preinstalled

Update:
I found that changing the setting:

ACCOUNT_SIGNUP_FORM_CLASS = 'accounts.forms.CustomUserCreationForm'

messes with the CUSTOM_USERNAME_VALIDATOR setting. Meaning, if I disable account_signup_from_class, the Custom_username_validator works, is there a fix around them.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2966
