### ISSUE TITLE
SOCIALACCOUNT_PROVIDERS does not supply working SocialApp.

### ISSUE THREAD

**Issue by Fingel** [pennersr/django-allauth#2967]
Hi, new user of django-allauth, so far very impressed.

One problem I've noticed is that in the post-installation documentation here:

https://django-allauth.readthedocs.io/en/latest/installation.html#post-installation

It says that once the setup is completed, you either need to create a `SocialApp`record in your database **or** make sure the `SOCIALACCOUNT_PROVIDERS` setting is correct.

However, even with the setting filled out:

```python
SOCIALACCOUNT_PROVIDERS = {
    'Discord': {
        'APP': {
            'client_id': os.getenv('DISCORD_CLIENT_ID'),
            'secret': os.getenv('DISCORD_SECRET'),
            'key': ''
        }
    }
}
```
Attempting to use the integrations returns:

```
SocialApp matching query does not exist.
```

The only way to use the integration successfully is to create a SocialApp record in the database. This is somewhat painful for deployment and development.

Is `SOCIALACCOUNT_PROVIDERS` settings just totally ignored? Or redundant?

**Comment by androa** [comment]
Exactly what was your typo? :) I'm having the same issue, and I cannot see what is wrong in the code you supplied here or in mine.

**Comment by mscheper** [comment]
> Exactly what was your typo? :)

@androa: My guess is that the `APP` key was supposed to be `APPS`. Did you get yours working?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2967
