### ISSUE TITLE
How to logout the facebook using django-allauth?

### ISSUE THREAD

**Issue by dhanababu-nyros** [pennersr/django-allauth#297]
I am new to django-allauth. I have successfully login from facebook using djang0-allauth. But I try to logout using '/accounts/logout'. It is also successfully logged out my application. But my problem is at the same time facebook not logged out(i.e; facebook not session expired.). Please solve my problem. Thanks...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/297
