### ISSUE TITLE
Login to django by phpbb

### ISSUE THREAD

**Issue by ManPython** [pennersr/django-allauth#2972]
It's possible to implement Login to django by phpbb2/3?

https://github.com/SimonEast/django-login-for-phpbb
https://pypi.org/project/django-phpBB3/
https://github.com/jedie/django-phpBB3
https://github.com/automaciej/django-phpbb
https://trac-hacks.org/wiki/PhpBbAuthPlugin
https://github.com/Lusitanian/PHPoAuthLib
http://djangobb.org/

**Comment by pennersr** [comment]
Not an issue -- closing.

**Comment by ManPython** [comment]
Just change for features or enhance?

**Comment by pennersr** [comment]
Sorry, but this is not the place for general questions. As for feature requests on new providers, that also only fills up the list of issues -- we could file an infinite number of feature requests on providers, that is not going to get any work done.  Would be happy to accept a PR, or alternatively, try sponsoring this activity -- https://github.com/sponsors/pennersr

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2972
