### ISSUE TITLE
"next" url parameter is not honored by discord provider

### ISSUE THREAD

**Issue by philip-ulrich** [pennersr/django-allauth#2975]
When accessing a page with auth required, the "next" url parameter is added and it's sent to the login page.

https://domain.com/accounts/login/?next=/other/page

Assuming the user logs in with discord, the next parameter is completely dropped when the request is sent to discord and not added back after the oauth response is posted back. Conversely, if you try the same URL after you log in - the redirect works. Implying it's only lost when the discord provider is handling the login.

**Comment by TrissieTheHusky** [comment]
Any updates on this?

**Comment by derek-adair** [comment]
Hello @philip-ulrich and @TrissieTheHusky or anyone who stumbles upon this.  We are doing some triage and I would like to help determine if this is still an issue.  Looks like philip is active so hopefully he can step in.

Here are some details that would be helpful not only here, but any open source issue you would like to bring up in a tracker such as this.

1. **Environment**
  * Version of django-allauth/python
  * Version of python
  * Allauth configuration (any relevant settings)
2. Do you have any logs?

------------------

It looks like the discord provider does not implement get_login_url, which seems like it is problematic.  I suspect you may see a warning thrown by the provider as this being the case.

**Comment by philip-ulrich** [comment]
I am active on github, but we stopped using django for this and quite a few other issues. So I can no longer reproduce this for you or provide any further information. Apologies.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2975
