### ISSUE TITLE
Release 0.46.0 with support for Django 3.2

### ISSUE THREAD

**Issue by mpoli** [pennersr/django-allauth#2976]
HEAD (currently https://github.com/pennersr/django-allauth/commit/36dd5a7dad52429143434517c50811927283e0bb) supports Django version 3.2,, but remains unreleased for two months now.

Relevant projects like cookiecutter-django are being held back at django 3.1 due to django-allauth 0.45.0 not supporting django 3.2. All the red Xs in https://github.com/cookiecutter/cookiecutter-django/issues/3398 except for django-allauth already support dango 3.2 in their releases.

It would be nice if django-allauth would pack a release from the current HEAD so that Django 3.2 is supported by it.

Edit: merging https://github.com/pennersr/django-allauth/pull/2973 beforehand might be interesting.

**Comment by mpoli** [comment]
Solved by https://github.com/pennersr/django-allauth/commit/615990c29c258c2118fc4182e7ad5cf553b8d18a

Thanks, @pennersr!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2976
