### ISSUE TITLE
Password set view redirects to password change form on submit

### ISSUE THREAD

**Issue by sergkop** [pennersr/django-allauth#298]
In my application I don't ask password in the registration form, but do it later when user confirms the email (and is automatically logged in). I found it restricting that password set form only redirects to password reset form. The similar method in django (django.contrib.auth.views.password_reset_confirm) has an optional parameter post_reset_redirect, which allows to redirect to a custom url on successful POST request. It would be nice to have a similar one in allauth.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/298
