### ISSUE TITLE
Manually resend confirmation email 

### ISSUE THREAD

**Issue by matthieudesprez** [pennersr/django-allauth#2980]
What would be the easiest way to manually resend confirmation email upon signup if user has not received it ?

I'm working on a project where the signup is done on a different frontend application than django.

Would I need to create a specific endpoint for that or is there something built-in in django-allauth ?

I saw the confirmation email is resend upon login, but I would just need the user to be able to click on a single button to resend this email.

Thank

**Comment by 9mido** [comment]
If your users able to login without their email being verified, they can re-send the confirmation email when they navigate to /accounts/email/

However, there is no way currently to allow logged out users to re-send an email verification to themselves. 

Maybe something can be done on the django admin page for admin users to manually send it. Otherwise, I am curious how this can be done. 

If you are able to make a PR or show us some code in this thread it would be worth looking at. 

Related #946

**Comment by matthieudesprez** [comment]
Thanks for your quick answer, I was able to achieve my need creating a custom view.

This way, a user can request another verification email sending from our react app, and we benefit from the cooldown_period check in send_email_confirmation.

```python
"""
Custom views to provide additional features to oidc_provider_app
"""
import json

from allauth.account.models import EmailAddress
from allauth.account.utils import send_email_confirmation
from django.contrib.auth import get_user_model
from django.http import HttpResponse, HttpResponseBadRequest
from django.views import View

User = get_user_model()


def is_user_email_verified(user, email):
    """
    returns True if EmailAddress exists and is already verified, otherwise returns False
    """
    result = False
    try:
        emailaddress = EmailAddress.objects.get_for_user(user, email)
        result = emailaddress.verified
    except EmailAddress.DoesNotExist:
        pass
    return result


class SendValidationEmailView(View):
    """
    Implement requests to manually send confirmation email in case it hasn't been received
    """

    def post(self, request, *args, **kwargs):
        """
        request for validation email sending
        """
        payload = json.loads(request.body)
        email = payload.get('email')
        if email is None:
            return HttpResponseBadRequest("No email provided")

        try:
            user = User.objects.get(email=email)
        except User.DoesNotExist:
            # avoid leaking information about user existence
            return HttpResponse(status=200)

        if not is_user_email_verified(user, email):
            send_email_confirmation(request, user, email)

        return HttpResponse(status=200)
```

**Comment by 9mido** [comment]
@matthieudesprez This code is quite nice and you were impressively able to figure something out really fast! I am wondering though how you are implementing this code? With a custom form, button, or something else? You mentioned button above but can we see the associated code (forms.py, urls.py, html files, etc) you are using for this view? 

In regards to the cooldown period, we have a few open issues and PRs about this, so things may not be working as intended in the current state. Can you take a look at these cooldown / spammable action issues/PRs and make sure that they align with what you are trying to do here? We need to be absolutely sure that when testing this, a user is not able to spam emails by clicking the button multiple times in a row for example. 

Issues/PRs: 2631, 2167

**Comment by matthieudesprez** [comment]
Thanks for these information and for linking these issues, I'll have a deeper look at it.

I'm just exposing this endpoint publicly from a [Django oidc + allauth application](https://github.com/wayward710/django-oidc-allauth) in a setup where the sign up part is handled on a separate React client, only the sign in is done with through Django form.

Upon signup the data is sent to another Django backend, which shares the database with the Django Authentication application, and UX wise it was necessary to provide a call to action to the user for requesting another email confirmation (in case he doesn't receive anything the first time)

That's why I couldn't use any form in Django to trigger the confirmation email resending.

**Comment by josesoal** [comment]
This worked for me

`       email_address = EmailAddress.objects.filter(
            user=self.request.user
        ).first()
        confirmation = EmailConfirmation.create(email_address)
        confirmation.sent = now()
        confirmation.save()

        adapter = get_adapter(self.request)
        signup = True # to get "email_confirmation_signup" template
        adapter.send_confirmation_mail(self.request, confirmation, signup)
`

**Comment by Ohnoimded** [comment]
How did you verify the code?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2980
