### ISSUE TITLE
Google PermissionDenied() error

### ISSUE THREAD

**Issue by onurmatik** [pennersr/django-allauth#2982]
Social sign-in with Google OAuth 2 client is failing with a PermissionDenied() exception most of the time (but not every time). 

The returned error does not tell much:

`{'provider': 'google', 'code': 'unknown', 'exception': PermissionDenied()}`

I found this thread that seems relevant:
https://stackoverflow.com/questions/65482931/django-allauth-google-login-not-working-on-ios

But in my case it is not only iOS, but equally with every major OS and browser I could test with. And the suggested workaround (setting the SESSION COOKIE_SAMESITE to 'None') did not work. 

I was not testing the social login flow daily but I think this started recently and I suspect a modification on Google side is causing the problem but I couldn't spot it. 

I am using the latest version (0.46) of allauth.

**Comment by pennersr** [comment]
Closing -- this is too little to go on and does not clearly point to an issue in allauth.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2982
