### ISSUE TITLE
Unicode in username breaks social auth

### ISSUE THREAD

**Issue by philip-ulrich** [pennersr/django-allauth#2983]
```
DataError at /accounts/discord/login/callback/
(1366, "Incorrect string value: '\\xF0\\x9D\\x98\\x9A\\xF0\\x9D...' for column `foc_web`.`auth_user`.`username` at row 1")
Request Method:	GET
Request URL:	http://redacted/accounts/discord/login/callback/?code=redacted&state=redacted
Django Version:	3.2.8
Exception Type:	DataError
Exception Value:	
(1366, "Incorrect string value: '\\xF0\\x9D\\x98\\x9A\\xF0\\x9D...' for column `foc_web`.`auth_user`.`username` at row 1")
Exception Location:	/home/container/.local/share/virtualenvs/foc_web-RLEHz5RU/lib/python3.8/site-packages/pymysql/err.py, line 143, in raise_mysql_exception
Python Executable:	/home/container/.local/share/virtualenvs/foc_web-RLEHz5RU/bin/python
Python Version:	3.8.8
Python Path:	
['/home/container/foc_web',
 '/home/container/.local/share/virtualenvs/foc_web-RLEHz5RU/bin',
 '/usr/local/lib/python38.zip',
 '/usr/local/lib/python3.8',
 '/usr/local/lib/python3.8/lib-dynload',
 '/home/container/.local/share/virtualenvs/foc_web-RLEHz5RU/lib/python3.8/site-packages']
Server time:	Sun, 21 Nov 2021 16:53:05 +0000
```

Services like Discord allow unicode characters in their "usernames". Unrelated, but Discord "usernames" are not unique so using a "username" as a real username is a bad idea. 

Would be a breaking change, but should consider switching to using discord ID as username and put username in extra data.

That said, my other issue (and peoples issues in general) remain untouched, so I expect I'll have to patch this myself.

**Comment by pennersr** [comment]
This is not an issue in allauth, but rather an issue in your database. Possibly, your mysql character set is not configured properly to store this data.

**Comment by philip-ulrich** [comment]
Assuming that is the case, that still leaves the fact that discord “usernames” are not unique. It should be the integer ID that is used for the username.

**Comment by pennersr** [comment]
The username handed over from discord to allauth is not used as is. It is a suggested username and checks are in place to see if this username is already taken.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2983
