### ISSUE TITLE
Request: Add Authink to the providers list

### ISSUE THREAD

**Issue by tomlawesome** [pennersr/django-allauth#2984]
It would be great if Authentik ( https://goauthentik.io ) could be added as an included/canned provider.

**Comment by pennersr** [comment]
Would be happy to accept a pull request, or alternatively, please considering sponsoring this: https://github.com/sponsors/pennersr

**Comment by tomlawesome** [comment]
Unfortunately, I don’t have the skill to submit a PR and its only for a self hosted app to store recipes.. so unfortunately can’t justify sponsoring it. 

Will have to look for a new app I guess! Thanks for responding.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2984
