### ISSUE TITLE
Redirect users post sign-up/sing-in to a specific page depending on the page they are coming from

### ISSUE THREAD

**Issue by nmacchitella** [pennersr/django-allauth#2985]
- I have an invite system in my django app that allow users to invite other people (using their email) to join their team.
- When an invited user clicks on an invitation, they are redirected to an url that carries informations about the specific team the user was invited to.
- Such url calls a view called accept_invitation that handles the following use-cases:

a) If a user is logged-in already AND they are also the invited user (i check the email of the invite), I add the user to the team and redirect them to the team's page.

b) If a user is logged-in already BUT they are not the invited user, I redirect them to a page where I invite them to log-in with a different account.

c) If a user is logged-out, I redirect them to a page where I invite them to log-in and/or sign-up to continue.

Use-case a) works just fine but use-case b) and c) I had to figure out how to propagate the informations of the invite to the following screens and past the login.

My initial idea was to add the parameters of the invitation to the request.session so that after the login-in I could have retrieved the informations from the request inside a MyAccountAdapter(DefaultAccountAdapter) adapter I defined then send the users where they had to go.

However, I am doing something wrong and MyAccountAdapter is not getting called. I am not sure why. I think it's because of another adapter MySocialAccountAdapter I made that maybe is messing things up (and I am not even sure if it's doing what it's supposed to do honestly).

Anyway, I am lost so any help would be super appreciated. (here is a stackoverflow [question](https://stackoverflow.com/questions/70208543/django-allauth-redirect-users-post-sign-up-sing-in-to-a-specific-page-depending) with all the code)

**Comment by pennersr** [comment]
It's really not doable to help out in project specific issues. Note sure what you mean by "MyAccountAdapter is not getting called." -- you are referring to the `get_login_redirect_url`? Note that that method is only called if there is no ?next= parameter. Also note that you seem to be missing a SOCIALACCOUNT_ADAPTER setting...  other than that, I have to close this issue.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2985
