### ISSUE TITLE
Update Facebook complete login

### ISSUE THREAD

**Issue by heindrickdumdum0217** [pennersr/django-allauth#2986]
Users may want to create custom provider which extends FacebookProvider and set custom provider_id.

For example
```
from allauth.socialaccount.providers.facebook.provider import FacebookProvider


class FacebookGroupProvider(FacebookProvider):
    id = "facebook_group"
    name = "Facebook Group"


provider_classes = [FacebookGroupProvider]
```

The problem is in this case social account will be created with FacebookProvider.id instead of custom provider_id.

https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/providers/facebook/views.py#L66
https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/providers/facebook/views.py#L38
https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/providers/facebook/views.py#L49
https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/providers/base.py#L63
https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/providers/base.py#L86

I think we don't need to update [login_by_token](https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/providers/facebook/views.py#L73) function for custom provider.
Because we use this function for Facebook login purpose.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2986
