### ISSUE TITLE
How to change password via REST calls.

### ISSUE THREAD

**Issue by sowinski** [pennersr/django-allauth#2988]
Hi,

I want to add to my front end the ability to change the password.

Is there a REST call in django-allauth to change the password or do I have to implement this on my own?

/accounts/password/change/ => if I do a POST call here it fails due to missing CSRF-Token

Thank you

**Comment by pennersr** [comment]
The allauth endpoint can be posted to from AJAX calls. You will indeed need to supply the CSRF token, like documented here:

https://docs.djangoproject.com/en/4.0/ref/csrf/#ajax

**Comment by sowinski** [comment]
Thank you for the fast response.

We habe an Android app which do use Token-Based authentication. We do not use any cookies nor we load a page to get a CSRF token. 
What would you do in this case? Would you recommend to modify your view to disable CSRF in this case or write your own REST endpoint?

**Comment by pennersr** [comment]
In that case, you indeed need to disable CSRF. You can use something like this to avoid forking/patching:

```

# some views.py
from allauth.account.views import password_change

custom_password_change = csrf_exempt(password_change)

# some urls.py -- same path, so make sure it gets listed before the allauth urls.
urlpatterns = [
    path(
        "password/change/",
        views.custom_password_change,
    ),
```

**Comment by sowinski** [comment]
Your provided solution is super clear and short. 

Unfortunately it is not working. 
If I try to post the data as an AJAX call I get returned the login form.

I guess my Token-Based authentication is not working in that case. Not sure why (Because everything else works fine)

https://www.django-rest-framework.org/api-guide/authentication/#tokenauthentication
Maybe this authentication is only valid for calls to the rest api?

**Comment by pennersr** [comment]
Think you're right, you would need a middleware running globally that checks the token and automatically signs users in.

**Comment by sowinski** [comment]
I will write my own endpoint in that case.

Thank you :)

**Comment by gabn88** [comment]
@sowinski 
Interestingly I was looking for the same. I guess I'm going to write some new REST views to solve the issue, as the solution of @pennersr leads to more problems (in authentication, for example, but also by leaving non AJAX forms wide open with a vulnerability as they also won't check CSRF anymore).

Maybe if I think about it I'll post them here.

**Comment by sowinski** [comment]
@gabn88 
Thank you. I need also registration for my app.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2988
