### ISSUE TITLE
FEATURE UPDATE 

### ISSUE THREAD

**Issue by AbhijithGanesh** [pennersr/django-allauth#2989]
Currently, The package is not optimized for Django 4.0 and it requires some work. Django 4.0 has implemented a new security policy related to origins [Same and Cross Origins] and there are certain internal changes too. They can be [read](https://docs.djangoproject.com/en/4.0/releases/4.0/) here.  These changes have to be implemented to keep the project running.

**Comment by pennersr** [comment]
This issue is not specific and hence difficult to act upon. When filing an issue, please accurately describe the issue.

**Comment by tomwojcik** [comment]
I think what OP meant is what I described in this SO question. https://stackoverflow.com/questions/70311260/how-to-send-non-empty-origin-header-in-post-request-if-running-an-app-on-localho

I think it's impossible to use allauth in Django 4 on localhost, but at the same time it's not something allauth should handle.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2989
