### ISSUE TITLE
username (added via populate_user) is overwritten by save_user

### ISSUE THREAD

**Issue by andylolz** [pennersr/django-allauth#2991]
I’m authenticating users via email, with `ACCOUNT_USERNAME_REQUIRED` set to false. I’d like to set a custom username for social account logins, that includes the social account’s UID.

I’ve created a custom social account adapter. In order to generate the custom username, I think I need access to `sociallogin.account.uid`, which I think rules out using `generate_unique_username` or `populate_username` (since these don’t have access to `sociallogin`).

I’m instead setting the custom username in `populate_user`. This works correctly for social account auto-signups.

However, without auto-signup, the username is thrown away by this bit of the default account adapter:
https://github.com/pennersr/django-allauth/blob/985930d303d54b49204d468b3771c811e687eb90/allauth/account/adapter.py#L233-L239

Would it work to change this to:
```python
username = data.get("username")
user_email(user, email)
if username:
    user_username(user, username)
if first_name:
    user_field(user, "first_name", first_name)
if last_name:
    user_field(user, "last_name", last_name)
```

Would you be happy to accept a pull request to this effect? Thanks,

**Comment by andylolz** [comment]
I’ve worked around this by creating a `save_user` adapter that calls super(), then overwrites the username, and then resaves the user. This works okay, but I wonder if there’s a better way.

**Comment by andylolz** [comment]
Apologies for rewording this ticket so many times! Hopefully it’s now a bit clearer what I’m trying to do here.

My current workaround is to create a `save_user` adapter that calls super(), then overwrites the user’s username with the custom one, and then resaves the user. This works okay, but I wonder if there’s a better way.

**Comment by derek-adair** [comment]
@andylolz Close this and move this conversation to an actual PR!  It looks good to me, but i'm just doing triage.

**Comment by andylolz** [comment]
Great – thank you! Done.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2991
