### ISSUE TITLE
makemigrations creates new migrations for OpenID models when steam provider is installed and openid provider is not installed

### ISSUE THREAD

**Issue by pnwparksfan** [pennersr/django-allauth#2992]
When the OpenID provider is not enabled and the [Steam provider](https://github.com/pennersr/django-allauth/blob/master/docs/providers.rst#steam) is enabled, running `makemigrations` will cause a new migration file to be created in `socialaccount/migrations/0004_openidnonce_openidstore.py`.

Steps to reproduce: 

 - Install the [example project](https://github.com/pennersr/django-allauth/tree/master/example)
 - Modify `settings.py` to add `"allauth.socialaccount.providers.steam"` to `INSTALLED_APPS` and remove/comment out `"allauth.socialaccount.providers.openid"`
 - Run `python manage.py makemigrations`
 - Go to `venv/lib/site-packages/allauth/socialaccount/migrations` and note the newly created file

Tested on v0.47.0 and current master branch at time of this report. Adding `"allauth.socialaccount.providers.openid"` to `INSTALLED_APPS` does avoid the migration issue; however, this is undesirable if a site does not need `openid` as a login option, and it seems that the openid provider shouldn't need to be installed for the steam provider to work.

**Comment by pennersr** [comment]
The Steam provider actually requires/uses the `openid` provider. So you currently cannot use `steam` without having `openid` installed. I've made a small change to detect the use of `steam` without `openid` and raise:

```django.core.exceptions.ImproperlyConfigured: The steam provider requires 'allauth.socialaccount.providers.openid' to be installed```

Closing via 69d79cb9

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2992
