### ISSUE TITLE
Google sign in broken after upgrade to 0.47.0

### ISSUE THREAD

**Issue by fleonasb** [pennersr/django-allauth#2994]
After upgrading from v0.46.0 to v.0.47.0, the Google Sign In has stopped working for me.

Under v0.46.0, when I click my "Sign In with Google", user is redirected to Google's authorization page.

Under v0.47.0, users get redirected to /accounts/google/login/?next=%2F, where an unstyled form is shown:
![image](https://user-images.githubusercontent.com/40849230/146017296-6becf141-088b-4b25-90e3-e406429d5333.png)

The "Sign In" link is redirected back to my login page. The "Sign up" link to a form page which we don't want to use (Google users are created as far as they belong to our Google Workspaces domain), and doesn't work anyway because it returns a  CSP policy error for form-action.

This is my current settings for django-allauth:
```python
# Django-allauth
ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'https'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = False
ACCOUNT_SESSION_REMEMBER = True
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
ACCOUNT_UNIQUE_EMAIL = True
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}

**Comment by fleonasb** [comment]
URL calling hierarchy with v0.46.0:

![image](https://user-images.githubusercontent.com/40849230/146020161-88862a28-c94a-45f1-8017-5bba66a8126b.png)

v0.47.0 stops at the first URL (?next=...)

**Comment by pennersr** [comment]
Please read the changelog, it is listed as a backwards incompatible change.

**Comment by majulahsingapuri** [comment]
Is there an example as to how to call the updated endpoint with POST from say a React frontend? I have been trying to send a POST request with the `csrfmiddlewaretoken` as a `URLSearchParam` in axios to authenticate using microsoft. i keep getting a CORS error but if i use the unstyled template form above, it works perfectly. any help is appreciated!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2994
