### ISSUE TITLE
Make allauth models swappable

### ISSUE THREAD

**Issue by 9mido** [pennersr/django-allauth#2997]
It is not easy to override the allauth models from within your own project and stay updated with the rest of allauth's future code changes. 

To customize the allauth models currently, you would need to override the entire allauth codebase by either placing allauth in your project folder or editing the allauth code directly in your virtual environment. If you wanted to stay updated with allauth's future code changes, you would need to do the same exact changes that the maintainer does when the allauth code gets updated which is hard to keep up with. Additionally, if you try to update allauth with pip if using a virtual environment, your customizations will most likely be lost. 

The feature request is to make allauth's models swappable with your own project models so that django developers could add / remove / change any of allauth's default models and fields and be able to do whatever they want to the allauth models without overriding the entire allauth code. This way, the django developer could make changes to allauth's models and still be able to easily update allauth when the maintainer updates it.

**Comment by pennersr** [comment]
Unfortunately, there is still no de facto standard for swappable models other than the user model. Related: https://code.djangoproject.com/ticket/19103

**Comment by pennersr** [comment]
Moved to https://codeberg.org/allauth/django-allauth/issues/2997
