### ISSUE TITLE
Signup with AJAX

### ISSUE THREAD

**Issue by sowinski** [pennersr/django-allauth#3007]
Hi,

is it possible to use AJAX for the registration instead of the signup form? 
I am not sure if I am doing something wrong. But from my current point of view it is not implemented for the registration.
Are my assumptions correct?

Thank you

**Comment by pennersr** [comment]
The signup view has this as a mixin: `AjaxCapableProcessFormViewMixin` -- so it should work.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3007
