### ISSUE TITLE
Validating weird emails 

### ISSUE THREAD

**Issue by YakPort** [pennersr/django-allauth#3012]
Hi I have a question 

I have these random emails kr.i.c.zi.k.ov.a.ya.s.v.e.tl.a.n.a@gmail.com signing up. Is there away of validating the emails before they sign up such as if it contains more than x no. of "."

Many thanks for your help

**Comment by pennersr** [comment]
Yes, see the `clean_email` method of the adapter. You're free to plug in your own logic here...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3012
