### ISSUE TITLE
Discord signup forcing user to enter first name and last name

### ISSUE THREAD

**Issue by bmull** [pennersr/django-allauth#3013]
When a user tries to signup using discord, it *always* sends them to the sign up form and requires first and last name. First and last name are not requirements in my project, so I have no idea why Discord is requiring this. Has anyone else seen this issue?

Django 3.1.6 and AllAuth 0.44.0 (but tried with 0.47.0 and same issue)

**Comment by pennersr** [comment]
Closing -- unclear, allauth does not require first/last name. So I am assuming this is something project specific.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3013
