### ISSUE TITLE
How to check authentication against specific provider?

### ISSUE THREAD

**Issue by regiov** [pennersr/django-allauth#3017]
Hi, is there any way to know if a user is currently authenticated against a specific social login provider?
I'm working on a website where certain parts will access Google Public Datasets resources and therefore will require authentication with Google. Can I somehow check this using django-allauth?

**Comment by pennersr** [comment]
You could hook up to the `user_logged_in` signal, check if `sociallogin` is in the signal kwargs, and if so, store the information you need (e.g. provider) in the session.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3017
