### ISSUE TITLE
how does one run code _before_ sign up/sign in occurs?

### ISSUE THREAD

**Issue by Pomax** [pennersr/django-allauth#3018]
For example, I want to lock down the `/accounts/...` routes so that they don't work if directly navigated to, only after the user visits the homepage. The obvious way to do this is to set a session value when the user requestss the homepage view, and then have some code that verifies that session value as a preprocessing step to allauth's `acocunts/login`. There are signals for _after_ sign up/sign in, but that's obviously too late, and I can of course monkey patch the `LoginView` class but that's pretty hacky.

Is there anything already built in for this?

**Comment by pennersr** [comment]
This could be done in a middleware of your own... in any case, this is beyond scope of allauth.

**Comment by Pomax** [comment]
Adding documentation to that effect would be nice, though, so that people _know_ it's beyond the scope of allauth itself, ideally with links to django's docs on middleware.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3018
