### ISSUE TITLE
AN ERROR OCCURED WHILE LOGGING VIA SOCIAL NETWORK

### ISSUE THREAD

**Issue by knagavarun** [pennersr/django-allauth#302]
When I'm trying to login via facebook/google/twitter through url http://127.0.0.1:8000/accounts/socialnetwork/login  ( here socialaccount is facebook/google/twitter),I'm able to login successfully and then getting redirected to http://127.0.0.1:8000/accounts/profile/,  but when I'm going to url http://127.0.0.1:8000/accounts/socialnetwork/login/callback/ I'm getting this error "an error occured while logging via social network" but could see "signout" and "change email" options if I'm already logged in.Also,when I'm going to http://127.0.0.1:8000/accounts/social/connections/, sometimes I can see only google and twitter acoounts ,sometimes only facebook account but not both depending upon my site_id in settings.py.Now,I'm really confused whether this's an issue with my callback urls  or my site domains or something else.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/302
