### ISSUE TITLE
KeyError: ('http://specs.openid.net/auth/2.0', 'assoc_type')  when using {% provider_login_url 'steam' %}

### ISSUE THREAD

**Issue by frame318** [pennersr/django-allauth#3025]
KeyError: ('http://specs.openid.net/auth/2.0', 'assoc_type') 

 when using 

{% provider_login_url 'steam' %}

TT help me pls

**Comment by pennersr** [comment]
Closing -- please include the full scenario and stack trace.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3025
