### ISSUE TITLE
Request for a separate ACCOUNT_LOGOUT_ON_PASSWORD_SET setting

### ISSUE THREAD

**Issue by smoehrle** [pennersr/django-allauth#3031]
As mentioned in #1261 I would like to have a separate option for ACCOUNT_LOGOUT_ON_PASSWORD_SET. Back than, there was no use-case for a separate option so the solution was using the existing ACCOUNT_LOGOUT_ON_PASSWORD_CHANGE option.

Here I want to give a rational for a separate option:
We currently use ACCOUNT_LOGOUT_ON_PASSWORD_CHANGE=True. Let me explain the reason with an example. Alice is a user of our website. Alice has the suspicion that her password leaked and somebody is using her account. She changes her password. All sessions get invalidated. To make this transparent to her, her current session is also invalidated, thus the setting =True.

We are currently adding a social login. Here we came across the set-password functionality and the same logout on password flow. Here we do not want to provide that *explicit feeling* of security. It's even a bit confusing from an UX perspective. So here we would like to set the setting = False.

I hope this makes our use case and the request for a separate option clear :)

**Comment by derek-adair** [comment]
@pennersr - Either modify allauth to work this way or close this one, not worth adding a setting when a user can achieve this.  If this isn't added then it is worth adding to the list of [recipes](https://github.com/pennersr/django-allauth/discussions/3427).

**Comment by pennersr** [comment]
> Here we do not want to provide that explicit feeling of security. It's even a bit confusing from an UX perspective. So here we would like to set the setting = False.


The above states that you want such an option without providing a good reason why. Closing -- I prefer not to add new settings without a really good rationale.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3031
