### ISSUE TITLE
How to get rid from example.com thing in email subject?

### ISSUE THREAD

**Issue by RajrupDasid** [pennersr/django-allauth#3037]
I am getting email from live server like this 
```
Hello from [example.com]

You're receiving this e-mail because you or someone else has requested a password for your user account.
It can be safely ignored if you did not request a password reset. Click the link below to reset your password.

http://examplexyz.com/accounts/password/reset/key/{token}/


In case you forgot, your username is xyz.

Thank you for using [example.com]
[example.com]
```
how can get rid from that example.com thing ?
I tried to customize base message and tried to add manually the site name  but nothing works
email subject has not changed

and tell me why there is no proper documentation for this things?

**Comment by DmytroLitvinov** [comment]
You need to change [Site instance](https://docs.djangoproject.com/en/4.0/ref/contrib/sites/) for your project.

**Comment by pennersr** [comment]
See `ACCOUNT_EMAIL_SUBJECT_PREFIX`

**Comment by adairhmj** [comment]
![image](https://github.com/pennersr/django-allauth/assets/44510632/771a3a28-ce2b-4249-af9a-c8a7b99a5bc6)
How should the names of these three locations be modified and who can tell me

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3037
