### ISSUE TITLE
`SOCIALACCOUNT_AUTO_SIGNUP = False` not working as expected

### ISSUE THREAD

**Issue by brsc2909** [pennersr/django-allauth#3038]
Allauth doesn't seem to be respecting `SOCIALACCOUNT_AUTO_SIGNUP = False`. The behaviour I expect is: 
 - unknown user attempts to sign in using their social account. (In my case Facebook)
 - Since no account exists for this user an error is returned.
 Whats Actually happening: 
 1. Unknown user attempts to sign in using their social account (Facebook).
 2. As expected `sociallogin.is_existing` is false so we're directed to `_process_signup(request, sociallogin)` https://github.com/pennersr/django-allauth/blob/46f4a8a72e0940b470c7345574b4eac95365a1ac/allauth/socialaccount/helpers.py#L172
3. Next when we check `is_auto_signup_allowed` we get `False`. Also as we would expect. https://github.com/pennersr/django-allauth/blob/46f4a8a72e0940b470c7345574b4eac95365a1ac/allauth/socialaccount/helpers.py#L20
4. At this stage everything seems goo right.  however the the login flow proceeds, the user is signed in but the user model is not populated correctly. I get a user created in my users table and a corresponding entry in `socialaccount_socialaccount`
 
Is it possible the user object is being created and saved before I get to `_process_signup` ? 

The Behaviour appears to be the same as whats happening in the issue below. 
https://github.com/pennersr/django-allauth/issues/1978

**Comment by pennersr** [comment]
> but the user model is not populated correctly.

What do you mean by this? I think the best way forward here would be to try and capture the issue you are experiencing in a unit test.

**Comment by mabuwasel** [comment]
I'm having the same issue, I believe what he means that the user is created with "None" username and it is seen as an empty string in Admin Panel, the account/user instance is still being created even though the auto_signup is set to False, I'm experiencing the same behavior.

**Comment by pennersr** [comment]
This issue is still unclear, so far nobody came up with a clear reproducible scenario. Auto signup is covered in a unit test. I am not sure why this is not working for you. You might want to set a breakpoint in `allauth/socialaccount/helpers.py::_process_signup()`. If you find anything wrong in allauth, please report back. Until then, I am closing this issue.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3038
