### ISSUE TITLE
Provider request: TikTok

### ISSUE THREAD

**Issue by Mukashev** [pennersr/django-allauth#3039]
Hi, is there a plan to support TikTok authentication in the future?

**Comment by pennersr** [comment]
Definitely, if somebody is willing to put in the work. Though let's not keep feature requests open for each and every provider that exists, that only floods the issue tracker. Looking forward for a PR or perhaps try sponsoring this project, thanks.

**Comment by kiliangui** [comment]
I'm working for an integration of tiktok. I'm trying to get my app verified to test the auth (Tiktok need your site to be verified to use Oauth2)

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3039
