### ISSUE TITLE
No Facebook app configured -- providers_media_js in login_extra.html

### ISSUE THREAD

**Issue by d0ru** [pennersr/django-allauth#304]
I'm trying to add social auth via Facebook on a new website. To eliminate my setup I've taken the "example" directory and let only "facebook" provider (the page  /accounts/login/ is loading properly with dummy credentials).

However, after entering the APP id and secret via admin in the Facebook social app the page /accounts/login/ doesn't load anymore and throws this:

```
Exception Type: ImproperlyConfigured
Exception Value:     No Facebook app configured: please add a SocialApp using the Django admin
Exception Location: /usr/local/lib/python2.7/dist-packages/
  allauth/socialaccount/providers/facebook/provider.py in media_js, line 86

Error during template rendering

In template /usr/local/lib/python2.7/dist-packages/
  allauth/templates/socialaccount/snippets/login_extra.html, error at line 3
```

What am I missing?

**Comment by BaburMB** [comment]
I had the same problem.
I have a question: if `settings.SITE_ID` is only one integer, how can I use authorization in my django project with two or more Social Accounts?
_(sorry, I am a newbie in Django and this is my first serious project)_

**Comment by aellerton** [comment]
Siteid is not related to social accounts. One site means say "development",
another "production". On a given site you can set up as many social
providers as you want.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/304
