### ISSUE TITLE
django-all-auth templates fails to implement mobile first Meta

### ISSUE THREAD

**Issue by officialksolomon** [pennersr/django-allauth#3041]
While using the all-auth template. i discovered the the base.html from which all other templates inherit from does not contain responsive and mobile first meta tags such as:

`<meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">`
Lack of the above listed meta tags was a major cause of unwanted result while styling with pure css and bootstrap.

Fix: Add all major modern meta tages to the head of the base.html

**Comment by pennersr** [comment]
The `allauth/templates/account/base.html` template is meant to be overridden in your own project. It does not make sense for allauth to try and offer an out of the box base template that suits all needs.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3041
