### ISSUE TITLE
Change E-Mail module uncertainity

### ISSUE THREAD

**Issue by Jayesh-Mahato** [pennersr/django-allauth#3042]
In Change E-mail menu: The Django super user signed with email shows a message that there is no email address associated with the account. However upon adding the email address again, it shows message : This e-mail address is already associated with this account.

<img width="500" alt="Screenshot 2022-03-01 at 3 44 50 PM" src="https://user-images.githubusercontent.com/5747707/156150492-4c134375-6d52-446d-b2a9-83943e52ff6f.png">

**Comment by pennersr** [comment]
Can you please list the steps needed to reproduce this scenario?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3042
