### ISSUE TITLE
auth with github is not wokring

### ISSUE THREAD

**Issue by jinaloo7** [pennersr/django-allauth#3044]
Hi I am trying to use django-allauth 0.43.0 and it is not working proeprerly.I am keep on getting extended uri with repeat param at the end like this. login/?next=/accounts/github/login/%3Fprocess%3Dlogin%26next%3D%252F
?next=/accounts/github/login/%3Fprocess%3Dlogin%26next%3D%252Faccounts%252Fgithub%252Flogin%252F%253Fprocess%253Dlogin%2526next%253D%25252F

Any idea what I did wrong while config django-allauth in my project?

**Comment by pennersr** [comment]
0.43.0 is from 2020, you might want to try upgrading.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3044
