### ISSUE TITLE
Documentation error on Microsoft Graph Provider

### ISSUE THREAD

**Issue by hugozaggo** [pennersr/django-allauth#3050]
Where: https://django-allauth.readthedocs.io/en/latest/providers.html#microsoft-graph

I believe 'tenant' should be 'TENANT', all-caps.

```
SOCIALACCOUNT_PROVIDERS = {
    'microsoft': {
        'tenant': 'organizations',
    }
}
```

**Comment by hugozaggo** [comment]
Only now noticed there are other issues opened for this, sorry!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3050
