### ISSUE TITLE
django-allauth-ui as a complimentary package

### ISSUE THREAD

**Issue by danihodovic** [pennersr/django-allauth#3051]
Hi,

I've been re-using django-allauth across a number of projects. I've ended up building a custom UI for each project and figured that I could consolidate the work into a simple package. The result is https://github.com/danihodovic/django-allauth-ui.

Do you think it would be useful for other uses? Does it make sense to mention the project in the README.md or the documentation?

**Comment by danihodovic** [comment]
Ping @pennersr

**Comment by pennersr** [comment]
Looks good, closed via ad3b9c8a

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3051
