### ISSUE TITLE
Google refresh token is never saved

### ISSUE THREAD

**Issue by robertwt7** [pennersr/django-allauth#3052]
Hi guys, 

I'm using this lib with [dj-rest-auth](https://dj-rest-auth.readthedocs.io/en/latest/installation.html#social-authentication-optional),

login and everything else works perfectly, however after login, the `token_secret` column in `socialaccount_socialtoken` is always empty. I'm using google and logging in using access_token from front end (using [next-auth[(https://next-auth.js.org) package from front end).

I already enabled the 'offline' mode from google as well.

Am i missing something?

`settings.py`

```
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": ["profile", "email", "calendar", "openid"],
        "AUTH_PARAMS": {
            "access_type": "offline",
        },
    }
}
```

`views.py` :

```
class GoogleLoginView(SocialLoginView):
    authentication_classes = (
        []
    )  # disable authentication, make sure to override `allowed origins` in settings.py in production!
    adapter_class = GoogleOAuth2Adapter
    callback_url = "http://localhost:3000"  # frontend application url
    client_class = OAuth2Client

```

I'm trying to dig into the code but not very familiar with it. can anyone please guide me on what am i doing wrong?

Cheers

**Comment by robertwt7** [comment]
Closing as this should be fixed by: https://github.com/iMerica/dj-rest-auth/pull/385

**Comment by pawelkruzynski** [comment]
I'm probably not the only one who experienced the same issue. 
What any of us might have missed during development is that Google will only provide secret_token once - during first authorization. 
So before you go any further with finding bugs in this library, make sure that you haven''t granted Google access to your application. If so, go to [https://myaccount.google.com/u/0/permissions](https://myaccount.google.com/u/0/permissions) and revoke the permission for your application. Then log in again and voila - SocialToken will be complete.  
Of course remember to apply settings from the first post of @robertwt7.

**Comment by robertwt7** [comment]
I did open a fork of `dj-rest-auth` with these line added to save the refresh token in db because by default it's not saving the refresh token:

https://github.com/robertwt7/dj-rest-auth-social/commit/015587ee5d740414a5e4423fdcb4f6d2baf7e549#diff-ddd88eb4ccdecce09b7f3e72781d12465dd72addab6ff6f035bcbc3118d80d82R110-R113


@pawelkruzynski

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3052
