### ISSUE TITLE
Social login not working when using in app browsers

### ISSUE THREAD

**Issue by minifisk** [pennersr/django-allauth#3058]
I'm using django allauth on my website, and it works fine when visiting from a regular browser. However when I visit the page from an in app browser, for example when clicking a link in Facebook messenger, neither Facebook or Google login works. The Facebook login don't do anything when clicked, and the Google login returns an error saying I'm providing a faulty callback URL.

**Comment by pennersr** [comment]
This does not clearly point to an issue in allauth, closing.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3058
