### ISSUE TITLE
[Feature Request] Simplify email change form when ACCOUNT_MAX_EMAIL_ADDRESSES is set to 1

### ISSUE THREAD

**Issue by pktiuk** [pennersr/django-allauth#3062]
Description from [configuration docs](https://django-allauth.readthedocs.io/en/latest/configuration.html)
>ACCOUNT_MAX_EMAIL_ADDRESSES(=None)
>   The maximum amount of email addresses a user can associate to his account. It is safe to change this setting for an already running project – it will not negatively affect users that already exceed the allowed amount. Note that if you set the maximum to 1, users will not be able to change their email address as they are unable to add the new address, followed by removing the old address.

I think in many cases, app developers would prefer setting value of `ACCOUNT_MAX_EMAIL_ADDRESSES` to 1.  
It would be convenient if form used for changing email addresses  would be simplified in such a case.

**Comment by pennersr** [comment]
See #3346

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3062
