### ISSUE TITLE
Cloudflare Access

### ISSUE THREAD

**Issue by darpham** [pennersr/django-allauth#3066]
Any possibility of adding Cloudflare Access to this project?
I'd like to have a single point of OIDC Authentication flow.

**Comment by pennersr** [comment]
Definitely -- ff anybody is willing to put in the effort or sponsor this activity. Having said that I prefer not to keep requests open for each and every missing provider as that would just pile up the issue tracker.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3066
