### ISSUE TITLE
Missing Polish translation

### ISSUE THREAD

**Issue by eriktelepovsky** [pennersr/django-allauth#3068]
This translation seems to be missing:

<img width="791" alt="image" src="https://user-images.githubusercontent.com/2685808/161592077-09107852-23db-4cd5-9588-5e73791ae9d9.png">

**Comment by pennersr** [comment]
Please file a pull request for translation improvements.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3068
