### ISSUE TITLE
Add python 3.10 support

### ISSUE THREAD

**Issue by jacksund** [pennersr/django-allauth#3083]
Would maintainers be willing to add python 3.10 to tox tests and official support? You can add this with the `py310` tag according the tox's [changelog](https://tox.wiki/en/latest/changelog.html#id158).

**Comment by pennersr** [comment]
Yes, feel free to submit a PR.

**Comment by jacksund** [comment]
Opened the PR. Is there a contributor guide though? I'm struggling to setup your test suite, so I haven't tested anything locally yet

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3083
