### ISSUE TITLE
Differentiate Login from Signup

### ISSUE THREAD

**Issue by chgad** [pennersr/django-allauth#3086]
Hello everyone,

I'm searching for a way to distinguish (in the response) between an actual social-login and a Signup (login for the first time), where an user account is created.

Is this somehow hidden in the Docs or currently not possible at all?

**Comment by denisemauldin** [comment]
https://django-allauth.readthedocs.io/en/latest/signals.html shows that you can use the `user_signed_up` signal for this.

**Comment by chgad** [comment]
And how does this affect the response after authentication?

The signal can be used to do additional stuff async to the authentication flow but not tell the Frontend-Part wether a new user signed up or an already existing one logged in.

**Comment by chgad** [comment]
I would expect a 201 response status for the signup case and a 200 response for the login case.

**Comment by denisemauldin** [comment]
Which URL are you expecting to return a 201 vs 200?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3086
