### ISSUE TITLE
Telegram Auth is not working 

### ISSUE THREAD

**Issue by source-home** [pennersr/django-allauth#3088]
Telegram auth is not working cause of hash on 
socialaccount\providers\telegram\views.py, line 17

**Comment by impaex** [comment]
Could you send more information?
Specifically, the full error and if possible, your implementation?

**Comment by pennersr** [comment]
Fixed via 89944bc2

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3088
