### ISSUE TITLE
Why signals work only in model.py

### ISSUE THREAD

**Issue by cyrilmarceau** [pennersr/django-allauth#3089]
Hi,

I search to create a file signals.py but if my signal is not in models.py it's not working. DO you know why ? It's possible to do this in separate file ?

Tout le monde explique que sa marche seulement dans le fichier models.py mais il n'y a pas d'explication

Thanks,

**Comment by pennersr** [comment]
This is not an issue in allauth. You need to hookup signals in code that runs when Django boots -- I would recommend the `ready` approach.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3089
