### ISSUE TITLE
Jinja support best practices

### ISSUE THREAD

**Issue by gone** [pennersr/django-allauth#3090]
I'd like to start using jinja in a project alongside allauth. I'd love to talk through the best approach and then submit some documentation around it.

1) Built in template tags - I think this is pretty straight forward. Just rebuild them using the django-jinja library.
2) Built in templates  - using the TEMPLATE_EXTENSION setting it seems pretty easy to swap that to jinja, and create a project specific copy of the different templates. Is a set of jinja templates something you'd be interested in merging into the repo? 

Is there any other details you think I'm missing?

**Comment by pennersr** [comment]
A set of Jinja templates would be best served in a repository of its own.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3090
