### ISSUE TITLE
Couldn´t install package: Django-allauth

### ISSUE THREAD

**Issue by larmc20** [pennersr/django-allauth#3093]
Pipenv install return the following error

> `[...]
> b.py", line 17, in finalize_options
> [pipenv.exceptions.InstallError]:           self.set_undefined_options('install',('install_layout','install_layout'))
> [pipenv.exceptions.InstallError]:         File "/home/tui/.pyenv/versions/3.10.4/lib/python3.10/distutils/cmd.py", line 290, in set_undefined_options
> [pipenv.exceptions.InstallError]:           setattr(self, dst_option, getattr(src_cmd_obj, src_option))
> [pipenv.exceptions.InstallError]:         File "/home/tui/.pyenv/versions/3.10.4/lib/python3.10/distutils/cmd.py", line 103, in __getattr__
> [pipenv.exceptions.InstallError]:           raise AttributeError(attr)
> [pipenv.exceptions.InstallError]:       AttributeError: install_layout. Did you mean: 'install_platlib'?
> [pipenv.exceptions.InstallError]:       [end of output]
> [pipenv.exceptions.InstallError]:   
> [pipenv.exceptions.InstallError]:   note: This error originates from a subprocess, and is likely not a problem with pip.
> [pipenv.exceptions.InstallError]: error: legacy-install-failure
> [pipenv.exceptions.InstallError]: 
> [pipenv.exceptions.InstallError]: × Encountered error while trying to install package.
> [pipenv.exceptions.InstallError]: ╰─> django-allauth
> [pipenv.exceptions.InstallError]: 
> [pipenv.exceptions.InstallError]: note: This is an issue with the package mentioned above, not pip.
> [pipenv.exceptions.InstallError]: hint: See above for output from the failure.
> ERROR: Couldn't install package: django-allauth
>  Package installation failed...
>   ☤  ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/1 — 00:00:04

**Comment by larmc20** [comment]
[output.log](https://github.com/pennersr/django-allauth/files/8672637/output.log)

**Comment by pennersr** [comment]
https://django-allauth.readthedocs.io/en/latest/faq.html#why-did-you-just-close-my-issue

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3093
