### ISSUE TITLE
Apple login doesn't bring name, just email

### ISSUE THREAD

**Issue by yandiro** [pennersr/django-allauth#3096]
I can get it to create a new user in my application, or login, in case it is not the first time, but the user has no first name nor last name.

serializers.py
```
class ApiRegisterSerializer(RegisterSerializer):
    firstName = serializers.CharField()
    lastName = serializers.CharField()

    def get_cleaned_data(self):
        cleaned_data = super().get_cleaned_data()
        cleaned_data['first_name'] = self.validated_data.get('firstName', '')
        cleaned_data['last_name'] = self.validated_data.get('lastName', '')
        return cleaned_data
```

settings.py
```
REST_AUTH_REGISTER_SERIALIZERS = {
    'REGISTER_SERIALIZER': 'floofersapp.serializers.ApiRegisterSerializer'
}
```
```
SOCIALACCOUNT_PROVIDERS = {
    'apple': {
        'APP': {
            'client_id': os.environ.get('APPLE_CLIENT_ID'),
            'secret': os.environ.get('APPLE_SECRET'),
            'key': os.environ.get('APPLE_KEY'),
            'certificate_key': APPLE_CERTIFICATE_KEY_BYTES.decode('ascii')
        }
    }
}
```
The url the user is redirected to has the `&scope=name email`.

Help would be much appreciated! Thanks!

**Comment by yandiro** [comment]
Just in case someone faces the same issue, Apple shares the name and email only the fist time the user logs in, so if you are using the same account to solve test your code, you need to login to you Apple account and delete your app from login with Apple, so it shares the name again when you log in to it.

**Comment by ayushin** [comment]
@yandiro were you able to get the the first name & last name server side or are you passing it from client?

**Comment by yandiro** [comment]
> @yandiro were you able to get the the first name & last name server side or are you passing it from client?

The name and email information is passed to the callback url you config on your service ID. But, again, only on your first login to tha app, further logins will not share name nor email.

**Comment by yandiro** [comment]
I havent tested this yet, because I need the mobile team to give me a hand, but check this out @ayushin: https://github.com/pennersr/django-allauth/issues/2718#issuecomment-1142078363

It may be a solution!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3096
