### ISSUE TITLE
Django 4.0 compatibility 

### ISSUE THREAD

**Issue by OleksiiDatsiuk** [pennersr/django-allauth#3098]
I have a question, does django-allouth support django 4.0? And if not, will there be any changes, which provide django 4.0 support?

**Comment by impaex** [comment]
Currently using django-allauth version 0.50.0 with Django version 4.0.3 on Python 3.10, and it seems to work perfectly fine.

**Comment by jaoxford** [comment]
Works fine for us.

**Comment by muhammad-afzaal** [comment]
What about Django 4.1+ versions?

**Comment by pennersr** [comment]
Test suite covers until 4.1.*

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3098
