### ISSUE TITLE
avatar sync results in SuspiciousOperation due to absolute path error

### ISSUE THREAD

**Issue by p7k** [pennersr/django-allauth#31]
https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/helpers.py#L133 produces a (file)name which later gets used downstream in a `os.path.join` by django-avatar where it tries to join it to the rest of the avatar path.

at least this should not result be an absolute path, as that would dismiss other path parts during `os.path.join`.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/31
