### ISSUE TITLE
emails are sent on login even when email_verification is optional

### ISSUE THREAD

**Issue by pykler** [pennersr/django-allauth#310]
@pennersr 

According to the `send_email_confirmation` doc string:

>    E-mail verification mails are sent:
>    a) Explicitly: when a user signs up
>    b) Implicitly: when a user attempts to log in using an unverified
>    e-mail while EMAIL_VERIFICATION is mandatory.

However, now when email verification != None (i.e. even if its optional) an email is sent everytime the user logs in (as of v0.12.0-dev).

This change seems to have been brought about by [this commit](https://github.com/pennersr/django-allauth/commit/d6aeeb13d3d728472afd97800531ea3e3189b8dc#L0R108), if this is not the desired functionality (as is indicated by the doc string above) I would like to fix it.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/310
