### ISSUE TITLE
Github Auth Faliure 

### ISSUE THREAD

**Issue by abindent** [pennersr/django-allauth#3102]
# THE ERROR
Everytime I am trying to login using the calback uri giving me `Social Network Login Failure` error.
The uri it returned : `https://3000-sinchandevo-textanalyze-trxgc1t7lzx.ws-us46.gitpod.io/api/accounts/github/login/callback/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch&state=loamwMWpis2a`

# DESCRIPTION
I have added my domain using `django.contirb.sites` and added a new social app also. But still it's not working.

The redirect_uri registered in github  `https://3000-sinchandevo-textanalyze-trxgc1t7lzx.ws-us46.gitpod.io/api/accounts/github/login/callback/`

The redirect uri the application using is `http://localhost:3000/api/accounts/github/login/callback/`

**Comment by toviszsolt** [comment]
@abindent if you check the url, it contains the error message. 😋 

`error` redirect_uri_mismatch
`error_description` The redirect_uri MUST match the registered callback URL for this application.
`error_uri` https://docs.github.com/apps/managing-oauth-apps/troubleshooting-authorization-request-errors/#redirect-uri-mismatch

**Comment by abindent** [comment]
Actually it is forcing the hostname to localhost when creating redirect uri but I want to set it to another domain.

**Comment by toviszsolt** [comment]
@abindent The name `localhost` normally resolves  to the loopback address `127.0.0.1`, and to the IPv6 loopback address `::1`

You must use the domain of the production environment.
And please read how the `oauth2` process working, because you need to pass a `callback url` during the login request and you need receive callback request on `callback url`.

**Comment by abindent** [comment]
> @abindent The name `localhost` normally resolves to the loopback address `127.0.0.1`, and to the IPv6 loopback address `::1`
> 
> You must use the domain of the production environment. And please read how the `oauth2` process working, because you need to pass a `callback url` during the login request and you need receive callback request on `callback url`.

I can't get it.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3102
