### ISSUE TITLE
Why don't we use redis sorted sets for the implmentation of rate limiting ?

### ISSUE THREAD

**Issue by lokesh1729** [pennersr/django-allauth#3103]
Hi,

I came across the rate-limiting code - https://sourcegraph.com/github.com/pennersr/django-allauth/-/blob/allauth/ratelimit.py?L46

I see that we are maintaining the list of sorted timestamps in the redis and every time we are dropping the older time intervals from the end and adding the current timestamp to the start.

The disadvantage of this approach is it takes O(n) time to drop the older intervals. I think it's better to use redis sorted sets as they give O(long) time complexity.

The combination of `ZADD` and `ZREMRANGEBYSCORE` would be sufficient I believe.

References
https://redis.io/commands/zadd/
https://redis.io/commands/zremrangebyscore/

**Comment by lokesh1729** [comment]
@pennersr ^^

**Comment by pennersr** [comment]
The reason it is not using any of that is that allauth is not using Redis, but rather the Django cache, and Redis is just one way of implementing the cache. We cannot safely assume that all projects use Redis.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3103
