### ISSUE TITLE
no tag in this repository for 0.51.0

### ISSUE THREAD

**Issue by dvzrv** [pennersr/django-allauth#3109]
Hi! I'm packaging this project for Arch Linux.
Upon trying to upgrade to 0.51.0 i realized that there is no tag and therefore also no auto-generated source tarball for 0.51.0 in this repository.

As [the source tarball on pypi.org does not contain the tests](https://github.com/pennersr/django-allauth/issues/2439) I am now blocked from upgrading.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3109
