### ISSUE TITLE
Social login for multiple User type

### ISSUE THREAD

**Issue by learningnoobi** [pennersr/django-allauth#3113]
Say I have 2 user types : 
 - buyer 
 - seller 
 
Now When I login with google or facebook using 
```{% provider_login_url 'google' %}```
How can I add extra information saying I want the user which is registered using social login to be of type buyer or seller?

**Comment by jharmon96** [comment]
You can extend the signup form and have the user select which category they fall into. Apologies for only providing a link, but I have not done this (yet). 

https://www.geeksforgeeks.org/python-extending-and-customizing-django-allauth/

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3113
