### ISSUE TITLE
Login template file is hardcoded to `login.html` but it should be respecting `ACCOUNT_TEMPLATE_EXTENSION`

### ISSUE THREAD

**Issue by violuke** [pennersr/django-allauth#3114]
The template name is hardcoded to use the extension `.html` when it shouldn't be:

https://github.com/pennersr/django-allauth/blob/4f9efa9e1d63e61a4f6cd067ef6c34b5343ef4fa/allauth/socialaccount/providers/base/mixins.py#L12

It should be working more like:

https://github.com/pennersr/django-allauth/blob/556bd220060697325d24ffce597db86a16c1e0c8/allauth/socialaccount/views.py#L30

Thank you. This is a great project.

**Comment by pennersr** [comment]
Closed` via 03abcab8

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3114
