### ISSUE TITLE
With social-login, I want to skip the signup stage

### ISSUE THREAD

**Issue by ilanlewin** [pennersr/django-allauth#312]
but it takes me to the signup page anyway after first login.

here are the settings I am using 

ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_EMAIL_VERIFICATION ='mandatory'
SOCIALACCOUNT_QUERY_EMAIL =True
SOCIALACCOUNT_AUTO_SIGNUP =True
SOCIALACCOUNT_EMAIL_REQUIRED =True
SOCIAL_ACCOUNT_EMAIL_VERIFICATION ='none'
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_REQUIRED = True

**Comment by kishorpawar** [comment]
> django-allauth (0.32.0)

```
ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_EMAIL_REQUIRED = True
SOCIALACCOUNT_QUERY_EMAIL = True
ACCOUNT_AUTHENTICATED_LOGIN_REDIRECTS = True
SOCIALACCOUNT_EMAIL_REQUIRED = ACCOUNT_EMAIL_REQUIRED
SOCIALACCOUNT_AUTO_SIGNUP = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_EMAIL_VERIFICATION = "none"
```

I have the above configuration.

My requirement is, after google/amazon authenticates user, I want to verify email is already present in `auth_user` and if `auth_user` object is active, land user on home page.

This is all happening as expected, except after I verify user is active, it redirects to `signup` page.

```
def pre_social_login(self, request, sociallogin):
    try:
	cr_user = auth_user.objects.get(email=sociallogin.user.email)
	if not cr_user.is_active:
		raise ImmediateHttpResponse(render_to_response("account/authentication_error.html"))
    except ObjectDoesNotExist as e:
	raise ImmediateHttpResponse(render_to_response("socialaccount/authentication_error.html"))
    except Exception as e:
	raise ImmediateHttpResponse(render_to_response("socialaccount/authentication_error.html"))
```

I am not understanding what parameter to set what values.
I tried SOCIALACCOUNT_AUTO_SIGNUP=True and SOCIALACCOUNT_AUTO_SIGNUP=False.
In both scenes it redirects to signup page.

Please let me know what parameters to use with what values to get my requirement working.

**Comment by kishorpawar** [comment]
I got the reason why it is being redirected to signup page.
because email id conflict.
and solution seem to be is [here](http://stackoverflow.com/a/24358708/1936024)

**Comment by kishorpawar** [comment]
The solution mentioned above and 'raise ImmediateHttpResponse(HttpResponseRedirect('/'))` doesn't seem to work.
It redirects to `/accounts/google/login/callback/?state=aDItYkDP7mZz&code=4/6jG7z70U4bCXU1h0Ig1xDohaEdsnPZKHFxvc1gbhVNg` at the end.

Any pointers? how do I redirect user to my home page?

**Comment by kishorpawar** [comment]
So the thing is I had `raise Imm...` in `try...except` so whenever it was raised it was going to `except` and `except` was showing `socialaccount/authentication_error.html`

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/312
