### ISSUE TITLE
Schoology Provider 403 Error

### ISSUE THREAD

**Issue by jwizenfeld04** [pennersr/django-allauth#3120]
I am trying to create a custom Oauth1 provider for the platform Schoology, but after following the setup to create a custom provider I continuously get a error saying Social Network Failure. After further digging into the error it is a 403 Forbidden error with the message "Invalid response while obtaining request token from "api.schoology.com"." What would be the best ways to attempt to fix this?

Schoology API Documentation: https://developers.schoology.com/api-documentation/authentication 

Error Message (printed out the request in terminal): 
{'_content': b'<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body>\r\n<center></center>\r\n</body>\r\n</html>\r\n', '_content_consumed': True, '_next': None, 'status_code': 403, 'headers': {'Server': 'awselb/2.0', 'Date': 'Mon, 27 Jun 2022 01:53:20 GMT', 'Content-Type': 'text/html', 'Content-Length': '118', 'Connection': 'keep-alive'}, 'raw': <urllib3.response.HTTPResponse object at 0x1123b8f10>, 'url': 'https://api.schoology.com/v1/oauth/request_token?oauth_callback=http%3A%2F%2F192.168.1.27%3A8000%2Faccounts%2Fschoology%2Flogin%2Fcallback%2F', 'encoding': 'ISO-8859-1', 'history': [], 'reason': 'Forbidden', 'cookies': <RequestsCookieJar[]>, 'elapsed': datetime.timedelta(microseconds=620406), 'request': <PreparedRequest [POST]>, 'connection': <requests.adapters.HTTPAdapter object at 0x112867c40>}

views.py file:
![views-file](https://user-images.githubusercontent.com/81655880/175861949-50553cad-6c5d-4cbc-9327-028415b6fc8e.png)

provider.py file
![Screen Shot 2022-06-26 at 9 56 09 PM](https://user-images.githubusercontent.com/81655880/175863013-9659cb71-914f-460c-9fe1-8376194fd09c.png)

Picture of error after overwriting the authentication_error.html file with `Code: {{ auth_error.code }}, Error: {{ auth_error.exception }}`
![Screen Shot 2022-06-26 at 9 49 59 PM](https://user-images.githubusercontent.com/81655880/175862373-8053380b-cd2e-451c-b9a7-6c77397146bf.png)

**Comment by pennersr** [comment]
I am sorry, but I am unable to provide personal support.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3120
