### ISSUE TITLE
Can django-allauth work with Google login today through dj-rest-auth, since Google Identity services is not yet supported?

### ISSUE THREAD

**Issue by helpme1** [pennersr/django-allauth#3126]
django-allauth does not seem to support the latest Google Identity services at the moment. Does this mean django-allauth is unable to work with Google login through dj-rest-auth for the time being?

**Comment by gdvalderrama** [comment]
I believe this was fixed [here](https://github.com/pennersr/django-allauth/commit/fe1d55ca7b610abf2211de3b581cd0f9f3332c9d), so it should work now

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3126
