### ISSUE TITLE
Django allauth with alternative email backends (django-post_office)

### ISSUE THREAD

**Issue by fuser-henry** [pennersr/django-allauth#3128]
Currently using the latest version of allauth (and was also using 0.41.0). 
I have having trouble with my email backend. I am using `django-post_office` as my backend and there were recent changes that have broken my custom HTML emails templates from django allauth (email_confirmation_message.html) 

The crux of the issue is that the newest version of django-post_office "cleans" the HTML template, but as a result, inline HTML and things don't work as they are supposed to, resulting in broken HTML emails. 
I am wondering, is there a setting in django allauth for django-post_office templates stored in the database, as opposed to file based templates? Is there any setting anywhere that would allow me to control where to point the path of the template?

**Comment by iarp** [comment]
In the account and socialaccount adapter's, which you can supply with your own custom one inheriting from allauths default, both have a `send_mail` method which takes in the data to be sent and sends it.

You can override that and use whatever you want to send your emails with. It's on you to render the email and everything else along with it.

https://github.com/pennersr/django-allauth/blob/master/allauth/account/adapter.py#L138

**Comment by franciscobmacedo** [comment]
For anyone coming across this issue later on, here's a simple adapater to use post office to send all auth emails:

```python

from allauth.account.adapter import DefaultAccountAdapter
from post_office import mail

class CustomAccountAdapter(DefaultAccountAdapter):
    def send_mail(self, template_prefix, email, context):
        msg = self.render_mail(template_prefix, email, context)
        mail.send(
            sender=msg.from_email,
            recipients=msg.to,
            subject=msg.subject,
            message=msg.body,
            headers=msg.extra_headers,
        )

```

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3128
