### ISSUE TITLE
NameError on basestring in Python 3

### ISSUE THREAD

**Issue by vyahhi** [pennersr/django-allauth#313]
The following lines throw "NameError: global name 'basestring' is not defined" in Python 3.3 (Django 1.6):
https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/fields.py#L25
https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/fields.py#L36

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/313
