### ISSUE TITLE
Common hook, view or adapter to prevent login based on custom logic?

### ISSUE THREAD

**Issue by mecampbellsoup** [pennersr/django-allauth#3132]
We want to prevent login for all users whose corresponding organization (`users.org_id` FK roughly in the DB schema) is not active (i.e. whose org is disabled).

Is there a single place in the code I can implement such a check or do I need to do e.g. `DefaultSocialAccountAdatper.pre_social_login` and `DefaultAccountAdapter.pre_login`?

**Comment by pennersr** [comment]
`pre_login` as that one takes care of both social and regular logins.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3132
