### ISSUE TITLE
CSS styles not being applied

### ISSUE THREAD

**Issue by lucasbracher** [pennersr/django-allauth#3133]
Hello, all!

I'm trying to load /accounts/email/ and /accounts/password/change/ , but when I try that, the styles on form are not loading properly.
There are no 404 messages on developers interface, I installed as prescribed and I don't know what's happening.
How to solve that problem?
Here are 2 screenshots showing the problem:

https://pasteboard.co/UPbFvT8qF5aG.png
https://pasteboard.co/K49rmUg1K5TO.png

Thanks!

**Comment by pennersr** [comment]
https://django-allauth.readthedocs.io/en/latest/faq.html#why-did-you-just-close-my-issue

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3133
