### ISSUE TITLE
document Authelia usage

### ISSUE THREAD

**Issue by alexanderadam** [pennersr/django-allauth#3134]
First of all: [the documentation of providers is marvellous](https://github.com/pennersr/django-allauth/blob/master/docs/providers.rst)! :heart: 
I just thought that it would probably be helpful to add [Authelia](https://www.authelia.com/) to the documented providers.

It's surely not a high priority wish but rather a nice to have.
Have a splendid day!

**Comment by pennersr** [comment]
Feel free to submit a PR to extend the documentation -- though, keeping a ticket open for this is not moving things forward, hence, closing.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3134
