### ISSUE TITLE
Support for login via url

### ISSUE THREAD

**Issue by matmair** [pennersr/django-allauth#3136]
Hi there @pennersr ! Thank you for this great library.
Would you be interested in the login page supporting login via the url? Something like this `https://example.org/accounts/login/?login=allaccess&password=nolimits`.

I just implemented it for a project and would love to provide a PR to upstream if you are interested.
Ref: https://github.com/inventree/InvenTree/pull/3465

**Comment by pennersr** [comment]
No, for reasons mentioned here: https://owasp.org/www-community/vulnerabilities/Information_exposure_through_query_strings_in_url

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3136
