### ISSUE TITLE
[Feature Proposal] Add ALLOW_LOGIN_WITH_NON_PRIMARY_EMAIL setting

### ISSUE THREAD

**Issue by mecampbellsoup** [pennersr/django-allauth#3139]
In our application, we allow users to "change" their email, but it's really just a workflow that combines "add email" and "verify email" to add a new email to their account and subsequently verify it via an email link.

We noticed that the _formerly_ primary email address however can still be used to login, and this threw us off.

Would you be open to a setting that restricted logins to be valid if and only if the _currently primary_ email address is used?

**Comment by mecampbellsoup** [comment]
> We noticed that the _formerly_ primary email address however can still be used to login, and this threw us off.

@pennersr is this the expected/correct behavior, BTW?

**Comment by pennersr** [comment]
> Would you be open to a setting that restricted logins to be valid if and only if the currently primary email address is used?

If there were a setting, would you able to explain under what circumstances it would make sense to turn this on/off? What issues are you experiencing with the current behavior -- as in, why is it an issue at all that the user can login with any of the emails (s)he has attached to his/her account, including the former primary one?

**Comment by mecampbellsoup** [comment]
> > Would you be open to a setting that restricted logins to be valid if and only if the currently primary email address is used?
> 
> If there were a setting, would you able to explain under what circumstances it would make sense to turn this on/off? What issues are you experiencing with the current behavior -- as in, why is it an issue at all that the user can login with any of the emails (s)he has attached to his/her account, including the former primary one?

In our application, we present the feature as "_change_ your email address" and not "add an additional email address".

However on the backend we don't want to delete email addresses since deleting customer information ad hoc is a no no and we have regulations like GDPR we need to implement in a coherent, unified manner (i.e. a customer can delete information but not piecemeal, rather all at once via a request to do so). Moreover we feed email addresses given to us by our users into our fraud risk scoring algorithm, and data cannot be removed from that service (it's a 3rd party service).

So, we want to continue to support our "change email" feature (which is really just using allauth's add and very email endpoints under the hood), and if a user changes their email address that should be the only address with which they can login because we use `iam_user.email` (not `allauth.account_emailaddress`) throughout our code base to uniquely identify the logged in user. (In theory we could move away from that and instead use `iam_user.uid` or something, and then this dependency on a potentially changing `iam_user.email` value would go away.)

**Comment by pennersr** [comment]
The allauth email address table is not meant to keep a record of historic email addresses. That would raise problems, for example, if a user changes his email address to a new one, you would expect that the old one is free to use. Yet, in your case, the old one is still taken. That may also collide with the right to erasure (https://gdpr-info.eu/art-17-gdpr/) -- as users can detect that even though they remove/change their email address you are still keeping it around. All in all, if you have a need for keeping historic email addresses around, please consider creating your own email address model for just this purpose so that it does not collide with regular signup logic.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3139
