### ISSUE TITLE
When having whitespace in OSM username "user" is shown instead of actual name

### ISSUE THREAD

**Issue by hholzgra** [pennersr/django-allauth#3140]
My OpenStreetMap username / login is "Hartmut Holzgraefe" with a space between first and last name.

When I log in via the OpenStreetMap provider `{{user.username}}` and `{% user_display.user %}` in templates get replaced with the fixed sting `user` instead of my real user name.

When I log in using a test user account with no whitespace in it I get the actual login name replaced as expected.

There is nothing in the OpenStreetMap provider that would explain this as far as I can tell, so the problem seems to be within allauth itself?

**Comment by iarp** [comment]
What does the User table itself have for the username value?

**Comment by pennersr** [comment]
This is due to:

```
>>> from allauth.account.adapter import get_adapter
>>> get_adapter().clean_username("a b")Traceback (most recent call last):
  File "<console>", line 1, in <module>
django.core.exceptions.ValidationError: ['Enter a valid username. This value may contain only letters, numbers, and @/./+/-/_ characters.']
>>> 
```

**Comment by pennersr** [comment]
Moved to https://codeberg.org/allauth/django-allauth/issues/3140
