### ISSUE TITLE
Let me help with russian describe.

### ISSUE THREAD

**Issue by Ananau** [pennersr/django-allauth#3141]
[django.po.zip](https://github.com/pennersr/django-allauth/files/9338908/django.po.zip)
It's a zip with django.po for russian translation to folder allauth\locale\ru\LC_MESSAGES\ 

Thank's for your module.
NO wars!

**Comment by pennersr** [comment]
Thanks, can you please turn this into a pull request?

**Comment by pennersr** [comment]
Included via 89bd7596

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3141
