### ISSUE TITLE
Integration with fusionauth?

### ISSUE THREAD

**Issue by proffalken** [pennersr/django-allauth#3142]
Hello,

I'm hoping to use [Inventree](https://inventree.readthedocs.io/en/latest/) for our makerspace and connect it to [FusionAuth](https://fusionauth.io/) via django-allauth (Inventree already uses this library), however I can't see FusionAuth listed as an Auth provider.

I know that FusionAuth will provide generic OAuth credentials, but I can't see how to configure a generic OAuth provider in the django-allauth config, and FusionAuth is not listed.

Have I missed a step in the documentation somewhere?

**Comment by pennersr** [comment]
Note sure what you mean by generic, but likely this is solved by https://github.com/pennersr/django-allauth/pull/3165

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3142
