### ISSUE TITLE
Login page `?next=` query parameter not preserved when user enters invalid credentials

### ISSUE THREAD

**Issue by acidtv** [pennersr/django-allauth#3143]
When the login url has a `next` query parameter and the user enters the wrong credentials before entering the correct ones, he is not redirected to the 'next' url.

**Comment by iarp** [comment]
Have you altered `account/login.html` at all? The following hidden field needs to exist on the form https://github.com/pennersr/django-allauth/blob/master/allauth/templates/account/login.html#L39

**Comment by acidtv** [comment]
Ah, we did have a hidden `next` field, but it was not implemented properly. Thanks for checking!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3143
