### ISSUE TITLE
Blank screen after user login with an unconfirmed email

### ISSUE THREAD

**Issue by BoPeng** [pennersr/django-allauth#3144]
With `ACCOUNT_EMAIL_REQUIRED=True`, what is the intended behavior if a user tries to login to a newly created account without confirming the email address? I assume some error message will be shown to ask users to look for an email address or some mechanism to re-send the email (by displaying `account_inactive.html`), but my website shows a blank screen. 

The user could encounter this problem if the confirmation email is expired because he could not login to resend email, nor can he re-register because the account already exists.

**Comment by BoPeng** [comment]
The issue caused by a customized adaptor.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3144
