### ISSUE TITLE
SOCIALACCOUNT_EMAIL_REQUIRED False with ACCOUNT_EMAIL_VERIFICATION mandatory leads to "stuck" users

### ISSUE THREAD

**Issue by riconnon** [pennersr/django-allauth#3146]
If using the following settings:
```
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_EMAIL_REQUIRED = True
SOCIALACCOUNT_EMAIL_REQUIRED = False
```

Users are able to signup with a social account, then not provide an email address, but will still be expected to verify their non-email address.
I think it would make sense for `ACCOUNT_EMAIL_VERIFICATION` to indicate that it is required iff the user _has_ an email address, but not otherwise.

**Comment by gerysalut1234567891011** [comment]
https://www.facebook.com/ninda.lestary.148

**Comment by gerysalut1234567891011** [comment]
ninda.lestary.148

**Comment by derek-adair** [comment]
A rare valid bug!!!

I disagree w/ the users suggestion here.  These are conflicting settings and allauth should probably detect this and throw a warning.

**Comment by derek-adair** [comment]
@pennersr looks like we have some kinda spam bot here? Dunno what this facebook link is about.

**Comment by riconnon** [comment]
@derek-adair 
fwiw the configuration I would like is that a user must provide a valid email and verify it if they do not setup any kind of social auth during signup

**Comment by flange-ipb** [comment]
Isn't the `SOCIALACCOUNT_EMAIL_VERIFICATION` configuration option addressing exactly this issue?

**Comment by riconnon** [comment]
`SOCIALACCOUNT_EMAIL_VERIFICATION` seems to require that all users must verify an email, which they cannot if they did not provide one.

**Comment by derek-adair** [comment]
I am trying to understand what your specific use case for this configuration is, could you elaborate why you feel the need to verify emails if they do not sign up w/ social?  It seems like you should either rely on it being verified or not.

**Comment by riconnon** [comment]
The use-case is to avoid trivial account signup "spam".
In the case of a social account I'm offloading the handling of that to the third-party provider, but if they signup directly I want the email verification to raise the bar a little on how easy it is to repeatedly signing up.

**Comment by derek-adair** [comment]
I'm not asking "why verify email addresses for direct signups".  I'm asking why not verify email for both social signups AND direct signups?  If "spam" is your concern than it would seem important that your 3rd party services provide you with an email address you can verify.

**Comment by pennersr** [comment]
Moved to https://codeberg.org/allauth/django-allauth/issues/3146
