### ISSUE TITLE
DoesNotExist at /accounts/google/login/ SocialApp matching query does not exist.

### ISSUE THREAD

**Issue by gamer-snave** [pennersr/django-allauth#3147]
**No Direct Solution to this problem still.**
All answers are the same and all revolve between changing SITE_ID, which really does NOT work, tried up to ID 5, and here am still web crawling >>
@pennersr 
@kiash254

**Comment by Kiash254** [comment]
🥳🥳 let's join revolution

**Comment by pennersr** [comment]
If the SocialApp is not found there is a configuration issue in your own project. There is no bug in allauth that causes this, hence, there is "still" no solution to this problem, nor won't there be any in the foreseeable future. 

FWIW, if configuration via the DB is giving you problems, note that you can also use configuration in settings:

```
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            "client_id": os.environ[("GOOGLE_OAUTH_CLIENT_ID"],
            "secret": os.environ[("GOOGLE_OAUTH_SECRET"],
        },
    },
}
```

**Comment by gamer-snave** [comment]
Working perfectly, Thanks.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3147
