### ISSUE TITLE
Prevent user from logging in with non-primary email address

### ISSUE THREAD

**Issue by mecampbellsoup** [pennersr/django-allauth#3148]
Is there a way to achieve this behavior presently?

One hacky approach might be to mark the no-longer-primary email address as not verified...

Related to #3139.

**Comment by iarp** [comment]
You can create your own authentication backend inheriting from allauths and overriding `_authenticate_by_email` https://github.com/pennersr/django-allauth/blob/master/allauth/account/auth_backends.py#L44

You want to mimic everything in the current `_authenticate_by_email` except implement your own version of `filter_users_by_email` as you can see here https://github.com/pennersr/django-allauth/blob/master/allauth/account/utils.py#L387

**Comment by derek-adair** [comment]
Close.  The suggestion in #3139 has already been rejected so this can as well.  Users seeking to implement this behavior can follow @iarp's quite thorough response.

Cheers!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3148
