### ISSUE TITLE
Facebook Developer Alert: Your app asks for read and write permissions at the same time. 

### ISSUE THREAD

**Issue by vinodpandey** [pennersr/django-allauth#315]
There is facebook developer alert with below message:

Your app asks for read and write permissions at the same time. You should only ask for write permissions when a user tries to share something to Facebook.

Below is the social accounts provider configuration used for facebook.

{
          'SCOPE': ['email', 'publish_stream'],
          'AUTH_PARAMS': { 'auth_type': 'reauthenticate' },
          'METHOD': 'oauth2' ,
          'LOCALE_FUNC': lambda request: 'en_US'
         }

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/315
