### ISSUE TITLE
Github Bad Verification Code

### ISSUE THREAD

**Issue by mustansirgodhrawala** [pennersr/django-allauth#3153]
Using basic github oauth behind nginx reverse proxy with SSL termination throws a 504 error. 

The error from github reads as such:

{'provider': 'github', 'code': 'unknown', 'exception': OAuth2Error("Error retrieving access token: b'error=bad_verification_code&error_description=The+code+passed+is+incorrect+or+expired.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-oauth-app-access-token-request-errors%2F%23bad-verification-code'")}

**Comment by pennersr** [comment]
https://django-allauth.readthedocs.io/en/latest/faq.html#why-did-you-just-close-my-issue

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3153
