### ISSUE TITLE
Need help with authentik provider

### ISSUE THREAD

**Issue by acul009** [pennersr/django-allauth#3154]
Hi, I just tried to create an authentik provider by copying the kkeycloak code.

But this is my first time writing pythong/jango and I'm kind of lost on how to format the code and even how to test it.

Can someone give me a quick rundown on what I actually need to do here?

Branch can be found here: https://github.com/acul009/django-allauth/tree/authentik

**Comment by pennersr** [comment]
Looking forward to see another provider, though I am unable to offer personal support...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3154
