### ISSUE TITLE
Unable to start this project in local

### ISSUE THREAD

**Issue by rakaliku** [pennersr/django-allauth#3157]
Hi Everyone,

I am trying to run this project in local but not able to. Getting below error in local host
Bad Request (400)

I am basically at beginner level, anyone can help me out here.

**Comment by pennersr** [comment]
https://django-allauth.readthedocs.io/en/latest/faq.html#why-did-you-just-close-my-issue

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3157
