### ISSUE TITLE
Cannot implement apple sign-in 

### ISSUE THREAD

**Issue by djangojeng-e** [pennersr/django-allauth#3158]
Hi, 

I am struggling in getting apple signin implemented on my django website using all-auth. 
I've had no issues implementing other social logins such as Google, Facebook etc. However, when it came down to Apple, it is driving me to nowhere. 

As per documented, I've added the following codes in settings.py. 

```
# apple login settings 

SOCIALACCOUNT_PROVIDERS = {
    "apple": {
        "APP": {
            # Your service identifier.
            "client_id" : "myexample.com",

            # The Key ID (visible in the "View Key Details" page).
            "secret": "232LWSA.com.myexample",


            "key": "4EDIOWA1Z",

           
            "certificate_key": """----BEGIN PRIVATE KEY----
MEIUWHDKFOEJKVNCJDUEFNQO33_DIEKFJIEHQHQ1EIjkjdiekf
2jieEDEWAX----END PRIVATE KEY----"""
        }
    }
}
```

I think I've done right jobs obtaining relevant `ServiceID`, `client_id`, `key ID` and `certificate_key` from my apple developer  account as it redirects to apple page after clicking `Sing in with Apple` button. 

When I enter correct apple account on apple page and return to my site, I get the following error on `/accounts/apple/login/callback/finish`. 

```
ValueError at /accounts/apple/login/callback/finish/

('Could not deserialize key data. The data may be in an incorrect format, it may be encrypted with an unsupported algorithm, or it may be an unsupported key type (e.g. EC curves with explicit parameters).',
[_OpenSSLErrorWithText(code=503841036, lib=60, reason=524556, reason_text=b'error:1E0801C:DECODER routines::unsupported')]) 
Request Method: GET 
Request URL : https://myexample.com/accounts/apple/login/callback/finish/?code=djfkjeojfokdjfkojioe337373737.38drrr.fgeiekd-usssaw-HIcaeq32B
django Version : 4.04 
Exception Type : ValueError 

```

Is django-allauth limited to support  apple sigin-in? Or, am I missing something on this?

**Comment by pennersr** [comment]
https://django-allauth.readthedocs.io/en/latest/faq.html#why-did-you-just-close-my-issue

**Comment by ccaputo** [comment]
In case anyone else runs into this, consider doing a `print(SOCIALACCOUNT_PROVIDERS)` after defining it, to make sure certificate_key looks as intended. In my case, I wasn't properly loading the private key into certificate_key and thus OpenSSL was not able to deserialize it.

@djangojeng-e in the above, the lack of a newline before `----END PRIVATE KEY----` may be the issue.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3158
