### ISSUE TITLE
[Question] Social provider VERIFIED_EMAIL

### ISSUE THREAD

**Issue by mecampbellsoup** [pennersr/django-allauth#3159]
I understand it's possible to treat emails received from a specific IDP via each provider's `VERIFIED_EMAIL` configuration, e.g.:

```
SOCIALACCOUNT_PROVIDERS = {
    "github": {
        # For each provider, you can choose whether or not the
        # email address(es) retrieved from the provider are to be
        # interpreted as verified.
        "VERIFIED_EMAIL": True
    },
```
This has the effect of treating all Github emails as verified in allauth's DB.

However, what is the default behavior? Does the IDP provide some indication/flag telling us whether the Github user has _verified their email on Github_ or not?

**Comment by iarp** [comment]
Default is False: https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/providers/base/provider.py#L109

Github does indicate if an email address is considered verified on their side and that data is returned in one of the two following api calls that your server makes after a user logs in. However the verified flag does not seem to be considered when looking at the email addresses on file.

* `https://api.github.com/user` which returns https://docs.github.com/en/rest/users/users#get-the-authenticated-user
* `https://api.github.com/user/emails` which returns https://docs.github.com/en/rest/users/emails#list-email-addresses-for-the-authenticated-user

If I recall correctly I believe this stems from an issue where too many websites will mark an email address as verified without actually verifying the email address. You can see that in play with facebook which you can read here: https://django-allauth.readthedocs.io/en/latest/providers.html#facebook under the `VERIFIED_EMAIL` header.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3159
