### ISSUE TITLE
How can I get google.oath2.credentials.Credential object to pass to the Drive API?

### ISSUE THREAD

**Issue by quanhd-0235** [pennersr/django-allauth#3160]
After using google authentication, how can I get google.oath2.credentials.Credential object to pass to the Drive API?
I stuck in this problem for a long time, could anyone have a solution? Any help is appreciated!

**Comment by iarp** [comment]
You import the Credential class and initialize it with data from the SocialToken object for the google account.

    from allauth.socialaccount.models import SocialAccount, SocialApp

    from google.oauth2.credentials import Credentials

    token = SocialToken.objects.get(pk=...)
    client = SocialApp.objects.get(provider='google')  # assuming you use SocialApp entries, otherwise use django.conf.settings entry.

    scopes = ['profile', 'email']

    creds = Credentials(
            token=token.token,
            refresh_token=token.
            scopes=scopes,
            token_uri='https://accounts.google.com/o/oauth2/token',

            client_id=client.client_id,
            client_secret=client.secret
        )

If the credential is expired (`if not creds.valid or creds.expired:`), you'll need to refresh them with `creds.refresh(Request())` and update the SocialToken entry that you pulled the credentials from

    from google.auth.transport.requests import Request

    if creds.refresh_token:
        token.token_secret = creds.refresh_token

    token.token = creds.token
    token.save()

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3160
