### ISSUE TITLE
Changing primary key for user model causes No Reverse Match

### ISSUE THREAD

**Issue by mustansirgodhrawala** [pennersr/django-allauth#3161]
Reverse for 'account_reset_password_from_key' with keyword arguments '{'uidb36': 'mgodhrawala402@gmail.com', 'key': 'bbz25w-9c6941d5cb69a49883f15bc8e076f504'}' not found. 1 pattern(s) tried: ['accounts/password/reset/key/(?P<uidb36>[0-9A-Za-z]+)-(?P<key>.+)/$']

**Comment by iarp** [comment]
Why would you be using the email address as a primary key for your user model? What do you expect to happen when the user changes their email address?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3161
