### ISSUE TITLE
How to ignore the continue page when using providers 

### ISSUE THREAD

**Issue by t-el** [pennersr/django-allauth#3162]
When I use a provider such as github , I get redirected to a continue page , I want to ignore this page

**Comment by iarp** [comment]
What url are you redirected to?

**Comment by t-el** [comment]
> What url are you redirected to?

outh/github/login

**Comment by iarp** [comment]
Is that on your web server side or githubs side? If its on github.com side theres nothing that can be done.

**Comment by mehraG** [comment]
@t-el add "SOCIALACCOUNT_LOGIN_ON_GET=True" in settings.py file.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3162
