### ISSUE TITLE
Best place to add login/logout/passwordchange to logentry

### ISSUE THREAD

**Issue by sowinski** [pennersr/django-allauth#3163]
Hi,

I would like to store in LogEntry when a user login / logout / or change his password.

Where would you place this code?

Thank you

**Comment by iarp** [comment]
https://django-allauth.readthedocs.io/en/latest/signals.html

* user_logged_in
* user_logged_out
* password_changed

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3163
