### ISSUE TITLE
How to use redirect view to OAuth2 authentication URL?

### ISSUE THREAD

**Issue by johnvonneumann7** [pennersr/django-allauth#3166]
I am trying to implement social login using dj-rest-auth + allauth, but
I think that before, if the OAuth2 authentication URL was Google, it was automatically redirected to Google when accessing `/rest-auth/google/url/` like the following (urls.py), but now, once you go to the login page generated by allauth, you have to press the "continue" button to get to the social login page. You have to go to the login page and press the "continue" button to get to the social login page. (See image).

How can I skip directly to the Google authentication page?

```
from allauth.socialaccount.providers.google import views as google_views

path("rest-auth/google/url/", google_views.oauth2_login),
```

![image](https://user-images.githubusercontent.com/78252058/193985714-8f0be429-9abd-4169-b003-303c77c28775.png)

**Comment by iarp** [comment]
https://django-allauth.readthedocs.io/en/latest/configuration.html

    SOCIALACCOUNT_LOGIN_ON_GET

**Comment by johnvonneumann7** [comment]
Thank you. This is perfect.

**Comment by nour1029** [comment]
> https://django-allauth.readthedocs.io/en/latest/configuration.html
> 
> ```
> SOCIALACCOUNT_LOGIN_ON_GET = True
> ```
Thanks

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3166
