### ISSUE TITLE
How To / Feature Request: Access User Current Login Provider

### ISSUE THREAD

**Issue by brittandeyoung** [pennersr/django-allauth#3168]
I have been searching the docs for this information but am unable to find it. Is there a way to identify how the user logged in for the current session? 

For example, If I where to log in with `Github` I would be able to determine that in a view. My use case it to allow companies to require their employees to use a certain provider when accessing their organization data. I would like to be able to identify  how the user is currently logged in (which provider or local login they used). I know there is a way to find all social links for a user, but I am interested in finding out how the user is currently logged in. 

If this is not a feature I would like to request this be added as a feature =) . I would also be willing to help implement it.

To me this would be awesome to have available as a part of the `request.user` object or something similar. You could access it by using something like `request.user.loginmethod`

**Comment by iarp** [comment]
You could use the `user_logged_in` signal. There is a parameter passed called `sociallogin` which contains the users SocialLogin object. That object has an `.account` property which is the SocialAccount which in turn has the providers name under `.provider`

    sociallogin.account.provider

**Comment by brittandeyoung** [comment]
@iarp thank you for your response. This is exactly what I was looking for. 

I am still a little new to Django. From reading I feel that the user session would be the best location to store this data. Does that sound right? Or would you have another suggestion for storing this data on login?

**Comment by iarp** [comment]
I would think so because that particular session will have logged in using that method and its session specific.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3168
