### ISSUE TITLE
[social signup] Require first and last name attributes

### ISSUE THREAD

**Issue by mecampbellsoup** [pennersr/django-allauth#3170]
Hi,

I would like to fail or at least pause social signup when the user's GitHub/Google/etc. profile does not include non-empty string values for fields like first name and last name.

Is this currently possible through configuration of any sort?

**Comment by mecampbellsoup** [comment]
For more context, I have `SOCIALACCOUNT_AUTO_SIGNUP = True` - does this bypass the usage of my `SOCIALACCOUNT_FORMS` override entirely?

```python
# gatekeeper/settings.py
SOCIALACCOUNT_FORMS = {"signup": "iam.socialaccount.forms.MySignupForm"}
```

```python
# iam/socialaccount/forms.py
from allauth.socialaccount.forms import SignupForm
from django import forms


class MySignupForm(SignupForm):
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)

    def save(self, request):

        # Ensure you call the parent class's save.
        # .save() returns a User object.
        print("request", request)
        raise Exception
        user = super().save(request)
        print("user", user)
        # Add your own processing here.

        # You must return the original result.
        return user
```

It seems that no matter what, I never reach the `raise Exception` line above in my social signup form override class.

I have verified that allauth is configured properly w/ the override:

```
>>> get_form_class(app_settings.FORMS, "signup", SignupForm)
<class 'iam.socialaccount.forms.MySignupForm'>
```

**Comment by iarp** [comment]
With `SOCIALACCOUNT_AUTO_SIGNUP = True` it skips the form:

https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/helpers.py#L23

**Comment by pennersr** [comment]
Indeed, you need to turn off auto signup so that the user can fill in those fields.

**Comment by mecampbellsoup** [comment]
Well what I'm requesting is a bit more nuanced than that.

I'd like to express a condition such that "if a social signup lacks a first or last name from their (GitHub/Google/etc.) user profile, fail auto signup". Otherwise I want auto signup to proceed.

**Comment by pennersr** [comment]
You can override the following adapter method to insert your own auto signup logic:

```
def is_auto_signup_allowed(self, request, sociallogin):
```

**Comment by eipy** [comment]
Hi, I'm trying to customize the signup form with little success. Any suggestions on what to check would be very welcome. 

I would like to either hide the email field from the form or display it as disabled (greyed out). Preferably former. The user should only pick out a user name. 

Below is how I configured the forms based on the docs, but when I get to http://localhost:8000/accounts/social/signup/, I still see both email and username fields pulled in by the {{ form.as_p }} template tag. 

My settings.py contains: 
`SOCIALACCOUNT_AUTO_SIGNUP = False
SOCIALACCOUNT_FORMS = {
    'signup': 'users.forms.CustomSignUpForm'
}`

My forms.py looks like this:
`from django import forms as d_forms
from allauth.socialaccount.forms import SignupForm

class CustomSignUpForm(SignupForm):

    class Meta:
        model = User
        fields = ['username']

    def save(self, request):

        # Ensure you call the parent class's save.
        # .save() returns a User object.
        user = super(CustomSignUpForm, self).save(request)

        # Add your own processing here.

        # You must return the original result.
        return user`

**Comment by eipy** [comment]
> Hi, I'm trying to customize the signup form with little success. Any suggestions on what to check would be very welcome.
> 
> I would like to either hide the email field from the form or display it as disabled (greyed out). Preferably former. The user should only pick out a username.
> 
> Below is how I configured the forms based on the docs, but when I get to http://localhost:8000/accounts/social/signup/, I still see both email and username fields pulled in by the {{ form.as_p }} template tag.
> 
> My settings.py contains:
> 
> `SOCIALACCOUNT_AUTO_SIGNUP = False` `SOCIALACCOUNT_FORMS = {'signup': 'users.forms.CustomSignUpForm'}`
> 
> My forms.py looks like this:
> 
> ```
> from django import forms as d_forms
> from allauth.socialaccount.forms import SignupForm
> 
> class CustomSignUpForm(SignupForm):
> 
>     class Meta:
>         model = User
>         fields = ['username']
> 
>     def save(self, request):
> 
>         # Ensure you call the parent class's save.
>         # .save() returns a User object.
>         user = super(CustomSignUpForm, self).save(request)
> 
>         # Add your own processing here.
> 
>         # You must return the original result.
>         return user
> ```

I was able to disable it with the following:
```
class CustomSignUpForm(SignupForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].widget.attrs['disabled'] = True

    class Meta:
        model = User
        fields = ['username']

    def save(self, request):
        user = super(CustomSignUpForm, self).save(request)
        return user
```

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3170
