### ISSUE TITLE
why when adding email to reset password give me this error ? 

### ISSUE THREAD

**Issue by khaldon** [pennersr/django-allauth#3171]
login.html
```
  <a class="mt-3 d-block text-primary" href="{% url 'account_reset_password' %}">Forget Password?</a>
```
I enter the email gives me this error 
![image](https://user-images.githubusercontent.com/10290194/196549207-67deeb27-1401-4185-80c5-0bb92bcb42a2.png)

**Comment by iarp** [comment]
We need to see more of the traceback error message to determine where it's actually failing. If you can make it happen again, get the traceback printed in the console and paste that into a code block here.

**Comment by pennersr** [comment]
Closing -- looks like a project settings issue.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3171
