### ISSUE TITLE
Installation warning with pip v22.3

### ISSUE THREAD

**Issue by dkirkham** [pennersr/django-allauth#3172]
When installing django-allauth with pip v22.3, the following warning is issued:

> DEPRECATION: django-allauth is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559

Impacts: django-allauth v0.44.0, 0.50.0, 0.51.0 and probably other versions
Environment: Python 3.8, pip v22.3 with venv

Pip v23.1 is scheduled for April 2023.

**Comment by pennersr** [comment]
See: 33bc4153 and ca50b5e2

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3172
