### ISSUE TITLE
After reset password from key, redirects to login page to "password/set/" view

### ISSUE THREAD

**Issue by Bartek1995** [pennersr/django-allauth#3174]
I found problem:

If user try to change his password from reset link, application redirects to login page.

This happening becouse we have setted action url in form
`            <form method="POST" action="{% url 'account_set_password' %}" `

If you remove that, changing password from reset link works properly.
`            <form method="POST" class="password_set">`

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3174
