### ISSUE TITLE
Force Login for Google Social

### ISSUE THREAD

**Issue by cbirchby** [pennersr/django-allauth#3176]
I'm using django-allauth specifically and only for Google authentication. I'm experiencing a few odd issues:

- Logout from a Chrome browser and the user is still remembered upon the next login. The user is never redirected to a Google login.

- Log out from a Safari browser and the user is NOT remembered upon the next login, therefore they are directed to the Google login at the next login attempt.

The desired result would be to always force users to go through the full login process. They should be directed to Google for their email and password. This allows users to share a computer and switch accounts.

I've experimented with multiple configuration settings, but with no luck. Here are the current configs:

`ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'

ACCOUNT_AUTHENTICATED_LOGIN_REDIRECTS = True
LOGIN_REDIRECT_URL = '/stores/store_list'

ACCOUNT_LOGOUT_REDIRECT_URL = 'home'

ACCOUNT_SESSION_REMEMBER = False
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 60

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'offline',
            'auth_type': 'reauthenticate',
        }
    }
}`

**Comment by iarp** [comment]
Add `"prompt": "consent"` to `AUTH_PARAMS` for google.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3176
