### ISSUE TITLE
Increasing entropy of the state parameter

### ISSUE THREAD

**Issue by knc6** [pennersr/django-allauth#3177]
Currently the package uses 12 character random string for `state` parameter.
It would be great to increase it to 16 characters or more to enhance security (increase entropy).
https://github.com/pennersr/django-allauth/blob/e49df55815e13a3e59e51fc9e4764f3af2a035d0/allauth/socialaccount/models.py#L300

**Comment by some1ataplace** [comment]
Similar to #2997

**Comment by pennersr** [comment]
Closed via 38d0a564

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3177
