### ISSUE TITLE
Snapchat Missing PKCE

### ISSUE THREAD

**Issue by AdamWP** [pennersr/django-allauth#3178]
When trying to integrate Snapchat I'm getting "Missing PKCE parameters". If I add code_challenge I can get past that error however the when snapchat redirects back to my website I get Social Network Login Failure.  Is there any way to handle PKCE on the redirect?

SOCIALACCOUNT_PROVIDERS = {
    'snapchat': {	
        'APP':{
            'client_id': SNAPCHAT_CLIENT_ID,
            'secret': SNAPCHAT_CLIENT_SECRET,
        },
	 'AUTH_PARAMS': {
            'code_challenge_method': 'S256',
	   'code_challenge': '362t6atUC1Fz'
        }
    },
}

**Comment by pennersr** [comment]
PKCE support as added here: c1b8fe5e

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3178
