### ISSUE TITLE
Login Provider Google

### ISSUE THREAD

**Issue by muhamadanjar** [pennersr/django-allauth#3183]
how do i login without new page like this 
![Screenshot from 2022-11-11 09-32-53](https://user-images.githubusercontent.com/10927965/201250964-18876bb7-4f7d-448d-ae43-1c90fc82439b.png)

this is my login page
![Screenshot from 2022-11-11 09-41-52](https://user-images.githubusercontent.com/10927965/201251182-5b2cad4a-d56d-4270-b966-7562a9a67a38.png)

i want to direct to login page google
![Screenshot from 2022-11-11 09-46-06](https://user-images.githubusercontent.com/10927965/201252059-e10be32c-ce10-40ce-b8d4-279f3c4a634c.jpg)

can this be done ?

**Comment by numan** [comment]
You can probably surround your image with a button and form like this:

```django
        <form method="post" action="{% provider_login_url "google" process="login" %}">
          {% csrf_token %}
          <button>
            <img class="p-2 me-2 bg-white google-sso-logo" src="{% static 'img/sso/google-logo.svg' %}"/>
          </button>
        </form>
```

**Comment by numan** [comment]
Also, look into this setting: `SOCIALACCOUNT_LOGIN_ON_GET`

**Comment by muhamadanjar** [comment]
thank you , that solve my problem

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3183
