### ISSUE TITLE
Dutch translation not working well

### ISSUE THREAD

**Issue by ericmuijs** [pennersr/django-allauth#3186]
I have an issue that some translations work, but others don't. Seems that specifically some long descriptions are not working. For example the password reset email is not working, it is English. [password_reset_key_message]

The issue seems to be dutch specific, as changing the language to German (with the same setup) results in a correct email message in German.

References
https://github.com/pennersr/django-allauth/blob/master/allauth/locale/nl/LC_MESSAGES/django.po

Version
Latest release

**Comment by pennersr** [comment]
Please file a pull request for translation improvements.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3186
