### ISSUE TITLE
Refreshing extra data

### ISSUE THREAD

**Issue by danpaulson** [pennersr/django-allauth#3191]
Assuming a SocialToken that is not expired, is there a built-in way to refresh the extra data from the provider without having the user interact with it? I am specifically looking at Patreon right now, but could be for any provider. I know I could hit Patreon's api myself, but wasn't sure if I was missing a SocialAccount.refresh() or something.

**Comment by iarp** [comment]
extra_data in the SocialAccount table is updated on every login IF the provider returns extra data every time. I don't have patreon to test with, i just double checked with google and it did.

**Comment by pennersr** [comment]
There is no refresh() like method, it would also go beyond the scope of authentication, so it is unlikely that this will be supported.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3191
