### ISSUE TITLE
Apple login not working

### ISSUE THREAD

**Issue by SarahIndigo** [pennersr/django-allauth#3194]
Hello there,
i've been trying to get apple login to work using allauth for a while now and haven't succeeded in doing so so far, i keep getting this error `provider_id: apple ,error: unknown ,exception: Error retrieving access token: b'{"error":"invalid_client"}', extra_context: {}`. 
i've added a section to be able to get the error but still i can't seem to be able to fix it so far. I've used allauth to authenticate using Facebook and Google successfully but not for Apple. Any help would be much appreciated.

**Comment by pennersr** [comment]
https://django-allauth.readthedocs.io/en/latest/faq.html#why-did-you-just-close-my-issue

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3194
