### ISSUE TITLE
'NoneType' object has no attribute 'is_active'

### ISSUE THREAD

**Issue by SchrodingersGat** [pennersr/django-allauth#3195]
It appears that it is possible to hit the `pre_login` method with a null user (i.e. `user=None`)

https://github.com/pennersr/django-allauth/blob/a62a370681c8ba052b19f5b8cf883a93a625b370/allauth/account/adapter.py#L401

Throwing an AttributeError (as described in the title).

Perhaps there should be a check here that the user is non-null?

**Comment by pennersr** [comment]
This should not be possible. Can you specify how to reproduce this scenario?

**Comment by SchrodingersGat** [comment]
I have not been able to reproduce locally, this was from a sentry log for https://demo.inventree.org

![image](https://user-images.githubusercontent.com/10080325/206877707-a8ffc842-af3f-4cb7-b638-1770af2c6ccc.png)

![image](https://user-images.githubusercontent.com/10080325/206877718-d8ca43a5-e34e-4487-b0e7-1df0a3519c36.png)

We also have a custom `LoginView` class:

https://github.com/inventree/InvenTree/blob/53ecca34d805a73ca56078591eb61d7cf661ea5e/InvenTree/InvenTree/views.py#L708

**Comment by pennersr** [comment]
I think your custom `LoginView` is wrong. It calls `full_clean()` but it does not check whether or not the form is valid.  Without a valid form `form.user` will be `None` -- explaining why you run into this issue.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3195
