### ISSUE TITLE
It isn't obvious that storing tokens doesn't work if listing provider credentials in settings.py

### ISSUE THREAD

**Issue by numan** [pennersr/django-allauth#3198]
In my settings.py file I have the following setting enabled:

```python
SOCIALACCOUNT_STORE_TOKENS = True
```

If I provide provider credentials in the settings.py file, rather than a `SocialApp` object:

```python
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': '123',
            'secret': '456',
            'key': ''
        },
        'AUTH_PARAMS': {
            'access_type': 'offline',
        },
    }
}
```

`SOCIALACCOUNT_STORE_TOKENS` has no impact and tokens are not saved. It would be great to document this behavior.

**Comment by pennersr** [comment]
I am adhering to the debatable principle that keeping open issues around with respect to documentation is not very helpful in improving things. Feel free to submit a pull request...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3198
