### ISSUE TITLE
django-allauth project continuity plan discussion

### ISSUE THREAD

**Issue by smkent** [pennersr/django-allauth#3202]
django-allauth is widely used. At time of writing, django-allauth has ~7600 GitHub stars and is the top-listed package in djangopackages.org's [authentication grid](https://djangopackages.org/grids/g/authentication/) with 132 users.

@pennersr explains in https://github.com/pennersr/django-allauth/issues/3201 that their time for django-allauth is limited. It would be great to plan for django-allauth's continuity so maintenance and new feature work can move forward. This could be done by adding additional project maintainers, and perhaps transferring django-allauth to a newly created GitHub organization for this purpose. Currently there are nearly 300 issues and 66 pull requests in django-allauth, which additional maintainers could help out with.

What are folks' thoughts?

**Comment by pennersr** [comment]
IMO, moving elsewhere is just noise. There is nothing stopping anybody from going over the issue list right now, help triage and/or contribute. The quality of issue reports and/or pull requests is not magically going to improve depending on where the repository resides. 

I put that note out for increased awareness, _not_ to signal development is coming to a halt. If people would chip in -- looking at companies using allauth specifically -- that could definitely speed up the pace.

**Comment by bufke** [comment]
Hello @pennersr I tried to reach out over the email listed under [Commercial Support](https://django-allauth.readthedocs.io/en/latest/support.html). [KoboToolbox](github.com/kobotoolbox/) is a not-for-profit using allauth. We would be interested in funding development and/or helping with maintenance. Let me know if you'd like to discuss further. You can reach me at david.burke at kobotoolbox.org

**Comment by matmair** [comment]
@pennersr Is there an interest in more maintainers or a maintainer collective like @jazzband or mainly funding?

**Comment by smkent** [comment]
I hadn't heard of @jazzband before but I really like that general idea. IMO that would be an easy way to add additional maintenance capacity to django-allauth.

**Comment by matmair** [comment]
@smkent it is a cool idea but a project belongs to the maintainer so if @pennersr is not intrested in this it is of no use for the project. Having a critical security component beeing reliant on a single factor is kind of risky but seems to be the norm for auth-packages in the django-sphere.

**Comment by smkent** [comment]
For sure, as owner @pennersr would need to be the decision maker here. It would be great to add more maintainers to django-allauth, especially considering it's both widely used and is a critical security component. @jazzband is a cool idea but I'm on board with any effective path to adding more maintainers.

**Comment by pennersr** [comment]
Is Jazzband truly the place where projects go and flourish? In my opinion, it is unrealistic to expect that there is a box of spare maintainers that you can open at will. Maintainership requires time and dedication. If done as a collective, it requires a shared vision -- a group of likely minded people. Often, people come and go that are eager to get a feature in they are dependent on for their own projects, but more is needed, all open issues and PRs need to be scrutinized, and there is already nothing stopping anybody from doing that. I really don't see a way to just hand out the keys to more people, that's why the priority is to get organized first -- hence the request for sponsorship.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3202
