### ISSUE TITLE
How do I disable message notification for post_login

### ISSUE THREAD

**Issue by DariusG4** [pennersr/django-allauth#3205]
When I logged in with allauth, I got a Tips message: "Successfully signed in as {{name}}" or "You have signed out." How do I disable this message?

**Comment by epicserve** [comment]
@DariusG4, why was this closed with no explanation? I'm currently seeing in the code that the only way to turn this off would be to override the adapter and copy and paste everything in [post_login()](https://github.com/pennersr/django-allauth/blob/master/allauth/account/adapter.py#L441) before the `self.add_message()` call, which isn't ideal. It would be much nicer if there were an app setting to turn this off. In fact, I would almost say that it should be the default not to show a success message after someone has logged in. I think users can tell if they have signed in or not and don't need a user notification to tell them so. This should, in my opinion, be reserved for unclear things. However, so it's not a breaking change, it probably shouldn't be the default setting.

**Comment by epicserve** [comment]
This is how I made those tweaks in the Django Base Site. It would be nice if this could just be rolled up into Django Allauth.
https://github.com/epicserve/django-base-site/blob/main/apps/accounts/auth_adapter.py

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3205
