### ISSUE TITLE
I would like to store access_tokens in db for every user, but i can't find where to do this

### ISSUE THREAD

**Issue by Madhatterflava** [pennersr/django-allauth#3206]
So, when user logs in i would like to have an access_token with refreshin time in DB. My users logs in by Twitch. Also I've tried to mention STORE_TOKEN = True. It doesn't work

**Comment by derek-adair** [comment]
@pennersr close as discussion/support.

@Madhatterflava You want `STORE_TOKENS` with an S.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3206
