### ISSUE TITLE
Cannot find the reference for email_confirmed signal in the view/adapter.

### ISSUE THREAD

**Issue by palmy-investing** [pennersr/django-allauth#3207]
Can someone help  me? I need to find the code piece where email_confirmed signals are checked. My registered signal gets ignored at the moment and I'd like to set some statements for regarding the problem in more detail. Thanks!

**Comment by pennersr** [comment]
https://django-allauth.readthedocs.io/en/latest/faq.html#why-did-you-just-close-my-issue

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3207
