### ISSUE TITLE
No reference for changing the error reference?

### ISSUE THREAD

**Issue by palmy-investing** [pennersr/django-allauth#3209]
Where can one set a custom error handler? Currently there is only the possibility of providing a 429.html template in the root.

**Comment by pennersr** [comment]
Not sure what you mean? It's just regular Django, e.g. https://docs.djangoproject.com/en/4.1/ref/views/#the-500-server-error-view

**Comment by palmy-investing** [comment]
> Not sure what you mean? It's just regular Django, e.g. https://docs.djangoproject.com/en/4.1/ref/views/#the-500-server-error-view

Oh okay got it. Thanks

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3209
