### ISSUE TITLE
Login immediately on successful register

### ISSUE THREAD

**Issue by ainthateasy** [pennersr/django-allauth#3210]
Is there a way to log a user in immediately after registering?

I've set `ACCOUNT_EMAIL_VERIFICATION = 'optional'` which allows login prior to verification. Is there a smooth way to log the user in once they're successfully registered as part of the standard registration or would I need to manually hit the login for them myself? 

Thanks!

**Comment by pennersr** [comment]
As long as you do not set verification to `mandatory` the user is immediately logged in after signing up.

**Comment by ainthateasy** [comment]
Apologies it's perhaps something to do with the dependent library dj-rest-auth not setting the JWT cookies on register. 

I will follow up with them. 

Thanks

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3210
