### ISSUE TITLE
How to allow only staff users ?

### ISSUE THREAD

**Issue by mahmudtopu3** [pennersr/django-allauth#3217]
Is there any better way to allow only staff users to login ?

**Comment by pennersr** [comment]
You're free to add whatever kind of logic in the adapter, e.g. in `pre_login` you could check `user.is_staff`. Not sure what you mean by "better"... closing, as this is not really specific.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3217
