### ISSUE TITLE
Using APIs for emails rather than relying on Raw HTML files.

### ISSUE THREAD

**Issue by IamGursimar** [pennersr/django-allauth#3219]
Hello, 

Is there any way in which I can use SendGrid templates via API? I want to use the prebuilt templates instead of relying on building the templates myself. 

How I normally send emails in Django:

`msg = Mail(
        from_email='somemail@mail.com',
        to_emails='somemail@mail.com',
    )
`
`msg.template_id = "TEMPLATE ID"`

`client = SendGridAPIClient(API KEY)`
`response = client.send(msg)`

**Comment by pennersr** [comment]
Have a look at the adapter method:

```    def send_mail(self, template_prefix, email, context):```

It is called like so:

```
            get_adapter(request).send_mail(
                "account/email/password_reset_key", email, context
            )
```

So, you can already override this method, and make a mapping of `template_prefix` to your own `TEMPLATE_ID`. Is there more needed?

**Comment by IamGursimar** [comment]
@pennersr  Thank you! Will try to apply it soon :)

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3219
