### ISSUE TITLE
New release request

### ISSUE THREAD

**Issue by smkent** [pennersr/django-allauth#3221]
A number of new features including [OpenID Connect support](https://github.com/pennersr/django-allauth/pull/3165) have been merged since the current stable release ([`0.51.0`](https://pypi.org/project/django-allauth/)) of django-allauth from June 7. It would be great if a new release were published to make these new features available for use.

@pennersr Are you interested in [adding additional project maintainers](https://github.com/pennersr/django-allauth/issues/3202) for actions such as releases? Is there anything folks can do to assist with or ease the release process?

Thanks!

**Comment by pennersr** [comment]
0.52.0 is released

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3221
