### ISSUE TITLE
Redirecting to sign in page.

### ISSUE THREAD

**Issue by doziestar** [pennersr/django-allauth#3223]
I have subclass the Signup view class in the past and everything was successful, but since the last update, anytime I subclass the signup view, the url keeps redirecting to the sign-in page with the next parameter pointing to "users/signup"

To recreate this:

1. try starting a new django application and implement the all-auth package, then subclass the signup view and try calling the view from a url

**Comment by pennersr** [comment]
Closing -- this is not specific enough

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3223
