### ISSUE TITLE
Email Verification - Optional until X days have passed.

### ISSUE THREAD

**Issue by helixaros** [pennersr/django-allauth#3224]
Hi there,

I want to allow users to register but show a message that they are unverified after they login.
After X days have passed (i.e. 10 days) then do not allow the user to login as their email is unverified (essentially treat verification as mandatory after that). 

How can I accomplish that ?

**Comment by pennersr** [comment]
Have a look at the adapter method `pre_login` -- you can override that to tweak the email verification logic based on your own logic.

**Comment by helixaros** [comment]
thank you!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3224
