### ISSUE TITLE
Instagram provider scope "basic" is not valid

### ISSUE THREAD

**Issue by Hisham-Pak** [pennersr/django-allauth#3226]
This issue has been discussed before at #2454 and #2514 but was never fixed

`basic` scope was used to read user's profile and media but now according to [documentation](https://developers.facebook.com/docs/instagram-basic-display-api/guides/getting-access-tokens-and-permissions) it has changed and `user_profile` scope is required and `user_media` is optional and `basic` scope does not work anymore.

![image](https://user-images.githubusercontent.com/45965466/210156871-62ec2b0e-0edb-43d5-bde2-1fef43b6059c.png)

When trying to login with `basic` scope this error response comes up:
```
{"error_type": "OAuthException", "code": 400, "error_message": "No valid scopes requested"}
```

**Comment by pennersr** [comment]
See: 30a3473b

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3226
