### ISSUE TITLE
Best way to get hold of sociallogin instance from inside DefaultAccountAdapter.is_open_for_signup

### ISSUE THREAD

**Issue by swinton** [pennersr/django-allauth#323]
I would like to get hold of the `sociallogin` instance from inside the `DefaultAccountAdapter.is_open_for_signup` method.

This is because, in my implementation, I would like to allow users who have logged in with my app before to connect new sociallogins to their existing accounts. Without this, there is a danger that a user will have multiple sociallogins attached to multiple users, whereas I'd very much like to encourage my users to access all their sociallogins via a single login.

To achieve this, I am detecting previous usage via a cookie, and then raising a `ImmediateHttpResponse` exception within my `is_open_for_signup` implementation, to load an interim page presenting some different options for login. 

I have this working, but I have had to fork allauth to achieve this. In my fork, all I am doing is passing in `sociallogin` in to `is_open_for_signup` [here](https://github.com/pennersr/django-allauth/blob/ae58183299df55c65a82457c14b481fc41274563/allauth/socialaccount/helpers.py#L59). 

E.g. instead of:

``` python
        try:
            if not get_account_adapter().is_open_for_signup(request):
                return render(request,
                              "account/signup_closed.html")

```

I have:

``` python
        try:
            if not get_account_adapter().is_open_for_signup(request, sociallogin):
                return render(request,
                              "account/signup_closed.html")

```

The `sociallogin` instance is then saved on the session temporarily, and then referred to in subsequent requests. Either to create a brand new account, or to connect the login with an existing account.

Ideally, I would not have to fork allauth to achieve this, but it's not immediately obvious to me how else I can achieve what I need.

Since `is_open_for_signup` lives on the `DefaultAccountAdapter` and not the `DefaultSocialAccountAdapter`, it does not seem right to simply amend the signature of the `is_open_for_signup` method to simply allow the additional `sociallogin` argument.

I would be very happy to send a pull request in for this, but I would like some direction on how best to proceed.

Thanks :)

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/323
