### ISSUE TITLE
Intergration with Vuejs not working - cors issue

### ISSUE THREAD

**Issue by RakeshAMD** [pennersr/django-allauth#3233]
Hello,

Django-allauth works fine with django directly. But when i try to integrate it with vuejs its throwing cors error 

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://login.microsoftonline.com/XXXXXXXXXXXXXXXXXXXXXXXXXXX/oauth2/v2.0/authorize?client_id=XXXXXXXXXXXXXXXXXXXXX&redirect_uri=https%3A%2F%2FXX.XX.XX.XX%3A8000%2Faccounts%2Fmicrosoft%2Flogin%2Fcallback%2F&scope=User.Read&response_type=code&state=XXXXXXXXX. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.`

below is the frontend call, i tried with multiple combinations. 

```
axios.get("https://XX.XX.XX.XX:8000/accounts/microsoft/login/", {
        // headers: { "Content-Type": "application/json" }
        // headers: { "Access-Control-Allow-Origin": "*" }
        // maxRedirects: '5',
        // withCredentials: true,
        headers: {
          "content-type": "multipart/form-data"
        },
        xsrfCookieName: 'csrftoken',
        xsrfHeaderName: 'X-CSRFToken',

      })
```
Below is the Django settings 

```
 # CORS CONFIGURATION
CORS_ALLOW_ALL_ORIGINS = True


 CSRF_TRUSTED_ORIGINS = [
     "http://XX.XX.XX.XX",
     "https://sub.example.com",
     "http://localhost:9000",
     "http://127.0.0.1:9000",
     "https://login.microsoftonline.com",
 ]

 CORS_ALLOWED_ORIGINS = [
     "http://XX.XX.XX.XX",
     "https://sub.example.com",
     "http://localhost:9000",
     "http://127.0.0.1:9000",
     "https://login.microsoftonline.com",

 ]
 CORS_ALLOW_CREDENTIALS = True

 CORS_ALLOW_HEADERS = [
 'accept',
 'accept-encoding',
 'authorization',
 'content-type',
 'dnt',
 'origin',
 'user-agent',
 'x-csrftoken',
 'x-requested-with',
 ]
```

Please provide feedback.

**Comment by pennersr** [comment]
https://django-allauth.readthedocs.io/en/latest/faq.html#why-did-you-just-close-my-issue

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3233
