### ISSUE TITLE
OAuth 2.0 PKCE Code Verifier longer than allowed

### ISSUE THREAD

**Issue by maxlienen** [pennersr/django-allauth#3237]
RFC 7636 states that the code verifier may be with a minimum length of 43 characters and a maximum length of 128 characters.

The following code, used in the `generate_code_challenge` method in [utils.py](https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/providers/oauth2/utils.py), outputs a code verifier with a random length between 58 and 171 characters using Python 3.8.10:

```
nbytes = random.randint(43, 128)
code_verifier = token_urlsafe(nbytes)
```

I think the main issue here is that bytes are mistaken with characters.

Another question for me would be why the code verifier length is random, a I do not surely know what the randomness adds, which is also not mentioned in RFC 7636.

So, for example, a fix for this would be:

```
# Create a code verifier with 128 characters
code_verifier = token_urlsafe(96)
```

This would always output a `code_verifier` of length 128. Using the maximum length adds entropy and, by this, security.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3237
