### ISSUE TITLE
empty user.email for keycloak

### ISSUE THREAD

**Issue by chassing** [pennersr/django-allauth#3241]
I found a bug introduced by #3165 regarding the `user.email` field with the `keycloak` provider (possibly other OIDC providers too). 

After a successful login, the `user.email` attribute is empty but was filled in with django-allauth 0.51.0.

I think the problem is in [extract_common_fields](https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/providers/openid_connect/provider.py#L43), which doesn't return the `email` attribute anymore, but that would be needed for [populate_user](https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/providers/base/provider.py#L75) that updates the user field.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3241
