### ISSUE TITLE
[FAQ] What is the minimal django version for the current version of django-allauth 

### ISSUE THREAD

**Issue by ffischer1984** [pennersr/django-allauth#3243]
the documentation says 'supports 4.1' but is this the minimal version or the maximal version?

**Comment by iarp** [comment]
You can see in the tox.ini the testing does py3.5 with django 2.0 all the way to py3.10 and django 4.1

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3243
