### ISSUE TITLE
Custom User model - USERNAME_FIELD is undefined

### ISSUE THREAD

**Issue by PHermans1** [pennersr/django-allauth#3246]
I have a custom user model that extended AbstractBaseUser and does not have a 'username' field. Instead it uses the 'email' field as the username. When I try to use this project, I get the following error:

```
FieldDoesNotExist at /accounts/login/
User has no field named 'username'
```

When I debug, it points me to the utils.py file at this method:
```
def get_username_max_length():
    from .account.app_settings import USER_MODEL_USERNAME_FIELD

    if USER_MODEL_USERNAME_FIELD is not None:
        User = get_user_model()
        max_length = User._meta.get_field(USER_MODEL_USERNAME_FIELD).max_length
    else:
        max_length = 0
    return max_length
```
When I examine the USER_MODEL_USERNAME_FIELD, it is 'username' and there appears to be no way for me to override this in my settings since it is coded to import from .account.app_settings.

Not clear how to fix it as I am new to OAuth, but hoping it is a simple thing for me to either configure or maybe a simple bug to fix. Not really sure.

**Comment by iarp** [comment]
Did you set `ACCOUNT_AUTHENTICATION_METHOD` ?

https://django-allauth.readthedocs.io/en/latest/configuration.html

**Comment by Dishanesachin** [comment]
Make sure that your custom user model is set up correctly. 

And it’s mention in the settings.py file as follows 

🔺 AUTH_USER_MODEL = ‘appname.customusermodel’
[More info | AUTH_USER_MODEL](https://docs.djangoproject.com/en/4.1/ref/settings/#std-setting-AUTH_USER_MODEL)

According to the django-allauth docs if you are using a custom user model without a username field you can tell django-allauth to look in another field.

In this case imagine that I you a custom user model with email as the username field
In that case the code look like following 
🔺 ACCOUNT_USER_MODEL_USERNAME_FIELD = ‘email’ 

[More info | ACCOUNT_USER_MODEL_USERNAME_FIELD](https://django-allauth.readthedocs.io/en/latest/advanced.html#custom-user-models).

I hope this might fix your issues 🙂

**Comment by pennersr** [comment]
You mention:

>  user model that extended AbstractBaseUser and does not have a 'username' field.

Yet, you have this:

> When I examine the USER_MODEL_USERNAME_FIELD, it is 'username' 

By setting that you tell allauth that there /is/ a username field. So, set that to `None`.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3246
