### ISSUE TITLE
PKCE code verifier not specified

### ISSUE THREAD

**Issue by VISHNU-P-M** [pennersr/django-allauth#3247]
In Social Authentication with Keycloak, 
I'm facing an issue retrieving tokens with the Keycloak SocialLoginView extended view.

here my view

`class KeycloakLogin(SocialLoginView):
    adapter_class = KeycloakOAuth2Adapter
    client_class = OAuth2Client
    callback_url = f"{settings.APP_UI_URL}/login"`

URL

`re_path(r'login/keycloak/?$', views.KeycloakLogin.as_view()),`

Error

> allauth.socialaccount.providers.oauth2.client.OAuth2Error: Error retrieving access token: b'{"error":"invalid_grant","error_description":"PKCE code verifier not specified"}'

**Comment by pennersr** [comment]
allauth does not have a `SocialLoginView`. Unclear what how this relates to allauth, closing.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3247
