### ISSUE TITLE
Multiple Client IDs for one provider (Google) for different platforms (Web, iOS, Android)

### ISSUE THREAD

**Issue by Terspychore** [pennersr/django-allauth#3248]
First of all, thank you for this amazing library,

Is there a way to manage multiple clients IDs for one provider (web, ios, android) ?

I have successfully done it with Apple using `client_id = '<app_id>, <service_id>'`, but when using this syntax for Google it does not work. (`The OAuth client was not found.`).

Moreover, only using one client_id does not work even if all of my IDs are in the same Google project. (getting the following error : `unauthorized_client`).

**Comment by oscarleonardoricci** [comment]
From the source code it seems that most of the functions are built in a way that supports multiple social apps and client_ids for the same provider but with the standard adapters this doesn't seem to work out of the box.

**Comment by pennersr** [comment]
Duplicate of https://github.com/pennersr/django-allauth/issues/1002

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3248
