### ISSUE TITLE
Want to add additional details of user while saving it to DB for my custom user model

### ISSUE THREAD

**Issue by abhibhaw** [pennersr/django-allauth#3251]
Hi! I'm using a custom user model for my project. And that has a foreign key constraint to org table. I want to create org for that user if not exist. Where should I put login for that?

I read the docs about writing a CustomSocialAdapter but that seems a bit incomplete and confusing. Can anyone guide here?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3251
