### ISSUE TITLE
can't login google in production server

### ISSUE THREAD

**Issue by muhamadanjar** [pennersr/django-allauth#3255]
![Screenshot from 2023-02-07 11-29-34](https://user-images.githubusercontent.com/10927965/217148702-6cfe3d49-5340-4ea7-9203-04ce17df4785.png)

hello i can't login via google in server production but work perfectly in my local computer

my host always ```academy``` not my domain
can you tell me why?

**Comment by 5no0p** [comment]
If you use version 0.52.0 this issue will show for Google provider...just downgrade to 0.51.0

**Comment by muhamadanjar** [comment]
i'm using version 0.51.0

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3255
