### ISSUE TITLE
User roles pulled from Keycloak

### ISSUE THREAD

**Issue by maxeval** [pennersr/django-allauth#3263]
Dear developers, is there any straightforward way of how to pull the `roles` for the user from Keycloak environment? Didn't find this feature in django-allauth docs (or at least it is not obvious for me). Thanx a lot!

**Comment by Vidski** [comment]
Overwrite the default adapter to handle roles:

`class KeycloakAccountAdapter(DefaultSocialAccountAdapter):

    def authentication_error(self, request, provider_id, error=None, exception=None, extra_context=None):
        super().authentication_error(request, provider_id, error, exception, extra_context)

    def is_open_for_signup(self, request, sociallogin):
        return False

    def new_user(self, request, sociallogin):
        return super().new_user(request, sociallogin)

    def pre_social_login(self, request, sociallogin):
        decoded = jwt.decode(jwt=sociallogin.token.token, options={"verify_signature": False})
        if 'my_client' not in decoded['resource_access']:
            messages.error(request, 'User role not found!')
            raise ImmediateHttpResponse(redirect('/auth/keycloak/login/'))

        is_admin = False
        if 'admin' in decoded['resource_access']['my_client']:
            is_admin = True
        ....
        ....
        ....
        sociallogin.connect(request, user)`

**Comment by maxeval** [comment]
Thanks a lot @Vidski, will try!
It's not quite obvious what is `sociallogin` object about and what it contains..

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3263
