### ISSUE TITLE
ACCOUNT_EMAIL_CONFIRMATION_COOLDOWN creates failing tests

### ISSUE THREAD

**Issue by Hafnernuss** [pennersr/django-allauth#3265]
I upgraded all my dependencies today, and this setting caused me quite some headache.
I have some custom sign-up logic that I test quite extensively, and because of this setting, random tests kept failing, but not when executing them individually. 

Maybe there is a clean way to disable this setting when testing, or a hint in the documentation?  🤔

**Comment by pennersr** [comment]
https://django-allauth.readthedocs.io/en/latest/faq.html#why-did-you-just-close-my-issue

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3265
