### ISSUE TITLE
serialize_instance fails if any field in user model is not DjangoJSONEncoder serializable

### ISSUE THREAD

**Issue by pembo13** [pennersr/django-allauth#3268]
`SocialLogin` handles explicitly handles serialization of several pieces of data itself through `DefaultSocialAccountAdapter.serialize_instance` and ultimately `utils.serialize_instance`.

The problem is that this explicitly uses `DjangoJSONEncoder` and any field that's not serializable by `DjangoJSONEncoder` causes an error during the social signup process.

This was triggered for me when using https://github.com/ahawker/django-ulid as a field on a custom user model.

**Comment by pennersr** [comment]
Can you pinpoint where this goes wrong?  Allauth uses:

```
            # Check if the field is serializable. If not, we'll fall back
            # to serializing the DB values which should cover most use cases.
            try:
                json.dumps(v, cls=DjangoJSONEncoder)
            except TypeError:
                v = field.get_prep_value(v)
                k = SERIALIZED_DB_FIELD_PREFIX + k
```

... so it calls out to `get_prep_value` if the value is not serializable. So, we end up here:

https://github.com/ahawker/django-ulid/blob/master/django_ulid/models.py#L44

So, `value.uuid` is returned there. But:

```
>>> json.dumps(uuid.uuid4(), cls=DjangoJSONEncoder)
'"47169716-65a0-4af8-b425-33c1565f6dbd"'
```

So, all in all, this seems serializable?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3268
