### ISSUE TITLE
ACCOUNT_PREVENT_ENUMERATION allows social signup when validate_unique_email fails

### ISSUE THREAD

**Issue by pembo13** [pennersr/django-allauth#3269]
With `ACCOUNT_PREVENT_ENUMERATION = True` `account_already_exists` is set to `True` but `form.is_valid()` returns `True` and proceeds to save form, in the process saving the user.

In my case, I'm enforcing unique users, and this causes a database error, but if `ACCOUNT_UNIQUE_EMAIL == True` I don't think a user should be saved at all -- though I'm not sure what the course of action should be -- I like the idea of `ACCOUNT_PREVENT_ENUMERATION`.

**Comment by pennersr** [comment]
The form validates because the POST is accepted and handled. Except, in the handling, there is a difference: `save()` would return `None` in case of a conflict. This has been refactored and made more explicit now, now `save()` will throw an exception, see `try_save()` -- f58889cf

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3269
