### ISSUE TITLE
AttributeError: 'PasswordResetFromKeyView' object has no attribute 'redirect_field_name'

### ISSUE THREAD

**Issue by uberfresh** [pennersr/django-allauth#3270]
### What is the issue?
- Hi, I am getting  `AttributeError: 'PasswordResetFromKeyView' object has no attribute 'redirect_field_name'`  after password change.

### Where is the issue?
- `password_reset_from_key_done`

### When did the issue appear?
- After 0.52.0 update

### How can we reproduce the issue?
-  Make a password reset.
-  Enter your email
- Wait for the email
- Click on the link
- Enter new pw
- Proceed
- Error `AttributeError` appears

**Comment by ffurqan** [comment]
I am interested to solve these issue problem I am expert in python,Django ###  message me ffurqanrahim@gmail.com then I am started at this project

**Comment by pennersr** [comment]
Password reset definitely works out of the box, likely you have made some modifications

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3270
