### ISSUE TITLE
E-Mail-Address change workflow (Feature request?)

### ISSUE THREAD

**Issue by sowinski** [pennersr/django-allauth#3271]
Hi,

as I understand. There is currently no workflow to directly change the e-mail-address.

The current way is it to use /accounts/email/ with the following steps:
1. Add new E-Mail
2. Verify E-mail
3. Mark the new email as a primary E-mail
4. Delete the old one

Is it possible to just change the E-Mail without doing the other steps?
For example.
1. User add to a form an E-Mail-Address
2. Afterwards he get directly an E-Mail, and if the user clicks on the email and accept it then the old e-mail will be deleted directly and the new one will be made/marked directly as the primary?

Thank you

**Comment by Sabrebar** [comment]
If you find an answer, please share it! :)

**Comment by pennersr** [comment]
Does this meet your use case?: https://github.com/pennersr/django-allauth/pull/3346

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3271
