### ISSUE TITLE
Issue with Custom Provider 

### ISSUE THREAD

**Issue by wardjallen** [pennersr/django-allauth#3272]
Hi I am am a newbie,  I am trying to make a custom Provider for Webex.  I think I have most of it working with exception to the last step when it completes login.  I get this Error  

Social Network Login Failure

An error occurred while attempting to login via your social network account.

in the Django console I do get my access_token and I am able to get my profile.  what am i possibly missing.  it seem like it is just not creating the actual user and finishing the login.  Any help is very much appreciated.

**Comment by pennersr** [comment]
Sorry, closing -- this is not an issue in allauth itself.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3272
