### ISSUE TITLE
`OpenIDConnectProvider` generates slug using `_server_id` and does not fallback to inherited implementation

### ISSUE THREAD

**Issue by ManiacMaxo** [pennersr/django-allauth#3282]
KeycloakProvider started using `openid_connect` as its base url since the `OpenIDConnectProvider` implemented `get_slug`

**Comment by ManiacMaxo** [comment]
Fixed in https://github.com/pennersr/django-allauth/pull/3283

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3282
