### ISSUE TITLE
django-allauth 0.53.0 - templates/accounts/base.html missing {% load i18n %}

### ISSUE THREAD

**Issue by pavgup** [pennersr/django-allauth#3286]
This seems a wee bit odd. When I compare the 0.53.0 release tag with the master branch in django-allauth, I see no differences, but I can see that the released version of django-allauth 0.53.0 is missing this package-breaking change here: https://github.com/pennersr/django-allauth/commit/a0fcdf7b8efe4adfbe5c08d2b9630defcdd42698

Trust me, I'm probably doing something wrong here, so blame me first, but I wonder if this can be double checked..

**Comment by fdemmer** [comment]
That commit you linked happened _after_ the [0.53.0 release](https://github.com/pennersr/django-allauth/commits/master); you should get 0.53.1.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3286
