### ISSUE TITLE
User manual activation after the user signs up

### ISSUE THREAD

**Issue by bingimar** [pennersr/django-allauth#3288]
hi, I looking for a solution to allow signups but require the user to wait for manual activation before being able to login.

Perhaps there is another 3rd party library that enables this?

**Comment by pennersr** [comment]
You can use `user.is_active` for this. Just make sure to set it to `False` by overriding the adapter method (e.g. `new_user`).

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3288
