### ISSUE TITLE
Customized User Model gets an error while in auto-signup process

### ISSUE THREAD

**Issue by yychen** [pennersr/django-allauth#329]
With the introduction of customized User model in Django 1.5, there might not be a first_name or last_name field in the model. However, it looks like it will automatic attach these two attributes to the customized user object in socialaccount/adapter.py

``` python
    user = get_user_model()()
    ...
    user.first_name = first_name or name_parts[0]
    user.last_name = last_name or name_parts[2]
```

And, in socialaccount/helpers.py, it checked whether the object has these two attributes and start to get the definition of the model, which will cause an exception

``` python
        for field in ['last_name',
                      'first_name']:
            if hasattr(u, field):
                truncated_value = (user_field(u, field) or '') \
                    [0:User._meta.get_field(field).max_length]
                user_field(u, field, truncated_value)
```

This is what I get:

```
FieldDoesNotExist at /accounts/facebook/login/callback/

User has no field named 'last_name'
```

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/329
