### ISSUE TITLE
Disable login with connected social

### ISSUE THREAD

**Issue by salmanrk** [pennersr/django-allauth#3293]
Is there a way to allow users connect social accounts but prohibit them being used for login? They'd only be allowed to login with email or the social used to register the account.
Just like social media management tools such as Hootsuite. Say someone is managing clients socials. If one of these clients decide to use their social to login the website they'd access that manager's account including all his client's accounts.

**Comment by pennersr** [comment]
The `SocialAccountAdapter` has a `pre_social_login` method:

```
    try:
        get_adapter(request).pre_social_login(request, sociallogin)
        signals.pre_social_login.send(
            sender=SocialLogin, request=request, sociallogin=sociallogin
        )
        process = sociallogin.state.get("process")
        if process == AuthProcess.REDIRECT:
            return _social_login_redirect(request, sociallogin)
        elif process == AuthProcess.CONNECT:
            return _add_social_account(request, sociallogin)
        else:
            return _complete_social_login(request, sociallogin)
    except ImmediateHttpResponse as e:
        return e.response
```

So, inside your current adapter you can check the process and deny the login accordingly.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3293
