### ISSUE TITLE
How to have two configs of the same provider

### ISSUE THREAD

**Issue by bb4L** [pennersr/django-allauth#3296]
i do need to configure allauth in the way that i have two different sign in with apple configurations working (from two different teams if it matters)

is there a way of doing it?

**Comment by pennersr** [comment]
Can you please elaborate on your use case? You want to show a login page, with "Login with Apple A" and "Login with Apple B"? How would a user make the choice between the two? Or, is A only to be shown on a specific domain?

**Comment by bb4L** [comment]
when using [dj-rest-auth](https://dj-rest-auth.readthedocs.io/en/latest/index.html) and Django as a Backend it would be nice to be able to configure multiple apple configurations so that multiple apps could use the same backend

**Comment by pennersr** [comment]
This is already supported in allauth, you can have multiple `SocialApp` records for the same provider in the latest main branch.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3296
