### ISSUE TITLE
Cache stores CSRF on login and register

### ISSUE THREAD

**Issue by mfvictor** [pennersr/django-allauth#3297]
LoginView and SignupView are caching the csrf token when back is pressed after Login/Signup. 

https://user-images.githubusercontent.com/8157518/229463400-b1e5b320-c240-4388-b7ec-1d6a8fa292a4.mp4

This can be reproduced in the example app.

**Comment by varunsaral** [comment]
@mfvictor if you are not working on this, can i take up the work?

**Comment by varunsaral** [comment]
@pennersr can i take up the work for this?

**Comment by pennersr** [comment]
Definitely...

**Comment by pennersr** [comment]
Closed via #3390

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3297
