### ISSUE TITLE
Retrieveing email from Google social account

### ISSUE THREAD

**Issue by saintger** [pennersr/django-allauth#330]
Hello,

Using django-allauth 0.12.0 with Django 1.5.1 on Debian Testing, I haven't managed to retrieve the email when signing through Google.
I got first name and last name all right, but no luck with email.
I tried printing extra_data in the file allauth/socialaccount/providers/google/views.py but I don't see any email inside.

My settings.py:
ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_EMAIL_REQUIRED = True
SOCIALACCOUNT_EMAIL_REQUIRED = False
SOCIALACCOUNT_QUERY_EMAIL = True

Can we retrieve the email wen signing through Google ?
If yes do you have any idea how I can debug this ?

Thanks

**Comment by anoopms1988** [comment]
Even after using this scope i dont get any email

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/330
