### ISSUE TITLE
not working in some client browser

### ISSUE THREAD

**Issue by alibaltschun** [pennersr/django-allauth#3300]
hello, i have a django project that working fine on my laptop for localhost and production
everything working fine on my laptop for signup sign in and sign out.

but one client cant login using mozila and have error 400: redirect_uri_missmatch.
that client change browser to chrome and working fine.

another client try sign up with chrome and have same error like client before, error 400: redirect_uri_missmatch.
and i tell them to tried on safari and working fine.

and on my laptop safari and chrome working fine.
i dont know what wrong and how to debug this problem.

thanks

**Comment by WhalenSITHS** [comment]
Following, similar issue device to device

**Comment by alibaltschun** [comment]
i found the problem. 

working fine while i tried access from domain.com and error while on www.domain.com

because on google console, i only input domain.com for whitelist url.

you need both

domain.com
www.domain.com

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3300
