### ISSUE TITLE
Parameterized/configurable reverse URLs?

### ISSUE THREAD

**Issue by wgordon17** [pennersr/django-allauth#3306]
So, my use case is that I'm customizing all the URLs and their associated `reverse` names. There are a bunch of places in `views.py`, `helpers.py`, and `adapter.py` that reference the `reverse` names statically. I would like to propose moving those to a SETTINGS dict, similarly to how was done for form overrides.

If this is something that's acceptable or useful, I could submit a PR. Just gauging acceptance before putting in the work 😅

**Comment by wgordon17** [comment]
@pennersr Could you help me gauge the level of acceptance or interest here?

I'm thinking of just keeping this relatively basic. For user settings, it would be

```
ACCOUNT_URLS = {
    "account_email_verification_sent": "email:verification_sent"
}
```

Then having a helper `get` function in `utils.py`

```
def get_url_name(urls, url_name)
    return urls.get(url_name, url_name)
```

And then in place of all the hardcoded URL names, it would be something like

```
reverse(get_url_name(app_settings.URLS, "account_email_verification_sent"))
```

WDYT? It at least _should have_ the benefit of being a backwards compatible (unless I'm missing something), and provides more flexibility going forward.

**Comment by wgordon17** [comment]
@pennersr 🤔 That's a valid point, totally forgot about third-party.

Ideally, I'm trying to have consistency in my URL resolution, with _everything_ matching `namespace:route-name`, and even trying to have consistency across `route-name`.

Honestly, given that the URL names are all just internal _anyway_, it's not like it has any customer impact, just developer experience impact.

I'm _currently_ working around this by have 2 copies of the exact same URLConf, same URLs but one with my naming and one with the default naming. Perhaps that's just good enough ¯\\\_(ツ)_/¯

**Comment by pennersr** [comment]
Naming things. I agree, things could have been named better. Though, in the end, it's just a name, and I value backwards compatibility with other projects above all.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3306
