### ISSUE TITLE
Social account connection does not prevent same email being used in an email password signup

### ISSUE THREAD

**Issue by anthonyrubin** [pennersr/django-allauth#3307]
The following edge case exists and I believe should be fixed:
Suppose someone signs up for an account using email and password, the email is ABC@gmail.com. Upon signup, a EmailAddress object (corresponding to ABC@gmail.com) and a user object are created, no problem.

Now suppose the client signs in to the account ABC@gmail.com and connects the social account XYZ@gmail.com, which does not exist at all in the database. This works no problem. Now the user can sign in via ABC@gmail.com or XYZ@gmail.com.

HERE IS THE EDGE CASE: Since connecting a social account to an existing account does not generate an **EmailAddress** object, a user can still take XYZ@gmail.com and sign up via username and password and a brand new account will be created.

Now you will be in a situation where ABC@gmail.com has the social account XYZ@gmail.com associated with it, and XYZ@gmail.com is associated with its own account.

I have tried to fix this locally on my own by checking, on signup, if there is a social account that exists with the email being passed, but it is not so simple as we cannot elegantly filter the SocialAccount objects by email.

**Comment by ericmuijs** [comment]
I think I have the exact similar issue. If I create a local account eric@gmail.com for example, I can still create an account with eric@gmail.com with the Social Gmail account connection, even with the following settings:

ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True

I end up with two users, with different usernames, having the same email adress! This is not preferable.


@anthonyrubin : this is the same issue right? Don't want to hijack the thread.

**Comment by pennersr** [comment]
This is more of a conceptual issue. Given an account, there are keys tied to that account that can be used to authenticate. One of those keys can be an email/password combination, another key is a social account. What properties are attached to the social account are not relevant for authenticated purposes. Of course, many providers provide email addresses, but not all, some provide phone numbers and so on. Note that this additional information can change without the allauth site being made aware of it. You might change your email or phone number over at the 3rd party provider site. So, the only reliable bit of information that allauth can use is the social account itself, regardless of what properties are attached to it.

@ericmuijs What you are describing is different from what @anthonyrubin is reporting, and should not be possible. You can create the signup using a social account, but you will be asked to enter a new non-conflicting email address for this account.

**Comment by anthonyrubin** [comment]
@pennersr what do you think of implementing some sort of settings flag to prevent this? Definitely is an important edge case to tackle, albeit a small percentage of users who may find themselves in it, any large scale production facing app needs to have this ironed out. I was able to hack a fix together by doing the following in the `clean_email` function of my user registration form:

```
def clean_email(self):
        email = self.cleaned_data['email'].lower()

        conflicting_social_account = False

        social_accounts = SocialAccount.objects.all()

        # TODO: Figure out how to clean this up, this sucks
        for account in social_accounts:
            if account.extra_data['email'] == email:
                conflicting_social_account = True
                break

        if User.objects.filter(email__iexact=email).exists() or conflicting_social_account:
        # These filter methods DO NOT WORK!
        #or SocialAccount.objects.annotate(email_text=Cast(F("extra_data__email"), models.TextField())).filter(email_text__icontains=email):
        #SocialAccount.objects.filter(extra_data__email__icontains=email).exists():
            raise ValidationError(
                f'A user is already associated with the email {email}'
            )
        else:
            return email

```

I could not find a clean way to filter down the SocialAccount objects and had to pull them all in and loop through them. I included in the code examples of filter functions that do not work.

Let me know your thoughts.

**Comment by pennersr** [comment]
I don't think you can solve this issue in a generic way. As mentioned, the social account itself is the key to your account, not its properties (e.g. email). Take for instance almost any provider other than Google, say Facebook. Over at Facebook, you can freely change your email address. You can do so before and after you have signed up at the allauth site. So how would blocking a specific email at signup help, given that the email can change at any time?

**Comment by pennersr** [comment]
I am going to close this -- this is working as designed.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3307
