### ISSUE TITLE
Two users with same email (signup with local and social)

### ISSUE THREAD

**Issue by ericmuijs** [pennersr/django-allauth#3308]
If I create a local account [eric@gmail.com](mailto:eric@gmail.com) for example, I can still create an account with [eric@gmail.com](mailto:eric@gmail.com) with the Social Gmail account connection, even with the following settings:

ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_LOGOUT_ON_GET = True #logout directly

# Email verification of signup
if 'DEVELOPMENT' in os.environ:
    ACCOUNT_EMAIL_VERIFICATION = 'none'

else:
    ACCOUNT_EMAIL_VERIFICATION = 'mandatory'

Initially I had the ACCOUNT_EMAIL_VERIFICATION on False / True instead of none/mandatory. 
Now with mandatory I get an server error:

Internal Server Error: /accounts/social/signup/

IntegrityError at /accounts/social/signup/
duplicate key value violates unique constraint "account_emailaddress_email_key"
DETAIL:  Key (email)=(eric@gmail.com) already exists.

@pennersr  : I noticed that it does ask for an email adress (only when it is duplicate), but it still goes ahead and makes a new account. Could it be related to having these settings later applied (after initial migration)? 

Somehow the form does give an error in my development setup (duplicate email). Only difference from account perspective is that I disabled EMAIL verification in development.

**Comment by ericmuijs** [comment]
I solved it with the following settings, users now get a warning when the email account already is used for a local account:

ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_LOGOUT_ON_GET = True #logout directly
ACCOUNT_PREVENT_ENUMERATION = False # direct response on duplicate email

# Email verification of signup
if 'DEVELOPMENT' in os.environ:
    ACCOUNT_EMAIL_VERIFICATION = 'none'

else:
    ACCOUNT_EMAIL_VERIFICATION = 'mandatory'

ACCOUNT_EMAIL_SUBJECT_PREFIX = '[SlimKookboek] '
ACCOUNT_SESSION_REMEMBER = True
ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = False

SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'

**Comment by ericmuijs** [comment]
@pennersr is this expected behavior? 
Seems that there is an issue with the initial setup combination + already existing account when  SOCIALACCOUNT_EMAIL_VERIFICATION = 'mandatory'.

**Comment by duplxey** [comment]
> I solved it with the following settings, users now get a warning when the email account already is used for a local account:
> 
> ACCOUNT_USERNAME_REQUIRED = False ACCOUNT_AUTHENTICATION_METHOD = 'email' ACCOUNT_EMAIL_REQUIRED = True ACCOUNT_UNIQUE_EMAIL = True ACCOUNT_LOGOUT_ON_GET = True #logout directly ACCOUNT_PREVENT_ENUMERATION = False # direct response on duplicate email
> 
> if 'DEVELOPMENT' in os.environ: ACCOUNT_EMAIL_VERIFICATION = 'none'
> 
> else: ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
> 
> ACCOUNT_EMAIL_SUBJECT_PREFIX = '[SlimKookboek] ' ACCOUNT_SESSION_REMEMBER = True ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = False
> 
> SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'

@ericmuijs what setting exactly solved it?

**Comment by pennersr** [comment]
See: https://github.com/pennersr/django-allauth/issues/3307#issuecomment-1531932556

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3308
