### ISSUE TITLE
SocialTokens table empty after Google Login

### ISSUE THREAD

**Issue by FSchianchi** [pennersr/django-allauth#3309]
Hello there,

- Python:		3.8.10
- Django:		4.1.7
- django-allauth:	0.54.0

I'm working on a webpage which I have to connect to the Company Google Workspace.
I correctly managed the login, with no issues.
Now, I have to connect to the Gmail of the authenticated user.

For connecting to Google Apps I need a Token that, as I understood, should be in the Database in the table SocialTokens (automatically filled-in after the login phase).

I populated Sites and Social Application manually, as below:
![Sites](https://user-images.githubusercontent.com/44117165/235918175-4b1fd4f8-e170-4356-893b-3f6229f0ed18.png)
![SocialApp](https://user-images.githubusercontent.com/44117165/235918339-bf6d003f-ea77-4d06-8f63-d7f774263732.png)

The authentication works properly, but after the login the model SocialToken (table "Social application tokens") is still empty.
The account is correctly created:
![SocialAccount](https://user-images.githubusercontent.com/44117165/235918469-fa6a2857-cbaa-400f-8ee9-631c1e38167a.png)

But I cannot figure out why the table SocialTokens is not populated after the correct Google login.
![SocialTokens](https://user-images.githubusercontent.com/44117165/235918616-49f1c085-419d-4605-a537-ba2c6454896d.png)

Here my **settings.py**
```
SITE_ID = 1

INSTALLED_APPS = [
    'django.contrib.admin',
    ...,
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]

SOCIALACCOUNT_PROVIDERS = {
    'google':{
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {'access_type':'offline'},
    }
}

SOCIALACCOUNT_STORE_TOKEN = True

SOCIALACCOUNT_AUTO_SIGNUP = True
```

I tried what below:
- update django-allauth (0.4 --> 0.54)
- SOCIALACCOUNT_STORE_TOKEN = True --> set False, True and unset(commented and deleted)
- SOCIALACCOUNT_AUTO_SIGNUP = True --> set False, True and unset(commented and deleted) 
- two lines above in all their combinations (es. SOCIALACCOUNT_STORE_TOKEN = True and SOCIALACCOUNT_AUTO_SIGNUP = False, viceversa, etc...)
- after each change I flushed the db, recreate superuser and redo the login with Google(which has properly worked)
- I checked Google API Client_id and Secret, if any value was wrong or wrongly set (on https://console.cloud.google.com/)
- tested both SITE_ID = 1 and 2, after have created a new Site
- tested 'access_type':'offline' and 'online'(also if it is wrong based on documentation usage of SOCIALACCOUNT_STORE_TOKEN)
- with and without https (in case it affects the data transmission, local and public) 
- DEBUG = True and False

Could anyone tell me if I wrote something wrong or if I missed anything, or if I misunderstood anything?

Thanks for any help.

**Comment by Vaseles** [comment]
Have you solved your problem?

**Comment by FSchianchi** [comment]
Not yet.
Also, if this is not the right place in which leaves this kind of Issues, please let me know.

**Comment by tschwaerzl** [comment]
Tokens don't get stored if you configure your oauth app (google) via `settings.py`. You have to add it into the database model of allauth or use a custom provider which fakes the database model entry using e.g. ENV vars.

Related:
https://github.com/pennersr/django-allauth/issues/2467
https://github.com/pennersr/django-allauth/issues/2467#issuecomment-663015581
https://github.com/pennersr/django-allauth/issues/3198

**Comment by FSchianchi** [comment]
Hi, thanks for the reply.
I added credentials on db model allauth, in the table SocialApp (second
image of the issue #3309), is that the one you meant? It doesn't work if
you mean it.

Il giorno gio 4 mag 2023 alle ore 15:42 Thomas Schwärzl <
***@***.***> ha scritto:

**Comment by Vaseles** [comment]
I have the same problem. Did you see what comes during registration?

**Comment by FSchianchi** [comment]
No, I am looking for the right place in which Google writes down logs of
useful information.
Have you found anything interesting?

[image: Dreamonkey logo]

*Federico Schianchi*

Founder | CEO

+39 348 663 8611 <+39+348+663+8611> | ***@***.***

www.dreamonkey.com | ***@***.***


Il giorno ven 5 mag 2023 alle ore 08:43 Vaseles ***@***.***>
ha scritto:

**Comment by FSchianchi** [comment]
I found a workaround, not a solution yet.

With a condition based on your code, **only the first time you need the Access Token**, you can make a GET request to `https://accounts.google.com/o/oauth2/v2/auth` adding `prompt=consent` to the URL for Auth Code request (just before `&access_type=offline`).
This string let you be able again to retrieve the Refresh Token, or Token Secret,  after the log-in phase and all fields to create the DB object you will use from here on.

After  the first time use the Refresh Token to update the Access Token when it expires (3599 ms - 1h)

**Comment by Vaseles** [comment]
I found information about adding an adapter SOCIALACCOUNT_ADAPTER = 'allauth.socialaccount.providers.google.views.GoogleOAuth2Adapter', but it also doesn't work

**Comment by FSchianchi** [comment]
For me neither.
Try also to flush your db, because the Token it's created only during the first request; but it didn't work in my case.

**Comment by Vaseles** [comment]
Today I deleted this database 5 times and migrated it again

**Comment by FSchianchi** [comment]
I got you, for me the same.
Try the "unclean" workaround, if it is urgent, I will try to find a solution and if you find one please let me know.

**Comment by Vaseles** [comment]
hi, I found more settings for google, did u solve this problem?
'google': {
        'SCOPE': [
            'profile', 
            'email',
            'https://www.googleapis.com/auth/gmail.readonly',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
            # 'prompt': 'consent',
        },
        'APP': {
            'client_id': os.environ.get('GOOGLE_CLIENT_ID'),
            'secret': os.environ.get('GOOGLE_SECRET'),
            'key': ''
        },
        'METHOD': 'oauth2',
        'ACCESS_TOKEN_METHOD': 'POST',
        'PROVIDER_ID': 'google',
        # 'ACCESS_TOKEN_URL': 'https://oauth2.googleapis.com/token',
        # 'AUTHORIZATION_URL': 'https://accounts.google.com/o/oauth2/auth',
        'REQUEST_TOKEN_URL': None,
        # 'USER_DATA_URL': 'https://www.googleapis.com/oauth2/v2/userinfo',
        'VERIFIED_EMAIL': True,
        'USE_SSL': True,
        'REDIRECT_URI': 'http://localhost:8000/accounts/google/login/callback/',
        # 'SOCIAL_TOKEN_MODEL': 'allauth.models.SocialToken', # custom model
}
but it doesn't work. When i use ACCESS_TOKEN_URL and AUTHORIZATION_URL i see a white screen

**Comment by nikklavzar** [comment]
Any updates on this? I am having the same issue.
`SOCIALACCOUNT_STORE_TOKEN = True` does nothing. The Social Account is created, but the Social Token table is empty.

**Comment by Vaseles** [comment]
> Any updates on this? I am having the same issue with Django 4.2. `SOCIALACCOUNT_STORE_TOKEN = True` does nothing. The Social Account is created, but the Social Token table is empty.

no, I also have this problem

**Comment by Vaseles** [comment]
I've already logged in, nothing, everything is supposedly fine in the logs, all that's left is to completely rewrite the function (or roll back the Django version back +- django-allauth

**Comment by Vaseles** [comment]
please write if you solve this problem

**Comment by nikklavzar** [comment]
I didn't test this yet, but to me it looks like the `SocialToken` object is never actually saved, unless I'm missing something.

If you look at the `OAuth2CallbackView` class, you have this line that instantiates the `SocialToken` object:
`token = self.adapter.parse_token(access_token)`.

But the `parse_token` method on the adapter doesn't save the token to the database, it only returns a new `SocialToken` object. Then it's passed to the `GoogleOAuth2Adapter`'s `complete_login` method, where it is never actually accessed.

**Comment by nikklavzar** [comment]
> please write if you solve this problem

As a workaround, I'm using the `pre_social_login` signal to catch the token
```
from allauth.socialaccount.signals import pre_social_login
from django.apps import AppConfig
def pre_social_login_callback(request, sociallogin, **kwargs):
    token = sociallogin.token
    # do something with the token


class CoreConfig(AppConfig):
    default_auto_field = "django.db.models.BigAutoField"
    name = "core"

    def ready(self):
        pre_social_login.connect(pre_social_login_callback)
```

Docs: https://django-allauth.readthedocs.io/en/latest/signals.html#allauth-socialaccount

**Comment by Vaseles** [comment]
How to fix error
**" RelatedObjectDoesNotExist at /accounts/google/login/callback/
SocialAccount has no user. "**
 when user registers for the first time?

**Comment by spiridon-alexandru** [comment]
It might be a typo, it seems that you're using `SOCIALACCOUNT_STORE_TOKEN`, but from [the docs](https://django-allauth.readthedocs.io/en/latest/configuration.html), plural is used `SOCIALACCOUNT_STORE_TOKENS`.

**Comment by nikklavzar** [comment]
> It might be a typo, it seems that you're using `SOCIALACCOUNT_STORE_TOKEN`, but from [the docs](https://django-allauth.readthedocs.io/en/latest/configuration.html), plural is used `SOCIALACCOUNT_STORE_TOKENS`.

Oh, I'm actually using the plural, made a typo in the comment

**Comment by Vaseles** [comment]
more thanks for answer

**Comment by PeiPeiWow** [comment]
OK, after a few hours of struggle, I finally solved this issue. My solution is as `follows:`

### 1. in settings.py you need the following:

- **Do not set SOCIALACCOUNT_PROVIDERS in settings.py, in your admin backend set it.**

- **SITE_ID = 2, not 1 !!!**

- **SOCIALACCOUNT_STORE_TOKENS = True**

my complete settings.py:
"""
```
Django settings for anyVision project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-cqhwu=lw%*k+n!k8*j&ejz#ea7t2wpdlmb7=$1dyi0cet06%h+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'userAuth',  # add this
    'rest_framework',
    'rest_framework.authtoken',
    'dj_rest_auth',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'dj_rest_auth.registration',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'corsheaders',

]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # corsheaders
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'anyVision.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'anyVision.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_AUTH = {
    'SESSION_LOGIN': True,
    'USE_JWT': True,
    'JWT_AUTH_HTTPONLY': False,
    'JWT_AUTH_COOKIE': 'my-app-auth',
    'JWT_AUTH_REFRESH_COOKIE': 'my-refresh-token',
    # 'JWT_AUTH_RETURN_EXPIRATION': True,
    # 'JWT_AUTH_REFRESH_COOKIE_PATH': 'http://127.0.0.1:8000/account/token/refresh/',
    # 'JWT_EXPIRATION_DELTA': timedelta(days=1),
    # 'JWT_REFRESH_EXPIRATION_DELTA': timedelta(days=7),
    # 'JWT_ALLOW_REFRESH': True,

}
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
### SITE_ID = 2
ACCOUNT_EMAIL_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'username'
ACCOUNT_EMAIL_VERIFICATION = 'optional'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        'dj_rest_auth.jwt_auth.JWTCookieAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema'
}


# --------------do not set this in setting.py------------------------------------------------------------------
# SOCIALACCOUNT_PROVIDERS = {
#     "google": {
#         "APP": {
#             "client_id": "yours",  # replace me
#             "secret": "yours",  # replace me
#             "key": "",  # leave empty
#         },
#
#         "SCOPE": [
#             "profile",
#             "email",
#         ],
#         "AUTH_PARAMS": {
#             "access_type": "online",
#         },
#         "VERIFIED_EMAIL": True,
#     },
# }
# -------------------------------------------------------------------------------------------------------------------------

SOCIALACCOUNT_STORE_TOKENS = True




CORS_ALLOW_ALL_ORIGINS = True

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=5),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=90),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
}


MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  
MEDIA_URL = '/media/'  

# dj-rest-auth settings~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
REST_AUTH_REGISTER_SERIALIZERS = {
    'REGISTER_SERIALIZER': 'path.to.your.RegisterSerializer',
}
REST_AUTH_SERIALIZERS = {
    'USER_DETAILS_SERIALIZER': 'path.to.your.UserDetailsSerializer',
}

```

<img width="1440" alt="image" src="https://github.com/pennersr/django-allauth/assets/128576445/5fbbca4c-67a0-4752-a196-3862d799053f">
### look at the arrow I point at Sites, click and open Add your site. in setting.py you need to set ALLOWED_HOSTS = ['127.0.0.1', 'localhost']


### make sure views.py has the right callback_urls which is matching the redirect URI you have set in Google API

```
from allauth.socialaccount.providers.google.views import GoogleOAuth2Adapter
from allauth.socialaccount.providers.oauth2.client import OAuth2Client
from dj_rest_auth.registration.views import SocialLoginView

class GoogleLogin(SocialLoginView): # if you want to use Authorization Code Grant, use this
    adapter_class = GoogleOAuth2Adapter
    # --------------------------------make sure views.py has the right callback_urls---------------------------
    callback_url = 'http://localhost:8000/accounts/google/login/callback/'
    client_class = OAuth2Client
```






### Make sure you have set the callback endpoint.

urls.py

```
from django.urls import path
from userAuth import views
from dj_rest_auth.views import LogoutView


urlpatterns = [
    path('google/login', views.GoogleLogin.as_view(), name='google_login'),
    # -------------------------------Make sure you have set the callback endpoint.--------------------------
    path('google/login/callback/', views.GoogleLogin.as_view(), name='google_callback'),
    path('logout', LogoutView.as_view(), name='logout'),
]
```

**Comment by FSchianchi** [comment]
Perfect, I'll try it within today.
Thank you so much for the answare!

If it worked, the problem would be the SOCIALACCOUNT_PROVIDERS in the wrong place.

About the SITE_ID I tested both 1 and 2, with 1 I deleted example.com in the list of sites and it works, with 2 I keep example.com in the list of sites and it works as well.

**Comment by pennersr** [comment]
The `SocialToken` model has a foreign key to the `SocialApp` the token originates from. Therefore, storing the token currently only works when having the app configuration in the database (in the `SocialApp` model) and not in the settings.

**Comment by pennersr** [comment]
@jnoring You're right, it's changed, see: d15c49b7

**Comment by pennersr** [comment]
No problem. It's a bit too early for a release, but just install using:

```
pip install git+https://github.com/pennersr/django-allauth.git@main#egg=django-allauth`
```

**Comment by pennersr** [comment]
Please use this: 639b4668

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3309
