### ISSUE TITLE
Idea Proposal: Allow a custom domain for redirect URIs

### ISSUE THREAD

**Issue by paxw-panevo** [pennersr/django-allauth#3310]
I'm hoping to use django-allauth to implement SSO (via OIDC/OAuth) on our multi-tenant SaaS app . Being a multi-tenant SaaS app, our django instance can have multiple domains:

- client1.example.com
- client2.example.com

When I register our SaaS app in the Identity Provider / IdP (e.g. Azure AD via Microsoft Graph), I also have to specify a redirect_uri. Since:

- we are a multi-tenant app
- Azure AD does not allow wildcards when specifying the redirect URI

It makes sense for us to specify a  "generic" domain for the redirect URI: `auth.example.com/account/<idp>/login/callback`

# Problem

allauth by default uses the `request` instance to craft the redirect/callback URI. 

- if user from client1 initiates SSO flow, the redirect_uri is client1.example.com/account/microsoft/login/callback
- if user from client2 initiates SSO flow, the redirect_uri is client2.example.com/account/microsoft/login/callback

This is problematic for IdPs (e.g. Azure AD via Microsoft Graph) where the redirect URI registered MUST match the specified redirect_uri seen in the IdP application (which, as mentioned in the previous section, is set to something generic `auth.example.com/account/<idp>/login/callback`). 

# Proposed Solution

1. Add a new OAUTH_REDIRECT_URI_DOMAIN setting and use this setting in places like OAuth2.get_callback_url

![image](https://user-images.githubusercontent.com/100712424/236066207-beed57bb-9d81-449a-9b43-83a287c26b18.png)

2. Create a new parameter `domain` in `build_absolute_uri` which takes precedence over anything else if available.

![image](https://user-images.githubusercontent.com/100712424/236066490-78c3dd16-9fd9-4411-943f-7e11917c375d.png)

I'm willing to open a PR if this sounds good.

---

Related issues:
https://github.com/pennersr/django-allauth/issues/1483
https://github.com/pennersr/django-allauth/issues/2601

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3310
