### ISSUE TITLE
Update Discord Provider for Changes to Username system

### ISSUE THREAD

**Issue by TurnrDev** [pennersr/django-allauth#3312]
This issue is mostly a reminder for myself, but Discord are switching their username system and so the Provider will need to be updated.

https://support-dev.discord.com/hc/en-us/articles/13667755828631

> To keep clients backwards-compatible, users that are migrated to the new username system will have a single zero (#0) discriminator. This will not appear in the client, but will be in payloads your app receives. After the migration to the new username system is complete, the 0 discriminator will be removed.

Todo: Add if statement so to check discriminator, if it's `"0"` or nonexistant, treat it as a new username (append `@` to the front?), also, append `#{discrim}` to the end

I'll create a PR for this soon

**Comment by p0lygun** [comment]
any updates ?

**Comment by TurnrDev** [comment]
Hi, sorry!

Been a busy few weeks with my poor kitty getting cancer :( 

I've got a few minutes now, I'll take a look

**Comment by pennersr** [comment]
Thanks @TurnrDev  .. sorry to hear about your Kitty, hope it turns out well!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3312
