### ISSUE TITLE
Two social apps for one provider.

### ISSUE THREAD

**Issue by abdullah13af** [pennersr/django-allauth#3314]
Is it possible to have two social apps for one provider?

Here is my use case:
I want to have two social apps for the "Microsoft" provider. One will be for organizations only and the other one will be for consumers (any user with a Microsoft account).

I know that I can set:
SOCIALACCOUNT_PROVIDERS = {
    'microsoft': {
        'TENANT': 'organizations',
    }
}

to only allow the organization's users to authenticate. And for consumers, I can set it to consumers (which is the default value). But the problem is I am unable to find a proper way to implement this idea. If anyone have any idea how I can implement this? or whether this is possible or not?

**Comment by bufke** [comment]
We work around this limitation by using the open id connect provider. That allows for creating multiple. It works with Azure AD. It's somewhat related to the issue I opened [here](https://github.com/pennersr/django-allauth/issues/3072). We might work on improving this some day, ideally as an upstream contribution or a custom provider.

**Comment by pennersr** [comment]
See: cc5279bb -- this allows you to have multiple providers.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3314
