### ISSUE TITLE
allauth.sociallogin complete_social_login has contradictory code

### ISSUE THREAD

**Issue by RomHartmann** [pennersr/django-allauth#3317]
There seems to be old code in allauth that makes no sense (and causes undesired behaviour)

https://github.com/pennersr/django-allauth/blob/77368a84903d32283f07a260819893ec15df78fb/allauth/socialaccount/helpers.py#L147C5-L148

---

`allauth.socialaccount.helpers.complete_social_login` has the following lines:
1. `assert not sociallogin.is_existing` - This checks if SocialAccount instance has been saved to db
2. `sociallogin.lookup()` - This makes even less sense - The docstring literally says "lookup existing account", and then it raises before it can check
3. `_complete_social_login()` - We then do the actual social login, _which handles existing SocialAccounts desirably`

I haven't done robust testing, but this makes no sense, and the reason I found it is because allauth seems to handle signup in the presence of an existing SocialAccount gracelessly. 

---

I'm just going to shoehorn a fix on my side because I'm in a hurry, but I wanted to put this on your radar. Perhaps I'm missing something here, but there are also almost no useful docstrings or comments in this part of the code

**Comment by iarp** [comment]
I'm struggling to understand what fix you're having to apply and what is wrong here? Are you getting an error under certain circumstances? Do you just not like this block of code?

**Comment by pennersr** [comment]
The `assert not sociallogin.is_existing` merely asserts that the `sociallogin` data structure still represents a login for which we have not checked whether or not it is actually an existing account, because, the `lookup()` that follows is going to actually do that check.

This is not old code. As @iarp mentions, it's not clear what issue you are trying to address. Closing.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3317
