### ISSUE TITLE
Add features as in django jwt to improve developer experience much more

### ISSUE THREAD

**Issue by Akhilkokani** [pennersr/django-allauth#3321]
I'm really enjoying this repo, thank you so much @pennersr for making this possible! I'm working as a full-stack developer and we have managed to use this repo in several production-grade applications that we have built.

I wanted to request if we could integrate all the features that can be found in packages like DjangoJWT, which would really scope and use cases for this repo exponentially.

**Comment by pennersr** [comment]
Closing for the above mentioned reasons.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3321
