### ISSUE TITLE
Dead link in docs faq

### ISSUE THREAD

**Issue by paloha** [pennersr/django-allauth#3322]
This link "http://www.sarahhagstrom.com/2013/09/the-missing-django-allauth-tutorial/" in [docs faq](https://django-allauth.readthedocs.io/en/latest/faq.html) is dead. So probably could be removed.

**Comment by atc2146** [comment]
Thanks for noticing - submitted a PR here:
https://github.com/pennersr/django-allauth/pull/3323

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3322
