### ISSUE TITLE
Broken CSS on trying to sign in via Social Logins

### ISSUE THREAD

**Issue by light-handle** [pennersr/django-allauth#3325]
<img width="1053" alt="image" src="https://github.com/pennersr/django-allauth/assets/774134/d78b4170-bcdc-4214-8e85-803cfe3fd76f">

While trying to sign in with Github, the user is redirected to this page which shows broken CSS.

**Comment by pennersr** [comment]
The templates as delivered out-of-the-box are simply placeholders to get you going. It's up to you to provide proper styling et al.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3325
