### ISSUE TITLE
NoReverseMatch at /accounts/login/

### ISSUE THREAD

**Issue by ghost** [pennersr/django-allauth#333]
I have installed allauth app and it was working fine when I ran it with django's inbuilt server. But it has been producing "Reverse for 'facebook_login' with arguments '()' and keyword arguments '{}' not found" error since I published the entire project on apache server. The settings.py file is exactly the same as was on the development server. I have already added facebook app on admin. 

Error is produced at following line: 
<a href="{% provider_login_url provider.id process=process %}">{{provider.name}}</a>

Below is a screenshot of the error.

(https://f.cloud.github.com/assets/1644221/831198/347c3ed4-f1b6-11e2-9eb8-4ae3f077c76d.PNG)

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/333
