### ISSUE TITLE
Need help with AJAX/Fetch for form submissions

### ISSUE THREAD

**Issue by dishansa** [pennersr/django-allauth#3331]
Hi,

I would like to know how to use Ajax, Axios, or Fetch with Django-Allauth. I'm not quite sure about it. Specifically, I'm looking for a way to submit a form without reloading the page and displaying any user errors that may occur. The problem is that I have no idea how to achieve this, and the documentation doesn't provide much guidance on using Ajax, Fetch, or similar methods.  I have read several issues and articles on this topic but still face difficulties.

I really appreciate any help you can provide.

Best regards.

**Comment by pennersr** [comment]
The allauth views can be posted to using XHR requests (using Axios, fetch or whatever). It is indeed short on documentation, but the gist of it is, that if there is a form taking e.g. `login` and `password` as its form fields, you can post the same using XHR and you'll get a JSON response back. Be sure to POST using `application/x-www-form-urlencoded`. 

Closing, not an issue in allauth.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3331
