### ISSUE TITLE
Potential security issue

### ISSUE THREAD

**Issue by psmoros** [pennersr/django-allauth#3332]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@runkixt) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by pennersr** [comment]
It would be good to indeed explicitly document the procedure, but for now, please contact me privately via raymond.penners@intenct.nl.

**Comment by pennersr** [comment]
The reported security issue is invalid.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3332
