### ISSUE TITLE
Display provider login only if the current site is added in Provider chosen sites

### ISSUE THREAD

**Issue by gschurck** [pennersr/django-allauth#3339]
Currently, with Django Sites enabled, if I add a django-allauth Provider, it will always be displayed in login if we use the `get_providers` function, whether we chose the website or not in the admin :
![image](https://github.com/pennersr/django-allauth/assets/21091232/6f2ba79d-de22-40a3-aa48-fba3dfd0709a)

It is also specified in the doc of the `get_providers` function that the providers should be ones for the current site : 
![image](https://github.com/pennersr/django-allauth/assets/21091232/756a86d8-a43b-4ad0-99ff-f640c0fa51f8)

**Comment by pennersr** [comment]
This is fixed in the current main branch.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3339
