### ISSUE TITLE
[Question] `email` field on `User` and `EmailAddress` models

### ISSUE THREAD

**Issue by MariaMozgunova** [pennersr/django-allauth#3343]
Hi,

The `User` model has an `email` field. In the meantime, `EmailAddress` holds `email` as well. What is the use case of having the `email` address in multiple places?

For example, the `save_user` method on the `DefaultAccountAdapter` explicitly sets email on the `User` model.

How can I find the answers to such conceptual questions in the future?

**Comment by pennersr** [comment]
Django's `User` model has an `email` field, that's not something under the influence of allauth. That `email` field actually resides in `AbstractUser`, so if your project implements its own `User` model, you could inherit from `AbstractBaseUser` instead and then you wouldn't have an `email` field.  But as said, this is all out of scope for allauth. What's in scope is this: if your user model has an email field (configurable via `ACCOUNT_USER_MODEL_EMAIL_FIELD`) then allauth keep the primary `EmailAddress` in sync there.

**Comment by MariaMozgunova** [comment]
Are there any projects that implement a custom `User` model inherited from `AbstractUser`? So that they do not have `User.email` and rely only on the `EmailAddress` keeping the email address?

**Comment by pennersr** [comment]
@MariaMozgunova It's up to your own project to define the user model. You can use the built in one, or define one of your own inheriting from either `AbstractBaseUser` or `AbstractUser`.

https://docs.djangoproject.com/en/4.2/topics/auth/customizing/#specifying-a-custom-user-model

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3343
