### ISSUE TITLE
Why not using User.objects.create_user ?

### ISSUE THREAD

**Issue by elnygren** [pennersr/django-allauth#3345]
Django docs suggest using [User.objects.create_user](https://docs.djangoproject.com/en/4.2/topics/auth/default/#creating-users), however, this library is using `User().save()` instead ([here](https://github.com/pennersr/django-allauth/blob/68dd4c54b420c00c57b45fa6526538ed7d4042ac/allauth/account/adapter.py#L249)). 

This means any custom behavior in `create_user` is skipped. Just wondering would it be better to use it instead?

Anyway, the fix here is obviously simple, as one can easily override the adapter's save_user behavior :)

**Comment by pennersr** [comment]
Can you please make this more concrete? What problems are you running into with the current approach? Looking at the Django source, I don't see anything we're missing out on, so this might be a case of "if it ain't broke don't fix it".

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3345
