### ISSUE TITLE
unauthorized_client error with Twitter Oauth2 social authentication

### ISSUE THREAD

**Issue by gschurck** [pennersr/django-allauth#3347]
I try to use Twitter Oauth2 social authentication with django-allauth, but I get this error : 
`unauthorized_client : Missing valid authorization header`

I checked multiple times and all my Twitter config seems ok, with good callbacks URL and Tokens set in django-allauth.

Any idea on how to fix it ?

**Comment by katomaso** [comment]
Gettting the same thing: `'{"error":"unauthorized_client","error_description":"Missing valid authorization header"}`

It seems that allauth needs to encode your username/password into the initial requests as described in https://developer.twitter.com/en/docs/authentication/oauth-2-0/user-access-token

**Comment by gschurck** [comment]
Yes same it's not working for me neither. And classic Twitter auth is also not working for me with allauth...

**Comment by gschurck** [comment]
Thanks, I found that the missing part was the `tweet.read` scope, Twitter OAuth2 is working for me now with allauth !
I opened a PR to fix that.

**Comment by katomaso** [comment]
Nice work! Do you know if there is a way how to re-define scope without modifying the source code? I tried `settings.SOCIALACCOUNT_PROVIDERS['twitter']['SCOPE']`  but it didn't work

**Comment by gschurck** [comment]
Thanks ! The good provider name is `twitter_oauth2` and not `twitter`, then it should work.

**Comment by gschurck** [comment]
The fix as been merged, it will be included in the next release version `0.55`

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3347
