### ISSUE TITLE
Getting user birthday data from Google social login

### ISSUE THREAD

**Issue by rokas-bendikas** [pennersr/django-allauth#3350]
Hi, I am building a Django backend, that allows users to login via standard credentials as well as Google social login options. I want to retrieve user's birthday in order to verify their age. I have defined a custom SocialAccountAdapter where I'm trying to query the Google API to retrieve the birthday, however, sociallogin.token is returned as None. Am I missing something and is there an easier way to achieve this?

My SocialAccountAdapter:

`class CustomSocialAccountAdapter(DefaultSocialAccountAdapter):
    def populate_user(self, request, sociallogin, data):
        user = super().populate_user(request, sociallogin, data)

        if sociallogin.account.provider == "google":
            # Get the birthday of the user by querying the Google+ API
            token = sociallogin.token.token

            # Make a GET request to the People API
            response = requests.get(
                "https://people.googleapis.com/v1/people/me?personFields=birthdays",
            )

            # Check if the request was successful
            if response.ok:
                # Parse the JSON response
                person_data = response.json()

                # Get the user's birth year
                birthdays = person_data.get("birthdays", [])
                for bd in birthdays:
                    date = bd.get("date", {})
                    if "year" in date:
                        user.birth_year = date["year"]
                        break

        picture_url = sociallogin.account.extra_data.get("picture")
        if picture_url:
            try:
                # Download the profile picture
                response = requests.get(picture_url, timeout=10)

                response.raise_for_status()  # Raises a HTTPError if the status is 4xx, 5xx

                # Create a new Django file-like object to use in your ImageField or FileField.
                picture_file = ContentFile(response.content)

                # Generate a unique filename
                picture_filename = generate_unique_filename(user.email)

                # You'll need to manually write the appropriate extension
                picture_file.name = picture_filename

                # Assign the file to the user's picture field
                user.picture = picture_file

            except (RequestException, IOError) as e:
                # Log the error
                print(f"Error downloading profile picture: {e}")

        return user
`

My settings.py:
`SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": [
            "profile",
            "email",
            "https://www.googleapis.com/auth/user.birthday.read",
        ],
        "AUTH_PARAMS": {
            "access_type": "online",
        },
    }
}`

**Comment by pennersr** [comment]
`populate_user()` is called while the `sociallogin` instance is still being assembled. You should hook up to `pre_social_login()` -- at this stage the `sociallogin` is fully complete.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3350
