### ISSUE TITLE
Social allauth filter users 

### ISSUE THREAD

**Issue by spinxi** [pennersr/django-allauth#3351]
I'm using social-allauth with microsoft in my django project, but I'm facing some issues, and really cant find the answer that's why I'm here.

I need to filter users while creating it's table in database.

It means that I want some users to have is_driver=True in user Database (I have custom UserModel) and some of them need to have is_dispatcher=True or is_accountant=True

So, I really don't get how to do it, how to filter users, is it microsoft part of work (should I assign roles on email or what)I think?

I will use signals for this and really can't figure it out how to do it:

​
Somethimg like this I think:

```
    @receiver(social_account_added)
    def handle_social_account_added(request, sociallogin, **kwargs):
        if sociallogin.account.provider == 'microsoft':
            user = sociallogin.account.user

            if 'Driver' in roles(have no Idea how to get that roles):
                user.is_driver = True
                
            elif 'Dispatcher' in roles:
                
                user.is_dispatcher = True
            else:
                user.is_driver = False
                user.is_dispatcher = False

            user.save()
```

**Comment by pennersr** [comment]
https://django-allauth.readthedocs.io/en/latest/faq.html#why-did-you-just-close-my-issue

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3351
