### ISSUE TITLE
Possible BUG: blocking user with email address

### ISSUE THREAD

**Issue by agy-why** [pennersr/django-allauth#3353]
Dear developers,

version: `allauth` 0.54.0 (`django` 4.2.3)

While testing our services, it seems that we could maliciously block some users from registering to our services:

1. a malicious user creates an account with the email address of another user. ex: username: `iAmAnIdiot` email: `user@example.com`)
2. as a results a profile is created and a verification email is sent to `user@example.com`
3. when the valid user `user` wants now to create an account with the "stolen" email, no new profile is created, the user gets a validation email telling that email is already in use. And obviously, validating the email would lead to an identity robbery.

A possible solution would be to:
1. always create a profile (as long as the email is not verified) 
2. always resend a verification email each time a new profile is created (incl. the username in the email, for disambiguation)
3. that way the first user verifying the email gain the race and the remaining (malicious) accounts are deleted.

In case we misunderstood the mechanics of the verification, I'd be glad to know the proper way to prevent this "blockage".

We thank you in advance for clarifications,

Yori Fournier

**Comment by pennersr** [comment]
The email address is the key to the account. In this scenario, the malicious user adds a key owned by the valid/real user (`user@example.com`) to an account. Why do you label this as identity robbery? Nothing is stolen -- the real user can always issue a password reset and re-secure the account.  There are multiple points at which the real user should become aware that something fishy is going on:

- (S)he received a confirmation email, but (s)he did not signup for any service. 

- When trying to signup him/herself, an email is sent to the user explaining that an account already exists. 

At any point, the user is free to issue a password reset and reclaim the account. So, nothing is robbed from the user.

**Comment by pennersr** [comment]
>  As far as we know, issuing a password reset is only possible after email verification. 

This is not the case.  Therefore, the user can always reclaim the account, and thus is there no case of identity robbery. Closing.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3353
