### ISSUE TITLE
Confirmation email can_confirm always "False"

### ISSUE THREAD

**Issue by SimonvdFliert** [pennersr/django-allauth#3354]
Hi,

I am trying to include allauth into my project. I followed the tutorial and got most of it working, however I am getting stuck when trying to verify the email through the confirmation e-mails. I copied the templates in my project so that I can override them. I tried debugging this for days, but I have yet to find a solution.

Here are my settings (aside from the additions mentioned in the documentation):

"EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS= 7
ACCOUNT_LOGIN_ATTEMPTS_LIMIT = 5
ACCOUNT_EMAIL_VERIFICATION ="mandatory"
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
ACCOUNT_LOGIN_ATTEMPTS_TIMEOUT = 86400
LOGIN_REDIRECT_URL = '/portfolio/'
LOGIN_URL = 'accounts/login/'
ACCOUNT_LOGOUT_REDIRECT_URL ='/accounts/login/'"

Signing up and logging in works, however, verifying the email address does not. I receive the e-mail in my terminal (due to the email_backend) and when clicked I get to the verification page, but I cannot post the verification, as it always shows:

"Unable to confirm {{ email }} because it is already confirmed by a different account."

I tried debugging the source code by overriding the methods to see what is happening. I identified that the {% if can_confirm %} is not triggering, making it impossible to POST the verification.  I tried going through the source code and identifying why the can_confirm is always False, but I don't fully understand why it is happening.

I found that the value is set in the class, ["can_confirm": self.object.email_address.can_set_verified(),]

I also reinstalled django a few times, removed all cookies that could be hampering with the site, removed all users from my database who is not a superuser and I also ensured that the url's are in the right order.

Has someone seen this issue before? Am i making an obvious mistake?

Kind regards,

Simon

**Comment by SimonvdFliert** [comment]
Hi Iarp,

Thanks for commenting. I did check this before hand and checked it here again.

All email adresses are unique, and I make sure that all email-addresses of new users are fully unique (bar the provider gmail.com, i did also test with a different provider, namely hotmail, and the issue still persisted)

**Comment by pennersr** [comment]
The `can_confirm` related functionality is not released yet. Could it be that you are using the latest allauth release (0.54.0), but with a copy of the templates from the current main branch? 0.54.0 does not set `can_confirm`, meaning, that `{% if %}` won't be handled properly if you mix versions.

**Comment by SimonvdFliert** [comment]
Ah yes, that was the issue. Retrieved the corresponding HTML templates and it works well.

Thanks for the help pennersr!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3354
