### ISSUE TITLE
PasswordResetFromKey from doesn't have a class

### ISSUE THREAD

**Issue by rasca** [pennersr/django-allauth#3359]
All the other forms have a class which let's me style them via css.

I have all accounts forms styled but this one, which is the only one missing a class.

PR: https://github.com/pennersr/django-allauth/pull/3358

**Comment by rasca** [comment]
PR merged! Thanks!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3359
