### ISSUE TITLE
Password Change View - success_url redirect

### ISSUE THREAD

**Issue by code-kasha** [pennersr/django-allauth#3360]
Hello, I saw a closed ticket from 2014 that concluded with overriding the view and adding a success_url

class PasswordChangeView(views.PasswordChangeView):
    success_url = reverse_lazy("index")
    template_name = "account/password_change.html"
    
Has the solution been updated? Sorry if I missed a ticket in my search, I was quite thorough

**Comment by code-kasha** [comment]
Definitely not a bug, I just wanted to know if PasswordChangeView can redirect to a custom path with a configuration setting like LOGIN_REDIRECT_URL, without actually overriding the password change view. Since it's been a couple of years since that answer was posted. No bugs

**Comment by pennersr** [comment]
There is no setting for this...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3360
