### ISSUE TITLE
Unable to confirm email address due to 'already confirmed' error

### ISSUE THREAD

**Issue by TheTiredOne22** [pennersr/django-allauth#3363]
I'm encountering an issue with Django-allauth while trying to confirm email addresses. When a user attempts to confirm their email address, they receive the following error message: "Unable to confirm because it is already confirmed by a different account."

**Comment by pennersr** [comment]
When filing bugs, please specfiy a clearly reproducible scenario. This report does not contain sufficient information to track anything down.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3363
