### ISSUE TITLE
OAuth Error with Twitter authentication v1

### ISSUE THREAD

**Issue by gschurck** [pennersr/django-allauth#3366]
When trying to login using `twitter` provider, I get this error :
`('Invalid response while obtaining request token from "api.twitter.com".',)`

Any solution for this ? Is this a limitation of the free usage for Twitter API v1 ?

**Comment by gschurck** [comment]
Finally it was just an issue on my side, misconfiguration of callback URL in Twitter Dev Portal.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3366
