### ISSUE TITLE
How to override user model?

### ISSUE THREAD

**Issue by Sabrebar** [pennersr/django-allauth#3367]
I want to use the default all-auth User model, but I wanna add some new feater (for example a method User.is_subscribed to go with my subscription system).
The thing is I have no idea how to do that properly, can someone please help me?

**Comment by pennersr** [comment]
https://django-allauth.readthedocs.io/en/latest/faq.html#why-did-you-just-close-my-issue

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3367
