### ISSUE TITLE
What is social application token?

### ISSUE THREAD

**Issue by TGoddessana** [pennersr/django-allauth#3368]
How are you?

First, thank you so much for creating and maintaining such a useful library.

I have implemented google login with django-allauth, and I have a few questions.

Question: What is social application token?
When I install the app, it adds an admin panel where I can add "social application token" as shown below.

![image](https://github.com/pennersr/django-allauth/assets/88619089/89edee99-fc11-40ea-92f0-a104739c6e82)

In fact, I did a Google login without putting anything in this panel, and noticed that the access token and refresh token are returned correctly. 

What is this, and why is it needed?
If it's in the official documentation and I just didn't find it, I apologize.

**Comment by pennersr** [comment]
https://django-allauth.readthedocs.io/en/latest/faq.html#why-did-you-just-close-my-issue

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3368
