### ISSUE TITLE
Manually creating social users

### ISSUE THREAD

**Issue by andresmrm** [pennersr/django-allauth#3369]
Hi! I'm using `allauth` with `dj-rest-auth`, so I first openned an [issue there](https://github.com/iMerica/dj-rest-auth/issues/530). But I think most of the customization necessary for this to work is more related to `allauth`, so I'm posting it also here.

As I said in my other issue:

> I need to have strict control over user creation. No automatic sign-up/registration.
> The desired flow is:
> 
> - I create a Django user through Django Admin, setting a Google email for it.
> - Then the user can login with a Google account with the same email.
>   If someone tries to login with a Google account which email isn't present in the User table, the access is denied.
> 
> At first I wanted to manually created all the required data for user registration before the user logins. But it looks like allauth creates data at socialaccount table with an ID that comes from Google login process.

I found this [issue](https://github.com/pennersr/django-allauth/issues/573) that seems similar to mine. But if I try to get `sociallogin.account` as shown there, it raises a `RelatedObjectDoesNotExist: SocialAccount has no user.`.

Anyway, I mixed the code from that issue with the code I posted at my another issue and ended with this:

```Python
# settings.py
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_ADAPTER = 'myapp.users.adapter.AccountAdapter'
SOCIALACCOUNT_ADAPTER = 'myapp.users.adapter.SocialAccountAdapter'
SOCIALACCOUNT_AUTO_SIGNUP = False


# adapter.py
from allauth.account.adapter import DefaultAccountAdapter
from allauth.account.utils import user_email
from allauth.socialaccount.adapter import DefaultSocialAccountAdapter
from django.contrib.auth import get_user_model
from django.core.exceptions import BadRequest, PermissionDenied


class AccountAdapter(DefaultAccountAdapter):
    def is_open_for_signup(self, request, **kwargs):
        return False


class SocialAccountAdapter(DefaultSocialAccountAdapter):
    def is_auto_signup_allowed(self, request, sociallogin):
        return False

    def pre_social_login(self, request, sociallogin):
        email = user_email(sociallogin.user)
        User = get_user_model()

        if not email:
            raise BadRequest()

        # Add this after allauth 0.55 release?
        # if EmailAddress.objects.is_verified(email):
        #     raise PermissionDenied()

        try:
            user = User.objects.get(email=email)
        except User.DoesNotExist:
            raise PermissionDenied()

        if not sociallogin.is_existing:
            if sociallogin.user.first_name and not user.first_name:
                user.first_name = sociallogin.user.first_name
            if sociallogin.user.last_name and not user.last_name:
                user.last_name = sociallogin.user.last_name

            sociallogin.connect(request, user)
```

Would this be a recommended way to do it?

> Until recently `allauth` had a [scary warning](https://github.com/pennersr/django-allauth/blob/cc5279bb61dba9cf0fafb10f4ae175c018749f1f/allauth/socialaccount/adapter.py#L152-L161) related to using the email of an existent user. But I'm not sure if this applies to my case, since I'm only using Google for social login (besides regular local login).

Thanks for the attention!

**Comment by pennersr** [comment]
https://django-allauth.readthedocs.io/en/latest/faq.html#why-did-you-just-close-my-issue

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3369
