### ISSUE TITLE
Phone number as username

### ISSUE THREAD

**Issue by nshayanfar** [pennersr/django-allauth#3373]
I have a use case that requires me to accept email and phone number as username. Now AllAuth has the ability to set phone number as username. The exact area that I have problem with is that the phone number should also be verified (the same routine as email). What is your suggestion?
I am open to pull requests also. Now I see two paths:
1- Add a third field specifically named "phone number" to the user and setup the necessary configuration fields.
2- Add optional verification for username field.

Is this something that you wish to include in the library? What am i missing?

**Comment by pennersr** [comment]
allauth does not provide a user model, so "adding a field phone number to the user" is not going to work. Also, this project makes as little assumptions on the user model as possible, so storing phone numbers in a user name field won't work either. All in all, the way you have specified it is not really compatible with the way this project is set up, it's best to keep this in a project of its own.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3373
