### ISSUE TITLE
SAML and OIDC organization sso

### ISSUE THREAD

**Issue by ryanhiebert** [pennersr/django-allauth#3375]
I'm happy to see the recent commits of SAML into main, and the implementation appears great to me. I intend to put the main branch into my staging environment to test, give feedback, and contribute if that proves useful. I do have a couple questions, if you have the opportunity to answer:

1. How can I best assist you in completing this feature? Are there specific places that you'd like me to particularly pay attention to?
2. What's your feeling about extending the approach you're taking for saml to OpenID Connect? I'm wanting to provide OIDC as an alternative to SAML for SSO for the organizations we have as clients.

**Comment by pennersr** [comment]
1. The SAML functionality is complete, though it had little mileage so far. So just put it to the test and report back any issues you encounter.
2. If your project has its own organization model, you likely want some kind of foreign key from that model to a `SocialApp` representing the provider for that organization. That would work for both OIDC and SAML, the only difference is that for SAML the url is of the form `/accounts/saml/<org-slug>/.../` and for OIDC it is `/accounts/<org-slug>/...`.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3375
