### ISSUE TITLE
Security relevance of SOCIALACCOUNT_LOGIN_ON_GET

### ISSUE THREAD

**Issue by jakdevmail** [pennersr/django-allauth#3376]
Hello there!
Going through the docs the setting SOCIALACCOUNT_LOGIN_ON_GET stands out for allowing a login merely via a GET-Request instead of the default POST-request.

It mentions security implications when setting this to True (does enabling GET-Request to initialize the login flow).

However, i don't see a reference for **why** this is a security problem. Could someone clarify?

Maybe adding this to the docs would be useful for the future as well.

Best regards

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3376
