### ISSUE TITLE
Login via Google issue 

### ISSUE THREAD

**Issue by darbre** [pennersr/django-allauth#3377]
I connected Allauth and Google provider.
‌
I expect that the user should be redirected to Google to select an account every time when user clicks Log In via Google button.
‌
But in my case user can't switch between Google accounts and truelly Logout from account:

1. User Login via Google account 1
2. User logs Out
3. The user clicks Log In via Google button and immediately logs into the same Google account 1 without asking which of the Google accounts the user wants to Log In.

‌
Does anyone know how to solve this problem?

**Comment by dishansa** [comment]
Can you provide the settings related to your allauth?

**Comment by derek-adair** [comment]
@pennersr Really need an issue template to encourage users providing more background info.  We have no clue what this users environment looks like.

------------------

This would be a pretty large problem if this is true.

**Comment by derek-adair** [comment]
tag as awaiting feedback or w/e...

**Comment by saleemjawad** [comment]
unable find the google in providers while registering **admin/socialaccount/socialapp/add/**

**Comment by pennersr** [comment]
`See` https://github.com/pennersr/django-allauth/issues/3787#issuecomment-2100192240

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3377
