### ISSUE TITLE
Overirding the templates issue

### ISSUE THREAD

**Issue by iMuhammadHassan** [pennersr/django-allauth#3379]
I make my application in django and install the allauth and configure in the settings file but i can't override the template of the provided by allauth..

I make templates directory in my main directory and under this i make account directory and in this i create a file login.html nut it does not override ..???

my_app/templates/account/login.html

**Comment by pennersr** [comment]
Likely due to the Django template loading order -- make sure your app/project gets priority (is listed first).

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3379
