### ISSUE TITLE
Intermittent login with Google errors

### ISSUE THREAD

**Issue by kate-skorija** [pennersr/django-allauth#3380]
We are using allauth library to allow login via Google on our site. We did not override any allauth functionality, or change any of our code around logging in recently. The error message for the intermittent failures is: 
```
"exception": "Error retrieving access token: b'{\\n \"error\": \"invalid_grant\",\\n \"error_description\": \"Bad Request\"\\n}'"
```
 We are using django-allauth==0.52.0. It seems this is affecting around 30% of users attempting to login with Google. 
 Any help or additional context would be appreciated.

**Comment by kate-skorija** [comment]
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.9/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 144, in dispatch
    access_token = self.adapter.get_access_token_data(request, app, client)
  File "/app/.heroku/python/lib/python3.9/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 70, in get_access_token_data
    return client.get_access_token(code, pkce_code_verifier=pkce_code_verifier)
  File "/app/.heroku/python/lib/python3.9/site-packages/allauth/socialaccount/providers/oauth2/client.py", line 93, in get_access_token
    raise OAuth2Error("Error retrieving access token: %s" % resp.content)
allauth.socialaccount.providers.oauth2.client.OAuth2Error: Error retrieving access token: b'{\n  "error": "invalid_grant",\n  "error_description": "Bad Request"\n}'

**Comment by kate-skorija** [comment]
A follow up question:
For the authentication errors, we would like pass some additional context to determine if the user has clicked on our 'Log in with Google' or 'Sign in with Google' button.
Here is what our log in button looks like, and we've tried to pass the 'login' info via the context attribute:
```
  <a class="login-btn login-btn-google" href="{% provider_login_url 'google' context='login' %}">{{ text }}</a>
```
But I have not been able to figure out a way to access this additional context in the authentication error signal. 
Is there any way to do so? I see there is an extra_context parameter but I'm not sure how to get info to that parameter. 
We are also hoping to access the user email that failed to authenticate.

**Comment by pennersr** [comment]
This issue is likely project/deployment specific -- closing as this is not actionable.

**Comment by dip-thistle** [comment]
> This issue is likely project/deployment specific -- closing as this is not actionable.

@pennersr why do you think this is a project/deployment specific error?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3380
