### ISSUE TITLE
Provider type not showing correctly in Django admin for OIDC and SAML

### ISSUE THREAD

**Issue by ryanhiebert** [pennersr/django-allauth#3381]
I'm using the latest commit on `main` for my testing. With the recent changes to OpenID Connect and SAML providers, which I'm really happy for, I'm finding that the displayed values for the names are giving me something like the following:

```
<property object at 0xffff86ef22f0>
```

This is happening because the `ProviderRegistry.as_choices()` method is attempting to read the `.name` property on the `provider_cls`, but these are properties that will only resolve to values when the class is instantiated. Since this is used in the provider dropdown, this is intended to be a _type_ of provider, so I expect that a class-attribute name is appropriate, but I'm not sure how you might want to spell this. As it is currently, I can't tell which is openid connect and which is SAML without inspecting the HTML to see what that `id` is.

------

<img width="507" alt="Screenshot 2023-08-17 at 9 47 37 PM" src="https://github.com/pennersr/django-allauth/assets/425099/683a0a6b-6aab-4c48-8584-5dfd37f776c2">

------

<img width="429" alt="Screenshot 2023-08-17 at 9 47 51 PM" src="https://github.com/pennersr/django-allauth/assets/425099/f2e6b862-db68-4a4c-857c-35e6bbf12ce3">

**Comment by pennersr** [comment]
Closed via 6e0725b0

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3381
