### ISSUE TITLE
[Azure/microsoft] The provided request must include a 'client_secret' input parameter

### ISSUE THREAD

**Issue by moovida** [pennersr/django-allauth#3388]
Hi, I am having trouble authenticating with Azure AD and am not sure what the issue might be.  I started from this tutorial and made it first work with github: https://learndjango.com/tutorials/django-allauth-tutorial

Then I moved to add azure AD support 
I added the following to settings.py (beyond the installed apps for microsoft and azure):

![image](https://github.com/pennersr/django-allauth/assets/390250/2485cc1d-0170-4389-b794-2729a829e7c0)

Then created the social application in the django admin using the registered app client id and secret:

![image](https://github.com/pennersr/django-allauth/assets/390250/44701a49-bc26-42d4-8c5e-24c8e1df2fbb)

When I now try to sign in I am properly taken to the organization page to pick my account, then a prompt asks me: Are you trying to sign in to django_azure_auth2?

So all good up to now. Once I push next, I get the generic: Social Network Login Failure

I placed a print in the exeption thrown in the OAuth2CallbackView of the oauth2 package and see the actual error:

```
Error retrieving access token: b'{"error":"invalid_client","error_description":"AADSTS70002: The provided request 
must include a \'client_secret\' input parameter.\\r\\n
[...]
"error_uri":"https://login.microsoftonline.com/error?code=70002"}'
[25/Aug/2023 07:07:21] "GET /accounts/microsoft/login/callback/?code=[...] HTTP/1.1" 200 621
```

Can anyone tell me if the client_secret created for the registered app in azure is the one that indeed has to be placed inside the Social applications "Secret key" in the django admin? 
Thanks for any hint (and for this amazing project of course).

PS: I also tried to change between azure and microsoft as a provider, but the current issue right now seems to be the client secret that does not propagate to where it should.

**Comment by moovida** [comment]
Ok, I got it, for some reason the app secret is not populated from the django admin, even if set.

But, if you define the secret in the settings (I had tried with **client_secret** before, but only debugging showed me that it is **secret** at that point) , it will work:

![image](https://github.com/pennersr/django-allauth/assets/390250/de6f0726-8c14-4518-a67f-ebbefd6005f6)

I would have loved to check why it does work for guthub, but right now trying the github login gives me some redirect uri mismatch. So I have to cleanup first. But this issue can be closed, if you think. I have too few knowledge to understand if it is ok to place that secret in the settings.py right now.

**Comment by pennersr** [comment]
At the time you had the app setup via the Django admin, did you happen to have an entry for `microsoft.APP` in `SOCIALACCOUNT_PROVIDERS` as well?

**Comment by moovida** [comment]
Yes @pennersr , is that the issue? Does one exclude the other? I had it there in first place because I would not know where to put the TENANT otherwise.

**Comment by moovida** [comment]
Yes @pennersr , is that the issue? Does one exclude the other? I had it there in first place because I would not know where to put the TENANT otherwise.

**Comment by pennersr** [comment]
TENANT is fetched like this:

```
class MicrosoftGraphOAuth2Adapter(OAuth2Adapter):
    provider_id = MicrosoftGraphProvider.id

    settings = app_settings.PROVIDERS.get(provider_id, {})
    # Lower case "tenant" for backwards compatibility
    tenant = settings.get("TENANT", settings.get("tenant", "common"))
```

So, it is not expected to be inside the APP dict. Therefore, you can still have TENANT in your settings and an app configured via the Django admin.

**Comment by moovida** [comment]
I tried to change as per your suggestions:

```
SOCIALACCOUNT_PROVIDERS = {
    'microsoft': {
        'TENANT': '....',
    }
}
```

and then have client id and secret in the social app from admin.

But at that point in the template the provider is not found:
![image](https://github.com/pennersr/django-allauth/assets/390250/b478ab59-4316-486e-bfc5-47692e330804)

without giving a particular exception.
Will try to dig more into that.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3388
