### ISSUE TITLE
Please don't error out on missing Facebook details...

### ISSUE THREAD

**Issue by Yetangitu** [pennersr/django-allauth#339]
I recently filed a bug report against a project using your code (https://github.com/fiduswriter/fiduswriter/issues/3) because there are environments where 'social' is just not done. They asked me to file a bug report here instead so here it goes:

Looking through the app config page I noticed it only gives the options of using Facebook, Twitter and Google. Neither of these are acceptable in any environment which has even the slightest respect for an author's privacy and confidentiality.

Please make it possible to use allauth using either a 'private' 'social' 'app' (lots of quotes there, for different reasons), openID or by foregoing on the social fad entirely. No configured social stuff should not be treated as an error...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/339
