### ISSUE TITLE
Documentation template needs updating

### ISSUE THREAD

**Issue by derek-adair** [pennersr/django-allauth#3395]
The navigation / theme for the documentation is quite dated and insufficient.  Main problem is the lack of navigation.

This is something I can spearhead given access.  *Personally* in my projects I elect to host static docs on my own domain so I have control, using [pydoc](https://docs.python.org/3/library/pydoc.html).  If that's not desirable updating the actual readthedocs.org template should be straight forward.

**Comment by derek-adair** [comment]
LOL!!!!!
>while the documentation can most certainly be improved, I am adhering to the debatable principle that keeping open issues around with respect to documentation is not very helpful in improving things. Please step in and file a pull request if you feel there is something unclear.

closing and moving to a discussion.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3395
