### ISSUE TITLE
Keycloak provider broken in version 0.55

### ISSUE THREAD

**Issue by antoinehumbert** [pennersr/django-allauth#3396]
In version 0.55 of django-allauth, the keycloak provider is broken because the callback url is hardcoded by OpenIDConnectAdapter at https://github.com/pennersr/django-allauth/blob/0.55.0/allauth/socialaccount/providers/openid_connect/views.py#L60, using "openid_connect_callback" URL name instead of "keycloak_callback").

The get_callback_url method should be redefined on class KeycloakOAuth2Adapter https://github.com/pennersr/django-allauth/blob/0.55.0/allauth/socialaccount/providers/keycloak/views.py#L13

**Comment by pennersr** [comment]
Ouch, can you prep a PR for this? :pray:

**Comment by antoinehumbert** [comment]
I'll do.

Instead of redefining get_callback_url in KeycloakOAuth2Adapter with the same implementation as in the base class OAuth2Provider, I'm thinking about:
- create a BaseOpenIDConnectAdapter implementing methods of actual OpenIDConnectAdapter except constructor (so without provider_id set on the class nor initiated on instances by constructor) and the current get_callback_url
- make OpenIDConnectAdapter inherit this base class and redifining the constructor (to set provider_id) and get_callback_url
- make KeycloakOAuth2Adapter inherit this base class

This way, we could also modify implementation of keycloak login and callback views by providing the KeycloakOAuth2Adapter class to .adapter_view() instead of an instance as the latter would not be required anymore

What do think about that ?

**Comment by antoinehumbert** [comment]
Hi @pennersr, will you create a branch for version 0.55 hotfixes I should start from for this fix, or would you like this PR to occur on the main branch and corresponding commit will ve cherrypicked for creation of a 0.55.1 version ?

**Comment by antoinehumbert** [comment]
The main reason is because when not using `allauth/urls.py` in a project (that's my case), but only `allauth/socialaccount/providers/keycloak/urls.py` (because we only want to allow keycloak authentication and do not want signin, signup views - we do auto signup - ...), then the "openid_connect_callback" URL cannot be reversed as it's not defined in project's urls.

The second reason is, as you said, because it is not pretty :
- we, indeed, have two URL patterns in defined urls that match the same path, and it works because openid_connect URLs were explicitly moved at the end of url patterns, but from a semantic point of view I'd rather reverse `keycloak_callback` when I want to work with keycloak rather than reversing `openid_connect_callabck` (even if the result is the same)
- also, the urls for `openid_connect` are *harcoded* in `allauth/socialaccount/providers/keycloak/urls.py` whereas `keycloak` urls are built from the *standard* `default_url_patterns` (https://github.com/pennersr/django-allauth/blob/main/allauth/socialaccount/providers/oauth2/urls.py#L6). So, we have definition of *same* URLs from two distinct sources with presumably no guarantee they still be in sync in the future.

I'll submit a PR and we can validate if its ok for you

**Comment by antoinehumbert** [comment]
To complete my previous comment, I didn't tested it but I think that even when including `allauth.urls` in project's urls.py, as soon as `openid_connect` provider is not defined in `SOCIALACCOUNT_PROVIDERS`, the `openid_connect_callback` URL will not be included in allauth urls, thus leading to a `NoReverseMatch` while trying to get the callback URL for keycloak.

So I think the problem is not limited to my particular project which only includes `allauth/socialaccount/providers/keycloak/urls.py`, but may also occur for any project defining `keycloak` provider and not `openid_connect` provider in `SOCIALACCOUNT_PROVIDERS`.

**Comment by pennersr** [comment]
It would be worthwhile to see if Keycloak can be removed completely, and relying solely on the `openid_connect` provider. Given that Keycloak was implemented before the OIDC implementation arrived, and then sort of started reusing that OIDC implementation, things got a bit messy. In any case, see the latest release (0.55.2) for a fix.

**Comment by antoinehumbert** [comment]
Thanks for the new release. I'll try to get some time looking at your proposal for removal of keycloak provider

**Comment by pennersr** [comment]
@antoinehumbert I've just tested it myself and it seems that it just works. The only thing you need is this config:

```
SOCIALACCOUNT_PROVIDERS = {
    "openid_connect": {
        "APPS": [
            {
                "provider_id": "keycloak",
                "name": "OIDC Keycloak",
                "client_id": "allauth",
                "secret": "hidden",
                "settings": {
                    "server_url": "http://keycloak:8080/realms/master/.well-known/openid-configuration",
                },
            }
        ]
    }
}
```

Don't forget to remove the Keycloak app from `INSTALLED_APPS`.

Given this, Keycloak will be scheduled to be removed.

**Comment by pennersr** [comment]
Removed via: 458a2a3c

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3396
