### ISSUE TITLE
Let SAML slo_url be optional

### ISSUE THREAD

**Issue by ryanhiebert** [pennersr/django-allauth#3400]
Some providers, such as Google Workspace, do not provide either a `metadata_url` or an `slo_url`. Using `"slo_url": ""` is a workaround, but it would make sense for this to be optional.

I may be able to work up a pull request if this is something worth implementing, but I'm not sure whether it would happen in a timely manner so I don't want to promise it.

/cc @agorka-contractsafe

**Comment by pennersr** [comment]
Closed via 336ebf18

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3400
