### ISSUE TITLE
provider_login_url and Jinja: any replacement for providers.registry.by_id ?

### ISSUE THREAD

**Issue by alee** [pennersr/django-allauth#3408]
Now that `providers.registry.by_id` is gone, what's the "right" way to implement `provider_login_url` for Jinja2?

I'd been using something similar to this SO post: https://stackoverflow.com/questions/45174765/use-djangos-allauth-with-jinja2

Relevant templatetags code:

https://github.com/pennersr/django-allauth/blob/fccd33f68b4c19acfa4277c97fbbf0a9226d2367/allauth/socialaccount/templatetags/socialaccount.py#L46

It'd be nice if we could extract some common function / logic from `ProviderLoginURLNode` that could be reused by both the registered Django templatetag function and a jinja configuration that injects `provider_login_url` into a jinja Environment...

I've tried using the same `get_adapter` based code in the current `provider_login_url` method

```
from allauth.socialaccount.adapter import get_adapter

def provider_login_url(request, provider_id, **kwargs):
    provider = get_adapter(request).get_provider(request, provider_id)
    ... # other logic to clean up next, auth_params etc.
    return provider.get_login_url(request, **kwargs)
```

and doing it directly by querying the `SocialApp` model

```
from allauth.socialaccount.models import SocialApp

def provider_login_url(request, provider_id, **kwargs):
    provider = SocialApp.objects.get(provider=provider_id).get_provider(request)
    ...
    return provider.get_login_url(request, **kwargs)
```

but both of these methods fail during our automated tests because `SocialApp` model instances apparently aren't being created in the test environment.

Do I need to set up a fixture for these, or is there a better way of generating a `provider_login_url` given a provider_id string e.g., ("orcid", "github", "google", "cilogon")?

**Comment by pennersr** [comment]
`SocialApp` is either populated via the database, or, via `settings`. In the latter case, `SocialApp.objects.get()` won't work. Use this:

`allauth.socialaccount.adapter.get_adapter().get_provider(request, provider_id)`

**Comment by pennersr** [comment]
See 6b8911a5 -- the use of `template.Node` is now gone, so you can do e.g.:

```
>>> from allauth.socialaccount.templatetags.socialaccount import *   
>>> provider_login_url({'request': None}, 'google')
'/accounts/google/login/'
```

**Comment by alee** [comment]
thanks for the prompt response @pennersr :pray: !

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3408
