### ISSUE TITLE
allauth.socialaccount.providers.linkedin should have an South initial migration

### ISSUE THREAD

**Issue by adityar7** [pennersr/django-allauth#341]
I've integrated allauth into an existing project with the Google, Facebook and LinkedIn providers. Any south commands now fail with:

```
NoMigrations: Application '<module 'allauth.socialaccount.providers.linkedin' from '/Library/Python/2.7/site-packages/allauth/socialaccount/providers/linkedin/__init__.pyc'>' has no migrations.
```

I don't see the initial South migrations in `allauth.socialaccount.providers.linkedin` while the other apps for Google and Facebook do have them. 

My understanding is that when South is installed, all installed apps need initial migrations (?).

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/341
