### ISSUE TITLE
Send notifications on important account changes

### ISSUE THREAD

**Issue by pennersr** [pennersr/django-allauth#3411]
It is good practice to send an email notifying the user whenever something related to the account changes. These notifications should clearly indicate:

- What changed (e.g. password changed, primary email changed ...)
- By whom: IP address and browser user agent

**Comment by varunsaral** [comment]
@pennersr want to work on this. Can I do?

**Comment by pennersr** [comment]
Sure. I imagine we need something like this:

- A base email template `allauth/templates/account/email/base_notification.txt`.

- An account adapter method `send_notification_mail(template_prefix, user, context)` that will send the email with additional information added to the context (`get_client_ip()`, timestamp, user agent, ...).

- Send the notification (using templates derived from `base_notification.txt`) on:

  - Password change/set/reset

  - MFA TOTP (de)activated, recovery codes regenerated

  - Social account (dis)connected

  - Email address change (added, removed, primary change, verified)

**Comment by pennersr** [comment]
Implemented via #3591 -- thanks @varunsaral

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3411
