### ISSUE TITLE
Documentation has a different version to the deployed

### ISSUE THREAD

**Issue by RadySonabu** [pennersr/django-allauth#3413]
When I add this to middleware section _allauth.account.middleware.AccountMiddleware_ it returns this response in the terminal.

![image](https://github.com/pennersr/django-allauth/assets/40710670/878e7f44-3762-469c-ba95-6eeb30b4fc58)

**Comment by pennersr** [comment]
Dupe of #3405

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3413
