### ISSUE TITLE
LinkedIn provider raises an UnicodeError exception when user info contains unicode characters

### ISSUE THREAD

**Issue by vezjakv** [pennersr/django-allauth#342]
Hi, 

I've encountered an exception while trying to connect with LinkedIn socialaccount provider:

```
Request URL:    http://localhost:8000/accounts/linkedin/login/callback/?oauth_token=...
Exception Type: UnicodeEncodeError
Exception Value: 'ascii' codec can't encode character u'\u010d' in position 104: ordinal not in range(128)
Exception Location: /usr/lib/python2.7/xml/etree/ElementTree.py in feed, line 1641
```

It seems that xml parser doesn't accept unicode chars but only encoded byte stream, like utf-8. When editing the line in `get_user_info()` by enclosing with `.encode('utf-8')` it works:

``` python
   def get_user_info(self):
        url = self.url + ':(%s)' % ','.join(self.fields)
        raw_xml = self.query(url).encode('utf-8')
        try:
            return self.to_dict(ElementTree.fromstring(raw_xml))
        except (ExpatError, KeyError, IndexError):
            return None
```

Is there something I've missed in provider configuration that causes  the above mentioned exception?
Thanks for the app, it works nicely otherwise.
## 

best regards 
v7v

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/342
