### ISSUE TITLE
Redirect to initial SP url after successful login with SAML provider

### ISSUE THREAD

**Issue by agorka-contractsafe** [pennersr/django-allauth#3422]
First, thanks so much for your responsiveness, we're really happy to use this library.

One use case we're getting into is redirecting a user to the page they were on before the login through a SAML provider. From what I've read in the code, when we're logging in, we eventually call `socialaccount.helpers._login_social_account` , which calls `sociallogin.get_redirect_url` to pass the redirect url into `perform_login`. That redirect URL gets it off the SocialLogin's state's  `next` param.

In the `socialaccount.providers.saml.LoginView`, we pass a `return_to` into the saml2 library login in the case of a connect process, which adds the saml RelayState to the url for the IdP. Once it gets back to the ACS view, we check the RelayState for the connect URL, but otherwise don't do anything with it. I wonder if at that point, it could make sense to set it as the `next` param to continue to work with redirects down the road, or simply storing it as `relay_state` if we don't want to assume that'd be the redirect. There's `stash_state` available on the SocialLogin (saw it's used in other providers), but think that would require some refactoring there and possibly not the best fit for the saml use case.

Curious on your thoughts about that, or if I've missed an existing way to redirect. Thanks again.

**Comment by pennersr** [comment]
Can you try this?: eb96b359

**Comment by agorka-contractsafe** [comment]
Checked and confirmed that worked great. Thanks @pennersr !

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3422
