### ISSUE TITLE
LinkedIn Auth 3 for scopes given to new apps

### ISSUE THREAD

**Issue by ethanitovitch** [pennersr/django-allauth#3423]
Description
- In the new update, LinkedIn apps are created with the following scopes: `'openid', 'profile', 'email'`
- These scopes only give you access to the following url: `/v2/userinfo`

Suggestion:
- New Provider linkedin_oauth3 lol

**Comment by pennersr** [comment]
It's not clear to me what this is about. The requested scopes are configurable via the settings. So, if you need other scopes just configure that. Can you please elaborate, is this a bug report, a feature request, or ...?

**Comment by ethanitovitch** [comment]
Hey @pennersr thanks for getting back to me!

So new LinkedIn apps only get the scopes I mentioned. Once you get back the token though the current LinkedIn provider makes a request to the /me endpoint to get profile data. However, the scopes that LinkedIn provides new apps can only use the token to make requests to /userinfo.

For my project I created a custom provider/adapter to get it working with the new profile data endpoint. I can make a pull request for a linkedin_oauth3 provider if you'd like

**Comment by ethanitovitch** [comment]
I guess this would be a feature request

**Comment by pennersr** [comment]
I don't think you need a new provider for that. Those scopes are just OpenID Connect based scopes. So, it seems LinkedIn wants you use OIDC instead of OAuth. Did you try using the OIDC provider, e.g. something like this:

```
    SOCIALACCOUNT_PROVIDERS = {
        "openid_connect": {
            "APPS": [
                {
                    "provider_id": "oidc_linkedin",
                    "name": "LinkedIn",
                    "client_id": "<insert-id>",
                    "secret": "<insert-secret>",
                    "settings": {
                        "server_url": "https://www.linkedin.com/oauth/.well-known/openid-configuration",
                    },
                }
            ]
        }
    }
```

**Comment by ethanitovitch** [comment]
interesting, I didn't see any documentation on openid, i'll check it out thanks

**Comment by pennersr** [comment]
Closing -- assuming allauth OIDC functionality is sufficient. If not, feel free to reopen.

**Comment by enzedonline** [comment]
Great, this answered my problem. Seems [Microsoft quietly dropped the LinkedIn Sign In](https://learn.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/sign-in-with-linkedin#:~:text=This%20version%20of%20Sign%20In%20with%20LinkedIn%20has%20been%20deprecated%20as%20of%20August%201%2C%202023.%20For%20all%20Sign%20In%20with%20LinkedIn%20implementations%20going%20forward%2C%20please%20refer%20to%20Sign%20In%20with%20LinkedIn%20using%20OpenID%20Connect.) (with OAuth) on 1st August. It only offers OIDC now.

**Comment by pennersr** [comment]
The `r_emailaddress` scope is only used by the LinkedIn providers, not by the OIDC provider. So if you're seeing that error that means you have somehow added that scope to the OIDC provider, which should indeed not be done. For OIDC, the scopes are standardized ("openid", "profile", "email").

**Comment by enzedonline** [comment]
Hmm ... I don't see where I'm getting that from then. My settings look like:
```python
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": ["profile", "email"], 
        "AUTH_PARAMS": {"access_type": "online"}
    }, 
    "facebook": {
        "METHOD": "oauth2", 
        "SCOPE": ["email", "public_profile"], 
        "VERIFIED_EMAIL": True
    }, 
    "openid_connect": {
        "APPS": [
            {
                "provider_id": "oidc_linkedin", 
                "name": "LinkedIn", 
                "client_id": "xxxx", 
                "secret": "xxxx", 
                "settings": {"server_url": "https://www.linkedin.com/oauth/.well-known/openid-configuration"}
            }
        ]
    }
}
```
(confirmed from running `print(SOCIALACCOUNT_PROVIDERS)` at an iPython prompt)

The social application is set up with
![image](https://github.com/pennersr/django-allauth/assets/72310199/97d86ab9-21d4-44b1-ac2d-a896364bcf95)

The response I get back from LinkedIn is:
```
https://.../accounts/linkedin_oauth2/login/callback/?error=unauthorized_scope_error&error_description=Scope+%26quot%3Br_emailaddress%26quot%3B+is+not+authorized+for+your+application&state=XdLhPuVCfjG7cqkB
```

**Comment by subzii** [comment]
thanks @enzedonline I was struggling with the same issue. 
If you can shed some light I wanna understand the difference between adding the social app through the admin dashboard and through the settings. Seems redundant to me.

**Comment by enzedonline** [comment]
@subzii I wish I knew myself ... I just lifted the settings from a suggestion by Roger to make the following:

```python
SOCIALACCOUNT_PROVIDERS["openid_connect"] = {
    "APPS": [
        {
            "provider_id": "oidc_linkedin",
            "name": "LinkedIn",
            "client_id": "xxx",
            "secret": "yyy",
            "settings": {
                "server_url": "https://www.linkedin.com/oauth/.well-known/openid-configuration",
            },
        }
    ]
}
```

I don't know how this differs from just adding it directly in the Django admin.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3423
