### ISSUE TITLE
@xframe_options_exempt for login/signup view

### ISSUE THREAD

**Issue by justmars** [pennersr/django-allauth#3425]
Hi all,

For a specific type of client view, I need to place the login / signup form inside an iframe. 

Using a `GET` request, this seems to work by using the [Decorating the class](https://docs.djangoproject.com/en/dev/topics/class-based-views/intro/#decorating-the-class) 

```py 
# views.py
class TaskpaneLoginView(LoginView):
    template_name = "account/login.html"

    @method_decorator(xframe_options_exempt)
    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)
```

This is invoked via the following url pattern:

```py 
# urls.py
app_name = "profiles"
urlpatterns: list[URLPattern] = [
    path("login", TaskpaneLoginView.as_view(), name="taskpane_login"),
]
```

The `POST` request that follows on form submission doesn't  push through due to a 403 response.

I think it's because this leads to a `LOGIN_REDIRECT_URL`, e.g. `/xxx`, resulting in `accounts/login/?next=/xxx/`.

Since this uses the original login link that isn't decorated by  `@xframe_options_exempt` like `profiles:taskpane_login`, the default middleware takes over and denies the response.

Any idea how to remedy? Or is this even the best way to approach the issue?

**Comment by pennersr** [comment]
allauth doesn't generate that 403 when handling login redirects, are you sure it's not just the CSRF middleware kicking in? In any case, this issue is not about a bug in allauth -- I need to close it.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3425
