### ISSUE TITLE
Request to Make provider Field Unique in SocialApp Model

### ISSUE THREAD

**Issue by Alihassanc5** [pennersr/django-allauth#3429]
I would like to propose adding the unique=True constraint to the provider field in the SocialApp model. Currently, the absence of this constraint can lead to potential issues where multiple SocialApp objects with the same provider value can be created, causing unexpected behavior and database errors like "Multiple object returned in queryset."

I am happy to contribute by writing a pull request to implement this change. Please consider this proposal for the benefit of data consistency and maintenance.

**Comment by pennersr** [comment]
When using the `sites` framework, you can assign a different app to a different `sites.Site`. Therefore, `provider` is intentionally not unique.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3429
