### ISSUE TITLE
Allow unverified users to use MFA when ACCOUNT_EMAIL_VERIFICATION = "none"?

### ISSUE THREAD

**Issue by Thutmose3** [pennersr/django-allauth#3432]
I think we should not block users to activate MFA when ACCOUNT_EMAIL_VERIFICATION = "none"

**Comment by pennersr** [comment]
Setting email verification to none can be done if you as the maintainer of the site don't care about this aspect. But, even if you don't care yourself, your end-users will, as users will be able to signup with other people's email, then turn on 2FA, and prevent the real user from ever signing up, effectively locking real users out of your site forever. This does not seem like a good thing to allow.

Zooming out a bit, MFA is all about security, so is email verification. Therefore, combining `verification=none` and `MFA` seem like a conflicting configuration, can you elaborate on your use case why you would want that?

**Comment by Thutmose3** [comment]
I understand your point. But people on our systems are not able to sign up. 
Every one of our clients has a unique instance/database. They can add users themselves, so the problem you are describing should not be an issue here.

I found a workaround, to automatically set EmailAddress.verified = True when a user is created.

I think you are right, by having this feature work out of the box, people will probably mess it up.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3432
