### ISSUE TITLE
Telegram bot_id required

### ISSUE THREAD

**Issue by damascene** [pennersr/django-allauth#3433]
I'm getting a blank page with `bot_id` required message on a blank page. URL:

```
https://oauth.telegram.org/auth?origin=http%3A%2F%2Fexample.com%2F&bot_id=TestLogin2bot&request_access=write&embed=0&return_to=http%3A%2F%2Fexample.com%2Faccounts%2Ftelegram%2Flogin%2Fcallback%2F%3Fid%3D342693514%26first_name%3DFirstName%26username%3DMyTG_username%26auth_date%3D1694974433%26hash%3Df180c399471fbe06026de9807b3f85ef5a51d82a875d4e----------
```

I've the settings:
```
SOCIALACCOUNT_PROVIDERS = {
    'telegram': {
        'APP': {
            'client_id': 'TestLogin2bot',
            'secret': '5480692???:??????????????????????????????????',
        }
    }
}

```

**Comment by acckiycobak** [comment]
SOCIALACCOUNT_PROVIDERS = {
    'telegram': {
        'APP': {
            'client_id': '**5480692???**',
            'secret': '**5480692???**:??????????????????????????????????',
        }
    }
}

**Comment by pennersr** [comment]
@acckiycobak Correct. Telegram documents:

> bot_id: Unique identifier for the bot. You can get it from bot token. For example, for the bot token 1234567:4TT8bAc8GHUspu3ERYn-KGcvsvGB9u_n4ddy, the bot id is 1234567.

... and allauth documents:

> 'client_id': 'bot_id',
> 'secret': 'bot token'

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3433
