### ISSUE TITLE
Multi-Factor Authentication Roadmap

### ISSUE THREAD

**Issue by asucrews** [pennersr/django-allauth#3434]
Hello,  

just want to know if there a roadmap for added Multi-Factor Authentication? Like what method on are the table or with ones are not, etc

**Comment by derek-adair** [comment]
@asucrews this is a issue/bug tracker, not for [discussions](https://github.com/pennersr/django-allauth/discussions).  Please ask this over there 👍

**Comment by pennersr** [comment]
Indeed -- closing.

(but, FWIW, WebAuthn is definitely on the roadmap)

**Comment by asucrews** [comment]
Created the request discussion, here the link so people can find it.

https://github.com/pennersr/django-allauth/discussions/3438

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3434
