### ISSUE TITLE
Support for SMS, email, hardware keys, etc., in MFA

### ISSUE THREAD

**Issue by franciscomonsanto** [pennersr/django-allauth#3435]
I had recently started to integrate [django-two-factor-auth](https://github.com/jazzband/django-two-factor-auth) in a project which is also using allauth. I just found out about allauth's own implementation of MFA (awesome feature to include in this project, BTW!) and I'd like to explore the possibility of using it instead, so I was wondering if there are any plans to support sending OTP codes via SMS (using twillio) or email, or supporting hardware token generators like Yubikey, as two-factor-auth does.

**Comment by pennersr** [comment]
Closing -- #3434

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3435
