### ISSUE TITLE
Fire AUTH_PASSWORD_VALIDATORS password_changed methods on password change

### ISSUE THREAD

**Issue by SebCorbin** [pennersr/django-allauth#3440]
In Django, each validator implementing a `password_changed()` method gets called, it allows use cases like [django_password_validators.password_history](https://pypi.org/project/django-password-validators/)

Hence the [`password_changed()`](https://github.com/django/django/blob/2c6ebb65c9eb6b11347d907127b82d31e04569e5/django/contrib/auth/password_validation.py#L60) function from Django should be called in [`ChangePasswordForm`](https://github.com/pennersr/django-allauth/blob/53e5d55fa5893f10ef7670ce0bb1bd8de850f6af/allauth/account/forms.py#L504)

**Comment by SebCorbin** [comment]
Sorry it is actually fired by `user.set_password()` (from the adapter), but my `AUTH_PASSWORD_VALIDATORS = []` setting in dev was interfering

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3440
