### ISSUE TITLE
SAML: Attributes with multiple values not possible?

### ISSUE THREAD

**Issue by valberg** [pennersr/django-allauth#3443]
I'm implementing a SAML Service Provider using the new SAML provider in allauth.

In doing this I've encountered that when extracting fields from the SAML assertion, only the first value of an attribute with multiple values is extracted.

https://github.com/pennersr/django-allauth/blob/105a6ae4c0073e0d047dd8528c61919e95bf1d43/allauth/socialaccount/providers/saml/provider.py#L78-L79

Is there a reason for this?

My problem is that I want to automatically add the user being logged in to groups which correspond to the values in an attribute provided by the IdP, and currently I can only add the user to a single group.

Or am I missing something?

**Comment by pennersr** [comment]
Until now, the attributes were only used for cases where there is supposed to be only one entry. For example, for the `username`, `uid`, it is not expected to have multiple entries. But indeed, that disregards the fact that the attribute mapping contains additional information not used by allauth. Likely, we need to keep a fixed set of keys for which we expect at most one value, and keep the list of values for all other attributes.

**Comment by pennersr** [comment]
Related info: https://github.com/SAML-Toolkits/python3-saml/issues/39

**Comment by pennersr** [comment]
@valberg Though, the code you pointed to is used in `extract_common_fields()` and `extract_uid()` -- both of which expect single values, not lists. But, all the original attribute data is stored using:

```
    def extract_extra_data(self, data):
        return data.get_attributes()
```

... and that preserves the lists. So, `socialaccount.extra_data` will have a roles key with lists of values.

So I am wondering, where are you checking the roles field?

**Comment by pennersr** [comment]
@valberg Please have a look at this test case that I just added: 53ba9b79

**Comment by valberg** [comment]
@pennersr Ah! I have been using the `data` argument passed to `DefaultSocialAccountAdapter.populate_user` because here I can access the values using the key from my `attribute_mapping` instead of the IdP counterpart.

My mapping looks something like this:

```python
"attribute_mapping": {
    ...
    "group": "http://schemas.xmlsoap.org/claims/Group"
}
```

To get the groups from `sociallogin.account.extra_data` I now have this snippet:

```python
        provider = self.get_provider(request, sociallogin.account.provider)
        attributes = provider.app.settings.get("attribute_mapping")
        group_claim = attributes.get("group")
        group_names = sociallogin.account.extra_data[group_claim]
        groups = Group.objects.filter(name__in=group_names)
```

This works fine. It would of course be nice to be able to access the data with the mapping I've already created, but in the end this could also just be a matter of documentation.

**Comment by pennersr** [comment]
Closing. As mentioned, `extra_data` intentionally contains all original (unmapped) data.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3443
