### ISSUE TITLE
KeyError at /accounts/keycloak-oidc/login/  'APP'

### ISSUE THREAD

**Issue by rv2931** [pennersr/django-allauth#3449]
Hello
I had a working installation with keycloack authentication via openid_connect provider but now I met a systematic error KeyError at /accounts/keycloak-oidc/login/  'APP'
My django allauth settings:

- social applications : 
    - Provider : OpenID connect
    - Name : keycloak-oidc
    - ClientID: \<myclientid from keycloak\>
    - Secret: \<mysecret from keycloak\>
    - Site : \<mysite with ID=1\>

- django settings : 
```
SITE_ID=1

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
...
    'django.contrib.messages',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.openid_connect',
   ....
]
MIDDLEWARE = [
    ....
    'allauth.account.middleware.AccountMiddleware',
]

AUTHENTICATION_BACKENDS = [

    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
]

SOCIALACCOUNT_PROVIDERS = {
    "openid_connect": {
        "SERVERS": [
            {
                "id": "keycloak-oidc",  # 30 characters or less
                "name": "Keycloak",
                "server_url": "https://<myhost>/auth/realms/<myrealm>"
            },
        ]
    }
}
LOGIN_URL= '/accounts/keycloak-oidc/login/?process='
```

I met this error when accessing/redirecting to http://localhost:18000/accounts/keycloak-oidc/login/
KeyError at /accounts/keycloak-oidc/login/
'APP'

As I have updated packages, maybe it is due to a change or a bug with new version 0.56.1, i don't know but previously it was working
If anyone as an idea where could it come from ?
What's the meaning of KeyError 'APP' ? is there that for allauth there is no APP or keycloack-odic dosn't exists ?
Thank you in advance
RV

Traces:
```
Environment:


Request Method: GET
Request URL: http://localhost:18000/accounts/keycloak-oidc/login/

Django Version: 4.2.5
Python Version: 3.10.13
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'entrepot',
 'django.contrib.sites',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'allauth.socialaccount.providers.openid_connect',
 'rest_framework',
 'rest_framework.authtoken',
 'django_filters',
 'import_export',
 'portal']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'allauth.account.middleware.AccountMiddleware']



Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.10/site-packages/allauth/socialaccount/providers/openid_connect/views.py", line 68, in login
    return view(request)
  File "/usr/local/lib/python3.10/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 86, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/allauth/socialaccount/providers/base/mixins.py", line 9, in dispatch
    provider = self.adapter.get_provider()
  File "/usr/local/lib/python3.10/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 46, in get_provider
    return get_adapter(self.request).get_provider(
  File "/usr/local/lib/python3.10/site-packages/allauth/socialaccount/adapter.py", line 204, in get_provider
    app = self.get_app(request, provider=provider)
  File "/usr/local/lib/python3.10/site-packages/allauth/socialaccount/adapter.py", line 282, in get_app
    apps = self.list_apps(request, provider=provider, client_id=client_id)
  File "/usr/local/lib/python3.10/site-packages/allauth/socialaccount/adapter.py", line 241, in list_apps
    for p, pcfg in app_settings.PROVIDERS.items():
  File "/usr/local/lib/python3.10/site-packages/allauth/socialaccount/app_settings.py", line 148, in __getattr__
    return getattr(_app_settings, name)
  File "/usr/local/lib/python3.10/site-packages/allauth/socialaccount/app_settings.py", line 37, in PROVIDERS
    ret["openid_connect"] = self._migrate_oidc(oidc)
  File "/usr/local/lib/python3.10/site-packages/allauth/socialaccount/app_settings.py", line 47, in _migrate_oidc
    app = dict(**server["APP"])

Exception Type: KeyError at /accounts/keycloak-oidc/login/
Exception Value: 'APP'
```

**Comment by pennersr** [comment]
It looks like you have your provider config partly in the database (client ID/secrets) and partly in the settings (`SOCIALACCOUNT_PROVIDERS`). Now, with recent versions of allauth the settings have been streamlined so that all config resides in apps, just like non-OIDC providers.  It was not listed as a backwards incompatible change because code is in place that interprets/migrates the old format, but, apparently, that code does not handle your scenario where config is placed both in the db and in the settings.

To fix this, either move everything in the settings:

```
  SOCIALACCOUNT_PROVIDERS = {
      "openid_connect": {
          "APPS": [
              {
                  "provider_id": "keycloak",
                  "name": "Keycloak",
                  "client_id": "<insert-id>",
                  "secret": "<insert-secret>",
                  "settings": {
                      "server_url": "http://keycloak:8080/realms/master/.well-known/openid-configuration",
                  },
              }
          ]
      }
  }
```

... or, drop your settings configuration and alter your `SocialApp` via the Django admin to match the config above.

**Comment by rv2931** [comment]
hum... ok I'll do it and came back
thank you for fast answer !

**Comment by rv2931** [comment]
So I dropped configuration file section and migrate "all" configurations in the database. I will try the inverse later. I don't know whats the best practice/most convenient in db or in config file settings. anyway
Know the default login page is telling now 'You currently have no social network accounts connected to this account.'

My DB settings: 
* Social applications:
  * Provider: OpenId Connect
  * Provider ID: keycloak-oidc
  * Name: Keycloak
  * Client Id: \<myclientid from keycloak\>
  * Secret key: \<secret id from keycloak\>
  * Key:
  * Settings: {"server_url": "https://keycloak.host/auth/realms/myrealm/.well-known/openidèconfiguration"}
  * Sites: 'arbitrary site name from admin.sites'

The parameter SITE_ID stays mandatory, for some reasons I don't really understand

**Comment by pennersr** [comment]
>  Now the default login page is telling now 'You currently have no social network accounts connected to this account.'

Not sure what you mean here -- if you're seeing the login page you're supposedly not logged in, yet, that "You currently..." messages suggests you are logged in?

In any case, does signing in work now?

**Comment by rv2931** [comment]
Hello
No I can't login anymore because my keycloak connecteor via openidconnect is no longer display as login option. The list of third party authentication method is empty
But with my initial configuraiton, I had to configure SERVER (in config) and APP in Database
In the configuration you gave me, I think there is only the APP site. How to configure the server part in database ?
I maybe wrong because I don't master in AllAuth configuration

**Comment by pennersr** [comment]
>  I had to configure SERVER (in config) **and** APP in Database

You either setup an app in your `settings.py`, or, add the app (with identical values) via the Django admin (`SocialApp` instance). You should not do both.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3449
