### ISSUE TITLE
Enable Private Vulnerability Reporting in GitHub

### ISSUE THREAD

**Issue by fazledyn-or** [pennersr/django-allauth#3451]
In your repository, we have found a bug that may require your attention. We do not want to disclose the details publicly. Therefore, we request you to enable private vulnerability reporting in your repository.

#### Sponsorship and Support:
This work is done by the security researchers from OpenRefactory and is supported by the [Open Source Security Foundation (OpenSSF)](https://openssf.org/): [Project Alpha-Omega](https://alpha-omega.dev/). Alpha-Omega is a project partnering with open source software project maintainers to systematically find new, as-yet-undiscovered vulnerabilities in open source code - and get them fixed - to improve global software supply chain security.

The bug is found by running the iCR tool by [OpenRefactory, Inc.](https://openrefactory.com/) and then manually triaging the results.

**Comment by pennersr** [comment]
https://django-allauth.readthedocs.io/en/latest/faq.html#i-think-i-found-a-security-issue-now-what

**Comment by pennersr** [comment]
Closing -- the reported issue is not valid.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3451
