### ISSUE TITLE
account.EmailAddress: (models.W043) MariaDB does not support indexes on expressions.

### ISSUE THREAD

**Issue by vaughanchandler** [pennersr/django-allauth#3453]
After upgrading from 0.54.0 to 0.57.0 I'm getting these warnings:

> account.EmailAddress: (models.W036) MariaDB does not support unique constraints with conditions.
> 	HINT: A constraint won't be created. Silence this warning if you don't care about it.
> account.EmailAddress: (models.W043) MariaDB does not support indexes on expressions.
> 	HINT: An index won't be created. Silence this warning if you don't care about it.

W036 is covered by #3385 but W043 doesn't seem to have been reported as yet.

**Comment by JamesParrott** [comment]
This seems like it could be related to the additions of these lines 3 months ago:
```
class EmailAddress(models.Model):
...
    class Meta:
    ...
        if app_settings.UNIQUE_EMAIL:
            constraints = [
                UniqueConstraint(
                    fields=["email"],
                    name="unique_verified_email",
                    condition=Q(verified=True),
                )
            ]
        indexes = [Index(Upper("email"), name="account_emailaddress_upper")]
```
https://github.com/pennersr/django-allauth/blob/701ef63cfd4508af0faf0671ac89c87e0d52a801/allauth/account/models.py#L37

**Comment by pennersr** [comment]
The index was added here:

https://github.com/pennersr/django-allauth/pull/3382

... which was needed to solve performance issues here:

https://github.com/pennersr/django-allauth/issues/3129

Now, if your database does not support this then compared to previous versions the behavior is the same, and you can safely ignore that warning. Other than storing all email addresses as lower case -- which is according to standards not the right thing to do (https://github.com/pennersr/django-allauth/issues/1873#issuecomment-1740703742) -- there is nothing that can be done here besides silencing the warning and or upgrading your database.

Closing this ticket -- it is not actionable. Storing as lower case can be discussed over at #1873.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3453
