### ISSUE TITLE
Problem of incomplete users when using custom profile models

### ISSUE THREAD

**Issue by elssar** [pennersr/django-allauth#346]
Right now, if you have a custom profile model, you can specify a form which the user will be redirected to if they register using a social app. The problem with this is that a user and socialaccount are created in the database before the custom profile is. So a user can decide not to fill out the extra form and still be able to log in.

This can be prevented by making a slight change to the adapter to redirect users without a profile to the profile form when they try to log in, or by writing a middleware that does the same. But that leaves the problem of having these incomplete users in the database.

Is there are way to delay creating the user and socialaccount objects till the user fills the profile form and add all three to the database together, in the same function?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/346
