### ISSUE TITLE
[i18n] Fix fuzzy for Ukrainian language

### ISSUE THREAD

**Issue by DmytroLitvinov** [pennersr/django-allauth#3469]

**Comment by pennersr** [comment]
You opened an empty issue? Any PR with translation improvements is welcome, but going to have to close this.

**Comment by DmytroLitvinov** [comment]
Hey @pennersr ,
I was working in parallel to fix.
I was not expecting that you are online right now and will close it so fast))

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3469
