### ISSUE TITLE
user_signed_up signal does not seem to work

### ISSUE THREAD

**Issue by sethmoon** [pennersr/django-allauth#347]
I am having difficulty getting the `user_signed_up` signal to work. It is set up per the [Django Documentation](https://docs.djangoproject.com/en/1.5/topics/signals/#connecting-receiver-functions), but it's not working. The file which the receiver resides is inside `app/signals.py` and the app is the first listed on `INSTALLED_APPS` to ensure that it is registered (as per the docs).

Here is my `apps/signals.py` file:

``` python
from allauth.account.signals import user_signed_up
from django.contrib.auth.models import Group
from django.dispatch import receiver

@receiver(user_signed_up)
def after_user_signed_up(sender, request, user):
    g = Group.objects.get(name='regular')
    user.groups.add(g)
```

This is not adding the user to the group as it should. I am not sure, but from the looks of [here](https://github.com/pennersr/django-allauth/blob/master/allauth/account/utils.py#L139-L144) and [here](https://github.com/pennersr/django-allauth/blob/master/allauth/account/views.py#L128-L130), it seems as though Allauth is sending the user object saved from the form as indicated [here](https://github.com/pennersr/django-allauth/blob/master/allauth/account/views.py#L127) and documented [here](https://docs.djangoproject.com/en/1.5/topics/forms/modelforms/#the-save-method).

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/347
