### ISSUE TITLE
The checked in templates are broken

### ISSUE THREAD

**Issue by duaneking** [pennersr/django-allauth#3472]
Any attempt to use the templets that are checked in like the docs say, kills Django with the following error:

django.template.exceptions.TemplateSyntaxError: 'allauth' is not a registered tag library. Must be one of:
account
admin_list
admin_modify
admin_urls
cache
debugger_tags
highlighting
i18n
indent_text
l10n
log
socialaccount
static
syntax_color
tz
widont

The django-allauth app is in my INSTALLED_APPs, so no idea how to fix this as the error honestly sounds like nonsense given that I'm explicitly hitting an allauth endpoint that cant exist until the allauth stuff is loaded, so to have it say its not inside itself is just painful.

All I want to do is edit the templates used by my app; I copied the templates from source that's checked in exactly like the docs say to do to edit them..  but all it does is blow up. Its fixed if I do a version specific template by manually downloading the source of the version I'm using, but that also means that on every release you have to audit and redo your templates, right?

Idea: Why doesn't the project do versioned releases on github so we can just grab them?  Am I going to need to go back through git history and then suffer every time I upgrade? That seems bad,  Why create that work for everybody using this library? Why not just do it once?

**Comment by duaneking** [comment]
If you want more people to support this project, please start going actual releases on GitHub for each version, and include versioned template packs or something instead of just expecting us to pull the entire source tree and dive.

That would mitigate a lot of our risk, really help mitigate django-allauths already poor reputation for being brittle and poorly documented, and help people who are just getting started with it have a bigger impact in supporting the python and Django communities by creating a separation of concerns that can at least be versioned and managed by the UI team that care about bootstrap verses react etc.

In my case, I just want to get away from the default white background as it actively hurts to look at.

**Comment by pennersr** [comment]
> 'allauth' is not a registered tag library.

This suggests that you are mixing versions. You are likely taking the templates from the latest main/development branch, and running these on the latest official release. The latest official release does not have a `{% load allauth %}`.

> Why doesn't the project do versioned releases on github so we can just grab them? 

You can already grab tarballs for all releases over here: https://pypi.org/project/django-allauth/#history

A big refactor landed on the development version with the goal of being able to adjust the look and feel of the whole project by only overriding a few core templates, instead of having to copy over all the files. It's a bit unfortunate that exactly this change is what you bumped into.

FWIW, if you run the example project on the development version, you'll find it looks like:

![image](https://github.com/pennersr/django-allauth/assets/201022/361d291c-d5df-4420-b8ed-8f3457a2bbf6)

![image](https://github.com/pennersr/django-allauth/assets/201022/7a360a5f-9d6a-4cc9-9ced-56c4acd961a6)

**Comment by bldr1862** [comment]
Thank you @pennersr . I ran into the same issue and I fixed it using the package templates instead of pulling the ones from the main branch.

**Comment by duaneking** [comment]
> > Why doesn't the project do versioned releases on github so we can just grab them?
> 
> You can already grab tarballs for all releases over here: https://pypi.org/project/django-allauth/#history
> 
That's my problem; This project is too large to simply only do releases on pypi and if I download that, I get everything, its not respecting separations of concerns enough.

That also makes it harder to do what I asked. 

The goal would be to separate the templates from the logic of the code, starting by simply separating the project into 2 sub-parts, versioning the both the same version number per each release, and then making the default templates an optional dependency,. but allowing others to do "per UI" sub packages..

So you would have the default release of `django-allauth` and then a new `django-allauth-templates`.

Then over time people could use `django-allauth-templates` as a base for other UI work, and create different projects like `django-allauth-templates-react` or `django-allauth-templates-vue` or `django-allauth-templates-bootstrap5` and you could tell them all "we only support django-allauth-templates, not the others", if they file a bug report.

But this would enable more flexibility and would build the community up to include everyone.

A bit part of my frustration was that I was simply not able to cleanly download the template files I wanted without hunting and pecking around for specific version tarballs of code that required I do more work than I should have had to do to extract files; there is clearly an interface here that allows a separation of concerns, so why isn't it being used? Why are the template files not its own sub-project, given they are replaceable? Isn't that why you used a template system?

This would allow others to support this project with whatever base UI templates as separate projects they like, versioned to the releases of the work done here.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3472
