### ISSUE TITLE
Use connect and next simultaneously with SAML provider

### ISSUE THREAD

**Issue by ryanhiebert** [pennersr/django-allauth#3478]
Right now the SAML provider notices that it should connect the provider to the currently logged in user account because it is pointing back at the connections page. We'd really like to be able to redirect to another page when we're connecting a user account, but if I add `process=connect` to the login URL it appears that it [overrides the return_to url](https://github.com/pennersr/django-allauth/blob/main/allauth/socialaccount/providers/saml/views.py#L170) that powers the `next` parameter working correctly.

Our use-case for this is to allow us to require users to re-authenticate with a different method of authentication if we see that they have an existing account with that email (and don't meet some common exceptions that are specific to our tenancy implementation) and need them to confirm that they would like to add that SSO provider to be able to log into their existing account.

/cc @atribed

**Comment by pennersr** [comment]
Fixed via a7ab2d85

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3478
