### ISSUE TITLE
OpenID Connect alternative urls

### ISSUE THREAD

**Issue by ryanhiebert** [pennersr/django-allauth#3479]
For historical reasons that are entirely valid, OpenID Connect urls put the provider_id in the URL in place of the generic provider name (google, microsoft, etc). As I'm looking to use OIDC as an alternative tenant-based SSO provider analagous to SAML, I'd prefer if I could have those urls prefixed with `oidc` the same way that `saml` does it.

I can imagine desiring consistency the other way around as well, where SAML and OIDC both use the provider_id in the slug and omit. I'm actually a bit torn which I'd prefer if I was looking at this fresh, but given that I currently have `saml` implemented and want to expand into OIDC, I currently am more interested in adding the `oidc/` slug prefix to the OIDC urls.

**Comment by ryanhiebert** [comment]
I realized another reason, that should have been obvious to me when I was typing up the earlier comment, that having saml and oidc provider_ids share a url namespace doesn't make sense: the view has to be resolved before we can look up the provider_id. So the non-prefixed mode for saml is a non-starter anyway. I knew that and I should have caught that sooner. Although it could be interesting to have a combo-view that could do or redirect to the the login for either provider.

**Comment by pennersr** [comment]
This is indeed something that without the historical baggage could/would be done differently. Though, I am also not sure how to proceed here. On the one hand, one could start introducing settings for the paths used in the `urls.py` files (e.g. for this `"r"^(?P<provider_id>[^/]+)/"`), but on the other hand, it is really not a lot of work to just fork the URL structure of allauth in your own project and adjust everything as you see fit.   All in all, options I see:

1. Introduce a setting `USE_NESTED_OIDC_URL_STRUCTURE` (for lack of a better name) that results in having a `/oidc/` parent path.
2. Introduce a more general mechanism to be able to influence any allauth path. E.g. give them all IDs, and have a `ALLAUTH_URL_PATH_MAP = {"openid_connect_login": "r"^(?P<provider_id>[^/]+)/", ...}`.
3. Break with history and backwards compatibility, and make them nested by (the one and only) default.
4. Do nothing, keep the situation as is.

For option 2, it would need to somehow tackle #1607 as well.  But all in all, I am a bit leaning towards option 4 -- as it really is not too much trouble to just fork the URLs.

**Comment by ryanhiebert** [comment]
Option 1 is what I was considering, at least as a transition to option 3 if that's where we want to end up. The url translation issue of #1607 is something that I'd rather not touch for this work, and the general mechanism of option 2 sounds like a bit of a pain that  I don't know will be necessary, especially if the URL restructuring I suggest in #3480 is an approach you're amenable to, because then adjusting the prefix is as easy as including the urlconf in your own app's urlconf directly.

I can understand wanting to just take option 4, but my motivation for avoiding it would be to allow me to use _most_ of the urls you've provided as-is, so that if there are any changes you need to make to them, I don't need to worry about keeping that duplicated code in sync with yours.

**Comment by pennersr** [comment]
Option 1 implemented via e786d100

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3479
