### ISSUE TITLE
Running Migrations gives an error in allauth 0.12

### ISSUE THREAD

**Issue by fRuiApps** [pennersr/django-allauth#348]
I did the upgrade - 

`pip install -U django-allauth`

and then 

`python manage.py migrate` 

this is the error I get -  - 

```
Migrating forwards to 0011_auto__chg_field_socialtoken_token.
 > twitter:0001_initial
 > twitter:0002_snowflake
KeyError: u'username'
```

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/348
