### ISSUE TITLE
Keep the provider url prefix out of the URL patterns

### ISSUE THREAD

**Issue by ryanhiebert** [pennersr/django-allauth#3480]
This is somewhat intertwined with #3479.

When using allauth urls, I've opted to use the saml urls directly to avoid them being under the `accounts/` url namespace. Just a personal preference. But when I include the `saml` urlpatterns, it needs to be included for a path of `""`, which gives no context in the parent urlconf of what URLs this path will take over, making it more difficult for the reader of code to resolve where any given URL might be loaded.

I would prefer to be able to import the urlpatterns like so:

```python
path('saml/', include(allauth.socialaccount.providers.saml.urls)),
```

This would also allow me to import these urls under a different path, without needing to duplicate the urlpatterns and reference the views myself. On principle, I tend to prefer this mode of including url paths whenever possible, as it seems cleaner generally.

**Comment by pennersr** [comment]
I am open to a PR where we alter the SAML `urls.py` to something like this:

```
organization_urlpatterns = [
    re_path(r"^(?P<organization_slug>[^/]+)/", ...]   # So no more saml/ here

url_patterns = path("saml/", include(organization_url_patterns))
```

Then, you could use: `from allauth.socialaccount.providers.saml.urls import organization_urlpatterns`. Making a `"saml/"`-less version the default would break consistency with other providers, that is not an option.

**Comment by ryanhiebert** [comment]
There certainly could be a backward-compatibility concern, and I understand not wanting to take my suggested approach because of it, but I did want to clarify that I don't want to break consistency. My suggestion was to make that change everywhere, with `saml/` just being the example I was using. So your root URL conf file would be responsible for looking at the provider to discover the prefix to include each urlpatterns with, rather than just adding the urlpatterns together.

----

For some reason I'm recalling that directly including a urlpatterns (rather than the urls module) doesn't work the way you might intuitively expect, so I'm not sure your alternative suggestion is as clean as you might expect.

**Comment by pennersr** [comment]
If this change is consistently rolled out through all providers, than the consistency concern is indeed mitigated. However, it could still result in backwards compatibility issues as existing deployments with altered (forked) URL structures that import from the provider `urls.py` would be affected.

**Comment by maruthiaws0808** [comment]
class EBayAccount(ProviderAccount):
    # def get_avatar_url(self):
    #     return self.account.extra_data.get("picture")

    # def to_str(self):
    #     dflt = super(EBayAccount, self).to_str()
    #     return self.account.extra_data.get("name", dflt)
    pass

**Comment by pennersr** [comment]
I don't see how we can do this in a backwards compatible manner. And if that is not possible, breaking backward compatibility on this is really not worth it.  The OIDC provider prefix is configurable using `SOCIALACCOUNT_OPENID_CONNECT_URL_PREFIX`, I am open to accepting a PR that introduces a similar setting for SAML. But other than that, closing...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3480
