### ISSUE TITLE
Auth0 Token-URL not working

### ISSUE THREAD

**Issue by nikolasbrendes** [pennersr/django-allauth#3485]
I tried to configure the auth0 login method for my Inventree and Authentik instance. 
Finally i got it to work.

The Error was, that allauth used the wrong URL to POST the Token to Authentik. The wrong url is: 
``` access_token_url = "{0/oauth/token".format(provider_base_url) ```

So I changed it to the following
``` access_token_url = "{0}/token/".format(provider_base_url) ```

I dont know if this error is specific to the Inventree instance (i dont think so)
The Error sits in the file ```allauth/socialaccount/providers/auth0``` Line 20

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3485
