### ISSUE TITLE
Issue with Migration when the database is recreated from the beginning

### ISSUE THREAD

**Issue by elementzonline** [pennersr/django-allauth#3488]
The following code block seems to be incorrect when the SITES_ENABLED is True. The AUTH_USER_MODEL dependency is not getting added to the dependency list when the SITES_ENABLED is True and causes the migration to fail.
```
class Migration(migrations.Migration):
    dependencies = (
        [
            ("sites", "0001_initial"),
        ]
        if app_settings.SITES_ENABLED
        else []
        + [
            migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ]
    )
```

Error during migration is as follows

    raise ValueError('Related model %r cannot be resolved' % self.remote_field.model)
ValueError: Related model 'auth.user' cannot be resolved

I resolved this issue by modifying the Migration file part like the one below
```
class Migration(migrations.Migration):
    dependencies = (
        [
            ("sites", "0001_initial"),
            migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ]
        if app_settings.SITES_ENABLED
        else []
        + [
            migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ]
    )
```

Hope this will get addressed in the next release.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3488
