### ISSUE TITLE
More arguments for initializing custom user model in SocialAccountAdapter

### ISSUE THREAD

**Issue by chulapitta** [pennersr/django-allauth#349]
When using custom user model derived from `AbstractBaseUser` with social accounts, there are often the need to initialize a new user instance with social information obtained from providers. However, the `populate_new_user` hook (as in `allauth.socialaccount.adapter.DefaultSocialAccountAdapter`) is currently passed  only the basic arguments: username, first_name, last_name, email, and name.

Additionally passing `provider_id` and `extra_data` from provider's adapter to `populate_new_user` would immensely increase the versatility of such hook. 

For example, in `allauth.socialaccount.providers.twitter.views.TwitterOAuthAdapter`, change the hook call (line 36)  to:

``` python
user = get_adapter() \
            .populate_new_user(username=extra_data.get('screen_name'),
                               name=extra_data.get('name'),
                               provider_id=self.provider_id,
                               extra_data=extra_data
                              )
```

Then developer can initialize the user model with the social information however he/she sees fit e.g. copy thumbnail link or construct custom display name.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/349
