### ISSUE TITLE
ReadTheDocs v0.57.0 docs not accessible

### ISSUE THREAD

**Issue by rudolfolah** [pennersr/django-allauth#3490]
Only the `latest` version is appearing in the documentation.

The build for 0.57.0 is appearing on ReadTheDoc: https://readthedocs.org/projects/django-allauth/versions/

<img width="977" alt="Screenshot 2023-10-18 at 10 26 53 PM" src="https://github.com/pennersr/django-allauth/assets/89982117/c31fcb82-bf81-4bda-a0cc-38bce1efad88">

However the link to "view docs" points to: https://readthedocs.org/dashboard/django-allauth/version/0.57.0/edit/

<img width="1086" alt="Screenshot 2023-10-18 at 10 25 37 PM" src="https://github.com/pennersr/django-allauth/assets/89982117/48994d5e-f83c-4ef1-a5d2-fb592b3186d0">

**Comment by pennersr** [comment]
That is due to this: https://blog.readthedocs.com/migrate-configuration-v2/

Fixing this requires creating a 0.57.0 branch and adding a `.readthedocs.yaml` file.

**Comment by varunsaral** [comment]
I will try to collate my understading here, after going through readthedocs docs, they maintain a latest version against the main branch and stable version against the most recent tag version. Our latest version i.e 0.57.0 didn't have config file hence it's breaking. To fix we will create a branch and add this, so when the build will try to checkout in the tag it will checkout in our 0.57.0 branch, find the config and build it succesfully. If i am write then @rudolfolah @pennersr , i can add the branch if thats fine.

**Comment by pennersr** [comment]
Trouble is, for releases I would like to stick to branches named `0.57.x` -- this way, whenever you need to release say `0.57.1` you can do that on the `0.57.x` branch and tag `0.57.1` from there. But solving this issue would mean creating a branch named `0.57.0` which clouds the `0.57.0` tag, or, I need to re-tag `0.57.0` which is a bit like changing history. All in all, this issue will solve itself once `0.58.0` is released, for now opting not to address this.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3490
