### ISSUE TITLE
TemplateSyntaxError at /accounts/login/

### ISSUE THREAD

**Issue by junior-r** [pennersr/django-allauth#3492]
Hello, I´m using Django=4.2.6 and django-allauth=0.57.0, here is the error

'allauth' is not a registered tag library. Must be one of:
account
admin_list
admin_modify
admin_urls
cache
django_browser_reload
i18n
l10n
log
socialaccount
static
tailwind_tags
tz

_"GET /accounts/login/ HTTP/1.1" 500_

**Comment by pennersr** [comment]
Dupe of #3472

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3492
