### ISSUE TITLE
mfa: PWA service worker script resets authentication flow

### ISSUE THREAD

**Issue by simonkern** [pennersr/django-allauth#3496]
Hey there,

I am serving a PWA using Django. For various reasons, I need to serve the service_worker script from Django. However, this causes `_remove_dangling_login` (see below) to be called, which interrupts the authentication flow and makes mfa unsable:

``` python
    def _remove_dangling_login(self, request, response):
        if request.path.startswith(settings.STATIC_URL) or request.path in [
            "/favicon.ico",
            "/robots.txt",
            "/humans.txt",
        ]:
            return
        if response.status_code // 100 != 2:
            return
        if not getattr(request, "_account_login_accessed", False):
            if "account_login" in request.session:
                request.session.pop("account_login")
```

I tried to solve this by subclassing AccountMiddleware (see below) and using my subclass in settings instead of `allauth.account.middleware.AccountMiddleware`.

``` python
from allauth.account.middleware import AccountMiddleware as AllauthAccountMiddleware


class AccountMiddleware(AllauthAccountMiddleware):
    def _remove_dangling_login(self, request, response):
        if request.path in [
            "/sw.js",
        ]:
            return
        super()._remove_dangling_login(request, response)
```

Unfortunately, this solution is blocked by the ready function in `allauth/account/apps.py`:
``` python
    def ready(self):
        required_mw = "allauth.account.middleware.AccountMiddleware"
        if required_mw not in settings.MIDDLEWARE:
            raise ImproperlyConfigured(
                f"{required_mw} must be added to settings.MIDDLEWARE"
            )
```

What is the recommended approach to resolve this situation? In my opinion,  it should either be possible to whitelist further urls / paths, or the middleware should be swappable.

If there is another approach that will resolve the situation more easily, please let me know.

**Comment by pennersr** [comment]
While making things swappable is definitely good to have, it would be great if this just worked out of the box. One idea would be to check the content type of the response, and only remove the dangling login if it is not text/html.

**Comment by pennersr** [comment]
Closed via e8a10356

**Comment by simonkern** [comment]
That works for me, thanks a lot for your quick response! Any chance this will be released soon?

**Comment by pennersr** [comment]
@simonkern Yes -- now.

**Comment by simonkern** [comment]
Fantastic, thanks a lot @pennersr ;-)

Have a nice weekend!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3496
