### ISSUE TITLE
Inconsistent Domain in Email for Sending Email Confirmation Message

### ISSUE THREAD

**Issue by prietojulii** [pennersr/django-allauth#3497]
This report highlights an inconsistency in the email confirmation message content. When an email is sent to confirm an account, the attached link contains a reference to "localhost" instead of the corresponding server domain. This discrepancy can cause confusion among users when accessing the confirmation link. It is recommended to review and correct the email confirmation link generation process to ensure it accurately reflects the server domain.

The error lies within the build_absolute_uri function, which generates the absolute URL including the domain. This function is incorrectly generating the URL with "localhost" instead of using the corresponding server domain. To rectify the issue, it is necessary to adjust the logic in the build_absolute_uri function to consistently use the server domain in the email confirmation.

This error impacts the rendering of templates: email_confirmation_message

**Comment by pennersr** [comment]
This is not a bug in allauth, but rather a configuration issue of your project/webserver.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3497
