### ISSUE TITLE
OpenID Connect with PKCE Enabled - Not syncing user information

### ISSUE THREAD

**Issue by jonnyhoff** [pennersr/django-allauth#3499]
I've setup OpenID Connect with PKCE enabled that authenticates on Windows Server Active Directory as you can see below. Users are able to log in but they get generic usernames, ie. `user` , `user0`, etc. and no group information.

**Current Config:**

```python
SOCIALACCOUNT_PROVIDERS = {
    'openid_connect': {
        'APP': {
            "provider_id": "oauth2",
            "name": "AD Oauth2",
            'client_id': config("OAUTH_CLIENT_ID"),
            'secret': '',
            "settings": {
                "server_url": "https://" + config("OAUTH_SERVER") + '/Adfs',
            },
        },
        'OAUTH_PKCE_ENABLED': True,
        'SCOPE': ['openid', 'email', 'profile'],
    }
}
```

---

**Social Account Record:**
![image](https://github.com/pennersr/django-allauth/assets/8642945/4430c5c1-7ae9-493e-9fa7-519532944440)

---

**User Record:**
![image](https://github.com/pennersr/django-allauth/assets/8642945/4684813e-5d94-4048-b5eb-35a30d3a179b)

Generic usernames are created, ie. `user` , `user0`, etc. and no group information.

**Comment by pennersr** [comment]
The Microsoft provider uses this for username:

https://github.com/pennersr/django-allauth/blob/main/allauth/socialaccount/providers/microsoft/provider.py#L42

If that is not there, it will fallback to generic usernames. Is that (`mailNickname`)  in your extra data?

**Comment by pennersr** [comment]
Moved to https://codeberg.org/allauth/django-allauth/issues/3499
