### ISSUE TITLE
complete custom profile 

### ISSUE THREAD

**Issue by watermelonlh** [pennersr/django-allauth#350]
I have an profile OneToOneField to user. I found there is no good way to complete it when user social account sign up. I try to use pre-login signal, but at this time the user model still not real created, so the profile cannot create. on the other hand, I use social account added signal, but this only useful for connect action, not fit sign up action.

is there any good solution?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/350
