### ISSUE TITLE
Get SAML IdP entity ID from metadata_url

### ISSUE THREAD

**Issue by ryanhiebert** [pennersr/django-allauth#3501]
When making a SAML `SocialApp` with an `idp` settings dictionary with a `metadata_url`, I notice that the `entity_id` key in the `idp` dictionary of the settings is still required. This strikes me as odd, given that the metadata_url is intended to supplant manual configuration of other settings like `sso_url`, `x509cert`, and `slo_url`. Do you think I'm missing something, or would it make sense to allow `metadata_url` to be the only key present in the `idp` dictionary of the settings?

**Comment by ryanhiebert** [comment]
I discovered that I can put an empty string for the IDP `entity_id` and the launch works fine. Based on that, it seems like fixing #3500 may fix this one for me as well.

**Comment by ryanhiebert** [comment]
I think that fixing #3500 is the way to go for this one, so I'm closing this one out.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3501
