### ISSUE TITLE
Switch to OAuth 2 for OpenStreetMap provider

### ISSUE THREAD

**Issue by danieldegroot2** [pennersr/django-allauth#3502]
Switch to OAuth 2 from HTTP Basic Auth and OAuth 1.0a. They are being deprecated.
See https://github.com/openstreetmap/operations/issues/867

Note, `api.openstreetmap.org` API url currently can not do OAuth 2 handshake. See https://github.com/openstreetmap/operations/issues/951#issuecomment-1748717154
You can split the `www.` base URL and `api.` API url. See https://github.com/osmlab/osm-auth/pull/123#issuecomment-1777330094

**Comment by pennersr** [comment]
Moved to https://codeberg.org/allauth/django-allauth/issues/3502

**Comment by pennersr** [comment]
There is no need to provide a new provider, starting from [3f7bc465](https://codeberg.org/allauth/django-allauth/commit/3f7bc465) the regular OIDC provider can be used.
