### ISSUE TITLE
0.58.1 tag missing

### ISSUE THREAD

**Issue by dvzrv** [pennersr/django-allauth#3506]
Hi! I package this project for Arch Linux.
We are now using the upstream tarballs of projects, as sdist tarballs are often either incomplete or broken (see https://rfc.archlinux.page/0020-sources-for-python-packaging/).

As such we are relying on the source tarball provided by this project. Unfortunately, there is no tag for the 0.58.1 release yet. It would be great if you could create it. Thanks!

**Comment by pennersr** [comment]
It's there now...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3506
