### ISSUE TITLE
Reset password helptext on LoginForm

### ISSUE THREAD

**Issue by jduar** [pennersr/django-allauth#3507]
With `0.58` I've noticed there was an addition of

```python
self.fields["password"].help_text = mark_safe(
    _('<a href="{}">Forgot your password?</a>').format(
        reverse("account_reset_password")
    )
)
```

on the `LoginForm` at `allauth/account/forms.py` 

https://github.com/pennersr/django-allauth/commit/ff1a6a38e14b0542a23362e650eb8d88e8edd73a

This has raised a problem as I don't have the `account_reset_password` view name configured. I allow authentication through  a social app only, and the social app provider handles password resets and such.

We'd like to avoid rewriting the whole of the class's `__init__` ideally. It'd make it easier to deal with this if this behaviour was either optional, maybe through a setting, or at least split into a separate method to allow easier changes for those with use cases such as ours, where we don't rely on allauth's password reset behaviour. Right now, we can't avoid the behaviour without changing the whole `__init__` method, as even trying to redefine it will result in an error if we call the super(). Thanks!

**Comment by pennersr** [comment]
Not needed -- it's handled here: c9cbc19d

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3507
