### ISSUE TITLE
(BUG?) Password reset statistics

### ISSUE THREAD

**Issue by sowinski** [pennersr/django-allauth#3509]
Hi,

I want to log how many password reset emails are send per day. 
(Because I guess there are some bots sending password resets all the time, but I am not sure).

1) Is there somewhere some informations saved on a password reset in the database?
2) If not, where would be the best place to implement my own code?
3) Not sure if this is a bug or a feature but if you enter a non registered address then the system is also sending an e-mail. Why? Can I turn this of?

**Comment by pennersr** [comment]
1. No
2. See above
3. Good UX. 

If you're worried about sending too many of these mails, the password reset view is rate limited. You might want to tighten the rate limits.

**Comment by sowinski** [comment]
Is it possible to disable this feature? It might be good UX but it is in Europe against GDPR laws.

It would be nice, if we could disable this in the settings. 

If it is not possible, where would you disable this at all for non registered users? ALso in the send_mail() method?

**Comment by pennersr** [comment]
> but it is in Europe against GDPR laws.

IANAL, but I doubt this to be true. I can signup on any EU site using your email address, and all those sites will all send you an unsolicited (confirmation) email, and you cannot prevent this. 

So yes, you can trick a system into sending an email to somebody that did not ask for it. How are you going to prevent that?

Having said that, given that people feel strongly about this there is some work ongoing in this area here: https://github.com/pennersr/django-allauth/pull/3528

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3509
