### ISSUE TITLE
can not login with linkedin/ linkedin_oauth2

### ISSUE THREAD

**Issue by MahmoudBayoumi19** [pennersr/django-allauth#3510]
i created app and verfiy my linkedin page and request access to Sign In with LinkedIn using OpenID Connect done,
I configured linkedin social application and tried to integrate it with both, 'allauth.socialaccount.providers.linkedin' and 'allauth.socialaccount.providers.linkedin_oauth2' but cannot login. This is my settings for both:
'linkedin_oauth2': {
'SCOPE': [
'openid',
'profile',
'w_member_social',
'email'
],
'APP': {
'client_id': 'client_id',
'secret': 'secret',
'key': ''
}
}
this url: /accounts/linkedin_oauth2/login/?process=login redirect to:
http://127.0.0.1:8000/accounts/linkedin_oauth2/login/callback/?code=AQQo34wWQ19rSQZy2D6ZT7i_sf2nEhT6HoYnxtwluOvh60Y5XVoEVDHNTmsX9RG5VDpv52PrtuPIsP5YXVGzuJOW3PwLJSbHWUumPHXtUcdrjg_gTaFDuPQwn_h2fsEsrY0BlibuxM5PR7mF34AuBMs5Hai1xF8rJaZUTLotaCMtdfOH-kc0sp8isDLc4R492gyY51fctE7ChVNZLZE&state=pnyyh12BgUsWAJ9l

**Comment by MahmoudBayoumi19** [comment]
> Hey had the same issue: #3423 @pennersr gave a good explanation. Please close the issue if it's sufficient otherwise I built a custom provider/adapter that you can use but I've been meaning to migrate to the oid solution

thanks a lot this helped me and worked.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3510
