### ISSUE TITLE
MFA Recovery Codes Template Issue - element textarea

### ISSUE THREAD

**Issue by dwasyl** [pennersr/django-allauth#3511]
Just checking out the new `mfa` functionality and noticed the `templates/mfa/recovery_codes/index.html` file includes a `{% element
 fields ... %}` tag which generates an `<input type="textarea".. >` which isn't valid code (for at least Edge). Instead a multiline `<textarea></textarea>` should be done here.

I'm not familiar enough with this new templating system to have this down pat yet, but it definitely doesn't work the way it's currently setup. I believe an `element` template for a `textarea` would be required to do this properly.

**Comment by pennersr** [comment]
This is already fixed in the soon to be released 058.2-dev over here: 281c0417

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3511
