### ISSUE TITLE
filter_users_by_email takes to much time for sql query

### ISSUE THREAD

**Issue by kemalbastak** [pennersr/django-allauth#3514]
```
def filter_users_by_email(email, is_active=None):
    ...
    mails = EmailAddress.objects.filter(email__iexact=email)
    ...
    if app_settings.USER_MODEL_EMAIL_FIELD:
        q_dict = {app_settings.USER_MODEL_EMAIL_FIELD + "__iexact": email}
    ...

```

these queries are taking too much time in user tables with large numbers. Is there a way to make it dynamically query it with case sensitive or incase sensitive. Maybe it could be just with case sensitive.

here is the debugtoolbar results

with __iexact query
![image](https://github.com/pennersr/django-allauth/assets/17602783/9492c0e2-50c3-4ed8-80fe-aa424371b5ab)

with __exact query
![image](https://github.com/pennersr/django-allauth/assets/17602783/c72f5926-b69e-4d78-ae89-464c3799b1a8)

**Comment by pennersr** [comment]
The email address table has an index:

```indexes = [Index(Upper("email"), name="account_emailaddress_upper")]```

Can you check whether that index exists in your db? 

Also, there are 2 queries happening, one on the email address table, and one on the user table. Which of these are you depicting above?

**Comment by kemalbastak** [comment]
Here are the queries generated

<img width="1661" alt="image" src="https://github.com/pennersr/django-allauth/assets/17602783/40c0b811-4e48-4a8d-b344-6f3f3046dbd7">

Also I don't have the index in my db. 

my package versions:
django-allauth==0.48.0
Django==3.2.12

**Comment by pennersr** [comment]
0.48.0 -- please upgrade

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3514
