### ISSUE TITLE
django.contrib.sites should be optional?

### ISSUE THREAD

**Issue by deliciouslytyped** [pennersr/django-allauth#3515]
I just did some quick checking because we are working on a beginner project that happens to use allauth, and it seems like some code might be checking if django.contrib.sites is used, and some code doesn't?

https://github.com/search?q=repo%3Apennersr%2Fdjango-allauth+sites

If feature checks work properly everywhere this dependency becomes optional (for example if we aren't using multiple virtual hosts?)

**Comment by pennersr** [comment]
It is optional. Just don't add it to your `INSTALLED_APPS`...

**Comment by deliciouslytyped** [comment]
Ok thanks!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3515
