### ISSUE TITLE
Other options for deactivating sites integration

### ISSUE THREAD

**Issue by hansegucker** [pennersr/django-allauth#3519]
We have a Django project that made use of the sites integration in the past. Now, we removed everything sites-related, but we have to keep `django.contrib.sites` in `INSTALLED_APPS` in order to keep the old migrations and the migration history intact. That works well with all libraries we are using but `django-allauth`. Is there any way to deactivate the use of Django sites in allauth other than removing it from the installed apps?

**Comment by pennersr** [comment]
I must admit, I don't really understand what you are trying to accomplish. What is the point in taking the necessary steps in getting rid of `sites` only to stop before the finish line? Why not finish the job (e.g. `DELETE FROM django_migrations WHERE app = 'sites'` and `DROP TABLE socialaccount_socialapp_sites`).

But indeed, allauth adjusts its behavior depending on whether or not `sites` is installed, that is not something that is configurable otherwise.

**Comment by hansegucker** [comment]
Yeah, well, I will try to describe our problem a little more in detail:

1. We introduced Django sites sometime in past and added foreign keys from our models to `Site`.
2. Now we decided to drop DJango sites because it's no longer necessary in our setup and makes things complicated.
3. So, we had to create migrations that delete all these references to Site. 
4. Together with other stuff that was necessary for dropping everything Site-related (like you described above), we were able to get rid of `sites`.
5. As a last step, we tried to remove `sites` from `INSTALLED_APPS`. That failed because some migrations (the migration that created the references and the migration that removed the references) still depend and also have to depend on sites in order to work. 
6. Dropping the references to site in those migrations will also fail because upgrading existing instances would be impossible.
7. So we decided that we have to keep `sites` in `INSTALLED_APPS` although it's semantically wrong. But there seems no other solution. And that's the reason why we have to persuade allauth not to use sites anymore although it's still installed.

**Comment by pennersr** [comment]
You could still squash your migrations, or, replace the migrations that add and remove references (your bullet nr. 5) with empty migrations. Just my 2cts, I would opt for removing `sites` all the way...

**Comment by hansegucker** [comment]
We definitely would like to to do it that way but imagine there is a production system which ran the migration that added the required references to `Site` (the status-quo). Now we release a new version that drops support for sites. This new version has to include a migration that also drops all these references. That doesn't work well with empty migrations ;-)

**Comment by pennersr** [comment]
You don't need to drop the migration. Just empty its operations. So, if you have a migration `0007_add_fk_to_site.py` that adds foreign keys references to the `Site` model, just empty it (`operations = []`). Other migrations that have this migration as a dependency can still point to it, and altering a migration that already ran on production does not affect production.

**Comment by hansegucker** [comment]
Yes, I understood that. But what about a possible migration `0016_drop_fk_to_site.py`?

**Comment by pennersr** [comment]
Empty that one as well. Basically, all migrations that add FKs to `Site` and then later on remove that reference to `Site` should be altered so that it no longer adds/removes those references.

**Comment by hansegucker** [comment]
But that only would work if the references would have been deleted already. But we delete them because we removed sites. So, we still need a new migration in the next release that removes those references.

**Comment by pennersr** [comment]
I was under the impression that you already removed all references to `Site` with only allauth being the exception? So, if you haven't already done so, I would make sure that all your own apps having references to `Site` drop those references (all while the `sites` app is still installed). Then, deploy that to production. So, at this point your apps no longer use the `Site` model, and migrations ran, so you can safely perform the `operations = []` trick. Then, all apps except allauth are free from the `sites` app. As for allauth, it is using this construct:

```
class Migration(migrations.Migration):
    dependencies = (
        [
            ("sites", "0001_initial"),
        ]
        if app_settings.SITES_ENABLED
        else []
    ) + [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
```

As well as:

```
            + (
                [
                    ("sites", models.ManyToManyField(to="sites.Site", blank=True)),
                ]
                if app_settings.SITES_ENABLED
                else []
            ),
```

So, its `socialaccount/0001_initial.py` migration is dynamic. Meaning, you can now safely remove `sites` from the `INSTALLED_APPS`:

- The `allauth` dependency on `("sites", "0001_initial")` will magically disappear.
- The `ManyToMany` created a `socialaccount_socialapp_sites` table that is indeed still there, but it is no longer used/referenced, so it's really harmless. You can drop it manually, or, write a migration that uses a raw SQL statement to drop it.

**Comment by hansegucker** [comment]
> I was under the impression that you already removed all references to Site with only allauth being the exception?

No, unfortunately not.

We just have no control which version of our software is installed in production as there isn't just one deployment. So, we have to do all the magic in one version. But I just got an idea how that could be possibly done. 

Thank you very much already for all the support today. I will reach back and tell whether it worked or not (and then what worked ;-)).

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3519
