### ISSUE TITLE
mfa template page

### ISSUE THREAD

**Issue by Suaralanre** [pennersr/django-allauth#3525]
Is there a way to edit the ```accounts/2fa``` templates from django-allauth[mfa]. I currently have a bootstrap template and I would love to fit this url with the template I have.

**Comment by pennersr** [comment]
There is nothing different from styling the `allauth.mfa` app vs the other apps. In any case, I recommend you try running the example program, it already shows Bootstrap templates:

![image](https://github.com/pennersr/django-allauth/assets/201022/76278224-14b2-4965-9507-841906bbf803)

![image](https://github.com/pennersr/django-allauth/assets/201022/cbf65b78-f530-4e19-8fc6-9798672425c0)

**Comment by Suaralanre** [comment]
Thanks a lot mate.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3525
