### ISSUE TITLE
MFA Feature Request: Method to check if user authenticated via MFA

### ISSUE THREAD

**Issue by dwasyl** [pennersr/django-allauth#3537]
In migrating over from django-otp-based MFA, one feature that existed there is an `is_verified` function on the `request.user` model as a way of checking that a particular User authenticated with their MFA key.

This is a handy security feature/validation for sites that might have multiple entry points or have not enabled MFA on particular login screens (i.e. admin).

In `django-otp` world, it comes from a [middleware module](https://github.com/django-otp/django-otp/blob/master/src/django_otp/middleware.py).

Clearly a bad practice not to have MFA on every single login, but it happens and having some way of validating that a user did in fact use MFA to login is handy rather than just assuming they did if they have an device configured.

**Comment by dwasyl** [comment]
That's great, thanks for making that work so elaborately and so well.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3537
