### ISSUE TITLE
Confirm Email With Code

### ISSUE THREAD

**Issue by ethanitovitch** [pennersr/django-allauth#3542]
Looks like certain email servers are disabling the signup link sent in emails (still a theory trying to confirm but haven't been able to reproduce)
Think it might be worthwhile to build a configuration for sending a code to confirm an email

**Comment by pennersr** [comment]
Duplicate of #3014

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3542
