### ISSUE TITLE
Adding openid_connect to INSTALLED_APPS causes login view to fail

### ISSUE THREAD

**Issue by enzedonline** [pennersr/django-allauth#3544]
When I add `'allauth.socialaccount.providers.openid_connect'` to `INSTALLED_APPS`, the login page fails to load with a `SocialApp.DoesNotExist` error in [allauth/socialaccount/adapter.py line 288](https://github.com/pennersr/django-allauth/blob/df41f2866a66b792a0e27611250cfd500fa956e2/allauth/socialaccount/adapter.py#L281), `DefaultSocialAccountAdapter.get_app()` method.

This happens whether or not an OIDC provider has been defined.

Trapping the error, it seems to be looking for a social app with provider `'accounts'`.

![image](https://github.com/pennersr/django-allauth/assets/72310199/bceb09bb-c75e-410c-aa79-a8f047edd68f)

This will occur with 

```python
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": ["profile", "email"], 
        "AUTH_PARAMS": {"access_type": "online"}
    }, 
    "facebook": {
        "METHOD": "oauth2", 
        "SCOPE": ["email", "public_profile"], 
        "VERIFIED_EMAIL": True
    }, 
}
```
 or 
```python
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": ["profile", "email"], 
        "AUTH_PARAMS": {"access_type": "online"}
    }, 
    "facebook": {
        "METHOD": "oauth2", 
        "SCOPE": ["email", "public_profile"], 
        "VERIFIED_EMAIL": True
    }, 
    "openid_connect": {
        "APPS": [
            {
                "provider_id": "oidc_linkedin", 
                "name": "LinkedIn", 
                "client_id": "xxxx", 
                "secret": "xxxx", 
                "settings": {"server_url": "https://www.linkedin.com/oauth/.well-known/openid-configuration"}
            }
        ]
    }
}
```

With the latter, I can call `self.list_apps(request, provider='oidc_linkedin', client_id=client_id)` and successfully and successfully return the LinkedIn app. Loading the page doesn't get that far however.

Removing `'allauth.socialaccount.providers.openid_connect'` loads the page fine. I can see the Facebook and Google apps load.

This does not affect the social connect pages, only login page. I've tried with own custom template and with allauth template. Same result, it seems to trigger before the template loads.

Not sure if this is a bug, or some config that missing that I've not picked up inthe docs.

**Comment by pennersr** [comment]
There is no reason why allauth would go looking for a provider called `accounts` without that being configured somehow, unless the project's URL routing somehow mistakenly interprets the `accounts` in your `/en/accounts/login` as a provider ID. I would recommend you first use standard URL routing (e.g. don't auto prefix `/en/`) and then figure out why things start breaking when you gradually expand from there...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3544
