### ISSUE TITLE
LinkedIn deprecated parts

### ISSUE THREAD

**Issue by zbabayee** [pennersr/django-allauth#3558]
Some parts of codes for linkedin oauth2 is deprecated .
these parts are:
LinkedInOAuth2Adapter views:
profile_url  "https://api.linkedin.com/v2/me" changed to  "https://api.linkedin.com/v2/userinfo"

LinkedInOAuth2Provider providers:
default scopes : 'r_liteprofile, r_fullprofile, r_basicprofile,...' changed to 'openid, profile and email'
profile fileds : 'id, firstName, lastName' changed to 'sub, name, given_name, family_name, picture, email, email_verified'
 function 'extract_uid' also should be change because there is no fied 'id' in linkedin response, it changed to 'sub'.

**Comment by pennersr** [comment]
The changes described turn LinkedIn from an OAuth2 provider into a regular OIDC provider. I think we need to look into deprecating the `linkedin_oauth2` provider in favor of just using the `openid_connect` provider.

Related: https://github.com/pennersr/django-allauth/issues/3391

**Comment by zbabayee** [comment]
yes, you're right.
thanks

**Comment by pennersr** [comment]
Closed via 29647f47

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3558
