### ISSUE TITLE
Django 1.6: form.fields is now a collections.OrderedDict, has no attribute 'keyOrder'

### ISSUE THREAD

**Issue by mkai** [pennersr/django-allauth#356]
Django 1.6 now uses `OrderedDict` from the `collections` module for `Form.fields`. 
See https://github.com/django/django/commit/07876cf02b6db453ca0397c29c225668872fa96d#django/forms/forms.py

django-allauth uses `form.fields.keyOrder` which assumes `form.fields`to be a SortedDict (from django.utils.datastructures). This results in an AttributeError when loading the signup page.

Django version: 1.7.dev20130813162246

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/356
