### ISSUE TITLE
Error in mfa

### ISSUE THREAD

**Issue by SheezyJay** [pennersr/django-allauth#3562]
Hey,
maybe i found an issue with the mfa.
If the user setup mfa everything is working but after login the user is redirected to the mfa-authenticate site and when the user click on cancel (eg. login page redirect), it bypass the mfa.

**Comment by SheezyJay** [comment]
Sry was my misstake i used before 
ACCOUNT_ADAPTER = 'allauth_2fa.adapter.OTPAdapter' and didnt delete it for allauth mfa

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3562
