### ISSUE TITLE
MultipleObjectsReturned with django-allauth 0.59.0

### ISSUE THREAD

**Issue by andreage** [pennersr/django-allauth#3564]
Starting with django-allauth 0.59.0 I'm receiving a `MultipleObjectsReturned` exception when the URL `accounts/facebook/login/callback/` is called.

I'm using the same database for two websites, therefore I have two Facebook Apps saved in the database. Each app is associated with its own `Site`.

I think the following commit broke my setup:

https://github.com/pennersr/django-allauth/commit/e5c480c363154c0968ba6f41f6497cc4395f42c6

specifically this:

![image](https://github.com/pennersr/django-allauth/assets/8830271/6776b382-d4b3-4452-bc1b-c0ed580cc167)

How can I investigate the reason why the `request` object is empty?

`SocialApp.objects.on_site` seems to call Django's built in `get_current_site`, which calls `Site.objects.get_current(request)` whose signature is `get_current(self, request=None)`. That means it works when request is None and that might be why it was working before.

Could it be that here:

![image](https://github.com/pennersr/django-allauth/assets/8830271/a92cd7aa-db02-421e-906a-7fcfe880f694)

`self.get_client(` is called with `self.request` instead of `request`?

Here as well:

![image](https://github.com/pennersr/django-allauth/assets/8830271/da36ae47-7667-4a70-be3a-d5ac804af75a)

`request` is used two times and then the third time `self.request` is used, but it might be just me who's confused.

**Comment by andreage** [comment]
Traceback (most recent call last):
  File "VIRTUALENV_PATH/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "VIRTUALENV_PATH/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "VIRTUALENV_PATH/python3.9/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "VIRTUALENV_PATH/python3.9/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 162, in dispatch
    return complete_social_login(request, login)
  File "VIRTUALENV_PATH/python3.9/site-packages/allauth/socialaccount/helpers.py", line 208, in complete_social_login
    sociallogin.lookup()
  File "VIRTUALENV_PATH/python3.9/site-packages/allauth/socialaccount/models.py", line 282, in lookup
    provider_id = self.account.get_provider().id
  File "VIRTUALENV_PATH/python3.9/site-packages/allauth/socialaccount/models.py", line 141, in get_provider
    provider = self._provider = adapter.get_provider(
  File "VIRTUALENV_PATH/python3.9/site-packages/allauth/socialaccount/adapter.py", line 205, in get_provider
    app = self.get_app(request, provider=provider)
  File "VIRTUALENV_PATH/python3.9/site-packages/allauth/socialaccount/adapter.py", line 290, in get_app
    raise MultipleObjectsReturned

Exception Type: MultipleObjectsReturned at /accounts/facebook/login/callback/

Raised during: allauth.socialaccount.providers.oauth2.views.view
Request information:
USER: AnonymousUser

**Comment by pennersr** [comment]
The culprit is this line of code:

```
provider_id = self.account.get_provider().id
```

In order to return the provider we need to lookup the app, as that is a property of the provider instance (`provider.app`). But, in your case, there are multiple apps, so `get_provider()` gets confused. While passing request here (`get_provider(request)`) would solve the issue, we actually don't need the full provider here, only its ID. To be fixed.

**Comment by andreage** [comment]
Thank you very much, it makes much more sense now.

**Comment by pennersr** [comment]
Upon closer inspection, there are other cases that need more than the ID. Fixed via f356138d.

**Comment by pennersr** [comment]
Can you try out the current main branch?

**Comment by andreage** [comment]
I'm sorry I thought I sent a reply to your question. It's working perfectly for me now!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3564
