### ISSUE TITLE
Docs don't match code for ACCOUNT_CHANGE_EMAIL / ACCOUNT_MAX_EMAIL_ADDRESSES

### ISSUE THREAD

**Issue by norchai** [pennersr/django-allauth#3565]
The docs say:

> ACCOUNT_MAX_EMAIL_ADDRESSES (default: None)
> 
> The maximum amount of email addresses a user can associate to his account. It is safe to change this setting for an already running project – it will not negatively affect users that already exceed the allowed amount. Note that if you set the maximum to 1, users will not be able to change their email address unless you enable ACCOUNT_CHANGE_EMAIL.

Which suggests that you can set `ACCOUNT_MAX_EMAIL_ADDRESSES=1` and `ACCOUNT_CHANGE_EMAIL=True` and users will thus be able to change their email.

However, with those settings configured, instead AppSettings raises `ImproperlyConfigured: Invalid combination of ACCOUNT_CHANGE_EMAIL and ACCOUNT_MAX_EMAIL_ADDRESSES`

What I expected instead: either those settings would be mutually compatible, or docs would say they aren't.

Using Python 3.10.9, Django 4.2, allauth 0.59.0.

**Comment by pennersr** [comment]
Closed via f60a326d

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3565
