### ISSUE TITLE
Social login failure using openid_connect with authentik

### ISSUE THREAD

**Issue by igor47** [pennersr/django-allauth#3569]
Trying to log into my mailman-web site using authentik. I added a provider like so:

```
SOCIALACCOUNT_PROVIDERS = {
    'openid_connect': {
        "APPS": [
            {
                "provider_id": "moomers",
                "name": "Moomers Auth",
                "client_id": "secret",
                "secret": "secret",
                "settings": {
                    "server_url": "https://server/application/o/mailman/.well-known/openid-configuration",
                }
            }
        ],
    }
}
```

i go through the flow and get the dreaded `Social Network Login Failure` page. there's very little info (see #1120) but, following instructions in https://stackoverflow.com/a/42085183/153995 i modified the `authentication_error.html` page with:

```
<p>
Code: {{ auth_error.code }}, Error: {{ auth_error.exception }}
</p>
```

and got:

```
Code: unknown, Error: Error retrieving access token: b'{"error": "invalid_client", "error_description": "Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method)"}' 
```

now i'm stuck. my Authentik install thinks everything is okay and says my logins are successfully authorized. any pointers to further debugging woud be appreciated!

BTW, i found different instructions for how to configure openid connect with django allauth [here](https://github.com/goauthentik/authentik/issues/3503#issuecomment-1845940095) but using a `SERVERS` section instead of `APPS` under `openid_connect` results in the same outcome.

**Comment by pennersr** [comment]
I am sorry, but this issue is not actionable on the allauth side as it does not point to a bug or something that is clearly wrong in allauth.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3569
