### ISSUE TITLE
Issue with SAML user creation 

### ISSUE THREAD

**Issue by brianray** [pennersr/django-allauth#3570]
This could also give users access to eachother's data so I would consider it a security issue. Hopefully it is a configuration on my end but I followed the examples.

I am using SAML provider. Logging in creates a Django user named 'user' and social account. It overwrites previously created user.

All the data ends up in the "extra data" field. 

I want it to create. New user when user logs in.

Here is my environment:

Django==4.2.7; python_version >= '3.8'
django-allauth==0.58.2
python3-saml==1.16.0

Here is my configuration JSON

{"idp": {"name": "Example IdP", "slo_url": "https://wac.example.com/sso_cond2fa_2023/SingleLogoutService", "sso_url": "https://wac.example.com/sso_cond2fa_2023/SingleSignOnService", "x509cert": "-----BEGIN CERTIFICATE-----XXXXX-----END CERTIFICATE-----", "entity_id": "urn:[dev-123.us.auth0.com](http://dev-123.us.auth0.com/)"}, "advanced": {"strict": false}, "attribute_mapping": {"uid": "http://schemas.auth0.com/clientID", "email": "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress", "surname": "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname", "firstname": "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname", "email_verified": "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress"}}

More info, here is screenshot of the results:
![Screen Shot 2023-12-17 at 7 25 14 PM](https://github.com/pennersr/django-allauth/assets/676284/bbbf323e-1a35-4b90-82c5-040887643173)

I did check the SAML Tracker and I do see that extra data in there too. Anyway I can force it to use those values to populate the Admin User so it is unique?

Thanks in advance, Brian Ray

**Comment by pennersr** [comment]
The socialaccount does not look proper. It has an empty `uid`, and the extra data does not look like actual extra data originating from SAML, but rather from an internal data payload which should not end up there. This is properly tested to work over here:

https://github.com/pennersr/django-allauth/blob/main/allauth/socialaccount/providers/saml/tests.py#L51

Also, your config does not seem to match up with the screenshot, e.g. dev-123.us.auth0.com vs prod-1.us.auth0.com. All in all, something is definitely off here, but this does not clearly pinpoint an issue in allauth.

**Comment by brianray** [comment]
Thanks @pennersr, but UID is still not getting populated. I did add the correct Enttity_id and now both match. 

I did notice we are poping off uid https://github.com/pennersr/django-allauth/blob/main/allauth/socialaccount/providers/saml/provider.py#L60. could that be part of the issue?

**Comment by pennersr** [comment]
Fixed via 6251d5e0

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3570
