### ISSUE TITLE
Issue with Microsoft sign in

### ISSUE THREAD

**Issue by muazshahid** [pennersr/django-allauth#3573]
Facing login issue while using Microsoft for sign in, I have configured everything according to the documentation, the app for Microsoft Sign in has been configured  and has admin consent granted in the Microsoft Entra admin. I used the Django admin panel to register the social application with the following settings:

[![social app settings][1]][1]

When I click the Sign in with Microsoft button, it redirects me to the consent page:

[![consent page][2]][2]

 after I click Continue, I am redirected to the sign in page to select the account to sign in, I sign in with an account from my organization and continue, the login does not succeed at this point and I am directed to the following page:

[![error page][3]][3]

The redirect URL is set to : "http://localhost:8000/accounts/microsoft/login/callback/"
and the app is set for **Single tenant.**
 

> API permissions:

[![enter image description here][4]][4]

> settings.py

    SOCIALACCOUNT_PROVIDERS = {
        'microsoft': {
            'TENANT': 'organizations',
        }
    }

  [1]: https://i.stack.imgur.com/EheEy.png
  [2]: https://i.stack.imgur.com/VWqOS.png
  [3]: https://i.stack.imgur.com/puFeS.png
  [4]: https://i.stack.imgur.com/JRA7u.png

**Comment by muazshahid** [comment]
I was able to find a fix for it, when you create a new client secret, it provides the user with a Client Secret ID and a Client Secret Value, the value should be used for the secret key while you register your app on the Django admin panel.

Maybe it needs to be clarified in the documentation.

![image](https://github.com/pennersr/django-allauth/assets/65394988/a5210f09-5edd-4ffb-8749-7e3ddb300c2e)

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3573
