### ISSUE TITLE
Problem with 'callback_url' of microsft provider? 

### ISSUE THREAD

**Issue by Ilyespes2017** [pennersr/django-allauth#3575]
Hello everyone, 

I spent two days with this issue, I have the impression that the callback of microsoft social does not work correctly.
I've tried many things like setting up `LOGIN_REDIRECT_URL` , but nothing worked.

```python
class MicrosoftLogin(SocialLoginView):  
    adapter_class = MicrosoftGraphOAuth2Adapter
    callback_url = "http://localhost:8000/accounts/microsoft/login/callback/"
    client_class = OAuth2Client`
``` 

to make the connection work, it forces me to use the default callback which is : 
`http://localhost:8000/accounts/microsoft/login/`

I'm specifically mentioning Microsoft, because I've already done the same work with google, I haven't had this problem and if, for example, I modify the callback_url, it actually bugs the application, and it won't work anymore, unlike microsoft's callback, even if I modify it, the default value never changes.

Here's the google example for more context:
```python
class GoogleLogin(SocialLoginView):
    adapter_class = GoogleOAuth2Adapter
    callback_url = "http://localhost:8080/"
    client_class = OAuth2Client
``` 

Many thanks in advance

**Comment by pennersr** [comment]
This issue does not seem to be about allauth -- you are discussing issues in `SocialLoginView` which is not in the allauth codebase.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3575
