### ISSUE TITLE
Example Application setup incomplete

### ISSUE THREAD

**Issue by rcooke** [pennersr/django-allauth#3577]
I'm trying to fire up the Example app, and I discovered a step is missing from the install.  After running `pip install ..`, you have to then also run:

`pip install django-allauth[mfa]`
`pip install django-allauth[saml]`

To get the qrcode and onelogin libs, otherwise migrate bombs.

**Comment by pennersr** [comment]
Closed via 49824851

**Comment by rcooke** [comment]
Haha  I am amazed at the "install .." syntax - never seen that before!  Now with your latest change, I'm on the hunt for a manual to explain how it works and why....

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3577
