### ISSUE TITLE
Social Login with sites framework ?

### ISSUE THREAD

**Issue by skrskr** [pennersr/django-allauth#3578]
#### Django allauth with sites framework
- We are using allauth with sites framework in django app.
- When user login from different sites with same gmail account, allauth retreive the same account created first not creating new user for different site

#### Packages versions
```
django==2.16
django-allauth == 0.44.0
```

**Comment by pennersr** [comment]
Both mentioned versions of django and django-allauth are end of life and insecure. You really need to upgrade.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3578
