### ISSUE TITLE
Option: Blocking by IP instead of user lock for ACCOUNT_LOGIN_ATTEMPTS_LIMIT

### ISSUE THREAD

**Issue by bigcat88** [pennersr/django-allauth#3584]
I couldn't find how to set up or easily add a block by IP instead of blocking a user if the password is entered incorrectly multiple times.

If there was a leak with logins, the site can easily be made unusable by trying out passwords for each login, which will lead to valid users not being able to log in.

Thank you.

**Comment by pennersr** [comment]
Have a look here:

https://github.com/pennersr/django-allauth/blob/main/allauth/account/adapter.py#L665

That ratelimit key currently only contains the login (i.e. username or password).  For now, you could override the adapter method `_get_login_attempts_cache_key()` and include the IP. However, that is a private method, and adding support for this out of the box would be good.

**Comment by pennersr** [comment]
Will be fixed by #3592

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3584
