### ISSUE TITLE
Custom social adapter's get_connect_redirect_url method not being called

### ISSUE THREAD

**Issue by cgmark101** [pennersr/django-allauth#3588]
Hi to all. I've created a custom social account adapter that overrides the get_connect_redirect_url method. However, this method is not being called when a social account is connected.

Here's my custom adapter:

core/social_adapter.py:
```py
from allauth.socialaccount.adapter import DefaultSocialAccountAdapter
from django.urls import reverse
from apps import models

class CustomSocialAccountAdapter(DefaultSocialAccountAdapter):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        print("CustomSocialAccountAdapter is being used")
    
    def get_connect_redirect_url(self, request, socialaccount):
        print("get_connect_redirect_url method")
        tag_code = request.COOKIES.get("tag_code")
        if tag_code:
            try:
                tag = models.Tag.objects.get(code=tag_code)
                if not tag.is_active:
                    return reverse("activate")
            except models.Tag.DoesNotExist:
                pass
        return reverse("home")
    
```

core/settigs.py:
```py
SOCIALACCOUNT_ADAPTER = 'core.social_adapter.CustomSocialAccountAdapter'
```

I've confirmed that my custom adapter is being used by calling the print() method in the __init__, but the get_connect_redirect_url method is never called. I've also checked my server logs and there are no error messages related to my custom adapter.

Using:
Django 5.0
django-allauth 0.59.0

Any help would be appreciated.

**Comment by pennersr** [comment]
I suggest you put a breakpoint/print over at `allauth.socialaccount.helpers._add_social_account()` -- this is the code that triggers when connecting a new account, and `get_connect_redirect_url` is definitely called there.

**Comment by cgmark101** [comment]
Thank you for your response. I apologize for the confusion in my initial description. To clarify, the issue occurs during the authentication process, specifically when the AuthProcess.LOGIN method is called.

After successfully completing Google OAuth, the function complete_social_login is called from helpers.py. This function then calls either _complete_social_login or _process_signup, depending on whether the user already exists or not.

My goal here is to redirect the user to a view called create_tag if the tag is not activated, for example /<tag_id>; a cookie is created with the value of tag_id, then redirect to the login page, and after a successful social login, redirect to the create_tag view, and this view will handle the rest

However, the current social login implementation always redirects to the LOGIN_REDIRECT_URL specified in the settings.py file.

All the redirect flow works well on normal accounts by overriding the allauth.account.views.LoginView form_valid method

**Comment by cgmark101** [comment]
Fixed it by creating a custom adapter 

core/custom_adapter.py
```py
from allauth.account.adapter import DefaultAccountAdapter
from django.urls import reverse
from apps import models

class CustomAccountAdapter(DefaultAccountAdapter):
    def get_login_redirect_url(self, request):
        tag_code = request.COOKIES.get("tag_code")
        if tag_code:
            try:
                tag = models.Tag.objects.get(code=tag_code)
                if not tag.is_active:
                    return reverse("create_tag")
            except models.Tag.DoesNotExist:
                pass

        return reverse("dashboard")
```

core/settings.py
```py
ACCOUNT_ADAPTER = 'core.account_adapter.CustomAccountAdapter'
```

This adapter works for both, normal accounts and social accounts

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3588
