### ISSUE TITLE
Issues with Microsoft Authentication

### ISSUE THREAD

**Issue by liofk** [pennersr/django-allauth#3590]
**I have used these guides to configure the microsoft provider.**
[https://docs.allauth.org/en/latest/socialaccount/providers/microsoft.html](url)
[https://stackoverflow.com/questions/73885989/django-allauth-azure-ad-configurations](url)
[https://stackoverflow.com/questions/75738664/redirect-uri-is-invalid-using-microsoft-oauth-to-sign-in-for-accounts-not-in-m](url)

**Microsoft returns this error when generating a user or logging in**
invalid_request: The provided value for the input parameter 'redirect_uri' is not valid. The expected value is a URI which matches a redirect URI registered for this client application.
**the url that returns to me**
[https://login.live.com/oauth20_authorize.srf?client_id=**CLIENT_ID**&scope=User.Read&redirect_uri=http%3a%2f%2f127.0.0.1%3a8000%2faccounts%2fmicrosoft%2flogin%2fcallback%2f&response_type=code&state=dHlLJmeLnzTFwjaw&uaid=b7ab4c738ede49e086fd051249fa74af&msproxy=1&issuer=mso&tenant=common&ui_locales=es-AR&epct=PAQABAAEAAAAmoFfGtYxvRrNriQdPKIZ-eIV96l5wgpJXj4OZXZPRzZ6ePqDLCadgLGvdnUHawlDnfOFKpchhiVa5LitDfXAdho1Gu85wD2vvR2aeK4lFnC3iDrVGxnD_gk3aMbnOJ0s0U5Cio4JZYMm73eCHzrGAqJliRrq1aZDocJ8dy9OneW7Jso0725O9EEXx9GzPOJZn2lRGKIoCL0JogDdwggIbcNIuAUbWuqtaGmq0Qgy0UiAA&jshs=0&username=**MAIL**%40hotmail.com&login_hint=**MAIL**%40hotmail.com](url)

**My current configuration is the following**
**Python:** 3.11.7
**Django:** 5.0
**Django-allauth:** 0.59.0
![MICROSOFT1](https://github.com/pennersr/django-allauth/assets/116922805/8ee3e0ab-db7e-4063-8663-6353630b5200)
![MICROSOFT2](https://github.com/pennersr/django-allauth/assets/116922805/4aac46a7-d755-42f4-8fac-8a5a5514574b)
![MICROSOFT3](https://github.com/pennersr/django-allauth/assets/116922805/05f4ba14-c0b7-4b9c-a47d-3f59c1e6de4c)
**1-** Microsoft Graph
**2-** APP NAME
**3-** Application ID (client)
**4-** Client Secret Value as shown when creating the secret
**Settings:** {} **Because I have configured my application for multi-tenant authentication (default)**

**Also try using these combinations, getting the same results**
Secret Key: Client Secret Secret ID
Key: Client Secret Value

Secret Key: Secret Value
Key: Client Client Secret Secret ID

Secret Key: Client Secret Secret ID
Key: empty

Secret Key: Secret Value
Key: empty

**Comment by pennersr** [comment]
The callback URL does not match. See:

`redirect_uri=http%3a%2f%2f127.0.0.1%3a8000%2faccounts%2fmicrosoft%2flogin%2fcallback%2f`

... that's 127.0.0.1, vs localhost which you have in your config.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3590
