### ISSUE TITLE
Template uses humanize, but not listed in Quickstart

### ISSUE THREAD

**Issue by Andrioden** [pennersr/django-allauth#3607]
Se:
- https://github.com/search?q=repo%3Apennersr%2Fdjango-allauth%20humanize&type=code
- https://docs.allauth.org/en/latest/installation/quickstart.html

I got an error while using django_compress 

```
(untitledgame) PS C:\Repos\untitledgame> python manage.py compress --force
DEBUG IS False
Compressing... Invalid template usersessions\usersession_list.html: 'humanize' is not a registered tag library. Must be one of:
...
...
```

Fixed by adding

"django.contrib.humanize" to INSTALLED_APPS

**Comment by pennersr** [comment]
The quickstart does not include `usersessions`, hence `humanize` is not needed there. Adding an installation section to the `usersessions` would be needed...

**Comment by pennersr** [comment]
b32eddb3

**Comment by Andrioden** [comment]
I wonder why `django_compressor` found the `usersessions\usersession_list.html` template when i havent installed `allauth.usersessions`?

Here is my full installed apps list, that gave me the error above
```python
INSTALLED_APPS = (
    # Default
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    # "django.contrib.humanize", # <-- have to add this
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Apps
    "compressor",
    # allauth
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.discord",
    "allauth.socialaccount.providers.google",
    # Custom
    "game",
    "monitor",
    "social",
)
```

**Comment by pennersr** [comment]
Likely, `compressor` loops over all templates of all apps, and the builtin templates are all contained within the `allauth` app.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3607
