### ISSUE TITLE
Don't ignore standard Django settings

### ISSUE THREAD

**Issue by ferrouswheel** [pennersr/django-allauth#361]
I have EMAIL_SUBJECT_PREFIX set, and lo allauth uses a ACCOUNT_EMAIL_SUBJECT_PREFIX with a completely different value. I find out that account related emails had the wrong subject all along.

I think this design choice could be better. If a user has their email preferences configured already, why the need to replicate all Django settings and make them completely separate?

If nothing else, ACCOUNT_EMAIL_SUBJECT_PREFIX should use EMAIL_SUBJECT_PREFIX if the user defines it and only use the allauth default value if neither setting is defined.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/361
