### ISSUE TITLE
Implementing openid_connect using django-alluth

### ISSUE THREAD

**Issue by delton-ecometrica** [pennersr/django-allauth#3610]
Hey all,

I have been trying to implement openid_connect using django-alluth but can't seem to configure the login parts in the html templates, also the when loading the socialproviders html tag, openid_connect doesn't appear even though it has been to INSTALLED_APPS and added the SOCIALACCOUNT_PROVIDERS Setting which has the endpoints and client id and secret in Django.

I have my own OIDC server which I want to connect using the openid_connect provider and would be grateful if there is documentation supporting it.

I am on django-allauth==0.54.0

The documentation for openid_connect is not clear on how it works, has anyone implemented openid_connect before using django-alluth

**Comment by delton-ecometrica** [comment]
Was using the wrong version of the package

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3610
