### ISSUE TITLE
get_providers returns Google Provider Twice

### ISSUE THREAD

**Issue by ottipc** [pennersr/django-allauth#3611]
Hi, when i set up

`allauth.socialaccount.providers.google`

im my settings.py the method :

`@register.simple_tag(takes_context=True)
def get_providers(context):
    """
    Returns a list of social authentication providers.

    Usage: `{% get_providers as socialaccount_providers %}`.

    Then within the template context, `socialaccount_providers` will hold
    a list of social providers configured for the current site.
    """
    request = context["request"]
    adapter = get_adapter()
    providers = adapter.list_providers(request)
    return sorted(providers, key=lambda p: p.name)`
    
  returns the Google Provider Twice! That causes problems in my implementation!
  
  
![image](https://github.com/pennersr/django-allauth/assets/42996997/69528a02-1e37-4531-976f-ada1890871bb)

Can someone tellme what happens here?

**Comment by pennersr** [comment]
Do you also happen to have it setup in your database?

**Comment by pennersr** [comment]
Closing -- this is likely to be a config issue.

**Comment by ottipc** [comment]
no config issue.
all was right!

**Comment by ottipc** [comment]
like you see in the ticket i only add google provider once in config.
had to debug for hours, but your method returning two Google Auth Provides, why ever he do this!

Database i didnt touch!

**Comment by ottipc** [comment]
we had to go to Auth0 because all of our developers had the same issue!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3611
