### ISSUE TITLE
Use Stripe Applications instead of Stripe Connect

### ISSUE THREAD

**Issue by MatthiasGabriel108** [pennersr/django-allauth#3618]
I was wondering why django-allauth uses Stripe Connect for auth, where it seems to me that since 2021, Stripe Applications are the way to go. Connect seems to mainly be used for handling payments, and it requires `read_write` scope. For our use case, and I believe many others as well, `read_only` is enough, but this scope isn't allowed with Connect, it's only allowed on Stripe Applications.

Here's some background info: https://support.stripe.com/questions/security-permissions-and-access-levels-when-connecting-your-stripe-account-to-a-third-party-platform#:~:text=Starting%20in%20July%202021%2C%20Platforms

**Comment by pennersr** [comment]
I must admit, I haven't used the Stripe provider myself. It was contributed by @akolpakov here:

https://github.com/pennersr/django-allauth/pull/1190

If Stripe Applications is a completely different provider (different endpoints, different user payload, ...) then it would make sense to add a provider dedicated for that (`stripe_apps` ?) If it the differences are minimal, then we could add a setting to specify whether it is to run in Connect or Applications mode.

**Comment by pennersr** [comment]
Moved to https://codeberg.org/allauth/django-allauth/issues/3618
