### ISSUE TITLE
Reverse URL generation fails when using namespaced URLs.

### ISSUE THREAD

**Issue by borfast** [pennersr/django-allauth#362]
If I include this in my urls.py:
`url(r'^accounts/', include('allauth.urls', namespace="accounts")),`
and then use this in a template:
`{% url 'accounts:account_login' %}`
it works fine and the link is rendered correctly.

But then if I visit one of the allauth pages (accounts/login, or accounts/signup, for example) I get exceptions. For instance, if I go to the login page, I will get this:

```
NoReverseMatch at /accounts/login/
Reverse for 'account_signup' with arguments '()' and keyword arguments '{}' not found.
```

The problem occurs in [allauth/account/views.py, line 72](https://github.com/pennersr/django-allauth/blob/master/allauth/account/views.py#L72).
I get similar issues in the signup page as well.

I'm not sure if this is a bug in allauth or something I'm doing wrong.

**Comment by rikkib1997** [comment]
Yes it does, when I want to change the url patterns of allauth, I don't want to have to change it in all my links referencing to it.

**Comment by turicas** [comment]
I have the same case as @rikkib1997: need to customize the URLs of my system and allauth simply does not allow it.
Could we please reopen this issue?

**Comment by stemcc** [comment]
Another common use case is allowing user organizations to have their own subdomains like my-company.site.com, and in which they can also login -- my-company.site.com/login.

**Comment by ccurvey** [comment]
I like namespaced URL names because "explicit is better than implicit" and " Namespaces are one honking great idea -- let's do more of those!"

To wit, it makes it easier for "future me" (or, heaven help us, future you) to be able to read my code

    {% url 'account_login' %}

Kinda leaves me wondering , "where did *account_login* come from?"  Whereas:

    {% url 'allauth:account_login' %}

Makes it more explicit.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/362
