### ISSUE TITLE
'SyncToAsync.__call__' was never awaited   session_check(request) 

### ISSUE THREAD

**Issue by stephane-martin** [pennersr/django-allauth#3634]
After upgrade to v0.61.0, i can see spurious warnings in logs:

```
.../lib/python3.12/site-packages/allauth/account/middleware.py:53: RuntimeWarning: coroutine 'SyncToAsync.__call__' was never awaited
  session_check(request)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

Looking at https://github.com/pennersr/django-allauth/blob/main/allauth/account/middleware.py, I think there is indeed something fishy.

In the async case:

```
_remove_dangling_login(
    request, response, sync_to_async(_session_check)
)
```

so a coroutine is passed as the third argument of `_remove_dangling_login`.

Then such coroutine is called but not awaited on line 53:

```
session_check(request)
```

The awaitable result of the session_check call is lost and left be caught by GC. Hence the warning.

**Comment by pennersr** [comment]
Fixed via 4037177cc8c3f77a1aed594611576f8b74536153

**Comment by stephane-martin** [comment]
thanks! looks alright to me

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3634
