### ISSUE TITLE
not able to upgrade to django-allauth==0.56.0

### ISSUE THREAD

**Issue by sumit12311** [pennersr/django-allauth#3635]
pip install django-allauth==0.56.0
ERROR: Could not find a version that satisfies the requirement django-allauth==0.56.0 (from versions: 0.1.0, 0.2.0, 0.3.0, 0.4.0, 0.5.0, 0.6.0, 0.7.0, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.9.0, 0.10.0, 0.10.1, 0.11.0, 0.11.1, 0.12.0, 0.13.0, 0.14.0, 0.14.1, 0.14.2, 0.15.0, 0.16.0, 0.16.1, 0.17.0, 0.18.0, 0.19.0, 0.19.1, 0.20.0, 0.21.0, 0.22.0, 0.23.0, 0.24.0, 0.24.1, 0.25.0, 0.25.1, 0.25.2, 0.26.0.post1, 0.26.1, 0.27.0, 0.28.0, 0.29.0, 0.30.0, 0.31.0, 0.32.0, 0.33.0, 0.34.0, 0.35.0, 0.36.0, 0.37.0, 0.37.1, 0.38.0, 0.39.0, 0.39.1, 0.40.0, 0.41.0, 0.42.0, 0.43.0, 0.44.0, 0.45.0, 0.46.0, 0.47.0, 0.48.0, 0.49.0, 0.50.0, 0.51.0, 0.52.0, 0.53.0, 0.53.1)
ERROR: No matching distribution found for django-allauth==0.56.0

**Comment by pennersr** [comment]
See pypi:

![image](https://github.com/pennersr/django-allauth/assets/201022/a71cd0bc-dc8c-4f53-8ffe-8f5a48f6e58d)

Due to a serious issue, 0.56.0 has been yanked. See the changelog.

**Comment by sumit12311** [comment]
It is showing me versions till 0.53.1 only, though I installed latest pip but unable to upgrade to version higher than 0.53.1
Please help

<img width="1504" alt="image" src="https://github.com/pennersr/django-allauth/assets/159553909/df080754-4b87-4d80-a3b5-bfd041c0fd47">

`(datatwo_env) [root@data1-staging-jiw2 datatwo]# pip install django-allauth==0.56.1
ERROR: Could not find a version that satisfies the requirement django-allauth==0.56.1 (from versions: 0.1.0, 0.2.0, 0.3.0, 0.4.0, 0.5.0, 0.6.0, 0.7.0, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.9.0, 0.10.0, 0.10.1, 0.11.0, 0.11.1, 0.12.0, 0.13.0, 0.14.0, 0.14.1, 0.14.2, 0.15.0, 0.16.0, 0.16.1, 0.17.0, 0.18.0, 0.19.0, 0.19.1, 0.20.0, 0.21.0, 0.22.0, 0.23.0, 0.24.0, 0.24.1, 0.25.0, 0.25.1, 0.25.2, 0.26.0.post1, 0.26.1, 0.27.0, 0.28.0, 0.29.0, 0.30.0, 0.31.0, 0.32.0, 0.33.0, 0.34.0, 0.35.0, 0.36.0, 0.37.0, 0.37.1, 0.38.0, 0.39.0, 0.39.1, 0.40.0, 0.41.0, 0.42.0, 0.43.0, 0.44.0, 0.45.0, 0.46.0, 0.47.0, 0.48.0, 0.49.0, 0.50.0, 0.51.0, 0.52.0, 0.53.0, 0.53.1)
ERROR: No matching distribution found for django-allauth==0.56.1
(datatwo_env) [root@data1-staging-jiw2 datatwo]# pip install django-allauth==0.57.0
ERROR: Could not find a version that satisfies the requirement django-allauth==0.57.0 (from versions: 0.1.0, 0.2.0, 0.3.0, 0.4.0, 0.5.0, 0.6.0, 0.7.0, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.9.0, 0.10.0, 0.10.1, 0.11.0, 0.11.1, 0.12.0, 0.13.0, 0.14.0, 0.14.1, 0.14.2, 0.15.0, 0.16.0, 0.16.1, 0.17.0, 0.18.0, 0.19.0, 0.19.1, 0.20.0, 0.21.0, 0.22.0, 0.23.0, 0.24.0, 0.24.1, 0.25.0, 0.25.1, 0.25.2, 0.26.0.post1, 0.26.1, 0.27.0, 0.28.0, 0.29.0, 0.30.0, 0.31.0, 0.32.0, 0.33.0, 0.34.0, 0.35.0, 0.36.0, 0.37.0, 0.37.1, 0.38.0, 0.39.0, 0.39.1, 0.40.0, 0.41.0, 0.42.0, 0.43.0, 0.44.0, 0.45.0, 0.46.0, 0.47.0, 0.48.0, 0.49.0, 0.50.0, 0.51.0, 0.52.0, 0.53.0, 0.53.1)
ERROR: No matching distribution found for django-allauth==0.57.0
`

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3635
