### ISSUE TITLE
Email registration unique constraint "users_user_email_key"

### ISSUE THREAD

**Issue by madatbay** [pennersr/django-allauth#3637]
I'm using `allauth` with `email` as the username field. All the processes are working except when a user tries to register again with an email that is not verified. Steps to reproduce
1. Register an user with an email
2. Do not verify that email
3. Try to make registration again
4. See the error message as:
```
django.db.utils.IntegrityError: duplicate key value violates unique constraint "users_user_email_key"
```
After debugging what I found out is:
1. In `validate_email` method in `RegisterSerializer` we are checking if we already have a `verified` email such as:
```
    def validate_email(self, email):
        email = get_adapter().clean_email(email)
        if allauth_account_settings.UNIQUE_EMAIL:
            if email and EmailAddress.objects.is_verified(email): <--------- Only checks if we have verified email that's why this conditional is skipped
                raise serializers.ValidationError(
                    _('A user is already registered with this e-mail address.'),
                )
        return email
```
2. Email passes validation in 1st step, and is tried to save email to the 2nd `user` instance 
3. But as email is already saved into the first `user` instance and waiting for verification we get the unique constraint `users_user_email_key` error

My email field
```
email = models.EmailField("Email", unique=True) <---- I can remove unique constrain from here, but then django admin will fail to prevent duplicates
```

Settings:
```
ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
```

Package version
```
django-allauth==0.60.1
```

**Comment by pennersr** [comment]
`RegisterSerializer` is -- I assume -- part of dj-rest-framework. When filing bugs, please limit the scope to django-allauth.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3637
