### ISSUE TITLE
How to add images in email with django allauth

### ISSUE THREAD

**Issue by josylad** [pennersr/django-allauth#3641]
Hello, 
is there a way to include images in emails? 

I want to add a logo to this OTP message - allauth/templates/mfa/email/otp_login_message.txt 

 But I can see that it is a txt file, so HTML attributes are not working. Any ideas?

**Comment by pennersr** [comment]
It supports both `.txt` as well as `.html` -- simply provide a `.html` file. See: https://github.com/pennersr/django-allauth/blob/main/allauth/account/adapter.py#L154

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3641
