### ISSUE TITLE
Slack provider callback shows a Third-Party Login failure

### ISSUE THREAD

**Issue by DragosDumitrache** [pennersr/django-allauth#3645]
Hi,

Firstly, thanks for creating `django-allauth`, I find it incredibly useful.

Let me preface this by saying, I have looked through existing and previous issues, but found nothing that was still relevant.

I've got an instance of an application where I'm trying to authenticate users using Slack. All the configuration is as documented, the callbacks are as required by the docs, the client ID and secrets are alright.

Yet, when receiving the callback, I get shown the following page

<img width="603" alt="Screenshot 2024-02-17 at 10 11 21" src="https://github.com/pennersr/django-allauth/assets/5496443/afbf952b-78c4-48db-959a-aa004959b624">

I've checked the same client ID and secrets with a different framework, and I've checked them with my own code so I can check the same URLs, I was able to login successfully in both cases.

I've also tried extending the `SocialAdapter` and logging errors, but all I got was an `empty` error.

I'm using version `0.61.1` with Django 5.

**Comment by ateeq-mughal** [comment]
The Same is happening with using GitHub OAuth. The callback url i am getting is (with no error msg):

http://localhost:8000/accounts/github/login/callback/?code=1216195be45faf4d04af&state=jYUTOFAXVKeiqzpk

I do not know what code and status in uri is referring to.

I'm using version **```0.61.1```**

**Comment by DragosDumitrache** [comment]
> The Same is happening with using GitHub OAuth. The callback url i am getting is (with no error msg):
> 
> http://localhost:8000/accounts/github/login/callback/?code=1216195be45faf4d04af&state=jYUTOFAXVKeiqzpk
> 
> I do not know what code and state in uri is referring to.
> 
> ![image](https://private-user-images.githubusercontent.com/76849373/306780297-890a892e-9469-4981-9e38-8945775b33e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4MDQwNTQsIm5iZiI6MTcwODgwMzc1NCwicGF0aCI6Ii83Njg0OTM3My8zMDY3ODAyOTctODkwYTg5MmUtOTQ2OS00OTgxLTllMzgtODk0NTc3NWIzM2U3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI0VDE5NDIzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhNTA5YWZiNzBjYTJmMjI2MzMwZGRjNDA0OTk5MDg2YzU2MThkODBiNzE4Y2UyZTBmOWQ5MWFjMTgxNTg0ZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FoLXqbI4vJRkImxi5sPgHeppBZdyV_pXQK8StBw9dK4)
> 
> I'm using version **`0.61.1`**
> 
> EDIT: Downgrading to **`0.54.0`** and removing `allauth.account.middleware.AccountMiddleware` middleware solved the problem. But now I can not use LinkedIn Open ID Connect authentication as it is not supported in version **`0.54.0`**.
> 
> Looking for the solution

Just want to reiterate as well, version 0.54.0 works for me too

**Comment by pennersr** [comment]
I have no idea what is going wrong for you, but it's not the case that GitHub does not work with the latest version. For example, it's just running fine over here:

https://django.demo.allauth.org/

**Comment by DragosDumitrache** [comment]
> I have no idea what is going wrong for you, but it's not the case that GitHub does not work with the latest version. For example, it's just running fine over here:
> 
> https://django.demo.allauth.org/

Yeah, no, the issue for me was Slack, but like I said, I also have no idea why it worked a few days later without me touching the code or the app setup, but it definitely doesn't seem related to this framework

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3645
