### ISSUE TITLE
[SAML] SLS required but is optional in SAML spec #3579

### ISSUE THREAD

**Issue by mecampbellsoup** [pennersr/django-allauth#3654]
SLS or "single logout service" is a non-required part of a SAML specification.

By default in our internal SAML app configurations, it is disabled:

<img width="1323" alt="image" src="https://github.com/coreweave/cloud-app/assets/2043821/9220dee5-2360-4454-86f6-a008001589fc">

However, [at least one spot in the SAML allauth code](https://github.com/pennersr/django-allauth/blob/079872ab5564fa73a73bbf36af990a29dea1ac3c/allauth/socialaccount/providers/saml/utils.py#L42) seems to indicate it's a required part of the IdP configuration.

Could we make this optional, is there a suggested workaround?

**Comment by pennersr** [comment]
I am not sure I fully understand the issue. The SLS endpoint is implemented by allauth, and given that it is there, what harm is there in exposing that?

**Comment by mecampbellsoup** [comment]
> I am not sure I fully understand the issue. The SLS endpoint is implemented by allauth, and given that it is there, what harm is there in exposing that?

It is possible to configure a valid SAML application in a provider like Okta without enabling SLS, so the functionality won't work I don't think.

**Comment by mecampbellsoup** [comment]
Fair point!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3654
