### ISSUE TITLE
Extra text in `account/email.html` template?

### ISSUE THREAD

**Issue by FroggyFlox** [pennersr/django-allauth#3655]
I noticed 2 seemingly extra text lines in the `account/email.html` template:
https://github.com/pennersr/django-allauth/blob/9090df782ce4e4a36a4991a859956e179024e71b/allauth/templates/account/email.html#L61
https://github.com/pennersr/django-allauth/blob/9090df782ce4e4a36a4991a859956e179024e71b/allauth/templates/account/email.html#L67

They appeared to have been introduced during https://github.com/pennersr/django-allauth/commit/ff1a6a38e14b0542a23362e650eb8d88e8edd73a

They appear harmless but thought I would bring it up in case it helps... sorry if this actually creates more noise than help.

**Comment by pennersr** [comment]
Thanks for reporting, fixed in 143068e5

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3655
