### ISSUE TITLE
[Models] Modify built-in allauth models other than User?

### ISSUE THREAD

**Issue by mecampbellsoup** [pennersr/django-allauth#3656]
I know that it's possible to modify the `User` model, either via [allauth's account configuration settings](https://docs.allauth.org/en/latest/account/advanced.html#custom-user-models), or Django's [`AUTH_USER_MODEL`](https://docs.djangoproject.com/en/5.0/topics/auth/customizing#auth-custom-user).

But, is it possible/what is the recommended way to make modifications to other models like `SocialApp`? Specifically, I'm interested in adding a foreign key, something like:

```sql
"socialaccount_socialapp_org_id_fkey" FOREIGN KEY (org_id) REFERENCES organization(id) ON DELETE CASCADE
```
A non-invasive option would be to add a join table like `socialaccount_socialapp_organization` but it got me wondering if this topic had come up before in allauth.

Thanks, as always! 😄 

---
**UPDATE**

I ended up subclassing the allauth model in my outer Django application which is called `iam` in our case:

```python
class SocialApp(SocialApp):
    # Add foreign key to organization
    org = models.ForeignKey(Organization, on_delete=models.CASCADE)
```

Django seemed smart enough to generate an interesting migration that works more or less perfectly, as long as you remember to `from iam.models import SocialApp` instead of `from allauth.socialaccount.models import SocialApp`:

```python
# Generated by Django 5.0.2 on 2024-02-24 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0106_fix_s3_alert_description_typo'),
        ('socialaccount', '0006_alter_socialaccount_extra_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialApp',
            fields=[
                ('socialapp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='socialaccount.socialapp')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iam.organization')),
            ],
            bases=('socialaccount.socialapp',),
        ),
    ]

```

```sql
Table "public.iam_socialapp"
      Column      |  Type   | Collation | Nullable | Default | Storage | Stats target | Description
------------------+---------+-----------+----------+---------+---------+--------------+-------------
 socialapp_ptr_id | integer |           | not null |         | plain   |              |
 org_id           | integer |           | not null |         | plain   |              |
Indexes:
    "iam_socialapp_pkey" PRIMARY KEY, btree (socialapp_ptr_id)
    "iam_socialapp_org_id_c4967d81" btree (org_id)
Foreign-key constraints:
    "iam_socialapp_org_id_c4967d81_fk_organization_id" FOREIGN KEY (org_id) REFERENCES organization(id) DEFERRABLE INITIALLY DEFERRED
    "iam_socialapp_socialapp_ptr_id_6817a7a6_fk_socialacc" FOREIGN KEY (socialapp_ptr_id) REFERENCES socialaccount_socialapp(id) DEFERRABLE INITIALLY DEFERRED
Access method: heap
```
So, it effectuated the "join table" strategy that I initially mentioned. Cool!

**Comment by pennersr** [comment]
For swapping out models there is open issue #2997 -- so closing this one in favor of that.

Wondering, why don't you just opt to add a one-to-one or many-to-many field on your organization model point to `SocialApp`?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3656
