### ISSUE TITLE
Using SAML inside AWS Cognito - 400: Bad request

### ISSUE THREAD

**Issue by benshaji-sequoiaat** [pennersr/django-allauth#3659]
HI, I've been using *allauth* for few months now and i should say its amazing and lifts all complex logic. I currently use it with AWS Cognito (for those who are curious, [check this article i wrote](https://b3nsh4.com/blog/2024/django-oauth-fullstory/)). 

As I mentioned, users can successfully login to my app for all users created in Cognito user pool. Now, I'm trying to integrate SAML as specified here https://docs.amazonaws.cn/en_us/cognito/latest/developerguide/cognito-user-pools-saml-idp.html

After setting everything in Azure, I can login with Azure via Cognito as my users normally login with Cognito and it returns Auth Code. We know this Code is exchanged to get token.

### What's the issue?
- Cognito returns Code after successfully sign-in with Azure
- But, backend returns: 400 Bad Request. *Failed to exchange code* ?
- Since login is successful, this user is created in Cognito user pool, but we get 400 from backend. I've cheked Social Accounts in admin dashboard and the account just authenticated was not created there.
I believe allauth is unaware that its SAML and i think it does not have to.  End of the day, allauth gets the Code which can be exchanged to Cognito. 

I know these details are not sufficient, let me know what log/information you're looking in specific. 
Thanks!

**Comment by benshaji-sequoiaat** [comment]
The issue was simple, it was because i had a local account with the same email address as my SAML auth email. 
You can find out the error by manually POST-ing the request via Postman. I use dj-rest-auth which is a wrapper around allauth. Hence, if somebody is trying to make SAML work via Cognito in allauth, it works out of the box. 
Good luck
Ben!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3659
