### ISSUE TITLE
DatabaseError at /admin/socialaccount/socialapp/

### ISSUE THREAD

**Issue by euanmillar** [pennersr/django-allauth#367]
Hi,

Apologies but I am a newbie, and I am having a bit of trouble.  I am getting "relation does not exist errors" whenever I try to click on Social accounts, social apps or social tokens in Django admin like this:

DatabaseError at /admin/socialaccount/socialaccount/
relation "socialaccount_socialaccount" does not exist

DatabaseError at /admin/socialaccount/socialapp/
relation "socialaccount_socialapp" does not exist

DatabaseError at /admin/socialaccount/socialtoken/
relation "socialaccount_socialapp" does not exist

I'm using a Postgres database and I thought I had installed allauth correctly but it looks like I've done something wrong.  Any help would be much appreciated.

Thanks,

Euan

**Comment by beren5000** [comment]
Greetings
Im having the same issue, now with django 2.1.7 and python 3, im using the migrate command, but with django-tenant-schemas, so i use migrate schemas, i  try to put all auth apps in shared and tenant apps, in the settings, but when i try to access to the admin to create my credentials, i get the same error
ProgrammingError at /es/admin/socialaccount/socialaccount/
relation "socialaccount_socialaccount" does not exist
LINE 1: SELECT COUNT(*) AS "__count" FROM "socialaccount_socialaccou...

there is something i can do with this?

**Comment by samsime** [comment]
> Greetings
> Im having the same issue, now with django 2.1.7 and python 3, im using the migrate command, but with django-tenant-schemas, so i use migrate schemas, i try to put all auth apps in shared and tenant apps, in the settings, but when i try to access to the admin to create my credentials, i get the same error
> ProgrammingError at /es/admin/socialaccount/socialaccount/
> relation "socialaccount_socialaccount" does not exist
> LINE 1: SELECT COUNT(*) AS "__count" FROM "socialaccount_socialaccou...
> 
> there is something i can do with this?

Try to do a migration:
python manage.py migrate

**Comment by samsime** [comment]
Try a migration:
python manage.py migrate

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/367
