### ISSUE TITLE
consume_or_429 has hardcoded path

### ISSUE THREAD

**Issue by je-bugshell** [pennersr/django-allauth#3671]
The function `consume_or_429` in `allauth/core/ratelimit.py:118,122` returns (if being rate limited) the 429.html. It would be nice to have more flexibility about where this template resides. To make the behavior more consistent with other http errors, could you either have this be an adaptable path, or maybe raise a 429 exception, for which one can write a custom handler? Thank you very much! You do amazing work!

**Comment by pennersr** [comment]
I mean, how do you alter these?:

https://github.com/django/django/blob/main/django/views/defaults.py#L15

**Comment by je-bugshell** [comment]
What I do is customize the error view and point the appropriate handler to that custom view. According to the [docs](https://docs.djangoproject.com/en/dev/topics/http/views/#customizing-error-views). For instance: 

In my `ROOT_URLCONF` file:
```python
handler400 = 'myapp.views.handler400'
```

then in myapp views:
```python
def handler400(request, exception=None):
    return render(request, 'errors/400.html', status=400)
```

I do this for 400, 403, 404, 405, 410, 500

**Comment by pennersr** [comment]
Django does not support a `handler429` -- but it's added to allauth now, so you can drop a custom `handler429` in there now.

See: fb13bc5f

**Comment by je-bugshell** [comment]
Legend!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3671
