### ISSUE TITLE
Assertion Error for Existing Users After Registering New User with Social Account

### ISSUE THREAD

**Issue by YuchenTOR** [pennersr/django-allauth#3679]
Hello,

I've encountered an issue where, after registering a new user through a social account integration, all existing users are unable to log in and are met with an AssertionError. This problem persists across all stored users and makes it impossible for them to log in after a new user registers via a social account.

Steps to Reproduce:

1. Register a new user using a social account (e.g., Google, Facebook).
2. Attempt to log in with an existing user account.
3. An AssertionError is thrown, preventing the login.
```
def complete_social_login(request, sociallogin):
    assert not sociallogin.is_existing …
    sociallogin.lookup()
    try:
        get_adapter().pre_social_login(request, sociallogin)
        signals.pre_social_login.send(
            sender=SocialLogin, request=request, sociallogin=sociallogin
        )
```
Current Behavior:

- After a new user registers through a social account, attempting to log in with any existing user accounts results in an AssertionError.

Expected Behavior:

- Existing users should be able to log in successfully, regardless of new users registering through social accounts.

Workarounds:

Restarting the Django server temporarily resolves the issue, allowing existing users to log in again without encountering the AssertionError.
Deleting the newly registered user also returns the system to normal, eliminating the login issue for existing users.
I am looking for guidance on how to permanently resolve this issue without resorting to restarting the server or deleting new users. Any insights or suggestions would be greatly appreciated.

Thank you for your assistance.

**Comment by pennersr** [comment]
This is truly odd. What kind of customizations did you make using signals and/or adapters? What is the `uid` of the `SocialAccount`? What allauth version are you using?

**Comment by YuchenTOR** [comment]
I'm very grateful for your response!

1. No adapters and signals used
2. The uid of SocialAccount is shown in the following image:
![image](https://github.com/pennersr/django-allauth/assets/134139550/3916bda4-eefa-4a32-b7f3-20e838a18f6f)
3. `SocialAccount, Email addresses, and Users data have been verified for correctness through the Django admin interface.
4. The user model is defined as follows::
```
class myUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('The email must be set')
        email = self.normalize_email(email)
        if 'uid' not in extra_fields or not extra_fields['uid']:
            extra_fields['uid'] = id_generator.next_sid(ItemType.USER)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self.create_user(email, password, **extra_fields)

class myUser(AbstractBaseUser, PermissionsMixin):
    uid = DIDField(unique=True, primary_key=True, default=id_generator.next_sid(ItemType.USER))
    email = models.EmailField(verbose_name='email address', unique=True)
    username = models.CharField(verbose_name="username", max_length=64)
    
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    objects = myUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    class Meta:
        verbose_name = 'user'
        verbose_name_plural = 'users'

    def __str__(self):
        return self.email
```
5. The detailed information about the assertion error is shown in the following image:
![image](https://github.com/pennersr/django-allauth/assets/134139550/30abc74b-7a51-4252-a570-4cda4715bca2)

**Comment by pennersr** [comment]
As a result of the handshake with the social account provider, a social login is instantiated representing the result. It contains all the info on the social account that is in progress of being logged in, but at this stage no lookups have been (should have been) done yet on whether or not that account represents an already existing account. Doing that lookup is not the responsibility of the provider, but of the central socialaccount logic. That is what this assert is about. Now, in your case, that premise seems to be violated -- hence the assert. Other than this, I really don't have much more to go on, so please double check why that is happening, why is `is_existing` True in your case -- set a breakpoint, or try to debug somehow. I'll have to close this -- this is not actionable on this end.

**Comment by jeanfcf** [comment]
I got the same error here

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3679
