### ISSUE TITLE
LOGIN_ON_EMAIL_CONFIRMATION does not work for users created manually eg. via admin

### ISSUE THREAD

**Issue by elnygren** [pennersr/django-allauth#3681]
Because `if signup` will be False in those cases https://github.com/pennersr/django-allauth/blob/0c0dbc2af82601f74547b87b5ca0fcfaef3ae029/allauth/account/utils.py#L361-L362

and https://github.com/pennersr/django-allauth/blob/0c0dbc2af82601f74547b87b5ca0fcfaef3ae029/allauth/account/views.py#L420 can't unstash the user which causes

https://github.com/pennersr/django-allauth/blob/0c0dbc2af82601f74547b87b5ca0fcfaef3ae029/allauth/account/views.py#L424-L425 to never run

**Comment by pennersr** [comment]
Login on confirm requires the user to be created in the same session as the confirmation happens. This is intentional and by design. More info is here:

https://github.com/pennersr/django-allauth/blob/main/allauth/account/views.py#L396

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3681
