### ISSUE TITLE
Signing up new users, facing username duplicate errors (0.61.1)

### ISSUE THREAD

**Issue by TheSudoFox** [pennersr/django-allauth#3690]
When attempting to sign up a new user, I am getting a `ValidationError` as well as a confirmation email: <img width="1102" alt="Screenshot 2024-03-19 at 8 11 25 PM" src="https://github.com/pennersr/django-allauth/assets/7543396/6291bf97-67d7-490c-af68-2b09c537dab6">

Here is the setup:

Adapter:
```
class AccountAdapter(DefaultAccountAdapter):
    def is_open_for_signup(self, request: HttpRequest):
        return getattr(settings, "ACCOUNT_ALLOW_REGISTRATION", True)
```
Form (empty customization):
```
class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """
 ```
 URLs:
 ```
     path(
        "accounts/",
        include("allauth.urls"),
    ),
 ```
 Settings:
 ```
 # django-allauth
# ------------------------------------------------------------------------------
ACCOUNT_ALLOW_REGISTRATION = env.bool("DJANGO_ACCOUNT_ALLOW_REGISTRATION", True)
# https://django-allauth.readthedocs.io/en/latest/configuration.html
ACCOUNT_AUTHENTICATION_METHOD = "username_email"
# https://django-allauth.readthedocs.io/en/latest/configuration.html
ACCOUNT_EMAIL_REQUIRED = True
# https://django-allauth.readthedocs.io/en/latest/configuration.html
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
# https://django-allauth.readthedocs.io/en/latest/configuration.html
ACCOUNT_ADAPTER = "bet.users.adapters.AccountAdapter"
# https://django-allauth.readthedocs.io/en/latest/forms.html
ACCOUNT_FORMS = {"signup": "bet.users.forms.UserSignupForm"}
# https://django-allauth.readthedocs.io/en/latest/configuration.html
SOCIALACCOUNT_ENABLED = False
SOCIALACCOUNT_ADAPTER = "bet.users.adapters.SocialAccountAdapter"
# https://django-allauth.readthedocs.io/en/latest/forms.html
SOCIALACCOUNT_FORMS = {"signup": "bet.users.forms.UserSocialSignupForm"}

SOCIALACCOUNT_PROVIDERS = {
    "twitch": {
        "APP": {
            "client_id": os.environ["TWITCH_CLIENT_ID"],
            "secret": os.environ["TWITCH_CLIENT_SECRET"],
        },
        "SCOPE": ["user_read"],
    },
}
```
 
 I have no customization on my `User` model's save method, nor any signals intercepting pre_save, post_save, etc. signals. I do also have a `UserSocialSignupForm` setup, which suffers a similar issue where I get a Third-Party authentication error (while also getting a confirmation email).
 
 When I override `clean_username()` at the Adapter level, I can see that the user exists by the time my adapter clean runs `filter_users_by_username`, thus springing the ValidationError. I am not sure why the full_clean()/validation is occurring after the object is saved.
 
*Note:* When I override `clean_username()` at the Adapter level and simply return the username, I retrieve two emails nearly simultaneously, as if test_save() found a user and the signup process happened together:
<img width="1216" alt="Screenshot 2024-03-19 at 9 26 11 PM" src="https://github.com/pennersr/django-allauth/assets/7543396/99ad2405-46fd-4a20-975c-25b2e8225577">
 
When I tried to poke into `save_user()` and make sure all the data is there, it looks good and the save seems to work as expected.

I did see some recent changes in these areas of the code, but couldn't suss out if this is a problem on my end somewhere or a bug in django-allauth. Please let me know if any additional information would be helpful, I believe the above is unlikely to immediately duplicate the problem but am not sure what <otherConfig> I am missing that could be impacting the request lifecycle.

**Comment by pennersr** [comment]
Please try and reproduce the issue with vanilla allauth, or try and remove the customizations you have done. I don't think this is an issue in allauth as this is a really basic scenario that is well covered in test cases. It's not feasible for me to see what is going wrong here, e.g. you also have a `UserSocialSignupForm` but I don't see that anywhere.... all in all, this issue is not actionable.

**Comment by TheSudoFox** [comment]
The UserSocialSignUp is also a blank reference to the SocialSignUp form provided by allauth.

I did what I could to pair down the implementation to the point there are no customizations, from the adapter to the form I'm just referencing vanilla implementation.

I'll try to go back through and recreate in a vanilla setup as well.

Have you or anyone seen how one might be messing up in this way?

**Comment by pennersr** [comment]
Alas, no... so unless your source is somewhere out in the open, I really have no clue here, other than I seriously doubt it to be an issue in allauth itself.

**Comment by TheSudoFox** [comment]
Thank you @pennersr for the quick reply and confirmation; I am not trying to unnecessarily pull your time (I just can't for the life of me figure out what I've customized) and will either figure it out or get a docker image on docker-hub that has available source in a vanilla implementation. Thank you!

**Comment by TheSudoFox** [comment]
The only other dependency I can see involved in this core loop is crispy forms, which is helping me render the form in a nice way, I setup the project with `cookiecutter-django` which does setup a rest API/authtoken solution but no 3rd party packages.

```
THIRD_PARTY_APPS = [
    "crispy_forms",
    "crispy_bootstrap5",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.twitch",
    "django_celery_beat",
    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",
    "drf_spectacular",
    "webpack_loader",
    "django_icons",
    "fcm_django",
]
```

Removing those social forms and retrying showed the same problem, sadly. I haven't been able to figure out *why* validation is happening after the object is saved, but I can see it happening right in front of my eyes. 😂

**Comment by TheSudoFox** [comment]
One question I have, if you are taking a look, is that confirmation email likely coming from the adapter/utils? I have been trying to follow that chain of operations and am failing to nail down exactly how I am getting the ValidationError and the confirmation email. (The ValidationError I nailed down to the `clean_username()` method getting run after overriding it/seeing the failure in print statements)

**Comment by TheSudoFox** [comment]
Thanks, I will dig more and post more details here if they seem relevant to others troubleshooting in the future!

**Comment by TheSudoFox** [comment]
In the end, I was able to narrow down the issue to middleware that I didn't expect to be in this request cycle unexpectedly erroring without properly emitting any message (just `pass`'d). This left me in the state described, where signup continued but the page would error out with a ValidationError. I hope this can save someone headache in the future!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3690
