### ISSUE TITLE
Facebook registration with an already-taken email.

### ISSUE THREAD

**Issue by tudorprodan** [pennersr/django-allauth#37]
Consider this:

A user goes to your website, registers a regular account.

Later, he comes back to the website, his session expired, he is no longer logged in. He clicks the Facebook connect button, maybe he forgot that he hasn't used Facebook to log in when he registered.

He gets a signup error.

This is because [`allauth.socialaccount.helpers._process_signup`](https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/helpers.py#L27) clears the `app_settings.auto_signup` flag when auto_signup is enabled and the email is already used.

This is partially correct, since `allauth` cannot just trust the social network to validate the user's email, so it cannot simply associate the oauth ID to the existing account.

But this should instead render a template with:
"This email is already in use, please sign in and click on the Facebook login button again to associate the Facebook account to your <site_name> account."

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/37
