### ISSUE TITLE
Make it easy to override templates by moving them to allauth subdirectory

### ISSUE THREAD

**Issue by owais** [pennersr/django-allauth#370]
Right now the templates sit at root of the templates directory which makes it harder to override some templates.

For example, to override the base.html template, one has to put base.html in projects templates directory but projects might have their own base.html. Some projects might have account subdirectory in templates causing more conflicts.

The solution to this would be to put all the templates under a directory called 'allauth' so base.html will become allauth/base.html.

This way anyone can override any template from allauth very easily.

Django's admin app does exactly this and makes it very easy to override template without causing conflicts with project's or other apps' templates.

**Comment by stavinsky** [comment]
I also had problems and spend 2-3 hours to solve problem. I solved it by changing TEMPLATE_DIRS but I this is no very good way. Templates have to be placed just like django convention said. This is first of tens app that made so much problems just with templates

**Comment by LoveIsGrief** [comment]
I actually ran into similar problems when namespacing allauth urlconfs e.g `url(r'^user/', include('allauth.urls', namespace="auth"))`. allauth couldn't resolve any urls anymore. Maybe that particular issue needs a new separate issue, but it's somewhat linked to this one.

**Comment by craiga** [comment]
For what it's worth, I found that just adding your base application's templates directory to Django's configuration is probably the cleanest workaround for this.

```python
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            "my_cool_app/templates",  # add this with your app name to use your own base.html
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ]
        },
    }
]
```

**Comment by CodePint** [comment]
I've spent the last hour trying to work out the best way of integrating this. I did have to go revisit how the template short circuiting worked as well (new to django)

I would like to propose the following change:
- move `base.html `to `account/base.html`

There seems little point having it in the root level directory and causing confusion with users base.html if it is only ever referenced via `account/base.html` and has been for the past 7 years.

**Comment by ckrybus** [comment]
This issue can be closed, the linked pr has been merged already.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/370
