### ISSUE TITLE
Microsoft provider does not have extract_email_addresses function defined

### ISSUE THREAD

**Issue by akoshegel** [pennersr/django-allauth#3702]
The extract_email_addresses is not defined on the MicrosoftGraphProvider class therefore it uses the one inherited from base Provider that always returns an empty array. It is impossible to accept social logins from Microsoft IdP just by including the provider to the django settings.

Most of the providers implement a default version of the extract_email_addresses. The MicrosoftGraphProvider could also have a default implementation like:

return [EmailAddress(email=data['mail'], verified=True, primary=True)]

**Comment by pennersr** [comment]
Providers do not need `extract_email_addresses()`. It is only need in case there are multiple email addresses involved, or, in order to extract additional attributes such as `verified`. The provider does extract `email` via `extract_common_fields()`.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3702
