### ISSUE TITLE
Password reset from key (email) issue - invalid link - solved

### ISSUE THREAD

**Issue by SGabor111** [pennersr/django-allauth#3708]
Hi,

When requesting password reset I get the email to click the link to reset password. The issue is when I click on the link it gives me the following issue:
The password reset link was invalid, possibly because it has already been used.

However when I copy and paste the link to the browser it works fine.

Does anyone know what is the issue here?
Thanks.

**Comment by SGabor111** [comment]
SESSION_COOKIE_SAMESITE = strict is not good when opening from gmail but with Lax it seems to be working fine

**Comment by SGabor111** [comment]
SESSION_COOKIE_SAMESITE = Lax

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3708
