### ISSUE TITLE
typo in `authentication_required` in headless RESTView

### ISSUE THREAD

**Issue by knowsuchagency** [pennersr/django-allauth#3709]
Thanks for this amazing package -- I'm really excited for the headless version you're working on!

I noticed a slight typo on the branch

```python
class RESTView(View):
    authtentication_required = False
    ...
```

should be...

```python
class RESTView(View):
    authentication_required = False
    ...
```

**Comment by pennersr** [comment]
Thanks for spotting that. That attribute is no longer need, I have it removed locally now (but have yet to push). All is very much in flux still, but getting there...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3709
