### ISSUE TITLE
Closing -- see SOCIALACCOUNT_EMAIL_AUTHENTICATION.

### ISSUE THREAD

**Issue by simkimsia** [pennersr/django-allauth#3713]
Closing -- see SOCIALACCOUNT_EMAIL_AUTHENTICATION.

_Originally posted by @pennersr in https://github.com/pennersr/django-allauth/issues/215#issuecomment-1773169765_
            

I have done search in the code for this and for `SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT`.
            
I think it doesn't work for microsoft graph provider and I am not sure how to check where it went wrong.
            
I have to write my own adapter, which I prefer not to. I modified an adapter I found from 2014 to make it work. https://stackoverflow.com/a/78254683/80353

**Comment by simkimsia** [comment]
I have found out why.

1. To find out how `SOCIALACCOUNT_EMAIL_AUTHENTICATION` is used, I need to search using `EMAIL_AUTHENTICATION` and not include the prefix.

2. at https://github.com/pennersr/django-allauth/blob/d29fd1736019a2f81843f34506250641a606813d/allauth/socialaccount/models.py#L337, the assumption is that the SocialLogin needs the oauth provider to return verified email addresses. So in my case, the Microsoft Graph for the tenant returned email addresses that are unverified. So it didn't proceed. 

I recommend updating the document to make this clear. How do I do that?

**Comment by simkimsia** [comment]
@pennersr  

> "VERIFIED_EMAIL": True

This cannot be done in database config right?

I'm doing this for microsoft graph provider

**Comment by pennersr** [comment]
You can also configure it per app via the app settings. To do so, add `{"verified_email": true}` to the app settings (also works when editting the `SocialApp` via the Django admin).

**Comment by pennersr** [comment]
Closing -- if anybody wants to improve the documentation, feel free to file a PR.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3713
