### ISSUE TITLE
Doesn't support Android Credential Manager for Google login from Android

### ISSUE THREAD

**Issue by ashwanthbalakrishnan5** [pennersr/django-allauth#3724]
When using api's to authenticate andriod app using google login and using Android Credential Manager on the app for authentication. Which will send only the ID token to the server.
But the existing implementation requires auth code or access token from the frontend (i.e. Android app) to authenticate.

**Comment by ashwanthbalakrishnan5** [comment]
This is partly related to dj_rest_auth,
But need changes here too, like fetch user info can't be done using ID token only...

**Comment by pennersr** [comment]
Logging in by ID token is already covered in the upcoming headless allauth functionality. If you haven't seen that yet, please read up here:

https://allauth.org/news/2024/04/api-feedback/

**Comment by ashwanthbalakrishnan5** [comment]
@pennersr,
Sounds Great !!!
Can we have a ETA on the stable release of API's ?

**Comment by pennersr** [comment]
ETA -- see https://github.com/pennersr/django-allauth/issues/360#issuecomment-2043412945

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3724
