### ISSUE TITLE
Does the MFA feature in django-allauth support FIDO passkeys? Or FIDO is simply handled by the chosen provider?

### ISSUE THREAD

**Issue by simkimsia** [pennersr/django-allauth#3726]
I saw this feature https://docs.allauth.org/en/latest/mfa/index.html

but I see that it adopts TOTP.

I wonder if FIDO is supported. Or I am simply mistaken. That FIDO is handled by the chosen provider?

**Comment by pennersr** [comment]
Not yet, but it's coming: https://allauth.org/news/2024/03/ngi-zero-grant-plan/

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3726
