### ISSUE TITLE
Facebook Graph API v14 support

### ISSUE THREAD

**Issue by masb3** [pennersr/django-allauth#3729]
At the moment django-allauth default Facebook Graph API version is v13.0 which will reach end of lifetime on 28 May, 2024. Is it enough to define **v14.0** in `SOCIALACCOUNT_PROVIDERS["facebook"]`?

**Comment by pennersr** [comment]
Yes. The next version of allauth will default to v19.0 (1dc9840d)

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3729
