### ISSUE TITLE
Set password after 3rd party sign up always redirects to change password

### ISSUE THREAD

**Issue by caumons** [pennersr/django-allauth#373]
When a user does a Sign Up using a 3rd party app e.g. Facebook or Linkedin and then try to set a password, he is automatically redirected to change password. Having a look at the source code, this happens if the user has a usable password. I'm now wondering which one is used here? How can a user really set a password after signing up through a 3rd party provider?

Thanks!

**Comment by pythdasch** [comment]
I've the same problem but I don't know how to resolve it. I redirect the user if 
if request.user.password != '!' and not is_password_usable(request.user.password):
        return HttpResponseRedirect(reverse('account_set_password'))

But after I've the page password_change.

How can I redirect the user after account_set_password ?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/373
