### ISSUE TITLE
socialauth provider saml does not log OneLogin_Saml2_Error exceptions

### ISSUE THREAD

**Issue by MichaelMenge** [pennersr/django-allauth#3732]
If a OneLogin_Saml2_Error  is raised in ```ACSView.dispatch``` ```allauth/socialaccount/providers/saml/views.py```   
in ```auth.process_response()``` e.g. because no private key is found ```error_reason``` is set, but not ```errors``` 
and no error is not logged 

also the user is shown a ```AuthError.CANCELLED```  Page.

**Comment by pennersr** [comment]
Fixed via 181b0d6b

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3732
