### ISSUE TITLE
Social provider (Auth0) - not getting user's email address

### ISSUE THREAD

**Issue by benshaji-sequoiaat** [pennersr/django-allauth#3733]
I use Auth0 as IDp. I'm able to login and looks good. But for logged in members, their email attribute is not returned (see below screenshot)

![image](https://github.com/pennersr/django-allauth/assets/111419118/bccb6a52-4ed3-4916-92f1-45263cb35b36)

### What else I did
I've a custom user model (with _email_ field). Therefore, I've added below settings as specified here: https://docs.allauth.org/en/latest/account/advanced.html#custom-user-models

```
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'
```
But whenever a new user logs in afterwards, login endpoint returns `400` status code (screenshot below)

![image](https://github.com/pennersr/django-allauth/assets/111419118/39a19ecd-3742-45c8-957a-2cc869da6a2a)

Because of this issue, I've removed those 4 config lines related to ACCOUNT. The current behavior is, when a new user logs in, a username is created (no email). 

If my understanding is correct, https://github.com/pennersr/django-allauth/blob/105aace58fe767595c61e3a43563af7e1c277797/allauth/socialaccount/providers/auth0/provider.py#L15 this class retrieves the 'email' already? No matter "Sign in with Google or Microsoft", and the account is created,  they can login - but, we cannot see their email in my backend (screenshot). 

What I'm i missing here? Any things to try out?

Thanks

**Comment by benshaji-sequoiaat** [comment]
This issue is resolved.  Assuming you have a custom user model already registered. Make sure below settings are added in SETTINGS as [mentioned here](https://docs.allauth.org/en/latest/account/configuration.html)
```
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = "none"
ACCOUNT_USER_MODEL_EMAIL_FIELD = "email"
```

2) Make sure your Auth URL`scope` includes `email%20openid%20profile&` (email, profile and optionally openid).

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3733
