### ISSUE TITLE
SOCIALACCOUNT_PROVIDER nextcloud ignores settings

### ISSUE THREAD

**Issue by rikmeijer** [pennersr/django-allauth#3734]
I have to manually change the domain (it just uses the default nextcloud.example.org), but after that connecting my nextcloud account still fails. I entered the settings json through the django admin panel, but I don't see any relevant logging.

![image](https://github.com/pennersr/django-allauth/assets/448159/6fec5528-e5da-46c0-a807-e11de9d0781a)

**Comment by pennersr** [comment]
Nextcloud does not support configurable settings via the database, yet. It currently uses this:

``` python
class NextCloudOAuth2Adapter(OAuth2Adapter):
    provider_id = "nextcloud"
    settings = app_settings.PROVIDERS.get(provider_id, {})
    server = settings.get("SERVER", "https://nextcloud.example.org")
```

**Comment by rikmeijer** [comment]
How do I configure that?? I am using paperlessOp 19 apr 2024 16:59 schreef Raymond Penners ***@***.***>:
Nextcloud does not support configurable settings via the database, yet. It currently uses this:
class NextCloudOAuth2Adapter(OAuth2Adapter):
    provider_id = "nextcloud"
    settings = app_settings.PROVIDERS.get(provider_id, {})
    server = settings.get("SERVER", "https://nextcloud.example.org")

**Comment by pennersr** [comment]
That's documented here: https://docs.allauth.org/en/latest/socialaccount/providers/nextcloud.html

**Comment by rikmeijer** [comment]
Ok, but where (file, env var, ??? do I put thatOp 19 apr 2024 17:13 schreef Raymond Penners ***@***.***>:
That's documented here: https://docs.allauth.org/en/latest/socialaccount/providers/nextcloud.html

**Comment by pennersr** [comment]
The snippet from the documentation points to the Django `settings.py`.

**Comment by pennersr** [comment]
Fixed via 0fa9090f

**Comment by pennersr** [comment]
@rikmeijer No need to update -- the changes are backwards compatible.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3734
