### ISSUE TITLE
linkedin_oauth2

### ISSUE THREAD

**Issue by actiotec** [pennersr/django-allauth#3735]
Hi, 

I have an issue with linked for which I can't get much more info except the default html page of allauth saying : 
Third-Party Login Failure
An error occurred while attempting to login via your third-party account.

my configuration:
```
INSTALLED_APPS: 'allauth.socialaccount.providers.linkedin_oauth2',
SOCIALACCOUNTS_PROVIDERS:
'linkedin_oauth2': {
        'SCOPE': [
            'profile',
            'email'
        ],
        'PROFILE_FIELDS': [
            'id',
            'first-name',
            'last-name',
            'email-address',
            'picture-url',
            'public-profile-url',
        ],
        'REDIRECT_URI': 'http://localhost:8000/accounts/linkedin_oauth2/login/callback/',
    }
```

And in my admin console I added my keys for linkedin provider and put the following id: **linkedin_oauth2**

Now I'm able to login on Linkedin, it redirects me to the correct REDIRECT_URL with a session id and a code 200 but then nothing happen except the default allauth error page for login with 3rd party as stated at the beginning of this message.

Any clue?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3735
