### ISSUE TITLE
Github verified email does not seem to work

### ISSUE THREAD

**Issue by shughes-uk** [pennersr/django-allauth#3745]
I was trying to figure out why Github user emails were not being verified, but it looks like the provider isn't set up for it.

https://github.com/pennersr/django-allauth/blob/1a4ee1d5b3b61f2e97d2e862ccecd47509022a3e/allauth/socialaccount/providers/github/views.py#L37C1-L56C21

The github email api does return the verification status in the call that is already being made. As far as I can tell, just checking that response and adding `verified_email` to the `extra_data` payload used by `complete_login` should be enough to get things working.

I'd be happy to make a PR if it's welcome.

**Comment by pennersr** [comment]
Correct. GitHub also returns a list of email addresses, so we should parse all of those and not just the first one -- which may not even be the primary one. So we need to extract all emails and their properties (`extract_email_addresses`). PR is welcome!

**Comment by pennersr** [comment]
Fixed via bc9fa026

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3745
