### ISSUE TITLE
Option to allow one-time password login for old users when using SOCIALACCOUNT_ONLY

### ISSUE THREAD

**Issue by riconnon** [pennersr/django-allauth#3746]
One of my sites would like to migrate to allowing login only using social accounts, but has existing users with passwords.

I think it would be good to have a configuration with the concept of a "legacy password login" option which allows users to authenticate with their password, then migrate to a social account.

I'd be happy to look at doing the work for this, but wanted to raise an issue to see if there was appetite to accept this before I do.

**Comment by pennersr** [comment]
I don't think it makes sense to bring this into scope. it is more of a policy related feature, and there are various ways you can implement nudging users to move over -- so it is a bit beyond the scope, and there is no one de facto way of implementing this.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3746
