### ISSUE TITLE
local signup for existing social user

### ISSUE THREAD

**Issue by tunavargi** [pennersr/django-allauth#375]
I created a facebook user with account "foo" and account email "foo@foomail.com". Then I want to register a local user with same mail address, when I am doing this I want to connect facebook account to my local user. Is there a way to do this ? First create the social account and then signup as a local user with that social_accounts email address. 

When I do this. I get the error ´this email is already registered´

Thanks

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/375
