### ISSUE TITLE
headless api documentation

### ISSUE THREAD

**Issue by knowsuchagency** [pennersr/django-allauth#3750]
Thanks so much for your work on the headless API!

The OpenAPI/Swagger documentation -- is that something you're generating manually?

I don't see that it's automatically added an endpoint via https://github.com/pennersr/django-allauth/blob/feat-headless/allauth/headless/urls.py

A thought -- I've found django-ninja (https://django-ninja.dev/) to be outstanding for API routes. It makes it straightforward to add additional routes -- one relevant example being https://github.com/eadwinCode/django-ninja-jwt

I understand the drawbacks of introducing a third-party dependency, but I feel it's sufficiently popular and battle-tested and would be a great way to ensure the routes are automatically documented via swagger with proper controls.

A quick example of how I often use it:

```python
from django.contrib.admin.views.decorators import staff_member_required

from ninja import NinjaAPI, Router
from ninja.security import django_auth
from ninja_jwt.authentication import JWTAuth
from ninja_jwt.routers.obtain import obtain_pair_router
from ninja_jwt.routers.verify import verify_router

from my_app.settings import DEBUG


auth = [JWTAuth(), django_auth]

api = NinjaAPI(
    title="My App",
    auth=auth,
    # I do this to prevent the OpenAPI documentation being shown in prod
    docs_url="/docs" if DEBUG else None,
    # probably overkill given the above, but I do it anyway
    docs_decorator=staff_member_required,
)

v1 = Router()

api.add_router("/v1", v1)

api.add_router(
    "/token",
    tags=["Auth"],
    router=obtain_pair_router,
)
api.add_router(
    "/token",
    tags=["Auth"],
    router=verify_router,
)

@v1.get("/get_thing")
def get_thing(request):
    ...

@v1.post("/post_thing")
def post_thing(request, thing: str):
    ...
```

**Comment by knowsuchagency** [comment]
I also saw this in the documentation:

```python
# These are the URLs to be implemented by your single-page application.
HEADLESS_FRONTEND_URLS = {
    "account_confirm_email": "https://app.project.org/account/verify-email/{key}",
    "account_reset_password_from_key": "https://app.org/account/password/reset/key/{key}",
    "account_signup": "https://app.org/account/signup",
}
```

What does configuring `HEADLESS_FRONTEND_URLS` do? What happens if it's missing?

**Comment by pennersr** [comment]
> The OpenAPI/Swagger documentation -- is that something you're generating manually?

Yes. What's important is that there is a valid OpenAPI spec, the way in which it is generated should not matter to consumers of the API.

> Ninja sufficiently popular and battle-tested 

But so is DRF. It's simply not an option to pick a side in this debate. The headless API should work with whatever API framework you are using, and not favor one above the other. 

> HEADLESS_FRONTEND_URLS

That is documented here:

https://github.com/pennersr/django-allauth/blob/feat-headless/docs/headless/configuration.rst

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3750
