### ISSUE TITLE
Microsoft Login (Social Account)

### ISSUE THREAD

**Issue by muazshahid** [pennersr/django-allauth#3751]
I updated from allauth 0.58.2 to the latest 0.62.0, my microsoft social account providor login was working correctly but it stopped working after the update, my social login button does not show up anymore on my login page after the update, I compared the provider.py in both versions and it has some changes like the oauth2_adapter_class,

allauth 0.62.0 has:
```
class MicrosoftGraphProvider(OAuth2Provider):
    id = "microsoft"
    name = "Microsoft"
    account_class = MicrosoftGraphAccount
    oauth2_adapter_class = MicrosoftGraphOAuth2Adapter
```

allauth 0.58.2 had:

```
class MicrosoftGraphProvider(OAuth2Provider):
    id = str("microsoft")
    name = "Microsoft Graph"
    account_class = MicrosoftGraphAccount

```
I wasn't sure if this makes a difference because I am not an expert with django, here are some details about my settings.

The settings in my app are like this :
```
SOCIALACCOUNT_PROVIDERS = {
                           'microsoft': {'VERIFIED_EMAIL': True, 'email_authentication': True,
                                         'TENANT': 'organizations', }}
```

The settings for the provider in my admin panel:
![image](https://github.com/pennersr/django-allauth/assets/65394988/e7fc64ae-be5b-47f7-a2ce-f7afd7f1e8ab)

Microsoft App setup:
![image](https://github.com/pennersr/django-allauth/assets/65394988/60419abc-b58d-4a31-84c0-b0a7fe1a7ec7)

I hope this is enough information, resolution will be greatly appreciated.

**Comment by muazshahid** [comment]
Fixed issue, the provider name has been updated from **"Microsoft Graph"** to **"Microsoft"** in provider.py allauth 0.62.0, I was referencing to the provider using "Microsoft Graph" which my template wasn't able to find and hence the issue of not seeing the button. 
Feeling dumb now, but I hope it proves helpful for someone else.

**Comment by muazshahid** [comment]
Fixed issue, the provider name has been updated from **"Microsoft Graph"** to **"Microsoft"** in provider.py allauth 0.62.0, I was referencing to the provider using "Microsoft Graph" which my template wasn't able to find and hence the issue of not seeing the button. 
Feeling dumb now, but I hope it proves helpful for someone else.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3751
