### ISSUE TITLE
admin confirmation after email confirmation

### ISSUE THREAD

**Issue by vdejager** [pennersr/django-allauth#3753]
I'm not sure if I missed something in the docs but currently there does not seem to be a way to block a user sign-in until an administrator also verified the account request.

This is discussed in : https://forum.djangoproject.com/t/allauth-customization-to-not-set-user-active-and-trigger-email-with-signal-email-confirmed/12726/6

The current workflow is:

1. user sign up
2. user is redirected to the email confirmation page
3. user confirms the email
4. user can login immediately

The workflow I would like to be able to follow is:
1. user sign up
2. user is redirected to the email confirmation page
3. user confirms the email
4. user is redirected to a page explaining admin should activate the account
5. admin makes the account active
6. user can login

I tried to make the account inactive in a custom signup adapter
```
from allauth.account.adapter import DefaultAccountAdapter

class AccountAdapter(DefaultAccountAdapter):

    def save_user(self,request,user, form,commit=True):
        # get the user from super save
        user = super().save_user(request, user, form,commit)
        user.is_active = False
        # make sure you save
        user.save()
        return user 
```

but this results in the signed-up user not being redirected to the email confirmation page but to the 'account inactive' page

comments in https://github.com/pennersr/django-allauth/blob/85fd652ca28aee8f5fa7aca791869d06ef826bc4/allauth/account/views.py#L256
suggest setting is_active=False on signup should do the job, but this seems to mess up the confirmation workflow

Any ideas to solve this without new functionality are welcome

**Comment by pennersr** [comment]
You could  listen to the email confirmed signal, and set `is_active = False` there. Though, be sure to only set that in case the account is a new one -- it might be that an already approved user verifies a secondary email address, in that case you don't want to toggle `is_active`.

**Comment by vdejager** [comment]
Clear, but is there any reason why the email confirmation is not send if the user 'is_active' is False? upon creation?

**Comment by pennersr** [comment]
The `is_active` field is not meant for what you are using it for, at the very least its semantics are fuzzy. I've seen people use it for the purposes you describe, but also for blocking bad behaving users. Django documents it as:

https://docs.djangoproject.com/en/5.0/ref/contrib/auth/: "We recommend that you set this flag to False instead of deleting accounts. That way, if your applications have any foreign keys to users, the foreign keys won’t break."

allauth uses the above semantics -- a deleted account is not supposed to perform any actions.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3753
