### ISSUE TITLE
typo in comments 'cocunt' plugin

### ISSUE THREAD

**Issue by Agamenox** [pennersr/django-allauth#3766]
in docs/installation/quickstart.rst on line 52 a typo needs to be corrected:
`        # Optional -- requires install using `django-allauth[socialacocunt]`.`
needs to be changed [socialacocunt] by [socialaccount] in comment:
`        # Optional -- requires install using `django-allauth[socialaccount]`.`
 
![image](https://github.com/pennersr/django-allauth/assets/8619960/c7569572-fb62-4738-af99-46696dd8d7d6)

**Comment by pennersr** [comment]
Closed via 2e37568c

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3766
