### ISSUE TITLE
sociallogin.is_existing fails if existing user associated in adapter.new_user

### ISSUE THREAD

**Issue by banagale** [pennersr/django-allauth#3769]
In a project I work on users can only sign up if they have been invited.

Our invite flow creates an `Invite` object and a related `CustomUser` with a non-usable password.

I want these users to get hooked up to social login, and took direction from #561 on overriding our custom social account adapter's `new_user` method.

However, in #3446, @pennersr [mentions](https://github.com/pennersr/django-allauth/issues/3446#issuecomment-1731957497):

>So, that means that somehow a real user is already attached to the sociallogin, which should not be possible at this point. 

This seems in conflict based on the logic flow:

* The failing assert of `sociallogin.is_existing` in `FinishACSView` when `complete_social_login` is called.
* However, `new_user()` is part of `ACSView`, when it stores `login`:
   ```
   login = provider.sociallogin_from_response(request, auth)
   ```
* And that view, if successful, leads directly into `FinishACSView`.  

### Questions
* Has the method for linking up an existing user account with a social login changed?
* If a real user should not be attached at the time `FinishACSView` runs, when should it be attached?

**Comment by banagale** [comment]
I wanted to add that our social app, the only one we're supporting is SAML. 

I see that #3997 resulted in  `SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECTS` getting added, which seems like perhaps the intent now is to use this to perform the connection I'm doing in `new_user`?

**Comment by pennersr** [comment]
`new_user()` is instantiating a new/blank `User` instance. it is supposed to be unsaved -- there shouldn't be any `user.pk` set.

> Has the method for linking up an existing user account with a social login changed?

No

> If a real user should not be attached at the time FinishACSView runs, when should it be attached?

The `adapter.pre_social_login()` would be a good place. At this point, allauth ran all its logic, and it is clear whether or not the social account and/or the user are known.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3769
