### ISSUE TITLE
Better template tags and files

### ISSUE THREAD

**Issue by paulocoutinhox** [pennersr/django-allauth#3771]
Hi,

Thanks for this plugin.

1 - Email list management:

Can you extract email list to a new template or put it inside some elements like providers to we customize the list?

Today is hard manage the list elements and button over it. Example:

<img width="1158" alt="image" src="https://github.com/pennersr/django-allauth/assets/395096/c8332bcb-d0e6-4ed6-8097-7bbf89234877">

2 - Can you extract subtitles to an element to we customize the subtitles elements?

Today it is a simple "P" element. Examples:

<img width="727" alt="image" src="https://github.com/pennersr/django-allauth/assets/395096/446176a6-0caa-4694-afd0-20bca05527b5">

and:

<img width="1289" alt="image" src="https://github.com/pennersr/django-allauth/assets/395096/41426be8-63fe-4b91-9682-7539016f22f3">

3 - A panel/form container to we understand what block we need customize.

For example, i want centralize all element when form/panel/container is about login. Example:

<img width="1704" alt="image" src="https://github.com/pennersr/django-allauth/assets/395096/e4d26a50-30ba-4f23-8ebe-1dcdb1ea3ce4">

4 - Obs

I know that we can customize all the forms/templates inside account folder. But what i suggest is extract somethings to elements with tags to we dont need override allauth templates but only the elements. It will make things always, updated.

Thanks.

**Comment by pennersr** [comment]
1) This point is not fully clear to me, can you make this a bit more specific?

2) Would this be addressed by adding a `p.html` template and turning all `<p>` into `{% element p %}` ?

3) The login form uses:

```{% element form form=form method="post" action=login_url tags="entrance,login" %}```

Note the `login` tag. You could detect that tag in the `form.html` element and add classes as you see fit. Would that work?

**Comment by paulocoutinhox** [comment]
Thanks for these things.

You will generate a new version?

Thanks man.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3771
