### ISSUE TITLE
 Deprecated signature algorithm SAML

### ISSUE THREAD

**Issue by tchenevi** [pennersr/django-allauth#3772]
Hi,

I'm using allauth to login with SAML. The IDP I want to connect to is using an old signature algorithm and I get the error : Deprecated signature algorithm found: http://www.w3.org/2000/09/xmldsig#rsa-sha1

Is there a way to widen the range of accepted Signature algorithms in the settings file or elsewhere ?

Thanks !

**Comment by pennersr** [comment]
Can you try setting this?:

```
{"idp": {...},
 "advanced": {"reject_deprecated_algorithm": False, ...},
```

**Comment by tchenevi** [comment]
It worked perfectly 
Thanks !

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3772
