### ISSUE TITLE
Account provider not listed/visible

### ISSUE THREAD

**Issue by theabraxas** [pennersr/django-allauth#3773]
I have an issue where, when going to the login/sign-in page and seeing the 'or use a third-part' section, a provider is not listed. Specifically, no matter what I do, I cannot get google to show up. I've simplified my settings to show what's up and hopefully find what's wrong.

Here's the account providers config from my base.py:
```
SOCIALACCOUNT_PROVIDERS = {
    'discord': {
        'APP': {
            'client_id': SOCIAL_AUTH_DISCORD_KEY,
            'secret': SOCIAL_AUTH_DISCORD_SECRET,
        }
    },
    'google': {
        'APP': {
            'client_id': SOCIAL_AUTH_GOOGLE_OAUTH2_KEY,
            'key': SOCIAL_AUTH_GOOGLE_OAUTH2_KEY,
            'secret': SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET
        },
    }
}
```

Further, though I'm not sure it matters, here are the only other allauth settings:
```
# AllAuth Settings
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_AUTHENTICATION_METHOD = "username_email"
ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = True
SITE_ID = 1 # Required for AllAuth
```

Here are my INSTALL_APPS lines which are relevant:
```
    # AllAuth components
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',   
    'allauth.socialaccount.providers.discord',
```

Visually, this is what I see:
![image](https://github.com/pennersr/django-allauth/assets/6147260/ccb55f79-6cfa-4ca5-841e-a580a288e973)

Further, this is the view from the admin page when trying to add an application:
![image](https://github.com/pennersr/django-allauth/assets/6147260/42c1f9ab-0d47-4752-8087-367b8ac316c3)
If I add facebook, gitlab, and others they show up on the dropdown but for some reason Google does not.

I am at a loss and would appreciate any ideas/insight! Thanks!

**Comment by pennersr** [comment]
Did you install using `pip install django-allauth[socialaccount]` ?

**Comment by pennersr** [comment]
See https://github.com/pennersr/django-allauth/issues/3775#issuecomment-2084776523

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3773
