### ISSUE TITLE
django-allauth doesn't cater for app-only access yes?

### ISSUE THREAD

**Issue by simkimsia** [pennersr/django-allauth#3777]
for microsoft graph, there are two kinds of access scenarios

https://learn.microsoft.com/en-us/graph/auth/auth-concepts#access-scenarios

![image](https://github.com/pennersr/django-allauth/assets/245021/1fd3a63d-e12e-4d23-a0e6-a3b6b4d5f2cf)

django-allauth helps with the `Delegated access`, which is the  app acting on behalf of a signed-in user.

because the access token is stored in socialtoken

but I assume that django-allauth doesn't help with app-only access yes?

**Comment by pennersr** [comment]
The scope of allauth is user authentication. Anything else, such as e.g. the machine-to-machine client credentials flow is out of scope.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3777
