### ISSUE TITLE
socialaccount/adapter.py  get_app trhows MultipleObjectsReturned exception if more than one saml provider is configured

### ISSUE THREAD

**Issue by MichaelMenge** [pennersr/django-allauth#3779]
I tried to configure multiple saml provider (see #3749)

as i tried to implement my own SocialAccountAdapter, i received an MultipleObjectsReturned exception

>>>
<h1>MultipleObjectsReturned
       at /accounts/login/</h1>
  <pre class="exception_value">No exception message supplied</pre>
  
Request Method: | GET
-- | --
https://listservtest.v274.uni-tuebingen.de/accounts/login/?next=/mailman3/
4.2.11
MultipleObjectsReturned
/opt/mailman/venv/lib64/python3.9/site-packages/allauth/socialaccount/adapter.py, line 301, in get_app
allauth.account.views.LoginView
/opt/mailman/venv/bin/python3
3.9.18
['/opt/mailman/mm',  '/',  '/opt/mailman/venv/bin',  '/etc/mailman3',  '/usr/lib64/python39.zip',  '/usr/lib64/python3.9',  '/usr/lib64/python3.9/lib-dynload',  '/opt/mailman/venv/lib64/python3.9/site-packages',  '/opt/mailman/venv/lib/python3.9/site-packages',  '/etc/mailman3']
Fri, 03 May 2024 15:30:45 +0000
>>>

I was able to reproduce the same exception without my SocialAccountAdapter and a striped down configuration of two 
saml providers in the settings.py 

```
SOCIALACCOUNT_PROVIDERS 	= 
    {'saml': {'APPS': [{'client_id': 'uni-tue',
                    'name': 'Uni Tuebingen IdP',
                    'provider_id': 'https://idp.uni-tuebingen.de/shibboleth',
                    'settings': {'idp': {'entity_id': 'https://idp.uni-tuebingen.de/idp/shibboleth',
                                         'metadata_url': 'https://www.aai.dfn.de/metadata/dfn-aai-idp-metadata.xml'},
                                 'sp': {'entity_id': 'https://listserv.uni-tuebingen.de/shibboleth'}}},
                   {'client_id': 'uni-tue-test',
                    'name': 'Uni Tuebingen Test-IdP',
                    'provider_id': 'https://www.aai.dfn.de/metadata/dfn-aai-test-metadata.xml',
                    'settings': {'idp': {'entity_id': 'https://idp-test.uni-tuebingen.de/idp/shibboleth',
                                         'metadata_url': 'file:///etc/mailman3/dfn-aai-test-metadata.xml'},
                                 'sp': {'entity_id': 'https://listserv.uni-tuebingen.de/shibboleth'}}}],
          'EMAIL_AUTHENTICATION': True,
          'EMAIL_VERIFICATION': 'none',
          'VERIFIED_EMAIL': True}}
```

**Comment by pennersr** [comment]
```
adapter.py, line 301, in get_app
```

Given that line number, I suspect you are running an outdated allauth version. Can you first try upgrading?

**Comment by pennersr** [comment]
You get this error just by doing a GET to the login view? If I copy your config into the example project, that just works for me:

![image](https://github.com/pennersr/django-allauth/assets/201022/0c64999f-4838-48df-a093-5c7bbf573676)

**Comment by MichaelMenge** [comment]
I used it with mailman3 
![Mailman3-MultipleObjectsReturned](https://github.com/pennersr/django-allauth/assets/33626518/08b8afa9-853e-48a6-9872-bf727a6a819f)

**Comment by pennersr** [comment]
Yes, that template is wrong. It is passing `provider.id` to `{% provider_login_url %}`. The `id` is `saml` in both cases, so trying to lookup the app later on results in an ambiguity, hence the error.  Instead, it should pass the `provider` as is:

```
{% provider_login_url provider process=... %}
```

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3779
