### ISSUE TITLE
Typo in checks for SOCIALACCOUNT_ONLY

### ISSUE THREAD

**Issue by lancetarn** [pennersr/django-allauth#3782]
First, thank you for maintaining this project. Wow.

It looks like the suggestion in

https://github.com/pennersr/django-allauth/blob/main/allauth/account/checks.py#L24

references `ACCOUNT_EMAIL_VERIFICATION_METHOD`, but I think we are really just after `ACCOUNT_EMAIL_VERIFICATION`

I'll make a quick PR if that helps.

https://github.com/pennersr/django-allauth/pull/3781

**Comment by pennersr** [comment]
Merged, thanks!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3782
