### ISSUE TITLE
How to prevent django.db.utils.IntegrityError for duplicate social login email?

### ISSUE THREAD

**Issue by quroom** [pennersr/django-allauth#3790]
```
django.db.utils.IntegrityError: duplicate key value violates unique constraint "account_emailaddress_email_key"
```
I get this error when I login same only email with another SocialLogin
(like facebook and google email can be duplicate)

```
ACCOUNT_UNIQUE_EMAIL = False
ACCOUNT_PREVENT_ENUMERATION = False
```

So I added this option but error still comes
email field is actually not unique.
I am usnig username as unique field for user.

And I haev one more question.
As long as email is not unique, could we create socialaccount has same email?
Or Can we make socialaccount with same user account?

I am not sure how I can implement. It's little bit complext to be because my env has nuxt frontend and django backend. It makes more complext.

**Comment by quroom** [comment]
I already migrated djang-allauth and then I changed ACCOUNT_UNIQUE_EMAIL to False
That's why error comes. Then do I need to make another migration file in my app?

**Comment by pennersr** [comment]
If you signup with a social account that has an email address that already exists locally, you are asked to enter a new email address. Not sure why this is not working for you. Are you using plain allauth? Can you reproduce this using the example project, or, the online demo? Are you on the latest version?

**Comment by quroom** [comment]
> If you signup with a social account that has an email address that already exists locally, you are asked to enter a new email address. Not sure why this is not working for you. Are you using plain allauth? Can you reproduce this using the example project, or, the online demo? Are you on the latest version?

I don't use latest version. I will make small example and test when I have time :)
Thanks for quick answer 👍

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3790
