### ISSUE TITLE
Unable to understand how to authenticate SOCIALACCOUNT_ONLY flag as True

### ISSUE THREAD

**Issue by iotheo** [pennersr/django-allauth#3792]
I tried to investigate on this new feature as I need it for the current project I'm developing, with the sole purpose to authenticate only with a third party provider, but whenever I set it to `True` and am trying to login (via `/accounts/login`) I get the following error:

```
Reverse for 'account_signup' not found. 'account_signup' is not a valid view function or pattern name.
```

I am not sure about the intent behind it, but checking from the related feature PR, it seems that this reverse among others is deliberately excluded when that flag is set to `True`.

At this point, I am uncertain as to what needs to be done in order to proceed in a third party auth only experience. 

I kindly ask you to assist me on that 🙏

**Comment by pennersr** [comment]
When `SOCIALACCOUNT_ONLY` is turned on, the regular account views are turned off. You can no longer signup for a local account, hence, the `account_signup` view is no longer included in `urls.py`. If you try to reverse it, it will indeed not be found. Where is that reverse happening, in one of your own templates? The allauth templates should gracefully handle the case where `account_signup` is not present..

**Comment by pennersr** [comment]
> Where is that reverse happening, in one of your own templates?

Please have a look into the above question.

FWIW -- allauth uses:

```
                        {% url 'account_signup' as signup_url %}
                        {% if signup_url %}
                            <li>
                                <a href="{{ signup_url }}">{% trans "Sign Up" %}</a>
                            </li>
                        {% endif %}
```

... which gracefully handles `account_signup` being absent. I assume that it is not working for you because you are using custom templates -- so simply do not reverse the signup page.

**Comment by iotheo** [comment]
Apologies for the confusion.

The snippet below contains the only custom template I am currently using.

As far as I understand I'm not directly using that reverse, unless am doing it naively.

```
{% load socialaccount %}

{% get_providers as socialaccount_providers %}
{{ socialaccount_providers }}


<a href="{% provider_login_url "google" %}">Login with Google</a>

{% if user.is_authenticated %}
    I am authenticated
    <a href="{% url 'account_logout' %}">Logout</a>
{% endif %}

**Comment by pennersr** [comment]
The only way to solve this is to find out where this reverse...

```
Reverse for 'account_signup' not found.
```
...is happening. Is it in a template, a view... can you share the full trace?

**Comment by iotheo** [comment]
Getting back to you, I noticed that even though I am using `0.62.1` version of `allauth`, it seems I'm getting an outdated version of what has been implemented in the `allauth/templates/allauth/layouts/base.html`

Made sure that everything is up to date by force reinstalling all the dependencies. My `base.html` deviates from what's supposed to be there.

```
{% load i18n %}
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>
            {% block head_title %}
            {% endblock head_title %}
        </title>
        {% block extra_head %}
        {% endblock extra_head %}
    </head>
    <body>
        {% block body %}
            {% if messages %}
                <div>
                    <strong>{% trans "Messages:" %}</strong>
                    <ul>
                        {% for message in messages %}<li>{{ message }}</li>{% endfor %}
                    </ul>
                </div>
            {% endif %}
            <div>
                <strong>{% trans "Menu:" %}</strong>
                <ul>
                    {% if user.is_authenticated %}
                        <li>
                            <a href="{% url 'account_email' %}">{% trans "Change Email" %}</a>
                        </li>
                        <li>
                            <a href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
                        </li>
                    {% else %}
                        <li>
                            <a href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
                        </li>
                        <li>
                            <a href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
            {% block content %}
            {% endblock content %}
        {% endblock body %}
        {% block extra_body %}
        {% endblock extra_body %}
    </body>
</html>```


More specifically, I reckon what causes the trouble is:

```
 {% else %}
      <li>
          <a href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
      </li>
      <li>
          <a href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
      </li>
  {% endif %}
```

Any ideas?

**Comment by pennersr** [comment]
My bad -- I am afraid that the behavior I am referring to is on the main branch but not yet on 0.62.x. It happened in this commit:

92b47ae2

So, what you are running into is an issue in the base templates of allauth, that is already fixed, but not released. You can simply copy that base template from the main branch -- or better yet, you will likely want to style that anyway, write a new base template of your own without doing the reverse.

**Comment by iotheo** [comment]
I appreciate your patience and your thorough explanation. You've done a great job so far 👏

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3792
