### ISSUE TITLE
Feature Request: Login using Phonenumber with OTP

### ISSUE THREAD

**Issue by ashwanthbalakrishnan5** [pennersr/django-allauth#3796]
Hi @pennersr,
What is your thought on this ?

**Comment by ashwanthbalakrishnan5** [comment]
Hi @pennersr,
Was thinking of a feature like this <https://github.com/CuriousLearner/django-phone-verify> 
Docs @ <https://www.sanyamkhurana.com/django-phone-verify/>
Looking forward on contributing to this

Can include support for sms gateway services like Twilio, AWS SNS,...

**Comment by devraj** [comment]
@pennersr our company would consider sponsoring this feature, could I email you to discuss?

**Comment by pennersr** [comment]
@devraj Of course -- see: https://github.com/pennersr/django-allauth?tab=readme-ov-file#commercial-support

**Comment by ashwanthbalakrishnan5** [comment]
@devraj and @pennersr any update on this feature.

@pennersr if you can provide a high level overview of how you expect it to be. I'll start working on it

**Comment by boosh** [comment]
It'd be great to also support sms validation here too (which I guess would be a prerequisite anyway). 

I've seen in #1426 saying to build this on top of twilio, and having just spent the last 2 days doing just that it's something I never want to repeat. My use case was validating user phone numbers as another factor to reduce abuse in my app.

**Comment by fatihkabakk** [comment]
I am looking forward to see this feature available, too.

**Comment by devraj** [comment]
> @devraj and @pennersr any update on this feature.
> 
> @pennersr if you can provide a high level overview of how you expect it to be. I'll start working on it

My apologies for not having spotted this comment. I will get int touch with @pennersr and move this forward from our point of view. There were some delays on the commercial project we were involved in which slowed down our decision making process.

**Comment by pennersr** [comment]
Moved to https://codeberg.org/allauth/django-allauth/issues/3796
