### ISSUE TITLE
/accounts/profile/ redirection 404 after facebook login 

### ISSUE THREAD

**Issue by nkeilar** [pennersr/django-allauth#38]
Upon signing up using facebook on the accounts/signup page the redirection fails with a 404. I've been digging through the source but its not clear to me how to override this with a redirection to a custom page. 
# 

As a separate note, I'm intergrating the allauth with lazysignup and am not sure of the best way to proceed. Lazysignup has already created a user on the database using a django sessons framework , thus my user in no longer 'anonymous'. Lazysignup provides a 'convert' view to take username, password, etc, and update the current lazyuser account (i.e. not create a new one). What would be the best way to enable social conversion of a lazyuser account? So that at the end of the survey, the user can link their results by existing user id to a social account. Any suggestions appreciated.

**Comment by okwow123** [comment]
oh guys... pitiful guys...
I also have problem with same things.
I think you probably have been seen youtube.
https://www.youtube.com/watch?v=1yqKNQ3ogKQ
or not... whatever...
Please get out of the facebook developer page!!!.
 AND restart the django server.
this is definitely bug... It is not related to django redirect page. DON'T change the settings.py,url.py....
TRUST ME

**Comment by ishanSrt** [comment]
@okwow123 still does not work

**Comment by ishanSrt** [comment]
sorry for that, actually i was using dashlane which automatically logged me in everytime

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/38
