### ISSUE TITLE
A little bug on password_reset_key_message.txt (email reset)

### ISSUE THREAD

**Issue by azuax** [pennersr/django-allauth#380]
Hi,

There's a small bug on the code of:
allauth/templates/account/email/password_reset_key_message.txt

On the line 6, it calls {{ username }}  but the variable is "user" so it must be:

{{ user.username }}

I hope it helps. 
Azuax

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/380
