### ISSUE TITLE
BLOCKER:Slack OIDC scopes.

### ISSUE THREAD

**Issue by abdawwa1** [pennersr/django-allauth#3806]
Hello folks, i'm new here i was testing django-allauth for a project i'm building and face an issue when trying to use Slack provider to login with as 3rd party login after some debugging i noticed that you have update `access_token_url` , `authorize_url` and `identity_url` but the `get_default_scope` for Slack provider didn't get updated.

After reading slack docs the OpenID scope should be changed to the following values `openid` , `email` and `profile`.

Also i've tested it and it worked like a charm , the current scope is set to `["identify"]`.

I've cloned the repository and made the change but i can't push my branch and open PR .

Slack docs reference : https://api.slack.com/authentication/sign-in-with-slack.

**Comment by pennersr** [comment]
Fixed via a52fb875

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3806
