### ISSUE TITLE
Logic question: connect process

### ISSUE THREAD

**Issue by jonasN5** [pennersr/django-allauth#3810]
Let's assume I'm trying to connect a Twitch account. When calling `complete_social_login`, let's assume `_lookup_by_email` found a matching email. Now I would assume that a new twitch social account gets created and connected, but https://github.com/pennersr/django-allauth/blob/main/allauth/socialaccount/internal/flows/connect.py#L107 this line is not called since just above, `sociallogin.is_existing` is `True`.
I'm probably misunderstanding something here, but I don't see what. It seems to me that `is_existing` here has a loophole in its flow, because `_lookup_by_email` will make it return `True` and thus prevent the new `SocialAccount` object from being created, even though it doesn't exist.

**Comment by pennersr** [comment]
See: `SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT`

**Comment by jonasN5** [comment]
Yes, I also have that option set to `True`. However, if `process == AuthProcess.CONNECT`, then `flows.login._authenticate` and `flows.login._login` are not called, so `SocialLogin._accept_login` is not called either.

**Comment by pennersr** [comment]
I see what you mean -- I will check the flows.

**Comment by pennersr** [comment]
Fixed via 9731a416

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3810
