### ISSUE TITLE
SAML settings

### ISSUE THREAD

**Issue by zgurea1** [pennersr/django-allauth#3811]
Hello, i am trying to add some security features to SAML auth, but i think the configs are reacting to changes that i made. I need to add the private key and specify the SigAlg to crypt the AuthRequest, and i don't find anywhere in documentation how to do it.

This is what i get
![image](https://github.com/pennersr/django-allauth/assets/60965273/70a8bb1c-b4ad-45c9-a6ce-d71cac8d254f)

This is what i need to get(its from another saml integration https://github.com/node-saml/passport-saml)
![image](https://github.com/pennersr/django-allauth/assets/60965273/43507bd6-5e48-4473-85cc-54cb603fdda1)

```json
{
  "sp": {
    "entity_id": "https://sp"
  },
  "idp": {
    "sso_url": "https://idp/login/saml",
    "entity_id": "urn:sp",
    "x509cert": "***"
  },
  "advanced": {
    "want_name_id": false,
    "metadata_signed": true,
    "digest_algorithm": "http://www.w3.org/2001/04/xmlenc#sha256",
    "name_id_encrypted": false,
    "signature_algorithm": "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256",
    "want_message_signed": false,
    "authn_request_signed": false,
    "logout_request_signed": false,
    "want_assertion_signed": false,
    "logout_response_signed": false,
    "want_name_id_encrypted": false,
    "want_assertion_encrypted": false,
    "want_attribute_statement": true,
    "allow_single_label_domains": true,
    "reject_deprecated_algorithm": true
  },
  "attribute_mapping": {
    "uid": "uid",
    "email": "email",
    "last_name": "last_name",
    "first_name": "first_name",
    "email_verified": "email_verified"
  }
}```

**Comment by pennersr** [comment]
How to set a key is actually missing from the `saml.rst` documentation.

**Comment by pennersr** [comment]
Closed via 49f38c11

**Comment by zgurea1** [comment]
@pennersr hi, thx for updating the docs, but i don't understand how to add x509cert and private_key to the json, if i use example from docs is invalid json, and if i cut (-----BEGIN CERTIFICATE-----) the certs are not valid.
I need to use authn_request_signed:true for SSO (Wrong AuthnRequest Signature. Please check the certificate), i get this error. 
Can i add a path to certs or a workaround for this issue?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3811
