### ISSUE TITLE
Integrate allauth headless api docs with drf spectacular

### ISSUE THREAD

**Issue by ashwanthbalakrishnan5** [pennersr/django-allauth#3813]
Hi @pennersr ,
In my DRF application I use docs generated by [drf-spectacular](https://github.com/tfranzel/drf-spectacular).
Is there any workaround to integrate allauth headless docs into the same page. I don't want the front-end guys to go back and forth between two docs. Also is there any way to include swagger docs in this ?

I think the workaround here should be somehow serve the docs in my server itself, like if the drf-spectacular serves docs are at ```/docs/api/redoc/``` then the allauth should be hosted in ```/docs/api/redoc/allauth/```. But I'm not sure how to do it

**Comment by ashwanthbalakrishnan5** [comment]
@pennersr Any updates on this ?

**Comment by pennersr** [comment]
Duplicate of #3830

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3813
