### ISSUE TITLE
Installation error when wheel is not installed

### ISSUE THREAD

**Issue by millsks** [pennersr/django-allauth#3814]
We have an application that uses django-allauth.  Installs perfectly when wheel is installed prior. Unfortunately,  the python build pack for PCF does not include wheel so when it tries to install django-allauth from a downloaded package stored in a vendor directory it will throw an error.  That error is because the bdist_wheel command is not available. 

Is it possible to get django-allauth built and published to pypi as a wheel binary distribution?

**Comment by pennersr** [comment]
I am not sure I fully grasp the issue. Wouldn't doing so fix the issue on the wrong end? Do you require wheels for all packages you are dependent on, or just allauth? If only allauth, why?

**Comment by millsks** [comment]
It was required for all the packages.  They have our CI/CD automation setup to download all the packages first so that they can be transferred as part of the deployable artifact.

Normally this wouldn't be a problem because the wheel package would be installed and it would be able to build django-allauth.  Unfortunately, the PCF python buildpack does not include wheel so it fails.

Would you be open to a PR with the required changes?  I don't mind helping and doing the leg work.

**Comment by millsks** [comment]
In addition I did also request the wheel package be added to the python buildpack.

As a workaround I was able to use the conda pkg manager to get wheel installed prior to installing other project dependencies.

If you are still willing to include the whl in addition to the tarball that would be great though.  It would help others that might hit this problem in the future.

**Comment by pennersr** [comment]
> Would` you be open to a PR with the required changes? I don't mind helping and doing the leg work.

I prefer not to pick this up. Distributing wheels is a recurring additional cost that allauth would have to incur on each release.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3814
