### ISSUE TITLE
[MFA] ActivateTOTPView not AJAX capable

### ISSUE THREAD

**Issue by mecampbellsoup** [pennersr/django-allauth#3820]
I was comparing `LoginView` to `ActivateTOTPView` and was confused that when making requests to the latter I wasn't getting JSON data back.

Is there any particular reason these views shouldn't be AJAX capable?

```python
class LoginView(
    NextRedirectMixin,
    RedirectAuthenticatedUserMixin,
    AjaxCapableProcessFormViewMixin,
    FormView,
):
```

```python
@method_decorator(reauthentication_required, name="dispatch")
class ActivateTOTPView(FormView):
```

Additionally, is there a way I can query a view to ask "are you AJAX capable"?

**Comment by pennersr** [comment]
AJAX support through those AJAX capable views has always been an undocumented poor (wo)men's approach to an API. Starting from 0.63.0 allauth has a real API (https://docs.allauth.org/en/latest/headless/api.html), fully documented and covering the whole of allauth. I would rather deprecate the existing AJAX capable views than extend them.

**Comment by mecampbellsoup** [comment]
Sweet!!

Do we more or less just need to do: 

```
--- a/cloud_console/django/project/settings.py
+++ b/cloud_console/django/project/settings.py
@@ -72,10 +72,10 @@ INSTALLED_APPS = [
     "cloud_console.django.apps.webauth",
     "cloud_console.django.apps.migrations",
     "django_extensions",
-    "allauth",
-    "allauth.mfa",
-    "allauth.account",
-    "allauth.socialaccount",
+    "allauth.headless",
+    "allauth.headless.mfa",
+    "allauth.headless.account",
+    "allauth.headless.socialaccount",
```

**Comment by pennersr** [comment]
There are no headless subapps, just follow this:

https://docs.allauth.org/en/latest/headless/installation.html

(or, have a look a the examples/react-spa project)

**Comment by mecampbellsoup** [comment]
Sorry thank you, missed those docs.

**Comment by pennersr** [comment]
Yes: https://docs.allauth.org/en/latest/headless/openapi-specification/#tag/Account:-2FA/paths/~1_allauth~1%7Bclient%7D~1v1~1account~1authenticators~1totp/post

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3820
