### ISSUE TITLE
Headless Unauthorized Error When Logging In from Nuxt App

### ISSUE THREAD

**Issue by vasilistotskas** [pennersr/django-allauth#3825]
**Description**

I am trying to log in from my Nuxt app server to my Django backend using an API endpoint. However, I am encountering an "Unauthorized" error. The Nuxt app is running on localhost:3000, and the Django backend is running on localhost:8000.

**Code**

```
import type { H3Event } from 'h3'
import { z } from 'zod'

export const ZodLoginResponse = z.object({
  status: z.number(),
  data: z.record(z.unknown()).optional(),
  meta: z.record(z.unknown()).optional(),
})

export const ZodLoginBody = z.object({
  email: z.string(),
  password: z.string(),
})

export default defineEventHandler(async (event: H3Event) => {
  const config = useRuntimeConfig()
  const validatedBody = await readValidatedBody(event, ZodLoginBody.parse)
  const response = await $fetch(`${config.public.djangoUrl}/_allauth/app/v1/auth/login`, {
    body: validatedBody,
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
  })
  return await parseDataAs(response, ZodLoginResponse)
})

```

**Error Message**
I am receiving the following error when trying to log in:

`Unauthorized: /_allauth/app/v1/auth/login`

**Postman Request**
I tried to log in using Postman and received the same error with the following response:

```
{
    "status": 401,
    "data": {
        "flows": [
            {
                "id": "login"
            },
            {
                "id": "signup"
            },
            {
                "id": "mfa_authenticate",
                "is_pending": true
            }
        ]
    },
    "meta": {
        "is_authenticated": false,
        "session_token": "l0t94t8ay19xnizdn5yiudpvc5h5yn7n"
    }
}
```

**Context**
The Nuxt app does not know the current sessionid cookie.
I have checked the ALLOWED_HOSTS and CSRF settings in Django and included localhost:3000.

**Questions**
How am I supposed to log in if the Nuxt app does not know the current sessionid cookie?
Do I need to set the X-Session-Token header? If so, how can I obtain it?
Are there any additional configurations needed on the Django side to enable login from the Nuxt app?

### Edit

Can be closed , the problem as i see is because of the flow `mfa_authenticate` pending

**Comment by pennersr** [comment]
You seem to have MFA turned on, and therefore, the user is not authenticated yet, hence, the 401. Check this part of the response:

```
            {
                "id": "mfa_authenticate",
                "is_pending": true
            }
```

So, the API is informing the client that authentication is still pending the completion of the MFA flow.

All in all, this seems to be working according to spec.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3825
