### ISSUE TITLE
Headless sign up view doesn't respect is_open_for_signup adapter method

### ISSUE THREAD

**Issue by grahamhealy20** [pennersr/django-allauth#3826]
Hi there,

I'm currently looking at wiring up my headless allauth app with django-invitations. I want to make sure that the application only allows sign ups where a user has been invited. Currently, looking at the `SignupView`, it doesn't seem to check whether or not sign ups are open like the HTML template view does using `get_adapter(self.request).is_open_for_signup(self.request)` method via the `CloseableSignupMixin`. Is there a way to do something similar with the headless app? I think it may be possible to just inherit the mixin, but maybe there needs to be a headless version of it to handle the different content type.

Many thanks for all of the hard work to make the headless API a reality! It's working really well for me!

**Comment by pennersr** [comment]
Fixed via dabd8269

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3826
