### ISSUE TITLE
Headless Authorization Code + PKCE Support?

### ISSUE THREAD

**Issue by vecchp** [pennersr/django-allauth#3827]
I'm currently using [dj-rest-auth](https://github.com/iMerica/dj-rest-auth) and [django-rest-social-auth](https://github.com/st4lk/django-rest-social-auth) for two separate projects that utilize the [authorization code flow with PKCE](https://auth0.com/docs/get-started/authentication-and-authorization-flow/authorization-code-flow-with-pkce) rather than the [implicit flow](https://oauth.net/2/grant-types/implicit/).

I am considering migrating from these libraries to the recently released headless API.  In the documentation I noticed the presence of a token flow (which appears to be the implicit grant) and a redirect flow (which does not seem suitable for the Authorization Code + PKCE workflow).

Could you clarify if the authorization code flow with PKCE is currently supported or if there are plans to implement it in the future? Additionally, if there is support, could you provide guidance on its usage?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3827
