### ISSUE TITLE
Report when register not validated email

### ISSUE THREAD

**Issue by CARocha** [pennersr/django-allauth#3829]
Hi, I used Django 5.x and  allauthh 0.61.1 but when a register not validated the email for example a put pepe1@example.comm (you double mm) is accepted why?

Thanks

**Comment by pennersr** [comment]
That is regular Django behavior:

```
>>> from django.core.validators import validate_email
>>> validate_email("pepe1@example.comm")
# No ValidationError is thrown
```

You could hookup something like this https://gist.github.com/dokterbob/876648/22fe8830c7beb419c02060ffa2658749d94d4b6d to the `clean_email()` adapter method.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3829
