### ISSUE TITLE
Unable to change email when account is protected under MFA

### ISSUE THREAD

**Issue by subhamagr** [pennersr/django-allauth#3833]
I am able to change the email address when MFA isn't activated, but as soon as I activate MFA on the account, I cannot change my email. No error is shown either.

[account_change_email_true](https://github.com/pennersr/django-allauth/assets/7915409/a1f9cb11-af57-4ed1-8bfd-a7e9b218d807)

but then I set `ACCOUNT_CHANGE_EMAIL = False`, I see the error.

[account_change_email_false](https://github.com/pennersr/django-allauth/assets/7915409/4d8874a1-417e-4a10-bfbd-60ffd479291f)

Why such a restriction?

**Comment by pennersr** [comment]
There is a risk that somebody else adds/changes to your email address, and prevents you from creating an account yourself. Normally, you can easily get out of such situation -- your email address is attached, so you can easily recover the account. However, if that person turns on 2FA, you will not be able to gain access to the account with your email address on it.

Having said that, not showing the error is a bug -- that requires fixing.

**Comment by pennersr** [comment]
Fixed via 6ca37d71

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3833
