### ISSUE TITLE
How to Resolve "Application labels aren't unique" Error When Adding allauth Services to a Django Project with Existing 'account' App

### ISSUE THREAD

**Issue by c0d33py** [pennersr/django-allauth#3837]
I'm encountering an error when attempting to integrate `allauth.account `services into my Django project, which already has an app named account. The error message reads: `django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: account`. 
How can I resolve this issue and successfully incorporate `allauth` services into my project alongside the existing `account` app? Any guidance or solutions would be greatly appreciated!

**Comment by pennersr** [comment]
You can use `label`: https://docs.djangoproject.com/en/5.0/ref/applications/#django.apps.AppConfig.label

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3837
