### ISSUE TITLE
Is it possible to configure microsoft/azure login/api endpoint?

### ISSUE THREAD

**Issue by rqi14** [pennersr/django-allauth#3838]
Hi. Thanks for sharing this awesome project. 

The general OIDC interface works great. I recently found that allauth supports microsoft/azure provider that communicates using graph api. It will be very useful. But it seems to support only the most common service run by microsoft, but not the national clouds. The Microsoft 365 service run by 21vianet in China has the graph api endpoint set to https://microsoftgraph.chinacloudapi.cn, instead of https://graph.microsoft.com. 

The login url is also different. for m365 by 21vianet, it is login.partner.microsoftonline.cn, instead of login.partner.microsoftonline.com

I am wondering if there is a way to set the endpoint in the configuration file?

**Comment by pennersr** [comment]
That is now possible via 92c1918f

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3838
