### ISSUE TITLE
Facebook auth works, but does not create a user account

### ISSUE THREAD

**Issue by OdifYltsaeb** [pennersr/django-allauth#3844]
I took the default settings from documentation, put them into middleware, installed apps and so on and then added the provider configuration.

What I see is, that user creation and authentication works just fine with google. 

With facebook, however, it's like this:
1. Click on the facebook provider button in the frontend
2. I'm redirected to facebook (POST request to `https://localdomain.xyz/_allauth/browser/v1/auth/provider/redirect` with data like `provider=facebook&process=login&callback_url=https%3A%2F%localdomain.xyz%2Fprovider%2Fcallback%3Fsuccess%3Dtrue%26next%3D%2Fplay&csrfmiddlewaretoken=B54IeoWT6WwQdp7eBD2ctKTO9v4zwvpK`)
3. Facebook authorization happens ( in the first time )
4. I'm then directed back to my site ( I see a request like `/accounts/facebook/login/callback/?code=AQAN-7e5sJsICYHAc1bjP2CuYLNbl-y5_w-8sxvIqkR72h89Kl8pTCXyXbrHW644zw9lsM2BN4IujYdg8HwvrLf5BGKYtJ78m6oiPE3oRqlFIt6e9oDJ9XGbD8Ge36xVjIxnez9hRin0zfpjHhRoHF6BnD8ZKl5Ey_iZ_sSH1a5atJZOnjDYCfkpYOnJ9fNY9qJ_Xl9vP1Gp5w_MoiM-m2c6qSqDTA3sBP6mg1dljhKAMLFMGVMbxKXJ-3LQqkSOD_a5inUAvXIjbMT0U8TcT082vxPlATPzWXoKVGyeJsiHLyjROvUCfrdawiEtYOh5r1u7vNZiNmJJZJCEJAH8vvkLADMKUAms1ODvaCdSSk3eJ0TwcIl4oNmxSa90DpFGidg&state=YYpkIHBqd6Wc9vVI 302 [0.62, 192.168.48.6:37040]` in my docker logs)
5. Django backend redirects back to the frontend: `GET /provider/callback?success=true&next=/play 200 in 37ms`
6. But no user was created. No errors happen

Here's my setup:

```
# settings
INSTALLED_APPS = [
    ...
    # Allauth
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.headless",
    "allauth.socialaccount.providers.facebook",
    "allauth.socialaccount.providers.google",
    "allauth.usersessions",
    ...
]

ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_LOGOUT_ON_PASSWORD_CHANGE = False
#ACCOUNT_LOGIN_BY_CODE_ENABLED = True
# Provider specific settings
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        # For each OAuth based provider, either add a ``SocialApp``
        # (``socialaccount`` app) containing the required client
        # credentials, or list them here:
        'SCOPE': [
            'email',
        ],
        'APP': {
            'client_id': env.str("GOOGLE_ID", default=""),
            'secret': env.str("GOOGLE_SECRET", default=""),
            'key': ''
        }
    },
    'facebook': {
        'METHOD': 'oauth2',  # Set to 'js_sdk' to use the Facebook connect SDK
        'SDK_URL': '//connect.facebook.net/en/sdk.js',
        'SCOPE': ['email',],
        'INIT_PARAMS': {'cookie': True},
        'FIELDS': [
            'id',
            'first_name',
            'last_name',
            'middle_name',
            'name',
            'name_format',
            'picture',
            'short_name'
        ],
        'EXCHANGE_TOKEN': True,
        'VERIFIED_EMAIL': False,
        'VERSION': 'v20.0',
        'GRAPH_API_URL': 'https://graph.facebook.com/v20.0',
        'APP': {
            'client_id': env.str("FACEBOOK_ID", default=""),
            'secret': env.str("FACEBOOK_SECRET", default=""),
            'key': ''
        }
    }
}
HEADLESS_ONLY = True
HEADLESS_FRONTEND_URLS = {
    "account_confirm_email": "%s/verify/{key}" % SITE_URL,
    "account_reset_password": "%s/forgot-password" % SITE_URL,
    "account_reset_password_from_key": "%s/recover-password/{key}" % SITE_URL,
    "account_signup": "%s/sign-up" % SITE_URL,
    "socialaccount_login_error": "%s/provider/callback" % SITE_URL,
}
```

Allauth version: 
`django-allauth = {extras = ["mfa", "socialaccount"], version = "^0.63.1"}`
Django version:
`Django = "==5.0.*"`

**Comment by pennersr** [comment]
Must admit, I do not know what is going on here. One thing I am wondering about:

`/provider/callback?success=true&next=/play`

Where is `success=true` coming from? That's not something allauth passes along.

FWIW, you can see Facebook up and running over here: https://react.demo.allauth.org/account/login

**Comment by OdifYltsaeb** [comment]
That is part of the callback url I pass to the form that is posted to redirect endpoint. You can see it in the data under #2.

And yup—it's obviously working, as your example page shows. That's why I wonder what's going on here.

**Comment by OdifYltsaeb** [comment]
@pennersr , While debugging the issue, I found that Facebook does not return my email address, even though I've chosen to share it in consent view, and my access permissions show I've shared it. That's the reason stuff fails silently.

Would you happen to have any idea how to get around it? The worst thing ( for me) is that it fails silently. Otherwise, I would know, in the FE, that the login was successful, but the user was not created because the email was missing. If I knew this, I could use the information to direct users to a view where they can enter their email. Or the reason is elsewhere, and I should look into it more deeply.

**Comment by pennersr** [comment]
@OdifYltsaeb If all is well it is not failing silently. The handshake with the provider succeeds, that is actually correct. But, when the backend redirects back to the frontend, the frontend freshly boots up and should fetch the current state of the session. If provider signup was not fully complete because of a missing email, you should be running into a 401 at this point, and the `provider_signup` flow should indicate `is_pending: true` -- meaning, you are expected to post the missing email to the provider signup endpoint. Only after completing that last step a new account gets created.

**Comment by OdifYltsaeb** [comment]
@pennersr, all right, but what do we debug next? What you describe is precisely what I would need.

What I see is that the code runs through the OAuth2CallbackView at /login/callback/, and in the end, there are no 401 responses, but 302 redirects from the backend to the frontend. What can I provide to help to figure out what is going on? Facebook app setup? Can you point out where the decision between returning 401 or 302 is?

**Comment by pennersr** [comment]
I cannot help you debug your frontend -- have a look at what the react-spa example app is doing. When it boots up, it fetches the session, checks for 401 and redirects to the pending flow if there is one. Did you implement that in your frontend? 

> Can you point out where the decision between returning 401 or 302 is?

Note that it is not the /login/callback that is returning the 401... the OAuth callback completely succeeds, and pushes the authentication state forwards. It then redirects to the frontend. It is up to the frontend to check what the current authentication state is when it boots up, so the frontend is to fetch the current session and that current session returns the 401. 

Try running this scenario in the example app.

**Comment by OdifYltsaeb** [comment]
Awesome, thanks. I'll look into that. Perhaps I've missed something in the frontend indeed.

**Comment by GiovanniGatti** [comment]
After hours and hours trying to solve a similar problem, I finally figured that everything worked behind a proxy. I was using the session based authentication, exactly as in the [react-spa example](https://codeberg.org/allauth/django-allauth/src/branch/main/examples/react-spa). 

This is probably due to token exchanges of tokens and CORS and CSRF or whatever.

If you're struggling with a similar issue, consider setting your dev environment as implemented here [react-spa/docker-compose.yml](https://codeberg.org/allauth/django-allauth/src/commit/0a7b4420bd1330eaff4768d2c22fa52cef06de53/examples/react-spa/docker-compose.yml). And then you try to login with the proxy (localhost:10000). With this setting, both front and backend will be in the same domain and it may save your day (or week).

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3844
