### ISSUE TITLE
NPM package to streamline the use of allauth headless in JS apps

### ISSUE THREAD

**Issue by CarlosBueno99** [pennersr/django-allauth#3845]
it'd be useful to have a npm package that covers the functionality in [allauth.js](https://github.com/pennersr/django-allauth/blob/main/examples/react-spa/frontend/src/lib/allauth.js) as that would help drive adoption by providing an easier entry point into a working implementation.

**Comment by pennersr** [comment]
I already see some work moving towards this direction: https://jsr.io/@knowsuchagency/allauth-fetch

(⚠️  I am not affiliated with that so not fully sure about its intent & status)

**Comment by thclark** [comment]
I'd actually recommend the use of auth.js (formerly next-auth, now available for multiple frameworks) which handles most of the frontend misery for you (refetching etc).

**Comment by pennersr** [comment]
For now, I would prefer to leave it up to the community to pick this up. Over in the npm realm, there is a lot of diversity and frameworks to be supported, and I think that is best served in projects on their own.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3845
