### ISSUE TITLE
Documentation for installing mfa has slight issue

### ISSUE THREAD

**Issue by techsavvyme** [pennersr/django-allauth#3850]
The following pip command in the documentation for installing MFA did not work for me:

pip install django-allauth[mfa]

Figured out after a while that quotes were needed:

pip install 'django-allauth[mfa]'

Maybe lack of experience with using pip, but thought maybe you'd want the documentation to be corrected.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3850
