### ISSUE TITLE
HEADLESS_ONLY = True and socialaccount_connect combination 

### ISSUE THREAD

**Issue by OdifYltsaeb** [pennersr/django-allauth#3854]
After you were (@pennersr ) right at my previous bug report, and I indeed had fumbled and set up things incorrectly, I'm half dreading that I'm submitting another useless bug report... but I'm not sure how else to get assistance either. Sorry.

So, after successfully setting up account creation and authentication flows following the examples in the examples/react-spa/ folder, I'm now trying to follow the view where I connect different providers to my account on my profile. Following the example set here https://github.com/pennersr/django-allauth/blob/main/examples/react-spa/frontend/src/socialaccount/ManageProviders.js I've set up buttons for connecting providers and making sure the request redirecting/posting to provider view has "connect" process instead of "login".

POST request to `/_allauth/browser/v1/auth/provider/redirect` is as follows : `provider=google&process=connect&callback_url=https%3A%2F%localdomain.xyz%2Fprofile&csrfmiddlewaretoken=1FGZhXhj02RAKWekg1DO4a0uNEPeVtW0`

This neatly takes me to google and I can choose my account there. All good. When google redirects me back to 
`https://localdomain.xyz/accounts/google/login/callback/?state=9rj1GsCdhrywvcX1&code=4%2F0AdLIrYeMAuCK_FLWskJuUfPLF1wDKXptgYkqAZfmojq-MG13zJShs8DvcTriOkAWXVS0TQ&scope=email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+openid&authuser=0&prompt=none` I get 500 error, though:
![image](https://github.com/pennersr/django-allauth/assets/212621/b08612d6-6ad7-453c-9224-ed98244f3620)

I noticed, that the "socialaccount_connections" is only included in allauth.urls.py if settings are "not HEADLESS_ONLY": https://github.com/pennersr/django-allauth/blob/main/allauth/urls.py#L37

Does that mean that the CONNECT views are not working for HEADLESS only right now, and this means the development is in progress? Should I do something differently? Create my own "socialaccount_connections" view for time being? Is this a bug? 

Edit: Maybe the best course of actions is to extend the Adapter class and make sure it returns correct redirect url and does not try to fall back to the template view?

**Comment by OdifYltsaeb** [comment]
Update:

I tried using the `HEADLESS_ADAPTER` setting and created my own adapter extending `DefaultHeadlessAdapter` like this:
```
from allauth.headless.adapter import DefaultHeadlessAdapter


class CustomHeadlessAdapter(DefaultHeadlessAdapter):
    def get_connect_redirect_url(self, request, socialaccount):
        return "/profile"
```

But that did not work either and I noticed that the adapter being used is DefaultSocialAccountAdapter, not DefaultHeadlessAdapter (or my adapter):
![image](https://github.com/pennersr/django-allauth/assets/212621/ed99b7c8-269e-4346-a7aa-956d6a6b08a6)

If I override SOCIALACCOUNT_ADAPTER, then stuff works just fine and I(user) end up at the profile view with provider successfully connected.

So potentially few errors:
- Connecting results in error because of reliance of reverse("socialaccount_connections") url being there if in HEADLESS_ONLY mode
- HEADLESS_ONLY mode does not utilize adapter set by HEADLESS_ADAPTER setting

**Comment by OdifYltsaeb** [comment]
Nope. was 0.63.1. It's all good when using 0.63.2, and I don't need to extend any of the adapters. Thank you!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3854
