### ISSUE TITLE
Google provider not showing in list of providers when adding social application in admin app using version 0.63.2

### ISSUE THREAD

**Issue by timcu** [pennersr/django-allauth#3857]
I downgraded to `django-allauth==0.61.1` and then Google did show in list of providers. Version 0.62.1 was also not showing Google in list of providers. 

Version 0.63.2 also had trouble resolving `{% url 'google_login_by_token' %}` but this was handled fine by 0.61.1

The only other provider I tested was GitHub and it showed fine in the list of providers in version 0.63.2.

I had installed version 0.63.2 using `pip install django-allauth[socialaccount]==0.63.2` but when I installed 0.61.1, it said it did not provide the extra 'socialaccount'.

**Comment by timcu** [comment]
Someone else experiencing the problem https://stackoverflow.com/questions/78453974/no-item-provider-dropdown-while-adding-social-application-to-django-admin

**Comment by pennersr** [comment]
Starting from 0.62.0 you need the `[socialaccount]` extra. I see that you installed 0.63.2 using that, but please give reinstalling or recreating your virtualenv a try -- the missing extra is really the only known issue in this regard.

**Comment by timcu** [comment]
Thanks for looking into it. I had tried deleting `django-allauth` and reinstalling to no benefit. However, just now I created a fresh new virtual environment and that worked. Maybe once I had done a `pip install django-allauth==0.63.2` on a virtualenv then no matter how many times I did `pip install django-allauth[socialaccount]==0.63.2` it would not install the extra, even if I had deleted django-allauth from my virtual environment (using the pycharm `-` button on the virtual environment)

**Comment by timcu** [comment]
I think I worked out the problem. It is a PyCharm bug. I had a `requirements.txt` file with the following contents
```
Django==5.0.6
django-allauth[socialaccount]==0.63.2
```

In a new virtual environment, PyCharm raises a flag to say not all packages are installed (as expected), and gives the option to "Install all missing packages". However, selecting that option only installs `django-allauth`, not `django-allauth[socialaccount]`

If I install with `pip install -r requirements.txt` the `socialaccount` installs correctly.

I will report this to JetBrains.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3857
