### ISSUE TITLE
Check if email is already registered in POST `/account/signup`

### ISSUE THREAD

**Issue by kushalmraut** [pennersr/django-allauth#3861]
**Title**: Check if email is already registered in `POST /account/signup`

**Description**: 

There is currently no mechanism to verify if an email is already registered when a user attempts to sign up using `POST /account/signup`. This can lead to multiple registrations with the same email address. 

**Proposed Solution**:
1. Implement a check within the `POST /account/signup` endpoint to verify if the email is already registered.
2. Alternatively, provide a flag or a separate endpoint to check if an email is already registered.

**Steps to Reproduce**:
1. Attempt to sign up a user with an email that is already registered.
2. Observe that the registration proceeds without any error or indication that the email is already in use.

**Expected Behavior**:
- The system should either:
  - Prevent the registration and return an appropriate error message if the email is already registered.
  - Provide a mechanism to check if an email is already registered before attempting to sign up.

**Additional Context**:
This enhancement will improve user experience by preventing duplicate registrations and ensuring that users are aware if their email is already in use.

**Comment by pennersr** [comment]
This is not true. See https://docs.allauth.org/en/latest/account/configuration.html -- `ACCOUNT_PREVENT_ENUMERATION`

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3861
