### ISSUE TITLE
Email2 field not being converted to lowercase, comparing fails

### ISSUE THREAD

**Issue by davefrassoni** [pennersr/django-allauth#3862]
on 0.63.0 emails are converted to lowercase, but when having email2 validation field it is not converted and validation fails.

https://docs.allauth.org/en/latest/release-notes/recent.html#id4

**Comment by pennersr** [comment]
Can you please elaborate what "but when having email2 validation field" means?

**Comment by davefrassoni** [comment]
email2 field is when you have the setting ACCOUNT_SIGNUP_EMAIL_ENTER_TWICE=true

email2 is a second field that prevents typos on signup process

**Comment by pennersr** [comment]
So, just to be sure, the issue is that when you enter your email twice but with different casing, then a validation error pops up. Right?

**Comment by pennersr** [comment]
That is now fixed via 11a59648

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3862
