### ISSUE TITLE
Telegram authentication needs /setdomain for your website.

### ISSUE THREAD

**Issue by mathew2005** [pennersr/django-allauth#3865]
This isn't documented by djangoallauth on how to setup telegram's widget login. I tried hours figuring it out and finally worked when i put my website domain using /setdomain command on bot father.

**Comment by pennersr** [comment]
Any PRs to improve the documentation are welcome. Though, I prefer not to keep issues open for documentation improvement as those can be filed endlessly....

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3865
