### ISSUE TITLE
How to match existing, local accounts to social accounts by username?

### ISSUE THREAD

**Issue by hansegucker** [pennersr/django-allauth#3867]
Hi everyone, hi @pennersr,

we have been using django-allauth with out project for a while and now encountered a new situation in which we have to match existing, local accounts to social accounts by their username during login. I searched the documentation and didn't found anything on this topic.

I would be glad to get some support regarding this issue. Thank you!

**Comment by pennersr** [comment]
I am not sure if what you are planning on doing is secure, but if you must, here are some pointers:

- The socialaccount adapter has  a `pre_social_login()` method. This method is called at the start of the social login flow. 
- You can override that method and check `sociallogin.is_existing` -- if this is false, it is a new social account being logged in, meaning, you can do your username lookups, and set `sociallogin.user` to the user resulting from that lookup.

**Comment by hansegucker** [comment]
Ah, thank you for your input!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3867
