### ISSUE TITLE
Headless mode: reset password not working

### ISSUE THREAD

**Issue by gleniat** [pennersr/django-allauth#3868]
Thank you for enhancing the library by introducing headless mode.

However, I am unable to get the reset password feature to work.

I have tried using the classic mode, which involves a reset password HTML form endpoint. In classic mode, the reset password email is sent correctly. However, in headless mode, I receive an empty 400 response and no email is sent.

### Request 1:

`POST http://localhost:3000/api/v1/_allauth/browser/v1/auth/password/request`
post data: no form data sent

response: error 400
```
{
    "status": 400,
    "errors": [
        {
            "message": "This field is required.",
            "code": "required",
            "param": "email"
        }
    ]
}
```

OK

### Request 2:

`POST http://localhost:3000/api/v1/_allauth/browser/v1/auth/password/request`
post data: email = invalid.email.invalid

error 400 empty response

**The response should not be empty.**

### Request 3:

`POST http://localhost:3000/api/v1/_allauth/browser/v1/auth/password/request`
post data: email = validemailoftheuser@example.com

**error 400 empty response again**

**The response should not be empty.**

**Comment by pennersr** [comment]
How exactly are you making those requests? Can you check what the difference is between the requests as posted over here:

https://react.demo.allauth.org/account/password/reset

Are you posting JSON?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3868
