### ISSUE TITLE
Headless Demo: Add ability to delete user

### ISSUE THREAD

**Issue by semihsezer** [pennersr/django-allauth#3874]
Many thanks for creating the demo environment, this is super helpful for me to understand how Django AllAuth works.

In the [headless Demo environment](https://react.demo.allauth.org/), could you add ability to delete your own user? I signed up with login password but now I can't test out Google login - I get a 401 error something went wrong and an email saying a user with this email already exists.

Workaround: Use another email, but this is a bit of a hassle if you want to test out multiple options or redo the login flow.

Thanks,
Semih
<img width="621" alt="Screenshot 2024-06-08 at 11 47 07 AM" src="https://github.com/pennersr/django-allauth/assets/12139945/af4cd2ab-c547-4bdd-b329-a7ea966a5769">
<img width="1920" alt="Screenshot 2024-06-08 at 11 45 48 AM" src="https://github.com/pennersr/django-allauth/assets/12139945/3d4d0f86-87a9-4b5e-a2e0-134d6b6065e8">

**Comment by pennersr** [comment]
It would be indeed handy to have a self destruct option in the example app, provided it is clear that this is just ad hoc functionality meant for testing purposes -- people should not expect this functionality to be an official polished GDPR-style remove your account function.  Can you add it?

**Comment by pennersr** [comment]
Moved to https://codeberg.org/allauth/django-allauth/issues/3874
