### ISSUE TITLE
Adding class for input doesn't word

### ISSUE THREAD

**Issue by aidar-aminev** [pennersr/django-allauth#3876]
<input {% if attrs.required %}required{% endif %}
               {% if attrs.disabled %}disabled{% endif %}
               {% if attrs.readonly %}readonly{% endif %}
               {% if attrs.checked %}checked{% endif %}
               {% if attrs.name %}name="{{ attrs.name }}"{% endif %}
               {% if attrs.id %}id="{{ attrs.id }}"{% endif %}
               {% if attrs.placeholder %}placeholder="{{ attrs.placeholder }}"{% endif %}
               {% if attrs.autocomplete %}autocomplete="{{ attrs.autocomplete }}"{% endif %}
               value="{{ attrs.value|default_if_none:'' }}"
               type="{{ attrs.type }}" class="form-control">

I added a class "form-control" to the input element. It doesn't appear on the site. There are no such problems with other elements.

**Comment by pennersr** [comment]
See https://docs.allauth.org/en/latest/common/templates.html -- particularly the note over at fields.html:

> The form fields, uses {{form.as_p}} by default, hence, not rendering the field.html.

So, if you are using the standard `fields.html` template `field.html` is not used, except for a few one off places where fields are rendered ad hoc.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3876
