### ISSUE TITLE
Document the usage of (dynamic) auth_params such as kc_idp_hint within provider_login_url

### ISSUE THREAD

**Issue by skinkie** [pennersr/django-allauth#3877]
I would like to hint keycloak that a specific button should cause a direct authentication flow into a specific identity provider. With a bit of debugging I was able to come up with the following, which works. I would have hoped that `kc_idp_hint='specific_idp'` would have worked, I understand this would append all parameters, which may be undesired.

```
            <form action="{% provider_login_url 'keycloak' auth_params="kc_idp_hint=specific_idp" %}" method="post">
                  {% csrf_token %}
                  <button type="submit">My Specific IDP</button>
            </form>
```

**Comment by pennersr** [comment]
Moved to https://codeberg.org/allauth/django-allauth/issues/3877
