### ISSUE TITLE
Allow to customize tokens mock in OAuth2TestsMixin

### ISSUE THREAD

**Issue by giuliopaci** [pennersr/django-allauth#3887]
OAuth2TestsMixin assumes that refresh_token and access_token can be mocked into a "testrf" and "testac" respectively and some tests (e.g., test_account_tokens) also makes some assertions based on this assumption.

In my application I had to implement a custom provider for a private service where authentication and user information are provided by means of a jwt token, so, if I want to keep my tests meaningful I need the access token to be a jwt token that I can decode. This collides with current assumption that I can use "testac" as an access token.

I solved the issue by:
1. override setUp() in order to dynamically create a mocked jwt token;
2. override get_login_response_json and test_account_tokens to use the mocked jwt token instead of "testac".

Would it make sense to implement this approach into OAuth2TestsMixin?

**Comment by pennersr** [comment]
The test related code shouldn't be considered as a public API, so relying on e.g. specific OAuth2TestsMixin behavior by an external project is dangerous. For example, the current test suite is in transition, moving away from classical Django class based unit tests to plain pytest functions. Now, the provider tests have not been refactored yet, but will be one day. Therefore, I don't think it makes much sense to add specific logic to OAuth2TestsMixin that is not used by allauth tests itself as this interface is bound to be broken.

**Comment by giuliopaci** [comment]
Ok, I was just asking it since my provider implementation closely resemble other allauth providers implementation, and so I thought the change could be more general and simplify other providers implementation (both external and internal).

While I understand that relying on OAuth2TestsMixin is considered dangerous, still I wonder if there better alternatives, considering that I tried to keep my provider implementation aligned to other providers in allauth. Reimplementing tests does not seem any better to me than relying on a private interface used by many similar implementations.

**Comment by pennersr** [comment]
See the PR above -- does that solve your issue?

**Comment by giuliopaci** [comment]
Unfortunately not, since the most important line to be changed is this one:

https://github.com/pennersr/django-allauth/pull/3899/files#diff-c0558bc40fcc747ca98eb225e2acb7a072d67fdcfc42e3f7dfd6fbcf7270238dR297

which has not been changed.

So, overriding get_access_token will make test_account_tokens fail.

**Comment by pennersr** [comment]
That is fixed now. Can you have a renewed look?

**Comment by giuliopaci** [comment]
PR seems fine to me now, thanks.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3887
