### ISSUE TITLE
[Suggestion] Signing up should (re)send verification mail

### ISSUE THREAD

**Issue by alexandernst** [pennersr/django-allauth#3891]
If `ACCOUNT_EMAIL_VERIFICATION` is set to `mandatory` and the user doesn't receive the verification email for whatever reason (temporal failure, network issues, mail being discarded by the receiver's MTA, etc...) the user would end up stuck in a situation where he can't sign up again (because the email has already being registered) and he can't request a new verification mail.

Maybe add an option to send a new verification mail whenever a user signs up with an email address that has already being registered, but the verification status of the email is `unverified`.

I ended up doing this:

```
class SignupForm(AllAuthSignupForm):
    def try_save(self, request):
        email = self.cleaned_data.get("email")
        if (
            self.account_already_exists and
            EmailAddress.objects.filter(email=email, verified=False).exists()
        ):
            # send confirmation email again
            user = get_user_model().objects.get(email=email)
            send_email_confirmation(request, user, signup=True, email=email)
            resp = HttpResponseRedirect(
                reverse("account_email_verification_sent", host='account')
            )
            return user, resp

        return super().try_save(request)
```

**Comment by pennersr** [comment]
> ... and he can't request a new verification mail.

That is actually not the case. When email verification is mandatory, each login attempt that logs in with an unverified email will trigger a verification email.

**Comment by alexandernst** [comment]
> That is actually not the case.

I just tested this once again and if a new signup is made with an email that already registered but not verified, the mail that is sent to the email address is `Account Already Exists`, which is different from that I'l proposing (`Email Confirmation`).

The `Account Already Exists` mail provides a link that can be used to reset the password, but that still won't verify the account.

**Comment by alexandernst** [comment]
Adding some more notes. The related code to this is located here: https://github.com/pennersr/django-allauth/blob/7148c9e03956fc8db7fd193243bd03af3f83c38b/allauth/account/forms.py#L380-L391

As you can see, the `try_save` in the `BaseSignupForm` will check if `self.account_already_exists` and it will call `adapter.send_account_already_exists_mail(email)`. My suggestion is to change that `if` statement to

```
if self.account_already_exists and EmailAddress.objects.filter(email=email, verified=False).exists():
    adapter.send_confirmation_mail(....)
elif self.account_already_exists:
    adapter.send_account_already_exists_mail(...)
else:
    ....
```

**Comment by pennersr** [comment]
So, if I understand you correctly, your request is to alter the signup behavior for an already signed up user, and change the account-already-exists email into a verification email? Thoughts:

- The original problem statement (stuck user) is not correct. Currently, you signup, receive a mail reminding you that you already have an account, you go "aha, I'll just login then", and then you'll receive the verification mail.
- Sending a verification mail on second signup leads to UX questions. For example, I signup with some password. Then, I sign up another time with a different password. With the proposed flow, I receive a verification email, and click on that. As a user, I have no idea what just happened, and likely expect my password is the last one I entered, but that does not seem correct.
- To mitigate the previous point, you would actually have to explain what just happened in the mail. And, you would also need do that for just this specific case (mandatory email).

The above looks a bit convoluted to me. It would be better to fix https://github.com/pennersr/django-allauth/issues/1267

**Comment by alexandernst** [comment]
Yes, that is correct. My suggestion is to alter the behaviour for an already signed up user **when the email hasn't been verified yet**.

* Indeed, the user does receive a `confirm your email with this link` email when he tries to login to an account that hasn't been verified, but imho (and this is really a personal opinion, I do understand that there is no right or wrong PoV on this subject) users won't expect this to happen. Imho, if the user doesn't receive a confirmation mail, he is more likely to try to sign up again rather than login (read next point).
* My view on this (as a user) is that if I signed up and I didn't receive the confirmation email it means that the sign up process didn't complete correctly and I'm expected to sign up again (I might think that `something in their server crashed, I'll try again`). This makes me (the user) believe that the password that I entered during the second sign up should prevail. I don't want to say that this is either correct nor incorrect, but it definitely sounds like a reasonable behaviour.
* The user already blamed "the server" for not receiving the first email, so "we" might as well not explain anything at all and act like this is was happened. Just send the confirmation email again.

I do see your point on this, so I guess that the behaviour of allauth should be based on what you think the user is more likely to do when he doesn't receive a confirmation email, the options being `sign up again` and `try to login`.

**Comment by pennersr** [comment]
The consequence of this is that we would end up with new way of handling this, for a very specific case, which raises questionable design choices (a repeated signup can alter a password (*)), whereas the current flows already do their job just fine without getting users stuck. Besides, the premise of this use case is that the email is not being delivered. Would revisiting the flows even solve this issue? Why would the email al of a sudden be delivered the second time? Email servers use proper queueing, an emails are very unlikely to just get lost. If regarded as spam, repeating the email is not helping.

(*) -- repeatedly setting the password on subsequent signups would allow a hacker to hijack your account while you are trying to signup. E.g. you signup, hacker signs up as well setting a new password, you confirm the email, hacker logs in.

All in all, I really don't think this is an issue that needs to be addressed.

**Comment by alexandernst** [comment]
> The consequence of this is that we would end up with new way of handling this, for a very specific case, which raises questionable design choices (...)

Fair enough.

> you signup, hacker signs up as well setting a new password, you confirm the email, hacker logs in

I really don't think this can actually happen. Theoretically it is possible, but chances of this happening are near 0.

> All in all, I really don't think this is an issue that needs to be addressed.

Alright 🙏

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3891
