### ISSUE TITLE
[Suggestion] Add a small tip about rates when testing

### ISSUE THREAD

**Issue by alexandernst** [pennersr/django-allauth#3893]
Today I spent an embarrassing amount of time trying to figure out why my unit tests were randomly failing. Sometimes this test would pass, sometimes it wouldn't.

```
response = self.client.post(
    reverse_lazy('account_signup', host='account'),
    {
        'email': 'myemail@example.com',
        'password1': 'mypasswd',
        'password2': 'mypasswd',
    },
    SERVER_NAME=f"account.{settings.PARENT_HOST}"
)

# Test if the confirmation email was sent
self.assertEqual(response.status_code, 302)
self.assertEqual(response.url, '/confirm-email/')
self.assertEqual(len(mail.outbox), 2)  # <-- flaky line
```

After quite some debugging I found the reason. Rate limits apply when testing!

I have a couple of suggestions:

1) Maybe don't use rate limits at all when testing? Something like:

```
if 'test' in sys.argv:
    ACCOUNT_RATE_LIMITS = False
```

2) Add a small tip somewhere in the docs stating that unit tests may run into rates limits problems (and maybe recommend a few possible solutions, such as using the DummyCache, disabling the rate limits altogether, etc...)

**Comment by pennersr** [comment]
You are free to apply 1) to your project. Doing that in allauth is not an option. For example, rate limits themselves also need to be tested, and some projects use `test`, others `pytest` and so on...

As for 2), feel free to submit a PR to improve the documentation.

**Comment by alexandernst** [comment]
Replying to your points in the same order:

1) Fair enough!

2) Will do!

**Comment by mscheper** [comment]
@alexandernst: Your 'embarrassing amount of time' probably saved me about the same amount of time, so thank you for adding the tip! 🙂

I already check `"test" in sys.argv` for [django-debug-toolbar](https://github.com/django-commons/django-debug-toolbar), so I thought of your suggestion 1 as soon as I read the tip. But perhaps this suggestion is also worth mentioning in the tip, for other devs?

**Comment by duaneking** [comment]
This s googles first result for "allauth rate limit tests" for me.

I do think that handling this better for tests would be nice; Its not just one person suffering through this, its a known issue with the stack that creates more needless suffering, on a scale big enough that google is actively sending people here...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3893
