### ISSUE TITLE
Forcing use of SAML nameID for email

### ISSUE THREAD

**Issue by rgegriff** [pennersr/django-allauth#3896]
Hi! I am trying to integrate with a client IdP, and am running into the following issues;

- client IdP doesn't seem to work when sending the nameID with a format OTHER than `urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified`
- client didn't seem able to attach attributes successfully

This put me into a little bit of a pickle, but I was able to resolve it by updating the saml provider's `_extract` method as follows

```python
    def _extract(self, data):
        provider_config = self.app.settings
        
[... cut for length ...]

        # If we did not find an email, check if the NameID contains the email.
        if (
            not attributes.get("email")
            and data.get_nameid_format()
            == "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"
            or provider_config.get("use_nameid_for_email", False)
        ):
            attributes["email"] = data.get_nameid()

        return attributes
```

Essentially adding `or provider_config.get("use_nameid_for_email", False)` to the end of the if statement.

This enabled me to accept and successfully authenticate with the responses sent from the IdP by adding `"use_nameid_for_email": True` to the provider settings.

Is there a better way to handle this situation to work around a difficult IdP? Alternatively, would you be interested with a PR featuring this change?

**Comment by pennersr** [comment]
So, the IdP always signals "unspecified" (`urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified`) for the format, yet, still uses the email as nameid? That actually sounds like an issue with the IdP, but indeed, given that often it is not feasible for IdPs to change, it is valuable for allauth to be able to adapt and work with whatever provider is out there. PR is welcome.

**Comment by pennersr** [comment]
Merged, thanks.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3896
