### ISSUE TITLE
Can I embed allauth template to my custom template?

### ISSUE THREAD

**Issue by appleparan** [pennersr/django-allauth#390]
I'm trying to make user profile by myself. I want to add feature editing user information to profile such as email, username, first name, last name etc and use bootstrap.

To modify email address, I thought that I should embed email.html template because it is fixed to EmailView. (I want to modify all of information in one page). However, When I use `{% include 'allauth/account/email' %}`, django doesn't recognize `add_email_form|bootstrap` because it is in different context.  (saying `'str' object has no attribute 'visible_fields'`)

There isn't any option to change view or template related to email. Could you make this more flexible or provide basic profile view?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/390
