### ISSUE TITLE
Outdated user object passed to `complete_social_signup`

### ISSUE THREAD

**Issue by alexanderjulmer** [pennersr/django-allauth#3902]
# Problem

When using Socialaccount with `SOCIALACCOUNT_AUTO_SIGNUP = False`, [`signup_by_form`](https://github.com/pennersr/django-allauth/blob/a1969ba4937100f5cc3faf4ed9b974d15efc89b3/allauth/socialaccount/internal/flows/signup.py#L38) will be called. This will try and save the form and obtain a `User` object. 

However, it will then call `complete_social_signup(request, sociallogin)` and consequently [`complete_signup(…sociallogin.user,…)`](https://github.com/pennersr/django-allauth/blob/a1969ba4937100f5cc3faf4ed9b974d15efc89b3/allauth/socialaccount/internal/flows/signup.py#L114). I suspect though that `sociallogin.user` is not updated when the form is saved and hence the user object that is not the one stored in the database. In fact, it is also failing the `flows.login.perform_login(request, login)` with `Model instances passed to related filters must be saved`.

Is this by design and am I missing something?

**Comment by pennersr** [comment]
`signup_by_form` invokes `form.try_save(request)`, which in turn calls:

```
        user = adapter.save_user(request, self.sociallogin, form=self)
```

The user instance there is this one (see the `save_user()` impementation):

```
        u = sociallogin.user
```

So, it is actually the same `User` instance.

**Comment by alexanderjulmer** [comment]
You are, of course, completely right. My mistake was to have `CustomSocialSignupForm` inherit from `account.SignupForm` rather than from `socialaccount.SignupForm` which has a different `save` method just as you described.

Apologies for the useless issue and thank you for your help.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3902
