### ISSUE TITLE
Specifying a Discovery service URL

### ISSUE THREAD

**Issue by mehrdadscomputer** [pennersr/django-allauth#3903]
I am using HAKA authentication, an authentication means for Finnish research organizations. 
The SAML implementation of `Django_allauth` works for me when there is one IDP.

In my case, I need to redirect the users to a service discovery page where they can choose which IDP to use to log in.
Is there any implementation for this?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3903
