### ISSUE TITLE
`get_app` use client_id for oauth to circumvent multipelobjectsreturned

### ISSUE THREAD

**Issue by jonathan-s** [pennersr/django-allauth#3912]
Providers that implement oauth, and thus use a client id, when making that initial login you could support a get parameters to fetch the client_id from there (if available). 

That would make it possible to use several providers of the same type without using different sites. 

I would also add that currently you'll get a nasty 500 error as `get_app` can throw a `MultipleObjectsReturned` error which doesn't seem to be caught in the views. 

Would you accept a patch for these changes?

**Comment by pennersr** [comment]
Thoughts:

- For OpenID Connect, which is what the OAuth providers are slowly migrating to, you can already have multiple providers of the same kind (by specifying `APPS`). 
- On a model level, the SocialAccount model has a `unique_together = ("provider", "uid")` which would be impacted.
- I would like to first understand the use case a bit more. Can you elaborate? 
- Also, what providers would you want to use this with, and aren't they perhaps already supporting OpenID Connect? 
- Wondering, as a user, suppose I can authenticate using Facebook using `?client_id=1` and `?client_id=2`, how would I be able to make the choice between those two options, and what does it even matter if I choose 1 or 2 ?

**Comment by pennersr** [comment]
> MultipleObjectsReturned error which doesn't seem to be caught in the views.

That is indeed not caught as this is considered misconfiguration. The only thing that could be done is to catch it and raise an `ImproperlyConfiguredException`.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3912
