### ISSUE TITLE
Adding/changing email address with MFA enabled

### ISSUE THREAD

**Issue by eyalch** [pennersr/django-allauth#3914]
It seems that it's impossible to add or change an email address while having MFA enabled, judging by this commit:
https://github.com/pennersr/django-allauth/pull/3383/commits/7bf4d5e6e4b188b7e0738652f2606b98804374ab

What is the logic behind this? What is the expected flow when a user needs to change an email address?

**Comment by pennersr** [comment]
This prevents an attack vector where an attacker signs up using your email, or adds your email as a secondary email. Obviously, (s)he cannot verify the email, but if (s)he is allowed to turn on 2FA that will block you from being able to sign up. Temporarily disabling MFA is the only way around this.

**Comment by eyalch** [comment]
Thanks for the explanation! I wonder if it's worth mentioning this behavior somewhere, as it's not very intuitive (though it makes sense).

**Comment by mitchelljkotler** [comment]
> This prevents an attack vector where an attacker signs up using your email, or adds your email as a secondary email. Obviously, (s)he cannot verify the email, but if (s)he is allowed to turn on 2FA that will block you from being able to sign up. Temporarily disabling MFA is the only way around this.

Can you explain how 2FA affects this?  If someone signs up with your email address and does not enable 2FA, aren't you still blocked from being able to sign up?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3914
