### ISSUE TITLE
[headless.account.views.SignupView] Possible to prevent sign up while user logged in?

### ISSUE THREAD

**Issue by mecampbellsoup** [pennersr/django-allauth#3916]
It seems that it's possible to begin another registration/signup process for a logged-in user. Is there a simple way to disable this?

**Comment by pennersr** [comment]
The `SignupView` is using `RedirectAuthenticatedUserMixin`, Do you have `ACCOUNT_AUTHENTICATED_LOGIN_REDIRECTS` turned on?

**Comment by mecampbellsoup** [comment]
We are using the headless API - does that account configuration setting still apply?

**Comment by pennersr** [comment]
This was indeed an issue, and I don't think it makes sense to have this behavior configurable for headless usage. Fixed via 27fcdf97

**Comment by mecampbellsoup** [comment]
Thank you!

**Comment by mecampbellsoup** [comment]
Do you know when you expect to cut a release for this BTW?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3916
