### ISSUE TITLE
Headless: any way of rate limiting / throttling requests to help guard against brute force attacks and mass sign-ups?

### ISSUE THREAD

**Issue by robin24** [pennersr/django-allauth#3918]
First, I'd like to thank everyone involved in the creation of the headless component for django-allauth, this is incredibly useful and I just started integrating it into my own project today.

One thing which I'm concerned about is that as of right now, there is seemingly no way of rate limiting / throttling specific API requests, especially for sign-up, login and password reset.
I'm worried this could enable attackers to more easily perform brute-force attacks on basic accounts using Email address and passwords for authentication without MFA, it also could enable automated mass creation of spam accounts in the database.
However, I'm not sure if I may be missing something here or if security mechanisms are in place elsewhere to minimize these risks. I use DRF for my other API endpoints which provides several throttling capabilities, but unable to find anything in regards to this in the DRF docs as far as I can tell.

Any clarification on this would be greatly appreciated, thanks!

**Comment by pennersr** [comment]
Rate limits are built in. It uses the regular mechanism that is also used for the non-headless version. See:

https://github.com/pennersr/django-allauth/blob/main/allauth/headless/account/views.py#L82

**Comment by robin24** [comment]
Ah, I was unaware of that. Thanks so much for the clarification!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3918
