### ISSUE TITLE
409 on POST to /auth/provider/signup (Headless API)

### ISSUE THREAD

**Issue by Jsalaz1989** [pennersr/django-allauth#3925]
For context, I've cloned a copy of the [react-spa](https://github.com/pennersr/django-allauth/tree/main/examples/react-spa) example, which works fine as a human user interacting with the React app. That is, I am able to sign up and log in via the browser with both a regular local account as well as through Google.

However, when testing with `pytest`, I'm getting a `409` when I `requests.post` or `django.test.Client.post` to `/_allauth/app/v1/auth/provider/signup`. The [409 response is not documented](https://allauth.org/docs/draft-api/#tag/Authentication:-Providers/paths/~1_allauth~1%7Bclient%7D~1v1~1auth~1provider~1signup/post) and the response text is simply `{"status": 409}`, so I don't have many hints about what went wrong. I've tried it with the Google email and password, as well as just the email, in the `post` body.

When I try with `/_allauth/browser` instead of `/_allauth/app` I get a `403` with html stating that I'm missing a CSRF token, but adding a `X-CSRFToken` header or the `cookies` parameter doesn't help, and honestly I'm not sure if I should even be using the `browser` client for these tests.

I'm trying to get `/auth/provider/signup` to work so that I can run my test as an authenticated user and I'm assuming this would be the first step. Otherwise, please guide me on how to authenticate the test client.

I've also tried with the settings in this repo's [tests/headless_only/settings.py](https://github.com/pennersr/django-allauth/blob/main/tests/headless_only/settings.py) but again a `409`.

**Comment by pennersr** [comment]
See:

```
    def handle(self, request, *args, **kwargs):
        self.sociallogin = flows.signup.get_pending_signup(self.request)
        if not self.sociallogin:
            return ConflictResponse(request)
```

So, your unit test does not have a session where a provider signup is pending.

**Comment by pennersr** [comment]
It is documented -- you are linking to the draft documentation.

https://docs.allauth.org/en/latest/headless/openapi-specification/#tag/Authentication:-Providers/paths/~1_allauth~1%7Bclient%7D~1v1~1auth~1provider~1signup/post

**Comment by Jsalaz1989** [comment]
> It is documented -- you are linking to the draft documentation.
> 
> https://docs.allauth.org/en/latest/headless/openapi-specification/#tag/Authentication:-Providers/paths/~1_allauth~1%7Bclient%7D~1v1~1auth~1provider~1signup/post

Oh of course *facepalm*

That said, could I please get an example of how to authenticate a client via google inside my test? I'm not able to make sense of  any of the [Authentication: Provider](https://docs.allauth.org/en/latest/headless/openapi-specification/#tag/Authentication:-Providers) endpoints for this purpose.

**Comment by pennersr** [comment]
See here: https://github.com/pennersr/django-allauth/blob/main/allauth/headless/socialaccount/tests/test_views.py#L210

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3925
