### ISSUE TITLE
[Contributing] Easy setup instructions

### ISSUE THREAD

**Issue by mecampbellsoup** [pennersr/django-allauth#3926]
While working on contributions like, most recently, https://github.com/pennersr/django-allauth/pull/3884, I find that I'm generally working on allauth briefly when I have time to switch away from my primary context, i.e. work.

At work, we use Poetry for our Python projects. Allauth seems to use `tox` as well as `setuptools`, etc.

It is difficult for me to remember how to "install" allauth after checking out the repo locally. I would like to propose adding some documentation around this to make it easier for contributors to quickly install and setup the code base.

**Comment by pennersr** [comment]
Moved to https://codeberg.org/allauth/django-allauth/issues/3926
