### ISSUE TITLE
Providers use overly generic app names

### ISSUE THREAD

**Issue by aehlke** [pennersr/django-allauth#393]
Using generic app names like "oauth", "facebook", "twitter" easily leads to conflicts with other apps. Django does not allow using the same app name, even if the app's path is different (it only considers the rightmost component). A lot of Django works, but some things fail, notably South migrations if you already have an app with migrations named the same as one of the allauth providers. In my case, our project has facebook and twitter apps already (my fault for naming them generically, but these aren't reusable components that I'm planning to open source, they're project-level apps).

I'm making a fork to rename all providers to e.g. facebook_provider, but I don't see how I can fix it for my case where I have to do this before even adding allauth at all to my project and also be able to migrate existing installs of allauth. I suspect it's not possible without backwards-compatibilty-breaking changes.

**Comment by pjdelport** [comment]
Note: #993 has a bit more discussion about this.

**Comment by dkarchmer** [comment]
I just upgraded from 0.20.0 to 0.23.0 (using Django 1.8.4). Everything seems to work after making the necessary changes, but as I understand the new instructions, I am supposed to also add 

'allauth.socialaccount.providers.twitter',
'allauth.socialaccount.providers.google',
'allauth.socialaccount.providers.facebook'

Only if I do this, I get the app label conflicts. I don't understand this well, but it seems like it is conflicting with the values I had before using 0.20.0. Do I need to add these providers explicitly? 

Is this related to this?

BTW, I really don't understand why these providers need to be implemented as Apps.

**Comment by Bartvds** [comment]
This is still happening and kind of a pain when adding allauth to existing projects.

**Comment by iMerica** [comment]
What was the decision on this? I'm getting started with All Auth today and it seems like the only way I can use it is to fork the project and rename the account app.

**Comment by fazpu** [comment]
Opened in 2013..., adding allauth to existing projects hurts due to this issue.

**Comment by ramon** [comment]
^ +1

**Comment by m-pasha** [comment]
have any ideas about where it will be solved?
I used in my django app allauth, but have app named 'account' too.

**Comment by jdeanwallace** [comment]
One way to workaround this issue is to make your conflicting Django app also look like an `allauth` provider. For example:

```python
# facebook/provider.py

# To avoid app naming conflicts between allauth providers and our local apps,
# let's make our local app look like a specific allauth provider.
# https://github.com/pennersr/django-allauth/issues/393
from allauth.socialaccount.providers.facebook.provider import provider_classes

```

```python
# example/settings.py

INSTALLED_APPS = [
    # ...
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "facebook",
    # ...
]
```

**Comment by amirhoseinbidar** [comment]
It's still the same issue for the account app in 2024. Changing the label of the account's app is not possible in my case due to hundreds of FK to my local account models. A real pain in the neck every time I want to use the all auth module since it appears as a dependency for other modules.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/393
