### ISSUE TITLE
Extend SignupInput with custom fields in allauth.headless

### ISSUE THREAD

**Issue by marcklose99** [pennersr/django-allauth#3934]
Hello,

First of all, thank you for your great work on this project.

I am currently using allauth.headless. I would like to extend the SignupInput with custom fields, similar to how one can extend the SignupForm when using regular allauth.

In a typical allauth setup, one can override the SignupForm as follows:

```
from allauth.account.forms import SignupForm

class MyCustomSignupForm(SignupForm):
    def save(self, request):
        user = super(MyCustomSignupForm, self).save(request)
        # Add your own processing here.
        return user
```

And in settings.py:
```
ACCOUNT_FORMS = {'signup': 'mysite.forms.MyCustomSignupForm'}
```
However, I am unclear on how to achieve similar functionality with SignupInput in allauth.headless.

Here is the current relevant code structure:

allauth.headless.account.urls.py:

```
from allauth.headless.account.urls import path, views

path(
    "signup",
    views.SignupView.as_api_view(client=client),
    name="signup",
),
```

allauth.headless.account.views.py:
```
from allauth.headless.account.views import APIView, method_decorator, rate_limit
from allauth.headless.account.inputs import SignupInput

@method_decorator(rate_limit(action="signup"), name="handle")
class SignupView(APIView):
    input_class = SignupInput

    def post(self, request, *args, **kwargs):
        ...
```

allauth.headless.account.inputs.py:
```
from allauth.headless.account.inputs import BaseSignupForm, inputs

class SignupInput(BaseSignupForm, inputs.Input):
    password = inputs.CharField()

    def clean_password(self):
        password = self.cleaned_data["password"]
        return get_account_adapter().clean_password(password)
```
I have already looked into the allauth.headless documentation but could not find information on extending the SignupInput class.
Is there an example that I might have overlooked which explains how to extend SignupInput for custom fields in allauth.headless?

Any assistance or example code snippets would be greatly appreciated.

Thank you for your help!

**Comment by pennersr** [comment]
As the headless functionality can also be used in a hybrid setup where both headless and regular signup is possible, the headless signup inputs automatically inherit custom signup form class you have setup. Do be sure to use `ACCOUNT_SIGNUP_FORM_CLASS` though, and not the `ACCOUNT_FORMS`. The former is meant for adding fields to the existing builtin form, whereas the latter is used to completely swap out the form.

Also check out this thread: https://github.com/pennersr/django-allauth/pull/2424#issuecomment-2122897015

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3934
