### ISSUE TITLE
When running the example, I run into: ModuleNotFoundError: No module named 'openid' allauth socialaccount

### ISSUE THREAD

**Issue by ShmuelTreiger** [pennersr/django-allauth#3935]
I'm trying to run the regular-django example. I pull the code from github, navigate to the subfolder, and run `docker compose up`. I'm met with the above error. I pulled different versions of the code and it seems [this commit](https://github.com/pennersr/django-allauth/commit/ff2f3626cd83bba9861d4982fecd1b6964c52d7d) breaks the example (i.e. the commit before it's working, this comit it breaks). I won't profess to under the project well enough to attempt a fix.

Full console output:
PS C:\Users\Shmuel\PycharmProjects\django-allauth\examples\regular-django> docker compose up
time="2024-06-30T16:19:51-07:00" level=warning msg="C:\\Users\\Shmuel\\PycharmProjects\\django-allauth\\examples\\regular-django\\docker-compose.yml: `version` is obsolete"
[+] Running 1/0
 ✔ Container regular-django-web-1  Created                                                                                                 0.0s 
Attaching to web-1
web-1  | python3 manage.py migrate
web-1  | Traceback (most recent call last):
web-1  |   File "/code/manage.py", line 11, in <module>
web-1  |     execute_from_command_line(sys.argv)                                                                                                
web-1  |   File "/usr/local/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line            
web-1  |     utility.execute()                                                                                                                  
web-1  |   File "/usr/local/lib/python3.12/site-packages/django/core/management/__init__.py", line 416, in execute                              
web-1  |     django.setup()                                                                                                                     
web-1  |   File "/usr/local/lib/python3.12/site-packages/django/__init__.py", line 24, in setup
web-1  |     apps.populate(settings.INSTALLED_APPS)                                                                                             
web-1  |   File "/usr/local/lib/python3.12/site-packages/django/apps/registry.py", line 124, in populate                                        
web-1  |     app_config.ready()                                                                                                                 
web-1  |   File "/code/allauth/socialaccount/apps.py", line 15, in ready
web-1  |     registry.load()                                                                                                                    
web-1  |   File "/code/allauth/socialaccount/providers/__init__.py", line 41, in load                                                           
web-1  |     provider_module = importlib.import_module(module_name)
web-1  |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                             
web-1  |   File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module                                                    
web-1  |     return _bootstrap._gcd_import(name[level:], package, level)                                                                        
web-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import                                                                      
web-1  |   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load                                                                   
web-1  |   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked                                                          
web-1  |   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked                                                                    
web-1  |   File "<frozen importlib._bootstrap_external>", line 995, in exec_module                                                              
web-1  |   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed                                                         
web-1  |   File "/code/allauth/socialaccount/providers/openid/provider.py", line 8, in <module>                                                 
web-1  |     from .utils import (                                                                                                               
web-1  |   File "/code/allauth/socialaccount/providers/openid/utils.py", line 5, in <module>                                                    
web-1  |     from openid.association import Association as OIDAssociation                                                                       
web-1  | ModuleNotFoundError: No module named 'openid'                                                                                          
web-1  | make: *** [Makefile:11: migrate] Error 1
web-1 exited with code 2

**Comment by OrazioOzziOsculati** [comment]
Hello, i have the same problem but with "run locally" mode. 
I cloned the code from the repo, created and activated the venv and installed the packages as the guide says 
When i try to send "python manage.py migrate" i get ModuleNotFoundError: No module named 'openid'

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3935
