### ISSUE TITLE
headless support for custom form fields?

### ISSUE THREAD

**Issue by PorridgeBear** [pennersr/django-allauth#3939]
I'm just in the middle of integrating headless with DRF + Simple JWT for API-based signup/login etc. 

I've used a custom adapter using `ACCOUNT_ADAPTER` to save a profile model linked to the User record created on signup, but I would like to pass and validate additional fields as part of the signup API call, e.g. first_name.

I found plenty of docs on how to use a custom class extending `SignupForm` and using the setting 

`ACCOUNT_FORMS = {"signup": "my.UserSignupForm"}` but this does not seem to get used.

I debugged out the class type for the `form` param passed to my custom adapter's `save_user` method

```
Message: 'AccountAdapter.save'
api-web-1  | Arguments: (<class 'allauth.headless.account.inputs.SignupInput'>,)
```

And see that it's not using the custom `UserSignupForm`.

I've had a look in this repository, particularly at whether there is different configuration for inputs vs. forms, but I didn't see much. 

My question is whether the custom forms configuration is meant to take effect for headless APIs, and if so, what the approach should be, and why I might be not seeing the right class coming into the custom adapter. 

Thanks for your time!

**Comment by pennersr** [comment]
See here on how to do that: https://github.com/pennersr/django-allauth/issues/3934#issuecomment-2198511888

**Comment by PorridgeBear** [comment]
Lovely stuff - that works perfectly 👍

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3939
