### ISSUE TITLE
Some language translation files need to be updated

### ISSUE THREAD

**Issue by caumons** [pennersr/django-allauth#394]
There are some `django.po` files inside `locale` dir that need to be updated, as some translations are not present or are marked as provisional by Poedit. Here is the list of the languages that need revision:
- es (missing translations)
- fr (missing translations)
- hr (some are marked as provisional)
- pt_BR (missing translations)
- pt_PT (missing translations)
- tr (missing translations)
- zh_CN (some are marked as provisional)

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/394
