### ISSUE TITLE
Add code time tolerance

### ISSUE THREAD

**Issue by edxavier** [pennersr/django-allauth#3954]
Please implement time tolerance for codes.

Ref: [django-otp](https://django-otp-official.readthedocs.io/en/stable/overview.html#django_otp.plugins.otp_totp.models.TOTPDevice.tolerance)

**tolerance**
The number of time steps in the past or future to allow. For example, if this is 1, we’ll accept any of three tokens: the current one, the previous one, and the next one. (Default: 1)

**Comment by Bhuvan2006** [comment]
Hi, I am new to **GitHub**, assign me to this issue I will solve this in some time.
Thank you.

**Comment by pennersr** [comment]
Moved to https://codeberg.org/allauth/django-allauth/issues/3954
