### ISSUE TITLE
`metadataValidUntil` cannot be configured for SAML via provider settings

### ISSUE THREAD

**Issue by alexanderjulmer** [pennersr/django-allauth#3955]
`python-saml` [supports setting a `metadataValidUntil`](https://github.com/SAML-Toolkits/python-saml?tab=readme-ov-file#settings) attribute which will define the `<md:EntityDescriptor validUntil="2024-07-11T13:59:38Z">` attribute.

Allauth's [`build_saml_config`](https://github.com/pennersr/django-allauth/blob/40117a711746be888528af69029cc5ed2692a7b2/allauth/socialaccount/providers/saml/utils.py#L95) does not read that attribute from the settings and does not set it. This results in the `validUntil` attribute being the [time of the request](https://github.com/SAML-Toolkits/python-saml/blob/245a0361a4852508676d37450f2e1dbe473851bf/src/onelogin/saml2/metadata.py#L55).

I propose to extend `build_saml_config` to also read an `metadata_valid_until` attribute from the settings.

Happy to set up a PR for this if needed.

**Comment by pennersr** [comment]
A pull request is welcome for this, thanks.

**Comment by pennersr** [comment]
Moved to https://codeberg.org/allauth/django-allauth/issues/3955
