### ISSUE TITLE
self.request.session[INTERNAL_RESET_SESSION_KEY] not persisted

### ISSUE THREAD

**Issue by davidu1975** [pennersr/django-allauth#3956]
Enabling CSRF protection in our Django app causes the value self.request.session[INTERNAL_RESET_SESSION_KEY] is "lost"

**Comment by pennersr** [comment]
I am sorry, but this ticket is not actionable. This not does not clearly pinpoint an issue in allauth. If the password reset wasn't working properly there would be a lot more complaints, so I do suspect this is a project specific issue.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3956
