### ISSUE TITLE
Third-Party Login Failure on the production server but it works fine on the localhost

### ISSUE THREAD

**Issue by muhameddadel** [pennersr/django-allauth#3958]
Here are my settings 
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            "client_id": os.getenv("GOOGLE_OAUTH2_CLIENT_ID"),
            "secret": os.getenv("GOOGLE_OAUTH2_CLIENT_SECRET"),
        },
        "SCOPE": [
            "profile",
            "email",
            "https://www.googleapis.com/auth/analytics.readonly",
        ],
        "AUTH_PARAMS": {
            "access_type": "offline",
            "prompt": "consent",
            "redirect_uri": f"https://{settings.HOST}/accounts/google/login/callback/"
        },
        "METHOD": "oauth2",
        "INIT_PARAMS": {"cookie": True},
        "STORE_TOKENS": True,
        "EXCHANGE_TOKEN": True,
        "VERIFIED_EMAIL": False,
    }
} everything works fine when I was trying on the localhost but after push the code to the server it gives me Third-party login Failure and I have checked the .env file and I've found everything setup well

**Comment by pennersr** [comment]
Closing -- this is a project specific deployment issue, not an issue in allauth.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3958
