### ISSUE TITLE
Users' email addresses can be leaked?

### ISSUE THREAD

**Issue by LukesFatherV** [pennersr/django-allauth#3959]
I'm encountering an issue with Django-Allauth that may be related to my custom signup form or a specific configuration setting. When a user attempts to sign up, the message "Confirmation email sent to [email]" is only displayed if the email is unique. If the email is already registered, this message is not shown.

This behavior could potentially lead to an email enumeration vulnerability, as it allows someone to test a list of emails and determine if they are registered based on whether the message appears.

I have observed this issue with Django-Allauth versions 0.57.0 and 0.63.3.

Here is my configuration.
ACCOUNT_EMAIL_REQUIRED = True 
ACCOUNT_AUTHENTICATION_METHOD = "email" 
ACCOUNT_CONFIRM_EMAIL_ON_GET = False 
ACCOUNT_EMAIL_VERIFICATION = "mandatory" 
ACCOUNT_MAX_EMAIL_ADDRESSES = 1 
ACCOUNT_USERNAME_REQUIRED = False 
ACCOUNT_PREVENT_ENUMERATION = True

**Comment by pennersr** [comment]
Fixed via c77de86b

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3959
