### ISSUE TITLE
Steam Provider doesn't appear in socialaccounts in Response from _allauth/browser/v1/config

### ISSUE THREAD

**Issue by lachdab** [pennersr/django-allauth#3960]
Hey, I'm trying to integrate Steam into my Django Rest + SolidJS Project. To understand how allauth headless works, I downloaded the react-spa example from the repo and added these things:

In INSTALLED_APPS:
"allauth.socialaccount.providers.openid",
"allauth.socialaccount.providers.steam",

In the Django admin dashboard, I added a social application with this data:
Provider: Steam
Name: Steam Provider
Client id: steam_api_key
Secret Key: steam_api_key

After starting the docker-compose and going to the signup page, I don't see any Steam Provider because providers is empty in the Response from _allauth/browser/v1/config.

Any help or insights would be greatly appreciated. Thank you!

**Comment by pennersr** [comment]
Steam is indeed currently not supported on headless. The OpenID protocol is retired, and Steam is the only provider still using that. OpenID support at headless is still a TODO.

**Comment by pennersr** [comment]
Moved to https://codeberg.org/allauth/django-allauth/issues/3960
