### ISSUE TITLE
account.EmailAddress: (models.W036) MySQL does not support unique constraints with conditions ref 3385

### ISSUE THREAD

**Issue by Coolmike890** [pennersr/django-allauth#3961]
This seems to be an error generated from using allauth and MySQL in Django. This issue is not fully resolved, as far as I can tell. The obvious solution would seem to be to migrate to PostgreSQL. However, my mySQLdump does not work (I think because of this - it's the only problem I can identify) , so I can't even back up the dbase. I'm looking for a workaround or patch so that I'll be able to migrate.

**Comment by pennersr** [comment]
It's not an error, see #3385 for background info on this

**Comment by Coolmike890** [comment]
I read it, and I understand your point of view. However, it's messed up my MySQL. I have no idea how to repair it so that I can export my data. That's an error from my point of view. If there's no fix, allauth should come with a giant warning NOT to use it with MySQL.

**Comment by pennersr** [comment]
You can use allauth with MySQL just fine. That W036 does not mess anything up, it's just a warning that the constraint is not actually checked by the database.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3961
