### ISSUE TITLE
Version 0.63.4 broke Cognito integration

### ISSUE THREAD

**Issue by msgre** [pennersr/django-allauth#3962]
Hi!

I am working on some demo project with minimal allauth setup and AWS Cognito as provider. I found, that latest upgrade 0.63.4 broke somehow comunication with AWS Cognito:

* When I click on "Sign In Via Amazon Cognito" button I am redirected to AWS Cognito login form
* After I fill credentials for user, I am redirected to "Third Party Login Failure" page (as you can see below, there is code parameter provided back from Cognito, so some sort of communication between allauth and provide must succeed)
![Snímek obrazovky 2024-07-11 v 9 59 31](https://github.com/pennersr/django-allauth/assets/64869/00a87e06-940d-4870-a2c1-6cc8db0b7d36)

When I downgrade the allauth package back to 0.63.3 it works again.

**Comment by msgre** [comment]
Hmmm, I tried to manualy revert some part in latest change and found, that reverting [`def __str__(self)`](https://github.com/pennersr/django-allauth/compare/0.63.3...0.63.4#diff-1146f4d8d70ea8972387442a0072045d763c9d9fe7c4d9b8dce39cf1c90de087R178) back to `return self.token` fixed the issue in 0.63.4.

Anyway, I have no idea why...

**Comment by pennersr** [comment]
Thanks for reporting. Fixed via 11fa4e8d / 0.63.5

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3962
