### ISSUE TITLE
Migration account.0006_emailaddress_lower throws unique error

### ISSUE THREAD

**Issue by steverecio** [pennersr/django-allauth#3965]
In migrating from 0.59.0 to 0.63.3 I ran into the following issue in migration [account.0006_emailaddress_lower](https://github.com/pennersr/django-allauth/blob/0.63.3/allauth/account/migrations/0006_emailaddress_lower.py#L16):

`psycopg.errors.UniqueViolation: duplicate key value violates unique constraint "users_user_email_key"`

**Comment by pennersr** [comment]
That suggests your database has users with the same email -- except that casing is different. That cannot be sorted out automatically and will need manual attention. Closing -- this is not an issue in allauth, if anything, the change made as part of that migration is to drop case sensitive email storage exactly to prevent issues like these.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3965
