### ISSUE TITLE
Example in the documentation provides logout with 'GET' method

### ISSUE THREAD

**Issue by tkozuch** [pennersr/django-allauth#3966]
Hi. I'm starting to use Django-allauth, and going through the documentation, I noticed:

> . The user is logged out only when the confirmation is received by means of a POST request.

https://docs.allauth.org/en/latest/account/views.html#logout

However in the example https://docs.allauth.org/en/latest/installation/examples.html#regular-django-project

I see that the logout is provided with a GET, is this a mistake?
![image](https://github.com/user-attachments/assets/e742fc87-034e-4eaf-ade6-aeec75b0d933)

also in the default template for managing account, 'Sign out' seems to be a GET, and not working. Wondering if this is intentional or an issue

**Comment by pennersr** [comment]
That is a link to a logout confirmation page, which uses a POST. Also see: `ACCOUNT_LOGOUT_ON_GET`

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3966
