### ISSUE TITLE
Not seeing commit in release tag(s)

### ISSUE THREAD

**Issue by mecampbellsoup** [pennersr/django-allauth#3967]
Hi @pennersr,

I have been waiting to see when https://github.com/pennersr/django-allauth/commit/27fcdf97e2b68655d91a27f748fb95e7613ca95b would be included in a release, but I'm still not seeing it despite the recent spate of release up to `0.63.6`: https://github.com/pennersr/django-allauth/commits/0.63.6

Am I missing something or was it perhaps overlooked?

Weirdly, when I do a comparison, it reports no missing commits though... https://github.com/pennersr/django-allauth/compare/master...0.63.6

This comparison does show some delta/difference, but not sure it's sensical: https://github.com/pennersr/django-allauth/compare/0.63.x...main

Thanks 😄

**Comment by pennersr** [comment]
Those weren't feature releases, but security releases. There hasn't been any new feature release, yet.

**Comment by mecampbellsoup** [comment]
So are you saying that https://github.com/pennersr/django-allauth/commit/27fcdf97e2b68655d91a27f748fb95e7613ca95b won't be included until there's a new release like `0.64.0`?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3967
