### ISSUE TITLE
"hackable accounts/ url" changes (_accounts_redirect) to middleware results in SynchronousOnlyOperation error on ASGI  

### ISSUE THREAD

**Issue by charlesobrien** [pennersr/django-allauth#3969]
There was a similar issue earlier this year - https://github.com/pennersr/django-allauth/issues/3612 - which was fixed in https://github.com/pennersr/django-allauth/pull/3614.

The changes to Middleware to implement hackable accounts/ urls (specifically the new redirect and reference to request.user) appears to have caused a regression.

> web    | Traceback (most recent call last):
web    |   File "/home/vscode/.local/lib/python3.12/site-packages/django/contrib/sessions/backends/base.py", line 244, in _get_session
web    |     return self._session_cache
web    |            ^^^^^^^^^^^^^^^^^^^
web    | AttributeError: 'SessionStore' object has no attribute '_session_cache'
web    | 
web    | During handling of the above exception, another exception occurred:
web    | 
web    | Traceback (most recent call last):
web    |   File "/home/vscode/.local/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
web    |     raise exc_info[1]
web    |   File "/home/vscode/.local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 42, in inner
web    |     response = await get_response(request)
web    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
web    |   File "/home/vscode/.local/lib/python3.12/site-packages/allauth/account/middleware.py", line 30, in middleware
web    |     return _accounts_redirect(request, response)
web    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web    |   File "/home/vscode/.local/lib/python3.12/site-packages/allauth/account/middleware.py", line 110, in _accounts_redirect
web    |     email_path if request.user.is_authenticated else login_path
web    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web    |   File "/home/vscode/.local/lib/python3.12/site-packages/django/utils/functional.py", line 251, in inner
web    |     self._setup()
web    |   File "/home/vscode/.local/lib/python3.12/site-packages/django/utils/functional.py", line 404, in _setup
web    |     self._wrapped = self._setupfunc()
web    |                     ^^^^^^^^^^^^^^^^^
web    |   File "/home/vscode/.local/lib/python3.12/site-packages/django/contrib/auth/middleware.py", line 37, in <lambda>
web    |     request.user = SimpleLazyObject(lambda: get_user(request))
web    |                                             ^^^^^^^^^^^^^^^^^
web    |   File "/home/vscode/.local/lib/python3.12/site-packages/django/contrib/auth/middleware.py", line 17, in get_user
web    |     request._cached_user = auth.get_user(request)
web    |                            ^^^^^^^^^^^^^^^^^^^^^^
web    |   File "/home/vscode/.local/lib/python3.12/site-packages/django/contrib/auth/__init__.py", line 209, in get_user
web    |     user_id = _get_user_session_key(request)
web    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web    |   File "/home/vscode/.local/lib/python3.12/site-packages/django/contrib/auth/__init__.py", line 62, in _get_user_session_key
web    |     return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
web    |                                                ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
web    |   File "/home/vscode/.local/lib/python3.12/site-packages/django/contrib/sessions/backends/base.py", line 55, in __getitem__
web    |     return self._session[key]
web    |            ^^^^^^^^^^^^^
web    |   File "/home/vscode/.local/lib/python3.12/site-packages/django/contrib/sessions/backends/base.py", line 249, in _get_session
web    |     self._session_cache = self.load()
web    |                           ^^^^^^^^^^^
web    |   File "/home/vscode/.local/lib/python3.12/site-packages/django/contrib/sessions/backends/db.py", line 55, in load
web    |     s = self._get_session_from_db()
web    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
web    |   File "/home/vscode/.local/lib/python3.12/site-packages/django/contrib/sessions/backends/db.py", line 34, in _get_session_from_db
web    |     return self.model.objects.get(
web    |            ^^^^^^^^^^^^^^^^^^^^^^^
web    |   File "/home/vscode/.local/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
web    |     return getattr(self.get_queryset(), name)(*args, **kwargs)
web    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web    |   File "/home/vscode/.local/lib/python3.12/site-packages/django/db/models/query.py", line 645, in get
web    |     num = len(clone)
web    |           ^^^^^^^^^^
web    |   File "/home/vscode/.local/lib/python3.12/site-packages/django/db/models/query.py", line 382, in __len__
web    |     self._fetch_all()
web    |   File "/home/vscode/.local/lib/python3.12/site-packages/django/db/models/query.py", line 1928, in _fetch_all
web    |     self._result_cache = list(self._iterable_class(self))
web    |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web    |   File "/home/vscode/.local/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
web    |     results = compiler.execute_sql(
web    |               ^^^^^^^^^^^^^^^^^^^^^
web    |   File "/home/vscode/.local/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1567, in execute_sql
web    |     cursor = self.connection.cursor()
web    |              ^^^^^^^^^^^^^^^^^^^^^^^^
web    |   File "/home/vscode/.local/lib/python3.12/site-packages/django/utils/asyncio.py", line 24, in inner
web    |     raise SynchronousOnlyOperation(message)
web    | django.core.exceptions.SynchronousOnlyOperation: You cannot call this from an async context - use a thread or sync_to_async.
web    | HTTP GET /accounts/ 500 [0.06, 127.0.0.1:58882]
web    | /home/vscode/.local/lib/python3.12/site-packages/allauth/account/middleware.py changed, reloading.
web    | Watching for file changes with StatReloader
web    | Performing system checks...
web    | 
web    | System check identified no issues (0 silenced).
web    | July 15, 2024 - 15:14:09
web    | Django version 5.1b1, using settings 'stack.config.settings.dev'
web    | Starting ASGI/Daphne version 4.1.2 development server at http://127.0.0.1:8000/
web    | Quit the server with CONTROL-C.
web    | Internal Server Error: /accounts/
web    | Traceback (most recent call last):
web    |   File "/home/vscode/.local/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
web    |     raise exc_info[1]
web    |   File "/home/vscode/.local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 42, in inner
web    |     response = await get_response(request)
web    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
web    |   File "/home/vscode/.local/lib/python3.12/site-packages/allauth/account/middleware.py", line 30, in middleware
web    |     return _accounts_redirect(request, response)
web    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web    |   File "/home/vscode/.local/lib/python3.12/site-packages/allauth/account/middleware.py", line 110, in _accounts_redirect
web    |     email_path if request.auser.is_authenticated else login_path
web    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web    | AttributeError: 'functools.partial' object has no attribute 'is_authenticated'
web    | HTTP GET /accounts/ 500 [0.04, 127.0.0.1:51034]
web    | /home/vscode/.local/lib/python3.12/site-packages/allauth/account/middleware.py changed, reloading.
web    | Watching for file changes with StatReloader
web    | Performing system checks...
web    | 
web    | System check identified no issues (0 silenced).
web    | July 15, 2024 - 15:15:04
web    | Django version 5.1b1, using settings 'stack.config.settings.dev'
web    | Starting ASGI/Daphne version 4.1.2 development server at http://127.0.0.1:8000/
web    | Quit the server with CONTROL-C.
web    | Internal Server Error: /accounts/
web    | Traceback (most recent call last):
web    |   File "/home/vscode/.local/lib/python3.12/site-packages/django/contrib/sessions/backends/base.py", line 244, in _get_session
web    |     return self._session_cache
web    |            ^^^^^^^^^^^^^^^^^^^
web    | AttributeError: 'SessionStore' object has no attribute '_session_cache'
web    | 
web    | During handling of the above exception, another exception occurred:
web    | 
web    | Traceback (most recent call last):
web    |   File "/home/vscode/.local/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
web    |     raise exc_info[1]
web    |   File "/home/vscode/.local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 42, in inner
web    |     response = await get_response(request)
web    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
web    |   File "/home/vscode/.local/lib/python3.12/site-packages/allauth/account/middleware.py", line 30, in middleware
web    |     return _accounts_redirect(request, response)
web    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web    |   File "/home/vscode/.local/lib/python3.12/site-packages/allauth/account/middleware.py", line 110, in _accounts_redirect
web    |     email_path if request.user.is_authenticated else login_path
web    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web    |   File "/home/vscode/.local/lib/python3.12/site-packages/django/utils/functional.py", line 251, in inner
web    |     self._setup()
web    |   File "/home/vscode/.local/lib/python3.12/site-packages/django/utils/functional.py", line 404, in _setup
web    |     self._wrapped = self._setupfunc()
web    |                     ^^^^^^^^^^^^^^^^^
web    |   File "/home/vscode/.local/lib/python3.12/site-packages/django/contrib/auth/middleware.py", line 37, in <lambda>
web    |     request.user = SimpleLazyObject(lambda: get_user(request))
web    |                                             ^^^^^^^^^^^^^^^^^
web    |   File "/home/vscode/.local/lib/python3.12/site-packages/django/contrib/auth/middleware.py", line 17, in get_user
web    |     request._cached_user = auth.get_user(request)
web    |                            ^^^^^^^^^^^^^^^^^^^^^^
web    |   File "/home/vscode/.local/lib/python3.12/site-packages/django/contrib/auth/__init__.py", line 209, in get_user
web    |     user_id = _get_user_session_key(request)
web    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web    |   File "/home/vscode/.local/lib/python3.12/site-packages/django/contrib/auth/__init__.py", line 62, in _get_user_session_key
web    |     return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
web    |                                                ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
web    |   File "/home/vscode/.local/lib/python3.12/site-packages/django/contrib/sessions/backends/base.py", line 55, in __getitem__
web    |     return self._session[key]
web    |            ^^^^^^^^^^^^^
web    |   File "/home/vscode/.local/lib/python3.12/site-packages/django/contrib/sessions/backends/base.py", line 249, in _get_session
web    |     self._session_cache = self.load()
web    |                           ^^^^^^^^^^^
web    |   File "/home/vscode/.local/lib/python3.12/site-packages/django/contrib/sessions/backends/db.py", line 55, in load
web    |     s = self._get_session_from_db()
web    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
web    |   File "/home/vscode/.local/lib/python3.12/site-packages/django/contrib/sessions/backends/db.py", line 34, in _get_session_from_db
web    |     return self.model.objects.get(
web    |            ^^^^^^^^^^^^^^^^^^^^^^^
web    |   File "/home/vscode/.local/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
web    |     return getattr(self.get_queryset(), name)(*args, **kwargs)
web    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web    |   File "/home/vscode/.local/lib/python3.12/site-packages/django/db/models/query.py", line 645, in get
web    |     num = len(clone)
web    |           ^^^^^^^^^^
web    |   File "/home/vscode/.local/lib/python3.12/site-packages/django/db/models/query.py", line 382, in __len__
web    |     self._fetch_all()
web    |   File "/home/vscode/.local/lib/python3.12/site-packages/django/db/models/query.py", line 1928, in _fetch_all
web    |     self._result_cache = list(self._iterable_class(self))
web    |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web    |   File "/home/vscode/.local/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
web    |     results = compiler.execute_sql(
web    |               ^^^^^^^^^^^^^^^^^^^^^
web    |   File "/home/vscode/.local/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1567, in execute_sql
web    |     cursor = self.connection.cursor()
web    |              ^^^^^^^^^^^^^^^^^^^^^^^^
web    |   File "/home/vscode/.local/lib/python3.12/site-packages/django/utils/asyncio.py", line 24, in inner
web    |     raise SynchronousOnlyOperation(message)
web    | django.core.exceptions.SynchronousOnlyOperation: You cannot call this from an async context - use a thread or sync_to_async.`

**Comment by pennersr** [comment]
Unfortunately, async is currently not part o the test suite. #3970 is a potential fix for this issue, though it does require Django 5.0. Can you please verify if this fixes your issue?

**Comment by charlesobrien** [comment]
@pennersr Just did a quick test on Django 5.1b1 / Daphne and https://github.com/pennersr/django-allauth/pull/3970 appears to resolve the issue.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3969
