### ISSUE TITLE
LinkedIn API not returning fullprofile data

### ISSUE THREAD

**Issue by samgclarke** [pennersr/django-allauth#397]
Using the LinkedIn API, and adding `'r_fullprofile'` to the `SCOPE` in `settings.py`, I get the authorization page asking for access to the full profile. However, when I inspect the `extra_data` dict there is no full profile data.

![authorize_linkedin](https://f.cloud.github.com/assets/3639944/1250071/6777c1a8-2aed-11e3-951e-e43133464fc3.png)

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/397
