### ISSUE TITLE
[MFA] Add totp svg to headless ManageTOTPView

### ISSUE THREAD

**Issue by mecampbellsoup** [pennersr/django-allauth#3976]
Similarly to #3884, it would be nice for allauth to provide a ready-to-go SVG when managing TOTP (i.e. requesting to enable it) via the headless API.

Again as with #3884 and `totp_url`, the non-headless API already [includes this data in its responses](https://github.com/pennersr/django-allauth/blob/7a887bd3c747e74ae1ddeb815662acc08465687d/allauth/mfa/totp/views.py#L43-L44). So this issue is about furthering the parity between headless and non-headless responses' data.

@pennersr would you like to see both `totp_svg` and `totp_svg_data_uri` added to the headless response? Or "other"... 😏

**Comment by pennersr** [comment]
I can imagine the need for this, but do we really need both? Constructing data URIs is rather trivial to do in JS.

**Comment by mecampbellsoup** [comment]
Hey, no doubt about that, but I don't trust our frontend team... 🤣 

For now I sorta' copy-pasted the code that makes the `totp_svg_data_uri` (w/ base64-encoded SVG data) and add it on before serving the response to our FE. So this isn't really a big deal to me/I have an easy workaround.

**Comment by pennersr** [comment]
But on the frontend side, it is really little more than:

```
npm i qrcode
QRCode.toDataURL(meta.totp_url)
```
You will also be able to control the width/height of the output image. All in all, as the QR code is about presentation & form, I think the frontend is better positioned to generate the QR code itself in a headless setup. And, when adding the SVG, it raises questions like why not a data URI, why not a PNG? All in all this is a bit of a slippery slope, I prefer not to go that route.

**Comment by mecampbellsoup** [comment]
You've convinced me, good points!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3976
