### ISSUE TITLE
Cannot schedule new futures after interpreter shutdown

### ISSUE THREAD

**Issue by jackkinsella** [pennersr/django-allauth#3982]
I started seeing this one rarely (about 3 people per day) after updating from `0.55.2` to `0.63.3`

I also have `django-allauth[socialaccount]==0.63.3` installed, in case that matters.

Oddly, this one leaves no stack-trace other than giving the message "cannot schedule new futures after interpreter shutdown"

 I only know about it via Sentry alerts in production.

<img width="339" alt="Screenshot 2024-07-19 at 05 57 59" src="https://github.com/user-attachments/assets/2d975b03-7e91-455a-98ea-34a611ddcd43">

**Comment by pennersr** [comment]
Are you using allauth in an async context? What python version are you running?

**Comment by jackkinsella** [comment]
So we have a WSGI server that manages all auth (e.g. logging in and logging out etc.) However we also have a small ASGI server that handles web-sockets.

These errors were logged from our wsgi server... however when I digged into the exception, I saw the logging came from our web_sockets module which is responsible for sending web sockets payloads (via channels) to redis for the asgi server to send to user connections.

We don't have full stack traces here yet, but looking at the file, I see this line of code `async_to_sync(channel_layer.group_send)(group_name, {'type': message_type, 'payload': payload})` which sounds very async to me. I will add better logging to find out more about what's happening.

At this point, I'm thinking it's more likely that the mention of the allauth URLs might be a red herring and something else is up , perhaps web sockets aysnc code that gets triggered by some system in our auth flow.

That sad, I'm happy to run experiments on our code (extra logging etc.) if you have any suspicions about this being related to allauth

**Comment by pennersr** [comment]
allauth itself is not doing any async. The only thing related in this area is the account middleware. This middleware did not exist in 0.55. It does recognize whether or not it is running in an async context, see:

https://github.com/pennersr/django-allauth/blob/main/allauth/account/middleware.py#L22

So maybe, that is related.

**Comment by pennersr** [comment]
This issue is not actionable on this end, so I am going to close this. If you do find something pointing to allauth, please reopen.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3982
