### ISSUE TITLE
Headless endpoints don't respect APPEND_SLASH Django setting

### ISSUE THREAD

**Issue by gleniat** [pennersr/django-allauth#3992]
Hi all,
thanks for the great library.

When the Django global setting APPEND_SLASH is set to `True` (which is a default Django value):

1. the headless endpoints should be switched to a trailing slash ones
2. non slash headless URLs should be redirected to the slash appended URLs

https://docs.djangoproject.com/en/dev/ref/settings/#append-slash value

So default URLs
```
    "account_confirm_email": "/account/verify-email/{key}",
    "account_reset_password": "/account/password/reset",
    "account_reset_password_from_key": "/account/password/reset/key/{key}",
    "account_signup": "/account/signup",
    "socialaccount_login_error": "/account/provider/callback",
```
become
```
    "account_confirm_email": "/account/verify-email/{key}/",
    "account_reset_password": "/account/password/reset/",
    "account_reset_password_from_key": "/account/password/reset/key/{key}/",
    "account_signup": "/account/signup/",
    "socialaccount_login_error": "/account/provider/callback/",
```
automatically.

maybe put a simple helper function somewhere

```python
def adjust_trailing_slash(raw_url):
    """
    Adjusts the URL to ensure it either always ends with a trailing slash when settings.APPEND_SLASH is True
    or never ends with a trailing slash when settings.APPEND_SLASH is False.
    
    Parameters:
    raw_url (str): The original URL that needs adjustment.

    Returns:
    str: The adjusted URL with or without a trailing slash based on the settings.APPEND_SLASH flag.
    """
    if settings.APPEND_SLASH:
        if not raw_url.endswith('/'):
            raw_url += '/'
    else:
        if raw_url.endswith('/'):
            raw_url = raw_url[:-1]
    return raw_url
```

and add a line to
https://github.com/pennersr/django-allauth/blob/301324e3ed2bf7c95987f24625ee8ebd7480ce85/allauth/core/internal/httpkit.py#L84
```python
        url = headless_settings.FRONTEND_URLS.get(urlname)
        url = adjust_trailing_slash(url)
```

**Comment by pennersr** [comment]
> So default URLs ... become ...

I don't understand the issue:

- First, there are no default URLs. `HEADLESS_FRONTEND_URLS` is empty by default.
- Second, `HEADLESS_FRONTEND_URLS` is meant to point to URLs of your single-page application. As that is typically not served by Django, I don't see why a backend setting like `APPEND_SLASH` should have any influence on the frontend.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3992
