### ISSUE TITLE
Cannot add security key  (webauthn)

### ISSUE THREAD

**Issue by inc-ali** [pennersr/django-allauth#3994]
Hi, 

I really appreciate your work on adding fido2 support! I tried to test it locally, but I could not add a new security key

**Here is what I did:**
1. I installed the package using `pip install git+https://github.com/pennersr/django-allauth.git@main#egg=django-allauth[mfa]`
2. Add `MFA_SUPPORTED_TYPES = ["totp", "webauthn", "recovery_codes"]` and `MFA_PASSKEY_LOGIN_ENABLED = True` to settings
3. Add `MFA_WEBAUTHN_ALLOW_INSECURE_ORIGIN = True` to local settings
4. Sign in with a local account using email and password
5. Navigate to `http://localhost:8000/accounts/2fa/webauthn/add/`
6. Provide a name for my key and checking the checkmark (tried both)
7. Click on the `Add` button

**What actually happend**
No post request was send to the backend. Instead the js console is throwing the following error.

```javascript
[Error] Error: Missing key: displayName — webauthn-json.js:88
	dispatchError (webauthn.js:8)
	(anonymous function) (webauthn.js:33)
```

This is the `credentials` json that gets passed to `webauthnJSON.create`

```json
{
    "publicKey": {
        "rp": {
            "name": "example.com",
            "id": "localhost"
        },
        "user": {
            "name": "user@example.com",
            "id": "OQ"
        },
        "challenge": "redacted",
        "pubKeyCredParams": [
            {
                "type": "public-key",
                "alg": -7
            },
            {
                "type": "public-key",
                "alg": -8
            },
            {
                "type": "public-key",
                "alg": -35
            },
            {
                "type": "public-key",
                "alg": -36
            },
            {
                "type": "public-key",
                "alg": -37
            },
            {
                "type": "public-key",
                "alg": -257
            },
            {
                "type": "public-key",
                "alg": -47
            }
        ],
        "excludeCredentials": [],
        "authenticatorSelection": {
            "residentKey": "discouraged",
            "userVerification": "discouraged",
            "requireResidentKey": false
        },
        "extensions": {
            "credProps": true
        }
    }
}
```

**What I expected to happen**
That I get prompted to add a new security key by my device (macOS)

Just a side note for the docs: I had to search through the docs to find I had to add step 3. Also I usually develop using `127.0.0.1` instead of `localhost`. But only on `localhost` I was prompted to provide my security key when I click on `Sign in with a passkey` (the flow seems to work, but it fails, since I don't have a passkey setup due to the issue above). 
Would it help if I add a PR to provide a dedicated page for working with passkeys?

**Comment by pennersr** [comment]
I have no explanation why this:

```
        "user": {
            "name": "user@example.com",
            "id": "OQ"
        },
```

does not contain a `displayName`. It's definitely handed over, and I do see it showing up just fine.

https://github.com/pennersr/django-allauth/blob/main/allauth/mfa/adapter.py#L156

So without being able to reproduce this there is little I can do here. Hope you can do a little bit of debugging to find out what is going on.

What fido2 package are you using?

**Comment by inc-ali** [comment]
I was using `fido2==1.1.3`.

Thanks to your hint I could find the issue, which was a misconfiguration from my side: 

I am using a custom user model and I did not set `ACCOUNT_USER_MODEL_USERNAME_FIELD`, hence `user_display(user)` returned `None`

Would it make sence to throw an exception at `get_public_key_credential_user_entity` instead of continuing if required data is missing?

**Comment by pennersr** [comment]
I think it would be better to handle this in `user_display()`. It is supposed to return a `str`, and apparently in your case it returns `None`:

```
return getattr(user, app_settings.USER_MODEL_USERNAME_FIELD)
```

So your custom model does have a `username` attribute, but it is empty? I was expecting this to throw an exception if your model has no username?

**Comment by pennersr** [comment]
This would address the issue:

```
def default_user_display(user) -> str:
    ret = None
    if app_settings.USER_MODEL_USERNAME_FIELD:
        ret = getattr(user, app_settings.USER_MODEL_USERNAME_FIELD)
    if not ret:
        ret = force_str(user)
    return ret
```

**Comment by pennersr** [comment]
Fixed via 80d50e33

**Comment by inc-ali** [comment]
> I think it would be better to handle this in `user_display()`. It is supposed to return a `str`, and apparently in your case it returns `None`:
> 
> ```
> return getattr(user, app_settings.USER_MODEL_USERNAME_FIELD)
> ```
> 
> So your custom model does have a `username` attribute, but it is empty? I was expecting this to throw an exception if your model has no username?

@pennersr correct. I am using `email` as the identifying field, so that in my case `user.userame` exists, but is `None`. As you described in the _Advanced Usage_ section, I should've set `ACCOUNT_USER_MODEL_USERNAME_FIELD = None`.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3994
