### ISSUE TITLE
Google+ Sign In

### ISSUE THREAD

**Issue by toolkmit** [pennersr/django-allauth#400]
In django-allauth, I am trying to use google plus sign in (as recommended by google - https://developers.google.com/accounts/docs/OAuth2Login) instead of the standard google Oauth2 sign in.  

For the most part I have this working -- I changed the SCOPE to be 'https://www.googleapis.com/auth/plus.login' instead of 'https://www.googleapis.com/auth/userinfo.profile', and the user is able to authenticate with google plus.  However, I am unable to get some user data such as first name and last name.  

Looking at the code, I believe this is because of the 'profile_url' within the  GoogleOAuth2Adapter class.  To work with Google plus it should be 'https://www.googleapis.com/plus/v1/people/me' instead of 'https://www.googleapis.com/oauth2/v1/userinfo'.  

Is there a way to override the profile_url or is there another workaround?

**Comment by aaugustin** [comment]
It took some trial and error but I found that things just work with these scopes:

```python
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'https://www.googleapis.com/auth/plus.login',
            'https://www.googleapis.com/auth/userinfo.email',
            'https://www.googleapis.com/auth/userinfo.profile',
        ],
    }
}
```

Including `https://www.googleapis.com/auth/plus.login` should allow using the Google+ APIs (I haven't tested that yet).

**Comment by derek-adair** [comment]
Probably worth closing as ... well... Google Plus is going away.

But hey maybe not.

**Comment by pennersr** [comment]
Closing -- dated

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/400
