### ISSUE TITLE
Feature request: MFA remember device key

### ISSUE THREAD

**Issue by bufke** [pennersr/django-allauth#4000]
Thanks for adding all the fantastic MFA options. Many sites, such as Google Apps, provide MFA with an option to "remember the device" which differs from stay logged in. A user may have an expired session, but can skip the MFA step on the device during login. One implementation of this is to store a code somewhere on the device, perhaps localstorage. Then the code can automatically be provided and MFA is skipped as far as the end user is concerned. There are security implications. What if the device is stolen? Is the code encrypted (probably not). It wouldn't be much different from stealing a TOTP secret. One hopes the browser is sandboxed and applications cannot simply open it's storage and read the key. If they could do so - they could just read the session cookie and save some trouble. I'm curious on your thoughts for this feature.

**Comment by pennersr** [comment]
Moved to https://codeberg.org/allauth/django-allauth/issues/4000

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/4000#issuecomment-3093874
