### ISSUE TITLE
Release tag format changed

### ISSUE THREAD

**Issue by mecampbellsoup** [pennersr/django-allauth#4003]
<img width="358" alt="image" src="https://github.com/user-attachments/assets/e6e451b6-7b6a-4f86-94f2-cf1fe63cfd56">

**Comment by pennersr** [comment]
This is documented in the changelog.

**Comment by mecampbellsoup** [comment]
> Additionally, 64 is a nice round number. Therefore, the version numbering is changed from 0.x.y to x.y.z. We will use a loose form of semantic versioning.

Just wondering - how come you didn't go with say `1.0.0` so it does (at least more closely?) sem ver...?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/4003
