### ISSUE TITLE
Adopt Semvar

### ISSUE THREAD

**Issue by dpgraham4401** [pennersr/django-allauth#4007]
First, thank you for your work on this amazing package. 

I recently saw the [64.0.0 changelog](https://allauth.org/news/2024/07/django-allauth-64.0.0-released/) and #4003. I got a laugh from the reasoning behind incrementing 64 major versions. However to quote the changelong: 

> We will use a loose form of semantic versioning. However, please be aware that feature releases may occasionally include minor documented backwards incompatibilities. Always read the release notes before upgrading.

If allauth is (well) past it's 1.0.0 release, why not increment the major version when there are backward incompatible changes in future releases? Obviously allauth is not afraid of incrementing the major version lol. 

Yes, we always plan to read the changelog before migrating versions, but for something as central as authorization/authentication we'd like to keep surprises to a minimum. I have this information, but 6 months from now, a coworker (or my future self) may not be aware that the new patch has a breaking change.

Are there things that would prevent allauth from adopting semvar now it's past 1.0.0?

**Comment by pennersr** [comment]
> If allauth is (well) past it's 1.0.0 release, why not increment the major version when there are backward incompatible changes in future releases?

That is the plan. The challenge will be how to define what is a breaking change. For example, consider some utility function over at `allauth.account.utils`. Suppose it gets changed/removed, would that be a backward incompatible change? Upstream projects are importing just about anything from allauth, so you could argue "yes". On the other hand, if it is only some utility function used mostly internally, the answer could just as well be "no". Similarly, suppose a template gets passed a new context var and used that to render something. Is that a breaking change? Possibly "yes" if you forked the templates, but "no" if you just use allauth out of the box. All in all, applying semver is really hard with a package the size of allauth. 

PS: Note that Django is not using semver.

**Comment by dpgraham4401** [comment]
> The challenge will be how to define what is a breaking change. For example, consider some utility function over at allauth.account.utils. Suppose it gets changed/removed, would that be a backward incompatible change?

I see an answer that's relatively black and white. Any backward incompatible change to a part of allauth's _publically documented API_ would require a major version update. Utility functions in `allauth.account.utils` that are not part of the packages publicly documented API would not constitute a breaking change compatibility. 

We can codify this information in the source as well with things like the [`__all__`](https://docs.python.org/3/tutorial/modules.html#importing-from-a-package) and private functions, which obviosly don't stop downstream systems from using those classes/function but that' s on them. Like I see `allauth.account.utils.get_next_redirect_url` is a public function but it's not documented (inline or online).

> Similarly, suppose a template gets passed a new context var and uses that to render something. Is that a breaking change?

I don't have an exmaple offhand, but other django pakcages follow semvar and package reusable templates. Generally it seems that as long as context vars are not renamed or removed, then that would not constitute a breaking changes. Similar to adding a new attribute to class that downstream users are expected to subclass, adding a new class attribute would not constitute a breaking change (even though it's possible a downstream user already has that attribute in a child class).

- This does seem like a gray area, but either way, there's no harm in incrementing the major version if the allauth team  decided it should mean a breaking change. 

I would love to help implement, but obviously would want your blessing before beginning.

**Comment by pennersr** [comment]
> I see an answer that's relatively black and white

I am not sure it's that clear cut. For example, `__all__` only affects `from foo import *`. Function `foo.bar` could still be properly documented. Is it documented somewhere that not adding something to `__all__` makes it semver exempt? 

Private functions are normally the way to go. But, problem there is that allauth consists of multiple subpackages, and a function `allauth.some_app.f` may be perfectly usable internally by `allauth.some_other_app`, but it is not intended to be used publically. Now, `f` could be renamed to `_f`, but I quite dislike that, as it really suggests it is `some_app` private, and `some_other_app` importing `_f` feels wrong. To mitigate this, works is already in progress to move things over to packages clearly labeled as `internal`.

> I would love to help implement, but obviously would want your blessing before beginning.

What would you propose to implement? As mentioned, I have some doubts on the `__all__` approach. And, `internal` is already set in motion. So I am not sure what more can be done at this point.

**Comment by dpgraham4401** [comment]
Moving existing public/semi-public functions into `internal`, marking those functions/classes as private (e.g., `def _my_function()`, and using the `@warnings.deprecated()` (see [PEP 702](https://peps.python.org/pep-0702/)) decorator in the future is what I had in mind. Sounds like allauth is already on it's way to this. Thank you the quick responses @pennersr!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/4007
