### ISSUE TITLE
[headless.account.views.LoginView] Prevent login while logged in?

### ISSUE THREAD

**Issue by mecampbellsoup** [pennersr/django-allauth#4008]
Similarly to https://github.com/pennersr/django-allauth/issues/3916, what is allauth's stance on permitting or prohibiting `POST /login` calls when the request is already authenticated?

We observe that currently there is nothing preventing it, and we are just curious if that is intentional.

**Comment by pennersr** [comment]
It's not intentional. It's not a real issue either. Still, it would be good to return a 409 as well here for consistency. You could argue that this is a backwards incompatible change, but it's a corner case really, the frontend should not be showing an option to login anyway.

**Comment by pennersr** [comment]
Fixed via f724e281

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/4008
