### ISSUE TITLE
httpkit serialize/deserialize does not preserve `is_secure()`, preventing SAML login

### ISSUE THREAD

**Issue by SimonTagne** [pennersr/django-allauth#4009]
My setup is django running through uwsgi, with an nginx https reverse proxy in front of it (with `uwsgi_pass`).

The ACS URL is correctly setup to the `https://.../saml/sso/acs/` endoint on both the IdP and the provider. The django request objects are therefore `django.core.handlers.wsgi.WSGIRequest` instances which correctly return their schemes as https instead of plain `django.http.HTTPRequest`. However, this is not preserved by the `httpkit.serialize_request`/`httpkit.deserialize_request` calls between the `ACSView` and `FinishACSView`, since the deserialization starts from a plain `HTTPRequest`. The ACS validation then fails with `invalid_response: The response was received at http://.../saml/sso/acs/ instead of https://.../saml/sso/acs/`

The easiest fix would be to store the result of `is_secure()` in `serialize_request()` and override `is_secure()` with a lambda in `deserialize_request()`. However, I'm not familiar enough with the reauthentication flow that also uses this code to assess if it would have any negative impact.

Alternatively we could subclass `HttpRequest` in `FinishACS` to reimplement `_get_scheme`.

I would be happy to submit a PR with any of those solutions if it helps

**Comment by pennersr** [comment]
Django's `is_secure()` is implemented as follows:

``` python
    def is_secure(self):
        return self.scheme == "https"

    @property
    def scheme(self):
        if settings.SECURE_PROXY_SSL_HEADER:
            try:
                header, secure_value = settings.SECURE_PROXY_SSL_HEADER
            except ValueError:
                raise ImproperlyConfigured(
                    "The SECURE_PROXY_SSL_HEADER setting must be a tuple containing "
                    "two values."
                )
            header_value = self.META.get(header)
            if header_value is not None:
                header_value, *_ = header_value.split(",", 1)
                return "https" if header_value.strip() == secure_value else "http"
        return self._get_scheme()
```

So, `is_secure` checks `scheme`, and that uses `META`, which is properly (de)serialized. So I am not sure why this is not working in your case -- can you do a little bit of debugging here?

**Comment by SimonTagne** [comment]
I don't have anything configured in `settings.SECURE_PROXY_SSL_HEADER`, so Django's `is_secure()` returns `_get_scheme()` on the last line.

That method is implemented differently in the base `HTTPRequest` and in `WSGIRequest`:
`HTTPRequest:`
```python
    def _get_scheme(self):
        """
        Hook for subclasses like WSGIRequest to implement. Return 'http' by
        default.
        """
        return "http"
```

`WSGIRequest`:
```python
    def _get_scheme(self):
        return self.environ.get("wsgi.url_scheme")
```

Since the WSGI environment is saved in `META` I can add
```python
SECURE_PROXY_SSL_HEADER = ("wsgi.url_scheme", "https")
```
to the settings as a workaround (I just confirmed that it works)

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/4009
