### ISSUE TITLE
[Headless Reauth] "Needs to reauthenticate" view?

### ISSUE THREAD

**Issue by mecampbellsoup** [pennersr/django-allauth#4019]
For sensitive endpoints like MFA activation/deactivation, reauthentication is required if the user hasn't authenticated within `app_settings.REAUTHENTICATION_TIMEOUT` from the current time, e.g. https://github.com/pennersr/django-allauth/blob/9440c0a9cef050be11bbad533ea95b11a5f45fee/allauth/mfa/totp/internal/flows.py#L19

This makes for a slightly clunky UX. In the case of activating MFA, we:

1. Show the QR code the user scans to generate an OTP client;
2. in that same UI the user enters the corresponding OTP code.

Then if they submit that form but reauthentication is required, we get a 401 Unauthorized back from allauth and have to repeat the process after the enter their password.

A better UX would be to query some endpoint before entering the "sensitive actions here" UI with the buttons to enable MFA, change password, etc.

For now, I can query the current session, and replicate the logic in `reauthentication_required`, i.e. comparing the current time to the last authenticated timestamp, but I was curious if there was appetite to implement this within allauth, where by this I mean something like `GET /reauthenticate` to go along with the [`POST` endpoint](https://docs.allauth.org/en/latest/headless/openapi-specification/#tag/Authentication:-Account/paths/~1_allauth~1%7Bclient%7D~1v1~1auth~1reauthenticate/post).

**Comment by kmahelona** [comment]
I had a similar problem. I thought `/_allauth/{client}/v1/auth/session` would give me a 401 if I needed to re-authenticate. An endpoint that tells me whether reauthentication will be required would be helpful rather than having to intercept 401s all the time.

**Comment by pennersr** [comment]
> A better UX would be to query some endpoint ...
> where by this I mean something like GET /reauthenticate to go along with the [POST endpoint](https://docs.allauth.org/en/latest/headless/openapi-specification/#tag/Authentication:-Account/paths/~1_allauth~1%7Bclient%7D~1v1~1auth~1reauthenticate/post).

Could you add a more detailed proposal? Do you mean to introduce some "did-recently-authenticate" endpoint ? But suppose it returns "yes", that's no guarantee that your call to the sensitive action will succeed.

**Comment by mecampbellsoup** [comment]
> > A better UX would be to query some endpoint ...
> > where by this I mean something like GET /reauthenticate to go along with the [POST endpoint](https://docs.allauth.org/en/latest/headless/openapi-specification/#tag/Authentication:-Account/paths/~1_allauth~1%7Bclient%7D~1v1~1auth~1reauthenticate/post).
> 
> Could you add a more detailed proposal? Do you mean to introduce some "did-recently-authenticate" endpoint ? But suppose it returns "yes", that's no guarantee that your call to the sensitive action will succeed.

As I mentioned, it might simply encapsulate/expose the logic of [`@reauthentication_required`](https://github.com/pennersr/django-allauth/blob/b242ded229f3e00cc7ccf7751c9cc23ac6d7eed4/allauth/account/decorators.py#L52-L77):

> For now, I can query the current session, and replicate the logic in `reauthentication_required`, i.e. comparing the current time to the last authenticated timestamp

**Comment by pennersr** [comment]
Moved to https://codeberg.org/allauth/django-allauth/issues/4019
