### ISSUE TITLE
Google refresh token not saved

### ISSUE THREAD

**Issue by Gwildor** [pennersr/django-allauth#403]
As I mentioned in #400, django-allauth doesn't seem to save the refresh token for the Google provider. When I connect my account with Google, the token is saved in SocialToken, but the token_secret field stays blank. Using the token to connect to Google's API works fine, until the OAuth2 token has expired. Then it should attempt to get a new token using the refresh token, but that obviously fails because it hasn't any, resulting in an exception. This flow works fine for Twitter: here I've seen the token being refreshed once it expired.

I get the following exception when trying to do something with Google's API a little over an hour after I connect my account:

```
Exception Type:     AccessTokenRefreshError
Exception Value:    invalid_request
```

I'm running the latest commit (6171a7f401) using Django 1.4.8. The exception is raised by google-api-python-client 1.2 on line 710 in oauth2client/client.py.

**Comment by jsanchezs** [comment]
@Gwildor Thank you very much for that solution =D

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/403
