### ISSUE TITLE
Headless Social account Google OAuth fails with error unknown

### ISSUE THREAD

**Issue by Altair2169** [pennersr/django-allauth#4041]
I have been trying to integrate Social Account Sign in with Headless and a React SPA following the example, my third party redirect to Google is succeeding and I am redirected to my backend after completing the sign in but AllAuth then hits my `socialaccount_login_error` URL with these params `account/provider/callback?error=unknown&error_process=login`, and I'm not receiving any session cookies from Django indicating a successful login (do note, I am using Django's Session management and not AllAuth's) , I'm not really sure how to handle this case since despite verbose logging, django isnt logging anything and the URL param is just indicating `unknown` as the error. 

AllAuth: v64.0.0
Django: 5.0.7

**Comment by Altair2169** [comment]
On further debugging and going through AllAuth's code, it's the `RedirectToProviderView` that's causing the errors, `render_authentication_error` takes in an exception which we are passing to `internal.on_authentication_error` which is not using the `exception` param for any logging and thats why we are not getting any additional logs (might be a bug?) , and by default we have set error to `ERRORS.UNKNOWN`, and coming back to the error itself, the error seems to be related to validating the form and I'm not sure why its failing there since I copy pasted the code from the SPA example,

my `postForm` code for reference:
```
//function call
postForm(redirectURL, {
    provider,
    callback_url: callBackURL,
    csrfmiddlewaretoken: getCookie("csrftoken") || "",
    process,
  });
  
  //function definition
  export const postForm = (action: string, data: dataProps) => {
  const form = document.createElement("form");
  form.method = "POST";
  form.action = action;

  Object.entries(data).map(([key, value]) => {
    const input = document.createElement("input");
    input.type = "hidden";
    input.name = key;
    input.value = value;
    console.log(key, value)
    form.appendChild(input);
  });
  document.body.appendChild(form);
  form.submit();
};
```
 and on logging the form data, these are the values I am getting (key,value pairs)
 
 ```
 provider google
callback_url http://localhost:5173/account/provider/callback
csrfmiddlewaretoken tln87e4kKgOxlVs51ZAmRP17bjHxFtyV
process login
```
its either that or Google's LoginByToken view is catching an exception which is again not being logged by `internal.on_authentication_error` anywhere, I think we need atleast a log for the exception even if we are not handling it inside the func

**Comment by Altair2169** [comment]
Also, on checking Django logs, we are directly getting redirected to the frontend social login error state, here's a sample log for this event

```
System check identified no issues (0 silenced).
August 20, 2024 - 04:59:46
Django version 5.0.7, using settings 'config.settings.local'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

[20/Aug/2024 05:03:56] "GET /api/users/me HTTP/1.1" 200 0
[20/Aug/2024 05:03:56] "GET /api/users/me HTTP/1.1" 200 0
[20/Aug/2024 05:03:57] "POST /_auth/browser/v1/auth/provider/redirect HTTP/1.1" 302 0
```

the redirect seems to be caused `complete_login` func inside `headless/socialaccount/internal.py` which is directly redirecting me to the frontend `socialaccount_login_error` url. 

@pennersr would really appreciate any help with this, I dont really know how to debug it further except for forking the package and adding explicit logging everywhere just to see whats happening

**Comment by Altair2169** [comment]
another update: I tried using my google oauth keys with the sample SPA and its working fine, so the problem definitely lies with my config, but I have replicated the config 1:1 from SPA as much as I can, and still facing the issue. Here's my config if it helps:


```
INSTALLED_APPS = [
    
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.microsoft",
    "allauth.headless",
    # "allauth.mfa",
    "django_celery_beat",
    "corsheaders",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]
AUTH_USER_MODEL = "users.User"
# django-allauth
# ------------------------------------------------------------------------------
ACCOUNT_ALLOW_REGISTRATION = env.bool("DJANGO_ACCOUNT_ALLOW_REGISTRATION", True)
# https://docs.allauth.org/en/latest/account/configuration.html
ACCOUNT_AUTHENTICATION_METHOD = "email"
# https://docs.allauth.org/en/latest/account/configuration.html
ACCOUNT_EMAIL_REQUIRED = True
# https://docs.allauth.org/en/latest/account/configuration.html
ACCOUNT_USERNAME_REQUIRED = False
# https://docs.allauth.org/en/latest/account/configuration.html
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
# https://docs.allauth.org/en/latest/account/configuration.html
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
# https://docs.allauth.org/en/latest/account/configuration.html
# ACCOUNT_ADAPTER = "users.adapters.AccountAdapter"
# https://docs.allauth.org/en/latest/account/forms.html
# ACCOUNT_FORMS = {"signup": "users.forms.UserSignupForm"}
# https://docs.allauth.org/en/latest/socialaccount/configuration.html
# SOCIALACCOUNT_ADAPTER = "users.adapters.SocialAccountAdapter"
# https://docs.allauth.org/en/latest/socialaccount/configuration.html
# SOCIALACCOUNT_FORMS = {"signup": "users.forms.UserSocialSignupForm"}

SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APPS": [
            {"client_id": GOOGLE_CLIENT_ID, "secret": GOOGLE_SECRET_KEY, "key": ""},
        ],
        "SCOPE": [
            "profile",
            "email",
        ],
        "AUTH_PARAMS": {"access_type": "online", "hd": "gloroots.com"},
        "OAUTH_PKCE_ENABLED": True,
        "EMAIL_AUTHENTICATION": True,
        "FETCH_USERINFO": True,
    }
}

# allauth headless
HEADLESS_ONLY = True

HEADLESS_FRONTEND_URLS = {
    # "account_confirm_email": "/account/verify-email/{key}",
    # "account_reset_password": "/account/password/reset",
    # "account_reset_password_from_key": "/account/password/reset/key/{key}",
    "account_signup": "http://localhost:5173/account/signup",
    "socialaccount_login_error": "http://localhost:5173/account/provider/callback",
}
```

**Comment by lsmolic** [comment]
@Altair2169 could you actually show us specifically what caused it? Like the line and the scenario? I'm worried that I'll run into something similar and it would really help to have as much information as possible. 

It might be useful to surface the error in some way because currently, the SPA app I was implementing never received a single ValidationError to the front end and I think that would be worth investigating further.

Thank you!

**Comment by Altair2169** [comment]
@lsmolic if you look at the `RedirectToProviderForm` view under `headless/socialaccount`, the form validates the post data and for validating the `callback_url` it calls `is_safe_url` func defined under `account/adapter` which in turn aside from basic url validation also check if the callback url  host is present in Django's `ALLOWED_HOSTS` setting and if not, it fails the validation

The issue was under the `RedirectToProviderForm` view, when the validation fails, it returns `render_authentication_error` which in turn calls `on_authentication_error` where the exception is passed but its not logged anywhere and the exception object is unused, hence the issue in debugging it.

There's no fix as such aside from maybe adding some logging for errors like these and a mention in docs that callback_url host should be present in `ALLOWED_HOSTS` setting which in hindsight seems kinda obvious but would still prefer a mention in docs

**Comment by meetgoti07** [comment]
Hello,
I'm facing the same issue. Tried to Debug it, but didn't worked. Do you have some time to help me?

Thanks

**Comment by meetgoti07** [comment]
Hello,

Thank you for your reply.

I tried that but it didn't worked. Initially I was using Separate client
and server.
But then I used the docker and replaced the client with my own vite client
server and it worked.

But I would like to know what is the issue that causing this error in
separate client and server (without docker).

Thanks and regards

**Comment by jaimesalazarlahera** [comment]
As mentioned by @Altair2169 

> also check if the callback url host is present in Django's `ALLOWED_HOSTS` setting and if not, it fails the validation

And @DAVIS-PYTH 

>  consider adding the port number to ALLOWED_HOSTS too

This solved it for me. Also using separate docker services for frontend and backend.

**Comment by meetgoti07** [comment]
@jaimesalazarlahera 
I did all this, It is redirecting me to the frontend, but not creating the session.

I'm sharing my configuration. Please check it. 
Thanks in advance.

```
ALLOWED_HOSTS = ['*', 'localhost', 'localhost:3000', 'http://localhost', 'http://localhost:3000', 'http://127.0.0.1', 'http://127.0.0.1:3000']
CORS_ORIGIN_ALLOW_ALL = True
```

```
HEADLESS_ONLY = True

HEADLESS_FRONTEND_URLS = {
    "account_confirm_email": "/account/verify-email/{key}",
    "account_reset_password": "/account/password/reset",
    "account_reset_password_from_key": "/account/password/reset/key/{key}",
    "account_signup": "/account/signup",
    "socialaccount_login_error": "/account/provider/callback",
}
HEADLESS_SERVE_SPECIFICATION = True

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APPS": [
            {
                "client_id": "xyz",
                "secret": "abc",
                "key": "",
                "settings": {
                    "scope": [
                        "profile",
                        "email",
                    ],
                    "auth_params": {
                        "access_type": "online",
                    },
                },
            },
        ],
        "SCOPE": [
            "profile",
            "email",
        ],
        "AUTH_PARAMS": {
            "access_type": "online",
        },
        "OAUTH_CALLBACK_URL": "http://localhost:8000/accounts/google/login/callback/",
    }
}

LOGIN_REDIRECT_URL = 'http://localhost:3000/account/provider/callback'  # Where to redirect users after login
LOGOUT_REDIRECT_URL = 'http://localhost:3000/account/provider/callback'  # Where to redirect users after logout
```
```
const Client = Object.freeze({
    APP: 'app',
    BROWSER: 'browser'
} as const)

type ClientType = typeof Client[keyof typeof Client]

const CLIENT: ClientType = Client.BROWSER

const BASE_URL: string = `http://localhost:8000/_allauth/${CLIENT}/v1`
const ACCEPT_JSON: { accept: string } = {
    accept: 'application/json'
}
```

`redirectToProvider("google", "http://localhost:3000/account/provider/callback")}>`

```
export function redirectToProvider (providerId:string , callbackURL:string, process = AuthProcess.LOGIN) {
    postForm(URLs.REDIRECT_TO_PROVIDER, {
        provider: providerId,
        process,
        callback_url: callbackURL,
        csrfmiddlewaretoken: getCSRFToken()
    })
}

```

```
CSRF_TRUSTED_ORIGINS = ['http://localhost', 'http://localhost:3000']
CORS_ALLOWED_ORIGINS = ['http://localhost', 'http://localhost:3000']

```

**Comment by lsmolic** [comment]
Just to make sure, are you using separate docker or nginx to route your
requests? It needs to be configured this way on localhost.

Also, make sure you do not have more options than I mentioned. Some of them
may be fine, but there are some constants that will actually make things
worse.

**Comment by meetgoti07** [comment]
No I am not using it. Isn't it possible without reverse proxy? Suppose my backend is django with a mobile app.

All auth has app mode, i don't know how to use it.

**Comment by lsmolic** [comment]
As far as I can tell because there Is a local host issue with Django CORS,
It will not create the cookie if you try to use different domains. That
means ports as well. So you have to set up some sort of path redirection

**Comment by meetgoti07** [comment]
@DAVIS-PYTH 

Hey, can you please share your settings.py configuration?
 Are you using with docker or without?

**Comment by DAVIS-PYTH** [comment]
@meetgoti07, I think you should set allow credentials to true.

you can use these configurations for your dev server, based on your needs:

if ENVIRONMENT == "development":
    CSRF_COOKIE_SAMESITE = 'Lax'
    SESSION_COOKIE_SAMESITE = 'Lax'

    CSRF_COOKIE_HTTPONLY = False
    SESSION_COOKIE_HTTPONLY = False

    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SECURE = False
else:
    CSRF_COOKIE_SAMESITE = 'None'
    SESSION_COOKIE_SAMESITE = 'None'

    CSRF_COOKIE_HTTPONLY = False
    SESSION_COOKIE_HTTPONLY = False

    CSRF_COOKIE_SECURE = True # ✅ Must be True for production over HTTPS
    SESSION_COOKIE_SECURE = True


CORS_ALLOW_ALL_ORIGINS = False (@meetgoti07 if this is false you should set CORS_ALLOWED_ORIGINS/CORS_ORIGIN_WHITELIST/CSRF_TRUSTED_ORIGINS)

CORS_ALLOW_CREDENTIALS = True 
CORS_ALLOW_HEADERS = ["Content-Type", "X-CSRFToken", "Authorization"]
CORS_EXPOSE_HEADERS = ["Content-Type", "X-CSRFToken"]

**Comment by meetgoti07** [comment]
@DAVIS-PYTH 
Are you using APP or BROWSER configuration in frontend?

Thank you so much for the help. I was stuck here since month.
Regards.

**Comment by meetgoti07** [comment]
@DAVIS-PYTH 

Sorry for being nosy. I'm a student trying to learn new things.

So I used your configuration and it is working ig. Because I can see a session is created in usersession_usersesion table.
But the issue is browser is setting up the cookie which the backend is sending. I tried manually setting up the cookie using copy paste. But still backend session is not retrieved. But session is present in database.

Can you please help me?

Config which I used

```
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SAMESITE = 'Lax'

CSRF_COOKIE_HTTPONLY = False
SESSION_COOKIE_HTTPONLY = False

CSRF_COOKIE_SECURE = False
SESSION_COOKIE_SECURE = False

CORS_ALLOW_ALL_ORIGINS = True

ALLOWED_HOSTS = ["http://localhost:3000", "localhost", "http:127.0.0.1:3000","*"]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = ["Content-Type", "X-CSRFToken","x-session-token" , "Authorization"]
CORS_EXPOSE_HEADERS = ["Content-Type", "X-CSRFToken", "x-session-token", "Authorization"]

CSRF_TRUSTED_ORIGINS = ["http://localhost:3000"]
```

**Comment by aripollak** [comment]
Thanks for your help in this ticket. I submitted an issue upstream at https://codeberg.org/allauth/django-allauth/issues/4291 to update the documentation.

**Comment by DAVIS-PYTH** [comment]
@meetgoti07 can you please share more info on what you mean when you say 'backend session is not retrieved'

**Comment by meetgoti07** [comment]
@DAVIS-PYTH 

> [@meetgoti07](https://github.com/meetgoti07) can you please share more info on what you mean when you say 'backend session is not retrieved'

Let me tell you the flow. First, I'll initiate the login and it will redirect me to Google page, once successful login, I'm getting redirected back to my frontend callback receiving page. It is a successful auth. But then the backend is not sending me the session in session API call. 

I think config call have Cookies in it, So I checked the config network request, the server is sending the cookie, but browser is not accepting it. So what I did was copied the cookies from request and set it up manually. Then only it allowed me to redirect to google page. Otherwise following error.

<img width="1470" alt="Image" src="https://github.com/user-attachments/assets/bfe7cc5e-95c9-4376-910d-3608f0205346" />

Response Header

<img width="706" alt="Image" src="https://github.com/user-attachments/assets/f2d85fd5-cdec-491c-8538-2ecbda697625" />

As you can see cookies are there, but it is not added to browser.

Once I add the cookie manually and then complete the auth, I'm also getting a sessionID in cookie which is getting set up in browser.

<img width="1073" alt="Image" src="https://github.com/user-attachments/assets/c79d1a15-f7c4-4f29-90c4-95cb76c29ce4" />

So there are some cookie issues.

**Comment by meetgoti07** [comment]
Hello,

I have found the solution. 

I had to include this line in the frontend network request.

`options.credentials = 'include'`

It was not needed when we were using Dokcker and reverse proxy. 

@DAVIS-PYTH @jaimesalazarlahera @lsmolic 
Thank you so much for your help.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/4041
