### ISSUE TITLE
Should allauth include HTML email templates in addition to plain text email templates?

### ISSUE THREAD

**Issue by Flimm** [pennersr/django-allauth#4042]
django-allauth includes many email templates, all in plain text. It does not include any HTML email templates, as mentioned in [the documentation](https://docs.allauth.org/en/latest/common/email.html):

> The project does not contain any HTML email templates out of the box. When you do provide these yourself, note that both the text and HTML versions of the message are sent.

Here are some problems with email messages that are only in plain text:

- The plain text email messages currently do not wrap at 72 or 78 characters, they do not wrap at all. This may violate the expectations of some email clients, although I am not sure. HTML email does not have this problem.
- Email clients may display plain text email messages in a monospace font. Users may prefer a normal variable-width font, which may only be enabled for HTML emails.
- I suspect email clients don't handle right-to-left languages in plain text emails very well, whereas HTML supports right-to-left languages quite well.

I'm happy to contribute a pull request adding HTML email templates to django-allauth. It seems that this is a feature that many users of allauth would want, and it makes sense to have one contributor do the work for the community, rather than duplicating the work.

We would want to make sure that future modifications the HTML email templates are reflected in the plain text templates, and vice-versa. To prevent the text of the HTML templates drifting from the text of the plain text templates, I could write a test comparing the two, using [Django's `strip_tags`](https://docs.djangoproject.com/en/stable/ref/utils/#django.utils.html.strip_tags). The `strip_tags` is reliable enough for use within tests, even if it is not reliable enough to use for untrusted input.

**Comment by pennersr** [comment]
Thoughts:
- How would you wrap at 72/78 given that the templates contain `{{ variables }}` ?
- Is `Format=Flowed` relevant to this discussion?
- Uncertain offering HTML emails out of the box is wise. It increases complexity on this end, and projects typically want to customize the look & feel of those HTML mails.

**Comment by Flimm** [comment]
Thank you for sharing your thoughts!

> How would you wrap at 72/78 given that the templates contain {{ variables }} ?

I think it would be possible using the [`wordwrap` template tag](https://docs.djangoproject.com/en/5.1/ref/templates/builtins/#wordwrap). But I'm not sure that wrapping at 78 characters is necessary.

> Is Format=Flowed relevant to this discussion?

I looked into that! That does seem promising, however, I'm not sure if email clients actually pay attention to this or not. I would need to do more research. [This Fastmail blog post from 2016](https://www.fastmail.com/blog/format-flowed/) points out that `format=flowed` is not respected by some major email clients, and they feel it wasn't worth supporting, since almost everyone has switched to HTML email anyway. I also need to do more research into whether email clients wrap plain text emails even without `format=flowed`.

One catch with `format=flowed` is that it isn't easy to set in Python. It's actually part of the `Content-Type` header, like this:

    Content-Type: text/plain; charset="utf-8"; format="flowed"

The Python API doesn't seem to offer an obvious way to modify the `Content-Type` header.

I'd also want emails to be rendered in a variable-width font, instead of a monospace font, and I don't think `format=flowed` fixes that.

> Uncertain offering HTML emails out of the box is wise. It increases complexity on this end, and projects typically want to customize the look & feel of those HTML mails.

I agree that adding more files does increase the complexity of the project, but maybe it's worth it for a better out-of-the box experience.

**Comment by pennersr** [comment]
With respect to HTML emails, projects typically tend to configure these such that the emails match the project's branding (logo, footer, button/link color, and so on). So whatever would be offered out of the box is unlikely to suffice, or would need to be highly configurable.  I don't want to introduce our own home grown email template abstraction for this, nor do I want this project to become dependent on e.g. MJML or any similar framework. And if the HTML templates offered out of the box were plain, then there would be hardly any difference with the text based ones. All in all, I would like to avoid all of this, and not include it in scope.

So then the wrapping issue remains, but you also write:

> But I'm not sure that wrapping at 78 characters is necessary.

I am not sure either.  Checking...

https://useplaintext.email/

... suggests either wrapping or format=flowed is the way to go. If that is the case, then format=flowed would have no impact to the templates. As for wrapping, then instead of altering all the templates, it would perhaps be better to add wrapping centrally in code just once, where the mail is being sent.

**Comment by Flimm** [comment]
I understand your reasoning. It sounds like you would accept a pull request implementing format=flowed, which looks like the best solution for plain text emails, according to https://useplaintext.email . I've already had a look at format=flowed, and it's not straightforward to implement in Django+Python, so I'll pass on contributing that change.

I'm going to implement basic HTML email templates for a private project, in order to achieve emails with variable-width fonts, right-to-left support, and HTML-wrapping, but I won't contribute the implementation upstream to django-allauth if you feel that the maintenance burden is not worth it.

Thank you for thinking this through with me. I'll close this issue, and you can re-open it if you feel there is enough interest to warrant re-opening.

**Comment by pennersr** [comment]
> but I won't contribute the implementation upstream to django-allauth if you feel that the maintenance burden is not worth it.

FWIW, it could still be a valuable separate project if you are wiling to open source your work. Then, we can see how that evolves, and perhaps at a later stage reconsider integration. But as it stands now, I don't think it is wise to put this in scope, yet.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/4042
