### ISSUE TITLE
settings.ACCOUNT_AUTHENTICATION_METHOD MANDATORY Phone Number with Verification

### ISSUE THREAD

**Issue by fatihkabakk** [pennersr/django-allauth#4043]
Currently when I try to set a CustomUser without username field and use USERNAME_FIELD = 'phone_number'
I cannot login to django admin because allauth's authentication backend tries to search the login user with 'username field'

setting ACCOUNT_USER_MODEL_USERNAME_FIELD = 'phone_number'
enables admin login.
However it is still hard to setup the social login functionality with mandatory phone number verification with allauth.
I think there should be mountable PhoneNumberAuthBackend, etc.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/4043
