### ISSUE TITLE
Authentik OIDC error in paperless-ngx

### ISSUE THREAD

**Issue by JannikWilhelm** [pennersr/django-allauth#4044]
as Described in https://github.com/paperless-ngx/paperless-ngx/discussions/7485, a Setup of authentik OIDC provider and paperless-ngx does not authorize or log in to paperless-ngx. Other services using OIDC (nextcloud, proxmox VE) do work correctly.
The button for Login via authentik appears in the Login screen, and clicking it, the authentik page loads correctly. However, on the redirect back to paperless, the error message appears and i am not logged in (refreshing or going back to the login Page does not help either).

There is no mention showing up in the logs either (neither in paperless web ui, nor in the docker logs)

**Comment by pennersr** [comment]
Can you please describe what the issue is within allauth scope only? As it is now described, it is unclear what the issue is and if it even is an allauth issue at all. Please limit the scope to allauth specifically.

**Comment by viaregio** [comment]
I had the same problem. In my case I had missed a character as I copied the secret from authentik to the setting from allauth.

**Comment by Maypul** [comment]
@JannikWilhelm  It did not work for me with the example provided in the Authentik docs, I had to use the one from:  https://github.com/goauthentik/authentik/issues/3503#issuecomment-1845940095 and replace PAPERLESS_SOCIALACCOUNT_PROVIDERS with this format. So in the end my config would look like:

      PAPERLESS_SOCIALACCOUNT_PROVIDERS: |
        {
          "openid_connect": {
            "SERVERS": [
              {
                "id": "authentik",
                "name": "Authentik",
                "server_url": "$AUTHENTIK_PAPERLESSNGX_URL",
                "token_auth_method": "client_secret_basic",
                "APP": {
                  "client_id": "$AUTHENTIK_PAPERLESSNGX_ID",
                  "secret": "$AUTHENTIK_PAPERLESSNGX_SECRET"
                }
              }
            ],
            "OAUTH_PKCE_ENABLED": "True"
          }
        }

and It would let me to log in.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/4044
