### ISSUE TITLE
Problem with current session API + mfa + social auth

### ISSUE THREAD

**Issue by bufke** [pennersr/django-allauth#4047]
Hello, I'm seeing unexpected behavior on the current session API. I made a small reproduction repo [here](https://gitlab.com/bufke/allauth-headless-social-mfa). 

It looks like under some circumstances, the current session API is not returning mfa_authenticate after the user authenticates with social auth and needs to proceed to MFA auth. This renders the user unable to login. The same user account works fine, completing both social and MFA auth, using the regular django templates at /accounts/.

The current session api works fine on https://react.demo.allauth.org and when I run a JavaScript dev server that proxies API requests to the backend. I suspect the issue has something to do with stash/unstash_login in [account/utils.py](https://github.com/pennersr/django-allauth/blob/cfd14550ddd4115b4b50b1aca54719cbcbf55f9b/allauth/account/utils.py#L169). 

When it works (in my js dev server), I see unstash gets a <allauth.account.models.Login object at 0x759959adb770> object. But does not when it isn't working (in the pure django example). 

I'll continue to debug but let me know if you have any ideas. I think I've demonstrated the problem in a very trivial JS example above.

**Comment by pennersr** [comment]
There is code in place that wipes out partial logins if you navigate away from the login that is in progress. That code resides in the account middleware (`_check_dangling_login()`). In your example project, you land on the `/` URL, which is not a view that handles the partial login. Therefore, the middleware kicks in and assumes the user has navigated away, wiping the dangling login. So this looks like it is working as designed.

**Comment by bufke** [comment]
Thanks for your response. I confirmed the `/` route is indeed triggering the session.pop. The example react app django backend, much like with my JS dev server, does not serve the JS for the react app. For my use case, I could extend the middleware and add an exception in _should_check_dangling_login just like robots.txt.  

I wonder if this is a common enough use case to add support for or document. I like to build my JS bundle and serve it from Django. This let's me publish an all-in-one Django app that serves both frontend and backend. While the JS is a static file and gets excluded in _should_check_dangling_login, the html to bootstrap the SPA is not excluded.

**Comment by pennersr** [comment]
There are a few options:

- Introduce a setting to exclude certain paths.
- Have `_should_check_dangling_login()` call out to a (new to be introduced) adapter method where you could plug in your own logic.
- Introduce a decorator (in similar spirit as e.g. `@csrf_exempt`) that you can use on `/`'.

I think the first option is the simplest way to move forward, so e.g. have a setting with this as defaults:

```
    ) or request.path in [
        "/favicon.ico",
        "/robots.txt",
        "/humans.txt",
    ]:
```

Name yet to be decided.

**Comment by bufke** [comment]
A setting seems reasonable and is a good opportunity to educate allauth users about the dangling login feature. It's not that difficult to extend middleware, if greater customization is needed, making an adapter less important IMO.

**Comment by bufke** [comment]
I take that back a little, it's a bit hard to extend the middleware. While it's a class, it references functions just in the same file. It's not easy to adjust just one function. 
 
Also:

> django.core.exceptions.ImproperlyConfigured: allauth.account.middleware.AccountMiddleware must be added to settings.MIDDLEWARE

**Comment by pennersr** [comment]
True. That middleware is a bit convoluted anyway, especially because of the async/sync handling, not sure it is worth trying to make that extensible if a simple setting would do the job just as well.

**Comment by pennersr** [comment]
Moved to https://codeberg.org/allauth/django-allauth/issues/4047
