### ISSUE TITLE
How to prevent bots from creating unnecessary sessions in django-allauth?

### ISSUE THREAD

**Issue by DarkKingArthas** [pennersr/django-allauth#4056]
Explanation of the problem:
I have an application that uses django-allauth for user authentication through social networks (Google, Facebook, VK). I've encountered an issue where bots attempting to authenticate through these providers are creating a large number of incomplete sessions in the database. This is leading to a significant growth in the database size and decreased performance.

I've tried to solve this problem by using the signals provided by the django-allauth library, such as user_signed_up and user_logged_in, social_account_added. However, these signals only fire upon successful completion of the authentication process. I was unable to find a signal that would fire on incomplete authentication attempts, so that I could delete the corresponding sessions.

I also tried using middleware to clean up expired sessions, but faced difficulties in determining which sessions should be considered "incomplete".

I'm looking for a solution that would allow me to efficiently detect and delete sessions created by bots attempting authentication, without impacting the experience of genuine users.

The problem is that even a single click on the social authentication link creates a new session in the database, even if the user doesn't complete the authentication process. This means that bots can easily create a large number of these incomplete sessions just by visiting the authentication URLs.

**Comment by pennersr** [comment]
What you could do is set a short session life time by default, and on login, extend that so that authenticated users have longer sessions. That can be done on `user_logged_in`.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/4056
