### ISSUE TITLE
Incorrect Relying Party (rp) ID in WebAuthn Creation Options Leading to DOMException

### ISSUE THREAD

**Issue by vasilistotskas** [pennersr/django-allauth#4058]
I'm encountering an issue with the WebAuthn implementation in my application. The api/_allauth/app/v1/account/authenticators/webauthn?passwordless=true GET method successfully returns WebAuthn creation options. However, the id field in the publicKey part of the creation options seems to be incorrect, which causes a DOMException when using the create method from the @github/webauthn-json/browser-ponyfill package.

The API response from the endpoint returns the following structure
```
{
    "status": 200,
    "data": {
        "creation_options": {
            "publicKey": {
                "rp": {
                    "id": "backend-service",
                    "name": "Webside"
                },
                "user": {
                    "id": "Ng",
                    "name": "test@msn.com",
                    "displayName": "billaras"
                },
                "challenge": "o7r-zns8rKYoJ2113QZxFyNZzRcKi-L6s2jQMM2Ol7U",
                "pubKeyCredParams": [
                    {
                        "type": "public-key",
                        "alg": -7
                    },
                    {
                        "type": "public-key",
                        "alg": -8
                    },
                    {
                        "type": "public-key",
                        "alg": -35
                    },
                    {
                        "type": "public-key",
                        "alg": -36
                    },
                    {
                        "type": "public-key",
                        "alg": -37
                    },
                    {
                        "type": "public-key",
                        "alg": -257
                    },
                    {
                        "type": "public-key",
                        "alg": -47
                    }
                ]
            }
        }
    }
}
```

The id field is currently set to "backend-service" that is the Kubernete Service name and not the domain.
When using the create and parseCreationOptionsFromJSON methods from the @github/webauthn-json/browser-ponyfill package, I receive the following error:
`DOMException: The relying party ID is not a registrable domain suffix of, nor equal to the current domain.`

Frontend: Nuxt.js application hosted at https://webside.gr
Backend: Django application serving the API at https://api.webside.gr

**Comment by pennersr** [comment]
You can override the ID in the adapter method, it has the following default implementation:

``` python
    def get_public_key_credential_rp_entity(self) -> Dict[str, str]:
        name = self._get_site_name()
        return {
            "id": context.request.get_host().partition(":")[0],
            "name": name,
        }
```

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/4058
