### ISSUE TITLE
Integrate with php project

### ISSUE THREAD

**Issue by watermelonlh** [pennersr/django-allauth#406]
I am using https://github.com/winhamwr/django-php-bridge to integrate a php project into my django project. They share the same authentication, which is I implemented in django by all-auth.

For now, the django-php-bridge is simply serialize the session into php-style and stored in db to provide for php side. It works fine with all-auth local user, but will get fail for all socail account.

the django server will report like `[WARNING] [django.request:162] Forbidden (Permission denied): /accounts/github/login/callback/`

I am wondering the socailaccount session is implemented different from local account?
Could you please give some advice on this issue? thx a lot!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/406
