### ISSUE TITLE
Use the p element in passkey-related templates

### ISSUE THREAD

**Issue by d9pouces** [pennersr/django-allauth#4062]
With django-allauth==64.1.0, in templates `mfa/index.html`, `mfa/webauthn/authenticator_list.html` and `templates/mfa/webauthn/authenticator_confirm_delete.html`, there are occurrences of raw `<p>` tags.

Why not use the `{% element p %}{% endelement %}` like everywhere else, to ease the customization?

**Comment by pennersr** [comment]
Definitely, this possibly was introduced by mistake because webauthn was in a different branch when element `p` got introduced.

**Comment by d9pouces** [comment]
Ok, I just submitted a pull request to fix this.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/4062
