### ISSUE TITLE
Remove type=text/javascript from templates

### ISSUE THREAD

**Issue by d9pouces** [pennersr/django-allauth#4066]
In HTML5, adding `type="text/javascript"` in script tags leads to warnings when we use the W3C HTML validator:
`Warning: The type attribute is unnecessary for JavaScript resources.`

**Comment by pennersr** [comment]
Merged via #4067, thanks.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/4066
