### ISSUE TITLE
WebAuthn Login POST API - Handling X-Session-Token for Initial Login Request (App Usage)

### ISSUE THREAD

**Issue by vasilistotskas** [pennersr/django-allauth#4068]
I'm encountering an issue with the WebAuthn login process using the app usage of the API in Django-Allauth. According to the documentation, the X-Session-Token header is required when using the app client for API calls.

While I am successfully able to perform actions such as adding and deleting WebAuthn tokens for a user account, I'm running into a problem when trying to log in using a Passkey. Specifically, the POST request to the WebAuthn login endpoint is returning a 400 error with the message Incorrect code.

Error Details:
```
{
    "url": "/api/_allauth/app/v1/auth/webauthn/login",
    "statusCode": 400,
    "statusMessage": "Bad Request",
    "data": {
        "status": 400,
        "errors": [
            {
                "message": "Incorrect code.",
                "code": "incorrect_code",
                "param": "credential"
            }
        ]
    }
}
```

Debugging Information
After extensive debugging, I've determined that the issue likely relates to the X-Session-Token header. Here's what I observed:

1.Login with Password Flow:

- Logging in with a password and being redirected to /authenticate/webauthn allows successful login using the WebAuthn passkey.
- In this scenario, I receive a 401 response from the login attempt, which includes a session_token in the error response. I then set this session_token and proceed to log in successfully.

2.Direct WebAuthn Login Flow:

- When attempting to log in directly using WebAuthn (without a password first), the login GET method does not return a session_token, and hence I cannot include the X-Session-Token in the initial POST request.

- This is the GET response from `webauthn/login`
```
{
    status: 200,
    data: {
        request_options: {
            publicKey: {
                challenge: "QTc7Vf1NF2iI-LlK7A1ZlaIH4GwdcjPVvgrVxV3gbtY",
                rpId: "webside.gr",
                allowCredentials: [],
                userVerification: "preferred"
            }
        }
    }
}
```

3.Workaround:

- By logging in using a password first, then proceeding with WebAuthn without refreshing the browser (SPA), I can successfully log in using the passkey.

Main Question
How should the X-Session-Token be handled in the initial WebAuthn login API call? Since this is the first API call I make, there's no session token available to include in the request headers. Is there a specific flow or additional API call I should make to obtain this token, or is this a potential bug in the library?

Code Example
Here is the relevant code snippet:
```
async function onSubmit() {
  try {
    loading.value = true
    const optResp = await getWebAuthnRequestOptionsForLogin()
    const jsonOptions = optResp?.data.request_options
    if (!jsonOptions) {
      throw new Error('No creation options')
    }
    const options = parseRequestOptionsFromJSON(jsonOptions)
    const credential = await get(options)
    session.value = await loginUsingWebAuthn({
      credential,
    })
    await performPostLoginActions()
  }
  catch (error) {
    console.error('=== Error ===', error)
    toast.add({
      title: t('common.error.default'),
      color: 'red',
    })
  }
  finally {
    await finalizeLogin()
  }
}
```

**Comment by pennersr** [comment]
Are you sure? There is a test case that specifically tests this, see:

https://github.com/pennersr/django-allauth/blob/main/allauth/headless/mfa/tests/test_webauthn.py#L28

**Comment by pennersr** [comment]
Additionally, the following does show the session token:

```
curl https://react.demo.allauth.org/_allauth/app/v1/auth/webauthn/login
```

So this seems to be working just fine?

**Comment by vasilistotskas** [comment]
Oh you are right, in case the `X-Session-Token` is already set, the login get method does not include a new session_token in the response, i was confused because there is no documented and i have built my types in using zod, for example

```
import { ZodWebAuthnLoginGetResponse } from '~/types/all-auth'

export default defineEventHandler(async () => {
  const config = useRuntimeConfig()
  try {
    const headers = await getAllAuthHeaders()
    const response = await $fetch(`${config.public.djangoUrl}/_allauth/app/v1/auth/webauthn/login`, {
      method: 'GET',
      headers,
    })
    return await parseDataAs(response, ZodWebAuthnLoginGetResponse)
  }
  catch (error) {
    await handleAllAuthError(error)
  }
})
```

```
export const ZodWebAuthnLoginGetResponse = z.object({
  status: z.literal(200),
  data: z.object({
    request_options: z.object({
      publicKey: z.object({
        challenge: z.string(),
        rpId: z.string().optional(),
        allowCredentials: z.array(z.object({
          type: z.literal('public-key'),
          id: z.string(),
          transports: z.array(z.enum(['ble', 'hybrid', 'internal', 'nfc', 'usb'])).optional(),
        })).optional(),
        userVerification: z.enum(['discouraged', 'preferred', 'required']).optional(),
      }),
    }),
  }),
})
```

So i also had to include the `meta` in the zod schema and i see that it works fine, thank you!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/4068
