### ISSUE TITLE
Provide a default profile page

### ISSUE THREAD

**Issue by pauloneves** [pennersr/django-allauth#407]
It would be nice if allauth had a default profile page. Just something that display some basic user data. When I login, it gives me a 404 error in the page: http://localhost:8000/accounts/profile/#_=_

![image](https://f.cloud.github.com/assets/221084/1312361/701d36f2-3232-11e3-91ff-269aa9096510.png)

**Comment by nscozzaro** [comment]
I agree with Paulo, it would be great to just have a page that says 'Success! Welcome *name/username*! ' or something else like that which is bare-bones, but indicates that everything is working properly.

**Comment by yurenchen000** [comment]
maybe some page show internal information is cool.
something like casdoor's profile page:
 - show username, user id
 - session login method: user:pass OR which social auth // if possible
 - user asscicated social auth // I'm not sure account associate
..

![door casbin com_account_1](https://user-images.githubusercontent.com/8458213/150093724-b37e6031-83f9-4aca-b198-52baa99604fa.png)


https://door.casbin.com/account

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/407
