### ISSUE TITLE
ModuleNotFoundError: No module named 'allauth.socialaccount.providers.linkedin' 

### ISSUE THREAD

**Issue by takuonline** [pennersr/django-allauth#4070]
Seems like allauth.socialaccount.providers.linkedin is not yet implemented; only linkedin_oauth2 is implemented, even though the documentation says "linkedin_oauth2" is now deprecated.

Current latest version of django-allauth: **64.1.0**

**Comment by pennersr** [comment]
See https://github.com/pennersr/django-allauth/issues/3558#issuecomment-1849033044 -- just use the regular OIDC provider instead. All linkedin providers are deprecated.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/4070
