### ISSUE TITLE
suspend_request should url-encode the path

### ISSUE THREAD

**Issue by boosh** [pennersr/django-allauth#4078]
At the moment `suspend_request` [doesn't urlencode the path](https://github.com/pennersr/django-allauth/blob/d30b64133913181f185d72589e3b9494f7488381/allauth/account/internal/flows/reauthentication.py#L43). That means URLs containing GET params aren't handled correctly if the user must log in, e.g.: 

http://localhost:8000/invitations/2/accept/?key=xxx
becomes:
http://localhost:8000/accounts/signup/?next=/invitations/2/accept/?key=xxx

The `?key=xxx` should be urlencoded; in fact, the whole path should be urlencoded and decoded before redirecting to whatever `next` points to after the user logs in.

**Comment by pennersr** [comment]
It is using `urlencode()`:

https://github.com/pennersr/django-allauth/blob/main/allauth/account/internal/flows/reauthentication.py#L43

**Comment by boosh** [comment]
Duh, sorry, I didn't notice that. I am however seeing the issue of the param not being urlencoded so I didn't even read the code right. I'll try to track down what's going on a bit more.

**Comment by boosh** [comment]
Apologies, my bad, the issue is occuring elsewhere.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/4078
