### ISSUE TITLE
How can we `resend the verification code` in `Email verification by code` flow?

### ISSUE THREAD

**Issue by KaratasFurkan** [pennersr/django-allauth#4079]
I've actually ask this in [here](https://github.com/pennersr/django-allauth/pull/4040#issuecomment-2316203369) already, but I thought having an issue can be easier to track. Copy&pasting the same question here:

#

Hi @pennersr , thanks for the feature!

I was testing it today and it works quite well. The only part I couldn't manage is re-sending the verification code email. I want to add a `Resend the verification email` button to the `confirm_email_verification_code.html` in case the user doesn't get the email for some reason. But I got lost in the source code unfortunately.

This is what I've tried so far:
```python
class ResendVerificationCodeEmailView(RedirectView):
    pattern_name = 'account_email_verification_sent'

    def post(self, request, *args, **kwargs):
        # This doesn't send an email:
        # email_verification_by_code.request_email_verification_code(
        #     self.request, user=None, email=request.session['account_email_verification_code']['email']
        # )
        #
        # This raises error regarding anonymous user
        # send_email_confirmation(self.request, request.user, email=request.session['account_email_verification_code']['email'])
        #
        # This raises error regarding anonymous user similar to "send_email_confirmation"
        # account_adapter = get_adapter()
        # if account_adapter.should_send_confirmation_mail(request, email_address, signup):
        #     account_adapter.send_confirmation_mail(request, emailconfirmation, signup)
        return self.get(request, *args, **kwargs)
```

Can you please help?

**Comment by pennersr** [comment]
> in case the user doesn't get the email for some reason.

Wondering, what circumstance do you foresee that results in the 2nd email to arrive while the 1st does not?

**Comment by KaratasFurkan** [comment]
We use a 3rd party service for sending emails, so there may be a temporary issue on the service and the second email which we will allow users to send after 1 minute waiting can work hopefully.

Or the user may delete the first email by mistake and need to send the second one.

Lastly, it's also important for UX, IMO. Imagine that a user tried to signup to our platform, they filled up the form and get to the "Enter your verification code" page. They waited 30 seconds and the email didn't come yet for some reason. In this case, if we display a "Resend your verification email" button which will be enabled after 1 min, they can wait for the countdown for a second shot. Otherwise, they may think "I didn't receive a verification code, what am I supposed to do?" and leave the platform.

**Comment by pennersr** [comment]
Was asking to determine the importance/priority of this, which seems rather low:

> there may be a temporary issue on the service

Unless you rely on a really bad service, mails get queued, retried and delivered.

> Or the user may delete the first email by mistake

The user can always undelete / recover from the trash.

And should it happen, the user won't become stuck. When trying to login they get another email. When they try to signup they also get an email explaining their situation.

**Comment by KaratasFurkan** [comment]
> Unless you rely on a really bad service, mails get queued, retried and delivered.

Yes, but the service may be unavailable (503) for a few seconds/minutes, so it may not even get the email request. We are using https://loops.so/ btw, it's an email service that gets email requests by api calls. You may also say that we can implement our own queue too but it makes things more complicated than a simple "resend button" IMO.

> And should it happen, the user won't become stuck. When trying to login they get another email. When they try to signup they also get an email explaining their situation.

I thought adding a button in the same page they are waiting to get the email would be more obvious for users.

> Was asking to determine the importance/priority of this

I see. Even if you think this isn't worth adding to the package itself, any help on how to create a custom utility for it would be much appreciated.

**Comment by pennersr** [comment]
I am not saying it shouldn't be added.  Though, it is a scenario/feature only a very small fraction (say <1%) should be needing. Some impatient users in the remaining 99% will also start hitting that button, only to end up with 2 or more emails each with a different code, lowering the UX as it becomes unclear which one to type in.

> You may also say that we can implement our own queue too but it makes things more complicated than a simple "resend button" IMO.

IMO it would really be better to handle this internally than to put the burden of handling this implementation detail on the user.

> any help on how to create a custom utility for it would be much appreciated.

Must admit, haven't given this a lot of thought, but this likely needs to be integrated in the `ConfirmEmailVerificationCodeView`. And, for sake of consistency, `ConfirmLoginCodeView` should then be given the same treatment as well. So if you're going to implement this in your own project, I would recommend you create your own views deriving from the allauth views and make those views handle both a resend action, next to the current "confirm code" action.

**Comment by KaratasFurkan** [comment]
Alright, thanks for the help and detailed explanations 🙏

**Comment by pennersr** [comment]
Moved to https://codeberg.org/allauth/django-allauth/issues/4079

**Comment by pennersr** [comment]
For those interested in this functionality, it is available over at the `feat/resend-code-or-change` branch at Codeberg. If anybody is willing to give this branch a test run that would be appreciated.

```
``ACCOUNT_EMAIL_VERIFICATION_SUPPORTS_CHANGE`` (default: ``False``)
  Whether or not the email can be changed after signup at the email veriication
  stage.

``ACCOUNT_EMAIL_VERIFICATION_SUPPORTS_RESEND`` (default: ``False``)
  Whether or not the user can request a new email verification code.
```

**Comment by pennersr** [comment]
That branch is merged now.
