### ISSUE TITLE
`ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION` broken with 64.2.0

### ISSUE THREAD

**Issue by francoisfreitag** [pennersr/django-allauth#4086]
Regression introduced in https://github.com/pennersr/django-allauth/commit/560cb24dce5593342d70cd81db568a2d35471367

Diff from 64.2.0 to reproduce the issue :
```diff
diff --git a/allauth/account/tests/test_email_verification.py b/allauth/account/tests/test_email_verification.py
index 172b1f40..4fc1653b 100644
--- a/allauth/account/tests/test_email_verification.py
+++ b/allauth/account/tests/test_email_verification.py
@@ -48,6 +48,8 @@ def test_login_on_verification(
     )
     assert resp.status_code == 302
     assert resp["location"] == reverse("account_email_verification_sent")
+    resp = client.get(resp["location"])
+    assert resp.status_code == 200
 
     email = EmailAddress.objects.get(email="a@a.com")
     key = EmailConfirmationHMAC(email).key
```

As far as I understand, following the redirect to the confirmation page causes to pass in the middleware and (incorrectly) removing the dangling login. After that, when the client clicks on the confirmation link, the `LoginStageController.enter` tries to `unstash_login`, which is incorrectly empty and cannot perform the login.
https://github.com/pennersr/django-allauth/blob/87edc03effd8b2932294f1da23e766a8b1adf2ee/allauth/account/middleware.py#L41

[failure.txt](https://github.com/user-attachments/files/16868652/log.txt)

**Comment by pennersr** [comment]
Thanks for the diff. A fix for this is here #4088.

**Comment by pennersr** [comment]
Merged. Thanks for reporting!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/4086
