### ISSUE TITLE
Weird behaviour running syncdb

### ISSUE THREAD

**Issue by pauloneves** [pennersr/django-allauth#409]
After the installation and configuration,  I've run ./manage.py syncdb and stumbled in a weird behaviour. Some models were synced and others not:

Synced:

> django.contrib.auth
> django.contrib.contenttypes
> django.contrib.messages
> django.contrib.sessions
> django.contrib.staticfiles
> django.contrib.sites
> south
> debug_toolbar
> allauth
> allauth.account
> allauth.socialaccount.providers.google
> allauth.socialaccount.providers.persona
> avatar
> django.contrib.admin
> django.contrib.admindocs

Not synced (use migrations):
- sc.base
- sc.personal
- allauth.socialaccount
- allauth.socialaccount.providers.facebook

I didn't understand why the last two models weren't created. Here is the output of the tables in my database:

mysql> show tables like '%accou%';
+--------------------------------+
| Tables_in_sambachoro (%accou%) |
+--------------------------------+
| account_emailaddress           |
| account_emailconfirmation      |
| socialaccount_socialaccount    |
| socialaccount_socialapp        |
| socialaccount_socialapp_sites  |
| socialaccount_socialtoken      |
+--------------------------------+

Is it correct?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/409
