### ISSUE TITLE
redirect_uri_mismatch error when authenticating with Google using Django Allauth

### ISSUE THREAD

**Issue by Stradivariuskein** [pennersr/django-allauth#4093]
I am using Django Allauth to authenticate users via Google in my application, but when attempting to link a Google account, I encounter a `redirect_uri_mismatch` error. I have reviewed the configuration and redirect URIs, but I cannot resolve the issue.

When I try to authenticate, the redirect URI that is sent is incorrect and is missing the subdomain, which seems to be causing the problem. I have tried forcing the `redirect_uri` in the social account configuration, but the issue persists. I do not see any errors in the logs.

### Settings Configuration:

```python
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'accounts',
]

SITE_ID = 2

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "allauth.account.middleware.AccountMiddleware",
]

# Google OAuth settings
ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'https'
SOCIALACCOUNT_LOGIN_ON_GET = True

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
            'https://www.googleapis.com/auth/userinfo.profile',  # Add necessary scopes
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
            'redirect_uri': "https://autotemplate.alanluque.com/accounts/google/login/callback/"
        },
        'OAUTH_PKCE_ENABLED': True,
        'FETCH_USERINFO': True,
    }
}

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]
```
### Problem Description:

When I try to authenticate with Google, I get a `redirect_uri_mismatch` error. In the Google console, I can see that the redirect URI being sent differs from the one I have configured. To resolve this, I explicitly added the correct `redirect_uri` to the settings, as shown above, but the problem remains.

I have also tried running it through `localhost` with the same result. I have checked and confirmed that the redirect URIs in the Google console match those configured in my application.

### Screenshots:

1. **Configured URI:**
![config_google_uri](https://github.com/user-attachments/assets/5ab6e17a-1b44-4fa8-aa3e-6776c5caa020)

2. **Error without URI configured in settings:**
![error_uri_mismach](https://github.com/user-attachments/assets/a73aec91-6580-41a5-aba9-dc2980435470)

3. **Error with URI configured in settings:**
![error_google_2](https://github.com/user-attachments/assets/e3da8ca3-9d13-4c2e-bce9-3f4fbffd0079)

**Comment by pennersr** [comment]
This must be a local deployment issue, as Google is definitely working even when using subdomains. See for example https://django.demo.allauth.org/  ... not sure what is going on, perhaps there is an in between proxy that is misconfigured, but this is not an issue in allauth.

**Comment by Stradivariuskein** [comment]
Thank you for your response. I’ve been searching for a solution for several days now. I have a proxy set up with Nginx, but even when I test it locally and add the redirect_uri to the Google console, I’m still facing the same issue. Could there be something else causing the problem?

Django redirect URI: 'redirect_uri': "http://localhost:8000/accounts/google/login/callback/"

Screenshot:
![config_google_uri2](https://github.com/user-attachments/assets/d164c54a-6bd3-4bfd-a077-3e34604c985c)


I would really appreciate it if there is someone who speaks Spanish because I am using a translator.

**Comment by MessyComposer** [comment]
Also had this issue, what seemed to work was adding both
`http://127.0.0.1:8000/accounts/google/login/callback/` and `http://127.0.0.1:8000/accounts/google/login/callback/?flowName=GeneralOAuthFlow`
To the authorized redirect URI's
