### ISSUE TITLE
How to keep an account temporarily activated after signup, until email is verified

### ISSUE THREAD

**Issue by sachingupta006** [pennersr/django-allauth#41]
Currently there is a setting `ACCOUNT_EMAIL_VERIFICATION`  that keeps the account inactive until the email given by the user is not verified. However is it possible to keep the account temporarily active, say for 7 days. If after 7 days also the email is not verified the account is made inactive?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/41
