### ISSUE TITLE
AssertionError while signup with postgres database

### ISSUE THREAD

**Issue by romali** [pennersr/django-allauth#411]
While signup with default template I get following error on my screen:

AssertionError at /accounts/signup/
No exception supplied
Request Method: POST
Request URL:    http://10.0.1.17:8888/accounts/signup/
Django Version: 1.5.4
Exception Type: AssertionError
Exception Location: /.../projects/cleandjango/motobazar/allauth/account/utils.py in send_email_confirmation, line 291

My platform:
postgresql-9.1
python-2.7.3
django-1.5.4

Allauth configuration:
ACCOUNT_AUTHENTICATION_METHOD = "username_email"
ACCOUNT_USERNAME_MIN_LENGTH = 6
ACCOUNT_PASSWORD_MIN_LENGTH = 6
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
EMAIL_CONFIRMATION_DAYS = 3

Here trackback:
http://dpaste.com/1413559/

Everything working fine with mysql and sqlite3 but not on postgres.
I seeing followings errors in postgresql log:

2013-10-11 20:49:03 CEST ERROR:  duplicate key value violates unique constraint "account_emailaddress_email_key"
2013-10-11 20:49:03 CEST DETAIL:  Key (email)=(robert111@*****_.com) already exists.
2013-10-11 20:49:03 CEST STATEMENT:  INSERT INTO "account_emailaddress" ("user_id", "email", "verified", "primary") VALUES (4, 'robert111@**_****.com', false, false) RETURNING "account_emailaddress"."id"

User is added to "account_emailaddress" and "auth_user" table but not to "account_emailconfirmation"

I would appreciate any help

**Comment by FalconBFR** [comment]
still broken in 2021

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/411
