### ISSUE TITLE
Catch the right exceptions in facebook.views.login_by_token

### ISSUE THREAD

**Issue by tino** [pennersr/django-allauth#412]
[except](https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/providers/facebook/views.py#L59) catches everything, including import errors, which caused me quite some confusion.

Shouldn't it be changed to `except GraphAPIError:` instead like [it was before](https://github.com/pennersr/django-allauth/commit/fd4b95b1b8d023eaec6cf1087e64256b04545f66#diff-b575d634dcab97c810e879414965b056L79)?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/412
