### ISSUE TITLE
Docs down?

### ISSUE THREAD

**Issue by engin-can** [pennersr/django-allauth#4129]
Getting the following error on https://docs.allauth.org/en/latest/headless/introduction.html

![CleanShot 2024-10-17 at 13 49 51](https://github.com/user-attachments/assets/6755eaec-1ebf-4303-8d43-1b41c361a5b0)

**Comment by ikelkar** [comment]
I'm getting the following when trying to access docs
<img width="746" alt="Screenshot 2024-10-17 at 12 24 09 PM" src="https://github.com/user-attachments/assets/a8b2a4d8-a62d-46b5-a055-fd6489e807aa">

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/4129
