### ISSUE TITLE
fixed mistakes arabic translation

### ISSUE THREAD

**Issue by EngFarisAlsmawi** [pennersr/django-allauth#4148]
https://github.com/pennersr/django-allauth/blob/45ea40aafe73a1de81907ea72a392fe821b51257/allauth/locale/ar/LC_MESSAGES/django.po#L1344

Correct translate:
` msgstr "عرض" 
`

**Comment by pennersr** [comment]
Closing -- as instructed in the issue template, please do not file issues here.
