### ISSUE TITLE
InconsistentMigrationHistory: conflict with installing django.contrib.sites

### ISSUE THREAD

**Issue by kanzure** [pennersr/django-allauth#4150]
If you install `django.contrib.sites` into `INSTALLED_APPS` after installing and migrating `allauth.socialaccount`, then you will get:

```
python3 manage.py migrate

    raise InconsistentMigrationHistory(
django.db.migrations.exceptions.InconsistentMigrationHistory: Migration socialaccount.0001_initial is applied before its dependency sites.0001_initial on database 'default'.
```

If you do not already have a production database with production data in the socialaccount tables, then one way to handle this situation would be:

1. `python3 manage.py migrate socialaccount zero`
2. install `django.contrib.sites` app in `INSTALLED_APPS`
3. `python3 manage.py migrate sites`
4. `python3 manage.py migrate socialaccount`

The re-migration is required because `allauth.socialaccount` migrations are dynamic and change based on whether `django.contrib.sites` is in `INSTALLED_APPS`, even if you have already run the socialaccount migrations in the distant past.

I posted this solution on [stackoverflow](https://stackoverflow.com/a/79253302/687783).

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/4150
