### ISSUE TITLE
Exception trying to connect account when I'm not an authenticated user

### ISSUE THREAD

**Issue by pauloneves** [pennersr/django-allauth#417]
I'm trying to automatically connect a user account using a link like this:

<p><a href="{% provider_login_url "facebook" process="connect" %}">Connect a facebook account</a></p>

I'm not authenticated as a user. I'm trying to have a workflow of automatically associating accounts, link I describe in this [StackOverflow question](http://stackoverflow.com/questions/19354009/django-allauth-social-login-automatically-linking-social-site-profiles-using-th). 

I thought that It wouldn't work, and would see an error message, but I got an weird exception:

<pre>
Environment:

Request Method: POST
Request URL: http://localhost:8000/accounts/persona/login/

Django Version: 1.5.4
Python Version: 2.7.4
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.admin',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'allauth.socialaccount.providers.dropbox',
 'allauth.socialaccount.providers.facebook',
 'allauth.socialaccount.providers.google',
 'allauth.socialaccount.providers.github',
 'allauth.socialaccount.providers.linkedin',
 'allauth.socialaccount.providers.openid',
 'allauth.socialaccount.providers.persona',
 'allauth.socialaccount.providers.soundcloud',
 'allauth.socialaccount.providers.stackexchange',
 'allauth.socialaccount.providers.twitch',
 'allauth.socialaccount.providers.twitter',
 'allauth.socialaccount.providers.vimeo',
 'allauth.socialaccount.providers.weibo',
 'example.demo',
 'bootstrapform')
Installed Middleware:
('django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware')

Traceback:
File "/home/neves/dev/django-allauth/example/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  187.                 response = middleware_method(request, response)
File "/home/neves/dev/django-allauth/example/venv/local/lib/python2.7/site-packages/django/contrib/sessions/middleware.py" in process_response
  26.                 patch_vary_headers(response, ('Cookie',))
File "/home/neves/dev/django-allauth/example/venv/local/lib/python2.7/site-packages/django/utils/cache.py" in patch_vary_headers
  142.     if response.has_header('Vary'):

Exception Type: AttributeError at /accounts/persona/login/
Exception Value: 'str' object has no attribute 'has_header'
</pre>

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/417
