### ISSUE TITLE
Redirects to Twitter authorization on every login.

### ISSUE THREAD

**Issue by rudymenendez** [pennersr/django-allauth#42]
Should it be taking the user to Twitter on every login (after they have signed up using Twitter)? The user experience seems to be that it should see that the user exists, login and redirect to the setup landing page (without going to Twitter).

When I compare this with Facebook, I get a popup but then it quickly closes and takes me to the setup landing page. This seems correct.

Is this a known issue for Twitter?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/42
