### ISSUE TITLE
Authentication via Popup

### ISSUE THREAD

**Issue by dedcode** [pennersr/django-allauth#426]
Hi!
It's seems that the facebook adapter is able to launch a popup for authentication but not the others, at least twitter/google. Is it possible to switch or allow this kind of behaviour? It seems completely weird to leave the website to authenticate.
Thanks

**Comment by fmalina** [comment]
For reference, this is where Google's official OAuth docs mention popup integration
https://developers.google.com/identity/protocols/OAuth2UserAgent

**Comment by dudu86** [comment]
Any update on this? Having login through Facebook and Google seems weird that only Facebook opens a popup and Google make you leave the website

**Comment by derek-adair** [comment]
Now this is an interesting feature to me.  Huge ROI potential as this is probably a pretty straight forward fix.  I believe this is pretty standard now and worth attention.

**Comment by pennersr** [comment]
Moved to https://codeberg.org/allauth/django-allauth/issues/426

**Comment by pennersr** [comment]
Moved to https://codeberg.org/allauth/django-allauth/issues/426
