### ISSUE TITLE
"[Errno 61] Connection refused" when trying to reset password or verify email

### ISSUE THREAD

**Issue by dollydagr** [pennersr/django-allauth#427]
Hi,

I am testing allauth through the "example.demo" app. Creating an account and signing in go well. However, when I attempt to:
- reset a password
- verify an email address
- add an email address

I run into this error:

```
Exception Type: error
Exception Value: [Errno 61] Connection refused
Exception Location: /usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py in create_connection, line 571
```

Is there something that I missed? Maybe an edit to settings.py?

Even on http://jug.gl/accounts/password/reset/, I couldn't test the "Reset my Password" functionality (nowhere to input the email address).

Thanks for your help!
dollydagr

**Comment by nkoronka** [comment]
Issue is still helping nearly six years later :)

**Comment by rahulkp220** [comment]
@nkoronka Just put in your settings.py file
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

**Comment by avalbad** [comment]
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  add too
settings.py

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/427
