### ISSUE TITLE
Display login form errors on bootstrap's modal

### ISSUE THREAD

**Issue by dollydagr** [pennersr/django-allauth#429]
Hi,

I am integrating django-allauth in my project. I already have my app's templates in place, and would like to get allauth's templates incorporated within them.

In my homepage, I am using bootstrap's modal to display the login form this way (and it works fine):

```
<a data-toggle="modal" data-remote="/accounts/login" data-target="#loginModal">{% trans "Login" %}</a>
<div id="loginModal>...</div>
```

If the forms is valid, it brings me to the profile template. If it's not, it brings me to the login template. Instead, I'd like to remain in the homepage with the modal in place, and have the errors and warnings displayed there.

Maybe I didn't integrate the login form the right way. Or maybe there is a way to capture the form errors in the modal.
Any hint is appreciated.

dollydagr

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/429
