### ISSUE TITLE
SMTPRecipientsRefused at /accounts/signup/

### ISSUE THREAD

**Issue by Rukomoynikov** [pennersr/django-allauth#438]
I'm not sure is it common error. When i'm registering, using standard templates and views, after submitting email and password, i receive this error:

> SMTPRecipientsRefused at /accounts/signup/
> {u'user8': (553, "5.1.2 We weren't able to find the recipient domain. Please check for any\n5.1.2 spelling errors, and make sure you didn't enter any spaces, periods,\n5.1.2 or other punctuation after the recipient's email address. z12sm84687374eev.6 - gsmtp")}

From django shell i sends email without problem. 

settings.py:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_USE_TLS = True
    EMAIL_HOST = 'smtp.gmail.com'
    EMAIL_PORT = 587
    EMAIL_HOST_USER = "username@gmail.com"
    EMAIL_HOST_PASSWORD = "password"

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/438
