### ISSUE TITLE
In the e-mail template, remove primary e-mail and make unverified e-mail primary have an unexpected behavior

### ISSUE THREAD

**Issue by dollydagr** [pennersr/django-allauth#439]
Hi,

I wanted to report an "strange" behavior in the email template ("email.html" comprising E-mail Addresses + Add E-mail forms).

Flow 1:
- I select a primary e-mail address
- I hit "remove", and confirm
- I have the expected message "You cannot remove your primary e-mail address.", BUT the selected e-mail address gets also submitted to the add_email_form (it appears in the corresponding TextField) which then displays the error message "This e-mail address is already associated with this account." 

Flow 2:
- I select an unverified e-mail address
- I hit "make primary"
- I have the expected message "Your primary e-mail address must be verified.", BUT also the same thing as above happens: the e-mail address is submitted to the add_email_form which then displays the error message "This e-mail address is already associated with this account."

dollydagr

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/439
