### ISSUE TITLE
Non ascii characters in firstname result in username being default to "userxx" 

### ISSUE THREAD

**Issue by wktang** [pennersr/django-allauth#441]
## How to repro:
1. Register a google account (abc@gmail.com) with the first name set to some foreign characters. (ALL characters MUST be NON-ascii characters).
2. Sign up using that google account.
3. The registered username becomes `user`.
## Expected results:

Username should be `abc` instead of `user`.

I am able to repro this issue with this commit [e2afc61bf07852f12783f53309c6e28c7752086b](https://github.com/pennersr/django-allauth/commit/e2afc61bf07852f12783f53309c6e28c7752086b). And I have verified that the previous commit [82738a7a690e72a9bdc4ee168cb547603a2e8b45](https://github.com/pennersr/django-allauth/commit/82738a7a690e72a9bdc4ee168cb547603a2e8b45) has the correct behavior.
## Some extra debug information:

"allauth/account/adapter.py#151", first_name = "明"
"allauth/account/adapter.py#152", last_name = "小"
"allauth/account/adapter.py#153", email = "abc@gmail.com"
"allauth/utils.py#25", username = "明"
"allauth/utils.py#26", username = ""
"allauth/utils.py#27", username = ""
"allauth/utils.py#33", username = ""
"allauth/utils.py#34", username = "user"

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/441
