### ISSUE TITLE
Create an optional way to make a mandatory password change on first login (only on local account) after creating a new temporary password for a especific user name by the system administrator. 

### ISSUE THREAD

**Issue by luzfcb** [pennersr/django-allauth#448]
Create an optional way to make a mandatory password change on first login (only on local account) after creating a new temporary password for a especific user name by the system administrator. 

This password expire after a time pre-defined in settings.

On what line of code would be best for me to try to start implementing this feature?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/448
