### ISSUE TITLE
TemplateSyntaxError at /accounts/login/

### ISSUE THREAD

**Issue by ngroup** [pennersr/django-allauth#45]
Request Method: GET
Request URL:    http://localhost:8000/accounts/login/
Django Version: 1.3
Exception Type: TemplateSyntaxError
Exception Value:  
Caught DoesNotExist while rendering: FacebookApp matching query does not exist.
Exception Location: /usr/lib/pymodules/python2.7/django/db/models/query.py in get, line 349
Python Executable:  /usr/bin/python
Python Version: 2.7.2

Caught DoesNotExist while rendering: FacebookApp matching query does not exist.
1   {% load allauth_tags %}
2  
3   {% if allauth.facebook_enabled %}
4   {% fbconnect %}
5   {% endif %}
6  
7

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/45
