### ISSUE TITLE
Email domain-specific registration approval

### ISSUE THREAD

**Issue by cro** [pennersr/django-allauth#451]
Greetings,

Our nonprofit uses Google Apps for Domains for email, calendaring, etc.  We are also building a custom application to help with some business processes.  If anyone attempts to register and login via Google I want to automatically permit them only if their email address is from our domain.  If they are from another domain, I need to approve their registration before they can be allowed access to the application.  Is there support somewhere in django-allauth for this now?  If not, is the allauth.socialaccount.signals.pre_social_login signal the best place to try to insert this logic?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/451
