### ISSUE TITLE
Unicode error on social tokens admin page

### ISSUE THREAD

**Issue by caumons** [pennersr/django-allauth#453]
When trying to access the social tokens admin page I'm getting the error `UnicodeEncodeError: 'ascii' codec can't encode character u'\xf1' in position 13: ordinal not in range(128)`

I've seen in the django-allauth source code that the models implement the `__str__` method intead of `__unicode__` (see https://docs.djangoproject.com/en/dev/ref/unicode/#choosing-between-str-and-unicode). So, non ASCII characters seem to cause problems here. I think that ALL models should use `__unicode__`.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/453
