### ISSUE TITLE
How to re-enable django-avatar support?

### ISSUE THREAD

**Issue by caumons** [pennersr/django-allauth#454]
I've seen that commit a1cfa58f12fb54bcb5f0344abe5e9d6fbaacf2cb has dropped django-avatar support. I'm using this feature in a production server and currently using v0.13 and I'm now stucked because I can't update it or I would loose this functionality. I don't understand the reason of this change...

If you do really want to drop this feature, could you please at least give an example showing how this integration should be done from now on? I think that more users would appreciate this info.

Thanks!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/454
