### ISSUE TITLE
Some Spanish translations are incorrect or missing

### ISSUE THREAD

**Issue by mxpxgx** [pennersr/django-allauth#461]
Example:
Spanish translation for "Sign In" is incorrect. The usual translation for "Sign In" is "Iniciar sesión" or "Ingresar". 
Note that "sign up" has a different meaning than "sign in". "Sign in" has a similar meaning to "login" which you are translating to "Iniciar sesión".

The following code can be found in https://github.com/pennersr/django-allauth/blob/master/allauth/locale/es/LC_MESSAGES/django.po

<pre>
#: templates/account/login.html:7 templates/account/login.html.py:11
#: templates/account/login.html:39
msgid "Sign In"
msgstr "Regístrate"
</pre>

Also, some sentences need to be impersonal. Example:
"Por favor, escribe tu contraseña actual." (current version)
"Por favor, escriba su contraseña actual." (impersonal version)

I'll send you a pull request later this week. I hope it helps.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/461
