### ISSUE TITLE
Empty form action will not submit

### ISSUE THREAD

**Issue by shacker** [pennersr/django-allauth#463]
In Chrome 31 (and I believe some previous versions), a form with a blank action (action="") refuses to submit. Hence, the template `account/password_reset_from_key.html` needs to be modified:

```
<form method="POST" action="." class="uniForm">
```

The period in the action attribute gets it working in Chrome again.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/463
