### ISSUE TITLE
Providers should allow their display name to be overridden from the settings. 

### ISSUE THREAD

**Issue by airtonix** [pennersr/django-allauth#466]
IE: 

```
SOCIALACCOUNT_PROVIDERS = {
    "persona" : {
       "display-name": "Mozilla Persona",
       "alt-text": "Using only your email address, login with Mozilla Persona"
    }
}
```

This would override the name of a provider that is used in template where the list is built in a loop.
https://github.com/pennersr/django-allauth/blob/master/allauth/templates/socialaccount/snippets/provider_list.html#L16

**Comment by derek-adair** [comment]
can be closed as per your decision on https://github.com/pennersr/django-allauth/pull/1202

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/466
