### ISSUE TITLE
Redirect to home page after successful password change 

### ISSUE THREAD

**Issue by Anton-Shutik** [pennersr/django-allauth#468]
Try to change password at /accounts/password/change. It will offer you to change password again. How can I specify the url redirect to?

**Comment by psychok7** [comment]
Hey guys, how can i make it so that after a password change i don't get logged out? I am able to do the redirect but it always logges me out before which i do not want..

**Comment by benedwards44** [comment]
@psychok7 it looks like in Django 1.7 they updated the auth engine to log a user out when they change their own password. I got this working with django-allauth by overriding the form_valid method of the PasswordChangeView class and adding in update_session_auth_hash(request, user), as per the Django docs:
https://docs.djangoproject.com/en/1.8/topics/auth/default/#session-invalidation-on-password-change

My views.py:

    # myproject/app/views.py
    from django.contrib.auth import update_session_auth_hash
    from django.contrib import messages
    from allauth.account.views import PasswordChangeView
    from allauth.account.adapter import get_adapter
    from allauth.account import signals

    class MyPasswordChangeView(PasswordChangeView):
        """
        Custom class to override the password change view 
        """

        success_url = "/my_account/"

        # Override form valid view to keep user logged i
        def form_valid(self, form):

            form.save()

            # Update session to keep user logged in.
            update_session_auth_hash(self.request, form.user)

            get_adapter().add_message(self.request,
                                                messages.SUCCESS,
                                                'account/messages/password_changed.txt')

            signals.password_changed.send(sender=self.request.user.__class__,
                                                request=self.request,
                                                user=self.request.user)

            return super(PasswordChangeView, self).form_valid(form)

    password_change = login_required(MyPasswordChangeView.as_view())

And my urls.py:

    # myproject/urls.py
    url(r'^accounts/password/change/$', 'myapp.views.password_change', name='password_change'),
    url(r'^accounts/', include('allauth.urls')),

**Comment by smcoll** [comment]
@benedwards44 thanks for that.  it makes sense to me that a password reset would invalidate all sessions, but revalidate the current session only.

**Comment by psychok7** [comment]
@benedwards44 thanks works great

**Comment by frederikbotha** [comment]
@benedwards44 thanks

**Comment by Omnipresent** [comment]
@benedwards44  will this keep the user logged in after they change their password but just update the current users session?

**Comment by benedwards44** [comment]
@Omnipresent that's correct, the user will stay logged in.

**Comment by dmischel** [comment]
@benedwards44  that works great (django 1.11) and thanks, mate, for the snippet. Just what I needed. I presume allauth is not being actively maintained any longer, howsomever useful.

**Comment by doganmeh** [comment]
This issue seems to have started about redirecting to an url after successful change of the password and, somehow, have evolved into re-validating the session after the password change. I just checked with allauth version 0.36 and the session was valid after the password change, so there is no need for custom code. 

As far as the redirect is concerned, I came to think that it is more appropriate to show the password change form in a modal, thus, the user will just exit out of, and there will be no need to redirect.

**Comment by hipertracker2** [comment]
This is still broken. I am on django-allauth 0.39.1 and django 1.11. After successful password change I am always redirected back to reset password page (/accounts/password/change/) .

I also tried to use ACCOUNT_LOGOUT_REDIRECT_URL="/" and even ACCOUNT_LOGIN_ON_PASSWORD_RESET=True but those options are completely ignored :(

**Comment by hipertracker** [comment]
Problem solved. To fix the landing url after the password change:

First:
```
url(r"^accounts/password/change/$", CustomPasswordChangeView.as_view(), name="account_password_change")
```

Scond:
```
from allauth.account.views import PasswordChangeView

class CustomPasswordChangeView(PasswordChangeView):
    success_url = '/'
```

**Comment by YashMarmat** [comment]
if you working on templates then you need to create a specific template file or html file which will redirect you to the home page. Also you need to put your template file in below location only !

templates(folder)/registration(folder)/password_reset_complete.html

and this code inside your html file.

{% extends 'base.html' %}

{% block title %}Password reset complete{% endblock title %}

{% block content %}

    <h1>Password reset complete !</h1>
    <p>Your new password has been set. You can log in now on the
    <a href=
    "{% url 'login' %}">log in page</a>.</p>

{% endblock content %}

**Comment by efojs** [comment]
Can be done solely in `urls.py` with `success_url=` argument passed to `as_view()` function (but anyway a better place for the logic is in the `views.py`):
```python
from allauth.account import views as allauth_views
from django.urls import reverse_lazy

urlpatterns = [
    path(
        'account/password/change/', 
        login_required(
            allauth_views.PasswordChangeView.as_view(
                success_url=reverse_lazy('some_path_name')
            )
        ), 
        name='account_change_password'
    ),
    path('account/', include('allauth.urls')),
]
```

**Comment by cemonel** [comment]
> url(r"^accounts/password/change/$", CustomPasswordChangeView.as_view(), name="account_password_change")

Don't forget to add [login_required()](https://docs.djangoproject.com/en/dev/topics/auth/default/#the-login-required-decorator) decorator since decorator is added explicitly on allauth side.

`path("accounts/password/change/", CustomPasswordChangeView.as_view(), name="account_change_password"),`

**Comment by pbadeer** [comment]
> Can be done solely in `urls.py` with `success_url=` argument passed to `as_view()` function (but anyway a better place for the logic is in the `views.py`):
> 
> ```python
> from allauth.account import views as allauth_views
> from django.contrib.auth.decorators import login_required
> from django.urls import reverse_lazy
> 
> urlpatterns = [
>     path(
>         'account/password/change/', 
>         login_required(
>             allauth_views.PasswordChangeView.as_view(
>                 success_url=reverse_lazy('some_path_name')
>             )
>         ), 
>         name='account_change_password'
>     ),
>     # after custom pattern
>     path('account/', include('allauth.urls')),
> ]
> ```

Note that for most fresh installs nowadays, `'account/password/change/'` should actually be `'accounts/password/change/'` (account becomes plural). If this code isn't working, check what your other URLs are by finding this line in urls.py: `path('account/', include('allauth.urls')),` and if it says "account/" then use that but if it says "accounts/" then use that.

**Comment by stitch** [comment]
> Can be done solely in `urls.py` with `success_url=` argument passed to `as_view()` function (but anyway a better place for the logic is in the `views.py`):
...

This should be in the documentation, thank you!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/468
