### ISSUE TITLE
Authentication does not persist on close browser

### ISSUE THREAD

**Issue by medaveanderson** [pennersr/django-allauth#471]
Hi,
I am pretty sure I am doing something wrong, since this does work on two other sites I have..
When a logged-in user closes and reopens their browser, the authentication is lost, and they have to re-logon.

Just to be sure, I added these to my settings.py:

SESSION_COOKIE_AGE = 1209600
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

Still no luck with it.

Thanks for any idea

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/471
