### ISSUE TITLE
Connecting a social account (well.. openid) logs in a new user instead

### ISSUE THREAD

**Issue by muelli** [pennersr/django-allauth#473]
I just followed the instructions to run the example app. Then I logged in with the superuser credentials I provided during syncdb. I opened /accounts/social/connections/ and selected OpenID from the list. It does link to /accounts/openid/login/?process=connect. I enter "http://openid.aliz.es/somethingrandom" as my OpenID, hit enter and I am being "Successfully signed in as user."

I expected to be still logged in as the superuser and that the OpenID account is linked to said account.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/473
