### ISSUE TITLE
Nothing rendered from Google callback if user cancels on permission page.

### ISSUE THREAD

**Issue by pauricthelodger** [pennersr/django-allauth#477]
Hey there,

I've noticed that when a user with Google Oauth cancels signup from their Google-side scope permission page, the returned page on my website is blank with a uri in the form of `^accounts/google/login/callback/?error=access_denied&state=<string of alphanumerics>$`.

Any idea what should be happening?

Cheers!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/477
