### ISSUE TITLE
usernames that look like emails can cause overlap

### ISSUE THREAD

**Issue by johanneswilm** [pennersr/django-allauth#483]
If you permit both email address and username to sign in, the following may happen:
1. Hacker A knows the email of User B and knows User B is using Site C.
2. Hacker A creates a new account with a username that is the same as User B's email address.
3. Depending on what kind of site this is, Hacker A may even be able to add some user content saying something like "Your account has been temporarily disabled. Please send your credit card number to .... to reenable your account."
4. User B signs into Site C with his email, lands in the newly created account and sends his credit card number to Hacker A, believing this is what he has to do to get his account back.

Would it for example be possible to only let a user sign up with a username that contains "@" and "." if the user uses the same string as his email and it isn't registered as an email of any other user?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/483
