### ISSUE TITLE
Question concerning tokens

### ISSUE THREAD

**Issue by philippeluickx** [pennersr/django-allauth#486]
Hey!

I got following situation:
Users can sign up through both a social account or basic email/pw.
If users do a email/pw signup, they can still add a social account (process=connect) later on.
The application is using the access tokens from allauth to do some magic.  It recycles a client from allauth code, which uses tokens from the session.

Problem:
If a user that signed up with email/pw and then later added a social account, logs in with the email/pw, there is no tokens in the session.
For this to be solved, I provide the log-in url for the social account.
However, the view checks if a user is already authenticated and if yes, does a simple redirect (if I understand the code correctly).  Meaning that no tokens are added to the session.
What works is
- Login through social account (tokens are in the session)
- Connect social account (tokens are in the session)

Question:
In the end, I would just like to know what is the best way to deal with re-using access tokens.  It is fairly simple when a user did the login through the social account, but less trivial when done through email/pw (and connected account afterwards).  Is process=connect the way to go also for obtaining the token in this case?

Thanks!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/486
