### ISSUE TITLE
Facebook email handling, revisited

### ISSUE THREAD

**Issue by marfire** [pennersr/django-allauth#487]
There's an open question as to whether Facebook-reported emails can be considered verified or not (see #145 for background). I think that there's good reason to think that they are. Others have investigated the issue (see [here](http://stackoverflow.com/questions/14280535/is-it-possible-to-check-if-an-email-is-confirmed-on-facebook) and [here](http://stackoverflow.com/questions/11808030/is-a-users-email-address-confirmed-in-facebook-graph-api), for example) and come to the conclusion that "if an account hasn't verified it's email yet it's not possible to get it.". The counterexample that was reported [here](http://stackoverflow.com/questions/10651900/potential-security-issue-with-facebook-login) does not seem to have been replicated (see [here](https://github.com/bbangert/velruse/issues/69), for example). In one of the SO posts above, Facebook replied to the poster to indicate that there was a bug that had been fixed.

However, I don't see that Facebook has explicitly made this guarantee anywhere, so it's understandable that allauth would want to be conservative here.

However, it should be easy for a given allauth user to decide to trust those emails. That appears to have been the point of VERIFIED_EMAIL in the Facebook provider settings, but the current implementation requires that both that setting and Facebook's _verified_ flag be set. I don't think it makes sense to look at the _verified_ flag, since Facebook is using that word to mean something quite different that doesn't really have anything to do with email. Instead, the VERIFIED_EMAIL setting should mean that all Facebook emails are to be considered verified. Facebook's _verified_ flag should be ignored.

**Comment by johnyoonh** [comment]
Emails from Facebook is verified. Would you be able to revert this commit?
https://stackoverflow.com/questions/26672839/facebook-login-and-email-verification

**Comment by marfire** [comment]
@johnyoonh: This commit simply made it possible to trust Facebook emails, so reverting it wouldn't accomplish anything. It seems like your actual suggestion is to get rid of the setting and just assume all emails from Facebook are verified?

As I said above, I think there's "good reason" to do so. That said, I don't know of any new information on the subject. The SO link you posted just refers to the same answer I mentioned in the original report.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/487
