### ISSUE TITLE
AttributeError 

### ISSUE THREAD

**Issue by skizzy** [pennersr/django-allauth#49]
Hello, when trying to install django-allauth on my windows machine, I’m getting an error:

  C:\Djang.P\New folder\django-allauth>setup.py install
   running install
 running bdist_egg
running egg_info
writing requirements to django_allauth.egg-info\requires.txt
writing django_allauth.egg-info\PKG-INFO
writing top-level names to django_allauth.egg-info\top_level.txt
writing dependency_links to django_allauth.egg-info\dependency_links.txt
reading manifest file 'django_allauth.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.txt' under directory 'allauth\facebook\templ
ates'
writing manifest file 'django_allauth.egg-info\SOURCES.txt'
installing library code to build\bdist.win32\egg
running install_lib
running build_py
creating build\bdist.win32\egg
creating build\bdist.win32\egg\allauth
copying build\lib\allauth\app_settings.py -> build\bdist.win32\egg\allauth
copying build\lib\allauth\context_processors.py -> build\bdist.win32\egg\allauth

creating build\bdist.win32\egg\allauth\facebook
creating build\bdist.win32\egg\allauth\facebook\templates
creating build\bdist.win32\egg\allauth\facebook\templates\facebook
copying build\lib\allauth\facebook\templates\facebook\channel.html -> build\bdis
t.win32\egg\allauth\facebook\templates\facebook
copying build\lib\allauth\facebook\templates\facebook\fbconnect.html -> build\bd
ist.win32\egg\allauth\facebook\templates\facebook
copying build\lib\allauth\models.py -> build\bdist.win32\egg\allauth
copying build\lib\allauth\tests.py -> build\bdist.win32\egg\allauth
copying build\lib\allauth\urls.py -> build\bdist.win32\egg\allauth
copying build\lib\allauth\utils.py -> build\bdist.win32\egg\allauth
copying build\lib\allauth__init__.py -> build\bdist.win32\egg\allauth
byte-compiling build\bdist.win32\egg\allauth\app_settings.py to app_settings.pyc

byte-compiling build\bdist.win32\egg\allauth\context_processors.py to context_pr
ocessors.pyc
byte-compiling build\bdist.win32\egg\allauth\models.py to models.pyc
byte-compiling build\bdist.win32\egg\allauth\tests.py to tests.pyc
byte-compiling build\bdist.win32\egg\allauth\urls.py to urls.pyc
byte-compiling build\bdist.win32\egg\allauth\utils.py to utils.pyc
byte-compiling build\bdist.win32\egg\allauth__init__.py to **init**.pyc
creating build\bdist.win32\egg\EGG-INFO
copying django_allauth.egg-info\PKG-INFO -> build\bdist.win32\egg\EGG-INFO
copying django_allauth.egg-info\SOURCES.txt -> build\bdist.win32\egg\EGG-INFO
copying django_allauth.egg-info\dependency_links.txt -> build\bdist.win32\egg\EG
G-INFO
copying django_allauth.egg-info\requires.txt -> build\bdist.win32\egg\EGG-INFO
copying django_allauth.egg-info\top_level.txt -> build\bdist.win32\egg\EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist\django_allauth-0.4.0-py2.7.egg' and adding 'build\bdist.win32\egg
' to it
removing 'build\bdist.win32\egg' (and everything under it)
Processing django_allauth-0.4.0-py2.7.egg
Removing c:\python27\lib\site-packages\django_allauth-0.4.0-py2.7.egg
Copying django_allauth-0.4.0-py2.7.egg to c:\python27\lib\site-packages
django-allauth 0.4.0 is already the active version in easy-install.pth

Installed c:\python27\lib\site-packages\django_allauth-0.4.0-py2.7.egg
Processing dependencies for django-allauth==0.4.0
Searching for django-email-confirmation
Reading http://pypi.python.org/simple/django-email-confirmation/
Download error: [Errno 11004] getaddrinfo failed -- Some packages may not be fou
nd!
Couldn't find index page for 'django-email-confirmation' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading http://pypi.python.org/simple/
Download error: [Errno 11004] getaddrinfo failed -- Some packages may not be fou
nd!
No local packages or download links found for django-email-confirmation
Best match: None
Traceback (most recent call last):
  File "C:\Djang.P\New folder\django-allauth\setup.py", line 33, in <module>
    setup(**METADATA)
  File "C:\Python27\lib\distutils\core.py", line 152, in setup
    dist.run_commands()
  File "C:\Python27\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "C:\Python27\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Python27\lib\site-packages\setuptools\command\install.py", line 76, i
n run
    self.do_egg_install()
  File "C:\Python27\lib\site-packages\setuptools\command\install.py", line 104,
in do_egg_install
    cmd.run()
  File "C:\Python27\lib\site-packages\setuptools\command\easy_install.py", line
211, in run
    self.easy_install(spec, not self.no_deps)
  File "C:\Python27\lib\site-packages\setuptools\command\easy_install.py", line
427, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "C:\Python27\lib\site-packages\setuptools\command\easy_install.py", line
478, in install_item
    self.process_distribution(spec, dist, deps)
  File "C:\Python27\lib\site-packages\setuptools\command\easy_install.py", line
519, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "C:\Python27\lib\site-packages\pkg_resources.py", line 563, in resolve
    dist = best[req.key] = env.best_match(req, self, installer)
  File "C:\Python27\lib\site-packages\pkg_resources.py", line 799, in best_match

```
return self.obtain(req, installer) # try and download/install
```

  File "C:\Python27\lib\site-packages\pkg_resources.py", line 811, in obtain
    return installer(requirement)
  File "C:\Python27\lib\site-packages\setuptools\command\easy_install.py", line
434, in easy_install
    self.local_index
  File "C:\Python27\lib\site-packages\setuptools\package_index.py", line 475, in
 fetch_distribution
    return dist.clone(location=self.download(dist.location, tmpdir))
AttributeError: 'NoneType' object has no attribute 'clone'

How can I get rid of that? Thanks!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/49
