### ISSUE TITLE
ACCOUNT_EMAIL_VERIFICATION = 'mandatory' but auto-signing in after sign up

### ISSUE THREAD

**Issue by chogarcia** [pennersr/django-allauth#494]
ACCOUNT_EMAIL_VERIFICATION = 'mandatory' 
but it is still auto signing in without email verified

my settings are:

```
ACCOUNT_AUTHENTICATION_METHOD = 'email' 
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = 'mandatory' 
ACCOUNT_USERNAME_REQUIRED = False
```

am I doing something wrong?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/494
