### ISSUE TITLE
Support Yahoo flavored OpenID/OAuth

### ISSUE THREAD

**Issue by brycenesbitt** [pennersr/django-allauth#497]
Despite broad support for social providers, the #3 social provider (http://janrain.com/blog/social-login-trends-across-the-web-for-q4-2013/ ), is not listed as a provider, and a search for Yahoo in the allauth docs produces no results (it's listed in the code however).

The Yahoo developer site is http://developer.yahoo.com/auth/ .  Will Yahoo get it's own provider in allauth?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/497
