### ISSUE TITLE
MySQL OpenID and Identity Field

### ISSUE THREAD

**Issue by Apreche** [pennersr/django-allauth#5]
I notice that you are aware of the issue relating to the identify field in the OpenID Account model judging by this comment on line 7 of allauth/openid.models.py

```
# Ideally, URLField(max_length=1024, unique=True) would be used
# for identity.  However, MySQL has a max_length limitation of 255
# for URLField. So let's be pragmetic and switch to TextField...
# TODO: Model field validation to ensure valid URLs
```

However, your solution does not fix the problem.

First of all, I see you have created a South migration to change the field. The problem is that the initial migration will always fail because MySQL will not allow you to create a field with max_length 1024. Thus, it is impossible to even get to the second migration which uses a text field instead.

I went and deleted both migrations and created just one. Of course, that doesn't work either. 

You specified the TextField to be unique, which just doesn't work. 

http://code.djangoproject.com/ticket/2495

Django allauth will not work in MySQL until you fix this.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/5
