### ISSUE TITLE
Trying to automate setting up initial data for Site and SocialApp for tests with Lettuce

### ISSUE THREAD

**Issue by robrechtdr** [pennersr/django-allauth#500]
**I want to automate setting up initial data for the Site and SocialApp models (for Github in my case) instead of manually setting this up via the admin** (for tests but also for other deployments). 

Now **I want to keep my Secret keys for all deployments for the Github apps secret** so I'm not using fixtures. 

I thought that **creating a custom management command to set up the data** would be the least ugly solution so I'm now running the following command to set up initial data for my Github app after `syncdb` and `migrate`:

```
python manage.py setup_allauth_social github --domain='http://localhost' --social_app_name='github_social_app'
```

This command works fine on every environment I've tried it on (local and test). But **when I use it with [Lettuce](http://lettuce.it/reference/terrain.html#lettuce-before-each-scenario) before each scenario, the Site and SocialApp data seem to have dissappeared on running the test steps in each scenario**:

---

_In `terrain.py`_

```
@before.each_scenario
def scenario_setup(scenario):
    """
    Setup before each scenario
    """
    # I think it's safe to assume changes to the db schema will not be
    # made in between running scenarios. So the flush command 
    # should be sufficient.
    call_command('flush', interactive=False, verbosity=1)
    call_command('setup_allauth_social', 'github', domain="http://localhost", setting="test")
```

_In `my_app/features/test_initial_data.feature`_

```
Given I go to the "/accounts/login/"
```

When I run the following :

```
python manage.py harvest -T -d --failfast --apps=my_app --settings=my_project.settings.test`
```

The test fails and I get the following:

```
DoesNotExist: Site matching query does not exist. Lookup parameters were {'pk': 2}
```

This also fails exactly in the same way if I use `@before.each_step` instead of `@before.each_scenario`.

---

This is likely caused because I set `SITE_ID = 2` in my settings and the `Site` entry with id of 2 doesn't exist at that point. But the question is, **why doesn't it exist in a Lettuce step but it does when I run the management command in my development environment or when I use unit tests?**

**I think it could have something to do with Allauth's migrations in combination with Lettuce calling a certain set of commands handling those Allauth migrations incorrectly just after Lettuce runs the functions decorated with `@before.each_scenario` and `@before.each_step`.**

Care to shed some light on the situation?

It's hard to imagine that I'm the first one to run into this problem, but I couldn't find any reports about this.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/500
