### ISSUE TITLE
Document/Support both HTTP & HTTPS flavors for Amazon OAuth2

### ISSUE THREAD

**Issue by brycenesbitt** [pennersr/django-allauth#501]
I added an 'amazon' provider to an existing site, but found it not quite as simple as it seemed.
Unlike Facebook/Google/Yahoo/Twitter, it appears that Amazon really wants a https website for use with Amazon login.

This feature request is to document the HTTPS requirements in allauth's readthedocs, in the Amazon section. 

Background is at:
https://sellercentral.amazon.com/forums/thread.jspa?messageID=2472691&#2472691
An 'Authorization Code Grant' on the server side can be used to bypass the requirement.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/501
