### ISSUE TITLE
KeyError: 'request' at tail end of Amazon OAuth2 process

### ISSUE THREAD

**Issue by brycenesbitt** [pennersr/django-allauth#502]
I have Amazon OAuth2 working to the point where it can reject a duplicate login.
On a successful login however I get:

```
socialaccount.py, line 18, in render:     request = context['request']
context.py, line 57, in __getitem__ raise KeyError(key)
KeyError: 'request'
```

Seemingly when it tries to render the final template.  Since it can't find the request object, and I can't test this locally under a debugger, there is not a lot to go on.  Class ProviderLoginURLNode(template.Node) is the one that dies.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/502
