### ISSUE TITLE
BaseSignupForm "Username" has unfortunately short maxlength=30

### ISSUE THREAD

**Issue by brycenesbitt** [pennersr/django-allauth#505]
Our site is configured with email as username.

We had a visitor with a 32 character email address who could not signup.  The issue (or at least the first issue) is here:

```
class BaseSignupForm(_base_signup_form_class()):
    username = forms.CharField(label=_("Username"),
                               max_length=30,
```

I'm not sure if this is a mirror of django's 30 character default in the AbstractUser model, but either way it really is not quite enough for email address as username.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/505
