### ISSUE TITLE
Inputted email ignored in signup if a custom user has the email as username

### ISSUE THREAD

**Issue by ialbert** [pennersr/django-allauth#512]
A very common use-case is that of using the email the  username. In those cases the username will overwrite the email that is inputted in the form.

The problem manifests itself in the case where there is a custom user with email as its username. In those cases both settings have to be the same

ACCOUNT_USER_MODEL_USERNAME_FIELD = "email"
ACCOUNT_USER_MODEL_EMAIL_FIELD = "email"

But the order of operation in the `account.adapter` at line 180 makes it so that the username overwrites the email, but since the username is not sent in the form the email will be set to be empty.

https://github.com/pennersr/django-allauth/blob/master/allauth/account/adapter.py#L180

The solution is to reverse the order by which the two fields are updated basically calling  the helper function `user_username` first, and `user_email` second.

**Comment by rocchidavide** [comment]
I set ACCOUNT_USER_MODEL_USERNAME_FIELD = None, but with this endpoint
http://127.0.0.1:8000/rest-auth/user/
I still obtain 
ImproperlyConfigured at /rest-auth/user/
Field name `username` is not valid for model `CustomUser`.

In my settings.py I had:

ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'

**Comment by pennersr** [comment]
The endpoint you are referring to is not implemented by allauth.

**Comment by rocchidavide** [comment]
Ops... sorry man

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/512
