### ISSUE TITLE
Use a uniform convention for specifying redirect urls

### ISSUE THREAD

**Issue by marfire** [pennersr/django-allauth#513]
Some of the views (many `sociallogin` views, `LoginView`, etc.) take an explicit `next` parameter specifying the url to redirect to on success. Others (like `PasswordChangeView`) have their redirect hardcoded, and you need to write some code to specify where to redirect.

The proposal here is to always check for a `next` (or `redirect_field_name`) parameter when redirecting. This would be more uniform and more flexible.

**Comment by bitcity** [comment]
+1, this would be a nifty change.

**Comment by derek-adair** [comment]
This is a very useful feature that I _believe_ is still on the table.  Very worthy of contribution if anyone is looking to jump in on something.  My bandwidth is limited to triage at the moment while I run builds / tests / play everquest.

**Comment by pennersr** [comment]
Done via #3727

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/513
