### ISSUE TITLE
Documentation: Icons at top are not responsive

### ISSUE THREAD

**Issue by cconrad** [pennersr/django-allauth#514]
Hi

Thanks for a great product.

I just wanted to let you know that the icons at the top of the Sphinx documentation are way to large on smaller screens:

![image](https://f.cloud.github.com/assets/584491/1957851/4cc05f9a-820f-11e3-8d5e-90b4a835c9b1.png)

Not sure why this happens, I also saw something similar on the Pyramid documentation. When I maximize the browser window the icons appear as intended, but I suspect this might be an issue for visitors on mobile devices.

Regards,
Claus

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/514
