### ISSUE TITLE
Check to see if there's a username before trying to use it in templates.

### ISSUE THREAD

**Issue by marfire** [pennersr/django-allauth#515]
In `password_reset_key_message.txt` there's the following

> In case you forgot, your username is {{username}}.

where `username` is hardcoded as `user.username`. Instead, it should presumably check the value of `ACCOUNT_USER_MODEL_USERNAME_FIELD`, and skip the line entirely if the value is `None`.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/515
