### ISSUE TITLE
Allauth not consistent in treating emails as case-insensitive

### ISSUE THREAD

**Issue by marfire** [pennersr/django-allauth#517]
In general, allauth treats email addresses in a case-insensitive way—in particular, the authentication backend uses `email__iexact` for lookups.

In same other places, though, that is not the case. Here are two I stumbled upon:
- In [`EmailAddressManager.get_users_for()`](https://github.com/pennersr/django-allauth/blob/master/allauth/account/managers.py#L35) the query says `email=email` instead of `email__iexact=email`.
- In [`EmailAddressManager.add_email()`](https://github.com/pennersr/django-allauth/blob/master/allauth/account/managers.py#L15) we do a `Model.create()`, checking for an `IntegrityError`. This will fail to raise the error if there is a case-insensitive match. Instead we'll probably have to check the database explicity (depending on the value of `app_settings.UNIQUE_EMAIL`).

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/517
