### ISSUE TITLE
Allow switching to a non-verified primary email address as specified in settings

### ISSUE THREAD

**Issue by marfire** [pennersr/django-allauth#518]
I'm quite surprised by the behavior discussed in #111 (implemented [here](https://github.com/pennersr/django-allauth/blob/master/allauth/account/views.py#L377)). Shouldn't that only apply when `ACCOUNT_EMAIL_VERIFICATION` is `mandatory`?

If email verification is set to `optional`, then you're saying that you're comfortable with the user accessing the site with an unverified primary email address. That should be respected here as well. (Perhaps that patch predated the introduction of `optional`?)

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/518
