### ISSUE TITLE
setup broken 

### ISSUE THREAD

**Issue by GeniusWiki** [pennersr/django-allauth#52]
try this:
sudo pip install git+https://github.com/pennersr/django-allauth.git

after install it doesn't include sub-models - no any subdirectory except facebook wich includes some html files. 
ls -lrt /Library/Python/2.7/site-packages/allauth

-rw-r--r--  1 root  wheel  2176 20 Mar 22:11 utils.py
-rw-r--r--  1 root  wheel   765 20 Mar 22:11 urls.py
-rw-r--r--  1 root  wheel   627 20 Mar 22:11 tests.py
-rw-r--r--  1 root  wheel     0 20 Mar 22:11 models.py
-rw-r--r--  1 root  wheel   328 20 Mar 22:11 context_processors.py
-rw-r--r--  1 root  wheel   402 20 Mar 22:11 app_settings.py
-rw-r--r--  1 root  wheel     0 20 Mar 22:11 **init**.py
-rw-r--r--  1 root  wheel  2810 20 Mar 22:11 utils.pyc
-rw-r--r--  1 root  wheel   797 20 Mar 22:11 urls.pyc
-rw-r--r--  1 root  wheel  1036 20 Mar 22:11 tests.pyc
-rw-r--r--  1 root  wheel   138 20 Mar 22:11 models.pyc
drwxr-xr-x  3 root  wheel   102 20 Mar 22:11 facebook
-rw-r--r--  1 root  wheel   616 20 Mar 22:11 context_processors.pyc
-rw-r--r--  1 root  wheel   517 20 Mar 22:11 app_settings.pyc
-rw-r--r--  1 root  wheel   140 20 Mar 22:11 **init**.pyc

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/52
