### ISSUE TITLE
<ImageFieldFile: None> is not JSON serializable

### ISSUE THREAD

**Issue by proft** [pennersr/django-allauth#520]
Hello!

I have `Django==1.6.1` and `django-allauth==0.15.0`. 
I use custom user model 

```
class User(AbstractBaseUser, PermissionsMixin):
    name = models.CharField('Name', max_length=255)
    email = models.EmailField(verbose_name="E-Mail", max_length=255, unique=True, db_index=True)
    photo = StdImageField(verbose_name="Photo", upload_to="photos", blank=True, size=(290, 290), thumbnail_size=(90, 90, True))
...
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["name", ]
```

After sign in with Twitter I got 

```
TypeError at /accounts/twitter/login/callback/
<ImageFieldFile: None> is not JSON serializable
```

Traceback 

```
Traceback:
File "/home/www/.virtualenvs/site/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  114.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/home/www/.virtualenvs/site/lib/python2.7/site-packages/allauth/socialaccount/providers/oauth/views.py" in view
  35.             return self.dispatch(request, *args, **kwargs)
File "/home/www/.virtualenvs/site/lib/python2.7/site-packages/allauth/socialaccount/providers/oauth/views.py" in dispatch
  91.             return complete_social_login(request, login)
File "/home/www/.virtualenvs/site/lib/python2.7/site-packages/allauth/socialaccount/helpers.py" in complete_social_login
  119.         return _complete_social_login(request, sociallogin)
File "/home/www/.virtualenvs/site/lib/python2.7/site-packages/allauth/socialaccount/helpers.py" in _complete_social_login
  130.         ret = _process_signup(request, sociallogin)
File "/home/www/.virtualenvs/site/lib/python2.7/site-packages/allauth/socialaccount/helpers.py" in _process_signup
  28.         request.session['socialaccount_sociallogin'] = sociallogin.serialize()
File "/home/www/.virtualenvs/site/lib/python2.7/site-packages/allauth/socialaccount/models.py" in serialize
  166.                    user=serialize_instance(self.account.user),
File "/home/www/.virtualenvs/site/lib/python2.7/site-packages/allauth/utils.py" in serialize_instance
  151.     return json.loads(json.dumps(ret, cls=DjangoJSONEncoder))
File "/opt/python2.7/lib/python2.7/json/__init__.py" in dumps
  250.         sort_keys=sort_keys, **kw).encode(obj)
File "/opt/python2.7/lib/python2.7/json/encoder.py" in encode
  207.         chunks = self.iterencode(o, _one_shot=True)
File "/opt/python2.7/lib/python2.7/json/encoder.py" in iterencode
  270.         return _iterencode(o, 0)
File "/home/www/.virtualenvs/site/lib/python2.7/site-packages/django/core/serializers/json.py" in default
  104.             return super(DjangoJSONEncoder, self).default(o)
File "/opt/python2.7/lib/python2.7/json/encoder.py" in default
  184.         raise TypeError(repr(o) + " is not JSON serializable")

Exception Type: TypeError at /accounts/twitter/login/callback/
Exception Value: <ImageFieldFile: None> is not JSON serializable
```

Advice with `SESSION_SERIALIZER` dont help me. Result is the same.

**Comment by andres-torres-marroquin** [comment]
I'm running into this issue too and as @patrick91 pointed out. Removing the field or renaming it with _ prefix "fixes the error" but I'm sure this is not the best solution for this. Have some of you fixed this in the right way?

**Comment by andres-torres-marroquin** [comment]
I fixed it changing the name of the fields, but I also added a proxy to the original name of the fields, so I could keep the rest of the code as it was.

Before the fix.
```python
class User(AbstractUser):
    ...
    avatar = models.ImageField(upload_to='avatars', null=True, blank=True)
    cover = models.ImageField(upload_to='covers', null=True, blank=True)
```

With the fix.
```python
class User(AbstractUser):
    ...
    _avatar = models.ImageField(upload_to='avatars', null=True, blank=True, db_column='avatar')
    _cover = models.ImageField(upload_to='covers', null=True, blank=True, db_column='cover')

    @property
    def avatar(self):
        return self._avatar

    @avatar.setter
    def avatar(self, value):
        self._avatar = value

    @property
    def cover(self):
        return self._cover

    @cover.setter
    def cover(self, value):
        self._cover = value
```

**Comment by gluwa** [comment]
I am experiencing this issue with default django imagefield.

Below is my test.

    from __future__ import absolute_import
    from __future__ import unicode_literals
    
    from django.test import TestCase
    from django.db import models
    
    from allauth.utils import serialize_instance
    
    
    class ImageModel(models.Model):
        """
        An abstract base class model that provides image field
        that represents the model.
        """
        image = models.ImageField(upload_to='image')
    
    
    class TestCase(TestCase):
    
        def test_serialization(self):
            image_model = ImageModel.objects.create()
            serialize_instance(image_model)

When you run it:

    $ ./manage.py test custom_user
    Creating test database for alias 'default'...
    E
    ======================================================================
    ERROR: test_serialization (app.tests.TestCase)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/project/app/tests.py", line 22, in test_serialization
        serialize_instance(image_model)
      File "/Volumes/HDD/Developer/gluwa/src/lib/allauth/utils.py", line 184, in serialize_instance
        return json.loads(json.dumps(ret, cls=DjangoJSONEncoder))
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 250, in dumps
        sort_keys=sort_keys, **kw).encode(obj)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 207, in encode
        chunks = self.iterencode(o, _one_shot=True)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 270, in iterencode
        return _iterencode(o, 0)
      File "/usr/local/google_appengine/lib/django-1.5/django/core/serializers/json.py", line 103, in default
        return super(DjangoJSONEncoder, self).default(o)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 184, in default
        raise TypeError(repr(o) + " is not JSON serializable")
    TypeError: <ImageFieldFile: None> is not JSON serializable
    
    ----------------------------------------------------------------------
    Ran 1 test in 0.055s
    
    FAILED (errors=1)
    Destroying test database for alias 'default'...

**Comment by gluwa** [comment]
@andres-torres-marroquin 's solution would work, but I don't think we should be forced to use a monkey patch.

**Comment by ryankask** [comment]
This is a django-allauth issue because custom user models can have any Django model field. If your user model had a `HandField` from the [docs](https://docs.djangoproject.com/en/1.10/howto/custom-model-fields/#converting-values-to-python-objects), for example, this error would occur because `DjangoJSONEncoder` doesn't know how to encode that type.

Potential solutions include:

- Not trying to serialise the `User` instance. Instead just serialise the natural key and fetch the user using that when needed (seems best to me)
- Add another setting specifying which JSON encoder to use.

**Comment by dethos** [comment]
@pennersr it seems @ryankask is right, I'm having the same issue with a custom user model with a type that `DjangoJSONEncoder` doesn't know how to encode.

Django: 1.10
All-auth: 0.27.0

Error: `TypeError: <UTC> is not JSON serializable`

Line on `allauth/socialaccount/models.py ? in serialize`:
 ```
    def serialize(self):
        ret = dict(account=serialize_instance(self.account),
                   user=serialize_instance(self.user),
                   state=self.state,
                   email_addresses=[serialize_instance(ea)
                                    for ea in self.email_addresses])
        ...
```

**Comment by davidmr** [comment]
I'm having this same issue with a custom User model that has a `ProcessedImageField` from [django-imagekit](https://github.com/matthewwithanm/django-imagekit).

I think a setting to specify which JSONEncoder to use would work.

**Comment by dethos** [comment]
It seems the issue is confirmed for custom users models with custom fields, which are more prevalent nowadays. It would be good if this issue could be reopened and the label `Unconfirmed` removed.

**Comment by pennersr** [comment]
> Not trying to serialise the User instance. Instead just serialise the natural key and fetch the user using that when needed (seems best to me)

That is not an option. The user being serialized is actually a temporary user instance, not yet backed by a database record, hence, no key exists.

**Comment by pennersr** [comment]
A bit of background: the issue is caused by the fact that after the provider handshake unsaved model instances are being assembled. So, we have an unsaved User instance, a SocialAccount instance and perhaps a SocialToken instance.

Now, it may be the case that after the handshake additional questions are to be asked to the user using the social signup form. What happens in this case is that the unsaved instances are stashed into the session, to be picked up at a later time once the social signup form is completed. 

Making the serialization pluggable is an option, though it is quite a hassle having to setup your own serialization for something as simple as a `TimeZoneField`. Also, I am afraid people will easily forget about this scenario, as depending on the flows the serialization route may or may note be taken.

Adding support for more fields can be done. For example, the ImageField is a regular Django field that can be properly handled. But, that won't help you when you are using a 3rd party `TimeZoneField`.

All in all, I would really like to see a solution that "just works"... leaning towards something like this:

- Add support for ImageField

- For fields that are not serializable, store the DB prep value:

```
>>> instance._meta.get_field('timezone').get_prep_value(v)
'UTC'
```
And, use `from_db_value` when deserializing.

The above is likely to be sufficient to get things working out of the box for most use cases. But, just in case there you have uncommon models/data types, we can move the (de)serialize method into the adapter so that if all else fails one can still override and adjust things as needed.

**Comment by pennersr** [comment]
I've moved ahead and added the above (cedad9f156a8c78bfbe43a0b3a723c1a0b840dbd). This approach is not pretty, but hopefully it is effective. Could you all let me know if this solves the issues with your custom user models...?

**Comment by davidmr** [comment]
@pennersr I tried the commit and it fixed my issue.

**Comment by dethos** [comment]
@pennersr sorry for the delay. I just tried the new version of allauth which includes the mentioned commit and on my case the problem seems to be solved.

**Comment by Nabu-thinker-ru** [comment]
I have custom user model with ImageField. I'd got error "Unable to auto serialize field 'origin', custom serialization override required", because 'ImageField' object has no attribute 'from_db_value'.

**Comment by sbywater** [comment]
I also still get this error running 0.35.0, with a custom user model that has a django ImageField.

**Comment by faprietoml** [comment]
I have a User model that is a subclass of AbstractUser and that has a 'photo' attribute.

The following error occurs:

```'Internal Server Error: /accounts/social/signup /
ImproperlyConfigured at /accounts/social/signup/
Unable to auto serialize field 'photo', custom serialization override required
```

django-allauth==0.40.0
Any idea to fix this???

**Comment by faprietoml** [comment]
> I have a User model that is a subclass of AbstractUser and that has a 'photo' field (ImageField).
> 
> The following error occurs:
> 
> ```
> ImproperlyConfigured at /accounts/social/signup/
> Unable to auto serialize field 'photo', custom serialization override required
> ```
> 
> django-allauth==0.40.0
> Any idea to fix this???

For sharing. I ended up adding a validation in the **deserialize_instance** method

```
SOCIALACCOUNT_ADAPTER=CustomSocialAccountAdapter

class CustomSocialAccountAdapter(DefaultSocialAccountAdapter):
    def deserialize_instance(self, model, data):
        ...
        elif is_db_value and not isinstance(f, ImageField):
        ....
```

I copied the original method and added this line in previous **if**:
``and not isinstance(f, ImageField)``

Thx.

**Comment by alfonsobreak28** [comment]
> [@andres-torres-marroquin](https://github.com/andres-torres-marroquin) 's solution would work, but I don't think we should be forced to use a monkey patch.





https://stackdev.space/questions/allowing-flexibility-in-emailfield-validation-in-django

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/520
