### ISSUE TITLE
Connecting an already registered social account

### ISSUE THREAD

**Issue by robrechtdr** [pennersr/django-allauth#523]
Just so you know:

Suppose that a user signs up via Github account. He then logs out.

Then another user makes a regular site account and goes to `/accounts/social/connections/` to connect the same Github account as the previous user to his account. 

Clicking on the `Github` link under _Add a 3rd Party Account_ now **just redirects to `/accounts/social/connections/` again without any message that the Github account is already registered**. It doesn't register it though (which is a good thing)

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/523
