### ISSUE TITLE
The login template tries to load the socialaccount templatetags even if you do not include the socialaccount app

### ISSUE THREAD

**Issue by AntelopeSalad** [pennersr/django-allauth#524]
I'm not sure if this is unexpected behavior or not. I decided to use allauth to handle the standard complete flow of creating an account with password resetting and all of that boring stuff.

I didn't plan to use it for its social features so I didn't include the `socialaccount` app anywhere in my `settings.py` file but when I hit `/accounts/login/` it throws a template error because it tries to do `{% local socialaccount %}` which clearly doesn't exist.

Perhaps the template should be smart enough not to include that if it does not exist?

I planned to overwrite all of the templates so it's not a big deal in the end.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/524
