### ISSUE TITLE
FEATURE REQUEST: Logging in by multiple field types (ex. email OR username)

### ISSUE THREAD

**Issue by AntelopeSalad** [pennersr/django-allauth#525]
Right now it seems like we can only login by email or username individually but there's no easy way to login by email or username from what I've seen.

For example it would be awesome if we could do:

`ACCOUNT_AUTHENTICATION_METHOD = ('email', 'username')`

And then it would accept either an email address or the username for the login name.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/525
