### ISSUE TITLE
Problem with multiple types of users

### ISSUE THREAD

**Issue by raakeshkumar** [pennersr/django-allauth#535]
I am using Django 1.6.1 and allauth .15. I have multiple types of users so i have to take user types as a form part so i am redirecting users where they select their user type and face below problems:
1 - Why username and email automatically appear there? (Very Annoying)
2 - With Google i don't get username and email. Can you suggest me something for that?
3 - Since Twitter doesn't return email, i want that an auto-generated email gets filled up with twitter because with blank, it throws an error Duplicate entry '' for key 'email'. Maybe something similar with Google also?
4 - I want that once a user selects a user type, they should be redirected to a different form where they will fill up other profile details before login. And this form is different for different users.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/535
