### ISSUE TITLE
Specify redirect_url for after social sign up action

### ISSUE THREAD

**Issue by variable** [pennersr/django-allauth#538]
Is it possible to specify the redirect_url explicitly for after signing up with social account? Reason being we need to have a validation detail screen but we are not able to manipulate it by catching the user_signed_up signal:

<pre>
socialaccount/models.py
def get_redirect_url(self, request):
          url = self.state.get('next')
          return url 

in account/utils.py
def complete_signup(request, user, email_verification, success_url,
                    signal_kwargs={}):
    signals.user_signed_up.send(sender=user.__class__,
                                request=request,
                                user=user,
                                **signal_kwargs)
    return perform_login(request, user,
                         email_verification=email_verification,
                         signup=True,
                         redirect_url=success_url,
                         signal_kwargs=signal_kwargs)

socialaccount/helpers.py
return complete_signup(request,
                           sociallogin.account.user,
                           app_settings.EMAIL_VERIFICATION,
                           sociallogin.get_redirect_url(request),
                           signal_kwargs={'sociallogin': sociallogin})

</pre>

sociallogin.get_redirect_url(request) gets executed before sending the signal, leaving no chance to manipulate the url by changing the 'next' value in state dictionary.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/538
