### ISSUE TITLE
after changing their email address, users are still able to login with their old email address (as well as the new one)

### ISSUE THREAD

**Issue by krisfields** [pennersr/django-allauth#539]
I have the following settings:

```
ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
```

On line 48 of allauth/account/auth_backends:

```
users = User.objects.filter(Q(email__iexact=email)
                                    | Q(emailaddress__email__iexact=email))
```

If the user enters an old email address, it finds it via the latter part of the query.  Apparently the user.emailaddress_set.all() has the old email address saved still.  I'm not sure why.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/539
