### ISSUE TITLE
ACCOUNT_EMAIL_SUBJECT_PREFIX error

### ISSUE THREAD

**Issue by guillaumevincent** [pennersr/django-allauth#540]
I try to found in django-allauth where ACCOUNT_EMAIL_SUBJECT_PREFIX is used.
I found only one usage in tests line 33 in allauth/account/tests.py.
I think there is an error on fomat_email_subject function in adapter.py

``` python
    def format_email_subject(self, subject):
        prefix = app_settings.EMAIL_SUBJECT_PREFIX
        if prefix is None:
            site = Site.objects.get_current()
            prefix = u"[{name}] ".format(name=site.name)
        return prefix + force_text(subject)
```

This code should not look like this:

``` python
    def format_email_subject(self, subject):
        prefix = app_settings.ACCOUNT_EMAIL_SUBJECT_PREFIX
        if prefix is None:
            site = Site.objects.get_current()
            prefix = u"[{name}] ".format(name=site.name)
        return prefix + force_text(subject)
```

I'm not proposing a pull-request because I don't understand a test I've made:

If my settings.py is:

```
EMAIL_SUBJECT_PREFIX = '[TEST] '
ACCOUNT_EMAIL_SUBJECT_PREFIX = '[TEST] '
```

I got `[127.0.0.1:8000] Confirm E-mail Address` instead of `[TEST] Confirm E-mail Address`

Is there an explanation on this issue ?
Thank you

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/540
