### ISSUE TITLE
Throttling of login attempts?

### ISSUE THREAD

**Issue by jleclanche** [pennersr/django-allauth#541]
Our project needs login attempts throttling. Is this a feature that would be welcome in allauth itself, or is it wiser to develop it outside of allauth? Are there existing solutions that play well with allauth?
I'd be willing to send a PR implementing login attempt throttling in the coming days if it's acceptable in core. I didn't find anything in the docs regarding this.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/541
