### ISSUE TITLE
Feature request: Email Regex

### ISSUE THREAD

**Issue by lpalomo** [pennersr/django-allauth#543]
Hi, I would like to present an idea that maybe could be nice to have. In my website I'm currently only allowing known email providers (as gmail, outlook, hotmail, etc.), for this I've added a check constraint on my DB (regex) (previewsly I tried adding a regex validator on the email field but it didn't work), so I think would be nice if there is a way to set an option with the regex used for validating emails. What do you think?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/543
