### ISSUE TITLE
Using Django-facebook side by side

### ISSUE THREAD

**Issue by DanielFerreiraJorge** [pennersr/django-allauth#545]
I'm thinking of using django-allauth for a new project, but I also want to use some of the more advanced facebook integrations provided by https://github.com/tschellenbach/Django-facebook

Is it possible to achieve this? Well... anything is possible but, does anybody know a easy way? Does it work out-of-the-box?

Thanks!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/545
