### ISSUE TITLE
Space in usernames - google plugin

### ISSUE THREAD

**Issue by scotartt** [pennersr/django-allauth#553]
I had a user register with the Google plugin. Obviously the person had filled in their Google name with their initial in the first name field, e.g. "F. Scott"  "Fitzgerald" or "Richard M." "Nixon" The plugin therefore created their username in Django as "richard m.". Clearly it worked and the user continued happily on their way.

But when I went to edit the user's permissions, to give them more access to my system, (i.e. add them to a group) the Django Admin module complained about the username - the space specifically. I had to edit the username to remove the space (I changed "richard m." to "richard") before I could save the user groups change.

I don't know whether me editing their username materially affects anything with their social authorisation or login, but, it would be nice if allauth created a username compatible with the Django admin app. 

While I'm on that point perhaps it be nice if the app did something like make the username the concatenation of the first AND last names in Google (stripping all the spaces)? So I become "scotmcphee" and not "scot2" because there's another "scot" already registered?

I'm running python 3.3, Django 1.6.2, and whatever the version of allauth was that pip installed on last Saturday.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/553
