### ISSUE TITLE
Feature request: Evernote authentication provider

### ISSUE THREAD

**Issue by jleclanche** [pennersr/django-allauth#556]
Evernote auth is oauth-based:
https://dev.evernote.com/doc/articles/authentication.php
http://django-social-auth.readthedocs.org/en/latest/backends/evernote.html
https://github.com/leehsueh/django-evernote-oauth

Would be great to have support for it.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/556
