### ISSUE TITLE
Encrypt social tokens

### ISSUE THREAD

**Issue by agriffis** [pennersr/django-allauth#557]
Given news like this: http://www.quora.com/Buffer/How-was-Buffer-compromised-today-10-26-2013

I'd like to pursue encrypting social tokens.  It seems like a worthwhile future feature for allauth proper, but in the meantime I'll experiment with ideas locally.  I'm creating this issue to start the discussion on how best to implement.

**Comment by CVirus** [comment]
:+1: for this

**Comment by nuschk** [comment]
:+1: also. Is this still being considered at the moment?

**Comment by hendrikschneider** [comment]
I think it's an important feature and would like to work on it if there is a chance that it's used. 

I wouldn't use https://github.com/defrex/django-encrypted-fields, because it is not maintained anymore. Therefore I would say propose to use https://github.com/georgemarshall/django-cryptography.

**Comment by acdameli** [comment]
@hendrikschneider Any progress or advice? I'm being tasked with ensuring out SocialApp secret is not persisted in plain text. I'm afraid I might need to fork django-allauth in order to get this to work.

**Comment by unformatt** [comment]
Anyone fork it and add encryption?

**Comment by turian** [comment]
So app tokens are stored unencrypted in the database in django-allauth? @agriffis  It appears to be that way...

**Comment by benjamindell** [comment]
Has anyone worked on this? Zoom now require that all tokens and user info is encrypted at rest. I would be surprised if there weren't other providers also stipulating the same.

**Comment by pennersr** [comment]
Note that "encrypted at rest" can be implemented on multiple levels, encrypting on the field level is just one option. Encrypting specific columns on the field level implies that all the other columns you have in your database are still unprotected.

**Comment by unformatt** [comment]
I forked this lib and encrypted the fields myself: https://github.com/unformatt/django-allauth/commit/94a32032745401053b66d07c3c859380d232850a

**Comment by turian** [comment]
@unformatt That's really cool. Have you submitted a PR to here?

**Comment by unformatt** [comment]
@turian  - I haven't because my fork is pretty old and python 2 only.

**Comment by turian** [comment]
> @turian - I haven't because my fork is pretty old and python 2 only.

Fight the good fight and support the cause. 3.6 is already EOL'ed

**Comment by benjamindell** [comment]
I have also now forked it to encrypt some of the fields (secret, token, extra_data). If anyone else wants to check it out it's over at [https://github.com/heysummit/django-allauth-crypto-fields](https://github.com/heysummit/django-allauth-crypto-fields)

**Comment by turian** [comment]
> I have also now forked it to encrypt some of the fields (secret, token, extra_data). If anyone else wants to check it out it's over at https://github.com/heysummit/django-allauth-crypto-fields

Great! Let's get this on pypi!

**Comment by derek-adair** [comment]
> I have also now forked it to encrypt some of the fields (secret, token, extra_data). If anyone else wants to check it out it's over at https://github.com/heysummit/django-allauth-crypto-fields

@benjamindell I commend you for your initiative.  Thank you for your contribution.

@pennersr **Personally**, I would do something wild and encrypt everything by default and laugh *maniacally* as people complain about the complexity of their new, more secure, application.  It is worth considering some pretty heavy handed options to add more security feature IMO.

**Comment by pennersr** [comment]
Moved to https://codeberg.org/allauth/django-allauth/issues/557
