### ISSUE TITLE
Do something after a mail confirmation

### ISSUE THREAD

**Issue by JVercout** [pennersr/django-allauth#559]
Hi everybody,

I would like to register my user on a mailchimp list after a mail confirmation on my platform. 
I thought it'll be easy to override get_email_confirmation_redirect_url to add an action (subscribe a mailchimp list) and then do the redirection. 
However, I never reach get_email_confirmation_redirect_url on my adaptor.

Do you have better method to do so ?

I paste right after the main element of my code. 

SETTINGS.py: 

```
ACCOUNT_ADAPTER ='app.adapter.ConfirmationWithMailChimpRegistration'
```

Adapter.py :

```
from allauth.account.adapter import DefaultAccountAdapter
class ConfirmationWithMailChimpRegistration(DefaultAccountAdapter):
    def get_email_confirmation_redirect_url(self, request):
        subscribe('listid', request.user.email,)
        return super(ConfirmationWithMailChimpRegistration,self).get_email_confirmation_redirect_url(self, request)
```

Debugging, I realize that I stay in :
account/views.py: (line 212)

```
resp = self.login_on_confirm(confirmation)
```

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/559
