### ISSUE TITLE
AssertionError when ACCOUNT_EMAIL_VERIFICATION = 'mandatory'

### ISSUE THREAD

**Issue by erez-o** [pennersr/django-allauth#560]
I solved it (I think) , but If that's the solution, I think it should be written in the docs

when I set ACCOUNT_EMAIL_VERIFICATION = 'mandatory', I get assertion error when trying to syncdb.
solved if I also set ACCOUNT_EMAIL_REQUIRED = True

running on django 1.5

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/560
