### ISSUE TITLE
converting lazy registered users to regular users

### ISSUE THREAD

**Issue by erez-o** [pennersr/django-allauth#561]
I allow lazy registration in my site, where unregistered users become "lazy registered" users when they do certain actions in my site (e.g. press like button). I save a User object, and mark unregistered in my UserProfile which is OneToOne with User.

If these lazy users eventually want to sign up (normally or via any app), I want to upgrade their existing user without creating a new one.

I will require an email confirmation if it makes a difference

How can I do that?

note: I've read http://stackoverflow.com/questions/15770071/how-do-we-use-django-allauth-with-lazysignup  but it didn't help me.

Thx a lot

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/561
