### ISSUE TITLE
Facebook login issues

### ISSUE THREAD

**Issue by philippeluickx** [pennersr/django-allauth#563]
Hey,

I am trying to get Facebook login implemented.
First I tried through oauth2 method, which works fine except on iOS... So on web and android it was tested and goes smooth, but then blocks on an iPhone.

So decided to try out js_sdk method, which works fine on localhost:8000 but does not work in my production environment. Social apps are set with correct id and key. Added the website to FB settings. But getting:

Social Network Login Failure
An error occurred while attempting to login via your social network account.

So... kind of baffled, not sure where to go next. Any tips are welcome!

**Comment by sachitad** [comment]
If you guys are looking for a full tutorial to add facebook login using django all auth, I have created a tutorial: https://www.youtube.com/watch?v=PtVu04V027c

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/563
