### ISSUE TITLE
A reliable hook to email verification event

### ISSUE THREAD

**Issue by scotartt** [pennersr/django-allauth#565]
This is related to the stackoverflow issue here - http://stackoverflow.com/questions/22282493/django-allauth-no-verification-email-for-social-users and possibly issues #485 and #518 

I would like a hook that is triggered when a user's email address is verified. Currently I have ACCOUNT_EMAIL_REQUIRED = True which means when a user clicks on the verification email I get the Signal allauth.account.signals.email_confirmed - which I use to drive some additional security settings.

However, as stated in the stackoverflow answer, when a user signs up using Google+ as the auth mechanism, the email is automatically verified because Google can verify it.  I have no problem with this behaviour, it's just that need to get some sort of Signal that the email address was verified, no matter the mechanism. 

Can Google verifying the email address automatically also generate this Signal? Or, an additional or different Signal is also acceptable. I just need an event, really, so that I know the email has been verified.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/565
