### ISSUE TITLE
Allow skip email verification in social signup

### ISSUE THREAD

**Issue by miguelcb84** [pennersr/django-allauth#569]
I've developed a web service that is currently in Beta. Some of my users complain about having to verify the email from the social account (which has already been verified by the provider).

So I tried to break in the process and mark the email as verified before the email with the verification link is sent. This is done among complete_signup and perform_login methods. There is no other entry point but the signal that is sent (user_signed_up). However, using a signal to modify the execution is not acceptable so I sketched some alternatives:

1) Use "none" as default with social account signup instead of EMAIL_VERIFICATION from settings (it is just changing complete_social_signup method in sociallaccount/helpers.py).

2) Add a new configuration parameter that allows the user to verify email in regular registration process and skip it in social account signup (again using it in helpers.py).

3) Add a method to the adapter that lets the developer mark the EmailAddress instance as verified when it comes from the socialaccount signup.

**Comment by janhesters** [comment]
Any news on this one? Is there any way we could help you develop this? :)

**Comment by danihodovic** [comment]
> Any news on this one? Is there any way we could help you develop this? :)

^

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/569
