### ISSUE TITLE
Password forgotten link should also expire

### ISSUE THREAD

**Issue by Roh-codeur** [pennersr/django-allauth#571]
It would appear that in the current version, the password reset link does not expire. Looking at the source, it seems like it does a base36_to_int(uidb36), hence it doesn't need to store the reset key. This would allow a user to use the same reset link to reset his account multiple times.

**Comment by RamizSami** [comment]
Hey I can't find it. Can you please guide me on how I can set the timeout for password reset link?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/571
