### ISSUE TITLE
Is this the right way to auto signup users

### ISSUE THREAD

**Issue by ialbert** [pennersr/django-allauth#573]
We are trying to streamline the social login into an existing site.  Basically we want to auto-connect social logins if the  user email already exists.

We will be enabling this only for trusted providers where the email is reliably set. 

There is little information out there on how automatically sign up users but I worked out a solution.  

Is this solution the recommended approach to implement the functionality in question? Thanks.

```
SOCIALACCOUNT_ADAPTER = 'adapters.AutoSignupAdapter'
```

then in the `adapters.py` I have:

```
from allauth.socialaccount.adapter import DefaultSocialAccountAdapter

class AutoSignupAdapter(DefaultSocialAccountAdapter):

    def pre_social_login(self, request, sociallogin):
        try:
            email = sociallogin.account.extra_data.get('email')
            verified = sociallogin.account.extra_data.get('verified_email')
            if email and verified:
                user = User.objects.get(email=email)
                if not sociallogin.is_existing:
                    sociallogin.connect(request, user)
        except User.DoesNotExist:
            pass
```

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/573
