### ISSUE TITLE
Correct way for overriding widget attrs

### ISSUE THREAD

**Issue by lpalomo** [pennersr/django-allauth#574]
Hi, I have been looking for the correct way to override the default forms without luck. Until now I've using django-widget-tweaks to add DOM attributes (class, style, data-*, etc) to the form fields; today I started the process of moving away of django-widget-tweaks and specify this DOM attributes in forms.py (as Django documentation sugested) but then I discovered that the default forms inherit from the custom form so I'm not overriding the app defaults, is the app who is overriding my custom options with its defaults. So my question is: what is the correct way for doing this?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/574
