### ISSUE TITLE
Remove autofocus on LoginForm

### ISSUE THREAD

**Issue by JVercout** [pennersr/django-allauth#575]
Hi everybody,

I'm asking myself how to remove autofocus on the account/LoginForm for username/email ? 

Is it possible to customize this form ?

Kiss,
Jérôme

**Comment by bellum** [comment]
Found this issue via google. Actually you can achieve this without custom view. Just define your form in settings:

ACCOUNT_FORMS = {
    'login': 'users.forms.LoginFormWithoutAutofocus'
}

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/575
