### ISSUE TITLE
DatabaseError on create account: Save with update_fields did not affect any rows.

### ISSUE THREAD

**Issue by georgewhewell** [pennersr/django-allauth#576]
Hi, I'm seeing this error being thrown occasionally:

```
DatabaseError at /accounts/twitter/login/callback/
Save with update_fields did not affect any rows.
```

I believe this is the relevant part of the traceback:

```
/base/data/home/apps/374647996476155101/vendor/allauth/account/utils.py in perform_login 
140.    login(request, user)
 ...

/base/data/home/runtimes/python27/python27_lib/versions/third_party/django-1.5/django/contrib/auth/__init__.py in login 
97.    user_logged_in.send(sender=user.__class__, request=request, user=user)
 ...

/base/data/home/runtimes/python27/python27_lib/versions/third_party/django-1.5/django/dispatch/dispatcher.py in send 
170.            response = receiver(signal=self, sender=sender, **named)
 ...

/base/data/home/runtimes/python27/python27_lib/versions/third_party/django-1.5/django/contrib/auth/models.py in update_last_login 
31.    user.save(update_fields=['last_login'])
 ...

/base/data/home/runtimes/python27/python27_lib/versions/third_party/django-1.5/django/db/models/base.py in save 
546.                       force_update=force_update, update_fields=update_fields)
 ...

/base/data/home/runtimes/python27/python27_lib/versions/third_party/django-1.5/django/db/models/base.py in save_base 
630.                                raise DatabaseError("Save with update_fields did not affect any rows.")
 ...
```

My MySQL logs say:

```
2014-03-24 21:20:16.542
(0.006) INSERT INTO `auth_user` (`password`, `last_login`, `is_superuser`, `username`, `first_name`, `last_name`, `email`, `is_staff`, `is_active`, `date_joined`) VALUES (!, 2014-03-24 21:20:16, False, xxx, xxx, xxx., , False, True, 2014-03-24 21:20:16); args=[u'!', u'2014-03-24 21:20:16', False, u'xxx', u'xxx', u'xxx.', '', False, True, u'2014-03-24 21:20:16']

[...]

2014-03-24 21:20:16.729
(0.005) UPDATE `auth_user` SET `last_login` = 2014-03-24 21:20:16 WHERE `auth_user`.`id` = 6 ; args=(u'2014-03-24 21:20:16', 6)
```

The problem appears to be creating and logging into an account in the same second causes this exception. Can anyone replicate this?

**Comment by asfaltboy** [comment]
For me this issue occurred when working on facebook sign-in for an existing user (without a `SocialAccount` yet), with using a custom GUID field in our `User.id` field.

The behaviour we wanted was to immediately associate an existing user with same email to their social account. However, it seems this behaviour is not supported in `sociallogin_from_response`, when called for the first time, and it does not locate a matching `SocialAccount`, then it defaults to creating a new user instance: https://github.com/pennersr/django-allauth/blob/db7e0e2ddff42081bc46002c656611ce5a5ba7b5/allauth/socialaccount/providers/base.py#L93-L99

This means that when a `logged_in` signal is fired, the instance does not yet exist and the update fails, as update an instance matching the uniquely generated ID is not succesful.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/576
