### ISSUE TITLE
HTTPS Callback URL

### ISSUE THREAD

**Issue by dh1tw** [pennersr/django-allauth#579]
My server running completely on HTTPS (enforced by Strict Transport Security). In my settings.py I've set: 

ACCOUNT_DEFAULT_HTTP_PROTOCOL = "https" 

However when a user tries to login with Facebook (Oauth2 - not JS), Django-allauth generates a Callback URI with "http" instead of "https" (/accounts/facebook/login/callback...)

Wouldn't it make sense that also these callbacks generate https URIs?

**Comment by bspotted** [comment]
Foursquare Provider seems to have this issue to. The Callback URI is working fine on HTTP but is unable to connect to HTTPS on foursquare. It appears the https is not working correctly.

cheers Daniel


https://de.foursquare.com/oauth2/authenticate?redirect_uri=http%3A%2F%2Fwww.bspotted.net%2Faccounts%2Ffoursquare%2Flogin%2Fcallback%2F

**Comment by XeniaGabriela** [comment]
Same problem with LinkedIn

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/579
