### ISSUE TITLE
installing django-auth with PIP downloads and installs a whole new copy of django

### ISSUE THREAD

**Issue by birep** [pennersr/django-allauth#58]
Yikes! That can't be intentional:

$ pip install django-allauth
Downloading/unpacking django-allauth
  Downloading django-allauth-0.4.0.tar.gz
  Running setup.py egg_info for package django-allauth
    warning: no files found matching '*.txt' under directory 'allauth/facebook/templates'
Downloading/unpacking django (from django-allauth)
  Downloading Django-1.4.tar.gz (7.6Mb): 7.6Mb downloaded
  Running setup.py egg_info for package django

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/58
