### ISSUE TITLE
Django + allauth + Facebook Canvas failure

### ISSUE THREAD

**Issue by badmetacoder** [pennersr/django-allauth#582]
We have an app that must work as a Facebook Canvas app using Django and allauth. No matter what voodoo we employ, the app works on local machines, but throws "Social Network Login Failure" after a successful call to /accounts/facebook/login/token over HTTP (inside Facebook Canvas). Has anyone seen this problem?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/582
