### ISSUE TITLE
populate_username & custom User model without first_name/last_name fields

### ISSUE THREAD

**Issue by wearpants** [pennersr/django-allauth#589]
When using a custom User model that lacks `first_name` and `last_name` fields, `DefaultAccountAdapter.populate_username` will generate an  username like 'none', 'none2', etc.,  instead of an username based on email, as seems to be intended. The problem arises from `allauth.utils._generate_unique_username_base`, which will convert arguments of `None` to a string 'none' (via `force_text`).

Either `populate_username` should pass only string values for `txts`, or `_generate_unique_username_base` should ignore non-string values when iterating through `txts`

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/589
