### ISSUE TITLE
Using *_login_url tags unable to redirect to url provided with 'next' argument

### ISSUE THREAD

**Issue by uroslates** [pennersr/django-allauth#59]
Currently if using any of the {% <Social_network>_login_url %} tags within your templates you are unable to force 'allauth' to redirect to some other url other than to 'socialaccount_connections' url (meaning to connections.html template).
Though infrastructure for this is there - they accept next parameters within this custom tags - this parameter value is not taken into consideration.
This is very hand for examples where you want to list social connections registration on some custom pages (read urls) that you then want to redirect to once your new social account was created (registered). 
The expected behavior would be to specify for example {% facebook_login_url next=profile_url %} and expect a link with this url to redirect to profile_url after the FB social account gets created/registered.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/59
