### ISSUE TITLE
Regenerate tokens

### ISSUE THREAD

**Issue by philippeluickx** [pennersr/django-allauth#590]
Hey,

I did something not-so-smart in hindsight... While cleaning up the api keys of the social apps (LinkedIn in casu), I switched the keys in my allauth instance.
Which apparently invalidates all the tokens generated previously.

Now, meanwhile other people have used the new keys.

Question here: is there an easy way for people to regenerate tokens? Because now when doing the signin with the "old" tokens, it asks for a new registration (which does not work, as the email address is already registered).

I tried putting the expiration date, but to no avail... Still redirected to the registration screen.
I also tried deleting the tokens, but also still redirects to registration...

The only option so far I can imagine is deleting all the social accounts, asking for people to sign up the traditional way (username/pw). But not everyone has a pw... so then they would have to reset it.
If you have any idea on how to do this in a more smooth way (hoping to simply re-confirm through LinkedIn when doing the sign-in when no token is present) then I would be glad to hear that!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/590
