### ISSUE TITLE
python3-openid-3.0.4 issue 'Association' object has no attribute 'getExpiresIn'

### ISSUE THREAD

**Issue by anythingapplied** [pennersr/django-allauth#597]
I get this error when trying to use the openid feature.  I've tracked it back to a name change in the python3-openid-3.0.4.  I reverted to python3-openid-3.0.1 and it fixed things.

The name getExpiresIn has apparently changed to expiresIn.  I tried just changing the only line that refers to this property from getExpiresIn to expiresIn when I was still using 3.0.4, but that still gave me errors.  It looks like 3.0.1 already has the expiresIn functionality (I see a line that says expiresIn = property(getExpiresIn), but I'm not sure why my simple fix didn't work.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/597
