### ISSUE TITLE
OpenID throwing TypeError at /accounts/openid/login/ - openid.consumer.discover.OpenIDServiceEndpoint object is not JSON serializable

### ISSUE THREAD

**Issue by nateworthy** [pennersr/django-allauth#601]
When trying to use OpenID, I'm getting a TypeError at /accounts/openid/login/ 

<openid.consumer.discover.OpenIDServiceEndpoint object> is not JSON serializable

any suggestions for debugging?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/601
