### ISSUE TITLE
Social Network Login Failure

### ISSUE THREAD

**Issue by variable** [pennersr/django-allauth#606]
I have the oauth2 working against another Oauth2 provider in development, but once I deployed to staging, I am getting Social Network Login Failure on callbacks, I have made sure the key, secret and redirect_urls are correct, but the error message isn't giving much hint on where is going wrong. Any ideas?

**Comment by variable** [comment]
Sorry only saw this just now, hope you have fixed it by now.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/606
