### ISSUE TITLE
EmailAddress not really required in DisconnectForm

### ISSUE THREAD

**Issue by metawake** [pennersr/django-allauth#61]
I was using django-allauth for an existing website for only connecting/disconnecting to accounts.
But while disconnecting FB account, the error message said that account is not connected to EmailAddress.
I don't think I need EmailAddress because I am using my custom authentication to log in.
I've commented out that line and the django-allauth continued to behave decently.
I suggest that we introduce a setting(boolean value) that makes that line in socialaccount/forms.py/DisconnectForm/clean() optional.
E.g.

if settings.USE_EMAIL_ADDRESS and EmailAddress.objects.filter(user=self.user,
                                           verified=True).count() == 0:
                raise forms.ValidationError(_("Your local account has no verified e-mail address."))

Do you think it could be worth pull request?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/61
