### ISSUE TITLE
Email verification when a different user is already logged in

### ISSUE THREAD

**Issue by HemantNegi** [pennersr/django-allauth#615]
when a user is already logged in and some other user user on the same browser verifies  his email address (by clicking the verification link in his email). 

it creates problem when
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True

it does not Sign out the logged in user ( the logged in user is not changed )

is this the expected behavior.

**Comment by roar** [comment]
Any news on making the security check in login_on_confirm configurable?

**Comment by pawciobiel** [comment]
@HemantNegi  LG™  :+1:  please do PR

**Comment by stuartmaxwell** [comment]
Hello, I just came across this issue after troubleshooting some odd behaviour. In fix #2636 it says the following: "...if the currently user is not the same user that requested the action, logout the current user." But in the case of confirming an email address, the email address is confirmed before the user is logged out, which I don't believe was the intention of the fix. Surely you wouldn't want another user to perform an action that should be performed by another user? I would have thought that in the scenario given, (User B clicks on a confirmation link sent to User A) that User B should be logged out *before* confirming the action.

Hope that makes sense. Let me know if I'm wrong here.

**Comment by pennersr** [comment]
> Surely you wouldn't want another user to perform an action that should be performed by another user?
> User B clicks on a confirmation link sent to User A

How can user B click on a confirmation link sent to user A? If the user is able to do so, then user B clearly has access to the inbox of user A meaning all security is lost no matter what you do?

**Comment by pennersr** [comment]
Closed via ce1658cc

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/615
