### ISSUE TITLE
Flickr Authorization

### ISSUE THREAD

**Issue by romdim** [pennersr/django-allauth#618]
Hello everyone!

I've been trying to authorize my flickr app through allauth all day unsuccessfully...
I keep getting "Oops! Flickr doesn't recognise the permission set." after I press "Ok, I'll authorize it" button...
Do you know what may be the problem?

I guess it's a permission problem, but don't know where and how it should be declared...
Any ideas?

Thanks in advance,
Romanos

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/618
