### ISSUE TITLE
data['email'] empty when using github provider

### ISSUE THREAD

**Issue by robbyt** [pennersr/django-allauth#619]
When authenticating with the Github provider, I'm not able to retrieve the user's email address.
I tried setting the github provider `SCOPE` to `["user", "user:email"]`, however the data['email'] in the github provider is always empty.

https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/providers/github/provider.py#L28

I have `SOCIALACCOUNT_QUERY_EMAIL = True` in my settings. I've also tried setting the `SCOPE` for the GitHub provider to `["user"]`, and `[]`. The `data` dict inside the github provider does not contain the user's email address.

This is possibly related to #369

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/619
