### ISSUE TITLE
PyPy distribution lacks templates folder

### ISSUE THREAD

**Issue by metawake** [pennersr/django-allauth#62]
Raymond,

This could be a little bit offtopic.
I've initially taken django-allauth from http://pypi.python.org/pypi/django-allauth/0.4.0
and it lacked the templates folder.
Installing from git-cloned folder indicated all healthy signs of template presents.
I think the pypy distro needs to be updated.

Alex

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/62
