### ISSUE TITLE
Use the shortcut get_current_site instead of get_current (from the model)

### ISSUE THREAD

**Issue by jensenbox** [pennersr/django-allauth#620]
We would prefer to not have to do a full install of the sites framework.

There is a simple work around, use https://docs.djangoproject.com/en/dev/ref/contrib/sites/#get-current-site-shortcut

This simple change will allow for using the framework or not easily - but there could be implications that I am not aware of of course.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/620
