### ISSUE TITLE
PayPal scope issue and KeyError

### ISSUE THREAD

**Issue by Gwildor** [pennersr/django-allauth#621]
Hi!

I'm trying to implement retrieving user information from PayPal by letting the users connect to it, but I'm having a problem with the scopes. For some reason, when I set more than just `openid` as a scope (the minimum PayPal requires, according to their [docs](https://developer.paypal.com/docs/integration/direct/identity/attributes/), PayPal redirects me back to my the following url:

`http://localhost:8000/accounts/paypal/login/callback/?state=aa8LkqGO5pQK&error_uri=http%3A%2F%2Flocalhost%3A8000%2Faccounts%2Fpaypal%2Flogin%2Fcallback%2F&error_description=Client+Validation+Error%3A+Invalid+scope.&error=invalid_scope`

As you can see, an `invalid_scope` error is returned. I was trying it with the following `SOCIALACCOUNT_PROVIDERS` setting:

``` python
SOCIALACCOUNT_PROVIDERS = {
    'paypal': {
        'SCOPE': ['openid', 'email'],
        'MODE': 'test'
    }
}
```

When the `SCOPE` setting is set to `['openid']` I can log in on PayPal and it sends me back to my website. There, though, I get a KeyError because Allauth tries to get the email, which is of course not in the response because the `email` scope is not used:

```
Traceback:
File "*/eggs/Django-1.6.5-py2.7.egg/django/core/handlers/base.py" in get_response
  112.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "*/eggs/django_allauth-0.16.1-py2.7.egg/allauth/socialaccount/providers/oauth2/views.py" in view
  51.             return self.dispatch(request, *args, **kwargs)
File "*/eggs/django_allauth-0.16.1-py2.7.egg/allauth/socialaccount/providers/oauth2/views.py" in dispatch
  98.                                                 response=access_token)
File "*/eggs/django_allauth-0.16.1-py2.7.egg/allauth/socialaccount/providers/paypal/views.py" in complete_login
  40.         return self.get_provider().sociallogin_from_response(request, extra_data)
File "*/eggs/django_allauth-0.16.1-py2.7.egg/allauth/socialaccount/providers/base.py" in sociallogin_from_response
  46.         common_fields = self.extract_common_fields(response)
File "*/eggs/django_allauth-0.16.1-py2.7.egg/allauth/socialaccount/providers/paypal/provider.py" in extract_common_fields
  32.                     email=data['email'])

Exception Type: KeyError at /accounts/paypal/login/callback/
Exception Value: 'email'
```

So, I think there are two issues:
- The scopes set are not passed to PayPal correctly.
- Connecting with PayPal should also work with just the minimal `openid` scope set.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/621
