### ISSUE TITLE
Inline javascript with Content-Security-Policy

### ISSUE THREAD

**Issue by afaikafk** [pennersr/django-allauth#626]
Inline javascript rendered using the template tag `providers_media_js` into the html directly can not work when the `Content-Security-Policy` header is added. Is there a way to use a different approach for passing these parameters to the page?

This project https://pypi.python.org/pypi/django-javascript-settings/ uses an interesting approach, could something like that work here too?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/626
