### ISSUE TITLE
add support to qq

### ISSUE THREAD

**Issue by jackxpeng** [pennersr/django-allauth#628]
I added qq support to allauth and would like to contribute it to this project.
1. It's based on the weibo/oauth2 provider.
2. QQ requires you to obtain an openid before being about to access their apis. I decided to use the openid as the uid since there is no id string in extra_data.
3. To add this I created an openid_connect provider that inherit from classes in the oauth2 app.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/628
