### ISSUE TITLE
Preferred way to add custom user model

### ISSUE THREAD

**Issue by bitcity** [pennersr/django-allauth#632]
I've installed & configured `allauth`, gone through the documentation & stackoverflow Q&A but I couldn't get a clear picture of this : 

Django recommends 3 ways to customize / extend user model:
1. Subclass `AbstractUser`
2. Subclass `AbstractBaseUser`
3. via separate `Profile` table & use a `OneToOneField` to join it

Question
a) Do all of these work perfectly with allauth or is there a preference?
b) Typically (1) fits my needs & I've seen a few other projects on github use it. Are there any limitations of this method?

Thanks

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/632
