### ISSUE TITLE
Case-insensitive usernames?

### ISSUE THREAD

**Issue by richardcornish** [pennersr/django-allauth#634]
It would be amazing if allauth could support case-insensitive username registration. As it stands, a long running "wontfix" Django bug on the user model is that if I register as "Rich" and try logging in as "rich", it won't work. But as it's popular for usernames to double as profile slugs, example.com/Rich and example.com/rich, while technically different URLs that can correspond to different users/profiles, are unintuitive to the user and can cause confusion when users interact.

I would love a settings flag like ACCOUNT_USERNAME_CASESENSITIVE, which defaults to Django's way, (=True). I could hack my own backend into this, but I feel like it should be caught higher up in the stack at the registration level where allauth is. Are there plans for something along these lines?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/634
