### ISSUE TITLE
Messages persist across user session

### ISSUE THREAD

**Issue by bitcity** [pennersr/django-allauth#636]
I have overridden some templates from allauth in my directory where I disable the message display in some views. The messages are visible only when the user explicitly visits `accounts/profile/inbox`. 

If a user (say `user1`) logs in, adds a new email address (triggering `add_message`) and then logs out, their messages won't get displayed (because they didn't visit `accounts/profile/inbox`)

Now if a second user (say `user2`) logs in with their credentials in the same browser and visits `accounts/profile/inbox`, they would see the email of `user1` displayed as well. I see that as a privacy issue. 

Am I doing something wrong or do the messages persist even after a user logs out ?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/636
