### ISSUE TITLE
Always redirecting home

### ISSUE THREAD

**Issue by cliffordh** [pennersr/django-allauth#637]
I'm trying to setup allauth without much success. I have set:

LOGIN_REDIRECT_URL = '/'
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_PROVIDERS = {
    'facebook': {
        'SCOPE': ['email', 'publish_stream'],
        'METHOD': 'js_sdk'  # instead of 'oauth2'
    }
}

and in urls.py:

```
(r'^accounts/', include('allauth.urls')),
```

However, every time I try to access /accounts/login I am redirected without an error message back to / (previously /accounts/profile until I added the LOGIN_REDIRECT_URL)

Any suggestions?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/637
