### ISSUE TITLE
Purge used email confirmation

### ISSUE THREAD

**Issue by bitcity** [pennersr/django-allauth#638]
Once an email confirmation has been used (i.e. the email has been verified), the email confirmation can be deleted from the database. Is there any reason to keep it?

I found an easy way to achieve this by overriding `confirm_email` in adapter.py

```
def confirm_email(self, request, email_address):
    email_address.verified = True
    email_address.set_as_primary(conditional=True)
    email_address.save()
    #My Modification below : 
    from allauth.account.models import EmailConfirmation
    EmailConfirmation.objects.filter(email_address__user = email_address.user).delete()
```

This will remove all expired / unused email confirmations once a valid one has been used and the email has been marked `Verified`. 

Is this approach good? Any obvious disadvantage or **security risk** that you see?

An advantage of purging the email confirmation is that `ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION` can be enabled without fear of misuse, as you [mention here](https://github.com/pennersr/django-allauth/blob/bd0f7a36f83595401f83a85f2efd20f82d4c45f2/allauth/account/views.py#L227)

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/638
