### ISSUE TITLE
I get a confusing error. please help

### ISSUE THREAD

**Issue by jenia** [pennersr/django-allauth#639]
I want to let users login using Google. I setup the allauth module and from the /accounts/login/ template I can login using Google. There's a link "google" that has an href="/accounts/google/login/?process=login". You can click that link to be authenticated by google.

Me, I have an html page with the exact same link
<a id="google-login" href="/accounts/google/login/?process=login">Google</a>

When I click it I get this error:
`XMLHttpRequest cannot load https://accounts.google.com/o/oauth2    /auth?state=************&response_type=…id=*************************. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1' is therefore not allowed access.`

Maybe this has to do with csrf? I'm not sure. please let me know.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/639
