### ISSUE TITLE
Setting required for Email verification link to expire on single use

### ISSUE THREAD

**Issue by HemantNegi** [pennersr/django-allauth#641]
There must be a setting to specify weather the verification link should expire on single use or it it will be valid during its entire lifetime

**Comment by derek-adair** [comment]
Vote to close as stale but welcoming a PR.  This is another type of issue that will crowd your tracker very quickly.  "Closed" does not mean "end of discussion" - it means this is not something the owners of this repository are planning on implementing.

If this is not something you are interested in adding to the source code it would be worthy adding this as an example to the documentation in some capacity.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/641
