### ISSUE TITLE
Custom SignupForm

### ISSUE THREAD

**Issue by ChillarAnand** [pennersr/django-allauth#645]
I have installed django-allauth and default signup form is working perfectly.

I need to add first & last name to signup form. I checked this http://stackoverflow.com/questions/12303478/how-to-customize-user-profile-when-using-django-allauth and done the same.

But when i start the server, I am getting this error.

![allauth](https://cloud.githubusercontent.com/assets/4463796/3310065/bfa8ec7c-f6ac-11e3-883d-3ceb6b78d08e.png)

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/645
