### ISSUE TITLE
Deprecated Google Scope

### ISSUE THREAD

**Issue by jinfu-leng** [pennersr/django-allauth#647]
As indicated here, two scopes (userinfo.profile and userinfo.email) are deprecated:
https://developers.google.com/+/api/oauth#deprecated-scopes

allauth is using these two scopes here:
https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/providers/google/provider.py#L11

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/647
