### ISSUE TITLE
Why use random_token function instead of django utils

### ISSUE THREAD

**Issue by getub** [pennersr/django-allauth#648]
Django utils has a function `get_random_string` in `django.utils.crypto` that can be used to generate a verification code. Is there a specific reason for not using that and writing one yourself?

The code for token generation in allauth is effectively:

```
email = ['abc@example.com']
bits = email + [str(random.SystemRandom().getrandbits(512))]
unique_str = hashlib.sha256("".join(bits).encode('utf-8')).hexdigest()
```

and code in Django is (assuming random.SystemRandom() is available)

```
unique_str =  ''.join([random.choice(allowed_chars) for i in range(length)])
```

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/648
