### ISSUE TITLE
Third party transactional email service

### ISSUE THREAD

**Issue by philippeluickx** [pennersr/django-allauth#652]
Hey!

I am currently looking into having my emails taken care of by a third party provider. A solid offering is e.g. Mandrill, for which a django implementation exists as well: https://github.com/brack3t/Djrill

Allauth will be sending emails through this third party in any case, as the implementation is using the default django send.email() methods. However, what is missing is that you e.g. can not use templates as defined in the third party service.
I was hoping to get your 2 cents: should allauth foresee such use cases? Mandrill offers advantages (more stable, analytics,...) but then having some templates in django (for allauth), some others (custom) in the serivce is painful and not consistent...

Cheers!

**Comment by tarkatronic** [comment]
FWIW, I realize this was closed a long time ago, but I built an adapter for allauth + Djrill based on @sssbox's code above, here: https://github.com/obsidiancard/django-allauth-djrill

I'll get it up on PyPi at some point, but I just got it working, so I figured I'd share it on the thread where I got my inspiration. Thank you!

**Comment by philippeluickx** [comment]
Nice, thanks!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/652
