### ISSUE TITLE
Only allow OpenID authentication against specified providers

### ISSUE THREAD

**Issue by ericamador** [pennersr/django-allauth#656]
It would be nice to have a configuration setting that only allows authentication against a list of specific OpenID providers. Is there a reason why this isn't an option? I will gladly make a pull request adding this functionality, but wanted to verify that it could be merged in before I do the work in case this functionality was purposefully excluded for some reason.

**Comment by leesolway** [comment]
I would really like to see this as well if possible.

**Comment by pennersr** [comment]
OpenID is no longer relevant, closing.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/656
