### ISSUE TITLE
AJAX template

### ISSUE THREAD

**Issue by Tyrdall** [pennersr/django-allauth#658]
It's easy to provide an AJAX login with `allauth` since you added the `AjaxCapableProcessFormViewMixin`. We only had to add a nice AJAX template, which does not extend a `base.html` or anything else. 

Now, if you keep the setting `LOGIN_URL = reverse_lazy('account_login')` and an anonymous user calls a decorated view (`login_required`), the user is redirect to the non-AJAX view. As you can imagine there are now some problems coming up with the AJAX template (looks like crap) =).

What about providing different templates for AJAX/non-AJAX purposes. E.g. check my customized way of handling this issue:

```
from allauth.account.views import LoginView
from django_libs.views_mixins import AjaxResponseMixin

class AJAXLoginView(AjaxResponseMixin, LoginView):
    pass
```

Now I can create a `login.html` and a `ajax_login.html` template.

Please have a look: https://github.com/bitmazk/django-libs/blob/master/django_libs/views_mixins.py#L28

**Comment by Jayesh-Mahato** [comment]
I am using the same scenario with bootstrap 3 template where in the Log In button in in the navbar on the top which is a different file navbar.html which in turn in called by base.html

Now I could load the bootstrap modal popup in Login button in the nav bar.
But I am unable to load the login view in the modal popup. The regular URL accounts/login works fine i.e. the non-Ajax template.

How do we call the login view inside the modal popup to work fine with the all-auth urls?

**Comment by Jayesh-Mahato** [comment]
@Tyrdall I tried using your views_mixins.py but the default non-ajax template login.html gets loaded in the modal popup. And after coming out of the modal (Escape), the modal popup doesn't loads on clicking the LogIn button anymore but instead flashes and disappears.

**Comment by Tyrdall** [comment]
@Jayesh-Mahato Well, can't help you here. Sounds like you need to review your AJAX handlers. But I would have to review your whole project to be sure.

Anyway, I'm afraid you'll to debug it yourself :(

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/658
