### ISSUE TITLE
DeprecationWarning, Django 1.6/allauth 0.17, Custom signup form

### ISSUE THREAD

**Issue by brycenesbitt** [pennersr/django-allauth#659]
Upgraded to Django 1.6, and pulled current allauth.  This results in the following somewhat malformed warning:

python2.7/site-packages/allauth/account/forms.py:196:
DeprecationWarning:
The custom signup form must offer a `def signup(self, request, user)` method
  DeprecationWarning)

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/659
