### ISSUE TITLE
User with an existing SocialAccount never see their field update

### ISSUE THREAD

**Issue by bdauvergne** [pennersr/django-allauth#662]
populate_user() is only called on the newly created User, it's never called on the user retrieved after a SocialLogin.lookup(). So if you change your first_name or last_name, it's never updated. 

It seems to me that SocialLogin.lookup() should be called somewhere in Provider.sociallogin_from_response(), what do you think ?

For now I must implement things like that to get the behaviour I expected:

``` python

from allauth.socialaccount.signals import pre_social_login
from django.dispatch import receiver

@receiver(pre_social_login)
def pre_social_login_populate_user(sender, request, sociallogin, **kwargs):
    account = sociallogin.account
    data = account.extra_data
    user = account.user
    if 'first_name' in data:
        user.first_name = data['first_name']
    if 'last_name' in data:
        user.last_name = data['last_name']
    user.save()
```

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/662
