### ISSUE TITLE
Initial value for the SignUpForm/LoginForm.

### ISSUE THREAD

**Issue by zkanda** [pennersr/django-allauth#666]
Trying to implement this seems to be hard. I also cannot subclass SignUpForm.

**Comment by Flimm** [comment]
> Have a look here: http://django-allauth.readthedocs.org/en/latest/advanced.html#invitations

That link is broken. Here is an updated link: https://django-allauth.readthedocs.io/en/latest/account/advanced.html#invitations

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/666
