### ISSUE TITLE
Minor: remove provider, exception if still in database

### ISSUE THREAD

**Issue by brycenesbitt** [pennersr/django-allauth#667]
If you have active users of a provider in the database,
and remove that provider from your SETTINGS,
and then hit the connections URL, you get:

<WSGIRequest path:/accounts/social/connections/>
File "allauth/socialaccount/providers/**init**.py", line 19, in by_id
    return self.provider_map[id]
KeyError: u'amazon'

In other words nothing checks if a provider is actually available.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/667
