### ISSUE TITLE
TemplateSyntaxError at /accounts/login/

### ISSUE THREAD

**Issue by debuggerpk** [pennersr/django-allauth#68]
here is the error

'allauth_tags' is not a valid tag library: Template library allauth_tags not found, tried django.templatetags.allauth_tags,django.contrib.staticfiles.templatetags.allauth_tags,django.contrib.admin.templatetags.allauth_tags,allauth.account.templatetags.allauth_tags,allauth.socialaccount.providers.facebook.templatetags.allauth_tags,allauth.socialaccount.providers.twitter.templatetags.allauth_tags

here is my settings.py

INSTALLED_APPS = (
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Uncomment the next line to enable the admin:
    'django.contrib.admin',
    # Uncomment the next line to enable admin documentation:
    # 'django.contrib.admindocs',
    'app',
    'emailconfirmation',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.twitter',
)

TEMPLATE_CONTEXT_PROCESSORS = (
    "django.core.context_processors.request",
    "allauth.context_processors.allauth",
    "allauth.account.context_processors.account",
    'django.contrib.auth.context_processors.auth',
)

AUTHENTICATION_BACKENDS = (
    "allauth.account.auth_backends.AuthenticationBackend",
)

what am i doing wrong?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/68
