### ISSUE TITLE
clean_<fieldname> on user SignupForm registration

### ISSUE THREAD

**Issue by humitos** [pennersr/django-allauth#681]
I've configured my project like this:

```
ACCOUNT_SIGNUP_FORM_CLASS = 'chap.challenge.forms.UserSignUpForm'
```

Then, my form class is something like this:

```
class UserSignUpForm(forms.ModelForm):

    [...]

    gender = forms.ChoiceField(
        choices=settings.GENDER_CHOICES,
        widget=forms.RadioSelect,
        required=False)

    class Meta:
        model = User

        fields = (
            'username', 'email', 'password1', 'password2',
            [...]
        )

      [...]

      # README: "clean_email" is not being called because BaseSignupForm
      # (from django-allauth) inherit from this one and overrides the
      # "clean_email" method so their method is called instead of our
      # allauth/account/forms.py#L208
      def clean_email(self):
          email = self.cleaned_data['email']
          if ValidateThisEmailFunction(email):
              raise forms.ValidationError('Not Valid.')
          return email
```

Here is the line with the issue:

https://github.com/pennersr/django-allauth/blob/master/allauth/account/forms.py#L257

I think this is a problem because there is no way to validate the fields in the way I want. Maybe, we should include `super(BaseSignupForm, self).clean_email()` in the `BaseSignupForm.clean_email` method as we are doing here:

https://github.com/pennersr/django-allauth/blob/master/allauth/account/forms.py#L296

**Comment by k4ml** [comment]
Overriding `clean_email` on adapter won't do much as it's not able to short circuit the logic. The subsequent logic still being run despited whatever you did in adapter.clean_email().
```
def clean_email(self):
        value = self.cleaned_data["email"]
        value = get_adapter().clean_email(value)
        if app_settings.UNIQUE_EMAIL:
            if value and email_address_exists(value):
                self.raise_duplicate_email_error()
        return value
```
For example we want to allow user to re-attempt signup using the same email address, as long as the email address not yet validated but seem impossible because of `if value and email_address_exists(value)` and it can't be overriden.

**Comment by k4ml** [comment]
Is it possible if all the `clean_*` methods in `BaseSignupForm` being moved out into mixin so that if user also implement clean_* in their custom form, that would take precedence ?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/681
