### ISSUE TITLE
NoReverseMatch at /accounts/login/

### ISSUE THREAD

**Issue by debuggerpk** [pennersr/django-allauth#69]
i am confused.

when i use the django shell and run this function

SocialApp.objects.get_current(FacebookProvider.id)

it gives me an id

i.e. Grand Plans of World Dominitation

but i get this error

NoReverseMatch at /accounts/login/
Reverse for 'facebook_channel' with arguments '()' and keyword arguments '{}' not found.

what could be wrong?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/69
