### ISSUE TITLE
Problem with {% providers_media_js %} at /allauth/templates/socialaccount/snippets/login_extra.html

### ISSUE THREAD

**Issue by ac1dxtrem** [pennersr/django-allauth#692]
Long story short, when I go to localhost:8000/accounts/login/ I get the following error:

"Reverse for 'facebook_login_by_token' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []"

**Comment by pennersr** [comment]
Assuming local configuration error ...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/692
