### ISSUE TITLE
Adding bootstrap form-control class to allauth's password fields.

### ISSUE THREAD

**Issue by brycenesbitt** [pennersr/django-allauth#695]
Twitter Bootstrap requires adding CSS class "form-control" to every text input.  See also:
http://stackoverflow.com/questions/18158293/how-can-i-work-around-the-need-for-bootstrap-3s-form-control-class

What's the cleanest way to do this for SignupForm / SignupView / "account/signup.html"?  The form is generated with {{ form.as_p }}.

Hacking views.py does not feel right.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/695
