### ISSUE TITLE
Use default login_url if it exists

### ISSUE THREAD

**Issue by eduardo-matos** [pennersr/django-allauth#697]
The `login_url` variable on [signup page](https://github.com/pennersr/django-allauth/blob/fc2b0ee66e2fac5aacbe98192759393aeb81260c/allauth/templates/account/signup.html#L11) uses a hard coded url defined [on the view](https://github.com/pennersr/django-allauth/blob/fc2b0ee66e2fac5aacbe98192759393aeb81260c/allauth/account/views.py#L178). There is no way to override this value on the project settings (which is desirable).

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/697
