### ISSUE TITLE
/accounts/social/signup redirects to /accounts/login no matter what

### ISSUE THREAD

**Issue by aptwebapps** [pennersr/django-allauth#70]
It hits this right in the beginning of /allauth/socialaccount/views.signup:

``` python
    signup = request.session.get('socialaccount_signup')
    if not signup:
        return HttpResponseRedirect(reverse('account_login'))
```

And I can't see how that session variable would ever get set when someone first visits the site. Am I misunderstanding the purpose of that view? I assumed it was to allow people to signup with a social id.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/70
