### ISSUE TITLE
Avoid database lookup for verified_email_required check

### ISSUE THREAD

**Issue by bitcity** [pennersr/django-allauth#700]
If a site is making a lot of frequent AJAX requests that require a `verified email` check, it would be a lot more efficient to save this flag in a signed cookie, rather than having a database look-up on each tiny request. The cookie would be updated on login & on verifying an email. Does this sound like a feasible and useful path to take? Or is there a better way to avoid a database lookup?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/700
