### ISSUE TITLE
No documentation for `ACCOUNT_FORMS` settings variable

### ISSUE THREAD

**Issue by wnajar** [pennersr/django-allauth#701]
Many users also want to overwrite the default signup form as seen in Issue #511 so there is the `ACCOUNT_SIGNUP_FORM_CLASS` settings variable. However, there is no settings variable for the login form so you have to use `ACCOUNT_FORMS = {'login': 'yourapp.forms.LoginForm'}`. There is no documentation at all for this parameter, making it very difficult or impossible to use.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/701
