### ISSUE TITLE
Versioning the Facebook API

### ISSUE THREAD

**Issue by marfire** [pennersr/django-allauth#703]
I recently ran into a problem with my Facebook login, and after some digging discovered that it was due to a conflict between the name of the permission I was requesting and the version of the Facebook API that was being used.

Facebook currently has three versions of its API: 1.0, 2.0, and 2.1. When you use an unversioned endpoint (e.g. `https://graph.facebook.com/oauth/access_token`), Facebook chooses the API version based on when the developer created their app (see [here](https://developers.facebook.com/docs/apps/upgrading) for more details).

I assume that allauth itself works fine with all three versions. For the developer, though, there is an important difference because some of the permission names have changed. If the developer wants to specify the permissions with `SCOPE` they also need to be able to specify the version of the API that should be used.

One obvious solution is to add a new Facebook setting (`VERSION`?). If present, allauth should use that to construct all of its Facebook API endpoints (e.g. `https://graph.facebook.com/v2.1/oauth/access_token`).

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/703
