### ISSUE TITLE
# TODO: Move into adapter `save_user` - please do it. It will help to extend allauth for multiple usertypes.

### ISSUE THREAD

**Issue by yrik** [pennersr/django-allauth#709]
Hi, I'm writing extension for allauth that will help to use any set of CustomUsers not just one https://github.com/yrik/django-allauth-multiple.

I'd love to have ability to overwrite `setup_user_email` call in adapter, not in `SignUpForm`.
https://github.com/pennersr/django-allauth/blob/master/allauth/account/forms.py#L308

**Comment by ncp1113** [comment]
Should this be closed? It looks like there is a save_user in DefaultAccountAdpater and in DefaultSocialaccountAdapter.

**Comment by derek-adair** [comment]
Can be closed.  I'm not really sure what this user was getting at but i've never had a problem leveraging multiple account types / welcome emails.  I think this was a misunderstanding on how to implement what he wanted.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/709
