### ISSUE TITLE
Received error "can't compare offset-naive and offset-aware datetimes"

### ISSUE THREAD

**Issue by krwenholz** [pennersr/django-allauth#71]
Hi there,

Awesome app, by the way. 

I received the error in the title after trying to authenticate a test email (perhaps I performed setup incorrectly somehow), but it was easily fixed by following the steps from this link: http://spottedsun.com/django-registration-activation-error-for-django-1-4/.  I just applied the same principle to code around line 155 of the emailactivation/models.py file.

Perhaps this was an annoying bug in my system, but it is fixed for now, unless I drastically messed up my own code.

Best of luck!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/71
