### ISSUE TITLE
How is SocialAccount created without user

### ISSUE THREAD

**Issue by sesas** [pennersr/django-allauth#711]
https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/providers/base.py#L48-L50

``` python
socialaccount = SocialAccount(extra_data=extra_data,
                                      uid=uid,
                                      provider=self.id)
```

I don't understand how this line of code works.  Similarly the `EmailAddress` is created without user: https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/providers/base.py#L83-L85

``` python
 83                 addresses.append(EmailAddress(email=email,
 84                                               verified=False,
 85                                               primary=True))
```

Because of this I am having trouble completing the login using a custom provider that I am writing. But the code referenced is from the allauth package.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/711
