### ISSUE TITLE
admin sending an email invite

### ISSUE THREAD

**Issue by kristofer** [pennersr/django-allauth#712]
I'd like to "pre-assign" a user to subsection of my app by allowing an admin to fill out the signup form and invite someone to validate their email.

the only way I have found to do this, is to be logged out, hit the signup form, have the verify email sent and then, before they use it, to assign them to a subsection of the app via the django admin --- not ideal.

is there any pointerr on how I might do this? I assume I might just use the methods of the DefaultAccountAdapter after I collect what I need to create the account from a form flow of mine? 

(I only want to do this with Email accounts, the social stuff is pushed off for this month) (and I have read some of the discussions on the potential for a complex invitation process to be built, I don't think I am quite that far along yet.)

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/712
