### ISSUE TITLE
Simplify certain pathways

### ISSUE THREAD

**Issue by SteveByerly** [pennersr/django-allauth#716]
I've been using allauth for a few months now and am overall happy with the package when used in its default state. However, when trying to extend it for my own needs I've run into some hurdles which I think can be avoided.

For instance, the flow to log a user in:

views.LoginView -> form.login() -> utils.perform_login() -> adapter.login() plus the back and forth to get the redirect_url.

Is there any reason not to refactor some of the utils funcs into the adapter? Or at least some other workflow that removes so many calls to different modules. It also seems odd that my utils module is returning my response and not the view.
I'm happy to do the work and provide a PR, but wanted to get your thoughts first.

**Comment by pennersr** [comment]
Closing this, assuming the fix to #741 was sufficient.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/716
