### ISSUE TITLE
Password Reset E-mail and Confirm E-mail Address links sent without https

### ISSUE THREAD

**Issue by ferrangb** [pennersr/django-allauth#717]
I have set ACCOUNT_DEFAULT_HTTP_PROTOCOL = "https" but the links I receive are with http.

After a question in stackoverflow, it seems that this setting is not properly working: http://stackoverflow.com/q/25824598/2230003

Is ACCOUNT_DEFAULT_HTTP_PROTOCOL enough or should I also set DEFAULT_HTTP_PROTOCOL = "https" and the environment variable HTTPS = "on"?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/717
