### ISSUE TITLE
Paypal redirects to /accounts/social/signup

### ISSUE THREAD

**Issue by Snotes** [pennersr/django-allauth#722]
I'm getting through the REST OAuth authentication, but then I'm redirected back to an account creation page like this:

![image](https://cloud.githubusercontent.com/assets/6978248/4344252/a0b43c88-4083-11e4-98d7-9ac9eeddb681.png)

The URL I'm using is https://domainname.com/accounts/paypal/login/

Any ideas or suggestions on how to avoid this extra step would be appreciated!

Thanks,

Thomas

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/722
