### ISSUE TITLE
Email field is set to None when username is email

### ISSUE THREAD

**Issue by bodgerbarnett** [pennersr/django-allauth#723]
If you use email as your username field, when a new user signs up, the user's email field is first set to be their email address.

However, on line 187 of adapter.py, it is set back to None as there isn't a username field in the form.

There is a possible fix, which is to swap lines 186 and 187 (so that the email field is set to None BEFORE it's set to the proper email address) but I'm not sure if this is the best way to fix it.

**Comment by xpostudio4** [comment]
@bodgerbarnett  how did you solved the issue, I don't seem to get how to configure it to make it happen.

**Comment by xpostudio4** [comment]
@pennersr, I haven't been able to find something about this in the documentation. How I am supposed to make this?, I will added to the documentation myself.

**Comment by bodgerbarnett** [comment]
The fix stated above by @pennersr sorted it for me.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/723
