### ISSUE TITLE
Mandrill API response 500 Failed to send a message 

### ISSUE THREAD

**Issue by damianpv** [pennersr/django-allauth#726]
Hello,

I'm using Django 1.7 and Mandrill to send emails and work fine in my project, but i get the next error with django-allauth:

Mandrill API response 500
Failed to send a message to [{'type': 'to', 'email': u'myemail@gmail.com', 'name': ''}], from webmaster@localhost
Request Method: POST
Request URL:    http://localhost:8000/accounts/password/reset/
Django Version: 1.7
Exception Type: MandrillAPIError
Exception Value:  
Mandrill API response 500
Failed to send a message to [{'type': 'to', 'email': u'myemail@gmail.com', 'name': ''}], from webmaster@localhost
Exception Location: /home/user/.virtualenvs/django/local/lib/python2.7/site-packages/djrill/mail/backends/djrill.py in _send, line 119

Regards,

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/726
