### ISSUE TITLE
Facebook sign in fails over HTTPS

### ISSUE THREAD

**Issue by lnhrdt** [pennersr/django-allauth#727]
I've been able to get allauth to function properly with Google and Facebook sign in on two separate environments when using HTTP.

However when switching to HTTPS, Google works but Facebook does not. I've made sure to properly set

```
ACCOUNT_DEFAULT_HTTP_PROTOCOL = "https"
```

in my Django project settings as well as update the protocol with the provider when switching.

Additionally, I've tried both the js_sdk and the oauth2 method with Facebook over https to no avail.

The strange thing is...
when the Facebook login fails with https, I end up with this error message

> Social Network Login Failure
> An error occurred while attempting to login via your social network account.

at at this url: https://mydomain/accounts/facebook/login/token/
but if I immediately thereafter go to this domain (manually): https://mydomain/accounts/facebook/login/
the login succeeds.

Any ideas? I've done my best to ensure this isn't a problem with my application or configuration.

**Comment by pablopda** [comment]
I have the same problem, I use Nginx as ssl terminator on front of django with allauth and facebook refuse to log in . Any hint ?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/727
