### ISSUE TITLE
OAuth2 callback view suppresses exceptions making it difficult to deal with problems

### ISSUE THREAD

**Issue by timmyomahony** [pennersr/django-allauth#729]
I was getting an authentication error when signing in with Facebook as the callback view suppresses any error information coming back from Facebook, simply showing the default authenticated error: 

https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/providers/oauth2/views.py#L113

It might be useful to at  least feed the message to the error template so that it can be easily printed (during DEBUG for example). Alternatively it might be a good idea to let the exception be raised when in DEBUG mode

**Comment by pennersr** [comment]
The exception is passed on to the adapter, as well as to the authentication error template. See `render_authentication_error` in the socialaccount `helpers.py`

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/729
