### ISSUE TITLE
504 Error on Signup

### ISSUE THREAD

**Issue by escaroda** [pennersr/django-allauth#731]
Hi. Does anyone know what the reason might be?
I have django 1.7, python 3 and on development (runserver) everything works fine.
But on production (Nginx, uwsgi, ssl(https) when I try to signup a user it stuck.. looks like page is loading but after half a minute I get 504 error from nginx web server

logs from uwsgi tell me this:
Wed Oct  8 12:10:14 2014 - uwsgi_response_write_headers_do(): Broken pipe [core/writer.c line 229] during POST /accounts/signup/ (95.25.216.123)
OSError: write error

logs from nginx this:
2014/10/08 08:16:30 [error] 1707#0: *6 upstream timed out (110: Connection timed out) while reading response header from upstream

So user is actually registered and an email have sent after long delay. When I click verification link from email, everything works like a charm. The problem is only with signup (long delay and 504 error in general). I think that it might be something with ssl(https) and nginx settings but I don't know what exactly

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/731
