### ISSUE TITLE
Populating User Fields from Social Account when ACCOUNT_EMAIL_REQUIRED = True

### ISSUE THREAD

**Issue by rfj001** [pennersr/django-allauth#732]
When you attempt to login with a social account and email is required, but the social account does not have an email linked, you are brought to an additional form asking for your email address. When you click submit on this form,  a user linked to your social account with the provided email address is created, but all other fields are wiped clean. Your user is no longer populated with data like first_name and last_name from the social account. 

Test this by fetching information from a google account without specifying to collect from the email scope. You can see in Django admin that before you submit the final form with your email you have a user with the name fields populated (no social account has yet been saved to the DB), but after submitting the form the final user only has an email address (with a linked social account).

**Comment by velis74** [comment]
Not sure if my problem is the same as above, but having

`ACCOUNT_EMAIL_REQUIRED = True`
`SOCIALACCOUNT_QUERY_EMAIL = True`

Results in no query for the account e-mail.
In particular, I logged in with Twitter and was redirected straight to `LOGIN_REDIRECT_URL`.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/732
