### ISSUE TITLE
sensitive_post_parameters for signup and login

### ISSUE THREAD

**Issue by HEdingfield** [pennersr/django-allauth#736]
I've noticed that when my app crashes during the signup or login procedure, I get an error report with all the password info included in the POST (e.g. it has both "password1" and "password2" if it crashes on the signup page). Wouldn't it be safer to implement the sensitive_post_parameters decorator somehow to strip this information out?

https://docs.djangoproject.com/en/1.6/howto/error-reporting/#django.views.decorators.debug.sensitive_post_parameters

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/736
