### ISSUE TITLE
Viadeo provider for allauth

### ISSUE THREAD

**Issue by teolemon** [pennersr/django-allauth#740]
I'm currently researching the Viadeo API since I miss it for a project where I use allauth.
Jotting down my findings so far as part of a feature request.

I've found the official documentation 
http://dev.viadeo.com/documentation/authentication/oauth-authentication/
as well as an implementation for a resume in bitbucket
https://bitbucket.org/tonioo/cmsplugin-viadeo-resume/src/2558c60e3543/cmsplugin_viadeo_resume/?at=default

**Comment by teolemon** [comment]
I've just found this:
https://github.com/gaecom/AllAuth/tree/master/additional-providers/hybridauth-viadeo

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/740
