### ISSUE TITLE
Create a post-authentication hook

### ISSUE THREAD

**Issue by koniiiik** [pennersr/django-allauth#741]
Rationale: We want to be able to plug in a two-factor authentication solution.

This means that after the allauth flow finishes, instead of allauth calling `django.contrib.auth.login`, we need to store the authenticated user in a separate session key, redirect to the 2FA mechanism and let that one call `django.contrib.auth.login` on success.

As far as I can see, the only place where `django.contrib.auth.login` is called is `DefaultAccountAdapter.login`, but that doesn't make it possible to implement additional steps requiring user interaction. However, if I'm not wrong, `DefaultAccountAdapter.login` is always called from `allauth.account.utils.perform_login`.

So, my proposal is to move the `perform_login` utility function to something like `DefaultAccountAdapter.finish`. This way, overriding the new method in a custom adapter would provide the required hook to insert any additional layers of authentication.

Somewhat related to #716.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/741
