### ISSUE TITLE
django 1.8 compatibility issue

### ISSUE THREAD

**Issue by gellingson** [pennersr/django-allauth#742]
In the dev branch the django team has apparently tightened up model code to throw an exception when assigning an unsaved model to a foreign key relationship (https://code.djangoproject.com/ticket/10811).

This breaks django-allauth's account creation upon return from oauth2 authentication:

ValueError at /accounts/facebook/login/callback/
Cannot assign "<User: >": "User" instance isn't saved in the database.

Request Method: GET
Request URL: http://localhost:8000/accounts/facebook/login/callback/?code=<...>
Django Version: 1.8.dev20140830184234
Python Version: 3.4.1
django-allauth version is the git head as of today (I needed the regex fix post-18.0)

Traceback:
File "/usr/local/lib/python3.4/site-packages/django/core/handlers/base.py" in get_response
1.                     response = wrapped_callback(request, _callback_args, *_callback_kwargs)
   File "/usr/local/lib/python3.4/site-packages/allauth/socialaccount/providers/oauth2/views.py" in view
2.             return self.dispatch(request, _args, *_kwargs)
   File "/usr/local/lib/python3.4/site-packages/allauth/socialaccount/providers/oauth2/views.py" in dispatch
3.                                                 response=access_token)
   File "/usr/local/lib/python3.4/site-packages/allauth/socialaccount/providers/facebook/views.py" in complete_login
4.         return fb_complete_login(request, app, access_token)
   File "/usr/local/lib/python3.4/site-packages/allauth/socialaccount/providers/facebook/views.py" in fb_complete_login
5.         .sociallogin_from_response(request, extra_data)
   File "/usr/local/lib/python3.4/site-packages/allauth/socialaccount/providers/base.py" in sociallogin_from_response
6.         user = socialaccount.user = adapter.new_user(request, sociallogin)
   File "/usr/local/lib/python3.4/site-packages/django/db/models/fields/related.py" in **set**
7.                         (value, self.field.rel.to._meta.object_name)

Exception Type: ValueError at /accounts/facebook/login/callback/
Exception Value: Cannot assign "<User: >": "User" instance isn't saved in the database.

The exception is thrown while attempting to store the social auth app (e.g. 'my-fb-oauth') as a relation on the socialaccount.SocialAccount.user object, but apparently the social auth app object being passed in does not have an id in it (although it definitely has one in the db, so not sure how/where it went missing?)

For now I can temporarily revert the django team's fix as a workaround but others may hit the same issue. Also, the django bug suggests there may be silent data loss in cases where the assignments are made in this order; could the current code be failing to record some intended relations (such as the social auth app) in this situation?

I tried google and fb (both oauth, not js) with the same outcome. Non-social account creation works fine.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/742
