### ISSUE TITLE
Rethinking ACCOUNT_SESSION_REMEMBER

### ISSUE THREAD

**Issue by davemerwin** [pennersr/django-allauth#753]
I think this works backwards.
It should maybe be:

False = Do not remember users (which it does)
True = Remember WITH THE TOGGLE
None = Do nothing

Unless you add a note to the template telling a user they will remain logged in, it feels a little weird to AUTOMATICALLY login a user via session with out them knowing that they EXPLICITLY opted to do that.

Thoughts? Am I missing something?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/753
