### ISSUE TITLE
Verification link to a verified email

### ISSUE THREAD

**Issue by mazing** [pennersr/django-allauth#754]
In the demo I can send a verification mail even though the email address is verified. Shouldn't it checked if email address is already verified before sending another email?

**Comment by pawciobiel** [comment]
Also it would be better if EmailAddress.send didn't use request object at all - simple query against DB would be just fine.

**Comment by 9mido** [comment]
To the _action_send function inside the EmailView class add this code:

Views.py:

```
from django.http import HttpResponseServerError
from allauth.account.models import EmailAddress
from django.contrib import messages

    def _action_send(self, request, *args, **kwargs):
        email = request.POST["email"]
        if EmailAddress.objects.filter(email=email, verified=True).exists():
            messages.error(self.request, "Email has already been verified")
            return HttpResponseRedirect(self.request.path_info)
            #return HttpResponseServerError("Email address has already been verified.")
```

**Comment by pennersr** [comment]
Handled in 880d963d

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/754
