### ISSUE TITLE
ajax response to email verification POST

### ISSUE THREAD

**Issue by pglotov** [pennersr/django-allauth#755]
I'm developing with angular.js, and I was able to deal with htmls in signup and login form responses nicely. However response to email verification form POST is a redirect which is very undesirable. Would it be a good idea to send a response rather than a redirect when ajax request is made to the email confirmation form? I can do it and would like to get some opinions if this is a good idea.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/755
