### ISSUE TITLE
Need opinions: remembering and displaying which method the user used to log in last time

### ISSUE THREAD

**Issue by heliodor** [pennersr/django-allauth#758]
One of the arguments against the use of social logins is that users won't remember how they logged in last time (Facebook, Twitter, email, etc.), leaving them confused, frustrated, and unable to retrieve the setings or work associated with their account.

I would like to propose a solution/idea and hear what others have to say:

How about setting a cookie upon each successful login that specifies the login method so that when users visit the login page again, they'll be told, "The last login from this computer and browser was with Twitter. <More user education and explanation goes here>" You could even go so far as to only present the last login method, together with an explanation and a toggle button that allows users to display the rest of the login methods.

I haven't seen this done anywhere on the internet in my extensive "career" of browsing the internet.

So what gives? Why hasn't this been done yet? What implications am I missing? Have any of you seen an example of this in use?

The changes to Django-AllAuth to make this happen are minimal:

Pass the 'response' object to the 'user_logged_in' signal. The rest can be left up to the app developer, namely:
Upon receiving the user_logged_in signal, set the cookie on the response object.
Use the cookie in the template or javascript of the login page.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/758
