### ISSUE TITLE
Making the email address required doesn't ask the user for an email address upon logging in after the config change

### ISSUE THREAD

**Issue by heliodor** [pennersr/django-allauth#763]
Steps:
1) Set ACCOUNT_EMAIL_REQUIRED=False and ACCOUNT_EMAIL_VERIFICATION="none"
2) Sign up a user who doesn't provide an email address
3) Set ACCOUNT_EMAIL_REQUIRED=True and ACCOUNT_EMAIL_VERIFICATION="none"
4) Log in as the existing user
5) You're taken to your account, when in fact you should be asked to hand over an email address.

Let's do that again but with ACCOUNT_EMAIL_VERIFICATION="mandatory".
Step 5 becomes: You're told a verification email has been sent, when in fact the system doesn't have an email address for you. You've been prevented from logging in, so now your account has become inaccessible!
 
To fix:
There needs to be a step, if necessary, to ask the user for an email address upon logging in and before the email verification logic.

I'll submit a pull request.

**Comment by pennersr** [comment]
Closing for above mentioned reasons, please file specific issues for any hooks you currently think are missing, if any.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/763
