### ISSUE TITLE
Social Network Login Failure

### ISSUE THREAD

**Issue by aliabbas-2012** [pennersr/django-allauth#769]
Internal Server Error: /accounts/facebook/login/callback/

My version is new every things fine looks fine 

Social Network Login Failure
An error occurred while attempting to login via your social network account.

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',

```
'django.middleware.csrf.CsrfViewMiddleware',
'django.contrib.auth.middleware.AuthenticationMiddleware',
'django.middleware.transaction.TransactionMiddleware',
'django.contrib.messages.middleware.MessageMiddleware',
 #'nocache.NoCache',
# Uncomment the next line for simple clickjacking protection:
# 'django.middleware.clickjacking.XFrameOptionsMiddleware',
#'apps.utils.auth.LoginRequiredMiddleware',  # Login required globally, used in beta stage
```

)

TEMPLATE_CONTEXT_PROCESSORS = (
    "django.core.context_processors.request",
    "django.contrib.auth.context_processors.auth",
    "django.core.context_processors.debug",
    "django.core.context_processors.i18n",
    "django.core.context_processors.media",
    "django.core.context_processors.static",
    "django.core.context_processors.tz",
    "django.contrib.messages.context_processors.messages",
    "apps.utils.context_processors.debug_mode",
    "apps.utils.context_processors.is_production",

```
"allauth.account.context_processors.account",
"allauth.socialaccount.context_processors.socialaccount",
```

)
# this for authentication wiht all auth

ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_SIGNUP_PASSWORD_VERIFICATION = False
SOCIALACCOUNT_QUERY_EMAIL = False
SOCIALACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = 'optional'
SOCIALACCOUNT_AUTO_SIGNUP = True
ACCOUNT_SESSION_REMEMBER =  True

well kindly guide me to solve this one

**Comment by ashmishra** [comment]
A great way to see the error is to override authentication_error.html:
http://stackoverflow.com/a/36728888/847165

**Comment by biwin** [comment]
at least auth errors `{{ auth_error }}` must be shown when in super debug mode, (localhost with debug ON)

**Comment by derek-adair** [comment]
Where does this occur? I'm having trouble adding support for various logins and i'm really lazy so... 

I'd be happy to submit a PR w/ this.

**Comment by yashgo0018** [comment]
callback url should be :-
 /accounts/facebook/login/callback/
instead of :-
 /accounts/facebook/login/callback

**Comment by Ravisiswaliya** [comment]
> callback url should be :-
> /accounts/facebook/login/callback/
> instead of :-
> /accounts/facebook/login/callback

Solved

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/769
