### ISSUE TITLE
Security flaw: Facebook access token sent in plain text over the net 

### ISSUE THREAD

**Issue by facugaich** [pennersr/django-allauth#77]
After an user logs in using the Facebook JS SDK, the resulting access token is sent to the server in plain text to complete login. See https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/providers/facebook/templates/facebook/fbconnect.html

This is a somewhat serious security flaw: access tokens can be used by themselves to retrieve the corresponding user info. That is, _no other credentials_ are needed, anyone can use them whether they are related to the app that requested it or not. Therefore, they should be kept secret.

The correct way to retrieve the access token is to use the encrypted cookie that is set up after the SDK log in. It is encrypted with the App secret and contains a code that can be exchanged for the access token. This method has one major drawback: A call to the FB servers is needed to exchange the code.

I have implemented this method in my [access-token branch](https://github.com/facugaich/django-allauth/tree/access-token) (see facugaich@c589ad849e94c392942d2415070518cf2fb4e7b0). It depends on facebook-sdk@56c78ee84020f1a30fee3c4120311c70c7eee001. Because of this and the drawback mentioned above, I think my version cannot be incorporated straight into the mainline, hence why I didn't make a pull request.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/77
