### ISSUE TITLE
Error when running tests with socialaccount\south_migrations\0001_initial.py

### ISSUE THREAD

**Issue by arctelix** [pennersr/django-allauth#770]
I am trying to run tests on my app and getting the flowing error on test database creation:

    django-allauth\allauth\socialaccount\south_migrations\0001_initial.py", line 25, in forwards
    ('last_login', self.gf('django.db.models.fields.DateTimeField')(default=datetime.datetime.now)),
    TypeError: 'ForeignKey' object is not callable

Any ideas?

**Comment by pennersr** [comment]
Doesn't ring a bell. Is this issue still valid?

**Comment by arctelix** [comment]
Yes it's stll valid.

**Comment by pennersr** [comment]
I think this should be fixed in e95d3a978b318f9c7f8c7552f0c3a4300d9e6f41 and/or  d3bba39591bf32877959829fdd62e74a0d6299fd. Could you try these?

**Comment by pennersr** [comment]
Assuming fixed...

**Comment by arctelix** [comment]
I will check on this soon and let  you know.

**Comment by arctelix** [comment]
Better late then never ;) Confirmed fixed in  e95d3a9..

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/770
