### ISSUE TITLE
Allow disconnected SocialAccounts

### ISSUE THREAD

**Issue by nailgun** [pennersr/django-allauth#773]
When user disconnects any social account from his account, SocialAccount object is being completely deleted from database.

Sometimes such behavior is unacceptable. You can have some models linked to SocialAccount via ForeignKey field. When SocialAccount is deleted, all these links are lost.

To overcome this issue, I propose to make SocialAccount.user foreign key nullable and instead of deleting SocialAccount objects, just reset user field to null. Such social account becomes "disconnected".

This behavior can be controlled by some setting, e.g. SOCIALACCOUNT_KEEP_DISCONNECTED=(True|False).

How do you like this design proposal? Maybe there is better alternative? For now I'm forcing such behavior in my app by monkeypatching allauth. But it's ugly and unmaintainable, I will better send a pull request here, if it's good for you.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/773
