### ISSUE TITLE
allauth ignores `error_messages` on fields

### ISSUE THREAD

**Issue by malthejorgensen** [pennersr/django-allauth#779]
If I want a custom error message when a duplicate is found on a field with `unique=True`, the standard way is to set `error_messages['unique']` on the field, to customize the error message.

For the `username` field on a model `User` I would do something like this:
```python
class User(AbstractBaseUser, PermissionsMixin):
    ...
    username = models.CharField(max_length=40, unique=True, error_messages={
        'unique': _('The username you have chosen is already taken - please, pick another one')
    })
    ...
```
(see [/django/db/model/base.py](https://github.com/django/django/blob/e7b9a58b081299b30f807d5c66f7a5d1940efe4c/django/db/models/base.py#L1012-L1016) line 1012-1016)

However in allauth the message is set by allauth itself:
[/allauth/account/adapter.py](https://github.com/pennersr/django-allauth/blob/71f74bf4d7cfe38d17a71825e3a410ecb3d3ec59/allauth/account/adapter.py#L224-L225) line 224-225

I think to keep consistent with "the django way", allauth should allow custom error message by the same mechanism.

_(Links reference the latest known commit as of 25th Nov 2014.)_

**Comment by pennersr** [comment]
Done (c05be3b)

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/779
