### ISSUE TITLE
google redirct uri mis match

### ISSUE THREAD

**Issue by alishahpakneeds** [pennersr/django-allauth#780]
Hi I am facing redirect_uri_mismatch in django all auth I have given this url in google console setting

The redirect URI in the request: http://localhost:8000/accounts/social/google/login/callback/ did not match a registered redirect URI.

I have this value in my database google setting 

 http://localhost:8000/accounts/social/google/login/callback/ 

but why this is error is comming 

Kindly help me

**Comment by acquayefrank** [comment]
Hi 
I'm facing a similar problem only in my case it's soundcloud.
My url is of the  form /accounts/<provider>/login/callback

**Comment by pennersr** [comment]
Should be: /accounts/google/login/callback/

**Comment by acquayefrank** [comment]
Yeah, so it's /accounts/soundcloud/login/callback/ but I keep getting Social Network Login Failure.
My tokens match and my callback url in soundcloud is correct.

**Comment by bkoatz** [comment]
yup I get this too

**Comment by bkoatz** [comment]
it started happenign after switching to SSL, but I added https to all my Site objects and my redirect uris

**Comment by Vishu9** [comment]
This worked for me :
                 1. Go to https://console.developers.google.com
                 2. Add without port http://127.0.0.1/accounts/google/login/callback/
                 3. Also Add http://localhost/accounts/google/login/callback/
                 4.  worked for me
![Google_API_All auth](https://user-images.githubusercontent.com/8943853/103145247-1a144a00-475d-11eb-91a5-5b94b8c8fc21.png)

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/780
