### ISSUE TITLE
New configuration setting ACCOUNT_SIGNUP_EMAIL_VERIFICATION

### ISSUE THREAD

**Issue by pbojinov** [pennersr/django-allauth#788]
Add a configuration settings `ACCOUNT_SIGNUP_EMAIL_VERIFICATION` so when users are signing up, it will let the user type in their email twice to avoid typos.

Similar to preexisting setting `ACCOUNT_SIGNUP_PASSWORD_VERIFICATION`  - When signing up, let the user type in their password twice to avoid typos.

**Use case**:
Users mistype their emails when signing up, sometimes as much as their password. Having them type in their email twice avoids adding bad emails to your system.

**Comment by mfa** [comment]
so the user copies the emailadress from field one to field two?

**Comment by pbojinov** [comment]
@mfa we started using this measure on our site client side and it has significantly decreased invalid emails (measured by decreases in bounces when sending welcome emails).

I agree with you that a lot of people will copy the email address from field one to field two but at least they are giving it a second look.

**Comment by pennersr** [comment]
This feature is common enough for it to be included out-of-the-box.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/788
