### ISSUE TITLE
using account html template generates dup

### ISSUE THREAD

**Issue by RafaelOrtiz** [pennersr/django-allauth#789]
Hi

I'm having an issue with allauth and django1.7. when using account/templates as html.
the mails sended have dups, ie. it sends a multipart email, one with the customized info in the html template and the other one with the default info saven in the .txt templates.

Is this expected or bug?

Thanks and cheers.

**Comment by pennersr** [comment]
Sending out both HTML and plain text mails is proper practice, so this is indeed intended. You will need to provide both HTML and plain text templates.
