### ISSUE TITLE
_base_signup_form_class causes issues with inheriting from different forms

### ISSUE THREAD

**Issue by wldcordeiro** [pennersr/django-allauth#792]
I'm trying to use Allauth with Django-Organizations. There's issues with the two though because of this
function. You describe the reasoning for this function existing as.
> Currently, we inherit from the custom form, if any. This is all
not very elegant, though it serves a purpose:
- There are two signup forms: one for local accounts, and one for
social accounts
- Both share a common base (BaseSignupForm)
- Given the above, how to put in a custom signup form? Which form
would your custom form derive from, the local or the social one?

I would argue that it's a needless function though.  Couldn't users inherit from both SignupForm and SocialSignupForm (I would rename that one to that) if they want both sets of behavior or selectively inherit if they're using only social or only local?

**Comment by wldcordeiro** [comment]
@pennersr could you weigh in? I'm curious why that implementation is necessary.

**Comment by pennersr** [comment]
I must admit, I have not found the time yet to have a thorough look at your pull request, though at first look, I am not really found of the approach where you have to inherit from two forms. Before diving into details, I would like to learn a bit more about the problem you are having with the existing approach. What is the issue when combined with django-organizations?

**Comment by pennersr** [comment]
Closing until the problem with the existing approach is clarified. Feel free to provide details & reopen.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/792
