### ISSUE TITLE
Create pre authenticated session for functional test

### ISSUE THREAD

**Issue by bodgerbarnett** [pennersr/django-allauth#798]
I am trying to create a functional test for my site which skips the user having to actually log in by creating a pre-authenticated session to trick the site into thinking that the test user is already logged in.

In order to do this, I create a dummy user in the db and a dummy EmailAddress too, then set up the session as follows:-

    session = SessionStore()
    session[SESSION_KEY] = user.pk
    session['user'] = user.pk
    session[BACKEND_SESSION_KEY] = settings.AUTHENTICATION_BACKENDS[0]
    session.save()

However, it doesn't quite work because the request contains an AnonymousUser so the site doesn't think the user is logged in.

Am I missing something from the session maybe?
Or is this just not possible for this kind of test?

**Comment by bodgerbarnett** [comment]
Interesting - so it looks like it might be something to do with my template maybe.

I've tried using that first chunk of login code and I test, just after it's run, for user.is_authenticated() and it's True.

But when I subsequently get the home page (which has a section wrapped in an if user.is_authenticated), it's still got the AnonymousUser so that test fails.

However, the logic in the template works fine if I run the server up and use that and log in that way.

So now I'm really confused.

**Comment by pennersr** [comment]
As @bsmartt13 mentions, this is not really an allauth issue. Closing ...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/798
