### ISSUE TITLE
Completely disable e-mail confirmation

### ISSUE THREAD

**Issue by rantecki** [pennersr/django-allauth#80]
Hi there,

Even though I have ACCOUNT_EMAIL_VERIFICATION = False, my site seems to still be trying to send email confirmations when a user logs in via a social account, which is then breaking because I don't have emailconfirmation_confirm_email defined in my urls.

In tracing this problem through the code, I may have come across a situation where send_email_confirmation() gets called twice - one with a check to see if EMAIL_VERIFICATION is enabled, and one without.  I might be missing something but this may possibly be a bug?

In _process_signup() in allauth/socialaccount/helpers.py:

```
    send_email_confirmation(u, request=request)
    ret = complete_social_signup(request, u, account)
```

Following complete_social_signup() ends up at perform_login() in allauth/account/utils.py, which contains:

```
if (app_settings.EMAIL_VERIFICATION
    and not EmailAddress.objects.filter(user=user,
                                        verified=True).exists()):
    send_email_confirmation(user, request=request)
```

Cheers,

Richard

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/80
