### ISSUE TITLE
Update installation doc

### ISSUE THREAD

**Issue by addremove** [pennersr/django-allauth#800]
Should this be changed in [installation docs](https://github.com/pennersr/django-allauth/blob/master/docs/installation.rst) from 

    ./manage.py syncdb

to 

    ./manage.py migrate

**Comment by RafaelOrtiz** [comment]
FWIW, allauth is full compatible with django 1.7

**Comment by addremove** [comment]
Why do I see this message when I perform a migration `Synchronize unmigrated apps: allauth`

**Comment by RafaelOrtiz** [comment]
Probably migrate is saying what it needs to do: 
Operations to perform:
  Synchronize unmigrated apps

after migrate it says what operations are fullfilled or not.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/800
