### ISSUE TITLE
HTML validation error

### ISSUE THREAD

**Issue by onetimeusername** [pennersr/django-allauth#803]
When using django-allauth I get this HTML validation error:

 & did not start a character reference. (& probably should have been escaped as &amp;.)
…%2Fwww.google.com%2Faccounts%2Fo8%2Fid&next=%2Ffragen%2F'>Login mit Facebook</…

What you see there is the result of:
 {% provider_login_url "facebook" openid="https://www.google.com/accounts/o8/id" next=url %}

That's not a huge thing, but fixing it should only be a matter of swapping strings.

Thanks for your work!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/803
