### ISSUE TITLE
Reset Password Ajax Endpoint is not working

### ISSUE THREAD

**Issue by levivm** [pennersr/django-allauth#805]
When you try to perform  a reset password via ajax, the response is always a normal http response, never is a json response, even when `PasswordResetView ` inherits    `AjaxCapableProcessFormViewMixin`  class

I found a workaround to this. I had to rewrite PasswordResetView post method
```
class ResetPassword(PasswordResetView):

    def post(self, request, *args, **kwargs):

        _super =  super(ResetPassword, self)

        form_class = _super.get_form_class()
        form = _super.get_form(form_class)
        if form.is_valid():
            response = _super.form_valid(form)
        else:
            response = _super.form_invalid(form)
        return _ajax_response(request, response, form=form)
```

But, it should works without rewriting PasswordResetView post method.

**Comment by pennersr** [comment]
Are you sure? I added a unit test for this, and it indicates a JSON response is returned. See 7b1006e4629c89f380a0399329eb0a275c3dc88f

**Comment by pennersr** [comment]
Assuming solved as demonstrated by the test case ...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/805
