### ISSUE TITLE
Catering for plus sign in username

### ISSUE THREAD

**Issue by petedrennan** [pennersr/django-allauth#809]
With my current setup, I get errors when trying to sign up with a plus sign in the username eg: "user+name"

How to I cater to this, or at least exclude the plus sign (and any others) from the username field?

For one, the profile url doesn't work:
    
    url(r'^u/(?P<username>[-\w]+)/$', 'single_user', name='single_user'),

Sign up works, but then I get:

Reverse for 'single_user' with arguments '(<SimpleLazyObject: <User: user+name>>,)' and keyword arguments '{}' not found. 1 pattern(s) tried: ['u/(?P<username>[-\\w]+)/$']

Not sure if this is an allauth specific issue or not - but I'd be keen to know if there is an allauth-side solution to excluding characters like + from signup.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/809
