### ISSUE TITLE
translations not recognized by makemessages

### ISSUE THREAD

**Issue by onurmatik** [pennersr/django-allauth#81]
Strings marked for translation in views and forms in allauth are not appear in the .po file after running manage.py makemessages. For example;

error = _("The username and/or password you specified are"
          " not correct.")

in account/forms.py does not appear in .po file.

Also I am using rosetta for translations but allauth does not appear in list of 3rd party apps, while others are there.

Am I missing something?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/81
