### ISSUE TITLE
Custom User Model --> Custom Signup Template... How to?

### ISSUE THREAD

**Issue by santocch** [pennersr/django-allauth#810]
Hello,
I'm using a custom forms.py for asking a new user at signup more info. I was able to have everything working using google as provider... but there are few things that I'm not able to solve. Here is the situation:

model.py:

    class UserProfile(models.Model):
        user = models.OneToOneField(User, related_name='profile')
        wsUser = models.CharField(max_length=40,)
        wsPwd = models.CharField(max_length=40,)

forms.py:

    class SignupForm(forms.ModelForm):
        wsUser = forms.CharField(max_length=40, label='WS Username')
        wsPwd  = forms.CharField(max_length=40, label='WS Password')
        def __init__(self, *args, **kwargs):
            super(SignupForm, self).__init__(*args, **kwargs)
        def signup(self, request, user):
            wsData = UserProfile()
            wsData.user = user
            wsData.wsUser = self.cleaned_data['wsUser']
            wsData.wsPwd = self.cleaned_data['wsPwd']
            wsData.save()
        class Meta:
            model = UserProfile
            fields = ('wsUser', 'wsPwd',)

settings.py:

    ACCOUNT_SIGNUP_FORM_CLASS = 'home.forms.SignupForm'
    SOCIALACCOUNT_AUTO_SIGNUP = False

Everything is ok but I have few problems:
  1. The rendered form (/accounts/social/signup/) include the 2 fields I defined in the UserProfile model (OK), the username field (empty... mandatory to be filled) and the email field (already filled with the google email)... I would like to have only the 2 fields from the UserProfile model , the username filled automatically with the email and a customized template...
  2. How can I use a custom template to render the /accounts/social/signup/ page? 
  3. Using the settings parameter ACCOUNT_USER_MODEL_USERNAME_FIELD = 'email' I was expecting that the email would be copied to the username field of the user model... but the field remain empty... how can I copy the email to the username field?
  4. I also tried to set ACCOUNT_USER_MODEL_USERNAME_FIELD = None but I got an error when I try to restart gunicorn... is this normal?

Thanks for giving some hint especially on the custom template.

**Comment by pythdasch** [comment]
I will answer to some of your issue : 
2. Just copy the templates in the django allauth application to your templates with the same structure : 
The template socialaccount signup is in socialaccount/signup.html
so copy this template and put it in your template app folder socialaccount/signup.html and customize it

3. Don't know what you want to do but it seems a little bit tricky : If you want to login with the email, just add the settings ACCOUNT_AUTHENTICATION_METHOD to "email".

**Comment by myeureka** [comment]
i wanted to check if user exists on Facebook and send him back json web token, my issue is already resolved, thanks for answer but i did somewhat you answered.

**Comment by pythdasch** [comment]
Ok so if the issue is resolved, close it :)

**Comment by santocch** [comment]
OK. Thanks... actually i followed your suggestions copying the templates

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/810
