### ISSUE TITLE
Soundcloud connect

### ISSUE THREAD

**Issue by pythdasch** [pennersr/django-allauth#812]
Hi,

I'm facing a mismatch url when I'm trying to connect to soundcloud.
In my soundcloud app I putted redirect_url to localhost:8000/members/dashboard/
Because my soundcloud login is on this page.

But when I log in there is a mismatch url problem.

I tried this redirect_url : http://localhost:8000/account/soundcloud/login/callback/
but still the same problem.
What could it be ?

**Comment by pythdasch** [comment]
Ok the callback url is : http://localhost:8000/accounts/soundcloud/login/callback/

Would be very awesome if the doc is more understandable for everyone. If you want I can add some explanation about some tips if you don't have time. Thanks for the project by the way

**Comment by mpetyx** [comment]
Hello,
I have a similar error, and I have no clue on why..
I have set up my app to redirect on 
``` https://localhost:8000/accounts/soundcloud/login/callback/ ```, at the administration panel of soundcloud [https://soundcloud.com/you/apps/myexampleapp/edit]
but when i try to login i get the following
```https://localhost:8000/accounts/soundcloud/login/callback/?error=redirect_uri_mismatch&error_description=The+redirection+URI+provided+does+not+match+a+pre-registered+value.&state=BQ4lQBG4e58D# ```
Any ideas on what might the issue?

**Comment by bkoatz** [comment]
Bump. Still an issue

**Comment by pythdasch** [comment]
this is more a matter of soundcloud configuration. The error is obvious : the callback you entered in the configuration is not the same as the real callback. Check your config

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/812
