### ISSUE TITLE
How to unlink an account from a social auth provider?

### ISSUE THREAD

**Issue by jleclanche** [pennersr/django-allauth#814]
We're implementing a custom social auth backend and we need the ability for users to unlink themselves from linked accounts. What is the correct way to implement this? It seems like there should be some docs for it but I can't find any.

Is it just a matter of deleting the SocialAccount linked with the user and provider or is there more to it?

**Comment by bittner** [comment]
Looks like it's all about [removing the token from the model](https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/forms.py#L65).

See also:
* [template](https://github.com/pennersr/django-allauth/blob/master/allauth/templates/socialaccount/connections.html#L23)
* [urls](https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/urls.py#L10)

**Comment by pennersr** [comment]
End users can manage the social accounts used to login here: `/accounts/social/connections/`.
It also handles the logic of requiring the user to set a password in case it was a social-only account.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/814
