### ISSUE TITLE
Facebook provider use v1.x of the api

### ISSUE THREAD

**Issue by EliotBerriot** [pennersr/django-allauth#815]
We're trying to ingreate allauth in our project. We've followed the setup as described in the documentation, and users can register/login via Facebook.

However, they get the following message:

    You must upgrade this app to Graph API v2.x
    v1.0 will be deprecated on April 30, 2015

In our settings, we have:

    SOCIALACCOUNT_PROVIDERS = {
        'facebook':
            {
                'SCOPE': ['email', 'user_birthday' ],
                'METHOD': 'oauth2',
                'VERIFIED_EMAIL': True,
                'VERSION': 'v2.2',
            }
    }

But allauth keep using the old API. What are we doing wrong ?

**Comment by agriffis** [comment]
What version of allauth are you using?

**Comment by EliotBerriot** [comment]
We are using allauth 0.19.0 along with django 1.7.3 and Python 3.4.

**Comment by pennersr** [comment]
How do you conclude allauth is still using v1?

**Comment by EliotBerriot** [comment]
We were getting a warning on Facebook, saying that the v1 API is deprecated and will be shut down soone. However, I've tried just now and the warning is not here anymore. I don't understand why but I'll close the issue and reopen it later it the problem arise again. 

Thank you for your help !

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/815
