### ISSUE TITLE
Use RequestSite as fallback to Site object

### ISSUE THREAD

**Issue by k4ml** [pennersr/django-allauth#817]
Currently allauth 'force' everyone to use the Site framework where there are always case when people don't want to use it because they are just a single site. A quote from django docs:-

>Some django.contrib applications take advantage of the sites framework but are architected in a way that doesn’t require the sites framework to be installed in your database. (Some people don’t want to, or just aren’t able to install the extra database table that the sites framework requires.) For those cases, the framework provides a django.contrib.sites.requests.RequestSite class, which can be used as a fallback when the database-backed sites framework is not available.

https://docs.djangoproject.com/en/1.7/ref/contrib/sites/#requestsite-objects

**Comment by pennersr** [comment]
See #57.
