### ISSUE TITLE
Upgrade Dropbox provider to use OAuth2

### ISSUE THREAD

**Issue by gaqzi** [pennersr/django-allauth#821]
I'm currently working on updating the Dropbox provider to use OAuth2.

But I'm a bit curious whether I should update the current one or create a new one for OAuth2?

Since the API key would change for users I guess it could break things for other users of the Dropbox provider.

I will for now prepare for it to be a dropbox2 provider. :)

**Comment by pennersr** [comment]
We indeed need to support both protocols. Have a look at the LinkedIn provider -- it also offers both. So, if you could put your work in a `dropbox_oauth2` package that would be great..

**Comment by JshWright** [comment]
This can be closed now, right? (per PR #824)

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/821
