### ISSUE TITLE
Confirm email lands in SPAM (text update required)

### ISSUE THREAD

**Issue by bittner** [pennersr/django-allauth#822]
Emails originating from `django-allauth` to confirm an email address (as part of a social account) have a very high probability to land in the SPAM folder. I can confirm this for Gmail, which says that a high number of users have identified similar emails as SPAM or phishing.

The reason seems to be in the sparse wording obviously giving a non-trustworthy impression.
```
Subject: Confirm E-mail Address

User <username> at <name of site> has given this as an email address.

To confirm this is correct, go to http://<url of site>/confirm_email/<long token>
```
The content of the confirmation email ([email_confirmation_message.txt](https://github.com/pennersr/django-allauth/blob/master/allauth/templates/account/email/email_confirmation_message.txt)) needs to be revisited.

**Comment by SteveByerly** [comment]
The email templates are very generic, I would assume purposefully. They're really just to give you functionality out of the box. They provide a sense of what important information is necessary, illustrate how to use the included context variables, and provide a general idea of what the messaging should be.

If you are worried about email delivery, you should be overriding the email templates in the 'account/email' dir of your templates directory. Really, though, you should be doing this already to personalize your app's emails.

**Comment by bittner** [comment]
I've heard this before. Let's face it, a few if not most users will not change the template, and emails landing in SPAM will affect the credibility of `django-allauth` as a product.
I would say, either the text of the template must be changed or hints / very specific instructions need to be added to the documentation ("Must-Do's After Installing"). My personal preference is 1, providing a high-quality sample text in the template.

**Comment by SteveByerly** [comment]
I think it's a bit hyperbolic to say the email templates affect the credibility of a third-party app. If you have to be told to customize things for your own project, you're kind of doing it wrong. This project is a utility for users to solve a problem of authentication, not a drop-in production solution.

I'm not a core committer, so i'll leave further discussion to @pennersr but if you think it's a worthwhile change, why not make a PR with the changes as you see fit?

**Comment by pennersr** [comment]
The built-in templates only serve as a starting point, and are typically overriden with project specific versions. Therefore, templating issues like these are not listed on my high priority issues list. I am open to integrating a PR with improvements on this point, but in order to keep things manageable I prefer not to keep a ticket open. That does not mean that @bittner is wrong though ... feel free to file a PR.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/822
