### ISSUE TITLE
Fix for potential problem with AuthProcess.REDIRECT

### ISSUE THREAD

**Issue by arctelix** [pennersr/django-allauth#829]
I am using the AuthProcess.REDIRECT along with dynamic scope and params for incremental authorization and have come across a potential problem when a user has two separate site accounts connected to two separate provider accounts.  The problem arises in the following  scenario:
1. User logs in to site as provider p_userA.
2. Then User logs into provider as p_userB.
3. User attempts to add dynamic scope to their `SocialAccount`.
4. The `SocialAccount` for p_userB is returned by `sociallogin` rather then the request.user's   p_userA `SocialAccount`.

I am using the flowing solution which i think would be worthwhile to include in allauth's `complete_social_login` or `_social_login_redirect`.  If you agree, i wold be happy to prepare a pull request.  (`get_site_name` can be substituted for "our site" but, perhaps this could be useful in other templates)

Granted, this could be quite confusing to an end user. However, if the end user was savvy enough to have two provider accounts they can figure this out. 

DefaultSocialAccountAdapter.pre_social_login():

```
if process == AuthProcess.REDIRECT:
        account = sociallogin.account
        if not request.user == account.user:
            c_account = SocialAccount.objects.get(user=request.user, provider=account.provider)
            mismatch_p_account = account.get_provider_account()
            context = {'sitename': get_site_name(request),
                             'provider': account.provider,
                             'current_p_account': c_account.get_provider_account(),
                             'mismatch_p_account': mismatch_p_account,
                             'mismatch_account_url': mismatch_p_account.get_profile_url()}
            resp = render(request, 'socialconnector/account_mismatch.html', context)
            raise ImmediateHttpResponse(resp)
```

account_mismatch.html:

```
{% extends "account/base.html" %}
{% load url from future %}
{% load i18n %}

{% block head_title %}{% trans "Account Mismatch" %}{% endblock %}

{% block content %}
<h1>
    {% trans "Account Mismatch" %}
</h1>

<h2>
    {% blocktrans with provider=provider|capfirst %}
    It appears you are logged into {{ provider }} as a different user.
    {% endblocktrans %}
</h2>

<p>
    {% blocktrans with provider=provider|capfirst %}
    You are currently logged in to {{ sitename }} as "{{ current_p_account }}",
    but you are logged into {{ provider }} as "{{ mismatch_p_account }}".

    Please do one of the folowing to correct the problem:<br>
    1) If you would like to continue using your current {{ provider }} account:<br>
       Choose Logout below then log in as "{{ mismatch_p_account }}".<br>
    2) If you would like to continue using your current {{ sitename }} account:
       Choose {{ provider }} below, then logout and log back in as "{{ current_p_account }}".

    {% endblocktrans %}
</p>
<p>
    <a href="{% url 'account_logout' %} " target="_blank"><div class="btn btn-primary">{% trans "Logout " %}</div></a>
    <a href="{{ mismatch_account_url }}"><div class="btn btn-warning">{{ provider|capfirst }}</div></a>
</p>
{% endblock %}
```

helpers for sitename:

```
try:
    from django.contrib.sites.models import Site, get_current_site
except ImportError:
    get_current_site = False
    Site = False

def get_site(request=None):
    if get_current_site and request:
        site = get_current_site(request)
    elif Site:
        site = Site.objects.get_current()
    else:
        class site(object):
            domain = app_settings.SITE_DOMAIN
            name = app_settings.SITE_NAME
    return site

def get_site_name(request=None):
    site = get_site(request)
    return site.name

def get_base_url(request=None):
    site = get_site(request)
    return 'http://%s' % site.domain
```

**Comment by pennersr** [comment]
Currently, the AuthProcess.REDIRECT logic handling makes no assumptions whatsoever. It simply redirects after the social login. Basically, that means that allauth simply has no builtin support for a concept such as dynamic scopes. You can use this functionality to build dynamic scopes yourself.

Your proposed changes would add one step towards making allauth aware of aware of dynamic scopes. I am still pondering about that, because if this becomes an officially supported feature instead of something you can add yourself, it probably deserves an improved interface all together, possibly by providing a decent hook in the adapter.

Btw, your code does not handle the case where request.user.is_anonymous() which might be the case. What would be the appropriate behavior then?

**Comment by arctelix** [comment]
I stepped away from this project for a bit, but wanted to get back to your comment. I threw this out there originally to make a placeholder for what i thought could be useful authentication logic in the future. 

I disagree that this would make allauth aware of dynamic scopes and I'm not suggesting that allauth should in any way try to implement dynamic scopes for us.  I was thinking more along the lines of authentication and that it should be aware of the possibility that one user can have multiple accounts from the same provider.  

Although this would be triggered by a dynamic scope request, it think it is still technically an authentication issue and would lessen the burden of detecting these errors when implementing dynamic scopes.  Another use case: I think it is inevitable that allauth will eventually allow a user to connect multiple accounts from the same provider (I plan to develop this feature).  

I'd have to get back into the project to confirm, but i believe request.user.is_anonymous() was redirected to login higher up the logic chain.  Again this would probably be different for each use case.

**Comment by derek-adair** [comment]
This is really complicated for a corner case.  I'd vote to close on this bad boy.  "Granted, this could be quite confusing to an end user." is right.  As a terminally online user I can't even imagine why someone would want to do such a thing as this user described supporting.

**Comment by pennersr** [comment]
@derek-adair Agreed

**Comment by derek-adair** [comment]
![image](https://github.com/pennersr/django-allauth/assets/847236/fe9d63f7-9354-49ec-be5b-6065339826db)

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/829
