### ISSUE TITLE
allauth/account/forms.py rsplit and JoinInvitation error

### ISSUE THREAD

**Issue by gitdeepak** [pennersr/django-allauth#83]
rsplit below gives an error that rsplit is "undefinded variable in from import:rsplit" in eclipse: ? 
def _base_signup_form_class():
    if not app_settings.SIGNUP_FORM_CLASS:
        return _DummyCustomSignupForm
    try:
        fc_module, fc_classname = app_settings.SIGNUP_FORM_CLASS.rsplit('.', 1)
    except ValueError:
        raise exceptions.ImproperlyConfigured('%s does not point to a form'
                                              ' class' 

and : Joininvitation below errors "unresolved import" ? 
    def save(self, request=None):
        # don't assume a username is available. it is a common removal if
        # site developer wants to use e-mail authentication.
        email = self.cleaned_data["email"]

```
    if self.cleaned_data.get("confirmation_key"):
        from friends.models import JoinInvitation # @@@ temporary fix for issue 93
        try:
```

Appreciate the help.

Thanks
Deepak

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/83
