### ISSUE TITLE
Django 1.8a1 issue with TEMPLATE_CONTEXT_PROCESSORS

### ISSUE THREAD

**Issue by orokusaki** [pennersr/django-allauth#830]
I'm receiving django.core.exceptions.ImproperlyConfigured: socialaccount context processor not found in settings.TEMPLATE_CONTEXT_PROCESSORS.See settings.py instructions here: https://github.com/pennersr/django-allauth#installation despite having added all the necessary context processors to the new-style `TEMPLATES['options']['context_processors]`. It functions when adding the old-style setting `TEMPLATE_CONTEXT_PROCESSORS`, but I'm not planning to use that setting any longer.

**Comment by twcook** [comment]
Now that Django 1.8 has shipped is there any plan to fix this?

**Comment by pennersr** [comment]
This is fixed in b1bce450

**Comment by vaibhav-jain** [comment]
Even after `updating` I am getting this error. How to resolve this issue????

**Comment by pawciobiel** [comment]
will this help https://github.com/pennersr/django-allauth/pull/950

**Comment by vaibhav-jain** [comment]
Yeah.... It is fixed. Thanks

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/830
