### ISSUE TITLE
Twitter login error if app is in read and write mode

### ISSUE THREAD

**Issue by aiia** [pennersr/django-allauth#831]
Hi Raymond,
Thank you for your great app, saving me a lot of time.

Now I use allauth for FB and Twitter login. And it's OK. But..
When I change Twitter app permissions from "Read only" to "Read and Write" login fails telling of some technical problem: "Something is technically wrong"..

I've read that write permissions work with OAuth1 only, but I could not understand if allauth uses OAuth 1 or 2 for twitter.

Could you please help to solve the problem..

Thanks
Iho

**Comment by pennersr** [comment]
Twitter is OAuth1. For allauth, read only is sufficient as you typically won't be updated the user's profile picture or anything else ...

**Comment by aiia** [comment]
Hi, thank you for the answer.
Your strategy concerning AllAuth app looks wrong: yes, it suffice for simple Twitter registering, but if a project is aiming read-write communication with a user's twitter account, AllAuth limits that project artificially by not allowing user to register with it.
As result a project's user needs additional confirmation for Twitter communication through a 3rd app.. Looks absolutely wrong.
Or a project needs to find another registration solution instead of AllAuth :((

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/831
