### ISSUE TITLE
Signup form integrated in the Checkout process for ecommerce.

### ISSUE THREAD

**Issue by cyberjoac** [pennersr/django-allauth#835]
Hi,

I love your application and am using it for user management in my ecommerce platform.
I am trying to find a way to integrate the user registration form inside the checkout form, to improve the conversion rates (for now, I block people accessing the checkout page if they are not registered/logged in)

Do you think there is a way to integrate the login / signup forms inside the checkout page?

Thanks a lot!

**Comment by pennersr** [comment]
I am sorry, but I prefer not to keep tickets open on project specific integration issues. I would assume you could manage to squeeze the login view in there, but it really all depends on the details with respect to your checkout implementation ...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/835
