### ISSUE TITLE
Django 1.7 migrations are out of sync with models

### ISSUE THREAD

**Issue by jessamynsmith** [pennersr/django-allauth#836]
In a clean Django 1.7 project, if I add ```allauth.socialaccount``` to INSTALLED_APPS, I get an error on ```python manage.py migrate```:

    Your models have changes that are not yet reflected in a migration, and so won't be applied.
    Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.

If I run ```python manage.py makemigrations``` it generates a migration for socialaccount:

    Migrations for 'socialaccount':
        0002_auto_20150214_0523.py:
            - Alter field extra_data on socialaccount
            - Alter field provider on socialaccount
            - Alter field provider on socialapp

**Comment by pacebook** [comment]
When I get log like the error, I was removed `/migrations` folder in the app folder. try it.

**Comment by jelenak** [comment]
The same error.

**Comment by ben519** [comment]
Same

**Comment by cmdelatorre** [comment]
Same here. Besides, every time I execute 

`manage.py makemigrations && PYTHONPATH=~/dev/aimara/ ./manage.py migrate`

A new migration is created:

>  Migrations for 'socialaccount':
>    0009_auto_20150223_1658.py:
>      - Alter field provider on socialaccount
>      - Alter field provider on socialapp
>  Operations to perform:
>    Synchronize unmigrated apps: pipeline, allauth, github, google
>    Apply all migrations: socialaccount, sessions, account, sites, admin, contenttypes, auth...
>  Synchronizing apps without migrations:
>    Creating tables...
>    Installing custom SQL...
>    Installing indexes...
>  Running migrations:
>    Applying socialaccount.0009_auto_20150223_1658... OK

Examples of successive [generated migrations here](http://linkode.org/4KMd41wuwwjLqouKand4M1).

The change between migrations is just the order of the arguments given to `models.CharField(...)`, in `migrations.AlterField(... field=models.CharField(...))`

**Comment by jessamynsmith** [comment]
I looked into this a little more.
The change on extra data seems to be just the b'' vs '' on the default, from:
```
('extra_data', allauth.socialaccount.fields.JSONField(default=b'{}', verbose_name='extra data')),
```
to
```
('extra_data', allauth.socialaccount.fields.JSONField(default='{}', verbose_name='extra data')),
migrations.AlterField(
            model_name='socialaccount',
            name='extra_data',
            field=allauth.socialaccount.fields.JSONField(default='{}', verbose_name='extra data'),
            preserve_default=True,
        ),
```

For socialaccount and socialapp, it is a change in choices for ```provider```, presumably related to the dynamically generated choices. In models.py:
```
provider = models.CharField(verbose_name=_('provider'),
                                max_length=30,
                                choices=providers.registry.as_choices())
```

Because I only have facebook enabled, the generated migration has:
```
        migrations.AlterField(
            model_name='socialaccount',
            name='provider',
            field=models.CharField(verbose_name='provider', max_length=30, choices=[('facebook', 'Facebook')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='socialapp',
            name='provider',
            field=models.CharField(verbose_name='provider', max_length=30, choices=[('facebook', 'Facebook')]),
            preserve_default=True,
        ),
```

**Comment by xerosis** [comment]
Not sure if this is related but also 1.7:
IOError: [Errno 13] Permission denied: u'/usr/local/lib/python2.7/dist-packages/allauth/socialaccount/migrations/0003_auto_20150224_1724.py'
I have no idea why it's trying to pull migrations from /usr/local in

**Comment by briandant** [comment]
I opened a PR that fixes at least some of the migration issues.

https://github.com/pennersr/django-allauth/pull/863

**Comment by rudicba** [comment]
+1 Issue confirmed here.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/836
