### ISSUE TITLE
In perform_login(), do not blindly redirect to account_email_verification_sent

### ISSUE THREAD

**Issue by jleclanche** [pennersr/django-allauth#841]
We're implementing an xhr-based login and signup form in [Pootle](https://github.com/translate/pootle). This hasn't been too much of a problem until we hit [this redirect](https://github.com/pennersr/django-allauth/blob/0a9b326d629b922cec73c3c205467af42895d275/allauth/account/utils.py#L118-L119) in `perform_login()`.

It's not possible to override perform_login(), and this is a problem because we need to a response which will know about the xhr request in some form. Suggestions on how I can fix this?

**Comment by pennersr** [comment]
The regular LoginView is already "AJAX capable" -- see `allauth.account.views.AjaxCapableProcessFormViewMixin`, so the redirect should already be turned into json by `_ajax_response`.  Does that help?

**Comment by jleclanche** [comment]
@pennersr But it's not. The redirect is sent as a 403, then the user receives it, and the "new request" isn't seen as an xhr request.

**Comment by jleclanche** [comment]
@pennersr ping

**Comment by jleclanche** [comment]
@pennersr I'd really like to work on this, it's blocking us for a release in our app. But I need to know which way you want this fixed.

**Comment by pennersr** [comment]
I would first like to capture your scenario in a test case. How is your scenario different from this one?:

https://github.com/pennersr/django-allauth/blob/master/allauth/account/tests.py#L292

Could it be that the 403 is the result of CSRF middleware?

**Comment by jleclanche** [comment]
@pennersr That testcase does not involve the `EmailVerificationMethod.MANDATORY` code path. I'll write a test for it.

**Comment by jleclanche** [comment]
@pennersr But I don't actually know what is actually *expected* to happen if one logs in with an unconfirmed email through ajax. Because right now, they hit the 403 and get the full `reverse('account_email_verification_sent')` page *as html* (eg. the redirected request loses `X_REQUESTED_WITH`).

**Comment by julen** [comment]
Added a test for this scenario, which passes (Travis seems to be having a longish nap though). The error involves client-side code very likely.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/841
