### ISSUE TITLE
tests fail in the presence of a custom social account adapter

### ISSUE THREAD

**Issue by yosemitebandit** [pennersr/django-allauth#843]
this plugin has been really great and I've gotten the functionality I wanted, so thanks for that!  I'm just trying to understand how to get the tests to pass at this point.

I made a social account adapter that implements domain whitelisting for social logins with google.  When I have this adapter turned on by setting `SOCIALACCOUNT_ADAPTER`, the `allauth.socialaccount.providers.google` tests fail when I run `python manage.py test google`.  

I'm happy to attach the specific failures if that's helpful..  But the larger question is how do I properly test allauth intenral apps in the presence of custom project settings?

**Comment by pennersr** [comment]
Could you check if the error disappears when you add `@override_settings(SOCIALACCOUNT_ADAPTER='allauth.socialaccount.adapter.DefaultSocialAccountAdapter')` to `allauth.socialaccount.providers.google.tests.GoogleTests` ? We probably need to force the default adapter in `allauth.socialaccount.tests` itself.

**Comment by pennersr** [comment]
Closing until things become more concrete ...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/843
