### ISSUE TITLE
how can i change order in signup form

### ISSUE THREAD

**Issue by kartikdanidhariya** [pennersr/django-allauth#844]
hi,
i use django_allauth 
i added two field in form "acc_type" and "accept"
in this link https://github.com/pennersr/django-allauth/issues/826
i added successfully but now order of form in 
'acc_type', 'accept', 'username', 'email', 'password1', 'password2', 
in this way 
but i want to in this way
'username', 'email', 'password1', 'password2', 'acc_type', 'accept'

i try to specify field_order = ['username', 'email', 'password1', 'password2', 'acc_type', 'accept'] in my form.py but not change the order
my form.py in like

```python
from django import forms
from .models import UserProfile


class SignupForm(forms.Form):
    
    class Meta:
        model = UserProfile
        fields = ('acc_type','accept')
        field_order = ['username', 'email', 'password1', 'password2', 'acc_type', 'accept']
    
    #acc_type = forms.CharField(max_length=20, label='Account_Type')
    acc_type = forms.ChoiceField(widget = forms.Select(), 
                 choices = ([('Individual','Individual'), ('Business','Business'), ]), required = True,)
    accept = forms.BooleanField(initial=True,required=True, label="CONSENT OF 18 YEARS OLD, PRIVACY POLICY, TERMS AND CONDITION")

    
    def __init__(self, *args, **kwargs):
        super(SignupForm, self).__init__(*args, **kwargs)

        #current_order = self.fields.keyOrder
        self.fields.keyOrder = ['username', 'email', 'password1', 'password2', 'acc_type', 'accept'] 
    
    def signup(self, request, user):
            #UserProfile.acc_type = self.cleaned_data['acc_type']
            user_profile = UserProfile(acc_type=self.cleaned_data['acc_type'], user=user, accept= self.cleaned_data['accept'])
            user_profile.save()
            #user.acc_type = self.cleaned_data['acc_type']
            user.save()
```
pls help!!
Thanks in advance!!!

**Comment by gbozee** [comment]
The Signup Form is inheriting from forms.Form not forms.ModelForm. so the Meta Class is invalid.
Also the order shouldn't matter because in the template, you can place the login input after the password etc

**Comment by kartikdanidhariya** [comment]
Thanks !!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/844
