### ISSUE TITLE
Signal to hook to when existing socialaccount user reconnects

### ISSUE THREAD

**Issue by gbozee** [pennersr/django-allauth#845]
Digging through the source code I observed this line 

    if sociallogin.state.get('process') == 'connect':
        return _add_social_account(request, sociallogin)

and the code for `_add_social_account(request,sociallogin)`

code snippet from source `allauth\socialaccount\helpers.py`

    def _add_social_account(request, sociallogin):
        if sociallogin.is_existing:
            if sociallogin.account.user != request.user:
                # Social account of other user. For now, this scenario
                # is not supported. Issue is that one cannot simply
                # remove the social account from the other user, as
                # that may render the account unusable.
                level = messages.ERROR
               message = 'socialaccount/messages/account_connected_other.txt'
        else:
            # This account is already connected -- let's play along
            # and render the standard "account connected" message
            # without actually doing anything.
            pass
        else:
            # New account, let's connect
            sociallogin.connect(request, request.user)
            try:
                signals.social_account_added.send(sender=SocialLogin,
                                              request=request,
                                              sociallogin=sociallogin)
            except ImmediateHttpResponse as e:
               return e.response
        default_next = get_adapter() \
            .get_connect_redirect_url(request,
                                  sociallogin.account)
        next_url = sociallogin.get_redirect_url(request) or default_next
        get_account_adapter().add_message(request, level, message)
        return HttpResponseRedirect(next_url)

I intend to swap the access token recieved for a long term token but based on the above, the signal is only available when a new social account is added. I was wondering if there is any mechanism for carrying out custom action after a social account is <b>reconnected</b>.

**Comment by pennersr** [comment]
You can probably handle this in the `pre_social_login` signal / adapter method. Here, you can check the sociallogin process and handle accordingly. Does that help?

**Comment by gbozee** [comment]
yes the pre_social_login signal works for my scenario. Thanks

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/845
