### ISSUE TITLE
The view allauth.account.views.EmailView didn't return an HttpResponse object. It returned None instead.

### ISSUE THREAD

**Issue by MaxKoroteev** [pennersr/django-allauth#846]
Error occurs on submit email_list form (url name 'account_email') if no email selected (because no primary yet) to Make Primary / Re-send Verification / Remove
Need to raise validation error "Please specify email" or something

**Comment by pennersr** [comment]
Addressed in fc304c05c73c75f7679782772c719843efd69982

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/846
