### ISSUE TITLE
redirect_uri_mismatch for some users

### ISSUE THREAD

**Issue by sheeshmohsin** [pennersr/django-allauth#847]
Hey, I am using django allauth for login with google, It is working fine for some users, but some users are complaining that on login with google it throws 'redirect_url_mismatch' error. Can anyone suggest me what's wrong with that login with google?

**Comment by pennersr** [comment]
I am sorry, cannot help you here... I don't think this is an issue in allauth. Feel free to reopen if you have something concrete to go on.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/847
