### ISSUE TITLE
Spdy and Oauth2

### ISSUE THREAD

**Issue by mh00h** [pennersr/django-allauth#849]
I have a django app served with gunicorn behind nginx. If I enable the spdy protocol in nginx, attempting to log into my site via google sends a post request or a regular uname/pwd from the login page, but no response. On my android phone, Chrome says "This webpage is not available". In the details portion, I see:

The webpage at <b>https://mywebsite.com/accounts/google/login/?process=login</b> might be temporarily down or it may have been moved permanently to a new web address.
Error code: ERR_SPDY_PROTOCOL_ERROR

I can log in using the admin interface just fine, but not from allauth's login template. With spdy enabled, I can browse my site just fine after I have logged in. Ideas?

**Comment by pennersr** [comment]
Sorry, I cannot help you here. This is unlikely to be an issue in allauth -- closing.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/849
