### ISSUE TITLE
127.0.0.1:8007 instead of my sitename?

### ISSUE THREAD

**Issue by typeshige** [pennersr/django-allauth#85]
I've been trying to figure out where this is failing but when I sign in with say Twitter, it tries to do this:

http://127.0.0.1:8007/accounts/twitter/login/callback/?oauth_token=xxxxxxx&oauth_verifier=xxxxx

instead of my website:

https://xxxx.something/accounts/twitter/login/callback/?oauth_token=xxxxxxx&oauth_verifier=xxxxx

Can you tell me where I missed something?

Thanks,
Shige

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/85
