### ISSUE TITLE
how to migrate existing users from another authentication system

### ISSUE THREAD

**Issue by percy3d** [pennersr/django-allauth#851]
I change auth systems and when logging in worked fine, I was told a verification email was sent(it was indeed). How can I avoid making existing users have to verify their email again...

**Comment by pennersr** [comment]
If all email addresses are already verified, you could create a migration that creates an EmailAddress record for each user and set EmailAddress.verified to True.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/851
