### ISSUE TITLE
Support Django 1.8

### ISSUE THREAD

**Issue by RutledgePaulV** [pennersr/django-allauth#858]
As django 1.8 is already in beta and will be released in the next couple of months and users are already beginning to use it I think we should add support to django-allauth. Seem to be relatively few required changes and several deprecated references that should be fixed.

REQUIRED:
* request is now a field of context rather than a hash entry. 
  * `allauth/socialaccount/templatetags/socialaccount.py:20`
  * `allauth/socialaccount/templatetags/socialaccount.py:55`

* the preferred method for defining template context processors has changed as described in https://github.com/pennersr/django-allauth/issues/830. 
  * `allauth/app_settings.py:8`

* RemovedInDjango19Warning: Loading the `url` tag from the `future` library is deprecated and will be removed in Django 1.9. Use the default `url` tag instead.
  * This affects multiple templates, I didn't bother to list them.

That's everything I've come across so far (I actually just tried django-allauth for the first time, so I'm sure I've missed things). Should probably also update the test_settings.py and the example app to use the new context processor definitions and any other 'old' things. If I find time I may put together a PR for these changes after reviewing backwards compatibility requirements, etc.

**Comment by JshWright** [comment]
Are you running the latest code? At least one of those has been addressed since the last release.

I'm running it on Django 1.8 without much in the way of issues.

**Comment by RutledgePaulV** [comment]
You were right that several of the deprecations I had listed have since been fixed. I've updated the issue to reflect what remains.

**Comment by philippeluickx** [comment]
Having an issue with 1.8 that is not present with 1.7.7

  RelatedObjectDoesNotExist: SocialAccount has no user.

Using this with django_rest_auth

Not sure if related, but found http://stackoverflow.com/questions/29598772/internal-server-error-when-trying-to-log-in-with-facebook-to-django-server

**Comment by pennersr** [comment]
You are no longer allowed to assign to, or read from `.user` on a `SocialAccount` instance that is not saved.  It will result in the `DoesNotExist` error. This should have already been fixed in allauth, but it could be that rest_auth code is still doing this ...

**Comment by philippeluickx** [comment]
Not sure on how this plays out in the back, but where it was blocking in rest_auth is this piece of code:

'''python
        try:
            login = self.adapter.complete_login(request, app, token,
                                                response=access_token)
            token.account = login.account
            login.token = token
            complete_social_login(request, login)
        except HTTPError:
            raise serializers.ValidationError('Incorrect value')
'''

It throws it with the login.account. In allauth it was in https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/models.py

'''python

    def __str__(self):
        return force_text(self.user)
'''

**Comment by pennersr** [comment]
Indeed, `.user` is invoked (through `__str__`) at a time the account has no user yet. While the `__str__` could be changed to handle this situation more gracefully, I think it should not be invoked at all. Stopping the invocation from happening is something that needs to be changed in `rest_auth`, not in `allauth`.

**Comment by philippeluickx** [comment]
Good point, thanks for the support!

**Comment by awwester** [comment]
for anyone coming across this, it was fixed in django-rest-auth 0.4 in https://github.com/Tivix/django-rest-auth/commit/80a7988a9b5b54288e732f96a3eb8c4a2cb98cb8

**Comment by agriffis** [comment]
@pennersr Seems like this could be closed?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/858
