### ISSUE TITLE
Email Verification

### ISSUE THREAD

**Issue by typeshige** [pennersr/django-allauth#86]
Hi,

I'm still experimenting with this app.  The first time my site never got to the screen where it says it sent an email.  I tried again and got that screen, but I haven't received it yet.

How can I test or have it try to resend?

As far as I know, emails can be sent from my server and from within the Django shell.  

Thanks,
Shige

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/86
