### ISSUE TITLE
ImmediateHttpResponse not working with social account login

### ISSUE THREAD

**Issue by arescope** [pennersr/django-allauth#868]
Related to #741 , when overriding the method login in the Adapter and raising an ImmediateHttpResponse, it is not catch for social account login, so it just fails as an Exception

Cheers

**Comment by variable** [comment]
Any chance to release this soon?

**Comment by ihristovzariba** [comment]
When overriding pre_social_login, raising ImmediateHttpResponse doesn't stop the login flow.
Django==1.9.6, django-allauth==0.25.2

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/868
