### ISSUE TITLE
django 1.3 support lost?

### ISSUE THREAD

**Issue by eamonnfaherty** [pennersr/django-allauth#88]
Hey, firstly and properly: THANK YOU! This library is awesome and you are great for keeping it so well maintained!

I am using django 1.3.1 and it does not work.

Within allauth/account/models.py there is

``` python
from django.utils import timezone
```

Are you going to support 1.3.x still?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/88
