### ISSUE TITLE
username is None when saving new user and ACCOUNT_USERNAME_REQUIRED = False

### ISSUE THREAD

**Issue by peppobon** [pennersr/django-allauth#882]
When saving a new user, if ACCOUNT_USERNAME_REQUIRED = False,  user.username = '' and therefore django cannot save more than 1 user because user.username must be unique.

Add 
if username is None:
            user.username = email
in adapter.populate_username definition to resolve the issue.

**Comment by pennersr** [comment]
How do you reproduce this? For example, if I signup by providing an email `john@doe.com` the username is automatically populated with `john`.  Or perhaps you are referring to social providers that don't pass any of email/username?

**Comment by peppobon** [comment]
No, I am using plain vanilla registration. Here username is not populated at all. Where in your code the username gets populated from email?
 
When signing up using test2@test.com I get an integrity error at line 203 in allauth/account/adapter.py

Here are the localvars:

first_name	None
user_field	  <function user_field at 0x103720158>
self	<allauth.account.adapter.DefaultAccountAdapter object at 0x106e78b38>
user	<User: >
data	{'confirmation_key': '',
 'email': 'test@test2.com',
 'password1': '1234567',
 'password2': '1234567'}
commit	True
email	'test@test2.com'
user_email	<function user_email at 0x103720268>
username	None
user_username	<function user_username at 0x1037201e0>
form	<allauth.account.forms.SignupForm object at 0x106e6a1d0>
last_name	None
request	'<WSGIRequest\n'
'path:/accounts/signup/,\n'
'GET:<QueryDict: {}>,\n'
"POST:{'confirmation_key': '',\n"
" 'csrfmiddlewaretoken': 'LWG4tXL4RpXNqaYPE783B2GhHkwXcBOx',\n"
" 'email': 'test@test2.com',\n"
" 'password1': '1234567',\n"
" 'password2': '1234567'},\n"
...

**Comment by pennersr** [comment]
Here: https://github.com/pennersr/django-allauth/blob/master/allauth/account/adapter.py#L168

So, I assume you have ACCOUNT_USER_MODEL_USERNAME_FIELD set to blank, which is not valid in your case as you do seem to have usernames.

**Comment by peppobon** [comment]
OK, reading the docs I understood that I needed ACCOUNT_USER_MODEL_USERNAME_FIELD=None 
when not using usernames but only email for registrations.

Thanks

**Comment by pennersr** [comment]
Only set it to none if your model does not have a username field.

**Comment by peppobon** [comment]
Yes!
Thanks for the support
Cheers

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/882
