### ISSUE TITLE
Creating users with longer usernames

### ISSUE THREAD

**Issue by jonzlin95** [pennersr/django-allauth#883]
Hi, 

Just wondering if there's a way to use the default all-auth SignupView for creating users with usernames longer than 30 characters. I tried overwriting the `ACCOUNT_SIGNUP_FORM_CLASS` setting, but it doesn't help.

I've tracked the code problem down to 
`allauth/account/forms.py` (Lines ~200)

```python
class BaseSignupForm(_base_signup_form_class()):
    username = forms.CharField(label=_("Username"),
                               max_length=30,
                               min_length=app_settings.USERNAME_MIN_LENGTH,
                               widget=forms.TextInput(
                                   attrs={'placeholder':
                                          _('Username'),
                                          'autofocus': 'autofocus'}))
    email = forms.EmailField(widget=forms.TextInput(
        attrs={'type': 'email',
               'placeholder': _('E-mail address')}))
```

Specifically, it seems that the max_length is fixed since `ACCOUNT_SIGNUP_FORM_CLASS`'s username field will just be overwritten by the BaseSignupForm model's. 

Easiest fix seems to be that a `app_settings.USERNAME_MAX_LENGTH` field is added and set to a default of 30, so that this behavior is modifiable. This makes sense, since there's already a `USERNAME_MIN_LENGTH` setting.

For now, I've simply hacked my usernames to be under 30 characters.

Cheers,
Jonathan

**Comment by jonzlin95** [comment]
Hi Raymond,

Just want to say thank you for fixing this so quickly! Really appreciate it and love the work you've done with django-allauth!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/883
