### ISSUE TITLE
login issue

### ISSUE THREAD

**Issue by eamonnfaherty** [pennersr/django-allauth#89]
I am using all-auth 0.7.0 and not all of my users can log in.

Some users can login where as others do not.  It looks like the user object is not being put into the request object correctly.  

The same user can log in using the admin screens when I make them a staff member.

I have checked in the login form and the user object is being retrieved correctly when the credentials are correct.  I cannot see where the user is being set in the request.  

i have been stuck on this for a couple of days already :(

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/89
