### ISSUE TITLE
Reset password from key endpoint response when token fails. 

### ISSUE THREAD

**Issue by levivm** [pennersr/django-allauth#890]
When you call reset password endpoint using ajax, the normal flow works fine but if you send an used token, the response is a HTML template saying the token is invalid and its status is 200. 

Response should be json dict with an error and status 403 or 400.

**Comment by julen** [comment]
I can confirm this, I've hit it myself.

I understand returning a 400 response for non-XHR requests might be disruptive if sites don't implement/customize 400 error pages, so taking that into account I believe this would need to be special-cased for XHR requests, @pennersr?

**Comment by pennersr** [comment]
I haven't investigated this myself yet, but it looks as if the adapter method `ajax_response` is not reached in this scenario. Also see `_ajax_response` in `account.views`. Normally these methods already take care of the special casing, so what needs to be investigated is why this is not happening here ...

**Comment by julen** [comment]
@pennersr it doesn't reach `_ajax_response()` because the view overrides `dispatch()`, aborting early on with `_response_bad_token()`. At the same time, `AjaxCapableProcessFormViewMixin` only deals with `post()`.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/890
