### ISSUE TITLE
AddEmailForm only checks EmailAddress objects

### ISSUE THREAD

**Issue by davegaeddert** [pennersr/django-allauth#897]
Is it intentional that the `clean_email` of AddEmailForm only checks for exiting emails in EmailAddress objects, and not the email field on the user model (https://github.com/pennersr/django-allauth/blob/master/allauth/account/forms.py#L336)?

We recently ran into a situation where we were creating users manually (User.objects.create and not going through the sign up process), and as a result there was not a matching EmailAddress object. A different user could then use the AddEmailForm and essentially "claim" any email address of another user that didn't yet have the actual EmailAddress object.

There's mention of these scenarios here: https://github.com/pennersr/django-allauth/blob/master/allauth/account/utils.py#L316 but that sync only run if they visit the right View. I was just curious if in your opinion it should be our responsibility to create an EmailAddress when we create a user (which is what we're doing now), or if the AddEmailForm should check the user model too just to be safe (like you do elsewhere https://github.com/pennersr/django-allauth/blob/master/allauth/account/forms.py#L405).

**Comment by pennersr** [comment]
The `AddEmailForm` should check the user model as well, though it is good practice to create `EmailAddress` yourself as well.

**Comment by davegaeddert** [comment]
I also just found out that our solution wasn't actually working. I was `get_or_create`-ing the `EmailAddress` in the `post_save` signal of User, regardless of how the User was created, but then I would get a 500 error after completing the signup form because of this: https://github.com/pennersr/django-allauth/blob/master/allauth/account/utils.py#L235

**Comment by pennersr** [comment]
If you are creating users manually and bypasing allauth (not going through the signup process as you mentioned), then I would not have expected that the code containing that assert would be executed. Given that it does hit, it seems as if you are *not* bypassing allauth for your manually created users?

**Comment by davegaeddert** [comment]
Sorry I didn't explain that terribly well. I am creating users entirely *outside* of the allauth process (for a custom invitation flow). I'm doing it in several places though, so my hope was that I could put it in a signal like below and basically cover all cases where a User got created and ensure that the EmailAddress exists too. The problem with that though is that it also fires when you go through the allauth signup process, and the signal runs first, being the first one to create the EmailAddress and causing the aforementioned assert to fail when `setup_user_email` runs.
```python
@receiver(post_save, sender=User)
def created_user(sender, instance, created, raw, **kwargs):
    if created:
        email, email_created = EmailAddress.objects.get_or_create(user=instance, email=instance.email)
        if email_created:
            email.primary = True
            email.save()
```

Just thought I would mention it, not sure if there's anything that should be done differently on your end, probably my responsibility to handle this a little more carefully.

Thanks for the quick responses on this!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/897
