### ISSUE TITLE
urllib3 InsecurePlatformWarning when trying to login via Twitter

### ISSUE THREAD

**Issue by soukiassianb** [pennersr/django-allauth#898]
Loging via Facebook is working as a charm but when trying to login with twitter it returns the error:

*Social Network Login Failure
An error occurred while attempting to login via your social network account.*

and in terminal
```
[01/Apr/2015 19:20:00] "GET /accounts/login/?next=/ HTTP/1.1" 200 15160
/Users/soukiassianb/.virtualenvs/showmade_alpha/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
```
I tried to fix it by [downgrading](http://stackoverflow.com/questions/29134512/insecureplatformwarning-a-true-sslcontext-object-is-not-available-this-prevent)  `requests` but it doesn't work.

I have no idea if it is due to my own virtual environment or something else..

Any help appreciated :rocket:

**Comment by pennersr** [comment]
Have you tried this?: "If you encounter this warning, it is strongly recommended you upgrade to a newer Python version, or that you use pyOpenSSL as described in the OpenSSL / PyOpenSSL section."

In any case, this is not an issue in allauth...

**Comment by BlastPy** [comment]
How disable this pyopenssl

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/898
