### ISSUE TITLE
Left over legacy code to django-friends?

### ISSUE THREAD

**Issue by SmileyChris** [pennersr/django-allauth#9]
Just browsing code, I see a reference [here](https://github.com/pennersr/django-allauth/blob/master/allauth/account/forms.py#L190) to `from friends.models import JoinInvitation`.
That looks to be part of jtauber's django-friends which isn't a requirement of this project.

Is this just crufty legacy code? (it has been in there since your first commit)

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/9
