### ISSUE TITLE
account.emailaddress: Accessor for field 'user' clashes with related field 'User.emailaddress_set'

### ISSUE THREAD

**Issue by dbirulia** [pennersr/django-allauth#90]
After I downloaded new version 0.8.0, copied into my project, and trying to run:
sudo python manage.py syncdb

I get an error:
Error: One or more models did not validate:
account.emailaddress: Accessor for field 'user' clashes with related field 'User.emailaddress_set'. Add a related_name argument to the definition for 'user'.
emailconfirmation.emailaddress: Accessor for field 'user' clashes with related field 'User.emailaddress_set'. Add a related_name argument to the definition for 'user'.

In 0.7.0 I didn't have this issue.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/90
