### ISSUE TITLE
Silence RemovedInDjango19Warning

### ISSUE THREAD

**Issue by gabriel-amram** [pennersr/django-allauth#903]
A deprecation warning I came across after ugprading to Django 1.8 and the latest django-allauth:

* `allauth/socialaccount/providers/__init__.py:2: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils import importlib`

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/903
