### ISSUE TITLE
admin not available

### ISSUE THREAD

**Issue by BenNG** [pennersr/django-allauth#909]
Hello, 

I'm new in django, I tried to install your package but after doing
The installation phase (Django + Post-Installation)
I don't have any admin available as you said in the doc @ 
localhost:8000

Cheers

**Comment by BenNG** [comment]
Hello again ! 
I found what was missing

in urls.py was missing 
```
    url(r'^admin/', include(admin.site.urls)),
```
and a user to log in with 
```
python manage.py createsuperuser
```

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/909
