### ISSUE TITLE
Catching duplicate emails in signup process

### ISSUE THREAD

**Issue by puterleat** [pennersr/django-allauth#914]
I'd like to create a custom signup form which inherits from SignupForm or BaseSignupForm and overrides the raise_duplicate_email_error method, but this doesn't seem possible with the current design. Has this arisen before? Can you suggest a clean method of overriding this method without monkey patching like so:

    from allauth.account import forms as allauthforms

    # evil monkey patch coming up

    def my_raise_duplicate_email_error(self):
        raise Exception("doing my own thing for duplicate emails")

    allauthforms.SignupForm.raise_duplicate_email_error = my_raise_duplicate_email_error

This works, but seems like a bad idea.

**Comment by pennersr** [comment]
Methods like `raise_duplicate_email_error` are internal and not the way to go. If you want to do special things concerning email address validation, override `clean_email` in the adapter.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/914
