### ISSUE TITLE
Getting Facebook acces_token

### ISSUE THREAD

**Issue by stefanilie** [pennersr/django-allauth#919]
Hi, I am using django-allauth to login to Facebook. It works just fine, but i don't know how to get the SocialAccessToken. Also, after I first login, it crashes with this error: http://s14.postimg.org/rratn4tb5/Screenshot_from_2015_04_17_13_10_52.png
Now I know what is selected is the callback containing the acces_token. What I do not know is HOW I can get the acces_token.
TL;DR:
1. How can I get a access_token from a callback or from the db?
2. How can i get rid of this error: http://s14.postimg.org/rratn4tb5/Screenshot_from_2015_04_17_13_10_52.png that appears only after the first login. If I refresh it works just fine.

**Comment by pennersr** [comment]
Closing -- please don't file questions as issues. Have a look here: #122

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/919
