### ISSUE TITLE
Requesting different scopes for different users

### ISSUE THREAD

**Issue by MaldorLevr** [pennersr/django-allauth#920]
Hi, I was wondering if it's possible to get different scopes for different users and if so how you would go about doing it

**Comment by pawciobiel** [comment]
@MaldorLevr Could you clarify and give example please?

**Comment by pennersr** [comment]
The `{% provider_login_url %}` takes an optional `scope` parameter. So, you should be able to present two different kind of login forms and per form use a different scope.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/920
