### ISSUE TITLE
KeyError in extract_uid() for Weibo provider

### ISSUE THREAD

**Issue by airoswell** [pennersr/django-allauth#921]
It seems that Weibo has changed its Auth api. Signing up using `Weibo` will raise `KeyError` due to the absence of key `"idstr"` in `data` in `WeiboProvider.extract_uid()`.

I wonder if there is a fix?

---
Somehow the error seems to goes away

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/921
