### ISSUE TITLE
line 96 of account/utils.py vs line 158 of account/utils.py (perform_login function)

### ISSUE THREAD

**Issue by gabn88** [pennersr/django-allauth#925]
def perform_login(request, user, email_verification,
                  redirect_url=None, signal_kwargs=None,
                  signup=False):

then in the complete_signup functon it is returned as:
      return perform_login(request, user,
                         email_verification=email_verification,
                         signup=True,
                         redirect_url=success_url,
                         signal_kwargs=signal_kwargs)

The order is different and normal args instead of kwargs are used... not sure of this is working correctly

**Comment by fmalina** [comment]
Looks fine to me. Order of keyword arguments is not significant.

**Comment by gabn88** [comment]
You are correct. I was why something wasn't performing as I wanted, but it had nothing to do with this (of course). I was a little confused because I had been doing javascript whole day :palm_tree:

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/925
