### ISSUE TITLE
Django 1.8 Templates configuration

### ISSUE THREAD

**Issue by Koed00** [pennersr/django-allauth#926]
Django 1.8 introduced a new `TEMPLATES` settings:

```
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            'templates'
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                "django.template.context_processors.request",
                "allauth.account.context_processors.account",
                "allauth.socialaccount.context_processors.socialaccount",
                "django.template.context_processors.static",
                "django.contrib.auth.context_processors.auth",
            ],
        },
    },
```

This means that `TEMPLATE_DIR` , `TEMPLATE_CONTEXT_PROCESSORS` and `TEMPLATE_LOADERS` are being ignored when using the new configuration method.

Allauth will check if it's context processors are in `TEMPLATE_CONTEXT_PROCESSORS`, so it will either give a false positive or a false negative.

Also the Django Admin module now requires the  `django.contrib.auth.context_processors.auth` to be present in `context_processors`. I'm not sure if this affects the operation of the allauth account processors.

**Comment by Koed00** [comment]
Similar to #830

**Comment by luzfcb** [comment]
@Koed00 this issue was fixed on master.

@pennersr what is missing for a 0.20.0 release

**Comment by pennersr** [comment]
Done

**Comment by luzfcb** [comment]
@pennersr Thanks.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/926
