### ISSUE TITLE
No Facebook Login at accounts/signup or accounts/login

### ISSUE THREAD

**Issue by Hiieu** [pennersr/django-allauth#927]
I installed django allauth without any problem. I can see signup form at accounts/signup and I can sign up or sign in, but I cant register/login via Facebook, because I dont see any url.

I'm using django 1.7

**Comment by Hiieu** [comment]
Solved, the facebook login form is at accounts/facebook/login

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/927
