### ISSUE TITLE
user_signed_up signal missing request data

### ISSUE THREAD

**Issue by djangojack** [pennersr/django-allauth#929]
I use allauth to register new users. The registration is working fine, but I'm trying to hook into the request after the user signs up, but all the request data is gone.

in models.py:
```
from allauth.account.signals import user_signed_up
from django.dispatch import receiver
@receiver(user_signed_up)
def user_signed_up_(request, user, **kwargs):
    print user
    print request.POST
```

terminal:
```
test@gmail.com
<QueryDict: {}>
```

**Comment by pennersr** [comment]
This can happen. For exampe, if auto signup is turned on, the signal may be invoked on a GET request (redirect from the oauth provider). If you want to hook into the POST parameters I would expect that you would need some kind of form validation as well. So, I would think that a custom signup form is the proper way forward...

**Comment by andreyshipilov** [comment]
This is still an issue to me. I have emails validated and still receive an empty reqiest.POST.

Is there any solution to that?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/929
