### ISSUE TITLE
SortedDict is deprecated and will be removed in Django 1.9

### ISSUE THREAD

**Issue by mainderay** [pennersr/django-allauth#931]
Just happened to notice this message in the Django dev server:

> .../lib/python3.4/site-packages/allauth/account/utils.py:176: RemovedInDjango19Warning: SortedDict is deprecated and will be removed in Django 1.9.

This was alluded to in #356 back in September 2013. It sounds imminent at this point?

**Comment by jannon** [comment]
Yeah, I'm already getting failing tests in another project that tests against django-allauth and the Django repo master HEAD because SortedDict is gone.

**Comment by yinzhuoqun** [comment]
see this url : https://code.djangoproject.com/wiki/SortedDict

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/931
