### ISSUE TITLE
send_confirmation requires request preventing bulk re-sending of verification emails

### ISSUE THREAD

**Issue by fmalina** [pennersr/django-allauth#933]
One has to fake a request and send bulk reminder using something like the following function (requires `settings.DOMAIN`). This can be also used as a workaround in custom model `create_user` or `create_superuser` methods, where request is not normally available:
```python
from django.test import RequestFactory
from allauth.account.models import EmailAddress
import settings

def send_confirm_primary(user, request=False):
    if not request:
        request = RequestFactory().get('/', SERVER_NAME=settings.DOMAIN)
    email, created = EmailAddress.objects.get_or_create(
                                 user=user, email=user.email, primary=True)
    email.send_confirmation(request)
```

**Comment by fmalina** [comment]
Fortunately one can fake a request and send bulk reminder using a function like this, this can be also used in custom model create_user or create_superuser methods:
```
from django.test import RequestFactory
from allauth.account.models import EmailAddress
import settings

def send_confirm(user, request=False):
    if not request:
        request = RequestFactory().get('/', SERVER_NAME=settings.DOMAIN)
    email, created = EmailAddress.objects.get_or_create(user=user, email=user.email, primary=True)
    email.send_confirmation(request)
```

**Comment by pawciobiel** [comment]
@fmalina  thanks for this snippet :+1:  

BTW: It would be good if we could change utils.cleanup_email_addresses, models.EmailAddress, models.EmailConfirmation or perhaps even adapter itself not to use request at all.

**Comment by pennersr** [comment]
Since 5a8137c, the `send_confirmation` method no longer requires a `request`. It still takes one (but defaults to `None` and is not required by allauth). I don't want to remove `request` completely as allauth is being used in all sorts of ways, and for some type of projects where everything is done within the request context having access to the request can be useful.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/933
