### ISSUE TITLE
Facebook provider valid email security hole supposedly fixed

### ISSUE THREAD

**Issue by yarbelk** [pennersr/django-allauth#934]
http://stackoverflow.com/questions/14280535/is-it-possible-to-check-if-an-email-is-confirmed-on-facebook

https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/providers/facebook/provider.py#L159

says that we cant trust it.  I cannot find the report that an unverified email isn't displayed (link on SO post), however tests with the graph api explore with a test user says that an unverified user willnot show an email.

**Comment by pennersr** [comment]
As long as FB does not officially document that email addresses are verified, I prefer not to assume that by default. You can already use the `VERIFIED_EMAIL` setting for the FB provider to opt in to assuming addresses are verified.

The documentation should be extended to include the above links and explain that it is likely okay to enable `VERIFIED_EMAIL`.

**Comment by yarbelk** [comment]
Totally agree.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/934
