### ISSUE TITLE
How to change ValidationError message?

### ISSUE THREAD

**Issue by mingissb** [pennersr/django-allauth#938]
Hi Sir,
How do I change the showing error message, such as:
"The username and/or password you specified are not correct."
To
“Please input correct name and password or ask deskhelper" (acctully, I need translation into Chinese)
I have not found the solution.
Please help.
Thanks in advance.

**Comment by pennersr** [comment]
Override the LoginForm (see ACCOUNT_FORMS). Then override the error_messages property of the form.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/938
