### ISSUE TITLE
documentation tweak

### ISSUE THREAD

**Issue by senex** [pennersr/django-allauth#94]
It might be nice if you added a trailing comma to

INSTALLED_APPS = (
    ...
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.github',
    'allauth.socialaccount.providers.linkedin',
    'allauth.socialaccount.providers.openid',
    'allauth.socialaccount.providers.soundcloud',
    'allauth.socialaccount.providers.twitter'

in your docs.  While what you have is absolutely correct, I was confused when I did a copy paste and the twitter name got joined with something else I had.  Python was not happy :)

This is less than a minor issue

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/94
