### ISSUE TITLE
templates not adequately namespaced

### ISSUE THREAD

**Issue by catskul** [pennersr/django-allauth#940]
base.html conflicts with other packages who similarly have not namespaced their templates.

This cause all kinds of hard to diagnose problems.

As recommended by the Django docs, templates should be pushed one level deeper below a parent directory named for the app parent.

**Comment by pennersr** [comment]
Dupe of #370

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/940
