### ISSUE TITLE
IntegrityError if using social signups without email in response

### ISSUE THREAD

**Issue by Tyrdall** [pennersr/django-allauth#941]
Hej guys,

I've seen this issue appeared several times, but none of the provided solutions worked for me, so I digged a little deeper. I'm using the following setup:

    ACCOUNT_AUTHENTICATION_METHOD = 'email'
    ACCOUNT_EMAIL_REQUIRED = True
    ACCOUNT_UNIQUE_EMAIL = True
    ACCOUNT_USERNAME_REQUIRED = False

The signup via email is working fine, also the signup via Facebook. But when it comes to Twitter sometimes the following issue appears:

     IntegrityError: duplicate key value violates unique constraint "auth_user_username_key"
    DETAIL:  Key (username)=(twitter_username) already exists.

Twitter does not provide an email, but it provides a username. The username is used right here: https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/adapter.py#L88
Since the username is set, there's no further check for already existing usernames in the ``populate_username`` function.

Now, if the username already exists (e.g. generated in an email signup), the error is raised.
For now I reset the username provided by social providers:

    class SocialAdapter(DefaultSocialAccountAdapter):
        def populate_user(self, *args, **kwargs):
            user = super(SocialAdapter, self).populate_user(*args, **kwargs)
            user.username = ''
            return user

**Comment by pennersr** [comment]
I cannot confirm this...

In this scenario, you will be presented with the social signup form to fill in the email address. Given that `ACCOUNT_USERNAME_REQUIRED` is set to `False`, no input exists to enter a username. Therefore, we will be entering `save_user`, not `populate_username` over here:

https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/adapter.py#L57

This ripples down to:

https://github.com/pennersr/django-allauth/blob/master/allauth/account/adapter.py#L191

But, given that the form data does not contain a username, the username is set to `None` so that the  `populate_username` that follows can plug in a unique value.

**Comment by pennersr** [comment]
Do you have a reproducible scenario for this?

**Comment by Tyrdall** [comment]
@pennersr Phew, that was some time ago.

Maybe you can setup a scenario like that:

- Prepare a Twitter account
- Use the Twitter username to create a new user manually and make sure the username field is filled with the Twitter username
- Signup using that Twitter account and see what happens

**Comment by pennersr** [comment]
This is basically what is implemented by the test case I referenced: a user with username test is created, and then it tries to onboard a Twitter user with identical username. In that case, the flow as discussed in my comment https://github.com/pennersr/django-allauth/issues/941#issuecomment-125304189 is taken, and that seems to work just fine.

So I am closing this. If you bump into a scenario that is not handled properly, please let me know.

**Comment by Tyrdall** [comment]
As far as I can see you are using ``'other'`` AND ``'test'`` as usernames, so they won't clash.

other: https://github.com/pennersr/django-allauth/commit/3a70f68994bcf5e0da2bf8baaaf309529b5bf891#diff-e523623d3e2899a7582cfbe222c26964R273
test: https://github.com/pennersr/django-allauth/commit/3a70f68994bcf5e0da2bf8baaaf309529b5bf891#diff-e523623d3e2899a7582cfbe222c26964L270

**Comment by pennersr** [comment]
No, your scenario is the one called `test_email_address_clash_username_not_required`. Inside `_email_address_clash` you'll see that an existing user (test / test@test.com) is created, and a new user with identical details is being signed up. The data being posted is the form data the user has to enter in the social signup form to resolve the conflict. In your case, with username not required, that is only the email address.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/941
