### ISSUE TITLE
IndexError, list index out of range. Error causing by signals. 

### ISSUE THREAD

**Issue by Hiieu** [pennersr/django-allauth#943]
I'm using signals to update gender, when social user changed their gender on facebook.com.
Signals work fine. I can sign up and login and gender is updating for fb users. 

```Python
#app/models.py

@receiver(user_signed_up)
@receiver(user_logged_in)
def set_gender(sender, **kwargs):
    user = kwargs.pop('user')
    extra_data = user.socialaccount_set.filter(provider='facebook')[0].extra_data  
    gender = extra_data['gender']

    if gender == 'male':
        user.gender = u'M'
    elif gender == 'female':
        user.gender = u'F'
    user.save()
```

But I've noticed that for normal accounts when 
I try to sign up at */accounts/signup* or sign in at */accounts/login* I got this error:
```Python
Exception Type: IndexError
Exception Value: list index out of range
```

However normal users are succesfully saved to database, I only have this error after registration and login.

 I think this is the cause of the problem:

```Python
extra_data = user.socialaccount_set.filter(provider='facebook')[0].extra_data
```

**Comment by pennersr** [comment]
Normal users don't have a facebook account attached, so this `user.socialaccount_set.filter(provider='facebook')[0]` indeed throws an `IndexError`. This is expected behavior.

**Comment by Hiieu** [comment]
http://stackoverflow.com/questions/30084721/indexerror-list-index-out-of-range-django-allauth-signals

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/943
