### ISSUE TITLE
How to get resend email verification mail?

### ISSUE THREAD

**Issue by fellipeh** [pennersr/django-allauth#946]
Hello,

I want to show a link for my user, when they click on it, send again the email address verification mail.

I don't want to use ACCOUNT_EMAIL_VERIFICATION = 'mandatory'  because the user can login, but I need to verify the mail address.

Regards,

**Comment by jleclanche** [comment]
If the user logs in again, the email verification is re-sent.

**Comment by fellipeh** [comment]
Isn't work.. I  tried now, and now email was sent.. :(

T.·.F.·.A.·.     S+F
*Fellipe Henrique P. Soares*

e-mail: > echo "lkrrovknFmsgor4ius" | perl -pe \ 's/(.)/chr(ord($1)-2*3)/ge'
*Blog: http://fhbash.wordpress.com/ <http://fhbash.wordpress.com/>*
*GitHub: https://github.com/fellipeh <https://github.com/fellipeh>*
*Twitter: @fh_bash*

**Comment by pennersr** [comment]
Users can trigger this from the email management screen. If you need this functionality somewhere else, you would need to hookup your own views.

**Comment by franciscojavierarceo** [comment]
@pennersr where is the email management screen? I don't see it in the admin pages. Thanks!!

**Comment by izabelo** [comment]
/accounts/email/

**Comment by pythonwood** [comment]
restful ?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/946
