### ISSUE TITLE
LinkedIn oauth1 now broken due to API changes. 

### ISSUE THREAD

**Issue by samgclarke** [pennersr/django-allauth#947]
I'nm assuming this is becuase of the recent API changes made by LinkedIn. Any idea where the issue lies? I just see the Social Network Failure message, which isn't too helpful.

**Comment by pythdasch** [comment]
I've the same issue !!

**Comment by samgclarke** [comment]
I solved this issue for now, by editing my *settings.py*:

     SOCIALACCOUNT_PROVIDERS = {
         'linkedin': {
            'SCOPE': [
                'r_emailaddress',
                'r_basicprofile',
                # 'r_fullprofile',  # not available
                # 'r_network'     # not available
            ]
        
         # 'PROFILE_FIELDS': [] Commented out as this seems to break things...
        
    }
}

**Comment by pennersr** [comment]
`allauth` does not query the `r_fullprofile` or `r_network` (only `r_emailaddress`)

**Comment by samgclarke** [comment]
Yes, I found that as long as you don't include `r_fullprofile` or any of the other now closed API fields it works:

    SOCIALACCOUNT_PROVIDERS = {
        'linkedin': {
            'SCOPE': [
                'r_emailaddress',
                'r_basicprofile',
            ],
            'PROFILE_FIELDS': [
                'id',
                'location',
                'first-name',
                'last-name',
                'email-address',
                'picture-url',
                'summary',
            ]
        }
    }

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/947
