### ISSUE TITLE
Social account ctx processor cannot be removed

### ISSUE THREAD

**Issue by julen** [pennersr/django-allauth#949]
When `allauth.socialaccount` is in `INSTALLED_APPS`, Allauth is forcing everyone to add the `socialaccount` template context processor. While this is the desired behavior in the majority of the cases, when building pure client-side UIs this context processor can result irrelevant.

Would you be open to lower the severity of this check and make it a warning, or even allow to disable the check altogether via some flag?

**Comment by pennersr** [comment]
I don't like to turn this into a warning, as that would encourage you to run projects with warnings.  I would be more in favor of removing the context processors altogether. The one in `account` is empty anyway. The `socialaccount` one can be avoided by offering a `get_providers` template tag.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/949
