### ISSUE TITLE
It's far too difficult to get going as a first-time django-allauth user

### ISSUE THREAD

**Issue by terrycojones** [pennersr/django-allauth#95]
It's not clear from the docs how one should get going using django-allauth.  I'd like to help.

For example, is one supposed to `pip install django-allauth` or take the `allauth` directory from the repo and use that in one's own project apps dir?  I imagine the former.  But then, how do you customize the appearance of the accounts pages?  I happen to already have a `base.html` file in my templates, so URLs like `accounts/login` do not show anything at all from django-allauth.

How does one get the `example` to run?  It would be great if the example worked out of the box.

This could all be improved (like I said, I'm happy to help). But someone will have to tell me the answers to my questions so I can document them :-)

**Comment by andradei** [comment]
Thanks for the _link_

**Comment by dhruvkar** [comment]
Looks like its back up at: http://www.techstricks.com/django-allauth-tutorial-step-by-step/

**Comment by khushal12** [comment]
Hi pinners can you give complete custamization idea for the from signup form to processing of data via views and template

**Comment by ebarojas** [comment]
This one is a bit helpful as well:
http://www.sarahhagstrom.com/2013/09/the-missing-django-allauth-tutorial/

**Comment by ivdekov** [comment]
Hey,

When I try running the example project I get the following error
"ImportError: No module named reddit"
Does anyone know why this is happening?

**Comment by Yevs** [comment]
This one was very helpful for me https://www.webforefront.com/django/setupdjangousercreation.html

**Comment by nattyjojo** [comment]
I have a react front end and trying to implement allauth DRF is very frustrating, the  allauth documentation is not clear and i cant get it runing.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/95
