### ISSUE TITLE
Social account ctx processor ImproperlyConfigured

### ISSUE THREAD

**Issue by levivm** [pennersr/django-allauth#952]
I'm using django allauth master repo version, I  have in my settings.py 

```
TEMPLATE_CONTEXT_PROCESSORS =  DEFAULT_SETTINGS.TEMPLATE_CONTEXT_PROCESSORS + (
    "django.core.context_processors.request",
    "allauth.account.context_processors.account",
    "allauth.socialaccount.context_processors.socialaccount",
    
)
```
Then when I run migrate, I'm getting this error
```
"/home/fernando/.virtualenvs/trulii/src/django-allauth/allauth/app_settings.py", line 27, in check_context_processors
    raise ImproperlyConfigured(excmsg)
django.core.exceptions.ImproperlyConfigured: socialaccount context processor not found in settings.TEMPLATE_CONTEXT_PROCESSORS.See settings.py instructions here: https://github.com/pennersr/django-allauth#installation
```

**Comment by lsgunth** [comment]
I've also hit this issue. You need to upgrade you template settings for django 1.8 per these instructions:

https://docs.djangoproject.com/en/1.8/ref/templates/upgrading/#the-templates-settings

Though, Django AllAuth doesn't really handle this transition well due to b91315f51efa035ccfbc194d33e2eeac3d1dbc4f.

**Comment by pawciobiel** [comment]
@lsgunth I was hopping that thanks to my tiny fix allauth will handle it better than it was before. Do you have any suggestion how we could improve it?

**Comment by NativeDman** [comment]
I ran into this problem with Django 1.8, and #954 fixes this for me.

Can a point release be made for this fix?

**Comment by pennersr** [comment]
0.20.0 is out

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/952
