### ISSUE TITLE
New release any time soon?

### ISSUE THREAD

**Issue by jleclanche** [pennersr/django-allauth#956]
[Pootle](https://github.com/translate/pootle) is gearing up for a release soon and it depends on some fixes which landed fairly recently in git.

Is there a 0.20 release planned at some point soon?

**Comment by jleclanche** [comment]
Note that 0.19 is from January, and 0.19.1 is from February 5th. So this essentially means 6 months without a new release right now.

**Comment by pennersr** [comment]
I really do realize that a release is far overdue, but I have been (and still am) completely overloaded with other projects. I hope to get a relase out soon-ish, but am not making any promises.

**Comment by jleclanche** [comment]
@pennersr Understood. If you need help with it, we'll be glad to assist since it affects us quite directly.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/956
