### ISSUE TITLE
Not possible to remove ACCOUNT_EMAIL_SUBJECT_PREFIX

### ISSUE THREAD

**Issue by mcgeeco** [pennersr/django-allauth#957]
Hi, sorry if I'm missing something here. I don't want a subject prefix, but as far as I can tell there's no way of achieving that. Surely if someone put:
```python
ACCOUNT_EMAIL_SUBJECT_PREFIX = None 
```
in their settings, the behaviour should be not to use a prefix, no? 
Instead the adapter does:
```python
prefix = app_settings.EMAIL_SUBJECT_PREFIX
    if prefix is None:
        site = get_current_site()
        prefix = "[{name}] ".format(name=site.name)
```
I would have thought prefix = None should skip adding a prefix, but if you want to keep the current behaviour, should a new value be used to determine no prefix?
Happy to work on this if you like.

**Comment by pennersr** [comment]
Simply set it to ""

**Comment by mcgeeco** [comment]
Thought I'd tried that, but I must have mixed something up. Sorry, and thanks.

**Comment by fl4p** [comment]
Setting it to "" does not work anymore, this issues might be re-opened.

**Comment by taewookim** [comment]
i tried "" and none. Neither works

**Comment by pennersr** [comment]
If `None`, the prefix is not used:

![image](https://user-images.githubusercontent.com/201022/70847153-40708b80-1e61-11ea-84f3-f9dfb53d0306.png)

**Comment by jonderwaater** [comment]
I tried setting `ACCOUNT_EMAIL_SUBJECT_PREFIX` to `None` and `""`, I still get the site name as prefix. Hacking it directly works though..

**Comment by jasperoosthoek** [comment]
This still doesn't work for some reason: `None` and `""` will still trigger an email with the site name in the prefix. Is it possible that the `EMAIL_SUBJECT_PREFIX` gets parsed somewhere else and becomes `None`? Using `django-allauth` 0.44.0

**Comment by TheBoroer** [comment]
@jasperoosthoek 
I just spent a while hunting this problem down..... the docs say to set `ACCOUNT_EMAIL_SUBJECT_PREFIX` to an empty string.....but in the source code (and ironically in the screenshots above it references EMAIL_SUBJECT_PREFIX  (without the stating ACCOUNT_).....

**Comment by ddoyaguez** [comment]
Hi. I have been struggling with this issue too. The solution that worked for me with v 0.47.0 was adding in my settings.py
`ACCOUNT_EMAIL_SUBJECT_PREFIX = ""`
Keep in mind that if you were reading the sent test emails with Gmail, when you change the setting from `EMAIL_SUBJECT_PREFIX` (that doesn't work) to `ACCOUNT_EMAIL_SUBJECT_PREFIX` (which does work as stated in docs) and perform the test, Gmail will show it in the same mail thread, so it will trick you to think that it does not work, but if you check the email data the subject prefix is removed indeed.

**Comment by jasperoosthoek** [comment]
Thank you for the fix! I'm sure to test with my next project.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/957
