### ISSUE TITLE
Signup instead save in local_settings

### ISSUE THREAD

**Issue by aktywnitu** [pennersr/django-allauth#958]
EXAMPLE  local_settings
 A string pointing to a custom form class (e.g. 'myapp.forms.SignupForm')
 that is used during signup to ask the user for additional input
 (e.g. newsletter signup, birth date). This class should implement a
 'save' method, accepting the newly signed up user as its only parameter.
 ACCOUNT_SIGNUP_FORM_CLASS = None

OFFICIAL DOCUMENTATION:
ACCOUNT_SIGNUP_FORM_CLASS (=None)
    A string pointing to a custom form class (e.g. ‘myapp.forms.SignupForm’) that is used during signup to ask the user for additional input (e.g. newsletter signup, birth date). This class should implement a def signup(self, request, user) method, where user represents the newly signed up user.

**Comment by pennersr** [comment]
local_settings is out of sync, to be fixed.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/958
