### ISSUE TITLE
TOS confirmation before sign up

### ISSUE THREAD

**Issue by aktywnitu** [pennersr/django-allauth#959]
Hi!

I need add Terms of Service checkbox in sign up form - i wiil do it with ACCOUNT_SIGNUP_FORM_CLASS setting, but I don't have idea how to do it with social account login.
For example - after user authenticate via Facebook I need show to him page with TOS checkbox confirmation. After confirmation I can create user, or change custom policy_accepted field to True. But I prefer the fisr method - create user only after accepting TOS.

Please tell me how to do it in elegant way.

**Comment by aktywnitu** [comment]
OK

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/959
