### ISSUE TITLE
RemovedInDjango19Warning:

### ISSUE THREAD

**Issue by twcook** [pennersr/django-allauth#961]
I didn't see this one listed yet, apologies if it is a duplicate.

python3.4/site-packages/allauth/account/views.py:196: RemovedInDjango19Warning: `request.REQUEST` is deprecated, use `request.GET` or `request.POST` instead.
  redirect_field_value = self.request.REQUEST.get(redirect_field_name)

**Comment by pennersr** [comment]
This has been addressed in 0.20.0

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/961
