### ISSUE TITLE
Gitlab oauth support 

### ISSUE THREAD

**Issue by thenewguy** [pennersr/django-allauth#964]
It would be handy if gitlab oauth was supported on custom domains

See http://doc.gitlab.com/ce/integration/oauth_provider.html

**Comment by pennersr** [comment]
Indeed. Feel free to reopen or submit a pull request once you have got something working...

**Comment by takotuesday** [comment]
Any possible update to this? If one was to add gitlab as a provider, what would the necessary steps be?

**Comment by takotuesday** [comment]
This is something that certainly interests me as well!

**Comment by destroyerofbuilds** [comment]
@pennersr could this issue please be reopened. As noted herereadthedocs.org#1441 there is need for this functionality.

**Comment by takotuesday** [comment]
It looks like [gitlab](https://github.com/gitlabhq/gitlabhq/blob/master/doc/api/oauth2.md) and [github's](https://developer.github.com/v3/oauth/#web-application-flow) web application flow is pretty similar, so a lot of the github provider could potentially be re-usable.

**Comment by takotuesday** [comment]
@pennersr it seems to me that a hurdle in adding gitlab is it is designed to be used in for in house hosting and under a custom domain, unlike github who has a fixed domain. There are a couple ways to work around this:

* set the domain in the database
* set the domain in the settings file

Which would you reccomend? Is there an approach that I am missing?

**Comment by pennersr** [comment]
There is currently no proper place for this to be stored in the database. A settings sounds more in line to what we have now:

`SOCIALACCOUNT_PROVIDERS = { 'gitlab': { 'DOMAIN': ... and so on }}`

**Comment by saily** [comment]
i've added this feature in: https://github.com/pennersr/django-allauth/pull/1231

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/964
