### ISSUE TITLE
Are there any qualms about including Reddit as an OAuth2 provider?

### ISSUE THREAD

**Issue by orokusaki** [pennersr/django-allauth#965]
Reddit is in the top 30 sites in the world, top 10 in the US, so I wondered why Reddit wasn't a provider herein when I viewed the docs.

If I was to write such a provider, could that be merged, or are there misgivings about adding Reddit?

Docs: https://github.com/reddit/reddit/wiki/OAuth2

**Comment by pennersr** [comment]
Ofcourse, I welcome any provider. Feel free to reopen or submit a pull request once you have got something working...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/965
