### ISSUE TITLE
How to know the current active language from email template ?

### ISSUE THREAD

**Issue by k4ml** [pennersr/django-allauth#966]
The `request` object doesn't get passed when calling `adapter.send_mail()`.

```python
get_adapter().send_mail(email_template,
                                self.email_address.email,
                                ctx)
```

So even though I use custom adapter and override the `send_mail()` method, I can't pass `LANGUAGE_CODE` to the context.

https://github.com/pennersr/django-allauth/blob/master/allauth/account/models.py#L136

I probably can get the current language by looking at the `activate_url` but that look hacky. Why not just pass the `request` object to `adapter.send_mail()` ?

**Comment by pawciobiel** [comment]
You can override `get_adapter().send_mail`, pull out the user/user's profile by it's email, get the correct language, activate it `translation.activate(language)`, pass it to template and send.

IMO passing request to send_mail doesn't make sense.

**Comment by k4ml** [comment]
That has 2 problems I think.

First it assume you have the language stored on user's profile. But what about sign up and sending comfirmation link, you don't have user yet.

Secondly, I think that's not how user expect the language to work. They might set prefered language as Japanese, but for some reason browsing the site English version and expecting the email to come in English. Here, the language can only be determined from the request, not user profile. 

I don't see why we can't put request object in the context.

**Comment by pawciobiel** [comment]
@k4ml, it looks like we create a user in SignupView SingUpForm save.
https://github.com/pennersr/django-allauth/blob/master/allauth/account/forms.py#L306
Perhaps it would make sense to override it and use language from request or allow user to choose one, and either store it or pass it in context if this is what you want.
Many parts of account app are coupled to views because of request and session and IMHO it's not ideal.

**Comment by k4ml** [comment]
Thanks @pawciobiel. That seem to work.

**Comment by pennersr** [comment]
It must be possible to invoke `send_mail` without passing a request, this in order to allow usage of that method from inside celery jobs etc.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/966
