### ISSUE TITLE
Error: pip install: no such file or directory [during the compiling of provider files]

### ISSUE THREAD

**Issue by Toruitas** [pennersr/django-allauth#968]
When installing django-allauth with pip on a win7 x64 and python 3.4.3 also x64, I get this error (from the pip log):

    byte-compiling C:\Users\Stuart\documents\github\python\practice\django1\taskbuster_project\tb_test\Lib\site-packages\allauth\socialaccount\providers\facebook\south_migrations\0002_auto__add_facebookaccesstoken__add_unique_facebookaccesstoken_app_acco.py to 0002_auto__add_facebookaccesstoken__add_unique_facebookaccesstoken_app_acco.cpython-34.pyc
    
    error: [Errno 2] No such file or directory: 'C:\\Users\\Stuart\\documents\\github\\python\\practice\\django1\\taskbuster_project\\tb_test\\Lib\\site-packages\\allauth\\socialaccount\\providers\\facebook\\south_migrations\\__pycache__\\0002_auto__add_facebookaccesstoken__add_unique_facebookaccesstoken_app_acco.cpython-34.pyc.56169120'

----
    Command "C:\Users\Stuart\documents\github\python\practice\django1\taskbuster_project\tb_test\Scripts\python.exe -c "import setuptools, tokenize;__file__='C:\\Users\\Stuart\\AppData\\Local\\Temp\\pip-build-2d2ya9l6\\django-allauth\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\Stuart\AppData\Local\Temp\pip-ztgym5qu-record\install-record.txt --single-version-externally-managed --compile --install-headers C:\Users\Stuart\documents\github\python\practice\django1\taskbuster_project\tb_test\include\site\python3.4" failed with error code 1 in C:\Users\Stuart\AppData\Local\Temp\pip-build-2d2ya9l6\django-allauth
    

I thought it may be a bad tarball, but of course after deleting the pip cache and redownloading the results are the same. 

site-packages\allauth\socialaccount\providers\facebook\south_migrations does contain a similarly named file 
0002_auto__add_facebookaccesstoken__add_unique_facebookaccesstoken_app_acco.py , 
but there's nothing compiled in the __pycache__ folder.

Any ideas why it is trying and failing to compile the .py into a .pyc?

**Comment by pennersr** [comment]
I really have no idea. Given that it is not clear to me that this is an issue in allauth itself, and given that fact that I am unable to test on Windows myself I am closing this. If you have something more concrete to go on, feel free to reopen.

**Comment by wasabigeek** [comment]
@Toruitas I had a similar issue while trying to upgrade from 0.18.0 to 0.22.0. What worked for me (not a great solution by any means) was to make a new virtualenv that installed allauth to 0.22.0 directly.

**Comment by jokang** [comment]
The file name is too long for Windows. Create a virtualenv in a folder with shorter path should work.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/968
