### ISSUE TITLE
Connecting social account while the user is *not* logged in

### ISSUE THREAD

**Issue by thedarklord1** [pennersr/django-allauth#972]
I have a user logged in, who has email verified also. The problem is, when I try to sign in a user using social app, (Facebook/Greymeter), it creates a new user, even if I have put in ACCOUNT_UNIQUE_EMAIL=True. Is there a support for linking in the users using social authentication? Am I missing something in the Docs? I have read it like a million times. Please help me.

**Comment by pennersr** [comment]
Currently, an email address received from FB is not assumed to be verified, as it is not documented to be so. Therefore, you cannot assume that, given a FB login with a given email address, that it is ok to login a local user with that same address. You can tweak this behavior by setting the provider specific setting `VERIFIED_EMAIL` in `SOCIALACCOUNT_PROVIDERS`.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/972
