### ISSUE TITLE
[Custom provider] How to bail out when token is not valid

### ISSUE THREAD

**Issue by owais** [pennersr/django-allauth#973]
I'm writing a custom oauth2 provider. Sometimes, the token returned by the user is not valid (or does not provide sufficient information). The `complete_login` method of the provider view fetches some extra user data but sometimes the API doesn't return proper data because of permissions issue. I tried raising an ImmediateHttpResponse exception here but it was not caught by allauth. 

What is the preferred way for a provider to test if the token returned is good or bad.

**Comment by pennersr** [comment]
You can raise a `PermissionDenied` or `OAuth2Error` -- these are caught and handled accordingly.

**Comment by owais** [comment]
Thanks

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/973
