### ISSUE TITLE
Active Directory ADFS 3.0 oAuth support

### ISSUE THREAD

**Issue by thenewguy** [pennersr/django-allauth#974]
I need to use internal SSO provided by ADFS.  Version 3.0 offers an oauth2 endpoint.

I am planning on putting this together soon.  I've figured out the auth flow and got it working with curl such that I've got a good enough idea to start implementing it.

Is ADFS support something that you would include with the standard providers?  If it is, I will need to put some thought into how to generalize the provider.  Although it may be simplest just to assume a particular claims response and document it as a requirement.

**Comment by thenewguy** [comment]
So I've got an initial provider together that lets me log into the adfs oauth server.

https://github.com/thenewguy/django-allauth/commit/ab9541f660d77f2839e9ad69be0673e0be75ffc1

It is just a minimal basic implementation at this point.  I would like to add optional (in an opt-out fashion) support for verifying the jwt returned from adfs.  What are your guidelines for introducing 3rd party dependencies (needed for the jwt cryptography)?

**Comment by thenewguy** [comment]
@pennersr Can you comment on your interest in shipping a backend for ADFS with allauth?  There doesn't seem to be support for ADFS from any open source django auth app so I thought this would be a nice addition to the package.

Do you have a recommendation for accommodating arbitrary fields in `extract_common_fields` and `extract_email_addresses`?  https://github.com/pennersr/django-allauth/compare/master...thenewguy:c98fd74fe56ce64ec04e206fc7bd2e3488d0704e?diff=unified&name=c98fd74fe56ce64ec04e206fc7bd2e3488d0704e#diff-c296efef21a19b0da264d7a2039074e0R24 Since the common fields returned by ADFS are site specific it would be best to allow the implementer to map additional fields and email addresses.  I was thinking of using a custom signal unless there is already a hook for this with allauth.

**Comment by thenewguy** [comment]
Well I went ahead and implemented the signals.  This allows one to disconnect the default parsing and connect a site specific implementation if necessary.  See https://github.com/pennersr/django-allauth/compare/master...thenewguy:4ad18357590f7e9cb8281fc66ac2722e91f7f3ef

**Comment by thenewguy** [comment]
Is there any interest to include this in allauth or do I need to release it as a 3rd party app?

**Comment by abarax** [comment]
This looks quite useful @thenewguy

**Comment by bennullgraham** [comment]
If you are disheartened OP, I also would find this useful.

**Comment by jobec** [comment]
+1
Same here

**Comment by jobec** [comment]
Mean while, I released a very first release of a separate Django backend for this:
https://pypi.python.org/pypi/django-auth-adfs3-oauth2
Feel free to test and contribute!

**Comment by thenewguy** [comment]
So I needed this again.  Planning to release it as a 3rd party package this time.

Integration is very small so it shouldn't be much of a maintenance burden.  Available from https://github.com/thenewguy/django-allauth-adfs for the moment.  Will eventually put it on pypi

**Comment by thenewguy** [comment]
@pennersr do you have any sort of submission process for related 3rd party apps to be listed as available somewhere in the package?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/974
