### ISSUE TITLE
How to add an admin's approval step in the email verification process?

### ISSUE THREAD

**Issue by san89kalp** [pennersr/django-allauth#975]
Right now, the verification email is sent right after user registers. There is no admin involved in it. However, I want to send email verification link only when admin approves the user's registration request. How can I achieve that?

**Comment by pawciobiel** [comment]
@san89kalp you could write an invitation app which would invite users before allauth authenticates them.
You may want to include some logic in your custom AccountAdapter.is_email_verified which checks if user has accepted invitation(?)

**Comment by pennersr** [comment]
The adapter now offers a `send_confirmation_mail` method, where you can decide not to send the mail at all and first inform your admin.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/975
