### ISSUE TITLE
plugable unique email logic

### ISSUE THREAD

**Issue by ashwoods** [pennersr/django-allauth#976]
At runtime django-allauth makes some assumptions that might not be correct. I.e. 
https://github.com/pennersr/django-allauth/blob/master/allauth/account/app_settings.py#L24
in our case, email doesn't have to be unique (multitenant setup).

**Comment by pennersr** [comment]
I don't like to turn that into a warning, as that would encourage you to go ahead and ignore warnings. 

Could you elaborate a bit on how things look on your end? I am assuming that you have a user model that has some kind of FK to the tenant it belongs to ... such that email addresses are unique within a tenant, right?

If so, then this assert is not the only problem you'll be running into, but also additional code like `allauth.utils.email_address_exists` would need to be addressed.

**Comment by ashwoods** [comment]
correct, for now. I was considering using Groups for my usecase but going the simple route for now. 

This is currently the only issue that I can't solve by subclassing or duplicating some small parts. I have got a prototype working with local accounts, still have to see if I bumb into any problems with the social part. 

I agree with you with the warnings parts, due to the fact that auth is a security package, maybe we should just check if any type of uniqueness is given, i.e. by checking if email is part of a unique_together too, or by allowing to set or override the uniqueness check explicitly.

**Comment by pennersr** [comment]
Basically, what you need is to be able to plug the email unique logic in allauth... labelling this as a feature request.

**Comment by pennersr** [comment]
Done -- see 020f554

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/976
