### ISSUE TITLE
Facebook registration auto signup not working

### ISSUE THREAD

**Issue by cyberjoac** [pennersr/django-allauth#977]
Hi,

After logging for the first time with Facebook login, I get taken to the form that requests both login and email address.

The whole point of the Facebook Login in the first place was to avoid a registration step.

Is there any way to automatically generate a custom username from the email address that got fetched from Facebook? 

Thanks a lot!

**Comment by pennersr** [comment]
Turn on auto signup and disable mandatory email verification (or, set VERIFIED_EMAIL to True for the FB provider).

**Comment by cyberjoac** [comment]
Issue is not with the email though but with the username.

My system is engineered so that I need the username.

I was wondering if there was a way to auto-generate a username from the
mail.

Thanks a lot for the swift answer !

**Comment by pennersr** [comment]
allauth does exactly that ...

**Comment by cyberjoac** [comment]
I'm really sorry, I did just that following your instructions, but I get sent automatically to the Signup form where I get asked for both Username and Email (email is indeed fetched from Facebook information, but username is not auto-generated).

Any clue what could I do to change this behavior?

Thanks a lot.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/977
