### ISSUE TITLE
Password forgotten flow: Change password does not change password

### ISSUE THREAD

**Issue by gabn88** [pennersr/django-allauth#983]
I got a question from my users: If they click "password forgotten" and enter their mailaddress, they do get an e-mail with a key. When the click it, they got to a screen to change their password. But if they then click "change password" they go back to the home page, no success message is displayed, and their password stays the same.

I have verified this at my development and production server and the issue stays the same. I'm using default templates, where in the password_reset_from_key.html it says:

    {% else %}
        {% if form %}
         <form method="POST" action=".">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" name="action" value="{% trans 'change password' %}"/>
            </form>
        {% else %}
            <p>{% trans 'Your password is now changed.' %}</p>
        {% endif %}
    {% endif %}

As you can see, the action = '.', which means the current url... is that how it should be?

How can I find out what goes wrong? I did quite some testing, which took a long time, but I cannot figure out where it goes wrong..

**Comment by pennersr** [comment]
This is probably solved by 41553417 and the `ACCOUNT_LOGOUT_ON_PASSWORD_CHANGE` setting that was introduced.

**Comment by gabn88** [comment]
Actually, I now set it to False, but the user is still redirected to the home page and the password is NOT changed.

I think I need to create my own change password view and let the form post towards that view, or not?

**Comment by gabn88** [comment]
Waa, the issue is found! :+1:  in the password_reset_from_key.html, there is an action="." ... this should be: action=""  of course!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/983
