### ISSUE TITLE
Login Facebook success but user not login on the website

### ISSUE THREAD

**Issue by wpvn-info** [pennersr/django-allauth#984]
I have integration django allauth on my site with facebook login.
When I click on facebook login button, an user account has been create and a token stored on database. But I not login on my site.

I use Django 1.8.2 and latest allauth.
I have check facebook login via javascript and I get status login.
I set facebook account to staff but it not work too.
I don't make any custom on User model.

I cannot find where is problem.
Can anyone please help me!

-----
If I login via admin
![image](https://cloud.githubusercontent.com/assets/10359131/8263603/8b6984b4-1706-11e5-965f-5761bc7f804c.png)

And if I login via Facebook
![image](https://cloud.githubusercontent.com/assets/10359131/8263611/adca3274-1706-11e5-9847-4cbd63a346c4.png)

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/984
