### ISSUE TITLE
Auth provider backend failure not handled well

### ISSUE THREAD

**Issue by lukeburden** [pennersr/django-allauth#985]
Occasionally a backend auth provider fails. I see this with Google from time to time. It'd be great if allauth code could detect when this happens allowing for proper handling of the error condition. At the moment the error goes undetected and allauth tries to "extract_uid" from a result from the provider despite the error condition. The error first trips up allauth code here:

https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/providers/google/provider.py#L46

At this point in the code, the local "data" (the provider response) is:
```
{u'error':
    {u'code' : 500,
     u'errors': [
         {u'domain': 'u\'\\\'u"u\\\\\\\'global\\\\\\\'"\\\'\'',
          u'message': 'u\'\\\'u"u\\\\\\\'Backend Error\\\\\\\'"\\\'\'',
          u'reason': 'u\'\\\'u"u\\\\\\\'backendError\\\\\\\'"\\\'\''}
      ],
      u'message': u'Backend Error'}
}
```
I hit these once every couple of months on a live installation where Google (and other providers) authentication is working really nicely in general. Django 1.7, py2.7, allauth 0.18 (code same in head, though).

Thoughts? Would it make sense to identify the error cases in the provider specific layer and pass generic errors up-stack so we can at least say "Something with the backend broke, please try again.".

Thanks!

**Comment by lukeburden** [comment]
Follow-up to this: I've just exposed allauth functionality using django-rest-auth and django-rest-framework. An extremely useful combination to leverage allauth social auth functionality. However, it again brings the problem documented in this issue to the fore for me. I might expose an endpoint such as:

/v1/auth/google/

.. to which a user can post an access token and get a token back for use of the rest of the API. This request gets plumbed through to the same provider logic as the web use case, so hits the same issue if a user submits an expired or otherwise invalid token. This is a very likely reality with an API - more so than with web-auth. A key-error filtering up from allauth in this situation is not ideal. It would be good if at minimum the 401 from the provider is detected and an appropriate error is returned such that users of allauth can handle sensibly.

I'll be forking and handling this better locally for Google/Facebook for now, but it'd be great to get your input on how this should be handled in way that may nicely work for all providers. In terms of errors being passed up the chain as well as how this should impact the web-facing flow.

**Comment by lukeburden** [comment]
Apologies, I should have checked the latest version. This issue was resolved in https://github.com/pennersr/django-allauth/commit/8705514dc164577f801cdacb5c46623c8cb9909b. Closing this issue out.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/985
