### ISSUE TITLE
Possible SQL injection vulnerability

### ISSUE THREAD

**Issue by alesegdia** [pennersr/django-allauth#986]
We are working on a project using allauth, and the test team detected a possible SQL injection vulnerability coming from the signup, precisely from the `password1` field. It sounded quite weird to me, since I thought no raw SQL queries are done within allauth, so it can be a false positive.

**Comment by pennersr** [comment]
allauth is not doing any raw SQL (apart from some legacy migration command). If you have anything more concrete to go on, feel free to reopen.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/986
