### ISSUE TITLE
Any option to configure allauth to send email to ADMINs whenever there is new user signup

### ISSUE THREAD

**Issue by sp8899** [pennersr/django-allauth#987]
if there is no such option, can someone show a sample code how to do so.

Thanks.

**Comment by aellerton** [comment]
That's code you can write yourself. 

Write a function that receives a [signal](http://django-allauth.readthedocs.org/en/latest/signals.html) when the user signs up and then call the Django [mail_admins](https://docs.djangoproject.com/en/1.8/topics/email/#mail-admins) function.

**Comment by pennersr** [comment]
@aellerton is right...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/987
