### ISSUE TITLE
Method to handle security issues privately

### ISSUE THREAD

**Issue by sssbox** [pennersr/django-allauth#989]
I haven't found any vulnerabilities to report, however, since allauth is a pretty vital piece of any project that uses it, it seems like there should be a well documented place for people who think they've found a security issue to privately submit a report.

An example of something that shouldn't be publicly posted: https://github.com/pennersr/django-allauth/issues/986

Even though I saw that issue pretty soon after it was sent and was personally fairly certain is was a false positive even before you responded, if it had been a real vulnerability I would prefer to not first publicly hear about it before a fix was available.

If you think this is a good idea, I'd be willing to lead the charge to set up a publicly write-only google group for this purpose and add relevant documentation pointing people to that email address.

**Comment by cro** [comment]
+1

Recommend also setting up a GPG key to sign/authenticate messages.

--cro

**Comment by bitcity** [comment]
+1

Or maybe something like Django does:
> Please report security issues only to security@djangoproject.com. This is a private list only open to long-time, highly trusted Django developers, and its archives are not public. For further details, please see our security policies.

**Comment by pennersr** [comment]
I've created a group: django-allauth-security@googlegroups.com

**Comment by bitcity** [comment]
Is there a link to subscribe to security specific announcements via this group ?

**Comment by pennersr** [comment]
This group is meant for reporting only. In case of a security issue a new release will be made, I do not plan on setting up a mailinglist especially for this.

**Comment by cro** [comment]
Raymond,

Sorry to be dense--you mean this address is for reporting potential issues
only?  Not for subscribing to security announcements?


--cro

**Comment by pennersr** [comment]
The reason for filing this ticket was that somebody filed a potential security issue publicly. The group addresses exactly this:

> If you think this is a good idea, I'd be willing to lead the charge to set up a publicly write-only google
> group for this purpose and add relevant documentation pointing people to that email address.

Subscribe to django-allauth-announce to get notified about security releases.

**Comment by pennersr** [comment]
Closing (122e538)

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/989
