### ISSUE TITLE
Connect two Social accounts and create only one username for both

### ISSUE THREAD

**Issue by DESHRAJ** [pennersr/django-allauth#991]
So the current usecase is :
First a user signs with an Email-Id: abcd@xyz.com through his google account. Then he is assigned username: abcd . After he logs out and then when he logs in through Dropbox with the same email id , then a new entry is created in social_accounts table with username: abcd2. Why so ? Is it possible to connect these two accounts ? 

(Note: The user has not yet registered through simple login method.)

**Comment by pennersr** [comment]
The user can connect the accounts via the social connections screen. You cannot automatically connect accounts unless you are absolutely sure that the email address returned by the social provider is 100% verified.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/991
