### ISSUE TITLE
What's the correct Redirect URI(s) for Instagram? 

### ISSUE THREAD

**Issue by qasimalbaqali** [pennersr/django-allauth#992]
I have used ```http://127.0.0.1:8000/accounts/instagram/login/callback/``` and I get the following error:
```json
{

    "code": 400,
    "error_type": "OAuthException",
    "error_message": "Redirect URI does not match registered redirect URI"

}
```

**Comment by pennersr** [comment]
Closing, this is a configuration issue (check if your redirect URI as configured in Instagram matches)

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/992
