### ISSUE TITLE
Allauth's provider app labels easily conflict with other Django apps

### ISSUE THREAD

**Issue by pjdelport** [pennersr/django-allauth#993]
Currently, Allauth's social account providers all have unqualified Django app labels that very easily conflict with other Django apps, making them difficult to use together.

As a motivating example, the `allauth.socialaccount.providers.facebook` provider ends up with the app label `facebook` by default, ~~the same as used by [facebook-sdk](https://pypi.python.org/pypi/facebook-sdk), which is pernicious if you want to use the latter on top of Allauth for Graph API access~~. This problem is not limited to Facebook, however: all of the current provider apps are named in a way that invites conflicts with other top-level Django apps related to the same social service.

Older Django versions don't offer an easy way to work around this problem, but Django 1.7's [app config](https://docs.djangoproject.com/en/1.7/ref/applications/) support allows the app label to be configured explicitly:

```python
class AllAuthFacebookConfig(AppConfig):

    name = 'allauth.socialaccount.providers.facebook'
    label = 'allauth_facebook'

    def ready(self):
        """
        Register this provider with allauth's registry.
        """
        # This import has the side effect of triggering the registration.
        import allauth.socialaccount.providers.facebook.provider
```

~~This lets Allauth and facebook-sdk coexist in the same Django instance.~~

(As a side note, doing the provider registration in `ready` can also replace the current hacky registration code in [`allauth/socialaccount/providers/__init__.py`](https://github.com/pennersr/django-allauth/blob/0.19.1/allauth/socialaccount/providers/__init__.py##L30-L38) and [`allauth/socialaccount/providers/facebook/provider.py`](https://github.com/pennersr/django-allauth/blob/0.19.1/allauth/socialaccount/providers/facebook/provider.py#L170).)

# Proposal

To solve this problem in general, I want to propose changing the default app labels for all providers to `allauth_<provider>` in a future release, using the following transition plan:

1. For each provider, add a `AllAuth<Provider>Config` with a qualified label like the above, along with documentation about how new installations can use it to avoid label conflicts.
2. For existing installations, add a backwards-compatibility ``AllAuth<Provider>UnqualifiedConfig` (or similar) for each provider that keeps the current app labels unchanged.
3. For a suitable transitional period (a major release or two?), make the `default_app_config` for each provider point to a version of the backwards-compatibility config that emits a deprecation warning with instructions for existing installations to update their INSTALLED_APPS to reference the unqualified config explicitly.
4. After the transitional period, switch `default_app_config` to the new, qualified configs.

## Django compatibility

The above requires Django 1.7, which conflicts with django-allauth's current support for 1.4. However, upstream support Django 1.4 support for is ending very soon (October 1, 2015, 3 months from now), which makes it reasonable for django-allauth to drop support for it then too, unless there's a call for django-allauth to continue supporting Django 1.4 beyond the upstream lifetime.

This gives two choices for implementing this proposal:

1. Wait until Django 1.4 support ends, then require Django 1.7 (the next supported release) and implement the above plan.
2. Keep Django 1.4 support, and implement the above plan guarded in `django.VERSION` checks, as appropriate.

**Comment by pennersr** [comment]
I am wondering, you mention:

"As a motivating example, the allauth.socialaccount.providers.facebook provider ends up with the app label facebook by default, the same as used by facebook-sdk"

However, the facebook-sdk is just a Python package, not a Django app. So there are no conflicts there. If you are having conflicts, you apparently have some other app on board that is using the `facebook` app name?

**Comment by pennersr** [comment]
Labelling as future, as this raises more complex questions, such as migrations, but also whether or not it is a good design decision for providers to correspond to Django apps at all.

**Comment by pjdelport** [comment]
@pennersr: Apologies, it appears I got my wires crossed somewhere regarding facebook-sdk!

The app label conflict arose in a project I was only sidelong involved in, and involved facebook-sdk among other apps. I don't recall the actual source of the conflict right now, but I must have conflated it with facebook-sdk somewhere along the line.

**Comment by pjdelport** [comment]
Also, I somehow missed the existing issue #393 before I filed this one.

**Comment by pennersr** [comment]
Closing due to #393

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/993
