### ISSUE TITLE
JSON serializer fails on some data types (sessions)

### ISSUE THREAD

**Issue by yarbelk** [pennersr/django-allauth#996]
https://github.com/pennersr/django-allauth/blob/master/allauth/utils.py#L173

As the comment says,  

```
    session are no longer pickled,
    but JSON encoded by default. 
```

Session serialization can be overridden by using the setting ```SESSIONS_SERIALIZER```.  This is really useful for those of us who have odd things in their models that need to be handled specially.

I have odd things in my user (UUID PK).  As it is implemented, it is very hard for me to override this.

when you compare this to the session serialization, there are differences - it does not use the `DjangoJSONEncoder`/`DjangoJSONDecoder` from  ```django.core.serializers.json```, they have a different interface. (```dumps(obj)``` and ```loads(obj)```).

In my case, I'm using a YAML serializer because it works better with arbitrary things.  This isn't probably correct in this case, but we should be ablse to swapp out the `DjangoJSONEncoder`, in the serialize_method

=== edit ===

Actually, it might make more sense to get `DjangoJSONEncoder` changed itself.  it would save me a huge amount of effort, circumventing it all over my project.

**Comment by yarbelk** [comment]
Same as #916

**Comment by pennersr** [comment]
#916 was fixed

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/996
